var pairs =
{
"selecting":{"current":1}
,"current":{"record":1,"record\u2019s":1}
,"record":{"browse":1,"time":1,"you\u2019re":1,"select":1,"current":1,"moving":1,"fill":1,"record":1,"use":1,"by":1,"highlighted":1,"form":1,"list":1,"table":1}
,"browse":{"mode":1}
,"mode":{"database":1}
,"database":{"active":1}
,"active":{"record":1}
,"time":{"each":1}
,"each":{"open":1}
,"open":{"window":1}
,"window":{"form":1}
,"form":{"view":1,"list":1}
,"view":{"record":1,"current":1,"margin":1,"select":1}
,"you\u2019re":{"displaying":1}
,"displaying":{"current":1}
,"select":{"record":1,"portal":1,"ecord":1}
,"moving":{"records":1}
,"records":{"list":1,"select":1,"changing":1}
,"list":{"view":1,"table":1}
,"fill":{"records":1}
,"use":{"controls":1}
,"controls":{"status":1}
,"status":{"toolbar":1}
,"toolbar":{"moving":1}
,"changing":{"current":1}
,"record\u2019s":{"appearance":1}
,"appearance":{"display":1}
,"display":{"state":1}
,"state":{"object":1}
,"object":{"current":1}
,"by":{"solid":1}
,"solid":{"vertical":1}
,"vertical":{"bar":1}
,"bar":{"left":1}
,"left":{"setting":1,"current":1}
,"setting":{"up":1}
,"up":{"form":1}
,"table":{"views":1,"view":1}
,"views":{"layout":1}
,"layout":{"table":1}
,"margin":{"left":1}
,"highlighted":{"select":1}
,"portal":{"row":1}
,"row":{"inside":1,"fields":1,"select":1}
,"inside":{"row":1}
,"fields":{"row":1}
,"ecord":{"portal":1}
}
;Search.control.loadWordPairs(pairs);
