var pairs =
{
"onlayoutexit":{"performs":1}
,"performs":{"script":1}
,"script":{"efore":1,"script":1,"step":1,"return":1,"proceeds":1,"canceled":1,"trigger":1,"runs":1}
,"efore":{"layout":1}
,"layout":{"exited":1}
,"exited":{"event":1}
,"event":{"processed":1,"triggered":1}
,"processed":{"browse":1}
,"browse":{"find":1}
,"find":{"preview":1}
,"preview":{"modes":1}
,"modes":{"use":1,"trigger":1}
,"use":{"exit":1}
,"exit":{"script":1}
,"step":{"triggered":1}
,"triggered":{"script":1}
,"return":{"true":1}
,"true":{"false":1,"event":1}
,"false":{"true":1,"event":1}
,"proceeds":{"false":1}
,"canceled":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"11.0":1}
,"11.0":{"script":1}
,"trigger":{"activated":1,"result":1}
,"activated":{"window":1}
,"window":{"closed":1}
,"closed":{"hen":1}
,"hen":{"script":1}
,"runs":{"modes":1}
}
;Search.control.loadWordPairs(pairs);
