var pairs =
{
"getsensor":{"returns":1,"sensorname":1,"stepcount":1}
,"returns":{"value":1,"data":1,"text":1,"accuracy":1,"empty":1}
,"value":{"sensor":1,"0.0":1,"accuracy":1,"timeout":1,"600":1,"forpastseconds":1}
,"sensor":{"ios":1,"option1":1,"option2":1,"parameters":1,"device":1}
,"ios":{"device":1}
,"device":{"getsensor":1,"running":1,"sensorname":1,"format":1,"radians":1,"meters":1,"degrees":1,"duration":1,"values":1}
,"sensorname":{"option1":1,"-the":1,"returns":1,"values":1}
,"option1":{"option2":1,"-optional":1}
,"option2":{"sensorname":1,"-optional":1,"battery":1}
,"-the":{"name":1}
,"name":{"supported":1}
,"supported":{"sensor":1}
,"-optional":{"parameter":1}
,"parameter":{"sensor":1}
,"parameters":{"braces":1}
,"braces":{"optional":1}
,"optional":{"text":1}
,"text":{"number":1,"accuracy":1,"rotationrate":1,"accelerationbyuser":1,"accelerationbygravity":1,"speed":1,"compassmagneticheadin":1,"data":1}
,"number":{"filemaker":1,"steps":1,"batterystatus":1,"representing":1,"location":1,"accuracy":1,"forpastseconds":1,"floors":1,"list":1,"represents":1,"seconds":1}
,"filemaker":{"pro":1,"go":1}
,"pro":{"7.0":1}
,"7.0":{"advanced":1}
,"advanced":{"use":1}
,"use":{"function":1}
,"function":{"capture":1,"values":1,"getsensor":1}
,"capture":{"by":1}
,"by":{"sensors":1,"user":1,"device":1,"carriage":1}
,"sensors":{"ios":1,"list":1}
,"running":{"filemaker":1}
,"go":{"find":1,"returns":1}
,"find":{"distance":1}
,"distance":{"number":1,"meters":1}
,"steps":{"traveled":1,"detected":1,"hour":1}
,"traveled":{"by":1}
,"user":{"acceleration":1,"ios":1,"duration":1,"8000":1}
,"acceleration":{"speed":1,"attitude":1,"user":1,"meters":1}
,"speed":{"heading":1,"acceleration":1,"speed":1,"device":1}
,"heading":{"attitude":1,"current":1}
,"attitude":{"ios":1,"speed":1,"attitude":1}
,"data":{"type":1,"returned":1,"default":1}
,"type":{"returned":1}
,"returned":{"option1":1,"list":1}
,"battery":{"batterylevel":1,"charge":1}
,"batterylevel":{"battery":1}
,"charge":{"level":1,"-unplugged":1}
,"level":{"0.0":1}
,"0.0":{"1.0":1,"359.9":1}
,"1.0":{"number":1}
,"batterystatus":{"number":1}
,"representing":{"status":1}
,"status":{"battery":1}
,"-unplugged":{"-charging":1}
,"-charging":{"-plugged":1}
,"-plugged":{"full":1}
,"full":{"number":1}
,"location":{"location":1,"current":1,"ios":1,"function":1}
,"current":{"location":1,"direction":1,"attitude":1}
,"format":{"latitude":1,"roll":1,"text":1}
,"latitude":{"degrees":1}
,"degrees":{"longitude":1,"horizontal":1,"altitude":1,"returns":1,"number":1,"relative":1}
,"longitude":{"degrees":1}
,"horizontal":{"accuracy":1}
,"accuracy":{"+\u002F-accuracy":1,"meters":1,"number":1,"100":1}
,"+\u002F-accuracy":{"meters":1}
,"meters":{"text":1,"timeout":1,"horizontal":1,"vertical":1,"age":1,"second":1,"traveled":1,"default":1}
,"timeout":{"seconds":1,"number":1,"10":1}
,"seconds":{"locationvalues":1,"attitude":1,"heading":1,"magnetic":1,"compasstrueheading":1,"step":1,"take":1,"midnight":1}
,"locationvalues":{"current":1,"locationvalues":1,"function":1}
,"altitude":{"meters":1}
,"vertical":{"accuracy":1}
,"age":{"minutes":1}
,"minutes":{"text":1}
,"radians":{"format":1,"second":1}
,"roll":{"pitch":1}
,"pitch":{"yaw":1}
,"yaw":{"text":1}
,"rotationrate":{"rotation":1}
,"rotation":{"rate":1}
,"rate":{"ios":1}
,"second":{"format":1,"squared":1,"number":1}
,"accelerationbyuser":{"acceleration":1}
,"squared":{"m\u002Fs":1}
,"m\u002Fs":{"format":1}
,"accelerationbygravity":{"gravity":1}
,"gravity":{"acceleration":1}
,"direction":{"movement":1}
,"movement":{"degrees":1}
,"359.9":{"degrees":1}
,"magnetic":{"magneticfield":1,"field":1,"north":1}
,"magneticfield":{"magnetic":1}
,"field":{"vector":1}
,"vector":{"microteslas":1}
,"microteslas":{"respect":1}
,"respect":{"current":1}
,"compassmagneticheadin":{"orientation":1}
,"orientation":{"user\u2019s":1}
,"user\u2019s":{"device":1}
,"relative":{"magnetic":1,"true":1}
,"north":{"returns":1}
,"compasstrueheading":{"orientation":1}
,"true":{"north":1}
,"step":{"counts":1}
,"counts":{"stepcount":1}
,"stepcount":{"number":1,"3600":1}
,"detected":{"by":1}
,"duration":{"number":1}
,"forpastseconds":{"stepdistance":1,"stepfloorsup":1,"stepfloorsdown":1,"air":1,"number":1}
,"stepdistance":{"estimated":1}
,"estimated":{"distance":1}
,"stepfloorsup":{"approximate":1}
,"approximate":{"number":1}
,"floors":{"ascended":1,"descended":1}
,"ascended":{"by":1}
,"stepfloorsdown":{"approximate":1}
,"descended":{"by":1}
,"air":{"pressure":1}
,"pressure":{"airpressure":1,"kilopascals":1}
,"airpressure":{"recorded":1}
,"recorded":{"air":1}
,"kilopascals":{"number":1}
,"list":{"sensors":1,"sensorname":1,"numbers":1}
,"values":{"device":1,"separated":1,"location":1,"locationvalues":1}
,"separated":{"by":1}
,"carriage":{"returns":1}
,"numbers":{"separated":1}
,"represents":{"distance":1,"time":1}
,"default":{"value":1}
,"100":{"meters":1}
,"time":{"seconds":1}
,"take":{"get":1}
,"get":{"data":1}
,"10":{"maximum":1}
,"maximum":{"value":1}
,"600":{"default":1}
,"midnight":{"filemaker":1}
,"empty":{"string":1}
,"string":{"if":1}
,"if":{"sensor":1,"user":1}
,"3600":{"eturns":1}
,"eturns":{"8000":1}
,"8000":{"if":1,"steps":1}
,"hour":{"sensors":1}
}
;Search.control.loadWordPairs(pairs);
