var pairs =
{
"hanging":{"width":1}
,"width":{"layout":1}
,"layout":{"expand":1,"accommodate":1,"layout":1,"wider":1,"resizing":1,"use":1,"objects":1,"store":1,"prevent":1,"layouts":1}
,"expand":{"reduce":1}
,"reduce":{"width":1}
,"accommodate":{"objects":1}
,"objects":{"eliminate":1,"setting":1,"place":1,"gray":1,"layout":1,"located":1,"resize":1}
,"eliminate":{"blank":1}
,"blank":{"space":1}
,"space":{"layout":1}
,"wider":{"helps":1}
,"helps":{"edge":1}
,"edge":{"layout":1}
,"resizing":{"window":1,"layout":1}
,"window":{"rag":1}
,"rag":{"gray":1}
,"gray":{"line":1,"right":1,"use":1}
,"line":{"right":1}
,"right":{"layout":1}
,"use":{"auto-resize":1,"script":1}
,"auto-resize":{"settings":1,"options":1}
,"settings":{"automatically":1}
,"automatically":{"resize":1}
,"resize":{"objects":1,"resizing":1}
,"setting":{"auto-resize":1}
,"options":{"layout":1}
,"place":{"objects":1}
,"store":{"objects":1}
,"prevent":{"appearing":1}
,"appearing":{"browse":1}
,"browse":{"find":1,"mode":1}
,"find":{"preview":1}
,"preview":{"modes":1}
,"modes":{"objects":1}
,"located":{"gray":1}
,"script":{"steps":1}
,"steps":{"browse":1}
,"mode":{"uto-resiz":1}
,"uto-resiz":{"ettings":1}
,"ettings":{"skipped":1}
,"skipped":{"tab":1}
,"tab":{"order":1}
,"order":{"dialog":1}
,"dialog":{"box":1}
,"box":{"lists":1}
,"lists":{"table":1}
,"table":{"view":1}
,"view":{"field":1}
,"field":{"objects":1}
,"layouts":{"change":1}
,"change":{"width":1}
}
;Search.control.loadWordPairs(pairs);
