var pairs =
{
"seconds":{"returns":1,"portion":1,"time":1,"value":1,"12:15:23":1}
,"returns":{"number":1,"23":1}
,"number":{"representing":1,"filemaker":1}
,"representing":{"seconds":1}
,"portion":{"time":1}
,"time":{"seconds":1,"time":1,"-any":1,"value":1,"number":1}
,"-any":{"time":1}
,"value":{"field":1,"returned":1}
,"field":{"type":1}
,"type":{"time":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"if":1}
,"if":{"seconds":1}
,"returned":{"seconds":1}
,"12:15:23":{"returns":1}
}
;Search.control.loadWordPairs(pairs);
