var pairs =
{
"url":{"shared":1,"link":1,"format":1}
,"shared":{"file":1,"filemaker":1,"ile":1}
,"file":{"if":1,"shared":1,"by":1,"choose":1,"menu":1,"includes":1,"link":1,"email":1}
,"if":{"file":1,"prompted":1,"don\u2019t":1,"ipv6":1}
,"filemaker":{"pro":1,"software":1,"sharing":1}
,"pro":{"advanced":1}
,"advanced":{"users":1,"technical":1}
,"users":{"access":1,"users":1,"by":1,"savin":1}
,"access":{"by":1,"sure":1,"file":1,"select":1,"host":1}
,"by":{"sending":1,"mail":1,"privilege":1}
,"sending":{"url":1,"records":1}
,"link":{"file":1,"database":1,"shared":1,"address":1,"appears":1,"copy":1,"client":1,"web-based":1,"current":1,"send":1}
,"mail":{"url":1}
,"format":{"fmp:\u002F\u002F[[account:password@]":1}
,"fmp:\u002F\u002F[[account:password@]":{"netaddress]\u002Ffile":1}
,"netaddress]\u002Ffile":{"nam":1}
,"nam":{"open":1}
,"open":{"shared":1,"host":1}
,"ile":{"want":1,"open":1}
,"want":{"recipient":1}
,"recipient":{"access":1,"type":1,"body":1,"connect":1}
,"sure":{"sharing":1}
,"sharing":{"settings":1,"choose":1,"client":1}
,"settings":{"provide":1}
,"provide":{"user":1}
,"user":{"access":1}
,"choose":{"file":1,"type":1,"email":1}
,"menu":{"sharing":1,"send":1}
,"type":{"network":1,"additional":1}
,"network":{"access":1}
,"select":{"all":1}
,"all":{"users":1}
,"privilege":{"set":1}
,"set":{"choose":1,"records":1}
,"send":{"link":1,"message":1,"url":1}
,"database":{"if":1}
,"prompted":{"choose":1}
,"email":{"client":1,"pens":1,"application":1,"ile":1,"snapshot":1}
,"client":{"profile":1,"computer":1,"filemaker":1,"server":1,"valid":1,"network":1,"host":1}
,"profile":{"email":1}
,"pens":{"message":1}
,"message":{"link":1,"recipient":1,"send":1,"if":1}
,"includes":{"requirements":1}
,"requirements":{"link":1}
,"address":{"message":1,"client":1}
,"additional":{"recipient":1}
,"body":{"message":1}
,"don\u2019t":{"email":1}
,"computer":{"url":1}
,"appears":{"dialog":1}
,"dialog":{"box":1}
,"box":{"save":1}
,"save":{"link":1}
,"copy":{"clipboard":1}
,"clipboard":{"paste":1}
,"paste":{"application":1}
,"application":{"accepts":1,"nstalled":1}
,"accepts":{"text":1}
,"text":{"recipient":1}
,"connect":{"file":1}
,"software":{"supported":1}
,"supported":{"email":1}
,"nstalled":{"filemaker":1}
,"technical":{"specifications":1}
,"specifications":{"link":1}
,"web-based":{"email":1}
,"host":{"machine":1,"if":1,"support":1}
,"machine":{"firewalls":1}
,"firewalls":{"client":1}
,"server":{"allow":1}
,"allow":{"filemaker":1}
,"valid":{"account":1}
,"account":{"password":1}
,"password":{"client":1}
,"ipv6":{"address":1,"email":1}
,"support":{"ipv6":1}
,"snapshot":{"link":1}
,"current":{"found":1}
,"found":{"set":1}
,"records":{"users":1,"snapshot":1}
,"savin":{"sending":1}
}
;Search.control.loadWordPairs(pairs);
