var pairs =
{
"edit":{"user":1,"menu":1,"dictionary":1}
,"user":{"dictionary":1,"open":1}
,"dictionary":{"pens":1,"dialog":1,"use":1,"spell":1,"end":1}
,"pens":{"user":1}
,"dialog":{"box":1,"[\u0022":1}
,"box":{"none":1,"users":1,"if":1,"show":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1,"advanced":1}
,"6.0":{"earlier":1}
,"earlier":{"script":1}
,"script":{"step":1}
,"step":{"choosing":1,"open":1}
,"choosing":{"edit":1}
,"menu":{"spelling":1}
,"spelling":{"edit":1}
,"use":{"script":1}
,"open":{"edit":1}
,"users":{"if":1}
,"if":{"restricted":1,"user":1,"[get":1,"replacing":1}
,"restricted":{"access":1}
,"access":{"filemaker":1}
,"advanced":{"menus":1}
,"menus":{"displays":1}
,"displays":{"custom":1}
,"custom":{"dialog":1}
,"show":{"custom":1}
,"[\u0022":{"edit":1}
,"spell":{"checking":1}
,"checking":{"\u0022]":1}
,"\u0022]":{"if":1}
,"[get":{"lastmessagechoice":1}
,"lastmessagechoice":{"=1]":1}
,"=1]":{"edit":1}
,"end":{"if":1}
,"replacing":{"contents":1}
,"contents":{"field":1}
,"field":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
