var pairs =
{
"security":{"lock":1,"environment":1}
,"lock":{"icons":1,"icon":1}
,"icons":{"connect":1}
,"connect":{"hosted":1}
,"hosted":{"solution":1}
,"solution":{"lock":1}
,"icon":{"encryption":1,"view":1,"connection":1,"check":1}
,"encryption":{"status":1}
,"status":{"connection":1}
,"connection":{"host":1,"encrypted":1}
,"host":{"lock":1}
,"view":{"detailed":1}
,"detailed":{"host\u2019s":1}
,"host\u2019s":{"ssl":1}
,"ssl":{"certificate":1,"if":1}
,"certificate":{"secure":1,"open":1,"filemaker":1}
,"secure":{"connections":1}
,"connections":{"encrypted":1}
,"encrypted":{"ssl":1,"closed":1,"verified":1}
,"if":{"security":1}
,"environment":{"server":1}
,"server":{"administrator":1,"verified":1,"pretending":1}
,"administrator":{"install":1}
,"install":{"custom":1}
,"custom":{"ssl":1}
,"open":{"filename":1,"lock":1}
,"filename":{"dialog":1}
,"dialog":{"box":1}
,"box":{"upper-right":1}
,"upper-right":{"corner":1}
,"corner":{"filemaker":1}
,"filemaker":{"ro":1,"server":1}
,"ro":{"advanced":1}
,"advanced":{"application":1}
,"application":{"window":1}
,"window":{"open":1}
,"closed":{"lock":1}
,"verified":{"connected":1,"ssl":1}
,"connected":{"server":1}
,"pretending":{"actual":1}
,"actual":{"destination":1}
,"destination":{"confidential":1}
,"confidential":{"risk":1}
,"risk":{"closed":1}
,"check":{"mark":1}
,"mark":{"connection":1}
}
;Search.control.loadWordPairs(pairs);
