var pairs =
{
"chart":{"preview":1,"setup":1,"display":1,"legend":1,"inspector":1,"multiple":1,"restore":1,"browse":1}
,"preview":{"use":1,"efficiently":1,"chart":1,"pause":1,"open":1,"slow":1,"choose":1,"update":1,"button":1,"refresh":1}
,"use":{"chart":1,"actual":1,"sample":1}
,"efficiently":{"chart":1}
,"setup":{"dialog":1}
,"dialog":{"box":1}
,"box":{"note":1,"by":1}
,"note":{"shared":1}
,"shared":{"file":1}
,"file":{"data":1}
,"data":{"made":1,"viewed":1,"series":1,"if":1,"preview":1,"you\u2019ve":1,"setting":1,"layout":1,"chart":1}
,"made":{"by":1}
,"by":{"users":1,"default":1}
,"users":{"displayed":1}
,"displayed":{"chart":1}
,"display":{"updated":1,"tooltips":1,"sample":1,"use":1}
,"updated":{"data":1}
,"viewed":{"browse":1}
,"browse":{"mode":1}
,"mode":{"display":1,"choose":1}
,"tooltips":{"objects":1}
,"objects":{"preview":1,"select":1}
,"pause":{"pointer":1,"preview":1}
,"pointer":{"title":1}
,"title":{"chart":1}
,"legend":{"axes":1}
,"axes":{"titles":1,"radius":1,"if":1}
,"titles":{"axes":1}
,"radius":{"objects":1}
,"select":{"object":1}
,"object":{"preview":1}
,"open":{"chart":1}
,"inspector":{"activate":1}
,"activate":{"object\u2019s":1}
,"object\u2019s":{"control":1}
,"control":{"switch":1}
,"switch":{"x-axis":1}
,"x-axis":{"y-axis":1,"display":1}
,"y-axis":{"swap":1}
,"swap":{"axes":1}
,"if":{"chart":1,"preview":1}
,"multiple":{"data":1}
,"series":{"defined":1}
,"defined":{"first":1}
,"first":{"y-series":1}
,"y-series":{"appears":1}
,"appears":{"x-axis":1}
,"sample":{"data":1}
,"slow":{"display":1}
,"actual":{"data":1}
,"choose":{"use":1,"view":1}
,"you\u2019ve":{"finished":1}
,"finished":{"editing":1}
,"editing":{"chart":1}
,"restore":{"use":1}
,"setting":{"erify":1}
,"erify":{"chart":1}
,"view":{"menu":1}
,"menu":{"show":1}
,"show":{"sample":1}
,"layout":{"mode":1}
,"default":{"pause":1}
,"update":{"pause":1}
,"button":{"refresh":1}
,"refresh":{"paused":1,"preview":1}
,"paused":{"preview":1}
}
;Search.control.loadWordPairs(pairs);
