var pairs =
{
"panel":{"controls":1,"control":1}
,"controls":{"layouts":1,"simplify":1,"layout":1}
,"layouts":{"use":1,"help":1}
,"use":{"panel":1}
,"simplify":{"entering":1}
,"entering":{"viewing":1}
,"viewing":{"data":1}
,"data":{"panel":1}
,"layout":{"objects":1,"use":1,"fields":1}
,"objects":{"allow":1,"tab":1}
,"allow":{"group":1}
,"group":{"objects":1}
,"tab":{"panels":1,"control":1}
,"panels":{"slide":1,"layout":1,"categories":1,"dots":1,"move":1}
,"slide":{"panels":1,"control":1}
,"control":{"layouts":1,"tab":1,"if":1}
,"help":{"organize":1}
,"organize":{"layout":1}
,"fields":{"customer":1}
,"customer":{"tables":1}
,"tables":{"grouped":1}
,"grouped":{"tab":1}
,"categories":{"personal":1}
,"personal":{"contact":1}
,"contact":{"business":1,"purchasing":1}
,"business":{"contact":1}
,"purchasing":{"products":1}
,"products":{"move":1}
,"move":{"slide":1}
,"dots":{"bottom":1}
,"bottom":{"slide":1}
,"if":{"device":1}
,"device":{"supports":1}
,"supports":{"gestures":1}
,"gestures":{"swipe":1}
,"swipe":{"slide":1}
}
;Search.control.loadWordPairs(pairs);
