var pairs =
{
"data":{"container":1,"interactive":1,"embedded":1}
,"container":{"fields":1,"field":1,"field\u2019s":1,"depends":1,"displaying":1,"scroll":1,"choose":1}
,"fields":{"container":1,"browse":1,"insert":1,"portals":1,"compressed":1}
,"field":{"store":1,"by":1,"pasting":1,"interactive":1,"field":1,"file":1,"choose":1,"displays":1,"displaying":1,"optimized":1,"pressing":1,"container":1,"press":1,"first":1,"data":1,"interactively":1,"popover":1,"global":1,"supported":1}
,"store":{"pictures":1,"reference":1}
,"pictures":{"audio":1,"photos":1}
,"audio":{"video":1,"file":1,".wma":1}
,"video":{"files":1,"scroll":1,"player":1,"file":1,"interactive":1,"quicktimevr":1}
,"files":{"pdfs":1,"inserting":1,"interactive":1,"keynote":1,"container":1,"drag":1,"graphics":1}
,"pdfs":{"type":1}
,"type":{"file":1,"inserted":1,"supported":1,"picture":1}
,"file":{"want":1,"clipboard":1,"type":1,"stored":1,"open":1,"filemaker":1,"track":1,"if":1,"file":1,"won\u2019t":1,"format":1,"picture":1,"field":1,"choose":1,"icon":1,"types":1,"store":1,"option":1,"associated":1,".aif":1,".mp3":1,".m4a":1,".m4v":1,".au":1,".wav":1,"container":1,"location":1,"hard":1,"formats":1}
,"want":{"keep":1}
,"keep":{"database":1}
,"database":{"add":1}
,"add":{"content":1}
,"content":{"container":1,"web":1}
,"by":{"inserting":1,"selecting":1,"double-clicking":1,"creating":1,"default":1}
,"inserting":{"dragging":1,"pdf":1}
,"dragging":{"field":1}
,"pasting":{"file":1}
,"clipboard":{"if":1}
,"if":{"field":1,"select":1,"move":1,"insert":1,"container":1,"use":1}
,"interactive":{"container":1,"containers":1,"content":1}
,"field\u2019s":{"contents":1}
,"contents":{"interactively":1,"audio":1,"scroll":1}
,"interactively":{"play":1,"container":1}
,"play":{"music":1,"video":1,"file":1}
,"music":{"play":1,"clips":1}
,"scroll":{"pdf":1,"page":1,"bar":1}
,"pdf":{"field":1,"choose":1,"windows":1,"dimmed":1,"files":1,"file":1,".pdf":1}
,"depends":{"file":1}
,"inserted":{"field":1,"file":1,"audio":1}
,"stored":{"setting":1,"container":1}
,"setting":{"inspector":1}
,"inspector":{"option":1}
,"option":{"optimized":1,"file":1,"reduce":1,"selected":1}
,"optimized":{"pecifying":1,"interactivity":1,"images":1,"interactive":1}
,"pecifying":{"formats":1}
,"formats":{"container":1,"inserted":1}
,"browse":{"mode":1}
,"mode":{"container":1}
,"choose":{"command":1,"storage":1,"insert":1,"file":1,"edit":1}
,"command":{"insert":1}
,"insert":{"menu":1,"each":1,"type":1,"package":1,"container":1,"file":1}
,"menu":{"choose":1,"picture":1,"audio\u002Fvideo":1,"file":1,"pdf":1,"clear":1}
,"storage":{"option":1,"change":1}
,"open":{"note":1,"file":1}
,"note":{"if":1,"sun":1}
,"select":{"store":1}
,"reference":{"file":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"import":1,"file":1}
,"import":{"file":1}
,"track":{"hard":1}
,"hard":{"disk":1}
,"disk":{"option":1,"by":1}
,"reduce":{"size":1}
,"size":{"filemaker":1}
,"move":{"delete":1}
,"delete":{"referenced":1,"data":1,"delete":1}
,"referenced":{"file":1}
,"won\u2019t":{"displayed":1}
,"displayed":{"table":1}
,"table":{"describes":1}
,"describes":{"insert":1}
,"each":{"supported":1}
,"supported":{"file":1,"format":1,"insert":1}
,"format":{"container":1,"type":1}
,"displays":{"container":1,"picture":1,"file\u2019s":1,"file":1,"first":1}
,"picture":{"choose":1,"container":1,"audio\u002Fvideo":1,"ncapsulated":1}
,"displaying":{"picture":1,"video":1,"pdf":1,"first":1,"file":1}
,"audio\u002Fvideo":{"field":1,"choose":1,"aiff":1}
,"interactivity":{"choose":1}
,"file\u2019s":{"contents":1}
,"player":{"play":1,"controls":1}
,"controls":{"field":1}
,"images":{"choose":1,"inserted":1,"insert":1}
,"icon":{"filename":1,"audio":1,"pdf":1,"note":1}
,"filename":{"container":1}
,"containers":{"df":1,"file":1}
,"df":{"field":1,".pdf":1}
,"page":{"document":1,"file":1,"pdf":1}
,"document":{"field":1}
,"bar":{"displaying":1,"by":1}
,"windows":{"if":1,"bitmap":1,"metafile\u002Fenhanced":1,"audio\u002Fvideo":1,"media":1}
,"dimmed":{"field":1}
,"web":{"browser":1}
,"browser":{"plug-in":1}
,"plug-in":{"adobe":1,"pdf":1}
,"adobe":{"reader":1}
,"reader":{"installed":1}
,"installed":{"local":1}
,"local":{"computer":1}
,"computer":{"install":1}
,"install":{"web":1}
,"first":{"page":1,"archive":1}
,"types":{"choose":1}
,"selected":{"open":1}
,"associated":{"application":1}
,"application":{"by":1}
,"selecting":{"field":1}
,"pressing":{"space":1}
,"space":{"bar":1}
,"double-clicking":{"field":1}
,"ncapsulated":{"postscript":1}
,"postscript":{".eps":1}
,".eps":{"gif":1}
,"gif":{".gif":1}
,".gif":{"jpeg\u002Fjfif":1}
,"jpeg\u002Fjfif":{".jpg":1}
,".jpg":{"df":1}
,".pdf":{"macos":1,"delete":1}
,"macos":{"photoshop":1,"ng":1,"plug-ins":1}
,"photoshop":{".psd":1}
,".psd":{"macos":1}
,"ng":{".png":1}
,".png":{"iff":1}
,"iff":{".tif":1}
,".tif":{"windows":1}
,"bitmap":{".bmp":1}
,".bmp":{"windows":1}
,"metafile\u002Fenhanced":{"metafile":1}
,"metafile":{".wmf\u002F.emf":1}
,".wmf\u002F.emf":{"windows":1}
,"aiff":{"audio":1}
,".aif":{".aiff":1}
,".aiff":{"avi":1}
,"avi":{"movie":1}
,"movie":{".avi":1,".mp4":1,".mpg":1,".mov":1}
,".avi":{"mp3":1}
,"mp3":{"audio":1}
,".mp3":{"mpeg-4":1}
,"mpeg-4":{"audio":1,"movie":1,"video":1}
,".m4a":{"mpeg-4":1}
,".mp4":{"mpeg":1}
,"mpeg":{"movie":1}
,".mpg":{".mpeg":1}
,".mpeg":{"mpeg-4":1}
,".m4v":{"quicktime":1}
,"quicktime":{"movie":1}
,".mov":{".qt":1}
,".qt":{"note":1,"formats":1}
,"sun":{"audio":1}
,".au":{"wave":1}
,"wave":{"audio":1}
,".wav":{"windows":1}
,"media":{"audio":1,"videos":1,"files":1}
,".wma":{"windows":1}
,"videos":{".wmv":1}
,".wmv":{"pdf":1}
,"press":{"backspace":1}
,"backspace":{"delete":1}
,"edit":{"menu":1}
,"clear":{"cut":1}
,"cut":{"quicktime":1}
,"quicktimevr":{"aren\u2019t":1}
,"aren\u2019t":{"supported":1}
,"package":{"files":1}
,"keynote":{"files":1}
,"archive":{"zip":1}
,"zip":{"package":1}
,"drag":{"file":1}
,"embedded":{"container":1}
,"portals":{"if":1}
,"popover":{"portal":1}
,"portal":{"if":1}
,"use":{"graphic":1}
,"graphic":{"place":1}
,"place":{"company":1,"changed":1}
,"company":{"logo":1}
,"logo":{"insert":1}
,"global":{"storage":1}
,"change":{"graphic":1}
,"changed":{"nserting":1}
,"nserting":{"graphics":1}
,"graphics":{"layout":1,"images":1}
,"layout":{"if":1}
,"location":{"file":1}
,"creating":{"calculation":1}
,"calculation":{"getastext":1}
,"getastext":{"function":1}
,"function":{"macos":1}
,"plug-ins":{"stored":1}
,"compressed":{"by":1}
,"default":{"music":1}
,"clips":{"movies":1}
,"movies":{"pictures":1}
,"photos":{"media":1}
}
;Search.control.loadWordPairs(pairs);
