var pairs =
{
"actions":{"don\u2019t":1}
,"don\u2019t":{"ctivat":1}
,"ctivat":{"cript":1}
,"cript":{"triggers":1,"trigger":1}
,"triggers":{"bulk":1,"check":1,"activate":1,"made":1,"schema":1}
,"bulk":{"operations":1}
,"operations":{"change":1,"activate":1}
,"change":{"records":1,"field":1,"data":1}
,"records":{"activate":1,"found":1,"replace":1}
,"activate":{"script":1,"except":1,"if":1,"field":1,"cript":1,"onobjectmodify":1,"summary":1}
,"script":{"trigger":1,"step":1,"triggers":1,"steps":1}
,"trigger":{"spell":1,"ill":1,"while":1,"made":1,"layout":1,"script":1,"apple":1,"summary":1,"set":1}
,"spell":{"checking":1}
,"checking":{"edit":1}
,"edit":{"menu":1}
,"menu":{"spelling":1,"find\u002Freplace":1,"commands":1}
,"spelling":{"check":1,"all":1}
,"check":{"all":1,"found":1,"spelling":1}
,"all":{"check":1,"fields":1,"records":1}
,"found":{"set":1}
,"set":{"script":1,"check":1,"field":1,"summary":1}
,"step":{"find\u002Freplace":1,"record":1,"script":1,"activate":1}
,"find\u002Freplace":{"edit":1,"open":1,"script":1}
,"open":{"find\u002Freplace":1}
,"record":{"time":1,"all":1}
,"time":{"activate":1}
,"fields":{"record":1,"activate":1,"calculation":1,"onobjectenter":1,"onobjectmodify":1}
,"except":{"if":1}
,"if":{"field":1}
,"field":{"active":1,"direct":1,"layout":1,"contents":1,"ow":1,"set":1,"by":1,"insert":1}
,"active":{"operation":1,"end":1}
,"operation":{"starts":1,"onobjectenter":1}
,"starts":{"onobjectexit":1}
,"onobjectexit":{"script":1,"onobjectkeystroke":1}
,"ill":{"activate":1}
,"end":{"operation":1}
,"onobjectenter":{"script":1,"onobjectexit":1}
,"direct":{"operations":1}
,"made":{"layout":1,"underlying":1,"field":1}
,"layout":{"object":1,"activate":1,"objects":1,"layout":1,"script":1,"im":1}
,"object":{"layout":1,"instance":1,"target":1}
,"while":{"made":1}
,"underlying":{"data":1}
,"data":{"activate":1,"layout":1,"fields":1}
,"instance":{"activate":1}
,"objects":{"layout":1,"activate":1}
,"steps":{"menu":1,"change":1,"layout":1}
,"commands":{"apply":1}
,"apply":{"table":1,"layout":1}
,"table":{"data":1}
,"im":{"port":1}
,"port":{"records":1}
,"replace":{"field":1}
,"contents":{"relookup":1,"activate":1}
,"relookup":{"field":1}
,"ow":{"custom":1}
,"custom":{"dialog":1}
,"dialog":{"script":1}
,"onobjectmodify":{"script":1}
,"by":{"name":1}
,"name":{"et":1}
,"et":{"web":1}
,"web":{"viewer":1}
,"viewer":{"activate":1}
,"target":{"field":1}
,"insert":{"text":1}
,"text":{"activate":1}
,"apple":{"events":1}
,"events":{"apply":1,"bypass":1}
,"bypass":{"layout":1}
,"schema":{"change":1}
,"summary":{"fields":1,"calculation":1}
,"calculation":{"fields":1}
,"onobjectkeystroke":{"script":1}
}
;Search.control.loadWordPairs(pairs);
