var pairs =
{
"formulas":{"functions":1}
,"functions":{"formula":1}
,"formula":{"calculates":1,"subtotal":1,"common":1,"called":1,"add":1}
,"calculates":{"single":1}
,"single":{"value":1}
,"value":{"based":1,"formula":1}
,"based":{"constants":1}
,"constants":{"1.07":1}
,"1.07":{"operators":1}
,"operators":{"field":1}
,"field":{"references":1,"named":1}
,"references":{"subtotal":1}
,"subtotal":{"invoicetotal":1,"create":1,"*1.07":1}
,"invoicetotal":{"enter":1,"value":1}
,"enter":{"if":1}
,"if":{"sales":1,"formula":1,"want":1}
,"sales":{"tax":1}
,"tax":{"field":1}
,"named":{"subtotal":1,"invoicetotal":1,"predefined":1,"average":1}
,"create":{"field":1}
,"*1.07":{"if":1}
,"common":{"popular":1}
,"popular":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"name":1}
,"name":{"defines":1}
,"defines":{"use":1}
,"use":{"named":1,"function":1}
,"predefined":{"formula":1}
,"called":{"function":1}
,"function":{"if":1,"named":1}
,"want":{"find":1}
,"find":{"average":1}
,"average":{"test":1,"follow":1}
,"test":{"scores":1}
,"scores":{"write":1,"simpler":1}
,"write":{"own":1}
,"own":{"formula":1}
,"add":{"all":1}
,"all":{"divide":1}
,"divide":{"by":1}
,"by":{"total":1}
,"total":{"number":1}
,"number":{"scores":1}
,"simpler":{"approach":1}
,"approach":{"use":1}
,"follow":{"rules":1}
,"rules":{"defined":1}
,"defined":{"use":1}
}
;Search.control.loadWordPairs(pairs);
