var pairs =
{
"creating":{"editing":1,"accounts":1,"ccounts":1}
,"editing":{"accounts":1,"privilege":1}
,"accounts":{"create":1,"shared":1,"privilege":1,"determines":1,"list":1,"authenticate":1,"under":1,"change":1}
,"create":{"edit":1,"accounts":1,"new":1,"password":1}
,"edit":{"ccounts":1,"privilege":1,"account":1}
,"ccounts":{"individual":1}
,"individual":{"accesses":1,"users":1}
,"accesses":{"file":1}
,"file":{"create":1,"note":1,"choose":1,"menu":1,"options":1,"authenticate":1,"enter":1,"hosted":1,"shared":1}
,"shared":{"individuals":1,"via":1}
,"individuals":{"arketing":1}
,"arketing":{"ccount":1}
,"ccount":{"ales":1,"assign":1}
,"ales":{"ccount":1}
,"assign":{"privilege":1}
,"privilege":{"set":1,"sets":1,"if":1}
,"set":{"each":1,"if":1,"password":1,"choose":1,"ee":1,"up":1,"clear":1}
,"each":{"new":1,"time":1,"account":1}
,"new":{"account":1,"password":1}
,"account":{"accounts":1,"warning":1,"name":1,"new":1,"change":1,"select":1,"authenticate":1,"names":1,"user":1,"active":1,"inactive":1,"duplicate":1,"button":1,"delete":1}
,"sets":{"extended":1,"account":1,"require":1}
,"extended":{"privilege":1}
,"if":{"change":1,"write":1,"lose":1,"manage":1,"file":1}
,"change":{"authentication":1,"file":1,"existing":1,"account":1,"password":1,"enter":1,"next":1}
,"authentication":{"order":1,"server":1}
,"order":{"accounts":1,"filemaker":1,"want":1}
,"determines":{"order":1}
,"filemaker":{"server":1,"webdirect":1}
,"server":{"searches":1,"oauth":1,"creating":1,"help":1}
,"searches":{"accounts":1}
,"list":{"valid":1}
,"valid":{"account":1}
,"warning":{"passwords":1}
,"passwords":{"recovered":1,"case":1,"a-z":1,"web-published":1}
,"recovered":{"on\u2019t":1}
,"on\u2019t":{"forget":1}
,"forget":{"account":1}
,"name":{"password":1,"enter":1,"account":1,"user":1,"defined":1,"file":1,"order":1}
,"password":{"assigned":1,"access":1,"etting":1,"change":1,"set":1,"passwords":1,"sure":1,"next":1,"remove":1,"delete":1,"create":1}
,"assigned":{"full":1}
,"full":{"access":1}
,"access":{"privilege":1,"change":1}
,"write":{"store":1}
,"store":{"secure":1}
,"secure":{"place":1}
,"place":{"if":1}
,"lose":{"forget":1}
,"note":{"automatically":1,"changing":1}
,"automatically":{"log":1}
,"log":{"each":1}
,"time":{"file":1,"logs":1}
,"choose":{"file":1,"ilemaker":1,"new":1,"create":1}
,"menu":{"file":1,"manage":1}
,"options":{"account":1,"choose":1}
,"etting":{"file":1}
,"manage":{"security":1}
,"security":{"if":1,"dialog":1,"settings":1}
,"dialog":{"box":1}
,"box":{"displays":1,"user":1}
,"displays":{"detailed":1}
,"detailed":{"security":1}
,"settings":{"use":1}
,"use":{"basic":1,"ascii":1,"colons":1}
,"basic":{"setup":1}
,"setup":{"create":1,"select":1,"drag":1}
,"existing":{"account":1,"accounts":1}
,"select":{"account":1,"require":1,"checkbox":1}
,"authenticate":{"via":1,"users":1}
,"via":{"choose":1,"external":1,"oauth":1,"filemaker":1,"web":1}
,"ilemaker":{"file":1}
,"users":{"via":1,"ase":1}
,"external":{"authentication":1,"server":1}
,"oauth":{"identity":1}
,"identity":{"provider":1}
,"provider":{"se":1,"account":1,"filemaker":1}
,"se":{"creating":1}
,"enter":{"change":1,"verify":1}
,"names":{"case":1,"match":1,"ascii":1,"passwords":1}
,"case":{"sensitive":1}
,"sensitive":{"creating":1,"create":1}
,"ase":{"each":1}
,"user":{"name":1,"doesn\u2019t":1,"choose":1}
,"defined":{"preferences":1}
,"preferences":{"dialog":1}
,"match":{"th":1}
,"th":{"user":1}
,"doesn\u2019t":{"ype":1}
,"ype":{"account":1}
,"verify":{"password":1}
,"sure":{"caps":1}
,"caps":{"lock":1}
,"lock":{"key":1}
,"key":{"keyboard":1}
,"keyboard":{"inadvertently":1}
,"inadvertently":{"enabled":1}
,"enabled":{"require":1}
,"require":{"account":1,"password":1,"periodic":1}
,"next":{"time":1,"login":1}
,"logs":{"select":1}
,"login":{"privilege":1}
,"ee":{"creating":1}
,"active":{"select":1}
,"checkbox":{"account":1,"choose":1}
,"inactive":{"set":1}
,"up":{"privilege":1}
,"clear":{"checkbox":1}
,"duplicate":{"account":1,"delete":1}
,"button":{"delete":1,"note":1}
,"delete":{"account":1,"password":1,"existing":1}
,"changing":{"authentication":1}
,"under":{"situations":1}
,"situations":{"file":1}
,"hosted":{"by":1}
,"by":{"filemaker":1}
,"help":{"choose":1}
,"drag":{"each":1}
,"want":{"use":1}
,"ascii":{"characters":1}
,"characters":{"passwords":1,"nd":1,"non-roman":1,"cyrillic":1,"use":1}
,"a-z":{"a-z":1,"0-9":1}
,"0-9":{"punctuation":1}
,"punctuation":{"characters":1}
,"nd":{"asswords":1}
,"asswords":{"accented":1}
,"accented":{"characters":1}
,"non-roman":{"characters":1}
,"cyrillic":{"japanese":1}
,"japanese":{"cross-platform":1}
,"cross-platform":{"database":1}
,"database":{"solutions":1}
,"solutions":{"files":1}
,"files":{"accessed":1,"set":1}
,"accessed":{"via":1}
,"webdirect":{"if":1}
,"web":{"publishing":1}
,"publishing":{"limit":1}
,"limit":{"account":1}
,"colons":{"account":1}
,"web-published":{"files":1}
,"periodic":{"password":1}
,"remove":{"password":1}
}
;Search.control.loadWordPairs(pairs);
