var pairs =
{
"refresh":{"rtal":1,"portal":1,"window":1}
,"rtal":{"efreshes":1}
,"efreshes":{"relationship":1}
,"relationship":{"contents":1}
,"contents":{"named":1,"portal":1}
,"named":{"object":1}
,"object":{"object":1,"name":1,"current":1,"naming":1,"script":1}
,"name":{"named":1,"refresh":1,"portal":1,"customer":1}
,"current":{"layout":1}
,"layout":{"if":1,"object":1}
,"if":{"object":1,"layout":1}
,"portal":{"refreshes":1,"updates":1,"displays":1,"global":1,"onobjectexit":1,"users":1,"performs":1,"refresh":1,"set":1,"[object":1}
,"refreshes":{"active":1}
,"active":{"layout":1}
,"naming":{"objects":1}
,"objects":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"14.0":1}
,"14.0":{"refresh":1}
,"updates":{"join":1,"portal":1}
,"join":{"relationship":1}
,"displays":{"related":1}
,"related":{"records":1}
,"records":{"use":1}
,"use":{"refresh":1}
,"global":{"field":1}
,"field":{"portal\u2019s":1,"portal\u0027s":1,"[customer":1}
,"portal\u2019s":{"filter":1}
,"filter":{"calculation":1}
,"calculation":{"modified":1,"filemaker":1,"updates":1}
,"modified":{"refresh":1}
,"onobjectexit":{"script":1}
,"script":{"trigger":1,"step":1}
,"trigger":{"ill":1}
,"ill":{"refresh":1}
,"users":{"commit":1}
,"commit":{"change":1}
,"change":{"field":1}
,"webdirect":{"refresh":1}
,"performs":{"refresh":1,"esh":1}
,"window":{"script":1}
,"step":{"if":1,"sets":1}
,"esh":{"object":1}
,"sets":{"value":1}
,"value":{"global":1}
,"portal\u0027s":{"filter":1}
,"set":{"field":1}
,"[customer":{":filter":1}
,":filter":{"16]":1}
,"16]":{"refresh":1}
,"[object":{"name":1}
,"customer":{"\u0022]":1}
,"\u0022]":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
