var pairs =
{
"read":{"data":1,"if":1,"utf-8":1,"target":1,"file":1,"specifies":1,"time":1,"text":1,"entire":1,"bytes":1,"operation":1,"variable":1,"contents":1,"64":1,"up":1,"pass":1,"($filecontents":1,"all":1}
,"data":{"file":1,"open":1,"read":1,"filename":1,"by":1,"script":1,"variable":1,"stored":1,"filemaker":1}
,"file":{"reads":1,"file":1,"id":1,"open":1,"script":1,"read":1,"utf-16":1,"stored":1,"filemaker":1,"if":1,"position":1,"larger":1,"part":1,"safer":1,"time":1,"[file":1,"named":1,"exists":1,"[\u0022$file":1,"64":1,"size":1,"reached":1,"store":1}
,"reads":{"data":1,"byte":1,"entire":1,"contents":1,"first":1,"file":1}
,"open":{"data":1,"file":1}
,"id":{"numeric":1,"open":1,"stores":1,"bytes":1,"$fileid":1}
,"numeric":{"expression":1}
,"expression":{"specifies":1}
,"specifies":{"file":1,"number":1,"character":1}
,"script":{"step":1,"[text":1,"[result":1}
,"step":{"specifies":1,"reads":1,"read":1,"multiple":1}
,"number":{"bytes":1,"unicode":1,"code":1}
,"bytes":{"read":1,"utf-16":1,"assumes":1,"target":1,"checks":1,"100":1,"$k_64mb":1}
,"if":{"read":1,"set":1,"th":1,"file":1,"character":1,"expect":1,"reads":1,"[not":1,"open":1,"large.log":1,"[$fileexists":1,"[get":1,"[$filesize":1,"end":1,"[(":1,"exit":1,"[$readerror":1,"close":1,"importing":1}
,"utf-8":{"bytes":1,"8-bit":1,"utf-16":1,"code":1,"close":1,"set":1,"end":1}
,"utf-16":{"number":1,"filemaker\u2019s":1,"endian":1,"file":1}
,"unicode":{"code":1,"utf-16":1,"character":1,"text":1}
,"code":{"units":1,"points":1}
,"units":{"read":1,"if":1,"utilities":1}
,"set":{"entire":1,"data":1,"variable":1,"error":1,"field":1}
,"entire":{"file":1}
,"target":{"field":1,"variable":1,"$variable":1,"$fileexists":1,"$fileid":1,"utilities":1,"$filesize":1,"$datachunk":1,"$filecontents":1}
,"field":{"variable":1,"data":1,"set":1,"close":1,"[table":1}
,"variable":{"store":1,"container":1,"read":1,"[$file":1,"entire":1,"improved":1,"[$k_filemissingerror":1,"[$k_endoffileerror":1,"[$k_64kb":1,"[$k_64mb":1,"[$readerror":1,"[$filecontents":1}
,"store":{"data":1,"variable":1,"contents":1}
,"character":{"encoding":1,"read":1,"consists":1,"reads":1}
,"encoding":{"file":1,"utf-8":1,"bytes":1,"reads":1}
,"filemaker\u2019s":{"default":1}
,"default":{"16-bit":1}
,"16-bit":{"unicode":1}
,"endian":{"haracter":1}
,"haracter":{"encoding":1}
,"8-bit":{"unicode":1}
,"assumes":{"specific":1}
,"specific":{"character":1}
,"byte":{"time":1}
,"time":{"if":1,"64":1,"performance":1,"sure":1,"variable":1}
,"th":{"target":1}
,"container":{"field":1,"data":1}
,"stored":{"container":1,"field":1}
,"filename":{"file":1}
,"filemaker":{"pro":1,"pr":1}
,"pro":{"18.0":1}
,"18.0":{"advanced":1}
,"advanced":{"script":1,"automating":1}
,"by":{"starting":1}
,"starting":{"current":1}
,"current":{"read-write":1}
,"read-write":{"position":1}
,"position":{"reads":1,"maximum":1}
,"maximum":{"data":1}
,"64":{"mb":1,"kb":1,"*1024":1}
,"mb":{"if":1,"perform":1,"each":1,"time":1,"store":1}
,"larger":{"64":1}
,"perform":{"script":1}
,"multiple":{"times":1,"code":1}
,"times":{"reading":1}
,"reading":{"larger":1,"64":1,"unicode":1}
,"each":{"time":1}
,"performance":{"reading":1,"data":1}
,"kb":{"reading":1,"read":1}
,"text":{"portion":1,"utf-8":1,"field":1}
,"portion":{"file":1}
,"part":{"character":1}
,"consists":{"multiple":1}
,"expect":{"read":1}
,"safer":{"read":1}
,"sure":{"number":1}
,"points":{"character":1}
,"contents":{"open":1,"if":1,"field":1}
,"stores":{"data":1}
,"[file":{"id":1}
,"$variable":{"read":1}
,"checks":{"file":1}
,"named":{"change.log":1}
,"change.log":{"exists":1,"get":1}
,"exists":{"documents":1,"[\u0022$file":1,"large":1}
,"documents":{"folder":1}
,"folder":{"if":1}
,"first":{"100":1}
,"100":{"utf-8":1,"target":1,"set":1}
,"utilities":{":log":1}
,":log":{"entry":1}
,"entry":{"text":1,"read":1}
,"[$file":{"value":1}
,"value":{"get":1,"100":1,"10":1,"64":1,"large.log":1,"$filecontents":1}
,"get":{"documentspath":1,"file":1}
,"documentspath":{"&\u0022":1}
,"&\u0022":{"change.log":1}
,"[\u0022$file":{"target":1}
,"$fileexists":{"if":1,"exit":1}
,"[not":{"$fileexists":1}
,"exit":{"script":1,"loop":1}
,"[text":{"result":1}
,"result":{"end":1}
,"end":{"if":1,"file":1,"loop":1}
,"$fileid":{"read":1,"bytes":1,"if":1,"target":1,"set":1}
,"close":{"data":1}
,"large.log":{"file":1,"get":1}
,"large":{"reads":1}
,"operation":{"data":1,"sucessful":1,"failed":1}
,"improved":{"performance":1}
,"error":{"capture":1}
,"capture":{"[on":1}
,"[on":{"set":1}
,"[$k_filemissingerror":{"value":1}
,"[$k_endoffileerror":{"value":1}
,"10":{"set":1}
,"[$k_64kb":{"value":1}
,"*1024":{"set":1,"*1024":1}
,"[$k_64mb":{"value":1}
,"[$fileexists":{"=0":1}
,"=0":{"exit":1,"get":1,"$readerror":1}
,"[result":{"$k_filemissingerror":1}
,"$k_filemissingerror":{"end":1}
,"[get":{"lasterror":1}
,"lasterror":{"=0":1,"if":1}
,"size":{"[\u0022$file":1,"greater":1}
,"$filesize":{"if":1}
,"greater":{"64":1}
,"[$filesize":{"$k_64kb":1}
,"$k_64kb":{"loop":1}
,"loop":{"read":1,"if":1,"else":1}
,"up":{"64":1}
,"$k_64mb":{"target":1}
,"$datachunk":{"read":1}
,"[$readerror":{"value:get":1,"end":1}
,"value:get":{"lasterror":1}
,"sucessful":{"if":1}
,"reached":{"concatenate":1,"exit":1}
,"concatenate":{"data":1}
,"pass":{"($datachunk":1}
,"($datachunk":{"data":1}
,"($filecontents":{"if":1}
,"[(":{"$readerror":1}
,"$readerror":{"=0":1,"=$k_endoffileerror":1}
,"=$k_endoffileerror":{"set":1}
,"[$filecontents":{"value":1}
,"$filecontents":{"&$datachunk":1,"read":1,"end":1}
,"&$datachunk":{"end":1}
,"failed":{"end":1}
,"else":{"if":1}
,"all":{"read":1}
,"[table":{":data":1}
,":data":{"$filecontents":1}
,"importing":{"data":1}
,"pr":{"advanced":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
