var pairs =
{
"json":{"functions":1,"format":1,"data":1}
,"functions":{"json":1,"parse":1,"function":1}
,"parse":{"create":1}
,"create":{"modify":1}
,"modify":{"format":1}
,"format":{"data":1,"orking":1}
,"data":{"json":1,"element":1,"easier":1,"by":1}
,"orking":{"json":1}
,"function":{"returns":1}
,"returns":{"jsondeleteelement":1}
,"jsondeleteelement":{"deletes":1}
,"deletes":{"json":1}
,"element":{"by":1,"json":1}
,"by":{"object":1}
,"object":{"name":1,"names":1}
,"name":{"array":1}
,"array":{"index":1,"indexes":1}
,"index":{"path":1}
,"path":{"jsonformatelements":1,"jsonlistkeys":1,"jsonlistvalues":1,"jsonsetelement":1}
,"jsonformatelements":{"formats":1}
,"formats":{"elements":1}
,"elements":{"json":1}
,"easier":{"read":1}
,"read":{"jsongetelement":1}
,"jsongetelement":{"queries":1}
,"queries":{"json":1}
,"jsonlistkeys":{"lists":1}
,"lists":{"object":1,"values":1}
,"names":{"keys":1}
,"keys":{"array":1}
,"indexes":{"json":1}
,"jsonlistvalues":{"lists":1}
,"values":{"json":1}
,"jsonsetelement":{"adds":1}
,"adds":{"modifies":1}
,"modifies":{"element":1}
}
;Search.control.loadWordPairs(pairs);
