var pairs =
{
"getsummary":{"returns":1,"summaryfield":1,"set":1,"capture":1,"function":1,"total":1}
,"returns":{"value":1,"reference":1,"summary":1}
,"value":{"summaryfield":1,"use":1,"entire":1,"country":1}
,"summaryfield":{"current":1,"breakfield":1,"-field":1}
,"current":{"range":1,"charge":1}
,"range":{"records":1}
,"records":{"file":1,"grand":1,"pertaining":1,"summary":1}
,"file":{"sorted":1,"isn\u2019t":1}
,"sorted":{"by":1}
,"by":{"breakfield":1,"break":1,"country":1,"sales":1}
,"breakfield":{"getsummary":1,"summaryfield":1,"-field":1}
,"-field":{"type":1,"expression":1}
,"type":{"summary":1}
,"summary":{"expression":1,"value":1,"field":1,"values":1,"all":1,"total":1}
,"expression":{"returns":1}
,"reference":{"breakfield":1,"calculate":1}
,"calculate":{"grand":1}
,"grand":{"summary":1}
,"use":{"summary":1,"getsummary":1}
,"field":{"summary":1,"break":1,"parameters":1,"number":1,"result":1,"returns":1,"value":1,"getsummary":1,"total":1}
,"break":{"field":1}
,"parameters":{"getsummary":1}
,"set":{"up":1,"records":1}
,"up":{"table":1}
,"table":{"break":1}
,"number":{"date":1,"countries":1}
,"date":{"time":1}
,"time":{"timestamp":1}
,"timestamp":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"function":1}
,"function":{"produces":1,"unstored":1}
,"produces":{"subsummary":1,"summary":1}
,"subsummary":{"values":1}
,"values":{"if":1,"want":1,"calculation":1,"browse":1}
,"if":{"file":1,"thischarge":1,"current":1,"number":1}
,"isn\u2019t":{"sorted":1}
,"result":{"blank":1}
,"blank":{"summary":1}
,"entire":{"found":1}
,"found":{"set":1}
,"capture":{"summary":1}
,"want":{"use":1}
,"calculation":{"display":1}
,"display":{"subsummary":1}
,"browse":{"mode":1}
,"mode":{"body":1}
,"body":{"part":1}
,"part":{"calculations":1}
,"calculations":{"getsummary":1}
,"unstored":{"get":1}
,"get":{"self-join":1}
,"self-join":{"relationship":1}
,"relationship":{"aggregate":1}
,"aggregate":{"functions":1}
,"functions":{"orking":1}
,"orking":{"related":1}
,"related":{"data":1}
,"data":{"portals":1}
,"portals":{"getsummary":1}
,"total":{"sales":1,"total":1}
,"sales":{"country":1,"total":1,"produces":1,"if":1,"zone":1,"by":1}
,"country":{"returns":1,"field":1,"sales":1,"if":1}
,"all":{"records":1}
,"pertaining":{"value":1}
,"thischarge":{"*getsummary":1}
,"*getsummary":{"avgcharge":1}
,"avgcharge":{"customer":1}
,"customer":{"verify":1}
,"verify":{"charge":1}
,"charge":{"displays":1,"if":1,"greater":1,"getsummary":1}
,"displays":{"verify":1}
,"greater":{"times":1,"returns":1}
,"times":{"average":1}
,"average":{"charge":1}
,"countries":{"country":1,"greater":1}
,"zone":{"returns":1}
}
;Search.control.loadWordPairs(pairs);
