var pairs =
{
"get":{"filemake":1,"filemakerpath":1,"filemaker":1,"application":1}
,"filemake":{"rpath":1}
,"rpath":{"returns":1}
,"returns":{"path":1,"empty":1,"\u002Fc:\u002Fprogram":1,"\u002Fmacintosh":1}
,"path":{"folder":1,"vary":1,"follow":1,"get":1,"filemaker":1}
,"folder":{"currently":1}
,"currently":{"running":1}
,"running":{"copy":1}
,"copy":{"filemaker":1}
,"filemaker":{"product":1,"pro":1,"go":1,"products":1,"path":1}
,"product":{"get":1}
,"filemakerpath":{"none":1,"get":1}
,"none":{"text":1}
,"text":{"filemaker":1}
,"pro":{"8.0":1,"advanced":1,"18":1}
,"8.0":{"function":1}
,"function":{"supported":1}
,"supported":{"filemaker":1,"returns":1}
,"advanced":{"filemaker":1}
,"go":{"runtime":1}
,"runtime":{"solutions":1}
,"solutions":{"filemaker":1}
,"products":{"it\u2019s":1}
,"it\u2019s":{"supported":1}
,"empty":{"string":1}
,"string":{"returns":1}
,"\u002Fc:\u002Fprogram":{"files\u002Ffilemaker\u002Ffilemaker":1}
,"files\u002Ffilemaker\u002Ffilemaker":{"pro":1}
,"18":{"dvanced\u002Fin":1}
,"dvanced\u002Fin":{"windows":1,"macos":1}
,"windows":{"returns":1}
,"\u002Fmacintosh":{"hd\u002Fapplications\u002Ffilemaker":1}
,"hd\u002Fapplications\u002Ffilemaker":{"pro":1}
,"macos":{"each":1}
,"each":{"part":1}
,"part":{"path":1}
,"vary":{"examples":1}
,"examples":{"rely":1}
,"rely":{"path":1}
,"follow":{"pattern":1}
,"pattern":{"get":1}
,"application":{"path":1}
}
;Search.control.loadWordPairs(pairs);
