var pairs =
{
"si":{"ngle-criteria":1}
,"ngle-criteria":{"relationships":1}
,"relationships":{"single-criteria":1,"graph":1}
,"single-criteria":{"relationship":1}
,"relationship":{"data":1,"use":1,"relate":1,"etween":1,"customers":1,"dialog":1,"contacts":1,"defined":1}
,"data":{"field":1,"split":1}
,"field":{"matched":1,"record":1,"name":1,"first":1,"last":1,"address1":1,"city":1,"state":1,"country":1,"contacts":1,"phone":1,"email":1,"customer":1,"dialog":1,"auto-enter":1,"holds":1,"set":1,"validate":1,"each":1}
,"matched":{"data":1}
,"record":{"table":1,"customers":1,"phone":1,"inserted":1,"allows":1,"deleted":1}
,"table":{"related":1,"values":1,"field":1,"nique":1,"customer":1,"single-criteria":1,"contacts":1,"edit":1,"via":1,"nter":1,"each":1,"elect":1,"record":1,"th":1,"filemaker":1}
,"related":{"record":1,"records":1,"single":1,"fields":1}
,"values":{"textfielda":1,"setting":1}
,"textfielda":{"textfieldb":1}
,"textfieldb":{"two":1}
,"two":{"tables":1,"fields":1}
,"tables":{"lines":1,"based":1,"customers":1,"single":1}
,"lines":{"two":1}
,"fields":{"single-criteria":1,"table":1,"settings":1,"each":1,"portal":1}
,"use":{"single-criteria":1,"options":1}
,"relate":{"two":1}
,"based":{"single":1}
,"single":{"common":1,"customer":1,"record":1}
,"common":{"value":1}
,"value":{"serial":1}
,"serial":{"number":1}
,"number":{"id":1,"create":1,"field":1,"text":1,"fiel":1,"validate":1,"contacts":1,"empty":1,"relationship":1,"customers":1,"email":1}
,"id":{"number":1,"field":1,"simple":1,"fields":1,"match":1}
,"create":{"database":1,"fields":1,"relationship":1}
,"database":{"wo":1}
,"wo":{"tables":1}
,"customers":{"stores":1,"customer":1,":c":1,"table":1,"record":1}
,"stores":{"names":1,"phone":1}
,"names":{"addresses":1}
,"addresses":{"contacts":1,"data":1,"create":1}
,"contacts":{"stores":1,"phone":1,"table":1}
,"phone":{"numbers":1,"number":1,"type":1}
,"numbers":{"types":1,"mobile":1,"email":1,"if":1}
,"types":{"phones":1}
,"phones":{"numbers":1}
,"mobile":{"email":1}
,"email":{"addresses":1,"address":1,"type":1}
,"split":{"two":1}
,"customer":{"multiple":1,"id":1,"layout":1}
,"multiple":{"phone":1}
,"name":{"comment":1,"text":1}
,"comment":{"customers":1}
,"first":{"name":1}
,"text":{"field":1}
,"last":{"name":1}
,"address1":{"text":1}
,"city":{"text":1}
,"state":{"text":1}
,"country":{"text":1}
,"type":{"text":1}
,"address":{"text":1,"enter":1,"empty":1,"contacts":1}
,"fiel":{"use":1}
,"options":{"field":1,"fields":1,"set":1}
,"dialog":{"box":1}
,"box":{"set":1,"select":1}
,"set":{"customers":1,"au":1,"field":1}
,":c":{"ustomer":1}
,"ustomer":{"id":1}
,"auto-enter":{"serial":1}
,"validate":{"field":1,"empty":1}
,"holds":{"unique":1}
,"unique":{"values":1}
,"setting":{"options":1}
,"settings":{"ensure":1}
,"ensure":{"ea":1}
,"ea":{"ch":1}
,"ch":{"record":1}
,"nique":{"id":1}
,"simple":{"number":1}
,"au":{"to-entry":1}
,"to-entry":{"options":1}
,"empty":{"relationships":1,"portal":1}
,"graph":{"create":1}
,"etween":{"customer":1}
,"each":{"table":1,"new":1}
,"match":{"field":1}
,"edit":{"relationship":1}
,"select":{"llow":1}
,"llow":{"creation":1}
,"creation":{"records":1,"related":1}
,"records":{"table":1,"contacts":1}
,"via":{"relationship":1}
,"nter":{"phone":1}
,"portal":{"row":1,"contacts":1,"phone":1}
,"row":{"ilemaker":1,"customers":1}
,"ilemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"reate":1,"creates":1}
,"reate":{"related":1}
,"defined":{"allow":1}
,"allow":{"creation":1}
,"inserted":{"automatically":1}
,"automatically":{"customer":1}
,"new":{"related":1}
,"allows":{"records":1}
,"elect":{"elete":1}
,"elete":{"related":1}
,"deleted":{"table":1,"add":1}
,"th":{"ere":1}
,"ere":{"reason":1}
,"reason":{"retain":1}
,"retain":{"old":1}
,"old":{"phone":1}
,"if":{"matching":1}
,"matching":{"contact":1}
,"contact":{"record":1}
,"add":{"portal":1,"related":1}
,"layout":{"add":1}
,"enter":{"phone":1}
,"filemaker":{"pro":1}
,"creates":{"related":1}
}
;Search.control.loadWordPairs(pairs);
