var pairs =
{
"trim":{"returns":1,"text":1,"tom":1,"middle":1}
,"returns":{"text":1,"tom":1,"william":1}
,"text":{"stripped":1,"text":1,"-any":1,"expression":1,"field":1,"filemaker":1}
,"stripped":{"all":1}
,"all":{"leading":1}
,"leading":{"trailing":1}
,"trailing":{"spaces":1}
,"spaces":{"trim":1,"convert":1,"accidentally":1}
,"-any":{"text":1}
,"expression":{"text":1}
,"field":{"text":1,"remove":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"use":1}
,"use":{"function":1}
,"function":{"remove":1}
,"remove":{"unneeded":1,"spaces":1}
,"unneeded":{"spaces":1}
,"convert":{"files":1}
,"files":{"programs":1}
,"programs":{"systems":1}
,"systems":{"require":1}
,"require":{"fixed":1}
,"fixed":{"number":1}
,"number":{"characters":1}
,"characters":{"field":1}
,"accidentally":{"typed":1}
,"typed":{"during":1}
,"during":{"data":1}
,"data":{"entry":1}
,"entry":{"trim":1}
,"tom":{"returns":1,"trim":1}
,"middle":{"00230013":1}
,"00230013":{"william":1}
,"william":{"1234":1}
,"1234":{"returns":1}
}
;Search.control.loadWordPairs(pairs);
