var pairs =
{
"creating":{"nd":1}
,"nd":{"changing":1}
,"changing":{"relationships":1}
,"relationships":{"choose":1,"tab":1,"graph":1,"locate":1,"drag":1,"database":1}
,"choose":{"file":1}
,"file":{"menu":1}
,"menu":{"manage":1}
,"manage":{"database":1}
,"database":{"relationships":1,"deleting":1}
,"tab":{"relationships":1}
,"graph":{"locate":1,"graph":1,"order":1,"add":1,"select":1}
,"locate":{"two":1,"single":1}
,"two":{"tables":1}
,"tables":{"relationship":1,"hen":1,"option":1}
,"relationship":{"graph":1,"self-joining":1,"create":1,"drag":1,"button":1,"note":1,"change":1,"double-click":1,"option":1,"dialog":1,"criteria":1,"joining":1}
,"order":{"create":1,"fields":1,"want":1,"edit":1,"related":1,"lowest":1,"display":1}
,"create":{"relationship":1,"second":1,"new":1}
,"self-joining":{"relationships":1}
,"single":{"table":1,"line":1,"field":1,"value":1}
,"table":{"filemaker":1,"occurrence":1,"relationships":1,"button":1,"occurrences":1,"duplicate":1,"edit":1,"add":1,"table":1,"back":1,"rename":1,"enter":1,"select":1,"via":1,"delete":1,"record":1,"option":1,"display":1,"match":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"create":1,"match":1,"return":1,"treat":1}
,"second":{"table":1,"match":1}
,"occurrence":{"add":1,"accept":1}
,"add":{"table":1,"relationship":1,"match":1,"change":1,"related":1}
,"button":{"adding":1,"rename":1,"type":1,"relationship":1}
,"adding":{"selecting":1}
,"selecting":{"table":1,"option":1}
,"occurrences":{"duplicate":1}
,"duplicate":{"table":1,"delete":1}
,"select":{"table":1,"new":1,"paired":1,"allow":1,"delete":1,"sort":1,"options":1}
,"rename":{"duplicated":1,"new":1}
,"duplicated":{"table":1}
,"edit":{"button":1,"relationship":1}
,"type":{"new":1}
,"new":{"name":1,"relationship":1,"table":1,"match":1,"relational":1}
,"name":{"note":1,"repeat":1}
,"note":{"can\u2019t":1,"self-joining":1,"option":1}
,"can\u2019t":{"change":1}
,"change":{"tables":1,"settings":1,"add":1,"relational":1,"duplicate":1,"order":1,"sort":1}
,"drag":{"atch":1,"match":1,"fields":1}
,"atch":{"field":1}
,"field":{"match":1,"table":1,"current":1,"relationship":1,"select":1,"change":1,"record":1,"related":1,"layout":1,"separated":1,"complex":1,"simple":1,"each":1,"tablea":1,"single":1,"value":1}
,"match":{"field":1,"record":1}
,"current":{"table":1}
,"back":{"second":1}
,"accept":{"default":1}
,"default":{"name":1}
,"repeat":{"step":1}
,"step":{"each":1}
,"each":{"match":1,"table":1,"line":1}
,"settings":{"relationship":1}
,"double-click":{"indicator":1,"fields":1}
,"indicator":{"line":1}
,"line":{"related":1,"match":1,"separate":1}
,"related":{"tables":1,"record":1,"table":1,"field":1,"records":1,"data":1}
,"hen":{"change":1}
,"relational":{"operator":1}
,"operator":{"select":1,"rom":1}
,"rom":{"list":1}
,"list":{"change":1,"middle":1,"sort":1,"order":1}
,"delete":{"pair":1,"add":1,"related":1,"matching":1,"co":1}
,"pair":{"join":1}
,"join":{"criteria":1}
,"criteria":{"select":1,"list":1,"called":1}
,"paired":{"criteria":1}
,"middle":{"part":1}
,"part":{"dialog":1}
,"dialog":{"box":1}
,"box":{"duplicate":1,"double-click":1,"selecting":1}
,"record":{"related":1,"current":1,"creates":1,"based":1,"deleted":1,"table":1,"sort":1,"tableb":1}
,"enter":{"data":1}
,"data":{"related":1,"portals":1,"by":1}
,"allow":{"creation":1}
,"creation":{"records":1}
,"records":{"table":1,"related":1,"browsing":1,"note":1,"select":1,"left":1,"dialog":1,"display":1,"access":1,"sort":1,"tablea":1,"match":1}
,"via":{"relationship":1}
,"option":{"selected":1,"deletes":1,"enabled":1,"carefully":1,"affect":1}
,"selected":{"entering":1,"multiple":1}
,"entering":{"data":1,"multiple":1}
,"creates":{"related":1}
,"based":{"match":1,"contents":1}
,"matching":{"record":1,"values":1,"single":1}
,"deleted":{"table":1}
,"deletes":{"related":1}
,"browsing":{"layout":1}
,"layout":{"display":1,"current":1}
,"display":{"related":1,"first":1,"recent":1,"portal":1}
,"multiple":{"relationships":1,"records":1,"values":1}
,"deleting":{"record":1}
,"enabled":{"called":1}
,"called":{"cascading":1,"multi":1}
,"cascading":{"delete":1}
,"co":{"nsider":1}
,"nsider":{"option":1}
,"carefully":{"enabling":1}
,"enabling":{"sort":1}
,"sort":{"related":1,"records":1,"change":1,"order":1}
,"left":{"list":1}
,"fields":{"sort":1,"sorted":1,"right":1}
,"sorted":{"drag":1}
,"right":{"list":1}
,"want":{"select":1}
,"options":{"change":1}
,"affect":{"sort":1}
,"first":{"found":1}
,"found":{"record":1}
,"lowest":{"value":1}
,"value":{"related":1,"red":1}
,"recent":{"checkout":1}
,"checkout":{"date":1}
,"date":{"iece":1}
,"iece":{"equipment":1}
,"equipment":{"sort":1}
,"access":{"multiple":1,"related":1}
,"portal":{"orking":1}
,"orking":{"related":1}
,"portals":{"ou":1}
,"ou":{"increase":1}
,"increase":{"number":1}
,"number":{"matching":1}
,"values":{"by":1,"match":1,"separated":1}
,"by":{"entering":1,"carriage":1,"matching":1}
,"separated":{"by":1}
,"carriage":{"returns":1}
,"returns":{"access":1,"red":1,"filemaker":1}
,"multi":{"ey":1}
,"ey":{"field":1}
,"complex":{"key":1}
,"key":{"field":1}
,"simple":{"relationship":1}
,"joining":{"records":1}
,"tablea":{"tableb":1,"values":1}
,"tableb":{"based":1,"match":1}
,"contents":{"single":1}
,"red":{"green":1}
,"green":{"blue":1}
,"blue":{"filemaker":1,"carriage":1}
,"return":{"records":1}
,"treat":{"each":1}
,"separate":{"value":1}
}
;Search.control.loadWordPairs(pairs);
