var pairs =
{
"go":{"portal":1,"record\u002Frequest\u002Fpage":1,"field":1}
,"portal":{"row":1,"select":1,"active":1,"last":1,"previous":1,"next":1,"xit":1,"layout":1,"selected":1,"displays":1,"create":1,"go":1}
,"row":{"avigates":1,"if":1,"portal":1,"by":1,"number":1,"selected":1,"[select":1,"row":1,"[s":1}
,"avigates":{"rows":1}
,"rows":{"active":1,"if":1}
,"active":{"portal":1,"first":1,"script":1}
,"select":{"specifies":1}
,"specifies":{"elect":1}
,"elect":{"entire":1,"first":1}
,"entire":{"portal":1}
,"if":{"ield":1,"next":1,"set":1,"field":1}
,"ield":{"portal":1,"enter":1}
,"first":{"moves":1,"row":1,"portal":1,"ield":1,"loop":1}
,"moves":{"first":1,"last":1,"previous":1,"next":1,"row":1}
,"last":{"moves":1,"row":1,"xit":1,"portal":1,"loop":1,"off]":1,"allows":1,"on]":1}
,"previous":{"moves":1,"row":1,"selected":1}
,"next":{"moves":1,"row":1,"previous":1,"exit":1}
,"xit":{"last":1,"script":1}
,"script":{"reaches":1,"first":1,"step":1,"[indefinitely]":1}
,"reaches":{"last":1}
,"selected":{"use":1,"changing":1,"script":1,"portal":1,"server-side":1}
,"use":{"exit":1,"step":1}
,"exit":{"last":1,"loop":1}
,"loop":{"exit":1,"last":1,"go":1,"selecting":1}
,"by":{"calculation":1}
,"calculation":{"moves":1,"create":1,"option":1}
,"number":{"result":1,"confirmed":1}
,"result":{"calculation":1,"go":1}
,"create":{"row":1,"record":1}
,"confirmed":{"dialog":1}
,"dialog":{"box":1,"filemaker":1}
,"box":{"if":1}
,"set":{"dialog":1}
,"filemaker":{"pro":1,"webdirect":1,"data":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"portal":1}
,"layout":{"stacking":1}
,"stacking":{"order":1}
,"order":{"script":1}
,"step":{"keep":1,"elects":1,"move":1,"result":1}
,"keep":{"field":1}
,"field":{"selected":1,"portal":1,"second":1,"[related":1,"[select\u002Fperform":1}
,"changing":{"rows":1}
,"elects":{"first":1}
,"enter":{"field":1}
,"move":{"field":1}
,"second":{"portal":1}
,"[select":{"next":1,"last":1,"ext":1}
,"off]":{"field":1}
,"displays":{"records":1}
,"records":{"current":1}
,"current":{"table":1}
,"table":{"script":1}
,"record\u002Frequest\u002Fpage":{"filemaker":1}
,"webdirect":{"cursor":1}
,"cursor":{"moves":1}
,"server-side":{"scripts":1}
,"scripts":{"filemaker":1}
,"data":{"api":1}
,"api":{"nd":1}
,"nd":{"custom":1}
,"custom":{"web":1}
,"web":{"publishing":1}
,"publishing":{"support":1}
,"support":{"by":1}
,"option":{"last":1}
,"record":{"go":1}
,"[related":{"invoices":1}
,"invoices":{":summary]":1,":status]":1}
,":summary]":{"go":1}
,"allows":{"user":1}
,"user":{"batch":1}
,"batch":{"updates":1}
,"updates":{"status":1}
,"status":{"field":1}
,"[s":{"elect":1}
,"[select\u002Fperform":{"invoices":1}
,":status]":{"pause\u002Fresume":1}
,"pause\u002Fresume":{"script":1}
,"[indefinitely]":{"go":1}
,"ext":{"exit":1}
,"on]":{"end":1}
,"end":{"loop":1}
,"selecting":{"portals":1}
,"portals":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
