var pairs =
{
"orking":{"buttons":1}
,"buttons":{"button":1,"layout\u2019s":1,"create":1,"vertically":1,"popover":1}
,"button":{"bars":1,"perform":1,"simply":1,"performs":1,"by":1,"labels":1,"create":1,"displays":1,"bar":1}
,"bars":{"layouts":1}
,"layouts":{"use":1,"display":1}
,"use":{"button":1}
,"perform":{"filemaker":1,"command":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"command":1,"ile":1}
,"command":{"script":1}
,"script":{"define":1,"step":1,"finds":1,"include":1}
,"define":{"button":1,"individual":1}
,"simply":{"switches":1}
,"switches":{"layout":1}
,"layout":{"by":1,"script":1,"bjects":1}
,"by":{"go":1,"pressing":1}
,"go":{"layout":1}
,"step":{"define":1}
,"performs":{"complex":1}
,"complex":{"script":1}
,"finds":{"sorts":1}
,"sorts":{"prints":1}
,"prints":{"records":1}
,"records":{"transfers":1}
,"transfers":{"filemaker":1}
,"ile":{"browse":1}
,"browse":{"mode":1}
,"mode":{"find":1,"button":1}
,"find":{"mode":1}
,"include":{"buttons":1}
,"layout\u2019s":{"tab":1}
,"tab":{"order":1,"button":1}
,"order":{"allows":1,"data":1}
,"allows":{"tab":1}
,"pressing":{"space":1}
,"space":{"bar":1}
,"bar":{"setting":1,"define":1}
,"setting":{"tab":1}
,"data":{"entry":1}
,"entry":{"layout":1}
,"bjects":{"buttons":1}
,"create":{"custom":1,"popover":1,"button":1}
,"custom":{"buttons":1,"icons":1}
,"labels":{"contain":1}
,"contain":{"combination":1}
,"combination":{"text":1}
,"text":{"icons":1}
,"icons":{"including":1,"type":1}
,"including":{"custom":1}
,"type":{"button":1}
,"popover":{"button":1,"popovers":1,"buttons":1}
,"displays":{"popover":1}
,"popovers":{"layouts":1}
,"display":{"multiple":1}
,"multiple":{"buttons":1}
,"vertically":{"horizontally":1}
,"horizontally":{"create":1}
,"individual":{"segments":1}
,"segments":{"buttons":1}
}
;Search.control.loadWordPairs(pairs);
