var pairs =
{
"show":{"all":1}
,"all":{"records":1}
,"records":{"inds":1,"table":1,"found":1,"browse":1,"performs":1,"sort":1,"[restore":1,"if":1,"end":1}
,"inds":{"all":1}
,"table":{"underlying":1}
,"underlying":{"foreground":1}
,"foreground":{"window":1}
,"window":{"selects":1}
,"selects":{"current":1}
,"current":{"record":1}
,"record":{"none":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1,"advanced":1}
,"6.0":{"earlier":1}
,"earlier":{"use":1}
,"use":{"script":1,"show":1}
,"script":{"step":1}
,"step":{"redisplay":1,"find":1}
,"redisplay":{"all":1}
,"found":{"set":1,"invoices":1,"sorts":1}
,"set":{"use":1,"perform":1}
,"browse":{"mode":1}
,"mode":{"preview":1,"if":1,"layout":1,"filemaker":1,"records":1}
,"preview":{"mode":1}
,"if":{"perform":1,"records":1,"[get":1,"sort":1}
,"perform":{"script":1,"find":1}
,"find":{"mode":1,"all":1,"[restore]":1,"request":1}
,"layout":{"mode":1,"all":1,"[\u0022":1}
,"advanced":{"switches":1}
,"switches":{"browse":1}
,"invoices":{"layout":1}
,"performs":{"sort":1,"find":1}
,"sort":{"go":1,"records":1}
,"go":{"layout":1}
,"[\u0022":{"nvoices":1}
,"nvoices":{"\u0022]":1}
,"\u0022]":{"show":1}
,"[restore":{"dialog":1}
,"dialog":{"off]":1}
,"off]":{"performs":1,"aking":1}
,"sorts":{"found":1}
,"[restore]":{"if":1}
,"[get":{"foundcount":1}
,"foundcount":{"=0]":1}
,"=0]":{"show":1}
,"end":{"if":1}
,"aking":{"find":1}
,"request":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
