var pairs =
{
"ana":{"ing":1}
,"ing":{"performance":1}
,"performance":{"thumbnails":1,"change":1}
,"thumbnails":{"speed":1,"caches":1,"secure":1,"choose":1,"tab":1,"images":1,"temporary":1}
,"speed":{"up":1}
,"up":{"rendering":1}
,"rendering":{"images":1}
,"images":{"container":1,"option":1,"use":1}
,"container":{"fields":1,"data":1}
,"fields":{"filemaker":1,"managed":1,"set":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"by":1,"encrypts":1}
,"by":{"default":1}
,"default":{"generates":1,"if":1,"temporary":1}
,"generates":{"image":1}
,"image":{"thumbnails":1}
,"caches":{"memory":1,"in-memory":1,"on-disk":1}
,"memory":{"container":1}
,"data":{"embedded":1}
,"embedded":{"field":1,"full":1}
,"field":{"stored":1}
,"stored":{"externally":1}
,"externally":{"filemaker":1}
,"encrypts":{"thumbnails":1}
,"secure":{"storage":1}
,"storage":{"embedded":1,"options":1,"select":1,"default":1,"caches":1,"permanent":1,"slows":1,"remote":1}
,"full":{"access":1}
,"access":{"privileges":1}
,"privileges":{"set":1}
,"set":{"options":1,"thumbnail":1}
,"options":{"thumbnails":1,"thumbnail":1}
,"choose":{"file":1,"storage":1}
,"file":{"menu":1,"closed":1}
,"menu":{"manage":1}
,"manage":{"containers":1}
,"containers":{"thumbnails":1}
,"tab":{"select":1}
,"select":{"deselect":1,"temporary":1,"permanent":1}
,"deselect":{"generate":1,"option":1}
,"generate":{"store":1}
,"store":{"thumbnails":1}
,"option":{"selected":1,"skip":1}
,"selected":{"by":1}
,"if":{"deselect":1}
,"skip":{"step":1}
,"step":{"choose":1}
,"thumbnail":{"images":1,"options":1}
,"use":{"temporary":1}
,"temporary":{"storage":1}
,"in-memory":{"each":1,"on-disk":1}
,"each":{"time":1}
,"time":{"database":1}
,"database":{"file":1}
,"closed":{"cache":1,"generating":1}
,"cache":{"discarded":1,"remains":1}
,"discarded":{"permanent":1}
,"permanent":{"storage":1}
,"on-disk":{"addition":1,"portion":1}
,"addition":{"in-memory":1}
,"portion":{"cache":1}
,"remains":{"database":1}
,"generating":{"thumbnails":1}
,"slows":{"performance":1}
,"change":{"setting":1}
,"setting":{"permanent":1}
,"remote":{"container":1}
,"managed":{"container":1}
}
;Search.control.loadWordPairs(pairs);
