var pairs =
{
"managing":{"ernal":1}
,"ernal":{"storage":1}
,"storage":{"container":1,"tab":1}
,"container":{"data":1,"fields":1,"field":1}
,"data":{"each":1,"externally":1,"by":1,"transfers":1}
,"each":{"database":1,"base":1}
,"database":{"define":1,"set":1,"location":1,"change":1,"name":1,"hosted":1}
,"define":{"base":1}
,"base":{"directories":1,"directory":1}
,"directories":{"store":1,"full":1,"choose":1,"bottom":1}
,"store":{"container":1}
,"externally":{"default":1,"base":1}
,"default":{"location":1,"edit":1}
,"location":{"each":1,"add":1,"network":1}
,"directory":{"database\u2019s":1,"default":1,"can\u2019t":1,"container":1,"new":1,"dialog":1,"base":1,"absolute":1,"contain":1,"select":1,"list":1,"delete":1,"if":1,"filemaker":1,"colon":1,"\u002Finvoices\u002Finv_":1,"filenames":1}
,"database\u2019s":{"location":1}
,"add":{"edit":1}
,"edit":{"delete":1,"base":1,"edit":1}
,"delete":{"base":1,"list":1,"note":1}
,"full":{"access":1}
,"access":{"privileges":1}
,"privileges":{"create":1}
,"create":{"change":1,"edit":1,"new":1}
,"change":{"base":1,"path":1,"database":1}
,"choose":{"file":1}
,"file":{"menu":1}
,"menu":{"manage":1}
,"manage":{"containers":1}
,"containers":{"storage":1}
,"tab":{"displays":1,"create":1}
,"displays":{"base":1}
,"can\u2019t":{"delete":1}
,"list":{"storage":1,"edit":1,"delete":1,"if":1}
,"fields":{"database":1,"field":1,"managed":1,"create":1}
,"set":{"up":1}
,"up":{"subdirectories":1}
,"subdirectories":{"individual":1}
,"individual":{"container":1}
,"field":{"options":1,"stores":1}
,"options":{"create":1}
,"new":{"base":1,"new":1}
,"dialog":{"box":1}
,"box":{"type":1,"base":1,"change":1}
,"type":{"path":1}
,"path":{"base":1,"path":1,"relative":1,"examples":1,"treated":1}
,"absolute":{"path":1}
,"relative":{"database":1}
,"network":{"path":1}
,"examples":{"base":1}
,"bottom":{"dialog":1}
,"contain":{"references":1}
,"references":{"parent":1}
,"parent":{"folder":1}
,"folder":{"\u0022\u002F":1}
,"\u0022\u002F":{".\u002F\u0022":1}
,".\u002F\u0022":{"edit":1}
,"select":{"base":1}
,"note":{"delete":1}
,"if":{"data":1,"rename":1,"base":1,"directory":1,"database":1}
,"by":{"container":1}
,"stores":{"data":1}
,"transfers":{"pending":1}
,"pending":{"if":1}
,"rename":{"database":1}
,"name":{"base":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"automatically":1}
,"automatically":{"update":1}
,"update":{"database":1}
,"colon":{"last":1}
,"last":{"part":1}
,"part":{"path":1}
,"treated":{"prefix":1}
,"prefix":{"filenames":1}
,"filenames":{"if":1,"inv_prefix":1}
,"\u002Finvoices\u002Finv_":{"all":1}
,"all":{"invoices":1}
,"invoices":{"stored":1,"directory":1}
,"stored":{"invoices":1}
,"inv_prefix":{"create":1}
,"hosted":{"computer":1}
,"computer":{"remote":1}
,"remote":{"container":1}
,"managed":{"container":1}
}
;Search.control.loadWordPairs(pairs);
