var pairs =
{
"up":{"routine":1,"database":1,"data":1,"consistent":1,"copying":1,"set":1}
,"routine":{"backups":1}
,"backups":{"recommended":1,"accomplish":1,"exist":1,"off-site":1}
,"recommended":{"document":1}
,"document":{"stored":1}
,"stored":{"computer":1,"backup":1}
,"computer":{"magnetic":1}
,"magnetic":{"media":1,"fields":1,"storage":1}
,"media":{"susceptible":1,"careful":1,"easier":1,"up":1,"simplest":1}
,"susceptible":{"variety":1}
,"variety":{"problems":1}
,"problems":{"storage":1}
,"storage":{"device":1,"media":1}
,"device":{"hard":1}
,"hard":{"disk":1}
,"disk":{"sole":1,"removable":1,"tape":1,"safekeeping":1}
,"sole":{"repository":1}
,"repository":{"data":1}
,"data":{"extreme":1,"day":1,"adding":1}
,"extreme":{"heat":1}
,"heat":{"cold":1}
,"cold":{"sunlight":1}
,"sunlight":{"presence":1}
,"presence":{"electric":1}
,"electric":{"magnetic":1}
,"fields":{"all":1}
,"all":{"contribute":1}
,"contribute":{"failure":1}
,"failure":{"magnetic":1,"single":1}
,"careful":{"backup":1}
,"backup":{"strategy":1,"third-party":1,"program":1,"copies":1,"database":1,"file":1,"folder":1}
,"strategy":{"include":1,"employs":1}
,"include":{"optical":1}
,"optical":{"magnetic":1}
,"easier":{"back":1}
,"back":{"up":1}
,"database":{"re-create":1,"sources":1,"sure":1,"file":1}
,"re-create":{"back":1,"files":1}
,"day":{"times":1,"new":1,"two":1,"week":1,"first":1}
,"times":{"week":1}
,"week":{"less":1,"eleventh":1}
,"less":{"frequently":1,"two-week":1}
,"frequently":{"usually":1}
,"usually":{"determined":1}
,"determined":{"by":1}
,"by":{"data":1}
,"adding":{"databases":1}
,"databases":{"difficult":1}
,"difficult":{"re-create":1}
,"files":{"event":1,"disk":1,"larger":1,"it\u2019s":1,"off-site":1}
,"event":{"corrupted":1}
,"corrupted":{"strong":1}
,"strong":{"backup":1}
,"employs":{"multiple":1}
,"multiple":{"media":1,"copies":1}
,"consistent":{"schedule":1}
,"schedule":{"affords":1}
,"affords":{"protection":1}
,"protection":{"failure":1}
,"single":{"hard":1}
,"removable":{"disk":1}
,"tape":{"media":1}
,"simplest":{"form":1}
,"form":{"up":1}
,"copying":{"files":1}
,"safekeeping":{"files":1}
,"larger":{"numerous":1}
,"numerous":{"use":1}
,"use":{"third-party":1,"filemaker":1}
,"third-party":{"program":1,"backup":1}
,"program":{"proper":1,"provide":1}
,"proper":{"backup":1}
,"provide":{"multiple":1}
,"copies":{"database":1,"less":1,"vital":1}
,"sources":{"restoration":1}
,"restoration":{"scheme":1,"files":1}
,"scheme":{"involving":1}
,"involving":{"rotating":1}
,"rotating":{"backups":1}
,"accomplish":{"typically":1}
,"typically":{"method":1}
,"method":{"involves":1}
,"involves":{"separate":1}
,"separate":{"backup":1}
,"two-week":{"rotation":1}
,"rotation":{"file":1,"ensures":1}
,"file":{"backed":1,"restoration":1,"want":1,"unchanged":1,"backup":1,"stored":1}
,"backed":{"up":1}
,"set":{"day":1,"reused":1}
,"new":{"set":1}
,"two":{"sets":1}
,"sets":{"backups":1}
,"exist":{"assuming":1}
,"assuming":{"day":1}
,"eleventh":{"day":1}
,"first":{"set":1}
,"reused":{"type":1}
,"type":{"rotation":1}
,"ensures":{"lurking":1}
,"lurking":{"problem":1}
,"problem":{"spoil":1}
,"spoil":{"chances":1}
,"chances":{"complete":1}
,"complete":{"file":1}
,"it\u2019s":{"idea":1}
,"idea":{"store":1}
,"store":{"backups":1}
,"off-site":{"location":1,"avoid":1}
,"location":{"fires":1}
,"fires":{"earthquakes":1}
,"earthquakes":{"disasters":1}
,"disasters":{"occur":1}
,"occur":{"safety":1}
,"safety":{"securing":1}
,"securing":{"copies":1}
,"vital":{"files":1}
,"avoid":{"damaging":1}
,"damaging":{"backup":1}
,"sure":{"copy":1}
,"copy":{"database":1}
,"want":{"restore":1}
,"restore":{"leave":1}
,"leave":{"original":1}
,"original":{"backup":1}
,"unchanged":{"backup":1}
,"folder":{"move":1,"use":1}
,"move":{"database":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"open":1}
,"open":{"database":1}
}
;Search.control.loadWordPairs(pairs);
