var pairs =
{
"open":{"upload":1}
,"upload":{"host":1,"filemaker":1,"database":1}
,"host":{"pens":1,"ialog":1,"automating":1}
,"pens":{"upload":1}
,"ialog":{"box":1}
,"box":{"none":1,"users":1,"if":1,"show":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1,"server":1,"host":1}
,"pro":{"13.0":1,"advanced":1}
,"13.0":{"script":1}
,"script":{"step":1}
,"step":{"choosing":1,"open":1}
,"choosing":{"file":1}
,"file":{"menu":1}
,"menu":{"sharing":1}
,"sharing":{"upload":1}
,"server":{"use":1,"dialog":1,"upload":1,"\u0022]":1,"end":1}
,"use":{"script":1}
,"dialog":{"box":1,"[\u0022":1}
,"users":{"if":1}
,"if":{"restricted":1,"user":1,"[get":1,"up":1}
,"restricted":{"access":1}
,"access":{"filemaker":1}
,"advanced":{"menus":1}
,"menus":{"displays":1}
,"displays":{"custom":1}
,"custom":{"dialog":1}
,"user":{"upload":1}
,"database":{"filemaker":1}
,"show":{"custom":1}
,"[\u0022":{"want":1}
,"want":{"upload":1}
,"\u0022]":{"if":1}
,"[get":{"lastmessagechoice":1}
,"lastmessagechoice":{"=1]":1}
,"=1]":{"upload":1}
,"end":{"if":1}
,"up":{"adi":1}
,"adi":{"ng":1}
,"ng":{"files":1}
,"files":{"filemaker":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
