var pairs =
{
"base64encoderfc":{"returns":1,"rfcnumber":1,"4648":1,"1421":1}
,"returns":{"data":1,"base64encoderfc":1,"qmxhy2s=when":1,"string":1}
,"data":{"text":1,"rfcnumber":1,"-any":1}
,"text":{"base64":1,"expression":1,"filemaker":1,"if":1,"1421":1}
,"base64":{"format":1}
,"format":{"base64encoderfc":1,"use":1}
,"rfcnumber":{"data":1,"-a":1,"parameter":1,"encodes":1}
,"-a":{"number":1}
,"number":{"representing":1}
,"representing":{"ietf":1}
,"ietf":{"rfc":1}
,"rfc":{"standard":1,"4648":1}
,"standard":{"base64":1,"follow":1}
,"use":{"data":1,"rfcnumber":1,"values":1,"unrecognized":1}
,"-any":{"text":1}
,"expression":{"field":1}
,"field":{"text":1}
,"filemaker":{"pro":1}
,"pro":{"16.0":1}
,"16.0":{"function":1}
,"function":{"base64encode":1,"defaults":1,"supported":1}
,"base64encode":{"except":1}
,"except":{"formatting":1}
,"formatting":{"use":1,"base64-encoded":1}
,"parameter":{"use":1}
,"values":{"rfc":1}
,"follow":{"formatting":1}
,"base64-encoded":{"text":1}
,"if":{"use":1}
,"unrecognized":{"value":1}
,"value":{"function":1}
,"defaults":{"rfc":1}
,"4648":{"rfcnumber":1,"line":1,"products":1}
,"encodes":{"text":1}
,"1421":{"maximum":1,"products":1}
,"maximum":{"line":1}
,"line":{"length":1,"feed":1,"endings":1,"breaks":1,"products":1,"carriage":1}
,"length":{"64":1,"76":1}
,"64":{"crlf":1}
,"crlf":{"carriage":1,"line":1}
,"carriage":{"return":1}
,"return":{"line":1}
,"feed":{"line":1,"characters":1}
,"endings":{"2045":1,"3548":1,"appended":1}
,"2045":{"maximum":1}
,"76":{"crlf":1}
,"3548":{"line":1}
,"breaks":{"4648":1,"4880":1}
,"4880":{"maximum":1}
,"appended":{"24-bit":1}
,"24-bit":{"crc":1}
,"crc":{"value":1}
,"supported":{"runtime":1}
,"runtime":{"solutions":1}
,"solutions":{"returns":1}
,"products":{":color":1,":container":1}
,":color":{"returns":1,"set":1}
,"qmxhy2s=when":{"products":1}
,"set":{"black":1,"help":1}
,"black":{"base64encoderfc":1}
,":container":{"returns":1,"set":1}
,"string":{"first":1}
,"first":{"line":1}
,"help":{"button":1}
,"button":{"ivborw0kggoaaaansuheugaaab8aaaarcayaaaalphdjaaaaaxnsr0iars4c6qaa":1}
,"ivborw0kggoaaaansuheugaaab8aaaarcayaaaalphdjaaaaaxnsr0iars4c6qaa":{"each":1}
,"each":{"64-character":1}
,"64-character":{"line":1}
}
;Search.control.loadWordPairs(pairs);
