var pairs =
{
"spelling":{"options":1,"tab":1,"type":1}
,"options":{"pens":1,"dialog":1,"spelling":1,"end":1,"automating":1}
,"pens":{"file":1}
,"file":{"options":1,"menu":1}
,"dialog":{"box":1,"[\u0022":1}
,"box":{"spelling":1,"users":1,"if":1}
,"tab":{"none":1,"use":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1,"advanced":1}
,"6.0":{"earlier":1}
,"earlier":{"script":1}
,"script":{"step":1}
,"step":{"choosing":1,"open":1}
,"choosing":{"file":1}
,"menu":{"file":1}
,"use":{"script":1}
,"open":{"file":1}
,"users":{"if":1}
,"if":{"restricted":1,"user":1,"[get":1,"etting":1}
,"restricted":{"access":1}
,"access":{"filemaker":1}
,"advanced":{"menus":1}
,"menus":{"displays":1}
,"displays":{"custom":1}
,"custom":{"dialog":1}
,"user":{"beep":1}
,"beep":{"questionable":1}
,"questionable":{"spellings":1}
,"spellings":{"option":1}
,"option":{"show":1}
,"show":{"custom":1}
,"[\u0022":{"check":1}
,"check":{"spelling":1}
,"type":{"\u0022]":1}
,"\u0022]":{"if":1}
,"[get":{"lastmessagechoice":1}
,"lastmessagechoice":{"=1]":1}
,"=1]":{"spelling":1}
,"end":{"if":1}
,"etting":{"file":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
