var pairs =
{
"script":{"workspace":1,"steps":1,"command":1,"new":1,"use":1,"editing":1,"step":1,"script":1}
,"workspace":{"eyboard":1,"create":1,"command":1}
,"eyboard":{"shortcuts":1}
,"shortcuts":{"mac":1,"script":1,"debug":1}
,"mac":{"os":1}
,"os":{"use":1}
,"use":{"hese":1,"advanced":1}
,"hese":{"keyboard":1}
,"keyboard":{"shortcuts":1}
,"create":{"edit":1,"new":1}
,"edit":{"scripts":1}
,"scripts":{"note":1,"disable":1,"debug":1}
,"note":{"keyboard":1}
,"debug":{"scripts":1,"selected":1}
,"disable":{"script":1,"selected":1}
,"steps":{"use":1}
,"advanced":{"tools":1}
,"tools":{"general":1,"press":1,"selected":1}
,"general":{"preference":1}
,"preference":{"selected":1}
,"selected":{"ad":1,"script":1,"command":1}
,"ad":{"vanced":1}
,"vanced":{"tools":1}
,"press":{"create":1}
,"new":{"script":1,"tab":1,"window":1}
,"command":{"-n":1,"-s":1,"-t":1,"-shift-t":1,"-r":1,"-option-r":1,"-shift-r":1,"-shift-option-r":1,"-w":1,"-option-w":1,"-shift-w":1,"-shift-}":1,"-shift-{":1,"-control-up":1,"-control-down":1,"-d":1,"-\u002Fprint":1,"-p":1}
,"-n":{"save":1}
,"save":{"script":1,"run":1,"all":1}
,"-s":{"open":1}
,"open":{"selected":1}
,"tab":{"command":1,"script":1,"shift-tab":1}
,"-t":{"open":1}
,"window":{"command":1}
,"-shift-t":{"run":1}
,"run":{"selected":1}
,"-r":{"save":1}
,"-option-r":{"debug":1}
,"-shift-r":{"save":1}
,"all":{"scripts":1,"tabs":1,"script":1}
,"-shift-option-r":{"close":1}
,"close":{"current":1,"all":1,"script":1}
,"current":{"tab":1}
,"-w":{"close":1}
,"tabs":{"command":1}
,"-option-w":{"close":1}
,"-shift-w":{"move":1}
,"move":{"next":1,"previous":1,"selected":1,"options":1}
,"next":{"tab":1}
,"editing":{"pane":1}
,"pane":{"command":1,"left":1}
,"-shift-}":{"move":1}
,"previous":{"tab":1}
,"-shift-{":{"move":1}
,"step":{"up":1,"options":1,"option":1,"delete":1,"command":1,"use":1}
,"up":{"script":1}
,"-control-up":{"arrow":1}
,"arrow":{"command":1,"add":1,"right":1,"tab":1}
,"-control-down":{"arrow":1}
,"add":{"comment":1}
,"comment":{"blank":1}
,"blank":{"line":1}
,"line":{"display":1}
,"display":{"script":1}
,"options":{"plus":1,"brackets":1,"esc":1}
,"plus":{"move":1}
,"brackets":{"script":1}
,"left":{"arrow":1}
,"right":{"arrow":1}
,"shift-tab":{"select":1}
,"select":{"script":1}
,"option":{"hen":1}
,"hen":{"focus":1}
,"focus":{"pace":1,"all":1}
,"pace":{"bar":1}
,"bar":{"remove":1}
,"remove":{"focus":1}
,"esc":{"delete":1}
,"delete":{"selected":1,"backspace":1}
,"backspace":{"duplicate":1}
,"duplicate":{"selected":1}
,"-d":{"disable":1}
,"-\u002Fprint":{"selected":1}
}
;Search.control.loadWordPairs(pairs);
