var pairs =
{
"getasboolean":{"returns":1,"data":1,"evaluates":1,"text":1,"container":1}
,"returns":{"true":1,"false":1,"boolean":1,"getasboolean":1,"field":1,"container":1}
,"true":{"if":1,"getasboolean":1}
,"if":{"data":1}
,"data":{"converts":1,"returns":1,"data":1,"-any":1}
,"converts":{"non-zero":1}
,"non-zero":{"numeric":1}
,"numeric":{"value":1}
,"value":{"container":1,"expression":1}
,"container":{"field":1,"expression":1,"number":1}
,"field":{"holds":1,"text":1,"returns":1,"named":1,"data":1,"empty":1}
,"holds":{"data":1}
,"false":{"getasboolean":1}
,"-any":{"text":1}
,"text":{"number":1,"returns":1}
,"number":{"date":1,"filemaker":1}
,"date":{"time":1}
,"time":{"timestamp":1}
,"timestamp":{"container":1}
,"expression":{"field":1,"error":1}
,"filemaker":{"pro":1}
,"pro":{"8.0":1}
,"8.0":{"returns":1}
,"boolean":{"value":1}
,"error":{"returns":1}
,"evaluates":{"true":1}
,"named":{"container":1}
}
;Search.control.loadWordPairs(pairs);
