var pairs =
{
"tableids":{"eturns":1,"filename":1,"university":1}
,"eturns":{"list":1}
,"list":{"all":1}
,"all":{"table":1}
,"table":{"occurrence":1,"occurrences":1}
,"occurrence":{"ds":1,"id":1,"first":1,"middle":1}
,"ds":{"filename":1}
,"filename":{"tableids":1,"filename":1,"-the":1}
,"-the":{"name":1}
,"name":{"open":1}
,"open":{"database":1}
,"database":{"file":1,"returns":1,"database":1}
,"file":{"local":1,"if":1}
,"local":{"remote":1}
,"remote":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"ach":1}
,"ach":{"value":1}
,"value":{"nique":1,"listed":1}
,"nique":{"identifies":1}
,"identifies":{"table":1}
,"id":{"independent":1}
,"independent":{"create":1}
,"create":{"each":1}
,"each":{"table":1}
,"first":{"table":1}
,"middle":{"largest":1}
,"largest":{"value":1}
,"listed":{"items":1}
,"items":{"separated":1}
,"separated":{"by":1}
,"by":{"carriage":1}
,"carriage":{"returns":1}
,"returns":{"tableids":1,"1065089":1}
,"university":{"database":1}
,"1065089":{"1065090":1}
,"1065090":{"university":1}
,"if":{"two":1}
,"two":{"table":1}
,"occurrences":{"defined":1}
,"defined":{"file":1}
}
;Search.control.loadWordPairs(pairs);
