var pairs =
{
"cationvalues":{"eturns":1}
,"eturns":{"current":1}
,"current":{"latitude":1,"location":1}
,"latitude":{"longitude":1}
,"longitude":{"altitude":1}
,"altitude":{"ios":1,"meters":1}
,"ios":{"device":1}
,"device":{"running":1,"format":1,"37.406489":1}
,"running":{"filemaker":1}
,"filemaker":{"go":1,"pro":1,"returns":1}
,"go":{"accuracy":1,"returns":1}
,"accuracy":{"minutes":1,"timeout":1,"-any":1,"values":1,"+\u002F-accuracy":1,"met":1,"number":1}
,"minutes":{"values":1,"0.2":1,"12":1}
,"values":{"returned":1,"locationvalues":1,"requested":1}
,"returned":{"locationvalues":1,"number":1,"location":1,"value":1}
,"locationvalues":{"accuracy":1,"fetches":1,"returns":1,"100":1}
,"timeout":{"accuracy":1,"-any":1,"if":1,"locationvalues":1}
,"-any":{"numeric":1}
,"numeric":{"expression":1}
,"expression":{"field":1}
,"field":{"number":1}
,"number":{"represents":1,"minutes":1,"accuracy":1,"timeout":1}
,"represents":{"distance":1,"time":1}
,"distance":{"meters":1}
,"meters":{"timeout":1,"horizontal":1,"vertical":1,"age":1}
,"time":{"take":1}
,"take":{"fetch":1}
,"fetch":{"location":1}
,"location":{"measured":1,"via":1,"device":1,"values":1,"cache":1,"received":1}
,"measured":{"seconds":1}
,"seconds":{"default":1,"use":1}
,"default":{"value":1}
,"value":{"60":1,"minutes":1,"except":1}
,"60":{"parameters":1}
,"parameters":{"braces":1}
,"braces":{"optional":1}
,"optional":{"text":1}
,"text":{"filemaker":1}
,"pro":{"12.0":1,"advanced":1}
,"12.0":{"function":1}
,"function":{"returns":1,"retrieve":1}
,"returns":{"current":1,"horizontal":1,"caches":1,"accurate":1,"empty":1,"location":1}
,"horizontal":{"vertical":1,"accuracy":1}
,"vertical":{"accuracy":1}
,"via":{"gps":1}
,"gps":{"cellular":1}
,"cellular":{"network":1}
,"network":{"wi-fi":1,"filemaker":1}
,"wi-fi":{"returns":1}
,"caches":{"current":1}
,"format":{"latitude":1}
,"+\u002F-accuracy":{"meters":1}
,"age":{"value":1}
,"0.2":{"represent":1,"minutes":1}
,"represent":{"0.2":1}
,"12":{"seconds":1}
,"use":{"getvalue":1}
,"getvalue":{"function":1}
,"retrieve":{"carriage":1}
,"carriage":{"return-delimited":1,"return":1}
,"return-delimited":{"values":1}
,"fetches":{"location":1,"larger":1}
,"requested":{"accuracy":1}
,"met":{"timeout":1}
,"if":{"cancel":1,"if":1,"location":1}
,"cancel":{"process":1}
,"process":{"filemaker":1}
,"accurate":{"location":1}
,"cache":{"if":1}
,"received":{"filemaker":1}
,"empty":{"string":1}
,"string":{"filemaker":1,"each":1}
,"advanced":{"locationvalues":1}
,"each":{"returned":1}
,"except":{"last":1}
,"last":{"carriage":1}
,"return":{"avoid":1}
,"avoid":{"excessive":1}
,"excessive":{"battery":1}
,"battery":{"consumption":1}
,"consumption":{"repeat":1}
,"repeat":{"fetches":1}
,"larger":{"number":1}
,"100":{"40":1}
,"40":{"returns":1}
,"37.406489":{"-121.983428":1}
,"-121.983428":{"0.0545050":1}
,"0.0545050":{"65":1}
,"65":{"10":1}
,"10":{"0.001236":1}
,"0.001236":{"mobile":1}
,"mobile":{"phone":1,"network":1}
,"phone":{"cell":1,"mobile":1}
,"cell":{"phone":1}
}
;Search.control.loadWordPairs(pairs);
