var pairs =
{
"relationinfo":{"eturns":1,"filename":1,"human":1}
,"eturns":{"list":1}
,"list":{"values":1,"separated":1,"defined":1}
,"values":{"each":1,"list":1,"output":1,"source":1}
,"each":{"relationship":1,"additional":1}
,"relationship":{"related":1,"onnected":1,"dialog":1,"defined":1,"selected":1,"relationinfo":1}
,"related":{"tablename":1,"records":1}
,"tablename":{"relationinfo":1,"filename":1,"-the":1,"additional":1,"table":1,"options":1,":field":1}
,"filename":{"tablename":1,"-the":1}
,"-the":{"name":1}
,"name":{"open":1,"table":1,"database":1}
,"open":{"database":1}
,"database":{"file":1,"table":1}
,"file":{"local":1,"text":1,"called":1}
,"local":{"remote":1}
,"remote":{"tablename":1}
,"table":{"database":1,"connected":1,"name":1,"record":1,"selected":1,"via":1,"employees":1,"company":1,"addresses":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"values":1}
,"separated":{"by":1}
,"by":{"carriage":1,"two":1,"spaces":1}
,"carriage":{"returns":1}
,"returns":{"lists":1,"each":1,"source":1}
,"lists":{"separated":1}
,"two":{"carriage":1}
,"additional":{"relationship":1,"list":1}
,"onnected":{"tablename":1}
,"output":{"values":1}
,"source":{"data":1,"name":1,"human":1}
,"data":{"source":1}
,"connected":{"tablename":1,"employees":1,"addresses":1}
,"options":{"options":1,"set":1,"separated":1,"create":1}
,"set":{"right":1,"options":1}
,"right":{"edit":1}
,"edit":{"relationship":1}
,"dialog":{"box":1}
,"box":{"relationship":1,"create":1,"sorted":1,"relationships":1}
,"defined":{"line":1,"relationships":1}
,"line":{"blank":1,"field":1}
,"blank":{"if":1}
,"if":{"options":1,"delete":1,"allow":1,"sort":1}
,"spaces":{"delete":1}
,"delete":{"if":1,"related":1,"records":1}
,"records":{"table":1,"selected":1,"all":1}
,"record":{"deleted":1}
,"deleted":{"table":1}
,"selected":{"right":1}
,"create":{"if":1,"records":1,"company":1,"sorted":1}
,"allow":{"creation":1}
,"creation":{"records":1}
,"via":{"relationship":1}
,"sorted":{"if":1,"addresses":1}
,"sort":{"records":1,"addresses":1}
,"relationships":{"list":1,"line":1,"criteria":1}
,"field":{"names":1}
,"names":{"qualified":1}
,"qualified":{"tablename":1}
,":field":{"name":1}
,"called":{"human":1}
,"human":{"resources":1}
,"resources":{"tables":1,"employees":1,"table":1}
,"tables":{"company":1,"delete":1,"sort":1}
,"company":{"employees":1,":company":1,"options":1}
,"employees":{"addresses":1,":company":1,":employee":1,":dateofhire":1,"<-->":1,"returns":1}
,"addresses":{"company":1,":employee":1,":datemovedin":1,"table":1,"relationship":1,"options":1}
,":company":{"id":1}
,"id":{"connected":1,"employees":1,"=employees":1,"source":1,"addresses":1}
,":employee":{"id":1}
,":dateofhire":{"connected":1}
,":datemovedin":{"relationships":1,">=employees":1}
,"criteria":{"create":1}
,"all":{"tables":1}
,"<-->":{"addresses":1}
,"=employees":{":company":1,":employee":1}
,">=employees":{":dateofhire":1}
}
;Search.control.loadWordPairs(pairs);
