var pairs =
{
"recover":{"file":1,"command":1,"damaged":1,"database":1}
,"file":{"ecovers":1,"dialog":1,"specifies":1,"recovered":1,"paths":1,"open":1,"intended":1,"repair":1,"maintenance":1,"creates":1,"original":1,"deleted":1,"if":1,"usable":1,"[open":1,"[with":1}
,"ecovers":{"damaged":1}
,"damaged":{"filemaker":1,"file":1,"open":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1,"6.0":1}
,"advanced":{"file":1,"recovery":1,"attempts":1}
,"dialog":{"specifies":1,"box":1,"applies":1,"invoices":1}
,"specifies":{"display":1,"file":1}
,"display":{"dialog":1}
,"box":{"script":1,"supported":1,"displays":1}
,"script":{"step":1}
,"step":{"performed":1}
,"performed":{"bytes":1}
,"bytes":{"data":1}
,"data":{"recovered":1,"recovery":1}
,"recovered":{"number":1,"setting":1,"creating":1,"file":1}
,"number":{"records":1,"field":1}
,"records":{"field":1}
,"field":{"values":1,"definitions":1}
,"values":{"skipped":1}
,"skipped":{"number":1}
,"definitions":{"recovered":1}
,"setting":{"dialog":1}
,"applies":{"default":1}
,"default":{"recovery":1}
,"recovery":{"operations":1,"options":1,"file":1}
,"operations":{"advanced":1}
,"options":{"dialog":1}
,"supported":{"output":1}
,"output":{"file":1}
,"creating":{"file":1}
,"paths":{"if":1}
,"if":{"don\u2019t":1,"space":1,"damaged":1,"[get":1,"recovering":1}
,"don\u2019t":{"select":1}
,"select":{"source":1}
,"source":{"file":1}
,"open":{"damaged":1,"file":1}
,"displays":{"runtime":1}
,"runtime":{"filemaker":1}
,"6.0":{"earlier":1}
,"earlier":{"recover":1}
,"command":{"aggressive":1,"part":1}
,"aggressive":{"attempt":1}
,"attempt":{"reopen":1}
,"reopen":{"damaged":1}
,"intended":{"data":1}
,"repair":{"use":1}
,"use":{"recover":1}
,"part":{"routine":1}
,"routine":{"file":1}
,"maintenance":{"filemaker":1}
,"attempts":{"recover":1}
,"creates":{"new":1}
,"new":{"recovered":1}
,"original":{"file":1}
,"deleted":{"replaced":1}
,"replaced":{"sure":1}
,"sure":{"disk":1}
,"disk":{"space":1}
,"space":{"recovered":1}
,"usable":{"invoices":1}
,"invoices":{"backup":1,"backup.fmp12":1}
,"backup":{"attempts":1,"\u0022]":1}
,"database":{"if":1}
,"[open":{"hidden":1}
,"hidden":{"invoices":1}
,"\u0022]":{"if":1,"end":1}
,"[get":{"lasterror":1}
,"lasterror":{"=807]":1}
,"=807]":{"recover":1}
,"[with":{"dialog":1}
,"backup.fmp12":{"\u0022]":1}
,"end":{"if":1}
,"recovering":{"files":1}
,"files":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
