var pairs =
{
"open":{"record\u002Frequest":1,"window":1,"record":1}
,"record\u002Frequest":{"akes":1,"script":1,"if":1}
,"akes":{"existing":1}
,"existing":{"record":1,"find":1}
,"record":{"find":1,"browse":1,"script":1,"if":1,"locked":1,"considered":1,"currently":1,"open":1,"attempt":1,"editing":1,"explicitly":1,"use":1,"set":1,"want":1}
,"find":{"request":1,"mode":1}
,"request":{"editing":1,"find":1,"return":1,"automating":1}
,"editing":{"if":1,"deleting":1,"cases":1}
,"if":{"current":1,"user":1,"error":1,"[get":1,"go":1,"if":1,"set":1,"end":1,"viewing":1}
,"current":{"user":1,"invoice":1}
,"user":{"record-editing":1,"sufficient":1,"proper":1,"insufficient":1,"record":1,"privileges":1,"account":1,"log":1}
,"record-editing":{"privileges":1}
,"privileges":{"none":1,"performed":1,"edit":1,"record":1,"allows":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1,"advanced":1}
,"6.0":{"earlier":1}
,"earlier":{"script":1}
,"script":{"step":1,"run":1}
,"step":{"existing":1,"verifies":1,"get":1,"open":1,"enter":1,"first":1}
,"browse":{"mode":1}
,"mode":{"existing":1,"editing":1}
,"performed":{"record":1}
,"verifies":{"user":1}
,"sufficient":{"access":1}
,"access":{"privileges":1}
,"edit":{"record":1,"go":1,"records":1}
,"proper":{"privilege":1}
,"privilege":{"set":1,"edit":1}
,"set":{"filemaker":1,"error":1,"run":1}
,"advanced":{"attempts":1,"generates":1}
,"attempts":{"prevent":1}
,"prevent":{"simultaneously":1}
,"simultaneously":{"editing":1}
,"deleting":{"record":1}
,"locked":{"record":1,"by":1}
,"considered":{"pened":1}
,"pened":{"nd":1}
,"nd":{"edited":1}
,"edited":{"if":1}
,"error":{"occurs":1,"message":1,"capture":1,"requests":1}
,"occurs":{"if":1}
,"insufficient":{"access":1}
,"currently":{"locked":1}
,"by":{"user":1,"users":1}
,"window":{"filemaker":1}
,"generates":{"error":1}
,"message":{"captured":1}
,"captured":{"set":1}
,"capture":{"script":1,"[on]":1}
,"get":{"lasterror":1}
,"lasterror":{"function":1,"=0]":1,"=200]":1}
,"function":{"find":1}
,"return":{"error":1}
,"requests":{"can\u2019t":1}
,"can\u2019t":{"locked":1}
,"users":{"attempt":1}
,"attempt":{"modify":1,"open":1}
,"modify":{"field":1}
,"field":{"record":1}
,"cases":{"use":1}
,"use":{"open":1}
,"explicitly":{"go":1}
,"go":{"record\u002Frequest\u002Fpage":1,"layout":1}
,"record\u002Frequest\u002Fpage":{"script":1}
,"enter":{"field":1}
,"first":{"obtain":1}
,"obtain":{"write":1}
,"write":{"lock":1}
,"lock":{"prints":1}
,"prints":{"current":1}
,"invoice":{"if":1,"details":1}
,"layout":{"[\u0022":1,"[original":1}
,"[\u0022":{"print":1,"invoice":1,"edit":1}
,"print":{"invoices":1,"[with":1}
,"invoices":{"\u0022]":1}
,"\u0022]":{"open":1,"if":1}
,"[get":{"lasterror":1,"lastmessagechoice":1}
,"=0]":{"print":1}
,"[with":{"dialog":1}
,"dialog":{"on]":1,"[\u0022":1}
,"on]":{"end":1,"else":1}
,"end":{"if":1}
,"[original":{"layout]":1}
,"layout]":{"checks":1,"end":1}
,"checks":{"if":1}
,"account":{"privilege":1,"note":1,"open":1}
,"records":{"if":1,"form":1}
,"log":{"account":1}
,"note":{"script":1}
,"run":{"properly":1,"full":1}
,"properly":{"if":1}
,"full":{"access":1}
,"allows":{"account":1}
,"[on]":{"go":1}
,"details":{"\u0022]":1}
,"=200]":{"show":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"want":{"re-login":1}
,"re-login":{"\u0022]":1,"[with":1}
,"lastmessagechoice":{"=1]":1}
,"=1]":{"re-login":1}
,"else":{"go":1}
,"viewing":{"records":1}
,"form":{"list":1}
,"list":{"table":1}
,"table":{"aking":1}
,"aking":{"find":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
