var pairs =
{
"select":{"all":1,"contents":1}
,"all":{"elects":1,"end":1}
,"elects":{"entire":1}
,"entire":{"contents":1}
,"contents":{"active":1}
,"active":{"field":1}
,"field":{"none":1,"show":1,"\u0022]":1,"browse":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1,"go":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"filemaker":1}
,"go":{"script":1}
,"script":{"step":1}
,"step":{"highlight":1}
,"highlight":{"text":1}
,"text":{"if":1}
,"if":{"keyboard":1,"[get":1,"selecting":1}
,"keyboard":{"hidden":1}
,"hidden":{"device":1}
,"device":{"selects":1}
,"selects":{"contents":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"dialog":{"[\u0022":1}
,"[\u0022":{"want":1}
,"want":{"select":1}
,"\u0022]":{"if":1}
,"[get":{"lastmessagechoice":1}
,"lastmessagechoice":{"=1]":1}
,"=1]":{"select":1}
,"end":{"if":1}
,"selecting":{"field":1}
,"browse":{"mode":1}
,"mode":{"find":1,"automating":1}
,"find":{"mode":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
