var pairs =
{
"onpanelswitch":{"performs":1,"applies":1,"passes":1}
,"performs":{"script":1}
,"script":{"hen":1,"focus":1,"script":1,"step":1,"return":1,"proceeds":1,"canceled":1,"rigger":1,"parameter":1,"determined":1,"value":1,"activated":1,"runs":1}
,"hen":{"panel":1}
,"panel":{"control":1,"script":1,"event":1,"switch":1,"switched":1}
,"control":{"panels":1,"user":1,"individual":1,"switching":1}
,"panels":{"happen":1,"control":1,"use":1}
,"happen":{"tab":1}
,"tab":{"control":1,"panel":1}
,"user":{"clicks":1}
,"clicks":{"inactive":1}
,"inactive":{"tab":1}
,"focus":{"object":1}
,"object":{"tab":1}
,"event":{"processed":1,"triggered":1}
,"processed":{"browse":1,"value":1}
,"browse":{"find":1}
,"find":{"modes":1}
,"modes":{"use":1,"trigger":1}
,"use":{"exit":1,"get":1,"script":1,"functions":1}
,"exit":{"script":1}
,"step":{"ithin":1}
,"ithin":{"triggered":1}
,"triggered":{"script":1}
,"return":{"true":1}
,"true":{"false":1,"event":1}
,"false":{"true":1,"event":1}
,"proceeds":{"false":1}
,"canceled":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"12.0":1}
,"12.0":{"onpanelswitch":1}
,"applies":{"entire":1}
,"entire":{"panel":1}
,"individual":{"panels":1}
,"switching":{"panels":1}
,"get":{"triggercurrentpanel":1,"triggertargetpanel":1,"returned":1}
,"triggercurrentpanel":{"get":1}
,"triggertargetpanel":{"functions":1,"script":1}
,"functions":{"script":1}
,"rigger":{"activated":1}
,"activated":{"panel":1,"by":1}
,"switch":{"event":1}
,"value":{"script":1,"get":1,"zero":1}
,"parameter":{"onpanelswitch":1,"pass":1,"script":1}
,"passes":{"script":1}
,"determined":{"panel":1}
,"switched":{"therefore":1}
,"therefore":{"if":1}
,"if":{"use":1}
,"pass":{"returned":1}
,"returned":{"value":1,"values":1}
,"zero":{"get":1}
,"values":{"use":1}
,"by":{"onpanelswtich":1}
,"onpanelswtich":{"script":1}
,"runs":{"modes":1}
,"trigger":{"result":1}
}
;Search.control.loadWordPairs(pairs);
