var pairs =
{
"ove\u002Fresize":{"window":1}
,"window":{"djusts":1,"current":1,"selects":1,"script":1,"name":1,"by":1,"points":1,"distance":1,"filemaker":1,"maintains":1,"se":1,"default":1,"height":1,"creen":1,"returns":1,"top-left":1,"go":1,"[current":1}
,"djusts":{"size":1}
,"size":{"location":1,"window":1}
,"location":{"chosen":1,"size":1}
,"chosen":{"window":1}
,"current":{"window":1,"foreground":1,"file":1,"record":1}
,"selects":{"current":1,"open":1}
,"foreground":{"window":1}
,"script":{"step":1,"user\u2019s":1}
,"step":{"performed":1,"full-screen":1,"supported":1}
,"performed":{"window":1}
,"name":{"selects":1,"current":1,"case-sensitive":1}
,"open":{"window":1}
,"by":{"name":1,"window":1,"supplying":1}
,"file":{"restricts":1,"selecting":1}
,"restricts":{"matches":1}
,"matches":{"current":1,"all":1}
,"selecting":{"option":1}
,"option":{"matches":1,"value":1}
,"all":{"filemaker":1}
,"filemaker":{"pro":1,"go":1}
,"pro":{"advanced":1,"6.0":1}
,"advanced":{"iles":1,"ses":1,"minimum":1,"maximum":1,"indow":1}
,"iles":{"height":1}
,"height":{"height":1,"adjusted":1,"width":1,"400":1}
,"adjusted":{"window":1,"window\u2019s":1}
,"points":{"width":1,"distance":1,"top":1,"left":1}
,"width":{"width":1,"adjusted":1,"depend":1,"values":1,"600":1}
,"distance":{"top":1,"points":1,"left":1}
,"top":{"adjusted":1,"screen":1,"layout":1,"and\u002For":1,"left":1}
,"window\u2019s":{"distance":1}
,"screen":{"card":1,"resolution":1,"macos":1}
,"card":{"top":1,"left":1}
,"layout":{"parent":1,"table":1,"positions":1,"[\u0022":1}
,"parent":{"window":1}
,"left":{"adjusted":1,"screen":1,"parent":1,"values":1,"0]":1}
,"6.0":{"earlier":1}
,"earlier":{"adjusted":1}
,"maintains":{"layout":1}
,"table":{"found":1}
,"found":{"set":1}
,"set":{"current":1}
,"record":{"original":1}
,"original":{"window":1,"location":1}
,"se":{"lection":1}
,"lection":{"by":1}
,"case-sensitive":{"enter":1}
,"enter":{"values":1}
,"values":{"each":1,"minimum":1,"less":1,"maximum":1,"greater":1,"multiple":1}
,"each":{"option":1}
,"value":{"entered":1,"move":1}
,"entered":{"filemaker":1}
,"ses":{"original":1}
,"default":{"values":1}
,"minimum":{"window":1,"filemaker":1,"values":1}
,"depend":{"script":1}
,"user\u2019s":{"operating":1,"screen":1}
,"operating":{"system":1}
,"system":{"if":1}
,"if":{"height":1}
,"less":{"minimum":1}
,"maximum":{"window":1,"filemaker":1,"value":1}
,"resolution":{"if":1}
,"greater":{"maximum":1}
,"move":{"window":1}
,"creen":{"by":1}
,"supplying":{"negative":1}
,"negative":{"top":1}
,"and\u002For":{"left":1}
,"multiple":{"monitor":1}
,"monitor":{"environments":1}
,"environments":{"macos":1}
,"macos":{"script":1,"resizes":1}
,"full-screen":{"window":1}
,"returns":{"error":1}
,"error":{"code":1}
,"code":{"filemaker":1}
,"go":{"script":1,"layout":1}
,"supported":{"cards":1}
,"cards":{"customer":1}
,"customer":{"info":1}
,"info":{"layout":1,"\u0022]":1}
,"positions":{"window":1}
,"top-left":{"corner":1}
,"corner":{"filemaker":1,"screen":1}
,"indow":{"windows":1}
,"windows":{"top-left":1}
,"resizes":{"window":1}
,"[\u0022":{"customer":1}
,"\u0022]":{"move\u002Fresize":1}
,"move\u002Fresize":{"window":1}
,"[current":{"window":1}
,"400":{"width":1}
,"600":{"top":1}
,"0]":{"saving":1}
,"saving":{"copying":1}
,"copying":{"files":1}
,"files":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
