var pairs =
{
"identifying":{"badges":1}
,"badges":{"icons":1,"displays":1,"display":1}
,"icons":{"layout":1,"objects":1}
,"layout":{"object":1,"mode":1,"objects":1,"script":1,"name":1,"disabled":1}
,"object":{"badges":1,"placeholder":1,"hidden":1,"script":1,"ee":1,"badge":1}
,"objects":{"layouts":1,"conditional":1,"object":1,"script":1,"layout":1,"tooltips":1,"condition":1,"badge":1}
,"layouts":{"layout":1,"dialog":1,"green":1,"button":1,"hidden":1}
,"mode":{"choose":1,"ee":1,"popovers":1}
,"choose":{"view":1}
,"view":{"menu":1}
,"menu":{"show":1}
,"show":{"type":1}
,"type":{"badge":1}
,"badge":{"want":1,"tooltip":1,"description":1,"placeholder":1,"displays":1,"conditional":1,"object":1,"objects":1,"appears":1,"layout":1,"manage":1,"yellow":1,"gray":1,"quick":1,"field":1,"button":1,"popover":1,"hide":1,"icon":1}
,"want":{"display":1}
,"display":{"move":1,"fields":1}
,"move":{"cursor":1}
,"cursor":{"badge":1}
,"tooltip":{"displays":1,"badge":1}
,"displays":{"object":1,"fields":1,"objects":1,"lower-right":1,"button":1,"popover":1}
,"placeholder":{"text":1}
,"text":{"field":1,"badge":1,"adding":1}
,"field":{"condition":1,"labels":1,"searchable":1}
,"condition":{"object":1,"badge":1,"defined":1}
,"hidden":{"badge":1,"condition":1}
,"description":{"placeholder":1}
,"fields":{"placeholder":1,"use":1,"green":1}
,"adding":{"changing":1,"tooltips":1}
,"changing":{"field":1,"button":1}
,"labels":{"conditional":1}
,"conditional":{"formatting":1}
,"formatting":{"badge":1,"defined":1,"layout":1}
,"defined":{"ee":1,"hide":1}
,"ee":{"defining":1,"setting":1,"configuring":1,"adding":1,"hiding":1}
,"defining":{"conditional":1,"changing":1}
,"script":{"trigger":1,"triggers":1}
,"trigger":{"badge":1,"badges":1}
,"triggers":{"set":1,"objects":1,"layouts":1}
,"set":{"badge":1,"manage":1,"ee":1}
,"appears":{"depends":1,"folder":1}
,"depends":{"size":1}
,"size":{"object":1}
,"setting":{"script":1}
,"lower-right":{"corner":1}
,"corner":{"layout":1}
,"manage":{"layouts":1}
,"dialog":{"box":1}
,"box":{"badge":1,"next":1}
,"folder":{"icon":1}
,"icon":{"layout":1}
,"next":{"layout":1}
,"name":{"script":1}
,"green":{"quick":1,"badge":1}
,"quick":{"find":1}
,"find":{"badge":1,"badges":1,"green":1,"ee":1,"tooltip":1}
,"yellow":{"quick":1,"badge":1}
,"gray":{"quick":1,"badge":1}
,"use":{"quick":1}
,"searchable":{"yellow":1,"search":1}
,"search":{"take":1}
,"take":{"fields":1}
,"disabled":{"quick":1}
,"configuring":{"quick":1}
,"tooltips":{"ee":1,"layouts":1}
,"button":{"badge":1,"objects":1,"popover":1}
,"popover":{"badge":1,"button":1,"buttons":1}
,"buttons":{"layout":1}
,"popovers":{"layouts":1}
,"hide":{"condition":1,"ee":1}
,"hiding":{"layout":1}
}
;Search.control.loadWordPairs(pairs);
