var pairs =
{
"creating":{"styles":1}
,"styles":{"ayout":1,"objects":1,"dots":1,"layouts":1,"design":1,"save":1,"applied":1,"current":1,"custom":1,"filemaker":1,"themes":1,"styles":1,"tab":1,"use":1}
,"ayout":{"style":1}
,"style":{"collection":1,"text":1,"object":1,"layout":1,"defined":1}
,"collection":{"attributes":1}
,"attributes":{"font":1,"each":1,"styles":1}
,"font":{"color":1}
,"color":{"line":1}
,"line":{"style":1}
,"text":{"alignment":1}
,"alignment":{"determine":1}
,"determine":{"appearance":1}
,"appearance":{"layout":1,"save":1,"appearance":1,"tab":1}
,"layout":{"each":1,"part":1,"background":1,"parts":1,"filemaker":1,"edit":1,"create":1,"use":1}
,"each":{"filemaker":1,"time":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"heme":1,"default":1,"theme\u0027s":1,"themes":1}
,"heme":{"includes":1}
,"includes":{"default":1}
,"default":{"style":1,"styles":1,"custom":1}
,"object":{"layout":1,"part":1,"type":1}
,"part":{"layout":1,"add":1,"type":1}
,"background":{"themes":1,"styles":1,"modify":1,"current":1}
,"themes":{"additional":1,"new":1,"create":1,"use":1,"layouts":1,"dialog":1,"files":1}
,"additional":{"default":1}
,"objects":{"default":1,"layout":1,"parts":1}
,"dots":{"slide":1}
,"slide":{"control":1}
,"control":{"rows":1}
,"rows":{"portal":1}
,"portal":{"theme":1}
,"theme":{"includes":1,"object":1,"dialog":1}
,"layouts":{"consistent":1,"save":1,"file":1}
,"consistent":{"appearance":1}
,"save":{"time":1,"use":1,"formatting":1,"styles":1}
,"time":{"reassigning":1,"create":1}
,"reassigning":{"formatting":1}
,"formatting":{"attributes":1}
,"create":{"new":1,"create":1,"styles":1,"modify":1}
,"new":{"object":1,"layout":1,"styles":1,"custom":1}
,"add":{"objects":1}
,"parts":{"layout":1,"applied":1,"use":1}
,"defined":{"current":1,"styles":1}
,"current":{"theme":1,"layout":1}
,"type":{"part":1,"create":1}
,"theme\u0027s":{"default":1}
,"modify":{"default":1,"styles":1}
,"design":{"new":1}
,"use":{"current":1,"styles":1,"custom":1,"appearance":1,"change":1,"manage":1,"file":1}
,"edit":{"save":1}
,"applied":{"multiple":1,"all":1}
,"multiple":{"objects":1}
,"all":{"objects":1}
,"custom":{"names":1,"styles":1,"themes":1}
,"names":{"apply":1}
,"apply":{"objects":1,"defined":1,"default":1}
,"tab":{"inspector":1}
,"inspector":{"view":1,"create":1}
,"view":{"apply":1}
,"change":{"theme":1}
,"dialog":{"box":1}
,"box":{"apply":1,"themes":1}
,"file":{"use":1,"import":1}
,"manage":{"themes":1}
,"import":{"themes":1}
}
;Search.control.loadWordPairs(pairs);
