var pairs =
{
"onverting":{"single":1}
,"single":{"multiple":1,"file":1}
,"multiple":{"files":1,"related":1}
,"files":{"convert":1,"filemaker":1,"don\u2019t":1,"use":1,"want":1,"filename":1,"drag":1,"folder":1,"separate":1,"created":1,"locations":1,"easier":1,"multifile":1,"duplicate":1,"if":1,"renamed":1,"replacing":1,"renaming":1,"data":1,"dialog":1,"testing":1,"viewing":1}
,"convert":{"files":1,"database":1,"iles":1,"drag":1,"create":1,"current":1,"all":1,"choose":1,"improperly":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1,"11":1,"12":1}
,"advanced":{"filemaker":1,"won\u2019t":1,"version":1,"application":1}
,"11":{"nd":1}
,"nd":{"earlier":1}
,"earlier":{"filemaker":1}
,"12":{"format":1}
,"format":{"use":1}
,"use":{"single-file":1,"multifile":1,"text":1}
,"single-file":{"conversion":1}
,"conversion":{"method":1,"dialog":1,"save":1,"move":1,"ou":1,"process":1}
,"method":{"standalone":1,"convert":1}
,"standalone":{"database":1}
,"database":{"files":1,"composed":1,"time":1,"conversion.log":1}
,"don\u2019t":{"display":1}
,"display":{"related":1}
,"related":{"data":1,"files":1}
,"data":{"files":1,"sources":1}
,"multifile":{"conversion":1,"relational":1}
,"composed":{"multiple":1}
,"want":{"quickly":1,"convert":1}
,"quickly":{"convert":1,"if":1}
,"iles":{"quickly":1}
,"if":{"filename":1,"period":1,"desired":1,"includes":1,"converted":1}
,"filename":{"includes":1,"extension":1,"filemaker":1,"new":1,"prevent":1}
,"includes":{"period":1,".fp7":1}
,"period":{"precedes":1,"exists":1}
,"precedes":{"filename":1}
,"extension":{"remove":1,"converted":1,".fmp12":1,"enter":1}
,"remove":{"if":1}
,"exists":{"filename":1}
,"won\u2019t":{"add":1}
,"add":{".fmp12":1}
,".fmp12":{"extension":1,"converted":1}
,"converted":{"file":1,"open":1,"files":1,"all":1,"database":1,"contain":1}
,"file":{"note":1,"want":1,"current":1,"enter":1,"if":1,".fmp12":1,"save":1,"structure":1,"references":1,"located":1,"journal":1,"components":1,"converting":1}
,"note":{"files":1}
,"open":{"current":1,"all":1,"open":1,"multiple":1,"conversion.log":1}
,"current":{"filemaker":1}
,"version":{"close":1}
,"close":{"file":1,"all":1}
,"drag":{"file":1,"files":1}
,"application":{"icon":1}
,"icon":{"conversion":1,"multiple":1}
,"dialog":{"box":1}
,"box":{"select":1,"start":1}
,"select":{"rename":1}
,"rename":{"old":1}
,"old":{"file":1}
,"enter":{"new":1,"filename":1}
,"new":{"name":1,"file":1,"empty":1}
,"name":{"if":1}
,"desired":{"it\u2019s":1}
,"it\u2019s":{"rename":1}
,".fp7":{"filename":1}
,"save":{"start":1,"time":1}
,"start":{"conversion":1}
,"time":{"by":1,"conversion":1}
,"by":{"clicking":1,"appending":1}
,"clicking":{"skip":1}
,"skip":{"index":1}
,"index":{"re-created":1}
,"re-created":{"postpones":1}
,"postpones":{"indexing":1}
,"indexing":{"close":1,"you\u2019ve":1}
,"all":{"files":1,"converted":1}
,"create":{"new":1}
,"empty":{"folder":1}
,"folder":{"converted":1,"files":1,"original":1,"created":1}
,"separate":{"folders":1}
,"folders":{"converted":1}
,"created":{"folder":1,"step":1}
,"original":{"files":1,"file":1}
,"locations":{"preserved":1}
,"preserved":{"converting":1}
,"converting":{"files":1,"single":1,"multiple":1}
,"easier":{"convert":1}
,"relational":{"database":1}
,"move":{"set":1}
,"set":{"files":1}
,"duplicate":{"original":1}
,"structure":{"choose":1}
,"choose":{"open":1,"folder":1,"choose":1}
,"step":{"choose":1}
,"renamed":{"by":1}
,"appending":{"number":1}
,"number":{"filename":1}
,"prevent":{"converted":1}
,"replacing":{"original":1}
,"renaming":{"files":1}
,"sources":{"file":1,"open":1}
,"references":{"convert":1}
,"improperly":{"relationships":1}
,"relationships":{"features":1}
,"features":{"rely":1}
,"rely":{"data":1}
,"ou":{"save":1}
,"you\u2019ve":{"converted":1}
,"text":{"editor":1}
,"editor":{"open":1}
,"conversion.log":{"file":1}
,"located":{"folder":1}
,"journal":{"conversion":1}
,"process":{"just":1}
,"just":{"completed":1}
,"completed":{"status":1}
,"status":{"messages":1}
,"messages":{"file":1,"manual":1}
,"components":{"converted":1}
,"contain":{"error":1}
,"error":{"messages":1}
,"manual":{"corrections":1}
,"corrections":{"converted":1}
,"testing":{"further":1}
,"further":{"converting":1}
,"viewing":{"conversion.log":1}
}
;Search.control.loadWordPairs(pairs);
