var pairs =
{
"viewing":{"records":1,"table":1}
,"records":{"form":1,"display":1,"browse":1}
,"form":{"list":1,"view":1}
,"list":{"table":1,"list":1,"view":1}
,"table":{"ou":1,"table":1,"view":1}
,"ou":{"change":1}
,"change":{"records":1,"data":1}
,"display":{"print":1,"field":1}
,"print":{"view":1}
,"view":{"records":1,"form":1,"button":1,"list":1,"table":1,"panel":1,"displays":1,"sorted":1,"field":1,"clicking":1,"header":1}
,"browse":{"mode":1}
,"mode":{"find":1,"preview":1,"individually":1}
,"find":{"mode":1}
,"preview":{"mode":1}
,"individually":{"form":1}
,"button":{"layout":1,"spreadsheet-like":1,"each":1,"list":1}
,"layout":{"bar":1,"if":1,"design":1}
,"bar":{"list":1}
,"spreadsheet-like":{"table":1}
,"each":{"row":1,"column":1,"layout":1,"panel":1}
,"row":{"displays":1}
,"displays":{"record":1,"field":1,"all":1,"popover":1}
,"record":{"each":1,"list":1,"popover":1,"popovers":1}
,"column":{"displays":1}
,"field":{"views":1,"borders":1,"fill":1}
,"views":{"each":1,"layouts":1}
,"if":{"layout":1}
,"design":{"privileges":1}
,"privileges":{"select":1}
,"select":{"views":1}
,"layouts":{"contain":1}
,"contain":{"panel":1}
,"panel":{"controls":1,"control":1,"front":1,"subsummary":1}
,"controls":{"form":1}
,"control":{"bring":1}
,"bring":{"associated":1}
,"associated":{"panel":1}
,"front":{"viewing":1}
,"all":{"fields":1}
,"fields":{"each":1,"update":1}
,"subsummary":{"parts":1}
,"parts":{"table":1}
,"sorted":{"by":1}
,"by":{"break":1}
,"break":{"fields":1}
,"update":{"dynamically":1}
,"dynamically":{"change":1}
,"data":{"file":1}
,"file":{"display":1}
,"borders":{"field":1,"fill":1}
,"fill":{"current":1}
,"current":{"record":1}
,"popover":{"buttons":1,"button":1,"record":1}
,"buttons":{"form":1}
,"clicking":{"popover":1}
,"popovers":{"table":1}
,"header":{"footer":1}
,"footer":{"part":1}
,"part":{"top":1}
,"top":{"bottom":1}
,"bottom":{"navigation":1}
,"navigation":{"part":1}
}
;Search.control.loadWordPairs(pairs);
