var pairs =
{
"rinting":{"table":1}
,"table":{"field":1,"select":1,"choose":1}
,"field":{"filemaker":1,"names":1,"types":1,"fields":1,"definitions":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"prints":1}
,"prints":{"field":1}
,"names":{"field":1}
,"types":{"formula\u002Fentry":1}
,"formula\u002Fentry":{"options":1}
,"options":{"each":1}
,"each":{"table":1}
,"select":{"choose":1,"tables":1,"fields":1}
,"choose":{"file":1,"table":1}
,"file":{"menu":1}
,"menu":{"manage":1}
,"manage":{"database":1}
,"database":{"print":1}
,"print":{"tables":1,"print":1,"field":1,"lick":1,"windows":1,"macos":1}
,"tables":{"tables":1,"tab":1,"want":1}
,"tab":{"select":1,"table":1}
,"want":{"print":1}
,"fields":{"tab":1,"want":1}
,"lick":{"print":1}
,"windows":{"print":1}
,"macos":{"print":1}
,"definitions":{"printing":1}
,"printing":{"field":1}
}
;Search.control.loadWordPairs(pairs);
