var pairs =
{
"avplayer":{"play":1}
,"play":{"lays":1,"media":1,"first":1,"end":1,"plays":1,"[field":1,"[object":1}
,"lays":{"audio":1}
,"audio":{"video":1,"start":1,"plays":1,"disable":1}
,"video":{"images":1,"image":1}
,"images":{"container":1}
,"container":{"field":1,"fields":1,"presentation":1}
,"field":{"layout":1,"specifies":1,"play":1,"doesn\u2019t":1,"url":1,"[library":1}
,"layout":{"object":1,"url":1,"objects":1}
,"object":{"url":1,"specifies":1,"play":1,"presentation":1}
,"url":{"source":1,"specifies":1,"play":1,"create":1,"calculation":1,"options":1}
,"source":{"pecifies":1,"media":1,"script":1}
,"pecifies":{"source":1}
,"media":{"layout":1,"field":1,"type":1,"if":1,"full":1,"embedded":1,"disables":1,"plays":1,"start":1,"media":1,"played":1,"default":1,"play":1,"files":1,"audio":1,"file":1}
,"specifies":{"layout":1,"container":1,"url":1,"display":1,"seconds":1,"playback":1,"end":1}
,"doesn\u2019t":{"layout":1,"allow":1}
,"type":{"url":1}
,"create":{"url":1}
,"calculation":{"if":1}
,"if":{"source":1,"option":1,"hide":1,"set":1,"foreground":1,"[get":1,"container":1}
,"script":{"step":1,"play":1,"trigger":1}
,"step":{"use":1}
,"use":{"active":1,"playback":1,"gestures":1,"script":1}
,"active":{"layout":1}
,"presentation":{"specifies":1,"full":1,"embedded":1,"start":1}
,"display":{"media":1}
,"options":{"presentation":1}
,"full":{"screen":1,"screen]":1}
,"screen":{"audio":1,"starts":1,"allows":1,"plays":1,"start":1,"embedded":1,"hides":1,"hide":1,"iphone":1}
,"start":{"full":1,"embedded":1,"playback":1,"offset":1,"end":1,"embedded]":1}
,"starts":{"playing":1}
,"playing":{"media":1,"window":1}
,"allows":{"changing":1,"media":1}
,"changing":{"presentation":1}
,"embedded":{"full":1,"starts":1,"allows":1,"plays":1,"doesn\u2019t":1,"ipad":1}
,"plays":{"media":1,"audio":1,"if":1}
,"allow":{"users":1}
,"users":{"change":1}
,"change":{"presentation":1}
,"disable":{"interaction":1}
,"interaction":{"enables":1,"playback":1,"use":1}
,"enables":{"disables":1,"user":1}
,"disables":{"user":1}
,"user":{"interaction":1,"rewind":1,"fast":1}
,"playback":{"if":1,"controls":1,"enables":1,"hide":1,"start":1,"range":1}
,"option":{"set":1,"30":1,"allows":1,"100":1}
,"set":{"use":1,"option":1,"field":1}
,"controls":{"gestures":1,"hides":1,"while":1,"enable":1,"playback":1,"position":1,"onrecordload":1,"yes]":1}
,"gestures":{"interact":1,"playback":1}
,"interact":{"media":1}
,"hide":{"controls":1,"playback":1}
,"hides":{"playback":1}
,"while":{"media":1}
,"enable":{"interaction":1}
,"position":{"specifies":1,"last":1,"getavplayerattribute":1,")]":1,"ibrary":1,"plays":1}
,"seconds":{"media":1}
,"offset":{"specifies":1}
,"range":{"seconds":1,"if":1}
,"played":{"playback":1}
,"30":{"user":1,"seconds":1}
,"rewind":{"play":1}
,"first":{"30":1,"100":1}
,"default":{"value":1}
,"value":{"option":1}
,"end":{"offset":1,"playback":1,"filemaker":1,"if":1}
,"100":{"user":1,"seconds":1}
,"fast":{"forward":1}
,"forward":{"play":1}
,"filemaker":{"pro":1,"go":1}
,"pro":{"14.0":1}
,"14.0":{"use":1}
,"files":{"container":1}
,"fields":{"layout":1,"automating":1}
,"objects":{"urls":1}
,"urls":{"filemaker":1}
,"go":{"media":1}
,"image":{"file":1}
,"file":{"if":1,"playing":1,"continues":1,"full":1,"position":1}
,"foreground":{"window":1}
,"window":{"media":1,"moves":1}
,"moves":{"back":1}
,"back":{"media":1}
,"continues":{"play":1}
,"onrecordload":{"script":1}
,"trigger":{"activated":1}
,"activated":{"avplayer":1}
,"[field":{"library":1}
,"library":{":video":1}
,":video":{"presentation":1,"position":1}
,"yes]":{"resumes":1}
,"resumes":{"playing":1}
,"last":{"stopped":1}
,"stopped":{"set":1,"position":1}
,"[library":{":last":1}
,":last":{"stopped":1}
,"getavplayerattribute":{"position":1}
,")]":{"avplayer":1}
,"ibrary":{":last":1}
,"iphone":{"embedded":1}
,"ipad":{"if":1}
,"[get":{"device":1}
,"device":{"=3":1,"=4":1}
,"=3":{"\u002F\u002Fipad]":1}
,"\u002F\u002Fipad]":{"avplayer":1}
,"[object":{"name":1}
,"name":{"container":1}
,"embedded]":{"else":1}
,"else":{"if":1}
,"=4":{"\u002F\u002Fiphone]":1}
,"\u002F\u002Fiphone]":{"avplayer":1}
,"screen]":{"end":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
