var pairs =
{
"open":{"manage":1}
,"manage":{"themes":1,"database\u2019s":1,"database":1}
,"themes":{"pens":1,"dialog":1,"use":1,"manage":1,"\u0022]":1,"end":1,"automating":1}
,"pens":{"manage":1}
,"dialog":{"box":1,"[\u0022":1}
,"box":{"none":1,"users":1,"diting":1,"if":1,"show":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"13.0":1,"advanced":1}
,"13.0":{"script":1}
,"script":{"step":1}
,"step":{"choosing":1,"open":1}
,"choosing":{"file":1}
,"file":{"menu":1}
,"menu":{"manage":1}
,"use":{"script":1}
,"users":{"if":1,"full":1}
,"if":{"restricted":1,"user":1,"[get":1,"managing":1}
,"restricted":{"access":1}
,"access":{"filemaker":1,"privileges":1}
,"advanced":{"menus":1}
,"menus":{"users":1}
,"full":{"layout":1}
,"layout":{"access":1,"themes":1}
,"privileges":{"open":1,"diting":1,"displays":1}
,"diting":{"record":1,"layouts":1}
,"record":{"access":1}
,"layouts":{"privileges":1}
,"displays":{"custom":1}
,"custom":{"dialog":1}
,"user":{"manage":1}
,"database\u2019s":{"layout":1}
,"show":{"custom":1}
,"[\u0022":{"want":1}
,"want":{"manage":1}
,"database":{"themes":1}
,"\u0022]":{"if":1}
,"[get":{"lastmessagechoice":1}
,"lastmessagechoice":{"=1]":1}
,"=1]":{"open":1}
,"end":{"if":1}
,"managing":{"layout":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
