var pairs =
{
"et":{"persistentid":1}
,"persistentid":{"returns":1,"none":1,"helps":1,"if":1}
,"returns":{"text":1,"unique":1,"value":1}
,"text":{"representing":1,"filemaker":1}
,"representing":{"unique":1}
,"unique":{"identifier":1,"unchanging":1}
,"identifier":{"computer":1}
,"computer":{"device":1,"filemaker":1}
,"device":{"running":1,"filemaker":1,"value":1,"returned":1}
,"running":{"filemaker":1,"device":1,"current":1}
,"filemaker":{"get":1,"pro":1,"go":1,"webdirect":1,"knowledge":1}
,"get":{"persistentid":1}
,"none":{"text":1}
,"pro":{"12.0":1,"advanced":1}
,"12.0":{"returns":1}
,"unchanging":{"identifier":1}
,"advanced":{"running":1,"client":1}
,"go":{"running":1,"user":1,"client":1}
,"current":{"filemaker":1}
,"webdirect":{"session":1}
,"session":{"form":1,"value":1}
,"form":{"32-digit":1}
,"32-digit":{"hexadecimal":1}
,"hexadecimal":{"string":1}
,"string":{"get":1}
,"helps":{"identify":1}
,"identify":{"devices":1}
,"devices":{"access":1}
,"access":{"solution":1}
,"solution":{"if":1}
,"if":{"web":1,"filemaker":1,"backup":1}
,"web":{"browser":1}
,"browser":{"cookies":1}
,"cookies":{"cleared":1}
,"cleared":{"during":1}
,"during":{"filemaker":1}
,"value":{"returned":1,"remains":1,"78569d0bd40b898a64e7d08ccdea8220":1}
,"returned":{"by":1,"value":1}
,"by":{"get":1}
,"user":{"restores":1}
,"restores":{"ios":1}
,"ios":{"backup":1,"device":1}
,"backup":{"device":1,"restored":1}
,"restored":{"ios":1}
,"remains":{"filemaker":1}
,"knowledge":{"base":1}
,"base":{"filemaker":1}
,"client":{"filemaker":1,"get":1}
,"78569d0bd40b898a64e7d08ccdea8220":{"filemaker":1}
}
;Search.control.loadWordPairs(pairs);
