var pairs =
{
"inding":{"duplicate":1}
,"duplicate":{"values":1,"records":1,"formula":1}
,"values":{"self-join":1}
,"self-join":{"relationshi":1,"relationship":1}
,"relationshi":{"procedure":1}
,"procedure":{"self-join":1}
,"relationship":{"calculation":1,"identify":1,"use":1,"creating":1}
,"calculation":{"field":1,"returning":1}
,"field":{"referencing":1,"determines":1,"create":1,"calculation":1,"define":1,"match":1,"tables":1,"named":1,"duplicates":1,"all":1}
,"referencing":{"relationship":1}
,"identify":{"all":1,"field":1}
,"all":{"duplicate":1,"status":1,"records":1}
,"records":{"except":1,"created":1,"identified":1,"find":1,"duplicates":1}
,"except":{"first":1}
,"first":{"instance":1,"name":1}
,"instance":{"order":1}
,"order":{"records":1}
,"created":{"system":1,"if":1}
,"system":{"set":1}
,"set":{"up":1}
,"up":{"duplicate":1}
,"identified":{"created":1}
,"if":{"plan":1,"count":1}
,"plan":{"delete":1}
,"delete":{"duplicate":1}
,"find":{"backup":1,"duplicates":1,"duplicate":1}
,"backup":{"opy":1}
,"opy":{"file":1}
,"file":{"saving":1,"contacts":1}
,"saving":{"copying":1}
,"copying":{"files":1}
,"files":{"identify":1}
,"determines":{"unique":1}
,"unique":{"entity":1,"identifier":1,"show":1}
,"entity":{"file":1}
,"contacts":{"database":1}
,"database":{"use":1}
,"use":{"mployee":1,"repeating":1,"chosen":1}
,"mployee":{"id":1}
,"id":{"field":1}
,"create":{"calculation":1,"new":1}
,"returning":{"text":1}
,"text":{"result":1}
,"result":{"hat":1}
,"hat":{"combines":1}
,"combines":{"data":1}
,"data":{"everal":1}
,"everal":{"fields":1}
,"fields":{"unique":1}
,"identifier":{"xample":1}
,"xample":{"first":1}
,"name":{"&last":1,"&phone":1,"table\u2019s":1}
,"&last":{"name":1}
,"&phone":{"number":1}
,"number":{"don\u2019t":1}
,"don\u2019t":{"use":1}
,"repeating":{"field":1}
,"define":{"self-join":1}
,"chosen":{"identifying":1}
,"identifying":{"field":1}
,"match":{"field":1}
,"tables":{"relationship":1}
,"creating":{"nd":1}
,"nd":{"changing":1}
,"changing":{"relationships":1}
,"relationships":{"create":1}
,"new":{"calculation":1}
,"named":{"check":1}
,"check":{"duplicate":1,"duplicates":1}
,"formula":{"if":1}
,"count":{"name":1}
,"table\u2019s":{"second":1}
,"second":{"occurrence":1}
,"occurrence":{"match":1}
,"duplicates":{"unique":1,"check":1,"field":1,"marked":1,"find":1}
,"show":{"all":1}
,"status":{"toolbar":1}
,"toolbar":{"perform":1}
,"perform":{"find":1}
,"marked":{"duplicates":1}
}
;Search.control.loadWordPairs(pairs);
