var pairs =
{
"setting":{"tab":1,"eys":1}
,"tab":{"order":1,"browse":1,"object":1,"key":1,"fields":1,"tab":1,"popover":1,"web":1}
,"order":{"data":1,"omit":1,"filemaker":1,"dialog":1,"ith":1,"individual":1,"automatically":1,"arrow":1,"appears":1,"add":1,"all":1,"want":1,"arrows":1,"fields":1,"choose":1,"objects":1,"calculation":1,"can\u2019t":1,"include":1,"use":1,"web":1,"continues":1,"layout":1}
,"data":{"entry":1}
,"entry":{"press":1,"can\u2019t":1}
,"press":{"tab":1,"backspace":1}
,"browse":{"mode":1}
,"mode":{"find":1,"default":1,"choose":1,"fields":1,"list":1}
,"find":{"mode":1}
,"default":{"ehavior":1,"tab":1}
,"ehavior":{"move":1}
,"move":{"left":1,"next":1}
,"left":{"right":1}
,"right":{"top":1}
,"top":{"bottom":1}
,"bottom":{"change":1}
,"change":{"default":1}
,"omit":{"fields":1,"objects":1}
,"fields":{"if":1,"objects":1,"buttons":1,"all":1,"can\u2019t":1,"included":1,"formatted":1,"popover":1,"tab":1}
,"if":{"want":1,"panel":1,"popover":1}
,"want":{"layout":1,"use":1,"arrow":1,"filemaker":1,"omit":1,"bring":1}
,"layout":{"mode":1,"press":1,"tab":1,"set":1}
,"choose":{"layouts":1,"set":1}
,"layouts":{"menu":1}
,"menu":{"set":1}
,"set":{"tab":1,"new":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"displays":1,"inserts":1,"layout":1}
,"displays":{"numbered":1}
,"numbered":{"arrows":1}
,"arrows":{"fields":1,"order":1,"create":1,"remove":1}
,"objects":{"set":1,"tab":1,"arrow":1,"add":1,"clear":1,"want":1,"display":1,"frontmost":1,"panel":1}
,"dialog":{"box":1}
,"box":{"objects":1,"open":1,"number":1,"if":1}
,"ith":{"set":1}
,"open":{"options":1,"popover":1}
,"options":{"want":1,"set":1}
,"use":{"reorder":1,"options":1,"go":1}
,"reorder":{"tab":1}
,"individual":{"objects":1}
,"arrow":{"object":1,"set":1,"leave":1}
,"object":{"arrow":1,"tab":1,"next":1,"body":1,"part":1}
,"number":{"replaced":1,"tab":1,"type":1,"want":1,"select":1,"press":1}
,"replaced":{"incremented":1}
,"incremented":{"objects":1}
,"automatically":{"resequenced":1}
,"resequenced":{"place":1,"add":1}
,"place":{"new":1}
,"new":{"object":1,"tab":1}
,"next":{"number":1,"field":1}
,"appears":{"arrow":1}
,"leave":{"backspace":1}
,"backspace":{"delete":1}
,"delete":{"number":1,"remove":1}
,"type":{"number":1}
,"add":{"rest":1,"remaining":1,"create":1,"clear":1}
,"rest":{"objects":1}
,"remaining":{"select":1,"elect":1}
,"select":{"objects":1,"fields":1,"number":1,"all":1}
,"create":{"new":1}
,"all":{"objects":1,"add":1,"arrows":1,"fields":1,"buttons":1}
,"clear":{"all":1}
,"elect":{"objects":1}
,"inserts":{"numbers":1}
,"numbers":{"order":1}
,"buttons":{"clear":1,"add":1,"remove":1,"included":1,"tab":1}
,"remove":{"objects":1,"select":1,"summary":1}
,"display":{"number":1}
,"summary":{"fields":1}
,"can\u2019t":{"included":1,"tab":1,"tabbed":1,"control":1}
,"included":{"tab":1,"default":1}
,"calculation":{"fields":1}
,"formatted":{"prevent":1}
,"prevent":{"entry":1}
,"tabbed":{"browse":1}
,"list":{"view":1}
,"view":{"can\u2019t":1}
,"body":{"part":1}
,"part":{"object":1,"record":1}
,"record":{"buttons":1}
,"include":{"buttons":1}
,"panel":{"control":1,"use":1,"want":1,"controls":1}
,"control":{"layout":1,"tab":1}
,"key":{"navigate":1,"return":1,"setting":1}
,"navigate":{"objects":1}
,"frontmost":{"anel":1}
,"anel":{"automate":1}
,"automate":{"navigation":1}
,"navigation":{"panel":1}
,"go":{"field":1}
,"field":{"script":1,"panel":1,"enter":1}
,"script":{"step":1}
,"step":{"target":1}
,"target":{"field":1}
,"bring":{"front":1}
,"front":{"selecting":1}
,"selecting":{"objects":1}
,"controls":{"if":1}
,"popover":{"layout":1,"open":1,"first":1,"button":1,"it\u2019s":1}
,"first":{"by":1}
,"by":{"clicking":1,"tabbing":1}
,"clicking":{"popover":1}
,"button":{"by":1,"pressing":1}
,"tabbing":{"popover":1}
,"pressing":{"space":1}
,"space":{"bar":1}
,"bar":{"tab":1}
,"it\u2019s":{"move":1}
,"enter":{"key":1}
,"return":{"key":1}
,"eys":{"moving":1}
,"moving":{"fields":1}
,"web":{"viewers":1,"viewer":1}
,"viewers":{"can\u2019t":1}
,"viewer":{"tab":1}
,"continues":{"defined":1}
,"defined":{"filemaker":1}
}
;Search.control.loadWordPairs(pairs);
