var pairs =
{
"ormatting":{"buttons":1}
,"buttons":{"popover":1,"popovers":1}
,"popover":{"buttons":1,"layout":1,"button":1,"nd":1,"content":1,"if":1,"hidden":1,"inspector":1,"popover":1,"by":1,"advanced":1,"boundary":1,"select":1,"choose":1}
,"popovers":{"format":1}
,"format":{"button":1,"popover":1,"abel":1,"changing":1,"display":1,"menu":1}
,"button":{"opover":1,"format":1,"popover":1,"inspector":1,"button":1,"icon":1,"layout":1,"icons":1,"label":1,"choose":1,"setup":1}
,"opover":{"button":1}
,"layout":{"mode":1,"bar":1}
,"mode":{"select":1}
,"select":{"button":1,"display":1,"outer":1,"popover":1,"inner":1}
,"inspector":{"appearance":1,"use":1}
,"appearance":{"appearance":1,"tab":1,"popover\u2019s":1}
,"tab":{"choose":1,"hoose":1,"change":1}
,"choose":{"button":1,"line":1,"options":1,"color":1,"format":1,"fill":1}
,"icon":{"object":1,"paragraph":1,"advanced":1,"label":1}
,"object":{"type":1,"add":1}
,"type":{"list":1}
,"list":{"top":1,"select":1,"ab":1,"value":1}
,"top":{"ab":1,"bottom":1,"tab":1}
,"ab":{"note":1,"graphic":1}
,"note":{"all":1}
,"all":{"options":1,"components":1}
,"options":{"all":1,"graphic":1,"text":1,"formatting":1}
,"components":{"change":1}
,"change":{"line":1,"format":1,"color":1,"fill":1,"appearance":1,"padding":1}
,"line":{"style":1}
,"style":{"color":1}
,"color":{"fill":1,"label":1,"change":1,"icons":1,"filemaker":1,"defined":1,"custom":1,"popover\u2019s":1,"options":1}
,"fill":{"attributes":1,"options":1,"color":1,"graphic":1}
,"attributes":{"choose":1}
,"graphic":{"change":1,"choose":1,"select":1,"padding":1,"ou":1}
,"abel":{"text":1}
,"text":{"choose":1,"inspector":1,"options":1,"icon":1,"paragraph":1}
,"use":{"text":1}
,"formatting":{"bar":1,"formatting":1}
,"bar":{"if":1,"formatting":1,"button":1,"set":1}
,"if":{"don\u2019t":1,"popover":1}
,"don\u2019t":{"formatting":1}
,"set":{"horizontal":1}
,"horizontal":{"vertical":1}
,"vertical":{"alignment":1}
,"alignment":{"label":1,"change":1}
,"label":{"text":1,"icons":1}
,"paragraph":{"set":1,"use":1}
,"icons":{"choose":1,"custom":1,"svg":1,"change":1,"png":1}
,"display":{"state":1,"popover":1}
,"state":{"second":1,"object":1}
,"second":{"list":1}
,"custom":{"icons":1,"border":1}
,"svg":{"format":1,"file":1,"support":1,"grammar":1}
,"changing":{"fill":1}
,"filemaker":{"ro":1}
,"ro":{"advanced":1,"svg":1}
,"advanced":{"ffects":1,"graphic":1}
,"ffects":{"elements":1}
,"elements":{"fill":1}
,"defined":{"svg":1}
,"file":{"svg":1}
,"support":{"filemaker":1}
,"grammar":{"button":1}
,"png":{"format":1}
,"add":{"shadow":1,"outer":1,"inner":1}
,"shadow":{"advanced":1,"inner":1,"adjust":1,"popover":1,"add":1,"popover\u2019s":1,"change":1}
,"outer":{"shadow":1}
,"inner":{"shadow":1}
,"adjust":{"padding":1}
,"padding":{"edges":1,"values":1,"icon":1,"format":1,"boundary":1}
,"edges":{"button":1}
,"values":{"points":1,"change":1}
,"points":{"left":1,"padding":1}
,"left":{"right":1}
,"right":{"top":1}
,"bottom":{"adjust":1}
,"value":{"points":1}
,"nd":{"popover":1}
,"content":{"separately":1,"object":1,"choose":1,"add":1,"advanced":1}
,"separately":{"layout":1}
,"hidden":{"select":1}
,"hoose":{"popover":1}
,"popover\u2019s":{"border":1,"content":1,"background":1,"title":1}
,"border":{"border":1,"popover\u2019s":1,"popover":1}
,"background":{"background":1,"popover\u2019s":1}
,"ou":{"create":1}
,"create":{"custom":1}
,"by":{"fills":1}
,"fills":{"popover":1}
,"boundary":{"popover":1,"popover\u2019s":1}
,"title":{"if":1}
,"setup":{"dialog":1,"choose":1}
,"dialog":{"box":1}
,"box":{"open":1}
,"open":{"double-click":1}
,"double-click":{"popover":1}
,"menu":{"popover":1}
}
;Search.control.loadWordPairs(pairs);
