var pairs =
{
"opying":{"importing":1}
,"importing":{"table":1,"filemaker":1,"ensure":1}
,"table":{"schema":1,"schemas":1,"want":1,"choose":1,"occurrences":1}
,"schema":{"note":1,"import":1,"choose":1,"data":1}
,"note":{"feature":1}
,"feature":{"use":1}
,"use":{"advanced":1}
,"advanced":{"tools":1,"etains":1}
,"tools":{"general":1,"yo":1}
,"general":{"preference":1}
,"preference":{"selected":1}
,"selected":{"ad":1}
,"ad":{"vanced":1}
,"vanced":{"tools":1}
,"yo":{"consolidate":1}
,"consolidate":{"tables":1}
,"tables":{"multifile":1,"want":1,"tab":1,"dialog":1,"fields":1}
,"multifile":{"solution":1}
,"solution":{"file":1}
,"file":{"two":1,"import":1,"menu":1,"mporting":1,"open":1,"table":1,"want":1,"dialog":1,"detailed":1,"retained":1,"relationships":1,"close":1,"located":1}
,"two":{"methods":1}
,"methods":{"consolidating":1}
,"consolidating":{"solutions":1}
,"solutions":{"copy":1}
,"copy":{"table":1,"tables":1,"choose":1,"copy":1,"open":1,"import":1}
,"schemas":{"open":1,"destination":1,"im":1,"import":1}
,"open":{"source":1,"database":1,"file":1,"log":1,"import.log":1}
,"source":{"files":1,"file":1,"destination":1,"references":1}
,"files":{"select":1,"privileges":1}
,"select":{"copy":1,"table":1,"source":1,"tables":1}
,"want":{"paste":1,"copy":1,"import":1}
,"paste":{"table":1,"open":1}
,"destination":{"file":1,"files":1,"database":1}
,"import":{"table":1,"just":1,"data":1,"records":1,"open":1,"tables":1,"list":1,"summary":1,"file":1,"check":1}
,"im":{"port":1}
,"port":{"table":1}
,"just":{"schemas":1}
,"data":{"single":1,"existing":1,"source":1}
,"single":{"schema":1}
,"choose":{"file":1}
,"menu":{"import":1,"manage":1}
,"records":{"file":1}
,"mporting":{"data":1}
,"existing":{"file":1}
,"database":{"file":1,"tables":1,"dialog":1,"details":1,"remotely":1}
,"manage":{"database":1}
,"tab":{"select":1,"paste":1,"import":1}
,"dialog":{"box":1}
,"box":{"select":1,"open":1,"full":1,"importing":1}
,"list":{"import":1}
,"summary":{"dialog":1}
,"log":{"file":1,"procedure":1}
,"detailed":{"log":1}
,"procedure":{"close":1}
,"close":{"dialog":1,"manage":1}
,"full":{"access":1}
,"access":{"privileges":1,"folder":1}
,"privileges":{"source":1}
,"retained":{"redefine":1,"if":1}
,"redefine":{"privilege":1}
,"privilege":{"sets":1}
,"sets":{"destination":1}
,"relationships":{"table":1}
,"occurrences":{"retained":1}
,"if":{"created":1,"valid":1,"you\u2019ve":1}
,"created":{"fields":1}
,"fields":{"tables":1,"scripts":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"etains":{"data":1}
,"references":{"tables":1,"pasting":1,"items":1}
,"scripts":{"if":1}
,"valid":{"copy":1,"open":1}
,"check":{"all":1,"documents":1}
,"all":{"data":1}
,"pasting":{"importing":1}
,"ensure":{"valid":1}
,"import.log":{"file":1}
,"located":{"folder":1}
,"folder":{"destination":1,"check":1,"copy":1}
,"details":{"unresolved":1}
,"unresolved":{"references":1}
,"items":{"renamed":1}
,"renamed":{"naming":1}
,"naming":{"conflict":1}
,"conflict":{"if":1}
,"you\u2019ve":{"destination":1}
,"remotely":{"write":1}
,"write":{"access":1}
,"documents":{"folder":1}
}
;Search.control.loadWordPairs(pairs);
