var pairs =
{
"get":{"hostapplicati":1,"hostapplicationversion":1,"host":1,"filemaker":1}
,"hostapplicati":{"onversion":1}
,"onversion":{"returns":1}
,"returns":{"filemaker":1,"empty":1,"proadvanced":1,"server":1,"cloud":1}
,"filemaker":{"host\u2019s":1,"pro":1,"server":1,"cloud":1}
,"host\u2019s":{"product":1}
,"product":{"name":1}
,"name":{"version":1}
,"version":{"get":1,"filemaker":1,"returns":1,"2.18":1,"host":1}
,"hostapplicationversion":{"none":1,"get":1}
,"none":{"text":1}
,"text":{"filemaker":1}
,"pro":{"9.0":1,"advanced":1,"18":1}
,"9.0":{"displays":1}
,"displays":{"value":1}
,"value":{"version":1}
,"advanced":{"filemaker":1}
,"server":{"filemaker":1,"18":1,"2.18":1,"version":1}
,"cloud":{"software":1,"server":1,"version":1}
,"software":{"if":1}
,"if":{"current":1}
,"current":{"file":1}
,"file":{"shared":1}
,"shared":{"hosted":1}
,"hosted":{"function":1}
,"function":{"returns":1}
,"empty":{"string":1}
,"string":{"returns":1,"host":1}
,"host":{"computer":1,"application":1,"version":1}
,"computer":{"itself":1,"running":1}
,"itself":{"returns":1}
,"proadvanced":{"18":1}
,"18":{"0.1":1,"dvanced":1,"ersion":1}
,"0.1":{"host":1}
,"running":{"filemaker":1}
,"dvanced":{"version":1}
,"ersion":{"returns":1}
,"2.18":{"0.57":1,"build":1}
,"0.57":{"host":1}
,"build":{"57":1}
,"57":{"get":1}
,"application":{"version":1}
}
;Search.control.loadWordPairs(pairs);
