var pairs =
{
"comparison":{"operators":1}
,"operators":{"comparison":1,"compare":1}
,"compare":{"two":1}
,"two":{"values":1}
,"values":{"return":1}
,"return":{"true":1}
,"true":{"false":1,"equals":1,"if":1}
,"false":{"expressions":1,"equals":1}
,"expressions":{"called":1,"mathematically":1}
,"called":{"boolean":1}
,"boolean":{"expressions":1}
,"mathematically":{"result":1}
,"result":{"true":1}
,"equals":{"false":1,"ymbol":1}
,"ymbol":{"name":1}
,"name":{"definition":1}
,"definition":{"=equals":1}
,"=equals":{"true":1}
,"if":{"items":1,"value":1}
,"items":{"equal":1}
,"equal":{"equal":1,"true":1,"greater":1,"value":1,">=for":1,"<=for":1}
,"greater":{"true":1,"equal":1}
,"value":{"left":1,"right":1}
,"left":{"exceeds":1,"less":1,"greater":1}
,"exceeds":{"right":1}
,"right":{"less":1,"greater":1,"use":1}
,"less":{"true":1,"value":1,"equal":1}
,"use":{"equal":1}
,">=for":{"greater":1}
,"<=for":{"less":1}
}
;Search.control.loadWordPairs(pairs);
