var pairs =
{
"ext":{"fields":1}
,"fields":{"use":1,"store":1,"text":1,"hold":1,"sort":1,"adding":1,"add":1}
,"use":{"text":1}
,"text":{"fields":1,"indexes":1,"field":1}
,"store":{"letters":1}
,"letters":{"symbols":1,"numbers":1}
,"symbols":{"numbers":1}
,"numbers":{"text":1,"special":1,"postal":1,"format":1,"add":1}
,"indexes":{"based":1}
,"based":{"values":1}
,"values":{"fields":1,"combinations":1}
,"hold":{"values":1}
,"combinations":{"letters":1}
,"special":{"characters":1}
,"characters":{"phone":1}
,"phone":{"numbers":1,"number":1}
,"postal":{"codes":1}
,"codes":{"serial":1,"phone":1}
,"serial":{"numbers":1}
,"sort":{"alphabetical":1}
,"alphabetical":{"order":1}
,"order":{"left":1}
,"left":{"right":1}
,"right":{"character":1}
,"character":{"by":1,"data":1}
,"by":{"character":1}
,"data":{"text":1}
,"field":{"displays":1,"objects":1,"adding":1}
,"displays":{"font":1}
,"font":{"ormatting":1}
,"ormatting":{"setting":1}
,"setting":{"up":1}
,"up":{"field":1}
,"objects":{"layout":1}
,"layout":{"mode":1}
,"mode":{"zip":1}
,"zip":{"code":1,"codes":1}
,"code":{"zip":1}
,"number":{"phone":1,"format":1}
,"format":{"phone":1}
,"add":{"fields":1,"field":1}
,"adding":{"fields":1,"field":1}
}
;Search.control.loadWordPairs(pairs);
