var pairs =
{
"mit":{"multiple":1}
,"multiple":{"records":1}
,"records":{"mits":1,"found":1,"omitted":1,"current":1,"specifies":1,"want":1,"[with":1,"except":1}
,"mits":{"records":1}
,"found":{"set":1}
,"set":{"starting":1,"go":1}
,"starting":{"current":1}
,"current":{"record":1,"found":1}
,"record":{"selects":1,"table":1,"omitted":1,"next":1,"if":1}
,"selects":{"next":1}
,"next":{"record":1}
,"table":{"dialog":1,"current":1}
,"dialog":{"specifies":1,"box":1,"number":1,"get":1}
,"specifies":{"display":1,"exact":1}
,"display":{"dialog":1}
,"box":{"script":1}
,"script":{"step":1}
,"step":{"performed":1,"omits":1}
,"performed":{"users":1,"layout":1,"omits":1}
,"users":{"enter":1}
,"enter":{"number":1}
,"number":{"records":1,"filemaker":1}
,"omitted":{"if":1,"records":1}
,"if":{"dialog":1,"script":1}
,"exact":{"number":1}
,"want":{"omit":1}
,"omit":{"calculation":1,"multiple":1}
,"calculation":{"result":1}
,"result":{"number":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1,"advanced":1}
,"6.0":{"earlier":1}
,"earlier":{"script":1}
,"omits":{"temporarily":1,"all":1}
,"temporarily":{"hides":1}
,"hides":{"records":1}
,"layout":{"mode":1}
,"mode":{"filemaker":1,"script":1}
,"advanced":{"switches":1}
,"switches":{"browse":1}
,"browse":{"mode":1}
,"all":{"records":1}
,"go":{"record\u002Frequest\u002Fpage":1}
,"record\u002Frequest\u002Fpage":{"[first]":1}
,"[first]":{"omit":1}
,"[with":{"dialog":1}
,"get":{"foundcount":1}
,"foundcount":{")]":1}
,")]":{"finding":1}
,"finding":{"records":1}
,"except":{"matching":1}
,"matching":{"criteria":1}
,"criteria":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
