var pairs =
{
"get":{"recordop":1,"recordopenstate":1,"record":1,"open":1}
,"recordop":{"enstate":1}
,"enstate":{"returns":1}
,"returns":{"number":1,"closed":1,"state":1,"if":1}
,"number":{"representing":1,"filemaker":1}
,"representing":{"state":1}
,"state":{"current":1,"get":1}
,"current":{"record":1,"user":1,"calculation":1,"window":1}
,"record":{"get":1,"new":1,"hasn\u2019t":1,"pertaining":1,"current":1,"open":1}
,"recordopenstate":{"none":1,"get":1}
,"none":{"number":1}
,"filemaker":{"pro":1}
,"pro":{"8.0":1}
,"8.0":{"returns":1}
,"closed":{"committed":1}
,"committed":{"record":1,"modified":1,"deleted":1,"function":1}
,"new":{"record":1}
,"hasn\u2019t":{"committed":1,"saved":1}
,"modified":{"record":1}
,"deleted":{"record":1}
,"function":{"returns":1,"evaluated":1}
,"pertaining":{"current":1}
,"user":{"if":1,"hasn\u2019t":1}
,"if":{"context":1,"current":1}
,"context":{"current":1,"evaluated":1}
,"calculation":{"function":1}
,"evaluated":{"based":1}
,"based":{"context":1}
,"window":{"returns":1}
,"saved":{"script":1}
,"script":{"revert":1,"step":1}
,"revert":{"record\u002Frequest":1}
,"record\u002Frequest":{"script":1}
,"step":{"get":1}
,"open":{"state":1}
}
;Search.control.loadWordPairs(pairs);
