var pairs =
{
"le":{"gal":1}
,"gal":{"nformation":1}
,"nformation":{"1992-201":1}
,"1992-201":{"ilemaker":1}
,"ilemaker":{"all":1}
,"all":{"ri":1,"trademarks":1,"persons":1}
,"ri":{"ghts":1}
,"ghts":{"re":1}
,"re":{"served":1}
,"served":{"filemaker":1}
,"filemaker":{"5201":1,"filemaker":1,"cloud":1,"go":1,"egistered":1,"webdirect":1,"all":1,"documentation":1,"use":1,"software":1,"assumes":1}
,"5201":{"patrick":1}
,"patrick":{"henry":1}
,"henry":{"drive":1}
,"drive":{"santa":1}
,"santa":{"clara":1}
,"clara":{"california":1}
,"california":{"95054":1}
,"95054":{"filemaker":1}
,"cloud":{"filemaker":1}
,"go":{"nd":1}
,"nd":{"file":1}
,"file":{"folder":1}
,"folder":{"logo":1}
,"logo":{"trademarks":1}
,"trademarks":{"filemaker":1,"property":1}
,"egistered":{"u.s":1}
,"u.s":{"countries":1}
,"countries":{"filemaker":1}
,"webdirect":{"rademark":1}
,"rademark":{"filemaker":1}
,"property":{"respective":1}
,"respective":{"owners":1}
,"owners":{"filemaker":1}
,"documentation":{"copyrighted":1,"written":1,"solely":1,"credits":1,"acknowledgments":1}
,"copyrighted":{"authorized":1}
,"authorized":{"additional":1}
,"additional":{"copies":1}
,"copies":{"distribute":1}
,"distribute":{"documentation":1}
,"written":{"permission":1}
,"permission":{"filemaker":1}
,"use":{"documentation":1}
,"solely":{"valid":1}
,"valid":{"licensed":1}
,"licensed":{"copy":1}
,"copy":{"filemaker":1}
,"software":{"all":1,"documentation":1,"license":1}
,"persons":{"companies":1}
,"companies":{"email":1}
,"email":{"addresses":1}
,"addresses":{"urls":1}
,"urls":{"listed":1,"purely":1,"informational":1}
,"listed":{"examples":1,"acknowledgments":1,"documentation":1}
,"examples":{"purely":1}
,"purely":{"fictitious":1,"coincidental":1}
,"fictitious":{"resemblance":1}
,"resemblance":{"existing":1}
,"existing":{"persons":1}
,"coincidental":{"product":1}
,"product":{"cr":1}
,"cr":{"edits":1}
,"edits":{"listed":1}
,"acknowledgments":{"documents":1,"ention":1}
,"documents":{"software":1}
,"credits":{"listed":1}
,"ention":{"third-party":1}
,"third-party":{"products":1}
,"products":{"urls":1,"visit":1}
,"informational":{"purposes":1}
,"purposes":{"constitutes":1}
,"constitutes":{"endorsement":1}
,"endorsement":{"recommendation":1}
,"recommendation":{"filemaker":1}
,"assumes":{"responsibility":1}
,"responsibility":{"regard":1}
,"regard":{"performance":1}
,"performance":{"products":1}
,"visit":{"website":1}
,"website":{"www.filemaker.com":1}
,"www.filemaker.com":{"software":1}
,"license":{"agreement":1}
,"agreement":{"dition":1}
,"dition":{"01":1}
}
;Search.control.loadWordPairs(pairs);
