var pairs =
{
"get":{"layou":1,"layoutaccess":1,"recordaccess":1,"access":1,"layout":1}
,"layou":{"taccess":1}
,"taccess":{"returns":1}
,"returns":{"number":1,"if":1,"record":1,"layout":1}
,"number":{"based":1,"filemaker":1}
,"based":{"record":1}
,"record":{"access":1}
,"access":{"privileges":1,"records":1,"filemaker":1,"layout":1,"layouts":1,"get":1}
,"privileges":{"current":1,"custom":1,"dialog":1,"account\u2019s":1,"if":1,"defined":1,"all":1,"details":1}
,"current":{"layout":1,"record":1}
,"layout":{"get":1,"privileges":1,"if":1,"read-write":1,"ignores":1,"return":1,"allows":1,"access":1}
,"layoutaccess":{"none":1,"returns":1,"get":1}
,"none":{"number":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1,"advanced":1}
,"6.0":{"earlier":1}
,"earlier":{"assign":1}
,"assign":{"access":1}
,"custom":{"layout":1}
,"dialog":{"box":1}
,"box":{"returns":1}
,"if":{"custom":1,"database":1,"layout":1}
,"account\u2019s":{"privilege":1}
,"privilege":{"set":1}
,"set":{"allow":1}
,"allow":{"access":1,"view":1,"modifiable":1}
,"records":{"via":1,"get":1}
,"via":{"layout":1}
,"view":{"access":1}
,"database":{"read-only":1}
,"read-only":{"access":1}
,"advanced":{"returns":1}
,"read-write":{"access":1}
,"modifiable":{"access":1}
,"defined":{"current":1}
,"ignores":{"current":1}
,"all":{"layouts":1}
,"layouts":{"check":1,"privileges":1,"returns":1}
,"check":{"access":1}
,"return":{"values":1}
,"values":{"get":1}
,"recordaccess":{"function":1}
,"function":{"diting":1}
,"diting":{"layouts":1}
,"details":{"limiting":1}
,"limiting":{"access":1}
,"allows":{"view-only":1}
,"view-only":{"access":1}
}
;Search.control.loadWordPairs(pairs);
