var pairs =
{
"hecking":{"file":1}
,"file":{"consistency":1,"if":1,"erify":1,"damaged":1,"verifies":1,"higher-level":1,"menu":1,"dialog":1,"want":1,"displays":1,"recover.log":1,"further":1,"scroll":1,"attempting":1,"filemaker":1}
,"consistency":{"filemaker":1,"database":1,"if":1,"check":1,"selected":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"verifies":1,"checks":1,"performing":1}
,"verifies":{"consistency":1,"internal":1}
,"database":{"file":1,"dialog":1,"administrator":1}
,"if":{"file":1,"suspect":1,"open":1,"don\u2019t":1,"consistency":1}
,"erify":{"consistency":1}
,"suspect":{"file":1}
,"damaged":{"consistency":1,"file":1,"saving":1}
,"check":{"reads":1,"read":1,"schema":1,"check":1,"consistency":1,"open":1,"place":1,"event":1,"status":1,"file":1,"revealed":1}
,"reads":{"block":1}
,"block":{"file":1,"valid":1,"properly":1,"check":1}
,"internal":{"structure":1}
,"structure":{"block":1}
,"valid":{"block":1}
,"properly":{"linked":1}
,"linked":{"blocks":1}
,"blocks":{"file":1,"checked":1,"processed":1,"found":1}
,"read":{"all":1}
,"all":{"data":1}
,"data":{"each":1,"existing":1}
,"each":{"block":1}
,"schema":{"higher-level":1}
,"higher-level":{"structures":1,"checks":1}
,"structures":{"file":1}
,"checks":{"performed":1,"consistency":1}
,"performed":{"by":1}
,"by":{"recover":1}
,"recover":{"command":1,"select":1,"recovering":1}
,"command":{"choose":1}
,"choose":{"file":1}
,"menu":{"recover":1}
,"select":{"damaged":1,"file":1}
,"dialog":{"box":1}
,"box":{"select":1,"type":1,"remains":1}
,"want":{"check":1}
,"open":{"encrypted":1,"log":1,"if":1,"file":1}
,"encrypted":{"database":1}
,"type":{"encryption":1}
,"encryption":{"password":1}
,"password":{"if":1,"database":1}
,"don\u2019t":{"encryption":1}
,"administrator":{"filemaker":1}
,"selected":{"file":1}
,"displays":{"summary":1,"separate":1}
,"summary":{"file\u2019s":1}
,"file\u2019s":{"status":1}
,"status":{"including":1,"dialog":1}
,"including":{"total":1}
,"total":{"number":1}
,"number":{"blocks":1,"bad":1,"description":1}
,"checked":{"total":1}
,"processed":{"number":1}
,"bad":{"blocks":1}
,"found":{"log":1}
,"log":{"file":1}
,"recover.log":{"file":1}
,"separate":{"window":1}
,"window":{"tab-delimited":1,"recent":1}
,"tab-delimited":{"format":1}
,"format":{"left":1}
,"left":{"right":1}
,"right":{"columns":1}
,"columns":{"show":1}
,"show":{"date":1}
,"date":{"time":1}
,"time":{"time":1,"zone":1}
,"zone":{"consistency":1}
,"place":{"filename":1}
,"filename":{"error":1}
,"error":{"number":1}
,"description":{"consistency":1}
,"event":{"save":1}
,"save":{"print":1}
,"print":{"file":1}
,"further":{"examination":1}
,"examination":{"close":1}
,"close":{"window":1}
,"recent":{"data":1}
,"existing":{"recover.log":1}
,"scroll":{"end":1}
,"end":{"file":1}
,"remains":{"open":1}
,"saving":{"compacted":1}
,"compacted":{"copy":1}
,"copy":{"file":1}
,"attempting":{"recover":1}
,"recovering":{"files":1}
,"files":{"if":1}
,"revealed":{"damage":1}
,"damage":{"cancel":1}
,"cancel":{"take":1}
,"take":{"open":1}
,"performing":{"consistency":1}
}
;Search.control.loadWordPairs(pairs);
