var pairs =
{
"perform":{"script":1,"by":1,"find":1}
,"script":{"server":1,"list":1,"want":1,"name":1,"parameter":1,"ait":1,"client":1,"result":1,"filemaker":1,"names":1,"[text":1,"email":1}
,"server":{"erforms":1,"hosting":1,"completed":1,"filemaker":1,"returns":1,"sends":1,"navigates":1,"displays":1,"[specified":1,"parameter":1,"dialog":1}
,"erforms":{"script":1}
,"list":{"calculated":1,"allows":1,"email":1,"get":1}
,"calculated":{"by":1}
,"by":{"name":1,"calculation":1,"perform":1}
,"name":{"server":1,"allows":1,"by":1,"case":1,"script":1,"invoices":1,"customer":1}
,"hosting":{"current":1}
,"current":{"file":1,"layout":1,"record":1}
,"file":{"list":1,"hosted":1,"calculation":1}
,"allows":{"select":1,"script":1}
,"select":{"script":1}
,"want":{"perform":1}
,"calculation":{"script":1,"evaluate":1}
,"case":{"sensitive":1}
,"sensitive":{"parameter":1,"runs":1}
,"parameter":{"specifies":1,"script":1,"server":1,"saves":1,"returns":1,"list":1}
,"specifies":{"script":1}
,"ait":{"completion":1}
,"completion":{"pauses":1,"selected":1,"show":1}
,"pauses":{"script":1}
,"client":{"sub-script":1,"use":1,"fetches":1}
,"sub-script":{"called":1,"email":1}
,"called":{"by":1}
,"completed":{"host":1}
,"host":{"wait":1,"client":1}
,"wait":{"completion":1}
,"selected":{"pass":1}
,"pass":{"script":1}
,"result":{"error":1,"get":1,"client":1,"server":1,"snapshot":1}
,"error":{"code":1,"running":1}
,"code":{"host":1,"filemaker":1}
,"use":{"get":1,"by":1}
,"get":{"scriptresult":1,"lasterror":1,"layoutname":1,"scriptparameter":1}
,"scriptresult":{"function":1,")]":1}
,"function":{"capture":1}
,"capture":{"result":1,"error":1}
,"lasterror":{"function":1}
,"filemaker":{"pro":1,"server":1,"cloud":1}
,"pro":{"13.0":1,"advanced":1}
,"13.0":{"current":1}
,"hosted":{"filemaker":1}
,"cloud":{"perform":1,"if":1}
,"returns":{"error":1,"result":1}
,"running":{"scripts":1}
,"scripts":{"filemaker":1,"main":1}
,"if":{"use":1}
,"advanced":{"file":1}
,"evaluate":{"data":1}
,"data":{"source":1}
,"source":{"name":1,"script":1}
,"invoices":{":do":1}
,":do":{"quarterly":1}
,"quarterly":{"billing":1}
,"billing":{"data":1}
,"names":{"case":1}
,"runs":{"script":1}
,"sends":{"current":1}
,"layout":{"name":1,"record":1,"[getvalue":1}
,"customer":{"id":1,"email":1}
,"id":{"customer":1}
,"email":{"address":1,"snapshot":1}
,"address":{"script":1,"parameter":1}
,"navigates":{"layout":1}
,"record":{"parameter":1,"emails":1,"create":1}
,"saves":{"snapshot":1}
,"snapshot":{"link":1}
,"link":{"current":1,"email":1,"server":1,"[\u0022$path":1,"\u0022]":1,"client":1}
,"emails":{"snapshot":1}
,"fetches":{"script":1}
,"displays":{"custom":1}
,"custom":{"dialog":1}
,"dialog":{"box":1,"[get":1,"getvalue":1}
,"box":{"perform":1}
,"[specified":{"list":1}
,"layoutname":{"customers":1}
,"customers":{":id":1,":email":1}
,":id":{"customers":1,"getvalue":1}
,":email":{"wait":1}
,"show":{"custom":1}
,"[get":{"scriptresult":1}
,")]":{"go":1,"enter":1,"perform":1}
,"go":{"layout":1}
,"[getvalue":{"get":1}
,"scriptparameter":{")]":1,"\u0022$path":1}
,"enter":{"find":1}
,"find":{"mode":1,"[]":1}
,"mode":{"[pause":1}
,"[pause":{"off]":1}
,"off]":{"set":1,"send":1}
,"set":{"field":1,"variable":1}
,"field":{"[customers":1}
,"[customers":{":id":1}
,"getvalue":{"get":1}
,"[]":{"set":1}
,"variable":{"[$path":1}
,"[$path":{"value:get":1}
,"value:get":{"temporarypath":1}
,"temporarypath":{"&\u0022":1}
,"&\u0022":{"snapshot.fmpsl":1}
,"snapshot.fmpsl":{"\u0022]":1}
,"\u0022]":{"save":1,"exit":1,"automating":1}
,"save":{"records":1}
,"records":{"snapshot":1}
,"[\u0022$path":{"current":1}
,"create":{"folders":1}
,"folders":{"off]":1}
,"send":{"mail":1}
,"mail":{"[send":1}
,"[send":{"via":1}
,"via":{"smtp":1}
,"smtp":{"server":1}
,"\u0022$path":{"\u0022]":1}
,"exit":{"script":1}
,"[text":{"result":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
,"main":{"script":1}
}
;Search.control.loadWordPairs(pairs);
