var pairs =
{
"get":{"recordopen":1,"recordopencount":1,"record":1,"uncommitted":1}
,"recordopen":{"count":1}
,"count":{"returns":1,"get":1}
,"returns":{"total":1,"number":1,"if":1}
,"total":{"number":1}
,"number":{"open":1,"filemaker":1}
,"open":{"records":1,"uncommitted":1,"count":1}
,"records":{"current":1,"haven\u2019t":1}
,"current":{"found":1,"user":1,"calculation":1,"window":1}
,"found":{"set":1}
,"set":{"haven\u2019t":1,"including":1}
,"haven\u2019t":{"saved":1}
,"saved":{"get":1,"if":1}
,"recordopencount":{"none":1,"get":1}
,"none":{"number":1}
,"filemaker":{"pro":1}
,"pro":{"8.0":1}
,"8.0":{"function":1}
,"function":{"returns":1,"evaluated":1}
,"uncommitted":{"records":1,"related":1}
,"including":{"uncommitted":1}
,"related":{"records":1}
,"user":{"hasn\u2019t":1}
,"hasn\u2019t":{"saved":1}
,"if":{"context":1,"record":1}
,"context":{"current":1,"evaluated":1}
,"calculation":{"function":1}
,"evaluated":{"based":1}
,"based":{"context":1}
,"window":{"returns":1}
,"record":{"related":1,"open":1}
}
;Search.control.loadWordPairs(pairs);
