var pairs =
{
"ormatting":{"ayout":1}
,"ayout":{"change":1,"saving":1}
,"change":{"formatting":1,"fill":1}
,"formatting":{"attributes":1,"saved":1}
,"attributes":{"layout":1}
,"layout":{"objects":1,"parts":1,"background":1,"if":1,"layers":1,"save":1,"theme":1}
,"objects":{"layout":1,"parts":1,"layered":1,"foreground":1,"formatting":1,"creating":1}
,"parts":{"layout":1,"background":1,"display":1,"objects":1,"foreground":1}
,"background":{"customize":1,"solid":1,"layout":1,"show":1,"don\u2019t":1,"parts":1}
,"customize":{"layouts":1,"color":1}
,"layouts":{"fill":1}
,"fill":{"objects":1,"transparent":1,"layout":1,"line":1}
,"solid":{"color":1}
,"color":{"color":1,"gradient":1,"line":1}
,"gradient":{"image":1}
,"image":{"addition":1}
,"addition":{"objects":1}
,"display":{"border":1}
,"border":{"customize":1,"layout":1}
,"line":{"style":1}
,"style":{"border":1,"shadows":1,"applied":1}
,"layered":{"layout":1}
,"if":{"set":1,"change":1}
,"set":{"fill":1}
,"transparent":{"objects":1,"setting":1}
,"foreground":{"objects":1,"transparent":1}
,"show":{"if":1}
,"don\u2019t":{"result":1}
,"result":{"fill":1}
,"setting":{"fill":1}
,"shadows":{"padding":1}
,"padding":{"layout":1}
,"layers":{"including":1}
,"including":{"background":1}
,"saved":{"current":1}
,"current":{"layout":1}
,"save":{"style":1}
,"applied":{"objects":1}
,"creating":{"styles":1}
,"styles":{"ayout":1}
,"saving":{"layout":1}
}
;Search.control.loadWordPairs(pairs);
