var pairs =
{
"setting":{"eys":1,"keys":1}
,"eys":{"moving":1}
,"moving":{"fields":1}
,"fields":{"field":1,"don\u2019t":1,"inspector":1,"windows":1}
,"field":{"it\u2019s":1,"tab":1,"enter":1,"by":1}
,"it\u2019s":{"go":1}
,"go":{"next":1}
,"next":{"field":1,"object":1}
,"tab":{"key":1,"characters":1,"behavior":1,"character":1,"windows":1}
,"key":{"return":1,"enter":1,"combination":1,"main":1,"tab":1,"set":1}
,"return":{"key":1,"characters":1}
,"enter":{"key":1,"tab":1,"keys":1}
,"combination":{"keys":1}
,"keys":{"setting":1,"data":1,"want":1,"main":1,"exit":1}
,"data":{"entry":1,"data":1,"tab":1}
,"entry":{"easier":1}
,"easier":{"fields":1}
,"don\u2019t":{"enter":1}
,"characters":{"return":1,"layout":1}
,"layout":{"mode":1}
,"mode":{"select":1}
,"select":{"fields":1,"keys":1}
,"inspector":{"data":1}
,"behavior":{"go":1}
,"object":{"select":1}
,"want":{"use":1}
,"use":{"exiting":1}
,"exiting":{"fields":1}
,"windows":{"keyboards":1,"option-tab":1}
,"keyboards":{"contain":1}
,"contain":{"two":1}
,"two":{"enter":1}
,"main":{"part":1}
,"part":{"keyboard":1}
,"keyboard":{"numeric":1,"behaves":1}
,"numeric":{"keypad":1}
,"keypad":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"enter":1}
,"behaves":{"return":1}
,"set":{"go":1,"keys":1}
,"character":{"field":1}
,"by":{"pressing":1}
,"pressing":{"ctrl":1}
,"ctrl":{"tab":1}
,"option-tab":{"macos":1}
,"macos":{"set":1}
,"exit":{"field":1}
}
;Search.control.loadWordPairs(pairs);
