var pairs =
{
"creating":{"kiosk":1}
,"kiosk":{"solution":1,"mode":1,"account":1}
,"solution":{"note":1,"display":1,"saved":1,"solution":1,"options":1,"quickly":1,"setting":1,"database":1,"open":1,"by":1}
,"note":{"feature":1}
,"feature":{"use":1}
,"use":{"advanced":1,"basic":1}
,"advanced":{"tools":1}
,"tools":{"general":1,"solution":1,"menu":1}
,"general":{"preference":1}
,"preference":{"selected":1}
,"selected":{"ad":1,"database":1}
,"ad":{"vanced":1}
,"vanced":{"tools":1}
,"display":{"kiosk":1}
,"mode":{"create":1,"database":1,"non-admin":1,"ignored":1,"change":1}
,"create":{"account":1,"specific":1,"options":1,"limited":1}
,"account":{"limited":1,"clear":1,"enable":1,"ty":1,"name":1}
,"limited":{"privilege":1,"access":1}
,"privilege":{"set":1}
,"set":{"create":1,"privilege":1,"list":1,"dialog":1,"name":1,"ensure":1}
,"specific":{"kiosk":1}
,"clear":{"default":1,"manage":1,"log":1}
,"default":{"option":1}
,"option":{"logging":1}
,"logging":{"file":1}
,"file":{"admin":1,"menu":1,"list":1,"select":1,"saving":1,"options":1,"quit":1,"provide":1,"each":1,"place":1,"primary":1,"include":1}
,"admin":{"account":1}
,"enable":{"kiosk":1}
,"database":{"pen":1,"files":1,"solution":1}
,"pen":{"choose":1}
,"choose":{"file":1,"tools":1}
,"menu":{"manage":1,"developer":1,"file":1,"button":1}
,"manage":{"security":1,"extended":1}
,"security":{"if":1,"dialog":1,"settings":1}
,"if":{"manage":1,"developer":1,"add":1,"bind":1,"solution":1}
,"dialog":{"box":1}
,"box":{"displays":1,"privilege":1}
,"displays":{"detailed":1}
,"detailed":{"security":1}
,"settings":{"use":1,"load":1,"add":1,"required":1,"choosing":1,"file":1}
,"basic":{"setup":1}
,"setup":{"cl":1}
,"cl":{"ick":1}
,"ick":{"new":1,"close":1}
,"new":{"account":1,"privilege":1,"folder":1}
,"ty":{"pe":1}
,"pe":{"account":1}
,"name":{"nd":1,"description":1}
,"nd":{"select":1}
,"select":{"new":1,"all":1,"options":1,"developer":1,"enable":1}
,"list":{"edit":1,"primary":1}
,"edit":{"privilege":1}
,"description":{"layouts":1}
,"layouts":{"value":1}
,"value":{"lists":1}
,"lists":{"scripts":1}
,"scripts":{"select":1}
,"all":{"view":1,"access":1,"database":1,"runtime":1}
,"view":{"all":1}
,"access":{"clear":1,"privilege":1,"primary":1,"kiosk":1}
,"extended":{"privileges":1}
,"privileges":{"checkbox":1}
,"checkbox":{"select":1}
,"options":{"required":1,"select":1,"developer":1,"open":1}
,"required":{"cl":1,"setting":1,"create":1}
,"close":{"all":1}
,"files":{"customize":1,"want":1,"double-click":1,"developer":1,"runtime":1,"project":1,"new":1}
,"customize":{"choose":1,"if":1}
,"developer":{"utilities":1,"solution":1}
,"utilities":{"if":1,"database":1,"settings":1,"copy":1}
,"saved":{"settings":1}
,"load":{"settings":1}
,"add":{"locate":1,"multiple":1}
,"locate":{"files":1}
,"want":{"customize":1}
,"multiple":{"files":1}
,"double-click":{"file":1}
,"primary":{"file":1}
,"setting":{"up":1,"bind":1}
,"up":{"files":1}
,"non-admin":{"accounts":1}
,"accounts":{"se":1,"full":1}
,"se":{"lect":1}
,"lect":{"options":1}
,"quickly":{"repeat":1}
,"repeat":{"process":1}
,"process":{"by":1}
,"by":{"clicking":1,"accounts":1}
,"clicking":{"save":1}
,"save":{"settings":1}
,"choosing":{"folder":1}
,"folder":{"location":1,"if":1,"created":1,"named":1}
,"location":{"settings":1}
,"saving":{"solution":1}
,"bind":{"files":1}
,"runtime":{"application":1,"files":1,"solution":1}
,"application":{"developer":1,"cleanly":1}
,"copy":{"selected":1,"all":1}
,"project":{"folder":1}
,"created":{"inside":1}
,"inside":{"project":1}
,"named":{"runtime":1}
,"open":{"choose":1,"tab":1,"primary":1}
,"tab":{"clear":1}
,"log":{"kiosk":1}
,"ignored":{"if":1}
,"full":{"access":1}
,"ensure":{"users":1}
,"users":{"access":1}
,"quit":{"application":1}
,"cleanly":{"each":1}
,"each":{"auxiliary":1}
,"auxiliary":{"file":1}
,"provide":{"startup":1}
,"startup":{"script":1}
,"script":{"primary":1,"open":1}
,"place":{"main":1}
,"main":{"menu":1}
,"button":{"runs":1,"create":1}
,"runs":{"startup":1}
,"include":{"exit":1}
,"exit":{"button":1}
,"change":{"default":1}
}
;Search.control.loadWordPairs(pairs);
