var pairs =
{
"angebeacons":{"eturns":1}
,"eturns":{"list":1}
,"list":{"ibeacons":1}
,"ibeacons":{"proximity":1,"search":1,"specific":1,"all":1,"group":1,"toys":1,"minor":1,"measured":1,"match":1,"uuid":1}
,"proximity":{"ios":1,"-a":1,"ibeacon":1,"value":1}
,"ios":{"device":1,"location":1}
,"device":{"rangebeacons":1,"ibeacon":1,"accuracy":1}
,"rangebeacons":{"uuid":1,"d9b9ec1f-xxxx-yyyy-80a9-1e39d4cea95c":1}
,"uuid":{"timeout":1,"-the":1,"identifies":1,"d9b9ec1f-xxxx-yyyy-80a9-1e39d4cea95c":1,"major":1}
,"timeout":{"major":1,"-the":1,"function":1}
,"major":{"minor":1,"-the":1,"value":1}
,"minor":{"uuid":1,"-the":1,"value":1}
,"-the":{"universally":1,"number":1,"value":1,"accuracy":1,"received":1}
,"universally":{"unique":1}
,"unique":{"identifier":1}
,"identifier":{"ibeacons":1,"each":1}
,"search":{"uuid":1}
,"identifies":{"ibeacons":1}
,"specific":{"type":1,"organization":1,"branch":1,"ibeacons":1}
,"type":{"specific":1}
,"organization":{"ibeacons":1}
,"all":{"branches":1,"ibeacons":1,"nearby":1}
,"branches":{"department":1}
,"department":{"store":1}
,"store":{"share":1}
,"share":{"uuid":1,"major":1,"minor":1}
,"number":{"seconds":1,"indicating":1}
,"seconds":{"wait":1,"major":1,"rangebeacons":1,"mobile":1}
,"wait":{"returning":1}
,"returning":{"value":1}
,"value":{"if":1,"seconds":1,"identifying":1,"minor":1,"parameters":1,"measured":1,"helps":1,"negative":1,"accuracy":1,"10":1,"returns":1}
,"if":{"timeout":1,"ibeacons":1,"ios":1,"query":1}
,"function":{"returns":1}
,"returns":{"value":1,"uuid":1,"unknown":1,"empty":1,"question":1,"all":1,"result":1,"ibeacons":1}
,"identifying":{"group":1,"specific":1}
,"group":{"ibeacons":1}
,"branch":{"department":1}
,"toys":{"specific":1}
,"parameters":{"braces":1}
,"braces":{"optional":1}
,"optional":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1,"go":1}
,"pro":{"15.0":1}
,"15.0":{"filemaker":1}
,"go":{"returns":1}
,"each":{"identified":1}
,"identified":{"ibeacon":1}
,"ibeacon":{"major":1,"returns":1,"determined":1,"close":1,"ios":1,"value":1}
,"-a":{"number":1}
,"indicating":{"relative":1}
,"relative":{"proximity":1}
,"unknown":{"proximity":1}
,"determined":{"ibeacon":1,"rssi":1}
,"close":{"ios":1}
,"accuracy":{"-the":1,"proximity":1,"determined":1}
,"measured":{"meters":1,"decibels":1}
,"meters":{"ibeacon":1}
,"helps":{"differentiate":1}
,"differentiate":{"ibeacons":1}
,"negative":{"value":1}
,"rssi":{"-the":1}
,"received":{"signal":1}
,"signal":{"strength":1}
,"strength":{"ibeacons":1}
,"decibels":{"if":1}
,"match":{"criteria":1}
,"criteria":{"function":1}
,"empty":{"string":1}
,"string":{"if":1}
,"location":{"services":1}
,"services":{"setting":1}
,"setting":{"function":1}
,"query":{"valid":1}
,"valid":{"function":1}
,"question":{"mark":1}
,"mark":{"rangebeacons":1}
,"d9b9ec1f-xxxx-yyyy-80a9-1e39d4cea95c":{"returns":1,"10":1,"14.68":1,"18.96":1,"30":1,"20":1}
,"nearby":{"ibeacons":1}
,"10":{"-1.00":1,"returns":1,"minor":1}
,"-1.00":{"d9b9ec1f-xxxx-yyyy-80a9-1e39d4cea95c":1}
,"14.68":{"-79":1}
,"-79":{"d9b9ec1f-xxxx-yyyy-80a9-1e39d4cea95c":1}
,"18.96":{"-81":1}
,"-81":{"rangebeacons":1}
,"30":{"returns":1,"seconds":1}
,"result":{"30":1,"20":1}
,"20":{"10":1,"seconds":1}
,"mobile":{"phone":1,"network":1}
,"phone":{"cell":1,"mobile":1}
,"cell":{"phone":1}
,"network":{"filemaker":1}
}
;Search.control.loadWordPairs(pairs);
