var pairs =
{
"updating":{"data":1}
,"data":{"filemaker":1,"sources":1,"odbc":1,"exit":1,"records":1,"controlled":1,"table":1,"source":1,"including":1,"entered":1,"entry":1,"entering":1,"external":1,"choose":1}
,"filemaker":{"odbc":1,"data":1,"saves":1,"software":1,"appears":1,"ptimistic":1,"automatically":1,"displays":1,"updates":1,"schema":1,"pro":1,"knowledge":1,"identify":1}
,"odbc":{"data":1,"tables":1,"table":1,"source":1}
,"sources":{"general":1,"committing":1}
,"general":{"committing":1}
,"committing":{"data":1,"filemaker":1}
,"saves":{"external":1}
,"external":{"data":1,"record":1,"field":1,"database":1}
,"exit":{"field":1}
,"field":{"move":1,"names":1,"list":1,"schema":1,"odbc":1,"external":1,"options":1,"missing":1,"objects":1}
,"move":{"record":1}
,"record":{"committing":1,"data":1,"find":1}
,"records":{"external":1,"menu":1}
,"controlled":{"by":1}
,"by":{"software":1,"users":1}
,"software":{"interactively":1,"actions":1}
,"interactively":{"by":1}
,"users":{"filemaker":1}
,"actions":{"take":1}
,"take":{"assure":1}
,"assure":{"record":1}
,"table":{"schema":1,"want":1,"list":1,"field":1,"relationships":1,"missing":1,"renamed":1,"data":1,"view":1}
,"schema":{"open":1,"odbc":1,"data":1,"new":1,"filemaker":1}
,"open":{"file":1}
,"file":{"link":1,"menu":1}
,"link":{"external":1}
,"source":{"browse":1,"hadow":1,"updated":1,"reappear":1,"doesn\u2019t":1,"missing":1,"database":1,"synchronize":1}
,"browse":{"mode":1}
,"mode":{"choose":1}
,"choose":{"records":1,"file":1,"table":1}
,"menu":{"refresh":1,"manage":1}
,"refresh":{"window":1,"data":1}
,"window":{"current":1,"script":1}
,"current":{"data":1}
,"including":{"data":1}
,"entered":{"by":1}
,"appears":{"flush":1}
,"flush":{"internal":1}
,"internal":{"cache":1}
,"cache":{"refresh":1}
,"script":{"step":1}
,"step":{"odbc":1}
,"tables":{"filemaker":1}
,"ptimistic":{"locking":1}
,"locking":{"control":1}
,"control":{"data":1}
,"entry":{"filemaker":1}
,"automatically":{"refresh":1}
,"entering":{"data":1}
,"find":{"odbc":1}
,"manage":{"database":1}
,"database":{"manage":1,"dialog":1,"field":1,"table":1,"renamed":1}
,"dialog":{"box":1}
,"box":{"fields":1}
,"fields":{"tab":1,"odbc":1,"if":1}
,"tab":{"choose":1}
,"want":{"table":1}
,"list":{"filemaker":1,"sync":1}
,"displays":{"fields":1,"table":1}
,"names":{"italics":1}
,"italics":{"select":1}
,"select":{"external":1}
,"sync":{"filemaker":1,"field":1}
,"updates":{"schema":1}
,"hadow":{"changed":1}
,"changed":{"field":1}
,"updated":{"filemaker":1}
,"new":{"missing":1}
,"missing":{"fields":1,"table":1,"column":1,"data":1,"filemaker":1}
,"if":{"delete":1,"odbc":1,"selected":1}
,"delete":{"field":1}
,"relationships":{"graph":1}
,"graph":{"sync":1,"field":1}
,"reappear":{"fter":1}
,"fter":{"synchronize":1}
,"synchronize":{"field":1}
,"options":{"set":1}
,"set":{"filemaker":1}
,"pro":{"advanced":1}
,"advanced":{"reset":1}
,"reset":{"if":1,"option":1}
,"doesn\u2019t":{"force":1}
,"force":{"option":1}
,"option":{"if":1,"synchronizing":1,"errors":1}
,"selected":{"empty":1}
,"empty":{"validation":1}
,"validation":{"option":1}
,"synchronizing":{"reset":1}
,"errors":{"troubleshooting":1}
,"troubleshooting":{"visit":1}
,"visit":{"filemaker":1}
,"knowledge":{"base":1}
,"base":{"error":1}
,"error":{"message":1,"displayed":1}
,"message":{"displays":1,"connection":1}
,"renamed":{"removed":1}
,"removed":{"external":1,"connection":1}
,"column":{"renamed":1}
,"connection":{"fails":1,"failure":1}
,"fails":{"error":1}
,"failure":{"displayed":1}
,"displayed":{"primary":1,"relationships":1}
,"primary":{"key":1}
,"key":{"missing":1,"odbc":1}
,"identify":{"unique":1}
,"unique":{"key":1}
,"view":{"error":1}
,"objects":{"display":1}
,"display":{"data":1}
}
;Search.control.loadWordPairs(pairs);
