var pairs =
{
"self-joining":{"relationships":1,"relationship":1}
,"relationships":{"self-joining":1,"graph":1,"edit":1}
,"relationship":{"self-join":1,"match":1,"relationships":1,"forming":1,"add":1,"button":1,"dialog":1,"choose":1,"select":1,"returns":1}
,"self-join":{"relationship":1,"portal":1,"examples":1,"search":1,"self":1}
,"match":{"fields":1,"field":1}
,"fields":{"defined":1,"employees:manager":1,"self-join":1}
,"defined":{"table":1}
,"table":{"filemaker":1,"basing":1,"display":1,"all":1,"named":1,"use":1,"choose":1,"each":1,"occurrence":1,"line":1,"relationships":1,"button":1}
,"filemaker":{"pro":1,"knowledge":1}
,"pro":{"advanced":1}
,"advanced":{"generates":1}
,"generates":{"second":1}
,"second":{"occurrence":1,"table":1}
,"occurrence":{"table":1,"define":1,"rename":1}
,"basing":{"relationship":1}
,"graph":{"prevents":1,"select":1,"creating":1,"two":1,"duplicate":1}
,"prevents":{"relationship":1}
,"forming":{"cycle":1}
,"cycle":{"impossible":1}
,"impossible":{"evaluate":1}
,"evaluate":{"use":1}
,"use":{"self-join":1,"table":1,"self-joining":1}
,"portal":{"layout":1}
,"layout":{"current":1}
,"current":{"table":1}
,"display":{"subset":1}
,"subset":{"data":1}
,"data":{"current":1}
,"all":{"employees":1}
,"employees":{"report":1,"relationships":1,"relationship":1,"managers":1,"value":1,":manager":1}
,"report":{"each":1}
,"each":{"manager":1,"relationship":1,"table":1}
,"manager":{"use":1}
,"named":{"employees":1}
,"select":{"table":1,"match":1}
,"add":{"relationship":1,"type":1}
,"button":{"orking":1,"create":1}
,"orking":{"ith":1}
,"ith":{"relationships":1}
,"creating":{"nd":1}
,"nd":{"changing":1}
,"changing":{"relationships":1}
,"edit":{"relationship":1}
,"dialog":{"box":1}
,"box":{"table":1}
,"choose":{"table":1,"employees":1}
,"field":{"each":1}
,"define":{"relationship":1,"self-joining":1}
,"type":{"name":1}
,"name":{"second":1}
,"rename":{"employees":1}
,"managers":{"match":1,":employee":1}
,"employees:manager":{"id":1}
,"id":{"managers":1,"relationship":1,"value":1,"relationships":1}
,":employee":{"id":1}
,"returns":{"related":1}
,"related":{"records":1}
,"records":{"employees":1}
,"value":{"employees":1,"managers":1}
,":manager":{"id":1}
,"two":{"occurrences":1}
,"occurrences":{"table":1}
,"line":{"fields":1}
,"examples":{"self-join":1}
,"search":{"filemaker":1}
,"knowledge":{"base":1}
,"base":{"select":1}
,"duplicate":{"table":1}
,"create":{"self-join":1}
,"self":{"join":1}
,"join":{"define":1}
}
;Search.control.loadWordPairs(pairs);
