var pairs =
{
"est":{"practices":1}
,"practices":{"designing":1}
,"designing":{"layouts":1,"layout":1}
,"layouts":{"sketch":1,"identify":1,"diverse":1,"paper":1,"visually":1,"onlayoutenter":1,"each":1,"optimally":1,"devices":1,"dynamic":1,"file":1,"creating":1,"objects":1,"use":1,"design":1}
,"sketch":{"layouts":1}
,"identify":{"devices":1}
,"devices":{"access":1,"vary":1,"layout":1,"filemaker":1}
,"access":{"layout":1}
,"layout":{"understand":1,"consistently":1,"objects":1,"performance":1,"design":1,"devices":1,"designed":1,"adapt":1,"range":1,"expands":1,"creating":1,"each":1,"script":1,"bar":1,"across":1,"horizontal":1,"background":1,"layout":1,"theme":1,"filemaker":1,"undo":1,"state":1,"characteristic":1,"consistent":1,"styles":1,"developing":1,"list":1}
,"understand":{"capabilities":1,"each":1}
,"capabilities":{"each":1}
,"each":{"filemaker":1,"device":1,"layout":1,"product":1}
,"filemaker":{"product":1,"ro":1,"go":1,"webdirect":1,"product\u2019s":1,"server":1,"data":1,"pro":1}
,"product":{"use":1,"unique":1,"filemaker":1}
,"use":{"screen":1,"theme":1,"predefined":1,"unstored":1,"filemaker":1}
,"screen":{"stencils":1,"size":1,"each":1,"stencil":1}
,"stencils":{"positioning":1,"button":1,"help":1,"visible":1}
,"positioning":{"tools":1}
,"tools":{"use":1,"help":1}
,"theme":{"suits":1,"characteristics":1,"change":1,"dialog":1,"button":1,"simple":1,"if":1,"layout":1,"remains":1,"displayed":1,"changing":1,"apply":1}
,"suits":{"purpose":1}
,"purpose":{"layout":1}
,"consistently":{"duplicate":1,"layouts":1,"all":1}
,"duplicate":{"layout":1,"attributes":1}
,"objects":{"optimize":1,"based":1,"if":1,"guides":1,"vertically":1,"fields":1,"use":1,"consistently":1,"opying":1,"improve":1,"displayed":1,"layout":1,"create":1}
,"optimize":{"layout":1}
,"performance":{"test":1,"screen":1,"layout":1}
,"test":{"layouts":1,"symbols":1}
,"diverse":{"audience":1}
,"audience":{"addition":1,"putting":1}
,"addition":{"planning":1}
,"planning":{"structure":1}
,"structure":{"database":1}
,"database":{"creating":1}
,"creating":{"custom":1,"filemaker":1,"layout":1,"styles":1}
,"custom":{"app":1,"web":1,"styles":1,"themes":1}
,"app":{"ketch":1}
,"ketch":{"layouts":1}
,"paper":{"onscreen":1}
,"onscreen":{"creating":1}
,"ro":{"advanced":1}
,"advanced":{"sketches":1,"tools":1,"returns":1,"custom":1}
,"sketches":{"help":1}
,"help":{"resolve":1,"create":1,"design":1,"quickly":1,"align":1}
,"resolve":{"design":1}
,"design":{"problems":1,"layout":1,"each":1,"layouts":1}
,"problems":{"communicate":1}
,"communicate":{"ideas":1}
,"ideas":{"save":1}
,"save":{"time":1,"theme":1}
,"time":{"sketching":1,"sizing":1}
,"sketching":{"process":1}
,"process":{"help":1}
,"create":{"layouts":1,"format":1,"custom":1}
,"visually":{"balanced":1}
,"balanced":{"provide":1}
,"provide":{"clear":1,"optimal":1}
,"clear":{"path":1}
,"path":{"users":1}
,"users":{"follow":1,"design":1,"layouts":1}
,"follow":{"devices":1}
,"vary":{"by":1}
,"by":{"hardware":1}
,"hardware":{"network":1}
,"network":{"performance":1}
,"size":{"resolution":1,"position":1,"number":1}
,"resolution":{"if":1}
,"if":{"identify":1,"wide":1,"layout":1,"change":1,"undo":1}
,"designed":{"desktop":1}
,"desktop":{"computer":1,"resolutions":1}
,"computer":{"ios":1}
,"ios":{"device":1}
,"device":{"provide":1,"design":1,"sizes":1,"setting":1,"direct":1}
,"optimal":{"solution":1}
,"solution":{"users":1,"designing":1}
,"adapt":{"each":1}
,"range":{"device":1}
,"sizes":{"configure":1}
,"configure":{"auto-resize":1}
,"auto-resize":{"options":1}
,"options":{"layout":1}
,"based":{"layout\u2019s":1}
,"layout\u2019s":{"height":1}
,"height":{"width":1}
,"width":{"ensures":1}
,"ensures":{"layout":1}
,"expands":{"fill":1}
,"fill":{"entire":1,"text":1}
,"entire":{"screen":1}
,"setting":{"auto-resize":1}
,"wide":{"variety":1}
,"variety":{"devices":1}
,"direct":{"users":1}
,"onlayoutenter":{"script":1}
,"script":{"trigger":1,"step":1,"triggers":1}
,"trigger":{"get":1}
,"get":{"systemplatform":1}
,"systemplatform":{"function":1}
,"function":{"go":1}
,"go":{"layout":1,"capture":1,"development":1,"choose":1,"designing":1}
,"step":{"each":1}
,"unique":{"features":1}
,"features":{"filemaker":1,"design":1}
,"capture":{"signatures":1}
,"signatures":{"filemaker":1}
,"webdirect":{"accessible":1,"guide":1}
,"accessible":{"compatible":1}
,"compatible":{"web":1}
,"web":{"browser":1,"publishing":1}
,"browser":{"understand":1}
,"product\u2019s":{"features":1}
,"development":{"guide":1}
,"guide":{"filemaker":1,"arrow":1}
,"server":{"custom":1}
,"publishing":{"guide":1}
,"data":{"api":1}
,"api":{"guide":1}
,"arrow":{"screen":1}
,"button":{"layout":1,"status":1}
,"bar":{"display":1}
,"display":{"screen":1,"dialog":1}
,"optimally":{"ipad":1}
,"ipad":{"iphone":1}
,"iphone":{"common":1}
,"common":{"desktop":1,"symbols":1}
,"resolutions":{"multiple":1}
,"multiple":{"screen":1,"layouts":1,"files":1}
,"visible":{"time":1}
,"sizing":{"layouts":1}
,"quickly":{"precisely":1,"duplicate":1}
,"precisely":{"size":1}
,"position":{"align":1}
,"align":{"layout":1}
,"guides":{"help":1,"visual":1,"dynamic":1,"layout":1,"screen":1}
,"vertically":{"horizontally":1}
,"horizontally":{"layout":1}
,"across":{"multiple":1}
,"dynamic":{"guides":1}
,"visual":{"cues":1}
,"cues":{"layout":1}
,"horizontal":{"vertical":1}
,"vertical":{"guides":1}
,"stencil":{"displayed":1}
,"displayed":{"theme":1,"if":1,"simultaneously":1}
,"characteristics":{"layout":1}
,"background":{"color":1}
,"color":{"field":1}
,"field":{"borders":1}
,"borders":{"fill":1}
,"text":{"attributes":1,"objects":1}
,"attributes":{"text":1,"applied":1,"layout":1,"ayout":1}
,"fields":{"select":1}
,"select":{"theme":1}
,"change":{"theme":1,"new":1}
,"dialog":{"box":1}
,"box":{"suits":1,"theme":1}
,"status":{"toolbar":1}
,"toolbar":{"display":1,"quickly":1}
,"simple":{"lines":1}
,"lines":{"colors":1}
,"colors":{"styles":1}
,"styles":{"choose":1,"filemaker":1,"create":1,"file":1,"save":1,"consistently":1,"ayout":1,"overriding":1,"common":1}
,"choose":{"minimalist":1,"touch":1}
,"minimalist":{"theme":1,"touch":1}
,"touch":{"themes":1,"if":1}
,"themes":{"minimalist":1,"custom":1,"styles":1}
,"undo":{"change":1,"filemaker":1,"redo":1}
,"new":{"theme":1}
,"remains":{"formatting":1}
,"formatting":{"attributes":1}
,"applied":{"previous":1,"new":1}
,"previous":{"applying":1}
,"applying":{"new":1}
,"pro":{"advanced":1}
,"returns":{"layout":1}
,"state":{"applied":1}
,"changing":{"theme":1}
,"characteristic":{"well-designed":1}
,"well-designed":{"layout":1}
,"consistent":{"appearance":1}
,"appearance":{"layout":1}
,"predefined":{"object":1}
,"object":{"styles":1}
,"format":{"objects":1,"painter":1}
,"file":{"multiple":1,"it\u2019s":1}
,"files":{"solution":1}
,"it\u2019s":{"layout":1}
,"developing":{"all":1}
,"all":{"styles":1,"layouts":1}
,"apply":{"styles":1}
,"ayout":{"format":1,"undo":1}
,"painter":{"tool":1}
,"tool":{"format":1,"button":1}
,"opying":{"formatting":1}
,"redo":{"commands":1}
,"commands":{"edit":1}
,"edit":{"menu":1}
,"menu":{"incrementally":1}
,"incrementally":{"remove":1}
,"remove":{"replace":1}
,"replace":{"layout":1}
,"improve":{"performance":1}
,"list":{"view":1}
,"view":{"portals":1}
,"portals":{"minimize":1,"panel":1}
,"minimize":{"number":1,"size":1,"use":1}
,"number":{"layout":1,"portals":1,"shadows":1}
,"simultaneously":{"minimize":1}
,"panel":{"controls":1}
,"controls":{"minimize":1}
,"shadows":{"minimize":1}
,"unstored":{"calculations":1}
,"calculations":{"script":1}
,"triggers":{"create":1}
,"overriding":{"existing":1}
,"existing":{"themes":1}
,"symbols":{"misinterpreted":1,"images":1}
,"misinterpreted":{"contexts":1}
,"contexts":{"flag":1}
,"flag":{"icon":1}
,"icon":{"warning":1,"success":1}
,"warning":{"icon":1}
,"success":{"cultures":1}
,"cultures":{"test":1}
,"images":{"diverse":1}
,"putting":{"layouts":1}
}
;Search.control.loadWordPairs(pairs);
