var pairs =
{
"if":{"valuates":1,"calculation":1,"step":1,"script":1,"records":1,"[get":1,"performs":1,"record":1,"else":1,"sort":1}
,"valuates":{"boolean":1}
,"boolean":{"calculation":1}
,"calculation":{"performs":1,"want":1,"result":1,"evaluates":1,"if":1,"unsuccessful":1}
,"performs":{"conditional":1,"find":1}
,"conditional":{"action":1}
,"action":{"based":1}
,"based":{"evaluation":1}
,"evaluation":{"sp":1}
,"sp":{"ecif":1}
,"ecif":{"boolean":1}
,"want":{"evaluated":1,"search":1}
,"evaluated":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"if":1}
,"result":{"number":1,"zero":1}
,"number":{"except":1,"calculation":1}
,"except":{"zero":1}
,"zero":{"calculation":1,"data":1}
,"evaluates":{"true":1,"false":1}
,"true":{"subsequent":1}
,"subsequent":{"script":1}
,"script":{"steps":1,"step":1,"editing":1,"search":1,"sub-script":1,"[specified":1,"find":1}
,"steps":{"executed":1}
,"executed":{"if":1}
,"data":{"resolve":1}
,"resolve":{"number":1}
,"false":{"subsequent":1,"use":1}
,"step":{"end":1,"if":1,"indentation":1,"script":1,"add":1,"else":1}
,"end":{"if":1}
,"indentation":{"use":1}
,"use":{"if":1,"get":1}
,"editing":{"pane":1}
,"pane":{"automatically":1}
,"automatically":{"enters":1}
,"enters":{"end":1}
,"add":{"additional":1}
,"additional":{"conditions":1}
,"conditions":{"by":1}
,"by":{"else":1}
,"else":{"if":1,"script":1,"sort":1,"go":1,"show":1}
,"unsuccessful":{"evaluate":1}
,"evaluate":{"false":1}
,"get":{"lasterror":1}
,"lasterror":{"function":1}
,"function":{"capture":1}
,"capture":{"errors":1}
,"errors":{"performs":1}
,"find":{"if":1,"[restore]":1,"records":1,"invoices":1,"[]":1}
,"records":{"found":1,"sorts":1,"sort":1,"[restore":1,"records":1,"record":1,"end":1}
,"found":{"displays":1,"sorts":1,"set":1,"\u0022]":1,"invoice":1,"invoices":1,"records":1,"want":1}
,"displays":{"all":1,"custom":1}
,"all":{"records":1}
,"sorts":{"perform":1,"found":1}
,"perform":{"find":1,"script":1}
,"[restore]":{"if":1}
,"[get":{"foundcount":1,"lastmessagechoice":1}
,"foundcount":{"=0]":1,"=1]":1}
,"=0]":{"show":1}
,"show":{"all":1,"custom":1}
,"sort":{"records":1}
,"[restore":{"dialog":1}
,"dialog":{"off]":1,"box":1,"[\u0022":1}
,"off]":{"end":1,"automating":1}
,"custom":{"dialog":1}
,"box":{"if":1,"user":1}
,"set":{"perform":1}
,"[\u0022":{"find":1,"invoice":1,"invoices":1,"record":1}
,"\u0022]":{"else":1,"end":1,"if":1}
,"record":{"found":1}
,"invoice":{"details":1}
,"details":{"layout":1,"\u0022]":1}
,"layout":{"if":1,"perform":1,"[\u0022":1}
,"invoices":{"layout":1,"\u0022]":1,"script":1,"parameter":1}
,"=1]":{"go":1,"calls":1}
,"go":{"layout":1}
,"user":{"run":1}
,"run":{"find":1}
,"search":{"if":1,"\u0022]":1}
,"[]":{"if":1}
,"lastmessagechoice":{"=1]":1}
,"calls":{"script":1}
,"sub-script":{"perform":1}
,"[specified":{"list":1}
,"list":{"find":1}
,"parameter":{"else":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
,"scripts":{"script":1}
}
;Search.control.loadWordPairs(pairs);
