var pairs =
{
"insert":{"current":1}
,"current":{"time":1,"system":1,"value":1,"layout":1}
,"time":{"astes":1,"ield":1,"last":1,"[select":1,"fields":1}
,"astes":{"current":1}
,"system":{"time":1}
,"ield":{"variable":1}
,"variable":{"select":1,"if":1,"doesn\u2019t":1,"container":1,"target":1,"set":1}
,"select":{"entire":1,"option":1,"field":1}
,"entire":{"contents":1}
,"contents":{"replaces":1,"field":1,"variable":1}
,"replaces":{"contents":1,"selected":1}
,"field":{"variable":1,"replaces":1,"inserts":1,"paste":1,"current":1,"use":1,"script":1,"data":1,"original":1}
,"if":{"don\u2019t":1,"variable":1,"target":1,"selection":1}
,"don\u2019t":{"select":1}
,"option":{"field":1}
,"selected":{"portion":1}
,"portion":{"active":1}
,"active":{"field":1}
,"inserts":{"data":1,"current":1}
,"data":{"insertion":1,"variable":1,"inserts":1,"end":1,"replaces":1,"placed":1,"run":1,"time":1}
,"insertion":{"point":1}
,"point":{"default":1,"end":1}
,"default":{"insertion":1}
,"end":{"field\u0027s":1,"variable\u2019s":1}
,"field\u0027s":{"data":1}
,"doesn\u2019t":{"container":1,"exist":1}
,"container":{"data":1}
,"variable\u2019s":{"current":1}
,"value":{"variable":1}
,"target":{"pecifies":1,"variable":1,"field":1,"data":1}
,"pecifies":{"field":1}
,"paste":{"variable":1}
,"set":{"if":1}
,"exist":{"script":1}
,"script":{"step":1}
,"step":{"creates":1,"performing":1,"if":1,"returns":1,"filemaker":1,"performs":1,"email":1}
,"creates":{"sing":1}
,"sing":{"variables":1}
,"variables":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"target":1}
,"layout":{"field":1,"inserts":1,"go":1,"[\u0022":1,"[original":1}
,"use":{"go":1,"et":1}
,"go":{"field":1,"layout":1}
,"performing":{"script":1}
,"placed":{"active":1}
,"returns":{"error":1}
,"error":{"code":1}
,"code":{"captured":1}
,"captured":{"get":1}
,"get":{"lasterror":1}
,"lasterror":{"function":1}
,"function":{"manually":1}
,"manually":{"select":1}
,"run":{"script":1}
,"webdirect":{"script":1,"use":1}
,"performs":{"if":1}
,"selection":{"select":1,"script":1}
,"et":{"selection":1}
,"email":{"history":1}
,"history":{"layout":1,"\u0022]":1}
,"last":{"field":1}
,"original":{"layout":1}
,"[\u0022":{"email":1}
,"\u0022]":{"insert":1}
,"[select":{"emails":1}
,"emails":{":last":1}
,":last":{"sent]":1}
,"sent]":{"go":1}
,"[original":{"layout]":1}
,"layout]":{"data":1}
,"fields":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
