var pairs =
{
"ing":{"borders":1}
,"borders":{"fill":1,"fields":1,"repeating":1,"portal":1,"rounded":1}
,"fill":{"baselines":1,"color":1,"choose":1,"all":1,"current":1,"interactive":1,"add":1}
,"baselines":{"fields":1,"set":1,"choose":1}
,"fields":{"layout":1,"inspector":1,"graphic":1,"set":1,"alternate":1}
,"layout":{"mode":1,"set":1}
,"mode":{"select":1,"border":1,"view":1,"ou":1}
,"select":{"fields":1,"options":1,"text":1}
,"inspector":{"appearance":1}
,"appearance":{"appearance":1,"tab":1,"add":1}
,"tab":{"graphic":1}
,"graphic":{"text":1,"fill":1,"line":1,"corner":1}
,"text":{"select":1,"baselines":1}
,"options":{"want":1,"add":1,"if":1}
,"want":{"use":1,"rounded":1}
,"use":{"add":1,"solid":1}
,"add":{"fill":1,"borders":1,"text":1,"background":1,"change":1}
,"color":{"fields":1,"color":1,"gradient":1,"fill":1}
,"choose":{"color":1,"each":1,"options":1}
,"gradient":{"image":1,"filling":1}
,"image":{"illing":1,"add":1}
,"illing":{"color":1}
,"filling":{"ith":1}
,"ith":{"image":1}
,"set":{"attributes":1,"show":1,"option":1}
,"attributes":{"graphic":1,"text":1}
,"line":{"choos":1}
,"choos":{"options":1}
,"repeating":{"fields":1}
,"alternate":{"row":1}
,"row":{"border":1}
,"border":{"control":1,"effects":1,"radius":1}
,"control":{"change":1}
,"change":{"shape":1,"borders":1}
,"shape":{"field":1}
,"field":{"corners":1,"boundaries":1,"list":1,"borders":1}
,"corners":{"graphic":1,"rounded":1}
,"corner":{"radius":1,"want":1}
,"radius":{"choose":1}
,"each":{"corner":1}
,"rounded":{"appearance":1,"corners":1,"borders":1,"rectangles":1}
,"if":{"current":1,"add":1}
,"current":{"layout":1,"record":1}
,"show":{"field":1,"borders":1}
,"boundaries":{"layout":1,"while":1,"hide":1}
,"effects":{"applied":1,"hide":1}
,"applied":{"effects":1}
,"hide":{"field":1,"switch":1}
,"while":{"layout":1}
,"view":{"menu":1,"current":1}
,"menu":{"show":1}
,"switch":{"browse":1}
,"browse":{"mode":1}
,"ou":{"set":1}
,"option":{"show":1}
,"all":{"records":1}
,"records":{"field":1}
,"list":{"view":1}
,"record":{"field":1,"if":1}
,"background":{"fill":1}
,"interactive":{"container":1}
,"container":{"use":1}
,"solid":{"color":1}
,"portal":{"rows":1}
,"rows":{"ormatting":1}
,"ormatting":{"portals":1}
,"portals":{"shade":1}
,"shade":{"shading":1}
,"shading":{"rounded":1}
,"rectangles":{"border":1}
}
;Search.control.loadWordPairs(pairs);
