var pairs =
{
"saving":{"sending":1,"records":1}
,"sending":{"records":1}
,"records":{"pdf":1,"found":1,"existing":1}
,"pdf":{"fil":1,"file":1,"file\u2019s":1,"create":1,"preview":1,"status":1,"dialog":1,"script":1,"option":1,"files":1,"file\u0027s":1}
,"fil":{"isplay":1}
,"isplay":{"layout":1}
,"layout":{"want":1,"create":1,"mode":1}
,"want":{"use":1}
,"use":{"basis":1}
,"basis":{"pdf":1}
,"file":{"pdf":1,"switching":1,"menu":1,"options":1,"create":1,"supported":1,"file":1,"protected":1}
,"file\u2019s":{"appearance":1}
,"appearance":{"based":1}
,"based":{"current":1}
,"current":{"layout":1,"record":1}
,"create":{"pdf":1,"found":1,"script":1}
,"switching":{"layouts":1}
,"layouts":{"save":1}
,"save":{"records":1,"pdf":1,"current":1,"append":1}
,"found":{"set":1}
,"set":{"aking":1,"blank":1}
,"aking":{"find":1}
,"find":{"request":1}
,"request":{"browse":1}
,"browse":{"layout":1}
,"mode":{"choose":1,"save":1}
,"choose":{"file":1}
,"menu":{"save\u002Fsend":1}
,"save\u002Fsend":{"records":1}
,"preview":{"mode":1}
,"status":{"toolbar":1}
,"toolbar":{"save":1}
,"dialog":{"box":1}
,"box":{"enter":1}
,"enter":{"name":1}
,"name":{"file":1}
,"options":{"save":1}
,"record":{"all":1,"paper":1}
,"all":{"records":1}
,"blank":{"record":1}
,"paper":{"form":1}
,"form":{"save":1}
,"append":{"records":1,"existing":1}
,"existing":{"filemaker":1,"pdf":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"pdf":1}
,"script":{"save":1,"step":1}
,"step":{"select":1,"saving":1}
,"select":{"append":1}
,"option":{"ave":1,"pdf":1}
,"ave":{"records":1}
,"supported":{"runtime":1}
,"runtime":{"solutions":1}
,"solutions":{"save":1}
,"files":{"access":1}
,"access":{"privileges":1}
,"privileges":{"allow":1}
,"allow":{"printing":1}
,"printing":{"database":1}
,"database":{"administrator":1}
,"administrator":{"if":1}
,"if":{"password":1}
,"password":{"option":1}
,"protected":{"contents":1}
,"contents":{"encrypted":1}
,"encrypted":{"encrypted":1,"pdf":1}
,"file\u0027s":{"content":1}
,"content":{"appears":1,"indexed":1,"document":1}
,"appears":{"unreadable":1}
,"unreadable":{"text":1}
,"text":{"non-pdf":1}
,"non-pdf":{"reading":1}
,"reading":{"applications":1}
,"applications":{"file\u0027s":1}
,"indexed":{"by":1}
,"by":{"operating":1}
,"operating":{"system":1}
,"system":{"search":1}
,"search":{"engines":1,"content":1,"utilities":1}
,"engines":{"users":1}
,"users":{"search":1}
,"document":{"desktop":1}
,"desktop":{"internet":1}
,"internet":{"search":1}
}
;Search.control.loadWordPairs(pairs);
