var pairs =
{
"scatter":{"bubble":1,"charts":1}
,"bubble":{"charts":1,"chart":1}
,"charts":{"get":1,"creating":1,"layout":1,"button":1,"choose":1,"finish":1,"x-axis":1,"extension":1,"ability":1}
,"get":{"started":1}
,"started":{"creating":1}
,"creating":{"chart":1,"quick":1,"editing":1}
,"chart":{"creating":1,"aking":1,"chart":1,"setup":1,"type":1,"types":1,"reveal":1,"choose":1,"inspector":1,"if":1,"summary":1,"change":1,"axes":1,"print":1,"relative":1}
,"quick":{"charts":1,"chart":1}
,"editing":{"charts":1}
,"layout":{"mode":1,"quick":1}
,"mode":{"find":1,"charts":1,"scatter":1}
,"find":{"records":1,"request":1}
,"records":{"want":1,"data":1}
,"want":{"chart":1,"include":1}
,"aking":{"find":1}
,"request":{"if":1}
,"if":{"charting":1,"you\u2019re":1,"radius":1}
,"charting":{"delimited":1}
,"delimited":{"data":1}
,"data":{"stored":1,"related":1,"source":1,"y-axis":1,"button":1,"series":1,"bubble":1,"show":1,"point":1,"summary":1,"settings":1,"points":1,"values":1}
,"stored":{"single":1}
,"single":{"record":1}
,"record":{"data":1}
,"related":{"records":1}
,"source":{"settings":1,"chart":1}
,"settings":{"pecifying":1,"x-axis":1,"y-axis":1}
,"pecifying":{"data":1}
,"setup":{"dialog":1}
,"dialog":{"box":1}
,"box":{"choose":1,"x-axis":1,"set":1}
,"choose":{"chart":1,"field":1,"symbol":1,"none":1}
,"type":{"chart":1,"title":1,"profit":1,"additional":1,"define":1}
,"types":{"enter":1}
,"enter":{"axis":1}
,"axis":{"settings":1,"plot":1,"options":1}
,"x-axis":{"title":1,"data":1,"product":1,"number":1,"y-axis":1,"values":1}
,"title":{"y-axis":1,"type":1,"button":1}
,"y-axis":{"title":1,"data":1,"note":1,"add":1,"series":1,"select":1,"values":1}
,"button":{"choose":1,"data":1,"label":1}
,"field":{"name":1,"type":1}
,"name":{"calculation":1,"data":1,"text":1}
,"calculation":{"complete":1}
,"complete":{"dialog":1,"series":1}
,"series":{"each":1,"data":1,"want":1,"y-axis":1,"repeat":1,"name":1,"remove":1,"change":1,"drag":1}
,"each":{"axis":1,"product":1,"data":1}
,"plot":{"product":1,"second":1}
,"product":{"development":1,"revenue":1,"chart":1,"profitable":1,"generates":1}
,"development":{"costs":1}
,"costs":{"x-axis":1}
,"revenue":{"y-axis":1,"each":1,"label":1}
,"note":{"x-axis":1}
,"number":{"field":1}
,"profit":{"gained":1,"margin":1}
,"gained":{"radius":1}
,"radius":{"data":1,"display":1}
,"include":{"comparison":1,"legend":1}
,"comparison":{"radius":1}
,"show":{"profit":1,"legend":1}
,"margin":{"cost":1}
,"cost":{"revenue":1}
,"reveal":{"product":1}
,"profitable":{"product":1}
,"generates":{"revenue":1}
,"label":{"data":1,"each":1}
,"point":{"symbol":1,"chart":1}
,"symbol":{"scatter":1,"mark":1,"color":1}
,"mark":{"each":1}
,"none":{"hide":1}
,"hide":{"symbols":1}
,"symbols":{"symbol":1}
,"color":{"determined":1,"scheme":1}
,"determined":{"by":1}
,"by":{"color":1}
,"scheme":{"setting":1,"legend":1}
,"setting":{"styles":1}
,"styles":{"chart":1}
,"inspector":{"changing":1,"select":1}
,"changing":{"chart":1}
,"you\u2019re":{"creating":1}
,"summary":{"data":1,"menu":1,"type":1}
,"menu":{"chart":1}
,"select":{"summary":1,"series":1,"show":1}
,"additional":{"data":1}
,"add":{"series":1}
,"repeat":{"step":1}
,"step":{"complete":1}
,"remove":{"data":1}
,"change":{"order":1,"labels":1,"color":1}
,"order":{"y-axis":1}
,"drag":{"items":1}
,"items":{"list":1}
,"list":{"select":1}
,"legend":{"display":1,"chart":1,"edit":1,"appearance":1}
,"display":{"legend":1,"bubble":1,"large":1}
,"labels":{"legend":1}
,"edit":{"series":1}
,"text":{"box":1}
,"set":{"axis":1}
,"options":{"formatting":1}
,"formatting":{"scaling":1}
,"scaling":{"chart":1}
,"axes":{"change":1,"include":1}
,"appearance":{"font":1}
,"font":{"style":1}
,"style":{"style":1,"chart":1}
,"print":{"save":1}
,"save":{"layout":1}
,"finish":{"chart":1}
,"values":{"numerical":1,"typically":1,"therefore":1,"0.2":1}
,"numerical":{"x-axis":1}
,"typically":{"explanatory":1,"response":1}
,"explanatory":{"variable":1}
,"variable":{"y-axis":1,"bubble":1,"radius":1}
,"response":{"variable":1}
,"extension":{"scatter":1}
,"ability":{"plot":1}
,"second":{"response":1}
,"relative":{"magnitude":1}
,"magnitude":{"radius":1}
,"points":{"precise":1}
,"precise":{"values":1}
,"therefore":{"if":1}
,"0.2":{"0.5.and":1}
,"0.5.and":{"0.7":1}
,"0.7":{"bubbles":1}
,"bubbles":{"display":1}
,"large":{"distinguish":1}
,"distinguish":{"difference":1}
,"difference":{"relationship":1}
,"relationship":{"choose":1}
,"define":{"axes":1}
}
;Search.control.loadWordPairs(pairs);
