var pairs =
{
"average":{"eturns":1,"all":1,"field":1,"function":1,"values":1,"exams":1,"score":1,"field2":1,"field1":1}
,"eturns":{"value":1}
,"value":{"average":1}
,"all":{"valid":1,"exams":1}
,"valid":{"non-blank":1}
,"non-blank":{"values":1}
,"values":{"field":1,"first":1,"second":1,"ield2":1,"ield3":1}
,"field":{"average":1,"field":1,"-any":1,"repeating":1,"set":1,"repeatingfield":1,"matching":1,"number":1,"therefore":1}
,"-any":{"related":1}
,"related":{"field":1,"records":1}
,"repeating":{"field":1,"fields":1}
,"set":{"non-repeating":1}
,"non-repeating":{"fields":1}
,"fields":{"expression":1,"parameters":1,"record":1,"first":1,"tables":1}
,"expression":{"returns":1}
,"returns":{"field":1,"average":1,"student\u2019s":1,"6.5":1,"calculation":1}
,"parameters":{"braces":1}
,"braces":{"optional":1}
,"optional":{"number":1}
,"number":{"filemaker":1,"repeats":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"field":1}
,"repeatingfield":{"field":1}
,"matching":{"related":1,"record":1}
,"records":{"by":1,"portal":1}
,"by":{"table":1}
,"table":{":field":1,":field1":1,":field2":1,"portal":1,"called":1}
,":field":{"records":1,"table":1,"referenced":1}
,"portal":{"non-repeating":1,"scores":1}
,"record":{"field1":1,"repeatingfield1":1,"by":1}
,"field1":{"field2":1}
,"field2":{"field3":1,"returns":1}
,"field3":{"repetitions":1,"returns":1}
,"repetitions":{"repeating":1,"values":1}
,"repeatingfield1":{"repeatingfield2":1}
,"repeatingfield2":{"repeatingfield3":1}
,"repeatingfield3":{"if":1}
,"if":{"result":1}
,"result":{"returned":1}
,"returned":{"repeating":1}
,"repeats":{"fields":1}
,"first":{"matching":1,"repetition":1}
,":field1":{"table":1}
,":field2":{"include":1}
,"include":{"fields":1}
,"tables":{"table":1}
,"referenced":{"field":1}
,"function":{"returns":1}
,"repetition":{"field":1}
,"second":{"repetition":1}
,"therefore":{")\u002F3=4":1}
,")\u002F3=4":{")\u002F2=4;7\u002F1=7;8\u002F1=8":1}
,")\u002F2=4;7\u002F1=7;8\u002F1=8":{"student":1}
,"student":{"table":1,"exam":1}
,"scores":{"all":1,"table":1}
,"exams":{"student":1,"average":1,":score":1,"examples":1}
,"exam":{"scores":1}
,"called":{"exams":1}
,":score":{"returns":1}
,"student\u2019s":{"average":1}
,"score":{"all":1}
,"examples":{"ield1":1}
,"ield1":{"two":1}
,"two":{"repetitions":1}
,"ield2":{"repetitions":1}
,"ield3":{"average":1}
,"6.5":{"calculation":1}
,"calculation":{"isn\u2019t":1,"repeating":1}
,"isn\u2019t":{"repeating":1}
}
;Search.control.loadWordPairs(pairs);
