var pairs =
{
"ormatting":{"portals":1}
,"portals":{"format":1,"display":1}
,"format":{"portal":1}
,"portal":{"backgrounds":1,"rows":1,"row":1,"viewed":1,"select":1,"inspector":1,"set":1,"appearance":1}
,"backgrounds":{"portal":1}
,"rows":{"separately":1,"contrast":1,"transparent":1,"select":1,"double-click":1,"partially":1}
,"separately":{"ayout":1}
,"ayout":{"mode":1}
,"mode":{"display":1,"change":1}
,"display":{"background":1,"records":1}
,"background":{"alternating":1,"color":1,"fill":1,"display":1,"selected":1,"note":1}
,"alternating":{"portal":1}
,"contrast":{"easy":1}
,"easy":{"identification":1}
,"identification":{"display":1}
,"color":{"selected":1,"color":1,"gradient":1,"palette":1,"choose":1,"drag":1}
,"selected":{"portal":1}
,"row":{"portal":1,"object":1,"fr":1,"background":1,"state":1,"double-click":1,"current":1,"doesn\u2019t":1,"border":1}
,"viewed":{"browse":1}
,"browse":{"mode":1}
,"change":{"background":1,"borders":1,"opacity":1}
,"fill":{"portal":1,"choose":1,"setting":1,"all":1}
,"select":{"portal":1,"use":1}
,"inspector":{"appearance":1,"choose":1}
,"appearance":{"appearance":1,"tab":1}
,"tab":{"graphic":1,"choose":1,"inspector":1}
,"graphic":{"fill":1,"line":1}
,"choose":{"solid":1,"portal":1,"primary":1,"none":1,"fill":1,"alternate":1,"active":1,"color":1}
,"solid":{"color":1,"shadow":1}
,"gradient":{"image":1,"shadow":1}
,"image":{"object":1,"fills":1}
,"object":{"type":1,"state":1}
,"type":{"list":1}
,"list":{"first":1,"tab":1,"second":1,"choose":1,"graphic":1}
,"first":{"list":1}
,"state":{"list":1,"appearance":1,"row":1,"portal":1}
,"second":{"list":1}
,"primary":{"graphic":1,"object":1}
,"none":{"note":1}
,"note":{"if":1,"portals":1}
,"if":{"fill":1}
,"setting":{"portal":1}
,"set":{"portal":1}
,"transparent":{"change":1,"fill":1}
,"all":{"portal":1}
,"fr":{"om":1}
,"om":{"object":1}
,"double-click":{"portal":1}
,"use":{"alternate":1,"active":1}
,"alternate":{"row":1,"object":1}
,"active":{"row":1,"object":1}
,"records":{"current":1}
,"current":{"table":1,"record":1}
,"table":{"selecting":1}
,"selecting":{"use":1}
,"record":{"use":1}
,"doesn\u2019t":{"focus":1}
,"focus":{"add":1}
,"add":{"change":1}
,"borders":{"portal":1}
,"line":{"choose":1}
,"shadow":{"color":1}
,"palette":{"button":1}
,"button":{"choose":1,"drag":1}
,"border":{"control":1,"style":1}
,"control":{"border":1}
,"style":{"portal":1}
,"partially":{"transparent":1}
,"drag":{"opacity":1}
,"opacity":{"slider":1,"image":1}
,"slider":{"windows":1,"macos":1}
,"windows":{"color":1}
,"macos":{"can\u2019t":1}
,"can\u2019t":{"change":1}
}
;Search.control.loadWordPairs(pairs);
