var pairs =
{
"orking":{"layout":1}
,"layout":{"parts":1,"determine":1,"part":1,"mode":1,"use":1}
,"parts":{"filemaker":1,"sections":1,"control":1,"contain":1,"part":1,"assigned":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"layouts":1,"isplays":1}
,"layouts":{"divided":1}
,"divided":{"layout":1}
,"sections":{"layout":1}
,"determine":{"data":1}
,"data":{"field":1,"ach":1}
,"field":{"treated":1}
,"treated":{"displayed":1}
,"displayed":{"by":1}
,"by":{"parts":1,"theme":1}
,"control":{"filemaker":1}
,"isplays":{"data":1}
,"ach":{"layout":1}
,"part":{"layout":1,"boundaries":1,"labels":1,"label":1,"styles":1}
,"contain":{"fields":1}
,"fields":{"portals":1}
,"portals":{"buttons":1}
,"buttons":{"text":1}
,"text":{"charts":1}
,"charts":{"objects":1}
,"objects":{"layout":1}
,"mode":{"gray":1}
,"gray":{"horizontal":1}
,"horizontal":{"lines":1,"position":1}
,"lines":{"mark":1}
,"mark":{"division":1}
,"division":{"layout":1}
,"boundaries":{"part":1,"trl-click":1}
,"labels":{"display":1,"part":1,"vertical":1}
,"display":{"horizontally":1,"orizontally":1}
,"horizontally":{"vertically":1}
,"vertically":{"left":1}
,"left":{"layout":1}
,"trl-click":{"windows":1}
,"windows":{"command-click":1}
,"command-click":{"macos":1}
,"macos":{"part":1}
,"label":{"hold":1,"display":1}
,"hold":{"mouse":1}
,"mouse":{"button":1}
,"button":{"vertical":1}
,"vertical":{"part":1,"horizontal":1}
,"orizontally":{"moment":1}
,"moment":{"parts":1}
,"assigned":{"styles":1}
,"styles":{"defined":1,"setting":1}
,"defined":{"by":1}
,"theme":{"layout":1}
,"use":{"inspector":1}
,"inspector":{"customize":1}
,"customize":{"part":1}
,"setting":{"fill":1}
,"fill":{"line":1}
,"line":{"style":1}
,"style":{"shadows":1}
,"shadows":{"padding":1}
,"padding":{"heading":1}
,"heading":{"headings":1}
,"headings":{"switch":1}
,"switch":{"part":1}
}
;Search.control.loadWordPairs(pairs);
