var pairs =
{
"hecking":{"spelling":1,"individual":1}
,"spelling":{"filemaker":1,"text":1,"type":1,"tab":1,"field-by-field":1,"dictionaries":1,"choose":1,"command":1,"verified":1,"check":1,"web":1,"select":1,"edit":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"check":1,"by":1,"ompares":1,"includes":1}
,"check":{"spelling":1,"choose":1,"if":1,"complete":1}
,"text":{"locations":1,"objects":1,"that\u2019s":1,"two":1,"check":1}
,"locations":{"selected":1}
,"selected":{"word":1,"edit":1}
,"word":{"passage":1,"appears":1,"box":1,"restricted":1,"dictionary":1,"spelling":1,"type":1,"ignore":1,"skipped":1,"add":1}
,"passage":{"field":1}
,"field":{"visible":1,"case":1,"record":1}
,"visible":{"fields":1}
,"fields":{"current":1,"visible":1,"all":1,"while":1,"behavior":1,"container":1,"create":1}
,"current":{"record":1,"found":1,"layout":1,"field":1}
,"record":{"including":1,"layout":1,"found":1}
,"including":{"related":1,"text":1}
,"related":{"fields":1}
,"all":{"records":1,"text":1,"ev":1}
,"records":{"current":1,"select":1}
,"found":{"set":1}
,"set":{"including":1,"filemaker":1,"options":1,"records":1,"layout":1}
,"while":{"layout":1}
,"layout":{"mode":1,"including":1,"find":1,"spelling":1}
,"mode":{"all":1}
,"objects":{"current":1,"tab":1}
,"tab":{"panels":1,"file":1,"inspector":1}
,"panels":{"slide":1,"front":1}
,"slide":{"panels":1}
,"front":{"set":1}
,"type":{"misspellings":1,"replacement":1}
,"misspellings":{"red":1}
,"red":{"dotted":1}
,"dotted":{"underline":1}
,"underline":{"text":1}
,"that\u2019s":{"edited":1}
,"edited":{"set":1}
,"options":{"spelling":1,"dialog":1,"filemaker":1}
,"file":{"options":1,"field":1}
,"dialog":{"box":1}
,"box":{"etting":1,"choose":1}
,"etting":{"file":1}
,"by":{"default":1}
,"default":{"checks":1}
,"checks":{"spelling":1}
,"field-by-field":{"basis":1}
,"basis":{"disable":1}
,"disable":{"spell":1}
,"spell":{"-c":1}
,"-c":{"hecking":1}
,"individual":{"fields":1}
,"behavior":{"data":1}
,"data":{"data":1,"tab":1}
,"inspector":{"select":1}
,"select":{"apply":1,"text":1,"suggestion":1,"edit":1,"dictionaries":1}
,"apply":{"visual":1}
,"visual":{"spell-checking":1}
,"spell-checking":{"check":1}
,"ompares":{"text":1}
,"two":{"dictionaries":1}
,"dictionaries":{"main":1,"languages":1,"time":1,"word":1,"choose":1}
,"main":{"dictionary":1}
,"dictionary":{"user":1,"main":1,"preset":1,"change":1,"filemaker":1,"user.upr":1,"create":1,"use":1,"display":1,"select":1,"learn":1,"selected":1,"choose":1}
,"user":{"dictionary":1,"dictionaries":1}
,"preset":{"match":1}
,"match":{"local":1}
,"local":{"language":1}
,"language":{"united":1,"main":1}
,"united":{"states":1}
,"states":{"usenglsh.mpr":1}
,"usenglsh.mpr":{"can\u2019t":1}
,"can\u2019t":{"edit":1}
,"edit":{"main":1,"menu":1,"spelling":1,"export":1,"user":1}
,"change":{"language":1,"user":1,"word":1}
,"includes":{"spelling":1}
,"languages":{"dutch":1}
,"dutch":{"french":1}
,"french":{"italian":1}
,"italian":{"german":1}
,"german":{"portuguese":1,"uk":1}
,"portuguese":{"brazil":1,"portugal":1}
,"brazil":{"portuguese":1}
,"portugal":{"spanish":1}
,"spanish":{"swedish":1}
,"swedish":{"swiss":1}
,"swiss":{"german":1}
,"uk":{"english":1}
,"english":{"english":1,"medical":1}
,"medical":{"user":1}
,"user.upr":{"second":1}
,"second":{"editable":1}
,"editable":{"dictionary":1}
,"create":{"multiple":1,"select":1}
,"multiple":{"user":1}
,"time":{"change":1,"user":1}
,"use":{"just":1}
,"just":{"main":1}
,"display":{"record":1}
,"find":{"set":1}
,"choose":{"edit":1,"spelling":1,"option":1}
,"menu":{"spelling":1}
,"command":{"if":1}
,"if":{"questionable":1,"want":1}
,"questionable":{"word":1}
,"appears":{"word":1}
,"option":{"note":1,"edit":1,"ch":1}
,"note":{"change":1,"user":1,"ou":1}
,"restricted":{"password-protected":1}
,"password-protected":{"file":1}
,"case":{"next":1}
,"next":{"replace":1}
,"replace":{"misspelled":1,"revise":1,"leave":1}
,"misspelled":{"word":1}
,"suggestion":{"list":1}
,"list":{"replace":1}
,"revise":{"misspelled":1}
,"replacement":{"check":1}
,"want":{"new":1}
,"new":{"word\u0027s":1}
,"word\u0027s":{"spelling":1}
,"verified":{"replace":1}
,"leave":{"word":1}
,"ignore":{"all":1}
,"ev":{"ery":1}
,"ery":{"occurrence":1}
,"occurrence":{"word":1}
,"skipped":{"leave":1}
,"add":{"user":1}
,"learn":{"note":1}
,"complete":{"note":1}
,"ou":{"check":1}
,"web":{"viewer":1}
,"viewer":{"summary":1}
,"summary":{"fields":1}
,"container":{"fields":1}
,"export":{"import":1}
,"import":{"user":1}
,"ch":{"eck":1}
,"eck":{"pelling":1}
,"pelling":{"current":1}
}
;Search.control.loadWordPairs(pairs);
