var pairs =
{
"ntering":{"preset":1}
,"preset":{"data":1}
,"data":{"value":1,"browse":1}
,"value":{"list":1,"lists":1,"drop-down":1,"included":1,"select":1,"clear":1,"dialog":1,"choose":1,"value":1,"want":1,"shift-click":1,"if":1}
,"list":{"field":1,"pop-up":1,"choose":1,"press":1,"depend":1,"validation":1,"defining":1}
,"field":{"display":1,"choose":1,"type":1,"edit":1,"arrow":1,"setup":1,"defined":1,"validation":1,"field":1,"named":1,"formatted":1,"accepts":1,"layout":1,"doesn\u2019t":1}
,"display":{"predetermined":1,"pop-up":1,"two":1,"layout":1}
,"predetermined":{"values":1}
,"values":{"radio":1,"enter":1,"dialog":1}
,"radio":{"button":1,"option":1,"buttons":1}
,"button":{"set":1,"button":1,"select":1,"shift-click":1,"sets":1,"clear":1,"ay":1}
,"set":{"checkbox":1,"drop-down":1,"control":1}
,"checkbox":{"set":1,"select":1,"sets":1}
,"drop-down":{"list":1,"lists":1}
,"pop-up":{"menu":1,"menus":1}
,"menu":{"use":1,"field":1,"type":1,"windows":1,"checkbox":1,"clear":1}
,"use":{"value":1,"arrow":1,"keyboard":1}
,"lists":{"quickly":1,"pop-up":1}
,"quickly":{"enter":1}
,"enter":{"preset":1,"value":1,"values":1,"use":1}
,"browse":{"mode":1}
,"mode":{"choose":1}
,"choose":{"predefined":1,"value":1,"type":1,"delete":1,"edit":1}
,"predefined":{"value":1}
,"type":{"value":1,"first":1}
,"included":{"ist":1,"value":1}
,"ist":{"field":1,"use":1}
,"select":{"suggestion":1,"radio":1,"value":1,"checkboxes":1,"clear":1,"press":1,"field":1}
,"suggestion":{"ist":1}
,"arrow":{"keys":1,"control":1,"open":1,"options":1}
,"keys":{"page":1,"end":1,"select":1}
,"page":{"up":1,"keys":1}
,"up":{"page":1,"field":1}
,"end":{"keys":1}
,"option":{"button":1}
,"clear":{"button":1,"values":1,"value":1,"ca":1,"field":1}
,"shift-click":{"select":1,"radio":1}
,"checkboxes":{"checkbox":1,"tab":1}
,"dialog":{"box":1}
,"box":{"clear":1,"action":1,"open":1}
,"delete":{"associated":1}
,"associated":{"value":1}
,"action":{"clears":1}
,"clears":{"field":1}
,"edit":{"value":1,"change":1,"items":1,"menu":1}
,"change":{"values":1}
,"open":{"close":1}
,"close":{"drop-down":1,"pop-up":1}
,"press":{"sc":1,"esc":1,"space":1}
,"sc":{"field":1}
,"control":{"next":1,"if":1}
,"next":{"arrow":1}
,"windows":{"press":1}
,"esc":{"macos":1}
,"macos":{"press":1}
,"space":{"bar":1}
,"bar":{"if":1,"enter":1}
,"if":{"field":1,"user":1}
,"options":{"value":1}
,"depend":{"field":1}
,"setup":{"setup":1,"determines":1}
,"determines":{"edit":1}
,"items":{"radio":1}
,"sets":{"checkbox":1,"drop-down":1}
,"menus":{"se":1}
,"se":{"setting":1}
,"setting":{"up":1,"type":1}
,"defined":{"member":1}
,"member":{"value":1}
,"validation":{"setting":1,"use":1}
,"defining":{"field":1}
,"keyboard":{"enter":1}
,"buttons":{"checkboxes":1,"black":1}
,"tab":{"field":1}
,"first":{"letter":1}
,"letter":{"value":1}
,"want":{"enter":1}
,"ca":{"ses":1}
,"ses":{"shift-click":1}
,"ay":{"clear":1}
,"named":{"olor":1}
,"olor":{"formatted":1,"field":1}
,"formatted":{"layout":1}
,"layout":{"display":1,"text":1,"stored":1,"clear":1,"select":1}
,"two":{"radio":1}
,"black":{"white":1}
,"white":{"olor":1}
,"text":{"entry":1}
,"entry":{"field":1}
,"accepts":{"value":1}
,"user":{"nter":1}
,"nter":{"ed":1}
,"ed":{"field":1}
,"stored":{"field":1}
,"doesn\u2019t":{"display":1}
}
;Search.control.loadWordPairs(pairs);
