var pairs =
{
"preparing":{"files":1,"multiple":1}
,"files":{"runtime":1,"if":1,"provide":1,"password":1,"filemaker":1,"permanently":1,"developer":1,"by":1,"separate":1,"want":1,"moved":1}
,"runtime":{"solutio":1,"application":1,"database":1,"solutions":1,"solution":1}
,"solutio":{"note":1,"if":1}
,"note":{"feature":1}
,"feature":{"use":1}
,"use":{"advanced":1,"binding":1}
,"advanced":{"tools":1,"files":1,"users":1,"manage":1}
,"tools":{"general":1,"efore":1}
,"general":{"preference":1}
,"preference":{"selected":1}
,"selected":{"ad":1}
,"ad":{"vanced":1}
,"vanced":{"tools":1}
,"efore":{"bind":1}
,"bind":{"files":1,"developer":1}
,"application":{"decide":1,"menu":1,"checking":1,"searches":1,"reason":1,"check":1}
,"decide":{"if":1}
,"if":{"want":1,"solution":1,"you\u2019re":1,"runtime":1,"preparing":1}
,"want":{"let":1,"users":1,"files":1,"multiple":1}
,"let":{"users":1}
,"users":{"open":1,"primary":1,"modify":1,"easier":1,"update":1,"print":1,"perform":1,"add":1}
,"open":{"auxiliary":1,"files":1,"modify":1}
,"auxiliary":{"files":1,"file":1}
,"menu":{"options":1}
,"options":{"open":1}
,"provide":{"button":1,"updates":1}
,"button":{"script":1,"startup":1}
,"script":{"solution":1,"returns":1,"value":1}
,"solution":{"perform":1,"files":1,"if":1,"windows":1,"macos":1,"ee":1,"let":1,"t\u2019s":1,"printed":1,"by":1,"all":1}
,"perform":{"operation":1,"spell":1}
,"operation":{"each":1}
,"each":{"auxiliary":1,"filemaker":1}
,"file":{"place":1,"let":1,"export":1,"path":1,"referenced":1,"folder":1,"avoid":1}
,"place":{"button":1}
,"startup":{"script":1}
,"returns":{"users":1}
,"primary":{"file":1}
,"modify":{"database":1,"files":1,"user-defined":1}
,"database":{"runtime":1,"solution":1,"create":1,"multiple":1,"sure":1}
,"password":{"protected":1}
,"protected":{"users":1}
,"filemaker":{"pro":1,"data":1}
,"pro":{"advanced":1}
,"permanently":{"unmodifiable":1}
,"unmodifiable":{"removing":1}
,"removing":{"admin":1}
,"admin":{"access":1}
,"access":{"database":1,"external":1}
,"create":{"cross-platform":1,"two":1}
,"cross-platform":{"runtime":1}
,"windows":{"bind":1,"solution":1,"macos":1}
,"developer":{"utilities":1}
,"utilities":{"windows":1,"macos":1,"indows":1}
,"macos":{"bind":1,"ee":1,"create":1,"use":1}
,"ee":{"inding":1,"mporting":1}
,"inding":{"files":1}
,"you\u2019re":{"creating":1}
,"creating":{"solution":1}
,"two":{"separate":1}
,"separate":{"runtime":1,"folders":1}
,"solutions":{"by":1}
,"by":{"binding":1,"providing":1,"choosing":1}
,"binding":{"original":1,"key":1}
,"original":{"solution":1}
,"indows":{"developer":1}
,"key":{"platforms":1}
,"platforms":{"provide":1}
,"updates":{"users":1}
,"easier":{"users":1}
,"update":{"runtime":1}
,"providing":{"scripts":1}
,"scripts":{"primary":1}
,"export":{"data":1}
,"data":{"import":1,"upgraded":1,"source":1,"sources":1}
,"import":{"updated":1}
,"updated":{"solution":1}
,"mporting":{"data":1}
,"upgraded":{"runtime":1}
,"print":{"reports":1}
,"reports":{"runtime":1}
,"t\u2019s":{"idea":1}
,"idea":{"set":1}
,"set":{"document":1}
,"document":{"margins":1}
,"margins":{"if":1,"let":1}
,"printed":{"variety":1}
,"variety":{"printers":1}
,"printers":{"se":1}
,"se":{"page":1}
,"page":{"margins":1}
,"spell":{"checking":1}
,"checking":{"records":1,"spelling":1}
,"records":{"change":1}
,"change":{"main":1}
,"main":{"spelling":1}
,"spelling":{"dictionary":1,"addition":1}
,"dictionary":{"language":1,"runtime":1}
,"language":{"database":1}
,"choosing":{"dictionaries":1}
,"dictionaries":{"supplied":1}
,"supplied":{"filemaker":1}
,"add":{"modify":1}
,"user-defined":{"dictionary":1}
,"addition":{"if":1}
,"multiple":{"files":1,"tables":1}
,"folders":{"verify":1,"during":1,"data":1}
,"verify":{"filemaker":1}
,"source":{"references":1,"stores":1,"case":1,"reference":1,"file:myfile.fmp12":1}
,"references":{"data":1,"verifying":1}
,"stores":{"file":1}
,"path":{"paths":1,"just":1,"filename":1}
,"paths":{"runtime":1,"data":1}
,"searches":{"access":1}
,"external":{"table":1,"data":1}
,"table":{"script":1}
,"value":{"list":1}
,"list":{"during":1}
,"during":{"development":1,"creation":1}
,"development":{"database":1}
,"creation":{"runtime":1}
,"all":{"files":1}
,"moved":{"folder":1}
,"folder":{"runtime":1,"resides":1}
,"reason":{"include":1}
,"include":{"path":1}
,"just":{"filename":1}
,"filename":{"file":1,"folders":1}
,"referenced":{"runtime":1}
,"check":{"data":1}
,"sources":{"find":1,"dialog":1,"current":1,"want":1}
,"find":{"file":1}
,"resides":{"keep":1}
,"keep":{"absolute":1}
,"absolute":{"relative":1}
,"relative":{"paths":1}
,"case":{"files":1}
,"manage":{"external":1}
,"dialog":{"box":1}
,"box":{"lists":1}
,"lists":{"data":1}
,"current":{"database":1}
,"sure":{"each":1}
,"reference":{"file":1}
,"file:myfile.fmp12":{"co":1}
,"co":{"nnecting":1}
,"nnecting":{"external":1}
,"tables":{"file":1}
,"avoid":{"problems":1}
,"problems":{"filemaker":1}
,"verifying":{"filemaker":1}
}
;Search.control.loadWordPairs(pairs);
