var pairs =
{
"get":{"quickfi":1,"quickfindtext":1,"quick":1}
,"quickfi":{"ndtext":1}
,"ndtext":{"returns":1}
,"returns":{"text":1,"custom":1}
,"text":{"stored":1,"filemaker":1,"quick":1,"entered":1,"get":1}
,"stored":{"quick":1}
,"quick":{"find":1}
,"find":{"box":1,"command":1,"text":1}
,"box":{"get":1,"script":1,"if":1}
,"quickfindtext":{"none":1,")]":1,"&\u0022\u005C\u0022":1,"get":1}
,"none":{"text":1}
,"filemaker":{"pro":1}
,"pro":{"11.0":1}
,"11.0":{"use":1}
,"use":{"function":1}
,"function":{"pass":1}
,"pass":{"text":1}
,"script":{"override":1}
,"override":{"perform":1}
,"perform":{"quick":1,"quickfind":1}
,"command":{"custom":1}
,"custom":{"menu":1,"error":1,"dialog":1}
,"menu":{"set":1}
,"set":{"performs":1}
,"performs":{"quick":1}
,"entered":{"quick":1}
,"if":{"records":1,"[get":1,"get":1}
,"records":{"found":1}
,"found":{"returns":1}
,"error":{"message":1}
,"message":{"perform":1}
,"quickfind":{"[get":1}
,"[get":{"quickfindtext":1,"lasterror":1}
,")]":{"if":1,"go":1}
,"lasterror":{"=0]":1}
,"=0]":{"go":1}
,"go":{"layout":1,"record\u002Frequest\u002Fpage":1}
,"layout":{"[\u0022":1}
,"[\u0022":{"invoice":1,"invoices":1}
,"invoice":{"details":1}
,"details":{"invoices":1}
,"invoices":{")]":1,"\u005C\u0022":1}
,"record\u002Frequest\u002Fpage":{"[first]":1}
,"[first]":{"else":1}
,"else":{"show":1}
,"show":{"custom":1}
,"dialog":{"[\u0022":1}
,"\u005C\u0022":{"&get":1}
,"&get":{"quickfindtext":1}
,"&\u0022\u005C\u0022":{"\u0022]":1}
,"\u0022]":{"end":1}
,"end":{"if":1}
}
;Search.control.loadWordPairs(pairs);
