var pairs =
{
"sing":{"reserved":1}
,"reserved":{"word":1,"symbol":1,"contain":1,"symbols":1}
,"word":{"symbol":1,"reserved":1}
,"symbol":{"field":1,"characters":1}
,"field":{"table":1,"names":1,"calculation":1,"named":1}
,"table":{"name":1,"names":1,"naming":1,"tablenames":1}
,"name":{"define":1,"appears":1,"table":1}
,"define":{"tables":1}
,"tables":{"fields":1,"naming":1}
,"fields":{"formulas":1,"guidelines":1}
,"formulas":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"reserves":1,"automatically":1,"characters":1}
,"reserves":{"use":1}
,"use":{"symbols":1}
,"symbols":{"including":1,"naming":1,"field":1,"${":1,"name":1}
,"including":{"names":1}
,"names":{"functions":1,"table":1,"names":1,"difficult":1,"reserved":1,"conflict":1}
,"functions":{"arguments":1,"roman":1}
,"arguments":{"pi":1}
,"pi":{"random":1,"returns":1,"note":1}
,"random":{"predefined":1}
,"predefined":{"parameters":1}
,"parameters":{"functions":1}
,"roman":{"greek":1}
,"greek":{"font":1}
,"font":{"scripts":1}
,"scripts":{"textfont":1}
,"textfont":{"function":1}
,"function":{"keywords":1,"double-click":1}
,"keywords":{"symbols":1}
,"naming":{"fields":1,"tables":1,"table":1}
,"guidelines":{"avoid":1}
,"avoid":{"symbols":1}
,"difficult":{"refer":1}
,"refer":{"calculations":1}
,"calculations":{"if":1}
,"if":{"field":1}
,"characters":{"${":1}
,"${":{"name":1,"field":1,"returns":1,".123":1,"pi":1,"enclose":1}
,"appears":{"function":1}
,"double-click":{"choose":1}
,"choose":{"field":1}
,"calculation":{"filemaker":1}
,"automatically":{"wraps":1}
,"wraps":{"characters":1}
,"contain":{"reserved":1}
,"returns":{"contents":1}
,"contents":{"field":1}
,"named":{"${":1,".123":1,"pi":1}
,".123":{"returns":1,"${":1}
,"note":{"during":1}
,"during":{"file":1}
,"file":{"conversion":1}
,"conversion":{"filemaker":1}
,"enclose":{"field":1}
,"conflict":{"reserved":1}
,"tablenames":{"examples":1}
}
;Search.control.loadWordPairs(pairs);
