var pairs =
{
"athematical":{"operators":1}
,"operators":{"mathematical":1,"perform":1,"formulas":1}
,"mathematical":{"operators":1}
,"perform":{"arithmetic":1}
,"arithmetic":{"computations":1}
,"computations":{"symbol":1}
,"symbol":{"name":1}
,"name":{"definition":1}
,"definition":{"plus":1}
,"plus":{"adds":1}
,"adds":{"two":1}
,"two":{"values":1}
,"values":{"-minus":1}
,"-minus":{"subtracts":1}
,"subtracts":{"second":1}
,"second":{"value":1,"power":1}
,"value":{"first":1,"\u002Fdivide":1,"by":1,"power":1,"precedence":1}
,"first":{"*multiply":1,"value":1,"se":1}
,"*multiply":{"multiplies":1}
,"multiplies":{"each":1}
,"each":{"value":1}
,"\u002Fdivide":{"divides":1}
,"divides":{"first":1}
,"by":{"second":1}
,"power":{"raises":1,"second":1}
,"raises":{"first":1}
,"precedence":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"evaluates":1}
,"evaluates":{"formulas":1,"expressions":1}
,"formulas":{"left":1}
,"left":{"right":1}
,"right":{"performing":1}
,"performing":{"multiplication":1}
,"multiplication":{"division":1}
,"division":{"addition":1}
,"addition":{"subtraction":1}
,"subtraction":{"parentheses":1}
,"parentheses":{"change":1,"first":1}
,"change":{"order":1}
,"order":{"filemaker":1}
,"expressions":{"parentheses":1}
,"se":{"sing":1}
,"sing":{"operators":1}
}
;Search.control.loadWordPairs(pairs);
