var pairs =
{
"sing":{"custom":1}
,"custom":{"function":1,"functions":1,"fu":1}
,"function":{"note":1,"dialog":1,"name":1,"custom":1,"names":1,"parameters":1,"functions":1,"formula":1,"if":1,"full":1,"function":1,"edit":1,"duplicate":1,"delete":1,"open":1,"copied":1,"invalid":1,"field":1,"enclosed":1,"protected":1,"content":1,"restricted":1,"change":1,"declaration":1,"copy":1,"filemaker":1}
,"note":{"feature":1}
,"feature":{"use":1}
,"use":{"advanced":1,"custom":1}
,"advanced":{"tools":1,"file":1,"determines":1}
,"tools":{"general":1,"ch":1}
,"general":{"preference":1}
,"preference":{"selected":1}
,"selected":{"ad":1,"function":1}
,"ad":{"vanced":1}
,"vanced":{"tools":1}
,"ch":{"oose":1}
,"oose":{"file":1}
,"file":{"menu":1,"choose":1,"dependent":1,"function":1}
,"menu":{"manage":1,"copy":1,"paste":1}
,"manage":{"custom":1}
,"functions":{"manage":1,"dialog":1,"if":1,"list":1,"edit":1,"close":1,"want":1,"press":1,"macos":1,"content":1,"names":1,"filemaker":1,"override":1,"verify":1,"change":1}
,"dialog":{"box":1}
,"box":{"new":1,"function":1,"perform":1,"replace":1,"lists":1,"continue":1,"choose":1,"edit":1,"duplicate":1,"select":1}
,"new":{"edit":1,"function":1,"filemaker":1}
,"edit":{"custom":1,"delete":1,"edit":1,"button":1,"view":1,"calculation":1}
,"name":{"type":1,"new":1,"add":1,"by":1,"mathematical":1,"select":1}
,"type":{"name":1,"parameter":1,"value":1,"reference":1}
,"names":{"unique":1,"operators":1,"identical":1,"filemaker":1,"if":1}
,"unique":{"exceed":1}
,"exceed":{"100":1}
,"100":{"characters":1}
,"characters":{"build":1,"(\u002F*<":1}
,"build":{"formula":1}
,"formula":{"se":1,"requires":1,"box":1,"if":1}
,"se":{"formulas":1}
,"formulas":{"functions":1}
,"if":{"formula":1,"want":1,"filemaker":1,"set":1,"created":1,"create":1}
,"requires":{"parameters":1}
,"parameters":{"function":1,"type":1,"list":1}
,"parameter":{"name":1,"parameters":1,"value":1,"names":1}
,"add":{"add":1,"button":1,"reference":1}
,"button":{"edit":1,"delete":1,"want":1}
,"delete":{"parameter":1,"delete":1,"button":1,"custom":1,"manage":1}
,"by":{"selecting":1}
,"selecting":{"list":1}
,"list":{"clicking":1,"double-click":1,"constant":1,"if":1}
,"clicking":{"edit":1}
,"want":{"item":1,"custom":1,"copy":1}
,"item":{"formula":1}
,"perform":{"actions":1}
,"actions":{"add":1}
,"reference":{"parameter":1,"pasted":1}
,"double-click":{"parameter":1,"function":1}
,"mathematical":{"text":1}
,"text":{"operator":1}
,"operator":{"keypad":1,"comparison":1,"operators":1,"list":1}
,"keypad":{"operator":1,"all":1}
,"comparison":{"logical":1}
,"logical":{"operator":1}
,"operators":{"choose":1,"functions":1}
,"choose":{"operator":1,"file":1}
,"constant":{"value":1}
,"value":{"type":1,"function":1,"expression":1}
,"replace":{"placeholder":1}
,"placeholder":{"parameter":1}
,"expression":{"type":1}
,"lists":{"keypad":1}
,"all":{"accounts":1,"users":1}
,"accounts":{"default":1,"assigned":1,"string":1}
,"default":{"option":1}
,"option":{"availability":1}
,"availability":{"allows":1}
,"allows":{"all":1}
,"users":{"current":1,"full":1}
,"current":{"database":1}
,"database":{"use":1,"create":1}
,"full":{"access":1}
,"access":{"privileges":1,"accounts":1}
,"privileges":{"select":1,"close":1,"currently":1,"edit":1,"full":1,"attempt":1}
,"select":{"accounts":1,"custom":1,"functions":1,"non-contiguous":1,"contiguous":1}
,"assigned":{"full":1}
,"close":{"edit":1,"manage":1}
,"continue":{"creating":1}
,"creating":{"custom":1}
,"duplicate":{"custom":1,"delete":1}
,"copy":{"press":1,"functions":1,"copy":1,"selected":1,"custom":1}
,"press":{"ctrl-click":1,"shift-click":1,"ctrl":1}
,"ctrl-click":{"windows":1}
,"windows":{"command-click":1,"command-c":1,"command-v":1}
,"command-click":{"macos":1}
,"macos":{"select":1,"copy":1,"choose":1,"paste":1}
,"non-contiguous":{"functions":1}
,"shift-click":{"select":1}
,"contiguous":{"functions":1}
,"ctrl":{"windows":1}
,"command-c":{"macos":1}
,"open":{"filemaker":1}
,"filemaker":{"pro":1,"software":1,"functions":1}
,"pro":{"advanced":1}
,"command-v":{"macos":1}
,"paste":{"functions":1,"paste":1,"selected":1}
,"copied":{"appears":1}
,"appears":{"bottom":1,"formula":1}
,"bottom":{"list":1}
,"determines":{"function":1}
,"invalid":{"context":1,"field":1}
,"context":{"target":1}
,"target":{"file":1}
,"dependent":{"function":1}
,"field":{"calculation":1,"type":1}
,"calculation":{"missing":1,"custom":1,"private":1}
,"missing":{"target":1}
,"pasted":{"function":1}
,"enclosed":{"comment":1}
,"comment":{"characters":1}
,"(\u002F*<":{"function_definition":1}
,"function_definition":{"*\u002F)":1}
,"*\u002F)":{"custom":1}
,"fu":{"nction":1}
,"nction":{"dependency":1}
,"dependency":{"rule":1}
,"rule":{"full":1}
,"currently":{"active":1}
,"active":{"database":1}
,"create":{"custom":1}
,"content":{"custom":1,"full":1}
,"protected":{"if":1}
,"set":{"all":1}
,"view":{"custom":1}
,"attempt":{"edit":1}
,"restricted":{"full":1}
,"string":{"private":1}
,"private":{"function":1}
,"change":{"calculation":1,"custom":1,"duplicate":1}
,"declaration":{"appears":1}
,"created":{"custom":1}
,"identical":{"new":1}
,"software":{"functions":1}
,"override":{"custom":1}
,"verify":{"custom":1}
}
;Search.control.loadWordPairs(pairs);
