var pairs =
{
"getlayoutobjectattribute":{"returns":1,"objectname":1,"web":1}
,"returns":{"attributes":1,"data":1,"objects":1,"portal":1,"number":1,"returns":1,"empty":1}
,"attributes":{"layout":1,"coordinates":1,"return":1,"returned":1,"based":1}
,"layout":{"object":1,"attributename":1,"boundary":1,"data":1,"if":1}
,"object":{"by":1,"current":1,"tab":1,"currently":1,"top-left":1,"number":1,"objects":1,"web":1,"all":1,"buttons":1,"returns":1,"coordinates":1,"filemaker":1}
,"by":{"objectname":1,"spaces":1}
,"objectname":{"currently":1,"attributename":1,"-the":1,"focus":1,"hidden":1,"enclosing":1,"groups":1}
,"currently":{"active":1}
,"active":{"calculation":1,"returns":1}
,"calculation":{"getlayoutobjectattribute":1}
,"attributename":{"repetitionnumber":1,"-the":1}
,"repetitionnumber":{"portalrownumber":1,"-the":1,"function":1}
,"portalrownumber":{"objectname":1,"-the":1,"function":1}
,"-the":{"name":1,"repetition":1,"number":1}
,"name":{"named":1,"supported":1,"table":1,":field":1,"text":1,"file":1}
,"named":{"layout":1,"objects":1}
,"current":{"layout":1,"record":1,"url":1,"content":1,"state":1}
,"supported":{"attribute":1}
,"attribute":{"repetitionnumber":1,"returns":1}
,"repetition":{"number":1,"returning":1,"portal":1}
,"number":{"repeating":1,"row":1,"containsfocus":1,"isfrontpanel":1,"isactive":1,"isobjecthidden":1,"bounds":1,"right":1,"top":1,"bottom":1,"width":1,"height":1,"rotation":1,"startpoint":1}
,"repeating":{"fields":1}
,"fields":{"portalrownumber":1,"portals":1,"-returns":1,"graphics":1}
,"row":{"portal":1,"selected":1,"repetitionnumber":1,"stores":1}
,"portal":{"parameters":1,"portal":1,"row":1}
,"parameters":{"braces":1,"reference":1}
,"braces":{"optional":1}
,"optional":{"text":1}
,"text":{"filemaker":1,"hasfocus":1,"left":1,"source":1,"objects":1,"return":1,"content":1,"including":1,"merge":1,"all":1,"enclosingobject":1,"containedobjects":1,"object":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"8.5":1}
,"8.5":{"attribute":1}
,"data":{"type":1,"image":1,"formatted":1,"name":1,"server":1,"first":1}
,"type":{"returned":1,"english":1}
,"returned":{"objecttype":1,"based":1,"repetitionnumber":1}
,"objecttype":{"object\u0027s":1}
,"object\u0027s":{"type":1,"properties":1}
,"english":{"text":1}
,"hasfocus":{"if":1}
,"if":{"objectname":1,"bject":1,"target":1,"image":1,"objects":1,"parameter":1}
,"focus":{"returns":1,"fields":1,"if":1}
,"objects":{"focus":1,"contain":1,"popovers":1,"return":1,"-returns":1,"text":1,"contained":1,"set":1,"located":1}
,"portals":{"tab":1,"-returns":1,"contain":1}
,"tab":{"panels":1,"slide":1}
,"panels":{"slide":1,"buttons":1,"button":1}
,"slide":{"panels":1,"panel":1}
,"buttons":{"popover":1,"harts":1,"popovers":1,"-returns":1}
,"popover":{"buttons":1}
,"harts":{"groups":1}
,"groups":{"returns":1,"number":1,"tab":1}
,"selected":{"number":1}
,"containsfocus":{"if":1}
,"bject":{"focus":1}
,"contain":{"focus":1,"objects":1}
,"button":{"bars":1}
,"bars":{"uttons":1,"popover":1,"opover":1}
,"uttons":{"popover":1}
,"popovers":{"charts":1,"right":1,"portals":1}
,"charts":{"groups":1,"-returns":1}
,"isfrontpanel":{"if":1}
,"target":{"object":1}
,"panel":{"front":1}
,"front":{"number":1}
,"isactive":{"if":1}
,"isobjecthidden":{"if":1}
,"hidden":{"current":1}
,"record":{"returns":1}
,"right":{"layout":1,"right":1,"edge":1}
,"boundary":{"number":1}
,"bounds":{"list":1,"left":1,"object":1,"parameters":1}
,"list":{"numeric":1,"named":1}
,"numeric":{"values":1}
,"values":{"separated":1,"horizontal":1,"returned":1}
,"separated":{"by":1}
,"spaces":{"describes":1,"represent":1}
,"describes":{"placement":1}
,"placement":{"object":1}
,"top-left":{"bottom-right":1,"point":1,"corner":1}
,"bottom-right":{"rotation":1,"point":1}
,"rotation":{"text":1,"rotation":1,"degrees":1}
,"left":{"left":1,"edge":1,"top":1}
,"edge":{"coordinate":1}
,"coordinate":{"object":1,"values":1}
,"top":{"top":1,"edge":1,"bottom":1}
,"bottom":{"bottom":1,"edge":1,"startpoint":1}
,"width":{"width":1,"object":1}
,"height":{"height":1,"object":1}
,"degrees":{"object":1}
,"startpoint":{"endpoint":1,"bottom-right":1}
,"endpoint":{"pair":1,"text":1,"filemaker":1}
,"pair":{"numeric":1}
,"horizontal":{"vertical":1}
,"vertical":{"separated":1}
,"represent":{"start":1}
,"start":{"point":1}
,"point":{"end":1,"line":1,"startpoint":1,"endpoint":1}
,"end":{"point":1}
,"line":{"object":1}
,"return":{"top-left":1,"merge":1,"empty":1}
,"source":{"source":1,"description":1,"attributes":1,"acts":1,")]":1}
,"description":{"object":1,"chart":1}
,"web":{"viewers":1,"viewer":1,"viewer\u0027s":1}
,"viewers":{"-returns":1}
,"-returns":{"current":1,"qualified":1,"text":1,"ame":1,"image":1,"xml":1,"empty":1,"field":1,"bitmap":1,"button\u2019s":1}
,"url":{"fields":1,"search":1}
,"qualified":{"field":1}
,"field":{"name":1,"data":1,"if":1,"externally":1,"returning":1,"repetition":1,"set":1,"[search":1}
,"table":{"name":1,"occurrence":1}
,":field":{"name":1}
,"merge":{"fields":1}
,"ame":{"table":1}
,"occurrence":{"graphics":1}
,"graphics":{"-returns":1}
,"image":{"data":1,"filename":1,"stored":1,"unstored":1}
,"filename":{"charts":1}
,"xml":{"description":1}
,"chart":{"object":1,"content":1}
,"all":{"objects":1}
,"empty":{"string":1}
,"string":{"text":1,"groups":1,"if":1}
,"content":{"content":1,"object":1,"html":1,"source":1}
,"html":{"code":1}
,"code":{"fields":1}
,"formatted":{"object\u0027s":1}
,"properties":{"text":1}
,"including":{"text":1}
,"file":{"container":1,"if":1}
,"container":{"field":1}
,"stored":{"field":1}
,"externally":{"reference":1}
,"reference":{"file":1,"field":1}
,"unstored":{"charts":1}
,"bitmap":{"representation":1}
,"representation":{"chart":1}
,"button\u2019s":{"text":1}
,"enclosingobject":{"objectname":1}
,"enclosing":{"layout":1}
,"containedobjects":{"list":1}
,"contained":{"objectname":1}
,"opover":{"buttons":1}
,"coordinates":{"points":1,"bounds":1}
,"points":{"relative":1}
,"relative":{"top-left":1}
,"corner":{"primary":1}
,"primary":{"screen\u2019s":1}
,"screen\u2019s":{"screen":1}
,"screen":{"excluding":1,"attributes":1}
,"excluding":{"taskbar":1,"menu":1}
,"taskbar":{"windows":1}
,"windows":{"screen":1}
,"menu":{"bar":1}
,"bar":{"dock":1}
,"dock":{"macos":1}
,"macos":{"ios":1}
,"ios":{"entire":1}
,"entire":{"screen":1,"field":1}
,"webdirect":{"function":1,"attributes":1,"last":1}
,"function":{"acts":1,"behaves":1,"returns":1}
,"acts":{"web":1,"first":1,"entire":1}
,"viewer":{"chart":1,"source":1}
,"set":{"auto-resize":1,"field":1}
,"auto-resize":{"attributes":1}
,"based":{"resized":1,"bounds":1}
,"resized":{"bounds":1}
,"state":{"filemaker":1}
,"last":{"communicated":1}
,"communicated":{"layout":1}
,"server":{"user":1}
,"user":{"switched":1}
,"switched":{"layout":1}
,"located":{"status":1}
,"status":{"toolbar":1}
,"toolbar":{"negative":1}
,"negative":{"coordinate":1}
,"behaves":{"if":1}
,"parameter":{"portalrownumber":1}
,"first":{"portal":1,"repetition":1}
,"returning":{"content":1,"bounds":1}
,"stores":{"web":1}
,"viewer\u0027s":{"current":1}
,"search":{":homepage":1}
,":homepage":{"field":1,"getlayoutobjectattribute":1}
,"[search":{":homepage":1}
,")]":{"attributes":1}
}
;Search.control.loadWordPairs(pairs);
