var pairs =
{
"get":{"windowhei":1,"windowheight":1,"window":1}
,"windowhei":{"ght":1}
,"ght":{"returns":1}
,"returns":{"height":1,"300":1}
,"height":{"points":1,"window":1,"include":1,"300":1}
,"points":{"window":1,"get":1}
,"window":{"script":1,"calculated":1,"position":1,"height":1,"get":1}
,"script":{"acting":1}
,"acting":{"get":1,"foreground":1}
,"windowheight":{"none":1,"returns":1,"get":1}
,"none":{"number":1}
,"number":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"7.0":1}
,"7.0":{"height":1}
,"calculated":{"top":1}
,"top":{"bottom":1}
,"bottom":{"outer":1}
,"outer":{"edges":1}
,"edges":{"window":1}
,"position":{"doesn\u2019t":1}
,"doesn\u2019t":{"include":1}
,"include":{"shadows":1,"menus":1}
,"shadows":{"effects":1}
,"effects":{"applied":1}
,"applied":{"windows":1}
,"windows":{"filemaker":1}
,"webdirect":{"window":1}
,"menus":{"toolbars":1}
,"toolbars":{"part":1}
,"part":{"web":1}
,"web":{"browser":1}
,"browser":{"window":1}
,"foreground":{"window":1}
,"300":{"current":1,"points":1}
,"current":{"window\u2019s":1}
,"window\u2019s":{"height":1}
}
;Search.control.loadWordPairs(pairs);
