var pairs =
{
"backup":{"script":1,"opies":1,"copy.fmp12":1,"file":1}
,"script":{"use":1,"save":1,"saves":1,"define":1,"all":1,"workspace":1,"button":1,"ackup":1,"steps":1,"editing":1,"triggers":1,"trigger":1,"10":1,"create":1}
,"use":{"script":1}
,"save":{"automated":1,"close":1}
,"automated":{"backup":1}
,"opies":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"database":1,"increment":1}
,"database":{"script":1,"close":1,"if":1}
,"saves":{"copy":1}
,"copy":{"database":1,"current":1}
,"close":{"close":1,"thereafter":1,"application":1,"tab":1,"script":1,"solution":1,"file":1}
,"thereafter":{"script":1}
,"define":{"global":1,"script":1}
,"global":{"field":1,"number":1}
,"field":{"called":1,"tables":1,"filemaker":1,"[<":1,"table":1,"1]":1,"4]":1,"0]":1}
,"called":{"count":1}
,"count":{"field":1}
,"tables":{"database":1}
,"if":{"define":1,"finished":1}
,"number":{"field":1}
,"increment":{"record":1}
,"record":{"each":1}
,"each":{"time":1}
,"time":{"close":1}
,"application":{"define":1}
,"all":{"solution":1}
,"solution":{"files":1,"file":1}
,"files":{"require":1}
,"require":{"backups":1}
,"backups":{"choose":1}
,"choose":{"scripts":1,"file":1}
,"scripts":{"menu":1,"script":1,"creating":1,"name":1}
,"menu":{"cript":1,"manage":1,"file":1}
,"cript":{"workspace":1}
,"workspace":{"choose":1,"new":1}
,"file":{"menu":1,"create":1,"options":1,"script":1,"time":1}
,"manage":{"scripts":1}
,"new":{"script":1}
,"button":{"details":1}
,"details":{"creating":1}
,"creating":{"scripts":1,"editing":1}
,"editing":{"scripts":1,"pane":1}
,"name":{"script":1,":count":1}
,"ackup":{"press":1}
,"press":{"enter":1}
,"enter":{"en":1}
,"en":{"ter":1}
,"ter":{"script":1}
,"steps":{"et":1}
,"et":{"field":1}
,"[<":{"table":1}
,"table":{"name":1}
,":count":{"field":1}
,"1]":{"[<":1}
,"4]":{"ave":1}
,"ave":{"co":1}
,"co":{"py":1}
,"py":{"[\u0022":1}
,"[\u0022":{"backup":1}
,"copy.fmp12":{"copy":1}
,"current":{"file":1}
,"create":{"folders":1,"backup":1,"script":1}
,"folders":{"off]":1}
,"off]":{"et":1}
,"0]":{"nd":1}
,"nd":{"if":1}
,"finished":{"close":1}
,"tab":{"script":1,"onlastwindowclose":1}
,"pane":{"save":1}
,"options":{"script":1}
,"triggers":{"tab":1}
,"onlastwindowclose":{"script":1}
,"trigger":{"select":1}
,"select":{"select":1,"backup":1}
,"10":{"11":1}
,"11":{"close":1}
}
;Search.control.loadWordPairs(pairs);
