var pairs =
{
"filtervalues":{"returns":1,"order":1,"texttofilter":1,"-values":1,"parameter":1,"function":1,"plaid":1,"valuelistitems":1}
,"returns":{"text":1,"plaid":1,"medium":1}
,"text":{"result":1,"expression":1,"field":1,"text":1,"filemaker":1}
,"result":{"values":1}
,"values":{"filtervalues":1,"valuecount":1,"empty":1}
,"order":{"originally":1}
,"originally":{"entered":1}
,"entered":{"texttofilter":1}
,"texttofilter":{"filtervalues":1,"-any":1}
,"-any":{"text":1}
,"expression":{"text":1}
,"field":{"filtervalues":1}
,"-values":{"want":1}
,"want":{"preserve":1}
,"preserve":{"text":1}
,"filemaker":{"pro":1}
,"pro":{"7.0":1}
,"7.0":{"description":1}
,"description":{"list":1}
,"list":{"values":1,"sizes":1}
,"valuecount":{"function":1}
,"function":{"each":1,"case":1}
,"each":{"returned":1}
,"returned":{"value":1,"filtervalues":1}
,"value":{"carriage":1,"list":1}
,"carriage":{"return":1}
,"return":{"allowing":1}
,"allowing":{"lists":1}
,"lists":{"easily":1}
,"easily":{"concatenated":1}
,"concatenated":{"if":1}
,"if":{"filtervalues":1}
,"parameter":{"doesn\u2019t":1}
,"doesn\u2019t":{"values":1}
,"empty":{"string":1}
,"string":{"returned":1}
,"case":{"sensitive":1}
,"sensitive":{"filtervalues":1}
,"plaid":{"canvas":1}
,"canvas":{"suitcase":1,"returns":1,"filtervalues":1}
,"suitcase":{"plaid":1}
,"valuelistitems":{"database":1}
,"database":{"sizes":1,"file":1,"value":1}
,"sizes":{"medium":1}
,"medium":{"returns":1,"hen":1,"large":1}
,"hen":{"database":1}
,"file":{"named":1}
,"named":{"database":1}
}
;Search.control.loadWordPairs(pairs);
