var pairs =
{
"planning":{"security":1}
,"security":{"shared":1,"file":1,"guide":1,"settings":1,"computers":1,"tips":1}
,"shared":{"ile":1,"file":1,"network":1}
,"ile":{"new":1}
,"new":{"filemaker":1}
,"filemaker":{"pro":1,"security":1,"file":1,"id":1,"cloud":1,"server":1,"webdirect":1}
,"pro":{"advanced":1}
,"advanced":{"file":1,"access":1,"databases":1}
,"file":{"initially":1,"automatically":1,"use":1,"secure":1,"depends":1,"if":1,"computer":1,"assword-protecting":1,"provide":1,"access":1,"follow":1,"additionally":1,"by":1,"attempts":1,"list":1,"want":1,"predefined":1,"filemaker":1,"account":1,"creating":1,"network":1,"web":1,"odbc":1,"users":1,"accounts":1,"set":1,"additional":1}
,"initially":{"unprotected":1}
,"unprotected":{"file":1}
,"automatically":{"logs":1}
,"logs":{"user":1}
,"user":{"admin":1,"access":1}
,"admin":{"account":1,"guest":1}
,"account":{"assigned":1,"credentials":1,"permits":1,"bout":1,"access":1,"assign":1,"anaging":1}
,"assigned":{"full":1}
,"full":{"access":1}
,"access":{"privilege":1,"nd":1,"users":1,"tables":1,"require":1,"file":1,"want":1,"tab":1,"files":1,"privileges":1,"authorized":1}
,"privilege":{"set":1,"sets":1}
,"set":{"permits":1,"each":1,"disable":1,"sure":1,"created":1,"screen":1}
,"permits":{"user":1,"users":1}
,"nd":{"chang":1}
,"chang":{"verything":1}
,"verything":{"file":1}
,"use":{"accounts":1,"groups":1,"file":1,"operating":1}
,"accounts":{"privilege":1,"authenticate":1,"create":1,"test":1}
,"sets":{"secure":1,"file":1,"enforce":1,"meet":1,"determine":1,"if":1,"open":1,"don\u2019t":1,"optionally":1,"provide":1}
,"secure":{"database":1,"file":1,"solution":1}
,"database":{"file":1,"protection":1,"files":1}
,"depends":{"share":1}
,"share":{"file":1,"database":1}
,"if":{"simply":1,"share":1,"want":1,"enable":1,"you\u2019re":1,"host":1}
,"simply":{"want":1}
,"want":{"keep":1,"protect":1,"enable":1,"privilege":1,"open":1,"corrections":1}
,"keep":{"else":1}
,"else":{"database":1}
,"computer":{"password-protect":1,"shared":1,"screen":1}
,"password-protect":{"file":1}
,"assword-protecting":{"local":1}
,"local":{"file":1}
,"provide":{"varying":1,"database":1}
,"varying":{"levels":1}
,"levels":{"file":1}
,"users":{"plan":1,"individually":1,"individual":1,"supported":1,"groups":1,"open":1}
,"plan":{"security":1,"number":1}
,"follow":{"steps":1}
,"steps":{"plan":1}
,"additionally":{"protect":1}
,"protect":{"file":1,"tables":1,"access":1,"files":1,"physical":1}
,"by":{"requiring":1,"supported":1,"filemaker":1,"use":1}
,"requiring":{"authorization":1}
,"authorization":{"file":1}
,"attempts":{"access":1}
,"tables":{"layouts":1,"fields":1}
,"layouts":{"value":1}
,"value":{"lists":1}
,"lists":{"scripts":1}
,"scripts":{"thorizing":1,"plan":1}
,"thorizing":{"ccess":1}
,"ccess":{"files":1}
,"files":{"filemaker":1,"hosted":1,"accessing":1,"by":1,"accounts":1,"rely":1,"while":1,"reside":1}
,"guide":{"determine":1}
,"determine":{"privilege":1,"grant":1,"if":1}
,"list":{"file":1}
,"fields":{"records":1}
,"records":{"layouts":1}
,"number":{"privilege":1}
,"enforce":{"varying":1}
,"require":{"note":1,"password":1}
,"note":{"each":1}
,"each":{"database":1,"if":1,"privilege":1}
,"predefined":{"privilege":1}
,"meet":{"all":1}
,"all":{"sing":1}
,"sing":{"predefined":1}
,"grant":{"access":1,"account":1}
,"individually":{"groups":1}
,"groups":{"users":1,"they\u2019re":1,"supported":1,"assign":1}
,"individual":{"users":1}
,"supported":{"accounts":1,"identity":1}
,"authenticate":{"via":1}
,"via":{"filemaker":1,"external":1,"oauth":1}
,"id":{"oauth":1,"files":1}
,"oauth":{"identity":1}
,"identity":{"providers":1,"provider":1}
,"providers":{"use":1,"creating":1}
,"they\u2019re":{"defined":1,"grant":1}
,"defined":{"by":1}
,"provider":{"groups":1,"files":1,"decide":1}
,"hosted":{"by":1}
,"cloud":{"azure":1,"filemaker":1}
,"azure":{"ad":1}
,"ad":{"oauth":1}
,"server":{"external":1,"files":1,"manage":1,"creating":1}
,"external":{"authentication":1,"server":1}
,"authentication":{"server":1,"servers":1}
,"manage":{"account":1}
,"credentials":{"via":1}
,"servers":{"oauth":1}
,"creating":{"accounts":1,"editing":1}
,"decide":{"if":1}
,"enable":{"guest":1,"extended":1}
,"guest":{"account":1,"accounts":1}
,"open":{"file":1,"shared":1}
,"bout":{"admin":1}
,"create":{"privilege":1}
,"editing":{"privilege":1}
,"extended":{"privileges":1}
,"privileges":{"privilege":1,"they\u2019re":1,"if":1}
,"network":{"client":1,"use":1}
,"client":{"access":1}
,"web":{"browser":1}
,"browser":{"via":1}
,"webdirect":{"access":1}
,"odbc":{"jdbc":1}
,"jdbc":{"data":1}
,"data":{"source":1}
,"source":{"enable":1}
,"don\u2019t":{"enable":1}
,"assign":{"privilege":1}
,"you\u2019re":{"guest":1}
,"disable":{"guest":1}
,"anaging":{"accounts":1}
,"test":{"each":1}
,"sure":{"restricts":1,"restrictions":1}
,"restricts":{"file":1}
,"created":{"sure":1}
,"restrictions":{"want":1}
,"corrections":{"privilege":1}
,"optionally":{"limit":1}
,"limit":{"files":1}
,"accessing":{"schema":1}
,"schema":{"files":1}
,"tab":{"thorizing":1}
,"protection":{"100":1}
,"100":{"secure":1}
,"solution":{"take":1}
,"take":{"reasonable":1}
,"reasonable":{"measures":1}
,"measures":{"protect":1}
,"rely":{"solely":1}
,"solely":{"filemaker":1}
,"host":{"filemaker":1}
,"databases":{"computer":1}
,"operating":{"system":1}
,"system":{"level":1,"require":1}
,"level":{"security":1}
,"settings":{"passwords":1}
,"passwords":{"restrict":1}
,"restrict":{"folder":1}
,"folder":{"file":1}
,"authorized":{"personnel":1}
,"personnel":{"protect":1}
,"while":{"stored":1}
,"stored":{"disk":1}
,"disk":{"encrypt":1}
,"encrypt":{"encrypting":1}
,"encrypting":{"database":1}
,"screen":{"saver":1}
,"saver":{"feature":1,"protect":1}
,"feature":{"operating":1}
,"password":{"order":1}
,"order":{"wake":1}
,"wake":{"up":1}
,"up":{"computer":1}
,"physical":{"security":1}
,"computers":{"hard":1}
,"hard":{"drives":1}
,"drives":{"backup":1}
,"backup":{"storage":1}
,"storage":{"media":1}
,"media":{"database":1}
,"reside":{"plan":1}
,"additional":{"security":1}
}
;Search.control.loadWordPairs(pairs);
