var pairs =
{
"cr":{"eating":1}
,"eating":{"custom":1}
,"custom":{"plug-ins":1,"plug-in":1}
,"plug-ins":{"if":1,"take":1,"filemaker":1,"hosted":1,"preferences":1,"optional":1,"update":1,"plug-ins":1,"file":1}
,"if":{"programmer":1,"lug-in":1}
,"programmer":{"familiar":1}
,"familiar":{"calculations":1}
,"calculations":{"scripts":1}
,"scripts":{"filemaker":1}
,"filemaker":{"pro":1,"lug-ins":1,"plug-in":1,"server":1,"cloud":1,"solution":1,"go":1}
,"pro":{"advanced":1}
,"advanced":{"create":1,"users":1,".fmx64":1,"macos":1,"etting":1}
,"create":{"filemaker":1,"custom":1,"plug-in":1}
,"lug-ins":{"plug-ins":1,"installed":1}
,"take":{"advantage":1}
,"advantage":{"recursion":1}
,"recursion":{"looping":1}
,"looping":{"hook":1}
,"hook":{"programming":1}
,"programming":{"interfaces":1}
,"interfaces":{"create":1}
,"plug-in":{"filemaker":1,"sdk":1,"file":1,"extension":1,"digitally":1,"optional":1,"load":1,"preferences":1,"updates":1,"sort":1,"choose":1}
,"sdk":{"use":1}
,"use":{"plug-ins":1,"function":1,"script":1}
,"users":{"eed":1,"permit":1,"disable":1}
,"eed":{"allow":1}
,"allow":{"solution":1,"install":1,"solutions":1}
,"solution":{"files":1,"installing":1,"file":1}
,"files":{"install":1,"plug-in":1,"contact":1}
,"install":{"enable":1,"plug-in":1,"compiled":1,"files":1}
,"enable":{"plug-ins":1,"configure":1}
,"hosted":{"iles":1}
,"iles":{"server":1}
,"server":{"administrator":1,"filemaker":1,"admin":1}
,"administrator":{"allow":1,"customer":1}
,"file":{"script":1,"windows":1,"container":1,"check":1,"sers":1}
,"script":{"step":1,"steps":1,"workspace":1}
,"step":{"update":1,"by":1,"security":1}
,"update":{"lug-ins":1,"if":1,"enable":1,"use":1}
,"installed":{"server":1,"plug-ins":1,"automatically":1}
,"admin":{"console":1}
,"console":{"filemaker":1,"create":1}
,"cloud":{"dmin":1}
,"dmin":{"console":1}
,"windows":{"plug-in":1}
,"extension":{".fmx":1,".fmplugin":1}
,".fmx":{"32-bit":1}
,"32-bit":{"filemaker":1}
,".fmx64":{"64-bit":1}
,"64-bit":{"filemaker":1}
,"macos":{"plug-in":1}
,".fmplugin":{"compile":1}
,"compile":{"test":1}
,"test":{"plug-in":1}
,"digitally":{"signing":1}
,"signing":{"plug-in":1}
,"optional":{"users":1,"set":1,"select":1}
,"permit":{"unsigned":1}
,"unsigned":{"plug-in":1}
,"load":{"etting":1}
,"etting":{"permitted":1,"plug-in":1}
,"permitted":{"hosts":1}
,"hosts":{"plug-ins":1}
,"preferences":{"install":1,"dialog":1,"optional":1,"plug-in":1}
,"compiled":{"plug-in":1}
,"container":{"field":1}
,"field":{"filemaker":1}
,"installing":{"plug-ins":1}
,"set":{"up":1}
,"up":{"solution":1}
,"check":{"version":1}
,"version":{"installed":1}
,"lug-in":{"update":1}
,"configure":{"plug-ins":1}
,"dialog":{"box":1}
,"box":{"filemaker":1,"by":1}
,"select":{"allow":1}
,"solutions":{"install":1}
,"updates":{"installed":1}
,"automatically":{"lug-in":1}
,"function":{"by":1,"use":1}
,"by":{"plug-in":1,"type":1,"category":1}
,"sort":{"list":1}
,"list":{"functions":1,"script":1}
,"functions":{"calculation":1}
,"calculation":{"dialog":1}
,"type":{"under":1}
,"under":{"name":1}
,"name":{"plug-in":1}
,"choose":{"function":1,"script":1}
,"steps":{"script":1}
,"workspace":{"by":1}
,"category":{"under":1}
,"security":{"reasons":1}
,"reasons":{"system":1}
,"system":{"administrators":1,"administrator":1}
,"administrators":{"require":1}
,"require":{"users":1}
,"disable":{"allow":1}
,"contact":{"system":1}
,"customer":{"filemaker":1}
,"go":{"prepare":1}
,"prepare":{"custom":1}
}
;Search.control.loadWordPairs(pairs);
