var pairs =
{
"bout":{"admin":1}
,"admin":{"guest":1,"account":1,"password":1}
,"guest":{"accounts":1,"admin":1,"account":1,"by":1,"option":1,"enable":1,"access":1,"open":1}
,"accounts":{"each":1,"warning":1,"default":1}
,"each":{"database":1}
,"database":{"file":1}
,"file":{"initially":1,"ccounts":1,"by":1,"options":1,"admin":1,"permit":1,"guest":1}
,"initially":{"two":1}
,"two":{"filemaker":1}
,"filemaker":{"file":1,"server":1,"cloud":1}
,"ccounts":{"admin":1}
,"account":{"assigned":1,"blank":1,"admin":1,"editable":1,"inactive":1,"se":1,"name":1,"guest":1,"determines":1,"note":1,"open":1,"permit":1,"change":1}
,"assigned":{"full":1,"read-only":1}
,"full":{"access":1}
,"access":{"privilege":1,"file":1,"change":1,"files":1}
,"privilege":{"set":1}
,"set":{"permits":1,"up":1,"write":1,"assign":1,"want":1}
,"permits":{"access":1}
,"by":{"default":1}
,"default":{"th":1,"guest":1,"password":1,"admin":1}
,"th":{"admin":1}
,"blank":{"assword":1}
,"assword":{"files":1}
,"files":{"privileges":1,"filemaker":1,"active":1,"guest":1,"protected":1}
,"privileges":{"set":1,"users":1}
,"up":{"file":1,"automatically":1}
,"options":{"set":1}
,"automatically":{"log":1}
,"log":{"file":1}
,"editable":{"rename":1,"delete":1}
,"rename":{"assign":1}
,"assign":{"password":1,"privilege":1}
,"password":{"account":1,"assigned":1,"access":1,"guest":1,"creating":1,"default":1,"admin":1}
,"inactive":{"delete":1,"disables":1}
,"delete":{"admin":1,"guest":1}
,"se":{"creating":1}
,"creating":{"editing":1}
,"editing":{"accounts":1}
,"warning":{"passwords":1}
,"passwords":{"recovered":1}
,"recovered":{"n\u2019t":1}
,"n\u2019t":{"forget":1}
,"forget":{"account":1}
,"name":{"password":1,"assign":1}
,"write":{"store":1}
,"store":{"secure":1}
,"secure":{"place":1}
,"place":{"if":1}
,"if":{"lose":1,"configured":1}
,"lose":{"forget":1}
,"change":{"file":1,"guest":1}
,"permit":{"users":1,"guest":1}
,"users":{"open":1,"files":1}
,"open":{"file":1,"by":1,"ialog":1,"ing":1}
,"determines":{"privileges":1}
,"read-only":{"access":1}
,"want":{"guest":1}
,"note":{"filemaker":1}
,"server":{"if":1}
,"configured":{"require":1}
,"require":{"password-protected":1}
,"password-protected":{"files":1}
,"cloud":{"don\u2019t":1}
,"don\u2019t":{"allow":1}
,"allow":{"hosted":1}
,"hosted":{"files":1}
,"active":{"guest":1}
,"disables":{"guest":1}
,"option":{"open":1}
,"ialog":{"box":1}
,"box":{"prohibits":1}
,"prohibits":{"users":1}
,"enable":{"guest":1}
,"ing":{"files":1}
,"protected":{"password":1}
}
;Search.control.loadWordPairs(pairs);
