var pairs =
{
"setti":{"ng":1}
,"ng":{"up":1}
,"up":{"recurring":1,"filemaker":1,"file":1,"automatic":1}
,"recurring":{"imports":1,"import":1}
,"imports":{"set":1,"filemaker":1,"open":1,"creating":1}
,"set":{"up":1,"privilege":1}
,"filemaker":{"pro":1,"pr":1}
,"pro":{"advanced":1}
,"advanced":{"file":1,"creates":1,"deletes":1,"note":1,"create":1,"data":1,"import":1,"session":1}
,"file":{"automatically":1,"excel":1,"first":1,"run":1,"data":1,"account":1,"create":1,"open":1,"want":1,"managing":1,"menu":1,"files":1,"types":1,"formats":1,"selected":1,"import":1,"next":1,"by":1,"closed":1,"folder":1,"log":1,"updated":1,"located":1,"grow":1}
,"automatically":{"update":1,"time":1,"generated":1}
,"update":{"data":1,"first":1}
,"data":{"imported":1,"external":1,"set":1,"new":1,"customize":1,"filemaker":1,"recurring":1,"want":1,"accept":1,"manually":1,"excel":1,"worksheet":1,"if":1,"existing":1,"first":1,"source":1,"while":1,"creates":1,"found":1}
,"imported":{"file":1,"data":1,"via":1,"first":1,"filemaker":1,"records":1}
,"excel":{"spreadsheet":1,"workbooks":1,"file":1}
,"spreadsheet":{"recurring":1}
,"import":{"occurs":1,"layout":1,"modified":1,"set":1,"records":1,"choose":1,"select":1,"open":1,"setup":1,"first":1,"by":1,"data":1,"creates":1,"recurring":1,"import-only":1,"log":1,"script":1,"supported":1}
,"occurs":{"automatically":1}
,"time":{"open":1,"view":1,"update":1,"filemaker":1,"data":1}
,"open":{"file":1,"path":1}
,"first":{"time":1,"record":1,"modify":1}
,"view":{"layout":1,"table":1,"viewing":1}
,"layout":{"data":1,"display":1,"layout":1,"mode":1,"replaces":1,"name":1,"filemaker":1,"new":1,"appears":1,"imported":1,"database":1,"if":1,"update":1,"during":1}
,"external":{"file":1,"files":1}
,"run":{"script":1}
,"script":{"update":1,"name":1,"use":1,"button":1,"planning":1,"filemaker":1}
,"creates":{"new":1,"import":1,"recurring":1}
,"new":{"table":1,"layout":1,"file":1,"name":1,"records":1,"data":1}
,"table":{"imported":1,"view":1,"recurring":1,"layout":1}
,"display":{"data":1,"imported":1}
,"customize":{"layout":1}
,"mode":{"if":1,"choose":1,"table":1}
,"if":{"each":1,"importing":1,"want":1,"made":1}
,"each":{"time":1}
,"deletes":{"data":1,"all":1}
,"replaces":{"current":1}
,"current":{"data":1}
,"via":{"recurring":1}
,"modified":{"filemaker":1}
,"note":{"set":1,"import":1}
,"account":{"assigned":1,"full":1}
,"assigned":{"full":1}
,"full":{"access":1}
,"access":{"privilege":1,"privileges":1}
,"privilege":{"set":1,"sets":1,"users":1}
,"sets":{"accounts":1,"extended":1}
,"accounts":{"privilege":1}
,"extended":{"privilege":1}
,"users":{"use":1}
,"use":{"account":1,"recurring":1,"update":1,"script":1}
,"privileges":{"use":1}
,"create":{"new":1,"display":1}
,"want":{"set":1,"import":1,"add":1,"modify":1}
,"creating":{"filemaker":1,"scripts":1}
,"managing":{"files":1}
,"files":{"browse":1,"type":1,"saved":1}
,"browse":{"mode":1}
,"choose":{"file":1,"excel":1,"worksheet":1}
,"menu":{"import":1}
,"records":{"file":1,"form":1,"reimports":1,"new":1}
,"type":{"windows":1,"file":1,"new":1}
,"windows":{"show":1}
,"show":{"macos":1}
,"macos":{"select":1}
,"select":{"type":1,"file":1,"set":1,"don\u2019t":1}
,"workbooks":{"(*":1}
,"(*":{"xlsx":1}
,"xlsx":{"list":1}
,"list":{"supported":1,"table":1}
,"supported":{"file":1,"import\u002Fexport":1,"server-side":1}
,"types":{"supported":1}
,"import\u002Fexport":{"file":1}
,"formats":{"locate":1}
,"locate":{"select":1}
,"automatic":{"recurring":1}
,"path":{"file":1}
,"selected":{"appears":1}
,"appears":{"recurring":1,"browse":1}
,"setup":{"dialog":1}
,"dialog":{"box":1}
,"box":{"skip":1}
,"skip":{"importing":1}
,"importing":{"column":1,"data":1}
,"column":{"headings":1}
,"headings":{"select":1}
,"don\u2019t":{"import":1}
,"record":{"field":1}
,"field":{"names":1}
,"names":{"accept":1}
,"accept":{"default":1}
,"default":{"layout":1,"script":1}
,"name":{"type":1,"layout":1,"script":1}
,"manually":{"10":1}
,"10":{"if":1}
,"by":{"worksheet":1,"named":1,"clicking":1}
,"worksheet":{"by":1,"named":1}
,"named":{"range":1}
,"range":{"choose":1,"note":1,"layout":1}
,"viewing":{"records":1}
,"form":{"list":1}
,"add":{"imported":1}
,"existing":{"table":1}
,"database":{"importing":1}
,"pr":{"advanced":1}
,"saved":{"original":1}
,"original":{"application":1}
,"application":{"filemaker":1}
,"import-only":{"process":1}
,"process":{"data":1}
,"modify":{"data":1,"import":1}
,"source":{"file":1}
,"next":{"import":1,"filemaker":1}
,"clicking":{"script":1}
,"button":{"recurring":1,"update":1}
,"made":{"data":1}
,"while":{"filemaker":1}
,"closed":{"data":1}
,"during":{"next":1}
,"session":{"data":1}
,"log":{"file":1}
,"folder":{"filemaker":1,"use":1}
,"updated":{"each":1}
,"located":{"folder":1}
,"all":{"imported":1}
,"reimports":{"data":1}
,"found":{"external":1}
,"grow":{"find":1}
,"find":{"want":1}
,"planning":{"creating":1}
,"scripts":{"automating":1,"automatically":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
,"generated":{"script":1}
,"server-side":{"cript":1}
,"cript":{"set":1}
}
;Search.control.loadWordPairs(pairs);
