var pairs =
{
"pecify":{"grand":1}
,"grand":{"totals":1,"total":1,"summary":1}
,"totals":{"new":1,"include":1,"panel":1,"remove":1}
,"new":{"layout\u002Freport":1,"summary":1}
,"layout\u002Freport":{"assistant":1}
,"assistant":{"if":1,"define":1,"modify":1,"determines":1,"grand":1}
,"if":{"selected":1,"define":1}
,"selected":{"include":1}
,"include":{"grand":1,"subtotals":1}
,"subtotals":{"grand":1}
,"panel":{"use":1,"define":1,"defining":1}
,"use":{"panel":1}
,"define":{"summary":1,"new":1,"ummary":1,"grand":1}
,"summary":{"field":1,"fields":1,"select":1,"definition":1,"list":1,"remove":1,"panel":1,"part":1,"placement":1,"assistant":1}
,"field":{"hoose":1,"list":1,"fields":1,"type":1,"current":1,"dialog":1,"table":1}
,"hoose":{"summary":1}
,"list":{"define":1,"se":1,"change":1}
,"fields":{"defined":1,"note":1,"grand":1,"finish":1}
,"defined":{"summary":1}
,"type":{"list":1}
,"current":{"table":1}
,"table":{"add":1,"choose":1}
,"add":{"se":1,"grand":1}
,"se":{"options":1,"defining":1}
,"options":{"su":1}
,"su":{"mmary":1}
,"mmary":{"field":1}
,"dialog":{"box":1}
,"box":{"new":1}
,"choose":{"manage":1,"report":1,"finish":1}
,"manage":{"database":1}
,"database":{"list":1}
,"defining":{"summary":1,"grand":1}
,"note":{"full":1}
,"full":{"access":1}
,"access":{"privileges":1}
,"privileges":{"define":1}
,"ummary":{"fields":1}
,"total":{"placement":1,"remove":1,"double-click":1}
,"placement":{"choose":1,"order":1}
,"report":{"end":1,"change":1}
,"end":{"report":1,"lick":1}
,"lick":{"add":1}
,"remove":{"grand":1}
,"select":{"grand":1}
,"definition":{"grand":1,"redefine":1}
,"double-click":{"grand":1}
,"change":{"grand":1,"order":1}
,"redefine":{"define":1}
,"part":{"leading":1,"if":1,"report":1}
,"leading":{"trailing":1}
,"trailing":{"depending":1}
,"depending":{"placement":1}
,"finish":{"assistant":1}
,"modify":{"characteristics":1}
,"characteristics":{"pagination":1}
,"pagination":{"page":1}
,"page":{"numbering":1}
,"numbering":{"hanging":1}
,"hanging":{"layout":1}
,"layout":{"part":1}
,"order":{"define":1,"summary":1}
,"determines":{"order":1}
}
;Search.control.loadWordPairs(pairs);
