var pairs =
{
"open":{"file":1,"hidden":1,"add":1,"manage":1,"database":1}
,"file":{"pens":1,"perform":1,"script":1,"by":1,"filemaker":1,"dialog":1,"open":1,"types":1,"bound":1,"unauthorized":1,"if":1,"hidden":1,"[open":1,"invoices":1}
,"pens":{"ilemaker":1}
,"ilemaker":{"pro":1,"data":1}
,"pro":{"advanced":1,"6.0":1}
,"advanced":{"ile":1,"atabase":1,"isplays":1,"convert":1,"databases":1,"if":1,"scripts":1}
,"ile":{"connects":1}
,"connects":{"odbc":1}
,"odbc":{"data":1}
,"data":{"source":1,"sources":1,"file":1}
,"source":{"open":1,"specifies":1,"script":1}
,"hidden":{"pen":1,"by":1,"invoices":1}
,"pen":{"ide":1}
,"ide":{"database":1}
,"database":{"add":1,"creation":1,"password":1,"invoices":1,"runs":1,"export":1}
,"add":{"filemaker":1,"odbc":1}
,"filemaker":{"data":1,"pro":1,"file":1}
,"specifies":{"filemaker":1,"odbc":1}
,"atabase":{"open":1}
,"manage":{"data":1}
,"sources":{"allows":1,"editing":1,"diting":1,"filemaker":1,"script":1}
,"allows":{"modify":1,"import":1}
,"modify":{"remove":1}
,"remove":{"external":1}
,"external":{"data":1,"file":1}
,"editing":{"ilemaker":1}
,"diting":{"odbc":1}
,"6.0":{"earlier":1}
,"earlier":{"odbc":1}
,"script":{"step":1,"steps":1,"file":1,"if":1,"moved":1,"invoices":1,"[specified":1}
,"step":{"reestablishes":1,"performs":1,"returns":1,"unable":1}
,"reestablishes":{"link":1}
,"link":{"odbc":1}
,"steps":{"open":1}
,"perform":{"filemaker":1,"script":1}
,"by":{"script":1,"filemaker":1}
,"if":{"file":1,"new":1,"open":1,"contact":1,"external":1}
,"isplays":{"open":1}
,"dialog":{"box":1,"create":1}
,"box":{"open":1,"displayed":1}
,"performs":{"user":1}
,"user":{"file":1}
,"displayed":{"if":1}
,"moved":{"deleted":1}
,"deleted":{"renamed":1}
,"renamed":{"if":1}
,"new":{"database":1}
,"creation":{"disabled":1}
,"disabled":{"installation":1}
,"installation":{"filemaker":1}
,"convert":{"file":1}
,"types":{"excel":1,"filemaker":1}
,"excel":{"tab":1}
,"tab":{"delimited":1}
,"delimited":{"files":1}
,"files":{"filemaker":1,"automating":1}
,"databases":{"import":1}
,"import":{"data":1,"if":1,"invoices":1}
,"password":{"allows":1}
,"contact":{"system":1}
,"system":{"administrator":1}
,"administrator":{"runtime":1}
,"runtime":{"solutions":1}
,"solutions":{"open":1}
,"returns":{"error":1}
,"error":{"if":1}
,"bound":{"solution":1}
,"solution":{"script":1}
,"unable":{"open":1}
,"unauthorized":{"file":1}
,"scripts":{"set":1}
,"set":{"run":1}
,"run":{"run":1,"exports":1}
,"exports":{"records":1}
,"records":{"current":1,"[with":1}
,"current":{"database":1}
,"invoices":{"backup":1,"script":1,"file":1}
,"backup":{"database":1,"\u0022]":1,"parameter":1}
,"runs":{"import":1}
,"export":{"records":1}
,"[with":{"dialog":1}
,"create":{"folders":1}
,"folders":{"off]":1}
,"off]":{"open":1}
,"[open":{"hidden":1}
,"\u0022]":{"perform":1}
,"[specified":{"list":1}
,"list":{"import":1}
,"parameter":{"managing":1}
,"managing":{"files":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
