var pairs =
{
"perform":{"quick":1}
,"quick":{"find":1,"find]":1,"finds":1}
,"find":{"erforms":1,"based":1,"box":1,"script":1,"contents":1,"field":1,"[invoices":1,"text":1,"[get":1,"browse":1}
,"erforms":{"quick":1}
,"based":{"text":1}
,"text":{"text":1,"returned":1,"filemaker":1,"typed":1,"quick":1}
,"returned":{"by":1}
,"by":{"calculation":1,"onobjectsave":1}
,"calculation":{"sp":1,"use":1}
,"sp":{"ecif":1}
,"ecif":{"search":1}
,"search":{"text":1,"based":1}
,"filemaker":{"pro":1}
,"pro":{"11.0":1}
,"11.0":{"script":1}
,"script":{"step":1,"trigger":1}
,"step":{"finds":1,"performs":1}
,"finds":{"records":1,"go":1}
,"records":{"match":1,"[restore":1,"found":1}
,"match":{"search":1,"&get":1}
,"use":{"get":1}
,"get":{"quickfindtext":1}
,"quickfindtext":{"function":1,")]":1}
,"function":{"pass":1}
,"pass":{"text":1}
,"typed":{"quick":1}
,"box":{"perform":1,"if":1,"custom":1}
,"performs":{"quick":1}
,"contents":{"custom":1}
,"custom":{"quick":1,"dialog":1,"menu":1}
,"field":{"sorts":1}
,"sorts":{"found":1}
,"found":{"set":1,"displays":1}
,"set":{"first":1}
,"first":{"record":1}
,"record":{"started":1}
,"started":{"by":1}
,"onobjectsave":{"script":1}
,"trigger":{"perform":1}
,"[invoices":{":custom":1}
,":custom":{"quick":1}
,"find]":{"sort":1}
,"sort":{"records":1}
,"[restore":{"dialog":1}
,"dialog":{"off]":1,"box":1,"[\u0022":1}
,"off]":{"go":1}
,"go":{"record\u002Frequest\u002Fpage":1,"layout":1}
,"record\u002Frequest\u002Fpage":{"[first]":1}
,"[first]":{"invoice":1}
,"invoice":{"details":1}
,"details":{"layout":1,"\u0022]":1}
,"layout":{"performs":1,"[\u0022":1}
,"if":{"records":1,"[get":1,"erforming":1}
,"displays":{"custom":1}
,"menu":{"item":1}
,"item":{"performs":1}
,"[\u0022":{"invoice":1,"records":1}
,"\u0022]":{"perform":1}
,"[get":{"quickfindtext":1,"lasterror":1}
,")]":{"if":1,"end":1}
,"lasterror":{"=401]":1}
,"=401]":{"show":1}
,"show":{"custom":1}
,"&get":{"quickfindtext":1}
,"end":{"if":1}
,"erforming":{"quick":1}
,"browse":{"mode":1}
,"mode":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
