var pairs =
{
"get":{"accountextendedpriv":1,"accountextendedprivileges":1,"currentextendedprivileges":1,"account":1,"extended":1}
,"accountextendedpriv":{"ileges":1}
,"ileges":{"returns":1}
,"returns":{"list":1,"extended":1,"empty":1,"fmwebdirect":1,"fmapp":1}
,"list":{"keywords":1,"if":1}
,"keywords":{"based":1,"separated":1}
,"based":{"account":1,"context":1}
,"account":{"open":1,"by":1,"assume":1,"run":1,"privileges":1,"extended":1}
,"open":{"file":1}
,"file":{"enabled":1,"if":1}
,"enabled":{"extended":1}
,"extended":{"privileges":1,"privilege":1}
,"privileges":{"get":1,"additional":1,"assigned":1,"account":1,"admin":1,"if":1}
,"accountextendedprivileges":{"none":1,"returns":1,"get":1}
,"none":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1,"network":1}
,"pro":{"11.0":1}
,"11.0":{"keywords":1}
,"separated":{"by":1}
,"by":{"carriage":1,"contrast":1}
,"carriage":{"returns":1}
,"additional":{"access":1}
,"access":{"assigned":1,"via":1,"privileges":1}
,"assigned":{"account\u2019s":1,"account":1}
,"account\u2019s":{"privilege":1}
,"privilege":{"set":1,"sets":1,"returns":1,"get":1,"[full":1}
,"set":{"accounts":1,"includes":1,"run":1}
,"accounts":{"privilege":1}
,"sets":{"extended":1}
,"empty":{"list":1}
,"if":{"user":1,"context":1,"logged":1}
,"user":{"doesn\u2019t":1}
,"doesn\u2019t":{"extended":1}
,"context":{"current":1,"evaluated":1}
,"current":{"calculation":1,"window":1}
,"calculation":{"function":1}
,"function":{"evaluated":1,"if":1}
,"evaluated":{"based":1}
,"window":{"get":1}
,"currentextendedprivileges":{"function":1,"returns":1}
,"logged":{"privilege":1,"running":1,"guest":1}
,"includes":{"access":1}
,"via":{"filemaker":1}
,"webdirect":{"extended":1}
,"fmwebdirect":{"if":1,"get":1}
,"running":{"script":1}
,"script":{"full":1,"set":1}
,"full":{"access":1}
,"contrast":{"get":1}
,"admin":{"account":1}
,"assume":{"[read-only":1}
,"[read-only":{"access]":1}
,"access]":{"privilege":1}
,"network":{"extended":1,"access":1}
,"[full":{"access]":1}
,"guest":{"account":1}
,"run":{"script":1,"full":1}
,"fmapp":{"get":1,"fmwebdirect":1}
}
;Search.control.loadWordPairs(pairs);
