var pairs =
{
"king":{"audio":1}
,"audio":{"video":1}
,"video":{"interactive":1,"files":1,"file":1,"codec":1}
,"interactive":{"container":1,"containers":1}
,"container":{"audio":1,"choose":1}
,"files":{"interactive":1,"play":1,"64-bit":1}
,"containers":{"hen":1}
,"hen":{"start":1}
,"start":{"playback":1,"playing":1}
,"playback":{"automatically":1}
,"automatically":{"option":1}
,"option":{"selected":1}
,"selected":{"inspector":1,"start":1}
,"inspector":{"audio":1}
,"file":{"starts":1,"interactive":1}
,"starts":{"playing":1}
,"playing":{"display":1,"ile":1}
,"display":{"record":1}
,"record":{"if":1}
,"if":{"option":1}
,"ile":{"by":1}
,"by":{"clicking":1}
,"clicking":{"play":1}
,"play":{"control":1,"correctly":1,"files":1}
,"control":{"delete":1}
,"delete":{"video":1}
,"choose":{"edit":1}
,"edit":{"menu":1}
,"menu":{"clear":1}
,"clear":{"cut":1}
,"cut":{"indows":1}
,"indows":{"audio":1}
,"correctly":{"32-bit":1,"64-bit":1}
,"32-bit":{"version":1}
,"version":{"filemaker":1,"cases":1}
,"filemaker":{"pro":1,"go":1}
,"pro":{"advanced":1}
,"advanced":{"ay":1,"filemaker":1}
,"ay":{"play":1}
,"64-bit":{"version":1,"versions":1}
,"cases":{"64-bit":1}
,"versions":{"audio":1}
,"codec":{"software":1}
,"software":{"required":1}
,"required":{"play":1}
,"go":{"sound":1}
,"sound":{"movies":1}
,"movies":{"multimedia":1}
,"multimedia":{"pdf":1}
,"pdf":{"music":1}
,"music":{"clips":1,"media":1}
,"clips":{"music":1}
,"media":{"files":1}
}
;Search.control.loadWordPairs(pairs);
