var pairs =
{
"ett":{"ing":1}
,"ing":{"script":1}
,"script":{"triggers":1,"want":1,"trigger":1,"script":1,"dialog":1,"optional":1,"parameter":1}
,"triggers":{"object":1,"set":1,"dialog":1,"made":1}
,"object":{"create":1,"script":1,"objects":1,"if":1,"layout":1}
,"create":{"script":1}
,"want":{"script":1,"run":1,"edit":1}
,"trigger":{"run":1,"10":1,"badge":1,"removing":1,"set":1}
,"run":{"layout":1,"script":1}
,"layout":{"mode":1,"select":1,"script":1,"object":1,"activate":1,"disable":1}
,"mode":{"select":1,"checkboxes":1}
,"select":{"layout":1,"objects":1,"modes":1,"multiple":1}
,"objects":{"choose":1,"appears":1,"set":1,"settings":1}
,"choose":{"format":1,"script":1,"view":1}
,"format":{"menu":1}
,"menu":{"set":1,"show":1}
,"set":{"script":1,"objects":1}
,"dialog":{"box":1}
,"box":{"double-click":1,"choose":1,"build":1,"set":1,"select":1,"displays":1}
,"double-click":{"event":1}
,"event":{"want":1}
,"optional":{"script":1}
,"parameter":{"type":1,"close":1}
,"type":{"text":1}
,"text":{"want":1}
,"edit":{"use":1}
,"use":{"calculation":1}
,"calculation":{"dialog":1}
,"build":{"complex":1}
,"complex":{"parameter":1}
,"close":{"script":1}
,"modes":{"script":1}
,"10":{"badge":1}
,"badge":{"layout":1,"objects":1,"appears":1,"choose":1}
,"appears":{"object":1,"depends":1}
,"depends":{"size":1}
,"size":{"object":1}
,"if":{"don\u2019t":1,"select":1}
,"don\u2019t":{"badge":1}
,"view":{"menu":1}
,"show":{"script":1}
,"made":{"object":1}
,"activate":{"script":1}
,"disable":{"script":1}
,"removing":{"clear":1}
,"clear":{"mode":1}
,"checkboxes":{"if":1}
,"multiple":{"objects":1}
,"settings":{"script":1}
,"displays":{"minus":1}
,"minus":{"sign":1}
,"sign":{"-\u0022":1}
,"-\u0022":{"trigger":1}
}
;Search.control.loadWordPairs(pairs);
