var pairs =
{
"beep":{"lays":1,"sound":1,"show":1}
,"lays":{"system":1}
,"system":{"beep":1}
,"sound":{"none":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"performs":1}
,"performs":{"find":1}
,"find":{"if":1,"[restore]":1}
,"if":{"records":1,"[get":1,"automating":1}
,"records":{"found":1}
,"found":{"beeps":1,"\u0022]":1}
,"beeps":{"set":1}
,"set":{"error":1}
,"error":{"capture":1}
,"capture":{"[on]":1}
,"[on]":{"perform":1}
,"perform":{"find":1}
,"[restore]":{"if":1}
,"[get":{"foundcount":1}
,"foundcount":{"=0]":1}
,"=0]":{"beep":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"dialog":{"[\u0022":1}
,"[\u0022":{"records":1}
,"\u0022]":{"end":1}
,"end":{"if":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
