var pairs =
{
"adding":{"changing":1,"text":1,"field":1}
,"changing":{"field":1,"fields":1,"deleting":1,"placeholder":1}
,"field":{"labels":1,"layout":1,"label":1,"field":1,"name":1,"placeholder":1,"tab":1,"that\u2019s":1,"dialog":1,"browse":1,"add":1,"\u2019s":1,"empty":1,"pencil":1,"rename":1,"cases":1}
,"labels":{"place":1,"various":1,"choose":1,"change":1,"layout":1,"labels":1,"placeholder":1}
,"place":{"field":1,"fields":1}
,"layout":{"include":1,"designed":1,"mode":1,"ield":1,"double-click":1,"nd":1,"select":1,"change":1,"positioning":1,"placeholder":1,"field":1,"add":1,"inspector":1}
,"include":{"field":1}
,"label":{"identify":1,"field":1,"format":1,"wh":1,"fo":1,"type":1,"adding":1,"labels":1,"select":1,"use":1,"press":1,"layout":1,"hen":1,"match":1,"appears":1,"place":1,"changing":1}
,"identify":{"field":1}
,"name":{"text":1,"label":1,"field":1,"each":1}
,"text":{"instructions":1,"field":1,"space":1,"tool":1,"label":1,"layout":1,"delete":1,"displays":1,"container":1,"place":1,"button":1,"display":1,"find":1,"select":1,"press":1,"doesn\u2019t":1,"print":1,"placeholder":1}
,"instructions":{"result":1}
,"result":{"calculation":1}
,"calculation":{"field":1,"display":1}
,"various":{"positions":1}
,"positions":{"field":1}
,"placeholder":{"text":1,"find":1}
,"space":{"limited":1}
,"limited":{"layout":1}
,"designed":{"touch":1}
,"touch":{"devices":1}
,"devices":{"field":1}
,"format":{"styles":1}
,"styles":{"formatting":1}
,"formatting":{"bar":1,"text":1}
,"bar":{"layout":1,"inspector":1}
,"mode":{"add":1,"optionally":1,"typing":1,"select":1,"placeholder":1,"doesn\u2019t":1,"identifies":1}
,"add":{"field":1,"placeholder":1,"change":1,"ed":1}
,"wh":{"en":1}
,"en":{"place":1}
,"ield":{"tab":1}
,"tab":{"drag":1,"labels":1,"use":1,"inspector":1}
,"drag":{"preferences":1}
,"preferences":{"rea":1}
,"rea":{"fields":1,"field":1}
,"fields":{"tab":1,"field":1,"layou":1,"fields":1,"formatted":1,"by":1,"placeholder":1,"adding":1}
,"choose":{"option":1,"view":1}
,"option":{"defining":1}
,"defining":{"changing":1}
,"use":{"field":1,"formatting":1,"tools":1}
,"that\u2019s":{"layout":1,"ayout":1}
,"double-click":{"field":1}
,"nd":{"create":1}
,"create":{"label":1}
,"dialog":{"box":1}
,"box":{"ee":1}
,"ee":{"placing":1}
,"placing":{"removing":1}
,"removing":{"fields":1}
,"layou":{"type":1}
,"type":{"label":1,"text":1,"new":1}
,"fo":{"field":1}
,"ayout":{"text":1}
,"tool":{"text":1,"status":1,"choose":1}
,"status":{"toolbar":1}
,"toolbar":{"want":1,"lick":1}
,"want":{"label":1}
,"select":{"label":1,"text":1,"field":1,"show":1}
,"change":{"edit":1,"style":1,"placeholder":1}
,"edit":{"field":1,"boxes":1}
,"new":{"label":1,"field":1}
,"style":{"appearance":1}
,"appearance":{"field":1}
,"inspector":{"formatting":1,"pane":1,"field":1,"apply":1}
,"delete":{"field":1,"use":1,"placeholder":1,"press":1}
,"press":{"backspace":1,"enter":1}
,"backspace":{"delete":1}
,"tools":{"position":1}
,"position":{"labels":1}
,"positioning":{"objects":1}
,"objects":{"layout":1}
,"displays":{"field":1}
,"browse":{"mode":1}
,"optionally":{"find":1}
,"find":{"mode":1}
,"typing":{"field":1}
,"container":{"fields":1}
,"formatted":{"edit":1}
,"boxes":{"drop-down":1}
,"drop-down":{"lists":1,"calendars":1}
,"lists":{"drop-down":1}
,"calendars":{"pop-up":1}
,"pop-up":{"menus":1}
,"menus":{"layout":1}
,"button":{"defining":1,"status":1,"pecify":1}
,"by":{"default":1}
,"default":{"placeholder":1}
,"\u2019s":{"layout":1}
,"pane":{"button":1}
,"lick":{"data":1}
,"data":{"data":1,"tab":1}
,"empty":{"display":1}
,"display":{"result":1,"placeholder":1,"table":1,"badge":1}
,"pencil":{"button":1}
,"pecify":{"calculation":1}
,"show":{"placeholder":1}
,"ed":{"placeholder":1}
,"enter":{"tab":1}
,"apply":{"if":1}
,"if":{"include":1}
,"hen":{"place":1}
,"rename":{"field":1}
,"cases":{"field":1}
,"match":{"new":1}
,"each":{"layout":1}
,"appears":{"placeholder":1}
,"table":{"view":1}
,"view":{"viewing":1,"menu":1}
,"viewing":{"records":1}
,"records":{"preview":1,"pdf":1}
,"preview":{"mode":1}
,"doesn\u2019t":{"print":1}
,"print":{"preview":1,"save":1,"print":1}
,"save":{"records":1,"blank":1}
,"pdf":{"file":1,"fil":1}
,"file":{"placeholder":1,"printing":1}
,"blank":{"records":1}
,"printing":{"record":1}
,"record":{"saving":1}
,"saving":{"sending":1}
,"sending":{"records":1}
,"fil":{"display":1}
,"badge":{"layout":1}
,"identifies":{"fields":1}
,"menu":{"show":1}
,"deleting":{"field":1}
}
;Search.control.loadWordPairs(pairs);
