var pairs =
{
"relookup":{"field":1,"operation":1}
,"field":{"contents":1,"current":1,"go":1,"specifies":1,"target":1,"match":1,"relationship":1,"lookup":1,"if":1,"selected":1,"relookup":1,"relookups":1,"matching":1,"parameter":1,"updates":1}
,"contents":{"opies":1,"returns":1,"step":1,"command":1,"use":1,"script":1,"[with":1}
,"opies":{"new":1}
,"new":{"values":1}
,"values":{"lookup":1,"customer":1}
,"lookup":{"source":1,"based":1,"target":1,"relook":1}
,"source":{"field":1}
,"current":{"found":1}
,"found":{"set":1}
,"set":{"dialog":1,"records":1,"finds":1,"based":1}
,"dialog":{"specifies":1,"box":1,"option":1,"invoices":1}
,"specifies":{"display":1,"field":1}
,"display":{"dialog":1}
,"box":{"script":1}
,"script":{"step":1}
,"step":{"performed":1,"editable":1,"data":1,"if":1}
,"performed":{"allowing":1,"found":1,"get":1}
,"allowing":{"users":1}
,"users":{"confirm":1}
,"confirm":{"field":1}
,"go":{"target":1,"layout":1}
,"target":{"field":1,"relookup":1}
,"operation":{"filemaker":1,"performed":1}
,"filemaker":{"pro":1,"data":1}
,"pro":{"advanced":1,"6.0":1}
,"advanced":{"moves":1}
,"moves":{"cursor":1}
,"cursor":{"field":1}
,"match":{"field":1}
,"relationship":{"lookup":1,"customer":1}
,"based":{"lookup":1,"relationship":1}
,"if":{"field":1,"use":1,"dialog":1}
,"selected":{"relookup":1}
,"returns":{"error":1}
,"error":{"code":1}
,"code":{"captured":1}
,"captured":{"get":1}
,"get":{"lasterror":1,"unexpected":1}
,"lasterror":{"function":1}
,"function":{"filemaker":1}
,"6.0":{"earlier":1}
,"earlier":{"target":1}
,"editable":{"field":1}
,"relookups":{"performed":1}
,"records":{"active":1,"server-side":1,"matching":1,"[replace":1}
,"active":{"table":1}
,"table":{"calculation":1}
,"calculation":{"fields":1,"field":1}
,"fields":{"relookup":1,"calculation":1}
,"command":{"if":1,"calculation":1}
,"use":{"relookup":1}
,"matching":{"value":1,"values":1,"records":1}
,"value":{"input":1}
,"input":{"fields":1}
,"parameter":{"relookup":1}
,"data":{"committed":1,"records":1,"api":1}
,"committed":{"first":1}
,"first":{"operation":1}
,"unexpected":{"committing":1}
,"committing":{"data":1}
,"server-side":{"scripts":1}
,"scripts":{"filemaker":1}
,"api":{"nd":1}
,"nd":{"custom":1}
,"custom":{"web":1}
,"web":{"publishing":1}
,"publishing":{"run":1}
,"run":{"script":1}
,"option":{"set":1}
,"finds":{"records":1}
,"customer":{"id":1}
,"id":{"field":1,"match":1}
,"updates":{"all":1}
,"all":{"lookups":1}
,"lookups":{"found":1,"automating":1}
,"layout":{"[\u0022":1}
,"[\u0022":{"nvoice":1}
,"nvoice":{"details":1}
,"details":{"\u0022]":1}
,"\u0022]":{"find":1}
,"find":{"matching":1}
,"[replace":{"invoices":1}
,"invoices":{":customer":1}
,":customer":{"id]":1}
,"id]":{"relookup":1,"re":1}
,"[with":{"dialog":1}
,"re":{"lookup":1}
,"relook":{"up":1}
,"up":{"efining":1}
,"efining":{"updating":1}
,"updating":{"lookups":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
