var pairs =
{
"previewing":{"printing":1}
,"printing":{"yo":1,"controlling":1}
,"yo":{"print":1}
,"print":{"all":1,"data":1,"records":1,"printer":1,"setup":1}
,"all":{"records":1}
,"records":{"database":1,"current":1,"by":1}
,"database":{"subset":1,"filemaker":1}
,"subset":{"records":1}
,"current":{"record":1,"layout":1}
,"record":{"blank":1,"create":1}
,"blank":{"record":1,"space":1}
,"create":{"paper":1,"layouts":1}
,"paper":{"form":1}
,"form":{"definitions":1}
,"definitions":{"scripts":1}
,"scripts":{"tables":1}
,"tables":{"fields":1}
,"fields":{"relationships":1}
,"relationships":{"structure":1}
,"structure":{"database":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"prints":1}
,"prints":{"records":1}
,"layout":{"create":1,"mode":1,"control":1}
,"layouts":{"print":1,"mailing":1,"reports":1}
,"data":{"print":1}
,"by":{"columnar":1}
,"columnar":{"list":1}
,"list":{"complex":1}
,"complex":{"sorted":1}
,"sorted":{"report":1}
,"report":{"totals":1}
,"totals":{"headers":1}
,"headers":{"footers":1}
,"footers":{"create":1}
,"mailing":{"labels":1}
,"labels":{"envelopes":1}
,"envelopes":{"new":1}
,"new":{"layout\u002Freport":1}
,"layout\u002Freport":{"assistant":1}
,"assistant":{"layout":1}
,"mode":{"easy":1}
,"easy":{"create":1}
,"reports":{"se":1}
,"se":{"creating":1}
,"creating":{"layout":1}
,"control":{"page":1}
,"page":{"margins":1}
,"margins":{"remove":1}
,"remove":{"blank":1}
,"space":{"keep":1}
,"keep":{"objects":1}
,"objects":{"printing":1}
,"controlling":{"layouts":1}
,"printer":{"print":1,"system":1}
,"setup":{"options":1}
,"options":{"depend":1}
,"depend":{"printer":1}
,"system":{"software":1,"documentation":1}
,"software":{"you\u2019re":1}
,"you\u2019re":{"refer":1}
,"refer":{"printer":1}
}
;Search.control.loadWordPairs(pairs);
