var pairs =
{
"get":{"regionmonitorevents":1}
,"regionmonitorevents":{"returns":1,"none":1,"function":1,")]":1}
,"returns":{"events":1,"name":1,"foreground":1}
,"events":{"caused":1,"each":1}
,"caused":{"script":1}
,"script":{"configure":1,"script":1,"step":1,"dialog":1}
,"configure":{"region":1}
,"region":{"monitor":1,"timestamp":1,"returns":1,"name":1,"while":1,"ibeacons":1,"show":1,"10:45":1}
,"monitor":{"script":1,"timestamp":1,"displayed":1,"region":1,"beaconmonitor":1}
,"step":{"run":1,"monitor":1}
,"run":{"get":1,"function":1}
,"none":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1,"go":1}
,"pro":{"16.0":1}
,"16.0":{"if":1}
,"if":{"event":1,"ios":1,"user":1}
,"event":{"script":1,"format":1}
,"function":{"returns":1,"return":1}
,"name":{"region":1,"timestamp":1,"monitor":1}
,"timestamp":{"ios":1,"formatted":1,"timestamp":1,"if":1}
,"ios":{"device":1,"notifications":1,"devices":1}
,"device":{"entered":1,"detected":1}
,"entered":{"exited":1,"monitored":1,"region":1}
,"exited":{"monitored":1,"hours":1}
,"monitored":{"region":1}
,"formatted":{"based":1}
,"based":{"settings":1}
,"settings":{"solution":1,"dialog":1}
,"solution":{"locale":1,"created":1,"configure":1}
,"locale":{"solution":1,"if":1,"filemaker":1}
,"created":{"system":1,"german":1}
,"system":{"locale":1,"settings":1}
,"each":{"monitor":1}
,"displayed":{"chronological":1}
,"chronological":{"order":1}
,"order":{"starting":1}
,"starting":{"earliest":1}
,"earliest":{"event":1}
,"format":{"region":1}
,"user":{"entered":1}
,"while":{"filemaker":1}
,"go":{"suspended":1,"returns":1,"system":1}
,"suspended":{"ios":1}
,"notifications":{"delivered":1}
,"delivered":{"filemaker":1}
,"foreground":{"get":1}
,"return":{"multiple":1}
,"multiple":{"values":1}
,"values":{"solution":1}
,"ibeacons":{"name":1}
,"beaconmonitor":{"script":1,"27\u002F1\u002F2019":1}
,"dialog":{"box":1,"[\u0022":1}
,"box":{"display":1,"displays":1}
,"display":{"ios":1}
,"devices":{"entering":1}
,"entering":{"exiting":1}
,"exiting":{"monitored":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"[\u0022":{"new":1}
,"new":{"ios":1}
,"detected":{"get":1}
,")]":{"solution":1}
,"german":{"locale":1}
,"displays":{"if":1}
,"10:45":{"january":1,";1":1}
,"january":{"27":1}
,"27":{"2019":1}
,"2019":{"exited":1}
,"hours":{"beaconmonitor":1}
,"27\u002F1\u002F2019":{"10:45":1,"1:26":1}
,";1":{"27\u002F1\u002F2019":1}
,"1:26":{"pm":1}
,"pm":{";0":1}
}
;Search.control.loadWordPairs(pairs);
