var pairs =
{
"get":{"syste":1,"systemplatform":1,"system":1,"operating":1}
,"syste":{"mp":1}
,"mp":{"latform":1}
,"latform":{"returns":1}
,"returns":{"number":1,"if":1,"-2":1,"current":1}
,"number":{"representing":1,"filemaker":1}
,"representing":{"current":1}
,"current":{"platform":1}
,"platform":{"get":1,"intel-based":1,"windows":1,"ios":1,"filemaker":1,"linux":1,"abs":1,"macos":1}
,"systemplatform":{"none":1,"returns":1,"get":1}
,"none":{"number":1}
,"filemaker":{"pro":1,"webdirect":1,"go":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"returns":1}
,"if":{"current":1,"platform":1}
,"intel-based":{"macs":1}
,"macs":{"-2":1}
,"-2":{"if":1,"current":1}
,"windows":{"if":1,"platform":1}
,"ios":{"if":1}
,"webdirect":{"if":1}
,"linux":{"get":1}
,"abs":{"get":1}
,"macos":{"get":1}
,"system":{"platform":1,"filemaker":1}
,"operating":{"system":1}
}
;Search.control.loadWordPairs(pairs);
