var pairs =
{
"one-to-one":{"relationships":1,"relationship":1}
,"relationships":{"one-to-one":1,"graph":1}
,"relationship":{"record":1,"relationships":1,"line":1,"returns":1}
,"record":{"table":1}
,"table":{"associated":1,"school":1,"contact":1,"one-to-one":1,"student":1,"records":1}
,"associated":{"record":1}
,"school":{"database":1}
,"database":{"each":1}
,"each":{"student":1,"table":1}
,"student":{"student":1,"id":1}
,"id":{"each":1,"assigned":1,"designed":1,"field":1}
,"assigned":{"person":1}
,"person":{"one-to-one":1}
,"graph":{"students":1}
,"students":{"table":1,"contact":1}
,"contact":{"info":1}
,"info":{"table":1,"tables":1}
,"line":{"key":1}
,"key":{"field":1,"contact":1,"relationship":1}
,"field":{"each":1,"primary":1,"foreign":1,"contact":1,"students":1}
,"designed":{"contain":1}
,"contain":{"unique":1}
,"unique":{"values":1}
,"values":{"students":1}
,"primary":{"key":1}
,"foreign":{"key":1}
,"returns":{"related":1}
,"related":{"records":1}
,"records":{"value":1,"students":1}
,"value":{"student":1}
,"tables":{"result":1}
,"result":{"one-to-one":1}
}
;Search.control.loadWordPairs(pairs);
