var pairs =
{
"elf":{"returns":1}
,"returns":{"content":1,"true":1}
,"content":{"object":1}
,"object":{"calculation":1,"associated":1,"self":1,"inspector":1,"value":1}
,"calculation":{"defined":1,"reference":1,"formula":1,"display":1}
,"defined":{"self":1}
,"self":{"none":1,"function":1,"create":1,"10":1,"value":1}
,"none":{"text":1}
,"text":{"number":1,"hide":1,"formatting":1,"value":1}
,"number":{"date":1,"entered":1}
,"date":{"time":1}
,"time":{"timestamp":1}
,"timestamp":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"9.0":1}
,"9.0":{"self":1}
,"function":{"calculation":1,"conditional":1}
,"reference":{"content":1,"object":1}
,"associated":{"explicitly":1}
,"explicitly":{"reference":1}
,"create":{"single":1}
,"single":{"calculation":1}
,"formula":{"applied":1,"object\u2019s":1}
,"applied":{"objects":1,"layout":1}
,"objects":{"self":1}
,"conditional":{"formatting":1}
,"formatting":{"tooltips":1,"panel":1,"number":1}
,"tooltips":{"placeholder":1}
,"placeholder":{"text":1}
,"hide":{"object":1}
,"inspector":{"option":1,"options":1}
,"option":{"title":1}
,"title":{"help":1}
,"help":{"accessibility":1}
,"accessibility":{"inspector":1}
,"options":{"nd":1}
,"nd":{"field":1}
,"field":{"definition":1,"greater":1,"object":1}
,"definition":{"calculations":1}
,"calculations":{"including":1,"formula":1}
,"including":{"auto-enter":1}
,"auto-enter":{"validation":1}
,"validation":{"calculations":1}
,"object\u2019s":{"conditional":1,"tooltip":1}
,"panel":{"set":1}
,"set":{"text":1}
,"entered":{"field":1,"if":1}
,"greater":{"10":1}
,"10":{"self":1,"returns":1,"use":1}
,"true":{"applied":1}
,"layout":{"field":1,"object\u2019s":1}
,"value":{"greater":1,"less":1,"zero":1}
,"use":{"layout":1}
,"tooltip":{"calculation":1,"text":1}
,"display":{"tooltip":1}
,"less":{"zero":1}
,"zero":{"entered":1,"value":1,"greater":1}
,"if":{"self":1}
}
;Search.control.loadWordPairs(pairs);
