var pairs =
{
"base":{"iii":1,"select":1}
,"iii":{"iv":1,"dbase":1}
,"iv":{"dbf":1,"compatible":1}
,"dbf":{"format":1,"files":1,"file":1,"criteria":1}
,"format":{"import":1,"importing":1}
,"import":{"convert":1,"application":1}
,"convert":{"export":1,"dbf":1}
,"export":{"dbase":1,"dbf":1,"format":1}
,"dbase":{"iii":1,"iv":1,"memo":1}
,"compatible":{"dbf":1}
,"files":{"filemaker":1,"exporting":1}
,"filemaker":{"pro":1,"knowledge":1}
,"pro":{"advanced":1}
,"advanced":{"field":1,"mports":1,"import":1}
,"field":{"names":1,"types":1,"data":1,"name":1,"maximum":1,"exported":1}
,"names":{"dbf":1,"maximum":1}
,"file":{"text":1,"filemaker":1,"filename":1}
,"text":{"number":1}
,"number":{"date":1}
,"date":{"time":1}
,"time":{"field":1}
,"types":{"convert":1}
,"mports":{"dbase":1}
,"memo":{"field":1,"file":1}
,"data":{"if":1,"search":1,"formatting":1,"export":1}
,"if":{"memo":1}
,"filename":{".dbt":1,".dbf":1}
,".dbt":{"folder":1}
,"folder":{"dbf":1}
,".dbf":{"export":1}
,"application":{"database":1}
,"database":{"meet":1}
,"meet":{"dbf":1}
,"criteria":{"characters":1}
,"characters":{"field":1}
,"name":{"spaces":1}
,"spaces":{"converted":1}
,"converted":{"underscores":1,"all":1}
,"underscores":{"letters":1}
,"letters":{"converted":1}
,"all":{"uppercase":1}
,"uppercase":{"duplicate":1}
,"duplicate":{"field":1}
,"maximum":{"128":1,"254":1,"4000":1}
,"128":{"fields":1}
,"fields":{"maximum":1}
,"254":{"characters":1}
,"4000":{"bytes":1}
,"bytes":{"record":1}
,"record":{"first":1}
,"first":{"value":1}
,"value":{"repeating":1}
,"repeating":{"field":1}
,"exported":{"exporting":1,"data":1}
,"exporting":{"repeating":1,"dbf":1}
,"search":{"filemaker":1}
,"knowledge":{"base":1}
,"select":{"apply":1}
,"apply":{"current":1}
,"current":{"layout\u2019s":1}
,"layout\u2019s":{"data":1}
,"formatting":{"exported":1}
,"importing":{"co":1}
,"co":{"nverting":1}
,"nverting":{"dbf":1}
}
;Search.control.loadWordPairs(pairs);
