var pairs =
{
"page":{"margins":1,"setup":1,"right":1,"select":1}
,"margins":{"margins":1,"each":1,"filemaker":1,"vary":1,"if":1,"type":1,"alternate":1,"switch":1,"dotted":1,"layout":1,"page":1,"display":1,"columns":1,"setting":1}
,"each":{"layout":1}
,"layout":{"if":1,"exact":1,"mode":1,"setup":1,"bar":1,"change":1,"navigation":1}
,"if":{"margins":1,"printing":1,"want":1,"layout":1,"you\u2019re":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"printer\u0027s":1}
,"printer\u0027s":{"default":1}
,"default":{"margins":1}
,"vary":{"printers":1}
,"printers":{"printer":1}
,"printer":{"drivers":1,"paper":1,"layout":1}
,"drivers":{"page":1}
,"printing":{"layout":1,"tab":1}
,"exact":{"spacing":1}
,"spacing":{"labels":1}
,"labels":{"preprinted":1}
,"preprinted":{"form":1}
,"form":{"choose":1}
,"choose":{"file":1,"unit":1,"view":1}
,"file":{"menu":1}
,"menu":{"print":1,"page":1,"sing":1}
,"print":{"setup":1,"choose":1,"columns":1,"records":1}
,"setup":{"windows":1,"macos":1,"layout":1,"button":1}
,"windows":{"file":1,"page":1}
,"macos":{"confirm":1,"status":1}
,"confirm":{"printer":1}
,"paper":{"settings":1}
,"settings":{"preview":1}
,"preview":{"mode":1}
,"mode":{"print":1,"layout":1,"margins":1,"right-click":1,"if":1}
,"status":{"toolbar":1}
,"toolbar":{"se":1}
,"se":{"documentation":1,"previewing":1}
,"documentation":{"computer":1}
,"computer":{"printer":1}
,"button":{"layout":1}
,"bar":{"cl":1}
,"cl":{"ick":1}
,"ick":{"printing":1}
,"tab":{"select":1}
,"select":{"use":1,"facing":1}
,"use":{"fi":1}
,"fi":{"xed":1}
,"xed":{"page":1}
,"type":{"values":1}
,"values":{"margins":1}
,"want":{"left":1}
,"left":{"right":1,"first":1}
,"right":{"margins":1,"second":1}
,"alternate":{"inside":1}
,"inside":{"margin":1}
,"margin":{"appears":1}
,"appears":{"left":1}
,"first":{"page":1}
,"second":{"page":1}
,"facing":{"pa":1}
,"pa":{"ges":1}
,"ges":{"check":1}
,"check":{"margins":1}
,"switch":{"preview":1}
,"dotted":{"line":1}
,"line":{"se":1}
,"previewing":{"data":1}
,"data":{"layout":1}
,"change":{"unit":1}
,"unit":{"measure":1}
,"measure":{"margins":1,"shortcut":1}
,"right-click":{"ruler":1}
,"ruler":{"choose":1}
,"shortcut":{"menu":1}
,"sing":{"rulers":1}
,"rulers":{"grid":1}
,"grid":{"show":1}
,"show":{"page":1}
,"view":{"menu":1}
,"display":{"layout":1}
,"navigation":{"parts":1}
,"parts":{"if":1}
,"you\u2019re":{"print":1}
,"columns":{"option":1,"resize":1,"page":1}
,"option":{"page":1}
,"resize":{"fit":1}
,"fit":{"new":1}
,"new":{"margins":1}
,"setting":{"up":1}
,"up":{"print":1}
,"records":{"columns":1}
}
;Search.control.loadWordPairs(pairs);
