var pairs =
{
"ntering":{"data":1}
,"data":{"records":1,"fields":1,"value":1,"opying":1,"container":1,"se":1,"filemaker":1,"database":1}
,"records":{"browse":1,"yo":1,"insert":1}
,"browse":{"mode":1}
,"mode":{"add":1}
,"add":{"database":1}
,"database":{"file":1}
,"file":{"by":1,"related":1}
,"by":{"entering":1}
,"entering":{"data":1,"changing":1,"preset":1}
,"yo":{"type":1}
,"type":{"fields":1}
,"fields":{"entering":1,"enter":1,"data":1,"mport":1}
,"changing":{"data":1}
,"enter":{"preset":1}
,"preset":{"data":1}
,"value":{"list":1}
,"list":{"entering":1,"copy":1}
,"copy":{"paste":1,"display":1}
,"paste":{"data":1,"images":1}
,"opying":{"moving":1}
,"moving":{"data":1}
,"insert":{"current":1,"files":1}
,"current":{"date":1}
,"date":{"field":1,"variables":1}
,"field":{"inserting":1,"copy":1}
,"inserting":{"current":1}
,"variables":{"field":1}
,"images":{"videos":1}
,"videos":{"insert":1}
,"files":{"word":1,"pdf":1,"container":1}
,"word":{"processing":1}
,"processing":{"files":1}
,"pdf":{"files":1}
,"container":{"fields":1}
,"mport":{"data":1}
,"se":{"importing":1}
,"importing":{"data":1}
,"filemaker":{"pr":1}
,"pr":{"advanced":1}
,"advanced":{"use":1}
,"use":{"lookups":1}
,"lookups":{"relationships":1}
,"relationships":{"copy":1}
,"display":{"data":1}
,"related":{"tables":1}
,"tables":{"audio":1}
,"audio":{"music":1}
,"music":{"songs":1}
,"songs":{"clips":1}
}
;Search.control.loadWordPairs(pairs);
