var pairs =
{
"sortvalues":{"sorts":1,"values":1,"34":1,"product":1}
,"sorts":{"list":1,"ascending":1,"descending":1,"values":1,"based":1}
,"list":{"values":1}
,"values":{"based":1,"datatype":1,"-any":1,"separated":1,"valuecount":1,"function":1,"appropriately":1,"sorted":1,"text":1}
,"based":{"data":1,"locale":1}
,"data":{"type":1,"sorted":1}
,"type":{"locale":1,"data":1}
,"locale":{"sortvalues":1,"values":1,"-the":1,"sorting":1,"parameter":1,"manner":1,"file":1,"english":1}
,"datatype":{"locale":1,"-a":1,"parameter":1,"sorts":1}
,"-any":{"text":1}
,"text":{"expression":1,"filemaker":1,"ascending":1,"number":1}
,"expression":{"field":1}
,"field":{"that\u2019s":1,"red":1}
,"that\u2019s":{"list":1}
,"separated":{"by":1}
,"by":{"carriage":1,"locale":1}
,"carriage":{"returns":1,"return":1}
,"returns":{"datatype":1,"sortvalues":1,"values":1}
,"-a":{"number":1}
,"number":{"specifies":1,"date":1}
,"specifies":{"type":1}
,"sorted":{"positive":1,"text":1,"default":1}
,"positive":{"value":1}
,"value":{"sorts":1,"carriage":1,"unrecognized":1,"values":1,"function":1}
,"ascending":{"order":1,"alphabetical":1}
,"order":{"negative":1,"locale":1,"datatype":1,"determined":1,"text":1,"file":1}
,"negative":{"value":1}
,"descending":{"order":1}
,"-the":{"name":1}
,"name":{"locale":1}
,"sorting":{"rules":1,"records":1,"blank":1}
,"rules":{"parameters":1,"sort":1}
,"parameters":{"braces":1}
,"braces":{"optional":1}
,"optional":{"text":1}
,"filemaker":{"pro":1}
,"pro":{"16.0":1}
,"16.0":{"description":1}
,"description":{"list":1}
,"valuecount":{"function":1}
,"function":{"each":1,"sort":1,"return":1,"supported":1}
,"each":{"returned":1}
,"returned":{"value":1}
,"return":{"allowing":1,"supported":1,"00":1}
,"allowing":{"lists":1}
,"lists":{"easily":1}
,"easily":{"concatenated":1}
,"concatenated":{"datatype":1}
,"parameter":{"use":1,"arabic":1}
,"use":{"values":1,"value":1,"names":1}
,"sort":{"values":1,"order":1}
,"appropriately":{"if":1}
,"if":{"use":1}
,"unrecognized":{"value":1}
,"date":{"time":1}
,"time":{"timestamp":1}
,"timestamp":{"locale":1}
,"names":{"locale\u2019s":1,"locale":1}
,"locale\u2019s":{"sorting":1}
,"determined":{"by":1}
,"manner":{"sorting":1}
,"records":{"hoosing":1}
,"hoosing":{"language":1}
,"language":{"indexing":1}
,"indexing":{"sorting":1}
,"blank":{"value":1}
,"file":{"calculation\u2019s":1,"locale":1}
,"calculation\u2019s":{"relationship":1}
,"relationship":{"graph":1}
,"graph":{"unrecognized":1}
,"supported":{"names":1,"runtime":1}
,"arabic":{"english":1}
,"english":{"hindi":1,"blue":1}
,"hindi":{"norwegian":1}
,"norwegian":{"spanish_traditional":1}
,"spanish_traditional":{"bengali":1}
,"bengali":{"estonian":1}
,"estonian":{"hungarian":1}
,"hungarian":{"panjabi":1}
,"panjabi":{"swedish":1}
,"swedish":{"bulgarian":1}
,"bulgarian":{"finnish":1}
,"finnish":{"icelandic":1}
,"icelandic":{"persian":1}
,"persian":{"swedish_custom":1}
,"swedish_custom":{"catalan":1}
,"catalan":{"finnish_custom":1}
,"finnish_custom":{"italian":1}
,"italian":{"polish":1}
,"polish":{"tamil":1}
,"tamil":{"catalog":1}
,"catalog":{"french":1}
,"french":{"japanese":1}
,"japanese":{"portuguese":1}
,"portuguese":{"telugu":1}
,"telugu":{"chinese":1}
,"chinese":{"german":1}
,"german":{"kannada":1}
,"kannada":{"romanian":1}
,"romanian":{"thai":1}
,"thai":{"chinese_stroke":1}
,"chinese_stroke":{"german_dictionary":1}
,"german_dictionary":{"korean":1}
,"korean":{"russian":1}
,"russian":{"turkish":1}
,"turkish":{"croatian":1}
,"croatian":{"greek":1}
,"greek":{"latvian":1}
,"latvian":{"serbian":1}
,"serbian":{"ukrainian":1}
,"ukrainian":{"czech":1}
,"czech":{"greek_mixed":1}
,"greek_mixed":{"lithuanian":1}
,"lithuanian":{"slovak":1}
,"slovak":{"unicode_raw":1}
,"unicode_raw":{"danish":1}
,"danish":{"gujarati":1}
,"gujarati":{"malayalam":1}
,"malayalam":{"slovenian":1}
,"slovenian":{"unicode_standard":1}
,"unicode_standard":{"dutch":1}
,"dutch":{"hebrew":1}
,"hebrew":{"marathi":1}
,"marathi":{"spanish":1}
,"spanish":{"vietnamese":1}
,"vietnamese":{"function":1}
,"runtime":{"solutions":1}
,"solutions":{"returns":1}
,"34":{"600":1,"29":1}
,"600":{"18":1}
,"18":{"29":1,"sortvalues":1}
,"29":{"-2":1,"18":1}
,"-2":{"return":1}
,"00":{"34":1}
,"product":{":colors":1}
,":colors":{"returns":1,"field":1}
,"default":{"order":1}
,"alphabetical":{"order":1}
,"blue":{"green":1}
,"green":{"green":1,"red":1,"blue":1,"yellow":1}
,"red":{"yellow":1,"green":1}
,"yellow":{"product":1}
}
;Search.control.loadWordPairs(pairs);
