var pairs =
{
"erforming":{"menu":1}
,"menu":{"command":1,"commands":1,"bar":1,"choices":1}
,"command":{"access":1}
,"access":{"menu":1,"privileges":1}
,"commands":{"by":1}
,"by":{"choosing":1}
,"choosing":{"menu":1}
,"bar":{"pressing":1,"selecting":1}
,"pressing":{"keyboard":1}
,"keyboard":{"shortcut":1}
,"shortcut":{"clicking":1,"menus":1}
,"clicking":{"buttons":1}
,"buttons":{"status":1}
,"status":{"toolbar":1}
,"toolbar":{"formatting":1}
,"formatting":{"bar":1}
,"selecting":{"shortcut":1}
,"menus":{"activating":1}
,"activating":{"apple":1}
,"apple":{"events":1}
,"events":{"macos":1}
,"macos":{"nly":1}
,"nly":{"menu":1}
,"choices":{"dimmed":1}
,"dimmed":{"if":1}
,"if":{"access":1}
,"privileges":{"file":1}
,"file":{"limited":1}
,"limited":{"protecting":1}
,"protecting":{"databases":1}
}
;Search.control.loadWordPairs(pairs);
