var pairs =
{
"bout":{"disconnecting":1}
,"disconnecting":{"users":1}
,"users":{"filemaker":1,"file":1,"disconnected":1,"maintain":1,"idle":1,"frequent":1,"open":1,"full":1}
,"filemaker":{"erver":1,"server":1,"pro":1}
,"erver":{"idle":1}
,"idle":{"edit":1,"option":1,"database":1,"time":1,"prevent":1,"full":1}
,"edit":{"privilege":1}
,"privilege":{"set":1}
,"set":{"ialog":1,"option":1,"basis":1,"users":1,"assigned":1,"disconnect":1}
,"ialog":{"box":1}
,"box":{"use":1}
,"use":{"disconnect":1}
,"disconnect":{"user":1}
,"user":{"server":1,"period":1,"connected":1,"database":1,"se":1}
,"server":{"idle":1,"period":1,"administrator":1,"administrators":1}
,"option":{"determine":1,"privilege":1,"determines":1,"disabled":1}
,"determine":{"users":1}
,"file":{"shared":1,"guest":1}
,"shared":{"by":1}
,"by":{"filemaker":1}
,"period":{"inactivity":1}
,"inactivity":{"ou":1,"keep":1}
,"ou":{"automatically":1}
,"automatically":{"disconnect":1}
,"keep":{"user":1}
,"connected":{"number":1,"hen":1,"filemaker":1}
,"number":{"active":1}
,"active":{"connections":1}
,"connections":{"performance":1,"filemaker":1}
,"performance":{"host":1,"while":1}
,"host":{"set":1}
,"basis":{"set":1}
,"disconnected":{"improve":1}
,"improve":{"performance":1}
,"while":{"permitting":1}
,"permitting":{"users":1}
,"maintain":{"connections":1}
,"administrator":{"sets":1}
,"sets":{"length":1}
,"length":{"time":1}
,"time":{"filemaker":1,"annoy":1}
,"pro":{"advanced":1}
,"advanced":{"users":1,"isconnect":1,"client":1}
,"database":{"filemaker":1,"ilemaker":1}
,"isconnect":{"user":1}
,"determines":{"filemaker":1}
,"client":{"disconnects":1}
,"disconnects":{"user":1}
,"ilemaker":{"server":1}
,"administrators":{"sure":1}
,"sure":{"idle":1}
,"annoy":{"users":1}
,"frequent":{"disconnections":1}
,"disconnections":{"privilege":1}
,"assigned":{"guest":1}
,"guest":{"account":1,"access":1}
,"account":{"enable":1}
,"enable":{"disconnect":1}
,"se":{"rver":1}
,"rver":{"idle":1}
,"prevent":{"users":1}
,"open":{"file":1}
,"access":{"remaining":1,"privilege":1,"privileges":1}
,"remaining":{"connected":1}
,"hen":{"idle":1}
,"full":{"access":1}
,"disabled":{"enabled":1}
,"enabled":{"therefore":1}
,"therefore":{"users":1}
,"privileges":{"remain":1}
,"remain":{"connected":1}
}
;Search.control.loadWordPairs(pairs);
