var pairs =
{
"show\u002Fhide":{"menubar":1,"toolbars":1}
,"menubar":{"hows":1,"[lock":1}
,"hows":{"hides":1}
,"hides":{"menu":1}
,"menu":{"bar":1}
,"bar":{"lock":1,"changed":1,"hide":1,"toggle":1,"filemaker":1,"status":1}
,"lock":{"prevents":1}
,"prevents":{"state":1}
,"state":{"menu":1}
,"changed":{"filemaker":1}
,"filemaker":{"go":1,"pro":1}
,"go":{"show":1,"layout":1}
,"show":{"menu":1}
,"hide":{"ide":1}
,"ide":{"menu":1}
,"toggle":{"switches":1}
,"switches":{"hiding":1}
,"hiding":{"menu":1}
,"pro":{"13":1}
,"13":{"script":1}
,"script":{"step":1}
,"step":{"supported":1}
,"supported":{"macos":1}
,"macos":{"active":1}
,"active":{"window":1}
,"window":{"card":1}
,"card":{"returns":1}
,"returns":{"error":1}
,"error":{"code":1}
,"code":{"code":1,"captured":1}
,"captured":{"get":1}
,"get":{"lasterror":1}
,"lasterror":{"function":1}
,"function":{"if":1}
,"if":{"guest":1,"[get":1,"automating":1}
,"guest":{"account":1}
,"account":{"logged":1}
,"logged":{"invoices":1}
,"invoices":{"layout":1,"\u0022]":1}
,"layout":{"hides":1,"[\u0022":1}
,"status":{"toolbar":1}
,"toolbar":{"if":1}
,"[get":{"accountname":1}
,"accountname":{"=\u0022":1}
,"=\u0022":{"[guest]":1}
,"[guest]":{"\u0022]":1}
,"\u0022]":{"go":1,"show\u002Fhide":1}
,"[\u0022":{"invoices":1}
,"[lock":{"hide]":1}
,"hide]":{"show\u002Fhide":1}
,"toolbars":{"[hide]":1}
,"[hide]":{"end":1}
,"end":{"if":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
