var pairs =
{
"entering":{"changing":1,"special":1}
,"changing":{"data":1}
,"data":{"field":1,"appears":1,"original":1}
,"field":{"limits":1,"type":1,"want":1,"valid":1,"browse":1,"formatted":1,"objects":1,"calculation":1,"filemaker":1}
,"limits":{"each":1}
,"each":{"field":1}
,"type":{"search":1,"tab":1,"first":1,"nter":1}
,"search":{"technical":1}
,"technical":{"specifications":1}
,"specifications":{"filemaker":1}
,"filemaker":{"knowledge":1,"pro":1}
,"knowledge":{"base":1}
,"base":{"type":1}
,"tab":{"character":1,"press":1,"windows":1,"field":1}
,"character":{"field":1}
,"want":{"insert":1,"enter":1}
,"insert":{"tab":1}
,"press":{"ctrl":1,"space":1}
,"ctrl":{"tab":1}
,"windows":{"option-tab":1}
,"option-tab":{"macos":1}
,"macos":{"if":1}
,"if":{"field":1,"mix":1}
,"valid":{"url":1}
,"url":{"open":1}
,"open":{"application":1}
,"application":{"urls":1}
,"urls":{"field":1}
,"browse":{"mode":1}
,"mode":{"use":1,"system":1,"hen":1}
,"use":{"keyboard":1,"arrow":1,"own":1,"system":1}
,"keyboard":{"enter":1}
,"enter":{"values":1,"use":1,"value":1}
,"values":{"radio":1}
,"radio":{"buttons":1}
,"buttons":{"checkboxes":1}
,"checkboxes":{"tab":1}
,"first":{"letter":1}
,"letter":{"value":1}
,"value":{"want":1,"data":1}
,"arrow":{"keys":1}
,"keys":{"select":1}
,"select":{"press":1}
,"space":{"bar":1}
,"bar":{"enter":1}
,"appears":{"depends":1}
,"depends":{"field":1}
,"formatted":{"layout":1}
,"layout":{"mode":1}
,"system":{"formats":1,"type":1}
,"formats":{"file":1,"ormatting":1,"choose":1,"own":1,"use":1,"verify":1,"checked":1,"if":1}
,"file":{"created":1}
,"created":{"computer\u0027s":1,"computer":1}
,"computer\u0027s":{"system":1}
,"ormatting":{"setting":1}
,"setting":{"up":1}
,"up":{"field":1}
,"objects":{"layout":1}
,"hen":{"files":1}
,"files":{"created":1,"system":1}
,"computer":{"system":1}
,"choose":{"view":1}
,"view":{"data":1}
,"original":{"system":1}
,"own":{"system":1,"formats":1}
,"verify":{"use":1}
,"checked":{"format":1}
,"format":{"menu":1}
,"menu":{"files":1}
,"mix":{"numbers":1}
,"numbers":{"text":1,"entered":1}
,"text":{"number":1,"performing":1}
,"number":{"field":1}
,"calculation":{"summary":1}
,"summary":{"field":1,"numbers":1}
,"pro":{"advanced":1}
,"advanced":{"ignores":1}
,"ignores":{"text":1}
,"performing":{"calculation":1}
,"entered":{"scientific":1}
,"scientific":{"notation":1}
,"notation":{"1.23e":1}
,"1.23e":{"15":1}
,"15":{"1.23e-15":1}
,"1.23e-15":{"entering":1}
,"special":{"characters":1}
,"characters":{"accent":1,"search":1}
,"accent":{"marks":1}
,"marks":{"help":1}
,"help":{"operating":1}
,"operating":{"system":1}
,"nter":{"special":1}
}
;Search.control.loadWordPairs(pairs);
