var pairs =
{
"onfileavplayerchange":{"performs":1}
,"performs":{"script":1}
,"script":{"edia":1,"trigger":1,"step":1,"runs":1}
,"edia":{"playing":1}
,"playing":{"field":1,"end":1,"avplayer":1,"video":1,"container":1}
,"field":{"url":1}
,"url":{"tate":1}
,"tate":{"player":1}
,"player":{"events":1}
,"events":{"activate":1}
,"activate":{"script":1}
,"trigger":{"user":1,"media":1,"result":1}
,"user":{"pauses":1}
,"pauses":{"plays":1}
,"plays":{"stops":1}
,"stops":{"media":1,"playing":1}
,"media":{"by":1,"stops":1,"playing":1}
,"by":{"playback":1}
,"playback":{"controls":1,"state":1}
,"controls":{"gestures":1}
,"gestures":{"video":1}
,"video":{"stops":1,"media":1,"set":1}
,"end":{"video":1}
,"avplayer":{"set":1,"play":1}
,"set":{"playback":1,"stopped":1,"script":1}
,"state":{"script":1}
,"step":{"set":1,"starts":1}
,"stopped":{"video":1}
,"play":{"script":1}
,"starts":{"playing":1}
,"container":{"layout":1}
,"layout":{"object":1}
,"object":{"onobjectavplayerchange":1}
,"onobjectavplayerchange":{"event":1}
,"event":{"processed":1}
,"processed":{"browse":1}
,"browse":{"find":1}
,"find":{"modes":1}
,"modes":{"none":1,"trigger":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"14":1}
,"14":{"script":1}
,"runs":{"modes":1}
}
;Search.control.loadWordPairs(pairs);
