var pairs =
{
"set":{"next":1}
,"next":{"serial":1,"invoice":1}
,"serial":{"value":1,"number":1,"value]":1}
,"value":{"esets":1,"auto-entry":1,"create":1,"filemaker":1,"field":1,"import":1,"invoice":1,"[invoices":1,"product":1,"[products":1,"show":1,"invoices":1}
,"esets":{"next":1}
,"auto-entry":{"serial":1}
,"number":{"field":1,"next":1,"value":1}
,"field":{"target":1,"specifies":1,"script":1,"defined":1,"calculated":1,"calculation":1,"delete":1,"actual":1,"file":1,"select":1,"if":1,"options":1}
,"target":{"field":1}
,"specifies":{"serial":1}
,"script":{"step":1}
,"step":{"operate":1,"use":1,"definition":1}
,"operate":{"field":1,"multiple":1}
,"defined":{"auto-entry":1}
,"calculated":{"result":1}
,"result":{"llows":1,"want":1}
,"llows":{"enter":1}
,"enter":{"next":1}
,"create":{"calculation":1}
,"calculation":{"determine":1,"expression":1,"evaluates":1,"sophisticated":1}
,"determine":{"next":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1,"advanced":1}
,"6.0":{"earlier":1}
,"earlier":{"define":1}
,"define":{"script":1,"relationship":1}
,"use":{"calculation":1,"target":1}
,"expression":{"determine":1}
,"evaluates":{"text":1}
,"text":{"result":1}
,"want":{"reset":1}
,"reset":{"next":1}
,"import":{"records":1}
,"records":{"filemaker":1,"if":1,"[with":1}
,"advanced":{"database":1,"attempts":1}
,"database":{"auto-entry":1,"script":1}
,"delete":{"multiple":1}
,"multiple":{"serialized":1,"files":1}
,"serialized":{"numbers":1}
,"numbers":{"filemaker":1}
,"definition":{"field":1}
,"actual":{"contents":1}
,"contents":{"field":1}
,"files":{"if":1}
,"if":{"field":1,"invoice":1,"perform":1,"[get":1,"defining":1}
,"file":{"filemaker":1,"field":1,"define":1,"use":1,"calculates":1}
,"attempts":{"update":1}
,"update":{"serial":1}
,"relationship":{"file":1}
,"select":{"field":1}
,"calculates":{"number":1}
,"invoice":{"id":1}
,"id":{"max":1,"field":1,"non-numeric":1,"1]":1,"invoices":1}
,"max":{"function":1,"invoices":1}
,"function":{"return":1}
,"return":{"value":1}
,"non-numeric":{"data":1}
,"data":{"calculation":1,"go":1,"entry":1}
,"sophisticated":{"maintain":1}
,"maintain":{"numeric":1}
,"numeric":{"non-numeric":1}
,"go":{"record\u002Frequest\u002Fpage":1}
,"record\u002Frequest\u002Fpage":{"[last]":1}
,"[last]":{"set":1}
,"[invoices":{":invoice":1}
,":invoice":{"id":1}
,"invoices":{":invoice":1,":next":1}
,"1]":{"sets":1}
,"sets":{"next":1}
,"product":{"field":1,"catalog.xlsx":1,"get":1}
,"options":{"importing":1,"during":1}
,"importing":{"records":1}
,"perform":{"auto-enter":1}
,"auto-enter":{"options":1}
,"during":{"mport":1}
,"mport":{"selected":1}
,"selected":{"order":1}
,"order":{"preserve":1}
,"preserve":{"dates":1}
,"dates":{"auto-entered":1}
,"auto-entered":{"values":1}
,"values":{"import":1}
,"[with":{"dialog":1}
,"dialog":{"table":1,"[\u0022":1}
,"table":{"products":1}
,"products":{"source":1}
,"source":{"new":1}
,"new":{"product":1}
,"catalog.xlsx":{"worksheet":1}
,"worksheet":{"stock":1}
,"stock":{"dd":1}
,"dd":{"mac":1}
,"mac":{"roman":1}
,"roman":{"set":1}
,"[products":{"product":1}
,"get":{"totalrecordcount":1}
,"totalrecordcount":{"prompts":1}
,"prompts":{"user":1}
,"user":{"input":1}
,"input":{"next":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"[\u0022":{"set":1}
,":next":{"serial":1}
,"value]":{"if":1,"end":1}
,"[get":{"lastmessagechoice":1}
,"lastmessagechoice":{"=1]":1}
,"=1]":{"set":1}
,"end":{"if":1}
,"defining":{"automatic":1}
,"automatic":{"data":1}
,"entry":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
