var pairs =
{
"esizing":{"layout":1}
,"layout":{"part":1,"mode":1,"while":1,"use":1}
,"part":{"layout":1,"label":1,"boundary":1,"part":1,"height":1,"alt-drag":1,"changing":1,"select":1,"by":1}
,"mode":{"selection":1}
,"selection":{"tool":1}
,"tool":{"selection":1,"status":1}
,"status":{"toolbar":1}
,"toolbar":{"drag":1}
,"drag":{"part":1}
,"label":{"part":1,"inspector":1}
,"boundary":{"line":1,"size":1,"position":1}
,"line":{"marks":1}
,"marks":{"bottom":1}
,"bottom":{"part":1,"boundary":1}
,"height":{"want":1,"entire":1,"bottom":1}
,"want":{"maintain":1}
,"maintain":{"height":1}
,"entire":{"layout":1}
,"while":{"changing":1}
,"changing":{"size":1,"change":1}
,"size":{"layout":1}
,"alt-drag":{"windows":1}
,"windows":{"option-drag":1}
,"option-drag":{"macos":1}
,"macos":{"part":1}
,"change":{"precisely":1}
,"precisely":{"resize":1,"sizing":1}
,"resize":{"part":1}
,"select":{"part":1}
,"by":{"clicking":1}
,"clicking":{"part":1}
,"inspector":{"lick":1}
,"lick":{"position":1}
,"position":{"position":1,"tab":1,"positioning":1}
,"tab":{"enter":1}
,"enter":{"value":1}
,"value":{"part\u0027s":1}
,"part\u0027s":{"height":1}
,"positioning":{"objects":1}
,"objects":{"layout":1}
,"use":{"rulers":1}
,"rulers":{"grid":1,"view":1}
,"grid":{"guides":1,"show":1,"view":1}
,"guides":{"choose":1,"help":1,"dynamic":1}
,"choose":{"view":1}
,"view":{"menu":1}
,"menu":{"rulers":1,"grid":1,"show":1}
,"show":{"grid":1,"guides":1}
,"help":{"precisely":1}
,"sizing":{"parts":1}
,"parts":{"sing":1}
,"sing":{"rulers":1}
,"dynamic":{"guides":1}
}
;Search.control.loadWordPairs(pairs);
