var pairs =
{
"supported":{"import\u002Fexport":1,"format":1}
,"import\u002Fexport":{"file":1}
,"file":{"formats":1,"format":1,"use":1}
,"formats":{"filemaker":1,"support":1,"export":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1,"format":1}
,"advanced":{"application":1,"program":1,"odbc":1,"data":1,"sh":1,"updates":1,"setti":1}
,"application":{"programs":1,"format":1,"import":1,"program":1}
,"programs":{"want":1}
,"want":{"exchange":1}
,"exchange":{"data":1}
,"data":{"use":1,"export":1,"application":1,"conversion":1,"html":1,"result":1,"sources":1,"source":1,"uerying":1,"via":1,"automatically":1,"file":1,"demand":1,"imported":1}
,"use":{"proprietary":1,"field":1,"static":1,"custom-separated":1,"filemaker":1,"script":1}
,"proprietary":{"file":1}
,"format":{"order":1,"application":1,"filemaker":1,"filename":1,".csv":1,".tab":1,".dbf":1,"retains":1,".fmp12":1,".htm":1,".mer":1,".xlsx":1,"xml":1,".xml":1}
,"order":{"exchange":1}
,"export":{"data":1,"formatting":1,"convert":1,"notes":1,"exports":1,"converting":1}
,"import":{"if":1,"export":1,"use":1,"xml":1,"image":1,"odbc":1,"read-only":1}
,"if":{"you\u2019re":1}
,"you\u2019re":{"exchanging":1}
,"exchanging":{"data":1}
,"program":{"check":1,"determine":1,"supports":1}
,"check":{"documentation":1}
,"documentation":{"program":1}
,"determine":{"common":1}
,"common":{"intermediary":1}
,"intermediary":{"file":1}
,"supports":{"ost":1}
,"ost":{"file":1}
,"support":{"data":1}
,"conversion":{"import":1}
,"formatting":{"font":1}
,"font":{"size":1}
,"size":{"style":1}
,"style":{"color":1}
,"color":{"formats":1}
,"convert":{"field":1,"export":1}
,"field":{"names":1,"types":1,"values":1}
,"names":{"field":1,"custom-separated":1,"character":1,"filemaker":1,"html":1,"excel":1,"tab-se":1,"import":1}
,"types":{"supported":1}
,"filename":{"extension":1}
,"extension":{"import\u002Fconvert":1}
,"import\u002Fconvert":{"export":1,"record":1}
,"notes":{"omma-se":1}
,"omma-se":{"parated":1}
,"parated":{"values":1}
,"values":{"format":1,"base":1,"ormat":1}
,".csv":{".txt":1}
,".txt":{"record":1,"import\u002Fconvert":1,"convert":1}
,"record":{"use":1}
,"custom-separated":{"values":1}
,".tab":{".txt":1}
,"character":{"separates":1}
,"separates":{"field":1}
,"base":{"iii":1}
,"iii":{"iv":1}
,"iv":{"dbf":1}
,"dbf":{"format":1}
,".dbf":{"format":1}
,"retains":{"field":1}
,".fmp12":{"format":1}
,"html":{"ta":1,"table":1}
,"ta":{"ble":1}
,"ble":{"format":1}
,".htm":{"export":1}
,"exports":{"data":1}
,"table":{"use":1}
,"static":{"webpage":1}
,"webpage":{"merge":1}
,"merge":{"format":1}
,".mer":{"format":1}
,"excel":{"format":1}
,".xlsx":{"record":1}
,"tab-se":{"parated":1}
,"ormat":{".tab":1}
,"converting":{"record":1}
,"xml":{"format":1,"files":1,"data":1}
,".xml":{"addition":1}
,"addition":{"xml":1}
,"files":{"import":1,"text":1,"folder":1,"all":1}
,"result":{"http":1}
,"http":{"request":1}
,"request":{"import":1}
,"image":{"files":1}
,"text":{"files":1}
,"folder":{"all":1,"files":1}
,"all":{"mporting":1,"import":1}
,"mporting":{"folder":1}
,"odbc":{"data":1,"jdbc":1}
,"sources":{"use":1}
,"source":{"serve":1,"filemaker":1}
,"serve":{"filemaker":1}
,"uerying":{"odbc":1}
,"sh":{"ari":1}
,"ari":{"ng":1}
,"ng":{"filemaker":1,"up":1}
,"via":{"odbc":1,"recurring":1}
,"jdbc":{"set":1}
,"set":{"up":1}
,"up":{"recurring":1}
,"recurring":{"imports":1,"import":1}
,"imports":{"filemaker":1}
,"updates":{"data":1}
,"automatically":{"first":1}
,"first":{"time":1}
,"time":{"view":1}
,"view":{"imported":1}
,"imported":{"data":1,"via":1}
,"script":{"update":1}
,"update":{"data":1}
,"demand":{"data":1}
,"read-only":{"filemaker":1}
,"setti":{"ng":1}
}
;Search.control.loadWordPairs(pairs);
