var pairs =
{
"merge":{"format":1,"export":1,"create":1,"fields":1}
,"format":{"import":1,"choose":1,"creating":1,"word":1}
,"import":{"convert":1}
,"convert":{"export":1}
,"export":{"rge":1,"vertical":1,"double":1,"format":1}
,"rge":{"files":1,"filemaker":1}
,"files":{"field":1,"exporting":1}
,"field":{"names":1,"separator":1,"data":1,"export":1}
,"names":{"imported":1,"application":1,"importing":1,"carriage":1}
,"imported":{"all":1,"support":1}
,"all":{"fields":1}
,"fields":{"text":1,"filemaker":1,"depending":1,"separated":1,"placing":1,"layout":1}
,"text":{"fields":1,"file":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1,"formats":1}
,"advanced":{"exports":1,"by":1}
,"exports":{"text":1}
,"file":{"characteristics":1}
,"characteristics":{"character":1}
,"character":{"separates":1,"semicolon":1,"locales":1,"quotation":1}
,"separates":{"fields":1}
,"depending":{"language":1}
,"language":{"operating":1}
,"operating":{"system":1}
,"system":{"u.s":1}
,"u.s":{"english":1}
,"english":{"systems":1}
,"systems":{"field":1}
,"separator":{"comma":1,"character":1}
,"comma":{"european":1}
,"european":{"systems":1}
,"semicolon":{"character":1}
,"locales":{"rge":1}
,"formats":{"include":1}
,"include":{"field":1}
,"application":{"data":1}
,"data":{"imported":1,"carriage":1,"enclosed":1}
,"support":{"format":1}
,"choose":{"applications":1}
,"applications":{"strip":1}
,"strip":{"field":1}
,"importing":{"exported":1,"co":1}
,"exported":{"data":1}
,"carriage":{"return":1}
,"return":{"characters":1}
,"characters":{"separate":1,"field":1,"values":1}
,"separate":{"records":1}
,"records":{"field":1}
,"enclosed":{"quotation":1}
,"quotation":{"marks":1}
,"marks":{"first":1,"field":1,"merge":1}
,"first":{"record":1}
,"record":{"header":1}
,"header":{"lists":1}
,"lists":{"field":1}
,"vertical":{"tab":1}
,"tab":{"characters":1}
,"values":{"repeating":1}
,"repeating":{"fields":1}
,"separated":{"by":1}
,"by":{"group":1,"typing":1}
,"group":{"separator":1}
,"double":{"quotation":1}
,"creating":{"form":1}
,"form":{"letters":1}
,"letters":{"word":1,"filemaker":1}
,"word":{"processor":1,"mail":1}
,"processor":{"export":1}
,"mail":{"merge":1}
,"create":{"form":1}
,"typing":{"letter":1}
,"letter":{"layout":1}
,"layout":{"merge":1,"importing":1}
,"placing":{"merge":1}
,"co":{"nverting":1}
,"nverting":{"rge":1}
,"exporting":{"rge":1}
}
;Search.control.loadWordPairs(pairs);
