var pairs =
{
"ork":{"ing":1}
,"ing":{"fields":1}
,"fields":{"layout":1,"remove":1,"want":1,"defined":1,"fields":1,"add":1}
,"layout":{"create":1,"place":1,"times":1,"objects":1,"mode":1,"add":1,"field\u0027s":1,"portal":1}
,"create":{"layout":1}
,"place":{"additional":1,"field":1,"fields":1,"related":1}
,"additional":{"fields":1}
,"remove":{"fields":1}
,"want":{"displayed":1,"place":1}
,"displayed":{"place":1}
,"field":{"layout":1,"displays":1,"name":1,"locations":1,"subsummary":1,"header":1,"heading":1}
,"times":{"want":1}
,"defined":{"defining":1}
,"defining":{"changing":1}
,"changing":{"fields":1}
,"objects":{"select":1}
,"select":{"move":1}
,"move":{"resize":1}
,"resize":{"reshape":1}
,"reshape":{"layout":1}
,"mode":{"each":1}
,"each":{"field":1,"group":1}
,"displays":{"field":1}
,"name":{"formatted":1,"field":1}
,"formatted":{"attributes":1}
,"attributes":{"font":1}
,"font":{"size":1}
,"size":{"style":1}
,"style":{"alignment":1}
,"alignment":{"line":1}
,"line":{"spacing":1}
,"spacing":{"color":1}
,"color":{"get":1}
,"get":{"by":1,"totals":1}
,"by":{"placing":1}
,"placing":{"field":1}
,"locations":{"layout":1}
,"add":{"summary":1,"field":1,"last":1,"related":1}
,"summary":{"field":1,"part":1}
,"subsummary":{"part":1}
,"part":{"calculate":1,"get":1,"footer":1,"repeat":1}
,"calculate":{"totals":1}
,"totals":{"each":1,"all":1}
,"group":{"sorted":1}
,"sorted":{"records":1}
,"records":{"grand":1,"database":1}
,"grand":{"summary":1}
,"all":{"records":1}
,"database":{"add":1}
,"header":{"part":1,"footer":1,"directory":1}
,"footer":{"part":1,"add":1}
,"repeat":{"data":1}
,"data":{"first":1}
,"first":{"record":1,"related":1}
,"record":{"last":1,"page":1,"inside":1,"place":1}
,"last":{"record":1,"name":1}
,"page":{"header":1}
,"directory":{"add":1}
,"related":{"field":1,"record":1,"fields":1}
,"field\u0027s":{"value":1}
,"value":{"first":1}
,"inside":{"portal":1}
,"portal":{"values":1,"deciding":1}
,"values":{"related":1}
,"deciding":{"place":1}
,"heading":{"headings":1}
}
;Search.control.loadWordPairs(pairs);
