var pairs =
{
"lookupnext":{"returns":1,"sourcefield":1,"lookup":1,"function":1,"flag":1}
,"returns":{"next":1,"value":1,"related":1}
,"next":{"lower":1,"lower\u002Fhigher":1,"value":1}
,"lower":{"value":1,"denote":1,"matching":1}
,"value":{"sourcefield":1,"lookupnext":1,"lower\u002Fhigherflag":1,"next":1,"two":1}
,"sourcefield":{"matching":1,"lower\u002Fhigherflag":1,"-the":1,"relationships":1,"lower":1,"tables":1}
,"matching":{"related":1,"record":1}
,"related":{"value":1,"record":1,"calculations":1,"table":1,"by":1}
,"lower\u002Fhigherflag":{"sourcefield":1,"-the":1,"function":1}
,"-the":{"field":1,"keywords":1}
,"field":{"lookup":1,"calculation":1,"related":1,"rate":1,"return":1}
,"lookup":{"value":1,"except":1,"fails":1,"function":1,"lamp":1,"defined":1,"=lookupnext":1,"calculation":1,"get":1}
,"keywords":{"lower":1}
,"denote":{"value":1}
,"lower\u002Fhigher":{"matching":1}
,"record":{"if":1,"found":1,"returned":1}
,"if":{"related":1}
,"found":{"text":1}
,"text":{"number":1}
,"number":{"date":1}
,"date":{"time":1}
,"time":{"timestamp":1}
,"timestamp":{"container":1}
,"container":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"7.0":1}
,"7.0":{"returns":1}
,"relationships":{"relationships":1,"graph":1}
,"graph":{"lookupnext":1}
,"except":{"lookup":1}
,"fails":{"value":1}
,"returned":{"by":1}
,"by":{"lower\u002Fhigherflag":1,"weight":1}
,"function":{"access":1,"won\u2019t":1,"find":1,"weight":1}
,"access":{"value":1}
,"tables":{"source":1,"items":1,"related":1}
,"source":{"field":1,"shipping":1}
,"calculation":{"field":1}
,"calculations":{"lookupnext":1}
,"won\u2019t":{"forced":1}
,"forced":{"unstored":1}
,"unstored":{"calculations":1}
,"table":{"odbc":1,"item":1,"rate":1}
,"odbc":{"data":1}
,"data":{"source":1,"items":1}
,"shipping":{"items":1,"based":1,"rate":1,"costs":1}
,"items":{"cost":1,"shipping":1,"table":1}
,"cost":{"shipping":1}
,"based":{"weight":1}
,"weight":{"ranges":1,"item":1,"want":1,"rate":1,"25":1,"max":1,"calculation":1}
,"ranges":{"use":1}
,"use":{"lookupnext":1}
,"find":{"shipping":1,"next":1}
,"rate":{"applies":1,"lookup":1,"code":1}
,"applies":{"item":1}
,"item":{"use":1,"match":1,"weight":1}
,"flag":{"lookup":1}
,"match":{"maximum":1}
,"maximum":{"weight":1}
,"want":{"find":1}
,"two":{"tables":1}
,"costs":{"database":1,"table":1,":max":1}
,"database":{"file":1}
,"file":{"data":1}
,"lamp":{"chair":1,"25":1}
,"chair":{"22":1}
,"22":{"desk":1,"25":1}
,"desk":{"60":1}
,"60":{"bed":1,"100":1}
,"bed":{"120":1}
,"120":{"shipping":1,"150":1}
,"code":{"maximum":1,"item":1}
,"25":{"50":1,"25":1,"100":1,"chair":1,"desk":1}
,"50":{"100":1}
,"100":{"150":1,"bed":1}
,"150":{"two":1,"records":1}
,"max":{"weight":1}
,"defined":{"rate":1}
,"=lookupnext":{"shipping":1}
,":max":{"weight":1}
,"return":{"25":1}
,"records":{"rate":1}
,"get":{"correct":1}
,"correct":{"rate":1}
}
;Search.control.loadWordPairs(pairs);
