var pairs =
{
"options":{"su":1,"summary":1}
,"su":{"mmary":1}
,"mmary":{"field":1}
,"field":{"dialog":1,"report":1,"name":1,"naming":1,"found":1,"average":1,"count":1,"if":1,"100":1,"maximum":1,"standard":1,"each":1,"fraction":1,"total":1,"find":1,"summarize":1,"types":1,"sort":1,"list":1,"weight":1,"based":1,"group":1,"summarizing":1,"option":1,"select":1,"repeating":1,"display":1,"change":1,"layout":1,"reflects":1,"use":1,"current":1,"table":1,"subtotaled":1,"calculate":1,"manually":1,"schemas":1}
,"dialog":{"box":1}
,"box":{"new":1,"use":1,"define":1}
,"new":{"layout\u002Freport":1,"summary":1}
,"layout\u002Freport":{"assistant":1}
,"assistant":{"if":1,"defining":1,"create":1}
,"if":{"clicked":1,"defining":1,"field":1,"applicable":1,"change":1,"choose":1,"filemaker":1}
,"clicked":{"add":1}
,"add":{"field":1}
,"use":{"options":1,"new":1,"supplemental":1}
,"summary":{"field":1,"fields":1,"calculation":1,"option":1,"type":1,"each":1,"value":1,"values":1,"based":1,"instructions":1}
,"define":{"new":1,"unstored":1}
,"report":{"new":1}
,"defining":{"summary":1}
,"fields":{"new":1,"summary":1,"select":1,"choose":1,"invalid":1,"associated":1,"create":1,"if":1,"getsummary":1,"define":1,"table":1}
,"name":{"type":1,"field":1}
,"type":{"name":1,"summary":1,"chose":1}
,"naming":{"fields":1}
,"select":{"type":1,"summary":1,"total":1,"restart":1,"field":1,"all":1,"individually":1}
,"calculation":{"summarize":1,"selected":1}
,"summarize":{"values":1,"note":1,"repetitions":1}
,"values":{"field":1,"value":1,"etting":1}
,"found":{"set":1,"records":1}
,"set":{"records":1,"filemaker":1}
,"records":{"by":1,"contain":1,"restart":1,"if":1,"value":1,"found":1,"sorted":1,"currently":1,"group":1}
,"by":{"total":1,"population":1,"calculate":1,"group":1}
,"total":{"calculating":1,"values":1,"all":1,"sales":1,"running":1,"show":1,"current":1,"each":1,"subtotaled":1,"based":1,"group":1}
,"calculating":{"total":1,"average":1,"ratio":1}
,"average":{"calculating":1,"values":1,"weighted":1,"field":1}
,"count":{"counting":1,"100":1,"running":1,"show":1,"current":1,"each":1}
,"counting":{"number":1}
,"number":{"records":1,"earliest":1,"date":1}
,"contain":{"value":1}
,"value":{"field":1,"each":1,"all":1,"summary":1,"fields":1,"correctly":1}
,"100":{"values":1,"minimum":1}
,"each":{"record":1,"option":1,"salesperson":1,"sorted":1,"repetition":1}
,"record":{"result":1}
,"result":{"count":1,"summary":1}
,"minimum":{"finding":1}
,"finding":{"lowest":1,"number":1,"values":1}
,"lowest":{"number":1}
,"earliest":{"date":1}
,"date":{"time":1}
,"time":{"timestamp":1}
,"timestamp":{"field":1}
,"maximum":{"finding":1}
,"standard":{"deviation":1}
,"deviation":{"finding":1,"mean":1,"by":1,"fraction":1,"formula":1,"change":1}
,"option":{"calculates":1,"if":1,"summarize":1}
,"calculates":{"standard":1}
,"mean":{"values":1}
,"fraction":{"total":1}
,"ratio":{"value":1}
,"all":{"values":1,"previous":1,"calculate":1,"repetitions":1,"records":1}
,"find":{"fraction":1}
,"sales":{"attributed":1}
,"attributed":{"each":1}
,"salesperson":{"list":1}
,"list":{"fields":1,"based":1,"average":1,"appears":1,"standard":1}
,"choose":{"field":1,"fraction":1}
,"note":{"fields":1,"format":1}
,"invalid":{"field":1}
,"types":{"dimmed":1}
,"dimmed":{"list":1}
,"based":{"summary":1,"value":1,"group":1,"if":1}
,"selected":{"select":1}
,"applicable":{"summary":1}
,"chose":{"select":1}
,"running":{"total":1,"count":1}
,"show":{"cumulative":1}
,"cumulative":{"total":1,"count":1}
,"current":{"all":1,"table":1}
,"previous":{"records":1}
,"restart":{"running":1,"summary":1}
,"sorted":{"group":1,"data":1}
,"group":{"select":1,"by":1,"records":1,"found":1,"field":1}
,"sort":{"restarted":1,"by":1}
,"restarted":{"field":1}
,"weighted":{"average":1,"normal":1}
,"appears":{"select":1}
,"weight":{"factor":1}
,"factor":{"determine":1,"count":1}
,"determine":{"average":1}
,"population":{"calculate":1,"standard":1}
,"calculate":{"population":1,"fraction":1,"single":1,"summary":1,"value":1}
,"subtotaled":{"field":1,"return":1}
,"summarizing":{"repeating":1}
,"repeating":{"field":1,"fields":1}
,"repetitions":{"individually":1,"field":1}
,"individually":{"select":1,"calculate":1}
,"single":{"summary":1}
,"repetition":{"note":1}
,"format":{"summary":1}
,"display":{"individual":1,"repeating":1}
,"individual":{"summary":1}
,"etting":{"up":1}
,"up":{"display":1}
,"associated":{"groups":1}
,"groups":{"records":1}
,"change":{"depending":1,"value":1,"found":1,"data":1}
,"depending":{"place":1}
,"place":{"field":1}
,"layout":{"records":1}
,"data":{"summary":1,"odbc":1,"source":1,"coming":1}
,"reflects":{"records":1}
,"currently":{"browsed":1}
,"browsed":{"all":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"recalculates":1,"file":1}
,"recalculates":{"result":1}
,"create":{"summary":1}
,"table":{"create":1,"defining":1}
,"return":{"browse":1}
,"browse":{"mode":1}
,"mode":{"sort":1}
,"correctly":{"standard":1}
,"formula":{"-1":1}
,"-1":{"weighted":1}
,"normal":{"standard":1}
,"manually":{"copy":1}
,"copy":{"perform":1,"field":1}
,"perform":{"calculations":1}
,"calculations":{"summary":1}
,"getsummary":{"function":1}
,"function":{"if":1}
,"file":{"accesses":1,"paste":1,"file":1,"copying":1}
,"accesses":{"data":1}
,"odbc":{"data":1}
,"source":{"use":1}
,"supplemental":{"fields":1}
,"unstored":{"calculations":1}
,"instructions":{"data":1}
,"coming":{"external":1}
,"external":{"sources":1}
,"sources":{"yo":1}
,"yo":{"copy":1}
,"schemas":{"file":1}
,"paste":{"file":1}
,"copying":{"moving":1}
,"moving":{"fields":1}
}
;Search.control.loadWordPairs(pairs);
