var pairs =
{
"else":{"if":1,"script":1,"statement":1}
,"if":{"valuates":1,"sp":1,"follow":1,"else":1,"script":1,"statement":1,"executed":1,"process":1,"records":1,"[get":1,"automating":1}
,"valuates":{"boolean":1}
,"boolean":{"calculation":1,"alculation":1}
,"calculation":{"performs":1}
,"performs":{"conditional":1,"find":1}
,"conditional":{"action":1}
,"action":{"based":1}
,"based":{"evaluation":1}
,"evaluation":{"if":1,"true":1}
,"sp":{"ecif":1}
,"ecif":{"boolean":1}
,"alculation":{"want":1}
,"want":{"evaluated":1}
,"evaluated":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"else":1}
,"follow":{"if":1,"else":1}
,"script":{"step":1,"execution":1}
,"step":{"else":1,"if":1,"evaluates":1,"performs":1}
,"evaluates":{"false":1,"true":1}
,"false":{"script":1}
,"execution":{"moves":1,"skip":1}
,"moves":{"else":1}
,"statement":{"evaluates":1,"execution":1}
,"true":{"block":1,"else":1}
,"block":{"steps":1}
,"steps":{"under":1}
,"under":{"else":1}
,"executed":{"evaluation":1}
,"process":{"reaching":1}
,"reaching":{"next":1}
,"next":{"else":1}
,"skip":{"end":1}
,"end":{"if":1}
,"find":{"sorts":1,"request":1,"[restore]":1}
,"sorts":{"records":1}
,"records":{"if":1,"match":1,"[restore":1,"found":1}
,"match":{"find":1}
,"request":{"displays":1}
,"displays":{"custom":1}
,"custom":{"dialog":1}
,"dialog":{"box":1,"off]":1,"[\u0022":1}
,"box":{"perform":1}
,"perform":{"find":1}
,"[restore]":{"if":1}
,"[get":{"lasterror":1}
,"lasterror":{"=0":1,"=401":1}
,"=0":{"sort":1}
,"sort":{"records":1}
,"[restore":{"dialog":1}
,"off]":{"else":1}
,"=401":{"show":1}
,"show":{"custom":1}
,"[\u0022":{"records":1}
,"found":{"\u0022]":1}
,"\u0022]":{"end":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
