var pairs =
{
"numtojtext":{"converts":1,"number":1,"123456789;2;0":1,"123456789;3;2":1}
,"converts":{"arabic":1}
,"arabic":{"numerals":1,"numeral":1}
,"numerals":{"japanese":1}
,"japanese":{"text":1,"character":1,"kanji":1,"traditional":1}
,"text":{"numtojtext":1,"filemaker":1,"arabic":1}
,"number":{"separator":1,"-any":1,"representing":1,"-full-width":1,"-kanji":1,"japanese":1,"-traditional":1,"numtojtext":1}
,"separator":{"charactertype":1,"-a":1,"-every":1,"tens":1,"type":1}
,"charactertype":{"number":1,"-a":1,"blank":1}
,"-any":{"numeric":1}
,"numeric":{"expression":1}
,"expression":{"field":1}
,"field":{"number":1}
,"-a":{"number":1}
,"representing":{"separator":1,"type":1}
,"type":{"text":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"if":1}
,"if":{"value":1}
,"value":{"separator":1}
,"blank":{"-no":1}
,"-no":{"separator":1}
,"-every":{"digits":1}
,"digits":{"thousands":1}
,"thousands":{"-ten":1,"japanese":1,"thousands":1,"millions":1}
,"-ten":{"thousands":1}
,"character":{"millions":1,"unit":1,"hundreds":1,"hundred":1,"thousands":1,"number":1}
,"millions":{"japanese":1,"hundred":1,"numtojtext":1,"separator":1}
,"unit":{"-tens":1,"-half-width":1}
,"-tens":{"japanese":1}
,"hundreds":{"japanese":1,"thousands":1}
,"hundred":{"thousands":1,"millions":1}
,"-half-width":{"hankaku":1}
,"hankaku":{"number":1,"1-byte":1}
,"-full-width":{"zenkaku":1}
,"zenkaku":{"number":1}
,"-kanji":{"number":1}
,"kanji":{"character":1,"number":1}
,"-traditional":{"kanji":1}
,"traditional":{"kanji":1}
,"123456789;2;0":{"returns":1}
,"returns":{"arabic":1,"japanese":1}
,"numeral":{"123456789":1}
,"123456789":{"half-width":1,"kanji":1}
,"half-width":{"hankaku":1}
,"1-byte":{"separators":1}
,"separators":{"thousands":1}
,"123456789;3;2":{"returns":1}
,"tens":{"hundreds":1}
}
;Search.control.loadWordPairs(pairs);
