var pairs =
{
"set":{"field":1}
,"field":{"by":1,"current":1,"calculation":1,"contents":1,"name":1,"literally":1,"calculated":1,"script":1,"return":1,"if":1,"field":1,"selected":1,"target":1,"doesn\u2019t":1,"each":1,"national":1,"set":1,"simplify":1,"customers":1,"[customers":1,"automating":1}
,"by":{"name":1,"script":1,"calculation":1}
,"name":{"eplaces":1,"script":1,"change":1,"step":1,"target":1,"named":1,"ignores":1,"[if":1,"set":1,"[getfieldname":1}
,"eplaces":{"entire":1}
,"entire":{"contents":1}
,"contents":{"calculated":1,"want":1,"field":1}
,"calculated":{"target":1,"value":1,"result":1,"single":1}
,"target":{"field":1}
,"current":{"record":1,"layout":1}
,"record":{"calculated":1,"active":1,"exited":1,"lock":1,"download":1}
,"value":{"target":1,"field":1,"sum":1}
,"calculation":{"field":1,"inserted":1,"target":1,"determine":1}
,"want":{"replace":1}
,"replace":{"calculated":1,"multiple":1}
,"result":{"pecifies":1,"if":1}
,"pecifies":{"calculation":1}
,"inserted":{"by":1}
,"script":{"step":1,"steps":1}
,"step":{"filemaker":1,"create":1,"replace":1,"if":1,"record":1,"functions":1,"perform":1}
,"filemaker":{"pro":1}
,"pro":{"10.0":1}
,"10.0":{"set":1}
,"create":{"calculation":1}
,"change":{"value":1}
,"literally":{"based":1}
,"based":{"second":1,"geographical":1}
,"second":{"calculation":1}
,"single":{"set":1}
,"multiple":{"set":1,"else":1}
,"if":{"conditions":1,"quotation":1,"field":1,"subsequent":1,"statement":1,"steps":1,"[credit":1,"single":1}
,"conditions":{"calculated":1}
,"return":{"text":1}
,"text":{"result":1}
,"quotation":{"marks":1}
,"marks":{"included":1}
,"included":{"qualified":1}
,"qualified":{"field":1}
,"named":{"field":1}
,"selected":{"browse":1}
,"browse":{"mode":1}
,"mode":{"find":1,"field":1}
,"find":{"mode":1}
,"doesn\u2019t":{"current":1}
,"layout":{"set":1}
,"ignores":{"validation":1}
,"validation":{"checking":1,"performed":1}
,"checking":{"set":1}
,"active":{"leaves":1,"record":1}
,"leaves":{"active":1}
,"exited":{"committed":1}
,"committed":{"scripts":1,"identifies":1}
,"scripts":{"use":1,"set":1}
,"use":{"series":1,"set":1}
,"series":{"set":1}
,"steps":{"group":1,"if":1,"record":1,"determine":1}
,"group":{"steps":1}
,"subsequent":{"set":1}
,"lock":{"record":1}
,"download":{"upload":1}
,"upload":{"data":1}
,"data":{"index":1}
,"index":{"field":1}
,"each":{"individual":1}
,"individual":{"set":1}
,"functions":{"record-level":1}
,"record-level":{"validation":1}
,"performed":{"record":1}
,"identifies":{"target":1}
,"national":{"statistics":1}
,"statistics":{"statistics":1,"based":1,"customers":1,"sum":1}
,"geographical":{"location":1}
,"location":{"enters":1,"=\u0022":1,"&\u0022":1}
,"enters":{"calculated":1}
,"sum":{"all":1,"invoices":1}
,"all":{"grand":1}
,"grand":{"totals":1}
,"totals":{"target":1}
,"[if":{"customers":1}
,"customers":{":country":1,":national":1,":world":1,"table":1}
,":country":{"=\u0022":1}
,"=\u0022":{"japan":1,"\u0022]":1,"set":1,"mobile":1}
,"japan":{"customers":1}
,":national":{"statistics":1}
,":world":{"statistics":1}
,"invoices":{":grand":1}
,":grand":{"total":1}
,"total":{")]":1}
,")]":{"demonstrates":1}
,"demonstrates":{"use":1}
,"simplify":{"scripts":1}
,"statement":{"multiple":1}
,"else":{"if":1}
,"determine":{"field":1,"target":1}
,"table":{"update":1}
,"update":{"credit":1}
,"credit":{"collection":1}
,"collection":{":phone":1,":call":1}
,":phone":{"number":1,"number]":1}
,"number":{"if":1}
,"[credit":{"collection":1}
,":call":{"location":1}
,"\u0022]":{"set":1}
,"[customers":{":work":1,":home":1,":mobile":1}
,":work":{"phone":1}
,"phone":{"credit":1}
,"number]":{"else":1,"end":1,"replacing":1}
,":home":{"phone":1}
,"mobile":{"set":1}
,":mobile":{"phone":1}
,"end":{"if":1}
,"perform":{"task":1}
,"task":{"by":1}
,"[getfieldname":{"evaluate":1}
,"evaluate":{"credit":1}
,"&\u0022":{"phone":1}
,"replacing":{"contents":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
