var pairs =
{
"save":{"copy":1,"dialog":1}
,"copy":{"aves":1,"current":1,"se":1,"file":1,"single":1,"create":1,"clone":1,"empty":1,"[copy":1,"[clone":1}
,"aves":{"copy":1,"complete":1,"compacted":1}
,"current":{"file":1,"database":1}
,"file":{"output":1,"allows":1,"paths":1,"open":1,"attachment":1,"attached":1,"filemaker":1,"displays":1,"opy":1,"aves":1,"compacted":1,"clone":1,"records":1,"all":1,"create":1,"path":1,"osted":1,"container":1,"\u0022]":1}
,"output":{"file":1}
,"allows":{"name":1}
,"name":{"location":1}
,"location":{"copy":1}
,"se":{"creating":1}
,"creating":{"file":1}
,"paths":{"select":1}
,"select":{"automatically":1}
,"automatically":{"open":1}
,"open":{"file":1,"default":1}
,"default":{"application":1,"email":1}
,"application":{"create":1,"output":1}
,"create":{"email":1,"folders":1,"new":1}
,"email":{"file":1,"message":1,"application":1}
,"attachment":{"display":1}
,"display":{"new":1}
,"new":{"email":1,"folders":1}
,"message":{"user\u2019s":1}
,"user\u2019s":{"default":1}
,"attached":{"if":1}
,"if":{"file":1,"[get":1,"saving":1}
,"filemaker":{"pro":1,"go":1}
,"pro":{"advanced":1,"6.0":1}
,"advanced":{"saves":1,"script":1}
,"saves":{"copy":1}
,"displays":{"save":1}
,"dialog":{"box":1,"[\u0022":1}
,"box":{"user":1}
,"user":{"copying":1}
,"copying":{"options":1,"files":1}
,"options":{"choose":1}
,"choose":{"save":1,"self-contained":1}
,"opy":{"current":1}
,"complete":{"copy":1}
,"compacted":{"copy":1}
,"clone":{"records":1,"current":1}
,"records":{"aves":1,"self-contained":1,"create":1}
,"self-contained":{"copy":1}
,"single":{"file":1}
,"all":{"container":1}
,"container":{"content":1,"objects":1}
,"content":{"embedded":1}
,"embedded":{"file":1,"copy":1}
,"folders":{"pecifies":1,"hat":1,"ption":1,"else":1,"off]":1}
,"pecifies":{"create":1}
,"hat":{"output":1}
,"path":{"filemaker":1}
,"6.0":{"earlier":1}
,"earlier":{"use":1}
,"use":{"script":1}
,"script":{"step":1}
,"step":{"back":1,"supported":1}
,"back":{"up":1}
,"up":{"file":1}
,"supported":{"current":1,"saves":1}
,"osted":{"filemaker":1}
,"go":{"choose":1}
,"objects":{"embedded":1}
,"ption":{"supported":1}
,"database":{"show":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"[\u0022":{"save":1}
,"empty":{"clone":1}
,"\u0022]":{"if":1}
,"[get":{"lastmessagechoice":1}
,"lastmessagechoice":{"=1]":1}
,"=1]":{"save":1}
,"[copy":{"current":1}
,"else":{"save":1}
,"[clone":{"records":1}
,"off]":{"end":1}
,"end":{"if":1}
,"saving":{"copying":1}
,"files":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
