var pairs =
{
"efining":{"field":1}
,"field":{"validation":1,"correctly":1,"choose":1,"define":1,"name":1,"dialog":1,"records":1,"record":1,"modified":1,"maximum":1,"stored":1,"display":1,"value":1,"auto-complete":1,"strict":1,"triggers":1,"commit":1,"filemaker":1}
,"validation":{"select":1,"options":1,"tab":1,"during":1,"instances":1,"warnings":1,"strict":1,"fails":1,"by":1,"global":1}
,"select":{"validation":1,"table":1,"existing":1,"allow":1,"numbers":1,"clear":1,"display":1}
,"options":{"ensure":1,"selected":1,"double-click":1,"field":1,"triggered":1}
,"ensure":{"data":1,"accuracy":1}
,"data":{"entered":1,"incorrectly":1,"field":1,"entry":1,"type":1}
,"entered":{"field":1,"select":1,"value":1}
,"correctly":{"validation":1}
,"selected":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"displays":1,"alculates":1,"validates":1}
,"displays":{"message":1}
,"message":{"if":1,"up":1}
,"if":{"enter":1,"database":1,"want":1,"field":1,"validation":1,"calculation":1,"validating":1}
,"enter":{"data":1,"value":1,"self":1,"number":1}
,"incorrectly":{"set":1}
,"set":{"option":1}
,"option":{"require":1,"field":1,"text":1}
,"require":{"users":1,"entered":1}
,"users":{"enter":1}
,"value":{"field":1,"select":1,"found":1,"matches":1,"value":1,"list":1,"lists":1,"match":1,"validated":1,"true":1,"values":1,"existing":1,"member":1,"choose":1}
,"choose":{"file":1,"ongoing":1,"numeric":1,"4-digit":1,"time":1,"value":1,"manage":1,"field":1}
,"file":{"menu":1,"size":1,"that\u2019s":1}
,"menu":{"manage":1}
,"manage":{"database":1,"value":1}
,"database":{"fields":1,"table":1}
,"fields":{"tab":1,"dialog":1,"by":1,"help":1}
,"tab":{"if":1,"validate":1}
,"table":{"select":1,"table":1,"list":1}
,"list":{"select":1,"date":1,"time":1,"blank":1,"member":1,"choose":1,"specific":1,"range":1}
,"existing":{"field":1,"value":1}
,"define":{"new":1}
,"new":{"options":1}
,"double-click":{"field":1}
,"name":{"options":1}
,"dialog":{"box":1}
,"box":{"validation":1,"select":1}
,"validate":{"data":1,"if":1}
,"ongoing":{"field":1}
,"during":{"data":1}
,"entry":{"limit":1,"setting":1,"validation":1}
,"limit":{"validation":1,"calculation":1}
,"instances":{"data":1}
,"allow":{"user":1}
,"user":{"override":1}
,"override":{"if":1,"validation":1}
,"want":{"user":1}
,"warnings":{"require":1}
,"numbers":{"strict":1,"dates":1}
,"strict":{"data":1}
,"type":{"choose":1,"validation":1,"values":1,"maximum":1,"message":1,"unique":1}
,"numeric":{"list":1,"values":1}
,"date":{"numeric":1,"list":1}
,"values":{"month":1,"hours":1,"matches":1,"match":1}
,"month":{"day":1}
,"day":{"digits":1,"list":1}
,"digits":{"year":1,"precision":1,"auto-complete":1}
,"year":{"5\u002F12\u002F201":1,"date":1}
,"5\u002F12\u002F201":{"strict":1}
,"4-digit":{"year":1}
,"time":{"numeric":1,"day":1}
,"hours":{"minutes":1}
,"minutes":{"00:00":1}
,"00:00":{"23:59":1}
,"23:59":{"seconds":1}
,"seconds":{"evaluated":1}
,"evaluated":{"data":1}
,"blank":{"empty":1}
,"empty":{"duplicate":1,"validated":1}
,"duplicate":{"value":1}
,"found":{"field":1}
,"records":{"unique":1}
,"unique":{"value":1}
,"matches":{"value":1,"result":1}
,"record":{"existing":1,"empty":1,"repeating":1}
,"member":{"value":1}
,"lists":{"create":1}
,"create":{"list":1}
,"specific":{"range":1}
,"range":{"letters":1,"type":1,"maximum":1}
,"letters":{"alphabetically":1}
,"alphabetically":{"numbers":1}
,"dates":{"times":1}
,"times":{"range":1}
,"result":{"calculation":1}
,"calculation":{"validated":1,"enter":1,"fields":1,"option":1,"evaluates":1,"return":1,"expected":1,"validation":1}
,"validated":{"by":1,"if":1}
,"by":{"calculation":1,"reference":1}
,"self":{"=<":1}
,"=<":{"match":1}
,"match":{"match":1,"expression":1,"ee":1,"evaluate":1}
,"expression":{"entered":1}
,"ee":{"defining":1}
,"defining":{"calculation":1}
,"clear":{"validate":1}
,"modified":{"exceed":1}
,"exceed":{"number":1,"file":1}
,"number":{"characters":1,"kilobytes":1,"digits":1}
,"characters":{"maximum":1,"type":1,"allowed":1,"if":1,"validation":1}
,"maximum":{"number":1}
,"allowed":{"exceed":1}
,"size":{"container":1,"file":1}
,"container":{"field":1}
,"kilobytes":{"enter":1,"setting":1}
,"setting":{"limits":1,"files":1,"up":1}
,"limits":{"size":1}
,"that\u2019s":{"embedded":1}
,"embedded":{"container":1}
,"stored":{"externally":1,"by":1}
,"externally":{"setting":1}
,"files":{"stored":1}
,"reference":{"container":1}
,"display":{"custom":1}
,"custom":{"message":1}
,"fails":{"select":1,"type":1}
,"up":{"255":1,"field":1}
,"255":{"characters":1}
,"evaluates":{"boolean":1}
,"boolean":{"value":1}
,"true":{"calculations":1,"default":1}
,"calculations":{"compare":1}
,"compare":{"value":1}
,"evaluate":{"true":1}
,"default":{"filemaker":1}
,"alculates":{"16":1}
,"16":{"digits":1}
,"precision":{"right":1}
,"right":{"decimal":1}
,"decimal":{"if":1}
,"validating":{"fields":1}
,"return":{"fractional":1}
,"fractional":{"use":1}
,"use":{"round":1}
,"round":{"function":1}
,"function":{"limit":1}
,"expected":{"number":1}
,"auto-complete":{"option":1,"during":1}
,"text":{"fields":1}
,"help":{"ensure":1}
,"accuracy":{"data":1}
,"triggered":{"exit":1,"commit":1}
,"exit":{"field":1}
,"commit":{"entire":1}
,"entire":{"record":1}
,"global":{"field":1}
,"triggers":{"exit":1}
,"repeating":{"field":1}
,"validates":{"each":1}
,"each":{"repetition":1}
,"repetition":{"individually":1}
,"individually":{"unique":1}
}
;Search.control.loadWordPairs(pairs);
