var pairs =
{
"calculation":{"dialog":1,"calculated":1,"context":1,"creating":1,"field":1,"if":1,"include":1,"pane":1,"result":1,"empty":1,"formulas":1}
,"dialog":{"box":1}
,"box":{"dialog":1,"appears":1,"defining":1,"filter":1,"change":1}
,"appears":{"build":1,"field":1,"functions":1,"list":1}
,"build":{"formula":1}
,"formula":{"calculation":1}
,"calculated":{"field":1}
,"field":{"if":1,"source":1,"build":1,"references":1,"typing":1,"name":1,"pane":1,"names":1,"set":1,"type":1,"repeating":1,"storage":1,"indexing":1}
,"if":{"evaluate":1,"calculation":1,"all":1}
,"evaluate":{"calculation":1,"if":1}
,"context":{"choose":1,"calculation":1,"calculations":1}
,"choose":{"table":1,"field":1,"function":1,"data":1,"correct":1,"ptions":1}
,"table":{"list":1,"two":1,"choose":1,"ist":1}
,"list":{"setting":1,"typing":1,"appears":1,"right":1,"fields":1,"view":1}
,"setting":{"context":1}
,"creating":{"calculation":1}
,"source":{"table":1}
,"two":{"occurrences":1}
,"occurrences":{"relationships":1}
,"relationships":{"graph":1}
,"graph":{"choice":1}
,"choice":{"affect":1}
,"affect":{"calculation":1}
,"include":{"fields":1}
,"fields":{"related":1,"prevent":1,"empty":1,"by":1,"fields":1,"global":1,"functions":1,"pane":1}
,"related":{"tables":1}
,"tables":{"use":1}
,"use":{"context":1}
,"calculations":{"choosing":1}
,"choosing":{"evaluation":1,"field":1}
,"evaluation":{"context":1}
,"references":{"operators":1}
,"operators":{"constant":1,"logical":1,"athematical":1,"text":1}
,"constant":{"values":1,"value":1}
,"values":{"functions":1}
,"functions":{"calculation":1,"pane":1,"fields":1,"displayed":1,"ane":1}
,"pane":{"cl":1,"double-click":1,"ee":1,"replace":1,"show\u002Fhide":1,"button":1,"functions":1,"type":1,"sort":1}
,"cl":{"ick":1}
,"ick":{"want":1,"operator":1}
,"want":{"item":1,"bout":1}
,"item":{"add":1}
,"add":{"re":1}
,"re":{"ference":1}
,"ference":{"field":1}
,"typing":{"field\u2019s":1,"field":1,"function":1}
,"field\u2019s":{"table":1}
,"name":{"choose":1,"list":1,"display":1,"function":1,"search":1}
,"double-click":{"ield":1,"function":1}
,"ield":{"name":1}
,"display":{"field":1}
,"names":{"choose":1}
,"ist":{"op":1}
,"op":{"erator":1}
,"erator":{"exponent":1}
,"exponent":{"type":1}
,"type":{"operator":1,"value":1,"result":1,"calculation":1,"calculated":1,"field":1}
,"operator":{"cl":1,"list":1}
,"right":{"calculation":1}
,"ee":{"comparison":1}
,"comparison":{"operators":1}
,"logical":{"operators":1}
,"athematical":{"operators":1}
,"text":{"operators":1}
,"value":{"type":1,"fu":1,"expression":1,"choose":1}
,"fu":{"nction":1}
,"nction":{"typing":1}
,"function":{"name":1,"calculation":1,"unction":1}
,"replace":{"placeholder":1}
,"placeholder":{"parameter":1}
,"parameter":{"value":1}
,"expression":{"alculation":1}
,"alculation":{"options":1}
,"options":{"field":1,"choose":1,"dialog":1,"defining":1}
,"set":{"field":1}
,"result":{"choose":1,"value":1,"want":1}
,"data":{"type":1}
,"correct":{"type":1}
,"bout":{"choosing":1}
,"repeating":{"umber":1,"fields":1}
,"umber":{"repetitions":1}
,"repetitions":{"ype":1,"defining":1}
,"ype":{"number":1}
,"number":{"repetitions":1}
,"defining":{"repeating":1,"field":1,"global":1}
,"prevent":{"calculation":1}
,"all":{"referenced":1,"fields":1}
,"referenced":{"fields":1}
,"empty":{"select":1,"enabled":1,"typically":1}
,"select":{"evaluate":1,"indexing":1}
,"enabled":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"evaluate":1,"define":1}
,"by":{"calculation":1}
,"typically":{"improves":1}
,"improves":{"performance":1}
,"performance":{"avoid":1}
,"avoid":{"confusion":1}
,"confusion":{"dates":1}
,"dates":{"filemaker":1,"two-digit":1}
,"define":{"calculation":1}
,"formulas":{"enter":1}
,"enter":{"four-digit":1}
,"four-digit":{"years":1}
,"years":{"entering":1,"select":1}
,"entering":{"dates":1}
,"two-digit":{"years":1}
,"indexing":{"storage":1,"options":1}
,"storage":{"options":1,"show":1}
,"ptions":{"storage":1}
,"global":{"fields":1,"storage":1}
,"show":{"hide":1}
,"hide":{"functions":1}
,"show\u002Fhide":{"functions":1}
,"button":{"calculation":1,"view":1}
,"filter":{"list":1}
,"search":{"box":1}
,"change":{"fields":1}
,"displayed":{"fields":1}
,"sort":{"button":1}
,"view":{"function":1,"help":1}
,"unction":{"functions":1}
,"ane":{"description":1}
,"description":{"appears":1}
,"help":{"button":1}
}
;Search.control.loadWordPairs(pairs);
