var pairs =
{
"finding":{"records":1}
,"records":{"based":1,"found":1,"match":1,"include":1}
,"based":{"criteria":1,"entire":1,"data":1}
,"criteria":{"single":1}
,"single":{"field":1}
,"field":{"perform":1,"selection":1,"browse":1,"entire":1,"use":1,"select":1,"find":1,"type":1}
,"perform":{"find":1}
,"find":{"based":1,"select":1,"right-click":1,"matching":1,"future":1,"request":1,"creates":1,"shortcut":1,"if":1,"records":1}
,"entire":{"field":1,"text":1}
,"selection":{"text":1,"shortcut":1}
,"text":{"field":1,"want":1,"if":1,"multiple":1,"choose":1}
,"browse":{"mode":1}
,"mode":{"field":1}
,"want":{"use":1}
,"use":{"find":1,"aving":1}
,"select":{"specific":1}
,"specific":{"text":1}
,"right-click":{"field":1}
,"shortcut":{"menu":1}
,"menu":{"choose":1,"find":1,"commands":1,"won\u2019t":1}
,"choose":{"find":1,"constrain":1}
,"matching":{"records":1}
,"found":{"set":1}
,"set":{"include":1,"requests":1,"field":1,"extend":1,"shortcut":1}
,"include":{"records":1,"order":1}
,"match":{"text":1}
,"if":{"text":1,"don\u2019t":1,"running":1}
,"multiple":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"performs":1}
,"performs":{"phrase":1}
,"phrase":{"search":1}
,"search":{"returning":1}
,"returning":{"records":1}
,"order":{"save":1}
,"save":{"find":1}
,"future":{"use":1}
,"aving":{"find":1}
,"request":{"performing":1,"deletes":1}
,"performing":{"find":1}
,"creates":{"new":1}
,"new":{"find":1}
,"deletes":{"existing":1}
,"existing":{"set":1}
,"requests":{"associated":1}
,"associated":{"current":1}
,"current":{"window":1}
,"window":{"quickly":1}
,"quickly":{"narrow":1}
,"narrow":{"broaden":1}
,"broaden":{"found":1}
,"constrain":{"found":1}
,"extend":{"found":1}
,"commands":{"disabled":1,"shortcut":1}
,"disabled":{"if":1}
,"don\u2019t":{"correct":1}
,"correct":{"privileges":1}
,"privileges":{"enter":1}
,"enter":{"field":1}
,"running":{"script":1}
,"script":{"paused":1}
,"paused":{"allowing":1}
,"allowing":{"preventing":1}
,"preventing":{"entry":1}
,"entry":{"fields":1}
,"fields":{"accounts":1,"container":1,"global":1,"commands":1}
,"accounts":{"privilege":1}
,"privilege":{"sets":1,"field":1}
,"sets":{"extended":1}
,"extended":{"privilege":1}
,"type":{"selected":1}
,"selected":{"support":1}
,"support":{"finds":1}
,"finds":{"summary":1}
,"summary":{"fields":1}
,"container":{"fields":1}
,"global":{"fields":1}
,"won\u2019t":{"find":1}
,"data":{"field":1}
}
;Search.control.loadWordPairs(pairs);
