var pairs =
{
"open":{"favorites":1,"last":1,"apps":1}
,"favorites":{"favorites":1,"window":1}
,"window":{"none":1,"closes":1,"include":1,"closing":1,"close":1,"[current":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"16.0":1,"advanced":1}
,"16.0":{"script":1}
,"script":{"step":1,"running":1}
,"step":{"choosing":1,"script":1}
,"choosing":{"file":1}
,"file":{"menu":1}
,"menu":{"apps":1}
,"apps":{"show":1,"windows":1,"window":1,"last":1,"managing":1}
,"show":{"apps":1}
,"windows":{"keep":1}
,"keep":{"filemaker":1}
,"advanced":{"open":1}
,"last":{"document":1,"step":1,"window":1}
,"document":{"window":1}
,"closes":{"by":1,"apps":1}
,"by":{"displaying":1}
,"displaying":{"apps":1}
,"include":{"open":1}
,"running":{"last":1}
,"closing":{"active":1}
,"active":{"document":1}
,"close":{"window":1}
,"[current":{"window]":1}
,"window]":{"open":1}
,"managing":{"files":1}
,"files":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
