var pairs =
{
"get":{"currentextend":1,"currentextendedprivileges":1,"accountextendedprivileges":1,"current":1,"active":1,"extended":1,"privileges":1}
,"currentextend":{"edprivileges":1}
,"edprivileges":{"returns":1}
,"returns":{"list":1,"extended":1,"empty":1,"value":1}
,"list":{"keywords":1,"separated":1,"if":1}
,"keywords":{"based":1,"list":1}
,"based":{"account":1,"context":1}
,"account":{"evaluate":1,"get":1,"evaluating":1}
,"evaluate":{"calculation":1}
,"calculation":{"enabled":1,"function":1,"privilege":1}
,"enabled":{"extended":1}
,"extended":{"privileges":1,"privilege":1,"priviliges":1}
,"privileges":{"get":1,"additional":1,"assigned":1,"account":1,"admin":1}
,"currentextendedprivileges":{"none":1,"returns":1,"fmwebdirect":1,"get":1}
,"none":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"keywords":1}
,"separated":{"by":1}
,"by":{"carriage":1}
,"carriage":{"returns":1}
,"additional":{"access":1}
,"access":{"assigned":1,"privileges":1,"via":1}
,"assigned":{"account\u2019s":1,"current":1}
,"account\u2019s":{"privilege":1}
,"privilege":{"set":1,"sets":1,"returns":1,"access":1}
,"set":{"accounts":1,"run":1,"includes":1}
,"accounts":{"privilege":1}
,"sets":{"extended":1}
,"empty":{"list":1}
,"if":{"user":1,"context":1,"logged":1}
,"user":{"doesn\u2019t":1}
,"doesn\u2019t":{"extended":1}
,"current":{"database":1,"calculation":1,"window":1,"extended":1}
,"database":{"file":1}
,"file":{"if":1}
,"context":{"current":1,"evaluated":1}
,"function":{"evaluated":1,"account":1}
,"evaluated":{"based":1}
,"window":{"if":1}
,"logged":{"running":1}
,"running":{"script":1}
,"script":{"set":1}
,"run":{"full":1}
,"full":{"access":1}
,"accountextendedprivileges":{"returns":1,"function":1}
,"admin":{"account":1}
,"evaluating":{"calculation":1}
,"includes":{"extended":1}
,"via":{"filemaker":1}
,"webdirect":{"keyword":1}
,"keyword":{"fmwebdirect":1}
,"fmwebdirect":{"position":1,"returns":1}
,"position":{"get":1}
,"value":{"greater":1}
,"greater":{"get":1}
,"active":{"extended":1}
,"priviliges":{"get":1}
}
;Search.control.loadWordPairs(pairs);
