var pairs =
{
"write":{"data":1,"file":1,"writes":1,"time":1,"larger":1,"utf-8":1}
,"data":{"file":1,"open":1,"source":1,"write":1,"option":1,"written":1,"read-write":1,"data":1,"script":1,"activity":1,"field":1,"filemaker":1}
,"file":{"writes":1,"file":1,"id":1,"open":1,"script":1,"write":1,"filemaker\u2019s":1,"filemaker":1,"overwritten":1,"position":1,"[file":1,"documents":1,"closes":1,"set":1,"exists":1,"[\u0022$file":1,"named":1,"contai":1,"2024-12-30":1,"[\u0022":1}
,"writes":{"data":1,"contents":1}
,"open":{"data":1}
,"id":{"numeric":1,"open":1,"write":1,"data":1,"$fileid":1}
,"numeric":{"expression":1}
,"expression":{"specifies":1}
,"specifies":{"file":1}
,"script":{"step":1,"runs":1}
,"step":{"data":1,"maximum":1,"write":1,"multiple":1}
,"source":{"field":1,"container":1,"set":1,"$variable":1,"activity":1,"table":1}
,"field":{"variable":1,"file":1,"specific":1,"12":1}
,"variable":{"data":1,"by":1,"[$file":1}
,"filemaker\u2019s":{"default":1}
,"default":{"utf-16":1}
,"utf-16":{"endian":1}
,"endian":{"character":1}
,"character":{"encoding":1,"end":1}
,"encoding":{"utf-8":1}
,"utf-8":{"if":1,"append":1,"close":1}
,"if":{"data":1,"doesn\u2019t":1,"[not":1,"open":1}
,"container":{"data":1}
,"option":{"ignored":1}
,"ignored":{"data":1}
,"written":{"binary":1,"file":1}
,"binary":{"append":1}
,"append":{"line":1}
,"line":{"feed":1}
,"feed":{"adds":1,"character":1,"utf-8-encoded":1,"checks":1,"close":1}
,"adds":{"line":1}
,"end":{"data":1,"if":1}
,"filemaker":{"pro":1}
,"pro":{"18.0":1,"advanced":1}
,"18.0":{"advanced":1}
,"advanced":{"data":1,"automating":1}
,"read-write":{"position":1}
,"position":{"file":1,"script":1,"[file":1,"write":1}
,"overwritten":{"by":1}
,"by":{"data":1,"line":1}
,"set":{"data":1,"variable":1}
,"maximum":{"data":1}
,"time":{"64":1,"performance":1}
,"64":{"mb":1,"kb":1}
,"mb":{"if":1,"perform":1,"each":1}
,"larger":{"64":1}
,"perform":{"script":1}
,"multiple":{"times":1}
,"times":{"writing":1}
,"writing":{"larger":1,"64":1}
,"each":{"time":1}
,"performance":{"writing":1}
,"kb":{"writes":1}
,"contents":{"variable":1}
,"utf-8-encoded":{"text":1}
,"text":{"open":1}
,"[file":{"id":1}
,"$variable":{"write":1}
,"checks":{"file":1}
,"documents":{"folder":1}
,"folder":{"named":1}
,"named":{"change.log":1,"dates.txt":1}
,"change.log":{"exists":1,"get":1}
,"exists":{"creates":1,"[\u0022$file":1}
,"creates":{"if":1}
,"doesn\u2019t":{"exist":1}
,"exist":{"writes":1}
,"activity":{":transaction":1}
,":transaction":{"field":1,"write":1}
,"closes":{"file":1}
,"[$file":{"value":1}
,"value":{"get":1}
,"get":{"documentspath":1,"file":1}
,"documentspath":{"&\u0022":1}
,"&\u0022":{"change.log":1}
,"[\u0022$file":{"target":1,"create":1}
,"target":{"$fileexists":1,"$fileid":1}
,"$fileexists":{"if":1,"create":1}
,"[not":{"$fileexists":1}
,"create":{"data":1,"folders":1}
,"folders":{"end":1}
,"$fileid":{"write":1,"data":1,"writes":1,"set":1,"new":1,"xporting":1}
,"close":{"data":1}
,"specific":{"position":1}
,"dates.txt":{"script":1,"target":1}
,"runs":{"file":1}
,"contai":{"ns":1}
,"ns":{"2024-11-3":1}
,"2024-11-3":{"nd":1}
,"nd":{"table":1}
,"table":{":month":1,":data":1}
,":month":{"field":1}
,"12":{"th":1}
,"th":{"script":1}
,"2024-12-30":{"open":1}
,"[\u0022":{"dates.txt":1}
,"new":{"position":1}
,":data":{"write":1}
,"xporting":{"data":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
