var pairs =
{
"rranging":{"objects":1}
,"objects":{"group":1,"change":1,"layout":1,"inspector":1,"align":1,"space":1,"forward":1,"located":1,"rotate":1,"use":1,"tab":1,"select":1,"bjects":1,"ou":1,"move":1}
,"group":{"align":1,"ungroup":1,"grouped":1,"ungrouping":1,"select":1,"change":1,"by":1}
,"align":{"distribute":1,"objects":1,"choose":1}
,"distribute":{"objects":1,"space":1}
,"change":{"stacking":1}
,"stacking":{"order":1}
,"order":{"rotate":1,"arrange":1,"panel":1,"objects":1,"bring":1,"send":1}
,"rotate":{"objects":1,"portals":1,"popover":1}
,"layout":{"mode":1}
,"mode":{"select":1}
,"select":{"objects":1,"group":1,"individual":1}
,"inspector":{"position":1}
,"position":{"position":1,"tab":1}
,"tab":{"button":1,"control":1,"controls":1,"objects":1}
,"button":{"arrange":1,"group":1,"original":1}
,"arrange":{"&align":1,"menu":1,"objects":1,"button":1}
,"&align":{"button":1}
,"ungroup":{"objects":1}
,"grouped":{"object":1}
,"object":{"if":1,"align":1,"moves":1}
,"if":{"single":1}
,"single":{"object":1}
,"choose":{"arrange":1}
,"menu":{"shortcut":1,"distribute":1,"move":1,"rotate":1}
,"shortcut":{"menu":1}
,"space":{"objects":1,"choose":1}
,"move":{"objects":1,"arrange":1}
,"forward":{"backward":1,"object":1,"stacking":1,"command":1}
,"backward":{"stacking":1,"object":1,"command":1}
,"located":{"tab":1}
,"control":{"slide":1,"popover":1}
,"slide":{"control":1,"controls":1}
,"popover":{"portal":1,"buttons":1}
,"portal":{"maintain":1,"select":1}
,"maintain":{"stacking":1}
,"panel":{"control":1}
,"portals":{"tab":1}
,"controls":{"slide":1,"web":1}
,"web":{"viewers":1}
,"viewers":{"popovers":1}
,"popovers":{"rotate":1}
,"buttons":{"choose":1}
,"ungrouping":{"select":1}
,"individual":{"objects":1}
,"use":{"objects":1}
,"bjects":{"tab":1}
,"ou":{"edit":1}
,"edit":{"text":1}
,"text":{"part":1,"objects":1}
,"part":{"group":1}
,"by":{"double-clicking":1}
,"double-clicking":{"text":1}
,"original":{"stacking":1}
,"bring":{"front":1,"forward":1}
,"front":{"object":1,"stacking":1,"command":1}
,"moves":{"front":1,"back":1,"forward":1,"backward":1}
,"command":{"send":1,"bring":1}
,"send":{"back":1,"backward":1}
,"back":{"object":1,"stacking":1,"command":1}
}
;Search.control.loadWordPairs(pairs);
