var pairs =
{
"find":{"matching":1}
,"matching":{"records":1,"current":1}
,"records":{"inds":1,"based":1,"match":1,"runs":1,"copied":1,"category":1,"[replace":1,"found":1,"[constrain":1,"[restore":1,"matching":1,"[extend":1}
,"inds":{"records":1}
,"based":{"context":1,"contents":1,"criteria":1}
,"context":{"field":1}
,"field":{"target":1,"specifies":1,"want":1,"constrain":1,"logical":1,"letting":1,"filemaker":1,"active":1,"if":1,"script":1,"data":1,"automating":1}
,"target":{"field":1}
,"specifies":{"field":1}
,"want":{"search":1,"add":1}
,"search":{"by":1,"extend":1,"filemaker":1}
,"by":{"replace":1}
,"replace":{"searches":1}
,"searches":{"entire":1,"found":1,"based":1,"selected":1}
,"entire":{"database":1,"contents":1}
,"database":{"replaces":1,"mode":1}
,"replaces":{"current":1}
,"current":{"found":1,"record":1,"record\u0027s":1,"customer":1}
,"found":{"set":1}
,"set":{"records":1,"displays":1,"include":1,"customer":1,"first":1,"\u0022]":1}
,"match":{"contents":1,"criteria":1}
,"contents":{"active":1,"field":1}
,"active":{"field":1,"script":1}
,"constrain":{"searches":1}
,"displays":{"matching":1,"invalid":1}
,"logical":{"search":1}
,"extend":{"broadens":1}
,"broadens":{"found":1}
,"include":{"additional":1}
,"additional":{"records":1}
,"criteria":{"field":1,"single":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"12.0":1,"advanced":1}
,"12.0":{"finds":1}
,"finds":{"records":1,"all":1}
,"letting":{"create":1}
,"create":{"scripts":1}
,"scripts":{"behave":1}
,"behave":{"similarly":1}
,"similarly":{"shortcut":1}
,"shortcut":{"menu":1}
,"menu":{"table":1}
,"table":{"view":1}
,"view":{"if":1,"find":1,"[view":1}
,"if":{"field":1,"data":1,"database":1,"manually":1,"selection":1,"[get":1,"finding":1}
,"advanced":{"searches":1,"displays":1,"switches":1,"files":1}
,"script":{"runs":1,"find":1,"step":1}
,"runs":{"if":1,"filemaker":1,"browse":1}
,"data":{"selected":1,"if":1,"run":1}
,"selected":{"active":1,"data":1,"filemaker":1}
,"invalid":{"command":1}
,"command":{"alert":1}
,"alert":{"find":1}
,"browse":{"preview":1,"mode":1}
,"preview":{"modes":1}
,"modes":{"if":1}
,"mode":{"script":1,"running":1}
,"switches":{"browse":1,"table":1}
,"running":{"script":1}
,"copied":{"pasted":1}
,"pasted":{"imported":1}
,"imported":{"filemaker":1}
,"files":{"if":1}
,"manually":{"select":1}
,"select":{"field":1}
,"run":{"script":1}
,"step":{"filemaker":1,"performs":1,"finds":1}
,"webdirect":{"script":1,"use":1}
,"performs":{"if":1}
,"selection":{"select":1,"script":1}
,"use":{"et":1}
,"et":{"selection":1}
,"all":{"records":1}
,"category":{"current":1}
,"record":{"switches":1,"sorts":1,"new":1}
,"[replace":{"products":1,"invoices":1}
,"products":{":category]":1}
,":category]":{"view":1}
,"[view":{"table]":1}
,"table]":{"new":1}
,"new":{"window":1,"found":1}
,"window":{"invoices":1,"[style":1}
,"invoices":{"layout":1,"invoices":1,")]":1,":customer":1}
,"layout":{"finds":1,"invoices":1}
,"customer":{"id":1,"found":1}
,"id":{"current":1,"creates":1,"show":1}
,"sorts":{"new":1}
,"first":{"record":1}
,"[style":{"document":1}
,"document":{"layout":1}
,")]":{"find":1}
,"[constrain":{"invoices":1}
,":customer":{"id]":1}
,"id]":{"sort":1,"else":1,"end":1}
,"sort":{"records":1}
,"[restore":{"dialog":1}
,"dialog":{"off]":1,"[\u0022":1}
,"off]":{"go":1}
,"go":{"record\u002Frequest\u002Fpage":1}
,"record\u002Frequest\u002Fpage":{"[first]":1}
,"[first]":{"extends":1}
,"extends":{"found":1}
,"record\u0027s":{"customer":1}
,"creates":{"new":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"[\u0022":{"want":1}
,"add":{"current":1}
,"\u0022]":{"if":1}
,"[get":{"lastmessagechoice":1}
,"lastmessagechoice":{"=1":1}
,"=1":{"find":1}
,"[extend":{"invoices":1}
,"else":{"find":1}
,"end":{"if":1}
,"finding":{"records":1}
,"single":{"field":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
