var pairs =
{
"finding":{"text":1}
,"text":{"characters":1,"fields":1,"calculation":1,"result":1,"pronounced":1,"field":1,"middle":1,"string":1,"match":1,"constant":1}
,"characters":{"search":1,"chris":1,"characters":1,"=and":1,"match":1,"word":1,"including":1,"character":1,"text":1,"display":1,"note":1,"row":1,"*for":1,"jo*n":1,"punctuation":1,"find":1,"literal":1,"japanese-indexed":1,"japanese":1,"perform":1}
,"search":{"text":1,"digits":1,"tilde":1}
,"fields":{"type":1,"return":1,"use":1,"characters":1,"perform":1,"backslash":1}
,"type":{"text":1,"field":1,"\u005Cand":1,"\u005Cthen":1}
,"calculation":{"fields":1,"field":1}
,"return":{"text":1,"browse":1,"field":1,"tab":1,"accented":1}
,"result":{"start":1}
,"start":{"find":1,"specific":1,"japanese":1,"literal":1}
,"find":{"request":1,"type":1,"character":1,"operators":1,"mode":1,"text":1,"status":1,"requests":1}
,"request":{"aking":1,"find":1,"includes":1}
,"aking":{"find":1}
,"field":{"examples":1,"invalid":1,"digit":1,"copy":1,"==(":1,"content":1,"differentiating":1,"by":1,"unicode":1,"sorts":1,"sort":1,"formula":1,"want":1,"indexing":1}
,"examples":{"start":1}
,"specific":{"roman":1}
,"roman":{"haracters":1}
,"haracters":{"fields":1}
,"use":{"language":1,"*to":1}
,"language":{"except":1,"field":1}
,"except":{"japanese":1}
,"japanese":{"characters":1,"hi":1,"text":1,"hiragana":1,"katakana":1,"half-width":1}
,"chris":{"smith":1,"chris":1,"smithson":1,"christopher":1}
,"smith":{"finds":1,"smith":1,"chris":1,"christenson":1,"==john":1,"john":1}
,"finds":{"chris":1,"japanese":1,"marten":1,"all":1,"springville":1,"gray":1,"don":1,"30":1,"53":1,"jon":1,"jr":1,"@(":1,"records":1,"spaces":1,"joey":1,"email":1,"\u00F2pera":1,"johnson":1,"john":1,"market":1,"case":1,"field":1,"change":1}
,"smithson":{"smith":1,"contain":1}
,"christenson":{"start":1}
,"hi":{"ragana":1,"ragana\u002Fka":1}
,"ragana":{"ka":1}
,"ka":{"takana":1,"nji":1,"na":1}
,"takana":{"ka":1,"vo":1}
,"nji":{"characters":1}
,"=and":{"*japanese":1}
,"*japanese":{"text":1}
,"pronounced":{"oda":1,"odayama":1,"odagawa":1,"kyoto":1,"tokyoto":1,"ha":1,"ba":1,"pa":1}
,"oda":{"equal":1,"japanese":1}
,"equal":{"sign":1,"signs":1}
,"sign":{"asterisk":1}
,"asterisk":{"finds":1}
,"odayama":{"japanese":1}
,"odagawa":{"phrase":1}
,"phrase":{"sequence":1,"word":1,"characters":1}
,"sequence":{"characters":1}
,"match":{"first":1,"phrase":1,"entire":1,"==john":1,"word":1,"contain":1}
,"first":{"characters":1}
,"word":{"match":1,"start":1,"==market":1}
,"literal":{"text":1}
,"including":{"spaces":1}
,"spaces":{"punctuation":1,"literal":1,"row":1,"double":1}
,"punctuation":{"double":1,"spaces":1}
,"double":{"quotation":1}
,"quotation":{"marks":1}
,"marks":{"marten":1,"\u0022@\u0022":1,"\u00F2pera":1,"finds":1,"use":1}
,"marten":{"jones":1,"interiors":1}
,"jones":{"interiors":1,"marten":1}
,"interiors":{"finds":1,"jones":1,"ltd":1}
,"ltd":{"finds":1,"name":1}
,"all":{"companies":1,"unknown":1}
,"companies":{"ltd":1}
,"name":{"comma":1}
,"comma":{"spring":1,"finds":1}
,"spring":{"finds":1}
,"springville":{"coldspring":1}
,"coldspring":{"harbor":1}
,"harbor":{"hotspring":1}
,"hotspring":{"unknown":1}
,"unknown":{"variable":1,"character":1,"characters":1}
,"variable":{"characters":1,"text":1}
,"character":{"wildcard":1,"@)":1,"gr@y":1,"search":1,"each":1,"special":1,"\u005Cfollowed":1,"carriage":1,"relaxed":1}
,"wildcard":{"character":1}
,"@)":{"each":1}
,"each":{"unknown":1,"digit":1}
,"gr@y":{"finds":1}
,"gray":{"grey":1}
,"grey":{"@on":1}
,"@on":{"finds":1}
,"don":{"ron":1}
,"ron":{"bron":1}
,"bron":{"invalid":1}
,"invalid":{"characters":1}
,"display":{"blank":1}
,"blank":{"characters":1}
,"note":{"find":1,"ormally":1}
,"digits":{"text":1}
,"digit":{"character":1,"finds":1}
,"30":{"finds":1,"300":1}
,"300":{"finds":1}
,"53":{"43":1}
,"43":{"zero":1}
,"zero":{"unknown":1,"characters":1}
,"row":{"zero":1,"character":1}
,"*for":{"all":1}
,"jo*n":{"finds":1}
,"jon":{"john":1}
,"john":{"j*r":1,"john":1,"smith":1,"smithers":1}
,"j*r":{"finds":1}
,"jr":{"junior":1}
,"junior":{"*phan*finds":1}
,"*phan*finds":{"phan":1}
,"phan":{"stephanie":1}
,"stephanie":{"s*finds":1}
,"s*finds":{"sophie":1}
,"sophie":{"steve":1}
,"steve":{"sven":1}
,"sven":{"operators":1}
,"operators":{"non-alphanumeric":1,"recognized":1}
,"non-alphanumeric":{"characters":1}
,"\u0022@\u0022":{"finds":1}
,"@(":{"email":1}
,"email":{"address":1}
,"address":{"finds":1,"joey@abc.net":1}
,"records":{"ontaining":1}
,"ontaining":{"comma":1}
,"special":{"meaning":1,"character":1,"characters":1}
,"meaning":{"invisible":1}
,"invisible":{"characters":1}
,"recognized":{"by":1}
,"by":{"filemaker":1,"special":1,"carriage":1,"japanese":1,"changing":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"escape":1}
,"escape":{"next":1}
,"next":{"character":1}
,"\u005Cfollowed":{"by":1}
,"carriage":{"return":1}
,"browse":{"mode":1}
,"mode":{"enter":1,"type":1}
,"enter":{"carriage":1}
,"copy":{"clipboard":1}
,"clipboard":{"find":1}
,"\u005Cand":{"paste":1}
,"paste":{"carriage":1}
,"tab":{"type":1,"windows":1}
,"\u005Cthen":{"press":1}
,"press":{"ctrl":1}
,"ctrl":{"tab":1}
,"windows":{"option-tab":1}
,"option-tab":{"macos":1}
,"macos":{"\u005C\u0022":1}
,"\u005C\u0022":{"joey\u005C\u0022":1}
,"joey\u005C\u0022":{"finds":1}
,"joey":{"joey\u005C@abc.net":1,"preceded":1}
,"joey\u005C@abc.net":{"finds":1}
,"joey@abc.net":{"\u005Cjoey":1}
,"\u005Cjoey":{"finds":1}
,"preceded":{"by":1}
,"accented":{"characters":1}
,"\u00F2pera":{"finds":1,"opera":1,"quotation":1}
,"opera":{"\u00F2pera":1,"partial":1}
,"partial":{"phrases":1}
,"phrases":{"sequence":1}
,"*to":{"find":1}
,"middle":{"text":1}
,"string":{"*\u0022":1}
,"*\u0022":{"son":1}
,"son":{"&phillips":1}
,"&phillips":{"finds":1,"paulson":1,"exact":1}
,"johnson":{"&phillips":1}
,"paulson":{"&phillips":1}
,"exact":{"matches":1}
,"matches":{"text":1,"match":1}
,"entire":{"field":1}
,"==(":{"two":1}
,"two":{"equal":1}
,"signs":{"field":1}
,"content":{"match":1}
,"==john":{"finds":1,"smith":1}
,"smithers":{"exact":1}
,"==market":{"finds":1}
,"market":{"market":1,"services":1,"marketing":1}
,"services":{"ongoing":1}
,"ongoing":{"market":1}
,"marketing":{"supermarket":1}
,"supermarket":{"=chris":1}
,"=chris":{"=smith":1}
,"=smith":{"finds":1}
,"christopher":{"smithson":1}
,"contain":{"japanese":1,"equivalent":1}
,"japanese-indexed":{"fields":1,"field":1}
,"kyoto":{"finds":1,"japanese":1,"fu":1}
,"tokyoto":{"japanese":1}
,"fu":{"kana":1}
,"kana":{"characters":1}
,"differentiating":{"hi":1}
,"ragana\u002Fka":{"takana":1}
,"vo":{"iced\u002Fse":1,"iced\u002Fun":1}
,"iced\u002Fse":{"mi-vo":1}
,"mi-vo":{"iced\u002Fun":1}
,"iced\u002Fun":{"voiced":1}
,"voiced":{"ka":1,"eration":1}
,"na":{"sm":1,"ka":1,"vo":1}
,"sm":{"all\u002Fre":1}
,"all\u002Fre":{"gular":1}
,"gular":{"ka":1}
,"eration":{"ma":1}
,"ma":{"rks":1}
,"rks":{"tilde":1}
,"tilde":{"character":1,"by":1}
,"relaxed":{"search":1}
,"hiragana":{"pronounced":1}
,"ha":{"finds":1,"japanese":1}
,"ba":{"japanese":1}
,"pa":{"japanese":1,"perform":1}
,"katakana":{"pronounced":1}
,"perform":{"find":1,"case-sensitive":1}
,"status":{"toolbar":1}
,"toolbar":{"note":1}
,"ormally":{"finds":1}
,"case":{"sensitive":1}
,"sensitive":{"width":1,"ind":1}
,"width":{"sensitive":1}
,"ind":{"request":1}
,"includes":{"japanese":1}
,"half-width":{"characters":1}
,"equivalent":{"full-width":1}
,"full-width":{"characters":1}
,"case-sensitive":{"width-sensitive":1}
,"width-sensitive":{"finds":1}
,"changing":{"default":1}
,"default":{"indexing":1}
,"indexing":{"sorting":1,"options":1}
,"sorting":{"language":1}
,"unicode":{"procedure":1,"order":1,"sort":1}
,"procedure":{"change":1}
,"change":{"order":1,"default":1}
,"order":{"field":1,"create":1}
,"sorts":{"if":1}
,"if":{"want":1}
,"want":{"original":1,"perform":1}
,"original":{"field":1}
,"sort":{"unicode":1,"fields":1}
,"create":{"calculation":1}
,"formula":{"simply":1}
,"simply":{"field":1}
,"requests":{"defining":1}
,"defining":{"field":1,"calculation":1}
,"options":{"defining":1}
,"backslash":{"special":1}
,"constant":{"find":1}
}
;Search.control.loadWordPairs(pairs);
