var pairs =
{
"get":{"window":1,"windowname":1}
,"window":{"name":1,"script":1,"window":1,"set":1,"title":1,"refreshed":1}
,"name":{"returns":1,"window":1,"et":1}
,"returns":{"name":1,"empty":1}
,"script":{"acting":1,"step":1}
,"acting":{"get":1,"foreground":1}
,"windowname":{"none":1,"teachers":1,"get":1}
,"none":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"7.0":1}
,"7.0":{"returns":1}
,"empty":{"string":1}
,"string":{"if":1}
,"if":{"window":1}
,"foreground":{"window":1}
,"set":{"window":1}
,"et":{"window":1}
,"title":{"script":1}
,"step":{"two":1}
,"two":{"windows":1}
,"windows":{"teachers":1}
,"teachers":{"students":1,"returned":1,"window":1}
,"students":{"displaying":1,"returned":1,"window":1}
,"displaying":{"layout":1}
,"layout":{"includes":1}
,"includes":{"unstored":1}
,"unstored":{"calculation":1}
,"calculation":{"field":1}
,"field":{"get":1}
,"returned":{"teachers":1,"students":1}
,"refreshed":{"students":1,"get":1}
}
;Search.control.loadWordPairs(pairs);
