var pairs =
{
"etting":{"text":1}
,"text":{"input":1,"text":1,"set":1}
,"input":{"method":1,"methods":1}
,"method":{"fields":1,"editor":1,"choose":1,"rom":1,"based":1,"last-used":1,"hiragana":1,"field":1}
,"fields":{"if":1,"set":1,"contain":1,"inspector":1}
,"if":{"operating":1}
,"operating":{"system":1}
,"system":{"configured":1}
,"configured":{"support":1}
,"support":{"input":1}
,"methods":{"entering":1,"fields":1,"software":1,"windows":1,"synchronize":1}
,"entering":{"text":1}
,"set":{"input":1,"text":1}
,"contain":{"japanese":1}
,"japanese":{"text":1,"filemaker":1,"input":1}
,"software":{"utilities":1}
,"utilities":{"convert":1}
,"convert":{"keystrokes":1}
,"keystrokes":{"characters":1}
,"characters":{"language":1}
,"language":{"japanese":1,"automatically":1,"storage":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"supports":1}
,"supports":{"japanese":1}
,"windows":{"macos":1}
,"macos":{"input":1}
,"editor":{"atok":1}
,"atok":{"kotoeri":1,"layout":1}
,"kotoeri":{"atok":1}
,"layout":{"mode":1}
,"mode":{"select":1}
,"select":{"fields":1}
,"inspector":{"data":1}
,"data":{"data":1,"tab":1}
,"tab":{"behavior":1,"options":1}
,"behavior":{"set":1}
,"choose":{"nput":1,"automatic":1}
,"nput":{"method":1}
,"rom":{"list":1}
,"list":{"choose":1}
,"automatic":{"input":1}
,"synchronize":{"field\u2019s":1}
,"field\u2019s":{"language":1}
,"automatically":{"set":1}
,"based":{"selected":1}
,"selected":{"language":1}
,"storage":{"tab":1}
,"options":{"field":1}
,"field":{"dialog":1,"japanese":1}
,"dialog":{"box":1}
,"box":{"roman":1}
,"roman":{"set":1}
,"last-used":{"ro":1}
,"ro":{"input":1}
,"hiragana":{"full-width":1}
,"full-width":{"katakana":1,"alphanumeric":1}
,"katakana":{"full-width":1,"half-width":1}
,"alphanumeric":{"half-width":1,"set":1}
,"half-width":{"katakana":1,"alphanumeric":1}
}
;Search.control.loadWordPairs(pairs);
