var pairs =
{
"close":{"data":1,"open":1,"all":1}
,"data":{"file":1,"files":1}
,"file":{"closes":1,"file":1,"id":1,"filemaker":1,"list":1,"ids":1,"[file":1,"sets":1,"[\u0022$file":1}
,"closes":{"open":1,"all":1,"file":1}
,"open":{"data":1}
,"id":{"numeric":1,"open":1,"parameter":1,"close":1,"closes":1,"\u0022*\u0022":1,"variable":1,"set":1,"$fileid":1}
,"numeric":{"expression":1}
,"expression":{"specifies":1}
,"specifies":{"file":1}
,"filemaker":{"pro":1}
,"pro":{"18.0":1,"advanced":1}
,"18.0":{"advanced":1}
,"advanced":{"use":1,"quits":1}
,"use":{"script":1,"get":1}
,"script":{"step":1}
,"step":{"close":1}
,"list":{"file":1}
,"ids":{"all":1}
,"all":{"currently":1,"open":1,"data":1}
,"currently":{"open":1}
,"files":{"use":1,"set":1,"closed":1,"close":1}
,"get":{"opendatafileinfo":1}
,"opendatafileinfo":{"function":1}
,"function":{"close":1}
,"set":{"file":1,"variable":1}
,"parameter":{"\u0022*\u0022":1}
,"\u0022*\u0022":{"asterisk":1,"file":1}
,"asterisk":{"surrounded":1}
,"surrounded":{"by":1}
,"by":{"double":1}
,"double":{"quotation":1}
,"quotation":{"marks":1}
,"marks":{"all":1}
,"closed":{"filemaker":1}
,"quits":{"closes":1}
,"[file":{"id":1}
,"sets":{"file":1}
,"variable":{"reads":1,"[$file":1}
,"reads":{"entire":1}
,"entire":{"file":1}
,"[$file":{"value":1}
,"value":{"data.txt":1}
,"data.txt":{"open":1}
,"[\u0022$file":{"target":1}
,"target":{"$fileid":1,"table":1}
,"$fileid":{"read":1,"bytes":1,"automating":1}
,"read":{"data":1,"utf-8":1}
,"bytes":{"target":1}
,"table":{":data":1}
,":data":{"read":1}
,"utf-8":{"close":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
