var pairs =
{
"filemaker":{"pro":1,"documentation":1,"community":1,"users":1}
,"pro":{"advanced":1,"18":1}
,"advanced":{"basics":1,"databases":1,"commands":1,"resource":1,"explore":1}
,"basics":{"description":1,"filemaker":1}
,"description":{"new":1}
,"new":{"features":1}
,"features":{"filemaker":1}
,"18":{"dvanced":1}
,"dvanced":{"introduction":1}
,"introduction":{"filemaker":1}
,"databases":{"modes":1}
,"modes":{"basics":1}
,"commands":{"files":1}
,"files":{"choose":1}
,"choose":{"help":1}
,"help":{"menu":1}
,"menu":{"get":1}
,"get":{"quick":1,"downloads":1}
,"quick":{"access":1}
,"access":{"additional":1}
,"additional":{"filemaker":1,"learning":1,"resources":1}
,"resource":{"center":1}
,"center":{"watch":1,"viewing":1}
,"watch":{"instructional":1}
,"instructional":{"videos":1}
,"videos":{"filemaker":1}
,"explore":{"online":1}
,"online":{"library":1,"forum":1,"knowledge":1}
,"library":{"offers":1}
,"offers":{"links":1}
,"links":{"tutorials":1}
,"tutorials":{"training":1}
,"training":{"electronic":1}
,"electronic":{"documentation":1}
,"documentation":{"product":1,"display":1,"center":1,"filemaker":1}
,"product":{"documentation":1}
,"display":{"product":1}
,"viewing":{"downloading":1}
,"downloading":{"additional":1}
,"community":{"collaborate":1}
,"collaborate":{"filemaker":1}
,"users":{"online":1}
,"forum":{"access":1}
,"learning":{"resources":1}
,"resources":{"service":1,"filemaker":1}
,"service":{"support":1}
,"support":{"search":1}
,"search":{"online":1}
,"knowledge":{"base":1}
,"base":{"get":1}
,"downloads":{"updates":1}
,"updates":{"additional":1}
}
;Search.control.loadWordPairs(pairs);
