var pairs =
{
"textdecode":{"returns":1,"container":1,"table":1}
,"returns":{"text":1,"textdecode":1,"utf-16le-encoded":1}
,"text":{"decoded":1,"data":1,"filemaker":1,"file":1,"utf-16le":1,"windows":1}
,"decoded":{"container":1}
,"container":{"data":1,"encoding":1,"-any":1,"field":1,"text":1}
,"data":{"character":1,"encoding":1}
,"character":{"encoding":1}
,"encoding":{"textdecode":1,"container":1,"-the":1,"text":1,"filemaker":1,"parameter":1}
,"-any":{"container":1}
,"field":{"encoded":1,"character":1,"text":1}
,"encoded":{"text":1}
,"-the":{"name":1}
,"name":{"character":1}
,"filemaker":{"pro":1,"encoding":1}
,"pro":{"16.0":1}
,"16.0":{"converts":1}
,"converts":{"text":1}
,"file":{"container":1}
,"utf-16le":{"encoding":1}
,"parameter":{"use":1}
,"use":{"values":1}
,"values":{"defined":1}
,"defined":{"textencode":1}
,"textencode":{"function":1}
,"function":{"function":1,"supported":1}
,"supported":{"runtime":1}
,"runtime":{"solutions":1}
,"solutions":{"returns":1}
,"table":{":container":1}
,":container":{"windows-1252":1}
,"windows-1252":{"returns":1}
,"utf-16le-encoded":{"text":1}
,"windows":{"character":1}
}
;Search.control.loadWordPairs(pairs);
