var pairs =
{
"yearname":{"returns":1,"date":1,"datefield":1}
,"returns":{"japanese":1}
,"japanese":{"year":1,"text":1}
,"year":{"name":1}
,"name":{"date":1,"emperor":1,"occurring":1}
,"date":{"format":1,"-any":1,"listed":1}
,"format":{"yearname":1,"date":1,"-a":1,"text":1,"blank":1,"meiji":1,"taisho":1,"showa":1,"heisei":1,"seireki":1,"mei":1,"tai":1,"sho":1,"hei":1,"xxxx":1}
,"-any":{"calendar":1}
,"calendar":{"date":1}
,"-a":{"number":1}
,"number":{"describes":1}
,"describes":{"display":1}
,"display":{"format":1}
,"text":{"filemaker":1,"emperor":1,"year":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"if":1}
,"if":{"value":1}
,"value":{"format":1}
,"blank":{"-japanese":1}
,"-japanese":{"text":1}
,"emperor":{"meiji":1,"taisho":1,"showa":1,"heisei":1,"seireki":1,"=long":1}
,"meiji":{"format":1,"japanese":1,"abbreviated":1}
,"taisho":{"format":1,"japanese":1,"abbreviated":1}
,"showa":{"format":1,"japanese":1,"abbreviated":1}
,"heisei":{"format":1,"japanese":1,"abbreviated":1}
,"seireki":{"format":1,"xxxx":1,"abbreviated":1,"returned":1}
,"xxxx":{"[before":1,"sei":1}
,"[before":{"1868.9.8]":1}
,"1868.9.8]":{"-japanese":1,"-m8":1}
,"abbreviated":{"format":1}
,"mei":{"japanese":1}
,"tai":{"japanese":1}
,"sho":{"japanese":1}
,"hei":{"japanese":1}
,"sei":{"xxxx":1}
,"-m8":{"t8":1}
,"t8":{"s8":1}
,"s8":{"h8":1}
,"h8":{"cex":1}
,"cex":{"xxx":1}
,"xxx":{"1868.9.8":1}
,"1868.9.8":{"name":1}
,"=long":{"=abbreviated":1}
,"=abbreviated":{"=2-byte":1}
,"=2-byte":{"roman":1}
,"roman":{"seireki":1}
,"returned":{"date":1}
,"listed":{"emperors":1}
,"emperors":{"yearname":1}
,"datefield":{"returns":1,"7\u002F15\u002F2008":1}
,"occurring":{"july":1}
,"july":{"15":1}
,"15":{"2008":1}
,"2008":{"datefield":1}
}
;Search.control.loadWordPairs(pairs);
