var pairs =
{
"extend":{"found":1}
,"found":{"set":1}
,"set":{"roadens":1,"current":1,"perform":1,"include":1,"\u0022]":1,"field":1,"[restore]":1,"automating":1}
,"roadens":{"existing":1}
,"existing":{"found":1}
,"current":{"stored":1}
,"stored":{"find":1}
,"find":{"requests":1,"request":1,"script":1,"mode":1}
,"requests":{"pecify":1}
,"pecify":{"fi":1}
,"fi":{"nd":1}
,"nd":{"re":1}
,"re":{"quests":1}
,"quests":{"llows":1}
,"llows":{"create":1}
,"create":{"store":1}
,"store":{"find":1}
,"request":{"script":1,"filemaker":1}
,"script":{"step":1}
,"step":{"restore":1,"equivalent":1,"extends":1}
,"restore":{"stored":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"script":1}
,"equivalent":{"logical":1}
,"logical":{"search":1}
,"search":{"extend":1}
,"perform":{"find":1}
,"extends":{"found":1}
,"include":{"unpaid":1}
,"unpaid":{"invoices":1,"\u0022]":1}
,"invoices":{"show":1,"found":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"dialog":{"[\u0022":1}
,"[\u0022":{"include":1}
,"\u0022]":{"if":1,"extend":1}
,"if":{"[get":1,"xtending":1}
,"[get":{"lastmessagechoice":1}
,"lastmessagechoice":{"=1]":1}
,"=1]":{"enter":1}
,"enter":{"find":1}
,"mode":{"[pause":1}
,"[pause":{"off]":1}
,"off]":{"set":1}
,"field":{"[invoices":1}
,"[invoices":{":status":1}
,":status":{"unpaid":1}
,"[restore]":{"end":1}
,"end":{"if":1}
,"xtending":{"broadening":1}
,"broadening":{"found":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
