var pairs =
{
"windows":{"want":1,"display":1,"script":1}
,"want":{"control":1}
,"control":{"flow":1}
,"flow":{"procedure":1}
,"procedure":{"tasks":1}
,"tasks":{"concurrently":1}
,"concurrently":{"window":1}
,"window":{"open":1,"based":1,"choose":1,"menu":1,"modify":1,"use":1,"displays":1,"create":1,"script":1}
,"open":{"time":1,"windows":1,"new":1,"window":1}
,"time":{"additional":1}
,"additional":{"open":1}
,"display":{"alerts":1}
,"alerts":{"prompt":1}
,"prompt":{"user":1}
,"user":{"provide":1}
,"provide":{"views":1}
,"views":{"data":1}
,"data":{"open":1}
,"new":{"document":1,"window":1}
,"document":{"window":1}
,"based":{"active":1}
,"active":{"window":1}
,"choose":{"window":1}
,"menu":{"new":1,"use":1}
,"modify":{"open":1}
,"use":{"commands":1,"windows":1}
,"commands":{"window":1}
,"script":{"steps":1,"includes":1,"step":1}
,"steps":{"open":1}
,"displays":{"layout":1}
,"layout":{"behaves":1}
,"behaves":{"current":1}
,"current":{"window":1}
,"create":{"script":1}
,"includes":{"new":1}
}
;Search.control.loadWordPairs(pairs);
