var pairs =
{
"manage":{"database":1}
,"database":{"keyboard":1,"dialog":1}
,"keyboard":{"shortcuts":1,"shortcut":1}
,"shortcuts":{"mac":1,"manage":1,"fields":1,"relationships":1}
,"mac":{"os":1}
,"os":{"use":1}
,"use":{"keyboard":1}
,"dialog":{"box":1}
,"box":{"use":1,"assign":1}
,"fields":{"tab":1}
,"tab":{"manage":1,"move":1}
,"assign":{"field":1}
,"field":{"type":1}
,"type":{"press":1,"characters":1,"percentage":1,"keyboard":1}
,"press":{"text":1,"move":1,"command":1,"add":1}
,"text":{"command":1,"specific":1,"note":1}
,"command":{"-t":1,"-n":1,"-d":1,"-i":1,"-m":1,"-r":1,"-l":1,"-s":1,"-g":1,"buttons":1,"drag":1,"-a":1,"-shift-a":1,"-y":1,"-u":1,"-shift-t":1,"-o":1,"-shift":1,"-shift-n":1,"-=note":1,"--(":1,"-e":1,"-shift-p":1,"command":1,"-z":1,"-shift-z":1}
,"-t":{"number":1,"press":1}
,"number":{"command":1}
,"-n":{"date":1,"change":1}
,"date":{"command":1}
,"-d":{"time":1,"own":1,"option":1}
,"time":{"command":1}
,"-i":{"timestamp":1,"page":1}
,"timestamp":{"command":1}
,"-m":{"container":1}
,"container":{"command":1}
,"-r":{"calculation":1,"ight":1,"edit":1,"choose":1}
,"calculation":{"command":1}
,"-l":{"summary":1,"eft":1}
,"summary":{"command":1}
,"-s":{"press":1}
,"move":{"selection":1,"selected":1}
,"selection":{"relationships":1,"incrementally":1,"object":1,"next":1,"pointer":1,"command":1,"cursor":1,"arrangement":1}
,"relationships":{"graph":1,"up":1,"selected":1}
,"graph":{"individually":1,"command":1,"type":1,"shortcuts":1}
,"individually":{"selecting":1}
,"selecting":{"tables":1,"table":1,"expanded":1}
,"tables":{"notes":1,"shift-click":1,"drag":1,"note":1,"press":1,"command":1,"related":1,"source":1,"selected":1}
,"notes":{"relationships":1,"command":1}
,"up":{"arrow":1}
,"arrow":{"arrow":1,"left":1,"right":1,"move":1,"shift":1,"option-down":1,"option-left":1,"option-right":1,"selecting":1,"option-shift-down":1,"option-shift-left":1,"option-shift-right":1}
,"left":{"arrow":1}
,"right":{"arrow":1}
,"incrementally":{"objects":1}
,"objects":{"shift":1,"share":1}
,"shift":{"-u":1,"-d":1,"-l":1,"-r":1}
,"-u":{"arrow":1,"toggle":1}
,"own":{"arrow":1}
,"eft":{"arrow":1}
,"ight":{"arrow":1}
,"object":{"includes":1,"option-up":1,"option-shift-up":1,"selection":1}
,"includes":{"text":1}
,"specific":{"characters":1}
,"characters":{"type":1,"note":1,"move":1,"switch":1}
,"note":{"if":1,"select":1,"command":1,"shift-click":1,"tool":1}
,"if":{"multiple":1}
,"multiple":{"objects":1,"tables":1}
,"share":{"initial":1}
,"initial":{"characters":1}
,"next":{"occurrence":1}
,"occurrence":{"by":1}
,"by":{"pressing":1,"dragging":1}
,"pressing":{"command":1}
,"-g":{"typing":1}
,"typing":{"characters":1}
,"switch":{"relationships":1}
,"buttons":{"tab":1}
,"selected":{"object":1,"table":1,"tables":1,"delete":1,"add":1,"command":1}
,"option-up":{"arrow":1}
,"option-down":{"arrow":1}
,"option-left":{"arrow":1}
,"option-right":{"arrow":1}
,"table":{"drag":1,"resize":1,"select":1,"command":1,"selected":1,"delete":1,"relationship":1}
,"drag":{"selected":1,"selection":1,"select":1,"duplicate":1,"choose":1}
,"resize":{"selected":1}
,"option-shift-up":{"arrow":1}
,"option-shift-down":{"arrow":1}
,"option-shift-left":{"arrow":1}
,"option-shift-right":{"arrow":1}
,"expanded":{"table":1}
,"select":{"multiple":1,"by":1,"all":1,"tables":1}
,"shift-click":{"multiple":1,"temporarily":1}
,"pointer":{"ultiple":1}
,"ultiple":{"tables":1}
,"dragging":{"completely":1}
,"completely":{"tables":1}
,"all":{"tables":1}
,"-a":{"select":1}
,"-shift-a":{"select":1}
,"related":{"currently":1}
,"currently":{"selected":1}
,"-y":{"select":1}
,"source":{"table":1}
,"toggle":{"display":1}
,"display":{"state":1,"percentage":1,"page":1}
,"state":{"selected":1}
,"add":{"table":1,"relationship":1,"text":1}
,"-shift-t":{"edit":1}
,"edit":{"table":1,"relationship":1}
,"-o":{"table":1,"relationship":1}
,"delete":{"table":1,"tables":1,"relationship":1,"relationships":1}
,"relationship":{"command":1,"selected":1,"delete":1,"selection":1}
,"-shift":{"-r":1}
,"-shift-n":{"drag":1}
,"duplicate":{"selection":1}
,"option":{"drag":1}
,"choose":{"keep":1}
,"keep":{"object":1,"magnification":1,"view":1,"note":1}
,"cursor":{"selected":1,"choose":1}
,"magnification":{"cursor":1}
,"-=note":{"shift-click":1}
,"temporarily":{"hooses":1,"ch":1}
,"hooses":{"view":1}
,"view":{"reduction":1}
,"reduction":{"cursor":1}
,"--(":{"hyphen":1}
,"hyphen":{"note":1}
,"ch":{"ooses":1}
,"ooses":{"magnification":1}
,"tool":{"selected":1}
,"change":{"display":1}
,"percentage":{"relationships":1,"value":1}
,"value":{"return":1}
,"return":{"snap":1}
,"snap":{"fit":1}
,"fit":{"command":1}
,"page":{"guides":1,"setup":1}
,"guides":{"command":1}
,"-e":{"display":1}
,"setup":{"options":1}
,"options":{"command":1}
,"-shift-p":{"undo":1}
,"undo":{"last":1}
,"last":{"command":1}
,"-z":{"red":1}
,"red":{"last":1}
,"-shift-z":{"field":1}
,"shortcut":{"table":1}
,"arrangement":{"shortcuts":1}
}
;Search.control.loadWordPairs(pairs);
