var pairs =
{
"iewing":{"applying":1}
,"applying":{"styles":1}
,"styles":{"layout":1,"styles":1,"tab":1,"list":1,"defined":1}
,"layout":{"layout":1,"mode":1,"background":1,"style":1,"ensure":1}
,"mode":{"select":1}
,"select":{"objects":1,"note":1,"layout":1,"show":1,"style":1}
,"objects":{"part":1,"parts":1}
,"part":{"label":1,"select":1,"set":1}
,"label":{"layout":1}
,"background":{"select":1,"ensure":1,"displayed":1,"style":1}
,"note":{"select":1}
,"ensure":{"objects":1,"body":1}
,"parts":{"selected":1}
,"selected":{"inspector":1,"layout":1}
,"inspector":{"styles":1}
,"tab":{"selected":1}
,"style":{"applied":1,"object":1,"styles":1,"layout":1,"shadows":1}
,"applied":{"layout":1}
,"displayed":{"styles":1}
,"list":{"display":1,"if":1}
,"display":{"all":1}
,"all":{"styles":1,"apply":1}
,"defined":{"current":1}
,"current":{"theme":1}
,"theme":{"select":1}
,"show":{"all":1}
,"apply":{"style":1}
,"object":{"part":1}
,"if":{"layout":1}
,"body":{"part":1}
,"set":{"transparent":1}
,"transparent":{"setting":1}
,"setting":{"fill":1}
,"fill":{"line":1}
,"line":{"style":1}
,"shadows":{"padding":1}
}
;Search.control.loadWordPairs(pairs);
