var pairs =
{
"textstyleadd":{"adds":1,"text":1,"plaid":1,"firstname":1,"textstyleadd":1,"statement":1,"titlefield":1,"function":1,"phrase":1}
,"adds":{"styles":1}
,"styles":{"text":1,"-any":1,"by":1,"removed":1,"styles":1,"case":1,"plain":1,"format":1,"concatenates":1,"let":1}
,"text":{"single":1,"styles":1,"-any":1,"expression":1,"field":1,"filemaker":1,"formatting":1,"use":1,"functions":1,"firstname":1,"italicizes":1}
,"single":{"action":1}
,"action":{"textstyleadd":1}
,"-any":{"text":1,"named":1}
,"expression":{"text":1}
,"field":{"styles":1,"type":1,"sophie":1}
,"named":{"style":1}
,"style":{"listed":1,"names":1,"plain":1,"use":1}
,"listed":{"description":1}
,"description":{"text":1}
,"filemaker":{"pro":1}
,"pro":{"7.0":1}
,"7.0":{"add":1}
,"add":{"multiple":1}
,"multiple":{"styles":1}
,"by":{"operator":1}
,"operator":{"style":1}
,"names":{"negative":1}
,"negative":{"values":1}
,"values":{"valid":1}
,"valid":{"all":1}
,"all":{"styles":1}
,"removed":{"if":1}
,"if":{"style":1,"mixed":1,"field":1}
,"plain":{"plain":1,"ignored":1,"bold":1,"italic":1}
,"ignored":{"if":1}
,"mixed":{"styles":1}
,"case":{"sensitive":1,"text":1}
,"sensitive":{"contain":1}
,"contain":{"spaces":1}
,"spaces":{"text":1}
,"formatting":{"options":1}
,"options":{"lost":1}
,"lost":{"if":1}
,"type":{"returned":1}
,"returned":{"text":1}
,"bold":{"italic":1,"underline":1,"underlined":1}
,"italic":{"underline":1,"returns":1,"calculation":1,"[\u0022":1}
,"underline":{"highlightyellow":1,"returns":1}
,"highlightyellow":{"condense":1}
,"condense":{"extend":1}
,"extend":{"strikethrough":1}
,"strikethrough":{"smallcaps":1}
,"smallcaps":{"superscript":1}
,"superscript":{"subscript":1}
,"subscript":{"uppercase":1}
,"uppercase":{"lowercase":1}
,"lowercase":{"titlecase":1}
,"titlecase":{"wordunderline":1,"bodystyle":1}
,"wordunderline":{"doubleunderline":1}
,"doubleunderline":{"allstyles":1}
,"allstyles":{"all":1}
,"format":{"change":1}
,"change":{"case":1,"style":1}
,"use":{"lower":1,"substitute":1}
,"lower":{"upper":1}
,"upper":{"proper":1}
,"proper":{"function":1}
,"function":{"text":1,"effective":1,"combined":1,"substitute":1}
,"functions":{"textstyleadd":1}
,"plaid":{"italic":1,"italics":1}
,"returns":{"word":1,"sophie":1}
,"word":{"plaid":1}
,"italics":{"textstyleadd":1}
,"firstname":{"bold":1,"field":1,"plain":1}
,"sophie":{"bold":1,"calculation":1}
,"underlined":{"text":1}
,"calculation":{"removes":1,"creates":1}
,"removes":{"all":1}
,"italicizes":{"entire":1}
,"entire":{"phrase":1}
,"phrase":{"textstyleadd":1,"italic":1,"bold":1}
,"creates":{"two":1}
,"two":{"descriptions":1,"phrases":1}
,"descriptions":{"styles":1}
,"concatenates":{"two":1}
,"phrases":{"styles":1}
,"let":{"function":1,"[\u00A0":1}
,"effective":{"avoid":1}
,"avoid":{"creating":1}
,"creating":{"complex":1}
,"complex":{"textstyleadd":1}
,"statement":{"let":1}
,"[\u00A0":{"titlestyle":1}
,"titlestyle":{"=smallcaps":1,"&\u0022":1}
,"=smallcaps":{"titlecase":1}
,"bodystyle":{"=plain":1,"find":1}
,"=plain":{"textstyleadd":1}
,"titlefield":{"titlestyle":1}
,"&\u0022":{"&textstyleadd":1}
,"&textstyleadd":{"bodyfield":1}
,"bodyfield":{"bodystyle":1}
,"find":{"occurrence":1}
,"occurrence":{"change":1}
,"substitute":{"function":1,"articlebody":1}
,"combined":{"textstyleadd":1}
,"articlebody":{"[\u0022":1}
,"[\u0022":{"phrase1":1,"phrase":1}
,"phrase1":{"textstyleadd":1}
}
;Search.control.loadWordPairs(pairs);
