var pairs =
{
"get":{"menubarstate":1}
,"menubarstate":{"returns":1,"none":1}
,"returns":{"number":1,"if":1,"menu":1}
,"number":{"representing":1,"filemaker":1}
,"representing":{"current":1}
,"current":{"menu":1}
,"menu":{"bar":1}
,"bar":{"state":1,"hidden":1,"visible":1,"unlocked":1}
,"state":{"get":1}
,"none":{"number":1}
,"filemaker":{"pro":1,"go":1,"webdirect":1}
,"pro":{"14.0":1,"advanced":1}
,"14.0":{"filemaker":1}
,"advanced":{"filemaker":1}
,"go":{"filemaker":1}
,"webdirect":{"returns":1,"menu":1}
,"if":{"menu":1}
,"hidden":{"unlocked":1,"locked":1}
,"unlocked":{"if":1,"returns":1}
,"visible":{"unlocked":1,"locked":1}
,"locked":{"if":1,"filemaker":1}
}
;Search.control.loadWordPairs(pairs);
