var pairs =
{
"inserting":{"current":1,"date":1}
,"current":{"date":1,"time":1,"user":1}
,"date":{"variables":1,"time":1,"page":1,"insert":1,"date":1,"number":1}
,"variables":{"field":1}
,"field":{"insert":1,"value":1,"current":1,"choose":1}
,"insert":{"current":1,"values":1,"menu":1}
,"time":{"user":1,"insert":1,"time":1,"number":1,"timestamp":1,"operating":1}
,"user":{"name":1,"easily":1}
,"name":{"field":1,"symbol":1,"insert":1,"preferences":1,"value":1,"user":1}
,"values":{"field":1,"dates":1}
,"value":{"change":1,"updates":1,"set":1}
,"change":{"change":1,"display":1,"user":1}
,"display":{"value":1}
,"updates":{"place":1,"records":1}
,"place":{"date":1}
,"symbol":{"layout":1}
,"layout":{"se":1,"browse":1}
,"se":{"inserting":1,"defining":1}
,"page":{"number":1}
,"number":{"variable":1,"text":1}
,"variable":{"layout":1}
,"browse":{"mode":1}
,"mode":{"field":1}
,"menu":{"choose":1,"items":1}
,"choose":{"menu":1,"current":1}
,"items":{"current":1}
,"text":{"timestamp":1,"field":1}
,"timestamp":{"field":1}
,"preferences":{"change":1,"filemaker":1,"current":1}
,"set":{"ting":1}
,"ting":{"general":1}
,"general":{"preferences":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"automatically":1,"insert":1}
,"automatically":{"enter":1}
,"enter":{"values":1,"account":1}
,"dates":{"times":1}
,"times":{"fields":1}
,"fields":{"record":1}
,"record":{"created":1}
,"created":{"updated":1}
,"updated":{"se":1}
,"defining":{"automatic":1}
,"automatic":{"data":1}
,"data":{"entry":1}
,"entry":{"if":1}
,"if":{"track":1}
,"track":{"creates":1}
,"creates":{"updates":1}
,"records":{"file":1}
,"file":{"protected":1}
,"protected":{"accounts":1}
,"accounts":{"secure":1}
,"secure":{"accurate":1}
,"accurate":{"method":1}
,"method":{"automatically":1}
,"account":{"name":1}
,"easily":{"change":1}
,"operating":{"system":1}
,"system":{"running":1}
,"running":{"filemaker":1}
}
;Search.control.loadWordPairs(pairs);
