var pairs =
{
"formatting":{"scaling":1}
,"scaling":{"chart":1}
,"chart":{"axe":1,"double-click":1,"layout":1,"inspector":1,"navigate":1,"set":1,"change":1,"select":1,"creating":1}
,"axe":{"reate":1}
,"reate":{"chart":1}
,"double-click":{"existing":1}
,"existing":{"chart":1}
,"layout":{"mode":1,"quick":1}
,"mode":{"chart":1,"charts":1,"decimal":1}
,"inspector":{"chart":1}
,"navigate":{"axis":1}
,"axis":{"options":1}
,"options":{"if":1,"displayed":1,"button":1,"axes":1,"print":1}
,"if":{"axis":1,"don\u2019t":1,"format":1}
,"displayed":{"axis":1,"positive\u002Fnegative":1}
,"button":{"display":1}
,"display":{"data":1,"options":1,"number":1}
,"data":{"value":1,"point":1,"points":1,"arithmetically":1,"exponentially":1,"values":1,"type":1,"format":1,"decimal":1,"series":1,"returned":1}
,"value":{"each":1,"zero":1,"frequency":1,"range":1}
,"each":{"data":1}
,"point":{"select":1,"labels":1,"ignored":1}
,"select":{"show":1,"linear":1,"logarithmic":1,"set":1}
,"show":{"data":1,"major":1,"minor":1}
,"points":{"chart":1}
,"set":{"display":1,"scale":1,"minimum":1,"maximum":1,"mid-point":1,"options":1}
,"axes":{"labels":1}
,"labels":{"x-axis":1,"label":1,"tick":1,"based":1}
,"x-axis":{"y-axis":1}
,"y-axis":{"radius":1}
,"radius":{"bubble":1}
,"bubble":{"chart":1}
,"change":{"angle":1}
,"angle":{"data":1,"enter":1,"control":1}
,"label":{"angle":1}
,"enter":{"value":1,"positive":1}
,"zero":{"90":1,"format":1,"99":1}
,"90":{"drag":1}
,"drag":{"angle":1}
,"control":{"angle":1,"set":1}
,"scale":{"tick":1,"choose":1}
,"tick":{"marks":1,"mark":1}
,"marks":{"scale":1,"if":1,"displayed":1}
,"choose":{"select":1,"field":1,"data":1}
,"linear":{"measure":1}
,"measure":{"data":1}
,"arithmetically":{"sales":1}
,"sales":{"growth":1}
,"growth":{"decline":1}
,"decline":{"select":1}
,"logarithmic":{"measure":1}
,"exponentially":{"sound":1}
,"sound":{"waves":1}
,"waves":{"measured":1}
,"measured":{"decibels":1}
,"decibels":{"earthquake":1}
,"earthquake":{"magnitudes":1}
,"magnitudes":{"tick":1}
,"mark":{"characteristics":1,"settings":1,"setting":1}
,"characteristics":{"select":1,"display":1}
,"major":{"ticks":1}
,"ticks":{"show":1,"enter":1}
,"minor":{"ticks":1}
,"frequency":{"labels":1}
,"don\u2019t":{"tick":1}
,"settings":{"tick":1,"applied":1}
,"setting":{"auto":1}
,"auto":{"estimated":1}
,"estimated":{"based":1}
,"based":{"data":1,"field":1}
,"values":{"chart":1}
,"minimum":{"set":1}
,"maximum":{"enter":1}
,"range":{"tick":1}
,"positive\u002Fnegative":{"charts":1}
,"charts":{"select":1,"layout":1,"finish":1,"creating":1}
,"mid-point":{"custom":1,"default":1,"zero":1}
,"custom":{"mid-point":1,"decimals":1}
,"default":{"mid-point":1}
,"format":{"labels":1,"characteristics":1,"applied":1}
,"field":{"type":1,"string":1}
,"type":{"data":1,"choose":1}
,"number":{"data":1,"fixed":1,"decimals":1}
,"decimal":{"percentage":1,"digits":1,"thousands":1}
,"percentage":{"currency":1}
,"currency":{"notes":1}
,"notes":{"custom":1}
,"decimals":{"separators":1,"set":1}
,"separators":{"ascii":1}
,"ascii":{"printable":1,"character":1}
,"printable":{"characters.the":1}
,"characters.the":{"tilde":1}
,"tilde":{"character":1}
,"character":{"allowed":1,"except":1}
,"allowed":{"decimal":1}
,"digits":{"zero":1}
,"99":{"enter":1}
,"positive":{"number":1}
,"fixed":{"number":1}
,"print":{"save":1}
,"save":{"layout":1}
,"quick":{"charts":1}
,"finish":{"chart":1}
,"creating":{"quick":1,"editing":1}
,"editing":{"charts":1}
,"thousands":{"characters":1}
,"characters":{"ascii":1}
,"except":{"hyphen":1}
,"hyphen":{"(-)":1}
,"(-)":{"if":1}
,"applied":{"data":1,"text":1}
,"series":{"incompatible":1}
,"incompatible":{"data":1}
,"returned":{"date":1}
,"date":{"settings":1,"data":1}
,"text":{"field":1}
,"string":{"date":1}
,"ignored":{"chart":1}
}
;Search.control.loadWordPairs(pairs);
