var pairs =
{
"view":{"isplays":1,"form":1,"list":1,"table":1,"next":1,"filemaker":1,"import":1,"[view":1,"depending":1}
,"isplays":{"data":1}
,"data":{"format":1}
,"format":{"view":1,"determined":1,"spreadsheet":1}
,"form":{"isplay":1,"else":1,"list":1}
,"isplay":{"records":1}
,"records":{"page":1,"records":1,"list":1,"screen":1,"viewed":1,"sorts":1,"[with":1,"[restore":1,"found":1,"form":1}
,"page":{"by":1,"format":1}
,"by":{"page":1,"database":1}
,"determined":{"by":1}
,"database":{"designer":1}
,"designer":{"view":1}
,"list":{"isplay":1,"browsed":1,"end":1,"table":1}
,"browsed":{"clicking":1}
,"clicking":{"backward":1}
,"backward":{"forward":1}
,"forward":{"buttons":1}
,"buttons":{"status":1}
,"status":{"toolbar":1}
,"toolbar":{"view":1}
,"table":{"isplay":1,"option":1,"view":1,"products":1,"performs":1,"automating":1}
,"screen":{"grid":1}
,"grid":{"fields":1}
,"fields":{"records":1}
,"viewed":{"time":1}
,"time":{"format":1}
,"spreadsheet":{"cycle":1}
,"cycle":{"switches":1}
,"switches":{"current":1,"table":1}
,"current":{"view":1}
,"next":{"view":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"6.0":1}
,"6.0":{"earlie":1}
,"earlie":{"filemaker":1}
,"webdirect":{"support":1}
,"support":{"view":1}
,"option":{"imports":1}
,"imports":{"records":1}
,"sorts":{"switches":1}
,"import":{"records":1}
,"[with":{"dialog":1}
,"dialog":{"table":1,"view":1}
,"products":{"source":1}
,"source":{"new":1}
,"new":{"product":1}
,"product":{"catalog.xlsx":1}
,"catalog.xlsx":{"worksheet":1}
,"worksheet":{"stock":1}
,"stock":{"add":1}
,"add":{"mac":1}
,"mac":{"roman":1}
,"roman":{"sort":1}
,"sort":{"records":1}
,"[restore":{"dialog":1}
,"[view":{"table":1,"form":1,"list":1}
,"performs":{"find":1}
,"find":{"view":1,"mode":1}
,"depending":{"number":1}
,"number":{"records":1}
,"found":{"set":1}
,"set":{"enter":1}
,"enter":{"find":1}
,"mode":{"[pause":1}
,"[pause":{"if":1}
,"if":{"[get":1,"viewing":1}
,"[get":{"foundcount":1}
,"foundcount":{"=1":1,"view":1}
,"=1":{"view":1}
,"else":{"if":1}
,"end":{"if":1}
,"viewing":{"records":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
