var pairs =
{
"textsizeremove":{"removes":1,"text":1,"10":1}
,"removes":{"all":1}
,"all":{"font":1,"text":1}
,"font":{"sizes":1,"sizetoremove":1,"size":1}
,"sizes":{"text":1}
,"text":{"font":1,"sizetoremove":1,"-any":1,"expression":1,"field":1,"filemaker":1,"default":1,"displays":1,"displayed":1,"formatting":1,"textsizeremove":1,"18":1,"returns":1}
,"sizetoremove":{"textsizeremove":1,"text":1,"-any":1,"font":1}
,"-any":{"text":1,"font":1}
,"expression":{"text":1}
,"field":{"sizetoremove":1,"if":1,"font":1,"type":1}
,"size":{"expressed":1,"field":1,"all":1,"set":1,"by":1,"removed":1,"portions":1,"font":1,"points":1,"textsizeremove":1}
,"expressed":{"integer":1}
,"integer":{"parameters":1}
,"parameters":{"braces":1}
,"braces":{"optional":1}
,"optional":{"text":1}
,"filemaker":{"pro":1}
,"pro":{"8.0":1}
,"8.0":{"use":1}
,"use":{"function":1}
,"function":{"revert":1}
,"revert":{"text":1}
,"default":{"font":1}
,"if":{"don\u2019t":1,"field":1}
,"don\u2019t":{"size":1}
,"displays":{"default":1}
,"set":{"layout":1}
,"layout":{"mode":1}
,"mode":{"field":1}
,"by":{"sizetoremove":1}
,"removed":{"portion":1,"18":1}
,"portion":{"text":1}
,"displayed":{"size":1,"field\u0027s":1,"field\u2019s":1}
,"portions":{"text":1}
,"field\u0027s":{"default":1}
,"points":{"72":1,"inch":1}
,"72":{"points":1}
,"inch":{"text":1}
,"formatting":{"options":1}
,"options":{"lost":1}
,"lost":{"if":1}
,"type":{"returned":1}
,"returned":{"text":1}
,"10":{"point":1}
,"point":{"text":1,"font":1}
,"18":{"point":1,"returns":1}
,"returns":{"10":1}
,"field\u2019s":{"default":1}
}
;Search.control.loadWordPairs(pairs);
