var pairs =
{
"ormatting":{"panel":1}
,"panel":{"controls":1,"choose":1,"slide":1,"layout":1,"control":1,"object":1}
,"controls":{"yo":1,"slide":1,"objects":1,"appearance":1}
,"yo":{"change":1}
,"change":{"appearance":1,"fill":1,"selecting":1,"style":1,"shape":1,"format":1,"width":1,"shadow":1,"dimensions":1}
,"appearance":{"tab":1,"appearance":1,"value":1}
,"tab":{"controls":1,"panels":1,"format":1,"panel":1,"control":1,"inspector":1,"choose":1,"hoose":1,"justification":1,"panel\u2019s":1,"width":1,"graphic":1,"select":1,"advanced":1,"padding":1}
,"slide":{"controls":1,"control":1,"panels":1,"panel":1}
,"objects":{"panels":1,"tab":1,"change":1,"panel":1}
,"panels":{"layout":1,"display":1,"dots":1,"slide":1,"objects":1,"left":1,"double-click":1,"formatting":1,"select":1,"ou":1,"inner":1}
,"layout":{"mode":1,"bar":1}
,"mode":{"addition":1,"select":1}
,"addition":{"format":1}
,"format":{"display":1,"component":1,"tab":1,"panel":1}
,"display":{"states":1,"state":1}
,"states":{"individual":1}
,"individual":{"tab":1,"slide":1}
,"state":{"object":1,"tab":1,"list":1}
,"object":{"components":1,"state":1,"type":1}
,"components":{"slide":1}
,"control":{"slide":1,"choose":1,"panels":1,"dots":1,"objects":1,"drag":1,"apply":1,"select":1,"appearance":1,"tab":1,"setup":1,"double-click":1,"advanced":1,"panel":1,"change":1}
,"dots":{"inspector":1,"object":1,"select":1,"patterns":1}
,"inspector":{"appearance":1,"choose":1}
,"choose":{"object":1,"slide":1,"fill":1,"line":1,"each":1,"tab":1,"options":1,"inches":1}
,"list":{"top":1}
,"top":{"tab":1,"ab":1}
,"component":{"slide":1}
,"type":{"list":1}
,"ab":{"change":1,"slide":1}
,"fill":{"frontmost":1,"graphic":1,"line":1,"all":1,"change":1,"color":1,"choose":1,"border":1}
,"frontmost":{"ab":1}
,"select":{"tab":1,"slide":1,"outer":1,"inner":1}
,"selecting":{"objects":1}
,"graphic":{"setting":1,"choose":1,"appearance":1,"select":1,"ppearance":1}
,"setting":{"fill":1}
,"line":{"style":1,"options":1}
,"style":{"shadows":1,"color":1,"border":1}
,"shadows":{"padding":1,"tab":1,"slide":1}
,"padding":{"illing":1,"change":1,"tab":1,"values":1}
,"illing":{"color":1}
,"color":{"gradient":1,"border":1,"style":1}
,"gradient":{"filling":1}
,"filling":{"ith":1}
,"ith":{"image":1}
,"image":{"apply":1}
,"apply":{"fill":1,"all":1,"outer":1}
,"all":{"tabs":1,"panels":1}
,"tabs":{"tab":1}
,"drag":{"arrow":1}
,"arrow":{"pointer":1}
,"pointer":{"selection":1}
,"selection":{"box":1}
,"box":{"surrounds":1,"choose":1}
,"surrounds":{"tab":1}
,"border":{"panel":1,"slide":1,"individual":1}
,"options":{"graphic":1,"formatting":1,"text":1,"tab":1,"choose":1}
,"formatting":{"bar":1,"formatting":1,"text":1}
,"bar":{"if":1,"formatting":1,"button":1,"setting":1,"text":1,"don\u2019t":1,"add":1}
,"if":{"don\u2019t":1}
,"don\u2019t":{"formatting":1}
,"button":{"layout":1,"change":1}
,"shape":{"corners":1}
,"corners":{"tab":1}
,"hoose":{"corner":1}
,"corner":{"radius":1,"want":1,"rounded":1}
,"radius":{"options":1}
,"each":{"corner":1}
,"want":{"rounded":1}
,"rounded":{"appearance":1,"place":1}
,"value":{"points":1,"corner":1,"change":1}
,"points":{"larger":1,"enter":1}
,"larger":{"value":1}
,"place":{"all":1}
,"left":{"center":1}
,"center":{"right":1}
,"right":{"spread":1}
,"spread":{"across":1}
,"across":{"tab":1}
,"double-click":{"tab":1}
,"setup":{"dialog":1}
,"dialog":{"box":1}
,"justification":{"change":1}
,"panel\u2019s":{"name":1}
,"name":{"select":1,"apply":1}
,"text":{"use":1,"options":1,"change":1}
,"use":{"text":1}
,"width":{"all":1,"label":1,"margin":1,"choose":1}
,"label":{"width":1}
,"margin":{"minimum":1}
,"minimum":{"fixed":1}
,"fixed":{"width":1}
,"inches":{"centimeters":1}
,"centimeters":{"points":1}
,"enter":{"value":1}
,"add":{"outer":1,"inner":1}
,"outer":{"shadows":1,"shadow":1}
,"advanced":{"graphic":1}
,"shadow":{"edit":1,"effects":1}
,"edit":{"button":1}
,"effects":{"add":1,"adjust":1}
,"inner":{"shadows":1,"shadow":1}
,"adjust":{"padding":1}
,"dimensions":{"select":1}
,"ppearance":{"appearance":1}
,"values":{"can\u2019t":1}
,"can\u2019t":{"change":1,"apply":1}
,"ou":{"can\u2019t":1}
,"patterns":{"format":1}
}
;Search.control.loadWordPairs(pairs);
