var pairs =
{
"get":{"accountn":1,"accountname":1,"account":1,"authentication":1}
,"accountn":{"returns":1}
,"returns":{"authenticated":1,"admin":1,"name":1,"account":1,"marketing":1}
,"authenticated":{"account":1}
,"account":{"name":1,"get":1,"[guest]":1,"authenticates":1,"by":1,"list":1,"first":1,"log":1,"getaccountname":1}
,"name":{"by":1,"authenticated":1,"appears":1,"listed":1,"entered":1,"case":1,"account":1,"get":1}
,"by":{"file\u0027s":1,"current":1,"authentication":1,"user":1}
,"file\u0027s":{"current":1}
,"current":{"user":1,"calculation":1,"window":1}
,"user":{"get":1,"default":1,"filemaker":1,"database":1,"belongs":1,"user":1,"logs":1,"enters":1}
,"accountname":{"none":1,"returns":1,"\u0027s":1,"get":1}
,"none":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1,"authentication":1}
,"pro":{"7.0":1,"advanced":1}
,"7.0":{"use":1}
,"use":{"function":1}
,"function":{"filemaker":1,"evaluated":1}
,"authentication":{"if":1,"order":1}
,"if":{"user":1,"individual":1,"context":1}
,"default":{"admin":1}
,"admin":{"account":1,"if":1}
,"advanced":{"guest":1,"if":1}
,"guest":{"account":1}
,"[guest]":{"returned":1}
,"returned":{"account":1}
,"authenticates":{"via":1}
,"via":{"external":1}
,"external":{"server":1}
,"server":{"oauth":1}
,"oauth":{"identity":1}
,"identity":{"provider":1}
,"provider":{"group":1}
,"group":{"credentials":1,"user":1,"name":1,"account":1}
,"credentials":{"get":1}
,"database":{"file":1}
,"file":{"group":1,"if":1}
,"belongs":{"group":1}
,"appears":{"account":1,"manage":1}
,"list":{"define":1}
,"define":{"accounts":1}
,"accounts":{"privileges":1}
,"privileges":{"filemaker":1,"determines":1}
,"individual":{"belongs":1}
,"first":{"group":1}
,"listed":{"choose":1}
,"choose":{"view":1}
,"view":{"by":1}
,"order":{"while":1}
,"while":{"defining":1}
,"defining":{"accounts":1}
,"determines":{"access":1}
,"access":{"user":1}
,"entered":{"by":1}
,"logs":{"account":1}
,"case":{"sensitive":1}
,"sensitive":{"get":1}
,"\u0027s":{"result":1}
,"result":{"identical":1}
,"identical":{"account":1}
,"manage":{"security":1}
,"security":{"dialog":1}
,"dialog":{"box":1}
,"box":{"if":1}
,"context":{"current":1,"evaluated":1}
,"calculation":{"function":1}
,"evaluated":{"based":1}
,"based":{"context":1}
,"window":{"returns":1}
,"marketing":{"marketing":1,"name":1,"logging":1,"account":1,"get":1}
,"log":{"database":1}
,"enters":{"marketing":1}
,"logging":{"marketing":1}
,"getaccountname":{"get":1}
}
;Search.control.loadWordPairs(pairs);
