var pairs =
{
"nserting":{"graphics":1}
,"graphics":{"layout":1,"gif":1,"data":1}
,"layout":{"layout":1,"mode":1,"editing":1,"parts":1,"background":1}
,"mode":{"choose":1,"right-click":1}
,"choose":{"insert":1,"graphic":1,"export":1}
,"insert":{"menu":1,"macos":1,"graphics":1}
,"menu":{"picture":1}
,"picture":{"fo":1}
,"fo":{"files":1}
,"files":{"type":1}
,"type":{"windows":1,"recommended":1}
,"windows":{"show":1,"insert":1}
,"show":{"macos":1}
,"macos":{"choose":1,"osition":1}
,"graphic":{"file":1,"layout":1,"each":1,"ou":1}
,"file":{"type":1,"reference":1,"disk":1,"select":1,"filemaker":1,"track":1,"if":1,"open":1,"images":1}
,"recommended":{"formats":1}
,"formats":{"graphics":1}
,"gif":{".gif":1}
,".gif":{"jpeg\u002Fjfif":1}
,"jpeg\u002Fjfif":{".jpg":1}
,".jpg":{"png":1}
,"png":{".png":1}
,".png":{"tiff":1}
,"tiff":{".tif":1}
,".tif":{"navigate":1}
,"navigate":{"graphic":1}
,"reference":{"file":1}
,"disk":{"select":1,"option":1}
,"select":{"store":1,"file":1}
,"store":{"reference":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"import":1,"file":1,"display":1}
,"import":{"graphic":1}
,"track":{"hard":1}
,"hard":{"disk":1}
,"option":{"reduce":1,"store":1}
,"reduce":{"size":1}
,"size":{"filemaker":1,"graphic":1}
,"if":{"move":1,"set":1}
,"move":{"delete":1}
,"delete":{"graphic":1}
,"display":{"select":1}
,"open":{"windows":1}
,"osition":{"size":1}
,"editing":{"objects":1}
,"objects":{"layout":1}
,"parts":{"layout":1}
,"background":{"insert":1}
,"data":{"container":1}
,"container":{"fields":1}
,"fields":{"graphic":1,"export":1}
,"each":{"record":1}
,"record":{"employee":1}
,"employee":{"photos":1,"directory":1}
,"photos":{"employee":1}
,"directory":{"database":1}
,"database":{"table":1}
,"table":{"data":1}
,"export":{"image":1,"graphic":1}
,"image":{"layout":1,"choose":1,"if":1}
,"right-click":{"image":1}
,"ou":{"can\u2019t":1}
,"can\u2019t":{"export":1}
,"set":{"option":1}
,"images":{"pictures":1}
,"pictures":{"photos":1}
}
;Search.control.loadWordPairs(pairs);
