var pairs =
{
"configure":{"region":1,"scripts":1}
,"region":{"monitor":1,"defined":1,"name":1,"optional":1,"region":1,"use":1,"monitors":1,"ios":1}
,"monitor":{"script":1,"specifies":1,"unique":1,"region":1,"existing":1,"canceled":1,"name":1,"uuid":1,"longitude":1,"radius":1,"value":1,"stop":1,"names":1,"monitor":1,"up":1,"associated":1}
,"script":{"onfigures":1,"run":1,"specifies":1,"parameter":1,"options":1,"step":1,"ios":1,"configured":1,"runs":1,"[monitor":1,"popartvideo":1}
,"onfigures":{"script":1}
,"run":{"ios":1,"script":1,"by":1}
,"ios":{"device":1,"version":1,"notifies":1}
,"device":{"enters":1,"ios":1,"entered":1}
,"enters":{"exits":1}
,"exits":{"region":1,"monitored":1,"defined":1,"range":1}
,"specifies":{"monitored":1,"name":1,"script":1,"universally":1,"value":1,"latitude":1,"longitude":1,"radius":1}
,"monitored":{"region":1}
,"defined":{"by":1,"region":1}
,"by":{"ibeacon":1,"geofence":1,"device":1,"region":1,"90":1,"180":1}
,"ibeacon":{"geofence":1,"if":1,"pop":1,"name":1}
,"geofence":{"use":1,"ibeacon":1,"latitude":1}
,"use":{"clear":1,"script":1,"ibeacons":1,"get":1}
,"clear":{"option":1,"all":1}
,"option":{"stop":1,"name":1}
,"stop":{"monitoring":1,"if":1}
,"monitoring":{"region":1}
,"name":{"specifies":1,"monitor":1,"each":1,"existing":1,"configured":1,"monitorname":1}
,"unique":{"name":1,"identifier":1}
,"each":{"monitor":1,"gallery":1,"time":1,"region":1}
,"if":{"name":1,"region":1,"value":1,"script":1}
,"existing":{"monitor":1}
,"canceled":{"new":1}
,"new":{"monitor":1}
,"configured":{"script":1,"each":1,"monitors":1,"correctly":1}
,"optional":{"script":1,"specifies":1}
,"parameter":{"specifies":1,"script":1}
,"options":{"ibeacons":1,"geofence":1,"missing":1}
,"ibeacons":{"uuid":1,"monitor":1,"specific":1,"all":1,"group":1,"toys":1,"galleries":1}
,"uuid":{"specifies":1,"identifies":1,"major":1,"ba37611e-fb73-4ffd-8fd3-63459d3ff280":1}
,"universally":{"unique":1}
,"identifier":{"ibeacons":1}
,"identifies":{"ibeacons":1}
,"specific":{"type":1,"organization":1,"branch":1,"ibeacons":1}
,"type":{"specific":1}
,"organization":{"ibeacons":1}
,"all":{"branches":1,"ibeacons":1,"active":1,"configured":1}
,"branches":{"department":1}
,"department":{"store":1}
,"store":{"share":1}
,"share":{"uuid":1,"major":1,"minor":1}
,"major":{"optional":1,"value":1,"10":1}
,"value":{"identifying":1,"major":1,"65535":1,"minor":1,"greater":1,"defined":1,"required":1,"latitude":1,"sign":1,"less":1,"longitude":1}
,"identifying":{"group":1,"specific":1}
,"group":{"ibeacons":1}
,"branch":{"department":1}
,"65535":{"minor":1,"options":1}
,"minor":{"optional":1,"value":1,"1]":1}
,"toys":{"specific":1}
,"latitude":{"specifies":1,"region":1,"range":1,"-i*90":1,"divided":1,"absolute":1}
,"longitude":{"specifies":1,"region":1,"range":1,"-i*180":1,"divided":1,"absolute":1}
,"radius":{"specifies":1,"meters":1}
,"meters":{"region":1}
,"greater":{"zero":1}
,"zero":{"less":1}
,"less":{"maximum":1,"90":1,"180":1}
,"maximum":{"value":1}
,"version":{"filemaker":1}
,"filemaker":{"pro":1,"go":1}
,"pro":{"16.0":1}
,"16.0":{"use":1}
,"step":{"run":1,"configured":1}
,"galleries":{"museum":1}
,"museum":{"configure":1}
,"scripts":{"provide":1}
,"provide":{"supplementary":1}
,"supplementary":{"audio":1}
,"audio":{"video":1}
,"video":{"content":1}
,"content":{"visitors":1}
,"visitors":{"approach":1}
,"approach":{"each":1}
,"gallery":{"stop":1,"configure":1}
,"names":{"clear":1}
,"active":{"region":1}
,"monitors":{"stopped":1,"window":1}
,"stopped":{"each":1}
,"time":{"device":1,"if":1}
,"notifies":{"filemaker":1}
,"go":{"determine":1,"displays":1}
,"determine":{"device":1}
,"entered":{"exited":1}
,"exited":{"region":1}
,"get":{"regionmonitorevents":1,"lastexternalerrordetail":1}
,"regionmonitorevents":{"function":1}
,"function":{"script":1,"errors":1}
,"up":{"20":1}
,"20":{"regions":1}
,"regions":{"time":1}
,"required":{"options":1}
,"missing":{"script":1}
,"associated":{"window":1}
,"window":{"displayed":1,"clears":1,"if":1}
,"displayed":{"script":1}
,"runs":{"closing":1,"popartvideo":1}
,"closing":{"window":1}
,"clears":{"all":1}
,"range":{"-90":1,"-180":1,"ibeacon":1}
,"-90":{"90":1}
,"90":{"returned":1,"if":1}
,"returned":{"value":1}
,"-i*90":{"quotient":1}
,"quotient":{"latitude":1,"longitude":1}
,"divided":{"by":1}
,"sign":{"latitude":1,"longitude":1}
,"absolute":{"value":1}
,"-180":{"180":1}
,"180":{"returned":1,"if":1}
,"-i*180":{"quotient":1}
,"correctly":{"filemaker":1}
,"displays":{"error":1}
,"error":{"use":1}
,"lastexternalerrordetail":{"function":1}
,"errors":{"receive":1}
,"receive":{"runs":1}
,"popartvideo":{"script":1,"uuid":1}
,"pop":{"art":1}
,"art":{"gallery":1}
,"[monitor":{"ibeacon":1}
,"monitorname":{"script":1}
,"ba37611e-fb73-4ffd-8fd3-63459d3ff280":{"major":1}
,"10":{"minor":1}
,"1]":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
