var pairs =
{
"check":{"record":1,"contents":1}
,"record":{"ses":1,"none":1,"started":1,"checking":1}
,"ses":{"spelling":1}
,"spelling":{"checker":1,"all":1,"automating":1}
,"checker":{"check":1}
,"contents":{"field":1}
,"field":{"current":1}
,"current":{"record":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"checks":1}
,"checks":{"spelling":1}
,"all":{"fields":1}
,"fields":{"current":1}
,"started":{"by":1}
,"by":{"onrecordcommit":1}
,"onrecordcommit":{"script":1}
,"script":{"trigger":1}
,"trigger":{"check":1}
,"checking":{"spelling":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
