var pairs =
{
"trigonometric":{"functions":1,"arc":1}
,"functions":{"trigonometric":1,"calculate":1,"use":1,"except":1}
,"calculate":{"degrees":1}
,"degrees":{"angles":1,"converts":1,"pi":1,"degrees":1,"function":1}
,"angles":{"geometric":1}
,"geometric":{"data":1}
,"data":{"function":1}
,"function":{"acos":1,"return":1,"greater":1}
,"acos":{"returns":1,"inverse":1}
,"returns":{"arccosine":1,"arcsine":1,"trigonometric":1,"cosine":1,"sine":1,"tangent":1}
,"arccosine":{"acos":1}
,"inverse":{"cosine":1,"sine":1,"tangent":1}
,"cosine":{"number":1,"cos":1}
,"number":{"asin":1,"atan":1,"cos":1}
,"asin":{"returns":1,"inverse":1}
,"arcsine":{"asin":1}
,"sine":{"number":1,"sin":1}
,"atan":{"returns":1,"inverse":1}
,"arc":{"tangent":1}
,"tangent":{"atan":1,"number":1,"tan":1}
,"cos":{"returns":1,"angleinradians":1}
,"angleinradians":{"degrees":1,"expressed":1,"all":1}
,"converts":{"angleinradians":1,"angleindegrees":1}
,"pi":{"calculates":1,"radians":1}
,"calculates":{"value":1}
,"value":{"constant":1}
,"constant":{"pi":1}
,"radians":{"converts":1,"sin":1,"tan":1,"unit":1,"degrees":1,"valid":1}
,"angleindegrees":{"radians":1}
,"sin":{"returns":1,"angleinradians":1}
,"expressed":{"radians":1}
,"tan":{"returns":1,"angleinradians":1}
,"all":{"trigonometric":1}
,"use":{"radians":1,"setprecision":1}
,"unit":{"measure":1}
,"measure":{"result":1}
,"result":{"convert":1}
,"convert":{"radians":1}
,"return":{"values":1}
,"values":{"all":1}
,"except":{"degrees":1}
,"valid":{"up":1}
,"up":{"15":1}
,"15":{"decimal":1}
,"decimal":{"if":1}
,"if":{"use":1}
,"setprecision":{"function":1}
,"greater":{"precision":1}
}
;Search.control.loadWordPairs(pairs);
