var pairs =
{
"orking":{"shared":1}
,"shared":{"files":1,"file":1}
,"files":{"client":1,"single":1,"actively":1}
,"client":{"client":1,"filemaker":1,"close":1,"comply":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"files":1,"ile":1}
,"single":{"user":1}
,"user":{"exceptions":1}
,"exceptions":{"open":1}
,"open":{"file":1,"host\u0027s":1}
,"file":{"layout":1,"define":1,"personalize":1,"records":1,"close":1,"client":1,"remains":1}
,"layout":{"found":1,"settings":1}
,"found":{"set":1}
,"set":{"sort":1,"prevents":1}
,"sort":{"order":1}
,"order":{"last":1}
,"last":{"time":1}
,"time":{"host":1}
,"host":{"closed":1,"perform":1}
,"closed":{"file":1}
,"define":{"script":1}
,"script":{"switch":1,"name":1}
,"switch":{"preferred":1}
,"preferred":{"layout":1}
,"settings":{"all":1}
,"all":{"users":1}
,"users":{"scripts":1,"access":1,"file":1}
,"scripts":{"saved":1}
,"saved":{"shared":1}
,"personalize":{"script":1}
,"name":{"if":1}
,"if":{"account\u2019s":1,"dialog":1}
,"account\u2019s":{"privilege":1}
,"privilege":{"set":1}
,"prevents":{"access":1}
,"access":{"layouts":1,"each":1,"records":1}
,"layouts":{"fields":1,"access":1,"delayed":1,"saved":1}
,"fields":{"can\u2019t":1}
,"can\u2019t":{"view":1}
,"view":{"layouts":1}
,"each":{"field":1}
,"field":{"field":1,"data":1}
,"data":{"network":1}
,"network":{"users":1}
,"records":{"layouts":1}
,"delayed":{"occasionally":1}
,"occasionally":{"users":1}
,"close":{"shared":1,"connection":1,"filemaker":1}
,"connection":{"file":1}
,"remains":{"open":1}
,"host\u0027s":{"computer":1}
,"computer":{"enhance":1}
,"enhance":{"computer\u0027s":1}
,"computer\u0027s":{"performance":1}
,"performance":{"close":1}
,"actively":{"if":1}
,"dialog":{"box":1}
,"box":{"requesting":1}
,"requesting":{"close":1}
,"ile":{"accessing":1}
,"accessing":{"client":1}
,"comply":{"host":1}
,"perform":{"maintenance":1}
}
;Search.control.loadWordPairs(pairs);
