var pairs =
{
"get":{"current":1,"currenttimeutcmilliseconds":1}
,"current":{"timeutcmilliseconds":1,"time":1}
,"timeutcmilliseconds":{"returns":1}
,"returns":{"current":1,"1:43:55.304":1}
,"time":{"coordinated":1,"utc":1,"filemaker":1,"time":1,"zone":1,"client-server":1,"takes":1}
,"coordinated":{"universal":1}
,"universal":{"time":1}
,"utc":{"nearest":1,"time":1,"08:43:55.304":1,"milliseconds":1}
,"nearest":{"millisecond":1}
,"millisecond":{"get":1}
,"currenttimeutcmilliseconds":{"none":1,")]":1,"\u002F1000":1,"get":1}
,"none":{"number":1}
,"number":{"time":1,"milliseconds":1}
,"filemaker":{"pro":1}
,"pro":{"13.0":1}
,"13.0":{"returns":1}
,"zone":{"adjustments":1,"time":1}
,"adjustments":{"form":1,"applied":1}
,"form":{"number":1}
,"milliseconds":{"1\u002F1\u002F0001":1}
,"1\u002F1\u002F0001":{"utc":1}
,"applied":{"return":1}
,"return":{"local":1}
,"local":{"time":1}
,"client-server":{"peer-to-peer":1}
,"peer-to-peer":{"environments":1}
,"environments":{"function":1}
,"function":{"evaluates":1}
,"evaluates":{"status":1}
,"status":{"client":1}
,"client":{"machine":1}
,"machine":{"running":1,"calculates":1}
,"running":{"script":1}
,"script":{"host":1,"set":1,"duration":1}
,"host":{"machine":1}
,"calculates":{"time":1,"local":1}
,"takes":{"find":1}
,"find":{"sort":1,"[restore]":1}
,"sort":{"records":1}
,"records":{"script":1,"[restore":1}
,"set":{"variable":1}
,"variable":{"[$start":1,"[$end":1}
,"[$start":{"get":1}
,")]":{"go":1,"show":1,"calculates":1}
,"go":{"layout":1}
,"layout":{"[\u0022":1}
,"[\u0022":{"invoices":1,"script":1}
,"invoices":{"\u0022]":1}
,"\u0022]":{"perform":1}
,"perform":{"find":1}
,"[restore]":{"sort":1}
,"[restore":{"dialog":1}
,"dialog":{"off]":1,"[\u0022":1}
,"off]":{"set":1}
,"[$end":{"get":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"duration":{"getastime":1}
,"getastime":{"$end":1,"getastimestamp":1}
,"$end":{"-$start":1}
,"-$start":{")]":1}
,"08:43:55.304":{"timeadjustment":1}
,"timeadjustment":{"-7":1}
,"-7":{"getastime":1}
,"getastimestamp":{"get":1}
,"\u002F1000":{"location":1}
,"location":{":timeadjustment":1}
,":timeadjustment":{"*3600":1}
,"*3600":{"returns":1}
,"1:43:55.304":{"pm":1}
,"pm":{"get":1}
}
;Search.control.loadWordPairs(pairs);
