var pairs =
{
"enter":{"preview":1}
,"preview":{"mode":1,"result":1}
,"mode":{"witches":1,"pause":1,"prints":1,"[pause":1}
,"witches":{"preview":1}
,"pause":{"temporarily":1}
,"temporarily":{"stops":1}
,"stops":{"script":1}
,"script":{"allow":1,"filemaker":1}
,"allow":{"users":1}
,"users":{"examine":1}
,"examine":{"preview":1}
,"result":{"proceeding":1}
,"proceeding":{"next":1}
,"next":{"step":1}
,"step":{"script":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1,"advanced":1}
,"6.0":{"earlier":1}
,"earlier":{"print":1}
,"print":{"invoices":1,"[with":1}
,"invoices":{"layout":1,"invoices":1,")]":1}
,"layout":{"new":1,"print":1}
,"new":{"window":1}
,"window":{"enters":1,"new":1,"[style":1,"[current":1}
,"enters":{"preview":1}
,"prints":{"closes":1}
,"closes":{"window":1}
,"[style":{"floating":1}
,"floating":{"document":1}
,"document":{"layout":1}
,")]":{"enter":1}
,"[pause":{"off]":1}
,"off]":{"print":1,"close":1}
,"[with":{"dialog":1}
,"dialog":{"off]":1}
,"close":{"window":1}
,"[current":{"window]":1}
,"window]":{"bout":1}
,"bout":{"filemaker":1}
,"advanced":{"modes":1}
,"modes":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
