var pairs =
{
"aming":{"runtime":1}
,"runtime":{"solution":1,"application":1,"database":1,"solutions":1,"name":1,"applications":1,"icons":1}
,"solution":{"note":1,"files":1,"machine":1,"file":1,"folder":1,"scripts":1,"during":1,"users":1}
,"note":{"feature":1,"creator":1}
,"feature":{"use":1}
,"use":{"advanced":1,"extension":1,"default":1,".fmpur":1,".fmp12":1}
,"advanced":{"tools":1,"nstalled":1,"document":1,"documents":1,"application":1}
,"tools":{"general":1,"filename":1}
,"general":{"preference":1}
,"preference":{"selected":1}
,"selected":{"ad":1}
,"ad":{"vanced":1}
,"vanced":{"tools":1}
,"filename":{"extension":1,"extensions":1}
,"extension":{"associates":1,"binding":1,"unique":1,".fmpur":1,"windows":1,"append":1,"filenames":1,"registers":1,"by":1,"all":1,"creator":1,"inserting":1,"fmpur":1,"filemaker":1,"runtime":1,"macos":1}
,"associates":{"all":1}
,"all":{"runtime":1,"files":1,"database":1,"filemaker":1}
,"files":{"runtime":1,"filenames":1,"use":1}
,"application":{"if":1,"started":1,"name":1,"windows":1,"starts":1,"creator":1,"restore":1,"open":1,"close":1,"restart":1}
,"if":{"user":1,"extension":1,"use":1}
,"user":{"runtime":1}
,"database":{"solution":1,"solutions":1,"filenames":1}
,"machine":{"filename":1}
,"binding":{"key":1,"process":1}
,"key":{"ensure":1}
,"ensure":{"correct":1,"macos":1}
,"correct":{"runtime":1}
,"started":{"solution":1}
,"file":{"double-clicked":1,"developer":1}
,"double-clicked":{"use":1}
,"unique":{"users":1,"ensure":1,"use":1,"registry":1}
,"users":{"computer":1,"filemaker":1}
,"computer":{"systems":1,"assigning":1}
,"systems":{"points":1}
,"points":{"naming":1}
,"naming":{"runtime":1}
,"solutions":{"runtime":1,"platforms":1,"assigning":1,"conflicts":1}
,"name":{"developer":1,"runtime":1,"new":1}
,"developer":{"utilities":1,"support":1}
,"utilities":{"name":1,"automatically":1,"append":1,"constructs":1}
,"new":{"solution":1,"filenames":1}
,"folder":{"bound":1}
,"bound":{"runtime":1}
,"filenames":{"include":1,"runtime":1,"start":1,"filemaker":1,"extension":1}
,"include":{"up":1}
,"up":{"31":1}
,"31":{"characters":1}
,"characters":{"choosing":1,"extension":1,"developer":1}
,"choosing":{"filenames":1}
,"platforms":{"runtime":1}
,"scripts":{"lookups":1,"external":1}
,"lookups":{"properly":1}
,"properly":{"use":1}
,"default":{"extension":1,"five-character":1}
,".fmpur":{"type":1,"five-character":1}
,"type":{"one-to":1}
,"one-to":{"five-character":1}
,"five-character":{"extension":1}
,"windows":{"filenames":1,"operating":1,"determine":1,"if":1,"solutions":1}
,"start":{"space":1}
,"space":{"developer":1}
,"automatically":{"update":1,"open":1}
,"update":{"all":1}
,"append":{"extension":1}
,"filemaker":{"data":1,"registered":1,"pro":1}
,"data":{"source":1}
,"source":{"references":1}
,"references":{"relationships":1}
,"relationships":{"scripts":1}
,"external":{"value":1}
,"value":{"lists":1}
,"lists":{"updated":1}
,"updated":{"interact":1}
,"interact":{"new":1}
,"registers":{"runtime":1}
,"operating":{"system":1}
,"system":{"extension":1}
,"by":{"windows":1,"technologies":1,"first":1}
,"determine":{"application":1,"difference":1}
,"starts":{"double-click":1}
,"double-click":{"solution":1}
,"during":{"binding":1}
,"process":{"macos":1}
,"macos":{"first":1,"nd":1,"determine":1,"solutions":1}
,"first":{"characters":1,"character":1}
,"creator":{"code":1,"codes":1}
,"code":{"runtime":1,"by":1,"stored":1,"creator":1,"choose":1,"apple":1}
,"technologies":{"macos":1}
,"nd":{"unique":1}
,"difference":{"runtime":1}
,"applications":{"creator":1}
,"stored":{"runtime":1}
,"codes":{"characters":1,"case":1,"registered":1,"if":1}
,"constructs":{"code":1}
,"inserting":{"uppercase":1}
,"uppercase":{"first":1}
,"character":{"default":1}
,"fmpur":{"ffmp":1}
,"ffmp":{"creator":1}
,"case":{"sensitive":1}
,"sensitive":{"note":1}
,"registered":{"apple":1,"ffmp":1}
,"apple":{"verify":1,"contact":1,"developer":1}
,"verify":{"creator":1}
,"choose":{"unique":1}
,"contact":{"apple":1}
,"support":{"visit":1}
,"visit":{"website":1}
,"website":{"eveloper.apple.com":1}
,"eveloper.apple.com":{"register":1}
,"register":{"creator":1}
,"registry":{"conflicts":1}
,"conflicts":{"windows":1,"non-unique":1}
,".fmp12":{"extension":1}
,"pro":{"advanced":1}
,"nstalled":{"hard":1}
,"hard":{"disks":1}
,"disks":{"all":1}
,"document":{"icons":1,"icon":1,"filemaker":1}
,"icons":{"change":1,"additionally":1,"original":1}
,"change":{"runtime":1}
,"additionally":{"filemaker":1}
,"documents":{"automatically":1}
,"open":{"filemaker":1,"document":1}
,"restore":{"document":1}
,"original":{"filemaker":1}
,"icon":{"discard":1}
,"discard":{"runtime":1}
,"close":{"exit":1}
,"exit":{"application":1}
,"restart":{"computer":1}
,"assigning":{"extension":1}
,"non-unique":{"filename":1}
,"extensions":{"windows":1}
}
;Search.control.loadWordPairs(pairs);
