var pairs =
{
"fieldids":{"eturns":1,"filename":1,"customers":1}
,"eturns":{"list":1}
,"list":{"all":1}
,"all":{"field":1,"unique":1}
,"field":{"ids":1,"fieldids":1}
,"ids":{"filename":1,"all":1}
,"filename":{"layoutname":1,"-the":1}
,"layoutname":{"fieldids":1,"filename":1,"-the":1}
,"-the":{"name":1}
,"name":{"open":1,"layout":1}
,"open":{"database":1}
,"database":{"file":1}
,"file":{"local":1,"text":1}
,"local":{"remote":1}
,"remote":{"layoutname":1}
,"layout":{"table":1,"returns":1,"customers":1}
,"table":{"database":1,"id":1,"customers":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"listed":1}
,"listed":{"items":1}
,"items":{"separated":1}
,"separated":{"by":1}
,"by":{"carriage":1}
,"carriage":{"returns":1}
,"returns":{"related":1,"ids":1}
,"related":{"fields":1,"field":1}
,"fields":{"returned":1,"default":1,"including":1,"layout":1}
,"returned":{"tableid":1}
,"tableid":{":relatedfieldid":1}
,":relatedfieldid":{"12":1}
,"12":{":4":1,"id":1}
,":4":{"12":1}
,"id":{"table":1,"related":1}
,"customers":{"returns":1,"fieldids":1,"layout":1}
,"unique":{"fields":1}
,"default":{"table":1}
,"including":{"related":1}
}
;Search.control.loadWordPairs(pairs);
