var pairs =
{
"dd":{"ing":1}
,"ing":{"slide":1}
,"slide":{"contro":1,"control":1,"panel":1}
,"contro":{"layout":1}
,"layout":{"mode":1,"want":1,"pop-up":1,"tools":1}
,"mode":{"choose":1}
,"choose":{"layout":1,"slide":1,"insert":1}
,"want":{"layout":1}
,"pop-up":{"menu":1}
,"menu":{"status":1,"drag":1}
,"status":{"toolbar":1}
,"toolbar":{"windows":1,"choose":1}
,"windows":{"arrow":1}
,"arrow":{"next":1}
,"next":{"tab":1}
,"tab":{"control":1}
,"control":{"tool":1,"drag":1,"macos":1,"ustomize":1,"changing":1,"add":1,"press":1,"setup":1,"portal":1,"popover":1}
,"tool":{"tab":1,"slide":1,"choose":1}
,"drag":{"crosshair":1,"objects":1}
,"crosshair":{"draw":1}
,"draw":{"slide":1}
,"macos":{"hold":1}
,"hold":{"tab":1}
,"ustomize":{"slide":1}
,"changing":{"slide":1}
,"add":{"objects":1}
,"objects":{"slide":1}
,"panel":{"use":1,"lick":1}
,"use":{"layout":1}
,"tools":{"status":1}
,"insert":{"menu":1}
,"lick":{"slide":1}
,"press":{"esc":1}
,"esc":{"close":1}
,"close":{"slide":1}
,"setup":{"dialog":1}
,"dialog":{"box":1}
,"box":{"place":1}
,"place":{"slide":1}
,"portal":{"place":1}
,"popover":{"portal":1}
}
;Search.control.loadWordPairs(pairs);
