var pairs =
{
"editing":{"ilemaker":1}
,"ilemaker":{"data":1,"file":1}
,"data":{"sources":1,"source":1}
,"sources":{"filemaker":1,"choose":1,"elect":1,"creating":1,"edit":1}
,"filemaker":{"data":1,"pro":1,"network":1,"files":1}
,"source":{"stores":1,"co":1,"list":1,"edit":1,"consist":1,"reference":1,"references":1}
,"stores":{"file":1}
,"file":{"paths":1,"add":1,"menu":1,"path":1,"file":1,"value":1}
,"paths":{"filemaker":1,"edited":1,"separated":1,"dialog":1,"slows":1,"edit":1}
,"pro":{"advanced":1}
,"advanced":{"searches":1}
,"searches":{"access":1}
,"access":{"table":1,"re-specify":1}
,"table":{"script":1}
,"script":{"value":1}
,"value":{"list":1}
,"list":{"ilemaker":1,"edit":1,"file":1,"dialog":1,"want":1,"\u0022\u002F\u0022":1}
,"add":{"filemaker":1,"file":1,"remove":1}
,"co":{"nnecting":1}
,"nnecting":{"external":1}
,"external":{"data":1,"scripts":1}
,"choose":{"file":1}
,"menu":{"manage":1}
,"manage":{"external":1}
,"elect":{"filemaker":1}
,"edit":{"ou":1,"file":1,"value":1,"filemaker":1}
,"ou":{"change":1}
,"change":{"name":1,"if":1}
,"name":{"data":1}
,"path":{"add":1,"list":1}
,"edited":{"text":1}
,"text":{"each":1}
,"each":{"filemaker":1}
,"consist":{"file":1}
,"separated":{"by":1}
,"by":{"carriage":1}
,"carriage":{"returns":1,"return":1}
,"returns":{"creating":1}
,"creating":{"file":1,"new":1}
,"dialog":{"boxes":1,"box":1}
,"boxes":{"option":1}
,"option":{"choosing":1}
,"choosing":{"existing":1}
,"existing":{"data":1}
,"new":{"data":1}
,"box":{"data":1}
,"reference":{"ilemaker":1,"accessed":1,"resolved":1}
,"want":{"access":1}
,"re-specify":{"data":1}
,"references":{"related":1,"set":1,"filemaker":1,"files":1}
,"related":{"files":1}
,"files":{"files":1,"external":1,"odbc":1,"graphics":1}
,"scripts":{"add":1}
,"remove":{"filename":1}
,"filename":{"extensions":1}
,"extensions":{"use":1}
,"use":{"characters":1,"asterisk":1}
,"characters":{"separators":1}
,"separators":{"file":1}
,"\u0022\u002F\u0022":{"carriage":1}
,"return":{"use":1}
,"asterisk":{"*)":1,"ip":1}
,"*)":{"wild":1}
,"wild":{"ard":1}
,"ard":{"character":1}
,"character":{"network":1}
,"network":{"file":1,"traffic":1}
,"slows":{"filemaker":1}
,"traffic":{"replace":1}
,"replace":{"asterisk":1}
,"ip":{"address":1}
,"address":{"variables":1}
,"variables":{"upported":1}
,"upported":{"ilemaker":1}
,"set":{"variable":1}
,"variable":{"reference":1,"changed":1}
,"accessed":{"reference":1}
,"resolved":{"change":1}
,"if":{"variable":1}
,"changed":{"ata":1}
,"ata":{"source":1}
,"odbc":{"dsns":1}
,"dsns":{"references":1}
,"graphics":{"file":1}
}
;Search.control.loadWordPairs(pairs);
