var pairs =
{
"open":{"manage":1}
,"manage":{"database":1,"database\u0027s":1}
,"database":{"pens":1,"dialog":1,"assigned":1,"tables":1,"end":1}
,"pens":{"manage":1}
,"dialog":{"box":1,"[\u0022":1}
,"box":{"none":1,"user":1,"if":1,"show":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"script":1}
,"script":{"step":1,"scripts":1}
,"step":{"manage":1,"choosing":1,"enable":1,"right-click":1}
,"user":{"create":1,"manage":1}
,"create":{"edit":1}
,"edit":{"tables":1}
,"tables":{"fields":1}
,"fields":{"relationships":1,"manage":1,"\u0022]":1,"field":1}
,"relationships":{"script":1}
,"choosing":{"file":1}
,"file":{"menu":1}
,"menu":{"manage":1}
,"assigned":{"full":1}
,"full":{"access":1}
,"access":{"privilege":1,"privileges":1}
,"privilege":{"set":1}
,"set":{"perform":1}
,"perform":{"script":1}
,"enable":{"users":1}
,"users":{"less":1}
,"less":{"full":1}
,"privileges":{"perform":1,"sharing":1}
,"right-click":{"current":1}
,"current":{"script":1}
,"scripts":{"pane":1}
,"pane":{"choose":1}
,"choose":{"grant":1}
,"grant":{"full":1}
,"sharing":{"files":1}
,"files":{"network":1}
,"network":{"schema":1}
,"schema":{"shared":1}
,"shared":{"databases":1}
,"databases":{"displays":1}
,"displays":{"custom":1}
,"custom":{"dialog":1}
,"if":{"user":1,"[get":1,"defining":1}
,"database\u0027s":{"tables":1}
,"show":{"custom":1}
,"[\u0022":{"want":1}
,"want":{"manage":1}
,"\u0022]":{"if":1}
,"[get":{"lastmessagechoice":1}
,"lastmessagechoice":{"=1]":1}
,"=1]":{"open":1}
,"end":{"if":1}
,"defining":{"changing":1}
,"changing":{"fields":1}
,"field":{"tab":1}
,"tab":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
