var pairs =
{
"etfieldname":{"returns":1}
,"returns":{"qualified":1,"name":1}
,"qualified":{"name":1}
,"name":{"field":1,"text":1}
,"field":{"reference":1,"field":1,"-any":1,"object":1,"tablename":1,"based":1,"focus":1}
,"reference":{"getfieldname":1,"passed":1}
,"getfieldname":{"field":1,"returns":1,"evaluate":1}
,"-any":{"field":1}
,"object":{"evaluation":1}
,"evaluation":{"text":1}
,"text":{"expression":1,"filemaker":1}
,"expression":{"refers":1}
,"refers":{"field\u2019s":1}
,"field\u2019s":{"name":1}
,"filemaker":{"pro":1}
,"pro":{"10.0":1}
,"10.0":{"use":1}
,"use":{"function":1}
,"function":{"get":1,"evaluated":1,"parameter":1}
,"get":{"qualified":1,"activefieldname":1}
,"tablename":{":fieldname":1}
,":fieldname":{"if":1}
,"if":{"context":1}
,"context":{"current":1,"evaluated":1}
,"current":{"calculation":1,"window":1}
,"calculation":{"function":1}
,"evaluated":{"based":1}
,"based":{"context":1,"data":1}
,"window":{"getfieldname":1}
,"passed":{"custom":1}
,"custom":{"function":1}
,"parameter":{"getfieldname":1}
,"evaluate":{"fieldname":1,"get":1}
,"fieldname":{"returns":1,"getfieldname":1}
,"data":{"stored":1}
,"stored":{"fieldname":1}
,"activefieldname":{"returns":1}
,"focus":{"executed":1}
}
;Search.control.loadWordPairs(pairs);
