var pairs =
{
"text":{"keyboard":1,"fields":1,"layout":1,"insertion":1,"delete":1,"command":1,"record":1,"form":1,"edit":1,"objects":1,"press":1,"field":1,"deletion":1,"editing":1,"formatting":1,"alignment":1,"style":1,"size":1,"navigation":1,"selection":1}
,"keyboard":{"shortcuts":1,"shortcut":1}
,"shortcuts":{"mac":1,"edit":1,"browse":1,"format":1,"text":1}
,"mac":{"os":1}
,"os":{"use":1}
,"use":{"text":1,"hese":1,"keyboard":1}
,"edit":{"format":1,"field":1,"ing":1}
,"format":{"text":1}
,"fields":{"text":1,"ield":1}
,"layout":{"use":1,"find":1,"ext":1,"modes":1}
,"hese":{"keyboard":1}
,"browse":{"layout":1}
,"find":{"modes":1,"requests":1,"next":1,"operation":1,"data":1,"selected":1}
,"modes":{"delete":1,"align":1,"move":1,"extend":1}
,"delete":{"press":1,"next":1,"previous":1,"copy":1}
,"press":{"next":1,"clear":1,"center":1,"bold":1,"up":1,"text":1,"line":1}
,"next":{"character":1,"word":1,"occurrence":1,"tab":1,"point":1,"line":1}
,"character":{"forward":1,"delete":1,"left":1,"right":1,"shift-right":1,"shift-left":1}
,"forward":{"delete":1,"all":1,"use":1}
,"word":{"option-forward":1,"option-delete":1,"option-left":1,"option-right":1,"option-shift-left":1,"option-shift-right":1}
,"option-forward":{"delete":1}
,"previous":{"character":1,"word":1,"line":1}
,"option-delete":{"text":1}
,"insertion":{"point":1}
,"point":{"line":1,"next":1,"size":1,"command":1,"text":1,"press":1}
,"line":{"command":1,"up":1,"arrow":1}
,"command":{"-delete":1,"-c":1,"-option-c":1,"-x":1,"-v":1,"-shift-option-v":1,"-z":1,"-y":1,"-shift-z":1,"-shift-f":1,"-g":1,"-shift-g":1,"-option-g":1,"-shift-option-g":1,"-option-i":1,"-shift":1,"-shift-y":1,"-\u005Cleft":1,"-[right":1,"-]":1,"-shift-|":1,"-shift-b":1,"-shift-i":1,"-shift-p":1,"-shift-_(":1,"-=or":1,"-shift-+":1,"-shift-u":1,"-option-shift->":1,"-option-shift-<":1,"-shift->":1,"-shift-<":1,"-up":1,"-down":1,"-left":1,"-right":1,"-shift-left":1,"-option-shift-up":1,"-shift-right":1,"-option-shift-down":1,"-shift-down":1,"-shift-up":1,"-a":1}
,"-delete":{"use":1}
,"field":{"layout":1,"move":1,"label":1,"extend":1,"command":1}
,"ext":{"find":1}
,"requests":{"press":1}
,"clear":{"selected":1}
,"selected":{"text":1,"copy":1,"cut":1,"data":1,"operation":1}
,"copy":{"selected":1,"all":1}
,"-c":{"copy":1,"objects":1}
,"all":{"text":1,"records":1,"reverse":1}
,"record":{"command":1}
,"objects":{"selected":1,"browse":1}
,"records":{"found":1}
,"found":{"set":1}
,"set":{"clipboard":1}
,"clipboard":{"text":1}
,"form":{"command":1}
,"-option-c":{"objects":1}
,"cut":{"selected":1}
,"-x":{"paste":1}
,"paste":{"command":1,"text":1}
,"-v":{"paste":1}
,"-shift-option-v":{"undo":1}
,"undo":{"command":1}
,"-z":{"redo":1}
,"redo":{"command":1}
,"-y":{"command":1}
,"-shift-z":{"exit":1}
,"exit":{"text":1}
,"ing":{"enter":1}
,"enter":{"numeric":1}
,"numeric":{"keypad":1}
,"keypad":{"find\u002Freplace":1}
,"find\u002Freplace":{"data":1,"direction":1}
,"data":{"command":1,"replace":1,"search":1,"database":1}
,"-shift-f":{"find":1}
,"occurrence":{"data":1,"command":1,"selected":1}
,"-g":{"reverse":1}
,"reverse":{"current":1,"keyboard":1}
,"current":{"direction":1,"find\u002Freplace":1}
,"direction":{"find":1,"replace":1,"forward":1,"backward":1}
,"operation":{"command":1}
,"-shift-g":{"replace":1}
,"replace":{"find":1,"data":1,"&find":1}
,"search":{"select":1}
,"select":{"next":1}
,"-option-g":{"reverse":1}
,"&find":{"operation":1}
,"-shift-option-g":{"find":1}
,"database":{"command":1}
,"-option-i":{"reverse":1}
,"-shift":{"-o":1}
,"-o":{"ption-i":1}
,"ption-i":{"insert":1}
,"insert":{"reaking":1,"tab":1}
,"reaking":{"space":1}
,"space":{"option-space":1}
,"option-space":{"bar":1}
,"bar":{"insert":1}
,"tab":{"field":1,"stop":1}
,"move":{"insertion":1}
,"stop":{"option-tab":1}
,"option-tab":{"open":1}
,"open":{"spelling":1}
,"spelling":{"dialog":1}
,"dialog":{"box":1}
,"box":{"alerted":1}
,"alerted":{"misspelled":1}
,"misspelled":{"wor":1}
,"wor":{"command":1}
,"-shift-y":{"note":1}
,"note":{"if":1}
,"if":{"current":1}
,"shortcut":{"switches":1}
,"switches":{"direction":1}
,"backward":{"if":1,"reverse":1}
,"ield":{"labels":1}
,"labels":{"text":1}
,"align":{"text":1}
,"center":{"command":1}
,"-\u005Cleft":{"command":1}
,"-[right":{"command":1}
,"-]":{"justified":1}
,"justified":{"command":1}
,"-shift-|":{"style":1}
,"style":{"text":1,"keyboard":1}
,"bold":{"command":1}
,"-shift-b":{"italic":1}
,"italic":{"command":1}
,"-shift-i":{"plain":1}
,"plain":{"command":1}
,"-shift-p":{"subscript":1}
,"subscript":{"command":1}
,"-shift-_(":{"underscore":1}
,"underscore":{"superscript":1}
,"superscript":{"command":1}
,"-=or":{"command":1}
,"-shift-+":{"underline":1}
,"underline":{"command":1}
,"-shift-u":{"change":1}
,"change":{"point":1}
,"size":{"press":1,"up":1,"menu":1,"keyboard":1}
,"up":{"point":1,"menu":1,"arrow":1}
,"-option-shift->":{"point":1}
,"-option-shift-<":{"next":1}
,"menu":{"command":1}
,"-shift->":{"next":1}
,"-shift-<":{"use":1}
,"label":{"move":1}
,"-up":{"arrow":1}
,"arrow":{"end":1,"line":1,"previous":1,"next":1,"use":1,"text":1,"entire":1}
,"end":{"text":1,"line":1,"next":1}
,"-down":{"arrow":1}
,"-left":{"arrow":1}
,"-right":{"arrow":1}
,"option-left":{"arrow":1}
,"option-right":{"arrow":1}
,"left":{"arrow":1}
,"right":{"arrow":1}
,"extend":{"selection":1}
,"selection":{"field":1,"press":1,"keyboard":1}
,"-shift-left":{"arrow":1}
,"option-shift-left":{"arrow":1}
,"-option-shift-up":{"arrow":1}
,"-shift-right":{"arrow":1}
,"option-shift-right":{"arrow":1}
,"-option-shift-down":{"arrow":1}
,"shift-right":{"arrow":1}
,"-shift-down":{"arrow":1}
,"shift-left":{"arrow":1}
,"-shift-up":{"arrow":1}
,"entire":{"contents":1}
,"contents":{"active":1}
,"active":{"field":1}
,"-a":{"text":1}
,"deletion":{"keyboard":1}
,"editing":{"keyboard":1}
,"formatting":{"keyboard":1}
,"alignment":{"keyboard":1}
,"navigation":{"keyboard":1}
}
;Search.control.loadWordPairs(pairs);
