var pairs =
{
"fining":{"updating":1}
,"updating":{"lookups":1}
,"lookups":{"lookup":1}
,"lookup":{"copies":1,"copy":1,"efine":1,"source":1,"target":1,"filemaker":1,"gain":1,"lookup":1,"based":1,"activated":1,"erformed":1,"match":1,"use":1,"related":1,"value":1,"current":1,"values":1,"alues":1,"update":1}
,"copies":{"data":1,"value":1}
,"data":{"table":1,"part":1,"copied":1,"displayed":1,"field":1,"match":1,"lookup":1,"perform":1,"looked":1,"records":1,"empty":1,"define":1}
,"table":{"field":1,"copied":1,"remains":1,"change":1,"use":1,"if":1,"price":1,"stays":1,"type":1,"filemaker":1,"match":1,"lookup":1,"creating":1,"list":1,"choose":1,"related":1,"find":1,"select":1,"value":1}
,"field":{"current":1,"related":1,"value":1,"lookup":1,"update":1,"contents":1,"relationship":1,"field":1,"type":1,"options":1,"choose":1,"across":1,"record":1}
,"current":{"table":1}
,"copied":{"data":1,"current":1,"statically":1,"select":1,"if":1}
,"part":{"current":1}
,"remains":{"table":1}
,"change":{"automatically":1,"value":1,"data":1}
,"automatically":{"data":1,"update":1}
,"use":{"lookup":1,"relationship":1,"starting":1}
,"copy":{"price":1,"data":1,"record":1}
,"price":{"item":1,"related":1,"invoice":1}
,"item":{"time":1}
,"time":{"purchase":1,"value":1}
,"purchase":{"invoice":1}
,"invoice":{"table":1}
,"if":{"price":1,"change":1,"relationship":1}
,"related":{"table":1,"data":1,"record":1,"records":1}
,"stays":{"difference":1}
,"difference":{"data":1}
,"displayed":{"dynamically":1}
,"dynamically":{"copied":1}
,"statically":{"use":1}
,"relationship":{"establish":1,"access":1,"next":1,"by":1,"lookup":1,"sort":1}
,"establish":{"connection":1}
,"connection":{"tables":1}
,"tables":{"lookup":1}
,"efine":{"lookup":1}
,"type":{"change":1,"lick":1}
,"value":{"match":1,"satisfies":1,"lookup":1,"stored":1,"current":1,"entered":1,"starting":1,"copied":1,"exists":1,"first":1}
,"match":{"field":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"relationship":1,"automatically":1}
,"access":{"first":1}
,"first":{"record":1,"created":1,"related":1}
,"record":{"related":1,"committing":1,"copied":1,"sort":1,"record":1,"lookup":1,"up":1}
,"satisfies":{"criteria":1}
,"criteria":{"relationship":1}
,"next":{"copies":1}
,"source":{"field":1}
,"target":{"field":1}
,"stored":{"edit":1}
,"edit":{"replace":1}
,"replace":{"delete":1}
,"delete":{"value":1}
,"update":{"data":1,"browse":1,"lookup":1}
,"perform":{"lookup":1,"relookup":1}
,"gain":{"by":1}
,"by":{"choosing":1,"modifying":1,"lookup":1,"match":1,"checkout":1}
,"choosing":{"records":1}
,"records":{"menu":1,"intend":1,"relookup":1,"urrent":1,"first":1,"descending":1}
,"menu":{"relookup":1,"manage":1}
,"relookup":{"field":1}
,"contents":{"browse":1,"relookup":1,"command":1,"updates":1,"script":1}
,"browse":{"mode":1}
,"mode":{"by":1,"current":1}
,"modifying":{"match":1}
,"based":{"multi":1}
,"multi":{"riteria":1}
,"riteria":{"relationship":1}
,"activated":{"ach":1}
,"ach":{"time":1}
,"entered":{"ield":1,"required":1}
,"ield":{"hat":1,"list":1}
,"hat":{"nvolved":1}
,"nvolved":{"elationship":1}
,"elationship":{"lookup":1}
,"erformed":{"each":1}
,"each":{"time":1}
,"required":{"fields":1}
,"fields":{"choose":1,"tab":1,"define":1,"looked":1}
,"choose":{"file":1,"table":1,"related":1,"records":1}
,"file":{"menu":1}
,"manage":{"database":1}
,"database":{"relationships":1}
,"relationships":{"tab":1,"sure":1,"graph":1,"automatically":1}
,"tab":{"define":1,"se":1,"select":1}
,"define":{"relationship":1,"new":1,"lookup":1}
,"creating":{"nd":1}
,"nd":{"changing":1}
,"changing":{"relationships":1}
,"sure":{"lookup":1}
,"lick":{"fields":1}
,"se":{"lect":1}
,"lect":{"table":1}
,"list":{"select":1,"existing":1}
,"select":{"ield":1,"looked-up":1,"field":1,"options":1,"match":1}
,"existing":{"fields":1}
,"new":{"field":1}
,"options":{"ick":1,"lookup":1}
,"ick":{"auto-enter":1}
,"auto-enter":{"tab":1}
,"looked-up":{"value":1}
,"starting":{"table":1,"point":1}
,"point":{"relationships":1}
,"graph":{"lookup":1}
,"looked":{"up":1}
,"up":{"select":1,"by":1,"recent":1}
,"find":{"records":1}
,"intend":{"update":1}
,"command":{"commit":1}
,"commit":{"active":1}
,"active":{"record":1}
,"committing":{"data":1}
,"updates":{"all":1}
,"all":{"fields":1,"records":1}
,"across":{"all":1}
,"urrent":{"found":1}
,"found":{"set":1}
,"set":{"undo":1}
,"undo":{"actions":1}
,"actions":{"update":1}
,"values":{"value":1}
,"exists":{"match":1}
,"created":{"related":1}
,"sort":{"order":1,"related":1,"records":1}
,"order":{"value":1,"copied":1,"relationship":1,"by":1}
,"recent":{"checkout":1}
,"checkout":{"date":1}
,"date":{"iece":1,"creating":1}
,"iece":{"equipment":1}
,"equipment":{"sort":1}
,"descending":{"order":1}
,"alues":{"defining":1}
,"defining":{"button":1}
,"button":{"script":1}
,"script":{"trigger":1,"step":1}
,"trigger":{"perform":1}
,"step":{"null":1}
,"null":{"data":1}
,"empty":{"data":1}
}
;Search.control.loadWordPairs(pairs);
