var pairs =
{
"filling":{"ith":1,"layout":1}
,"ith":{"image":1}
,"image":{"fill":1,"image":1,"stored":1,"layout":1,"file":1,"formats":1,"sure":1,"elect":1,"segments":1,"choose":1,"if":1}
,"fill":{"object":1,"layout":1,"line":1,"image":1,"option":1,"portion":1,"graphic":1,"extend":1}
,"object":{"image":1,"body":1,"state":1,"graphic":1,"layout":1}
,"stored":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"file":1}
,"file":{"appears":1,"nserting":1,"open":1,"choose":1,"sliced":1,"layout":1}
,"appears":{"record":1}
,"record":{"layout":1}
,"layout":{"insert":1,"reference":1,"supported":1,"background":1,"parts":1,"mode":1,"part":1,"match":1}
,"insert":{"image":1,"macos":1}
,"reference":{"image":1,"file":1}
,"nserting":{"graphics":1}
,"graphics":{"layout":1}
,"supported":{"image":1}
,"formats":{"include":1}
,"include":{"png":1}
,"png":{".png":1}
,".png":{"bmp":1}
,"bmp":{".bmp":1}
,".bmp":{"tiff":1}
,"tiff":{".tif":1}
,".tif":{"gif":1}
,"gif":{".gif":1}
,".gif":{"jpeg\u002Fjfif":1}
,"jpeg\u002Fjfif":{".jpg":1}
,".jpg":{"note":1}
,"note":{"filling":1,"selecting":1}
,"background":{"ith":1,"select":1,"sure":1,"portion":1,"fill":1,"image":1}
,"sure":{"fill":1,"objects":1}
,"parts":{"transparent":1,"selected":1,"fill":1}
,"transparent":{"setting":1}
,"setting":{"fill":1}
,"line":{"style":1}
,"style":{"shadows":1}
,"shadows":{"padding":1}
,"padding":{"layout":1}
,"mode":{"select":1,"right-click":1}
,"select":{"objects":1,"note":1,"file":1}
,"objects":{"part":1,"parts":1}
,"part":{"label":1,"it\u2019s":1,"layout":1}
,"label":{"layout":1}
,"selecting":{"layout":1}
,"selected":{"inspector":1}
,"inspector":{"appearance":1}
,"appearance":{"appearance":1,"tab":1,"object":1}
,"tab":{"change":1}
,"change":{"appearance":1,"inserted":1}
,"body":{"part":1}
,"it\u2019s":{"state":1}
,"state":{"button":1,"list":1,"object":1}
,"button":{"pressed":1}
,"pressed":{"choose":1}
,"choose":{"object":1,"select":1,"fill":1,"export":1,"location":1}
,"list":{"top":1}
,"top":{"ab":1}
,"ab":{"display":1}
,"display":{"state":1,"lines":1,"square":1}
,"graphic":{"fill":1,"choose":1}
,"elect":{"image":1}
,"open":{"windows":1}
,"windows":{"insert":1}
,"macos":{"change":1}
,"inserted":{"image":1}
,"option":{"slice":1,"store":1}
,"slice":{"divides":1}
,"divides":{"image":1}
,"segments":{"fill":1}
,"portion":{"image":1,"company":1}
,"company":{"logo":1}
,"logo":{"ensures":1}
,"ensures":{"colors":1}
,"colors":{"layout":1}
,"match":{"brand":1}
,"brand":{"allows":1}
,"allows":{"yo":1}
,"yo":{"use":1}
,"use":{"color":1}
,"color":{"multiple":1}
,"multiple":{"layouts":1}
,"layouts":{"su":1}
,"su":{"bstantially":1}
,"bstantially":{"increasing":1}
,"increasing":{"size":1}
,"size":{"file":1}
,"sliced":{"fills":1}
,"fills":{"display":1}
,"lines":{"rounded":1}
,"rounded":{"corners":1}
,"corners":{"circles":1}
,"circles":{"display":1}
,"square":{"images":1}
,"images":{"export":1}
,"export":{"image":1,"fill":1}
,"right-click":{"image":1}
,"location":{"type":1}
,"type":{"filename":1}
,"filename":{"save":1}
,"save":{"ou":1}
,"ou":{"can\u2019t":1}
,"can\u2019t":{"export":1}
,"if":{"set":1}
,"set":{"option":1}
,"store":{"reference":1}
,"extend":{"behind":1}
,"behind":{"navigation":1}
,"navigation":{"parts":1}
}
;Search.control.loadWordPairs(pairs);
