var pairs =
{
"getastext":{"returns":1,"data":1,"container":1,"45":1}
,"returns":{"data":1,"external":1,"remote:cat.jpg":1,"45":1,"days":1,"fy98":1}
,"data":{"field":1,"data":1,"-any":1,"returned":1,"embedded":1,"stored":1}
,"field":{"type":1,"number":1,"getastext":1,"98":1}
,"type":{"text":1,"number":1}
,"text":{"getastext":1,"filemaker":1,"text":1,"functions":1,"container":1,"resolve":1}
,"-any":{"number":1}
,"number":{"date":1,"field":1}
,"date":{"time":1}
,"time":{"timestamp":1}
,"timestamp":{"expression":1,"container":1}
,"expression":{"field":1}
,"container":{"text":1,"container":1,"field":1,"data":1,"returns":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"use":1}
,"use":{"formulas":1}
,"formulas":{"involving":1}
,"involving":{"text":1}
,"functions":{"data":1}
,"returned":{"field":1,"format":1}
,"external":{"path":1}
,"path":{"text":1,"question":1}
,"resolve":{"valid":1}
,"valid":{"path":1}
,"question":{"mark":1}
,"mark":{"if":1}
,"if":{"container":1,"fiscalyear":1}
,"embedded":{"database":1}
,"database":{"container":1}
,"stored":{"externally":1}
,"externally":{"data":1}
,"format":{"getastext":1}
,"remote:cat.jpg":{"size:320,240":1}
,"size:320,240":{"jpeg:images\u002Fanimals\u002Fcat.jpg":1}
,"jpeg:images\u002Fanimals\u002Fcat.jpg":{"getastext":1}
,"45":{"returns":1,"&getastext":1}
,"&getastext":{"daysdelinquent":1,"fiscalyear":1}
,"daysdelinquent":{"&\u0022":1,"fy":1}
,"&\u0022":{"days":1}
,"days":{"late":1}
,"late":{"returns":1,"value":1}
,"value":{"daysdelinquent":1}
,"fy":{"&getastext":1}
,"fiscalyear":{"returns":1,"number":1}
,"fy98":{"if":1}
}
;Search.control.loadWordPairs(pairs);
