var pairs =
{
"opying":{"pasting":1}
,"pasting":{"scripts":1,"script":1,"ensure":1}
,"scripts":{"script":1,"folders":1,"hen":1}
,"script":{"workspace":1,"script":1,"folder":1,"step":1,"want":1,"displayed":1,"steps":1}
,"workspace":{"se":1,"if":1}
,"se":{"lect":1}
,"lect":{"script":1}
,"folder":{"script":1,"privileges":1}
,"step":{"copy":1,"open":1,"item":1,"retain":1}
,"copy":{"choose":1,"pen":1,"multiple":1,"step":1,"time":1,"scripts":1}
,"choose":{"edit":1}
,"edit":{"menu":1}
,"menu":{"copy":1,"paste":1}
,"pen":{"file":1}
,"file":{"want":1,"pasted":1,"copy":1,"script":1}
,"want":{"paste":1}
,"paste":{"item":1,"if":1}
,"item":{"open":1,"se":1,"ch":1}
,"open":{"script":1,"log":1}
,"if":{"pasting":1,"problems":1,"copy":1}
,"ch":{"oose":1}
,"oose":{"edit":1}
,"problems":{"pasted":1,"errors":1}
,"pasted":{"script":1,"objects":1}
,"displayed":{"new":1}
,"new":{"tab":1}
,"tab":{"problem":1}
,"problem":{"steps":1}
,"steps":{"highlighted":1,"reference":1,"write":1,"breakpoints":1}
,"highlighted":{"view":1}
,"view":{"additional":1}
,"additional":{"problems":1}
,"errors":{"open":1}
,"log":{"file":1}
,"objects":{"retain":1}
,"retain":{"privileges":1,"references":1}
,"privileges":{"redefine":1,"source":1,"create":1}
,"redefine":{"privilege":1}
,"privilege":{"sets":1}
,"sets":{"destination":1}
,"destination":{"file":1,"scripts":1}
,"multiple":{"scripts":1}
,"folders":{"script":1,"write":1,"destination":1}
,"reference":{"each":1}
,"each":{"copy":1}
,"references":{"if":1,"lost":1,"pasting":1}
,"time":{"references":1}
,"lost":{"check":1}
,"check":{"all":1}
,"all":{"references":1}
,"ensure":{"valid":1}
,"valid":{"scripts":1}
,"write":{"access":1}
,"access":{"privileges":1,"source":1}
,"source":{"script":1,"destination":1}
,"create":{"scripts":1}
,"hen":{"copy":1}
,"breakpoints":{"pauses":1,"retained":1}
,"pauses":{"re":1}
,"re":{"copied":1}
,"copied":{"duplicate":1}
,"duplicate":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
