var pairs =
{
"efining":{"database":1}
,"database":{"tables":1,"contain":1,"cl":1,"dialog":1}
,"tables":{"use":1,"organize":1,"add":1,"tab":1,"fields":1,"relationships":1,"orking":1,"place":1,"naming":1}
,"use":{"database":1}
,"organize":{"group":1,"data":1}
,"group":{"data":1}
,"data":{"by":1,"limited":1,"filemaker":1,"convert":1}
,"by":{"common":1,"storage":1,"default":1}
,"common":{"characteristics":1}
,"characteristics":{"principles":1}
,"principles":{"database":1}
,"contain":{"tables":1}
,"limited":{"by":1}
,"storage":{"space":1}
,"space":{"hard":1}
,"hard":{"disk":1}
,"disk":{"by":1}
,"default":{"new":1,"fields":1}
,"new":{"file":1,"table":1,"name":1,"tables":1}
,"file":{"table":1,"automatically":1,"menu":1,"fields":1,"application":1,"named":1}
,"table":{"name":1,"renamed":1,"fields":1,"create":1,"type":1,"calculations":1,"occurrences":1,"manage":1,"naming":1,"tablenames":1}
,"name":{"file":1,"fields":1,"table":1,"select":1,"change":1,"filemaker":1}
,"renamed":{"deleted":1}
,"deleted":{"tables":1}
,"add":{"file":1}
,"automatically":{"displayed":1}
,"displayed":{"relationships":1}
,"relationships":{"graph":1,"relationships":1,"scripts":1}
,"graph":{"by":1,"establish":1,"creating":1}
,"fields":{"primary":1,"track":1,"choose":1,"tab":1,"addition":1,"table":1,"created":1,"new":1,"define":1}
,"primary":{"key":1}
,"key":{"field":1}
,"field":{"account":1}
,"account":{"name":1}
,"track":{"created":1,"record":1}
,"created":{"record":1,"last":1,"import":1}
,"record":{"last":1,"timestamp":1,"created":1}
,"last":{"modified":1}
,"modified":{"record":1,"rename":1}
,"timestamp":{"fields":1}
,"rename":{"delete":1}
,"delete":{"fields":1}
,"choose":{"file":1}
,"menu":{"manage":1}
,"manage":{"database":1}
,"cl":{"ick":1}
,"ick":{"tables":1}
,"tab":{"ype":1,"define":1}
,"ype":{"name":1}
,"create":{"change":1,"table":1,"file":1}
,"change":{"table":1,"continue":1}
,"select":{"table":1}
,"type":{"new":1}
,"continue":{"define":1}
,"define":{"tables":1,"fields":1,"table":1}
,"addition":{"storing":1}
,"storing":{"data":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"tables":1,"updates":1}
,"establish":{"context":1}
,"context":{"layouts":1}
,"layouts":{"calculations":1,"reports":1}
,"calculations":{"related":1,"relationships":1}
,"related":{"tables":1}
,"orking":{"ith":1}
,"ith":{"relationships":1}
,"creating":{"managing":1}
,"managing":{"layouts":1}
,"reports":{"hen":1}
,"hen":{"change":1}
,"updates":{"all":1}
,"all":{"references":1}
,"references":{"table":1}
,"scripts":{"table":1}
,"occurrences":{"default":1}
,"dialog":{"box":1}
,"box":{"create":1}
,"import":{"data":1}
,"convert":{"file":1}
,"application":{"prevent":1}
,"prevent":{"default":1}
,"place":{"empty":1}
,"empty":{"file":1}
,"named":{"defaultfields.xml":1}
,"defaultfields.xml":{"location":1}
,"location":{"windows":1}
,"windows":{"drive":1}
,"drive":{":\u005Cprogramdata\u005Cfilemaker\u005Cshared":1}
,":\u005Cprogramdata\u005Cfilemaker\u005Cshared":{"macos":1}
,"macos":{"\u002Fusers\u002Fshared\u002Ffilemaker\u002Fshared":1}
,"\u002Fusers\u002Fshared\u002Ffilemaker\u002Fshared":{"name":1}
,"naming":{"tables":1,"table":1}
,"tablenames":{"default":1}
}
;Search.control.loadWordPairs(pairs);
