var pairs =
{
"get":{"layoutnu":1,"layoutnumber":1,"layoutname":1,"layout":1,"current":1}
,"layoutnu":{"mber":1}
,"mber":{"returns":1}
,"returns":{"number":1,"current":1}
,"number":{"layout":1,"filemaker":1,"value":1,"get":1}
,"layout":{"manage":1,"number":1,"list":1}
,"manage":{"layouts":1}
,"layouts":{"dialog":1,"name":1,"manage":1,"get":1}
,"dialog":{"box":1}
,"box":{"currently":1}
,"currently":{"displayed":1}
,"displayed":{"get":1}
,"layoutnumber":{"none":1,"alternative":1,"get":1}
,"none":{"number":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"if":1}
,"if":{"multiple":1}
,"multiple":{"windows":1,"layouts":1}
,"windows":{"open":1}
,"open":{"current":1}
,"current":{"file":1,"layout":1}
,"file":{"each":1}
,"each":{"window":1}
,"window":{"own":1,"use":1}
,"own":{"layout":1}
,"value":{"returned":1}
,"returned":{"foreground":1}
,"foreground":{"window":1}
,"use":{"get":1}
,"alternative":{"get":1}
,"layoutname":{"function":1}
,"function":{"if":1}
,"name":{"returns":1}
,"list":{"layouts":1}
}
;Search.control.loadWordPairs(pairs);
