var pairs =
{
"installing":{"plug-ins":1}
,"plug-ins":{"database":1,"note":1,"installed":1,"install":1,"match":1,"use":1,"extensions":1,"starts":1,"stored":1}
,"database":{"developers":1}
,"developers":{"insert":1}
,"insert":{"plug-in":1,"menu":1,"file":1}
,"plug-in":{"files":1,"preferences":1,"file":1,"container":1,"pl":1,"compare":1,"stored":1,"by":1,"support":1,"version":1,"intended":1,"each":1,"if":1,"plug-in":1,"id":1}
,"files":{"container":1,"trial":1,"option":1}
,"container":{"fields":1,"field":1}
,"fields":{"use":1,"browse":1,"compressed":1}
,"use":{"scripts":1,"solution":1,"insert":1,"install":1,"get":1}
,"scripts":{"calculations":1,"insert":1}
,"calculations":{"install":1}
,"install":{"update":1,"files":1,"etting":1,"plug-in":1,"plug-ins":1,"64-bit":1,"multiple":1}
,"update":{"plug-ins":1,"plug-in":1,"nd":1}
,"note":{"if":1}
,"if":{"concerned":1,"don\u2019t":1,"lug-in":1,"solution":1,"plug-in":1,"loaded":1}
,"concerned":{"unwanted":1}
,"unwanted":{"plug-ins":1}
,"installed":{"use":1,"folders":1,"plug-in":1,"versions":1}
,"solution":{"files":1,"file":1,"requires":1}
,"trial":{"basis":1}
,"basis":{"disable":1}
,"disable":{"allow":1}
,"allow":{"solutions":1,"required":1}
,"solutions":{"install":1}
,"option":{"plug-in":1}
,"preferences":{"aware":1,"create":1}
,"aware":{"solution":1}
,"file":{"behave":1,"select":1,"open":1,"script":1,"create":1}
,"behave":{"intended":1}
,"intended":{"if":1,"all":1}
,"don\u2019t":{"allow":1}
,"required":{"plug-ins":1}
,"etting":{"plug-in":1}
,"create":{"container":1,"script":1}
,"field":{"container":1,"choose":1,"creating":1,"target":1,"run":1,"update":1}
,"browse":{"mode":1}
,"mode":{"select":1}
,"select":{"container":1,"plug-in":1}
,"choose":{"insert":1}
,"menu":{"insert":1}
,"open":{"write":1}
,"write":{"script":1}
,"script":{"use":1,"step":1,"install":1}
,"step":{"place":1,"container":1,"last":1}
,"place":{"plug-in":1,"plug-ins":1}
,"creating":{"editing":1}
,"editing":{"scripts":1}
,"target":{"field":1}
,"run":{"script":1}
,"pl":{"ug-ins":1}
,"ug-ins":{"installed":1}
,"folders":{"windows":1}
,"windows":{"c:\u005Cusers\u005Cuser_name":1,"application":1}
,"c:\u005Cusers\u005Cuser_name":{"\u005Cappdata\u005Clocal\u005Cfilemaker\u005Cfilemaker":1}
,"\u005Cappdata\u005Clocal\u005Cfilemaker\u005Cfilemaker":{"pro":1}
,"pro":{"advanced\u005C18":1,"advanced\u002F18":1,"advanced":1}
,"advanced\u005C18":{"0\u005Cextensions\u005C\u2022":1}
,"0\u005Cextensions\u005C\u2022":{"macos":1}
,"macos":{"macintosh":1,"folder":1,"plug-ins":1}
,"macintosh":{"hd\u002Fusers\u002Fuser_name":1}
,"hd\u002Fusers\u002Fuser_name":{"\u002Flibrary\u002Fapplication":1}
,"\u002Flibrary\u002Fapplication":{"support\u002Ffilemaker\u002Ffilemaker":1}
,"support\u002Ffilemaker\u002Ffilemaker":{"pro":1}
,"advanced\u002F18":{"0\u002Fextensions":1}
,"0\u002Fextensions":{"ou":1}
,"ou":{"use":1}
,"get":{"installedfmplugins":1,"applicationarchitecture":1}
,"installedfmplugins":{"function":1,"filemaker":1}
,"function":{"identify":1,"determine":1}
,"identify":{"version":1}
,"version":{"installed":1,"plug-in":1,"filemaker":1,"current":1,"if":1}
,"compare":{"version":1}
,"stored":{"container":1}
,"by":{"reinstalling":1,"folder":1,"default":1}
,"reinstalling":{"if":1}
,"lug-in":{"update":1}
,"nd":{"get":1}
,"filemaker":{"ro":1,"pro":1,"runtime":1}
,"ro":{"advanced":1}
,"advanced":{"install":1,"application\u2019s":1,"if":1,"instruct":1,"filemaker":1,"application":1,"load":1}
,"match":{"filemaker":1}
,"application\u2019s":{"architecture":1}
,"architecture":{"64-bit":1,"install":1}
,"64-bit":{"version":1,"plug-ins":1}
,"applicationarchitecture":{"function":1}
,"determine":{"current":1}
,"current":{"application\u0027s":1,"version":1}
,"application\u0027s":{"architecture":1}
,"multiple":{"versions":1}
,"versions":{"plug-in":1,"filemaker":1,"manually":1}
,"support":{"multiple":1}
,"requires":{"specific":1}
,"specific":{"plug-in":1}
,"instruct":{"users":1}
,"users":{"manually":1}
,"manually":{"place":1,"install":1}
,"extensions":{"folder":1}
,"folder":{"inside":1,"current":1,"search":1,"by":1,"install":1,"filemaker":1}
,"inside":{"filemaker":1}
,"runtime":{"folder":1}
,"all":{"installed":1}
,"each":{"user\u2019s":1}
,"user\u2019s":{"appdata\u005Clocal\u005Cfilemaker\u005Cextensions":1}
,"appdata\u005Clocal\u005Cfilemaker\u005Cextensions":{"windows":1}
,"application":{"support\u002Ffilemaker\u002Fextensions":1,"folder":1}
,"support\u002Ffilemaker\u002Fextensions":{"macos":1}
,"search":{"order":1}
,"order":{"loading":1}
,"loading":{"plug-ins":1}
,"starts":{"extensions":1}
,"last":{"location":1}
,"location":{"checked":1}
,"checked":{"appdata\u005Clocal\u005Cfilemaker\u005Cextensions":1}
,"load":{"plug-in":1}
,"loaded":{"plug-in":1}
,"id":{"macos":1}
,"compressed":{"by":1}
,"default":{"install":1}
}
;Search.control.loadWordPairs(pairs);
