var pairs =
{
"nter":{"find":1}
,"find":{"mode":1,"request":1,"requests":1,"records":1,"omit":1,"go":1,"[]":1}
,"mode":{"witches":1,"pause":1,"pauses":1,"[pause":1,"bout":1}
,"witches":{"find":1}
,"pause":{"temporarily":1}
,"temporarily":{"stops":1}
,"stops":{"script":1}
,"script":{"allow":1,"step":1}
,"allow":{"users":1}
,"users":{"enter":1}
,"enter":{"find":1}
,"request":{"find":1,"if":1,"select":1,"perform":1,"criteria":1}
,"requests":{"allows":1,"use":1,"time":1,"defined":1,"duplicated":1,"dialog":1,"find":1}
,"allows":{"create":1}
,"create":{"edit":1}
,"edit":{"requests":1,"find":1,"edit":1}
,"use":{"script":1,"multiple":1}
,"step":{"filemaker":1,"defined":1,"each":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1,"advanced":1}
,"6.0":{"earlier":1}
,"earlier":{"select":1}
,"select":{"find":1,"list":1,"action":1}
,"time":{"script":1,"use":1}
,"defined":{"filemaker":1,"existing":1}
,"advanced":{"isplays":1,"search":1,"modes":1}
,"isplays":{"current":1}
,"current":{"find":1}
,"if":{"additional":1}
,"additional":{"find":1}
,"existing":{"find":1}
,"duplicated":{"edited":1}
,"edited":{"deleted":1}
,"deleted":{"edit":1}
,"list":{"find":1}
,"dialog":{"box":1}
,"box":{"edit":1,"select":1}
,"action":{"find":1}
,"records":{"omit":1,"want":1,"perform":1,"single":1}
,"omit":{"records":1}
,"want":{"find":1,"filemaker":1}
,"perform":{"single":1,"actions":1,"find":1}
,"single":{"find":1,"script":1}
,"actions":{"time":1}
,"multiple":{"find":1}
,"each":{"field":1}
,"field":{"request":1}
,"criteria":{"want":1}
,"search":{"invoice":1}
,"invoice":{"details":1}
,"details":{"layout":1,"\u0022]":1}
,"layout":{"enters":1,"[\u0022":1}
,"enters":{"find":1}
,"pauses":{"user":1}
,"user":{"input":1}
,"input":{"performs":1}
,"performs":{"find":1}
,"go":{"layout":1}
,"[\u0022":{"invoice":1}
,"\u0022]":{"enter":1}
,"[pause":{"on]":1}
,"on]":{"perform":1}
,"[]":{"enter":1}
,"bout":{"filemaker":1}
,"modes":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
