var pairs =
{
"go":{"record\u002Frequest\u002Fpage":1}
,"record\u002Frequest\u002Fpage":{"oves":1,"[first]":1,"[with":1,"[next":1}
,"oves":{"record":1}
,"record":{"report":1,"file":1,"found":1,"by":1,"number":1,"find":1,"perform":1,"empty":1,"aking":1}
,"report":{"page":1,"preview":1,"previous":1,"next":1,"exit":1}
,"page":{"displays":1,"report":1,"number":1,"server-side":1}
,"displays":{"find":1,"first":1,"last":1,"previous":1,"next":1}
,"find":{"request":1,"mode":1,"sorts":1,"[restore]":1}
,"request":{"first":1,"find":1,"moves":1,"number":1,"preview":1,"previewing":1}
,"first":{"moves":1,"record":1,"find":1,"page":1}
,"moves":{"first":1,"last":1,"previous":1,"next":1,"record":1,"report":1}
,"file":{"found":1}
,"found":{"set":1}
,"set":{"browse":1,"displays":1,"if":1,"dialog":1,"variable":1}
,"browse":{"mode":1}
,"mode":{"displays":1,"moves":1,"last":1,"script":1}
,"preview":{"mode":1}
,"last":{"moves":1,"record":1,"find":1,"page":1,"exits":1,"loop":1,"end":1}
,"previous":{"moves":1,"record":1,"find":1,"page":1,"selected":1}
,"next":{"moves":1,"record":1,"find":1,"page":1,"previous":1}
,"exit":{"last":1,"loop":1}
,"exits":{"script":1,"loop":1}
,"script":{"reaches":1,"step":1}
,"reaches":{"last":1}
,"if":{"next":1,"record":1,"[isempty":1}
,"selected":{"use":1}
,"use":{"exit":1}
,"loop":{"exit":1,"last":1,"if":1,"selecting":1}
,"by":{"calculation":1}
,"calculation":{"specifies":1,"determine":1,"option":1}
,"specifies":{"calculation":1}
,"determine":{"desired":1}
,"desired":{"record":1}
,"number":{"find":1,"page":1,"set":1,"dialog":1,"user":1,"want":1}
,"dialog":{"display":1,"box":1,"off]":1,"[\u0022":1,"invoices":1}
,"display":{"number":1}
,"box":{"confirmation":1,"show":1}
,"confirmation":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"browse":1}
,"step":{"moves":1}
,"server-side":{"scripts":1}
,"scripts":{"customer":1}
,"customer":{"web":1}
,"web":{"publishing":1}
,"publishing":{"support":1}
,"support":{"by":1}
,"option":{"performs":1}
,"performs":{"find":1}
,"sorts":{"records":1}
,"records":{"first":1,"[restore":1,"loops":1,"export":1}
,"perform":{"find":1}
,"[restore]":{"sort":1}
,"sort":{"records":1}
,"[restore":{"dialog":1}
,"off]":{"go":1}
,"[first]":{"record":1,"loop":1}
,"user":{"enters":1}
,"enters":{"custom":1}
,"custom":{"dialog":1}
,"show":{"custom":1,"all":1}
,"[\u0022":{"enter":1}
,"enter":{"record":1}
,"want":{"view":1}
,"view":{"invoices":1}
,"invoices":{":record":1}
,":record":{"number]":1}
,"number]":{"go":1,"show":1}
,"[with":{"dialog":1}
,"all":{"records":1}
,"loops":{"records":1}
,"export":{"files":1,"field":1}
,"files":{"container":1}
,"container":{"field":1}
,"field":{"exits":1,"set":1,"contents":1}
,"empty":{"container":1}
,"variable":{"[$path":1}
,"[$path":{"value":1}
,"value":{"get":1}
,"get":{"documentspath":1}
,"documentspath":{"&products":1}
,"&products":{":container]":1}
,":container]":{"go":1}
,"[isempty":{"products":1}
,"products":{":container":1}
,":container":{")]":1,"\u0022$path":1}
,")]":{"export":1}
,"contents":{"[products":1}
,"[products":{":container":1}
,"\u0022$path":{"create":1}
,"create":{"folders":1}
,"folders":{"off]":1}
,"[next":{"exit":1}
,"end":{"loop":1}
,"selecting":{"current":1}
,"current":{"record":1}
,"aking":{"find":1}
,"previewing":{"printing":1}
,"printing":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
