var pairs =
{
"serialincrement":{"returns":1,"text":1,"abc12":1,"abc1.2":1,"abc123;999":1}
,"returns":{"text":1,"abc13":1,"abc19":1,"abc11":1,"abc1.3":1,"abc123;1000":1}
,"text":{"numbers":1,"incrementby":1,"-any":1,"number":1,"by":1,"filemaker":1,"text":1,"performing":1,"if":1,"character":1}
,"numbers":{"numbers":1,"incremented":1}
,"incremented":{"by":1,"serialincrement":1}
,"by":{"serialincrement":1,"text":1}
,"incrementby":{"text":1,"-any":1,"value":1,"values":1}
,"-any":{"text":1,"numeric":1}
,"number":{"incrementby":1,"integer":1,"text":1,"considered":1,"right":1}
,"numeric":{"expression":1}
,"expression":{"increment":1}
,"increment":{"text":1}
,"filemaker":{"pro":1}
,"pro":{"7.0":1}
,"7.0":{"function":1}
,"function":{"doesn\u2019t":1}
,"doesn\u2019t":{"remove":1}
,"remove":{"text":1}
,"performing":{"standard":1}
,"standard":{"math":1}
,"math":{"value":1}
,"value":{"text":1,"decimal":1,"last":1}
,"if":{"incrementby":1}
,"decimal":{"number":1}
,"integer":{"portion":1}
,"portion":{"incrementby":1}
,"last":{"number":1}
,"character":{"number":1}
,"considered":{"separator":1}
,"separator":{"use":1,"number":1}
,"use":{"positive":1}
,"positive":{"negative":1}
,"negative":{"incrementby":1}
,"values":{"serialincrement":1}
,"abc12":{"returns":1,"-1":1,"1.2":1}
,"abc13":{"serialincrement":1}
,"abc19":{"serialincrement":1}
,"-1":{"returns":1}
,"abc11":{"serialincrement":1}
,"1.2":{"returns":1}
,"abc1.2":{"1.2":1}
,"abc1.3":{"character":1}
,"right":{"incremented":1}
,"abc123;999":{"returns":1}
}
;Search.control.loadWordPairs(pairs);
