var pairs =
{
"wordcount":{"returns":1,"text":1,"sun":1,"letter":1}
,"returns":{"count":1,"wordcount":1,"total":1,"each":1}
,"count":{"total":1}
,"total":{"number":1}
,"number":{"text":1,"filemaker":1,"letter":1}
,"text":{"wordcount":1,"text":1,"-any":1,"expression":1,"field":1,"x=y=1.5":1}
,"-any":{"text":1}
,"expression":{"text":1}
,"field":{"number":1,"if":1,"text":1}
,"filemaker":{"pro":1,"knowledge":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"addition":1}
,"addition":{"space":1}
,"space":{"tab":1}
,"tab":{"enter":1}
,"enter":{"carriage":1}
,"carriage":{"return":1}
,"return":{"characters":1}
,"characters":{"characters":1,"equal":1}
,"equal":{"(=)":1}
,"(=)":{"ampersand":1,"character":1}
,"ampersand":{"(&)":1}
,"(&)":{"hyphen":1}
,"hyphen":{"(-)":1}
,"(-)":{"identify":1}
,"identify":{"new":1}
,"new":{"word":1}
,"word":{"word":1,"separators":1}
,"separators":{"search":1}
,"search":{"filemaker":1}
,"knowledge":{"base":1}
,"base":{"wordcount":1}
,"sun":{"rising":1}
,"rising":{"returns":1}
,"letter":{"returns":1,"field":1}
,"if":{"letter":1}
,"x=y=1.5":{"returns":1}
,"each":{"equal":1}
,"character":{"identifies":1}
,"identifies":{"new":1}
}
;Search.control.loadWordPairs(pairs);
