var pairs =
{
"formatting":{"button":1,"bar":1,"formatting":1}
,"button":{"bar":1,"bar\u2019s":1,"layout":1,"icons":1}
,"bar":{"layout":1,"select":1,"edge":1,"button":1,"dividers":1,"segment":1,"icon":1,"object":1,"if":1,"formatting":1,"set":1,"choose":1,"values":1,"change":1}
,"layout":{"mode":1,"layout":1,"pop-up":1,"bar":1}
,"mode":{"choose":1}
,"choose":{"layout":1,"button":1,"options":1,"display":1,"color":1}
,"pop-up":{"menu":1}
,"menu":{"select":1}
,"select":{"button":1,"line":1,"outer":1,"inner":1,"color":1,"display":1}
,"edge":{"handles":1,"segment":1}
,"handles":{"all":1}
,"all":{"inspector":1,"options":1,"components":1,"segments":1}
,"inspector":{"appearance":1,"use":1}
,"appearance":{"appearance":1,"tab":1,"size":1}
,"tab":{"choose":1}
,"dividers":{"button":1,"choose":1,"object":1}
,"segment":{"button":1,"object":1,"choose":1}
,"icon":{"object":1,"all":1,"edge":1,"choose":1,"label":1}
,"object":{"type":1}
,"type":{"list":1,"size":1,"change":1}
,"list":{"top":1,"ch":1,"graphic":1,"choose":1,"aragraph":1,"advanced":1,"select":1,"ab":1,"value":1}
,"top":{"ab":1,"bottom":1}
,"ab":{"note":1,"graphic":1}
,"note":{"all":1}
,"options":{"all":1,"text":1,"formatting":1}
,"components":{"change":1}
,"change":{"line":1,"appearance":1,"format":1,"color":1,"fill":1}
,"line":{"style":1,"type":1}
,"style":{"color":1,"olor":1}
,"color":{"button":1,"change":1,"line":1,"label":1,"icons":1,"filemaker":1,"defined":1,"custom":1}
,"bar\u2019s":{"border":1,"dividers":1,"segments":1}
,"border":{"choose":1}
,"ch":{"oose":1}
,"oose":{"line":1}
,"olor":{"graphic":1}
,"graphic":{"change":1,"select":1,"padding":1,"values":1,"choose":1}
,"size":{"button":1,"color":1}
,"format":{"label":1,"changing":1,"adjust":1}
,"label":{"text":1,"icon":1}
,"text":{"all":1,"inspector":1,"options":1,"icon":1,"choose":1}
,"segments":{"choose":1}
,"use":{"text":1}
,"if":{"don\u2019t":1}
,"don\u2019t":{"formatting":1}
,"set":{"horizontal":1}
,"horizontal":{"vertical":1,"button":1}
,"vertical":{"alignment":1,"button":1}
,"alignment":{"label":1,"add":1}
,"aragraph":{"set":1}
,"add":{"outer":1,"inner":1,"padding":1}
,"outer":{"shadow":1}
,"shadow":{"button":1,"add":1}
,"advanced":{"graphic":1,"elements":1}
,"inner":{"shadow":1}
,"padding":{"label":1,"values":1,"button":1,"icon":1}
,"values":{"points":1,"top":1,"left":1}
,"points":{"left":1,"padding":1}
,"left":{"right":1}
,"right":{"top":1,"vertical":1}
,"bottom":{"add":1,"horizontal":1}
,"display":{"state":1}
,"state":{"graphic":1,"second":1}
,"second":{"list":1}
,"fill":{"color":1}
,"icons":{"custom":1,"svg":1,"change":1,"png":1}
,"custom":{"icons":1}
,"svg":{"format":1,"file":1,"grammar":1}
,"changing":{"fill":1}
,"filemaker":{"ro":1}
,"ro":{"advanced":1,"svg":1}
,"elements":{"fill":1}
,"defined":{"svg":1}
,"file":{"filemaker":1}
,"grammar":{"button":1}
,"png":{"format":1}
,"adjust":{"padding":1}
,"value":{"points":1}
}
;Search.control.loadWordPairs(pairs);
