var pairs =
{
"aggregate":{"functions":1}
,"functions":{"aggregate":1,"perform":1,"fields":1}
,"perform":{"statistical":1}
,"statistical":{"analysis":1}
,"analysis":{"numbers":1}
,"numbers":{"dates":1}
,"dates":{"times":1}
,"times":{"functions":1}
,"fields":{"record":1,"displayed":1,"use":1,"max":1}
,"record":{"related":1}
,"related":{"fields":1}
,"displayed":{"portal":1}
,"portal":{"repeating":1,"alternative":1}
,"repeating":{"fields":1,"field":1}
,"use":{"sum":1,"extend":1}
,"sum":{"function":1,"total":1}
,"function":{"add":1,"values":1,"returns":1}
,"add":{"values":1}
,"values":{"listed":1,"include":1,"repetitions":1,"field":1,"ield":1}
,"listed":{"portal":1}
,"alternative":{"creating":1}
,"creating":{"report":1}
,"report":{"grouped":1}
,"grouped":{"data":1}
,"data":{"subtotals":1}
,"subtotals":{"parameter":1}
,"parameter":{"values":1,"formula":1}
,"include":{"numeric":1,"non-repeating":1}
,"numeric":{"constant":1}
,"constant":{"10":1,"parameter":1}
,"10":{"valid":1}
,"valid":{"expression":1,"non-blank":1,"value":1}
,"expression":{"constant":1}
,"formula":{"repeating":1}
,"field":{"result":1,"parameters":1,"value":1,"ignored":1,"repetitions":1,"referenced":1,"count":1,"fields":1,"min":1,"stdev":1,"stdevp":1,"sum":1,"variance":1,"variancep":1}
,"result":{"repetition":1,"first":1}
,"repetition":{"repeating":1,"use":1}
,"parameters":{"field1":1}
,"field1":{"field2":1}
,"field2":{"include":1}
,"non-repeating":{"field":1}
,"value":{"result":1,"average":1,"field":1}
,"first":{"repetition":1}
,"extend":{"function":1}
,"repetitions":{"exceed":1,"calculated":1,"holds":1,"function":1}
,"exceed":{"number":1}
,"number":{"repetitions":1,"valid":1}
,"calculated":{"field":1}
,"ignored":{"calculated":1}
,"holds":{"field":1}
,"referenced":{"calculation":1}
,"calculation":{"repetitions":1}
,"returns":{"average":1}
,"average":{"value":1,"all":1}
,"all":{"valid":1}
,"non-blank":{"values":1,"value":1}
,"count":{"number":1}
,"ield":{"list":1}
,"list":{"concatenated":1,"non-blank":1}
,"concatenated":{"list":1}
,"max":{"valid":1}
,"min":{"valid":1}
,"stdev":{"standard":1}
,"standard":{"deviation":1}
,"deviation":{"sample":1,"population":1}
,"sample":{"represented":1}
,"represented":{"by":1}
,"by":{"series":1}
,"series":{"n-blank":1,"non-blank":1,"on-blank":1}
,"n-blank":{"values":1}
,"stdevp":{"standard":1}
,"population":{"represented":1}
,"total":{"all":1}
,"variance":{"variance":1,"sample":1,"population":1}
,"variancep":{"variance":1}
,"on-blank":{"values":1}
}
;Search.control.loadWordPairs(pairs);
