var pairs =
{
"upper":{"returns":1,"text":1,"function":1,"ca":1,"12n34p":1}
,"returns":{"all":1,"ca":1,"12n34p":1}
,"all":{"letters":1}
,"letters":{"text":1}
,"text":{"uppercase":1,"text":1,"-any":1,"expression":1,"field":1,"filemaker":1,"formatting":1}
,"uppercase":{"upper":1}
,"-any":{"text":1}
,"expression":{"text":1}
,"field":{"text":1,"displays":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"use":1}
,"use":{"upper":1}
,"function":{"ensure":1}
,"ensure":{"consistent":1}
,"consistent":{"data":1}
,"data":{"entry":1}
,"entry":{"state":1}
,"state":{"abbreviations":1}
,"abbreviations":{"postal":1}
,"postal":{"codes":1}
,"codes":{"change":1}
,"change":{"field":1}
,"displays":{"modifying":1}
,"modifying":{"contents":1}
,"contents":{"text":1}
,"formatting":{"functions":1}
,"functions":{"upper":1}
,"ca":{"returns":1,"upper":1}
,"12n34p":{"returns":1}
}
;Search.control.loadWordPairs(pairs);
