var pairs =
{
"formatting":{"graphics":1,"options":1,"graphic":1}
,"graphics":{"layout":1,"nserting":1,"inspector":1}
,"layout":{"format":1,"layout":1,"mode":1}
,"format":{"graphic":1,"list":1,"graphics":1}
,"graphic":{"references":1,"filemaker":1,"graphic":1,"button":1,"boundaries":1}
,"references":{"image":1}
,"image":{"file":1,"unaltered":1,"if":1,"up":1,"fit":1,"distorted":1}
,"file":{"disk":1,"nformation":1}
,"disk":{"affect":1}
,"affect":{"graphic":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"formatting":1,"rops":1}
,"options":{"change":1}
,"change":{"original":1}
,"original":{"image":1,"proportions":1}
,"nformation":{"inserting":1}
,"inserting":{"graphics":1}
,"nserting":{"graphics":1}
,"mode":{"select":1}
,"select":{"inserted":1,"formats":1,"maintain":1}
,"inserted":{"graphics":1}
,"inspector":{"data":1}
,"data":{"data":1,"tab":1,"formatting":1}
,"tab":{"data":1}
,"button":{"select":1}
,"formats":{"want":1}
,"want":{"use":1}
,"use":{"display":1}
,"display":{"image":1}
,"unaltered":{"size":1}
,"size":{"format":1}
,"list":{"choose":1}
,"choose":{"crop":1,"reduce":1,"horizontal":1}
,"crop":{"frame":1}
,"frame":{"filemaker":1}
,"rops":{"image":1}
,"if":{"large":1}
,"large":{"fit":1}
,"fit":{"graphic":1,"boundaries":1,"enlarge":1,"reduce":1,"select":1,"proportions":1}
,"boundaries":{"scale":1,"format":1,"set":1}
,"scale":{"image":1}
,"up":{"up":1,"fit":1}
,"reduce":{"image":1,"enlarge":1}
,"enlarge":{"image":1}
,"maintain":{"original":1}
,"proportions":{"image":1,"boundaries":1}
,"distorted":{"fit":1}
,"set":{"image\u2019s":1}
,"image\u2019s":{"horizontal":1}
,"horizontal":{"vertical":1}
,"vertical":{"alignment":1,"alignments":1}
,"alignment":{"alignment":1,"choose":1}
,"alignments":{"images":1}
,"images":{"format":1}
}
;Search.control.loadWordPairs(pairs);
