var pairs =
{
"proper":{"returns":1,"text":1,"abcd":1,"name":1}
,"returns":{"first":1,"abcd":1,"yumiko":1}
,"first":{"letter":1}
,"letter":{"each":1}
,"each":{"word":1}
,"word":{"text":1}
,"text":{"uppercase":1,"text":1,"-any":1,"expression":1,"field":1,"filemaker":1}
,"uppercase":{"all":1}
,"all":{"letters":1}
,"letters":{"lowercase":1}
,"lowercase":{"proper":1}
,"-any":{"text":1}
,"expression":{"text":1}
,"field":{"text":1,"yumiko":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"proper":1}
,"abcd":{"returns":1,"proper":1}
,"name":{"returns":1,"field":1}
,"yumiko":{"kitagawa":1}
,"kitagawa":{"name":1}
}
;Search.control.loadWordPairs(pairs);
