var pairs =
{
"maintaining":{"recovering":1}
,"recovering":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"databases":1,"database":1,"manages":1,"disk-based":1,"runs":1,"attempt":1,"files":1}
,"databases":{"power":1,"regular":1}
,"power":{"failures":1,"supply":1,"outages":1}
,"failures":{"hardware":1}
,"hardware":{"problems":1}
,"problems":{"factors":1,"if":1,"potentially":1}
,"factors":{"damage":1}
,"damage":{"filemaker":1,"unexpected":1}
,"database":{"file":1,"ram":1,"filemaker":1,"requires":1,"corruption":1}
,"file":{"recover":1,"recommended":1,"corruption":1,"application":1,"updated":1,"damage":1,"hard-drive":1,"file":1,"usually":1,"require":1,"recovering":1,"maintenance":1,"recovery":1}
,"recover":{"feature":1,"file":1}
,"feature":{"salvage":1}
,"salvage":{"damaged":1}
,"damaged":{"file":1}
,"recommended":{"perform":1}
,"perform":{"regular":1}
,"regular":{"maintenance":1,"aintenance":1}
,"maintenance":{"filemaker":1,"file":1}
,"aintenance":{"takes":1}
,"takes":{"two":1}
,"two":{"forms":1}
,"forms":{"up":1}
,"up":{"saving":1}
,"saving":{"compacted":1}
,"compacted":{"copy":1}
,"copy":{"order":1}
,"order":{"understand":1}
,"understand":{"file":1}
,"corruption":{"occurs":1,"ensure":1}
,"occurs":{"filemaker":1,"file":1,"during":1}
,"manages":{"data":1}
,"data":{"filemaker":1,"hard":1,"written":1,"buffers":1}
,"disk-based":{"application":1}
,"application":{"load":1,"transfers":1,"termination":1}
,"load":{"entire":1}
,"entire":{"database":1}
,"ram":{"file":1,"back":1,"hard":1}
,"transfers":{"data":1}
,"hard":{"drive":1,"disk":1}
,"drive":{"ram":1,"common":1,"update":1,"hard":1,"fault":1,"disk":1,"current":1}
,"back":{"file":1}
,"updated":{"data":1}
,"written":{"data":1}
,"buffers":{"ram":1}
,"common":{"file":1,"database":1}
,"unexpected":{"application":1,"quit":1}
,"termination":{"quit":1,"common":1}
,"quit":{"cases":1,"occurs":1}
,"cases":{"unexpected":1,"multiple":1}
,"hard-drive":{"updates":1}
,"updates":{"situation":1}
,"situation":{"next":1}
,"next":{"time":1}
,"time":{"database":1}
,"runs":{"onsistency":1}
,"onsistency":{"check":1}
,"check":{"file":1,"filemaker":1,"hard":1}
,"usually":{"problems":1}
,"if":{"unexpected":1,"database":1,"problem":1,"files":1}
,"during":{"hard":1}
,"update":{"file":1}
,"require":{"recovery":1}
,"recovery":{"if":1}
,"requires":{"extensive":1}
,"extensive":{"correction":1}
,"correction":{"open":1}
,"open":{"consistency":1}
,"consistency":{"check":1}
,"attempt":{"recover":1}
,"files":{"unexpected":1,"subject":1,"hard":1}
,"ensure":{"operating":1}
,"operating":{"system":1}
,"system":{"stable":1,"file":1}
,"stable":{"un":1}
,"un":{"software":1}
,"software":{"absolutely":1,"conflict":1,"optimizes":1,"compatible":1}
,"absolutely":{"critical":1}
,"critical":{"machines":1}
,"machines":{"keeping":1}
,"keeping":{"configurations":1}
,"configurations":{"simple":1}
,"simple":{"reduces":1}
,"reduces":{"chance":1}
,"chance":{"software":1}
,"conflict":{"easier":1}
,"easier":{"troubleshoot":1}
,"troubleshoot":{"if":1}
,"problem":{"use":1}
,"use":{"uninterruptible":1}
,"uninterruptible":{"power":1}
,"supply":{"if":1}
,"subject":{"power":1}
,"outages":{"all":1}
,"all":{"hard":1}
,"disk":{"problems":1,"utility":1}
,"potentially":{"cases":1}
,"multiple":{"corrupted":1}
,"corrupted":{"files":1}
,"fault":{"check":1}
,"utility":{"program":1}
,"program":{"software":1}
,"optimizes":{"compresses":1}
,"compresses":{"partitions":1}
,"partitions":{"hard":1}
,"current":{"version":1}
,"version":{"driver":1,"operating":1}
,"driver":{"software":1}
,"compatible":{"version":1}
}
;Search.control.loadWordPairs(pairs);
