var pairs =
{
"opying":{"moving":1}
,"moving":{"data":1}
,"data":{"records":1,"choose":1,"record":1,"tab":1,"container":1,"copied":1}
,"records":{"browse":1,"portal":1,"current":1,"found":1}
,"browse":{"mode":1}
,"mode":{"copy":1}
,"copy":{"move":1,"cut":1,"value":1,"values":1,"application":1,"all":1,"note":1,"paste":1,"record":1,"current":1}
,"move":{"value":1}
,"value":{"field":1}
,"field":{"select":1,"choose":1,"hold":1,"last":1,"want":1,"selected":1}
,"select":{"contents":1}
,"contents":{"field":1,"individual":1,"multiple":1}
,"choose":{"edit":1,"insert":1}
,"edit":{"menu":1}
,"menu":{"copy":1,"paste":1,"last":1}
,"cut":{"display":1}
,"display":{"record":1,"records":1}
,"record":{"if":1,"accessed":1,"copy":1,"application":1,"clipboard":1,"including":1,"copied":1,"found":1}
,"if":{"field":1,"tab":1}
,"hold":{"data":1,"text":1}
,"paste":{"copy":1,"record":1,"text":1,"contents":1}
,"last":{"record":1,"visited":1}
,"accessed":{"field":1}
,"want":{"hold":1}
,"insert":{"menu":1}
,"visited":{"record":1}
,"values":{"record":1}
,"application":{"field":1,"paste":1}
,"selected":{"choose":1,"press":1}
,"clipboard":{"copy":1,"data":1,"formatting":1,"copying":1}
,"all":{"data":1,"records":1}
,"including":{"related":1}
,"related":{"records":1}
,"portal":{"fields":1}
,"fields":{"tab":1,"selected":1,"copied":1,"data":1,"layout":1}
,"tab":{"panels":1}
,"panels":{"slide":1,"front":1,"frontmost":1}
,"slide":{"panels":1}
,"front":{"ost":1,"fields":1}
,"ost":{"panel":1}
,"panel":{"fields":1,"closed":1}
,"note":{"fields":1}
,"copied":{"if":1,"except":1,"tab-delimited":1}
,"frontmost":{"panel":1}
,"closed":{"popovers":1}
,"popovers":{"portals":1}
,"portals":{"display":1}
,"current":{"table":1,"record":1}
,"table":{"copy":1,"view":1}
,"found":{"set":1}
,"set":{"clipboard":1}
,"press":{"shift":1}
,"shift":{"windows":1}
,"windows":{"option":1}
,"option":{"macos":1}
,"macos":{"while":1}
,"while":{"choosing":1}
,"choosing":{"edit":1}
,"text":{"clipboard":1,"choose":1,"paste":1}
,"formatting":{"bold":1}
,"bold":{"italic":1}
,"italic":{"field":1}
,"except":{"data":1}
,"container":{"fields":1}
,"tab-delimited":{"format":1}
,"format":{"order":1}
,"order":{"fields":1}
,"layout":{"ou":1}
,"ou":{"copy":1}
,"individual":{"cells":1}
,"cells":{"table":1,"copy":1}
,"view":{"copy":1}
,"multiple":{"cells":1}
,"copying":{"pasting":1}
,"pasting":{"copy":1}
}
;Search.control.loadWordPairs(pairs);
