var pairs =
{
"onlayoutsizechange":{"performs":1}
,"performs":{"script":1}
,"script":{"fter":1,"step":1,"rigger":1,"runs":1}
,"fter":{"layout":1}
,"layout":{"window":1}
,"window":{"changed":1,"first":1,"by":1,"orientation":1,"mouse":1,"script":1}
,"changed":{"size":1}
,"size":{"result":1,"layout":1}
,"result":{"filemaker":1}
,"filemaker":{"go":1,"pro":1,"webdirect":1}
,"go":{"rotating":1}
,"rotating":{"ios":1}
,"ios":{"device":1}
,"device":{"hiding":1}
,"hiding":{"status":1}
,"status":{"toolbar":1}
,"toolbar":{"window":1,"formatting":1}
,"first":{"filemaker":1,"event":1}
,"pro":{"advanced":1,"13.0":1}
,"advanced":{"filemaker":1}
,"webdirect":{"changing":1}
,"changing":{"size":1}
,"by":{"user":1,"script":1,"hiding":1}
,"user":{"interaction":1}
,"interaction":{"by":1}
,"step":{"by":1,"window":1}
,"formatting":{"bar":1}
,"bar":{"via":1}
,"via":{"menu":1}
,"menu":{"command":1}
,"command":{"shortcut":1}
,"shortcut":{"script":1}
,"event":{"processed":1}
,"processed":{"browse":1}
,"browse":{"find":1}
,"find":{"modes":1}
,"modes":{"none":1,"trigger":1}
,"none":{"filemaker":1}
,"13.0":{"use":1}
,"use":{"get":1}
,"get":{"windoworientation":1}
,"windoworientation":{"function":1}
,"function":{"return":1}
,"return":{"current":1}
,"current":{"window":1}
,"orientation":{"if":1}
,"if":{"resize":1}
,"resize":{"window":1}
,"mouse":{"script":1}
,"rigger":{"activates":1}
,"activates":{"finish":1}
,"finish":{"resizing":1}
,"resizing":{"window":1}
,"runs":{"modes":1}
,"trigger":{"result":1}
}
;Search.control.loadWordPairs(pairs);
