var pairs =
{
"delete":{"all":1}
,"all":{"records":1,"&get":1}
,"records":{"eletes":1,"current":1,"filemaker":1,"delete":1,"attempts":1,"found":1,"group":1,"first":1,"stops":1,"script":1,"if":1,"[with":1,"automating":1}
,"eletes":{"all":1}
,"current":{"found":1,"table":1}
,"found":{"set":1,"\u0022]":1}
,"set":{"dialog":1,"deleting":1,"show":1}
,"dialog":{"specifies":1,"box":1,"on]":1,"[\u0022":1,"off]":1}
,"specifies":{"display":1}
,"display":{"dialog":1}
,"box":{"script":1}
,"script":{"step":1}
,"step":{"performed":1,"deletes":1,"use":1}
,"performed":{"users":1}
,"users":{"confirm":1}
,"confirm":{"deletion":1}
,"deletion":{"all":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"undo":1}
,"undo":{"deleting":1}
,"deleting":{"records":1,"if":1}
,"attempts":{"lock":1}
,"lock":{"group":1,"all":1,"next":1}
,"group":{"records":1,"script":1,"if":1}
,"if":{"lock":1,"record":1,"user":1,"[get":1,"adding":1}
,"deletes":{"group":1}
,"next":{"group":1}
,"first":{"time":1}
,"time":{"can\u2019t":1}
,"can\u2019t":{"lock":1}
,"record":{"edited":1}
,"edited":{"by":1}
,"by":{"user":1}
,"user":{"delete":1}
,"stops":{"returns":1}
,"returns":{"error":1}
,"error":{"code":1}
,"code":{"captured":1}
,"captured":{"get":1}
,"get":{"lasterror":1}
,"lasterror":{"function":1}
,"function":{"delete":1}
,"table":{"use":1,"show":1}
,"use":{"show":1,"delete":1}
,"show":{"all":1,"custom":1}
,"[with":{"dialog":1}
,"on]":{"if":1}
,"custom":{"dialog":1}
,"[\u0022":{"want":1}
,"want":{"delete":1}
,"&get":{"foundcount":1}
,"foundcount":{"&\u0022":1}
,"&\u0022":{"records":1}
,"\u0022]":{"if":1}
,"[get":{"lastmessagechoice":1}
,"lastmessagechoice":{"=1]":1}
,"=1]":{"delete":1}
,"off]":{"end":1}
,"end":{"if":1}
,"adding":{"duplicating":1}
,"duplicating":{"deleting":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
