var pairs =
{
"getwidth":{"returns":1,"field":1,"product":1}
,"returns":{"width":1,"getwidth":1,"1024":1}
,"width":{"pixels":1}
,"pixels":{"content":1,"images":1}
,"content":{"container":1}
,"container":{"field":1}
,"field":{"holds":1,"field":1,"-any":1,"text":1}
,"holds":{"images":1}
,"images":{"getwidth":1,"container":1}
,"-any":{"text":1}
,"text":{"number":1,"expression":1}
,"number":{"date":1,"filemaker":1}
,"date":{"time":1}
,"time":{"timestamp":1}
,"timestamp":{"container":1}
,"expression":{"numeric":1,"number":1}
,"numeric":{"expression":1}
,"filemaker":{"pro":1}
,"pro":{"12.0":1}
,"12.0":{"returns":1}
,"product":{"returns":1}
}
;Search.control.loadWordPairs(pairs);
