var pairs =
{
"illing":{"color":1}
,"color":{"gradient":1,"stops":1,"stop":1,"color":1,"palette":1}
,"gradient":{"note":1,"sure":1,"gradient":1,"control":1,"color":1,"drag":1,"button":1,"blends":1,"center":1,"layout":1,"colors":1,"style":1,"object":1}
,"note":{"filling":1}
,"filling":{"layout":1}
,"layout":{"background":1,"parts":1,"mode":1,"drag":1}
,"background":{"ith":1,"select":1,"sure":1,"fill":1}
,"ith":{"color":1}
,"sure":{"fill":1,"objects":1}
,"fill":{"layout":1,"line":1,"choose":1,"blended":1,"extend":1}
,"parts":{"transparent":1,"selected":1,"images":1}
,"transparent":{"setting":1}
,"setting":{"fill":1}
,"line":{"style":1}
,"style":{"shadows":1,"button":1}
,"shadows":{"padding":1}
,"padding":{"layout":1}
,"mode":{"select":1}
,"select":{"objects":1,"selecting":1}
,"objects":{"part":1,"layout":1}
,"part":{"label":1,"it\u2019s":1}
,"label":{"layout":1}
,"selecting":{"layout":1}
,"selected":{"inspector":1,"object":1}
,"inspector":{"appearance":1}
,"appearance":{"appearance":1,"tab":1,"object":1}
,"tab":{"change":1}
,"change":{"appearance":1,"direction":1,"linear":1,"start":1,"gradient":1}
,"object":{"body":1,"state":1,"graphic":1,"reverse":1,"use":1,"layout":1}
,"body":{"part":1}
,"it\u2019s":{"state":1}
,"state":{"button":1,"list":1,"object":1}
,"button":{"pressed":1,"radial":1,"change":1}
,"pressed":{"choose":1}
,"choose":{"object":1,"gradient":1,"color":1}
,"list":{"top":1}
,"top":{"ab":1}
,"ab":{"display":1}
,"display":{"state":1}
,"graphic":{"fill":1}
,"control":{"colors":1,"gradient":1,"choose":1,"add":1,"change":1,"angle":1,"image":1,"selected":1,"control":1,"object":1}
,"colors":{"blended":1,"left":1}
,"blended":{"color":1,"linear":1}
,"stops":{"gradient":1,"reduce":1}
,"stop":{"control":1}
,"palette":{"add":1}
,"add":{"olors":1,"color":1}
,"olors":{"color":1,"gradient":1}
,"reduce":{"olors":1}
,"drag":{"color":1,"angle":1,"blue":1}
,"direction":{"fill":1}
,"linear":{"gradient":1,"color":1}
,"radial":{"gradient":1,"color":1}
,"blends":{"angle":1}
,"angle":{"enter":1,"control":1}
,"enter":{"value":1}
,"value":{"macos":1}
,"macos":{"drag":1}
,"start":{"end":1}
,"end":{"points":1}
,"points":{"linear":1}
,"center":{"point":1,"change":1}
,"point":{"radius":1}
,"radius":{"radial":1}
,"blue":{"handle":1}
,"handle":{"gradient":1}
,"image":{"radial":1}
,"reverse":{"gradient":1}
,"left":{"right":1}
,"right":{"center":1}
,"use":{"color":1}
,"extend":{"behind":1}
,"behind":{"navigation":1}
,"navigation":{"parts":1}
}
;Search.control.loadWordPairs(pairs);
