var pairs =
{
"related":{"tables":1,"table":1,"data":1,"records":1,"fields":1,"re":1}
,"tables":{"create":1,"relational":1,"hat":1,"typical":1,"customers":1,"ecause":1,"elements":1}
,"create":{"relational":1}
,"relational":{"database":1}
,"database":{"allow":1,"consists":1,"illustrating":1,"it\u2019s":1,"related":1}
,"allow":{"data":1}
,"data":{"tables":1,"stored":1,"dynamically":1,"place":1,"changed":1,"up-to-date":1,"current":1,"efficiently":1,"related":1,"each":1,"nd":1,"data":1,"products":1,"source":1}
,"consists":{"ne":1}
,"ne":{"related":1}
,"hat":{"contain":1}
,"contain":{"ou":1}
,"ou":{"ach":1}
,"ach":{"instance":1}
,"instance":{"data":1,"related":1}
,"stored":{"table":1,"two":1}
,"table":{"time":1,"change":1,"copy":1,"define":1,"file":1}
,"time":{"accessed":1,"copied":1}
,"accessed":{"displayed":1}
,"displayed":{"related":1,"each":1,"lineitems":1}
,"change":{"instance":1,"data":1,"lineitems":1}
,"dynamically":{"all":1,"layout":1}
,"all":{"change":1}
,"place":{"data":1}
,"changed":{"appears":1}
,"appears":{"data":1}
,"up-to-date":{"elational":1}
,"elational":{"databases":1}
,"databases":{"allow":1}
,"current":{"state":1,"table":1,"time":1,"prices":1}
,"state":{"set":1}
,"set":{"up":1}
,"up":{"manage":1,"efining":1}
,"manage":{"data":1}
,"efficiently":{"flexibility":1}
,"flexibility":{"save":1}
,"save":{"disk":1}
,"disk":{"space":1}
,"space":{"retrieve":1}
,"retrieve":{"data":1}
,"copy":{"current":1}
,"define":{"lookup":1}
,"lookup":{"copied":1,"th":1}
,"copied":{"data":1,"pasted":1,"copied":1,"remains":1}
,"two":{"just":1,"tables":1}
,"just":{"if":1}
,"if":{"copied":1,"price":1}
,"pasted":{"target":1}
,"target":{"field":1}
,"field":{"looked-up":1}
,"looked-up":{"data":1}
,"remains":{"static":1}
,"static":{"looked":1,"relationships":1,"ata":1,"entered":1}
,"looked":{"up":1}
,"efining":{"updating":1}
,"updating":{"lookups":1}
,"lookups":{"concept":1,"display":1}
,"concept":{"art":1}
,"art":{"dynamic":1}
,"dynamic":{"static":1,"data":1}
,"relationships":{"two":1}
,"typical":{"sales":1}
,"sales":{"solution":1,"data":1,"price":1}
,"solution":{"tables":1,"visit":1}
,"customers":{"stores":1,"lineitems":1,"isplayed":1}
,"stores":{"customer":1,"products":1,"sales":1}
,"customer":{"customer":1,"names":1}
,"names":{"contact":1}
,"contact":{"products":1}
,"products":{"stores":1,"current":1,"displayed":1}
,"prices":{"ineitems":1}
,"ineitems":{"stores":1}
,"each":{"line":1,"invoice":1,"record":1}
,"line":{"nvoice":1,"item":1}
,"nvoice":{"including":1}
,"including":{"item":1}
,"item":{"old":1,"static":1}
,"old":{"quantity":1}
,"quantity":{"price":1}
,"price":{"sold":1,"each":1,"items":1}
,"sold":{"invoices":1}
,"invoices":{"record":1,"mix":1,"data":1,"layout":1,"database":1}
,"record":{"each":1,"related":1}
,"invoice":{"displayed":1,"remain":1}
,"records":{"customers":1}
,"lineitems":{"tables":1,"sales":1,"portal":1,"invoices":1}
,"ecause":{"invoices":1}
,"mix":{"ture":1}
,"ture":{"dynamic":1}
,"nd":{"static":1}
,"ata":{"use":1}
,"use":{"related":1}
,"fields":{"lookups":1}
,"display":{"data":1}
,"re":{"cords":1}
,"cords":{"customers":1}
,"isplayed":{"dynamically":1}
,"layout":{"invoices":1,"lookup":1}
,"entered":{"lineitems":1}
,"portal":{"invoices":1}
,"th":{"otals":1}
,"otals":{"invoice":1}
,"remain":{"unchanged":1}
,"unchanged":{"if":1}
,"items":{"change":1}
,"illustrating":{"building":1}
,"building":{"relational":1}
,"it\u2019s":{"plan":1}
,"plan":{"first":1}
,"first":{"planning":1}
,"planning":{"relational":1}
,"elements":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"solution":1}
,"visit":{"page":1}
,"page":{"english":1}
,"english":{"related":1}
,"file":{"external":1}
,"external":{"data":1}
}
;Search.control.loadWordPairs(pairs);
