var pairs =
{
"printer":{"paper":1,"choose":1,"print":1,"windows":1,"if":1,"filemaker":1,"cases":1,"selected":1,"sets":1}
,"paper":{"options":1,"orientation":1,"size":1}
,"options":{"filemaker":1,"each":1,"want":1,"saved":1,"print":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1,"dvanced":1}
,"advanced":{"prints":1,"paper":1,"macos":1,"subsequent":1}
,"prints":{"default":1,"layout":1}
,"default":{"printer":1,"by":1}
,"choose":{"printer":1,"file":1,"properties":1,"specific":1}
,"print":{"filemaker":1,"setup":1,"documents":1,"layout":1,"labels":1,"preprinted":1,"script":1}
,"orientation":{"options":1,"windows":1,"scale":1}
,"each":{"filemaker":1}
,"dvanced":{"file":1}
,"file":{"file":1,"open":1,"menu":1,"print":1,"choosing":1}
,"open":{"choose":1}
,"menu":{"page":1}
,"page":{"setup":1}
,"setup":{"preview":1,"windows":1,"macos":1,"print":1,"script":1}
,"preview":{"mode":1}
,"mode":{"print":1}
,"windows":{"page":1,"printer":1,"paper":1}
,"macos":{"status":1,"format":1,"options":1}
,"status":{"toolbar":1}
,"toolbar":{"choose":1}
,"if":{"set":1,"use":1,"regularly":1}
,"set":{"properties":1,"options":1}
,"properties":{"printer":1,"default":1}
,"format":{"select":1}
,"select":{"printer":1}
,"specific":{"printer":1}
,"cases":{"leave":1}
,"leave":{"printer":1}
,"selected":{"choose":1}
,"use":{"exclusively":1,"printer":1}
,"exclusively":{"print":1}
,"documents":{"set":1}
,"want":{"paper":1,"create":1,"automating":1}
,"size":{"orientation":1}
,"scale":{"macos":1}
,"saved":{"current":1}
,"current":{"file":1}
,"layout":{"file":1,"printer":1,"script":1}
,"choosing":{"printer":1}
,"sets":{"default":1}
,"by":{"filemaker":1}
,"subsequent":{"printing":1}
,"printing":{"operations":1}
,"operations":{"script":1}
,"script":{"step":1,"prints":1,"contain":1,"steps":1}
,"step":{"defined":1,"print":1,"printer":1}
,"defined":{"use":1}
,"regularly":{"print":1}
,"labels":{"print":1}
,"preprinted":{"form":1}
,"form":{"want":1}
,"create":{"script":1}
,"contain":{"print":1}
,"steps":{"store":1}
,"store":{"recall":1}
,"recall":{"printer":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
,"scripts":{"print":1}
}
;Search.control.loadWordPairs(pairs);
