var pairs =
{
"creating":{"runtime":1,"solution":1}
,"runtime":{"solution":1,"solutions":1,"application":1,"applications":1,"database":1,"solutio":1,"folder":1}
,"solution":{"note":1,"decide":1,"components":1,"custom":1,"multiple":1,"ensure":1,"versions":1,"respective":1,"folder":1,"if":1,"create":1,"ocumenting":1,"developer":1}
,"note":{"topic":1}
,"topic":{"describes":1}
,"describes":{"features":1}
,"features":{"use":1}
,"use":{"advanced":1,"file":1,"copy":1}
,"advanced":{"tools":1,"order":1,"runtime":1,"full":1}
,"tools":{"general":1,"yo":1,"re":1}
,"general":{"preference":1}
,"preference":{"selected":1}
,"selected":{"ad":1}
,"ad":{"vanced":1}
,"vanced":{"tools":1}
,"yo":{"bind":1}
,"bind":{"filemaker":1,"database":1,"solutions":1}
,"filemaker":{"database":1,"pro":1,"pr":1}
,"database":{"files":1,"solution":1,"file":1,"ilemaker":1,"bind":1}
,"files":{"runtime":1,"scripts":1,"return":1,"odbc":1,"times":1,"multiple":1,"solution":1,"folder":1,"decide":1,"layout":1,"layouts":1}
,"solutions":{"solutions":1,"require":1,"kiosk":1,"tooltips":1,"charts":1,"create":1}
,"require":{"filemaker":1,"specific":1}
,"pro":{"advanced":1}
,"order":{"computer":1}
,"computer":{"create":1}
,"create":{"runtime":1,"scripts":1,"documentation":1}
,"kiosk":{"mode":1}
,"mode":{"build":1}
,"build":{"database":1}
,"decide":{"users":1,"file":1}
,"users":{"interact":1,"completed":1,"open":1,"navigate":1}
,"interact":{"database":1}
,"components":{"primary":1}
,"primary":{"database":1,"file":1}
,"file":{"connects":1,"display":1,"menu":1,"all":1,"just":1,"that\u2019s":1,"primary":1,"users":1,"stores":1,"navigation":1,"quit":1,"auxiliary":1,"original":1}
,"connects":{"all":1}
,"all":{"auxiliary":1,"files":1,"data":1}
,"auxiliary":{"files":1}
,"scripts":{"buttons":1,"auxiliary":1}
,"buttons":{"open":1,"scripts":1,"users":1}
,"open":{"auxiliary":1,"first":1}
,"return":{"primary":1}
,"display":{"splash":1}
,"splash":{"screen":1}
,"screen":{"layout":1}
,"layout":{"startup":1,"introduce":1,"custom":1,"file":1}
,"startup":{"quit":1}
,"quit":{"runtime":1,"application":1}
,"application":{"common":1,"runtime":1,"ifferences":1,"filemaker":1,"tarting":1}
,"common":{"elements":1}
,"elements":{"consistent":1}
,"consistent":{"appearance":1}
,"appearance":{"cross-platform":1}
,"cross-platform":{"solutions":1}
,"tooltips":{"custom":1}
,"custom":{"menus":1,"help":1,"settings":1}
,"menus":{"layout":1,"specific":1}
,"introduce":{"solution":1}
,"help":{"system":1,"layout":1}
,"system":{"usage":1}
,"usage":{"tips":1}
,"tips":{"solution":1}
,"multiple":{"privilege":1,"files":1,"tables":1,"database":1}
,"privilege":{"sets":1}
,"sets":{"levels":1,"determine":1}
,"levels":{"access":1}
,"access":{"layouts":1,"account":1,"privileges":1,"database":1}
,"layouts":{"menus":1,"solution":1}
,"specific":{"tables":1,"plug-in":1}
,"tables":{"record":1,"single":1}
,"record":{"fields":1}
,"fields":{"password-protected":1}
,"password-protected":{"accounts":1}
,"accounts":{"assigned":1}
,"assigned":{"privilege":1}
,"determine":{"level":1}
,"level":{"access":1}
,"account":{"user":1}
,"user":{"advanced":1}
,"re":{"stripped":1}
,"stripped":{"runtime":1}
,"applications":{"none":1,"shared":1,"enabled":1}
,"none":{"commands":1}
,"commands":{"file":1}
,"menu":{"manage":1}
,"manage":{"submenu":1}
,"submenu":{"runtime":1}
,"shared":{"network":1}
,"network":{"include":1}
,"include":{"ability":1,"data":1}
,"ability":{"save\u002Fsend":1}
,"save\u002Fsend":{"records":1}
,"records":{"pdf":1}
,"pdf":{"files":1}
,"odbc":{"import":1,"data":1}
,"import":{"execute":1}
,"execute":{"sql":1}
,"sql":{"script":1}
,"script":{"step":1}
,"step":{"odbc":1}
,"data":{"sources":1,"source":1}
,"sources":{"relationships":1,"updated":1}
,"relationships":{"graph":1}
,"graph":{"supported":1}
,"supported":{"runtime":1}
,"ifferences":{"runtime":1}
,"pr":{"advanced":1}
,"ilemaker":{"pro":1}
,"full":{"functionality":1,"access":1}
,"functionality":{"applications":1}
,"enabled":{"except":1}
,"except":{"if":1}
,"if":{"full":1,"you\u2019re":1,"multiple":1,"practical":1,"modify":1,"distribute":1}
,"privileges":{"removed":1}
,"removed":{"removing":1}
,"removing":{"admin":1}
,"admin":{"access":1}
,"times":{"prepare":1}
,"prepare":{"delivery":1}
,"delivery":{"users":1}
,"completed":{"development":1}
,"development":{"final":1}
,"final":{"version":1}
,"version":{"bound":1}
,"bound":{"ready":1,"runtime":1}
,"ready":{"distribute":1}
,"distribute":{"test":1,"databases":1}
,"test":{"runtime":1,"versions":1}
,"ensure":{"behaves":1}
,"behaves":{"expected":1}
,"expected":{"preparing":1}
,"preparing":{"files":1}
,"solutio":{"if":1}
,"you\u2019re":{"creating":1}
,"versions":{"windows":1,"solution":1,"place":1}
,"windows":{"macos":1}
,"macos":{"test":1}
,"respective":{"platforms":1}
,"platforms":{"if":1}
,"single":{"file":1}
,"folder":{"bound":1,"sure":1,"created":1}
,"practical":{"keep":1}
,"keep":{"all":1}
,"sure":{"include":1,"file":1}
,"source":{"reference":1}
,"reference":{"each":1}
,"each":{"file":1}
,"just":{"filename":1}
,"filename":{"sure":1}
,"that\u2019s":{"related":1}
,"related":{"database":1}
,"modify":{"filenames":1}
,"filenames":{"all":1}
,"updated":{"if":1}
,"first":{"primary":1}
,"stores":{"custom":1}
,"settings":{"use":1}
,"navigation":{"buttons":1}
,"tarting":{"runtime":1}
,"navigate":{"primary":1}
,"databases":{"runtime":1}
,"plug-in":{"versions":1}
,"place":{"plug-ins":1}
,"plug-ins":{"runtime":1}
,"created":{"bind":1}
,"charts":{"supported":1}
,"documentation":{"database":1}
,"ocumenting":{"developer":1}
,"developer":{"solution":1,"utilities":1}
,"utilities":{"use":1}
,"copy":{"file":1}
,"original":{"it\u2019s":1,"files":1}
,"it\u2019s":{"idea":1}
,"idea":{"backup":1}
,"backup":{"opy":1}
,"opy":{"original":1}
}
;Search.control.loadWordPairs(pairs);
