var pairs =
{
"select":{"dictionaries":1}
,"dictionaries":{"pens":1,"dialog":1,"use":1,"check":1}
,"pens":{"select":1}
,"dialog":{"box":1}
,"box":{"none":1,"users":1,"checks":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1,"advanced":1}
,"6.0":{"earlier":1}
,"earlier":{"script":1}
,"script":{"step":1}
,"step":{"choosing":1,"open":1}
,"choosing":{"edit":1}
,"edit":{"menu":1}
,"menu":{"spelling":1}
,"spelling":{"select":1,"all":1}
,"use":{"script":1}
,"open":{"select":1}
,"users":{"if":1}
,"if":{"restricted":1}
,"restricted":{"access":1}
,"access":{"filemaker":1}
,"advanced":{"menus":1}
,"menus":{"select":1}
,"checks":{"spelling":1}
,"all":{"fields":1}
,"fields":{"current":1}
,"current":{"record":1}
,"record":{"select":1,"replacing":1}
,"check":{"record":1}
,"replacing":{"contents":1}
,"contents":{"field":1}
,"field":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
