var pairs =
{
"onobjectsave":{"performs":1}
,"performs":{"script":1}
,"script":{"fter":1,"script":1,"step":1,"return":1,"proceeds":1,"canceled":1,"remains":1,"trigger":1,"triggers":1,"runs":1}
,"fter":{"object":1}
,"object":{"data":1,"saved":1}
,"data":{"validated":1,"changed":1}
,"validated":{"saved":1}
,"saved":{"field":1}
,"field":{"exited":1,"active":1,"data":1}
,"exited":{"event":1}
,"event":{"processed":1,"triggered":1}
,"processed":{"browse":1}
,"browse":{"find":1}
,"find":{"modes":1}
,"modes":{"use":1,"trigger":1}
,"use":{"exit":1}
,"exit":{"script":1}
,"step":{"ithin":1}
,"ithin":{"triggered":1}
,"triggered":{"script":1}
,"return":{"true":1}
,"true":{"false":1,"event":1}
,"false":{"true":1,"event":1}
,"proceeds":{"false":1}
,"canceled":{"object":1}
,"active":{"event":1,"filemaker":1}
,"remains":{"active":1}
,"filemaker":{"pro":1}
,"pro":{"10.0":1}
,"10.0":{"script":1}
,"trigger":{"activates":1,"script":1,"result":1}
,"activates":{"selected":1}
,"selected":{"field":1}
,"changed":{"actions":1}
,"actions":{"don\u2019t":1,"trigger":1}
,"don\u2019t":{"activate":1}
,"activate":{"script":1}
,"triggers":{"list":1}
,"list":{"actions":1}
,"runs":{"modes":1}
}
;Search.control.loadWordPairs(pairs);
