var pairs =
{
"get":{"data":1}
,"data":{"file":1,"file\u2019s":1,"read":1,"source":1}
,"file":{"position":1,"file":1,"id":1,"target":1,"first":1,"read":1,"named":1,"displays":1,"[\u0022$file":1,"[file":1}
,"position":{"returns":1,"open":1,"if":1,"file":1,"moves":1,"script":1,"[file":1,"last":1,"&$position":1}
,"returns":{"read-write":1}
,"read-write":{"position":1}
,"open":{"data":1,"file":1}
,"id":{"numeric":1,"open":1,"get":1,"target":1,"$fileid":1}
,"numeric":{"expression":1}
,"expression":{"specifies":1}
,"specifies":{"file":1}
,"target":{"field":1,"$position]":1,"$fileid":1,"$position":1}
,"field":{"variable":1,"file":1,"completed":1}
,"variable":{"store":1,"doesn\u2019t":1,"current":1,"[$file":1}
,"store":{"data":1}
,"file\u2019s":{"read-write":1}
,"if":{"variable":1,"field":1}
,"doesn\u2019t":{"exist":1}
,"exist":{"script":1}
,"script":{"step":1}
,"step":{"creates":1,"sets":1}
,"creates":{"sing":1,"file":1}
,"sing":{"variables":1}
,"variables":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"18.0":1}
,"18.0":{"advanced":1}
,"advanced":{"data":1}
,"first":{"read-write":1}
,"read":{"written":1}
,"written":{"read-write":1,"set":1}
,"moves":{"point":1}
,"point":{"data":1}
,"set":{"data":1,"variable":1}
,"sets":{"variable":1}
,"current":{"read-write":1}
,"[file":{"id":1}
,"$position]":{"creates":1}
,"named":{"change.log":1}
,"change.log":{"writes":1,"create":1}
,"writes":{"contents":1}
,"contents":{"products":1}
,"products":{":status":1}
,":status":{"field":1,"write":1}
,"displays":{"read-write":1}
,"completed":{"result":1}
,"result":{"displayed":1}
,"displayed":{"current":1}
,"last":{"byte":1}
,"byte":{"written":1}
,"[$file":{"value":1}
,"value":{"change.log":1}
,"create":{"data":1,"folders":1}
,"[\u0022$file":{"create":1,"target":1}
,"folders":{"open":1}
,"$fileid":{"write":1,"data":1,"target":1,"automating":1}
,"write":{"data":1,"utf-8":1}
,"source":{"products":1}
,"utf-8":{"get":1}
,"$position":{"show":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"dialog":{"[\u0022":1}
,"[\u0022":{"current":1}
,"&$position":{"close":1}
,"close":{"data":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
