var pairs =
{
"ormatting":{"text":1}
,"text":{"browse":1,"attributes":1,"number":1,"select":1,"field":1}
,"browse":{"mode":1}
,"mode":{"change":1,"layout":1,"formatting":1}
,"change":{"text":1,"paragraph":1}
,"attributes":{"font":1,"field":1,"browse":1}
,"font":{"size":1}
,"size":{"color":1}
,"color":{"style":1}
,"style":{"data":1}
,"data":{"text":1,"browse":1,"applies":1}
,"number":{"date":1}
,"date":{"time":1}
,"time":{"timestamp":1}
,"timestamp":{"fields":1}
,"fields":{"change":1}
,"paragraph":{"alignment":1}
,"alignment":{"margins":1}
,"margins":{"line":1}
,"line":{"spacing":1}
,"spacing":{"change":1}
,"field":{"data":1,"format":1,"choose":1}
,"layout":{"mode":1,"browse":1,"displays":1,"bar":1}
,"formatting":{"specific":1,"stored":1,"text":1,"bar":1,"formatting":1}
,"specific":{"layout":1}
,"stored":{"data":1}
,"applies":{"layout":1}
,"displays":{"field":1}
,"format":{"data":1,"menu":1}
,"select":{"text":1}
,"choose":{"command":1}
,"command":{"format":1}
,"menu":{"formatting":1}
,"bar":{"if":1,"formatting":1,"button":1,"change":1}
,"if":{"don\u2019t":1}
,"don\u2019t":{"formatting":1}
,"button":{"layout":1}
}
;Search.control.loadWordPairs(pairs);
