var pairs =
{
"getvalue":{"returns":1,"listofvalues":1,"london":1}
,"returns":{"requested":1,"value":1}
,"requested":{"value":1}
,"value":{"by":1,"return":1,"trailing":1}
,"by":{"valuenumber":1}
,"valuenumber":{"listofvalues":1,"-the":1}
,"listofvalues":{"getvalue":1,"valuenumber":1,"-a":1}
,"-a":{"list":1}
,"list":{"carriage":1,"text":1,"values":1}
,"carriage":{"return-delimited":1,"return":1}
,"return-delimited":{"values":1}
,"values":{"valuenumber":1,"valuecount":1}
,"-the":{"value":1}
,"return":{"list":1,"getvalue":1,"aris":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"8.0":1}
,"8.0":{"description":1}
,"description":{"list":1}
,"valuecount":{"function":1}
,"function":{"getvalue":1}
,"trailing":{"carriage":1}
,"london":{"paris":1}
,"paris":{"hong":1}
,"hong":{"kong":1}
,"kong":{"return":1}
}
;Search.control.loadWordPairs(pairs);
