var pairs =
{
"hanging":{"password":1}
,"password":{"file":1,"dialog":1,"change":1,"expires":1,"expire":1,"order":1,"want":1,"new":1,"fields":1}
,"file":{"filemaker":1,"occur":1,"administrator":1,"temporary":1,"password":1,"change":1,"menu":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"display":1}
,"display":{"change":1}
,"change":{"password":1,"first":1}
,"dialog":{"box":1}
,"box":{"open":1,"enter":1}
,"open":{"file":1}
,"occur":{"two":1}
,"two":{"situations":1}
,"situations":{"first":1}
,"first":{"time":1}
,"time":{"open":1}
,"administrator":{"file":1}
,"temporary":{"password":1}
,"expires":{"password":1}
,"expire":{"regular":1}
,"regular":{"interval":1}
,"interval":{"require":1}
,"require":{"new":1}
,"new":{"password":1}
,"order":{"open":1}
,"want":{"if":1}
,"if":{"privileges":1}
,"privileges":{"permit":1}
,"permit":{"ch":1}
,"ch":{"oose":1}
,"oose":{"file":1}
,"menu":{"change":1}
,"enter":{"old":1}
,"old":{"password":1}
,"fields":{"change":1}
}
;Search.control.loadWordPairs(pairs);
