var pairs =
{
"creating":{"managing":1,"layout":1}
,"managing":{"layouts":1}
,"layouts":{"reports":1,"don\u2019t":1,"display":1,"entering":1,"file":1,"database":1,"print":1}
,"reports":{"filemaker":1,"by":1,"group":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"ayouts":1}
,"ayouts":{"determine":1}
,"determine":{"organized":1}
,"organized":{"viewing":1}
,"viewing":{"printing":1}
,"printing":{"reporting":1,"mailing":1}
,"reporting":{"finding":1,"summaries":1}
,"finding":{"entering":1}
,"entering":{"data":1}
,"data":{"layouts":1,"just":1,"variety":1,"reporting":1,"graphically":1,"field":1,"grouped":1,"considerations":1}
,"don\u2019t":{"store":1}
,"store":{"data":1}
,"just":{"display":1}
,"display":{"database":1,"data":1,"default":1,"placing":1}
,"database":{"files":1,"file":1,"web":1,"create":1}
,"files":{"layouts":1}
,"variety":{"database":1}
,"file":{"design":1,"change":1}
,"design":{"separate":1,"data":1}
,"separate":{"layouts":1}
,"summaries":{"printing":1}
,"mailing":{"labels":1}
,"labels":{"displaying":1,"adding":1,"add":1}
,"displaying":{"data":1}
,"graphically":{"charts":1}
,"charts":{"database":1}
,"web":{"browser":1}
,"browser":{"touch":1}
,"touch":{"device":1}
,"device":{"change":1,"layout":1}
,"change":{"layout\u2019s":1,"data":1}
,"layout\u2019s":{"design":1}
,"field":{"reflected":1,"all":1,"objects":1,"labels":1}
,"reflected":{"field":1}
,"all":{"layouts":1}
,"create":{"layouts":1,"layout":1,"reports":1,"report":1}
,"by":{"new":1}
,"new":{"layout\u002Freport":1}
,"layout\u002Freport":{"assistant":1}
,"assistant":{"guides":1,"creating":1}
,"guides":{"creating":1}
,"layout":{"report":1,"display":1,"layout":1,"fields":1,"new":1,"choose":1,"mode":1,"parts":1,"creating":1,"records":1,"adding":1,"dimensions":1,"viewed":1,"resizing":1}
,"report":{"options":1,"layout":1}
,"options":{"choose":1}
,"choose":{"type":1,"fields":1}
,"type":{"device":1}
,"default":{"view":1}
,"view":{"layout":1}
,"fields":{"data":1,"display":1,"layou":1,"ormatting":1}
,"grouped":{"sorted":1}
,"sorted":{"create":1}
,"placing":{"removing":1}
,"removing":{"fields":1}
,"layou":{"arrange":1}
,"arrange":{"format":1}
,"format":{"fields":1}
,"ormatting":{"setting":1}
,"setting":{"up":1}
,"up":{"field":1}
,"objects":{"layout":1}
,"mode":{"add":1}
,"add":{"modify":1,"layout":1,"graphics":1,"emphasis":1}
,"modify":{"field":1}
,"adding":{"changing":1,"text":1}
,"changing":{"field":1,"width":1}
,"parts":{"organize":1,"create":1,"controlling":1}
,"organize":{"summarize":1}
,"summarize":{"layout":1,"data":1}
,"group":{"summarize":1}
,"considerations":{"create":1}
,"records":{"printed":1}
,"printed":{"controlling":1,"changing":1}
,"controlling":{"layouts":1}
,"print":{"add":1}
,"graphics":{"text":1,"layout":1}
,"text":{"add":1,"layout":1}
,"emphasis":{"interest":1}
,"interest":{"nserting":1}
,"nserting":{"graphics":1}
,"dimensions":{"layout":1}
,"viewed":{"printed":1}
,"width":{"layout":1}
,"resizing":{"layout":1}
}
;Search.control.loadWordPairs(pairs);
