var pairs =
{
"delete":{"file":1,"creating":1}
,"file":{"deletes":1,"target":1,"path":1,"delete":1,"paths":1,"[target":1,"change.log":1,"if":1,"doesn\u2019t":1,"$file":1,"deleted":1}
,"deletes":{"file":1,"change.log":1}
,"target":{"file":1}
,"path":{"file":1}
,"creating":{"file":1}
,"paths":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"18.0":1}
,"18.0":{"advanced":1}
,"advanced":{"deletes":1}
,"change.log":{"file":1,"deletes":1,"delete":1}
,"[target":{"file":1}
,"if":{"file":1,"[get":1,"show":1}
,"doesn\u2019t":{"exist":1}
,"exist":{"error":1,"else":1}
,"error":{"occurs":1,"message":1,"capture":1,"&get":1}
,"occurs":{"script":1}
,"script":{"displays":1,"[text":1}
,"displays":{"custom":1}
,"custom":{"error":1,"dialog":1}
,"message":{"set":1}
,"set":{"error":1,"variable":1}
,"capture":{"[on":1}
,"[on":{"set":1}
,"variable":{"[$file":1,"[$errormessage":1}
,"[$file":{"value":1}
,"value":{"change.log":1,"file":1,"error":1}
,"$file":{"if":1}
,"[get":{"lasterror":1}
,"lasterror":{"if":1,"=100":1,"&\u00B6":1}
,"=100":{"set":1}
,"[$errormessage":{"value":1,"exit":1}
,"else":{"set":1}
,"&get":{"lasterror":1}
,"&\u00B6":{"&\u0022":1}
,"&\u0022":{"file":1}
,"deleted":{"end":1,"adding":1}
,"end":{"if":1}
,"show":{"custom":1}
,"dialog":{"[$errormessage":1,"[\u0022":1}
,"exit":{"script":1}
,"[text":{"result":1}
,"result":{"end":1}
,"[\u0022":{"file":1}
,"adding":{"duplicating":1}
,"duplicating":{"deleting":1}
,"deleting":{"records":1}
,"records":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
