var pairs =
{
"onobjectmodify":{"performs":1,"script":1,"passes":1,"activate":1,"reduce":1}
,"performs":{"script":1}
,"script":{"hen":1,"steps":1,"step":1,"trigger":1,"operations":1,"triggers":1,"parameter":1,"determined":1,"rigger":1,"run":1,"value":1,"if":1,"modified":1,"field\u0027s":1,"runs":1}
,"hen":{"value":1}
,"value":{"associated":1,"change":1,"script":1,"field":1,"include":1,"filemaker":1}
,"associated":{"object":1}
,"object":{"result":1,"user":1,"checkbox":1,"script":1}
,"result":{"user":1}
,"user":{"types":1,"clicks":1,"enters":1}
,"types":{"object":1}
,"clicks":{"object":1}
,"checkbox":{"value":1}
,"change":{"edit":1,"field":1}
,"edit":{"operations":1}
,"operations":{"cut":1,"performed":1}
,"cut":{"paste":1}
,"paste":{"clear":1}
,"clear":{"script":1}
,"steps":{"insert":1}
,"insert":{"text":1}
,"text":{"script":1,"via":1}
,"step":{"change":1,"script":1}
,"field":{"event":1,"object":1,"modified":1,"web":1}
,"event":{"processed":1}
,"processed":{"browse":1}
,"browse":{"find":1}
,"find":{"modes":1}
,"modes":{"none":1,"trigger":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"10.0":1}
,"10.0":{"script":1}
,"trigger":{"activates":1,"activate":1,"set":1,"monitor":1,"result":1}
,"activates":{"if":1}
,"if":{"panel":1,"set":1,"script":1}
,"panel":{"control":1}
,"control":{"panels":1}
,"panels":{"switched":1}
,"switched":{"script":1}
,"activate":{"script":1,"value":1,"field":1}
,"performed":{"actions":1}
,"actions":{"don\u2019t":1}
,"don\u2019t":{"activate":1}
,"triggers":{"window":1}
,"window":{"refreshed":1}
,"refreshed":{"update":1}
,"update":{"data":1}
,"data":{"external":1,"source":1}
,"external":{"data":1}
,"source":{"auto-enter":1}
,"auto-enter":{"fields":1}
,"fields":{"updated":1,"activate":1}
,"updated":{"onobjectmodify":1}
,"set":{"summary":1,"onobjectmodify":1}
,"summary":{"calculation":1}
,"calculation":{"fields":1}
,"parameter":{"onobjectmodify":1,"pass":1}
,"passes":{"script":1}
,"determined":{"script":1}
,"rigger":{"activated":1}
,"activated":{"if":1}
,"run":{"field":1}
,"modified":{"therefore":1,"use":1,"value":1}
,"therefore":{"if":1}
,"use":{"script":1}
,"pass":{"field\u0027s":1}
,"field\u0027s":{"unmodified":1,"current":1}
,"unmodified":{"value":1}
,"include":{"step":1}
,"current":{"modified":1}
,"webdirect":{"support":1}
,"support":{"onobjectmodify":1}
,"monitor":{"keystrokes":1}
,"keystrokes":{"field":1,"onobjectmodify":1}
,"web":{"user":1}
,"enters":{"text":1}
,"via":{"keyboard":1}
,"keyboard":{"input":1}
,"input":{"method":1}
,"method":{"editor":1}
,"editor":{"predictive-text":1}
,"predictive-text":{"suggestion":1}
,"suggestion":{"monitoring":1}
,"monitoring":{"keystrokes":1}
,"reduce":{"performance":1}
,"performance":{"lead":1}
,"lead":{"unexpected":1}
,"unexpected":{"script":1}
,"runs":{"modes":1}
}
;Search.control.loadWordPairs(pairs);
