var pairs =
{
"scripts":{"menu":1,"choose":1,"pane":1,"scripts":1,"folders":1}
,"menu":{"script":1,"filemaker":1,"ight-click":1,"select":1,"button":1,"windows":1,"preferences":1,"checkbox":1,"clear":1,"reorder":1,"drag":1}
,"script":{"folder":1,"workspace":1,"name":1,"names":1}
,"folder":{"appears":1,"scripts":1,"choose":1,"list":1,"desired":1,"names":1,"want":1}
,"appears":{"submenu":1,"scripts":1}
,"submenu":{"scripts":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"assigns":1}
,"assigns":{"keyboard":1}
,"keyboard":{"shortcuts":1}
,"shortcuts":{"first":1}
,"first":{"scripts":1}
,"choose":{"scripts":1,"include":1,"view":1,"exclude":1}
,"workspace":{"scripts":1,"choose":1,"preferences":1}
,"pane":{"add":1,"manage":1}
,"add":{"script":1,"separator":1}
,"ight-click":{"script":1}
,"name":{"folder":1}
,"include":{"scripts":1}
,"select":{"checkbox":1,"display":1,"script":1}
,"checkbox":{"left":1,"macos":1,"remove":1}
,"left":{"script":1}
,"list":{"display":1,"right-click":1}
,"display":{"checkboxes":1,"new":1}
,"checkboxes":{"script":1}
,"names":{"folders":1,"select":1}
,"folders":{"scripts":1}
,"manage":{"scripts":1}
,"button":{"set":1,"separator":1}
,"set":{"default":1}
,"default":{"behavior":1}
,"behavior":{"display":1}
,"new":{"scripts":1,"separator":1}
,"windows":{"script":1}
,"view":{"menu":1}
,"preferences":{"select":1}
,"macos":{"choose":1}
,"remove":{"script":1}
,"clear":{"checkbox":1}
,"right-click":{"script":1}
,"exclude":{"scripts":1}
,"reorder":{"scripts":1}
,"drag":{"script":1}
,"desired":{"location":1}
,"location":{"add":1}
,"separator":{"script":1,"new":1,"button":1,"appears":1}
,"want":{"new":1}
}
;Search.control.loadWordPairs(pairs);
