var pairs =
{
"copying":{"duplicating":1}
,"duplicating":{"deleting":1}
,"deleting":{"objects":1}
,"objects":{"layout":1,"duplicated":1,"cut":1,"choosing":1}
,"layout":{"mode":1,"database":1,"object":1,"paste":1,"theme":1,"choose":1}
,"mode":{"select":1}
,"select":{"object":1}
,"object":{"copy":1,"paste":1,"centered":1,"windows":1,"choose":1,"replacing":1,"layout":1,"retains":1,"attributes":1,"position":1}
,"copy":{"cut":1,"object":1,"paste":1,"duplicate":1,"appears":1,"first":1,"original":1}
,"cut":{"object":1,"arrow":1,"delete":1}
,"paste":{"layout":1,"macos":1,"object":1}
,"database":{"file":1}
,"file":{"choose":1}
,"choose":{"edit":1,"duplicate":1}
,"edit":{"menu":1}
,"menu":{"copy":1,"paste":1,"duplicate":1,"clear":1,"revert":1}
,"arrow":{"pointer":1}
,"pointer":{"want":1,"new":1}
,"want":{"object":1,"deselecting":1}
,"centered":{"choose":1}
,"windows":{"edit":1,"option":1}
,"macos":{"hold":1,"drag":1}
,"hold":{"alt":1}
,"alt":{"key":1}
,"key":{"windows":1,"macos":1}
,"option":{"key":1,"macos":1}
,"drag":{"pointer":1,"note":1,"new":1}
,"new":{"location":1,"theme":1,"object":1,"copy":1}
,"location":{"release":1}
,"release":{"mouse":1}
,"mouse":{"duplicate":1}
,"duplicate":{"object":1,"press":1,"locked":1,"command":1,"drag":1,"new":1}
,"press":{"ctrl":1,"backspace":1}
,"ctrl":{"windows":1}
,"note":{"objects":1}
,"duplicated":{"snap":1}
,"snap":{"grid":1}
,"grid":{"guides":1}
,"guides":{"dynamic":1,"sing":1,"delete":1}
,"dynamic":{"guides":1}
,"sing":{"rulers":1}
,"rulers":{"grid":1}
,"delete":{"object":1,"if":1,"use":1}
,"replacing":{"clipboard":1}
,"clipboard":{"choose":1}
,"clear":{"press":1}
,"backspace":{"delete":1}
,"if":{"copy":1}
,"theme":{"object":1,"use":1}
,"retains":{"attributes":1}
,"attributes":{"original":1,"apply":1,"new":1,"opying":1,"ayout":1}
,"original":{"layout":1,"object":1}
,"revert":{"style":1}
,"style":{"remove":1}
,"remove":{"attributes":1}
,"apply":{"default":1}
,"default":{"attributes":1}
,"use":{"inspector":1,"duplicate":1}
,"inspector":{"copy":1}
,"opying":{"formatting":1}
,"formatting":{"attributes":1}
,"ayout":{"copy":1}
,"locked":{"objects":1}
,"command":{"create":1}
,"create":{"series":1}
,"series":{"equally":1}
,"equally":{"spaced":1}
,"spaced":{"identical":1}
,"identical":{"objects":1}
,"choosing":{"edit":1}
,"position":{"want":1,"relative":1}
,"deselecting":{"choose":1}
,"appears":{"position":1}
,"relative":{"first":1}
,"first":{"copy":1}
}
;Search.control.loadWordPairs(pairs);
