var pairs =
{
"printing":{"record":1,"preview":1,"records":1}
,"record":{"find":1,"currently":1,"blank":1,"current":1,"fields":1,"placeholder":1,"view":1}
,"find":{"sort":1}
,"sort":{"records":1}
,"records":{"want":1,"sorting":1,"ow":1,"found":1,"browsed":1,"varying":1,"fit":1,"arranged":1,"columns":1}
,"want":{"print":1}
,"print":{"finding":1,"print":1,"dialog":1,"choose":1,"blank":1,"macos":1,"options":1,"field":1,"all":1,"orking":1,"layouts":1,"popover":1,"preview":1,"chose":1,"records":1,"data":1,"columns":1}
,"finding":{"records":1}
,"sorting":{"records":1}
,"ow":{"paper":1}
,"paper":{"copy":1}
,"copy":{"prior":1}
,"prior":{"printing":1}
,"preview":{"layout":1,"placeholder":1,"mode":1}
,"layout":{"bar":1,"use":1,"print":1,"enlarge":1,"removing":1,"mode":1,"setup":1}
,"bar":{"browse":1,"filemaker":1}
,"browse":{"mode":1}
,"mode":{"hoose":1,"current":1,"resizing":1,"records":1}
,"hoose":{"file":1}
,"file":{"menu":1}
,"menu":{"print":1,"macos":1}
,"dialog":{"box":1}
,"box":{"print":1,"configured":1}
,"choose":{"option":1,"filemaker":1,"all":1,"formatting":1,"affect":1}
,"option":{"windows":1,"print":1,"macos":1}
,"windows":{"choose":1,"print":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"rom":1,"prints":1,"page":1}
,"rom":{"pop-up":1}
,"pop-up":{"menu":1}
,"macos":{"print":1,"if":1}
,"all":{"records":1,"data":1}
,"found":{"set":1}
,"set":{"records":1,"sliding":1}
,"browsed":{"record":1,"current":1}
,"currently":{"selected":1}
,"selected":{"browse":1}
,"current":{"record":1,"layout":1,"date":1}
,"blank":{"record":1,"orm":1,"space":1,"spaces":1}
,"use":{"option":1,"merge":1}
,"orm":{"blank":1}
,"fields":{"choose":1,"eliminate":1,"layout":1,"variable":1,"set":1}
,"formatting":{"option":1}
,"if":{"don\u2019t":1,"layout":1}
,"don\u2019t":{"options":1}
,"options":{"show":1,"depend":1,"use":1,"remove":1,"close":1}
,"show":{"details":1}
,"details":{"elect":1}
,"elect":{"printer":1}
,"printer":{"settings":1,"system":1}
,"settings":{"hen":1,"choose":1}
,"hen":{"windows":1,"print":1}
,"depend":{"printer":1}
,"system":{"software":1,"documentation":1}
,"software":{"you\u2019re":1}
,"you\u2019re":{"refer":1}
,"refer":{"printer":1}
,"documentation":{"ou":1}
,"ou":{"lose":1}
,"lose":{"up":1}
,"up":{"lank":1,"blank":1,"print":1}
,"lank":{"space":1}
,"space":{"printing":1,"field":1,"print":1,"records":1}
,"varying":{"amounts":1}
,"amounts":{"data":1}
,"data":{"by":1,"removing":1,"visible":1,"duplicate":1,"sliding":1,"fits":1}
,"by":{"sliding":1,"resizing":1,"filemaker":1}
,"sliding":{"options":1}
,"merge":{"fields":1}
,"eliminate":{"extra":1}
,"extra":{"blank":1}
,"field":{"data":1,"portal":1,"boundaries":1,"layout":1}
,"removing":{"blank":1}
,"spaces":{"printouts":1}
,"printouts":{"placing":1,"hen":1}
,"placing":{"merge":1}
,"portal":{"scroll":1,"display":1}
,"scroll":{"bar":1}
,"prints":{"data":1,"print":1}
,"visible":{"scrolling":1}
,"scrolling":{"print":1}
,"duplicate":{"layout":1}
,"enlarge":{"field":1}
,"display":{"largest":1}
,"largest":{"data":1}
,"remove":{"extra":1}
,"orking":{"fields":1}
,"layouts":{"panel":1}
,"panel":{"controls":1,"slide":1,"prints":1}
,"controls":{"frontmost":1}
,"frontmost":{"ab":1,"anels":1}
,"ab":{"panel":1}
,"slide":{"panel":1}
,"popover":{"buttons":1}
,"buttons":{"popovers":1,"frontmost":1}
,"popovers":{"contents":1,"navigation":1}
,"contents":{"popovers":1}
,"navigation":{"parts":1}
,"parts":{"objects":1,"calculated":1}
,"objects":{"print":1,"preview":1}
,"placeholder":{"text":1}
,"text":{"print":1}
,"chose":{"print":1}
,"view":{"print":1}
,"fits":{"field":1}
,"boundaries":{"change":1,"by":1}
,"change":{"boundaries":1}
,"resizing":{"field":1,"reshaping":1}
,"reshaping":{"objects":1}
,"fit":{"printed":1}
,"printed":{"page":1}
,"page":{"pagination":1,"breaks":1,"numbers":1,"margins":1}
,"pagination":{"settings":1}
,"affect":{"page":1}
,"breaks":{"defining":1,"numbering":1}
,"defining":{"page":1}
,"numbering":{"subsummary":1}
,"subsummary":{"parts":1}
,"calculated":{"summary":1}
,"summary":{"fields":1}
,"variable":{"supplied":1}
,"supplied":{"by":1}
,"numbers":{"current":1}
,"date":{"page":1}
,"margins":{"define":1,"fields":1}
,"define":{"page":1}
,"close":{"up":1}
,"arranged":{"columns":1}
,"columns":{"if":1,"setting":1,"popover":1}
,"setup":{"dialog":1}
,"configured":{"print":1}
,"setting":{"up":1}
,"anels":{"panel":1}
}
;Search.control.loadWordPairs(pairs);
