var pairs =
{
"new":{"file":1,"filemaker":1}
,"file":{"create":1,"none":1,"script":1,"remains":1,"remain":1,"step":1,"import":1,"creating":1,"automating":1}
,"create":{"window":1,"new":1,"folders":1}
,"window":{"users":1,"new":1,"script":1}
,"users":{"create":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1,"6.0":1}
,"advanced":{"file":1}
,"none":{"filemaker":1}
,"6.0":{"earlier":1}
,"earlier":{"script":1}
,"script":{"step":1,"active":1,"steps":1,"continues":1}
,"step":{"create":1,"new":1,"exports":1}
,"active":{"if":1,"add":1}
,"if":{"script":1,"want":1}
,"steps":{"remain":1}
,"remain":{"script":1,"active":1}
,"continues":{"new":1}
,"remains":{"open":1}
,"open":{"active":1}
,"want":{"original":1}
,"original":{"file":1}
,"add":{"select":1}
,"select":{"window":1}
,"exports":{"records":1}
,"records":{"creates":1,"set":1,"[with":1}
,"creates":{"new":1}
,"import":{"records":1}
,"set":{"error":1}
,"error":{"capture":1}
,"capture":{"[on]":1}
,"[on]":{"export":1}
,"export":{"records":1}
,"[with":{"dialog":1}
,"dialog":{"create":1}
,"folders":{"new":1}
,"creating":{"filemaker":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
