var pairs =
{
"loop":{"epeats":1,"exporting":1,"script":1,"structure":1,"if":1,"step":1,"set":1,"loops":1,"export":1,"automating":1}
,"epeats":{"set":1}
,"set":{"script":1,"field":1,"variable":1}
,"script":{"steps":1,"step":1,"performs":1,"editing":1}
,"steps":{"perform":1,"script":1,"enclosed":1}
,"perform":{"batch":1}
,"batch":{"processes":1}
,"processes":{"none":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"use":1}
,"use":{"loop":1}
,"exporting":{"container":1}
,"container":{"field":1}
,"field":{"contents":1,"[customers":1,"set":1}
,"contents":{"all":1,"customers":1,"[products":1}
,"all":{"records":1}
,"records":{"found":1,"go":1,"export":1}
,"found":{"set":1}
,"step":{"end":1,"mark":1,"go":1,"exit":1,"loop":1,"indentation":1,"script":1,"copies":1}
,"end":{"loop":1,"repeating":1}
,"mark":{"end":1}
,"repeating":{"structure":1}
,"structure":{"script":1,"encounters":1}
,"performs":{"script":1}
,"enclosed":{"loop":1}
,"encounters":{"exit":1}
,"exit":{"loop":1,"last":1}
,"if":{"script":1}
,"go":{"record\u002Frequest\u002Fpage":1,"portal":1}
,"record\u002Frequest\u002Fpage":{"script":1,"[first]":1,"[next":1}
,"portal":{"row":1}
,"row":{"script":1}
,"last":{"option":1,"end":1}
,"option":{"selected":1}
,"selected":{"loop":1}
,"indentation":{"use":1}
,"editing":{"pane":1}
,"pane":{"automatically":1}
,"automatically":{"enters":1}
,"enters":{"end":1}
,"copies":{"contents":1}
,"customers":{":work":1}
,":work":{"phone":1,"phone]":1}
,"phone":{"customer":1}
,"customer":{":day":1}
,":day":{"contact":1}
,"contact":{"all":1,"customers":1}
,"[first]":{"loop":1}
,"[customers":{":day":1}
,"phone]":{"go":1}
,"[next":{"exit":1}
,"loops":{"records":1}
,"export":{"files":1,"field":1}
,"files":{"container":1}
,"variable":{"[$path":1}
,"[$path":{"value":1}
,"value":{"get":1}
,"get":{"documentspath":1}
,"documentspath":{"&products":1}
,"&products":{":container]":1}
,":container]":{"go":1}
,"[products":{":container":1}
,":container":{"\u0022$path":1}
,"\u0022$path":{"create":1}
,"create":{"folders":1}
,"folders":{"go":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
