var pairs =
{
"sing":{"predefined":1}
,"predefined":{"privilege":1}
,"privilege":{"sets":1,"set":1,"full":1,"accounts":1,"view":1}
,"sets":{"new":1,"full":1,"except":1,"privilege":1,"modify":1,"create":1,"user":1}
,"new":{"filemaker":1}
,"filemaker":{"pro":1,"file":1}
,"pro":{"advanced":1}
,"advanced":{"database":1,"security":1}
,"database":{"predefined":1,"dialog":1,"definition":1}
,"full":{"access":1,"account":1}
,"access":{"permits":1,"privilege":1,"all":1,"override":1,"manage":1,"nd":1,"except":1,"privileges":1}
,"permits":{"accessing":1,"viewing":1,"write":1,"access":1,"full":1,"change":1}
,"accessing":{"changing":1}
,"changing":{"file":1,"data":1}
,"file":{"data":1,"ccount":1,"active":1,"ust":1}
,"data":{"entry":1,"read-only":1,"note":1,"view-only":1,"validation":1,"sources":1}
,"entry":{"permits":1,"privilege":1}
,"viewing":{"entering":1,"changing":1}
,"entering":{"data":1}
,"read-only":{"access":1}
,"note":{"read-only":1,"full":1}
,"set":{"permits":1,"global":1,"change":1,"data":1,"read-only":1,"records":1,"limited":1,"permitted":1,"accounts":1,"assignments":1,"create":1,"each":1,"error":1}
,"write":{"access":1}
,"all":{"global":1,"record":1,"tables":1,"modifiable":1,"executable":1,"except":1,"all":1,"note":1}
,"global":{"fields":1}
,"fields":{"create":1,"all":1,"tables":1}
,"create":{"privilege":1,"edit":1,"modify":1}
,"record":{"data":1}
,"view-only":{"duplicate":1}
,"duplicate":{"read-only":1,"modify":1,"copies":1}
,"change":{"records":1,"delete":1,"number":1,"security":1,"two":1,"privilege":1}
,"records":{"custom":1,"all":1}
,"custom":{"privileges":1}
,"privileges":{"view":1,"use":1,"all":1,"manage":1,"two":1,"permit":1,"privilege":1,"existing":1,"open":1}
,"view":{"all":1,"layouts":1,"view":1,"value":1,"scripts":1,"grant":1}
,"tables":{"change":1,"create":1,"relationships":1}
,"delete":{"predefined":1,"create":1,"view":1,"privilege":1}
,"except":{"enable":1,"fmreauthenticate10":1,"full":1}
,"enable":{"disable":1}
,"disable":{"extended":1}
,"extended":{"privileges":1}
,"use":{"duplicate":1}
,"modify":{"duplicate":1,"fields":1,"account":1,"delete":1,"extended":1}
,"copies":{"table":1}
,"table":{"summarizes":1,"compares":1}
,"summarizes":{"properties":1}
,"properties":{"privilege":1}
,"edit":{"delete":1,"accounts":1}
,"layouts":{"all":1}
,"modifiable":{"view":1,"executable":1}
,"value":{"lists":1}
,"lists":{"all":1}
,"scripts":{"all":1}
,"executable":{"all":1,"extended":1}
,"fmreauthenticate10":{"all":1,"allow":1}
,"allow":{"printing":1,"exporting":1,"password":1}
,"printing":{"allow":1}
,"exporting":{"manage":1}
,"manage":{"extended":1,"accounts":1,"database":1,"security":1}
,"accounts":{"don\u2019t":1,"full":1,"manage":1,"active":1}
,"don\u2019t":{"full":1}
,"override":{"data":1}
,"validation":{"warnings":1}
,"warnings":{"disconnect":1}
,"disconnect":{"user":1}
,"user":{"server":1,"database":1}
,"server":{"hen":1}
,"hen":{"idle":1}
,"idle":{"allow":1}
,"password":{"modification":1,"change":1,"length":1}
,"modification":{"password":1}
,"number":{"days":1}
,"days":{"minimum":1}
,"minimum":{"password":1}
,"length":{"menu":1}
,"menu":{"commands":1}
,"commands":{"all":1}
,"dialog":{"box":1,"boxes":1}
,"box":{"order":1}
,"order":{"modify":1}
,"relationships":{"data":1}
,"sources":{"privilege":1}
,"security":{"advanced":1,"settings":1}
,"settings":{"dialog":1,"table":1}
,"boxes":{"modify":1}
,"account":{"access":1,"assigned":1}
,"nd":{"privileges":1}
,"two":{"privileges":1,"limited":1}
,"permit":{"accounts":1,"account":1}
,"limited":{"ability":1,"privileges":1}
,"ability":{"change":1}
,"compares":{"full":1}
,"permitted":{"accounts":1}
,"grant":{"remove":1}
,"remove":{"account":1}
,"assignments":{"except":1}
,"existing":{"privilege":1}
,"definition":{"full":1}
,"open":{"file":1}
,"ccount":{"assigned":1,"authenticated":1}
,"assigned":{"full":1}
,"each":{"file":1}
,"active":{"ccount":1,"account":1}
,"authenticated":{"via":1}
,"via":{"filemaker":1}
,"ust":{"assigned":1}
,"error":{"message":1}
,"message":{"if":1}
,"if":{"edit":1}
}
;Search.control.loadWordPairs(pairs);
