var pairs =
{
"priority":{"displaying":1}
,"displaying":{"formatting":1}
,"formatting":{"attributes":1,"displayed":1,"css":1}
,"attributes":{"change":1,"objects":1,"display":1}
,"change":{"display":1}
,"display":{"attributes":1,"save":1}
,"objects":{"layout":1}
,"layout":{"parts":1,"background":1,"level":1}
,"parts":{"layout":1}
,"background":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"displays":1}
,"displays":{"formats":1}
,"formats":{"defined":1}
,"defined":{"hierarchy":1}
,"hierarchy":{"precedence":1}
,"precedence":{"factor":1,"formatting":1}
,"factor":{"determines":1}
,"determines":{"format":1}
,"format":{"attributes":1}
,"save":{"layout":1}
,"level":{"theme":1,"illustration":1}
,"theme":{"level":1}
,"illustration":{"order":1}
,"order":{"precedence":1}
,"displayed":{"order":1}
,"css":{"cascading":1}
,"cascading":{"style":1}
,"style":{"sheet":1}
}
;Search.control.loadWordPairs(pairs);
