var pairs =
{
"ew":{"lay":1}
,"lay":{"ou":1}
,"ou":{"t\u002Freport":1}
,"t\u002Freport":{"new":1}
,"new":{"layout\u002Freport":1}
,"layout\u002Freport":{"assistant":1}
,"assistant":{"panel":1,"database":1,"choose":1,"create":1,"script":1}
,"panel":{"new":1,"close":1,"assistant":1}
,"database":{"table":1,"add":1}
,"table":{"layout":1,"records":1,"views":1,"display":1,"view":1,"summary":1}
,"layout":{"access":1,"type":1,"want":1,"note":1,"creating":1,"rinting":1,"display":1,"name":1,"layout":1,"pop-up":1,"laptop":1,"touch-compatible":1,"types":1,"displayed":1,"all":1,"setup":1,"choose":1,"records":1,"complex":1,"mode":1,"defining":1,"labels":1}
,"access":{"name":1}
,"name":{"layout":1,"type":1,"automatically":1}
,"type":{"layout":1,"escriptive":1,"choose":1,"bout":1,"list":1}
,"want":{"create":1,"review":1,"layout":1,"records":1}
,"create":{"default":1,"report":1,"depending":1,"layout":1,"variations":1,"simple":1}
,"default":{"view":1,"orientation":1,"custom":1,"displayed":1}
,"view":{"layout":1,"want":1,"selected":1,"panel":1,"records":1,"data":1,"browse":1,"viewing":1,"fields":1,"list":1,"displayed":1,"dialog":1,"drawing":1,"view":1,"use":1,"summary":1,"creating":1,"merge":1}
,"note":{"want":1}
,"review":{"help":1}
,"help":{"topics":1}
,"topics":{"creating":1}
,"creating":{"layout":1,"managing":1,"script":1,"dynamic":1,"styles":1}
,"managing":{"layouts":1}
,"layouts":{"reports":1,"layout":1,"choose":1,"change":1,"create":1,"display":1,"form":1,"table":1,"assigned":1}
,"reports":{"considerations":1,"continue":1,"table":1}
,"considerations":{"create":1}
,"report":{"layout":1,"choose":1,"each":1,"display":1,"create":1,"layouts":1,"rows":1,"data":1,"option":1,"assistant":1,"report":1,"sorted":1}
,"rinting":{"labels":1}
,"labels":{"envelopes":1,"vertical":1}
,"envelopes":{"show":1,"report":1,"reports":1}
,"show":{"records":1}
,"records":{"choose":1,"want":1,"displayed":1,"form":1,"list":1,"time":1,"rows":1,"table":1,"define":1}
,"choose":{"table":1,"type":1,"additional":1,"computer":1,"ipad":1,"custom":1,"labels":1,"view":1,"create":1,"form":1}
,"display":{"layout":1,"records":1,"print":1,"computers":1,"summary":1}
,"escriptive":{"name":1}
,"automatically":{"ap":1}
,"ap":{"pears":1}
,"pears":{"menus":1}
,"menus":{"choosing":1}
,"choosing":{"layouts":1}
,"pop-up":{"menu":1}
,"menu":{"change":1}
,"change":{"setting":1,"layout\u2019s":1,"orientation":1,"value":1,"values":1,"fields":1,"data":1}
,"setting":{"managing":1,"up":1}
,"depending":{"type":1,"size":1}
,"additional":{"options":1,"views":1}
,"options":{"choose":1,"set":1}
,"computer":{"create":1,"screen":1,"touch":1}
,"laptop":{"desktop":1}
,"desktop":{"computer":1}
,"screen":{"touch":1}
,"touch":{"device":1,"devices":1}
,"device":{"create":1,"choose":1,"change":1,"layouts":1}
,"touch-compatible":{"input":1}
,"input":{"device":1}
,"ipad":{"iphone":1}
,"iphone":{"custom":1}
,"custom":{"device":1,"values":1}
,"layout\u2019s":{"default":1}
,"orientation":{"portrait":1,"control":1,"landscape":1,"width":1}
,"portrait":{"portrait":1,"orientation":1}
,"control":{"change":1,"if":1}
,"landscape":{"landscape":1,"orientation":1}
,"if":{"choose":1,"chose":1,"fields":1,"options":1}
,"value":{"32000":1}
,"32000":{"points":1}
,"points":{"width":1}
,"width":{"height":1,"800":1,"1280":1}
,"height":{"custom":1,"1145":1,"665":1}
,"values":{"enter":1,"default":1,"portrait":1,"subtotals":1,"table":1}
,"enter":{"all":1}
,"all":{"custom":1,"views":1}
,"800":{"height":1}
,"1145":{"landscape":1}
,"1280":{"height":1}
,"665":{"printer":1}
,"printer":{"arrange":1}
,"arrange":{"data":1}
,"data":{"printing":1,"entry":1,"report":1,"predefined":1,"grouped":1,"table":1,"spreadsheet-like":1,"by":1,"values":1}
,"printing":{"labels":1,"multiple":1,"report":1}
,"vertical":{"labels":1}
,"each":{"layout":1,"separate":1,"group":1}
,"bout":{"layout":1}
,"types":{"if":1}
,"chose":{"computer":1}
,"displayed":{"choose":1,"view":1,"standard":1,"each":1,"grid":1,"layout":1,"browse":1}
,"selected":{"display":1}
,"views":{"choose":1,"layout":1}
,"close":{"assistant":1}
,"setup":{"dialog":1}
,"dialog":{"box":1}
,"box":{"setting":1,"appears":1}
,"up":{"form":1}
,"form":{"list":1,"display":1,"view":1,"fields":1,"time":1}
,"list":{"table":1,"display":1,"view":1,"depending":1,"records":1}
,"standard":{"form":1}
,"fields":{"by":1,"displayed":1,"defined":1,"objects":1,"data":1,"sorted":1,"add":1,"browse":1,"just":1,"check":1,"text":1}
,"by":{"default":1,"values":1,"grouping":1,"columns":1}
,"separate":{"line":1}
,"line":{"order":1}
,"order":{"browse":1,"left":1}
,"browse":{"mode":1}
,"mode":{"find":1,"record":1,"records":1,"layouts":1,"modify":1,"quickly":1}
,"find":{"mode":1}
,"record":{"form":1}
,"time":{"form":1,"list":1,"change":1}
,"entry":{"onscreen":1}
,"onscreen":{"browsing":1}
,"browsing":{"list":1}
,"size":{"layout":1}
,"viewing":{"printing":1}
,"multiple":{"records":1}
,"rows":{"list":1,"columns":1}
,"grid":{"order":1}
,"left":{"right":1}
,"right":{"field":1}
,"field":{"names":1}
,"names":{"column":1}
,"column":{"headings":1}
,"headings":{"report":1}
,"print":{"data":1}
,"variations":{"report":1}
,"simple":{"report":1}
,"columns":{"data":1,"fields":1}
,"predefined":{"layout":1}
,"complex":{"report":1}
,"grouped":{"by":1}
,"subtotals":{"grand":1,"each":1}
,"grand":{"totals":1}
,"totals":{"finished":1,"table":1}
,"finished":{"choices":1}
,"choices":{"layouts":1}
,"computers":{"touch":1}
,"devices":{"finish":1}
,"finish":{"layouts":1}
,"modify":{"table":1}
,"appears":{"if":1}
,"defined":{"database":1}
,"add":{"change":1,"delete":1}
,"objects":{"embellishments":1,"layout":1}
,"embellishments":{"layout":1}
,"defining":{"changing":1}
,"changing":{"fields":1}
,"drawing":{"inserting":1}
,"inserting":{"objects":1}
,"continue":{"next":1}
,"next":{"panel":1}
,"option":{"creating":1}
,"script":{"sort":1,"simplifies":1}
,"sort":{"report":1}
,"simplifies":{"process":1}
,"process":{"viewing":1}
,"sorted":{"properly":1,"table":1}
,"properly":{"display":1}
,"summary":{"it\u2019s":1,"data":1,"recalculate":1}
,"it\u2019s":{"easy":1}
,"easy":{"forget":1}
,"forget":{"fields":1}
,"spreadsheet-like":{"format":1}
,"format":{"allows":1}
,"allows":{"quickly":1}
,"quickly":{"rearrange":1,"reorder":1}
,"rearrange":{"fields":1}
,"delete":{"records":1}
,"define":{"fields":1}
,"reorder":{"resize":1}
,"resize":{"columns":1}
,"just":{"mouse":1}
,"mouse":{"if":1}
,"set":{"data":1}
,"use":{"table":1}
,"grouping":{"data":1}
,"check":{"subtotals":1}
,"group":{"grand":1}
,"recalculate":{"update":1}
,"update":{"real":1}
,"real":{"time":1}
,"dynamic":{"reports":1}
,"merge":{"fields":1}
,"text":{"placed":1,"style":1}
,"placed":{"report":1}
,"assigned":{"text":1}
,"style":{"part":1}
,"part":{"creating":1}
,"styles":{"ayout":1}
}
;Search.control.loadWordPairs(pairs);
