var pairs =
{
"files":{"script":1,"files":1}
,"script":{"steps":1}
,"steps":{"files":1,"operate":1,"create":1}
,"operate":{"entire":1}
,"entire":{"files":1}
,"create":{"file":1}
,"file":{"open":1,"save":1,"convert":1,"filemaker":1,"recover":1,"set":1}
,"open":{"close":1}
,"close":{"file":1}
,"save":{"copy":1}
,"copy":{"file":1}
,"convert":{"file":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"set":1}
,"set":{"multi":1,"print":1}
,"multi":{"ser":1}
,"ser":{"status":1}
,"status":{"allow":1}
,"allow":{"users":1}
,"users":{"choose":1}
,"choose":{"formats":1}
,"formats":{"file":1}
,"recover":{"file":1}
,"print":{"setup":1}
,"setup":{"options":1}
,"options":{"print":1}
}
;Search.control.loadWordPairs(pairs);
