var pairs =
{
"importing":{"data":1,"omitted":1}
,"data":{"filemaker":1,"bring":1,"source":1,"application":1,"access":1,"imports":1,"file":1,"existing":1,"target":1,"choose":1,"match":1,"first":1,"second":1,"files":1,"field-by-field":1,"extra":1,"new":1,"single":1,"related":1,"table":1,"correctly":1,"validated":1,"skipped":1,"during":1}
,"filemaker":{"pr":1,"pro":1}
,"pr":{"advanced":1}
,"advanced":{"import":1,"file":1,"support":1,"supports":1,"target":1,"doesn\u2019t":1}
,"import":{"data":1,"file":1,"access":1,"process":1,"note":1,"field":1,"update":1,"match":1,"contents":1,"ndicates":1,"john":1,"smith":1,"123":1,"anytown":1,"usa":1,"3\u002F3\u002F1960":1,"408":1,"records":1,"fields":1,"table":1,"if":1}
,"bring":{"data":1}
,"source":{"usually":1,"file":1,"data":1,"automate":1}
,"usually":{"file":1}
,"file":{"existing":1,"filemaker":1,"formats":1,"source":1,"number":1,"during":1,"file":1,"format":1,"new":1,"import":1,"add":1,"replace":1,"options":1,"mporting":1,"ptions":1,"undone":1,"menu":1,"local":1,"located":1,"each":1,"imports":1,"concept":1,"updated":1,"copy":1,"office":1,"update":1,"by":1,"if":1,"matches":1,"record":1,"blank":1,"found":1,"appears":1,"mapping":1,"result":1,"replaced":1,"overwrites":1,"data":1,"imported":1,"multiple":1,"adding":1}
,"existing":{"filemaker":1,"file":1,"records":1}
,"pro":{"advanced":1,"format":1}
,"formats":{"supported":1,"if":1,"import":1}
,"supported":{"import\u002Fexport":1}
,"import\u002Fexport":{"file":1}
,"if":{"filemaker":1,"data":1,"field":1,"importable":1,"records":1,"source":1,"routinely":1}
,"support":{"format":1}
,"format":{"application":1,"filemaker":1,"onverting":1,"ensure":1}
,"application":{"export":1,"format":1}
,"export":{"data":1}
,"supports":{"import":1}
,"access":{"files":1,"excel":1}
,"files":{"export":1,"choose":1}
,"excel":{"import":1}
,"number":{"fields":1,"multiple":1,"last":1,"records":1}
,"fields":{"order":1,"source":1,"skip":1,"don\u2019t":1,"select":1,"target":1,"each":1,"uniquely":1,"last":1,"first":1,"second":1,"import":1,"related":1,"data":1}
,"order":{"filemaker":1}
,"target":{"file":1,"fields":1,"filemaker":1}
,"during":{"import":1}
,"process":{"choose":1,"creates":1,"adds":1,"by":1}
,"choose":{"target":1,"file":1,"replace":1,"add":1}
,"imports":{"correct":1,"fields":1,"by":1,"automating":1}
,"correct":{"fields":1}
,"skip":{"fields":1,"importing":1}
,"don\u2019t":{"want":1,"import":1}
,"want":{"import":1}
,"note":{"create":1}
,"create":{"new":1}
,"new":{"filemaker":1,"records":1,"record":1,"rd":1}
,"onverting":{"data":1}
,"add":{"new":1,"records":1,"remaining":1}
,"records":{"fil":1,"file":1,"import":1,"source":1,"matching":1,"fields":1,"target":1,"overwrite":1,"updated":1,"data":1,"if":1,"found":1,"filemaker":1,"script":1,"pdating":1,"replacing":1}
,"fil":{"pdate":1}
,"pdate":{"matching":1}
,"matching":{"records":1,"record":1}
,"replace":{"existing":1,"ecords":1,"data":1}
,"options":{"import":1,"set":1}
,"field":{"mapping":1,"record":1,"employee":1,"use":1,"source":1,"ndicates":1,"import":1,"don\u2019t":1,"123-456-7890":1,"if":1}
,"mapping":{"dialog":1,"column":1,"target":1}
,"dialog":{"box":1}
,"box":{"import":1}
,"mporting":{"data":1}
,"ptions":{"update":1}
,"update":{"replace":1,"matching":1,"file":1,"records":1}
,"ecords":{"overwrite":1}
,"overwrite":{"data":1}
,"undone":{"safeguard":1}
,"safeguard":{"data":1}
,"menu":{"save":1}
,"save":{"copy":1}
,"copy":{"backup":1,"target":1,"database":1,"laptop":1}
,"backup":{"copy":1}
,"local":{"file":1}
,"located":{"computer":1}
,"computer":{"add":1,"copy":1,"update":1}
,"creates":{"new":1}
,"record":{"target":1,"source":1,"row":1}
,"each":{"importable":1,"file":1,"entity":1,"field":1}
,"importable":{"record":1,"records":1}
,"select":{"add":1,"ields":1,"all":1}
,"adds":{"all":1}
,"all":{"records":1,"fields":1,"matching":1}
,"concept":{"art":1}
,"art":{"adding":1,"updating":1,"replacing":1}
,"adding":{"records":1}
,"updated":{"data":1,"table":1,"by":1}
,"database":{"desktop":1,"database":1,"people":1}
,"desktop":{"computer":1}
,"laptop":{"computer":1}
,"office":{"road":1}
,"road":{"determine":1}
,"determine":{"records":1}
,"by":{"choosing":1,"itself":1,"matching":1,"setting":1,"creating":1}
,"choosing":{"match":1}
,"match":{"fields":1,"field":1}
,"matches":{"data":1}
,"updating":{"records":1}
,"uniquely":{"identify":1}
,"identify":{"each":1,"person":1}
,"entity":{"database":1}
,"people":{"use":1}
,"use":{"match":1,"by":1}
,"employee":{"number":1}
,"multiple":{"match":1,"tables":1}
,"last":{"name":1}
,"name":{"first":1,"phone":1,"identify":1}
,"first":{"name":1,"importable":1,"record":1}
,"phone":{"number":1}
,"person":{"isn\u2019t":1}
,"isn\u2019t":{"match":1}
,"itself":{"select":1}
,"ields":{"import":1}
,"contents":{"all":1}
,"blank":{"target":1}
,"found":{"set":1,"records":1}
,"set":{"found":1,"skip":1,"validating":1}
,"table":{"record":1,"time":1,"related":1,"field":1}
,"appears":{"updated":1}
,"column":{"match":1}
,"ndicates":{"match":1,"import":1}
,"result":{"123-456-7890":1}
,"123-456-7890":{"match":1,"123-456-7890":1,"john":1}
,"john":{"don\u2019t":1,"john":1,"import":1}
,"smith":{"don\u2019t":1,"smith":1,"456":1}
,"456":{"new":1}
,"rd":{"import":1,"newtown":1}
,"123":{"main":1}
,"main":{"st":1}
,"st":{"456":1}
,"newtown":{"import":1,"usa":1}
,"anytown":{"newtown":1}
,"usa":{"import":1,"usa":1,"don\u2019t":1}
,"3\u002F3\u002F1960":{"3\u002F3\u002F1960":1,"import":1}
,"408":{"555-6789":1}
,"555-6789":{"replace":1}
,"replaced":{"data":1,"number":1,"import":1}
,"row":{"data":1}
,"overwrites":{"fields":1}
,"second":{"importable":1,"record":1}
,"doesn\u2019t":{"examine":1}
,"examine":{"compare":1}
,"compare":{"data":1}
,"field-by-field":{"basis":1}
,"basis":{"concept":1}
,"replacing":{"records":1,"existing":1}
,"extra":{"records":1}
,"imported":{"choose":1,"data":1,"during":1}
,"remaining":{"data":1}
,"single":{"table":1}
,"time":{"import":1}
,"related":{"fields":1,"field":1,"tables":1}
,"tables":{"import":1}
,"omitted":{"records":1}
,"ensure":{"imported":1}
,"correctly":{"formatted":1}
,"formatted":{"define":1}
,"define":{"fields":1}
,"validated":{"imported":1}
,"skipped":{"conform":1}
,"conform":{"validation":1}
,"validation":{"options":1}
,"validating":{"data":1}
,"routinely":{"import":1}
,"automate":{"process":1}
,"setting":{"up":1}
,"up":{"recurring":1}
,"recurring":{"imports":1}
,"creating":{"script":1}
,"script":{"im":1,"step":1}
,"im":{"port":1}
,"port":{"records":1}
,"step":{"setti":1}
,"setti":{"ng":1}
,"ng":{"up":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
,"scripts":{"methods":1}
,"methods":{"importing":1}
,"pdating":{"matching":1}
}
;Search.control.loadWordPairs(pairs);
