var pairs =
{
"get":{"encryptionstate":1}
,"encryptionstate":{"returns":1,"none":1}
,"returns":{"value":1,"if":1,"31725":1}
,"value":{"representing":1}
,"representing":{"file\u0027s":1}
,"file\u0027s":{"current":1}
,"current":{"encryption":1}
,"encryption":{"state":1}
,"state":{"get":1}
,"none":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"13.0":1}
,"13.0":{"returns":1}
,"if":{"database":1}
,"database":{"encrypted":1,"file":1}
,"encrypted":{"shared":1,"encrypted":1,"database":1}
,"shared":{"id":1}
,"id":{"return":1,"31725":1}
,"return":{"delimited":1}
,"delimited":{"list":1}
,"list":{"if":1}
,"file":{"shared":1}
,"31725":{"get":1}
}
;Search.control.loadWordPairs(pairs);
