var pairs =
{
"export":{"records":1,"criteria":1,"choose":1,"type":1,"file":1,"fields":1,"order":1,"format":1}
,"records":{"xports":1,"file":1,"excel":1,"exports":1,"currently":1,"exporting":1,"if":1,"filename":1,"web":1,"[restore":1,"[with":1}
,"xports":{"records":1}
,"file":{"dialog":1,"path":1,"allows":1,"file":1,"type":1,"paths":1,"create":1,"attachment":1,"script":1,"result":1,"appears":1,"character":1,"selected":1,"prompting":1,"name":1}
,"dialog":{"specifies":1,"boxes":1,"box":1,"text":1,"get":1,"off]":1,"create":1}
,"specifies":{"display":1}
,"display":{"dialog":1}
,"boxes":{"script":1,"let":1}
,"script":{"step":1,"absolute":1,"hosted":1,"set":1,"run":1}
,"step":{"performed":1,"last":1,"perform":1,"dialog":1,"server-side":1,"script":1,"supported":1}
,"performed":{"dialog":1}
,"let":{"user":1}
,"user":{"set":1,"go":1}
,"set":{"new":1,"list":1,"export":1,"records":1,"dialog":1,"excel":1}
,"new":{"export":1,"folders":1,"criteria":1}
,"criteria":{"create":1,"export":1}
,"create":{"folders":1,"new":1,"email":1}
,"folders":{"pecifies":1,"hat":1,"accessed":1,"ption":1,"unpaid":1}
,"pecifies":{"create":1}
,"hat":{"output":1}
,"output":{"file":1,"folder":1}
,"path":{"output":1,"list":1,"line":1,"locates":1,"database":1,"assumed":1,"http":1,"filemaker":1}
,"allows":{"file":1}
,"type":{"export":1,"folder":1,"use":1,"xml":1,"ignores":1}
,"choose":{"folder":1,"xslt":1,"output":1}
,"folder":{"want":1,"path":1,"note":1,"if":1}
,"want":{"export":1,"transform":1,"limit":1}
,"list":{"path":1,"select":1}
,"line":{"filemaker":1}
,"filemaker":{"pro":1,"go":1,"webdirect":1}
,"pro":{"advanced":1,"6.0":1}
,"advanced":{"use":1,"runs":1,"automating":1}
,"use":{"first":1,"depends":1,"find":1}
,"first":{"path":1}
,"locates":{"creating":1}
,"creating":{"file":1}
,"paths":{"file":1,"server-side":1}
,"depends":{"import":1}
,"import":{"requirements":1}
,"requirements":{"program":1}
,"program":{"exported":1}
,"exported":{"data":1,"records":1}
,"data":{"options":1,"formatting":1,"filemaker":1,"record":1,"export":1}
,"options":{"automatically":1,"dialog":1}
,"automatically":{"open":1}
,"open":{"file":1}
,"email":{"file":1}
,"attachment":{"saving":1}
,"saving":{"if":1}
,"if":{"filemaker":1,"xml":1,"want":1,"choose":1,"include":1,"dialog":1,"pecify":1,"field":1,"[not":1,"xporting":1}
,"runs":{"script":1}
,"absolute":{"path":1}
,"database":{"file":1}
,"hosted":{"path":1}
,"assumed":{"current":1}
,"current":{"user\u2019s":1,"layout\u2019s":1}
,"user\u2019s":{"documents":1}
,"documents":{"folder":1}
,"note":{"export":1}
,"excel":{"worksheet":1,"workbooks":1,"fil":1,"file":1}
,"worksheet":{"by":1}
,"by":{"choosing":1}
,"choosing":{"excel":1}
,"workbooks":{".xlsx":1}
,".xlsx":{"se":1}
,"se":{"ving":1}
,"ving":{"nd":1}
,"nd":{"sending":1}
,"sending":{"records":1}
,"fil":{"if":1}
,"xml":{"export":1,"xsl":1,"grammar":1,"xslt":1,"formats":1,"ls":1}
,"xsl":{"options":1}
,"box":{"appears":1,"user":1}
,"appears":{"xml":1,"default":1,"script":1}
,"grammar":{"choose":1,"export":1}
,"xslt":{"style":1,"source":1}
,"style":{"sheet":1}
,"sheet":{"if":1}
,"transform":{"xml":1}
,"source":{"file":1}
,"result":{"http":1}
,"http":{"request":1}
,"request":{"calculation":1,"note":1,"export":1}
,"calculation":{"generates":1}
,"generates":{"file":1}
,"fields":{"name":1}
,"name":{"numeric":1,"single-byte":1,"exists":1}
,"numeric":{"name":1}
,"single-byte":{"kana":1}
,"kana":{"character":1}
,"character":{"japanese":1,"set":1}
,"japanese":{"version":1}
,"version":{"fmpdsoresult":1}
,"fmpdsoresult":{"grammar":1}
,"order":{"export":1,"script":1,"file":1,"adding":1}
,"last":{"export":1,"exported":1}
,"default":{"edited":1,"download":1}
,"edited":{"deleted":1}
,"deleted":{"if":1}
,"select":{"apply":1}
,"apply":{"current":1}
,"layout\u2019s":{"data":1}
,"formatting":{"exported":1,"last":1}
,"6.0":{"earlier":1}
,"earlier":{"set":1}
,"adding":{"script":1}
,"perform":{"step":1,"find":1}
,"exports":{"all":1,"found":1}
,"all":{"records":1}
,"currently":{"browsed":1}
,"browsed":{"if":1}
,"limit":{"set":1}
,"exporting":{"use":1,"fmp12":1,"mp12":1}
,"find":{"request":1,"[restore]":1}
,"include":{"script":1}
,"server-side":{"script":1,"scripts":1}
,"text":{"compatible":1}
,"compatible":{"appears":1}
,"run":{"behavior":1}
,"behavior":{"if":1}
,"get":{"documentspathlisting":1,"lasterror":1}
,"documentspathlisting":{"function":1,"unpaid":1}
,"function":{"server-side":1,"returns":1}
,"scripts":{"exporting":1,"filemaker":1}
,"fmp12":{"format":1,"xml":1}
,"format":{"supported":1,"get":1}
,"supported":{"folders":1,"create":1,"filemaker":1,"mobile":1,"if":1}
,"accessed":{"paths":1}
,"go":{"exporting":1,"layout":1}
,"formats":{"supported":1}
,"ption":{"supported":1}
,"webdirect":{"th":1,"outputs":1}
,"th":{"script":1}
,"mobile":{"browsers":1}
,"browsers":{"exporting":1}
,"mp12":{"xml":1}
,"ls":{"xlsx":1}
,"xlsx":{"formats":1}
,"pecify":{"output":1}
,"selected":{"filemaker":1}
,"outputs":{"exported":1}
,"filename":{"file":1}
,"ignores":{"file":1}
,"web":{"browser\u2019s":1}
,"browser\u2019s":{"default":1}
,"download":{"location":1}
,"location":{"if":1}
,"field":{"data":1}
,"record":{"data":1}
,"lasterror":{"function":1}
,"returns":{"736":1}
,"736":{"finds":1}
,"finds":{"sorts":1}
,"sorts":{"records":1}
,"found":{"set":1}
,"prompting":{"user":1}
,"layout":{"[\u0022":1}
,"[\u0022":{"invoices":1}
,"invoices":{"\u0022]":1}
,"\u0022]":{"perform":1}
,"[restore]":{"sort":1}
,"sort":{"records":1}
,"[restore":{"dialog":1}
,"off]":{"export":1}
,"[with":{"dialog":1}
,"unpaid":{"invoice":1}
,"invoice":{"list.xlsx":1}
,"list.xlsx":{"unicode":1,")]":1}
,"unicode":{"utf-16":1}
,"utf-16":{")]":1}
,")]":{"exports":1,"export":1,"end":1}
,"exists":{"output":1}
,"[not":{"patterncount":1}
,"patterncount":{"get":1}
,"end":{"if":1}
,"xporting":{"data":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
