var pairs =
{
"eset":{"account":1}
,"account":{"password":1,"name":1,"user":1,"requires":1,"reset":1}
,"password":{"esets":1,"existing":1,"reset":1,"new":1,"account":1,"next":1,"displaying":1,"sales":1,"[account":1,"1234":1,"resets":1,"contents":1,"field":1,"accounts":1}
,"esets":{"password":1}
,"existing":{"filemaker":1}
,"filemaker":{"ccount":1,"pro":1}
,"ccount":{"account":1,"password":1}
,"name":{"allows":1,"existing":1,"sales":1,"get":1}
,"allows":{"name":1}
,"pro":{"advanced":1,"7.0":1}
,"advanced":{"ccount":1}
,"reset":{"new":1,"multiple":1,"account":1,"current":1}
,"new":{"password":1}
,"user":{"change":1}
,"change":{"password":1,"current":1}
,"next":{"login":1,"time":1}
,"login":{"forces":1}
,"forces":{"users":1}
,"users":{"change":1,"less":1}
,"time":{"log":1}
,"log":{"database":1,"account":1}
,"database":{"filemaker":1}
,"7.0":{"use":1}
,"use":{"multiple":1}
,"multiple":{"occurrences":1,"accounts":1}
,"occurrences":{"script":1}
,"script":{"step":1,"assigned":1,"script":1,"pane":1}
,"step":{"reset":1,"enable":1,"right-click":1,"resets":1}
,"accounts":{"single":1,":password]":1,"automating":1}
,"single":{"script":1}
,"assigned":{"full":1}
,"full":{"access":1}
,"access":{"privilege":1,"privileges":1}
,"privilege":{"set":1}
,"set":{"perform":1}
,"perform":{"script":1}
,"enable":{"users":1}
,"less":{"full":1}
,"privileges":{"perform":1,"script":1}
,"right-click":{"current":1}
,"current":{"script":1,"account\u0027s":1,"account":1}
,"pane":{"choose":1}
,"choose":{"grant":1}
,"grant":{"full":1}
,"resets":{"account":1,"password":1}
,"displaying":{"dialog":1}
,"dialog":{"box":1,"[\u0022":1}
,"box":{"password":1}
,"sales":{"account":1,"new":1}
,"requires":{"change":1}
,"[account":{"name":1}
,"1234":{"expire":1}
,"expire":{"password]":1}
,"password]":{"if":1}
,"if":{"want":1,"[get":1,"creating":1}
,"want":{"change":1}
,"account\u0027s":{"password":1}
,"contents":{"password":1}
,"field":{"show":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"[\u0022":{"reset":1}
,":password]":{"if":1,"end":1}
,"[get":{"lastmessagechoice":1}
,"lastmessagechoice":{"=1]":1}
,"=1]":{"reset":1}
,"get":{"accountname":1}
,"accountname":{"new":1}
,"end":{"if":1}
,"creating":{"editing":1}
,"editing":{"accounts":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
