var pairs =
{
"refresh":{"window":1,"entire":1}
,"window":{"pdates":1,"including":1,"refresh":1,"resumes":1,"freeze":1,"script":1,"use":1,"[]":1}
,"pdates":{"entire":1}
,"entire":{"contents":1,"window":1}
,"contents":{"active":1}
,"active":{"window":1}
,"including":{"related":1}
,"related":{"records":1,"data":1,"odbc":1}
,"records":{"flush":1,"related":1,"refreshed":1,"updates":1,"rows":1,"updated":1}
,"flush":{"cached":1}
,"cached":{"join":1,"external":1}
,"join":{"deletes":1,"order":1}
,"deletes":{"queries":1}
,"queries":{"related":1}
,"refreshed":{"select":1,"filemaker":1}
,"select":{"option":1,"flush":1}
,"option":{"if":1}
,"if":{"script":1,"want":1}
,"script":{"affect":1,"access":1,"step":1}
,"affect":{"related":1}
,"data":{"if":1,"sharing":1,"deletes":1,"source":1,"select":1,"filemaker":1}
,"want":{"minimize":1}
,"minimize":{"performance":1}
,"performance":{"impact":1}
,"impact":{"re-accessing":1}
,"re-accessing":{"related":1}
,"sharing":{"database":1}
,"database":{"network":1}
,"network":{"flush":1}
,"external":{"data":1}
,"odbc":{"data":1,"records":1,"table":1}
,"source":{"records":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"advanced":1,"6.0":1}
,"advanced":{"empties":1}
,"empties":{"internal":1}
,"internal":{"cache":1}
,"cache":{"refreshes":1}
,"refreshes":{"record":1}
,"record":{"data":1}
,"access":{"odbc":1}
,"6.0":{"earlier":1}
,"earlier":{"script":1}
,"step":{"updates":1,"select":1,"filemaker":1,"closes":1}
,"updates":{"entire":1,"visibility":1,"records":1,"total":1}
,"visibility":{"state":1}
,"state":{"all":1}
,"all":{"objects":1,"open":1,"records":1}
,"objects":{"hidden":1}
,"hidden":{"conditions":1}
,"conditions":{"window":1}
,"resumes":{"updating":1}
,"updating":{"active":1,"entire":1}
,"freeze":{"window":1}
,"order":{"refresh":1}
,"rows":{"current":1}
,"current":{"odbc":1}
,"table":{"update":1}
,"update":{"single":1}
,"single":{"layout":1}
,"layout":{"object":1}
,"object":{"updating":1,"script":1}
,"use":{"esh":1}
,"esh":{"object":1}
,"webdirect":{"script":1}
,"closes":{"all":1}
,"open":{"popovers":1}
,"popovers":{"updates":1}
,"total":{"field":1}
,"field":{"include":1,"[invoices":1}
,"include":{"taxes":1}
,"taxes":{"beeps":1}
,"beeps":{"all":1}
,"updated":{"go":1}
,"go":{"record\u002Frequest\u002Fpage":1}
,"record\u002Frequest\u002Fpage":{"[first]":1,"[next":1}
,"[first]":{"loop":1}
,"loop":{"set":1,"refresh":1}
,"set":{"field":1}
,"[invoices":{":total":1}
,":total":{"invoices":1,"*invoices":1}
,"invoices":{":total":1}
,"*invoices":{":tax]":1}
,":tax]":{"go":1}
,"[next":{"exit":1}
,"exit":{"last":1}
,"last":{"end":1}
,"end":{"loop":1}
,"[]":{"beep":1}
,"beep":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
