var pairs =
{
"fieldstyle":{"eturns":1,"filename":1,"function":1,"customers":1}
,"eturns":{"field":1}
,"field":{"formatting":1,"layout":1,"value":1,"returns":1,"vertical":1,"formatted":1}
,"formatting":{"applied":1}
,"applied":{"fieldname":1}
,"fieldname":{"layoutname":1,"filename":1,"-the":1}
,"layoutname":{"filename":1,"fieldname":1,"-the":1}
,"filename":{"fieldstyle":1,"layoutname":1,"-the":1}
,"-the":{"name":1}
,"name":{"open":1,"layout":1,"field":1,"value":1}
,"open":{"database":1}
,"database":{"file":1}
,"file":{"local":1,"fieldname":1,"fieldstyle":1}
,"local":{"remote":1}
,"remote":{"layoutname":1}
,"layout":{"database":1,"text":1,"customers":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"if":1}
,"if":{"field":1}
,"value":{"list":1}
,"list":{"associated":1,"standard":1,"returns":1,"current":1,"named":1}
,"associated":{"fieldstyle":1,"value":1}
,"function":{"returns":1}
,"returns":{"name":1,"standard":1,"scrolling":1,"popuplist":1,"popupmenu":1,"checkbox":1,"radiobutton":1,"calendar":1}
,"standard":{"field":1,"standard":1}
,"vertical":{"scroll":1}
,"scroll":{"bar":1}
,"bar":{"returns":1}
,"scrolling":{"drop-down":1}
,"drop-down":{"list":1,"calendar":1}
,"popuplist":{"pop-up":1}
,"pop-up":{"menu":1}
,"menu":{"returns":1}
,"popupmenu":{"checkbox":1}
,"checkbox":{"returns":1,"radio":1}
,"radio":{"button":1}
,"button":{"returns":1,"associated":1}
,"radiobutton":{"drop-down":1,"yes\u002Fno":1}
,"calendar":{"returns":1,"data":1}
,"data":{"entry":1}
,"entry":{"layout":1,"current":1}
,"customers":{"database":1,"data":1}
,"current":{"customer":1}
,"customer":{"returns":1,"field":1}
,"yes\u002Fno":{"list":1}
,"formatted":{"radio":1}
,"named":{"yes\u002Fno":1}
}
;Search.control.loadWordPairs(pairs);
