var pairs =
{
"get":{"reques":1,"requestcount":1,"request":1,"find":1}
,"reques":{"tcount":1}
,"tcount":{"returns":1}
,"returns":{"total":1,"find":1}
,"total":{"number":1}
,"number":{"find":1,"filemaker":1}
,"find":{"requests":1,"request":1}
,"requests":{"defined":1}
,"defined":{"current":1,"returns":1}
,"current":{"table":1,"file":1}
,"table":{"get":1}
,"requestcount":{"none":1,"get":1}
,"none":{"number":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"if":1}
,"if":{"multiple":1}
,"multiple":{"windows":1}
,"windows":{"open":1}
,"open":{"current":1}
,"file":{"returned":1,"calculation":1}
,"returned":{"foreground":1}
,"foreground":{"window":1}
,"window":{"file":1}
,"calculation":{"defined":1}
,"request":{"count":1}
,"count":{"get":1}
}
;Search.control.loadWordPairs(pairs);
