var pairs =
{
"open":{"script":1}
,"script":{"workspace":1,"step":1,"prevents":1,"edited":1}
,"workspace":{"pens":1,"none":1,"file":1,"script":1,"show":1,"end":1}
,"pens":{"script":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1,"advanced":1}
,"6.0":{"earlier":1}
,"earlier":{"script":1}
,"step":{"choosing":1,"performed":1}
,"choosing":{"scripts":1}
,"scripts":{"menu":1,"open":1,"script":1,"\u0022]":1}
,"menu":{"script":1,"manage":1}
,"file":{"menu":1}
,"manage":{"scripts":1,"database\u0027s":1,"database":1}
,"performed":{"filemaker":1}
,"advanced":{"alts":1}
,"alts":{"execution":1}
,"execution":{"current":1}
,"current":{"script":1}
,"prevents":{"unexpected":1}
,"unexpected":{"conditions":1}
,"conditions":{"occurring":1}
,"occurring":{"if":1}
,"if":{"currently":1,"user":1,"[get":1,"automating":1}
,"currently":{"running":1}
,"running":{"script":1}
,"edited":{"displays":1}
,"displays":{"custom":1}
,"custom":{"dialog":1}
,"dialog":{"box":1,"[\u0022":1}
,"box":{"if":1}
,"user":{"manage":1}
,"database\u0027s":{"scripts":1}
,"show":{"custom":1}
,"[\u0022":{"want":1}
,"want":{"manage":1}
,"database":{"scripts":1}
,"\u0022]":{"if":1}
,"[get":{"lastmessagechoice":1}
,"lastmessagechoice":{"=1]":1}
,"=1]":{"open":1}
,"end":{"if":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
