var pairs =
{
"managing":{"saved":1}
,"saved":{"find":1,"finds":1,"recent":1}
,"find":{"requests":1,"recent":1,"user":1,"criteria":1,"users":1,"windows":1,"macos":1,"aving":1,"request":1,"delete":1}
,"requests":{"saved":1}
,"recent":{"find":1,"finds":1}
,"user":{"depends":1,"name":1,"accounts":1,"data":1,"externally":1}
,"depends":{"account":1}
,"account":{"table":1,"saved":1,"edit":1,"lists":1,"id":1,"dialog":1}
,"table":{"layout":1}
,"layout":{"based":1}
,"based":{"including":1}
,"including":{"related":1}
,"related":{"tables":1}
,"tables":{"referenced":1}
,"referenced":{"find":1}
,"criteria":{"users":1}
,"users":{"logged":1,"sharing":1}
,"logged":{"filemaker":1,"external":1}
,"filemaker":{"file":1,"users":1}
,"file":{"account":1}
,"finds":{"recent":1,"filemaker":1,"depending":1,"external":1,"rom":1,"user":1}
,"sharing":{"account":1}
,"edit":{"duplicate":1,"saved":1,"account":1}
,"duplicate":{"delete":1}
,"delete":{"saved":1,"clear":1,"all":1}
,"external":{"authentication":1,"user":1,"server":1,"account":1}
,"authentication":{"account":1,"server":1}
,"lists":{"saved":1}
,"depending":{"account":1}
,"id":{"user":1}
,"name":{"passed":1,"data":1}
,"passed":{"external":1}
,"server":{"clear":1,"creating":1}
,"clear":{"saved":1,"edit":1}
,"accounts":{"active":1,"authenticate":1}
,"active":{"status":1}
,"status":{"toolbar":1}
,"toolbar":{"arrow":1}
,"arrow":{"next":1}
,"next":{"find":1}
,"windows":{"hold":1}
,"hold":{"find":1}
,"macos":{"choose":1}
,"choose":{"edit":1}
,"rom":{"list":1}
,"list":{"sp":1}
,"sp":{"ecify":1}
,"ecify":{"options":1}
,"options":{"saved":1}
,"aving":{"find":1}
,"request":{"follow":1}
,"follow":{"steps":1}
,"steps":{"creating":1}
,"creating":{"accounts":1}
,"authenticate":{"via":1}
,"via":{"external":1,"oauth":1}
,"oauth":{"identity":1}
,"identity":{"provider":1}
,"provider":{"access":1}
,"access":{"edit":1}
,"dialog":{"box":1}
,"box":{"edit":1,"user":1,"select":1}
,"data":{"manage":1,"external":1,"want":1}
,"manage":{"user":1}
,"select":{"user":1}
,"want":{"delete":1}
,"all":{"saved":1}
,"externally":{"authenticated":1}
,"authenticated":{"account":1}
}
;Search.control.loadWordPairs(pairs);
