var pairs =
{
"trimall":{"returns":1,"text":1,"spaces":1,"julian":1,"japanese":1}
,"returns":{"copy":1,"julian":1,"japanese":1}
,"copy":{"text":1}
,"text":{"spaces":1,"trimspaces":1,"-any":1,"expression":1,"field":1,"filemaker":1,"non-roman":1,"if":1,"string":1}
,"spaces":{"removed":1,"text":1,"full-and":1,"use":1,"set":1,"character":1,"non-ro":1,"if":1,"all":1,"non-roman":1}
,"removed":{"inserted":1,"type":1}
,"inserted":{"trimall":1,"depending":1}
,"trimspaces":{"trimtype":1,"-0":1,"true":1,"false":1}
,"trimtype":{"text":1,"-0":1,"tables":1,"value":1,"parameter":1}
,"-any":{"text":1}
,"expression":{"text":1}
,"field":{"trimspaces":1,"name":1,"japanese":1}
,"-0":{"false":1,"depending":1}
,"false":{"true":1,"if":1,"trimall":1}
,"true":{"trimtype":1,"if":1}
,"depending":{"trim":1,"value":1}
,"trim":{"style":1,"function":1}
,"style":{"use":1}
,"use":{"text":1,"trimall":1,"trim":1,"roman":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"use":1}
,"non-roman":{"spaces":1,"characters":1,"range":1,"-non-ro":1,"roman":1,"languages":1}
,"full-and":{"half-width":1}
,"half-width":{"spaces":1,"space":1}
,"function":{"set":1}
,"set":{"trimspaces":1,"trimspace":1,"true":1,"zero":1}
,"if":{"want":1,"unicode":1,"none":1,"isn\u2019t":1,"use":1,"value":1}
,"want":{"remove":1,"keep":1}
,"remove":{"full-width":1,"remove":1,"space":1,"space*1":1,"*=insert":1}
,"full-width":{"spaces":1}
,"trimspace":{"false":1,"parameter":1}
,"keep":{"full-width":1}
,"character":{"considered":1,"unicode":1,"blocks":1}
,"considered":{"roman":1,"non-roman":1}
,"roman":{"if":1,"range":1,"-roman":1,"text":1,"languages":1,"characters":1}
,"unicode":{"value":1}
,"value":{"less":1,"greater":1,"trimtype":1,"removes":1,"japanese":1}
,"less":{"2f00":1}
,"2f00":{"character":1,"considered":1}
,"greater":{"equal":1}
,"equal":{"2f00":1}
,"characters":{"roman":1,"superscripts":1,"non-roman":1,"leave":1,"reduce":1,"removed":1,"trimspace":1,"all":1}
,"range":{"belonging":1,"include":1}
,"belonging":{"character":1,"cjk":1}
,"blocks":{"latin":1,"symbols":1}
,"latin":{"latin-1":1,"extended-a":1,"greek":1}
,"latin-1":{"supplement":1}
,"supplement":{"latin":1}
,"extended-a":{"&b":1}
,"&b":{"ipa":1}
,"ipa":{"extensions":1}
,"extensions":{"spacing":1}
,"spacing":{"modifier":1}
,"modifier":{"letters":1}
,"letters":{"combining":1}
,"combining":{"diacritical":1,"marks":1}
,"diacritical":{"marks":1}
,"marks":{"greek":1,"symbols":1}
,"greek":{"cyrillic":1,"extended":1}
,"cyrillic":{"armenian":1}
,"armenian":{"hebrew":1}
,"hebrew":{"arabic":1}
,"arabic":{"devanagari":1}
,"devanagari":{"bengali":1}
,"bengali":{"gurmukhi":1}
,"gurmukhi":{"gujarati":1}
,"gujarati":{"oriya":1}
,"oriya":{"tamil":1}
,"tamil":{"telugu":1}
,"telugu":{"kannada":1}
,"kannada":{"malayalam":1}
,"malayalam":{"thai":1}
,"thai":{"lao":1}
,"lao":{"tibetan":1}
,"tibetan":{"georgian":1}
,"georgian":{"hangul":1}
,"hangul":{"jamo":1,"compatibility":1}
,"jamo":{"additional":1,"kanbun":1}
,"additional":{"latin":1}
,"extended":{"blocks":1}
,"symbols":{"roman":1,"combining":1,"letter-like":1,"number":1}
,"include":{"punctuation":1}
,"punctuation":{"characters":1}
,"superscripts":{"sub-scripts":1}
,"sub-scripts":{"currency":1}
,"currency":{"symbols":1}
,"letter-like":{"symbols":1}
,"number":{"forms":1}
,"forms":{"arrows":1}
,"arrows":{"math":1}
,"math":{"operators":1}
,"operators":{"control":1}
,"control":{"pictures":1}
,"pictures":{"geometric":1}
,"geometric":{"shapes":1}
,"shapes":{"dingbats":1}
,"dingbats":{"characters":1}
,"cjk":{"symbols\u002Fpunctuations":1,"unified":1}
,"symbols\u002Fpunctuations":{"hiragana":1}
,"hiragana":{"katakana":1}
,"katakana":{"bopomofo":1}
,"bopomofo":{"hangul":1}
,"compatibility":{"jamo":1}
,"kanbun":{"cjk":1}
,"unified":{"ideographs":1}
,"ideographs":{"spaces":1}
,"tables":{"trimtype":1}
,"removes":{"all":1,"spaces":1}
,"all":{"spaces":1,"cases":1}
,"non-ro":{"ro":1,"characters":1,"-ro":1}
,"ro":{"characters":1,"includes":1,"removes":1,"space":1}
,"leave":{"space":1}
,"space":{"ro":1,"non-ro":1,"add":1,"remove":1,"space":1,"non-roman":1,"middle":1}
,"includes":{"half-width":1}
,"reduce":{"multiple":1}
,"multiple":{"space":1}
,"add":{"spaces":1}
,"none":{"leave":1}
,"cases":{"spaces":1}
,"type":{"non-roman":1}
,"-non-ro":{"non-ro":1}
,"-ro":{"roman":1}
,"-roman":{"remove":1}
,"space*1":{"space":1}
,"*=insert":{"space":1}
,"isn\u2019t":{"full-width":1}
,"languages":{"japanese":1,"set":1}
,"japanese":{"if":1,"text":1}
,"julian":{"scott":1}
,"scott":{"dunn":1}
,"dunn":{";0;0":1,"trimall":1}
,";0;0":{"returns":1}
,"string":{"field":1,"if":1,"space":1,"roman":1}
,"name":{"trimspace":1,"field":1}
,"parameter":{"set":1}
,"zero":{"returns":1}
,"middle":{"trimall":1}
}
;Search.control.loadWordPairs(pairs);
