var pairs =
{
"converting":{"files":1,"databases":1}
,"files":{"filemaker":1,"created":1,"format":1,"onverting":1,"hen":1,"compatible":1,"modified":1,"larger":1,"part":1,"convert":1,"additional":1}
,"filemaker":{"pro":1,"knowledge":1}
,"pro":{"11":1,"advanced":1,"file":1,"12":1,"ersion":1}
,"11":{"advanced":1,"earlier":1}
,"advanced":{"filemaker":1,"version":1,"ersion":1,"creates":1,"nd":1}
,"earlier":{"files":1,"filemaker":1}
,"created":{"by":1,"filemaker":1,"manual":1}
,"by":{"current":1,"file":1}
,"current":{"filemaker":1}
,"version":{"all":1,"convert":1,"hat":1}
,"all":{"versions":1}
,"versions":{"filemaker":1,"contents":1}
,"file":{"format":1,"convert":1,"view":1,"review":1,"items":1,"conversion.log":1,"item":1,"corrected":1,"test":1,"security":1,"\u2019s":1,"follow":1,"files":1}
,"format":{"filename":1,"converted":1,"order":1,"conversion":1}
,"filename":{"extension":1}
,"extension":{".fmp12":1}
,".fmp12":{"files":1}
,"converted":{"open":1,"file":1,"sure":1,"files":1,"database":1,"convert":1}
,"open":{"current":1,"version":1}
,"ersion":{"convert":1,"7.x":1}
,"convert":{"files":1,"single":1,"multiple":1,"properly":1,"file":1,"database":1}
,"12":{"format":1,"filemaker":1,"advanced":1}
,"order":{"use":1}
,"use":{"current":1,"converted":1}
,"single":{"file":1,"multiple":1}
,"multiple":{"files":1}
,"onverting":{"single":1}
,"hen":{"convert":1}
,"creates":{"conversion.log":1}
,"conversion.log":{"file":1}
,"view":{"conversion":1}
,"conversion":{"status":1,"process":1,"files":1}
,"status":{"problems":1}
,"problems":{"occurred":1}
,"occurred":{"during":1}
,"during":{"conversion":1}
,"process":{"convert":1,"increases":1}
,"7.x":{"8.x":1}
,"8.x":{"9.x":1}
,"9.x":{"10.x":1}
,"10.x":{"11.x":1}
,"11.x":{"filemaker":1}
,"compatible":{"filemaker":1}
,"nd":{"supported":1}
,"supported":{"versions":1}
,"contents":{"original":1}
,"original":{"files":1,"file":1}
,"modified":{"open":1}
,"hat":{"created":1}
,"manual":{"corrections":1}
,"corrections":{"correct":1}
,"correct":{"re-create":1,"items":1}
,"re-create":{"items":1,"snapshot":1}
,"items":{"converted":1,"original":1,"corrected":1}
,"properly":{"cases":1}
,"cases":{"correct":1}
,"review":{"conversion.log":1}
,"corrected":{"test":1,"converted":1}
,"test":{"converted":1,"sure":1}
,"item":{"file":1}
,"sure":{"aspect":1,"script":1}
,"aspect":{"converted":1}
,"script":{"expect":1}
,"expect":{"accounts":1}
,"accounts":{"privilege":1}
,"privilege":{"sets":1}
,"sets":{"provide":1}
,"provide":{"required":1}
,"required":{"file":1}
,"security":{"converted":1}
,"larger":{"original":1}
,"part":{"conversion":1}
,"increases":{"file":1}
,"\u2019s":{"size":1}
,"size":{"crease":1}
,"crease":{"typically":1}
,"typically":{"increase":1}
,"increase":{"varies":1}
,"varies":{"by":1}
,"follow":{"general":1}
,"general":{"steps":1}
,"steps":{"converting":1}
,"database":{"file":1,"use":1,"records":1}
,"additional":{"converting":1}
,"databases":{"refer":1}
,"refer":{"filemaker":1}
,"knowledge":{"base":1}
,"base":{"snapshot":1}
,"snapshot":{"links":1,"link":1}
,"links":{"converted":1}
,"records":{"found":1}
,"found":{"re-create":1}
}
;Search.control.loadWordPairs(pairs);
