var pairs =
{
"configuring":{"quick":1}
,"quick":{"find":1}
,"find":{"if":1,"use":1,"badges":1,"badge":1,"set":1,"green":1,"layout":1,"reset":1,"settings":1,"quick":1,"search":1}
,"if":{"layout":1,"field":1,"quick":1}
,"layout":{"enabled":1,"layout":1,"mode":1,"choose":1,"disabled":1,"want":1,"pop-up":1,"setup":1,"bar":1,"improve":1}
,"enabled":{"quick":1}
,"use":{"search":1}
,"search":{"box":1,"data":1,"color":1,"take":1,"summary":1,"placing":1,"performance":1,"fields":1,"exclude":1,"all":1,"enable":1}
,"box":{"browse":1,"select":1}
,"browse":{"mode":1}
,"mode":{"search":1,"show":1,"ch":1}
,"data":{"across":1,"data":1,"tab":1,"searching":1}
,"across":{"multiple":1}
,"multiple":{"fields":1}
,"fields":{"layout":1,"selected":1,"green":1,"yellow":1,"fields":1,"can\u2019t":1,"don\u2019t":1,"inspector":1,"default":1,"by":1,"set":1,"contain":1,"included":1}
,"show":{"quick":1}
,"badges":{"supported":1,"next":1,"related":1}
,"supported":{"fields":1,"quick":1}
,"selected":{"layout":1}
,"choose":{"view":1}
,"view":{"menu":1}
,"menu":{"show":1,"layout":1}
,"badge":{"next":1,"gray":1,"layout":1,"field":1,"examples":1}
,"next":{"each":1,"field":1}
,"each":{"field":1,"song":1}
,"field":{"if":1,"enabled":1,"field":1,"searchable":1,"quick":1}
,"searchable":{"supported":1,"yellow":1,"search":1}
,"set":{"included":1,"fields":1}
,"included":{"search":1}
,"color":{"badge":1}
,"gray":{"gray":1,"quick":1}
,"disabled":{"quick":1}
,"green":{"green":1,"quick":1,"badge":1}
,"yellow":{"yellow":1,"quick":1,"badges":1}
,"take":{"fields":1}
,"examples":{"fields":1}
,"related":{"fields":1}
,"can\u2019t":{"indexed":1}
,"indexed":{"calculations":1}
,"calculations":{"fields":1}
,"don\u2019t":{"store":1}
,"store":{"calculation":1}
,"calculation":{"elect":1}
,"elect":{"fields":1}
,"inspector":{"data":1}
,"tab":{"behavior":1}
,"behavior":{"select":1}
,"select":{"include":1,"enable":1}
,"include":{"field":1,"track":1,"artist":1}
,"ch":{"oose":1}
,"oose":{"layout":1}
,"want":{"layout":1}
,"pop-up":{"menu":1}
,"setup":{"layout":1,"button":1,"dialog":1}
,"button":{"layout":1}
,"bar":{"layout":1}
,"dialog":{"box":1}
,"enable":{"quick":1,"reset":1}
,"reset":{"all":1,"quick":1,"uick":1}
,"all":{"fields":1,"songs":1}
,"default":{"quick":1,"merge":1}
,"settings":{"reset":1}
,"summary":{"container":1}
,"container":{"global":1}
,"global":{"fields":1}
,"by":{"default":1}
,"merge":{"fields":1}
,"placing":{"merge":1}
,"improve":{"search":1}
,"performance":{"limit":1}
,"limit":{"search":1}
,"contain":{"data":1}
,"searching":{"table":1}
,"table":{"songs":1}
,"songs":{"include":1,"track":1}
,"track":{"number":1}
,"number":{"artist":1,"search":1,"set":1}
,"artist":{"name":1}
,"name":{"each":1,"search":1}
,"song":{"include":1}
,"exclude":{"track":1}
,"uick":{"find":1}
}
;Search.control.loadWordPairs(pairs);
