var pairs =
{
"uerying":{"odbc":1}
,"odbc":{"data":1,"client":1,"recognize":1,"interface":1,"drivers":1,"details":1,"import":1}
,"data":{"source":1,"existing":1,"sources":1,"doesn\u2019t":1,"new":1}
,"source":{"filemaker":1,"oracle":1,"want":1,"finally":1,"fields":1,"file":1,"performing":1,"create":1,"records":1,"hoose":1,"continue":1,"open":1,"chose":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"configuring":1,"atabase":1,"database":1,"import":1,"file":1,"sql":1,"displays":1,"puts":1}
,"configuring":{"odbc":1}
,"client":{"driver":1}
,"driver":{"interact":1,"enter":1}
,"interact":{"records":1}
,"records":{"import":1,"existing":1,"want":1,"script":1,"odbc":1,"choose":1,"execute":1,"database":1}
,"import":{"records":1,"construct":1,"data":1,"existing":1,"field":1,"action":1,"mporting":1,"execute":1}
,"existing":{"filemaker":1,"file":1}
,"atabase":{"file":1}
,"file":{"create":1,"odbc":1,"map":1,"co":1,"menu":1,"choose":1,"data":1,"dialog":1,"fo":1,"filemaker":1,"etting":1,"if":1}
,"create":{"new":1,"filemaker":1}
,"new":{"filemaker":1,"record":1,"file":1}
,"database":{"file":1}
,"oracle":{"access":1}
,"access":{"databases":1,"data":1,"odbc":1}
,"databases":{"first":1}
,"first":{"access":1}
,"want":{"import":1}
,"construct":{"query":1}
,"query":{"records":1,"language":1,"builder":1,"onstructing":1,"importing":1,"copy":1,"stored":1,"field":1,"odbc":1}
,"finally":{"if":1}
,"if":{"you\u2019re":1,"data":1,"importing":1}
,"you\u2019re":{"importing":1}
,"importing":{"data":1,"existing":1,"via":1}
,"map":{"fields":1}
,"fields":{"data":1,"filemaker":1,"during":1}
,"co":{"nnecting":1}
,"nnecting":{"external":1}
,"external":{"data":1,"sql":1}
,"sources":{"access":1,"writing":1,"supported":1}
,"writing":{"sql":1}
,"sql":{"queries":1,"script":1,"structured":1,"passed":1,"server":1,"query":1,"data":1}
,"queries":{"access":1,"select":1}
,"menu":{"im":1,"import":1,"open":1}
,"im":{"port":1}
,"port":{"records":1}
,"script":{"step":1}
,"step":{"xecute":1,"all":1,"execute":1,"external":1}
,"xecute":{"sql":1}
,"all":{"applications":1,"unicode":1}
,"applications":{"support":1}
,"support":{"odbc":1}
,"recognize":{"basic":1}
,"basic":{"subset":1}
,"subset":{"sql":1}
,"structured":{"query":1}
,"language":{"statements":1}
,"statements":{"sql":1}
,"passed":{"odbc":1,"sql":1}
,"interface":{"data":1}
,"performing":{"queries":1}
,"select":{"first_name":1,"save":1}
,"first_name":{"last_name":1}
,"last_name":{"customers":1,"values":1}
,"customers":{"city=n\u0027paris":1,"first_name":1}
,"city=n\u0027paris":{"updates":1}
,"updates":{"creation":1}
,"creation":{"new":1}
,"record":{"insert":1}
,"insert":{"customers":1}
,"values":{"n\u0027jane":1}
,"n\u0027jane":{"n\u0027smith":1}
,"n\u0027smith":{"note":1}
,"note":{"sql":1}
,"server":{"supports":1,"lose":1,"code":1}
,"supports":{"unicode":1}
,"unicode":{"non-unicode":1,"strings":1,"string":1}
,"non-unicode":{"field":1}
,"field":{"types":1,"use":1,"toring":1,"details":1,"mapping":1}
,"types":{"prefix":1}
,"prefix":{"all":1}
,"strings":{"uppercase":1}
,"uppercase":{"stands":1}
,"stands":{"ational":1}
,"ational":{"sql-92":1}
,"sql-92":{"standard":1}
,"standard":{"unicode":1}
,"string":{"non-english":1}
,"non-english":{"characters":1}
,"characters":{"passed":1}
,"lose":{"data":1}
,"doesn\u2019t":{"exist":1}
,"exist":{"sql":1}
,"code":{"page":1}
,"page":{"filemaker":1}
,"choose":{"file":1,"odbc":1}
,"open":{"th":1,"file":1,"requirement":1}
,"th":{"open":1}
,"dialog":{"box":1}
,"box":{"locate":1,"future":1,"appears":1,"map":1}
,"locate":{"file":1}
,"fo":{"files":1}
,"files":{"type":1}
,"type":{"windows":1}
,"windows":{"show":1}
,"show":{"macos":1}
,"macos":{"choose":1}
,"hoose":{"data":1}
,"continue":{"server-based":1}
,"server-based":{"odbc":1}
,"drivers":{"require":1}
,"require":{"data":1}
,"requirement":{"varies":1}
,"varies":{"depending":1}
,"depending":{"driver":1}
,"enter":{"user":1}
,"user":{"name":1}
,"name":{"password":1}
,"password":{"if":1,"option":1}
,"chose":{"skip":1}
,"skip":{"dialog":1}
,"future":{"select":1}
,"save":{"user":1}
,"option":{"if":1}
,"builder":{"dialog":1}
,"appears":{"construct":1}
,"onstructing":{"sql":1}
,"via":{"odbc":1}
,"details":{"execute":1}
,"execute":{"query":1,"sql":1,"if":1}
,"copy":{"paste":1}
,"paste":{"field":1}
,"use":{"use":1,"import":1}
,"stored":{"field":1}
,"toring":{"sql":1}
,"displays":{"import":1}
,"mapping":{"dialog":1,"fields":1}
,"etting":{"import":1}
,"action":{"mapping":1}
,"during":{"import":1}
,"mporting":{"data":1}
,"puts":{"imported":1}
,"imported":{"records":1}
,"supported":{"runtime":1}
,"runtime":{"solutions":1}
,"solutions":{"query":1}
}
;Search.control.loadWordPairs(pairs);
