var pairs =
{
"considerations":{"create":1}
,"create":{"report":1,"layouts":1}
,"report":{"layout":1,"easily":1,"grouped":1,"future":1,"displays":1}
,"layout":{"creating":1,"grouped":1,"choice":1,"sorts":1,"type":1,"create":1,"include":1,"view":1,"new":1,"separately":1,"arranges":1}
,"creating":{"report":1}
,"grouped":{"data":1}
,"data":{"want":1,"by":1,"refer":1,"fields":1}
,"want":{"report":1,"categorize":1,"summarize":1,"running":1}
,"easily":{"proceed":1}
,"proceed":{"new":1}
,"new":{"layout\u002Freport":1}
,"layout\u002Freport":{"assistant":1}
,"assistant":{"assistant":1,"field":1,"if":1,"create":1,"set":1}
,"field":{"fields":1,"names":1,"size":1}
,"fields":{"want":1,"assistant":1,"left":1,"choose":1,"columns":1}
,"categorize":{"group":1}
,"group":{"data":1}
,"by":{"if":1,"choosing":1,"category":1}
,"if":{"including":1,"define":1,"trouble":1,"script":1,"plan":1,"re-create":1}
,"including":{"subtotals":1}
,"subtotals":{"grand":1}
,"grand":{"totals":1}
,"totals":{"fields":1,"organize":1}
,"summarize":{"define":1}
,"define":{"summary":1}
,"summary":{"fields":1}
,"trouble":{"want":1}
,"refer":{"onscreen":1}
,"onscreen":{"help":1}
,"help":{"each":1}
,"each":{"panel":1,"layout":1}
,"panel":{"assistant":1}
,"choice":{"saving":1}
,"saving":{"script":1}
,"script":{"switches":1,"scripts":1,"view":1,"add":1,"step":1}
,"switches":{"layout":1}
,"sorts":{"records":1}
,"records":{"if":1,"by":1,"list":1,"columns":1}
,"scripts":{"menu":1}
,"menu":{"choose":1,"cript":1,"printer":1}
,"choose":{"run":1,"file":1}
,"run":{"report":1}
,"future":{"verify":1}
,"verify":{"viewing":1}
,"viewing":{"found":1}
,"found":{"set":1}
,"set":{"want":1,"up":1}
,"running":{"script":1}
,"view":{"edit":1,"layout":1,"records":1,"browse":1}
,"edit":{"script":1}
,"add":{"find":1}
,"find":{"script":1}
,"step":{"by":1}
,"choosing":{"scripts":1}
,"cript":{"workspace":1}
,"workspace":{"create":1}
,"displays":{"fields":1}
,"left":{"right":1}
,"right":{"across":1}
,"across":{"page":1}
,"page":{"field":1,"reduce":1,"setup":1,"orientation":1,"options":1}
,"names":{"column":1,"addresses":1}
,"column":{"headings":1}
,"headings":{"simple":1}
,"simple":{"list":1}
,"list":{"predefined":1,"view":1,"columns":1}
,"predefined":{"layout":1}
,"type":{"list":1}
,"include":{"subtotals":1}
,"organize":{"records":1}
,"category":{"save":1}
,"save":{"layout":1}
,"browse":{"mode":1}
,"mode":{"if":1,"print":1}
,"plan":{"printing":1}
,"printing":{"records":1}
,"columns":{"extend":1,"print":1,"arrange":1}
,"extend":{"width":1}
,"width":{"page":1}
,"reduce":{"field":1,"scale":1}
,"size":{"font":1,"data":1}
,"font":{"size":1}
,"file":{"menu":1}
,"printer":{"setup":1,"page":1}
,"setup":{"windows":1,"macos":1,"dialog":1}
,"windows":{"page":1}
,"macos":{"preview":1,"status":1}
,"preview":{"mode":1}
,"print":{"setup":1,"less":1,"each":1,"multi":1,"records":1}
,"status":{"toolbar":1}
,"toolbar":{"setup":1}
,"dialog":{"box":1}
,"box":{"change":1}
,"change":{"page":1}
,"orientation":{"horizontal":1}
,"horizontal":{"landscape":1}
,"landscape":{"reduce":1}
,"scale":{"print":1}
,"less":{"100":1}
,"100":{"if":1}
,"re-create":{"layout":1}
,"up":{"printer":1,"print":1}
,"options":{"create":1}
,"layouts":{"show":1}
,"show":{"columns":1}
,"separately":{"report":1}
,"arranges":{"fields":1}
,"arrange":{"records":1}
,"multi":{"olumn":1}
,"olumn":{"directory":1}
,"directory":{"names":1}
,"addresses":{"setting":1}
,"setting":{"up":1}
}
;Search.control.loadWordPairs(pairs);
