var pairs =
{
"diting":{"record":1}
,"record":{"access":1,"calculation":1,"privileges":1,"features":1,"records":1,"viewing":1,"database":1,"created":1,"editing":1,"exits":1,"committed":1,"user":1,"cases":1,"multiple":1}
,"access":{"privileges":1,"records":1,"limits":1,"allowed":1,"activity":1,"modify":1,"fields":1,"field":1,"design":1,"manage":1,"record-by-record":1,"modification":1,"choose":1,"select":1,"prohibit":1,"lookups":1,"privilege":1,"limited":1,"confidential":1,"change":1,"prohibited":1,"record":1,"calculation":1,"calculations":1}
,"privileges":{"privilege":1,"all":1,"individual":1,"limited":1,"tables":1,"custom":1,"dialog":1,"select":1,"table":1,"viewing":1,"choose":1,"want":1,"field":1,"minimum":1,"lookup":1,"destination":1,"filemaker":1,"order":1,"prohibited":1,"fields":1,"permits":1,"usually":1,"affect":1,"allow":1,"records":1,"record_created_by":1,"record_creation_date":1,"unexpected":1,"global":1}
,"privilege":{"sets":1,"set":1,"start":1,"viewing":1,"restrictions":1,"permitted":1,"calculations":1}
,"sets":{"limit":1,"files":1,"extended":1,"data":1,"summary":1}
,"limit":{"access":1,"privilege":1,"ability":1}
,"records":{"file":1,"all":1,"each":1,"choose":1,"prohibit":1,"limited":1,"records":1,"table":1,"note":1,"view":1,"browse":1,"user":1,"fields":1,"viewable":1,"copy":1,"access":1,"exclude":1,"edit":1,"created":1,"calculation":1,"inadvertently":1}
,"file":{"file":1,"set":1,"custom":1,"if":1,"relationships":1,"table":1,"shared":1}
,"set":{"privileges":1,"allows":1,"individual":1,"limit":1,"record":1,"edit":1,"dialog":1,"choose":1,"accounts":1,"custom":1,"filtered":1,"option":1,"delete":1,"auto-enter":1,"sort":1}
,"all":{"tables":1,"records":1,"access":1,"by":1}
,"tables":{"limit":1,"file":1,"set":1,"defined":1,"files":1,"se":1,"create":1,"permit":1,"view":1,"prohibit":1,"all":1,"want":1,"match":1,"edit":1,"entering":1}
,"allows":{"creating":1}
,"creating":{"editing":1,"deleting":1,"inconsistent":1}
,"editing":{"deleting":1,"new":1,"privilege":1,"records":1,"accounts":1,"creating":1,"field":1,"scripts":1,"user":1}
,"deleting":{"records":1,"privileges":1,"types":1}
,"custom":{"privileges":1,"record":1,"field":1}
,"individual":{"tables":1,"record":1}
,"limits":{"each":1}
,"each":{"table":1,"record":1,"field":1,"window":1}
,"table":{"privilege":1,"view":1,"privileges":1,"access":1,"visible":1,"set":1,"created":1,"selected":1,"calculation":1,"continue":1,"fields":1,"summarizes":1,"boolean":1,"cases":1,"notes":1}
,"ability":{"view":1,"user":1}
,"view":{"edit":1,"all":1,"limit":1,"allow":1,"records":1,"privileges":1,"boolean":1}
,"edit":{"create":1,"delete":1,"privilege":1,"all":1,"custom":1,"privileges":1,"record":1}
,"create":{"delete":1,"accounts":1,"edit":1}
,"delete":{"all":1,"records":1,"lists":1,"privileges":1,"data":1,"record":1}
,"limited":{"by":1,"single":1,"custom":1,"value":1,"summary":1,"privileges":1}
,"by":{"calculation":1,"components":1,"data":1,"current":1,"users":1,"moving":1}
,"calculation":{"returns":1,"evaluates":1,"dialog":1,"entering":1,"determines":1,"defining":1,"prohibit":1}
,"returns":{"boolean":1}
,"boolean":{"esult":1,"calculation":1,"record":1}
,"esult":{"each":1}
,"evaluates":{"true":1,"false":1,"fa":1}
,"true":{"access":1,"non-zero":1,"limit":1,"if":1}
,"allowed":{"specific":1,"access":1,"calculation":1}
,"specific":{"activity":1}
,"activity":{"viewing":1,"prohibited":1}
,"viewing":{"record":1,"records":1,"editing":1,"field":1}
,"false":{"access":1,"zero":1}
,"prohibited":{"access":1,"table":1,"field":1,"find\u002Freplace":1,"calculation":1}
,"modify":{"fields":1}
,"fields":{"each":1,"restricted":1,"table":1,"want":1,"prohibited":1,"tables":1,"relationship":1,"view":1,"calculated":1,"displayed":1,"summarize":1,"modifiable":1,"editable":1,"contain":1,"improve":1,"separate":1,"fields":1,"global":1}
,"restricted":{"table":1,"data":1}
,"visible":{"user":1}
,"user":{"access":1,"change":1,"limited":1,"get":1,"browse":1,"view":1,"exits":1,"type":1}
,"field":{"data":1,"access":1,"privileges":1,"want":1,"set":1,"created":1,"note":1,"lookup":1,"view":1,"value":1,"named":1,"automatically":1,"it\u2019s":1}
,"data":{"set":1,"access":1,"view":1,"editing":1,"allowed":1,"sers":1,"each":1,"minimum":1,"records":1,"features":1,"fail":1,"apple":1,"entry":1}
,"defined":{"current":1,"by":1}
,"current":{"file":1,"account":1,"date":1}
,"if":{"file":1,"lookup":1,"access":1,"don\u2019t":1,"user":1,"calculation":1,"based":1}
,"relationships":{"tables":1}
,"files":{"want":1,"protect":1}
,"want":{"protect":1,"edit":1,"permit":1,"limit":1,"display":1}
,"protect":{"create":1,"tables":1}
,"accounts":{"privilege":1,"creating":1,"start":1}
,"se":{"accounts":1,"creating":1,"defining":1}
,"extended":{"privilege":1}
,"start":{"editing":1}
,"new":{"existing":1,"table":1,"field":1}
,"existing":{"privilege":1}
,"dialog":{"box":1}
,"box":{"ee":1,"assign":1,"creating":1,"select":1,"enter":1}
,"ee":{"creating":1}
,"design":{"records":1}
,"choose":{"ption":1,"permit":1,"custom":1,"options":1,"allow":1,"limited":1,"modifiable":1}
,"ption":{"edit":1}
,"permit":{"creating":1,"viewing":1,"users":1}
,"prohibit":{"deleting":1,"creating":1,"accessing":1,"privilege":1,"access":1,"record":1,"viewing":1,"editing":1}
,"accessing":{"records":1,"related":1}
,"manage":{"security":1}
,"security":{"dialog":1}
,"assign":{"privilege":1}
,"select":{"tables":1,"new":1,"table":1,"each":1}
,"created":{"set":1,"choose":1,"by":1,"se":1,"current":1}
,"options":{"view":1,"choose":1}
,"lists":{"set":1,"value":1}
,"allow":{"privilege":1,"prohibit":1,"viewing":1,"users":1}
,"single":{"table":1}
,"selected":{"allow":1}
,"enter":{"calculation":1,"account":1,"creation":1}
,"entering":{"formula":1}
,"formula":{"limiting":1}
,"limiting":{"access":1,"data":1}
,"record-by-record":{"basis":1}
,"basis":{"prohibit":1}
,"note":{"avoid":1,"access":1}
,"avoid":{"creating":1}
,"inconsistent":{"combinations":1}
,"combinations":{"view":1}
,"users":{"delete":1,"inadvertently":1,"edit":1,"auto-entered":1}
,"modification":{"fields":1,"dates":1}
,"continue":{"next":1}
,"next":{"step":1,"lower":1}
,"step":{"select":1}
,"modifiable":{"allow":1,"scripts":1}
,"sers":{"view":1}
,"browse":{"records":1,"access":1}
,"features":{"filemaker":1,"feature":1,"records":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"limit":1,"display":1}
,"summarizes":{"effects":1}
,"effects":{"features":1}
,"feature":{"limiting":1}
,"lookups":{"relookups":1}
,"relookups":{"lookups":1,"defined":1}
,"components":{"all":1}
,"minimum":{"match":1,"source":1,"matching":1,"finds":1,"get":1}
,"match":{"fields":1,"occur":1}
,"relationship":{"view":1,"related":1}
,"lookup":{"occur":1,"view":1,"edit":1,"operation":1}
,"occur":{"records":1,"under":1}
,"viewable":{"source":1}
,"source":{"destination":1,"field":1}
,"destination":{"tables":1,"field":1}
,"under":{"circumstances":1}
,"circumstances":{"includes":1}
,"includes":{"first":1}
,"first":{"related":1}
,"related":{"matching":1,"data":1,"fields":1}
,"matching":{"record":1,"fields":1}
,"copy":{"next":1}
,"lower":{"value":1}
,"value":{"minimum":1,"lists":1,"list":1}
,"display":{"error":1,"based":1,"records":1,"values":1}
,"error":{"message":1}
,"message":{"if":1}
,"operation":{"skips":1}
,"skips":{"records":1}
,"restrictions":{"accessing":1}
,"order":{"relationship":1,"reasons":1}
,"based":{"matching":1,"content":1,"user-editable":1}
,"finds":{"found":1}
,"found":{"set":1,"sets":1}
,"filtered":{"display":1}
,"get":{"foundcount":1,"set":1,"functions":1}
,"foundcount":{"function":1}
,"function":{"if":1,"hidden":1}
,"list":{"based":1,"display":1}
,"content":{"field":1,"result":1}
,"values":{"users":1,"part":1,"found":1}
,"inadvertently":{"gain":1,"allow":1,"deny":1}
,"gain":{"access":1}
,"confidential":{"valuelistitems":1}
,"valuelistitems":{"function":1}
,"hidden":{"access":1}
,"summary":{"fields":1,"values":1,"get":1}
,"calculated":{"fields":1}
,"displayed":{"summary":1}
,"summarize":{"multiple":1}
,"multiple":{"records":1,"windows":1}
,"exclude":{"data":1}
,"find\u002Freplace":{"replace":1}
,"replace":{"contents":1}
,"contents":{"spelling":1}
,"spelling":{"checking":1}
,"checking":{"user":1}
,"change":{"data":1,"restricted":1,"record\u2019s":1}
,"scripts":{"set":1,"apple":1}
,"option":{"script":1,"field":1}
,"script":{"run":1,"perform":1,"steps":1}
,"run":{"full":1}
,"full":{"access":1}
,"permits":{"script":1}
,"perform":{"operations":1}
,"operations":{"user":1}
,"usually":{"if":1}
,"don\u2019t":{"enable":1}
,"enable":{"option":1}
,"steps":{"attempt":1}
,"attempt":{"access":1}
,"fail":{"se":1,"if":1}
,"apple":{"events":1,"event":1}
,"events":{"data":1,"apple":1}
,"affect":{"ability":1}
,"event":{"commands":1}
,"commands":{"fail":1}
,"determines":{"privilege":1,"record":1}
,"permitted":{"each":1}
,"database":{"access":1}
,"non-zero":{"result":1}
,"result":{"access":1,"boolean":1}
,"zero":{"two":1}
,"two":{"examples":1}
,"examples":{"limit":1}
,"account":{"define":1,"name":1,"names":1}
,"define":{"text":1,"date":1}
,"text":{"field":1}
,"named":{"record_created_by":1,"record_creation_date":1}
,"record_created_by":{"set":1,"=get":1}
,"auto-enter":{"option":1}
,"automatically":{"enter":1}
,"name":{"record":1}
,"defining":{"automatic":1,"custom":1,"global":1}
,"automatic":{"data":1}
,"entry":{"use":1}
,"use":{"calculation":1}
,"=get":{"accountname":1,"currentdate":1}
,"accountname":{"user":1}
,"date":{"define":1,"field":1,"record":1}
,"record_creation_date":{"set":1,"=get":1}
,"creation":{"date":1,"dates":1}
,"currentdate":{"user":1}
,"cases":{"use":1,"base":1}
,"types":{"records":1}
,"unexpected":{"if":1}
,"user-editable":{"field":1}
,"it\u2019s":{"user":1}
,"deny":{"themselves":1}
,"themselves":{"access":1}
,"record\u2019s":{"content":1}
,"fa":{"lse":1}
,"lse":{"user":1}
,"exits":{"record":1}
,"committed":{"user":1}
,"type":{"return":1}
,"return":{"record":1}
,"base":{"record":1,"privilege":1}
,"calculations":{"fields":1,"summary":1}
,"editable":{"by":1}
,"auto-entered":{"fields":1}
,"contain":{"account":1}
,"names":{"creation":1}
,"dates":{"modification":1,"if":1}
,"shared":{"boolean":1}
,"global":{"fields":1,"storage":1}
,"improve":{"network":1}
,"network":{"performance":1}
,"performance":{"by":1}
,"moving":{"global":1}
,"separate":{"table":1}
,"notes":{"defining":1}
,"storage":{"support":1}
,"support":{"multiple":1}
,"windows":{"own":1,"each":1}
,"own":{"found":1}
,"part":{"found":1}
,"window":{"own":1}
,"sort":{"order":1}
,"reasons":{"base":1}
,"functions":{"rely":1}
,"rely":{"values":1}
}
;Search.control.loadWordPairs(pairs);
