var pairs =
{
"adding":{"selecting":1,"ilemaker":1}
,"selecting":{"table":1}
,"table":{"occurrences":1,"occurrence":1,"button":1,"dialog":1,"name":1,"ame":1,"set":1,"select":1,"add":1}
,"occurrences":{"all":1,"select":1,"want":1}
,"all":{"table":1}
,"occurrence":{"relationships":1,"current":1,"external":1,"each":1,"based":1}
,"relationships":{"relationships":1,"graph":1,"tab":1}
,"graph":{"includes":1,"unique":1,"database":1,"select":1}
,"includes":{"tables":1}
,"tables":{"rom":1,"add":1,"choose":1,"button":1,"related":1,"1-away":1,"highlight":1,"source":1}
,"rom":{"external":1}
,"external":{"data":1}
,"data":{"sources":1,"source":1}
,"sources":{"add":1,"odbc":1,"edit":1,"manage":1,"ee":1,"if":1}
,"add":{"table":1,"filemaker":1,"odbc":1,"new":1,"multiple-path":1}
,"select":{"related":1,"table":1,"filemaker":1,"dbc":1,"next":1,"tables":1}
,"related":{"choose":1,"tables":1,"select":1,"table":1}
,"choose":{"file":1,"data":1,"select":1,"table":1,"highlight":1,"command":1}
,"file":{"menu":1,"select":1,"dialog":1}
,"menu":{"manage":1}
,"manage":{"database":1,"data":1}
,"database":{"relationships":1,"orking":1}
,"tab":{"add":1}
,"button":{"table":1,"choose":1}
,"dialog":{"box":1}
,"box":{"add":1}
,"current":{"file":1,"filemaker":1}
,"name":{"list":1,"add":1,"table":1,"open":1}
,"list":{"tables":1}
,"source":{"choose":1,"select":1,"quickest":1,"existing":1,"name":1,"add":1,"table":1}
,"ame":{"list":1}
,"filemaker":{"pro":1,"data":1}
,"pro":{"advanced":1}
,"advanced":{"ile":1}
,"ile":{"current":1,"open":1}
,"open":{"file":1,"relationships":1}
,"quickest":{"method":1}
,"method":{"adding":1}
,"ilemaker":{"data":1}
,"dbc":{"data":1}
,"existing":{"odbc":1,"data":1}
,"odbc":{"data":1}
,"new":{"diting":1}
,"diting":{"odbc":1}
,"multiple-path":{"filemaker":1}
,"edit":{"duplicate":1}
,"duplicate":{"delete":1}
,"delete":{"existing":1}
,"ee":{"co":1}
,"co":{"nnecting":1}
,"nnecting":{"external":1}
,"if":{"change":1}
,"change":{"name":1}
,"each":{"table":1}
,"unique":{"name":1}
,"orking":{"ith":1}
,"ith":{"relationships":1}
,"want":{"highlight":1}
,"highlight":{"choose":1,"tables":1,"table":1}
,"1-away":{"choose":1}
,"command":{"select":1}
,"next":{"related":1}
,"set":{"related":1}
,"based":{"source":1}
}
;Search.control.loadWordPairs(pairs);
