var pairs =
{
"getrepetition":{"returns":1,"repeatingfield":1,"parcelbids":1,"if":1}
,"returns":{"contents":1,"reference":1,"1200":1}
,"contents":{"repeating":1,"repetition":1}
,"repeating":{"field":1}
,"field":{"by":1,"expression":1,"number":1,"repetition":1,"brackets":1,"parcelbids":1,"defined":1}
,"by":{"number":1}
,"number":{"getrepetition":1,"repeatingfield":1,"-the":1,"text":1,"date":1}
,"repeatingfield":{"number":1,"-any":1}
,"-any":{"repeating":1}
,"expression":{"returns":1}
,"reference":{"repeating":1}
,"-the":{"field":1}
,"repetition":{"number":1,"repeating":1}
,"text":{"number":1}
,"date":{"time":1}
,"time":{"timestamp":1}
,"timestamp":{"container":1}
,"container":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"find":1}
,"find":{"contents":1}
,"brackets":{"[]":1}
,"[]":{"array":1}
,"array":{"operators":1}
,"operators":{"parcelbids":1}
,"parcelbids":{"[2]":1,"field":1,"returns":1,"true":1,"housebids":1}
,"[2]":{"returns":1}
,"1200":{"contents":1,"1500":1,"getrepetition":1}
,"defined":{"repeat":1}
,"repeat":{"values":1}
,"values":{"values":1,"2500":1}
,"2500":{"1200":1}
,"1500":{"getrepetition":1}
,"if":{"isempty":1}
,"isempty":{"parcelbids":1}
,"true":{"parcelbids":1}
,"housebids":{"returns":1}
}
;Search.control.loadWordPairs(pairs);
