var pairs =
{
"selecting":{"objects":1}
,"objects":{"panel":1,"select":1,"drag":1,"multiple":1,"anel":1,"add":1,"distribute":1,"horizontally":1,"size":1,"resizing":1,"if":1,"tab":1,"define":1,"frontmost":1}
,"panel":{"controls":1,"slide":1,"tab":1,"switch":1,"front":1,"want":1,"panel":1,"control":1,"shift-click":1,"own":1,"rranging":1,"press":1,"use":1,"move":1}
,"controls":{"layout":1}
,"layout":{"mode":1,"script":1}
,"mode":{"select":1}
,"select":{"tab":1,"front":1,"panel":1,"all":1,"multiple":1,"select":1,"objects":1}
,"tab":{"panels":1,"panel":1,"dot":1,"inspector":1,"order":1,"key":1}
,"panels":{"slide":1,"objects":1,"tab":1,"dot":1,"want":1,"all":1,"elect":1,"rranging":1}
,"slide":{"panels":1,"panel":1}
,"front":{"tab":1,"slide":1,"select":1,"gain":1,"if":1,"situation":1}
,"switch":{"tab":1,"anels":1}
,"want":{"front":1,"selected":1,"select":1,"control":1,"automate":1,"bring":1}
,"dot":{"panel":1,"bring":1,"switch":1}
,"control":{"lick":1,"select":1,"fields":1}
,"lick":{"tab":1}
,"bring":{"panel":1,"front":1}
,"gain":{"hift-click":1}
,"hift-click":{"additional":1}
,"additional":{"ab":1}
,"ab":{"dots":1}
,"dots":{"ntil":1}
,"ntil":{"all":1}
,"all":{"panels":1,"tab":1,"objects":1}
,"selected":{"select":1}
,"drag":{"arrow":1}
,"arrow":{"pointer":1}
,"pointer":{"selection":1}
,"selection":{"box":1,"modify":1,"choose":1}
,"box":{"surrounds":1}
,"surrounds":{"panel":1}
,"multiple":{"objects":1,"panels":1}
,"shift-click":{"each":1,"nother":1,"objects":1}
,"each":{"object":1}
,"object":{"want":1,"name":1,"script":1}
,"elect":{"objects":1}
,"anel":{"shift-click":1,"saved":1,"if":1,"filemaker":1}
,"nother":{"tab":1}
,"anels":{"shift-click":1}
,"add":{"selection":1}
,"modify":{"selection":1}
,"choose":{"options":1}
,"options":{"arrange":1}
,"arrange":{"&align":1}
,"&align":{"position":1}
,"position":{"position":1,"tab":1}
,"inspector":{"align":1}
,"align":{"edges":1}
,"edges":{"objects":1}
,"distribute":{"objects":1}
,"horizontally":{"vertically":1}
,"vertically":{"objects":1}
,"size":{"multiple":1}
,"rranging":{"objects":1}
,"resizing":{"reshaping":1}
,"reshaping":{"objects":1}
,"if":{"save":1,"want":1,"script":1,"field":1}
,"save":{"records":1}
,"records":{"excel":1,"xporting":1}
,"excel":{"file":1}
,"file":{"fields":1,"export":1}
,"fields":{"frontmost":1,"excel":1}
,"frontmost":{"anel":1}
,"saved":{"if":1}
,"export":{"records":1}
,"xporting":{"data":1}
,"data":{"filemaker":1,"entry":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"objects":1,"selects":1}
,"own":{"stacking":1}
,"stacking":{"order":1}
,"order":{"panel":1,"objects":1,"setting":1,"data":1}
,"define":{"custom":1}
,"custom":{"tab":1}
,"press":{"tab":1}
,"key":{"navigate":1}
,"navigate":{"objects":1}
,"automate":{"navigation":1}
,"navigation":{"panel":1}
,"use":{"go":1,"object":1}
,"go":{"field":1}
,"field":{"script":1,"panel":1,"frontmost":1,"moves":1,"appears":1,"first":1,"that\u2019s":1}
,"script":{"step":1,"locates":1}
,"step":{"target":1,"specifies":1,"locate":1}
,"target":{"field":1}
,"setting":{"tab":1}
,"entry":{"if":1}
,"specifies":{"field":1}
,"selects":{"field":1}
,"moves":{"panel":1}
,"appears":{"layout":1}
,"locates":{"field":1}
,"first":{"panel":1}
,"move":{"forward":1,"front":1}
,"forward":{"panel":1}
,"situation":{"assign":1}
,"assign":{"object":1}
,"name":{"field":1}
,"that\u2019s":{"panel":1}
,"locate":{"instance":1}
,"instance":{"field":1}
}
;Search.control.loadWordPairs(pairs);
