var pairs =
{
"get":{"systemnicaddr":1,"systemnicaddress":1,"persistentid":1,"mac":1,"system":1}
,"systemnicaddr":{"ess":1}
,"ess":{"returns":1}
,"returns":{"hardware":1,"address":1,"empty":1,"00:07:34:4e:c2:0d":1}
,"hardware":{"addresses":1}
,"addresses":{"all":1}
,"all":{"nic":1}
,"nic":{"network":1,"address":1}
,"network":{"interface":1}
,"interface":{"controller":1}
,"controller":{"cards":1}
,"cards":{"connected":1}
,"connected":{"computer":1}
,"computer":{"get":1}
,"systemnicaddress":{"none":1,"get":1}
,"none":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1,"go":1,"knowledge":1}
,"pro":{"7.0":1}
,"7.0":{"values":1}
,"values":{"list":1}
,"list":{"returned":1}
,"returned":{"by":1}
,"by":{"function":1,"carriage":1,"colons":1}
,"function":{"separated":1,"supported":1,"reliable":1,"filemaker":1}
,"separated":{"by":1}
,"carriage":{"returns":1}
,"address":{"consists":1,"ios":1,"get":1}
,"consists":{"bytes":1}
,"bytes":{"displayed":1}
,"displayed":{"hexadecimal":1}
,"hexadecimal":{"separated":1}
,"colons":{"filemaker":1}
,"webdirect":{"function":1}
,"supported":{"returns":1}
,"empty":{"string":1}
,"string":{"filemaker":1}
,"go":{"function":1}
,"reliable":{"method":1}
,"method":{"obtaining":1}
,"obtaining":{"address":1}
,"ios":{"device":1}
,"device":{"identify":1,"use":1}
,"identify":{"ios":1}
,"use":{"get":1}
,"persistentid":{"function":1}
,"knowledge":{"base":1}
,"base":{"returns":1}
,"00:07:34:4e:c2:0d":{"get":1}
,"mac":{"address":1}
,"system":{"nic":1}
}
;Search.control.loadWordPairs(pairs);
