var pairs =
{
"delete":{"record\u002Frequest":1,"master":1,"active":1,"portal":1,"related":1,"go":1,"current":1,"&products":1}
,"record\u002Frequest":{"eletes":1,"script":1,"if":1,"related":1,"active":1,"[with":1}
,"eletes":{"current":1}
,"current":{"record":1,"find":1,"layout":1,"product":1}
,"record":{"find":1,"request":1,"sure":1,"want":1,"portal":1,"selected":1,"perform":1,"if":1,"[from":1}
,"find":{"request":1,"mode":1}
,"request":{"dialog":1,"filemaker":1,"delete":1,"sure":1,"want":1}
,"dialog":{"specifies":1,"box":1,"on]":1,"[\u0022":1,"off]":1}
,"specifies":{"display":1}
,"display":{"dialog":1}
,"box":{"script":1,"if":1}
,"script":{"step":1,"steps":1}
,"step":{"performed":1,"browse":1,"deletes":1,"note":1}
,"performed":{"users":1}
,"users":{"confirm":1}
,"confirm":{"deletion":1}
,"deletion":{"record":1,"records":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"undo":1}
,"undo":{"delete":1}
,"browse":{"mode":1}
,"mode":{"script":1,"deletes":1}
,"deletes":{"current":1}
,"master":{"record":1}
,"sure":{"record":1,"related":1,"find":1}
,"want":{"delete":1}
,"active":{"use":1,"ortal":1,"portal":1}
,"use":{"navigation":1,"delete":1}
,"navigation":{"script":1}
,"steps":{"use":1}
,"if":{"current":1,"relationship":1,"user":1,"[get":1,"adding":1}
,"layout":{"portal":1,"roduct":1}
,"portal":{"record":1,"sure":1,"row":1,"based":1}
,"related":{"record":1}
,"selected":{"use":1}
,"perform":{"delete":1}
,"ortal":{"row":1}
,"row":{"use":1,"script":1,"delete":1}
,"note":{"performing":1}
,"performing":{"delete":1}
,"relationship":{"portal":1}
,"based":{"allow":1}
,"allow":{"deletion":1}
,"records":{"find":1,"automating":1}
,"user":{"delete":1}
,"go":{"related":1}
,"[from":{"table":1}
,"table":{"products":1}
,"products":{"layout":1}
,"roduct":{"details":1}
,"details":{"\u0022]":1}
,"\u0022]":{"delete":1,"if":1}
,"[with":{"dialog":1}
,"on]":{"displays":1}
,"displays":{"custom":1}
,"custom":{"dialog":1}
,"product":{"show":1}
,"show":{"custom":1}
,"[\u0022":{"want":1}
,"&products":{":name":1}
,":name":{"&\u0022":1}
,"&\u0022":{"\u0022]":1}
,"[get":{"lastmessagechoice":1}
,"lastmessagechoice":{"=1]":1}
,"=1]":{"delete":1}
,"off]":{"end":1}
,"end":{"if":1}
,"adding":{"duplicating":1}
,"duplicating":{"deleting":1}
,"deleting":{"records":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
