var pairs =
{
"base64encode":{"returns":1,"data":1,"rfc":1,"products":1}
,"returns":{"data":1,"qmxhy2s=when":1,"string":1}
,"data":{"text":1,"data":1,"-any":1,"converted":1}
,"text":{"base64":1,"expression":1,"filemaker":1,"text":1,"fields":1,"base64encoderfc":1}
,"base64":{"format":1,"encoding":1,"string":1}
,"format":{"base64encode":1,"encoding":1}
,"-any":{"text":1}
,"expression":{"field":1}
,"field":{"text":1,"content":1}
,"filemaker":{"pro":1}
,"pro":{"13.0":1}
,"13.0":{"function":1}
,"function":{"converts":1,"base64":1}
,"converts":{"text":1}
,"fields":{"variables":1}
,"variables":{"calculations":1}
,"calculations":{"utf-8":1}
,"utf-8":{"format":1}
,"encoding":{"container":1,"base64encode":1,"retain":1}
,"container":{"data":1,"field":1}
,"converted":{"encoding":1}
,"rfc":{"2045":1}
,"2045":{"standard":1}
,"standard":{"formatting":1}
,"formatting":{"base64-encoded":1}
,"base64-encoded":{"text":1}
,"base64encoderfc":{"function":1}
,"retain":{"filename":1}
,"filename":{"extension":1}
,"extension":{"encoded":1}
,"encoded":{"container":1}
,"content":{"base64encode":1}
,"products":{":color":1,":container":1}
,":color":{"returns":1,"set":1}
,"qmxhy2s=when":{"products":1}
,"set":{"black":1,"help":1}
,"black":{"base64encode":1}
,":container":{"returns":1,"set":1}
,"string":{"ivborw0kggoaaaansuheugaaab8":1,"shortened":1}
,"ivborw0kggoaaaansuheugaaab8":{"products":1}
,"help":{"button":1}
,"button":{"base64":1}
,"shortened":{"readability":1}
}
;Search.control.loadWordPairs(pairs);
