var pairs =
{
"get":{"custommenuse":1,"custommenusetname":1,"custom":1,"menu":1,"active":1}
,"custommenuse":{"tname":1}
,"tname":{"returns":1}
,"returns":{"name":1,"empty":1,"custom":1}
,"name":{"active":1,"get":1}
,"active":{"custom":1,"menu":1,"returns":1,"script":1}
,"custom":{"menu":1,"menus":1}
,"menu":{"set":1}
,"set":{"get":1,"isn\u2019t":1,"empty":1,"custom":1,"active":1,"script":1,"name":1}
,"custommenusetname":{"none":1,"get":1}
,"none":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1,"menus]":1}
,"pro":{"8.0":1}
,"8.0":{"if":1}
,"if":{"active":1}
,"isn\u2019t":{"custom":1}
,"empty":{"string":1}
,"string":{"returned":1,"returns":1,"[standard":1}
,"returned":{"filemaker":1}
,"webdirect":{"function":1}
,"function":{"supported":1}
,"supported":{"returns":1}
,"[standard":{"filemaker":1}
,"menus]":{"menu":1}
,"script":{"install":1,"step":1}
,"install":{"menu":1}
,"step":{"get":1}
,"menus":{"get":1}
}
;Search.control.loadWordPairs(pairs);
