var pairs =
{
"ongesturetap":{"performs":1,"set":1,"activate":1,"active":1}
,"performs":{"script":1}
,"script":{"hen":1,"script":1,"step":1,"return":1,"proceeds":1,"canceled":1,"returns":1,"trigger":1,"rigger":1,"runs":1}
,"hen":{"tap":1}
,"tap":{"gesture":1,"filemaker":1,"two":1,"second":1,"windows":1,"activates":1}
,"gesture":{"received":1,"center":1,"script":1}
,"received":{"layout":1}
,"layout":{"windows":1,"window":1}
,"windows":{"nd":1,"ongesturetap":1,"if":1,"windows":1,"devices":1}
,"nd":{"ios":1}
,"ios":{"event":1,"double-tap":1,"tap":1}
,"event":{"processed":1,"triggered":1}
,"processed":{"ongesturetap":1}
,"set":{"up":1}
,"up":{"activate":1}
,"activate":{"browse":1,"taps":1,"script":1}
,"browse":{"find":1}
,"find":{"modes":1}
,"modes":{"use":1,"trigger":1}
,"use":{"exit":1}
,"exit":{"script":1}
,"step":{"ithin":1}
,"ithin":{"triggered":1}
,"triggered":{"script":1}
,"return":{"true":1}
,"true":{"false":1,"event":1}
,"false":{"true":1,"event":1}
,"proceeds":{"false":1,"processes":1}
,"canceled":{"if":1}
,"if":{"triggered":1,"double-tap":1,"finger":1,"tap":1}
,"returns":{"value":1}
,"value":{"script":1}
,"processes":{"tap":1}
,"filemaker":{"pro":1,"application":1}
,"pro":{"13.0":1}
,"13.0":{"script":1}
,"trigger":{"supported":1,"tap":1,"activated":1,"result":1}
,"supported":{"windows":1}
,"taps":{"made":1}
,"made":{"active":1}
,"active":{"web":1,"edit":1,"window":1}
,"web":{"viewers":1}
,"viewers":{"active":1}
,"edit":{"boxes":1}
,"boxes":{"gestures":1}
,"gestures":{"activate":1,"two-finger":1}
,"two":{"fingers":1}
,"fingers":{"ios":1,"windows":1,"location":1,"se":1}
,"double-tap":{"finger":1}
,"finger":{"ios":1,"aware":1,"layout":1}
,"aware":{"trigger":1}
,"activated":{"first":1}
,"first":{"tap":1}
,"second":{"tap":1}
,"devices":{"support":1}
,"support":{"gestures":1}
,"two-finger":{"tap":1}
,"activates":{"ongesturetap":1}
,"window":{"if":1,"filemaker":1,"indows":1}
,"application":{"window":1}
,"indows":{"if":1}
,"location":{"gesture":1}
,"center":{"point":1}
,"point":{"tapping":1}
,"tapping":{"fingers":1}
,"se":{"get":1}
,"get":{"triggergestureinfo":1,"gesture":1}
,"triggergestureinfo":{"get":1}
,"rigger":{"activate":1}
,"runs":{"modes":1}
}
;Search.control.loadWordPairs(pairs);
