var pairs =
{
"publishing":{"data":1,"export":1,"option":1}
,"data":{"static":1,"webpage":1,"doesn\u2019t":1,"website":1,"filemaker":1,"viewed":1,"copy":1}
,"static":{"webpages":1,"publishing":1,"data":1}
,"webpages":{"static":1,"use":1,"new":1}
,"export":{"data":1,"html":1,"file":1}
,"webpage":{"add":1,"existing":1,"web":1,"publish":1}
,"add":{"webpage":1,"links":1}
,"existing":{"website":1,"webpages":1}
,"website":{"web":1,"database":1,"hosted":1}
,"web":{"users":1,"server":1,"browsers":1,"authoring":1}
,"users":{"connect":1}
,"connect":{"website":1,"database":1,"upload":1}
,"database":{"static":1,"publish":1}
,"option":{"if":1}
,"if":{"data":1,"you\u2019d":1}
,"doesn\u2019t":{"change":1}
,"change":{"don\u2019t":1,"appearance":1}
,"don\u2019t":{"full-time":1,"want":1}
,"full-time":{"internet":1}
,"internet":{"access":1,"intranet":1}
,"access":{"don\u2019t":1,"privileges":1}
,"want":{"users":1}
,"publish":{"static":1}
,"hosted":{"web":1}
,"server":{"computer":1,"application":1,"documentation":1,"add":1}
,"computer":{"connected":1}
,"connected":{"internet":1}
,"intranet":{"connect":1}
,"upload":{"webpage":1}
,"application":{"copying":1,"note":1,"export":1}
,"copying":{"uploading":1}
,"uploading":{"files":1}
,"files":{"web":1}
,"note":{"static":1}
,"use":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"access":1,"advanced":1}
,"privileges":{"protection":1}
,"protection":{"security":1}
,"security":{"options":1}
,"options":{"web":1}
,"documentation":{"check":1}
,"check":{"isp":1}
,"isp":{"network":1}
,"network":{"administrator":1}
,"administrator":{"follow":1}
,"follow":{"steps":1}
,"steps":{"1-12":1}
,"1-12":{"xporting":1}
,"xporting":{"data":1}
,"advanced":{"export":1}
,"html":{"table":1,"ta":1}
,"table":{"xml":1,"data":1}
,"xml":{"file":1}
,"file":{"export":1,"if":1}
,"ta":{"ble":1}
,"ble":{"generate":1}
,"generate":{"table":1}
,"viewed":{"by":1}
,"by":{"supported":1}
,"supported":{"web":1}
,"browsers":{"customize":1}
,"customize":{"appearance":1}
,"appearance":{"text":1,"data":1}
,"text":{"editing":1}
,"editing":{"web":1}
,"authoring":{"application":1}
,"you\u2019d":{"programmatically":1}
,"programmatically":{"change":1}
,"copy":{"new":1}
,"new":{"webpage":1}
,"links":{"existing":1}
}
;Search.control.loadWordPairs(pairs);
