var pairs =
{
"saving":{"importing":1}
,"importing":{"exporting":1}
,"exporting":{"data":1}
,"data":{"exchange":1,"file":1,"currently":1,"order":1,"excel":1,"existing":1,"imported":1,"applications":1,"formats":1}
,"exchange":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"applications":1,"data":1,"records":1,"pdf":1,"file":1,"files":1}
,"applications":{"by":1,"new":1}
,"by":{"saving":1}
,"file":{"formats":1,"set":1,"convert":1}
,"formats":{"import":1,"use":1}
,"import":{"data":1}
,"currently":{"database":1}
,"database":{"spreadsheet":1}
,"spreadsheet":{"program":1}
,"program":{"export":1,"save":1}
,"export":{"address":1,"data":1}
,"address":{"data":1}
,"order":{"create":1}
,"create":{"personalized":1}
,"personalized":{"form":1}
,"form":{"letters":1}
,"letters":{"word":1}
,"word":{"processing":1}
,"processing":{"program":1}
,"save":{"filemaker":1,"found":1}
,"excel":{"pdf":1}
,"pdf":{"files":1}
,"files":{"save":1,"import":1,"export":1}
,"found":{"set":1}
,"set":{"records":1,"up":1}
,"records":{"email":1,"existing":1}
,"email":{"snapshot":1}
,"snapshot":{"link":1}
,"link":{"append":1}
,"append":{"filemaker":1}
,"existing":{"filemaker":1}
,"up":{"recurring":1}
,"recurring":{"imports":1}
,"imports":{"help":1}
,"help":{"routinely":1}
,"routinely":{"refresh":1}
,"refresh":{"read-only":1}
,"read-only":{"data":1}
,"imported":{"file":1}
,"convert":{"data":1}
,"new":{"filemaker":1}
,"use":{"application":1}
}
;Search.control.loadWordPairs(pairs);
