var pairs =
{
"eplacing":{"contents":1}
,"contents":{"fiel":1,"field":1,"se":1,"command":1}
,"fiel":{"process":1}
,"process":{"overwrites":1}
,"overwrites":{"field":1}
,"field":{"record":1,"values":1,"want":1,"contents":1,"replace":1,"replaced":1,"defined":1,"dialog":1,"type":1,"validation":1}
,"record":{"record":1,"found":1,"select":1,"committing":1}
,"found":{"set":1}
,"set":{"new":1,"serialized":1}
,"new":{"value":1,"data":1}
,"value":{"undo":1,"serialized":1,"choose":1,"select":1,"currently":1,"th":1,"serial":1,"incremental":1,"increment":1,"options":1,"replace":1,"field":1,"changed":1,"based":1}
,"undo":{"replacing":1}
,"replacing":{"field":1,"data":1}
,"values":{"backup":1,"record":1}
,"backup":{"opy":1}
,"opy":{"file":1}
,"file":{"if":1}
,"if":{"find":1,"replacing":1,"field":1,"select":1,"clear":1}
,"find":{"omit":1}
,"omit":{"sort":1}
,"sort":{"records":1}
,"records":{"database":1,"sorting":1,"browse":1,"menu":1,"reserialized":1,"replace":1}
,"database":{"table":1}
,"table":{"se":1}
,"se":{"finding":1,"lect":1}
,"finding":{"records":1}
,"sorting":{"records":1}
,"browse":{"mode":1}
,"mode":{"current":1}
,"current":{"record":1,"settings":1}
,"select":{"contents":1,"value":1,"update":1}
,"want":{"replace":1,"evaluated":1}
,"replace":{"if":1,"field":1,"each":1,"value":1,"serial":1,"calculated":1,"replace":1,"calculation":1,"performed":1,"task":1}
,"data":{"constant":1,"validated":1,"defining":1,"records":1}
,"constant":{"value":1}
,"serialized":{"numbers":1,"number":1}
,"numbers":{"calculated":1,"type":1,"initial":1}
,"calculated":{"result":1,"value":1}
,"result":{"type":1,"calculation":1,"match":1}
,"type":{"value":1,"starting":1,"replaced":1}
,"choose":{"records":1}
,"menu":{"replace":1}
,"lect":{"option":1}
,"option":{"replace":1,"next":1}
,"each":{"value":1}
,"currently":{"selected":1}
,"selected":{"field":1}
,"th":{"contents":1}
,"replaced":{"entire":1,"field":1,"data":1}
,"entire":{"found":1}
,"number":{"replace":1,"select":1,"entry":1}
,"serial":{"numbers":1,"number":1}
,"starting":{"value":1}
,"initial":{"value":1}
,"incremental":{"value":1}
,"increment":{"by":1}
,"by":{"if":1,"replace":1}
,"defined":{"automatically":1}
,"automatically":{"enter":1,"entered":1}
,"enter":{"serial":1,"calculation":1}
,"update":{"serial":1}
,"entry":{"options":1}
,"options":{"reset":1,"field":1,"next":1}
,"reset":{"next":1}
,"next":{"value":1,"automatically":1}
,"dialog":{"box":1}
,"box":{"calculated":1,"enter":1,"next":1}
,"calculation":{"dialog":1,"want":1,"summary":1}
,"evaluated":{"result":1}
,"match":{"field":1}
,"summary":{"fields":1}
,"fields":{"if":1}
,"validated":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"validate":1}
,"validate":{"new":1}
,"defining":{"field":1}
,"validation":{"if":1}
,"entered":{"value":1}
,"performed":{"sequence":1,"committing":1}
,"sequence":{"if":1,"records":1}
,"clear":{"option":1}
,"changed":{"options":1}
,"based":{"current":1}
,"settings":{"sequence":1}
,"reserialized":{"by":1}
,"task":{"replace":1}
,"command":{"performed":1}
,"committing":{"active":1,"data":1}
,"active":{"record":1}
}
;Search.control.loadWordPairs(pairs);
