var pairs =
{
"replace":{"field":1,"operation":1,"current":1,"serial":1,"calculated":1,"value":1}
,"field":{"contents":1,"record":1,"specifies":1,"replace":1,"replacement":1,"current":1,"replaced":1,"starting":1,"all":1,"perform":1}
,"contents":{"eplaces":1,"dialog":1,"current":1,"modifies":1,"script":1,"[with":1,"customer":1}
,"eplaces":{"value":1}
,"value":{"field":1,"dialog":1,"place":1,"entry":1,"starting":1,"by":1,"selected":1,"filemaker":1}
,"record":{"found":1,"current":1,"number":1,"calculation":1}
,"found":{"set":1}
,"set":{"value":1,"replace":1,"entry":1,"update":1,"up":1,"undo":1,"use":1,"filemaker":1,"sort":1,"contents":1}
,"dialog":{"specifies":1,"box":1,"option":1,"on]":1,"invoices":1}
,"specifies":{"display":1,"target":1}
,"display":{"replace":1}
,"box":{"script":1,"enter":1}
,"script":{"step":1}
,"step":{"performed":1,"if":1,"value":1,"script":1,"reserialize":1,"data":1}
,"performed":{"target":1,"get":1}
,"target":{"field":1}
,"operation":{"replace":1,"performed":1}
,"current":{"contents":1,"value":1,"found":1,"record":1,"record\u0027s":1,"contents]":1}
,"replacement":{"value":1}
,"place":{"field":1}
,"serial":{"numbers":1,"number":1,"value":1,"numbers]":1}
,"numbers":{"reserializes":1,"selected":1,"all":1}
,"reserializes":{"field":1}
,"entry":{"options":1}
,"options":{"next":1,"first":1,"custom":1,"resets":1,"changed":1}
,"next":{"value":1,"serial":1,"number":1}
,"first":{"record":1,"operation":1}
,"number":{"incrementing":1,"entry":1,"value":1,"automatically":1,"prohibit":1}
,"incrementing":{"value":1}
,"custom":{"values":1,"web":1}
,"values":{"enter":1}
,"enter":{"value":1,"calculation":1}
,"starting":{"point":1,"next":1}
,"point":{"serialization":1}
,"serialization":{"value":1}
,"by":{"increment":1}
,"increment":{"each":1}
,"each":{"serialized":1}
,"serialized":{"field":1}
,"update":{"serial":1}
,"resets":{"serial":1}
,"automatically":{"entered":1}
,"entered":{"follow":1,"replace":1}
,"follow":{"records":1}
,"records":{"reserialized":1,"if":1,"found":1,"filemaker":1,"[restore":1}
,"reserialized":{"script":1,"records":1}
,"if":{"option":1,"field":1,"dialog":1}
,"option":{"serial":1,"set":1,"assigns":1}
,"changed":{"sequence":1}
,"sequence":{"newly":1}
,"newly":{"reserialized":1}
,"replaced":{"set":1}
,"up":{"auto-entry":1}
,"auto-entry":{"serial":1}
,"prohibit":{"modification":1}
,"modification":{"value":1}
,"selected":{"filemaker":1,"field":1}
,"filemaker":{"pro":1,"webdirect":1,"data":1,"go":1}
,"pro":{"advanced":1,"6.0":1}
,"advanced":{"sequential":1}
,"sequential":{"numbers":1}
,"calculated":{"result":1}
,"result":{"displays":1}
,"displays":{"calculation":1}
,"calculation":{"dialog":1,"replacement":1,"replace":1}
,"6.0":{"earlier":1}
,"earlier":{"script":1}
,"modifies":{"all":1}
,"all":{"records":1,"invoices":1}
,"undo":{"replace":1}
,"reserialize":{"field":1}
,"use":{"replace":1}
,"data":{"committed":1,"records":1,"api":1,"automating":1}
,"committed":{"first":1}
,"get":{"unexpected":1}
,"unexpected":{"committing":1}
,"committing":{"data":1}
,"webdirect":{"server-side":1}
,"server-side":{"scripts":1}
,"scripts":{"filemaker":1}
,"api":{"nd":1}
,"nd":{"custom":1}
,"web":{"publishing":1}
,"publishing":{"run":1}
,"run":{"script":1}
,"go":{"support":1,"record\u002Frequest\u002Fpage":1}
,"support":{"dialog":1}
,"assigns":{"serial":1}
,"invoices":{"found":1,":invoice":1,":customer":1}
,"sort":{"records":1}
,"[restore":{"dialog":1}
,"on]":{"go":1}
,"record\u002Frequest\u002Fpage":{"[first]":1}
,"[first]":{"replace":1}
,"[with":{"dialog":1}
,":invoice":{"id":1}
,"id":{"serial":1,"field":1,"current":1}
,"numbers]":{"replaces":1}
,"replaces":{"contents":1}
,"customer":{"id":1}
,"record\u0027s":{"customer":1}
,"perform":{"find":1}
,"find":{"[restore]":1}
,"[restore]":{"replace":1}
,":customer":{"id":1}
,"contents]":{"finding":1}
,"finding":{"replacing":1}
,"replacing":{"data":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
