var pairs =
{
"show":{"omitted":1,"custom":1,"all":1}
,"omitted":{"inds":1,"records":1,"end":1,"simpler":1,"multiple":1,"record":1,"single":1}
,"inds":{"records":1}
,"records":{"current":1,"found":1,"show":1,"\u0022]":1,"script":1,"omit":1,"[replace":1}
,"current":{"found":1,"record":1}
,"found":{"set":1,"all":1}
,"set":{"none":1,"current":1,"omit":1,"automating":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1,"advanced":1}
,"6.0":{"earlier":1}
,"earlier":{"use":1}
,"use":{"script":1}
,"script":{"step":1}
,"step":{"browse":1,"find":1,"show":1,"perform":1}
,"browse":{"mode":1}
,"mode":{"preview":1,"if":1,"layout":1,"filemaker":1,"records":1}
,"preview":{"mode":1}
,"if":{"perform":1,"[get":1,"demonstrates":1}
,"perform":{"script":1,"task":1}
,"find":{"mode":1,"matching":1}
,"layout":{"mode":1}
,"advanced":{"switches":1}
,"switches":{"browse":1}
,"all":{"omitted":1,"records":1}
,"custom":{"dialog":1}
,"dialog":{"[\u0022":1}
,"[\u0022":{"show":1}
,"\u0022]":{"if":1}
,"[get":{"lastmessagechoice":1}
,"lastmessagechoice":{"=1]":1}
,"=1]":{"show":1}
,"end":{"if":1}
,"demonstrates":{"find":1}
,"matching":{"records":1}
,"simpler":{"create":1}
,"create":{"found":1,"new":1}
,"record":{"show":1}
,"multiple":{"steps":1}
,"steps":{"create":1}
,"new":{"found":1}
,"omit":{"current":1,"record":1}
,"single":{"find":1}
,"task":{"field":1}
,"field":{"unique":1,"find":1}
,"unique":{"values":1}
,"values":{"invoice":1}
,"invoice":{"id":1}
,"id":{"field":1}
,"[replace":{"invoices":1}
,"invoices":{":invoice":1}
,":invoice":{"id]":1}
,"id]":{"mitting":1}
,"mitting":{"records":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
