var pairs =
{
"llow":{"user":1}
,"user":{"abort":1,"switches":1}
,"abort":{"llows":1,"script":1,"left":1,"[off]":1}
,"llows":{"prevents":1}
,"prevents":{"users":1}
,"users":{"stopping":1,"stop":1}
,"stopping":{"running":1,"script":1}
,"running":{"script":1}
,"script":{"allows":1,"by":1,"step":1,"executed":1,"use":1,"steps":1,"change":1,"skips":1,"continue":1,"performs":1,"allow":1,"cancel":1,"exit":1,"automating":1}
,"allows":{"users":1,"unknown":1,"script":1}
,"stop":{"script":1,"erver-side":1}
,"by":{"pressing":1,"default":1}
,"pressing":{"esc":1}
,"esc":{"command-":1}
,"command-":{"period":1}
,"period":{"macos":1}
,"macos":{"prevents":1,"filemaker":1,"prevent":1}
,"filemaker":{"pro":1,"data":1,"go":1}
,"pro":{"6.0":1,"advanced":1}
,"6.0":{"earlier":1}
,"earlier":{"allow":1}
,"allow":{"user":1}
,"step":{"script":1,"set":1,"case":1,"determines":1,"affect":1,"dialog":1}
,"executed":{"all":1}
,"all":{"sub-scripts":1}
,"sub-scripts":{"by":1}
,"default":{"users":1,"unknown":1,"allows":1}
,"prevent":{"users":1}
,"use":{"allow":1}
,"set":{"by":1,"allow":1}
,"unknown":{"obsolete":1,"script":1,"default":1}
,"obsolete":{"unrecognized":1}
,"unrecognized":{"script":1}
,"steps":{"stop":1,"return":1,"allows":1,"skipped":1}
,"change":{"behavior":1}
,"behavior":{"set":1}
,"case":{"unknown":1}
,"return":{"filemaker":1}
,"advanced":{"error":1}
,"error":{"ommand":1}
,"ommand":{"unknown":1}
,"skips":{"unknown":1}
,"continue":{"ru":1,"print":1}
,"ru":{"clients":1}
,"clients":{"can\u2019t":1}
,"can\u2019t":{"stop":1}
,"erver-side":{"scripts":1}
,"scripts":{"cripts":1}
,"cripts":{"performed":1}
,"performed":{"via":1}
,"via":{"ustom":1}
,"ustom":{"web":1}
,"web":{"publishing":1}
,"publishing":{"filemaker":1}
,"data":{"api":1}
,"api":{"cases":1}
,"cases":{"script":1}
,"determines":{"unknown":1}
,"skipped":{"filemaker":1}
,"go":{"script":1,"filemaker":1,"development":1}
,"affect":{"running":1}
,"performs":{"user":1}
,"switches":{"back":1}
,"back":{"filemaker":1}
,"development":{"guide":1}
,"guide":{"displays":1}
,"displays":{"records":1}
,"records":{"print":1}
,"print":{"invoices":1,"dialog":1,"script":1,"[restore":1}
,"invoices":{"layout":1,"cancel":1,"invoices":1,")]":1}
,"layout":{"new":1,"print":1}
,"new":{"window":1}
,"window":{"preview":1,"open":1,"[style":1,"[current":1}
,"preview":{"mode":1}
,"mode":{"pauses":1,"[pause":1}
,"pauses":{"script":1}
,"cancel":{"printing":1,"script":1}
,"printing":{"print":1}
,"dialog":{"box":1,"option":1,"on]":1}
,"box":{"print":1}
,"option":{"allow":1}
,"left":{"extra":1}
,"extra":{"window":1}
,"open":{"if":1}
,"if":{"cancel":1}
,"[off]":{"new":1}
,"[style":{"floating":1}
,"floating":{"document":1}
,"document":{"name":1}
,"name":{"print":1}
,")]":{"enter":1}
,"enter":{"preview":1}
,"[pause":{"on]":1}
,"on]":{"print":1,"close":1}
,"[restore":{"printer":1}
,"printer":{"dialog":1}
,"close":{"window":1}
,"[current":{"window]":1}
,"window]":{"stop":1}
,"exit":{"script":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
