var pairs =
{
"get":{"screenscalefactor":1}
,"screenscalefactor":{"returns":1,"none":1,"=1.5]":1}
,"returns":{"scale":1,"get":1,"ipad":1}
,"scale":{"factor":1}
,"factor":{"screen":1,"based":1,"control":1,"layout":1,"standard":1,"150":1}
,"screen":{"current":1,"device":1,"scale":1}
,"current":{"file":1}
,"file":{"open":1}
,"open":{"get":1}
,"none":{"number":1}
,"number":{"filemaker":1}
,"filemaker":{"pro":1,"go":1,"webdirect":1,"data":1}
,"pro":{"13.0.2":1,"iphone":1}
,"13.0.2":{"macos":1}
,"macos":{"filemaker":1}
,"go":{"function":1,"layout":1}
,"function":{"returns":1}
,"based":{"relative":1}
,"relative":{"pixel":1}
,"pixel":{"density":1}
,"density":{"screen":1}
,"device":{"retina":1}
,"retina":{"display":1}
,"display":{"mac":1,"iphone":1,"detects":1}
,"mac":{"retina":1}
,"iphone":{"iphone":1,"phone":1,"plus":1,"windows":1}
,"phone":{"ipad":1}
,"ipad":{"pro":1,"retina":1}
,"plus":{"iphone":1}
,"windows":{"function":1}
,"control":{"panel":1}
,"panel":{"filemaker":1}
,"webdirect":{"server-side":1}
,"server-side":{"scripts":1}
,"scripts":{"filemaker":1}
,"data":{"api":1}
,"api":{"custom":1}
,"custom":{"web":1}
,"web":{"publishing":1}
,"publishing":{"function":1}
,"detects":{"screen":1}
,"layout":{"designed":1,"if":1,"[invoices":1,"[invoices]":1}
,"designed":{"large":1}
,"large":{"scale":1}
,"standard":{"layout":1}
,"if":{"[get":1}
,"[get":{"screenscalefactor":1}
,"=1.5]":{"go":1}
,"[invoices":{"factor":1}
,"150":{"%]":1}
,"%]":{"else":1}
,"else":{"go":1}
,"[invoices]":{"end":1}
,"end":{"if":1}
}
;Search.control.loadWordPairs(pairs);
