var pairs =
{
"duplicate":{"record\u002Frequest":1,"current":1,"value":1,"selected":1}
,"record\u002Frequest":{"uplicates":1,"script":1,"step":1,"adding":1}
,"uplicates":{"current":1}
,"current":{"record":1,"find":1}
,"record":{"current":1,"find":1,"field":1,"case":1,"if":1,"use":1,"duplicates":1,"perform":1}
,"find":{"request":1,"mode":1,"last":1,"[restore]":1}
,"request":{"none":1,"if":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1,"advanced":1}
,"6.0":{"earlier":1}
,"earlier":{"browse":1}
,"browse":{"mode":1}
,"mode":{"script":1,"duplicates":1}
,"script":{"step":1}
,"step":{"duplicate":1,"portal":1,"use":1}
,"duplicates":{"current":1,"value":1,"record":1}
,"if":{"record":1,"field":1,"replace":1,"option":1}
,"field":{"set":1,"current":1,"defined":1,"if":1,"filemaker":1}
,"set":{"up":1}
,"up":{"automatic":1}
,"automatic":{"entry":1}
,"entry":{"values":1}
,"values":{"script":1}
,"value":{"field":1,"duplicated":1,"current":1}
,"case":{"filemaker":1}
,"advanced":{"generates":1,"duplicates":1}
,"generates":{"enters":1}
,"enters":{"new":1}
,"new":{"value":1}
,"duplicated":{"record":1}
,"defined":{"lookup":1}
,"lookup":{"if":1}
,"replace":{"existing":1}
,"existing":{"value":1}
,"option":{"selected":1,"option":1,"allow":1}
,"selected":{"field":1,"duplicate":1,"row":1}
,"use":{"duplicate":1,"go":1}
,"portal":{"rows":1,"row":1}
,"rows":{"display":1}
,"display":{"related":1}
,"related":{"records":1,"table":1}
,"records":{"first":1,"enabled":1,"automating":1}
,"first":{"use":1}
,"go":{"portal":1,"record\u002Frequest\u002Fpage":1}
,"row":{"script":1,"selected":1,"related":1}
,"table":{"option":1}
,"allow":{"creation":1}
,"creation":{"related":1}
,"enabled":{"relationship":1}
,"relationship":{"performs":1}
,"performs":{"find":1}
,"last":{"record":1}
,"perform":{"find":1}
,"[restore]":{"go":1}
,"record\u002Frequest\u002Fpage":{"[last]":1}
,"[last]":{"duplicate":1}
,"adding":{"duplicating":1}
,"duplicating":{"deleting":1}
,"deleting":{"records":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
