var pairs =
{
"setrecursion":{"sets":1,"expression":1,"terminate":1,"returns":1,"setrecursion":1,"while":1,"increases":1}
,"sets":{"maximum":1}
,"maximum":{"number":1}
,"number":{"iterations":1,"date":1}
,"iterations":{"recursion":1,"text":1,"function":1}
,"recursion":{"loops":1,"subject":1}
,"loops":{"expression":1}
,"expression":{"setrecursion":1,"maxiterations":1,"-any":1,"field":1,"custom":1}
,"maxiterations":{"expression":1,"-the":1,"if":1,"exceeded":1,"by":1}
,"-any":{"calculation":1}
,"calculation":{"expression":1}
,"field":{"constant":1}
,"constant":{"maxiterations":1}
,"-the":{"maximum":1}
,"text":{"number":1}
,"date":{"time":1}
,"time":{"timestamp":1}
,"timestamp":{"container":1}
,"container":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"18.0":1}
,"18.0":{"advanced":1}
,"advanced":{"by":1}
,"by":{"default":1,"setrecursion":1}
,"default":{"while":1}
,"while":{"function":1,"loop":1,"[i":1,"=0":1}
,"function":{"recursive":1,"allows":1,"return":1}
,"recursive":{"custom":1}
,"custom":{"functions":1}
,"functions":{"each":1,"use":1}
,"each":{"limited":1}
,"limited":{"50,000":1}
,"50,000":{"iterations":1}
,"allows":{"increase":1}
,"increase":{"decrease":1}
,"decrease":{"limit":1}
,"limit":{"maxiterations":1,"times":1,"200000":1}
,"if":{"maxiterations":1,"stack":1}
,"exceeded":{"function":1}
,"return":{"returns":1,"if":1}
,"returns":{"result":1,"while":1,"100000":1}
,"result":{"expression":1}
,"use":{"non-tail":1}
,"non-tail":{"recursion":1}
,"subject":{"maxiterations":1}
,"terminate":{"return":1}
,"stack":{"space":1}
,"space":{"memory":1}
,"memory":{"setrecursion":1}
,"loop":{"attempts":1}
,"attempts":{"iterate":1}
,"iterate":{"limit":1}
,"times":{"by":1}
,"[i":{"=0":1,"=i":1,"&\u00B6":1}
,"=0":{"=\u0022":1,"100000":1}
,"=\u0022":{"10":1}
,"10":{"[i":1}
,"=i":{"=out":1,"200000":1}
,"=out":{"&\u00A0$variable":1}
,"&\u00A0$variable":{"[i":1}
,"&\u00B6":{"returns":1}
,"100000":{"setrecursion":1,"=i":1}
,"increases":{"iteration":1}
,"iteration":{"limit":1}
,"200000":{"setrecursion":1}
}
;Search.control.loadWordPairs(pairs);
