var pairs =
{
"valuelistitems":{"eturns":1,"filename":1,"customers":1}
,"eturns":{"list":1}
,"list":{"values":1,"valuelistitems":1,"database":1,"all":1,"customers":1}
,"values":{"value":1}
,"value":{"list":1,"li":1}
,"filename":{"value":1,"-the":1,"references":1}
,"li":{"st":1}
,"st":{"filename":1,"-the":1}
,"-the":{"name":1}
,"name":{"open":1,"value":1}
,"open":{"database":1}
,"database":{"file":1}
,"file":{"local":1,"text":1,"if":1,"function":1}
,"local":{"remote":1}
,"remote":{"value":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"listed":1}
,"listed":{"items":1}
,"items":{"separated":1,"code":1}
,"separated":{"by":1}
,"by":{"carriage":1}
,"carriage":{"returns":1}
,"returns":{"filemaker":1,"empty":1,"list":1}
,"webdirect":{"function":1}
,"function":{"supports":1,"returns":1}
,"supports":{"returning":1}
,"returning":{"current":1}
,"current":{"file":1}
,"if":{"filename":1}
,"references":{"file":1}
,"empty":{"string":1}
,"string":{"valuelistitems":1}
,"customers":{"code":1,"database":1}
,"code":{"returns":1,"value":1}
,"all":{"items":1}
}
;Search.control.loadWordPairs(pairs);
