var pairs =
{
"windows":{"script":1,"open":1,"move":1}
,"script":{"steps":1}
,"steps":{"windows":1,"affect":1}
,"affect":{"screen":1}
,"screen":{"elements":1}
,"elements":{"windows":1}
,"open":{"close":1}
,"close":{"window":1}
,"window":{"select":1,"arrange":1,"update":1,"freeze":1,"scroll":1,"show":1,"status":1,"set":1}
,"select":{"window":1}
,"arrange":{"windows":1}
,"move":{"resize":1}
,"resize":{"window":1}
,"update":{"window":1}
,"freeze":{"window":1}
,"scroll":{"window":1}
,"show":{"hide":1}
,"hide":{"window":1}
,"status":{"toolbar":1}
,"toolbar":{"menu":1}
,"menu":{"bar":1}
,"bar":{"text":1}
,"text":{"ruler":1}
,"ruler":{"set":1}
,"set":{"title":1,"zoom":1}
,"title":{"window":1}
,"zoom":{"level":1}
,"level":{"view":1}
,"view":{"data":1}
,"data":{"list":1}
,"list":{"table":1}
,"table":{"form":1}
,"form":{"refresh":1}
,"refresh":{"window":1}
}
;Search.control.loadWordPairs(pairs);
