var pairs =
{
"get":{"systemvers":1,"systemversion":1,"system":1,"os":1,"operating":1,"windows":1,"mac":1}
,"systemvers":{"ion":1}
,"ion":{"returns":1}
,"returns":{"version":1,"6.1":1,"win":1,"safari":1,"10.1":1,"ipad":1}
,"version":{"current":1,"10.1":1,"filemaker":1,"returns":1,"web":1,"74":1,"get":1}
,"current":{"operating":1}
,"operating":{"system":1}
,"system":{"get":1,"device":1,"mac":1,"linux":1,"ipad":1,"macos":1,"version":1}
,"systemversion":{"none":1,"get":1}
,"none":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"returns":1}
,"6.1":{"windows":1}
,"windows":{"6.3":1,"8.1":1,"10":1,"operating":1,"computer":1,"version":1}
,"6.3":{"windows":1}
,"8.1":{"10.0":1}
,"10.0":{"windows":1}
,"10":{"10.1":1}
,"10.1":{"macos":1,"operating":1,"hen":1,"returns":1}
,"macos":{"version":1,"operating":1}
,"device":{"web":1,"returns":1,"unknown":1,"filemaker":1}
,"web":{"browser":1}
,"browser":{"browser":1,"version":1,"returns":1,"ie":1,"chrome":1,"unknown":1,"accessing":1}
,"webdirect":{"filemaker":1,"operating":1,"web":1,"returns":1,"safari":1,"chrome":1}
,"win":{"windows":1,"chrome":1}
,"mac":{"macos":1,"version":1}
,"linux":{"linux":1,"operating":1}
,"ipad":{"ipad":1,"iphone":1,"safari":1,"filemaker":1}
,"iphone":{"iphone":1,"ipod":1}
,"ipod":{"ipod":1,"touch":1}
,"touch":{"android":1}
,"android":{"android":1,"device":1}
,"unknown":{"operating":1,"browser":1}
,"safari":{"safari":1,"browser":1,"ipad":1,"version":1}
,"ie":{"internet":1}
,"internet":{"explorer":1}
,"explorer":{"browser":1}
,"chrome":{"chrome":1,"browser":1,"74":1,"version":1}
,"accessing":{"filemaker":1}
,"hen":{"current":1}
,"74":{".0":1}
,".0":{"windows":1,"get":1}
,"computer":{"filemaker":1}
,"os":{"version":1}
}
;Search.control.loadWordPairs(pairs);
