var pairs =
{
"html":{"ta":1,"table":1,"files":1}
,"ta":{"ble":1}
,"ble":{"format":1}
,"format":{"export":1,"displaying":1}
,"export":{"data":1}
,"data":{"html":1,"static":1}
,"table":{"format":1,"each":1,"values":1,"value":1}
,"displaying":{"data":1}
,"static":{"web":1}
,"web":{"age":1,"browser":1,"bl":1}
,"age":{"web":1}
,"browser":{"dynamically":1}
,"dynamically":{"publishing":1}
,"publishing":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"advanced":1}
,"advanced":{"database":1}
,"database":{"web":1}
,"bl":{"ishing":1}
,"ishing":{"databases":1}
,"databases":{"filemaker":1}
,"webdirect":{"each":1}
,"each":{"record":1,"field":1,"repeating":1}
,"record":{"exports":1}
,"exports":{"row":1,"column":1}
,"row":{"html":1}
,"field":{"exports":1,"exported":1}
,"column":{"html":1,"exporting":1}
,"values":{"each":1}
,"repeating":{"field":1}
,"exported":{"nested":1}
,"nested":{"table":1}
,"value":{"column":1}
,"exporting":{"html":1}
}
;Search.control.loadWordPairs(pairs);
