var pairs =
{
"creating":{"editing":1}
,"editing":{"privilege":1,"accounts":1}
,"privilege":{"sets":1,"create":1,"set":1}
,"sets":{"privilege":1,"levels":1,"extended":1,"define":1,"common":1,"create":1,"anaging":1,"file":1,"shared":1,"tab":1}
,"levels":{"access":1,"sing":1}
,"access":{"database":1,"want":1,"levels":1,"privilege":1,"privileges":1}
,"database":{"layouts":1,"file":1}
,"layouts":{"viewable":1,"privileges":1}
,"viewable":{"menus":1}
,"menus":{"printing":1}
,"printing":{"permitted":1}
,"permitted":{"accounts":1}
,"accounts":{"privilege":1,"use":1,"create":1,"choose":1}
,"extended":{"privilege":1,"privileges":1}
,"create":{"privilege":1,"edit":1,"manage":1,"modify":1,"new":1}
,"define":{"types":1}
,"types":{"access":1}
,"want":{"permit":1}
,"permit":{"file":1}
,"file":{"each":1,"predefined":1,"open":1,"account":1,"if":1,"insufficient":1,"menu":1,"while":1,"table":1}
,"each":{"database":1,"predefined":1}
,"predefined":{"privilege":1,"data":1,"read-only":1}
,"common":{"types":1}
,"sing":{"predefined":1}
,"edit":{"accounts":1,"existing":1,"enter":1,"privilege":1}
,"use":{"privilege":1,"by":1,"detailed":1}
,"anaging":{"accounts":1}
,"manage":{"privilege":1,"security":1,"privileges":1}
,"open":{"file":1}
,"account":{"assigned":1,"action":1,"change":1}
,"assigned":{"full":1}
,"full":{"access":1}
,"set":{"privilege":1,"permits":1,"take":1,"use":1,"by":1,"predefined":1,"edit":1,"creating":1,"new":1,"select":1,"if":1,"manage":1,"diting":1}
,"permits":{"privileges":1}
,"privileges":{"file":1,"privilege":1,"remain":1,"delete":1,"diting":1}
,"if":{"open":1,"change":1,"manage":1,"rename":1}
,"insufficient":{"privileges":1}
,"menu":{"manage":1}
,"security":{"command":1,"if":1,"dialog":1,"settings":1}
,"command":{"disabled":1}
,"disabled":{"create":1}
,"modify":{"privilege":1}
,"shared":{"file":1}
,"while":{"clients":1}
,"clients":{"privilege":1,"if":1,"privileges":1}
,"take":{"disrupt":1}
,"disrupt":{"current":1}
,"current":{"clients":1}
,"change":{"privileges":1,"except":1,"name":1}
,"by":{"clients":1,"account":1}
,"remain":{"unchanged":1}
,"unchanged":{"next":1}
,"next":{"time":1}
,"time":{"open":1}
,"table":{"actions":1}
,"actions":{"perform":1}
,"perform":{"each":1}
,"action":{"full":1}
,"data":{"entry":1}
,"entry":{"privilege":1}
,"read-only":{"access":1}
,"except":{"enable":1}
,"enable":{"disable":1}
,"disable":{"extended":1}
,"delete":{"no*duplicate":1,"privilege":1}
,"no*duplicate":{"*before":1}
,"*before":{"delete":1}
,"choose":{"file":1}
,"dialog":{"box":1}
,"box":{"displays":1}
,"displays":{"basic":1}
,"basic":{"security":1}
,"settings":{"use":1}
,"detailed":{"setup":1}
,"setup":{"privilege":1}
,"tab":{"create":1}
,"new":{"privilege":1,"edit":1,"name":1}
,"existing":{"privilege":1}
,"select":{"privilege":1}
,"enter":{"change":1}
,"name":{"optional":1,"updated":1}
,"optional":{"description":1}
,"description":{"privilege":1}
,"rename":{"privilege":1}
,"updated":{"all":1}
,"all":{"accounts":1}
,"diting":{"record":1,"layouts":1,"value":1,"scripts":1,"extended":1,"privilege":1}
,"record":{"access":1}
,"value":{"list":1}
,"list":{"privileges":1}
,"scripts":{"privileges":1}
}
;Search.control.loadWordPairs(pairs);
