var pairs =
{
"displaying":{"hiding":1,"table":1}
,"hiding":{"fields":1}
,"fields":{"table":1,"clear":1,"want":1,"list":1,"add":1,"button":1,"dialog":1,"choose":1,"select":1,"trash":1,"current":1,"removed":1,"displaying":1,"columns":1}
,"table":{"view":1,"column":1,"choose":1,"list":1}
,"view":{"browse":1,"modify":1,"dialog":1,"reorder":1,"display":1,"layout":1,"table":1,"likewise":1,"fields":1,"by":1,"style":1}
,"browse":{"mode":1}
,"mode":{"right-click":1,"format":1}
,"right-click":{"table":1}
,"column":{"heading":1}
,"heading":{"choose":1}
,"choose":{"table":1,"field":1,"manage":1}
,"modify":{"modify":1,"status":1,"table":1}
,"status":{"toolbar":1}
,"toolbar":{"modify":1}
,"dialog":{"box":1}
,"box":{"hide":1,"choose":1,"indicating":1}
,"hide":{"fields":1,"table":1}
,"clear":{"checkboxes":1}
,"checkboxes":{"fields":1}
,"want":{"hide":1,"change":1}
,"reorder":{"columns":1,"fields":1}
,"columns":{"drag":1,"table":1}
,"drag":{"double":1}
,"double":{"arrow":1}
,"arrow":{"control":1}
,"control":{"next":1}
,"next":{"field":1}
,"field":{"reorder":1,"add":1,"table":1,"define":1,"choose":1,"use":1}
,"list":{"table":1,"list":1,"fields":1,"remove":1,"prevent":1}
,"display":{"additional":1,"existing":1}
,"additional":{"fields":1}
,"add":{"fields":1,"choose":1}
,"button":{"open":1,"display":1}
,"open":{"add":1}
,"define":{"new":1}
,"new":{"field":1}
,"manage":{"database":1}
,"database":{"list":1}
,"remove":{"fields":1}
,"select":{"fields":1}
,"trash":{"button":1}
,"existing":{"fields":1}
,"current":{"layout":1}
,"layout":{"table":1,"view":1,"visible":1,"views":1,"marked":1,"theme\u2019s":1,"mode":1}
,"likewise":{"if":1}
,"if":{"hide":1,"want":1}
,"removed":{"layout":1,"list":1}
,"visible":{"users":1}
,"users":{"view":1}
,"views":{"fields":1}
,"marked":{"lock":1}
,"lock":{"icon":1}
,"icon":{"lock":1,"modify":1}
,"indicating":{"can\u2019t":1}
,"can\u2019t":{"removed":1}
,"prevent":{"fields":1}
,"by":{"clearing":1,"layout":1}
,"clearing":{"checkbox":1}
,"checkbox":{"es":1}
,"es":{"add":1}
,"style":{"point":1}
,"point":{"size":1}
,"size":{"font":1}
,"font":{"determined":1,"settings":1,"characteristics":1}
,"determined":{"by":1}
,"theme\u2019s":{"default":1}
,"default":{"font":1}
,"settings":{"if":1}
,"change":{"font":1}
,"characteristics":{"field":1}
,"use":{"layout":1}
,"format":{"field":1}
}
;Search.control.loadWordPairs(pairs);
