var pairs =
{
"end":{"if":1}
,"if":{"arks":1,"script":1,"step":1,"records":1,"[get":1,"automating":1}
,"arks":{"end":1}
,"script":{"step":1,"editing":1}
,"step":{"structure":1,"end":1,"indentation":1,"script":1,"performs":1}
,"structure":{"none":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"if":1}
,"indentation":{"use":1}
,"use":{"if":1}
,"editing":{"pane":1}
,"pane":{"automatically":1}
,"automatically":{"enters":1}
,"enters":{"end":1}
,"performs":{"find":1}
,"find":{"if":1,"[restore]":1}
,"records":{"found":1,"sorts":1,"sort":1,"[restore":1}
,"found":{"displays":1}
,"displays":{"all":1}
,"all":{"records":1}
,"sorts":{"perform":1}
,"perform":{"find":1}
,"[restore]":{"if":1}
,"[get":{"foundcount":1}
,"foundcount":{"=0]":1}
,"=0]":{"show":1}
,"show":{"all":1}
,"sort":{"records":1}
,"[restore":{"dialog":1}
,"dialog":{"off]":1}
,"off]":{"end":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
