var pairs =
{
"favorite":{"files":1,"osts":1,"add":1,"file":1,"right-click":1,"don\u2019t":1,"host":1,"edit":1}
,"files":{"host":1,"manage":1}
,"host":{"manage":1,"choose":1,"favorite":1,"name":1,"enter":1,"button":1,"dialog":1,"selected":1,"right-click":1,"double-click":1}
,"manage":{"favorite":1}
,"osts":{"choose":1}
,"choose":{"file":1,"filename":1,"host":1,"remove":1}
,"file":{"menu":1,"favorite":1,"shared":1,"right-click":1,"isn\u2019t":1,"dialog":1}
,"menu":{"apps":1,"hosts":1}
,"apps":{"show":1,"recent":1,"apps":1,"window":1}
,"show":{"apps":1,"hosts":1,"hide":1}
,"recent":{"window":1}
,"window":{"create":1,"apps":1,"add":1,"choose":1}
,"create":{"window":1}
,"add":{"local":1,"app":1,"file":1,"favorite":1,"host":1}
,"local":{"file":1,"arrow":1}
,"app":{"browse":1,"host":1}
,"browse":{"choose":1}
,"filename":{"add":1,"remove":1,"choose":1}
,"shared":{"network":1}
,"network":{"favorite":1}
,"remove":{"favorite":1,"note":1}
,"right-click":{"filename":1,"host":1}
,"note":{"file":1,"fi":1}
,"isn\u2019t":{"deleted":1}
,"deleted":{"hard":1}
,"hard":{"disk":1}
,"disk":{"removed":1}
,"removed":{"apps":1}
,"hosts":{"show":1,"hosts":1,"open":1,"dialog":1,"access":1,"search":1}
,"open":{"file":1}
,"dialog":{"box":1}
,"box":{"hosts":1,"display":1,"cl":1,"note":1}
,"display":{"hide":1,"add":1,"edit":1}
,"hide":{"list":1,"macos":1}
,"list":{"hosts":1,"add":1}
,"access":{"next":1}
,"next":{"local":1}
,"arrow":{"windows":1}
,"windows":{"show":1}
,"macos":{"host":1}
,"name":{"list":1,"hosts":1,"displayed":1,"remove":1,"display":1}
,"don\u2019t":{"host":1}
,"enter":{"host":1}
,"search":{"box":1}
,"cl":{"ick":1}
,"ick":{"add":1}
,"button":{"display":1}
,"fi":{"le":1}
,"le":{"name":1}
,"displayed":{"last":1}
,"last":{"favorite":1}
,"selected":{"remove":1}
,"edit":{"favorite":1}
,"double-click":{"host":1}
}
;Search.control.loadWordPairs(pairs);
