var pairs =
{
"bout":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"custom":1,"creates":1,"file":1,"layouts":1}
,"custom":{"apps":1,"app":1}
,"apps":{"filemaker":1}
,"app":{"solution":1,"file":1,"lso":1,"olves":1,"page":1,"web":1}
,"solution":{"database":1}
,"database":{"file":1,"tables":1,"se":1}
,"file":{"all":1,"set":1,"contacts":1,"holds":1,"contain":1,"new":1,"various":1,"text":1,"layouts":1,"change":1,"design":1,"disk":1,"size":1}
,"all":{"terms":1,"filemaker":1,"records":1,"topic":1,"data":1}
,"terms":{"filemaker":1}
,"creates":{"custom":1}
,"set":{"files":1,"layout":1,"up":1}
,"files":{"database":1,"calculated":1}
,"tables":{"layouts":1,"contain":1,"enter":1,"define":1,"each":1,"records":1}
,"layouts":{"cripts":1,"data":1,"determine":1,"store":1,"file":1,"entering":1,"each":1,"reports":1,"layout":1}
,"cripts":{"relationships":1}
,"relationships":{"nd":1,"allow":1}
,"nd":{"associated":1}
,"associated":{"data":1}
,"data":{"enter":1,"file":1,"fields":1,"entered":1,"text":1,"organized":1,"layouts":1,"just":1,"field":1,"summary":1,"records":1,"tables":1,"stored":1,"change":1,"up-to-date":1,"current":1,"efficiently":1,"related":1,"two":1}
,"enter":{"custom":1,"data":1}
,"lso":{"includes":1}
,"includes":{"fields":1}
,"fields":{"definitions":1,"data":1,"belong":1,"store":1,"filemaker":1,"contained":1,"display":1,"add":1,"layouts":1}
,"definitions":{"calculations":1}
,"calculations":{"passwords":1}
,"passwords":{"access":1}
,"access":{"privileges":1}
,"privileges":{"each":1}
,"each":{"custom":1,"piece":1,"file":1,"instance":1}
,"olves":{"specific":1}
,"specific":{"problems":1}
,"problems":{"tracking":1}
,"tracking":{"customers":1}
,"customers":{"invoices":1,"file":1}
,"invoices":{"concepts":1}
,"concepts":{"all":1}
,"page":{"english":1,"file":1}
,"english":{"tables":1}
,"contain":{"all":1,"multiple":1,"value":1}
,"records":{"fields":1,"file":1,"contain":1,"printed":1}
,"contacts":{"file":1}
,"holds":{"pertaining":1}
,"pertaining":{"friends":1}
,"friends":{"customers":1}
,"multiple":{"tables":1}
,"topic":{"related":1}
,"related":{"topics":1,"table":1,"data":1,"tables":1}
,"topics":{"relational":1}
,"relational":{"database":1}
,"se":{"defining":1,"adding":1,"creating":1}
,"defining":{"database":1,"changing":1}
,"new":{"record":1}
,"record":{"enter":1,"create":1,"field":1,"name":1,"fit":1}
,"belong":{"record":1}
,"create":{"records":1,"reports":1}
,"various":{"edit":1}
,"edit":{"sort":1}
,"sort":{"find":1}
,"find":{"group":1}
,"group":{"records":1,"summarize":1}
,"value":{"se":1,"field":1}
,"adding":{"duplicating":1}
,"duplicating":{"deleting":1}
,"deleting":{"records":1}
,"store":{"calculate":1,"data":1}
,"calculate":{"display":1}
,"display":{"data":1,"change":1,"print":1,"arrange":1}
,"entered":{"record":1,"fields":1}
,"field":{"by":1,"values":1,"defining":1,"layout":1,"displayed":1,"labels":1}
,"by":{"typing":1}
,"typing":{"pasting":1}
,"pasting":{"importing":1}
,"importing":{"application":1}
,"application":{"value":1}
,"values":{"filemaker":1,"summary":1,"each":1}
,"text":{"numbers":1,"entered":1,"add":1}
,"numbers":{"dates":1}
,"dates":{"times":1}
,"times":{"timestamps":1}
,"timestamps":{"pictures":1}
,"pictures":{"sounds":1}
,"sounds":{"movies":1}
,"movies":{"files":1}
,"calculated":{"values":1}
,"summary":{"values":1,"reporting":1}
,"piece":{"record":1}
,"name":{"address":1}
,"address":{"telephone":1}
,"telephone":{"number":1}
,"number":{"stored":1}
,"stored":{"field":1,"table":1}
,"changing":{"fields":1}
,"contained":{"file":1}
,"determine":{"data":1}
,"organized":{"viewing":1}
,"viewing":{"printing":1}
,"printing":{"reporting":1,"mailing":1}
,"reporting":{"finding":1,"printing":1}
,"finding":{"entering":1}
,"entering":{"data":1}
,"just":{"display":1}
,"change":{"design":1,"data":1,"appears":1,"instance":1}
,"design":{"layout":1,"separate":1}
,"layout":{"doesn\u2019t":1,"change":1,"field":1,"display":1,"relationships":1}
,"doesn\u2019t":{"affect":1}
,"affect":{"data":1}
,"appears":{"layout":1,"dynamically":1}
,"displayed":{"set":1,"related":1}
,"print":{"record":1}
,"fit":{"page":1}
,"separate":{"layouts":1}
,"mailing":{"labels":1}
,"labels":{"publishing":1,"create":1}
,"publishing":{"custom":1}
,"web":{"layouts":1}
,"disk":{"space":1}
,"space":{"maximum":1,"related":1}
,"maximum":{"file":1}
,"size":{"allows":1}
,"allows":{"se":1}
,"creating":{"managing":1}
,"managing":{"layouts":1}
,"reports":{"choose":1,"group":1}
,"choose":{"fields":1}
,"arrange":{"format":1}
,"format":{"fields":1}
,"add":{"modify":1,"graphics":1,"emphasis":1}
,"modify":{"field":1}
,"summarize":{"data":1}
,"printed":{"add":1}
,"graphics":{"text":1}
,"emphasis":{"interest":1}
,"interest":{"relationships":1}
,"allow":{"table":1,"data":1}
,"table":{"data":1,"time":1,"change":1,"copy":1,"storing":1}
,"define":{"relationship":1,"lookup":1}
,"relationship":{"two":1}
,"two":{"tables":1,"looked-up":1}
,"instance":{"data":1,"related":1}
,"time":{"accessed":1,"copied":1}
,"accessed":{"displayed":1}
,"dynamically":{"all":1}
,"up-to-date":{"relationships":1}
,"current":{"state":1,"table":1,"time":1}
,"state":{"set":1}
,"up":{"manage":1,"efining":1}
,"manage":{"data":1}
,"efficiently":{"flexibility":1}
,"flexibility":{"save":1}
,"save":{"disk":1}
,"lookup":{"retrieve":1}
,"retrieve":{"data":1}
,"copy":{"current":1}
,"storing":{"data":1}
,"looked-up":{"data":1}
,"copied":{"copied":1,"remains":1}
,"remains":{"static":1}
,"static":{"looked":1}
,"looked":{"up":1}
,"efining":{"updating":1}
,"updating":{"lookups":1}
,"lookups":{"hat":1}
,"hat":{"tables":1}
}
;Search.control.loadWordPairs(pairs);
