var pairs =
{
"setting":{"up":1,"11":1}
,"up":{"files":1}
,"files":{"developer":1,"standalone":1,"protect":1,"automatically":1,"scripts":1,"kiosk":1,"create":1,"elements":1,"close":1,"customize":1,"want":1,"aming":1,"overwrite":1,"clear":1,"project":1,"names":1,"solution":1,"bind":1,"runtime":1,"modifications":1,"left":1,"copied":1,"cleared":1}
,"developer":{"solution":1,"utilities":1,"solutions":1}
,"solution":{"note":1,"require":1,"saved":1,"double-click":1,"remove":1,"choose":1,"options":1,"10":1,"setting":1}
,"note":{"topic":1,"filemaker":1,"type":1}
,"topic":{"describes":1}
,"describes":{"features":1}
,"features":{"use":1}
,"use":{"advanced":1}
,"advanced":{"tools":1,"rovides":1,"order":1,"llow":1}
,"tools":{"general":1,"ilemaker":1,"menu":1}
,"general":{"preference":1}
,"preference":{"selected":1}
,"selected":{"ad":1,"developer":1,"database":1}
,"ad":{"vanced":1}
,"vanced":{"tools":1}
,"ilemaker":{"pro":1}
,"pro":{"advanced":1,"12":1}
,"rovides":{"developer":1}
,"utilities":{"let":1,"if":1,"database":1,"overwrite":1,"copy":1,"project":1}
,"let":{"bind":1}
,"bind":{"database":1,"files":1}
,"database":{"files":1,"solution":1,"tables":1,"file":1}
,"standalone":{"runtime":1}
,"runtime":{"database":1,"solution":1,"files":1}
,"require":{"filemaker":1}
,"filemaker":{"pro":1}
,"order":{"computer":1}
,"computer":{"encrypt":1}
,"encrypt":{"database":1}
,"protect":{"unauthorized":1}
,"unauthorized":{"access":1}
,"access":{"while":1,"all":1,"privileges":1}
,"while":{"stored":1}
,"stored":{"disk":1,"file":1}
,"disk":{"rename":1}
,"rename":{"set":1,"file":1}
,"set":{"database":1,"non-runtime":1,"up":1}
,"automatically":{"update":1}
,"update":{"internal":1}
,"internal":{"links":1}
,"links":{"related":1}
,"related":{"files":1}
,"scripts":{"display":1,"access":1,"note":1}
,"display":{"database":1}
,"kiosk":{"mode":1}
,"mode":{"remove":1}
,"remove":{"administrative":1,"file":1,"project":1}
,"administrative":{"access":1}
,"all":{"accounts":1,"database":1,"files":1,"selected":1}
,"accounts":{"prevent":1}
,"prevent":{"users":1}
,"users":{"modifying":1}
,"modifying":{"design":1}
,"design":{"structural":1}
,"structural":{"elements":1}
,"elements":{"databases":1,"scripts":1}
,"databases":{"add":1}
,"add":{"filemaker":1,"locate":1}
,"12":{"ilename":1}
,"ilename":{"extension":1}
,"extension":{".fmp12":1,"adding":1}
,".fmp12":{"set":1}
,"non-runtime":{"files":1}
,"create":{"error":1,"folder":1,"developer":1}
,"error":{"log":1}
,"log":{"processing":1}
,"processing":{"errors":1}
,"errors":{"note":1}
,"llow":{"include":1}
,"include":{"database":1}
,"tables":{"database":1}
,"file":{"capability":1,"level":1,"dialog":1,"add":1,"runtime":1,"list":1,"select":1,"box":1,"saving":1}
,"capability":{"eliminates":1}
,"eliminates":{"main":1}
,"main":{"reasons":1}
,"reasons":{"multiple":1}
,"multiple":{"files":1}
,"privileges":{"stored":1}
,"level":{"complex":1}
,"complex":{"solutions":1}
,"solutions":{"benefit":1}
,"benefit":{"multiple":1}
,"close":{"all":1}
,"customize":{"choose":1,"all":1,"select":1,"database":1}
,"choose":{"tools":1,"location":1,"folder":1,"macos":1}
,"menu":{"developer":1}
,"if":{"developer":1,"want":1,"overwrite":1,"default":1,"empty":1}
,"saved":{"settings":1}
,"settings":{"load":1,"select":1,"file":1,"choose":1}
,"load":{"settings":1}
,"select":{"file":1,"primary":1,"create":1,"options":1}
,"dialog":{"box":1}
,"box":{"browse":1,"change":1,"select":1}
,"browse":{"find":1}
,"find":{"settings":1}
,"locate":{"files":1}
,"want":{"customize":1,"new":1}
,"primary":{"file":1}
,"double-click":{"file":1}
,"list":{"rename":1,"type":1,"remove":1,"files":1}
,"type":{"new":1,"filename":1}
,"new":{"name":1,"files":1,"based":1}
,"name":{"rename":1,"project":1}
,"change":{"updates":1}
,"updates":{"internal":1}
,"filename":{"extension":1,"extensions":1}
,"adding":{"filename":1}
,"extensions":{"runtime":1}
,"aming":{"runtime":1}
,"project":{"folder":1}
,"folder":{"choose":1,"dialog":1,"windows":1,"checkbox":1,"selected":1,"location":1,"if":1,"store":1,"created":1}
,"location":{"solution":1,"settings":1}
,"windows":{"choose":1}
,"macos":{"if":1}
,"overwrite":{"earlier":1,"matching":1,"files":1,"destination":1}
,"earlier":{"versions":1}
,"versions":{"files":1}
,"clear":{"overwrite":1}
,"matching":{"files":1}
,"checkbox":{"if":1}
,"names":{"list":1}
,"options":{"select":1,"customize":1,"developer":1}
,"10":{"quickly":1}
,"quickly":{"repeat":1}
,"repeat":{"process":1}
,"process":{"save":1}
,"save":{"settings":1}
,"saving":{"solution":1}
,"11":{"create":1}
,"copy":{"all":1}
,"modifications":{"made":1}
,"made":{"by":1}
,"by":{"utilities":1,"developer":1}
,"default":{"option":1}
,"option":{"overwrite":1}
,"destination":{"files":1}
,"left":{"project":1}
,"store":{"files":1}
,"copied":{"by":1}
,"cleared":{"project":1}
,"empty":{"new":1}
,"based":{"name":1}
,"created":{"set":1}
}
;Search.control.loadWordPairs(pairs);
