var pairs =
{
"getthumbnail":{"returns":1,"field":1,"invoices":1}
,"returns":{"thumbnail":1,"container":1,"image":1}
,"thumbnail":{"image":1,"height":1,"container":1,"maximum":1,"exports":1}
,"image":{"content":1,"container":1,"maintains":1,"resolution":1,"if":1,"returned":1,"data":1,"creating":1}
,"content":{"container":1}
,"container":{"field":1,"data":1,"filemaker":1}
,"field":{"height":1,"width":1,"-any":1,"parameter":1,"image":1,"evaluate":1,"[invoices":1,"contents":1}
,"height":{"width":1,"field":1,"-the":1,"thumbnail":1}
,"width":{"getthumbnail":1,"height":1,"-the":1,"thumbnail":1,"50":1}
,"-any":{"expression":1}
,"expression":{"returns":1}
,"data":{"width":1,"that\u2019s":1,"field":1}
,"-the":{"maximum":1}
,"maximum":{"width":1,"height":1}
,"filemaker":{"pro":1}
,"pro":{"12.0":1}
,"12.0":{"returns":1}
,"that\u2019s":{"larger":1}
,"larger":{"pecified":1,"image\u2019s":1}
,"pecified":{"values":1}
,"values":{"width":1}
,"maintains":{"proportions":1}
,"proportions":{"original":1}
,"original":{"image":1,"size":1}
,"resolution":{"72":1}
,"72":{"dpi":1}
,"dpi":{"thumbnails":1}
,"thumbnails":{"made":1,"images":1,"if":1}
,"made":{"larger":1}
,"image\u2019s":{"original":1}
,"size":{"function":1,"managing":1}
,"function":{"returns":1}
,"if":{"generate":1,"option":1,"field":1}
,"generate":{"store":1}
,"store":{"thumbnails":1}
,"images":{"option":1}
,"option":{"selected":1,"deselected":1}
,"selected":{"manage":1}
,"manage":{"containers":1}
,"containers":{"dialog":1}
,"dialog":{"box":1,"customers":1}
,"box":{"if":1}
,"deselected":{"image":1}
,"returned":{"original":1}
,"managing":{"performance":1}
,"performance":{"thumbnails":1}
,"parameter":{"field":1}
,"evaluate":{"file":1}
,"file":{"path":1,"paths":1}
,"path":{"image":1}
,"creating":{"file":1}
,"paths":{"exports":1}
,"exports":{"thumbnail":1,"attaches":1}
,"50":{"points":1,"50":1,"export":1,"set":1}
,"points":{"set":1}
,"set":{"field":1,"variable":1}
,"[invoices":{":exportcontainer":1}
,":exportcontainer":{"getthumbnail":1,"create":1,"filename":1,"\u0022$attachment":1}
,"invoices":{":container":1,":exportcontainer":1}
,":container":{"50":1}
,"export":{"field":1}
,"contents":{"[invoices":1}
,"create":{"folders":1}
,"folders":{"off]":1}
,"off]":{"creates":1,"send":1}
,"creates":{"thumbnail":1}
,"attaches":{"email":1}
,"email":{"set":1}
,"variable":{"[$attachment":1}
,"[$attachment":{"value:get":1}
,"value:get":{"temporarypath":1}
,"temporarypath":{"&getcontainerattribute":1}
,"&getcontainerattribute":{"invoices":1}
,"filename":{")]":1}
,")]":{"export":1}
,"\u0022$attachment":{"create":1,"\u0022]":1}
,"send":{"mail":1}
,"mail":{"[send":1}
,"[send":{"via":1}
,"via":{"e-mail":1}
,"e-mail":{"client":1}
,"client":{"dialog":1}
,"customers":{":email":1}
,":email":{"\u0022$attachment":1}
}
;Search.control.loadWordPairs(pairs);
