var pairs =
{
"get":{"printern":1,"printername":1,"printer":1,"default":1}
,"printern":{"ame":1}
,"ame":{"returns":1}
,"returns":{"text":1,"string":1,"empty":1,"hp":1,"24.109.265.43":1}
,"text":{"identifying":1,"filemaker":1}
,"identifying":{"default":1}
,"default":{"printer":1}
,"printer":{"name":1,"port":1,"if":1,"get":1}
,"name":{"get":1,"driver":1,"name":1,"printer":1,"macos":1}
,"printername":{"none":1,"get":1}
,"none":{"text":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"windows":1}
,"windows":{"returns":1}
,"string":{"each":1,"entries":1,"returns":1}
,"each":{"entries":1}
,"entries":{"separated":1}
,"separated":{"by":1}
,"by":{"comma":1,"word":1}
,"comma":{"printer":1}
,"driver":{"name":1}
,"port":{"macos":1}
,"macos":{"returns":1,"filemaker":1,"get":1}
,"word":{"queue":1}
,"queue":{"name":1}
,"if":{"ip":1,"isn\u2019t":1}
,"ip":{"address":1}
,"address":{"printer":1}
,"isn\u2019t":{"unknown":1}
,"unknown":{"inserted":1}
,"inserted":{"result":1}
,"result":{"except":1}
,"except":{"queue":1}
,"webdirect":{"function":1}
,"function":{"supported":1}
,"supported":{"returns":1}
,"empty":{"string":1}
,"hp":{"laserjet":1}
,"laserjet":{"p4015":1}
,"p4015":{"winspool":1}
,"winspool":{"ne03":1}
,"ne03":{"windows":1}
,"24.109.265.43":{"macos":1}
}
;Search.control.loadWordPairs(pairs);
