var pairs =
{
"savin":{"sending":1}
,"sending":{"records":1}
,"records":{"snapshot":1,"called":1,"want":1,"xporting":1,"deleted":1,"associated":1,"based":1,"if":1}
,"snapshot":{"link":1}
,"link":{"save":1,"capture":1,"format":1,"includes":1,"aking":1,"dialog":1,"preserve":1,"return":1,"created":1,"proper":1,"napshot":1,"file":1}
,"save":{"found":1,"snapshot":1,"records":1,"copy":1}
,"found":{"set":1}
,"set":{"records":1,"performed":1,"saved":1,"record":1}
,"called":{"snapshot":1}
,"capture":{"found":1}
,"performed":{"find":1,"database":1}
,"find":{"request":1,"records":1}
,"request":{"found":1,"browse":1,"ake":1}
,"saved":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"snapshot":1,"advanced":1}
,"format":{"fmpsl":1}
,"fmpsl":{"filename":1,"file":1}
,"filename":{"extension":1,"enter":1}
,"extension":{".fmpsl":1}
,".fmpsl":{"email":1}
,"email":{"fmpsl":1}
,"file":{"person":1,"menu":1,"saving":1,"re-create":1}
,"person":{"snapshot":1}
,"includes":{"current":1}
,"current":{"found":1,"file":1}
,"record":{"ids":1,"data":1}
,"ids":{"including":1}
,"including":{"layout":1}
,"layout":{"view":1,"mode":1,"deleted":1,"records":1,"running":1}
,"view":{"sort":1}
,"sort":{"order":1}
,"order":{"mode":1}
,"mode":{"toolbar":1,"layout":1,"preview":1,"choose":1}
,"toolbar":{"visibility":1}
,"visibility":{"find":1}
,"want":{"save":1}
,"aking":{"find":1}
,"browse":{"mode":1}
,"preview":{"mode":1}
,"choose":{"file":1}
,"menu":{"save\u002Fsend":1}
,"save\u002Fsend":{"records":1}
,"dialog":{"box":1}
,"box":{"accept":1}
,"accept":{"default":1}
,"default":{"filename":1}
,"enter":{"name":1}
,"name":{"options":1}
,"options":{"lick":1}
,"lick":{"save":1}
,"preserve":{"record":1}
,"data":{"snapshot":1,"state":1,"export":1,"filemaker":1}
,"return":{"record":1}
,"state":{"snapshot":1}
,"created":{"preserve":1,"records":1}
,"export":{"records":1}
,"xporting":{"data":1}
,"advanced":{"save":1}
,"copy":{"file":1}
,"saving":{"copying":1}
,"copying":{"files":1}
,"files":{"records":1}
,"deleted":{"snapshot":1,"associated":1}
,"associated":{"layout":1,"table":1}
,"table":{"displayed":1}
,"displayed":{"records":1}
,"based":{"current":1}
,"re-create":{"find":1}
,"ake":{"sure":1}
,"sure":{"use":1}
,"use":{"snapshot":1}
,"proper":{"access":1}
,"access":{"privileges":1}
,"privileges":{"layout":1}
,"if":{"actions":1}
,"actions":{"set":1,"snapshot":1}
,"database":{"switching":1}
,"switching":{"layout":1}
,"running":{"script":1}
,"script":{"responding":1,"trigger":1}
,"responding":{"script":1}
,"trigger":{"actions":1}
,"napshot":{"links":1}
,"links":{"supported":1}
,"supported":{"runtime":1}
,"runtime":{"solutions":1}
,"solutions":{"save":1}
}
;Search.control.loadWordPairs(pairs);
