var pairs =
{
"get":{"currentprivileg":1,"currentprivilegesetname":1,"accountprivilegesetname":1,"current":1}
,"currentprivileg":{"esetname":1}
,"esetname":{"returns":1}
,"returns":{"name":1,"[full":1,"[read-only":1}
,"name":{"privilege":1,"get":1}
,"privilege":{"set":1}
,"set":{"evaluate":1,"run":1,"name":1}
,"evaluate":{"calculation":1}
,"calculation":{"file":1,"function":1}
,"file":{"get":1,"function":1}
,"currentprivilegesetname":{"none":1,"returns":1,"return":1,"get":1}
,"none":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"if":1}
,"if":{"user":1,"context":1,"function":1}
,"user":{"default":1,"read-only":1,"administrator":1,"sales":1}
,"default":{"admin":1}
,"admin":{"account":1}
,"account":{"haven\u2019t":1}
,"haven\u2019t":{"modified":1}
,"modified":{"access":1}
,"access":{"privileges":1,"database":1}
,"privileges":{"file":1,"get":1}
,"function":{"returns":1,"evaluated":1,"current":1}
,"[full":{"access]":1}
,"access]":{"if":1,"user":1,"get":1,"current":1}
,"context":{"current":1,"evaluated":1}
,"current":{"calculation":1,"window":1,"script":1,"user":1,"privilge":1,"privilege":1}
,"evaluated":{"based":1,"script":1}
,"based":{"context":1}
,"window":{"if":1}
,"script":{"set":1,"get":1}
,"run":{"full":1}
,"full":{"access":1}
,"read-only":{"access":1}
,"database":{"running":1}
,"running":{"script":1}
,"accountprivilegesetname":{"returns":1,"function":1}
,"[read-only":{"access]":1}
,"administrator":{"get":1}
,"return":{"[full":1,"[data":1}
,"sales":{"department":1}
,"department":{"get":1}
,"[data":{"entry":1}
,"entry":{"only]":1}
,"only]":{"get":1}
,"privilge":{"set":1}
}
;Search.control.loadWordPairs(pairs);
