var pairs =
{
"display":{"state":1,"arker":1,"contrasting":1,"fill":1,"object":1,"states":1}
,"state":{"object":1,"list":1,"fills":1,"portal":1,"displays":1,"set":1}
,"object":{"attributes":1,"components":1,"steps":1,"type":1,"if":1,"state":1,"types":1,"layout":1,"user":1,"activated":1,"pressed":1,"primary":1,"identifies":1,"part":1}
,"attributes":{"indicating":1,"all":1,"display":1}
,"indicating":{"state":1}
,"components":{"isual":1,"buttons":1,"choose":1}
,"isual":{"feedback":1}
,"feedback":{"actions":1}
,"actions":{"ake":1}
,"ake":{"format":1}
,"format":{"button":1,"placeholder":1}
,"button":{"display":1,"current":1,"held":1,"bar":1}
,"arker":{"color":1}
,"color":{"button":1,"list":1}
,"current":{"record":1,"panel":1,"row":1}
,"record":{"display":1,"alternating":1,"list":1,"displayed":1}
,"contrasting":{"color":1}
,"list":{"view":1,"top":1,"second":1,"tab":1}
,"view":{"layout":1,"select":1,"list":1,"ecords":1,"portal":1,"selected":1,"change":1}
,"layout":{"mode":1,"part":1,"setting":1}
,"mode":{"select":1}
,"select":{"objects":1,"body":1}
,"objects":{"note":1,"types":1,"objects":1,"components":1}
,"note":{"active":1,"all":1}
,"active":{"current":1,"object":1,"segment":1,"use":1,"row":1,"currently":1}
,"alternating":{"records":1}
,"records":{"display":1,"displayed":1}
,"fill":{"list":1,"line":1,"current":1}
,"body":{"part":1,"layout":1}
,"part":{"label":1,"considered":1,"normal":1,"viewed":1,"all":1,"diting":1,"change":1,"definition":1,"hanging":1,"hen":1}
,"label":{"body":1}
,"considered":{"object":1}
,"steps":{"inspector":1,"3-5":1}
,"inspector":{"lick":1}
,"lick":{"appearance":1}
,"appearance":{"appearance":1,"tab":1}
,"tab":{"object":1,"displays":1,"note":1,"key":1}
,"type":{"list":1,"selected":1,"ist":1}
,"top":{"tab":1}
,"displays":{"type":1,"selected":1,"row":1,"conditions":1}
,"selected":{"object":1,"objects":1,"focus":1,"row":1}
,"if":{"select":1}
,"types":{"filemaker":1,"components":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"displays":1}
,"buttons":{"portals":1}
,"portals":{"slide":1,"epeat":1,"pressed":1}
,"slide":{"controls":1}
,"controls":{"choose":1}
,"choose":{"object":1,"state":1,"display":1}
,"ist":{"choose":1}
,"second":{"list":1}
,"all":{"style":1,"object":1,"rows":1}
,"style":{"attributes":1,"shadows":1}
,"normal":{"inactive":1}
,"inactive":{"object":1}
,"user":{"currently":1,"pauses":1}
,"currently":{"selected":1,"pressed":1}
,"focus":{"object":1}
,"activated":{"by":1}
,"by":{"mouse-click":1}
,"mouse-click":{"tab":1}
,"key":{"script":1}
,"script":{"hover":1,"trigger":1}
,"hover":{"user":1,"state":1}
,"pauses":{"pointer":1}
,"pointer":{"object":1}
,"pressed":{"mouse":1,"state":1,"row":1}
,"mouse":{"button":1}
,"held":{"clickable":1}
,"clickable":{"object":1}
,"primary":{"body":1,"state":1}
,"viewed":{"form":1}
,"form":{"view":1}
,"ecords":{"displayed":1}
,"displayed":{"rows":1,"fill":1}
,"rows":{"portal":1,"conditions":1}
,"portal":{"setting":1,"alternate":1,"active":1,"current":1,"rows":1,"ormatting":1,"onobjectenter":1}
,"setting":{"primary":1,"fill":1}
,"fills":{"background":1}
,"background":{"body":1}
,"alternate":{"object":1}
,"identifies":{"even-numbered":1,"current":1}
,"even-numbered":{"record":1}
,"row":{"portal":1,"hovered":1,"active":1,"state":1}
,"panel":{"panel":1,"control":1}
,"control":{"active":1}
,"segment":{"button":1}
,"bar":{"format":1}
,"placeholder":{"text":1}
,"text":{"formatting":1,"set":1}
,"formatting":{"placeholder":1,"display":1}
,"set":{"style":1,"portal":1}
,"diting":{"creating":1}
,"creating":{"styles":1}
,"styles":{"layout":1}
,"line":{"style":1}
,"shadows":{"padding":1}
,"padding":{"ormatting":1}
,"ormatting":{"portals":1}
,"epeat":{"steps":1}
,"3-5":{"additional":1}
,"additional":{"display":1}
,"states":{"object":1}
,"change":{"alternating":1,"settings":1}
,"settings":{"part":1}
,"definition":{"dialog":1}
,"dialog":{"box":1}
,"box":{"body":1}
,"hanging":{"layout":1}
,"hen":{"formatting":1}
,"conditions":{"apply":1,"met":1}
,"apply":{"hover":1}
,"hovered":{"active":1}
,"use":{"active":1}
,"met":{"currently":1}
,"onobjectenter":{"script":1}
,"trigger":{"assigned":1,"display":1}
,"assigned":{"portal":1}
}
;Search.control.loadWordPairs(pairs);
