var pairs =
{
"show\u002Fhide":{"toolbars":1,"status":1}
,"toolbars":{"hows":1,"returns":1,"[show]":1,"[hide]":1}
,"hows":{"hides":1}
,"hides":{"filemaker":1,"status":1}
,"filemaker":{"pro":1,"go":1}
,"pro":{"advanced":1,"6.0":1}
,"advanced":{"tatus":1,"status":1}
,"tatus":{"toolbar":1}
,"toolbar":{"filemaker":1,"editing":1,"lock":1,"include":1,"show":1,"hide":1,"toggle":1,"equivalent":1,"pauses":1,"enter":1,"automating":1}
,"go":{"toolbar":1,"editing":1}
,"editing":{"toolbar":1}
,"lock":{"prohibits":1}
,"prohibits":{"user":1}
,"user":{"manually":1,"input":1}
,"manually":{"hiding":1}
,"hiding":{"filemaker":1}
,"include":{"edit":1}
,"edit":{"record":1}
,"record":{"toolbar":1}
,"show":{"filemaker":1}
,"status":{"toolbar":1}
,"hide":{"hides":1}
,"toggle":{"switches":1}
,"switches":{"hiding":1}
,"equivalent":{"clicking":1}
,"clicking":{"show\u002Fhide":1}
,"6.0":{"earlier":1}
,"earlier":{"if":1}
,"if":{"script":1}
,"script":{"step":1,"[indefinitely]":1}
,"step":{"performed":1}
,"performed":{"card":1}
,"card":{"show\u002Fhide":1}
,"returns":{"error":1}
,"error":{"code":1}
,"code":{"captured":1}
,"captured":{"get":1}
,"get":{"lasterror":1}
,"lasterror":{"function":1}
,"function":{"enters":1}
,"enters":{"find":1}
,"find":{"mode":1,"hides":1,"[]":1}
,"mode":{"status":1,"[pause":1}
,"pauses":{"user":1}
,"input":{"performs":1}
,"performs":{"find":1}
,"enter":{"find":1}
,"[pause":{"off]":1}
,"off]":{"show\u002Fhide":1}
,"[show]":{"pause\u002Fresume":1}
,"pause\u002Fresume":{"script":1}
,"[indefinitely]":{"perform":1}
,"perform":{"find":1}
,"[]":{"show\u002Fhide":1}
,"[hide]":{"status":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
