var pairs =
{
"any-to-many":{"relationships":1}
,"relationships":{"many-to-many":1,"by":1,"each":1}
,"many-to-many":{"relationship":1}
,"relationship":{"occurs":1,"exists":1,"two":1,"students":1,"line":1,"display":1}
,"occurs":{"multiple":1}
,"multiple":{"records":1}
,"records":{"table":1,"join":1,"enrollments":1,"classes":1,"students":1}
,"table":{"associated":1,"many-to-many":1,"called":1,"each":1,"includes":1,"match":1,"created":1,"joins":1,"record":1,"enrollments":1,"classes":1,"primary":1,"foreign":1,"named":1,"create":1,"add":1,"date":1,"records":1,"design":1}
,"associated":{"multiple":1}
,"exists":{"customers":1}
,"customers":{"products":1,"purchase":1,"relational":1,"inquired":1}
,"products":{"customers":1,"products":1,"purchased":1}
,"purchase":{"various":1}
,"various":{"products":1}
,"purchased":{"by":1}
,"by":{"customers":1,"table":1}
,"relational":{"database":1}
,"database":{"systems":1}
,"systems":{"usually":1}
,"usually":{"allow":1}
,"allow":{"implement":1}
,"implement":{"direct":1}
,"direct":{"many-to-many":1}
,"two":{"tables":1,"one-to-many":1,"student":1,"class":1}
,"tables":{"keeping":1,"joins":1,"students":1,"typically":1,"create":1,"design":1,"access":1}
,"keeping":{"track":1}
,"track":{"invoices":1,"started":1,"student":1}
,"invoices":{"if":1,"invoice":1}
,"if":{"invoices":1,"student":1}
,"invoice":{"number":1,"avoid":1}
,"number":{"customers":1,"wouldn\u2019t":1,"referring":1}
,"inquired":{"invoice":1}
,"wouldn\u2019t":{"number":1}
,"referring":{"reason":1}
,"reason":{"assigning":1}
,"assigning":{"unique":1}
,"unique":{"value":1}
,"value":{"each":1,"primary":1}
,"each":{"invoice":1,"record":1,"student":1,"class":1,"two":1,"relationship":1}
,"avoid":{"problem":1}
,"problem":{"break":1}
,"break":{"many-to-many":1}
,"one-to-many":{"relationships":1}
,"called":{"join":1}
,"join":{"table":1,"tables":1}
,"record":{"join":1,"each":1,"students":1}
,"includes":{"match":1,"students":1}
,"match":{"field":1,"fields":1}
,"field":{"value":1,"class":1,"join":1,"keep":1,"track":1}
,"primary":{"keys":1,"key":1}
,"keys":{"two":1,"foreign":1,"student":1}
,"joins":{"join":1,"typical":1}
,"fields":{"foreign":1,"populated":1,"sense":1,"enrollments":1,"tables":1,"data":1,"classes":1}
,"foreign":{"keys":1,"key":1}
,"key":{"fields":1,"student":1,"class":1}
,"populated":{"data":1}
,"data":{"records":1,"across":1}
,"created":{"table":1}
,"typical":{"many-to":1}
,"many-to":{"relationship":1}
,"students":{"classes":1,"includes":1,"table":1,"layout":1}
,"classes":{"student":1,"class":1,"table":1,"portal":1}
,"student":{"register":1,"classes":1,"id":1,"students":1,"paid":1,"registers":1,"record":1,"enrolled":1}
,"register":{"classes":1}
,"class":{"include":1,"join":1,"id":1,"classes":1,"cost":1,"create":1,"student":1}
,"include":{"students":1}
,"enrollments":{"creates":1,"join":1,"table":1}
,"creates":{"two":1}
,"line":{"enrollments":1}
,"id":{"uniquely":1,"class":1,"create":1,"field":1,"fields":1}
,"uniquely":{"identifies":1}
,"identifies":{"each":1}
,"create":{"table":1,"student":1,"relationship":1,"separate":1,"portal":1}
,"named":{"enrollments":1}
,"typically":{"hold":1}
,"hold":{"fields":1}
,"sense":{"table":1}
,"add":{"fields":1}
,"date":{"field":1}
,"keep":{"track":1}
,"started":{"class":1}
,"cost":{"field":1}
,"paid":{"take":1}
,"take":{"class":1}
,"design":{"if":1,"portal":1}
,"registers":{"classes":1}
,"enrolled":{"join":1,"create":1,"set":1}
,"access":{"fields":1}
,"across":{"tables":1}
,"separate":{"relationship":1}
,"display":{"list":1}
,"list":{"all":1}
,"all":{"classes":1}
,"portal":{"layout":1,"show":1,"browse":1,"displays":1}
,"layout":{"based":1,"portal":1}
,"based":{"students":1}
,"show":{"related":1}
,"related":{"records":1}
,"browse":{"records":1}
,"displays":{"all":1}
,"set":{"up":1}
,"up":{"join":1}
}
;Search.control.loadWordPairs(pairs);
