var pairs =
{
"open":{"help":1,"onscreen":1}
,"help":{"pens":1,"none":1,"filemaker":1,"show":1,"\u0022]":1,"end":1,"automating":1}
,"pens":{"onscreen":1}
,"onscreen":{"help":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1,"product":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"script":1}
,"script":{"step":1}
,"step":{"displaying":1}
,"displaying":{"help":1}
,"product":{"displays":1}
,"displays":{"custom":1}
,"custom":{"dialog":1}
,"dialog":{"box":1,"[\u0022":1}
,"box":{"if":1}
,"if":{"user":1,"[get":1,"help":1}
,"user":{"onscreen":1}
,"show":{"custom":1}
,"[\u0022":{"want":1}
,"want":{"open":1}
,"\u0022]":{"if":1}
,"[get":{"lastmessagechoice":1}
,"lastmessagechoice":{"=1]":1}
,"=1]":{"open":1}
,"end":{"if":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
