var pairs =
{
"set":{"variable":1,"enter":1,"field":1}
,"variable":{"ets":1,"value":1,"want":1,"$$for":1,"if":1,"set":1,"doesn\u2019t":1,"copy":1,"[$current_customer_id":1,"save":1,"[$path":1,"toggle":1,"[$$script_trigger":1}
,"ets":{"local":1}
,"local":{"global":1,"variable":1}
,"global":{"variable":1}
,"value":{"name":1,"value":1,"variable":1,"customers":1,"get":1,"\u0022]":1}
,"name":{"name":1,"variable":1,"$for":1,"value":1}
,"want":{"create":1}
,"create":{"prefix":1,"if":1,"sing":1,"folders":1}
,"prefix":{"name":1,"$is":1}
,"$for":{"local":1}
,"$$for":{"global":1}
,"if":{"prefix":1,"repetition":1,"variable":1,"[get":1,"global":1,"[$$script_trigger":1,"find":1}
,"$is":{"automatically":1}
,"automatically":{"name":1}
,"enter":{"text":1}
,"text":{"calculation":1}
,"calculation":{"repetition":1}
,"repetition":{"repetition":1,"index":1,"default":1}
,"index":{"number":1}
,"number":{"variable":1,"&\u0022":1}
,"default":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"8.0":1}
,"8.0":{"if":1}
,"doesn\u2019t":{"exist":1}
,"exist":{"script":1}
,"script":{"step":1,"triggered":1,"[text":1,"go":1,"trigger":1}
,"step":{"create":1}
,"sing":{"variables":1}
,"variables":{"creates":1,"automating":1}
,"creates":{"related":1}
,"related":{"record":1}
,"record":{"by":1,"excel":1,"create":1}
,"by":{"local":1}
,"copy":{"match":1}
,"match":{"field":1}
,"field":{"set":1,"[invoices":1}
,"[$current_customer_id":{"value":1}
,"customers":{":customer":1}
,":customer":{"id]":1,"id":1,"name]":1}
,"id]":{"go":1}
,"go":{"layout":1,"record\u002Frequest\u002Fpage":1,"selected":1}
,"layout":{"[\u0022":1}
,"[\u0022":{"invoice":1,"save":1}
,"invoice":{"details":1,"&invoice":1,"ios":1}
,"details":{"\u0022]":1,"ipad":1}
,"\u0022]":{"new":1,"if":1,"save":1,"go":1,"set":1,"exit":1}
,"new":{"record\u002Frequest":1}
,"record\u002Frequest":{"set":1}
,"[invoices":{":customer":1}
,"id":{"$current_customer_id]":1}
,"$current_customer_id]":{"local":1}
,"save":{"records":1,"current":1}
,"records":{"excel":1,"pdf":1,"[replace":1}
,"excel":{"pdf":1,"[restore":1}
,"pdf":{"files":1,"\u0022]":1,"[restore":1}
,"files":{"documents":1}
,"documents":{"folder":1}
,"folder":{"show":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"dialog":{"[\u0022":1,"\u0022$path":1}
,"current":{"record":1}
,"[get":{"lastmessagechoice":1}
,"lastmessagechoice":{"=1]":1}
,"=1]":{"set":1}
,"[$path":{"value":1}
,"get":{"documentspath":1}
,"documentspath":{"&\u0022":1}
,"&\u0022":{"invoice":1,".xlsx":1,".pdf":1}
,"&invoice":{":invoice":1}
,":invoice":{"number":1}
,".xlsx":{"\u0022]":1}
,"[restore":{"dialog":1}
,"\u0022$path":{"current":1,"urrent":1}
,"folders":{"off]":1}
,"off]":{"else":1,"end":1}
,"else":{"set":1}
,".pdf":{"\u0022]":1}
,"urrent":{"record":1}
,"end":{"if":1}
,"toggle":{"stop":1}
,"stop":{"script":1}
,"triggered":{"set":1}
,"[$$script_trigger":{"value":1,"=\u0022":1}
,"ipad":{"\u0022]":1}
,"=\u0022":{"\u0022]":1}
,"exit":{"script":1}
,"[text":{"result":1}
,"result":{"end":1}
,"find":{"matching":1}
,"matching":{"records":1}
,"[replace":{"invoices":1}
,"invoices":{":customer":1}
,"name]":{"go":1}
,"record\u002Frequest\u002Fpage":{"[first]":1}
,"[first]":{"sing":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
,"scripts":{"script":1}
,"selected":{"invoice":1}
,"ios":{"script":1}
,"trigger":{"entering":1}
,"entering":{"invoice":1}
}
;Search.control.loadWordPairs(pairs);
