var pairs =
{
"get":{"applicationarchitecture":1}
,"applicationarchitecture":{"returns":1,"none":1,"=\u0022":1}
,"returns":{"current":1,"i386":1}
,"current":{"application":1}
,"application":{"architecture":1}
,"architecture":{"get":1,"installs":1}
,"none":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1,"server":1,"cloud":1,"webdirect":1,"data":1,"go":1}
,"pro":{"14.0":1,"advanced":1}
,"14.0":{"returns":1}
,"i386":{"32-bit":1,"\u0022]":1}
,"32-bit":{"version":1}
,"version":{"filemaker":1,"plug-in":1}
,"advanced":{"x86_64":1,"filemaker":1}
,"x86_64":{"64-bit":1,"\u0022]":1}
,"64-bit":{"version":1,"arm-based":1}
,"server":{"filemaker":1}
,"cloud":{"filemaker":1}
,"webdirect":{"filemaker":1}
,"data":{"api":1}
,"api":{"custom":1}
,"custom":{"web":1}
,"web":{"publishing":1}
,"publishing":{"arm7":1}
,"arm7":{"filemaker":1}
,"go":{"running":1}
,"running":{"armv7-based":1,"armv7s-based":1,"64-bit":1}
,"armv7-based":{"device":1}
,"device":{"arm7s":1,"arm64":1,"detects":1}
,"arm7s":{"filemaker":1}
,"armv7s-based":{"device":1}
,"arm64":{"filemaker":1}
,"arm-based":{"device":1}
,"detects":{"application":1}
,"installs":{"version":1}
,"plug-in":{"if":1,"file":1}
,"if":{"[get":1}
,"[get":{"applicationarchitecture":1}
,"=\u0022":{"i386":1,"x86_64":1}
,"\u0022]":{"install":1}
,"install":{"plug-in":1}
,"file":{"[plugins":1}
,"[plugins":{":32bit]":1,":64bit]":1}
,":32bit]":{"else":1}
,"else":{"if":1}
,":64bit]":{"end":1}
,"end":{"if":1}
}
;Search.control.loadWordPairs(pairs);
