var pairs =
{
"ontrolling":{"layouts":1}
,"layouts":{"print":1}
,"print":{"printer":1,"records":1,"multi":1}
,"printer":{"use":1,"options":1}
,"use":{"printer":1}
,"options":{"choose":1,"reduce":1}
,"choose":{"margins":1,"all":1}
,"margins":{"layout":1}
,"layout":{"options":1,"print":1,"objects":1}
,"all":{"affect":1}
,"affect":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"prints":1}
,"prints":{"data":1}
,"data":{"yo":1}
,"yo":{"et":1}
,"et":{"up":1}
,"up":{"layout":1}
,"records":{"columns":1}
,"columns":{"print":1}
,"multi":{"olumn":1}
,"olumn":{"phone":1}
,"phone":{"directory":1}
,"directory":{"set":1}
,"set":{"sliding":1}
,"sliding":{"options":1}
,"reduce":{"blank":1}
,"blank":{"spaces":1}
,"spaces":{"printouts":1}
,"printouts":{"prevent":1}
,"prevent":{"layout":1}
,"objects":{"printing":1}
}
;Search.control.loadWordPairs(pairs);
