var pairs =
{
"etting":{"memory":1}
,"memory":{"preferences":1,"called":1,"tab":1}
,"preferences":{"filemaker":1,"macos":1,"preferences":1,"dialog":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"automatically":1,"saves":1,"enu":1,"start":1,"save":1}
,"automatically":{"records":1}
,"records":{"stored":1}
,"stored":{"temporarily":1}
,"temporarily":{"computer\u0027s":1}
,"computer\u0027s":{"ram":1}
,"ram":{"memory":1}
,"called":{"cache":1}
,"cache":{"size":1,"filemaker":1,"hard":1,"full":1,"contents":1,"disk":1}
,"size":{"cache":1,"mb":1}
,"saves":{"cache":1}
,"hard":{"disk":1}
,"disk":{"windows":1,"database":1,"interval":1,"by":1,"script":1}
,"windows":{"choose":1}
,"choose":{"edit":1,"filemaker":1,"time":1}
,"edit":{"menu":1}
,"menu":{"preferences":1}
,"macos":{"choose":1}
,"enu":{"preferences":1}
,"dialog":{"box":1}
,"box":{"memory":1}
,"tab":{"set":1}
,"set":{"options":1,"file":1}
,"options":{"want":1}
,"want":{"use":1}
,"use":{"improve":1}
,"improve":{"application":1}
,"application":{"performance":1}
,"performance":{"attempt":1}
,"attempt":{"set":1}
,"file":{"cache":1,"disk":1}
,"mb":{"enter":1}
,"enter":{"value":1}
,"value":{"take":1}
,"take":{"quit":1}
,"quit":{"filemaker":1}
,"start":{"save":1}
,"save":{"disk":1,"cache":1,"database":1}
,"database":{"file":1}
,"full":{"save":1}
,"contents":{"during":1,"minutes":1}
,"during":{"idle":1}
,"idle":{"time":1}
,"time":{"save":1,"interval":1}
,"interval":{"10":1,"list":1}
,"10":{"minutes":1}
,"minutes":{"15":1,"30":1,"hour":1,"choose":1}
,"15":{"minutes":1}
,"30":{"minutes":1}
,"hour":{"cache":1}
,"list":{"saving":1}
,"saving":{"less":1,"reduces":1}
,"less":{"battery-powered":1}
,"battery-powered":{"portable":1}
,"portable":{"computers":1}
,"computers":{"conserves":1}
,"conserves":{"power":1}
,"power":{"saving":1}
,"reduces":{"chance":1}
,"chance":{"data":1}
,"data":{"loss":1}
,"loss":{"system":1}
,"system":{"crash":1}
,"crash":{"ou":1}
,"ou":{"force":1}
,"force":{"filemaker":1}
,"by":{"running":1}
,"running":{"script":1}
,"script":{"flush":1,"step":1}
,"flush":{"cache":1}
}
;Search.control.loadWordPairs(pairs);
