var pairs =
{
"creating":{"charts":1,"quick":1,"editing":1}
,"charts":{"data":1,"filemaker":1,"use":1,"layout":1,"update":1,"display":1}
,"data":{"two":1,"charts":1,"remain":1,"comparison":1}
,"two":{"create":1}
,"create":{"charts":1,"quick":1,"chart":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"create":1,"sets":1,"charts":1}
,"quick":{"chart":1,"charts":1}
,"chart":{"browse":1,"based":1,"setup":1,"print":1,"save":1,"tool":1,"method":1,"new":1,"existing":1,"show":1,"bitmap":1}
,"browse":{"mode":1,"find":1}
,"mode":{"start":1,"create":1,"filemaker":1,"paste":1}
,"start":{"filemaker":1}
,"sets":{"up":1}
,"up":{"chart":1}
,"based":{"current":1}
,"current":{"state":1}
,"state":{"database":1}
,"database":{"use":1}
,"use":{"chart":1}
,"setup":{"dialog":1}
,"dialog":{"box":1}
,"box":{"modify":1}
,"modify":{"quick":1}
,"print":{"chart":1}
,"save":{"new":1}
,"new":{"layout":1}
,"layout":{"if":1,"mode":1,"add":1,"creating":1,"copy":1}
,"if":{"correct":1,"change":1}
,"correct":{"privileges":1}
,"privileges":{"creating":1}
,"tool":{"layout":1}
,"method":{"each":1}
,"each":{"setting":1}
,"setting":{"create":1}
,"add":{"chart":1}
,"existing":{"layout":1}
,"editing":{"charts":1}
,"update":{"dynamically":1,"data":1}
,"dynamically":{"data":1}
,"display":{"summary":1}
,"summary":{"data":1}
,"remain":{"accurate":1}
,"accurate":{"maintain":1}
,"maintain":{"required":1}
,"required":{"sort":1}
,"sort":{"order":1}
,"order":{"if":1,"chart":1}
,"change":{"sort":1}
,"show":{"data":1}
,"comparison":{"note":1}
,"note":{"copy":1}
,"copy":{"chart":1}
,"find":{"mode":1}
,"paste":{"layout":1}
,"bitmap":{"image":1}
,"image":{"update":1}
}
;Search.control.loadWordPairs(pairs);
