var pairs =
{
"custom-separated":{"values":1}
,"values":{"format":1,"files":1,"choose":1}
,"format":{"import":1,"convert":1}
,"import":{"convert":1}
,"convert":{"custom-separated":1,"files":1,"file":1}
,"files":{"character":1,"format":1,"converting":1}
,"character":{"separates":1}
,"separates":{"field":1}
,"field":{"values":1,"names":1}
,"choose":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"row":1}
,"row":{"data":1}
,"data":{"file":1}
,"file":{"field":1,"script":1}
,"names":{"all":1}
,"all":{"fields":1}
,"fields":{"text":1,"convert":1,"importing":1}
,"text":{"fields":1}
,"script":{"step":1}
,"step":{"choose":1}
,"importing":{"custom-separated":1}
,"converting":{"custom-separated":1}
}
;Search.control.loadWordPairs(pairs);
