var pairs =
{
"formatting":{"text":1,"data":1,"bar":1,"fields":1,"conflicts":1,"appearance":1,"stored":1,"layout":1,"applied":1,"existing":1,"change":1,"pasting":1,"field":1,"options":1,"visible":1}
,"text":{"text":1,"fields":1,"field":1,"vertical":1,"formats":1,"layout":1,"select":1,"browse":1,"ruler":1,"formatting":1,"automatically":1,"formatted":1,"format":1,"bold":1}
,"fields":{"layouts":1,"format":1,"text":1,"layout":1,"unformatted":1}
,"layouts":{"appears":1,"use":1}
,"appears":{"layout":1}
,"layout":{"maintain":1,"mode":1,"displays":1}
,"maintain":{"flexibility":1}
,"flexibility":{"formatting":1}
,"data":{"layouts":1,"formats":1,"browse":1,"layout":1,"formatted":1,"formatting":1,"paste":1}
,"use":{"layout":1,"browse":1,"font":1,"tabs":1,"ruler":1,"paragraph":1}
,"mode":{"apply":1,"reformat":1,"layout":1,"select":1,"choose":1,"use":1,"browse":1,"filemaker":1,"formatting":1,"takes":1,"add":1,"export":1,"format":1,"if":1,"field":1,"macos":1}
,"apply":{"primary":1,"bold":1}
,"primary":{"font":1}
,"font":{"paragraph":1,"use":1,"height":1}
,"paragraph":{"settings":1,"tabs":1,"appearance":1}
,"settings":{"field":1,"paragraph":1,"set":1,"tab":1,"change":1}
,"field":{"objects":1,"browse":1,"object":1,"text":1,"choose":1,"drag":1,"data":1,"layout":1,"field":1,"formatting":1,"active":1,"press":1}
,"objects":{"layouts":1,"layout":1}
,"browse":{"mode":1}
,"bold":{"italic":1,"print":1}
,"italic":{"emphasis":1,"highlighted":1}
,"emphasis":{"fields":1}
,"format":{"entire":1,"menu":1,"fields":1,"field":1,"existing":1,"choose":1,"characters":1,"year":1}
,"entire":{"contents":1}
,"contents":{"field":1}
,"reformat":{"field":1,"text":1}
,"object":{"layout":1,"browse":1,"format":1,"formatted":1}
,"select":{"text":1,"field":1,"existing":1}
,"choose":{"format":1,"style":1,"options":1,"unit":1,"tab":1,"align":1,"view":1,"edit":1}
,"menu":{"formatting":1,"line":1,"rulers":1,"ruler":1,"undo":1}
,"bar":{"choose":1,"layout":1}
,"style":{"style":1,"submenu":1,"shadows":1}
,"submenu":{"sideways":1}
,"sideways":{"orientation":1}
,"orientation":{"formatting":1}
,"vertical":{"writing":1}
,"writing":{"inspector":1}
,"inspector":{"appearance":1,"line":1,"choose":1}
,"appearance":{"appearance":1,"tab":1,"occurrence":1}
,"tab":{"sp":1,"inspector":1,"type":1,"character":1,"tab":1,"list":1,"ruler":1,"stops":1,"stop":1,"settings":1}
,"sp":{"ecify":1}
,"ecify":{"text":1}
,"formats":{"text":1,"layout":1}
,"line":{"spacing":1,"style":1}
,"spacing":{"settings":1,"buttons":1,"type":1,"tabs":1}
,"tabs":{"dialog":1,"layout":1,"appearance":1,"choose":1,"rulers":1}
,"dialog":{"boxes":1}
,"boxes":{"alignment":1,"layout":1}
,"alignment":{"spacing":1,"value":1,"character":1}
,"buttons":{"formatting":1}
,"options":{"paragraph":1,"special":1}
,"type":{"value":1,"type":1,"alignment":1,"character":1}
,"value":{"height":1,"position":1}
,"height":{"choose":1,"layout":1}
,"unit":{"measure":1}
,"measure":{"lines":1,"varies":1,"rulers":1}
,"lines":{"unit":1}
,"varies":{"font":1}
,"position":{"new":1,"fill":1}
,"new":{"decimal":1,"positions":1}
,"decimal":{"tabs":1}
,"align":{"type":1}
,"character":{"type":1,"periods":1,"fill":1,"change":1}
,"fill":{"space":1,"character":1,"line":1}
,"space":{"tab":1}
,"periods":{"name":1}
,"name":{"number":1}
,"number":{"phone":1,"date":1}
,"phone":{"directory":1}
,"directory":{"type":1}
,"change":{"tab":1,"settings":1,"custom":1,"pasted":1,"unit":1,"paragraphs":1}
,"list":{"change":1,"clear":1}
,"set":{"clear":1,"up":1,"styles":1}
,"clear":{"tab":1,"use":1}
,"ruler":{"format":1,"select":1,"margin":1,"drag":1,"move":1}
,"view":{"menu":1}
,"rulers":{"create":1,"sing":1,"grid":1}
,"create":{"text":1,"conflicting":1}
,"existing":{"text":1,"field":1}
,"drag":{"first-line":1,"ruler":1}
,"first-line":{"left":1,"indent":1}
,"left":{"margin":1}
,"margin":{"right":1,"marker":1,"markers":1}
,"right":{"margin":1}
,"marker":{"new":1,"left":1,"independently":1,"it\u2019s":1}
,"positions":{"text":1}
,"markers":{"indent":1,"delete":1}
,"indent":{"markers":1,"marker":1}
,"delete":{"tab":1}
,"move":{"first-line":1,"insertion":1}
,"independently":{"alt-drag":1}
,"alt-drag":{"windows":1}
,"windows":{"option-drag":1}
,"option-drag":{"macos":1}
,"macos":{"marker":1,"if":1}
,"it\u2019s":{"create":1}
,"conflicting":{"field":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"resolves":1}
,"resolves":{"text":1}
,"conflicts":{"format":1}
,"occurrence":{"field":1}
,"stored":{"data":1}
,"displays":{"field":1}
,"formatted":{"browse":1,"text":1,"entered":1}
,"takes":{"precedence":1}
,"precedence":{"data":1}
,"add":{"change":1}
,"custom":{"color":1}
,"color":{"setting":1}
,"setting":{"fill":1,"up":1}
,"shadows":{"padding":1}
,"padding":{"eliminate":1}
,"eliminate":{"formatting":1}
,"applied":{"browse":1}
,"export":{"re-import":1}
,"re-import":{"data":1}
,"paste":{"text":1}
,"unformatted":{"text":1}
,"automatically":{"acquires":1}
,"acquires":{"default":1}
,"default":{"formatting":1}
,"pasted":{"text":1}
,"edit":{"menu":1}
,"undo":{"formatting":1}
,"pasting":{"text":1}
,"characters":{"number":1}
,"date":{"time":1,"bold":1}
,"time":{"timestamp":1}
,"timestamp":{"fields":1}
,"year":{"date":1}
,"print":{"special":1}
,"special":{"formatting":1}
,"entered":{"option":1}
,"option":{"layout":1}
,"if":{"field":1,"set":1}
,"visible":{"browse":1}
,"active":{"ormatting":1}
,"ormatting":{"setting":1}
,"up":{"field":1,"tab":1}
,"stops":{"field":1}
,"press":{"option-tab":1}
,"option-tab":{"move":1}
,"insertion":{"point":1}
,"point":{"next":1}
,"next":{"tab":1}
,"stop":{"change":1}
,"sing":{"rulers":1}
,"grid":{"text":1}
,"highlighted":{"set":1}
,"styles":{"paragraph":1}
,"paragraphs":{"tabs":1}
}
;Search.control.loadWordPairs(pairs);
