var pairs =
{
"isabling":{"script":1}
,"script":{"step":1,"steps":1,"run":1,"disabled":1,"workspace":1,"select":1}
,"step":{"note":1}
,"note":{"feature":1}
,"feature":{"use":1}
,"use":{"advanced":1}
,"advanced":{"tools":1}
,"tools":{"general":1,"ou":1}
,"general":{"preference":1}
,"preference":{"selected":1}
,"selected":{"ad":1}
,"ad":{"vanced":1}
,"vanced":{"tools":1}
,"ou":{"disable":1}
,"disable":{"enable":1,"script":1,"edit":1}
,"enable":{"script":1}
,"steps":{"test":1,"skipped":1,"disable":1,"choose":1,"script":1}
,"test":{"portions":1}
,"portions":{"script":1}
,"run":{"script":1}
,"disabled":{"script":1}
,"skipped":{"ch":1}
,"ch":{"oose":1}
,"oose":{"scripts":1}
,"scripts":{"menu":1}
,"menu":{"script":1,"disable":1,"preferences":1}
,"workspace":{"uble-click":1,"choose":1,"preferences":1}
,"uble-click":{"cript":1}
,"cript":{"script":1,"steps":1}
,"select":{"cript":1}
,"choose":{"edit":1,"view":1}
,"edit":{"menu":1,"color":1}
,"color":{"coding":1}
,"coding":{"disabled":1}
,"view":{"menu":1}
,"preferences":{"syntax":1}
,"syntax":{"coloring":1}
,"coloring":{"tab":1}
,"tab":{"windows":1,"macos":1}
,"windows":{"choose":1}
,"macos":{"disable":1}
}
;Search.control.loadWordPairs(pairs);
