var pairs =
{
"hiragana":{"converts":1,"hiragana":1,"text":1,"japanese":1,"characters":1}
,"converts":{"katakana":1}
,"katakana":{"hankaku":1,"characters":1}
,"hankaku":{"zenkaku":1}
,"zenkaku":{"text":1}
,"text":{"hiragana":1,"text":1,"-any":1,"expression":1,"field":1,"filemaker":1,"string":1}
,"-any":{"text":1}
,"expression":{"text":1}
,"field":{"text":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"hiragana":1}
,"japanese":{"text":1}
,"string":{"katakana":1,"hiragana":1}
,"characters":{"returns":1}
,"returns":{"japanese":1}
}
;Search.control.loadWordPairs(pairs);
