var pairs =
{
"preventing":{"objects":1}
,"objects":{"printing":1,"layout":1,"want":1,"browse":1,"display":1,"gray":1}
,"printing":{"keep":1,"create":1,"nonprinting":1}
,"keep":{"objects":1}
,"layout":{"printing":1,"print":1,"read":1,"printed":1,"mode":1,"modes":1,"se":1}
,"create":{"button":1}
,"button":{"report":1}
,"report":{"layout":1,"place":1}
,"print":{"print":1,"report":1,"inspector":1,"layout":1}
,"place":{"instructions":1}
,"instructions":{"layout":1}
,"read":{"during":1}
,"during":{"data":1}
,"data":{"entry":1}
,"entry":{"printed":1}
,"printed":{"layout":1}
,"mode":{"select":1,"print":1,"choose":1}
,"select":{"object":1,"hide":1}
,"object":{"objects":1,"visibility":1,"set":1}
,"want":{"print":1}
,"inspector":{"osition":1}
,"osition":{"position":1}
,"position":{"tab":1}
,"tab":{"sliding":1}
,"sliding":{"&visibility":1,"options":1}
,"&visibility":{"object":1}
,"visibility":{"select":1}
,"hide":{"printing":1}
,"nonprinting":{"objects":1,"object":1}
,"browse":{"layout":1}
,"modes":{"preview":1}
,"preview":{"mode":1}
,"choose":{"view":1}
,"view":{"menu":1}
,"menu":{"show":1}
,"show":{"non-printing":1}
,"non-printing":{"objects":1}
,"display":{"nonprinting":1}
,"gray":{"border":1}
,"border":{"close":1}
,"close":{"up":1}
,"up":{"blank":1}
,"blank":{"space":1,"spaces":1}
,"space":{"by":1}
,"by":{"nonprinting":1}
,"set":{"sliding":1}
,"options":{"object":1}
,"se":{"removing":1}
,"removing":{"blank":1}
,"spaces":{"printouts":1}
,"printouts":{"keep":1}
}
;Search.control.loadWordPairs(pairs);
