var pairs =
{
"middlevalues":{"returns":1,"text":1,"plaid":1,"list":1}
,"returns":{"text":1,"middlevalues":1,"canvas":1}
,"text":{"numberofvalues":1,"starting":1,"startingvalue":1,"-any":1,"expression":1,"field":1,"filemaker":1,"function":1}
,"numberofvalues":{"text":1,"-any":1}
,"starting":{"startingvalue":1}
,"startingvalue":{"middlevalues":1,"numberofvalues":1,"-any":1,"function":1,"=1":1,"greater":1}
,"-any":{"text":1,"numeric":1}
,"expression":{"text":1,"field":1}
,"field":{"startingvalue":1,"number":1,"sophie":1}
,"numeric":{"expression":1}
,"number":{"numberofvalues":1,"text":1,"values":1}
,"filemaker":{"pro":1}
,"pro":{"7.0":1}
,"7.0":{"description":1}
,"description":{"list":1}
,"list":{"values":1,"return":1,"field":1}
,"values":{"valuecount":1,"text":1}
,"valuecount":{"function":1}
,"function":{"each":1,"evaluated":1,"returns":1}
,"each":{"returned":1}
,"returned":{"value":1}
,"value":{"nds":1}
,"nds":{"carriage":1}
,"carriage":{"return":1}
,"return":{"allowing":1,"ill":1}
,"allowing":{"lists":1}
,"lists":{"easily":1}
,"easily":{"concatenated":1}
,"concatenated":{"if":1}
,"if":{"startingvalue":1}
,"evaluated":{"if":1}
,"=1":{"if":1}
,"greater":{"number":1}
,"plaid":{"canvas":1}
,"canvas":{"suitcase":1,"middlevalues":1}
,"suitcase":{"returns":1}
,"ill":{"ohn":1}
,"ohn":{"hen":1}
,"hen":{"list":1}
,"sophie":{"bill":1}
,"bill":{"john":1}
}
;Search.control.loadWordPairs(pairs);
