var pairs =
{
"defining":{"changing":1,"fields":1}
,"changing":{"fields":1,"field":1}
,"fields":{"view":1,"change":1,"add":1,"define":1,"current":1,"etting":1,"creating":1,"defining":1,"new":1,"changing":1,"remove":1,"delete":1,"deleting":1}
,"view":{"browse":1,"table":1,"button":1}
,"browse":{"mode":1}
,"mode":{"table":1}
,"table":{"view":1}
,"button":{"layout":1}
,"layout":{"bar":1,"select":1,"preference":1,"preferences":1}
,"bar":{"create":1}
,"create":{"field":1,"fields":1}
,"field":{"column":1,"naming":1,"type":1,"choose":1,"field":1,"right-click":1,"options":1,"create":1,"define":1,"change":1,"new":1,"add":1,"remove":1,"removing":1,"delete":1}
,"column":{"heading":1}
,"heading":{"type":1,"field":1,"fields":1}
,"type":{"name":1,"right-click":1,"bout":1,"set":1}
,"name":{"field":1}
,"naming":{"fields":1}
,"change":{"field":1,"fields":1}
,"right-click":{"column":1}
,"choose":{"field":1}
,"bout":{"choosing":1}
,"choosing":{"field":1}
,"set":{"options":1}
,"options":{"field":1,"setting":1,"fields":1}
,"setting":{"options":1}
,"add":{"field":1,"newly":1,"fields":1}
,"define":{"automatically":1,"fields":1,"field":1}
,"automatically":{"placed":1}
,"placed":{"layout":1}
,"select":{"add":1}
,"newly":{"defined":1}
,"defined":{"fields":1}
,"current":{"layout":1}
,"preference":{"preferences":1}
,"preferences":{"dialog":1,"create":1}
,"dialog":{"box":1}
,"box":{"define":1}
,"etting":{"layout":1}
,"creating":{"fields":1}
,"new":{"field":1,"fields":1}
,"remove":{"fields":1,"field":1}
,"removing":{"fields":1}
,"delete":{"field":1,"fields":1}
,"deleting":{"fields":1}
}
;Search.control.loadWordPairs(pairs);
