var pairs =
{
"hoosing":{"evaluation":1}
,"evaluation":{"context":1}
,"context":{"calculation":1,"table":1,"want":1,"choice":1,"colorstable":1,"two":1,"shapessourcetable":1,"determines":1}
,"calculation":{"field":1,"source":1,"evaluate":1,"filemaker":1,"starting":1,"critical":1,"defined":1,"fields":1,"formula":1,"dialog":1,"calculation":1,"result":1}
,"field":{"context":1,"names":1,"formula":1,"returns":1,"defined":1}
,"table":{"relationships":1,"table":1,"occurrence":1,"name":1,"occurrences":1,"two":1,"calculation":1,"colorssourcetable":1,"shapessourcetable":1,"colorstable":1}
,"relationships":{"graph":1,"table":1,"first":1,"use":1}
,"graph":{"relationship":1,"context":1,"perspective":1,"field":1}
,"relationship":{"evaluated":1,"returns":1,"colorstable":1}
,"evaluated":{"define":1,"context":1}
,"define":{"calculation":1}
,"source":{"table":1,"tables":1}
,"occurrence":{"relationships":1,"each":1,"colorstable":1,"effects":1,"table":1,"group":1}
,"want":{"calculation":1}
,"evaluate":{"each":1,"calculation":1,"context":1}
,"each":{"context":1,"calculation":1,"relationship":1}
,"choice":{"represents":1}
,"represents":{"table":1,"association":1}
,"perspective":{"data":1}
,"data":{"choose":1}
,"choose":{"context":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"evaluate":1}
,"starting":{"table":1}
,"association":{"related":1}
,"related":{"tables":1,"two":1,"style":1,"weight":1,"records":1,"unrelated":1}
,"tables":{"fields":1,"named":1,"properties":1,"related":1,"relationships":1,"tog":1}
,"fields":{"choosing":1,"second":1,"colorstable":1,"table":1,"each":1,"unrelated":1}
,"choosing":{"evaluation":1}
,"critical":{"expect":1}
,"expect":{"database":1}
,"database":{"two":1}
,"two":{"source":1,"tables":1,"separate":1,"calculation":1,"records":1}
,"named":{"colorssourcetable":1}
,"colorssourcetable":{"shapessourcetable":1,"colorstable":1,"evaluated":1,"each":1,"values":1,"formula":1}
,"shapessourcetable":{"tables":1,"shapestable":1,"change":1,"records":1}
,"properties":{"source":1}
,"name":{"table":1}
,"occurrences":{"relationships":1}
,"names":{"colorssourcetable":1}
,"colorstable":{"colorstable":1,"color":1,"shapestable":1,"share":1,"table":1,"returns":1}
,"color":{"style":1}
,"style":{"number":1}
,"number":{"weight":1,"fields":1,"match":1}
,"weight":{"shapessourcetable":1,"price":1,"fields":1,"red":1,"match":1}
,"shapestable":{"shape":1,"related":1,"style":1,":price":1,"weight":1}
,"shape":{"style":1}
,"price":{"tables":1,"circle":1,"square":1}
,"separate":{"relationships":1}
,"first":{"colorstable":1}
,"second":{"colorstable":1,"calculation":1}
,"share":{"source":1}
,"defined":{"colorssourcetable":1}
,"effects":{"context":1}
,"formula":{"determine":1,"sum":1,"evaluation":1,"use":1}
,"determine":{"sum":1}
,"sum":{"prices":1,"shapestable":1}
,"prices":{"table":1}
,"change":{"evaluation":1}
,"records":{"values":1,"relationship":1,"shape":1}
,"values":{"shape":1,"color":1}
,"circle":{"100":1}
,"100":{"$2.00":1,"$6.00":1,"relationships":1}
,"$2.00":{"square":1}
,"square":{"100":1}
,"$6.00":{"triangle":1,"calculation":1}
,"triangle":{"200":1}
,"200":{"$9.00":1}
,"$9.00":{"single":1,"second":1}
,"single":{"record":1}
,"record":{"colorssourcetable":1}
,"red":{"100":1}
,"use":{"match":1,"global":1}
,"match":{"fields":1,"field":1}
,"returns":{"set":1,"two":1,"value":1}
,"set":{"related":1,"evaluate":1}
,":price":{"set":1}
,"value":{"$8.00":1,"$15.00":1}
,"$8.00":{"relationship":1}
,"$15.00":{"constructing":1}
,"constructing":{"calculation":1}
,"determines":{"tables":1}
,"unrelated":{"calculation":1,"tables":1}
,"dialog":{"box":1}
,"box":{"calculation":1}
,"global":{"fields":1}
,"tog":{"table":1}
,"group":{"context":1}
,"result":{"calculation":1}
}
;Search.control.loadWordPairs(pairs);
