var pairs =
{
"creating":{"accounts":1,"editing":1}
,"accounts":{"authenticate":1,"filemaker":1,"by":1,"contain":1,"follow":1,"situations":1,"authentication":1}
,"authenticate":{"via":1,"users":1,"oauth":1,"group":1,"accounts":1,"user":1}
,"via":{"oauth":1,"choose":1}
,"oauth":{"identity":1,"identify":1}
,"identity":{"provider":1,"providers":1}
,"provider":{"if":1,"accounts":1,"database":1,"choose":1,"group":1,"enter":1,"authenticate":1,"account":1,"set":1,"filemaker":1,"uthenticating":1}
,"if":{"you\u2019re":1,"manage":1,"supported":1,"oauth":1}
,"you\u2019re":{"hosting":1}
,"hosting":{"filemaker":1}
,"filemaker":{"pro":1,"server":1,"uthenticated":1}
,"pro":{"advanced":1}
,"advanced":{"iles":1,"database":1,"won\u2019t":1,"file":1}
,"iles":{"filemaker":1}
,"server":{"set":1,"authenticate":1,"account":1,"help":1}
,"set":{"up":1,"choose":1,"creating":1,"assigned":1,"clear":1,"authentication":1,"additional":1}
,"up":{"accounts":1,"oauth":1,"privilege":1,"multiple":1}
,"users":{"based":1,"oauth":1,"you\u2019ll":1,"multiple":1}
,"based":{"supported":1}
,"supported":{"oauth":1,"by":1}
,"providers":{"amazon":1,"allow":1}
,"amazon":{"google":1}
,"google":{"allows":1}
,"allows":{"control":1}
,"control":{"access":1}
,"access":{"databases":1,"additional":1,"file":1}
,"databases":{"third-party":1}
,"third-party":{"identity":1}
,"allow":{"access":1}
,"additional":{"security":1,"options":1}
,"security":{"measures":1,"if":1,"dialog":1,"settings":1}
,"measures":{"multifactor":1}
,"multifactor":{"authentication":1}
,"authentication":{"requires":1,"note":1,"order":1}
,"requires":{"method":1}
,"method":{"authentication":1}
,"note":{"set":1}
,"database":{"files":1}
,"files":{"hosted":1,"shared":1}
,"hosted":{"by":1}
,"by":{"filemaker":1,"oauth":1,"group":1}
,"shared":{"by":1}
,"won\u2019t":{"authenticate":1}
,"choose":{"file":1,"oauth":1,"authenticate":1,"create":1}
,"file":{"menu":1,"account":1,"oauth":1,"contain":1,"filemaker":1,"first":1,"creating":1}
,"menu":{"manage":1}
,"manage":{"security":1}
,"dialog":{"box":1}
,"box":{"displays":1}
,"displays":{"detailed":1}
,"detailed":{"security":1}
,"settings":{"use":1}
,"use":{"basic":1}
,"basic":{"setup":1}
,"setup":{"new":1}
,"new":{"account":1}
,"account":{"authenticate":1,"determines":1,"active":1,"inactive":1,"oauth":1,"name":1,"authentication":1,"access":1,"authenticates":1}
,"group":{"user":1,"individual":1,"name":1,"via":1,"members":1,"member":1}
,"user":{"choose":1,"credentials":1,"name":1,"file":1}
,"individual":{"user":1}
,"credentials":{"if":1}
,"enter":{"group":1,"group\u2019s":1}
,"name":{"object":1,"defined":1,"external":1,"two":1}
,"object":{"id":1}
,"id":{"user":1,"group":1,"privilege":1}
,"defined":{"by":1}
,"group\u2019s":{"azure":1}
,"azure":{"object":1}
,"privilege":{"set":1,"sets":1}
,"create":{"edit":1,"account":1}
,"edit":{"privilege":1}
,"editing":{"privilege":1,"accounts":1}
,"sets":{"privilege":1}
,"assigned":{"account":1}
,"determines":{"externally":1}
,"externally":{"authenticated":1}
,"authenticated":{"group":1}
,"members":{"file":1}
,"active":{"select":1}
,"select":{"checkbox":1}
,"checkbox":{"account":1,"it\u2019s":1}
,"inactive":{"set":1}
,"clear":{"checkbox":1}
,"it\u2019s":{"file":1,"set":1}
,"contain":{"multiple":1,"filemaker":1,"group":1}
,"multiple":{"accounts":1}
,"uthenticated":{"account":1}
,"external":{"server":1}
,"two":{"oauth":1}
,"identify":{"provider":1}
,"member":{"user":1}
,"first":{"matching":1,"ignored":1}
,"matching":{"account":1,"accounts":1}
,"order":{"matching":1,"accounts":1,"issue":1}
,"follow":{"first":1}
,"ignored":{"therefore":1}
,"therefore":{"it\u2019s":1}
,"situations":{"exist":1}
,"exist":{"wrong":1}
,"wrong":{"account":1}
,"issue":{"if":1}
,"you\u2019ll":{"set":1}
,"options":{"filemaker":1}
,"help":{"create":1}
,"authenticates":{"via":1}
,"uthenticating":{"users":1}
}
;Search.control.loadWordPairs(pairs);
