var pairs =
{
"char":{"returns":1,"number":1,"97":1,"98":1,"9800097":1,"228":1,"77600097":1}
,"returns":{"characters":1,"empty":1,"single":1,"string":1,"char":1,"ab":1,"case":1}
,"characters":{"unicode":1,"represented":1,"letter":1,"string":1}
,"unicode":{"code":1,"characters":1}
,"code":{"points":1,"point":1}
,"points":{"number":1,"text":1,"unicode":1,"character":1}
,"number":{"char":1,"number":1,"-a":1,"representing":1,"treated":1,"function":1,"99,999":1,"digits":1,"represents":1}
,"-a":{"decimal":1}
,"decimal":{"number":1}
,"representing":{"unicode":1}
,"text":{"filemaker":1,"if":1}
,"filemaker":{"pro":1}
,"pro":{"10.0":1}
,"10.0":{"each":1}
,"each":{"group":1,"five-digit":1}
,"group":{"digits":1,"returned":1}
,"digits":{"number":1,"function":1}
,"treated":{"unicode":1}
,"point":{"character":1,"multiple":1,"version":1}
,"character":{"each":1,"if":1,"represented":1,"single":1,"called":1,"composite":1,"char":1,"two":1}
,"five-digit":{"group":1}
,"returned":{"text":1}
,"if":{"number":1}
,"function":{"returns":1}
,"empty":{"string":1}
,"string":{"if":1,"characters":1,"char":1,"displayed":1}
,"99,999":{"function":1}
,"single":{"character":1,"code":1}
,"represented":{"by":1}
,"by":{"code":1,"single":1,"letter":1}
,"multiple":{"code":1}
,"letter":{"plus":1,"dieresis":1}
,"plus":{"dieresis":1}
,"dieresis":{"by":1,"character":1}
,"version":{"character":1}
,"called":{"precomposed":1}
,"precomposed":{"character":1}
,"composite":{"character":1}
,"97":{"returns":1}
,"98":{"returns":1}
,"9800097":{"returns":1}
,"ab":{"char":1}
,"228":{"returns":1}
,"77600097":{"returns":1}
,"case":{"number":1}
,"represents":{"two":1}
,"two":{"unicode":1,"characters":1}
,"displayed":{"single":1}
}
;Search.control.loadWordPairs(pairs);
