var pairs =
{
"textsize":{"font":1,"text":1,"plaid":1,"textfont":1}
,"font":{"size":1}
,"size":{"text":1,"expressed":1,"points":1}
,"text":{"fontsize":1,"-any":1,"expression":1,"number":1,"formatting":1,"textsize":1,"contained":1,"courier":1}
,"fontsize":{"textsize":1,"text":1,"-any":1}
,"-any":{"text":1,"font":1}
,"expression":{"text":1}
,"number":{"field":1,"filemaker":1,"textsize":1}
,"field":{"fontsize":1}
,"expressed":{"integer":1}
,"integer":{"text":1}
,"filemaker":{"pro":1}
,"pro":{"7.0":1}
,"7.0":{"font":1}
,"points":{"72":1,"inch":1}
,"72":{"points":1}
,"inch":{"text":1}
,"formatting":{"options":1}
,"options":{"lost":1}
,"lost":{"if":1}
,"if":{"data":1}
,"data":{"type":1}
,"type":{"returned":1}
,"returned":{"text":1}
,"plaid":{"18":1,"24":1}
,"18":{"returns":1,"point":1}
,"returns":{"word":1,"text":1}
,"word":{"plaid":1}
,"point":{"text":1}
,"24":{"returns":1,"point":1}
,"textfont":{"textcolor":1}
,"textcolor":{"mytable":1}
,"mytable":{":mytext":1}
,":mytext":{"rgb":1,"formatted":1}
,"rgb":{"125":1}
,"125":{"125":1,"courier":1}
,"courier":{"12":1,"font":1}
,"12":{"returns":1}
,"contained":{"mytable":1}
,"formatted":{"12-point":1}
,"12-point":{"green":1}
,"green":{"text":1}
}
;Search.control.loadWordPairs(pairs);
