var pairs =
{
"xecuting":{"sql":1}
,"sql":{"interact":1,"server":1,"statements":1,"script":1,"statement":1,"miscellaneous":1,"text":1}
,"interact":{"data":1}
,"data":{"sources":1,"filemaker":1,"source":1}
,"sources":{"via":1,"sql":1}
,"via":{"odbc":1}
,"odbc":{"addition":1,"interact":1,"data":1}
,"addition":{"importing":1}
,"importing":{"data":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"database":1,"atabase":1}
,"database":{"file":1,"table":1}
,"file":{"via":1,"execute":1,"choose":1}
,"server":{"oracle":1,"filemaker":1}
,"oracle":{"sql":1}
,"statements":{"xecute":1,"go":1,"add":1,"syntax":1,"data":1}
,"xecute":{"sql":1}
,"script":{"step":1,"button":1,"execute":1,"steps":1,"editing":1}
,"step":{"use":1,"script":1}
,"use":{"sql":1}
,"statement":{"supported":1,"choose":1,"data":1}
,"supported":{"by":1,"sql":1}
,"by":{"data":1}
,"source":{"insert":1,"select":1,"continue":1,"documentation":1,"via":1}
,"insert":{"update":1}
,"update":{"delete":1}
,"delete":{"use":1}
,"go":{"simply":1}
,"simply":{"importing":1}
,"atabase":{"file":1}
,"execute":{"sql":1}
,"add":{"records":1,"execute":1}
,"records":{"database":1}
,"table":{"sql":1}
,"choose":{"scripts":1,"calculated":1}
,"scripts":{"menu":1}
,"menu":{"cript":1,"button":1}
,"cript":{"workspace":1}
,"workspace":{"new":1}
,"new":{"script":1}
,"button":{"add":1,"odbc":1}
,"miscellaneous":{"category":1}
,"category":{"script":1}
,"steps":{"pane":1}
,"pane":{"script":1,"lick":1}
,"editing":{"pane":1}
,"lick":{"action":1}
,"action":{"menu":1}
,"select":{"data":1}
,"continue":{"user":1}
,"user":{"name":1}
,"name":{"password":1}
,"password":{"sql":1}
,"calculated":{"sql":1}
,"text":{"sql":1,"nter":1}
,"nter":{"sql":1}
,"documentation":{"listing":1}
,"listing":{"supported":1}
,"syntax":{"execute":1}
}
;Search.control.loadWordPairs(pairs);
