var pairs =
{
"hanging":{"touch":1}
,"touch":{"keyboard":1,"standard":1}
,"keyboard":{"type":1,"display":1,"system":1,"ate":1,"text":1,"number":1,"date":1,"url":1,"email":1,"numeric":1,"calculator-style":1,"ipad":1,"matches":1,"phone":1,"symbols":1}
,"type":{"set":1,"help":1,"choose":1,"numeric":1}
,"set":{"up":1}
,"up":{"keyboard":1}
,"display":{"field":1}
,"field":{"type":1,"inspector":1}
,"help":{"quickly":1}
,"quickly":{"enter":1}
,"enter":{"values":1}
,"values":{"layout":1}
,"layout":{"mode":1}
,"mode":{"select":1}
,"select":{"text":1,"touch":1}
,"text":{"number":1,"fields":1}
,"number":{"date":1,"punctuation":1,"ields":1,"fields":1,"keypad":1,"keyboard":1,"keyboar":1}
,"date":{"time":1}
,"time":{"timestamp":1}
,"timestamp":{"field":1,"ields":1,"fields":1}
,"inspector":{"data":1}
,"data":{"data":1,"tab":1,"type":1}
,"tab":{"behavior":1}
,"behavior":{"select":1}
,"choose":{"use":1}
,"use":{"keyboard":1}
,"system":{"default":1}
,"default":{"number":1,"keyboard":1,"data":1}
,"punctuation":{"keyboard":1,"standard":1}
,"ate":{"time":1}
,"ields":{"default":1}
,"numeric":{"10-key":1}
,"10-key":{"keyboard":1,"ustom":1}
,"fields":{"tandard":1,"number":1,"ascii":1}
,"tandard":{"eyboard":1}
,"eyboard":{"text":1}
,"ascii":{"standard":1}
,"standard":{"scii":1,"rl":1,"email":1,"ios":1,"umber":1}
,"scii":{"keyboard":1}
,"url":{"standard":1}
,"rl":{"keyboard":1}
,"email":{"standard":1,"keyboard":1}
,"ustom":{"10-key":1}
,"calculator-style":{"number":1}
,"keypad":{"iphone\u002Fipod":1}
,"iphone\u002Fipod":{"touch":1}
,"ios":{"number":1}
,"ipad":{"custom":1}
,"custom":{"number":1,"keyboard":1}
,"matches":{"iphone":1}
,"iphone":{"number":1}
,"keyboar":{"number":1}
,"umber":{"punctuation":1}
,"phone":{"custom":1,"numbers":1}
,"symbols":{"commonly":1}
,"commonly":{"phone":1}
,"numbers":{"change":1}
,"change":{"touch":1}
}
;Search.control.loadWordPairs(pairs);
