var pairs =
{
"sorting":{"records":1}
,"records":{"by":1,"report":1,"region":1,"menu":1,"move":1}
,"by":{"subsummary":1,"category":1,"field":1,"region":1,"total":1,"grouping":1}
,"subsummary":{"values":1,"report":1,"value":1}
,"values":{"properly":1,"lists":1,"total":1,"regions":1}
,"properly":{"display":1}
,"display":{"report":1,"break":1}
,"report":{"grouped":1,"data":1,"note":1,"subtotals":1,"by":1,"sorted":1,"creating":1}
,"grouped":{"data":1,"displayed":1}
,"data":{"subtotals":1,"sorted":1,"report":1,"logically":1,"automatically":1,"suppose":1,"by":1}
,"subtotals":{"subsummary":1,"sales":1,"sorted":1,"include":1,"creating":1,"table":1}
,"sorted":{"display":1,"by":1,"if":1}
,"break":{"fields":1}
,"fields":{"if":1}
,"if":{"subsummary":1,"create":1,"select":1,"data":1}
,"displayed":{"by":1}
,"category":{"produced":1}
,"produced":{"totals":1}
,"totals":{"subsummary":1,"sorted":1}
,"value":{"sort":1}
,"sort":{"reorder":1,"data":1,"status":1,"records":1,"order":1,"table":1}
,"reorder":{"data":1,"based":1}
,"logically":{"report":1}
,"note":{"if":1,"create":1}
,"create":{"leading":1,"report":1}
,"leading":{"trailing":1}
,"trailing":{"groups":1}
,"groups":{"table":1}
,"table":{"view":1}
,"view":{"data":1,"browse":1,"table":1,"button":1,"list":1}
,"automatically":{"sorted":1}
,"field":{"group":1,"regional":1,"use":1,"total":1,"region":1,"field":1,"dialog":1,"don\u2019t":1,"sort":1}
,"group":{"data":1}
,"suppose":{"create":1}
,"sales":{"by":1,"examples":1,"summary":1,"sorted":1,"descending":1,"report":1,"select":1}
,"region":{"sort":1,"records":1,"report":1,"ascending":1,"summary":1}
,"lists":{"data":1}
,"total":{"sales":1}
,"examples":{"total":1}
,"summary":{"field":1}
,"regional":{"totals":1}
,"ascending":{"order":1}
,"order":{"report":1,"create":1,"list":1,"descending":1,"sort":1,"summary":1}
,"regions":{"sorted":1}
,"descending":{"order":1}
,"include":{"field":1}
,"use":{"categorize":1}
,"categorize":{"records":1}
,"creating":{"report":1,"layout":1,"dynamic":1}
,"layout":{"note":1,"bar":1}
,"browse":{"mode":1}
,"mode":{"creating":1,"sort":1,"print":1}
,"dynamic":{"reports":1}
,"reports":{"table":1}
,"status":{"toolbar":1}
,"toolbar":{"choose":1}
,"choose":{"records":1}
,"menu":{"sort":1}
,"move":{"grouping":1}
,"grouping":{"field":1}
,"list":{"select":1,"view":1}
,"select":{"if":1,"reorder":1,"summary":1,"sort":1}
,"based":{"summary":1}
,"dialog":{"box":1}
,"box":{"select":1,"sort":1}
,"button":{"list":1,"layout":1}
,"bar":{"go":1}
,"go":{"preview":1}
,"preview":{"mode":1}
,"print":{"sorted":1}
,"don\u2019t":{"re-sort":1}
,"re-sort":{"add":1}
,"add":{"remove":1}
,"remove":{"summary":1}
}
;Search.control.loadWordPairs(pairs);
