var pairs =
{
"adding":{"viewing":1}
,"viewing":{"data":1}
,"data":{"view":1,"filemaker":1,"fields":1,"each":1,"field":1,"records":1,"record":1,"if":1}
,"view":{"data":1,"records":1,"add":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"atabase":1,"saves":1}
,"atabase":{"view":1}
,"records":{"database":1,"add":1,"field":1,"browse":1}
,"database":{"add":1,"file":1,"filemaker":1,"contain":1,"layouts":1}
,"add":{"duplicate":1,"edit":1,"change":1}
,"duplicate":{"delete":1}
,"delete":{"records":1}
,"edit":{"data":1}
,"fields":{"text":1,"fter":1,"start":1,"called":1}
,"text":{"field":1}
,"field":{"audio":1,"data":1,"labels":1}
,"audio":{"video":1}
,"video":{"files":1}
,"files":{"fields":1}
,"fter":{"create":1}
,"create":{"database":1}
,"file":{"define":1,"if":1}
,"define":{"tables":1}
,"tables":{"fields":1}
,"start":{"entering":1}
,"entering":{"data":1}
,"each":{"set":1}
,"set":{"fields":1}
,"called":{"record":1}
,"record":{"records":1,"haven\u2019t":1,"back":1}
,"labels":{"data":1}
,"browse":{"mode":1}
,"mode":{"view":1}
,"change":{"omit":1}
,"omit":{"delete":1}
,"saves":{"file":1}
,"if":{"you\u2019ve":1,"database":1}
,"you\u2019ve":{"entered":1}
,"entered":{"data":1}
,"haven\u2019t":{"saved":1}
,"saved":{"revert":1,"state":1}
,"revert":{"record":1}
,"back":{"saved":1}
,"state":{"database":1}
,"contain":{"multiple":1}
,"multiple":{"layouts":1}
,"layouts":{"display":1,"choose":1}
,"display":{"data":1}
,"choose":{"layout":1}
,"layout":{"pop-up":1}
,"pop-up":{"menu":1}
,"menu":{"records":1}
}
;Search.control.loadWordPairs(pairs);
