var pairs =
{
"onviewchange":{"performs":1}
,"performs":{"script":1}
,"script":{"fter":1,"step":1,"trigger":1,"runs":1}
,"fter":{"switch":1}
,"switch":{"views":1}
,"views":{"form":1}
,"form":{"list":1}
,"list":{"table":1}
,"table":{"manually":1}
,"manually":{"script":1}
,"step":{"event":1}
,"event":{"processed":1}
,"processed":{"browse":1}
,"browse":{"find":1}
,"find":{"preview":1}
,"preview":{"modes":1}
,"modes":{"none":1,"trigger":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"11.0":1}
,"11.0":{"script":1}
,"trigger":{"activate":1,"result":1}
,"activate":{"window":1}
,"window":{"action":1,"view":1}
,"action":{"window":1}
,"view":{"change":1}
,"change":{"script":1}
,"runs":{"modes":1}
}
;Search.control.loadWordPairs(pairs);
