var pairs =
{
"open":{"menu":1,"specific":1,"dialog":1,"edit":1,"favorites":1,"preferences":1,"file":1,"manage":1,"script":1,"find\u002Freplace":1,"help":1,"hosts":1,"filemaker":1,"upload":1}
,"menu":{"item":1,"use":1}
,"item":{"script":1}
,"script":{"steps":1,"workspace":1}
,"steps":{"open":1}
,"specific":{"filemaker":1}
,"filemaker":{"pro":1,"network":1}
,"pro":{"advanced":1}
,"advanced":{"dialog":1,"menus":1}
,"dialog":{"boxes":1,"box":1}
,"boxes":{"if":1}
,"if":{"had":1,"restricted":1}
,"had":{"chosen":1}
,"chosen":{"command":1}
,"command":{"menu":1}
,"use":{"script":1}
,"box":{"users":1,"open":1}
,"users":{"if":1}
,"restricted":{"access":1}
,"access":{"filemaker":1,"privileges":1}
,"menus":{"access":1}
,"privileges":{"script":1}
,"edit":{"saved":1}
,"saved":{"finds":1}
,"finds":{"dialog":1}
,"favorites":{"window":1}
,"window":{"open":1}
,"preferences":{"dialog":1}
,"file":{"options":1}
,"options":{"dialog":1}
,"manage":{"database":1,"external":1,"layouts":1,"themes":1,"value":1}
,"database":{"dialog":1}
,"external":{"data":1}
,"data":{"sources":1}
,"sources":{"dialog":1}
,"layouts":{"dialog":1}
,"workspace":{"open":1}
,"themes":{"dialog":1}
,"value":{"lists":1}
,"lists":{"dialog":1}
,"find\u002Freplace":{"dialog":1}
,"help":{"open":1}
,"hosts":{"ialog":1}
,"ialog":{"box":1,"bo":1}
,"network":{"settings":1}
,"settings":{"dialog":1}
,"upload":{"host":1}
,"host":{"ialog":1}
}
;Search.control.loadWordPairs(pairs);
