var pairs =
{
"ceiling":{"returns":1,"number":1,"1.25":1,"(-1.25":1}
,"returns":{"number":1,"ceiling":1,"-1":1}
,"number":{"rounded":1,"number":1,"-any":1,"filemaker":1}
,"rounded":{"up":1}
,"up":{"next":1}
,"next":{"integer":1}
,"integer":{"ceiling":1}
,"-any":{"numeric":1}
,"numeric":{"expression":1}
,"expression":{"field":1,"number":1}
,"field":{"numeric":1}
,"filemaker":{"pro":1}
,"pro":{"7.0":1}
,"7.0":{"ceiling":1}
,"1.25":{"returns":1}
,"(-1.25":{"returns":1}
}
;Search.control.loadWordPairs(pairs);
