var pairs =
{
"pen":{"ur":1,"url":1}
,"ur":{"llows":1}
,"llows":{"user":1}
,"user":{"open":1}
,"open":{"url":1}
,"url":{"dialog":1,"ptions":1,"allows":1,"create":1,"calculation":1,"supports":1,"types":1,"type":1,"starts":1,"if":1,"spaces":1,"[with":1,"script":1,"web":1}
,"dialog":{"specifies":1,"box":1,"http:\u002F\u002Fwww.filemaker.com\u002F\u0022]":1,"file:\u002F\u002Fc:\u002Fmy_file.txt":1,"mailto":1,"fmp:\u002F\u002Faccount:password@host\u002Fdatabase":1}
,"specifies":{"display":1}
,"display":{"pen":1}
,"ptions":{"dialog":1}
,"box":{"script":1}
,"script":{"step":1,"editing":1}
,"step":{"performed":1,"visible":1}
,"performed":{"url":1}
,"allows":{"type":1}
,"type":{"url":1,"if":1}
,"create":{"url":1}
,"calculation":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1,"homepage":1}
,"pro":{"6.0":1,"advanced":1}
,"6.0":{"earlier":1}
,"earlier":{"open":1}
,"supports":{"http":1}
,"http":{"https":1,"filemaker":1}
,"https":{"ldap":1}
,"ldap":{"ldaps":1}
,"ldaps":{"ftp":1}
,"ftp":{"file":1}
,"file":{"mailto":1,"my_file.txt":1,"running":1,"resides":1}
,"mailto":{"url":1,"&customers":1}
,"types":{"application":1}
,"application":{"registered":1,"new":1}
,"registered":{"operating":1}
,"operating":{"system":1}
,"system":{"each":1,"open":1}
,"each":{"url":1}
,"if":{"url":1}
,"starts":{"http":1}
,"advanced":{"user\u0027s":1,"file":1,"account":1,"filename":1}
,"user\u0027s":{"web":1,"hard":1}
,"web":{"browser":1,"address":1}
,"browser":{"processes":1,"displays":1}
,"processes":{"url":1}
,"spaces":{"special":1}
,"special":{"characters":1}
,"characters":{"replace":1,"encoded":1}
,"replace":{"characters":1,"\u0022@\u0022":1}
,"encoded":{"values":1}
,"values":{"required":1}
,"required":{"valid":1}
,"valid":{"urls":1}
,"urls":{"replace":1,"field":1}
,"\u0022@\u0022":{"40":1}
,"40":{"note":1}
,"note":{"filemaker":1}
,"webdirect":{"support":1}
,"support":{"file:\u002F\u002Fprotocol":1}
,"file:\u002F\u002Fprotocol":{"user\u0027s":1}
,"displays":{"filemaker":1}
,"homepage":{"open":1}
,"[with":{"dialog":1}
,"http:\u002F\u002Fwww.filemaker.com\u002F\u0022]":{"windows":1}
,"windows":{"notepad":1}
,"notepad":{"file":1}
,"my_file.txt":{"root":1}
,"root":{"level":1}
,"level":{"user\u0027s":1}
,"hard":{"disk":1}
,"disk":{"open":1}
,"file:\u002F\u002Fc:\u002Fmy_file.txt":{"\u0022]":1}
,"\u0022]":{"launches":1,"account":1}
,"launches":{"default":1}
,"default":{"email":1}
,"email":{"application":1,"value":1,"field":1}
,"new":{"email":1}
,"value":{"email":1}
,"field":{"address":1,"automating":1}
,"address":{"message":1,"ipv6":1,"machine":1,"urls":1}
,"message":{"open":1}
,"&customers":{":email]":1}
,":email]":{"shared":1}
,"shared":{"filemaker":1}
,"running":{"system":1}
,"fmp:\u002F\u002Faccount:password@host\u002Fdatabase":{"\u0022]":1}
,"account":{"filemaker":1,"name":1,"password":1}
,"name":{"password":1}
,"password":{"account":1,"host":1,"entered":1}
,"host":{"dns":1}
,"dns":{"entry":1}
,"entry":{"ipv4":1}
,"ipv4":{"address":1}
,"ipv6":{"address":1}
,"machine":{"file":1}
,"resides":{"database":1}
,"database":{"filemaker":1}
,"filename":{"account":1}
,"entered":{"open":1}
,"visible":{"users":1}
,"users":{"script":1}
,"editing":{"access":1}
,"access":{"privileges":1}
,"privileges":{"therefore":1}
,"therefore":{"secure":1}
,"secure":{"hyperlink":1}
,"hyperlink":{"hyperlinks":1}
,"hyperlinks":{"url":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
