var pairs =
{
"uniquevalues":{"returns":1,"values":1,"34":1,"product":1}
,"returns":{"unique":1,"datatype":1,"uniquevalues":1}
,"unique":{"values":1}
,"values":{"list":1,"datatype":1,"-any":1,"separated":1,"locale":1,"parameters":1,"valuecount":1,"based":1}
,"list":{"based":1,"values":1}
,"based":{"data":1,"unicode":1,"default":1}
,"data":{"type":1,"values":1,"sorted":1}
,"type":{"locale":1,"data":1,"text":1}
,"locale":{"uniquevalues":1,"values":1,"-the":1,"data":1,"parameters":1,"parameter":1,"english":1}
,"datatype":{"locale":1,"-a":1}
,"-any":{"text":1}
,"text":{"expression":1,"filemaker":1,"file":1}
,"expression":{"field":1}
,"field":{"that\u2019s":1,"red":1}
,"that\u2019s":{"list":1}
,"separated":{"by":1}
,"by":{"carriage":1}
,"carriage":{"returns":1,"return":1}
,"-a":{"number":1}
,"number":{"specifies":1}
,"specifies":{"type":1}
,"-the":{"name":1}
,"name":{"locale":1}
,"parameters":{"braces":1,"sortvalues":1}
,"braces":{"optional":1}
,"optional":{"text":1}
,"filemaker":{"pro":1}
,"pro":{"16.0":1}
,"16.0":{"description":1}
,"description":{"list":1}
,"valuecount":{"function":1}
,"function":{"each":1,"except":1,"determines":1,"distinguish":1,"supported":1}
,"each":{"returned":1}
,"returned":{"value":1}
,"value":{"carriage":1}
,"return":{"allowing":1,"600":1}
,"allowing":{"lists":1}
,"lists":{"easily":1}
,"easily":{"concatenated":1}
,"concatenated":{"datatype":1}
,"sortvalues":{"function":1}
,"except":{"affect":1}
,"affect":{"function":1}
,"determines":{"uniqueness":1}
,"uniqueness":{"data":1,"determined":1}
,"sorted":{"uniqueness":1}
,"determined":{"manner":1}
,"manner":{"indexing":1}
,"indexing":{"hoosing":1,"sorting":1}
,"hoosing":{"language":1}
,"language":{"indexing":1}
,"sorting":{"if":1}
,"if":{"set":1}
,"set":{"locale":1}
,"parameter":{"unicode_raw":1}
,"unicode_raw":{"function":1}
,"distinguish":{"values":1}
,"unicode":{"numeric":1}
,"numeric":{"encoding":1}
,"encoding":{"differentiates":1}
,"differentiates":{"characters":1}
,"characters":{"case":1}
,"case":{"diacritical":1}
,"diacritical":{"marks":1}
,"marks":{"function":1}
,"supported":{"runtime":1}
,"runtime":{"solutions":1}
,"solutions":{"returns":1}
,"34":{"600":1}
,"600":{"18":1,"18.0":1}
,"18":{"600":1,"uniquevalues":1}
,"18.0":{"return":1}
,"product":{":colors":1}
,":colors":{"removes":1,"field":1}
,"removes":{"duplicates":1}
,"duplicates":{"based":1}
,"default":{"data":1}
,"file":{"locale":1}
,"english":{"red":1}
,"red":{"green":1,"yellow":1}
,"green":{"yellow":1,"red":1}
,"yellow":{"product":1}
}
;Search.control.loadWordPairs(pairs);
