var pairs =
{
"textfontremove":{"removes":1,"text":1,"arial":1}
,"removes":{"all":1}
,"all":{"fonts":1,"text":1}
,"fonts":{"fonttoremove":1}
,"fonttoremove":{"text":1,"-any":1,"font":1}
,"text":{"textfontremove":1,"fonttoremove":1,"-any":1,"expression":1,"field":1,"parameters":1,"filemaker":1,"default":1,"displays":1,"displayed":1,"formatting":1,"courier":1,"returns":1,"arial":1}
,"-any":{"text":1,"font":1}
,"expression":{"text":1}
,"field":{"fonttoremove":1,"if":1,"font":1,"type":1}
,"font":{"name":1,"all":1,"set":1,"by":1,"removed":1,"portions":1,"spellings":1,"names":1,"textfontremove":1}
,"name":{"expressed":1}
,"expressed":{"text":1}
,"parameters":{"braces":1}
,"braces":{"optional":1}
,"optional":{"text":1}
,"filemaker":{"pro":1}
,"pro":{"8.0":1}
,"8.0":{"use":1}
,"use":{"function":1}
,"function":{"revert":1}
,"revert":{"text":1}
,"default":{"field":1,"font":1}
,"if":{"don\u2019t":1,"field":1}
,"don\u2019t":{"font":1}
,"displays":{"default":1}
,"set":{"layout":1}
,"layout":{"mode":1}
,"mode":{"field":1}
,"by":{"fonttoremove":1}
,"removed":{"portion":1,"arial":1}
,"portion":{"text":1}
,"displayed":{"font":1,"field\u0027s":1,"field\u2019s":1}
,"portions":{"text":1}
,"field\u0027s":{"default":1}
,"spellings":{"font":1}
,"names":{"correct":1}
,"correct":{"text":1}
,"formatting":{"options":1}
,"options":{"lost":1}
,"lost":{"if":1}
,"type":{"returned":1}
,"returned":{"text":1}
,"arial":{"text":1,"returns":1,"font":1}
,"courier":{"text":1}
,"returns":{"arial":1}
,"field\u2019s":{"default":1}
}
;Search.control.loadWordPairs(pairs);
