var pairs =
{
"eordering":{"excluding":1}
,"excluding":{"layouts":1}
,"layouts":{"layout":1,"folders":1,"prevent":1,"subfolders":1}
,"layout":{"pop-up":1,"mode":1,"appearing":1,"order":1,"want":1,"folder":1,"menus":1}
,"pop-up":{"menu":1}
,"menu":{"layout":1,"add":1,"choose":1,"change":1,"dr":1,"create":1,"se":1,"browse":1,"excluded":1}
,"mode":{"change":1,"all":1}
,"change":{"order":1,"layout":1}
,"order":{"layouts":1,"reorder":1}
,"folders":{"listed":1,"layout":1,"separator":1}
,"listed":{"layout":1}
,"add":{"separator":1}
,"separator":{"lines":1,"line":1,"arrow":1,"include":1}
,"lines":{"group":1,"layout":1}
,"group":{"layouts":1}
,"prevent":{"layout":1}
,"appearing":{"layout":1}
,"choose":{"manage":1,"separator":1}
,"manage":{"layouts":1}
,"reorder":{"folders":1}
,"dr":{"ag":1}
,"ag":{"ayout":1}
,"ayout":{"folder":1}
,"folder":{"up":1,"all":1,"folder":1,"appears":1,"name":1}
,"up":{"if":1}
,"if":{"you\u2019re":1}
,"you\u2019re":{"moving":1}
,"moving":{"folder":1}
,"all":{"layouts":1,"items":1}
,"subfolders":{"move":1}
,"move":{"folder":1}
,"appears":{"submenu":1,"next":1}
,"submenu":{"name":1}
,"name":{"layout":1,"separator":1,"each":1}
,"create":{"separator":1}
,"line":{"grouping":1,"include":1}
,"grouping":{"layouts":1}
,"se":{"lect":1}
,"lect":{"layout":1,"checkbox":1}
,"want":{"separator":1}
,"arrow":{"next":1}
,"next":{"new":1,"layout":1,"name":1}
,"new":{"choose":1}
,"include":{"exclude":1,"item":1,"layout":1}
,"exclude":{"layouts":1,"item":1}
,"browse":{"find":1}
,"find":{"preview":1}
,"preview":{"modes":1}
,"modes":{"note":1}
,"note":{"layout":1}
,"items":{"displayed":1}
,"displayed":{"layout":1}
,"excluded":{"se":1}
,"checkbox":{"next":1}
,"item":{"select":1,"clear":1,"included":1}
,"select":{"include":1}
,"menus":{"exclude":1}
,"clear":{"option":1}
,"option":{"check":1}
,"check":{"mark":1}
,"mark":{"appears":1}
,"each":{"item":1}
,"included":{"layout":1}
}
;Search.control.loadWordPairs(pairs);
