var pairs =
{
"changing":{"popover":1}
,"popover":{"settings":1,"button":1,"closed":1,"if":1,"open":1,"layout":1,"left":1,"right":1,"new":1,"type":1,"hiding":1,"assign":1,"set":1}
,"settings":{"if":1}
,"if":{"popover":1,"title":1,"want":1}
,"button":{"setup":1,"select":1,"choose":1,"right":1,"popover":1,"place":1,"nd":1}
,"setup":{"dialog":1,"change":1}
,"dialog":{"box":1}
,"box":{"open":1,"show":1}
,"open":{"layout":1,"select":1,"exit":1}
,"layout":{"mode":1,"left":1}
,"mode":{"if":1}
,"closed":{"double-click":1}
,"double-click":{"popover":1}
,"select":{"popover":1,"nd":1,"clear":1}
,"choose":{"format":1,"script":1}
,"format":{"menu":1}
,"menu":{"display":1,"popover":1}
,"display":{"popover":1}
,"nd":{"choose":1,"define":1}
,"change":{"direction":1,"title":1,"position":1}
,"direction":{"popover":1,"change":1}
,"left":{"popover":1,"button":1}
,"right":{"popover":1,"button":1}
,"place":{"arrow":1}
,"arrow":{"pointer":1}
,"pointer":{"popover\u2019s":1}
,"popover\u2019s":{"title":1}
,"title":{"bar":1,"popover":1,"double":1,"based":1,"select":1}
,"bar":{"if":1,"hidden":1,"title":1,"don\u2019t":1,"change":1}
,"hidden":{"drag":1}
,"drag":{"popover":1}
,"new":{"direction":1}
,"type":{"title":1}
,"double":{"quotation":1}
,"quotation":{"marks":1}
,"marks":{"title":1}
,"based":{"calculation":1}
,"calculation":{"button":1,"calculation":1,"dialog":1}
,"define":{"calculation":1}
,"show":{"hi":1,"title":1}
,"hi":{"de":1}
,"de":{"title":1}
,"clear":{"show":1}
,"don\u2019t":{"scroll":1}
,"scroll":{"use":1,"popover":1}
,"use":{"hold":1}
,"hold":{"objects":1}
,"objects":{"stay":1,"popover":1}
,"stay":{"visible":1}
,"visible":{"users":1}
,"users":{"scroll":1}
,"hiding":{"title":1}
,"position":{"objects":1}
,"assign":{"script":1}
,"script":{"triggers":1,"run":1}
,"triggers":{"popover":1,"choose":1,"setting":1,"automating":1}
,"want":{"script":1}
,"run":{"open":1}
,"exit":{"popover":1}
,"set":{"script":1}
,"setting":{"up":1}
,"up":{"script":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
