var pairs =
{
"ate":{"fields":1}
,"fields":{"use":1,"store":1,"separators":1,"order":1,"new":1,"adding":1,"add":1}
,"use":{"date":1,"current":1,"four-digit":1}
,"date":{"fields":1,"parts":1,"time":1,"formatting":1,"by":1,"formula":1,"week":1,"field":1,"get":1,"arithmetic":1,"calculations":1}
,"store":{"dates":1}
,"dates":{"sort":1,"calculation":1,"filemaker":1,"entered":1,"two-digit":1,"number":1,"date":1}
,"sort":{"search":1}
,"search":{"dates":1}
,"calculation":{"formulas":1,"field":1}
,"formulas":{"summary":1}
,"summary":{"fields":1}
,"separators":{"date":1}
,"order":{"date":1}
,"parts":{"depend":1}
,"depend":{"system":1}
,"system":{"formats":1,"format":1}
,"formats":{"set":1,"date":1}
,"set":{"file":1}
,"file":{"display":1}
,"display":{"format":1}
,"format":{"field":1,"date":1,"phone":1}
,"field":{"changing":1,"july":1,"validation":1,"result":1,"datestarted":1,"adding":1,"date":1}
,"changing":{"display":1}
,"july":{"2019":1}
,"2019":{"7\u002F7\u002F2019":1}
,"7\u002F7\u002F2019":{"formats":1}
,"time":{"timestamp":1}
,"timestamp":{"fields":1}
,"new":{"files":1}
,"files":{"clones":1,"use":1}
,"clones":{"existing":1}
,"existing":{"files":1}
,"current":{"operating":1}
,"operating":{"system":1}
,"formatting":{"avoid":1}
,"avoid":{"confusion":1}
,"confusion":{"dates":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"use":1,"stores":1}
,"four-digit":{"years":1}
,"years":{"sure":1,"defining":1,"handled":1,"filemaker":1}
,"sure":{"dates":1}
,"entered":{"four-digit":1}
,"defining":{"field":1}
,"validation":{"ates":1}
,"ates":{"two-digit":1}
,"two-digit":{"years":1}
,"handled":{"entering":1}
,"entering":{"dates":1}
,"stores":{"dates":1}
,"number":{"days":1,"phone":1,"format":1}
,"days":{"january":1,"calculation":1,"dateended":1}
,"january":{"0001":1}
,"0001":{"therefore":1}
,"therefore":{"calculate":1}
,"calculate":{"dates":1}
,"by":{"subtracting":1}
,"subtracting":{"adding":1}
,"adding":{"number":1,"fields":1,"field":1}
,"result":{"date":1}
,"formula":{"calculates":1}
,"calculates":{"date":1}
,"week":{"value":1}
,"value":{"datestarted":1}
,"datestarted":{"date":1,"subtract":1}
,"subtract":{"date":1}
,"get":{"number":1}
,"dateended":{"-datestarte":1}
,"-datestarte":{"zip":1}
,"zip":{"code":1,"codes":1}
,"code":{"zip":1}
,"codes":{"phone":1}
,"phone":{"number":1,"numbers":1}
,"numbers":{"format":1,"add":1}
,"add":{"fields":1,"field":1}
,"arithmetic":{"mathematical":1}
,"mathematical":{"operations":1}
,"operations":{"dates":1}
}
;Search.control.loadWordPairs(pairs);
