var pairs =
{
"pen":{"edit":1}
,"edit":{"saved":1}
,"saved":{"finds":1,"find":1}
,"finds":{"pens":1,"dialog":1,"end":1}
,"pens":{"edit":1}
,"dialog":{"box":1,"[\u0022":1}
,"box":{"none":1,"users":1,"if":1,"show":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"10.0":1,"advanced":1}
,"10.0":{"use":1}
,"use":{"script":1}
,"script":{"step":1}
,"step":{"open":1}
,"open":{"edit":1}
,"users":{"if":1}
,"if":{"restricted":1,"user":1,"[get":1,"managing":1}
,"restricted":{"access":1}
,"access":{"filemaker":1}
,"advanced":{"menus":1}
,"menus":{"displays":1}
,"displays":{"custom":1}
,"custom":{"dialog":1}
,"user":{"open":1}
,"show":{"custom":1}
,"[\u0022":{"want":1}
,"want":{"change":1}
,"change":{"saved":1}
,"find":{"\u0022]":1,"requests":1}
,"\u0022]":{"if":1}
,"[get":{"lastmessagechoice":1}
,"lastmessagechoice":{"=1]":1}
,"=1]":{"open":1}
,"end":{"if":1}
,"managing":{"saved":1}
,"requests":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
