var pairs =
{
"ng":{"external":1}
,"external":{"data":1,"table":1}
,"data":{"sources":1,"source":1}
,"sources":{"you\u2019ve":1,"odbc":1,"access":1,"define":1,"set":1}
,"you\u2019ve":{"data":1}
,"source":{"options":1,"connect":1,"name":1,"add":1}
,"options":{"ilemaker":1}
,"ilemaker":{"data":1}
,"odbc":{"data":1}
,"access":{"ilemaker":1,"odbc":1}
,"define":{"reference":1}
,"reference":{"file":1}
,"file":{"editing":1}
,"editing":{"ilemaker":1}
,"set":{"up":1}
,"up":{"driver":1}
,"driver":{"data":1}
,"connect":{"data":1}
,"name":{"dsn":1}
,"dsn":{"identify":1}
,"identify":{"tables":1}
,"tables":{"want":1}
,"want":{"th":1}
,"th":{"data":1}
,"add":{"external":1}
,"table":{"relationships":1}
,"relationships":{"graph":1}
,"graph":{"diting":1}
,"diting":{"odbc":1}
}
;Search.control.loadWordPairs(pairs);
