var pairs =
{
"efining":{"automatic":1,"updating":1}
,"automatic":{"data":1}
,"data":{"entry":1,"text":1,"select":1,"type":1,"enter":1,"field":1}
,"entry":{"save":1,"clear":1,"alternatively":1,"setting":1,"if":1,"start":1}
,"save":{"time":1}
,"time":{"ensure":1,"container":1,"timestamp":1}
,"ensure":{"accuracy":1}
,"accuracy":{"set":1,"during":1,"data":1}
,"set":{"options":1,"enter":1}
,"options":{"automatically":1,"double-click":1,"field":1,"automatic":1}
,"automatically":{"enter":1,"updated":1}
,"enter":{"data":1,"current":1,"record":1,"name":1,"account":1,"value":1,"result":1,"calculation":1,"auto":1}
,"text":{"number":1,"fields":1}
,"number":{"date":1,"field":1,"generate":1,"starting":1,"set":1}
,"date":{"time":1,"ime":1,"im":1}
,"container":{"fields":1,"field":1}
,"fields":{"filemaker":1,"tab":1,"define":1,"dialog":1,"help":1,"destination":1,"empty":1,"referenced":1,"value":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"enter":1,"enters":1}
,"current":{"user\u0027s":1}
,"user\u0027s":{"name":1}
,"name":{"field":1,"options":1,"person":1,"list":1,"creates":1,"modifies":1,"modification":1,"selected":1,"general":1}
,"field":{"choose":1,"list":1,"name":1,"dialog":1,"enter":1,"each":1,"last":1,"note":1,"if":1,"related":1,"auto-complete":1,"value":1,"empty":1,"define":1,"auto":1}
,"choose":{"file":1,"date":1,"name":1,"account":1,"creation":1,"commit":1}
,"file":{"menu":1}
,"menu":{"manage":1}
,"manage":{"database":1}
,"database":{"fields":1,"table":1}
,"tab":{"if":1,"select":1,"preferences":1}
,"if":{"database":1,"prevent":1,"creation":1,"select":1,"prohibit":1,"all":1,"option":1}
,"table":{"select":1,"table":1,"list":1,"option":1}
,"select":{"table":1,"text":1,"options":1,"creation":1,"modification":1,"serial":1,"value":1,"data":1,"calculated":1,"replace":1,"looked-up":1,"prohibit":1,"evaluate":1}
,"list":{"select":1,"existing":1,"enter":1,"assign":1}
,"existing":{"fields":1,"value":1}
,"define":{"new":1,"lookup":1,"value":1,"calculation":1}
,"new":{"options":1}
,"double-click":{"field":1}
,"dialog":{"box":1}
,"box":{"auto-enter":1,"select":1,"if":1,"value":1}
,"auto-enter":{"tab":1,"calculations":1,"calculation":1,"calculated":1}
,"record":{"creation":1,"select":1,"modification":1,"option":1,"performed":1,"accessed":1,"referenced":1,"all":1}
,"creation":{"date":1,"choose":1,"generate":1,"name":1}
,"ime":{"timestamp":1}
,"timestamp":{"select":1,"list":1,"rom":1}
,"person":{"creates":1,"modifies":1}
,"creates":{"record":1}
,"account":{"name":1}
,"modification":{"date":1,"choose":1,"value":1,"name":1}
,"im":{"timestamp":1}
,"rom":{"list":1}
,"modifies":{"record":1}
,"assign":{"serialized":1}
,"serialized":{"number":1}
,"each":{"record":1}
,"serial":{"number":1,"numbers":1}
,"generate":{"choose":1,"serial":1}
,"numbers":{"records":1}
,"records":{"created":1,"committed":1}
,"created":{"generate":1}
,"commit":{"generate":1}
,"committed":{"next":1}
,"next":{"value":1}
,"value":{"type":1,"100":1,"field":1,"last":1,"enter":1,"copied":1,"define":1,"defined":1,"automatic":1,"lists":1,"edit":1,"browse":1,"selected":1,"calculated":1,"auto-enter":1,"that\u2019s":1}
,"type":{"starting":1,"increment":1,"up":1}
,"starting":{"value":1,"number":1}
,"100":{"type":1}
,"increment":{"increment":1,"by":1}
,"by":{"enter":1,"calculation":1,"entering":1}
,"last":{"active":1,"visited":1,"record":1}
,"active":{"record":1}
,"visited":{"record":1}
,"option":{"refers":1,"set":1,"text":1,"deselecte":1}
,"refers":{"last":1}
,"performed":{"activity":1}
,"activity":{"clicking":1}
,"clicking":{"field":1}
,"note":{"value":1}
,"accessed":{"table":1}
,"up":{"255":1,"field":1}
,"255":{"characters":1}
,"characters":{"enter":1}
,"result":{"calculation":1}
,"calculation":{"select":1,"defining":1,"fields":1,"dialog":1,"empty":1,"self-modifying":1,"field":1}
,"calculated":{"value":1,"create":1,"referenced":1}
,"defining":{"calculation":1}
,"replace":{"existing":1}
,"prevent":{"overwriting":1}
,"overwriting":{"data":1}
,"copied":{"field":1}
,"related":{"record":1}
,"looked-up":{"value":1}
,"lookup":{"efining":1}
,"updating":{"lookups":1}
,"lookups":{"prohibit":1}
,"prohibit":{"user":1,"modification":1}
,"user":{"modifying":1,"name":1}
,"modifying":{"value":1}
,"defined":{"auto-entered":1}
,"auto-entered":{"select":1}
,"clear":{"all":1}
,"all":{"selected":1,"referenced":1,"fields":1}
,"selected":{"checkboxes":1,"filemaker":1,"value":1}
,"checkboxes":{"define":1}
,"lists":{"save":1}
,"during":{"data":1}
,"alternatively":{"auto-complete":1}
,"auto-complete":{"option":1,"during":1}
,"help":{"ensure":1}
,"setting":{"up":1}
,"enters":{"user":1}
,"general":{"tab":1}
,"preferences":{"dialog":1}
,"edit":{"field":1}
,"browse":{"mode":1}
,"mode":{"if":1}
,"create":{"record":1}
,"referenced":{"fields":1,"by":1}
,"destination":{"field":1}
,"empty":{"if":1,"calculation":1,"value":1}
,"evaluate":{"if":1}
,"calculations":{"self-referencing":1}
,"self-referencing":{"auto-enter":1}
,"self-modifying":{"leave":1}
,"leave":{"replace":1}
,"deselecte":{"auto-enter":1}
,"that\u2019s":{"automatically":1}
,"updated":{"can\u2019t":1}
,"can\u2019t":{"changed":1}
,"changed":{"by":1}
,"entering":{"data":1}
,"auto":{"enter":1,"entry":1}
,"start":{"number":1}
}
;Search.control.loadWordPairs(pairs);
