var pairs =
{
"diting":{"privilege":1,"record":1,"layouts":1}
,"privilege":{"tart":1,"set":1,"sets":1,"if":1}
,"tart":{"editing":1}
,"editing":{"new":1,"privilege":1,"enable":1,"commands":1,"record":1,"fields":1,"minimum":1,"scripts":1}
,"new":{"existing":1,"passwords":1,"window":1,"windows":1}
,"existing":{"privilege":1}
,"set":{"edit":1,"dialog":1,"clipboard":1,"enable":1,"field":1,"change":1,"cases":1,"menu":1,"options":1}
,"edit":{"privilege":1,"extended":1}
,"dialog":{"box":1}
,"box":{"creating":1,"choose":1,"user":1}
,"creating":{"editing":1}
,"sets":{"privileges":1,"extended":1}
,"privileges":{"et":1,"hen":1,"manage":1,"allow":1,"change":1,"apply":1,"layouts":1,"prohibit":1,"diting":1,"setting":1}
,"et":{"options":1}
,"options":{"allow":1,"set":1,"minimum":1,"editing":1,"password":1}
,"allow":{"printing":1,"saving":1,"copying":1,"importing":1,"querying":1,"exporting":1,"users":1,"entering":1,"user":1}
,"printing":{"allow":1,"print":1,"allo":1}
,"saving":{"records":1,"copy":1}
,"records":{"pdf":1,"allow":1,"excel":1,"found":1,"filemaker":1,"macos":1,"data":1}
,"pdf":{"file":1}
,"file":{"allow":1,"rom":1,"change":1,"choose":1,"active":1}
,"print":{"finder":1}
,"finder":{"apple":1}
,"apple":{"event":1,"events":1}
,"event":{"choose":1}
,"choose":{"allow":1,"manage":1,"disconnect":1,"changed":1,"option":1,"clear":1,"minimum":1,"all":1}
,"allo":{"exporting":1}
,"exporting":{"records":1,"note":1}
,"excel":{"file":1}
,"copying":{"all":1}
,"all":{"records":1,"enable":1,"menu":1}
,"found":{"set":1}
,"clipboard":{"allow":1}
,"importing":{"records":1}
,"filemaker":{"file":1,"network":1,"server":1,"erver":1,"pro":1,"uthenticated":1}
,"copy":{"records":1}
,"macos":{"allow":1,"clearing":1}
,"querying":{"data":1}
,"data":{"apple":1,"doesn\u2019t":1,"validation":1,"layouts":1}
,"events":{"getcellvalue":1,"access":1,"allow":1}
,"getcellvalue":{"field":1}
,"field":{"contents":1,"choose":1,"defined":1,"validation":1}
,"contents":{"record":1,"layout":1,"choose":1}
,"record":{"value":1,"access":1}
,"value":{"table":1}
,"table":{"contents":1}
,"layout":{"contents":1}
,"note":{"windows":1,"setting":1,"if":1}
,"windows":{"clearing":1,"perform":1,"limiting":1,"create":1,"creating":1}
,"clearing":{"option":1,"allow":1}
,"option":{"activex":1,"prohibits":1,"se":1,"choosing":1}
,"activex":{"automation":1}
,"automation":{"macos":1}
,"prohibits":{"apple":1,"users":1}
,"access":{"data":1,"privileges":1}
,"users":{"privilege":1,"filemaker":1,"new":1,"open":1}
,"enable":{"disable":1,"all":1,"basic":1}
,"disable":{"extended":1,"all":1}
,"extended":{"privileges":1,"privilege":1}
,"hen":{"setting":1}
,"setting":{"up":1,"ignored":1,"menu":1}
,"up":{"filemaker":1}
,"network":{"sh":1}
,"sh":{"aring":1}
,"aring":{"pu":1}
,"pu":{"blishing":1}
,"blishing":{"odbc":1}
,"odbc":{"\u002Fjdbc":1}
,"\u002Fjdbc":{"sharing":1}
,"sharing":{"allow":1}
,"manage":{"security":1,"extended":1}
,"security":{"dialog":1}
,"entering":{"data":1}
,"doesn\u2019t":{"match":1}
,"match":{"validation":1}
,"validation":{"options":1,"warnings":1,"overrides":1,"option":1,"disconnect":1}
,"user":{"override":1,"shared":1,"idle":1,"se":1,"modify":1,"file":1,"change":1}
,"override":{"data":1,"validation":1}
,"warnings":{"note":1}
,"ignored":{"field":1}
,"defined":{"prohibit":1}
,"prohibit":{"field":1,"editing":1}
,"overrides":{"by":1}
,"by":{"clearing":1,"privilege":1}
,"se":{"defining":1,"rver":1,"diting":1}
,"defining":{"field":1}
,"disconnect":{"user":1}
,"shared":{"file":1,"files":1}
,"rom":{"filemaker":1}
,"server":{"software":1,"performance":1,"bout":1}
,"software":{"user":1}
,"idle":{"typically":1,"note":1,"allow":1}
,"typically":{"improves":1}
,"improves":{"filemaker":1}
,"performance":{"choose":1}
,"rver":{"idle":1}
,"if":{"you\u2019re":1,"choose":1,"set":1,"want":1}
,"you\u2019re":{"hosting":1}
,"hosting":{"shared":1}
,"files":{"filemaker":1,"switch":1}
,"bout":{"disconnecting":1}
,"disconnecting":{"users":1}
,"erver":{"idle":1}
,"change":{"password":1,"preference":1}
,"password":{"choose":1,"require":1,"number":1,"dialog":1,"order":1,"account":1,"length":1,"change":1,"character":1}
,"modify":{"own":1}
,"own":{"password":1}
,"require":{"users":1}
,"number":{"days":1,"characters":1}
,"days":{"number":1,"elapsed":1,"enter":1,"note":1}
,"elapsed":{"next":1}
,"next":{"time":1}
,"time":{"each":1}
,"each":{"user":1}
,"order":{"open":1}
,"open":{"file":1,"close":1,"filemaker":1,"additional":1,"windows":1}
,"changed":{"days":1}
,"enter":{"number":1}
,"choosing":{"allow":1}
,"account":{"full":1,"assigned":1}
,"full":{"access":1}
,"assigned":{"privilege":1}
,"cases":{"choose":1}
,"clear":{"options":1}
,"minimum":{"character":1,"password":1,"disable":1,"disables":1}
,"character":{"length":1}
,"length":{"new":1,"enter":1,"privileges":1}
,"passwords":{"choose":1}
,"characters":{"limited":1}
,"limited":{"set":1}
,"menu":{"commands":1,"new":1}
,"commands":{"file":1,"choose":1,"except":1,"browse":1,"editing":1,"if":1}
,"active":{"menu":1}
,"except":{"disabled":1,"open":1}
,"disabled":{"by":1}
,"basic":{"editing":1}
,"browse":{"mode":1}
,"mode":{"minimum":1}
,"close":{"create":1}
,"create":{"database":1,"scripts":1}
,"database":{"files":1,"windows":1}
,"switch":{"database":1}
,"perform":{"scripts":1}
,"scripts":{"open":1,"allow":1}
,"pro":{"advanced":1}
,"advanced":{"elp":1}
,"elp":{"change":1}
,"preference":{"options":1}
,"apply":{"filemaker":1}
,"uthenticated":{"accounts":1}
,"accounts":{"external":1,"ee":1,"privilege":1}
,"external":{"server-authenticated":1}
,"server-authenticated":{"accounts":1}
,"ee":{"accounts":1}
,"layouts":{"privileges":1,"se":1}
,"fields":{"records":1}
,"disables":{"window":1}
,"window":{"menu":1,"command":1}
,"command":{"prohibits":1}
,"limiting":{"menu":1}
,"want":{"control":1}
,"control":{"ability":1}
,"ability":{"users":1}
,"additional":{"windows":1}
}
;Search.control.loadWordPairs(pairs);
