var pairs =
{
"install":{"menu":1,"use":1,"list":1}
,"menu":{"set":1}
,"set":{"hanges":1,"based":1,"install":1,"manage":1,"script":1,"reverts":1,"want":1,"if":1,"installed":1,"\u0022]":1,"[\u0022":1,"use":1,"automating":1}
,"hanges":{"menu":1}
,"based":{"conditions":1}
,"conditions":{"established":1}
,"established":{"script":1}
,"script":{"sp":1,"step":1}
,"sp":{"ecif":1}
,"ecif":{"menu":1}
,"use":{"fi":1,"file":1}
,"fi":{"le":1}
,"le":{"de":1}
,"de":{"fault":1}
,"fault":{"overrides":1}
,"overrides":{"file\u2019s":1}
,"file\u2019s":{"default":1}
,"default":{"menu":1,"off]":1}
,"manage":{"custom":1}
,"custom":{"menus":1,"menu":1}
,"menus":{"dialog":1}
,"dialog":{"box":1}
,"box":{"menu":1,"select":1}
,"step":{"close":1,"install":1}
,"close":{"file":1}
,"file":{"default":1}
,"reverts":{"manage":1}
,"select":{"menu":1}
,"want":{"script":1}
,"list":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"8.0":1}
,"8.0":{"invoice":1}
,"invoice":{"details":1}
,"details":{"layout":1,"\u0022]":1}
,"layout":{"installs":1,"[\u0022":1}
,"installs":{"invoices":1}
,"invoices":{"menu":1}
,"if":{"print":1,"[get":1,"reating":1}
,"print":{"invoices":1}
,"installed":{"go":1}
,"go":{"layout":1}
,"[\u0022":{"invoice":1,"nvoices":1}
,"\u0022]":{"if":1,"install":1}
,"[get":{"custommenusetname":1}
,"custommenusetname":{"=\u0022":1}
,"=\u0022":{"print":1}
,"nvoices":{"menu":1}
,"off]":{"end":1}
,"end":{"if":1}
,"reating":{"editing":1}
,"editing":{"custom":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
