var pairs =
{
"get":{"recordnu":1,"recordnumber":1,"recordid":1,"activerecordnumber":1,"record":1,"current":1}
,"recordnu":{"mber":1}
,"mber":{"returns":1}
,"returns":{"number":1,"current":1}
,"number":{"representing":1,"filemaker":1,"get":1}
,"representing":{"record\u2019s":1}
,"record\u2019s":{"position":1}
,"position":{"current":1}
,"current":{"found":1,"calculation":1,"window":1,"record":1}
,"found":{"set":1}
,"set":{"get":1,"depending":1}
,"recordnumber":{"none":1,"get":1}
,"none":{"number":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"value":1}
,"value":{"returned":1,"uniquely":1}
,"returned":{"determined":1}
,"determined":{"by":1}
,"by":{"relative":1}
,"relative":{"place":1}
,"place":{"record":1}
,"record":{"found":1,"table":1,"record":1,"number":1}
,"depending":{"find":1}
,"find":{"criteria":1}
,"criteria":{"sort":1}
,"sort":{"order":1}
,"order":{"return":1}
,"return":{"value":1}
,"uniquely":{"permanently":1}
,"permanently":{"identifies":1}
,"identifies":{"record":1}
,"table":{"use":1}
,"use":{"get":1}
,"recordid":{"function":1}
,"function":{"if":1,"evaluated":1}
,"if":{"context":1}
,"context":{"current":1,"evaluated":1}
,"calculation":{"function":1}
,"evaluated":{"based":1}
,"based":{"context":1}
,"window":{"returns":1}
,"activerecordnumber":{"get":1}
}
;Search.control.loadWordPairs(pairs);
