var pairs =
{
"reating":{"portals":1}
,"portals":{"display":1,"add":1}
,"display":{"related":1,"vertical":1,"all":1,"while":1,"portal\u2019s":1,"portal":1}
,"related":{"record":1,"fields":1,"records":1,"table":1,"field":1}
,"record":{"create":1,"options":1,"exit":1,"select":1,"clear":1,"display":1}
,"create":{"portal":1,"new":1}
,"portal":{"displays":1,"related":1,"tool":1,"drag":1,"size":1,"setup":1,"select":1,"sort":1,"records":1,"filter":1,"row":1,"users":1,"time":1,"initial":1,"number":1,"background":1,"rows":1,"dialog":1,"add":1,"create":1}
,"displays":{"data":1,"related":1}
,"data":{"related":1}
,"fields":{"rows":1,"by":1,"portal":1,"want":1}
,"rows":{"first":1,"portal":1,"ormatting":1}
,"first":{"define":1,"record":1,"row":1}
,"define":{"relationship":1,"formula":1}
,"relationship":{"table":1,"hoose":1}
,"table":{"occurrence":1,"invoice":1,"display":1,"primary":1,"relationship":1,"browse":1,"ee":1}
,"occurrence":{"current":1,"use":1}
,"current":{"layout":1,"table":1,"record":1}
,"layout":{"based":1,"add":1,"products":1,"mode":1,"want":1}
,"based":{"table":1}
,"use":{"manage":1,"delete":1}
,"manage":{"database":1}
,"database":{"dialog":1,"tables":1,"select":1}
,"dialog":{"box":1}
,"box":{"defining":1,"show":1,"choose":1,"define":1}
,"defining":{"database":1}
,"tables":{"creating":1,"custom":1}
,"creating":{"nd":1,"portal":1}
,"nd":{"changing":1}
,"changing":{"relationships":1}
,"relationships":{"invoice":1}
,"invoice":{"layout":1}
,"add":{"list":1,"fields":1,"portal":1}
,"list":{"line":1}
,"line":{"items":1}
,"items":{"by":1,"table":1}
,"by":{"creating":1,"sort":1}
,"records":{"line":1,"choose":1,"portal":1,"lick":1,"filter":1,"allow":1,"deleted":1,"option":1,"visible":1,"new":1}
,"products":{"illustrating":1}
,"illustrating":{"layout":1}
,"mode":{"portal":1,"allow":1}
,"tool":{"portal":1,"status":1}
,"status":{"toolbar":1}
,"toolbar":{"position":1}
,"position":{"crosshair":1}
,"crosshair":{"pointer":1}
,"pointer":{"layout":1,"diagonally":1}
,"want":{"portal":1}
,"drag":{"pointer":1,"objects":1}
,"diagonally":{"portal":1}
,"size":{"want":1}
,"setup":{"dialog":1}
,"show":{"ecords":1,"scroll":1}
,"ecords":{"choose":1}
,"choose":{"related":1,"apps":1,"fields":1,"default":1}
,"apps":{"add-ons":1,"create":1}
,"add-ons":{"if":1}
,"if":{"current":1}
,"primary":{"key":1}
,"key":{"default":1}
,"default":{"primarykey":1,"scroll":1}
,"primarykey":{"field":1}
,"field":{"dding":1,"first":1}
,"dding":{"add-on":1}
,"add-on":{"tables":1,"table":1}
,"custom":{"apps":1}
,"new":{"table":1,"add-on":1}
,"hoose":{"manage":1}
,"select":{"record":1,"sort":1,"reset":1,"format":1}
,"options":{"portal":1}
,"sort":{"records":1,"portal":1,"dialog":1}
,"lick":{"sort":1,"calculation":1}
,"filter":{"records":1,"portal":1}
,"calculation":{"dialog":1,"filter":1}
,"formula":{"calculation":1}
,"allow":{"related":1,"deletion":1,"vertical":1}
,"deleted":{"related":1}
,"browse":{"mode":1}
,"deletion":{"portal":1}
,"option":{"selected":1,"scroll":1}
,"selected":{"use":1}
,"delete":{"portal":1}
,"row":{"script":1,"existing":1}
,"script":{"step":1}
,"step":{"display":1}
,"vertical":{"scroll":1,"scrolling":1}
,"scroll":{"bar":1,"bars":1}
,"bar":{"right":1,"choose":1,"display":1,"exiting":1,"reset":1}
,"right":{"portal":1}
,"users":{"enter":1}
,"enter":{"records":1}
,"visible":{"portal":1}
,"time":{"allow":1,"scrolling":1}
,"scrolling":{"show":1,"display":1,"occurs":1}
,"all":{"time":1}
,"while":{"scrolling":1}
,"occurs":{"scroll":1}
,"portal\u2019s":{"first":1}
,"exit":{"current":1}
,"reset":{"scroll":1,"note":1}
,"exiting":{"record":1}
,"clear":{"option":1}
,"note":{"can\u2019t":1}
,"can\u2019t":{"change":1}
,"change":{"style":1}
,"style":{"scroll":1}
,"bars":{"select":1}
,"format":{"options":1}
,"initial":{"related":1}
,"number":{"rows":1}
,"background":{"color":1}
,"color":{"portal":1}
,"ormatting":{"portals":1}
,"objects":{"related":1}
,"existing":{"portal":1}
,"ee":{"dding":1}
}
;Search.control.loadWordPairs(pairs);
