var pairs =
{
"reate":{"script":1}
,"script":{"report":1,"select":1,"type":1,"name":1,"automatically":1,"switch":1,"filemaker":1,"include":1,"step":1,"rerun":1}
,"report":{"new":1,"by":1,"each":1,"run":1,"edit":1}
,"new":{"layout\u002Freport":1}
,"layout\u002Freport":{"assistant":1}
,"assistant":{"panel":1,"automate":1,"if":1,"reate":1}
,"panel":{"new":1}
,"automate":{"report":1}
,"by":{"creating":1}
,"creating":{"script":1}
,"select":{"create":1,"run":1}
,"create":{"script":1}
,"type":{"script":1}
,"name":{"scripts":1,"ptionally":1}
,"scripts":{"menu":1}
,"menu":{"keep":1}
,"keep":{"default":1}
,"default":{"name":1,"steps":1}
,"ptionally":{"select":1}
,"run":{"script":1,"report":1}
,"automatically":{"display":1}
,"display":{"up-to-date":1}
,"up-to-date":{"report":1}
,"each":{"time":1}
,"time":{"open":1}
,"open":{"layout":1}
,"layout":{"if":1,"summary":1}
,"if":{"layout":1,"want":1}
,"summary":{"data":1}
,"data":{"doesn\u2019t":1}
,"doesn\u2019t":{"report":1}
,"switch":{"list":1}
,"list":{"view":1}
,"view":{"table":1,"create":1}
,"table":{"view":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"ncludes":1}
,"ncludes":{"default":1}
,"steps":{"modify":1}
,"modify":{"finish":1}
,"finish":{"assistant":1}
,"want":{"include":1}
,"include":{"subset":1,"perform":1}
,"subset":{"records":1}
,"records":{"database":1}
,"database":{"run":1}
,"edit":{"script":1}
,"perform":{"find":1}
,"find":{"script":1}
,"step":{"finish":1}
,"rerun":{"report":1}
}
;Search.control.loadWordPairs(pairs);
