var pairs =
{
"moving":{"objects":1}
,"objects":{"layout":1,"want":1,"new":1,"dynamic":1,"remember":1,"help":1}
,"layout":{"layout":1,"mode":1,"override":1}
,"mode":{"select":1}
,"select":{"objects":1}
,"want":{"move":1,"rranging":1}
,"move":{"drag":1,"selection":1}
,"drag":{"objects":1,"selection":1,"object":1}
,"new":{"position":1}
,"position":{"dynamic":1,"object":1,"selection":1}
,"dynamic":{"guides":1}
,"guides":{"help":1,"choose":1,"move":1,"dynamic":1,"grid":1}
,"help":{"position":1,"achieve":1}
,"object":{"you\u2019re":1,"edge":1}
,"you\u2019re":{"dragging":1}
,"dragging":{"objects":1}
,"choose":{"view":1}
,"view":{"menu":1}
,"menu":{"dynamic":1}
,"selection":{"point":1,"precisely":1,"use":1,"press":1,"sing":1,"boundaries":1}
,"point":{"press":1}
,"press":{"right":1,"shift":1,"alt":1}
,"right":{"arrow":1}
,"arrow":{"left":1,"up":1,"arrow":1,"limit":1}
,"left":{"arrow":1}
,"up":{"arrow":1}
,"limit":{"movement":1}
,"movement":{"horizontal":1}
,"horizontal":{"vertical":1}
,"vertical":{"direction":1}
,"direction":{"press":1}
,"shift":{"drag":1}
,"precisely":{"move":1}
,"use":{"rulers":1}
,"rulers":{"guides":1,"grid":1}
,"grid":{"inspector":1,"position":1}
,"inspector":{"positioning":1}
,"positioning":{"objects":1}
,"override":{"snap-to":1}
,"snap-to":{"move":1}
,"alt":{"windows":1}
,"windows":{"command":1}
,"command":{"macos":1}
,"macos":{"drag":1}
,"sing":{"rulers":1}
,"boundaries":{"document":1}
,"document":{"window":1}
,"window":{"drag":1,"moving":1}
,"edge":{"document":1}
,"remember":{"layer":1}
,"layer":{"align":1}
,"align":{"rotate":1}
,"rotate":{"objects":1}
,"achieve":{"want":1}
,"rranging":{"objects":1}
}
;Search.control.loadWordPairs(pairs);
