var pairs =
{
"set":{"use":1,"computer":1}
,"use":{"system":1,"current":1,"formats":1}
,"system":{"formats":1,"language":1}
,"formats":{"ets":1,"stored":1,"instructs":1,"saved":1,"currently":1,"change":1,"startup":1,"script":1,"file":1,"current":1,"checks":1,"started":1,"[on]":1,"automating":1}
,"ets":{"formats":1}
,"stored":{"file":1}
,"file":{"current":1,"filemaker":1,"stores":1,"ou":1,"system":1}
,"current":{"system":1}
,"instructs":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1,"6.0":1}
,"advanced":{"use":1,"database":1,"alerts":1,"handles":1}
,"saved":{"file":1}
,"6.0":{"earlier":1}
,"earlier":{"each":1}
,"each":{"filemaker":1}
,"database":{"file":1,"created":1}
,"stores":{"date":1}
,"date":{"time":1}
,"time":{"number":1}
,"number":{"formatting":1,"formats":1}
,"formatting":{"computer":1}
,"computer":{"database":1,"use":1}
,"created":{"regional":1,"australia":1}
,"regional":{"settings":1}
,"settings":{"system":1}
,"currently":{"set":1}
,"change":{"formats":1}
,"ou":{"simply":1}
,"simply":{"enter":1}
,"enter":{"view":1}
,"view":{"data":1}
,"data":{"format":1}
,"format":{"familiar":1}
,"familiar":{"if":1}
,"if":{"database":1,"[get":1,"files":1}
,"australia":{"dates":1}
,"dates":{"usually":1}
,"usually":{"written":1}
,"written":{"day-month-year":1,"month-day-year":1}
,"day-month-year":{"open":1}
,"open":{"united":1}
,"united":{"states":1}
,"states":{"dates":1}
,"month-day-year":{"filemaker":1}
,"alerts":{"system":1}
,"startup":{"script":1}
,"script":{"set":1,"step":1,"trigger":1}
,"step":{"control":1}
,"control":{"filemaker":1}
,"handles":{"date":1}
,"checks":{"system":1}
,"language":{"system":1}
,"started":{"by":1}
,"by":{"onfirstwindowopen":1}
,"onfirstwindowopen":{"script":1}
,"trigger":{"if":1}
,"[get":{"systemlanguage":1}
,"systemlanguage":{"=\u0022":1}
,"=\u0022":{"apanese":1}
,"apanese":{"\u0022]":1}
,"\u0022]":{"set":1}
,"[on]":{"end":1}
,"end":{"if":1}
,"files":{"system":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
