var pairs =
{
"random":{"returns":1,"none":1,"number":1,"function":1,"*10":1}
,"returns":{"number":1,"pseudo-random":1,"random":1,"randomly":1}
,"number":{"including":1,"filemaker":1,"range":1,"insert":1,"int":1}
,"including":{"including":1,"random":1}
,"none":{"number":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1,"advanced":1}
,"6.0":{"earlier":1}
,"earlier":{"returns":1}
,"pseudo-random":{"number":1}
,"range":{"0,1":1}
,"0,1":{"filemaker":1}
,"advanced":{"generates":1}
,"generates":{"new":1}
,"new":{"random":1}
,"insert":{"random":1}
,"function":{"formula":1,"reevaluated":1}
,"formula":{"formula":1,"random":1,"display":1}
,"reevaluated":{"by":1}
,"by":{"changing":1}
,"changing":{"data":1}
,"data":{"fields":1}
,"fields":{"formula":1}
,"display":{"access":1}
,"access":{"calculation":1}
,"calculation":{"field":1}
,"field":{"defined":1}
,"defined":{"unstored":1}
,"unstored":{"result":1}
,"result":{"int":1}
,"int":{"random":1,"dice":1,"test":1}
,"*10":{"returns":1}
,"dice":{":numsides":1}
,":numsides":{"*random":1}
,"*random":{"returns":1,")]":1}
,"randomly":{"chosen":1}
,"chosen":{"single":1}
,"single":{"die":1,"variable":1}
,"die":{"script":1,"rolls":1}
,"script":{"calculates":1}
,"calculates":{"multiple":1}
,"multiple":{"die":1}
,"rolls":{"adds":1,"single":1}
,"adds":{"rolls":1}
,"variable":{"displays":1,"[$roll":1,"[$counter":1}
,"displays":{"custom":1}
,"custom":{"dialog":1}
,"dialog":{"loop":1,"[$roll]":1}
,"loop":{"set":1,"if":1,"show":1}
,"set":{"variable":1}
,"[$roll":{"value:$roll":1}
,"value:$roll":{"int":1}
,"test":{":numsides":1}
,")]":{"set":1}
,"[$counter":{"value:$counter":1,"=dice":1}
,"value:$counter":{"1]":1}
,"1]":{"exit":1}
,"exit":{"loop":1}
,"if":{"[$counter":1}
,"=dice":{":numdice]":1}
,":numdice]":{"end":1}
,"end":{"loop":1}
,"show":{"custom":1}
}
;Search.control.loadWordPairs(pairs);
