var pairs =
{
"allow":{"formatting":1}
,"formatting":{"bar":1}
,"bar":{"nables":1,"formatting":1,"view":1,"menu":1,"button":1,"enabled":1,"disables":1,"filemaker":1,"script":1,"hidden":1,"kiosk":1,"go":1,"[on]":1}
,"nables":{"disables":1}
,"disables":{"display":1,"view":1,"formatting":1}
,"display":{"formatting":1}
,"view":{"menu":1}
,"menu":{"formatting":1,"item":1,"items":1}
,"item":{"formatting":1,"disables":1}
,"button":{"layout":1}
,"layout":{"bar":1,"mode":1,"formatting":1,"[\u0022":1}
,"enabled":{"hides":1}
,"hides":{"formatting":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"script":1}
,"script":{"step":1}
,"step":{"all":1,"disable":1,"active":1,"called":1}
,"all":{"modes":1}
,"modes":{"except":1}
,"except":{"layout":1}
,"mode":{"use":1,"allow":1,"comment":1}
,"use":{"script":1}
,"disable":{"formatting":1}
,"items":{"related":1}
,"related":{"formatting":1}
,"active":{"window":1}
,"window":{"file":1}
,"file":{"script":1}
,"called":{"runtime":1}
,"runtime":{"solutions":1}
,"solutions":{"formatting":1}
,"hidden":{"kiosk":1}
,"kiosk":{"mode":1}
,"comment":{"field":1}
,"field":{"invoice":1,"[invoices":1}
,"invoice":{"details":1}
,"details":{"layout":1,"\u0022]":1}
,"go":{"layout":1,"field":1}
,"[\u0022":{"invoice":1}
,"\u0022]":{"go":1}
,"[invoices":{":comments]":1}
,":comments]":{"allow":1}
,"[on]":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
