var pairs =
{
"diting":{"scripts":1}
,"scripts":{"privileges":1,"file":1,"allow":1,"hide":1,"set":1,"actions":1,"choose":1,"allowed":1,"menu":1,"imported":1,"custom":1,"duplicating":1,"run":1,"want":1,"full":1,"edit":1}
,"privileges":{"privilege":1,"all":1,"individual":1,"allow":1,"script":1,"custom":1,"dialog":1,"you\u2019ve":1,"account":1,"depending":1,"creating":1}
,"privilege":{"sets":1,"set":1,"granting":1,"all":1,"choose":1}
,"sets":{"limit":1,"data":1,"running":1}
,"limit":{"access":1}
,"access":{"scripts":1,"privileges":1,"design":1,"options":1,"running":1,"privilege":1,"allow":1,"script":1}
,"file":{"file":1,"set":1,"prevent":1}
,"set":{"privileges":1,"custom":1,"each":1,"note":1,"determine":1,"permit":1,"edit":1,"dialog":1,"creating":1,"executable":1}
,"all":{"scripts":1,"modifiable":1,"executable":1,"access":1}
,"allow":{"prohibit":1,"ability":1,"ing":1,"running":1,"script":1,"creating":1,"creation":1}
,"prohibit":{"ability":1,"privilege":1,"running":1}
,"ability":{"view":1,"run":1}
,"view":{"create":1}
,"create":{"modify":1,"group":1}
,"modify":{"scripts":1,"script":1}
,"hide":{"all":1,"script":1}
,"prevent":{"run":1}
,"run":{"by":1,"scripts":1,"full":1}
,"by":{"privilege":1,"clearing":1}
,"custom":{"privileges":1,"script":1}
,"individual":{"scripts":1}
,"each":{"script":1}
,"script":{"modifiable":1,"prevent":1,"privileges":1,"execute":1,"go":1,"step":1,"privilege":1,"cript":1,"names":1,"name":1,"workspace":1,"steps":1,"select":1,"set":1,"created":1,"al":1,"imported":1,"runs":1,"pr":1,"script":1,"th":1}
,"modifiable":{"hide":1,"all":1,"note":1,"modify":1,"script":1}
,"note":{"script":1,"if":1}
,"actions":{"permitted":1}
,"permitted":{"by":1}
,"determine":{"steps":1}
,"steps":{"script":1,"cript":1}
,"execute":{"if":1}
,"if":{"privilege":1,"script":1}
,"permit":{"accessing":1}
,"accessing":{"salary":1}
,"salary":{"field":1}
,"field":{"script":1,"[e":1}
,"go":{"field":1}
,"[e":{"mployees":1}
,"mployees":{":salary":1}
,":salary":{"script":1}
,"step":{"fail":1}
,"fail":{"override":1}
,"override":{"script":1}
,"granting":{"full":1}
,"full":{"access":1,"ac":1}
,"cript":{"workspace":1,"debugger":1}
,"workspace":{"start":1,"allowed":1,"view":1,"privilege":1}
,"start":{"editing":1}
,"editing":{"new":1,"privilege":1,"printing":1,"scripts":1}
,"new":{"existing":1,"script":1,"scripts":1}
,"existing":{"privilege":1}
,"edit":{"privilege":1,"duplicate":1,"rivileges":1,"privileges":1}
,"dialog":{"box":1}
,"box":{"ee":1,"creating":1,"select":1,"allow":1,"notes":1}
,"ee":{"creating":1}
,"creating":{"editing":1,"new":1}
,"data":{"access":1}
,"design":{"scripts":1,"report":1}
,"choose":{"all":1,"custom":1,"modifiable":1,"executable":1,"access":1}
,"executable":{"all":1,"prohibit":1,"access":1}
,"options":{"allow":1}
,"running":{"scripts":1,"viewing":1,"script":1}
,"allowed":{"allowed":1,"prohibited":1}
,"prohibited":{"viewing":1,"script":1,"prohibited":1,"allow":1,"start":1}
,"viewing":{"script":1,"editing":1}
,"names":{"scripts":1}
,"menu":{"except":1,"privilege":1}
,"except":{"hidden":1}
,"hidden":{"by":1}
,"clearing":{"checkbox":1}
,"checkbox":{"left":1}
,"left":{"script":1}
,"name":{"script":1,"scripts":1}
,"group":{"filter":1}
,"filter":{"edit":1}
,"duplicate":{"delete":1}
,"delete":{"print":1}
,"print":{"scripts":1}
,"ing":{"scripts":1}
,"imported":{"database":1}
,"database":{"files":1,"design":1}
,"files":{"allowed":1,"privilege":1}
,"debugger":{"database":1}
,"report":{"allowed":1}
,"select":{"each":1,"new":1,"allow":1}
,"created":{"set":1}
,"you\u2019ve":{"finished":1}
,"finished":{"setting":1}
,"setting":{"privileges":1}
,"printing":{"deleting":1}
,"deleting":{"script":1}
,"al":{"allow":1}
,"runs":{"full":1}
,"ac":{"cess":1}
,"cess":{"privileges":1}
,"account":{"assigned":1}
,"assigned":{"full":1}
,"pr":{"ohibit":1}
,"ohibit":{"viewing":1}
,"th":{"script":1}
,"duplicating":{"modifiable":1}
,"creation":{"new":1}
,"notes":{"column":1}
,"column":{"scripts":1}
,"depending":{"scripts":1}
,"want":{"set":1}
,"rivileges":{"all":1}
}
;Search.control.loadWordPairs(pairs);
