var pairs =
{
"end":{"dde":1}
,"dde":{"execute":1,"command":1,"dynamic":1,"windows":1,"ex":1,"connection":1}
,"execute":{"windows":1,"commands":1,"series":1,"script":1,"[service":1}
,"windows":{"dde":1,"feature":1}
,"command":{"application":1}
,"application":{"execute":1,"service":1,"executes":1,"valid":1,"refer":1,"filemaker":1}
,"commands":{"application":1,"refer":1,"calculated":1,"formats":1,"text":1,"calculation":1,"ut":1,"www.filemaker.com":1}
,"service":{"name":1}
,"name":{"name":1,"application":1,"enter":1,"text":1,"calculation":1,"valid":1,"topic":1,"iexplore":1}
,"executes":{"commands":1,"send":1}
,"refer":{"documentation":1}
,"documentation":{"application":1}
,"valid":{"service":1,"topics":1,"commands":1}
,"enter":{"service":1,"topic":1,"commands":1}
,"text":{"create":1,"string":1}
,"create":{"service":1,"topic":1,"commands":1}
,"calculation":{"topic":1,"creating":1,"filemaker":1}
,"topic":{"filename":1,"application":1,"name":1,"if":1,"filemaker":1,"all":1,"www_openurl":1}
,"filename":{"text":1}
,"string":{"describes":1,"specifies":1}
,"describes":{"topic":1}
,"topics":{"enter":1}
,"creating":{"file":1}
,"file":{"paths":1}
,"paths":{"commands":1}
,"calculated":{"value":1}
,"value":{"text":1}
,"specifies":{"application":1}
,"formats":{"enter":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1,"advanced":1}
,"6.0":{"earlier":1}
,"earlier":{"script":1}
,"script":{"step":1,"send":1,"first":1,"steps":1,"includes":1,"completed":1}
,"step":{"sends":1,"macos-based":1,"ignored":1,"service":1,"executes":1}
,"sends":{"dde":1}
,"dynamic":{"data":1}
,"data":{"exchange":1}
,"exchange":{"command":1}
,"series":{"commands":1}
,"advanced":{"sends":1,"script":1,"closes":1}
,"ut":{"receive":1}
,"receive":{"dde":1}
,"feature":{"if":1}
,"if":{"run":1,"script":1}
,"run":{"script":1}
,"send":{"dde":1}
,"ex":{"ecute":1}
,"ecute":{"script":1}
,"macos-based":{"computer":1}
,"computer":{"script":1}
,"ignored":{"error":1}
,"error":{"code":1}
,"code":{"generated":1}
,"generated":{"captured":1}
,"captured":{"get":1}
,"get":{"lasterror":1}
,"lasterror":{"function":1}
,"function":{"filemaker":1}
,"first":{"establishes":1}
,"establishes":{"dde":1}
,"connection":{"connection":1,"stays":1,"new":1}
,"stays":{"open":1}
,"open":{"perform":1,"connections":1,"step":1}
,"perform":{"ubsequent":1}
,"ubsequent":{"script":1}
,"steps":{"service":1}
,"includes":{"dde":1}
,"closes":{"current":1}
,"current":{"connection":1}
,"new":{"service":1}
,"all":{"open":1}
,"connections":{"close":1}
,"close":{"script":1}
,"completed":{"url":1}
,"url":{"internet":1}
,"internet":{"explorer":1}
,"explorer":{"internet":1,"open":1}
,"[service":{"name":1}
,"iexplore":{"topic":1}
,"www_openurl":{"commands":1}
,"www.filemaker.com":{"\u0022]":1}
,"\u0022]":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
