var pairs =
{
"mporting":{"data":1}
,"data":{"upgraded":1,"sure":1,"imported":1,"new":1}
,"upgraded":{"runtime":1,"customer\u2019s":1,"file":1,"solution":1}
,"runtime":{"solution":1,"files":1,"database":1,"application":1}
,"solution":{"note":1,"include":1,"files":1,"use":1,"create":1,"database":1,"file":1,"test":1,"importing":1}
,"note":{"feature":1,"creating":1}
,"feature":{"use":1}
,"use":{"advanced":1,"extension":1,"developer":1,"sample":1,"buttons":1}
,"advanced":{"tools":1}
,"tools":{"general":1,"upgraded":1}
,"general":{"preference":1}
,"preference":{"selected":1}
,"selected":{"ad":1}
,"ad":{"vanced":1}
,"vanced":{"tools":1}
,"customer\u2019s":{"runtime":1}
,"include":{"scripts":1,"convert":1}
,"scripts":{"new":1}
,"new":{"runtime":1,"file":1,"solution\u2019s":1,"solution":1,"files":1}
,"files":{"allow":1,"old":1,"first":1,"inside":1,"place":1,"folder":1,"new":1,"contain":1,"users":1,"convert":1,"import":1,"prepare":1}
,"allow":{"users":1}
,"users":{"import":1,"copy":1}
,"import":{"records":1,"properly":1,"data":1}
,"records":{"old":1,"new":1,"[<":1,"import":1}
,"old":{"runtime":1,"files":1,"solution":1,"version":1,"filename":1}
,"first":{"converted":1}
,"converted":{"new":1}
,"file":{"format":1,"create":1,"import":1,"functionality":1,"[<":1,">]":1,"use":1}
,"format":{"note":1}
,"creating":{"upgraded":1}
,"extension":{"old":1,">]":1}
,"create":{"folder":1,"script":1}
,"folder":{"named":1,"new":1,"each":1,"use":1}
,"named":{"old":1}
,"inside":{"folder":1}
,"database":{"files":1,"solution":1}
,"place":{"copies":1}
,"copies":{"old":1}
,"each":{"upgraded":1}
,"script":{"convert":1,"include":1,"repeat":1}
,"convert":{"old":1,"file":1}
,"functionality":{"script":1}
,"[<":{"filename":1,"old":1}
,"filename":{"old":1,"new":1}
,"version":{"solution":1}
,">]":{"import":1,"close":1,"add":1}
,"solution\u2019s":{"extension":1}
,"close":{"file":1}
,"add":{"button":1}
,"button":{"activate":1}
,"activate":{"script":1}
,"repeat":{"steps":1}
,"steps":{"each":1}
,"developer":{"utilities":1}
,"utilities":{"bind":1}
,"bind":{"upgraded":1}
,"test":{"buttons":1}
,"buttons":{"runtime":1,"provide":1,"new":1}
,"application":{"use":1}
,"sample":{"data":1}
,"sure":{"records":1}
,"properly":{"data":1}
,"imported":{"correct":1}
,"correct":{"fields":1}
,"fields":{"distribute":1}
,"distribute":{"new":1}
,"contain":{"buttons":1}
,"provide":{"instructions":1}
,"instructions":{"telling":1}
,"telling":{"users":1}
,"copy":{"old":1}
,"prepare":{"upgraded":1}
,"importing":{"data":1}
}
;Search.control.loadWordPairs(pairs);
