var pairs =
{
"excel":{"format":1,"worksheets":1,"documentation":1,"saved":1,"limitations":1,"online":1,"file":1,"files":1}
,"format":{"filemaker":1,"all":1,"importing":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"import":1,"row":1,"assigns":1,"imports":1,"ile":1,"files":1}
,"import":{"convert":1,"choose":1}
,"convert":{"export":1,"idden":1}
,"export":{"excel":1}
,"worksheets":{"if":1}
,"if":{"file":1,"all":1,"select":1,"current":1}
,"file":{"worksheet":1,"field":1,"formatted":1,"system":1}
,"worksheet":{"named":1}
,"named":{"range":1}
,"range":{"choose":1,"want":1}
,"choose":{"worksheet":1,"filemaker":1}
,"want":{"import":1}
,"row":{"data":1}
,"data":{"file":1,"column":1,"large":1,"type":1,"formatting":1,"data":1,"excel":1,"filemaker":1}
,"field":{"names":1,"type":1,"filemaker":1,"data":1}
,"names":{"ilemaker":1}
,"ilemaker":{"pro":1}
,"assigns":{"field":1}
,"type":{"text":1,"data":1,"excel":1}
,"text":{"number":1,"field":1,"format":1}
,"number":{"date":1,"fields":1}
,"date":{"time":1}
,"time":{"if":1}
,"all":{"rows":1,"fields":1}
,"rows":{"column":1}
,"column":{"hold":1,"text":1}
,"hold":{"type":1}
,"imports":{"calculation":1}
,"calculation":{"formulas":1}
,"formulas":{"boolean":1}
,"boolean":{"values":1}
,"values":{"considered":1}
,"considered":{"numbers":1}
,"numbers":{"charts":1,"exported":1}
,"charts":{"graphics":1}
,"graphics":{"notes":1}
,"notes":{"comments":1}
,"comments":{"imported":1}
,"imported":{"non-data":1}
,"non-data":{"structures":1}
,"structures":{"macros":1}
,"macros":{"converted":1}
,"converted":{"convert":1}
,"idden":{"iles":1}
,"iles":{"excel":1}
,"documentation":{"password-protected":1}
,"password-protected":{"files":1}
,"files":{"field":1,"exporting":1,"excel":1}
,"large":{"equivalent":1}
,"equivalent":{"data":1}
,"saved":{"text":1}
,"fields":{"truncated":1,"rounded":1,"repeating":1,"exported":1}
,"truncated":{"32,767":1}
,"32,767":{"characters":1}
,"characters":{"number":1}
,"rounded":{"closest":1}
,"closest":{"value":1}
,"value":{"accepted":1}
,"accepted":{"by":1}
,"by":{"excel":1}
,"limitations":{"excel":1}
,"online":{"help":1}
,"help":{"numbers":1}
,"exported":{"number":1,"if":1,"data":1}
,"repeating":{"fields":1}
,"select":{"apply":1}
,"apply":{"current":1}
,"current":{"layout\u0027s":1,"layout":1}
,"layout\u0027s":{"data":1}
,"formatting":{"exported":1,"can\u2019t":1}
,"formatted":{"resemble":1}
,"resemble":{"data":1}
,"ile":{"if":1}
,"layout":{"formatting":1}
,"can\u2019t":{"applied":1}
,"applied":{"excel":1}
,"system":{"format":1}
,"importing":{"co":1}
,"co":{"nverting":1}
,"nverting":{"excel":1}
,"exporting":{"filemaker":1}
}
;Search.control.loadWordPairs(pairs);
