var pairs =
{
"ow":{"custom":1}
,"custom":{"dialog":1,"message":1,"text":1,"button":1}
,"dialog":{"isplays":1,"box":1,"options":1,"input":1,"ignores":1,"script":1,"boxes":1,"[\u0022":1,"off]":1}
,"isplays":{"custom":1}
,"message":{"dialog":1,"specifies":1,"text":1,"displays":1,"message":1,"script":1}
,"box":{"custom":1,"enter":1,"title":1,"labels":1,"if":1,"create":1,"target":1,"displayed":1,"allows":1,"stays":1,"up":1,"closed":1,"button":1,"perform":1,"freeze":1,"automating":1}
,"text":{"labels":1,"create":1,"calculation":1,"entered":1,"identify":1,"buttons":1,"number":1,"custom":1}
,"labels":{"title":1,"specifies":1,"buttons":1}
,"title":{"specifies":1,"custom":1,"calculation":1,"message":1}
,"specifies":{"title":1,"message":1,"buttons":1,"abel":1}
,"enter":{"literal":1,"data":1,"customer":1,"custom":1,"fields":1,"find":1,"browse":1}
,"literal":{"text":1}
,"create":{"dialog":1,"message":1,"button":1,"label":1,"keyboard":1,"record":1}
,"calculation":{"message":1,"button":1,"calculation":1,"commit":1,"filemaker":1,"summary":1}
,"button":{"labels":1,"label":1,"custom":1,"titles":1,"displays":1,"field":1,"users":1,"show":1,"user":1,"by":1,"if":1,"labeled":1,"database":1,"changing":1,"cancel":1}
,"buttons":{"up":1,"if":1,"custom":1}
,"up":{"display":1,"fields":1,"buttons":1}
,"display":{"custom":1,"script":1}
,"if":{"leave":1,"fields":1,"field":1,"checkbox":1,"values":1,"records":1,"[get":1,"creates":1,"enters":1,"find":1,"user":1,"end":1,"else":1,"message":1}
,"leave":{"button":1,"all":1}
,"label":{"blank":1,"based":1,"specifies":1,"calculation":1,"create":1,"\u2018&done":1}
,"blank":{"button":1}
,"all":{"button":1,"users":1,"scripts":1,"records":1}
,"titles":{"blank":1,"use":1}
,"displays":{"lower-right":1,"user":1,"custom":1}
,"lower-right":{"corner":1}
,"corner":{"custom":1}
,"based":{"calculation":1}
,"commit":{"data":1}
,"data":{"checkboxes":1,"committed":1,"input":1,"stored":1,"inserted":1,"entry":1,"commitment":1}
,"checkboxes":{"pass":1}
,"pass":{"input":1}
,"input":{"dialog":1,"field":1,"use":1,"custom":1,"user":1,"display":1,"type":1,"store":1,"fields":1}
,"target":{"field":1,"if":1,"fields":1}
,"field":{"variable":1,"target":1,"active":1,"data":1,"activates":1,"selects":1,"type":1,"validation":1,"script":1,"entry":1,"options":1}
,"variable":{"ccording":1,"users":1,"input":1}
,"ccording":{"action":1}
,"action":{"each":1}
,"each":{"button":1}
,"fields":{"layout":1,"variables":1,"don\u2019t":1,"independent":1,"show":1,"data":1,"customers":1}
,"layout":{"re":1,"show":1,"first":1,"[\u0022":1}
,"re":{"active":1}
,"active":{"data":1}
,"committed":{"if":1,"record":1,"committed":1,"database":1}
,"record":{"committed":1,"stored":1,"prompts":1,"by":1}
,"checkbox":{"enabled":1}
,"enabled":{"button":1}
,"users":{"enter":1,"button":1,"right-click":1,"currently":1,"inadvertently":1}
,"stored":{"variable":1,"database":1}
,"show":{"input":1,"custom":1,"all":1}
,"activates":{"input":1}
,"selects":{"target":1}
,"use":{"password":1,"input":1,"get":1,"behavior":1,"new":1}
,"password":{"character":1}
,"character":{"(*)":1}
,"(*)":{"masks":1}
,"masks":{"text":1}
,"entered":{"displayed":1,"input":1}
,"displayed":{"database":1,"alter":1}
,"database":{"option":1,"label":1,"that\u2019s":1,"develop":1}
,"option":{"obscures":1}
,"obscures":{"data":1}
,"alter":{"actual":1}
,"actual":{"data":1}
,"abel":{"text":1}
,"identify":{"input":1}
,"user":{"enter":1,"presses":1,"resolve":1,"find":1,"input":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"show":1}
,"options":{"dialog":1,"allowing":1,"input":1,"script":1}
,"allows":{"set":1}
,"set":{"dialog":1,"field":1}
,"variables":{"use":1,"input":1}
,"script":{"pauses":1,"step":1,"all":1,"scripts":1,"halts":1,"sub-script":1,"[specified":1,"end":1,"prompting":1,"find":1}
,"pauses":{"custom":1}
,"stays":{"screen":1}
,"screen":{"ields":1}
,"ields":{"input":1}
,"type":{"text":1,"validation":1,"label":1}
,"number":{"date":1}
,"date":{"time":1}
,"time":{"timestamp":1}
,"timestamp":{"container":1}
,"container":{"variables":1}
,"store":{"values":1}
,"values":{"text":1,"entered":1}
,"get":{"lastmessagechoice":1}
,"lastmessagechoice":{"function":1,"=1]":1,"=2]":1}
,"function":{"determine":1}
,"determine":{"button":1}
,"presses":{"first":1}
,"first":{"button":1}
,"by":{"default":1,"access":1,"placing":1,"pressing":1,"id":1}
,"default":{"labeled":1}
,"labeled":{"second":1,"cancel":1,"type":1}
,"second":{"button":1}
,"cancel":{"button":1,"users":1}
,"don\u2019t":{"match":1,"current":1}
,"match":{"target":1}
,"validation":{"error":1,"errors":1,"target":1}
,"error":{"message":1}
,"resolve":{"validation":1}
,"errors":{"dialog":1}
,"closed":{"defining":1}
,"defining":{"field":1}
,"current":{"layout":1,"script":1}
,"independent":{"layouts":1}
,"layouts":{"set":1}
,"step":{"data":1,"limited":1,"performs":1}
,"inserted":{"calculation":1}
,"summary":{"fields":1}
,"ignores":{"field":1}
,"entry":{"options":1,"fields":1,"via":1}
,"allowing":{"preventing":1}
,"preventing":{"entry":1}
,"via":{"show":1}
,"limited":{"by":1}
,"access":{"privileges":1}
,"privileges":{"criteria":1,"windows":1}
,"criteria":{"place":1,"performs":1}
,"place":{"enable":1}
,"enable":{"script":1}
,"right-click":{"current":1}
,"scripts":{"pane":1,"enter":1,"sub-scripts":1,"general":1}
,"pane":{"choose":1}
,"choose":{"grant":1}
,"grant":{"full":1}
,"full":{"access":1}
,"windows":{"create":1}
,"keyboard":{"shortcut":1}
,"shortcut":{"custom":1,"key":1,"alt":1}
,"placing":{"ampersand":1}
,"ampersand":{"shortcut":1}
,"key":{"letter":1}
,"letter":{"button":1}
,"alt":{"button":1}
,"\u2018&done":{"change":1}
,"change":{"data":1}
,"commitment":{"status":1}
,"status":{"button":1}
,"that\u2019s":{"use":1}
,"behavior":{"users":1,"affect":1}
,"currently":{"expect":1}
,"expect":{"button":1}
,"changing":{"behavior":1}
,"affect":{"validity":1}
,"validity":{"data":1}
,"develop":{"more-complex":1}
,"more-complex":{"custom":1}
,"boxes":{"use":1}
,"new":{"window":1,"record":1,"record\u002Frequest":1,"customer":1}
,"window":{"script":1,"new":1}
,"performs":{"find":1,"script":1}
,"find":{"if":1,"[restore]":1,"mode":1,"criteria":1,"returns":1,"performs":1,"customers":1,"[]":1,"\u0022]":1,"parameter":1}
,"records":{"found":1,"if":1,"halts":1}
,"found":{"displays":1,"\u0022]":1,"find":1}
,"perform":{"find":1,"script":1}
,"[restore]":{"if":1}
,"[get":{"foundcount":1,"lastmessagechoice":1}
,"foundcount":{"=0]":1}
,"=0]":{"show":1}
,"[\u0022":{"records":1,"new":1,"customer":1,"find":1}
,"\u0022]":{"end":1,"if":1}
,"end":{"if":1}
,"creates":{"new":1}
,"prompts":{"user":1}
,"customer":{"details":1,"enter":1}
,"details":{"layout":1,"\u0022]":1}
,"inadvertently":{"create":1}
,"pressing":{"return":1}
,"return":{"enter":1}
,"freeze":{"window":1}
,"record\u002Frequest":{"show":1,"[with":1}
,"customers":{":company":1,":name":1,":city]":1,"by":1,":id":1}
,":company":{"customers":1}
,":name":{"customers":1}
,":city]":{"if":1}
,"=1]":{"delete":1,"perform":1,"calls":1}
,"delete":{"record\u002Frequest":1}
,"[with":{"dialog":1}
,"off]":{"else":1,"show":1,"end":1}
,"else":{"go":1,"show":1,"if":1}
,"go":{"layout":1}
,"enters":{"find":1}
,"mode":{"prompts":1,"[pause":1}
,"returns":{"records":1}
,"halts":{"all":1}
,"[pause":{"off]":1}
,"id":{"name":1}
,"name":{"city":1}
,"city":{"customers":1}
,":id":{"customers":1}
,"[]":{"if":1}
,"calls":{"script":1}
,"sub-script":{"perform":1}
,"[specified":{"list":1}
,"list":{"find":1}
,"parameter":{"else":1}
,"sub-scripts":{"halt":1}
,"halt":{"script":1}
,"=2]":{"enter":1}
,"browse":{"mode":1}
,"prompting":{"user":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
,"general":{"options":1}
}
;Search.control.loadWordPairs(pairs);
