var pairs =
{
"removing":{"admin":1}
,"admin":{"access":1}
,"access":{"database":1,"privilege":1,"privileges":1,"files":1,"sers":1,"dialog":1,"extended":1,"layout":1}
,"database":{"note":1,"all":1,"files":1,"saved":1,"manage":1}
,"note":{"feature":1}
,"feature":{"use":1}
,"use":{"advanced":1,"developer":1}
,"advanced":{"tools":1,"structural":1}
,"tools":{"general":1,"ou":1,"menu":1}
,"general":{"preference":1}
,"preference":{"selected":1}
,"selected":{"ad":1}
,"ad":{"vanced":1}
,"vanced":{"tools":1}
,"ou":{"use":1}
,"developer":{"utilities":1,"solution":1}
,"utilities":{"remove":1,"close":1,"if":1,"database":1,"settings":1}
,"remove":{"all":1,"admin":1,"change":1}
,"all":{"administrative":1,"accounts":1,"database":1}
,"administrative":{"accounts":1}
,"accounts":{"file":1,"full":1}
,"file":{"selecting":1,"customized":1,"list":1,"select":1,"remove":1}
,"selecting":{"option":1}
,"option":{"permanently":1,"enabled":1}
,"permanently":{"deletes":1,"remove":1}
,"deletes":{"database":1}
,"full":{"access":1}
,"privilege":{"set":1}
,"set":{"includes":1,"run":1,"assigned":1}
,"includes":{"all":1}
,"files":{"solution":1,"recovered":1,"customize":1,"want":1,"double-click":1,"developer":1,"permanently":1}
,"solution":{"runtime":1,"solution":1,"options":1,"select":1}
,"runtime":{"application":1}
,"application":{"filemaker":1}
,"filemaker":{"ro":1}
,"ro":{"advanced":1}
,"structural":{"design":1}
,"design":{"elements":1}
,"elements":{"files":1}
,"recovered":{"modify":1}
,"modify":{"tables":1}
,"tables":{"field":1}
,"field":{"definitions":1}
,"definitions":{"relationships":1}
,"relationships":{"scripts":1}
,"scripts":{"access":1,"text":1}
,"privileges":{"by":1,"creating":1,"tab":1,"option":1}
,"by":{"returning":1,"developer":1}
,"returning":{"original":1}
,"original":{"file":1}
,"customized":{"by":1}
,"close":{"all":1}
,"customize":{"choose":1,"if":1}
,"choose":{"tools":1}
,"menu":{"developer":1}
,"if":{"developer":1,"add":1,"run":1,"account":1,"privilege":1}
,"saved":{"settings":1}
,"settings":{"load":1,"add":1,"required":1}
,"load":{"settings":1}
,"add":{"locate":1,"multiple":1}
,"locate":{"files":1}
,"want":{"customize":1}
,"multiple":{"files":1}
,"double-click":{"file":1}
,"list":{"primary":1}
,"primary":{"file":1}
,"select":{"developer":1,"remove":1}
,"required":{"setting":1}
,"setting":{"up":1}
,"up":{"files":1}
,"options":{"options":1,"developer":1}
,"sers":{"can\u2019t":1}
,"can\u2019t":{"access":1,"use":1}
,"dialog":{"boxes":1}
,"boxes":{"manage":1,"listed":1}
,"manage":{"database":1,"external":1,"custom":1,"security":1,"extended":1}
,"external":{"data":1}
,"data":{"sources":1}
,"sources":{"manage":1}
,"custom":{"functions":1}
,"functions":{"manage":1,"removed":1}
,"security":{"users":1,"if":1}
,"users":{"access":1,"can\u2019t":1}
,"listed":{"if":1}
,"run":{"script":1,"full":1}
,"script":{"set":1,"workspace":1}
,"creating":{"editing":1}
,"editing":{"scripts":1}
,"text":{"version":1}
,"version":{"custom":1}
,"removed":{"users":1}
,"extended":{"privileges":1}
,"tab":{"manage":1}
,"account":{"manage":1,"permits":1}
,"enabled":{"users":1}
,"layout":{"mode":1}
,"mode":{"script":1}
,"workspace":{"if":1}
,"assigned":{"account":1}
,"permits":{"users":1}
,"change":{"encryption":1}
,"encryption":{"password":1}
,"password":{"encrypted":1}
,"encrypted":{"file":1}
}
;Search.control.loadWordPairs(pairs);
