var pairs =
{
"guides":{"dynamic":1,"help":1,"align":1,"objects":1,"snap":1,"layout":1,"layouts":1,"ch":1,"show":1,"nap-to":1,"bjects":1,"guides":1,"hidden":1,"choose":1,"selected":1}
,"dynamic":{"guide":1,"guides":1}
,"guide":{"use":1,"horizontal":1,"drag":1,"new":1,"locked":1,"choose":1,"all":1,"current":1,"right-click":1,"color":1,"remove":1,"back":1,"show":1}
,"use":{"guides":1,"horizontal":1,"dynamic":1,"shared":1}
,"help":{"create":1}
,"create":{"edit":1,"vertical":1}
,"edit":{"objects":1,"right-click":1}
,"objects":{"layout":1,"across":1,"dynamic":1,"move":1,"snap":1}
,"layout":{"use":1,"drag":1,"layout":1,"mode":1,"right-click":1,"part":1}
,"horizontal":{"vertical":1,"guide":1,"ruler":1}
,"vertical":{"guides":1,"guide":1,"ruler":1}
,"align":{"objects":1}
,"across":{"multiple":1}
,"multiple":{"layouts":1}
,"layouts":{"use":1,"create":1,"lock":1}
,"drag":{"objects":1,"vertical":1,"horizontal":1,"guide":1}
,"snap":{"upper":1,"guides":1,"layout":1}
,"upper":{"lower":1}
,"lower":{"boundaries":1}
,"boundaries":{"centers":1,"field":1,"choose":1,"boundaries":1,"line":1,"view":1}
,"centers":{"objects":1}
,"move":{"resize":1,"guide":1,"use":1}
,"resize":{"position":1}
,"position":{"guides":1,"if":1}
,"mode":{"create":1}
,"ruler":{"drag":1,"if":1,"isn\u2019t":1,"vertical":1,"right-click":1}
,"if":{"ruler":1,"guide":1}
,"isn\u2019t":{"displayed":1}
,"displayed":{"select":1}
,"select":{"view":1}
,"view":{"menu":1}
,"menu":{"rulers":1,"guides":1,"dynamic":1,"show":1}
,"rulers":{"move":1}
,"new":{"position":1}
,"locked":{"unlock":1,"guide":1}
,"unlock":{"move":1,"guide":1}
,"right-click":{"guide":1}
,"choose":{"share":1,"lock":1,"remove":1,"view":1}
,"share":{"guide":1}
,"all":{"layouts":1}
,"shared":{"guide":1}
,"current":{"layout":1}
,"lock":{"unlock":1,"guide":1}
,"color":{"unlocked":1}
,"unlocked":{"guide":1}
,"remove":{"guide":1}
,"back":{"horizontal":1,"vertical":1}
,"show":{"hide":1,"guides":1,"text":1}
,"hide":{"guides":1}
,"ch":{"oose":1}
,"oose":{"view":1}
,"nap-to":{"ffect":1}
,"ffect":{"choose":1}
,"bjects":{"snap":1}
,"hidden":{"dynamic":1}
,"text":{"boundaries":1,"object":1}
,"field":{"boundaries":1,"object":1}
,"line":{"each":1}
,"each":{"text":1}
,"object":{"field":1,"objects":1}
,"part":{"boundaries":1}
}
;Search.control.loadWordPairs(pairs);
