var pairs =
{
"get":{"record":1,"recordaccess":1,"layoutaccess":1}
,"record":{"access":1,"privileges":1,"if":1,"return":1}
,"access":{"returns":1,"privileges":1,"record":1,"records":1,"view-only":1,"get":1}
,"returns":{"number":1,"if":1,"value":1,"privileges":1,"record":1}
,"number":{"representing":1,"filemaker":1}
,"representing":{"current":1}
,"current":{"record\u0027s":1,"record":1,"calculation":1,"window":1}
,"record\u0027s":{"access":1}
,"privileges":{"assigned":1,"dialog":1,"account\u2019s":1,"set":1,"defined":1,"details":1,"custom":1}
,"assigned":{"custom":1,"individual":1}
,"custom":{"record":1}
,"dialog":{"box":1}
,"box":{"get":1}
,"recordaccess":{"none":1,"returns":1,"if":1,"get":1}
,"none":{"number":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"returns":1}
,"if":{"custom":1,"view":1,"edit":1,"context":1}
,"account\u2019s":{"privilege":1}
,"privilege":{"set":1}
,"set":{"view":1,"current":1,"limited":1,"get":1,"edit":1}
,"view":{"edit":1,"set":1}
,"edit":{"privileges":1,"set":1}
,"limited":{"calculation":1,"access":1}
,"calculation":{"defined":1,"function":1}
,"defined":{"limited":1,"accessing":1}
,"value":{"true":1}
,"true":{"note":1,"get":1}
,"note":{"if":1}
,"accessing":{"records":1}
,"records":{"ignores":1,"returns":1}
,"ignores":{"access":1}
,"individual":{"layouts":1}
,"layouts":{"check":1}
,"check":{"access":1}
,"return":{"values":1}
,"values":{"get":1}
,"layoutaccess":{"function":1}
,"function":{"get":1,"evaluated":1}
,"context":{"current":1,"evaluated":1}
,"evaluated":{"based":1}
,"based":{"context":1}
,"window":{"diting":1}
,"diting":{"record":1}
,"details":{"limiting":1}
,"limiting":{"access":1}
,"view-only":{"get":1}
}
;Search.control.loadWordPairs(pairs);
