var pairs =
{
"aving":{"find":1}
,"find":{"request":1,"se":1,"windows":1,"choose":1,"macos":1,"en":1,"if":1,"dialog":1,"records":1,"omit":1,"operator":1,"network":1}
,"request":{"last":1,"want":1,"choose":1,"selected":1,"saved":1,"new":1,"edit":1,"dialog":1,"find":1,"change":1}
,"last":{"finds":1}
,"finds":{"recent":1,"list":1,"button":1}
,"recent":{"finds":1,"find":1}
,"list":{"complex":1,"select":1,"find":1}
,"complex":{"find":1}
,"want":{"use":1,"save":1,"change":1,"select":1}
,"use":{"regular":1,"create":1,"multiple":1,"change":1}
,"regular":{"basis":1}
,"basis":{"name":1}
,"name":{"save":1,"saved":1,"select":1,"current":1}
,"save":{"use":1,"choose":1,"current":1,"saved":1,"new":1,"find":1}
,"create":{"find":1}
,"choose":{"recent":1,"records":1,"save":1,"find":1}
,"se":{"aking":1,"lect":1,"defining":1}
,"aking":{"find":1}
,"selected":{"find":1,"field":1}
,"records":{"menu":1,"omit":1,"finding":1,"adds":1,"excludes":1,"use":1,"search":1,"lick":1,"include":1}
,"menu":{"save":1}
,"current":{"find":1,"table":1}
,"windows":{"arrow":1}
,"arrow":{"next":1}
,"next":{"find":1,"follow":1}
,"macos":{"hold":1}
,"hold":{"find":1}
,"en":{"ter":1}
,"ter":{"name":1}
,"saved":{"find":1,"finds":1}
,"if":{"want":1,"find":1}
,"change":{"search":1,"existing":1,"store":1}
,"search":{"criteria":1}
,"criteria":{"save":1,"continue":1,"se":1,"field":1,"type":1,"selected":1,"finding":1,"cell":1,"want":1,"select":1,"top":1,"change":1,"find":1}
,"button":{"status":1,"saved":1}
,"status":{"toolbar":1}
,"toolbar":{"if":1}
,"continue":{"next":1}
,"follow":{"steps":1}
,"steps":{"-3":1,"search":1}
,"-3":{"options":1}
,"options":{"saved":1}
,"dialog":{"box":1}
,"box":{"advanced":1,"choose":1,"field":1,"remove":1,"save":1}
,"advanced":{"change":1}
,"new":{"find":1,"change":1,"list":1}
,"lect":{"find":1}
,"edit":{"edit":1,"find":1}
,"omit":{"records":1}
,"finding":{"records":1}
,"adds":{"found":1}
,"found":{"set":1}
,"set":{"omitting":1}
,"omitting":{"records":1}
,"excludes":{"individual":1}
,"individual":{"request":1}
,"multiple":{"requests":1}
,"requests":{"if":1}
,"field":{"under":1,"name":1,"related":1,"new":1,"insert":1,"repetition":1,"criteria":1}
,"under":{"find":1}
,"lick":{"field":1}
,"select":{"field":1,"related":1,"line":1}
,"related":{"table":1,"field":1}
,"table":{"name":1,"top":1,"want":1}
,"top":{"list":1,"dialog":1}
,"operator":{"criteria":1,"further":1}
,"type":{"search":1,"repetition":1}
,"insert":{"operator":1}
,"further":{"refine":1}
,"refine":{"search":1}
,"include":{"variables":1}
,"variables":{"search":1}
,"cell":{"repeating":1}
,"repeating":{"field":1,"fields":1}
,"repetition":{"type":1,"number":1}
,"number":{"se":1}
,"defining":{"repeating":1}
,"fields":{"add":1}
,"add":{"repeat":1}
,"repeat":{"steps":1}
,"existing":{"criteria":1}
,"line":{"field":1}
,"store":{"delete":1}
,"delete":{"existing":1}
,"remove":{"return":1}
,"return":{"options":1}
,"network":{"clients":1}
,"clients":{"share":1}
,"share":{"account":1}
,"account":{"save":1}
}
;Search.control.loadWordPairs(pairs);
