var pairs =
{
"correct":{"word":1,"misspelled":1,"spelling":1}
,"word":{"pens":1,"none":1,"use":1,"filemaker":1,"end":1}
,"pens":{"spelling":1}
,"spelling":{"dialog":1,"correct":1,"type":1,"tab":1,"\u0022]":1,"automating":1}
,"dialog":{"box":1,"[\u0022":1}
,"box":{"user":1,"users":1,"if":1,"show":1,"correct":1}
,"user":{"correct":1,"open":1}
,"misspelled":{"word":1,"displays":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1,"advanced":1}
,"6.0":{"earlier":1}
,"earlier":{"script":1}
,"script":{"step":1}
,"step":{"choosing":1,"open":1,"correct":1}
,"choosing":{"edit":1}
,"edit":{"menu":1}
,"menu":{"spelling":1,"file":1}
,"use":{"script":1}
,"open":{"spelling":1}
,"users":{"if":1}
,"if":{"restricted":1,"user":1,"[get":1,"checking":1}
,"restricted":{"access":1}
,"access":{"filemaker":1}
,"advanced":{"menus":1,"identifies":1}
,"menus":{"check":1}
,"check":{"spelling":1}
,"type":{"selected":1}
,"selected":{"file":1}
,"file":{"menu":1,"options":1}
,"options":{"spelling":1}
,"tab":{"script":1}
,"identifies":{"misspelled":1}
,"displays":{"custom":1}
,"custom":{"dialog":1}
,"show":{"custom":1}
,"[\u0022":{"open":1}
,"\u0022]":{"if":1}
,"[get":{"lastmessagechoice":1}
,"lastmessagechoice":{"=1]":1}
,"=1]":{"correct":1}
,"end":{"if":1}
,"checking":{"spelling":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
