var pairs =
{
"erform":{"find\u002Freplace":1}
,"find\u002Freplace":{"inds\u002Freplaces":1,"options":1,"summary":1,"operation":1,"script":1,"perform":1,"search":1,"performed":1,"find":1,"[with":1}
,"inds\u002Freplaces":{"data":1}
,"data":{"options":1,"matches":1,"show":1,"\u0022]":1,"automating":1}
,"options":{"perform":1,"dialog":1}
,"perform":{"find\u002Freplace":1,"choose":1,"find":1}
,"dialog":{"box":1,"specifies":1,"prevents":1,"replace":1,"[\u0022":1,"products":1,"[name]":1,"[company]":1,"[address]":1}
,"box":{"dialog":1,"end":1,"replace":1}
,"specifies":{"display":1,"find":1,"text":1,"direction":1}
,"display":{"find\u002Freplace":1,"confirmation":1}
,"summary":{"dialog":1}
,"end":{"find\u002Freplace":1,"if":1}
,"operation":{"setting":1,"executed":1}
,"setting":{"dialog":1}
,"prevents":{"display":1}
,"confirmation":{"dialog":1}
,"replace":{"all":1,"criteria":1,"&find":1,"replaces":1,"term":1,"action":1,"specifies":1,"instances":1,"all]":1,"placeholder":1}
,"all":{"operation":1,"script":1,"finds":1,"instances":1,"records\u002Frequests":1,"fields":1,"records":1}
,"executed":{"if":1}
,"if":{"want":1,"perform":1,"[get":1,"replaces":1,"finding":1}
,"want":{"user":1,"find\u002Freplace":1,"find":1,"replace":1}
,"user":{"enter":1,"go":1}
,"enter":{"find":1}
,"find":{"replace":1,"next":1,"term":1,"specifies":1,"term\u2019s":1,"match":1,"current":1,"active":1,"data":1,"criteria":1,"next]":1}
,"criteria":{"use":1,"all":1}
,"use":{"open":1,"go":1}
,"open":{"find\u002Freplace":1}
,"script":{"step":1,"run":1}
,"step":{"perform":1,"select":1,"replace":1}
,"choose":{"action":1}
,"action":{"want":1,"pair":1}
,"next":{"finds":1,"instance":1,"occurrence":1}
,"finds":{"instance":1,"replaces":1,"find":1,"all":1,"field":1}
,"instance":{"find":1,"script":1}
,"term":{"replace":1,"replaces":1,"searches":1,"find":1,"direction":1,"embedded":1,"doesn\u2019t":1}
,"&find":{"finds":1}
,"replaces":{"term":1,"highlighted":1,"all":1,"text":1,"specific":1}
,"searches":{"next":1}
,"run":{"replace":1}
,"highlighted":{"text":1}
,"text":{"matches":1,"replace":1,"reorder":1}
,"matches":{"find":1}
,"pair":{"perform":1}
,"select":{"all":1,"field":1}
,"instances":{"find":1}
,"direction":{"specifies":1,"want":1}
,"search":{"records":1}
,"records":{"match":1,"prompting":1}
,"match":{"case":1,"omits":1}
,"case":{"considers":1,"performing":1}
,"considers":{"find":1}
,"term\u2019s":{"case":1}
,"performing":{"find":1}
,"omits":{"finds":1}
,"embedded":{"word":1}
,"word":{"all":1}
,"records\u002Frequests":{"finds":1,"found":1,"restricts":1}
,"found":{"set":1}
,"set":{"current":1}
,"current":{"records\u002Frequests":1,"record\u002Frequest":1,"field":1,"product":1}
,"restricts":{"find":1}
,"record\u002Frequest":{"all":1}
,"fields":{"finds":1}
,"field":{"layout":1,"restricts":1,"use":1,"script":1,"find\u002Freplace":1,"matches":1,"[products":1,"show":1,"\u0022]":1,"record":1}
,"layout":{"current":1}
,"active":{"field":1}
,"go":{"field":1}
,"performed":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"if":1}
,"doesn\u2019t":{"return":1}
,"return":{"error":1}
,"error":{"replaces":1}
,"reorder":{"level":1}
,"level":{"field":1}
,"prompting":{"user":1}
,"[products":{":reorder":1,":description]":1}
,":reorder":{"level]":1}
,"level]":{"perform":1}
,"[with":{"dialog":1}
,"all]":{"next":1,"perform":1,"end":1}
,"occurrence":{"product":1}
,"product":{"name":1}
,"name":{"description":1}
,"description":{"field":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"[\u0022":{"want":1}
,"\u0022]":{"if":1}
,"[get":{"lastmessagechoice":1}
,"lastmessagechoice":{"=1]":1}
,"=1]":{"go":1,"perform":1}
,":description]":{"perform":1}
,"products":{":name":1}
,":name":{"find":1,"replace":1}
,"next]":{"end":1}
,"specific":{"terms":1}
,"terms":{"current":1,"record":1}
,"record":{"data":1}
,"placeholder":{"terms":1}
,"[name]":{"customers":1}
,"customers":{":name":1,":company":1,":address":1}
,"[company]":{"customers":1}
,":company":{"replace":1}
,"[address]":{"customers":1}
,":address":{"replace":1}
,"finding":{"replacing":1}
,"replacing":{"data":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
