var pairs =
{
"dding":{"layout":1}
,"layout":{"part":1,"mode":1,"choose":1,"dimmed":1,"adding":1,"preview":1,"view":1,"list":1,"bar":1,"parts":1}
,"part":{"layout":1,"tool":1,"part":1,"definition":1,"want":1,"types":1,"type":1,"sub-summary":1,"filemaker":1,"top":1,"if":1,"field":1,"determines":1,"resize":1}
,"mode":{"drag":1}
,"drag":{"part":1}
,"tool":{"part":1,"status":1}
,"status":{"toolbar":1}
,"toolbar":{"layout":1}
,"choose":{"insert":1,"field":1}
,"insert":{"menu":1}
,"menu":{"part":1}
,"definition":{"dialog":1}
,"dialog":{"box":1}
,"box":{"select":1}
,"select":{"type":1,"name":1}
,"type":{"layout":1,"part":1}
,"want":{"layout":1,"group":1,"subsequent":1}
,"types":{"description":1,"layout":1}
,"description":{"each":1}
,"each":{"part":1,"region":1}
,"dimmed":{"subsummary":1}
,"subsummary":{"parts":1,"part":1,"data":1,"values":1}
,"parts":{"exist":1,"want":1}
,"exist":{"layout":1}
,"adding":{"subsummary":1}
,"sub-summary":{"sorted":1}
,"sorted":{"by":1}
,"by":{"select":1,"break":1,"first":1,"subsummary":1}
,"name":{"field":1,"tables":1}
,"field":{"want":1,"choose":1,"table":1,"all":1,"grouped":1,"region":1,"touches":1,"displays":1}
,"group":{"records":1}
,"records":{"by":1,"sorted":1,"value":1,"print":1}
,"break":{"field":1}
,"table":{"by":1,"name":1}
,"first":{"choosing":1}
,"choosing":{"table":1}
,"tables":{"list":1}
,"list":{"list":1,"fields":1,"view":1}
,"fields":{"records":1,"portals":1}
,"all":{"records":1}
,"value":{"field":1}
,"grouped":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"calculate":1,"onsiders":1}
,"calculate":{"subsummary":1}
,"data":{"if":1}
,"if":{"subtotal":1,"top":1}
,"subtotal":{"sales":1}
,"sales":{"figures":1}
,"figures":{"each":1}
,"region":{"break":1,"sorting":1}
,"sorting":{"records":1}
,"values":{"add":1}
,"add":{"fields":1,"title":1,"regular":1}
,"portals":{"graphic":1}
,"graphic":{"objects":1}
,"objects":{"text":1,"body":1}
,"text":{"layout":1}
,"onsiders":{"object":1}
,"object":{"part":1,"just":1}
,"top":{"object":1,"field":1}
,"just":{"touching":1}
,"touching":{"part":1}
,"touches":{"bottom":1}
,"bottom":{"division":1}
,"division":{"line":1}
,"line":{"header":1}
,"header":{"part":1,"body":1,"regular":1,"footer":1,"show":1}
,"displays":{"prints":1}
,"prints":{"header":1}
,"body":{"blank":1,"part":1}
,"blank":{"space":1}
,"space":{"objects":1}
,"determines":{"spacing":1}
,"spacing":{"records":1}
,"print":{"layout":1,"cover":1}
,"preview":{"layout":1}
,"view":{"layout":1,"list":1,"button":1}
,"button":{"layout":1}
,"bar":{"print":1}
,"cover":{"page":1}
,"page":{"report":1,"add":1}
,"report":{"add":1}
,"title":{"header":1}
,"resize":{"size":1}
,"size":{"page":1}
,"regular":{"header":1,"footer":1}
,"footer":{"layout":1,"footers":1,"headers":1,"heading":1}
,"subsequent":{"pages":1}
,"pages":{"footer":1}
,"footers":{"header":1}
,"headers":{"footers":1}
,"show":{"header":1,"footer":1}
,"heading":{"headings":1}
}
;Search.control.loadWordPairs(pairs);
