var pairs =
{
"omit":{"record":1}
,"record":{"mits":1,"found":1,"table":1,"omit":1,"operates":1,"end":1}
,"mits":{"current":1}
,"current":{"record":1,"find":1,"ind":1,"date":1}
,"found":{"set":1}
,"set":{"switches":1,"next":1,"if":1}
,"switches":{"current":1}
,"find":{"request":1,"mode":1}
,"request":{"finding":1,"including":1}
,"finding":{"omitting":1,"records":1}
,"omitting":{"records":1}
,"records":{"none":1,"omitting":1,"omits":1,"except":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"script":1}
,"script":{"step":1}
,"step":{"omits":1,"performed":1}
,"omits":{"temporarily":1,"current":1}
,"temporarily":{"hides":1}
,"hides":{"current":1}
,"next":{"record":1}
,"table":{"current":1}
,"operates":{"browse":1}
,"browse":{"mode":1}
,"mode":{"find":1,"script":1,"switches":1}
,"performed":{"find":1}
,"ind":{"request":1}
,"including":{"records":1}
,"if":{"created":1,"[invoices":1,"finding":1}
,"created":{"current":1,"get":1}
,"date":{"if":1}
,"[invoices":{":date":1}
,":date":{"created":1}
,"get":{"currentdate":1}
,"currentdate":{")]":1}
,")]":{"omit":1}
,"end":{"if":1}
,"except":{"matching":1}
,"matching":{"criteria":1}
,"criteria":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
