var pairs =
{
"get":{"activelayoutobjectn":1,"activelayoutobjectname":1,"active":1,"layout":1}
,"activelayoutobjectn":{"ame":1}
,"ame":{"returns":1}
,"returns":{"name":1,"empty":1,"customername":1}
,"name":{"layout":1,"get":1}
,"layout":{"object":1,"called":1}
,"object":{"focus":1,"script":1,"name":1,"active":1}
,"focus":{"calculation\u0027s":1,"function":1,"objects":1,"press":1,"field":1}
,"calculation\u0027s":{"current":1}
,"current":{"window":1,"layout":1}
,"window":{"get":1}
,"activelayoutobjectname":{"none":1,"returns":1,"get":1}
,"none":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"8.5":1}
,"8.5":{"layout":1}
,"function":{"returns":1}
,"empty":{"string":1}
,"string":{"clicking":1}
,"clicking":{"button":1}
,"button":{"popover":1,"panel":1,"tab":1}
,"popover":{"button":1}
,"panel":{"control":1,"slide":1,"named":1}
,"control":{"focus":1}
,"objects":{"focus":1}
,"press":{"tab":1}
,"tab":{"perform":1,"panel":1}
,"perform":{"object":1}
,"script":{"step":1}
,"step":{"navigate":1}
,"navigate":{"button":1}
,"slide":{"panel":1}
,"named":{"field":1}
,"field":{"current":1,"get":1}
,"called":{"customername":1}
,"customername":{"focus":1,"get":1}
,"active":{"layout":1,"object":1}
}
;Search.control.loadWordPairs(pairs);
