var pairs =
{
"finding":{"records":1}
,"records":{"perform":1,"table":1,"data":1,"browsed":1,"don\u2019t":1,"found":1,"open":1,"based":1}
,"perform":{"quick":1,"find":1}
,"quick":{"find":1}
,"find":{"browse":1,"selected":1,"helpful":1,"find":1,"mode":1,"request":1,"requests":1}
,"browse":{"mode":1}
,"mode":{"filemaker":1,"perform":1,"just":1,"based":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"searches":1}
,"searches":{"across":1,"all":1}
,"across":{"all":1}
,"all":{"fields":1,"records":1}
,"fields":{"enabled":1,"if":1}
,"enabled":{"quick":1}
,"selected":{"layout":1}
,"layout":{"quick":1}
,"helpful":{"if":1}
,"if":{"data":1,"don\u2019t":1}
,"data":{"multiple":1,"erforming":1,"table":1,"matching":1,"records":1,"managing":1}
,"multiple":{"fields":1}
,"don\u2019t":{"field":1,"match":1}
,"field":{"data":1,"selection":1,"finding":1}
,"erforming":{"quick":1}
,"table":{"comparing":1,"aking":1}
,"comparing":{"search":1}
,"search":{"criteria":1}
,"criteria":{"data":1,"found":1,"single":1}
,"aking":{"find":1}
,"request":{"records":1}
,"matching":{"criteria":1}
,"found":{"set":1}
,"set":{"subset":1,"find":1,"view":1}
,"subset":{"records":1}
,"browsed":{"records":1}
,"match":{"omitted":1}
,"omitted":{"constrain":1}
,"constrain":{"narrow":1}
,"narrow":{"extend":1}
,"extend":{"broaden":1}
,"broaden":{"found":1}
,"just":{"records":1}
,"view":{"edit":1}
,"edit":{"calculate":1}
,"calculate":{"summaries":1}
,"summaries":{"sort":1}
,"sort":{"print":1}
,"print":{"delete":1}
,"delete":{"export":1}
,"export":{"replace":1}
,"replace":{"data":1}
,"open":{"window":1}
,"window":{"order":1}
,"order":{"perform":1}
,"requests":{"data":1}
,"managing":{"files":1}
,"files":{"perform":1}
,"based":{"entire":1,"criteria":1}
,"entire":{"field":1}
,"selection":{"text":1}
,"text":{"field":1}
,"single":{"field":1}
}
;Search.control.loadWordPairs(pairs);
