var pairs =
{
"orking":{"pdf":1}
,"pdf":{"files":1,"unavailable":1,"file":1}
,"files":{"interactive":1}
,"interactive":{"container":1}
,"container":{"indows":1,"windows":1,"choose":1,"keyboard":1}
,"indows":{"sure":1}
,"sure":{"web":1}
,"web":{"browser":1}
,"browser":{"plug-in":1}
,"plug-in":{"adobe":1}
,"adobe":{"reader":1}
,"reader":{"installed":1}
,"installed":{"local":1,"insert":1}
,"local":{"computer":1}
,"computer":{"if":1}
,"if":{"installed":1}
,"insert":{"menu":1}
,"menu":{"pdf":1,"copy":1,"clear":1}
,"unavailable":{"pdf":1}
,"file":{"select":1,"interactive":1,"selected":1}
,"select":{"copy":1,"text":1}
,"copy":{"text":1,"press":1,"pdf":1,"macos":1,"delete":1}
,"text":{"pdf":1,"copy":1}
,"windows":{"select":1,"choose":1,"switch":1,"display":1}
,"press":{"ctrl":1,"command-c":1}
,"ctrl":{"macos":1,"windows":1,"shift":1}
,"macos":{"select":1,"hold":1}
,"command-c":{"choose":1}
,"choose":{"edit":1}
,"edit":{"menu":1}
,"hold":{"option":1}
,"option":{"key":1}
,"key":{"choose":1}
,"delete":{"pdf":1}
,"clear":{"pdf":1}
,"selected":{"interactive":1}
,"keyboard":{"shortcuts":1}
,"shortcuts":{"press":1}
,"switch":{"layout":1}
,"layout":{"mode":1}
,"mode":{"press":1}
,"shift":{"windows":1}
,"display":{"manage":1}
,"manage":{"database":1}
,"database":{"dialog":1}
,"dialog":{"box":1}
}
;Search.control.loadWordPairs(pairs);
