var pairs =
{
"setting":{"up":1}
,"up":{"field":1}
,"field":{"display":1,"inspector":1,"control":1,"if":1,"auto-complete":1,"calendar":1}
,"display":{"drop-down":1}
,"drop-down":{"calenda":1,"calendar":1}
,"calenda":{"layout":1}
,"layout":{"mode":1}
,"mode":{"select":1,"find":1,"se":1}
,"select":{"field":1}
,"inspector":{"data":1}
,"data":{"data":1,"tab":1}
,"tab":{"field":1}
,"control":{"style":1,"panel":1}
,"style":{"choose":1}
,"choose":{"drop-down":1}
,"calendar":{"selection":1,"displays":1,"icon":1,"automatically":1,"select":1}
,"selection":{"options":1}
,"options":{"include":1}
,"include":{"icon":1}
,"icon":{"show":1,"field":1,"browse":1}
,"show":{"hide":1}
,"hide":{"calendar":1}
,"displays":{"calendar":1}
,"if":{"option":1}
,"option":{"set":1}
,"set":{"calendar":1}
,"automatically":{"displayed":1}
,"displayed":{"user":1}
,"user":{"enters":1}
,"enters":{"field":1}
,"auto-complete":{"existing":1}
,"existing":{"values":1}
,"values":{"vailable":1}
,"vailable":{"fields":1}
,"fields":{"defined":1}
,"defined":{"text":1}
,"text":{"view":1}
,"view":{"drop-down":1}
,"browse":{"mode":1}
,"find":{"mode":1}
,"se":{"control":1}
,"panel":{"windows":1}
,"windows":{"system":1}
,"system":{"preferences":1}
,"preferences":{"macos":1}
,"macos":{"change":1}
,"change":{"day":1}
,"day":{"week":1}
,"week":{"drop-down":1}
}
;Search.control.loadWordPairs(pairs);
