var pairs =
{
"mporting":{"data":1,"folder":1,"xml":1}
,"data":{"existing":1,"source":1,"imported":1,"mporting":1,"odbc":1,"uerying":1,"filemaker":1,"want":1,"target":1,"ch":1,"layout":1,"matches":1,"correct":1,"each":1,"dialog":1,"new":1,"12":1}
,"existing":{"file":1,"filemaker":1,"records":1,"matching":1,"ecords":1,"table":1}
,"file":{"import":1,"filemaker":1,"created":1,"format":1,"type":1,"types":1,"formats":1,"you\u2019re":1,"undone":1,"menu":1,"located":1,"want":1,"perform":1,"if":1,"open":1,"displaying":1,"multiple":1,"sure":1,"replaces":1,"hoose":1,"dialog":1,"worksheet":1,"field":1,"choose":1,"filename":1,"11":1}
,"import":{"data":1,"found":1,"add":1,"read-only":1,"file":1,"sources":1,"folder":1,"records":1,"finding":1,"foreground":1,"import":1,"field":1,"if":1,"choose":1,"select":1,"action":1,"source":1,"details":1,"process":1}
,"filemaker":{"pro":1,"pr":1}
,"pro":{"advanced":1}
,"advanced":{"file":1,"ile":1,"setti":1,"supports":1,"source":1,"save":1,"upports":1,"if":1,"determines":1}
,"ile":{"file":1,"local":1,"data":1}
,"created":{"by":1}
,"by":{"application":1,"setting":1}
,"application":{"records":1,"application":1,"importing":1}
,"records":{"import":1,"pdate":1,"replace":1,"if":1,"backup":1,"replacing":1,"importing":1,"filemaker":1,"omit":1,"want":1,"closed":1,"imported":1,"target":1,"skip":1,"sure":1,"found":1,"file":1,"data":1}
,"found":{"set":1}
,"set":{"import":1,"current":1,"open":1,"records":1,"updated":1}
,"add":{"new":1}
,"new":{"records":1,"table":1}
,"pdate":{"atching":1}
,"atching":{"records":1}
,"replace":{"existing":1}
,"if":{"routinely":1,"you\u2019re":1,"importing":1,"import":1,"target":1,"match":1,"sort":1,"10":1}
,"routinely":{"import":1}
,"source":{"automate":1,"filemaker":1,"application":1,"file":1}
,"automate":{"process":1}
,"process":{"by":1,"etting":1}
,"setting":{"up":1}
,"up":{"recurring":1}
,"recurring":{"imports":1,"import":1}
,"imports":{"data":1,"topic":1}
,"imported":{"via":1,"found":1,"data":1}
,"via":{"recurring":1}
,"read-only":{"filemaker":1}
,"setti":{"ng":1}
,"ng":{"up":1}
,"topic":{"explains":1}
,"explains":{"import":1}
,"format":{"filemaker":1}
,"supports":{"import":1}
,"sources":{"topics":1}
,"topics":{"import":1}
,"folder":{"image":1,"files":1,"import":1}
,"image":{"files":1}
,"files":{"text":1,"all":1,"type":1,"current":1}
,"text":{"files":1}
,"all":{"mporting":1,"xml":1,"fields":1,"files":1}
,"xml":{"data":1}
,"odbc":{"data":1}
,"uerying":{"odbc":1}
,"importing":{"data":1,"updating":1,"records":1,"excel":1,"custom-separated":1}
,"save":{"data":1,"copy":1}
,"want":{"import":1,"update":1,"change":1}
,"type":{"filemaker":1,"windows":1,"file":1,"character":1}
,"upports":{"list":1}
,"list":{"supported":1,"choose":1}
,"supported":{"file":1,"import\u002Fexport":1}
,"types":{"supported":1}
,"import\u002Fexport":{"file":1}
,"formats":{"if":1}
,"you\u2019re":{"updating":1,"importing":1,"adding":1,"replacing":1}
,"updating":{"existing":1,"matching":1,"replacing":1,"atching":1}
,"matching":{"records":1}
,"backup":{"opy":1,"copy":1}
,"opy":{"target":1}
,"target":{"filemaker":1,"file":1,"table":1,"choose":1,"ile":1}
,"replacing":{"existing":1,"records":1,"xisting":1}
,"ecords":{"overwrites":1}
,"overwrites":{"data":1}
,"undone":{"safeguard":1}
,"safeguard":{"data":1}
,"ch":{"oose":1}
,"oose":{"file":1,"target":1}
,"menu":{"save":1,"display":1,"import":1}
,"copy":{"backup":1,"target":1}
,"local":{"file":1}
,"located":{"computer":1}
,"computer":{"sure":1}
,"sure":{"understand":1,"found":1}
,"understand":{"updating":1}
,"pr":{"advanced":1}
,"omit":{"open":1}
,"open":{"file":1,"filemaker":1,"if":1}
,"perform":{"find":1,"methods":1}
,"find":{"found":1}
,"current":{"window":1,"folder":1,"table":1}
,"window":{"records":1,"source":1}
,"finding":{"records":1}
,"determines":{"found":1}
,"foreground":{"window":1}
,"closed":{"file":1}
,"displaying":{"windows":1}
,"windows":{"al":1,"show":1}
,"al":{"records":1}
,"multiple":{"tables":1}
,"tables":{"use":1}
,"use":{"layout":1}
,"layout":{"pop-up":1,"table":1,"doesn\u2019t":1}
,"pop-up":{"menu":1}
,"display":{"layout":1,"all":1}
,"table":{"want":1,"fields":1,"import":1,"current":1,"name":1,"new":1,"importing":1,"creating":1,"imported":1}
,"doesn\u2019t":{"display":1}
,"fields":{"table":1,"want":1,"target":1,"during":1}
,"field":{"mapping":1,"data":1,"delimiter":1,"values":1}
,"mapping":{"dialog":1,"fields":1}
,"dialog":{"box":1}
,"box":{"if":1,"files":1,"choose":1,"import":1,"finishing":1}
,"adding":{"new":1}
,"skip":{"next":1}
,"next":{"step":1}
,"step":{"if":1}
,"update":{"records":1}
,"updated":{"if":1}
,"match":{"field":1}
,"matches":{"if":1}
,"xisting":{"records":1}
,"change":{"if":1}
,"sort":{"records":1}
,"correct":{"record":1}
,"record":{"source":1,"target":1}
,"replaces":{"data":1}
,"each":{"record":1}
,"hoose":{"file":1}
,"show":{"macos":1}
,"macos":{"select":1}
,"select":{"type":1,"file":1}
,"choose":{"all":1,"worksheet":1,"character":1,"type":1,"file":1,"import":1,"existing":1}
,"excel":{"file":1,"data":1}
,"worksheet":{"includes":1,"named":1}
,"includes":{"named":1}
,"named":{"range":1}
,"range":{"excel":1,"import":1}
,"custom-separated":{"values":1}
,"values":{"file":1,"source":1}
,"delimiter":{"dialog":1}
,"character":{"list":1,"separates":1}
,"separates":{"field":1}
,"filename":{"extension":1}
,"extension":{".tab":1}
,".tab":{".txt":1}
,".txt":{"rename":1}
,"rename":{"source":1}
,"10":{"import":1}
,"action":{"icon":1,"perform":1,"mapping":1}
,"icon":{"choose":1}
,"methods":{"importing":1}
,"11":{"ch":1}
,"name":{"new":1}
,"creating":{"new":1}
,"12":{"ma":1}
,"ma":{"fields":1}
,"details":{"import":1}
,"finishing":{"import":1}
,"etting":{"import":1}
,"during":{"import":1}
}
;Search.control.loadWordPairs(pairs);
