var pairs =
{
"middlewords":{"returns":1,"text":1,"plaid":1,"name":1}
,"returns":{"text":1,"middlewords":1,"canvas":1,"brigitte":1}
,"text":{"numberofwords":1,"starting":1,"startingword":1,"-any":1,"expression":1,"field":1,"filemaker":1,"function":1}
,"numberofwords":{"text":1,"-any":1}
,"starting":{"startingword":1}
,"startingword":{"middlewords":1,"numberofwords":1,"-any":1,"function":1,"=1":1,"greater":1}
,"-any":{"text":1,"numeric":1}
,"expression":{"text":1,"field":1}
,"field":{"startingword":1,"number":1,"brigitte":1}
,"numeric":{"expression":1}
,"number":{"numberofwords":1,"text":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"if":1}
,"if":{"startingword":1}
,"function":{"evaluated":1,"returns":1}
,"evaluated":{"if":1}
,"=1":{"if":1}
,"greater":{"number":1}
,"plaid":{"canvas":1}
,"canvas":{"suitcase":1}
,"suitcase":{";2;2":1,"middlewords":1}
,";2;2":{"returns":1}
,"name":{";1;2":1,"field":1}
,";1;2":{"returns":1}
,"brigitte":{"erika":1}
,"erika":{"name":1,"durand":1}
}
;Search.control.loadWordPairs(pairs);
