var pairs =
{
"print":{"setup":1,"options":1,"invoices":1,"settings":1,"[with":1}
,"setup":{"ets":1,"dialog":1,"allows":1,"options":1,"[restore":1}
,"ets":{"print":1}
,"options":{"paper":1,"stored":1,"pdfs":1}
,"paper":{"size":1}
,"size":{"orientation":1}
,"orientation":{"stored":1}
,"stored":{"script":1}
,"script":{"step":1}
,"step":{"dialog":1,"performed":1,"last":1,"page":1,"restore":1,"filemaker":1,"sets":1,"print":1}
,"dialog":{"specifies":1,"box":1,"output":1,"option":1,"off]":1,"on]":1}
,"specifies":{"display":1}
,"display":{"print":1}
,"box":{"script":1}
,"performed":{"if":1}
,"if":{"set":1}
,"set":{"dialog":1}
,"output":{"script":1}
,"last":{"printer":1}
,"printer":{"printer":1,"script":1}
,"page":{"setup":1}
,"allows":{"choose":1}
,"choose":{"page":1}
,"restore":{"page":1}
,"filemaker":{"pro":1,"server":1,"cloud":1,"webdirect":1}
,"pro":{"6.0":1}
,"6.0":{"earlie":1}
,"earlie":{"filemaker":1}
,"server":{"filemaker":1}
,"cloud":{"ilemaker":1}
,"ilemaker":{"go":1,"webdirect":1}
,"go":{"filemaker":1,"layout":1}
,"webdirect":{"ot":1,"script":1}
,"ot":{"support":1}
,"support":{"dialog":1}
,"option":{"filemaker":1}
,"sets":{"options":1}
,"pdfs":{"created":1}
,"created":{"ave":1}
,"ave":{"records":1}
,"records":{"pdf":1,"print":1,"[restore":1}
,"pdf":{"script":1}
,"invoices":{"layout":1,"\u0022]":1}
,"layout":{"sorts":1,"[\u0022":1}
,"sorts":{"records":1}
,"settings":{"prints":1}
,"prints":{"go":1}
,"[\u0022":{"print":1}
,"\u0022]":{"sort":1}
,"sort":{"records":1}
,"[restore":{"dialog":1}
,"off]":{"print":1}
,"[with":{"dialog":1}
,"on]":{"previewing":1}
,"previewing":{"printing":1}
,"printing":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
