var pairs =
{
"sert":{"audio\u002Fvideo":1}
,"audio\u002Fvideo":{"mports":1,"performed":1,"returns":1,"[\u0022":1,"[reference":1}
,"mports":{"audio":1}
,"audio":{"video":1,"file":1}
,"video":{"file":1,"interactive":1}
,"file":{"file":1,"reference":1,"container":1,"option":1,"if":1,"referenced":1,"specifies":1,"intend":1,"path":1,"paths":1,"source":1,"imported":1,"options":1,"relative":1,"media":1}
,"reference":{"current":1,"instructs":1,"source":1,"set":1}
,"current":{"interactive":1}
,"interactive":{"container":1,"containers":1}
,"container":{"store":1,"field":1,"file":1,"fields":1}
,"store":{"reference":1,"link":1}
,"instructs":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"advanced":1,"12.0":1}
,"advanced":{"store":1,"file":1,"display":1,"displays":1}
,"link":{"audio":1}
,"field":{"actual":1,"field":1,"use":1,"script":1,"layout":1,"inserts":1,"[customers":1,"active":1,"by":1}
,"actual":{"file":1}
,"option":{"reduce":1,"filemaker":1}
,"reduce":{"size":1}
,"size":{"filemaker":1}
,"if":{"move":1,"active":1}
,"move":{"delete":1}
,"delete":{"file":1}
,"referenced":{"filemaker":1}
,"display":{"source":1}
,"source":{"file":1}
,"specifies":{"audio":1}
,"intend":{"insert":1}
,"insert":{"interactive":1,"audio\u002Fvideo":1}
,"path":{"movie":1,"movie:audio\u002Fmusic.mp3":1}
,"movie":{"moviemac":1}
,"moviemac":{"oviewin":1}
,"oviewin":{"movielinux":1}
,"movielinux":{"creating":1}
,"creating":{"file":1}
,"paths":{"filemaker":1}
,"12.0":{"field":1}
,"use":{"go":1}
,"go":{"field":1}
,"script":{"step":1,"performed":1}
,"step":{"performing":1,"insert":1,"interactive":1}
,"performing":{"script":1}
,"performed":{"file":1,"insert":1}
,"displays":{"dialog":1}
,"dialog":{"box":1}
,"box":{"user":1}
,"user":{"select":1}
,"select":{"preview":1}
,"preview":{"file":1}
,"imported":{"filemaker":1}
,"webdirect":{"support":1}
,"support":{"store":1}
,"options":{"if":1}
,"active":{"container":1}
,"layout":{"script":1}
,"returns":{"error":1}
,"error":{"code":1}
,"code":{"captured":1}
,"captured":{"get":1}
,"get":{"lasterror":1,"documentspath":1}
,"lasterror":{"function":1}
,"function":{"script":1}
,"containers":{"pecifying":1,"automating":1}
,"pecifying":{"formats":1}
,"formats":{"container":1}
,"fields":{"list":1,"media":1}
,"list":{"supported":1}
,"supported":{"media":1}
,"media":{"types":1,"field":1,"file":1,"name":1,"files":1}
,"types":{"data":1}
,"data":{"container":1}
,"inserts":{"audio":1,"media":1}
,"relative":{"path":1}
,"movie:audio\u002Fmusic.mp3":{"go":1}
,"[customers":{":media]":1}
,":media]":{"insert":1}
,"[\u0022":{"usic.mp3":1}
,"usic.mp3":{"\u0022]":1}
,"\u0022]":{"inserts":1,"sound":1}
,"name":{"field":1}
,"by":{"reference":1}
,"set":{"variable":1}
,"variable":{"[$media_path":1}
,"[$media_path":{"value":1}
,"value":{"get":1}
,"documentspath":{"&products":1}
,"&products":{":media":1}
,":media":{"name]":1}
,"name]":{"insert":1}
,"[reference":{"\u0022$media_path":1}
,"\u0022$media_path":{"\u0022]":1}
,"sound":{"movies":1}
,"movies":{"songs":1}
,"songs":{"clips":1}
,"clips":{"multimedia":1}
,"multimedia":{"media":1}
,"files":{"audio":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
