var pairs =
{
"efining":{"fu":1}
,"fu":{"rigana":1}
,"rigana":{"options":1}
,"options":{"furigana":1,"double-click":1,"field":1}
,"furigana":{"option":1,"tab":1,"field":1}
,"option":{"japanese-specific":1,"automatically":1}
,"japanese-specific":{"feature":1}
,"feature":{"enters":1,"stores":1}
,"enters":{"field":1,"kana":1}
,"field":{"kana":1,"japanese":1,"set":1,"two":1,"hold":1,"options":1,"dialog":1,"select":1,"display":1,"compliant":1,"file":1,"shared":1}
,"kana":{"reading":1,"hiragana":1,"readings":1,"data":1,"translate":1,"format":1,"generated":1,"furigana":1}
,"reading":{"japanese":1}
,"japanese":{"text":1}
,"text":{"that\u2019s":1,"compose":1,"fields":1,"options":1}
,"that\u2019s":{"entered":1}
,"entered":{"field":1,"nother":1,"generates":1,"choose":1,"furigana":1,"updated":1}
,"compose":{"kana":1}
,"hiragana":{"katakana":1}
,"katakana":{"kanji":1}
,"kanji":{"characters":1,"entered":1,"text":1}
,"characters":{"field":1}
,"set":{"furigana":1}
,"automatically":{"enters":1}
,"readings":{"kanji":1}
,"nother":{"field":1}
,"two":{"text":1}
,"fields":{"feature":1,"tab":1}
,"stores":{"data":1}
,"data":{"entered":1}
,"generates":{"kana":1}
,"choose":{"file":1,"table":1,"kana":1}
,"file":{"menu":1,"furigana":1}
,"menu":{"manage":1}
,"manage":{"database":1}
,"database":{"fields":1}
,"tab":{"if":1,"select":1}
,"if":{"displayed":1,"choose":1}
,"displayed":{"if":1}
,"table":{"table":1,"list":1}
,"list":{"select":1}
,"select":{"field":1,"use":1}
,"hold":{"kanji":1}
,"double-click":{"field":1}
,"dialog":{"box":1}
,"box":{"furigana":1}
,"use":{"furigana":1}
,"display":{"kana":1}
,"translate":{"choose":1}
,"format":{"furigana":1}
,"generated":{"entered":1}
,"compliant":{"input":1}
,"input":{"method":1}
,"method":{"manually":1}
,"manually":{"edit":1}
,"edit":{"kana":1}
,"shared":{"client\u0027s":1}
,"client\u0027s":{"operating":1}
,"operating":{"system":1}
,"system":{"determines":1}
,"determines":{"kana":1}
,"updated":{"define":1}
,"define":{"urigana":1}
,"urigana":{"options":1}
}
;Search.control.loadWordPairs(pairs);
