var pairs =
{
"date":{"functions":1,"system":1,"calendar":1,"onth":1,"occurs":1,"month":1,"function":1,"6;0;2019":1}
,"functions":{"date":1,"calculate":1}
,"calculate":{"dates":1}
,"dates":{"manipulate":1,"displayed":1}
,"manipulate":{"date":1}
,"system":{"formats":1}
,"formats":{"affect":1,"function":1}
,"affect":{"dates":1}
,"displayed":{"files":1}
,"files":{"system":1}
,"function":{"returns":1,"arguments":1}
,"returns":{"date":1,"5\u002F31\u002F2019":1}
,"calendar":{"date":1}
,"onth":{"day":1}
,"day":{"year":1,"number":1,"month":1,"week":1}
,"year":{"day":1,"date":1,"ate":1,"number":1}
,"number":{"day":1,"representing":1,"days":1,"weeks":1}
,"month":{"ate":1,"number":1,"year":1}
,"ate":{"occurs":1,"dayofweek":1,"weekofyear":1,"weekofyearfiscal":1,"starting":1}
,"occurs":{"dayname":1,"dayofyear":1,"monthname":1,"use":1}
,"dayname":{"text":1}
,"text":{"hat":1}
,"hat":{"full":1}
,"full":{"name":1}
,"name":{"weekday":1,"month":1}
,"weekday":{"ate":1}
,"dayofweek":{"number":1}
,"representing":{"day":1,"th":1,"week":1,"year":1}
,"week":{"date":1,"ate":1}
,"dayofyear":{"number":1}
,"days":{"year":1}
,"th":{"month":1}
,"monthname":{"full":1}
,"weekofyear":{"number":1}
,"weeks":{"january":1}
,"january":{"year":1}
,"weekofyearfiscal":{"number":1}
,"starting":{"day":1}
,"use":{"zero":1}
,"zero":{"negative":1}
,"negative":{"numbers":1}
,"numbers":{"date":1}
,"arguments":{"formula":1}
,"formula":{"returns":1}
,"5\u002F31\u002F2019":{"date":1}
}
;Search.control.loadWordPairs(pairs);
