var pairs =
{
"reventing":{"database":1}
,"database":{"damage":1,"back":1}
,"damage":{"file":1,"ensure":1}
,"file":{"corruption":1}
,"corruption":{"inevitable":1}
,"inevitable":{"idea":1}
,"idea":{"take":1}
,"take":{"measures":1}
,"measures":{"prevent":1}
,"prevent":{"damage":1}
,"ensure":{"databases":1}
,"databases":{"properly":1,"frequently":1,"first":1,"run":1}
,"properly":{"backed":1}
,"backed":{"up":1}
,"up":{"routine":1,"heavily":1}
,"routine":{"backups":1}
,"backups":{"re":1}
,"re":{"recommended":1}
,"recommended":{"database":1}
,"back":{"up":1}
,"heavily":{"databases":1}
,"frequently":{"lose":1}
,"lose":{"day":1}
,"day":{"use":1}
,"use":{"uninterruptible":1,"virus":1}
,"uninterruptible":{"power":1}
,"power":{"supply":1}
,"supply":{"check":1}
,"check":{"condition":1}
,"condition":{"hard":1}
,"hard":{"disk":1}
,"disk":{"drive":1,"current":1}
,"drive":{"utility":1}
,"utility":{"program":1}
,"program":{"sure":1}
,"sure":{"software":1,"driver":1}
,"software":{"optimizes":1,"compatible":1,"run":1,"open":1}
,"optimizes":{"compresses":1}
,"compresses":{"partitions":1}
,"partitions":{"hard":1}
,"current":{"sure":1}
,"driver":{"software":1}
,"compatible":{"operating":1}
,"operating":{"system":1}
,"system":{"version":1}
,"version":{"use":1}
,"virus":{"detection":1,"protection":1}
,"detection":{"software":1}
,"run":{"virus":1}
,"protection":{"software":1}
,"open":{"hosted":1}
,"hosted":{"databases":1}
,"first":{"close":1}
,"close":{"databases":1}
}
;Search.control.loadWordPairs(pairs);
