var pairs =
{
"text":{"operators":1,"items":1,"constants":1,"string":1,"strings":1,"constant":1,"empty":1,"if":1,"formula":1,"field":1,"comments":1}
,"operators":{"use":1,"combine":1}
,"use":{"text":1}
,"combine":{"two":1}
,"two":{"text":1}
,"items":{"larger":1}
,"larger":{"item":1}
,"item":{"text":1}
,"constants":{"formula":1,"enclosed":1}
,"formula":{"format":1,"represent":1,"symbol":1,"quotation":1,"\u002F**\u002Fc":1,"\u002F\u002Fc":1,"${":1,"concatenates":1}
,"format":{"formula":1}
,"represent":{"special":1}
,"special":{"characters":1}
,"characters":{"formula":1,"considered":1}
,"symbol":{"name":1}
,"name":{"definition":1,"\u005Cbackslash":1,"identifies":1,"separated":1}
,"definition":{"&concatenate":1}
,"&concatenate":{"appends":1}
,"appends":{"text":1}
,"string":{"right":1,"left":1}
,"right":{"end":1}
,"end":{"text":1,"characters":1}
,"left":{"text":1}
,"strings":{"fields":1}
,"fields":{"constants":1}
,"enclosed":{"quotes":1}
,"quotes":{"functions":1}
,"functions":{"text":1}
,"constant":{"marks":1,"quotation":1}
,"marks":{"end":1,"text":1,"filemaker":1,"operator":1}
,"considered":{"text":1}
,"quotation":{"marks":1}
,"empty":{"value":1}
,"value":{"text":1}
,"if":{"enter":1}
,"enter":{"text":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"ries":1}
,"ries":{"interpret":1}
,"interpret":{"text":1}
,"field":{"function":1,"names":1}
,"function":{"name":1,"names":1}
,"\u005Cbackslash":{"marks":1}
,"operator":{"character":1,"carriage":1}
,"character":{"character":1,"operator":1}
,"carriage":{"return":1}
,"return":{"inserts":1,"result":1}
,"inserts":{"paragraph":1}
,"paragraph":{"carriage":1}
,"result":{"formula":1}
,"\u002F**\u002Fc":{"style":1}
,"style":{"comment":1}
,"comment":{"marks":1,"identifies":1,"formula":1}
,"comments":{"formula":1}
,"\u002F\u002Fc":{"style":1}
,"identifies":{"single-line":1,"reserved":1}
,"single-line":{"comment":1}
,"${":{"reserved":1}
,"reserved":{"name":1,"function":1}
,"names":{"keywords":1,"table":1,"formula":1}
,"keywords":{"field":1}
,"table":{"names":1}
,"concatenates":{"first":1}
,"first":{"last":1}
,"last":{"name":1}
,"separated":{"by":1}
,"by":{"space":1}
,"space":{"firstname":1}
,"firstname":{"&\u0022":1}
,"&\u0022":{"&lastname":1}
,"&lastname":{"michelle":1}
,"michelle":{"cannon":1}
}
;Search.control.loadWordPairs(pairs);
