var pairs =
{
"abs":{"returns":1,"number":1,"function":1,"(-123":1,"pricedifference":1,"targetdate":1}
,"returns":{"absolute":1,"123":1,"positive":1}
,"absolute":{"value":1}
,"value":{"number":1,"abs":1}
,"number":{"abs":1,"number":1,"-any":1,"time":1,"positive":1,"appears":1,"pricedifference":1,"days":1}
,"-any":{"numeric":1}
,"numeric":{"expression":1}
,"expression":{"field":1,"number":1}
,"field":{"numeric":1,"abs":1}
,"time":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"absolute":1}
,"positive":{"if":1,"value":1}
,"if":{"negative":1}
,"negative":{"number":1}
,"appears":{"field":1}
,"function":{"removes":1}
,"removes":{"minus":1}
,"minus":{"sign":1}
,"sign":{"positive":1}
,"(-123":{"returns":1}
,"123":{"abs":1}
,"pricedifference":{"returns":1,"field":1}
,"targetdate":{"-actualdate":1,"actualdate":1}
,"-actualdate":{"returns":1}
,"days":{"difference":1}
,"difference":{"values":1}
,"values":{"targetdate":1}
}
;Search.control.loadWordPairs(pairs);
