var pairs =
{
"get":{"windowst":1,"windowstyle":1,"window":1}
,"windowst":{"yle":1}
,"yle":{"returns":1}
,"returns":{"style":1,"zero":1,"returns":1,"if":1}
,"style":{"window":1}
,"window":{"script":1,"document":1,"if":1,"floating":1,"dialog":1,"card":1,"filemaker":1,"function":1,"style":1}
,"script":{"acting":1}
,"acting":{"get":1,"foreground":1}
,"windowstyle":{"none":1,"get":1}
,"none":{"number":1}
,"number":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"12.0":1}
,"12.0":{"returns":1}
,"zero":{"if":1}
,"if":{"window":1,"current":1}
,"document":{"window":1}
,"floating":{"document":1}
,"dialog":{"window":1}
,"card":{"window":1}
,"foreground":{"window":1}
,"webdirect":{"function":1}
,"function":{"returns":1,"evaluated":1}
,"current":{"window":1}
,"evaluated":{"get":1}
}
;Search.control.loadWordPairs(pairs);
