var pairs =
{
"ad":{"account":1}
,"account":{"dds":1,"name":1,"password":1,"privilege":1,"names":1,"data":1,"add":1,"[account":1,"read-only":1,"accounts":1,"current":1,"\u0022]":1}
,"dds":{"new":1}
,"new":{"account":1,"privilege":1,"user":1,"data":1}
,"name":{"password":1,"name":1,"new":1,"user":1,"accounts":1,"if":1,"get":1}
,"password":{"privilege":1,"password":1,"new":1,"next":1,"literals":1,"1234":1,"custom":1,"accounts":1}
,"privilege":{"set":1,"sets":1}
,"set":{"account":1,"assign":1,"user":1,"full":1,"assigned":1,"up":1,"perform":1,"[data":1,"[read-only":1}
,"assign":{"predefined":1}
,"predefined":{"privilege":1}
,"user":{"create":1,"change":1,"account":1,"password":1,"read-only":1}
,"create":{"new":1}
,"full":{"access":1}
,"access":{"privilege":1,"privileges":1}
,"assigned":{"via":1,"full":1}
,"via":{"script":1}
,"script":{"step":1,"script":1,"pane":1}
,"step":{"accounts":1,"generated":1,"enable":1,"right-click":1}
,"accounts":{"full":1,":name":1,":password]":1,":password":1,"automating":1}
,"sets":{"created":1}
,"created":{"manually":1}
,"manually":{"user":1}
,"change":{"password":1}
,"next":{"login":1,"time":1}
,"login":{"forces":1}
,"forces":{"users":1}
,"users":{"change":1,"less":1}
,"time":{"log":1}
,"log":{"database":1,"account":1}
,"database":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"7.0":1}
,"7.0":{"account":1}
,"literals":{"stored":1}
,"stored":{"script":1}
,"generated":{"runtime":1}
,"runtime":{"based":1}
,"based":{"calculations":1}
,"calculations":{"set":1}
,"up":{"account":1}
,"names":{"unique":1}
,"unique":{"assigned":1}
,"perform":{"script":1}
,"enable":{"users":1}
,"less":{"full":1}
,"privileges":{"perform":1,"adds":1,"requires":1,"name":1,"current":1,"add":1}
,"right-click":{"current":1}
,"current":{"script":1,"user":1,"user\u0027s":1}
,"pane":{"choose":1}
,"choose":{"grant":1}
,"grant":{"full":1}
,"adds":{"new":1}
,"data":{"entry":1}
,"entry":{"privileges":1,"only]":1,"account":1}
,"requires":{"change":1}
,"add":{"account":1,"new":1}
,"[account":{"name":1}
,"1234":{"privilege":1}
,"[data":{"entry":1}
,"only]":{"expire":1}
,"expire":{"password]":1}
,"password]":{"adds":1,"else":1}
,"read-only":{"privileges":1}
,"custom":{"dialog":1}
,"dialog":{"box":1,"[\u0022":1}
,"box":{"show":1}
,"show":{"custom":1}
,"[\u0022":{"want":1,"privileges":1}
,"want":{"add":1}
,":name":{"accounts":1,"password":1}
,":password]":{"if":1}
,"if":{"[get":1,"adds":1,"creating":1}
,"[get":{"lastmessagechoice":1,"accountprivilegesetname":1}
,"lastmessagechoice":{"=1]":1}
,"=1]":{"add":1}
,":password":{"privilege":1}
,"[read-only":{"access]":1}
,"access]":{"\u0022]":1}
,"\u0022]":{"end":1,"add":1}
,"end":{"if":1}
,"user\u0027s":{"name":1}
,"accountprivilegesetname":{"[read-only":1}
,"get":{"username":1}
,"username":{"password":1}
,"else":{"show":1}
,"creating":{"editing":1}
,"editing":{"accounts":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
