var pairs =
{
"textformatremove":{"removes":1,"text":1,"plaid":1}
,"removes":{"all":1}
,"all":{"text":1,"fonts":1}
,"text":{"formatting":1,"single":1,"text":1,"-any":1,"expression":1,"field":1,"filemaker":1,"textformatremove":1}
,"formatting":{"text":1,"applied":1}
,"single":{"action":1}
,"action":{"textformatremove":1}
,"-any":{"text":1}
,"expression":{"text":1}
,"field":{"text":1}
,"filemaker":{"pro":1}
,"pro":{"8.0":1}
,"8.0":{"use":1}
,"use":{"function":1}
,"function":{"remove":1}
,"remove":{"all":1}
,"fonts":{"styles":1}
,"styles":{"font":1}
,"font":{"sizes":1,"colors":1}
,"sizes":{"font":1}
,"colors":{"text":1}
,"plaid":{"returns":1,"text":1}
,"returns":{"word":1}
,"word":{"plaid":1}
}
;Search.control.loadWordPairs(pairs);
