var pairs =
{
"textfont":{"font":1,"text":1,"plaid":1,"textcolor":1}
,"font":{"text":1,"name":1,"names":1,"textfont":1,"textsize":1}
,"text":{"fontname":1,"-any":1,"expression":1,"field":1,"text":1,"filemaker":1,"formatting":1,"textfont":1,"contained":1,"courier":1}
,"fontname":{"textfont":1,"text":1,"-any":1}
,"-any":{"text":1,"font":1}
,"expression":{"text":1}
,"field":{"fontname":1,"type":1}
,"name":{"expressed":1}
,"expressed":{"text":1}
,"filemaker":{"pro":1}
,"pro":{"7.0":1}
,"7.0":{"spellings":1}
,"spellings":{"font":1}
,"names":{"correct":1}
,"correct":{"text":1}
,"formatting":{"options":1}
,"options":{"lost":1}
,"lost":{"if":1}
,"if":{"field":1}
,"type":{"returned":1}
,"returned":{"text":1}
,"plaid":{"courier":1,"arial":1}
,"courier":{"returns":1,"font":1,"12":1}
,"returns":{"word":1,"text":1}
,"word":{"plaid":1}
,"arial":{"returns":1,"font":1}
,"textsize":{"textfont":1}
,"textcolor":{"mytable":1}
,"mytable":{":mytext":1}
,":mytext":{"rgb":1,"formatted":1}
,"rgb":{"125":1}
,"125":{"125":1,"courier":1}
,"12":{"returns":1}
,"contained":{"mytable":1}
,"formatted":{"12pt":1}
,"12pt":{"green":1}
,"green":{"text":1}
}
;Search.control.loadWordPairs(pairs);
