var pairs =
{
"nserting":{"date":1,"merge":1}
,"date":{"page":1,"entered":1,"print":1,"time":1,"fixed":1,"computer\u0027s":1,"static":1,"current":1,"symbol":1,"date":1,"show":1,"add":1}
,"page":{"number":1,"numbers":1,"10":1}
,"number":{"variable":1,"symbol":1,"page":1,"row":1,"inserted":1,"add":1}
,"variable":{"layout":1,"today\u2019s":1,"date":1,"time":1,"user":1,"variable":1,"you\u2019ve":1,"browse":1,"ormatting":1,"text":1,"insert":1}
,"layout":{"display":1,"stays":1,"mode":1,"<$$>":1,"note":1}
,"display":{"print":1,"current":1,"date":1,"page":1,"all":1}
,"print":{"fixed":1,"preview":1,"report":1,"layout":1}
,"fixed":{"date":1,"time":1,"user":1}
,"entered":{"variable":1}
,"today\u2019s":{"date":1}
,"preview":{"records":1,"mode":1,"modes":1}
,"records":{"display":1,"insert":1}
,"current":{"time":1,"date":1,"user":1}
,"time":{"report":1,"print":1,"user":1,"fixed":1,"computer\u0027s":1,"static":1,"current":1,"symbol":1,"time":1,"show":1,"add":1}
,"report":{"footer":1,"display":1,"pagenumber":1,"se":1}
,"footer":{"each":1}
,"each":{"time":1}
,"user":{"name":1}
,"name":{"place":1,"field":1,"fixed":1,"user":1,"preferences":1,"static":1,"date":1,"symbol":1,"name":1,"show":1}
,"place":{"layout":1,"insertion":1}
,"stays":{"display":1}
,"insert":{"current":1,"menu":1,"layout":1,"dialog":1,"symbol":1,"time":1,"date":1}
,"field":{"browse":1,"objects":1}
,"browse":{"mode":1,"find":1}
,"mode":{"layout":1,"selection":1,"current":1,"printed":1,"currentdate":1,"if":1,"preview":1,"text":1}
,"selection":{"tool":1}
,"tool":{"selection":1,"status":1}
,"status":{"toolbar":1}
,"toolbar":{"want":1}
,"want":{"if":1,"inserted":1,"place":1}
,"if":{"want":1,"insert":1,"resize":1}
,"inserted":{"existing":1,"portal":1}
,"existing":{"text":1}
,"text":{"object":1,"color":1,"block":1,"fit":1,"contents":1,"resizing":1}
,"object":{"double-click":1}
,"double-click":{"want":1}
,"insertion":{"point":1}
,"point":{"choose":1}
,"choose":{"insert":1,"commands":1}
,"menu":{"choose":1,"type":1}
,"commands":{"choose":1,"insert":1}
,"computer\u0027s":{"calendar":1,"clock":1}
,"calendar":{"date":1,"currentdate":1}
,"static":{"change":1}
,"change":{"current":1,"user\u0027s":1}
,"clock":{"time":1,"currenttime":1}
,"preferences":{"name":1,"username":1}
,"user\u0027s":{"name":1}
,"symbol":{"variable":1,"page":1,"record":1,"result":1,"insert":1,"variable\u0027s":1,"appears":1,"commands":1,"variables":1,"browse":1,"expands":1}
,"show":{"current":1,"user":1}
,"currentdate":{"time":1,"value":1}
,"currenttime":{"user":1,"insert":1}
,"username":{"page":1}
,"numbers":{"preview":1}
,"printed":{"report":1}
,"pagenumber":{"record":1}
,"record":{"number":1}
,"row":{"number":1,"recordnumber":1}
,"portal":{"row":1}
,"recordnumber":{"symbol":1}
,"result":{"get":1}
,"get":{"function":1,"unctions":1}
,"function":{"flag":1}
,"flag":{"flags":1,"chose":1}
,"flags":{"get":1}
,"unctions":{"get":1}
,"chose":{"select":1}
,"select":{"symbol":1}
,"dialog":{"box":1}
,"box":{"surrounded":1}
,"surrounded":{"by":1}
,"by":{"double":1}
,"double":{"races":1}
,"races":{"accountname":1,"set":1}
,"accountname":{"merge":1}
,"merge":{"variable":1,"variables":1}
,"you\u2019ve":{"created":1}
,"created":{"display":1}
,"10":{"report":1}
,"se":{"nserting":1}
,"variables":{"layout":1,"case":1}
,"<$$>":{"if":1}
,"variable\u0027s":{"symbol":1}
,"appears":{"layout":1}
,"value":{"variable":1}
,"find":{"preview":1}
,"modes":{"print":1}
,"note":{"type":1}
,"type":{"characters":1,"currenttime":1}
,"characters":{"listed":1,"races":1}
,"listed":{"symbol":1}
,"case":{"sensitive":1}
,"sensitive":{"contain":1}
,"contain":{"spaces":1}
,"spaces":{"extra":1}
,"extra":{"characters":1}
,"set":{"formatting":1}
,"formatting":{"options":1}
,"options":{"font":1}
,"font":{"style":1}
,"style":{"line":1}
,"line":{"spacing":1}
,"spacing":{"text":1}
,"color":{"alignment":1}
,"alignment":{"variable":1}
,"ormatting":{"setting":1}
,"setting":{"up":1}
,"up":{"field":1}
,"objects":{"layout":1,"add":1}
,"resize":{"text":1}
,"block":{"variable\u2019s":1,"displays":1,"clipped":1,"display":1}
,"variable\u2019s":{"symbol":1}
,"displays":{"prints":1}
,"prints":{"text":1}
,"fit":{"dimensions":1}
,"dimensions":{"symbol":1}
,"expands":{"replaced":1}
,"replaced":{"variable":1}
,"contents":{"text":1}
,"clipped":{"entirety":1}
,"entirety":{"if":1}
,"all":{"text":1}
,"resizing":{"reshaping":1}
,"reshaping":{"objects":1}
,"add":{"date":1,"page":1,"time":1,"variable":1}
}
;Search.control.loadWordPairs(pairs);
