var pairs =
{
"aking":{"find":1}
,"find":{"request":1,"records":1,"fields":1,"filemaker":1,"mode":1,"first":1,"status":1,"find":1,"windows":1,"macos":1,"operation":1,"requests":1,"data":1,"field":1,"related":1,"all":1,"saved":1}
,"request":{"find":1,"blank":1,"select":1,"returns":1,"recent":1,"tips":1}
,"records":{"search":1,"match":1,"replace":1,"matching":1,"displayed":1,"database":1,"browse":1,"choose":1,"performing":1,"tables":1,"related":1,"portal":1}
,"search":{"criteria":1,"find":1}
,"criteria":{"type":1,"value":1,"entered":1,"search":1,"jo@n":1,"perform":1,"container":1,"enter":1}
,"type":{"criteria":1,"value":1}
,"value":{"values":1,"field":1}
,"values":{"find":1,"indexed":1}
,"fields":{"find":1,"want":1,"calculation":1,"referencing":1,"take":1,"defining":1,"summary":1,"global":1,"web":1,"create":1,"perform":1,"confirms":1}
,"blank":{"record":1}
,"record":{"perform":1,"matching":1}
,"perform":{"find":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"searches":1,"displays":1}
,"searches":{"records":1,"all":1}
,"match":{"criteria":1}
,"entered":{"matching":1}
,"matching":{"records":1,"specific":1,"criteria":1}
,"replace":{"previous":1}
,"previous":{"found":1}
,"found":{"set":1}
,"set":{"find":1,"criteria":1,"records.the":1,"omitted":1,"unchanged":1,"inds":1}
,"mode":{"fr":1,"saved":1,"arrow":1,"show":1,"choose":1,"badge":1,"check":1}
,"fr":{"om":1}
,"om":{"layout":1}
,"layout":{"pop-up":1,"fields":1,"bar":1}
,"pop-up":{"menu":1,"menus":1}
,"menu":{"select":1,"perform":1,"show":1}
,"select":{"layout":1,"field":1}
,"want":{"search":1}
,"field":{"use":1,"indexing":1,"index":1,"describes":1,"perform":1,"data":1,"filemaker":1,"portal":1}
,"use":{"finding":1,"insert":1,"index":1}
,"finding":{"hen":1,"text":1}
,"hen":{"type":1}
,"insert":{"operators":1}
,"operators":{"list":1,"omit":1}
,"list":{"layout":1,"recent":1,"cancel":1,"find":1}
,"bar":{"help":1}
,"help":{"enter":1}
,"enter":{"criteria":1,"values":1,"search":1,"invoice":1}
,"jo@n":{"find":1}
,"first":{"names":1}
,"names":{"john":1}
,"john":{"joan":1}
,"joan":{"finding":1}
,"text":{"characters":1,"number":1}
,"characters":{"operators":1}
,"omit":{"exclude":1}
,"exclude":{"records":1}
,"specific":{"set":1}
,"status":{"toolbar":1}
,"toolbar":{"choose":1,"portion":1}
,"choose":{"requests":1,"find":1,"show":1,"clear":1}
,"requests":{"menu":1,"field":1}
,"returns":{"found":1}
,"records.the":{"highlighted":1}
,"highlighted":{"rea":1}
,"rea":{"pie":1}
,"pie":{"chart":1}
,"chart":{"pie":1,"icon":1,"switch":1}
,"icon":{"status":1,"fields":1}
,"portion":{"total":1}
,"total":{"records":1}
,"displayed":{"pie":1}
,"switch":{"etween":1}
,"etween":{"found":1}
,"omitted":{"records":1}
,"database":{"access":1}
,"access":{"list":1}
,"recent":{"finds":1}
,"finds":{"find":1,"browse":1,"list":1,"filemaker":1,"indexed":1,"arrow":1,"windows":1,"macos":1}
,"saved":{"finds":1}
,"browse":{"mode":1}
,"arrow":{"next":1}
,"next":{"find":1}
,"windows":{"hold":1,"command-period":1}
,"hold":{"find":1}
,"macos":{"choose":1,"show":1}
,"cancel":{"find":1}
,"operation":{"finished":1}
,"finished":{"leave":1}
,"leave":{"previous":1}
,"unchanged":{"press":1}
,"press":{"esc":1}
,"esc":{"windows":1}
,"command-period":{"macos":1}
,"show":{"all":1}
,"all":{"records":1,"find":1,"invoices":1,"recent":1}
,"performing":{"finds":1}
,"tables":{"narrowed":1}
,"narrowed":{"existing":1}
,"existing":{"found":1}
,"inds":{"unindexed":1}
,"unindexed":{"fields":1}
,"calculation":{"fields":1}
,"referencing":{"related":1}
,"related":{"fields":1,"field":1,"record":1,"records":1}
,"take":{"finds":1}
,"indexed":{"fields":1,"use":1}
,"defining":{"field":1}
,"indexing":{"options":1}
,"options":{"if":1}
,"if":{"field\u2019s":1}
,"field\u2019s":{"values":1}
,"index":{"enter":1,"can\u2019t":1}
,"can\u2019t":{"enter":1}
,"container":{"fields":1,"field":1}
,"summary":{"fields":1}
,"global":{"fields":1}
,"web":{"viewers":1}
,"viewers":{"find":1}
,"data":{"container":1}
,"create":{"text":1}
,"number":{"field":1}
,"describes":{"identifies":1}
,"identifies":{"contents":1}
,"contents":{"container":1}
,"displays":{"all":1}
,"invoice":{"file":1}
,"file":{"displaying":1}
,"displaying":{"line":1}
,"line":{"items":1}
,"items":{"related":1}
,"portal":{"find":1,"delete":1}
,"invoices":{"listing":1}
,"listing":{"computer":1}
,"computer":{"by":1,"item":1}
,"by":{"typing":1}
,"typing":{"computer":1}
,"item":{"field":1}
,"delete":{"recent":1}
,"clear":{"all":1}
,"badge":{"magnifying":1}
,"magnifying":{"glass":1}
,"glass":{"icon":1}
,"confirms":{"you\u2019re":1}
,"you\u2019re":{"find":1}
,"check":{"boxes":1}
,"boxes":{"pop-up":1}
,"menus":{"radio":1}
,"radio":{"buttons":1}
,"buttons":{"find":1}
}
;Search.control.loadWordPairs(pairs);
