var pairs =
{
"fieldnames":{"eturns":1,"filename":1,"returns":1,"customers":1}
,"eturns":{"list":1}
,"list":{"names":1,"all":1}
,"names":{"all":1,"fieldnames":1}
,"all":{"fields":1}
,"fields":{"layoutname":1,"displayed":1,"default":1,"including":1,"customers":1}
,"layoutname":{"filename":1,"-the":1}
,"filename":{"fieldnames":1,"layoutname":1,"-the":1}
,"-the":{"name":1}
,"name":{"open":1,"layout":1,"field":1}
,"open":{"database":1}
,"database":{"file":1}
,"file":{"local":1,"text":1,"fieldnames":1,"data":1}
,"local":{"remote":1}
,"remote":{"layoutname":1}
,"layout":{"table":1,"show":1}
,"table":{"database":1,"customers":1}
,"text":{"filemaker":1,"increase":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"listed":1}
,"listed":{"items":1}
,"items":{"separated":1}
,"separated":{"by":1}
,"by":{"carriage":1}
,"carriage":{"returns":1}
,"returns":{"related":1,"question":1,"list":1}
,"related":{"fields":1}
,"displayed":{"tablename":1}
,"tablename":{":fieldname":1}
,":fieldname":{"format":1}
,"format":{"if":1}
,"if":{"fieldnames":1}
,"question":{"mark":1}
,"mark":{"name":1}
,"field":{"go":1,"layout":1,"names":1}
,"go":{"calculation":1}
,"calculation":{"dialog":1,"result":1}
,"dialog":{"box":1}
,"box":{"sure":1}
,"sure":{"calculation":1}
,"result":{"text":1}
,"increase":{"size":1}
,"size":{"field":1}
,"show":{"field":1}
,"customers":{"returns":1,"database":1,"data":1}
,"default":{"table":1}
,"data":{"entry":1}
,"entry":{"returns":1,"layout":1}
,"including":{"related":1}
}
;Search.control.loadWordPairs(pairs);
