var pairs =
{
"assword-protecting":{"local":1}
,"local":{"file":1,"ile":1}
,"file":{"prevent":1,"file":1,"located":1,"passwords":1,"prompted":1,"esn\u2019t":1,"if":1,"provide":1,"access":1,"planning":1,"edit":1,"inactive":1,"menu":1,"options":1,"files":1,"first":1}
,"prevent":{"local":1}
,"located":{"computer":1}
,"computer":{"isn\u2019t":1}
,"isn\u2019t":{"shared":1}
,"shared":{"protect":1,"ile":1,"network":1}
,"protect":{"file":1}
,"passwords":{"addition":1,"all":1,"setting":1,"password-protect":1}
,"addition":{"sure":1}
,"sure":{"password-protect":1,"guest":1,"log":1}
,"password-protect":{"all":1,"local":1}
,"all":{"accounts":1}
,"accounts":{"assigned":1,"file":1}
,"assigned":{"full":1}
,"full":{"access":1}
,"access":{"privilege":1,"users":1,"change":1}
,"privilege":{"et":1,"set":1}
,"et":{"password-protecting":1}
,"password-protecting":{"file":1}
,"prompted":{"enter":1}
,"enter":{"account":1}
,"account":{"name":1,"account":1,"inactive":1}
,"name":{"password":1}
,"password":{"time":1,"full":1,"assigned":1,"access":1,"protected":1,"protection":1,"set":1,"etting":1,"remove":1,"delete":1,"removing":1}
,"time":{"open":1}
,"open":{"file":1,"tab":1}
,"esn\u2019t":{"ccount":1}
,"ccount":{"can\u2019t":1}
,"can\u2019t":{"pen":1}
,"pen":{"file":1}
,"if":{"share":1,"edit":1,"don\u2019t":1,"write":1,"lose":1}
,"share":{"file":1}
,"provide":{"varying":1}
,"varying":{"levels":1}
,"levels":{"file":1}
,"users":{"plan":1}
,"plan":{"security":1}
,"security":{"file":1,"shared":1}
,"planning":{"security":1}
,"ile":{"accounts":1}
,"edit":{"admin":1,"full":1}
,"admin":{"account":1,"blank":1}
,"set":{"sure":1,"allow":1,"if":1,"admin":1,"password":1}
,"guest":{"account":1}
,"inactive":{"delete":1,"if":1}
,"delete":{"accounts":1,"password":1}
,"allow":{"extended":1}
,"extended":{"privileges":1}
,"privileges":{"want":1,"privilege":1,"leave":1}
,"want":{"diting":1,"remove":1}
,"diting":{"extended":1}
,"don\u2019t":{"extended":1}
,"leave":{"disabled":1}
,"disabled":{"disable":1}
,"disable":{"automatic":1}
,"automatic":{"sign-in":1}
,"sign-in":{"choose":1}
,"choose":{"file":1}
,"menu":{"file":1}
,"options":{"open":1,"dialog":1,"set":1}
,"tab":{"sure":1}
,"log":{"selected":1}
,"selected":{"warning":1,"account":1}
,"warning":{"asswords":1}
,"asswords":{"defined":1}
,"defined":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"files":1}
,"files":{"annot":1,"shared":1,"you\u2019re":1}
,"annot":{"recovered":1}
,"recovered":{"n\u2019t":1}
,"n\u2019t":{"forget":1}
,"forget":{"account":1}
,"write":{"store":1}
,"store":{"secure":1}
,"secure":{"place":1}
,"place":{"if":1}
,"lose":{"forget":1}
,"change":{"file":1}
,"network":{"password":1}
,"protected":{"want":1}
,"remove":{"password":1,"passwords":1}
,"protection":{"files":1,"file":1}
,"you\u2019re":{"sharing":1}
,"sharing":{"remove":1}
,"first":{"remove":1}
,"dialog":{"box":1}
,"box":{"sure":1}
,"blank":{"password":1}
,"etting":{"file":1}
,"removing":{"passwords":1}
,"setting":{"passwords":1}
}
;Search.control.loadWordPairs(pairs);
