var pairs =
{
"code":{"returns":1,"points":1,"text":1,"point":1,"bs":1,"ht":1,"lf":1,"cr":1,"esc":1,"fs":1,"gs":1,"rs":1,"unit":1,"space":1,"delete":1,"ab":1,"by":1}
,"returns":{"unicode":1,"empty":1,"code":1,"nan":1,"97":1,"98":1,"9800097":1,"228":1,"77600097":1}
,"unicode":{"code":1}
,"points":{"characters":1}
,"characters":{"text":1,"number":1,"unicode":1,"reported":1,"represented":1}
,"text":{"code":1,"text":1,"-one":1,"if":1,"returns":1,"function":1,"multiple":1}
,"-one":{"characters":1}
,"number":{"filemaker":1,"field":1,"value":1}
,"filemaker":{"pro":1,"number":1}
,"pro":{"10.0":1}
,"10.0":{"returns":1}
,"if":{"zero":1,"character":1,"text":1,"characters":1}
,"zero":{"characters":1}
,"empty":{"string":1}
,"string":{"if":1,"code":1}
,"character":{"text":1,"if":1,"returned":1,"represented":1,"next":1,"function":1,"table":1,"entered":1}
,"function":{"returns":1,"enter":1}
,"point":{"character":1,"each":1,"first":1,"second":1,"composite":1}
,"multiple":{"characters":1}
,"each":{"character":1}
,"returned":{"group":1,"get":1}
,"group":{"digits":1,"separator":1}
,"digits":{"code":1,"converting":1}
,"first":{"character":1}
,"represented":{"by":1,"filemaker":1}
,"by":{"digits":1,"trigger":1,"dieresis":1}
,"second":{"character":1}
,"next":{"left":1}
,"left":{"digits":1,"arrow":1}
,"converting":{"composite":1}
,"composite":{"character":1}
,"table":{"navigational":1}
,"navigational":{"characters":1}
,"reported":{"script":1,"notes":1}
,"script":{"activated":1}
,"activated":{"by":1}
,"trigger":{"key":1}
,"key":{"pressed":1}
,"pressed":{"reported":1}
,"notes":{"backspace":1}
,"backspace":{"corresponds":1,"tab":1}
,"corresponds":{"unicode\u002Fascii":1}
,"unicode\u002Fascii":{"code":1}
,"bs":{"backspace":1}
,"tab":{"corresponds":1,"shift-tab":1}
,"ht":{"horizontal":1}
,"horizontal":{"tab":1}
,"shift-tab":{"shift":1}
,"shift":{"detected":1}
,"detected":{"value":1}
,"value":{"returned":1,"code":1}
,"get":{"triggermodifierkeys":1}
,"triggermodifierkeys":{"function":1}
,"enter":{"10":1}
,"10":{"corresponds":1}
,"lf":{"line":1}
,"line":{"feed":1}
,"feed":{"return":1}
,"return":{"13":1,"escape":1}
,"13":{"corresponds":1}
,"cr":{"carriage":1}
,"carriage":{"return":1}
,"escape":{"27":1,"left":1}
,"27":{"corresponds":1}
,"esc":{"escape":1}
,"arrow":{"28":1,"29":1,"30":1,"31":1}
,"28":{"corresponds":1}
,"fs":{"file":1}
,"file":{"separator":1}
,"separator":{"up":1,"right":1,"arrow":1,"space":1}
,"up":{"arrow":1}
,"29":{"corresponds":1}
,"gs":{"group":1}
,"right":{"arrow":1}
,"30":{"corresponds":1}
,"rs":{"record":1}
,"record":{"separator":1}
,"31":{"corresponds":1}
,"unit":{"separator":1}
,"space":{"32":1,"forward":1}
,"32":{"corresponds":1}
,"forward":{"delete":1}
,"delete":{"127":1,"if":1}
,"127":{"corresponds":1}
,"field":{"type":1}
,"type":{"function":1}
,"nan":{"number":1}
,"97":{"code":1}
,"98":{"code":1}
,"ab":{"returns":1}
,"9800097":{"code":1}
,"228":{"code":1}
,"dieresis":{"character":1}
,"entered":{"separate":1}
,"separate":{"keystroke":1}
,"keystroke":{"returns":1}
}
;Search.control.loadWordPairs(pairs);
