var pairs =
{
"cryptencrypt":{"encrypts":1,"data":1,"cryptdecrypt":1,"accepts":1,"protection":1}
,"encrypts":{"data":1}
,"data":{"key":1,"cryptencrypt":1,"-any":1,"container":1,"returns":1,"binary":1,"aes-gcm":1,"validate":1,"during":1,"file":1}
,"key":{"returns":1,"data":1,"-any":1,"encrypt":1,"parameter":1,"key":1}
,"returns":{"container":1,"returns":1}
,"container":{"data":1,"filemaker":1}
,"-any":{"text":1}
,"text":{"expression":1,"container":1}
,"expression":{"field":1}
,"field":{"encrypt":1,"key":1,"data":1}
,"encrypt":{"key":1,"data":1,"decrypt":1}
,"filemaker":{"pro":1}
,"pro":{"16.0":1}
,"16.0":{"use":1}
,"use":{"cryptencrypt":1}
,"cryptdecrypt":{"functions":1}
,"functions":{"encrypt":1}
,"decrypt":{"field":1}
,"accepts":{"text":1}
,"binary":{"file":1}
,"file":{"named":1,"includes":1}
,"named":{"encrypted.data":1}
,"encrypted.data":{"function":1,"cryptencrypt":1}
,"function":{"pbkdf2":1,"supported":1}
,"pbkdf2":{"algorithm":1}
,"algorithm":{"convert":1,"128-bit":1}
,"convert":{"key":1}
,"parameter":{"cryptographic":1}
,"cryptographic":{"key":1}
,"aes-gcm":{"authenticated":1}
,"authenticated":{"encryption":1}
,"encryption":{"algorithm":1}
,"128-bit":{"level":1}
,"level":{"returned":1}
,"returned":{"file":1}
,"includes":{"encrypted":1}
,"encrypted":{"sha256":1}
,"sha256":{"digest":1}
,"digest":{"data":1}
,"validate":{"data":1}
,"during":{"decryption":1}
,"decryption":{"function":1}
,"supported":{"runtime":1}
,"runtime":{"solutions":1}
,"solutions":{"returns":1}
,"protection":{"secret":1}
,"secret":{"password":1}
}
;Search.control.loadWordPairs(pairs);
