var pairs =
{
"placing":{"chart":1}
,"chart":{"layout":1,"located":1,"title":1,"portal":1,"popover":1,"da":1,"sort":1,"grand":1,"data":1,"compares":1,"had":1}
,"layout":{"part":1,"mode":1,"parts":1}
,"part":{"data":1,"chart":1,"note":1,"current":1,"all":1,"use":1,"first":1,"last":1,"body":1,"se":1,"sorting":1,"place":1}
,"data":{"charts":1,"sorted":1,"values":1,"group":1,"set":1,"outer-most":1,"based":1,"each":1,"pie":1,"by":1,"company":1,"calculate":1,"charted":1,"entire":1,"point":1}
,"charts":{"created":1,"placed":1,"individual":1,"sort":1,"summary":1}
,"created":{"layout":1}
,"mode":{"evaluated":1}
,"evaluated":{"based":1}
,"based":{"layout":1,"chart\u2019s":1,"sort":1,"entire":1,"current":1,"related":1}
,"located":{"use":1}
,"use":{"calculation":1,"data":1,"grand":1}
,"calculation":{"chart":1}
,"title":{"title":1,"calculated":1,"displayed":1}
,"calculated":{"based":1,"current":1,"titles":1}
,"chart\u2019s":{"layout":1}
,"note":{"place":1,"if":1}
,"place":{"chart":1}
,"portal":{"place":1}
,"popover":{"portal":1}
,"da":{"ta":1}
,"ta":{"charted":1}
,"charted":{"summarized":1,"top":1,"by":1,"header":1}
,"summarized":{"groups":1,"values":1}
,"groups":{"records":1,"header":1,"footer":1,"bottom":1,"leading":1,"trailing":1,"charts":1,"group":1}
,"records":{"selected":1,"sorted":1,"relationship":1,"filemaker":1,"layout":1}
,"selected":{"ata":1}
,"ata":{"charted":1}
,"top":{"navigation":1,"bottom":1}
,"navigation":{"layout":1,"parts":1,"part":1}
,"current":{"found":1,"record":1}
,"found":{"set":1}
,"set":{"first":1,"last":1,"subsummaries":1,"based":1,"use":1,"filemaker":1,"trailing":1,"place":1,"related":1,"chart":1,"data":1,"hen":1}
,"first":{"record":1,"field":1}
,"record":{"outermost":1,"outer":1,"sub-group":1,"leading":1,"sorted":1,"found":1,"related":1,"delimited":1}
,"outermost":{"sorted":1}
,"sorted":{"groups":1,"group":1,"subsummary":1,"by":1}
,"header":{"body":1,"footer":1}
,"body":{"layout":1}
,"outer":{"ost":1,"summaries":1}
,"ost":{"sorted":1}
,"footer":{"layout":1,"top":1}
,"last":{"record":1}
,"bottom":{"navigation":1}
,"leading":{"subsummary":1,"grand":1}
,"subsummary":{"layout":1,"group":1}
,"all":{"records":1}
,"group":{"first":1,"trailing":1,"last":1,"leading":1,"create":1,"data":1,"outer-most":1,"records":1,"th":1,"related":1}
,"sub-group":{"sorted":1}
,"trailing":{"subsummary":1,"grand":1}
,"grand":{"summary":1,"summaries":1}
,"summary":{"layout":1,"aggregated":1,"field":1,"part":1}
,"placed":{"subsummary":1,"grand":1,"header":1}
,"create":{"chart":1,"bar":1}
,"sort":{"order":1,"field":1,"data":1}
,"order":{"filemaker":1,"charts":1,"dialog":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"charts":1,"assumes":1,"chart":1}
,"individual":{"data":1}
,"values":{"entire":1,"charted":1,"data":1}
,"entire":{"found":1}
,"subsummaries":{"considered":1}
,"considered":{"inner":1,"outer":1}
,"inner":{"summaries":1}
,"summaries":{"display":1,"considered":1,"calculated":1}
,"display":{"aggregate":1,"summary":1}
,"aggregate":{"data":1}
,"outer-most":{"level":1,"sorted":1}
,"level":{"each":1}
,"each":{"sorted":1,"subsummary":1,"country":1}
,"aggregated":{"data":1}
,"parts":{"summarize":1,"body":1,"affect":1}
,"summarize":{"each":1,"data":1}
,"by":{"first":1,"country":1}
,"field":{"listed":1,"y-axis":1,"create":1}
,"listed":{"sort":1}
,"dialog":{"box":1}
,"box":{"grand":1}
,"assumes":{"want":1}
,"want":{"chart":1}
,"th":{"erefore":1}
,"erefore":{"xpects":1}
,"xpects":{"x-axis":1}
,"x-axis":{"definition":1,"category":1}
,"definition":{"category":1,"slice":1}
,"category":{"labels":1}
,"labels":{"pie":1,"summarize":1}
,"pie":{"charts":1}
,"y-axis":{"definition":1,"slice":1}
,"slice":{"data":1}
,"bar":{"chart":1}
,"compares":{"total":1}
,"total":{"number":1}
,"number":{"companies":1}
,"companies":{"country":1,"each":1}
,"country":{"sort":1,"x-axis":1,"summarized":1,"place":1}
,"company":{"field":1}
,"calculate":{"number":1}
,"se":{"related":1}
,"related":{"records":1,"table":1}
,"relationship":{"current":1,"first":1,"last":1}
,"table":{"leading":1,"trailing":1,"note":1}
,"if":{"place":1}
,"sorting":{"records":1}
,"had":{"placed":1}
,"displayed":{"data":1}
,"point":{"header":1}
,"hen":{"data":1}
,"delimited":{"values":1}
,"affect":{"calculated":1}
,"titles":{"charts":1}
}
;Search.control.loadWordPairs(pairs);
