var pairs =
{
"sp":{"ecifying":1}
,"ecifying":{"text":1}
,"text":{"formats":1,"attributes":1,"format":1,"layout":1,"options":1,"size":1}
,"formats":{"fields":1,"layout":1,"stored":1}
,"fields":{"layout":1,"set":1,"place":1,"selected":1}
,"layout":{"mode":1,"displays":1,"bar":1,"font":1}
,"mode":{"set":1,"italicize":1,"formatting":1,"text":1,"apply":1,"formats":1,"select":1}
,"set":{"text":1,"by":1}
,"attributes":{"each":1,"shared":1,"note":1,"field":1,"status":1}
,"each":{"field":1,"theme":1}
,"field":{"object":1,"share":1,"objects":1,"each":1,"data":1,"se":1}
,"object":{"all":1,"including":1,"displays":1,"text":1}
,"all":{"characters":1,"repetitions":1}
,"characters":{"field":1}
,"including":{"all":1}
,"repetitions":{"if":1}
,"if":{"refers":1}
,"refers":{"repeating":1}
,"repeating":{"field":1}
,"share":{"font":1}
,"font":{"size":1,"fields":1}
,"size":{"style":1,"text":1,"default":1}
,"style":{"color":1,"changing":1}
,"color":{"line":1}
,"line":{"spacing":1}
,"spacing":{"tab":1}
,"tab":{"paragraph":1,"select":1,"inspector":1}
,"paragraph":{"settings":1}
,"settings":{"attributes":1}
,"shared":{"field":1}
,"objects":{"insert":1}
,"insert":{"field":1}
,"displays":{"data":1,"field":1}
,"data":{"field":1,"browse":1,"applied":1}
,"note":{"change":1}
,"change":{"text":1,"default":1}
,"browse":{"mode":1}
,"italicize":{"underline":1}
,"underline":{"word":1}
,"word":{"emphasis":1}
,"emphasis":{"browse":1}
,"formatting":{"overrides":1,"text":1,"bar":1,"formatting":1}
,"overrides":{"formats":1}
,"format":{"layout":1}
,"apply":{"specific":1,"use":1}
,"specific":{"layouts":1}
,"layouts":{"browse":1}
,"stored":{"data":1}
,"applied":{"layout":1}
,"se":{"formatting":1}
,"select":{"fields":1,"text":1}
,"place":{"start":1}
,"start":{"fields":1}
,"selected":{"inspector":1}
,"inspector":{"appearance":1,"apply":1}
,"appearance":{"appearance":1,"tab":1}
,"options":{"want":1}
,"want":{"press":1}
,"press":{"enter":1}
,"enter":{"tab":1}
,"use":{"formatting":1}
,"bar":{"formatting":1,"button":1,"shortcut":1}
,"button":{"layout":1}
,"shortcut":{"menu":1}
,"menu":{"quick":1}
,"quick":{"access":1}
,"access":{"text":1}
,"status":{"toolbar":1}
,"toolbar":{"each":1}
,"theme":{"change":1,"layout":1}
,"default":{"font":1,"style":1,"size":1}
,"by":{"default":1}
,"changing":{"theme":1}
}
;Search.control.loadWordPairs(pairs);
