var pairs =
{
"configuring":{"odbc":1,"data":1}
,"odbc":{"client":1,"data":1,"tables":1,"driver":1,"jdbc":1,"64-bit":1,"32-bit":1,"lick":1,"manager":1,"imports":1}
,"client":{"driver":1,"application":1}
,"driver":{"importing":1,"odbc":1,"interact":1,"additionally":1,"manufacturer":1,"if":1,"macos":1,"use":1,"configured":1,"data":1,"appears":1,"third-party":1,"access":1}
,"importing":{"odbc":1}
,"data":{"odbc":1,"source":1,"sources":1,"import":1,"choose":1}
,"tables":{"relationships":1}
,"relationships":{"graph":1}
,"graph":{"client":1,"if":1,"add":1}
,"application":{"configure":1,"filemaker":1,"details":1}
,"configure":{"driver":1,"oracle":1,"modify":1}
,"source":{"you\u2019re":1,"provide":1,"configuration":1,"application":1,"administrator":1,"appears":1,"configure":1,"system":1,"name":1,"driver":1,"want":1,"you\u2019ll":1,"drivers":1,"identifying":1,"file":1,"install":1,"configured":1,"co":1,"filemaker":1}
,"you\u2019re":{"if":1,"32-bit":1,"64-bit":1}
,"if":{"accessing":1,"importing":1,"you\u2019re":1,"data":1,"desired":1}
,"accessing":{"records":1,"odbc":1,"filemaker":1}
,"records":{"oracle":1,"execute":1,"data":1}
,"oracle":{"database":1,"client":1,"sql":1}
,"database":{"configure":1}
,"interact":{"data":1}
,"provide":{"password":1}
,"password":{"perform":1}
,"perform":{"display":1}
,"display":{"query":1}
,"query":{"varies":1}
,"varies":{"each":1}
,"each":{"application\u2019s":1,"data":1}
,"application\u2019s":{"client":1}
,"additionally":{"data":1}
,"configuration":{"vary":1,"dialog":1}
,"vary":{"odbc":1}
,"manufacturer":{"odbc":1}
,"filemaker":{"supports":1,"knowledge":1,"pro":1,"launch":1}
,"supports":{"external":1}
,"external":{"sql":1,"data":1}
,"sql":{"data":1,"server":1,"script":1}
,"sources":{"oracle":1,"supported":1,"search":1,"odbc":1,"refer":1,"uerying":1}
,"server":{"mysql":1}
,"mysql":{"community":1}
,"community":{"edition":1}
,"edition":{"odbc":1}
,"import":{"records":1}
,"execute":{"sql":1}
,"script":{"step":1}
,"step":{"use":1}
,"use":{"additional":1,"32-bit":1,"64-bit":1,"procedure":1,"use":1,"driver":1,"driver\u2019s":1}
,"additional":{"data":1}
,"supported":{"external":1,"odbc":1,"by":1,"filemaker":1}
,"search":{"filemaker":1}
,"knowledge":{"base":1}
,"base":{"overview":1}
,"overview":{"various":1}
,"various":{"odbc":1}
,"jdbc":{"filemaker":1}
,"pro":{"advanced":1}
,"advanced":{"note":1,"use":1,"32-bit":1,"finish":1,"configuration":1,"data":1,"windows":1}
,"note":{"windows":1,"odbc":1}
,"windows":{"if":1,"open":1,"filemaker":1,"64-bit":1,"macos":1}
,"32-bit":{"version":1,"odbc":1,"windows":1}
,"version":{"filemaker":1}
,"64-bit":{"version":1,"odbc":1,"windows":1,"open":1,"double-click":1}
,"macos":{"use":1}
,"procedure":{"general":1}
,"general":{"guideline":1}
,"guideline":{"configuring":1}
,"refer":{"documentation":1}
,"documentation":{"accompanies":1}
,"accompanies":{"each":1}
,"details":{"start":1}
,"start":{"odbc":1}
,"administrator":{"control":1}
,"control":{"panel":1}
,"panel":{"choose":1}
,"choose":{"system":1,"data":1,"driver":1}
,"system":{"security":1,"dsn":1,"dsns":1}
,"security":{"administrative":1}
,"administrative":{"tools":1}
,"tools":{"32-bit":1}
,"open":{"ata":1,"data":1}
,"ata":{"sources":1}
,"double-click":{"odbcad32.exe":1}
,"odbcad32.exe":{"file":1}
,"file":{"c:\u005Cwindows\u005Csyswow64":1,"enter":1}
,"c:\u005Cwindows\u005Csyswow64":{"folder":1}
,"folder":{"64-bit":1}
,"lick":{"system":1}
,"dsn":{"tab":1,"data":1,"log":1}
,"tab":{"user":1,"if":1,"odbc":1,"system":1}
,"user":{"dsn":1}
,"appears":{"list":1,"data":1,"name":1}
,"list":{"driver":1}
,"configured":{"skip":1,"driver":1}
,"skip":{"remaining":1}
,"remaining":{"steps":1}
,"steps":{"accessing":1}
,"modify":{"you\u2019ll":1}
,"you\u2019ll":{"interact":1,"accessing":1}
,"name":{"all":1,"enter":1}
,"all":{"users":1}
,"users":{"log":1}
,"log":{"computer":1,"system":1,"add":1}
,"computer":{"user":1}
,"dsns":{"supported":1}
,"add":{"configure":1}
,"want":{"use":1}
,"third-party":{"endor":1}
,"endor":{"install":1}
,"install":{"new":1,"odbc":1}
,"new":{"driver":1}
,"driver\u2019s":{"installation":1}
,"installation":{"program":1}
,"program":{"choose":1}
,"finish":{"setup":1,"save":1}
,"setup":{"dialog":1}
,"dialog":{"box":1}
,"box":{"appears":1,"continue":1}
,"enter":{"descriptive":1}
,"descriptive":{"text":1}
,"text":{"identify":1,"if":1}
,"identify":{"data":1}
,"drivers":{"offer":1}
,"offer":{"options":1}
,"options":{"customize":1}
,"customize":{"access":1}
,"access":{"data":1,"records":1}
,"identifying":{"data":1}
,"desired":{"finish":1}
,"save":{"data":1}
,"manager":{"actual":1,"freeware":1,"utility":1}
,"actual":{"technologies":1}
,"technologies":{"ww.odbcmanager.net":1}
,"ww.odbcmanager.net":{"note":1}
,"freeware":{"product":1}
,"product":{"supported":1}
,"by":{"filemaker":1}
,"launch":{"odbc":1}
,"utility":{"system":1}
,"imports":{"system":1}
,"continue":{"name":1}
,"co":{"nnecting":1}
,"nnecting":{"external":1}
,"uerying":{"odbc":1}
}
;Search.control.loadWordPairs(pairs);
