var pairs =
{
"setting":{"up":1}
,"up":{"field":1,"fields":1}
,"field":{"auto-complete":1,"use":1,"based":1,"inspector":1,"control":1,"indexing":1,"show":1,"sort":1,"defining":1}
,"auto-complete":{"during":1,"type":1,"text":1,"existing":1,"value":1,"autocomplete":1}
,"during":{"data":1}
,"data":{"entry":1,"data":1,"tab":1}
,"entry":{"set":1,"layout":1}
,"set":{"up":1}
,"use":{"auto-complete":1,"display":1}
,"type":{"help":1,"auto-enter":1}
,"help":{"users":1}
,"users":{"quickly":1,"uggestions":1}
,"quickly":{"enter":1}
,"enter":{"values":1,"record":1}
,"values":{"browse":1,"value":1,"suggestions":1,"second":1}
,"browse":{"mode":1}
,"mode":{"find":1,"users":1,"select":1}
,"find":{"mode":1}
,"uggestions":{"based":1}
,"based":{"ntered":1,"values":1,"value":1}
,"ntered":{"field":1}
,"value":{"list":1,"lists":1}
,"list":{"use":1,"drop-down":1,"auto-complete":1,"su":1,"prevent":1,"select":1,"uto-complete":1,"configured":1}
,"text":{"fields":1}
,"fields":{"displayed":1,"automatically":1}
,"displayed":{"ed":1}
,"ed":{"boxes":1}
,"boxes":{"dr":1}
,"dr":{"op-down":1}
,"op-down":{"lists":1,"calendars":1}
,"lists":{"dr":1,"value":1,"auto-complete":1}
,"calendars":{"note":1}
,"note":{"set":1}
,"automatically":{"enter":1}
,"record":{"created":1}
,"created":{"modified":1}
,"modified":{"defining":1}
,"defining":{"automatic":1,"field":1,"value":1}
,"automatic":{"data":1}
,"layout":{"mode":1}
,"select":{"field":1,"edit":1,"include":1}
,"inspector":{"data":1}
,"tab":{"field":1}
,"control":{"style":1}
,"style":{"choose":1}
,"choose":{"edit":1}
,"edit":{"box":1}
,"box":{"drop-down":1}
,"drop-down":{"list":1,"calendar":1,"lists":1}
,"calendar":{"select":1,"auto-complete":1}
,"existing":{"values":1}
,"suggestions":{"ased":1,"displaying":1}
,"ased":{"field\u2019s":1}
,"field\u2019s":{"index":1}
,"index":{"indexing":1}
,"indexing":{"enabled":1,"options":1}
,"enabled":{"defining":1}
,"options":{"drop-down":1}
,"su":{"ggestions":1}
,"ggestions":{"based":1}
,"prevent":{"suggestions":1}
,"displaying":{"list":1}
,"include":{"arrow":1}
,"arrow":{"show":1}
,"show":{"hide":1,"values":1}
,"hide":{"list":1}
,"uto-complete":{"supported":1}
,"supported":{"drop-down":1}
,"configured":{"use":1}
,"display":{"values":1}
,"second":{"field":1}
,"sort":{"by":1}
,"by":{"second":1}
,"autocomplete":{"typeahead":1}
,"typeahead":{"type":1}
,"auto-enter":{"autoenter":1}
,"autoenter":{"set":1}
}
;Search.control.loadWordPairs(pairs);
