var pairs =
{
"sing":{"operators":1,"variables":1}
,"operators":{"formulas":1,"athematical":1,"comparison":1,"logical":1,"text":1,"note":1,"evaluated":1}
,"formulas":{"operator":1,"sing":1}
,"operator":{"symbol":1,"tells":1}
,"symbol":{"instruction":1}
,"instruction":{"manipulates":1}
,"manipulates":{"expressions":1}
,"expressions":{"formula":1}
,"formula":{"plus":1}
,"plus":{"operator":1}
,"tells":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"add":1}
,"add":{"expression":1}
,"expression":{"types":1}
,"types":{"operators":1}
,"athematical":{"operators":1}
,"comparison":{"operators":1}
,"logical":{"operators":1}
,"text":{"operators":1}
,"note":{"variables":1}
,"variables":{"formulas":1,"operators":1}
,"evaluated":{"order":1}
,"order":{"listed":1,"evaluation":1}
,"listed":{"\u002F**\u002F":1}
,"\u002F**\u002F":{"\u002F\u002F2":1}
,"\u002F\u002F2":{"${":1}
,"${":{"\u002F7":1}
,"\u002F7":{"-8":1}
,"-8":{"&9":1}
,"&9":{"10":1}
,"10":{"11":1}
,"11":{"xo":1}
,"xo":{"order":1}
}
;Search.control.loadWordPairs(pairs);
