var pairs =
{
"unsort":{"records":1}
,"records":{"estores":1,"current":1,"entered":1,"script":1,"prints":1,"go":1,"[restore":1,"options":1,"automating":1}
,"estores":{"records":1}
,"current":{"found":1}
,"found":{"set":1}
,"set":{"order":1}
,"order":{"records":1,"invoices":1}
,"entered":{"none":1,"by":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"use":1}
,"use":{"script":1}
,"script":{"step":1}
,"step":{"maintain":1,"executing":1,"print":1}
,"maintain":{"original":1}
,"original":{"creation":1,"layout":1}
,"creation":{"order":1}
,"invoices":{"entered":1,"layout":1,"\u0022]":1}
,"by":{"invoice":1,"date":1}
,"invoice":{"number":1}
,"number":{"membership":1}
,"membership":{"records":1}
,"date":{"perform":1}
,"perform":{"unsort":1}
,"executing":{"sort":1}
,"sort":{"records":1}
,"print":{"invoices":1,"[with":1}
,"layout":{"sorts":1,"unsorts":1,"[\u0022":1,"[original":1}
,"sorts":{"records":1}
,"prints":{"returns":1}
,"returns":{"original":1}
,"unsorts":{"records":1}
,"go":{"layout":1}
,"[\u0022":{"print":1}
,"\u0022]":{"sort":1}
,"[restore":{"dialog":1}
,"dialog":{"off]":1}
,"off]":{"print":1,"go":1}
,"[with":{"dialog":1}
,"[original":{"layout]":1}
,"layout]":{"unsort":1}
,"options":{"sorting":1}
,"sorting":{"records":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
