var pairs =
{
"get":{"un":1,"functions":1,"currenttime":1,"function":1,"accountextendedprivileges":1,"accountgroupname":1,"accountn":1,"accountprivilegesetname":1,"activefieldcontents":1,"activefieldname":1,"activefieldtablename":1,"activelayoutobjectname":1,"activemodifierkeys":1,"activeportalrownumber":1,"activerecordnumber":1,"activerepetitionnumber":1,"activeselectionsize":1,"activeselectionstart":1,"allowabortstate":1,"allowformattingbarstate":1,"applicationarchitecture":1,"applicationlanguage":1,"applicationversion":1,"calculationrepetitionnumber":1,"connectionattributes":1,"connectionstate":1,"currentdate":1,"currentextendedprivileges":1,"currenthosttimestamp":1,"currentprivilegesetname":1,"currenttimestamp":1,"currenttimeutcmilliseconds":1,"custommenusetname":1,"desktoppath":1,"device":1,"documentspath":1,"documentspathlisting":1,"encryptionstate":1,"errorcapturestate":1,"filemakerpath":1,"filename":1,"filepath":1,"filesize":1,"foundcount":1,"highcontrastcolor":1,"highcontraststate":1,"hostapplicationversion":1,"hostipaddress":1,"hostname":1,"installedfmplugins":1,"lasterror":1,"lastexternalerrordetail":1,"lastmessagechoice":1,"layoutaccess":1,"layoutcount":1,"layoutname":1,"layoutnumber":1,"layouttablename":1,"layoutviewstate":1,"menubarstate":1,"modifiedfields":1,"multiuserstate":1,"networkprotocol":1,"networktype":1,"pagenumber":1,"persistentid":1,"preferencespath":1,"printername":1,"quickfindtext":1,"recordaccess":1,"recordid":1,"recordmodificationcount":1,"recordnumber":1,"recordopencount":1,"recordopenstate":1,"regionmonitorevents":1,"requestcount":1,"requestomitstate":1,"screendepth":1,"screenheight":1,"screenscalefactor":1,"screenwidth":1,"scriptanimationstate":1,"scriptname":1,"scriptparameter":1,"scriptresult":1,"sortstate":1,"statusareastate":1,"systemdrive":1,"systemipaddress":1,"systemlanguage":1,"systemnicaddress":1,"systemplatform":1,"systemversion":1,"temporarypath":1,"textrulervisible":1,"totalrecordcount":1,"touchkeyboardstate":1,"triggercurrentpanel":1,"triggerexternalevent":1,"triggergestureinfo":1,"triggerkeystroke":1,"triggermodifierkeys":1,"triggertargetpanel":1,"usercount":1,"username":1,"usesystemformatsstate":1,"uuid":1,"uuidnumber":1,"windowcontentheight":1,"windowcontentwidth":1,"windowdesktopheight":1,"windowdesktopwidth":1,"windowheight":1,"windowleft":1,"windowmode":1,"windowname":1,"windoworientation":1,"windowstyle":1,"windowtop":1,"windowvisible":1,"windowwidth":1,"windowzoomlevel":1,"get":1}
,"un":{"ctions":1}
,"ctions":{"get":1}
,"functions":{"monitor":1,"return":1,"script":1,"get":1}
,"monitor":{"errors":1,"script":1}
,"errors":{"scripts":1,"external":1}
,"scripts":{"capture":1}
,"capture":{"file":1,"script":1}
,"file":{"status":1,"enabled":1,"get":1,"view":1,"filemaker":1,"open":1}
,"status":{"actions":1,"get":1,"toolbar":1}
,"actions":{"performed":1}
,"performed":{"get":1,"sub":1}
,"return":{"regular":1}
,"regular":{"basis":1}
,"basis":{"get":1}
,"currenttime":{"function":1,"current":1}
,"function":{"placed":1,"up":1,"returns":1,"get":1,"evaluated":1,"getfunctions":1}
,"placed":{"stored":1}
,"stored":{"calculation":1,"qu":1}
,"calculation":{"field":1,"fields":1,"result":1,"run":1,"file":1}
,"field":{"time":1,"unstored":1,"hat":1,"focus":1,"get":1,"eing":1}
,"time":{"update":1,"stored":1,"nearest":1,"coordinated":1,"utc":1}
,"update":{"new":1,"fields":1,"performance":1}
,"new":{"record":1}
,"record":{"created":1,"if":1,"focus":1,"access":1,"current":1,"privileges":1,"get":1,"committed":1,"found":1}
,"created":{"if":1}
,"if":{"calculation":1,"calculations":1,"allow":1,"formatting":1,"set":1,"high":1,"omit":1,"animations":1,"text":1,"touch":1,"use":1,"window":1,"account":1,"[databasename":1,"[get":1,"end":1,"go":1}
,"fields":{"calculation":1,"modified":1}
,"result":{"returns":1,"update":1,"performed":1}
,"returns":{"current":1,"get":1,"false":1,"path":1}
,"current":{"time":1,"record":1,"account\u2019s":1,"user":1,"indow":1,"found":1,"application":1,"file\u2019s":1,"file":1,"date":1,"encryption":1,"layout":1,"menu":1,"table":1,"page":1,"record\u2019s":1,"find":1,"script":1,"sort":1,"status":1,"system":1,"platform":1,"operating":1,"filemaker":1,"window":1}
,"modified":{"current":1}
,"calculations":{"unstored":1}
,"unstored":{"time":1,"idea":1}
,"performance":{"reasons":1}
,"reasons":{"calculation":1}
,"idea":{"get":1}
,"script":{"status":1,"step":1,"configure":1,"script":1,"returns":1,"currently":1,"parameter":1,"get":1,"result":1,"trigger":1,"acting":1,"function":1,"message":1,"captures":1,"performs":1,"prints":1,"else":1}
,"up":{"date":1,"show":1}
,"date":{"moment":1,"system":1,"time":1}
,"moment":{"calculation":1}
,"run":{"function":1,"get":1}
,"accountextendedprivileges":{"list":1}
,"list":{"keywords":1,"all":1,"fields":1,"th":1}
,"keywords":{"based":1}
,"based":{"account":1,"ccount":1,"record":1,"user\u0027s":1}
,"account":{"open":1,"authenticates":1,"name":1,"if":1,"script":1,"go":1,"\u0022]":1}
,"open":{"file":1,"ile":1,"records":1,"get":1}
,"enabled":{"extended":1,"state":1,"current":1}
,"extended":{"privileges":1}
,"privileges":{"get":1,"current":1,"assigned":1,"dialog":1}
,"accountgroupname":{"current":1}
,"account\u2019s":{"group":1}
,"group":{"name":1}
,"name":{"account":1,"by":1,"eing":1,"field":1,"table":1,"ayout":1,"version":1,"current":1,"privilege":1,"active":1,"currently":1,"get":1,"computer":1,"layout":1,"network":1,"script":1,"macos":1,"panel":1,"filemaker":1,"window":1}
,"authenticates":{"via":1}
,"via":{"external":1,"e-mail":1}
,"external":{"server":1,"filemaker":1}
,"server":{"oauth":1}
,"oauth":{"identity":1}
,"identity":{"provider":1}
,"provider":{"get":1}
,"accountn":{"authenticated":1}
,"authenticated":{"account":1}
,"by":{"file\u2019s":1,"account":1,"get":1,"show":1}
,"file\u2019s":{"current":1,"host":1}
,"user":{"get":1,"abort":1,"genera":1,"button":1}
,"accountprivilegesetname":{"privilege":1}
,"privilege":{"set":1}
,"set":{"name":1,"get":1,"eing":1,"error":1,"haven\u2019t":1,"current":1,"display":1,"if":1,"up":1}
,"eing":{"by":1,"calculated":1,"evaluate":1}
,"ile":{"get":1,"filename":1}
,"activefieldcontents":{"contents":1}
,"contents":{"field":1}
,"hat":{"focus":1}
,"focus":{"get":1,"calculation\u0027s":1,"current":1,"repeating":1}
,"activefieldname":{"name":1}
,"activefieldtablename":{"name":1}
,"table":{"occurrence":1,"get":1}
,"occurrence":{"field":1,"isplaying":1}
,"activelayoutobjectname":{"name":1}
,"ayout":{"objec":1}
,"objec":{"focus":1}
,"calculation\u0027s":{"current":1}
,"indow":{"get":1}
,"activemodifierkeys":{"number":1}
,"number":{"keyboard":1,"representing":1,"records":1,"enabled":1,"error":1,"button":1,"based":1,"layouts":1,"layout":1,"current":1,"times":1,"open":1,"find":1,"bits":1,"clients":1}
,"keyboard":{"modifier":1,"set":1}
,"modifier":{"keys":1}
,"keys":{"pressed":1,"onobjectkeystroke":1}
,"pressed":{"get":1}
,"activeportalrownumber":{"umber":1}
,"umber":{"representing":1}
,"representing":{"portal":1,"record":1,"epetition":1,"characters":1,"starting":1,"current":1,"repetition":1,"security":1,"type":1,"file\u2019s":1,"currently":1,"level":1,"unique":1,"ecord":1,"state":1,"event":1,"universally":1,"large":1,"mode":1,"orientation":1}
,"portal":{"row":1}
,"row":{"focus":1}
,"activerecordnumber":{"number":1}
,"found":{"set":1}
,"activerepetitionnumber":{"number":1}
,"epetition":{"focus":1}
,"repeating":{"field":1}
,"activeselectionsize":{"number":1}
,"characters":{"selected":1,"activated":1}
,"selected":{"get":1,"text":1,"current":1}
,"activeselectionstart":{"number":1}
,"starting":{"character":1}
,"character":{"selected":1}
,"text":{"get":1,"representing":1,"errors":1,"dentifying":1,"stored":1,"ruler":1}
,"allowabortstate":{"true":1}
,"true":{"if":1}
,"allow":{"user":1}
,"abort":{"script":1}
,"step":{"returns":1,"get":1,"run":1,"script":1}
,"false":{"get":1,"if":1}
,"allowformattingbarstate":{"true":1}
,"formatting":{"bar":1}
,"bar":{"allowed":1,"state":1,"macos":1}
,"allowed":{"visible":1}
,"visible":{"returns":1}
,"applicationarchitecture":{"current":1}
,"application":{"architecture":1,"language":1}
,"architecture":{"get":1}
,"applicationlanguage":{"text":1}
,"language":{"get":1,"currently":1}
,"applicationversion":{"filemaker":1}
,"filemaker":{"client\u2019s":1,"product":1,"host\u2019s":1,"returned":1,"network":1,"machine":1,"get":1,"temporary":1,"user":1,"go":1}
,"client\u2019s":{"product":1}
,"product":{"name":1,"get":1,"hen":1}
,"version":{"get":1,"number":1,"current":1}
,"calculationrepetitionnumber":{"number":1}
,"repetition":{"calculation":1}
,"calculated":{"get":1}
,"connectionattributes":{"name":1}
,"host":{"ertificate":1,"computer":1}
,"ertificate":{"authority":1}
,"authority":{"issued":1}
,"issued":{"ssl":1}
,"ssl":{"certificate":1}
,"certificate":{"secure":1}
,"secure":{"connection":1}
,"connection":{"get":1,"current":1}
,"connectionstate":{"number":1}
,"security":{"state":1}
,"state":{"network":1,"get":1,"installed":1,"current":1,"keyboard":1}
,"network":{"connection":1,"get":1,"protocol":1,"access":1,"interface":1}
,"currentdate":{"current":1,"check":1,"-30]":1}
,"system":{"calendar":1,"clock":1,"located":1,"get":1,"formats":1}
,"calendar":{"get":1}
,"currentextendedprivileges":{"list":1}
,"ccount":{"sed":1}
,"sed":{"evaluate":1}
,"evaluate":{"th":1,"calculation":1}
,"th":{"alculation":1,"ip":1,"characters":1}
,"alculation":{"enabled":1}
,"currenthosttimestamp":{"host\u0027s":1}
,"host\u0027s":{"current":1}
,"nearest":{"second":1,"millisecond":1}
,"second":{"system":1}
,"clock":{"get":1}
,"currentprivilegesetname":{"name":1}
,"currenttimestamp":{"current":1}
,"currenttimeutcmilliseconds":{"current":1}
,"coordinated":{"universal":1}
,"universal":{"time":1}
,"utc":{"nearest":1}
,"millisecond":{"get":1}
,"custommenusetname":{"name":1}
,"active":{"custom":1,"ile":1,"returns":1,"file":1,"ic":1}
,"custom":{"menu":1,"dialog":1,"record":1}
,"menu":{"set":1,"bar":1,"returns":1}
,"desktoppath":{"path":1}
,"path":{"desktop":1,"documents":1,"folder":1,"location":1,"preferences":1,"current":1}
,"desktop":{"folder":1,"space":1}
,"folder":{"current":1,"returned":1,"currently":1,"get":1}
,"device":{"number":1,"running":1}
,"type":{"computer":1,"network":1}
,"computer":{"mobile":1,"current":1,"hosting":1,"device":1,"get":1}
,"mobile":{"evice":1}
,"evice":{"running":1}
,"running":{"filemaker":1,"copy":1,"aused":1,"operating":1}
,"documentspath":{"path":1,"function":1}
,"documents":{"folder":1}
,"documentspathlisting":{"list":1}
,"all":{"iles":1,"computers":1,"nic":1}
,"iles":{"folders":1}
,"folders":{"documents":1}
,"returned":{"by":1}
,"encryptionstate":{"value":1}
,"value":{"representing":1,"get":1}
,"encryption":{"state":1}
,"errorcapturestate":{"true":1}
,"error":{"capture":1,"occur":1}
,"filemakerpath":{"returns":1}
,"currently":{"running":1,"active":1,"displayed":1,"set":1,"ccessing":1}
,"copy":{"filemaker":1}
,"filename":{"name":1,"extension":1}
,"extension":{"get":1}
,"filepath":{"full":1}
,"full":{"path":1}
,"location":{"currently":1}
,"filesize":{"size":1}
,"size":{"bytes":1}
,"bytes":{"currently":1}
,"foundcount":{"number":1}
,"records":{"urrent":1,"current":1}
,"urrent":{"found":1,"high":1}
,"highcontrastcolor":{"urrent":1}
,"high":{"contrast":1}
,"contrast":{"default":1,"active":1}
,"default":{"color":1,"options":1,"printer":1}
,"color":{"scheme":1,"shade":1}
,"scheme":{"name":1}
,"highcontraststate":{"true":1}
,"hostapplicationversion":{"filemaker":1}
,"host\u2019s":{"product":1}
,"hostipaddress":{"ip":1}
,"ip":{"address":1,"addresses":1}
,"address":{"host":1}
,"hostname":{"registered":1}
,"registered":{"name":1}
,"hosting":{"ile":1}
,"installedfmplugins":{"ame":1}
,"ame":{"version":1}
,"installed":{"plug-ins":1}
,"plug-ins":{"get":1}
,"lasterror":{"number":1,"get":1}
,"occur":{"ed":1}
,"ed":{"execution":1}
,"execution":{"executed":1}
,"executed":{"script":1}
,"lastexternalerrordetail":{"text":1}
,"lastmessagechoice":{"number":1,"based":1,"=1]":1,"=2]":1}
,"button":{"clicked":1,"labeled":1}
,"clicked":{"alert":1}
,"alert":{"message":1}
,"message":{"displayed":1,"prompts":1,"account":1}
,"displayed":{"by":1,"get":1,"returns":1}
,"show":{"custom":1}
,"dialog":{"script":1,"box":1,"[\u0022":1,"databasename":1}
,"layoutaccess":{"number":1}
,"access":{"privileges":1,"current":1}
,"layout":{"get":1,"currently":1,"manage":1,"[\u0022":1,"[original":1}
,"layoutcount":{"total":1}
,"total":{"number":1}
,"layouts":{"ile":1,"dialog":1}
,"layoutname":{"name":1,"\u0022]":1}
,"layoutnumber":{"number":1}
,"manage":{"layouts":1}
,"box":{"currently":1,"get":1}
,"layouttablename":{"name":1}
,"isplaying":{"records":1}
,"layoutviewstate":{"number":1}
,"view":{"get":1}
,"menubarstate":{"number":1}
,"modifiedfields":{"list":1}
,"multiuserstate":{"number":1}
,"level":{"sharing":1}
,"sharing":{"file":1}
,"networkprotocol":{"name":1}
,"protocol":{"tcp\u002Fip":1}
,"tcp\u002Fip":{"filemaker":1}
,"machine":{"get":1}
,"networktype":{"number":1}
,"pagenumber":{"number":1}
,"page":{"printed":1}
,"printed":{"previewed":1}
,"previewed":{"get":1}
,"persistentid":{"text":1}
,"unique":{"identifier":1,"id":1}
,"identifier":{"computer":1,"uuid":1}
,"preferencespath":{"path":1}
,"preferences":{"default":1,"dialog":1}
,"options":{"folder":1}
,"printername":{"text":1}
,"dentifying":{"default":1}
,"printer":{"name":1}
,"quickfindtext":{"text":1}
,"qu":{"ick":1}
,"ick":{"fi":1}
,"fi":{"nd":1}
,"nd":{"box":1}
,"recordaccess":{"number":1}
,"record\u2019s":{"access":1}
,"assigned":{"custom":1}
,"recordid":{"unique":1}
,"id":{"number":1}
,"recordmodificationcount":{"total":1}
,"times":{"current":1}
,"committed":{"get":1}
,"recordnumber":{"umber":1}
,"ecord":{"\u2019s":1}
,"\u2019s":{"position":1}
,"position":{"current":1}
,"recordopencount":{"total":1}
,"haven\u2019t":{"een":1}
,"een":{"saved":1}
,"saved":{"get":1}
,"recordopenstate":{"number":1}
,"regionmonitorevents":{"events":1}
,"events":{"caused":1}
,"caused":{"script":1}
,"configure":{"region":1}
,"region":{"monitor":1}
,"requestcount":{"total":1}
,"find":{"request":1}
,"request":{"efined":1,"returns":1}
,"efined":{"current":1}
,"requestomitstate":{"true":1}
,"omit":{"selected":1}
,"screendepth":{"number":1}
,"bits":{"represent":1}
,"represent":{"color":1}
,"shade":{"gray":1}
,"gray":{"pixel":1}
,"pixel":{"main":1}
,"main":{"screen":1}
,"screen":{"get":1,"window":1,"current":1,"windows":1}
,"screenheight":{"height":1}
,"height":{"points":1}
,"points":{"screen":1,"window":1,"desktop":1,"outer":1}
,"window":{"current":1,"ontent":1,"script":1,"visible":1,"hidden":1,"get":1}
,"screenscalefactor":{"scale":1}
,"scale":{"factor":1}
,"factor":{"screen":1}
,"screenwidth":{"width":1}
,"width":{"points":1}
,"scriptanimationstate":{"true":1}
,"animations":{"enabled":1}
,"scriptname":{"name":1}
,"aused":{"get":1}
,"scriptparameter":{"script":1}
,"parameter":{"passed":1}
,"passed":{"current":1}
,"scriptresult":{"script":1}
,"sub":{"-script":1}
,"-script":{"get":1}
,"sortstate":{"alue":1}
,"alue":{"representing":1}
,"sort":{"state":1}
,"statusareastate":{"number":1}
,"toolbar":{"state":1}
,"systemdrive":{"drive":1}
,"drive":{"letter":1}
,"letter":{"windows":1,"send":1,"sends":1}
,"windows":{"volume":1,"bottom":1}
,"volume":{"name":1}
,"macos":{"running":1,"get":1}
,"operating":{"system":1}
,"located":{"get":1}
,"systemipaddress":{"list":1}
,"addresses":{"all":1}
,"computers":{"onnected":1}
,"onnected":{"active":1}
,"ic":{"network":1}
,"interface":{"controller":1}
,"controller":{"card":1,"cards":1}
,"card":{"get":1}
,"systemlanguage":{"language":1}
,"systemnicaddress":{"hardware":1}
,"hardware":{"addresses":1}
,"nic":{"etwork":1}
,"etwork":{"interface":1}
,"cards":{"connected":1}
,"connected":{"computer":1}
,"systemplatform":{"number":1}
,"platform":{"get":1}
,"systemversion":{"version":1}
,"temporarypath":{"returns":1}
,"temporary":{"folder":1}
,"textrulervisible":{"true":1}
,"ruler":{"displayed":1}
,"totalrecordcount":{"total":1}
,"touchkeyboardstate":{"true":1}
,"touch":{"keyboard":1}
,"display":{"automatically":1}
,"automatically":{"returns":1}
,"triggercurrentpanel":{"index":1}
,"index":{"object":1}
,"object":{"name":1}
,"panel":{"switch":1}
,"switch":{"rom":1,"onpanelswitch":1}
,"rom":{"onpanelswitch":1}
,"onpanelswitch":{"script":1}
,"trigger":{"activated":1,"get":1,"onlayoutkeystroke":1}
,"activated":{"get":1,"onexternalcommandreceived":1,"ongesturetap":1,"onobjectkeystroke":1}
,"triggerexternalevent":{"number":1}
,"event":{"activated":1}
,"onexternalcommandreceived":{"script":1}
,"triggergestureinfo":{"details":1}
,"details":{"gesture":1}
,"gesture":{"activated":1}
,"ongesturetap":{"script":1}
,"triggerkeystroke":{"th":1}
,"onobjectkeystroke":{"script":1}
,"onlayoutkeystroke":{"script":1}
,"triggermodifierkeys":{"state":1}
,"triggertargetpanel":{"index":1}
,"usercount":{"number":1}
,"clients":{"currently":1}
,"ccessing":{"file":1}
,"username":{"name":1}
,"genera":{"tab":1}
,"tab":{"preferences":1}
,"usesystemformatsstate":{"true":1}
,"use":{"system":1}
,"formats":{"format":1}
,"format":{"menu":1}
,"uuid":{"text":1,"get":1,"value":1}
,"universally":{"unique":1}
,"uuidnumber":{"number":1}
,"large":{"universally":1}
,"windowcontentheight":{"height":1}
,"ontent":{"get":1}
,"windowcontentwidth":{"width":1}
,"windowdesktopheight":{"height":1}
,"space":{"get":1}
,"windowdesktopwidth":{"width":1}
,"windowheight":{"height":1}
,"acting":{"get":1,"elative":1,"relative":1}
,"windowleft":{"horizontal":1}
,"horizontal":{"distance":1}
,"distance":{"points":1}
,"outer":{"edge":1}
,"edge":{"window":1,"screen":1,"menu":1}
,"elative":{"left":1}
,"left":{"ost":1}
,"ost":{"edge":1}
,"windowmode":{"number":1}
,"mode":{"filemaker":1}
,"hen":{"function":1}
,"evaluated":{"get":1}
,"windowname":{"name":1}
,"windoworientation":{"value":1}
,"orientation":{"window":1}
,"windowstyle":{"style":1}
,"style":{"window":1}
,"windowtop":{"vertical":1}
,"vertical":{"distance":1}
,"relative":{"top":1}
,"top":{"edge":1}
,"bottom":{"edge":1}
,"windowvisible":{"true":1}
,"hidden":{"hide":1}
,"hide":{"window":1}
,"windowwidth":{"width":1}
,"windowzoomlevel":{"zoom":1}
,"zoom":{"percentage":1}
,"percentage":{"current":1}
,"check":{"each":1}
,"each":{"record":1}
,"prompts":{"user":1}
,"labeled":{"ignore":1}
,"ignore":{"send":1}
,"send":{"letter":1,"mail":1}
,"mail":{"set":1,"[send":1}
,"captures":{"user\u0027s":1}
,"user\u0027s":{"response":1}
,"response":{"get":1,"script":1}
,"performs":{"action":1}
,"action":{"cancels":1}
,"cancels":{"rest":1}
,"rest":{"script":1}
,"prints":{"payment":1}
,"payment":{"late":1}
,"late":{"letter":1,"\u0022]":1,"notice":1}
,"sends":{"email":1}
,"email":{"associated":1}
,"associated":{"account":1}
,"go":{"layout":1,"record\u002Frequest\u002Fpage":1,"get":1}
,"[\u0022":{"layoutname":1,"30":1,"late":1}
,"\u0022]":{"go":1,"if":1,"print":1,"end":1}
,"record\u002Frequest\u002Fpage":{"[first]":1,"[next":1}
,"[first]":{"loop":1}
,"loop":{"if":1,"go":1}
,"[databasename":{":date":1}
,":date":{"get":1}
,"-30]":{"show":1}
,"30":{"days":1}
,"days":{"late":1}
,"[get":{"lastmessagechoice":1}
,"=1]":{"halt":1}
,"halt":{"script":1}
,"else":{"if":1,"send":1}
,"=2]":{"go":1}
,"notice":{"\u0022]":1,"message":1}
,"print":{"[]":1}
,"[]":{"else":1}
,"[send":{"via":1}
,"e-mail":{"client":1}
,"client":{"dialog":1}
,"databasename":{":client":1}
,":client":{"subject":1}
,"subject":{"late":1}
,"end":{"if":1,"loop":1}
,"[next":{"exit":1}
,"exit":{"last":1}
,"last":{"on]":1}
,"on]":{"end":1}
,"[original":{"layout]":1}
,"layout]":{"filemaker":1}
,"getfunctions":{"get":1}
}
;Search.control.loadWordPairs(pairs);
