var pairs =
{
"recovering":{"filemaker":1,"file":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"files":1,"runs":1,"attempt":1}
,"files":{"filemaker":1,"open":1}
,"runs":{"consistency":1}
,"consistency":{"check":1,"file":1}
,"check":{"utomatically":1,"consistent":1}
,"utomatically":{"if":1}
,"if":{"database":1,"suspect":1,"active":1}
,"database":{"choose":1,"requires":1,"open":1,"depending":1,"repaired":1,"check":1}
,"choose":{"verify":1}
,"verify":{"consistency":1}
,"file":{"if":1,"damaged":1,"underlying":1,"recovery":1,"completely":1,"reserved":1,"first":1,"open":1,"use":1,"maintenance":1}
,"suspect":{"file":1}
,"damaged":{"if":1,"database":1,"recovered":1}
,"requires":{"extensive":1}
,"extensive":{"correction":1}
,"correction":{"open":1}
,"open":{"filemaker":1,"save":1,"displaying":1,"recover":1,"file":1}
,"attempt":{"recover":1}
,"recover":{"file":1,"command":1,"data":1}
,"underlying":{"action":1}
,"action":{"file":1}
,"recovery":{"preserve":1,"process":1}
,"preserve":{"data":1}
,"data":{"context":1,"generically":1,"sort":1,"clone":1,"recovery":1,"reason":1}
,"context":{"data":1}
,"generically":{"refers":1}
,"refers":{"file\u2019s":1}
,"file\u2019s":{"schema":1}
,"schema":{"structure":1}
,"structure":{"tables":1}
,"tables":{"records":1}
,"records":{"layouts":1,"incorrectly":1,"unexpectedly":1}
,"layouts":{"scripts":1,"layout":1}
,"scripts":{"field":1,"data":1}
,"field":{"definitions":1,"types":1}
,"definitions":{"non-essential":1}
,"non-essential":{"data":1}
,"sort":{"order":1}
,"order":{"recovered":1}
,"recovered":{"utilities":1,"database":1,"special":1}
,"utilities":{"guarantee":1}
,"guarantee":{"file":1}
,"completely":{"repaired":1}
,"repaired":{"therefore":1,"recovered":1}
,"therefore":{"damaged":1}
,"save":{"backup":1,"compacted":1}
,"backup":{"opy":1}
,"opy":{"recovered":1}
,"depending":{"severity":1}
,"severity":{"problem":1}
,"problem":{"import":1}
,"import":{"data":1}
,"clone":{"original":1}
,"original":{"database":1}
,"consistent":{"content":1}
,"content":{"if":1}
,"active":{"operation":1}
,"operation":{"running":1}
,"running":{"time":1}
,"time":{"shutdown":1}
,"shutdown":{"general":1}
,"general":{"recovering":1}
,"reserved":{"files":1}
,"displaying":{"index":1}
,"index":{"problems":1}
,"problems":{"save":1}
,"compacted":{"copy":1}
,"copy":{"file":1,"saving":1,"recover":1}
,"first":{"databases":1}
,"databases":{"returning":1}
,"returning":{"records":1}
,"incorrectly":{"find":1}
,"find":{"fixed":1,"including":1}
,"fixed":{"by":1}
,"by":{"saving":1,"misplaced":1}
,"saving":{"compacted":1}
,"command":{"aggressively":1,"open":1,"regular":1}
,"aggressively":{"attempts":1}
,"attempts":{"correct":1}
,"correct":{"file":1}
,"process":{"delete":1}
,"delete":{"corrupted":1}
,"corrupted":{"fields":1}
,"fields":{"layouts":1}
,"layout":{"objects":1}
,"objects":{"scripts":1}
,"reason":{"use":1}
,"use":{"recover":1,"command":1}
,"regular":{"file":1}
,"maintenance":{"conditions":1}
,"conditions":{"return":1}
,"return":{"incorrect":1}
,"incorrect":{"find":1}
,"including":{"mismatched":1}
,"mismatched":{"field":1}
,"types":{"records":1}
,"unexpectedly":{"deleted":1}
,"deleted":{"by":1}
,"misplaced":{"script":1}
,"script":{"step":1}
,"step":{"option":1}
,"option":{"set":1}
,"set":{"edit":1}
,"edit":{"relationship":1}
,"relationship":{"dialog":1}
,"dialog":{"box":1}
,"box":{"eliminated":1}
,"eliminated":{"all":1}
,"all":{"possibilities":1}
,"possibilities":{"assuming":1}
,"assuming":{"file":1}
,"special":{"notes":1}
,"notes":{"file":1}
}
;Search.control.loadWordPairs(pairs);
