var pairs =
{
"recovering":{"files":1}
,"files":{"if":1,"filemaker":1}
,"if":{"file":1,"open":1,"don\u2019t":1}
,"file":{"appears":1,"can\u2019t":1,"damaged":1,"note":1,"recovery":1,"menu":1,"recover":1,"ialog":1,"name":1,"se":1,"recover.log":1,"displays":1,"further":1,"scroll":1,"file":1,"created":1,"filemaker":1,"version":1,"recovered":1,"blocks":1,"copy":1,"backup":1,"safest":1,"newly":1}
,"appears":{"damaged":1}
,"damaged":{"first":1,"open":1,"filename":1,"convert":1,"file":1}
,"first":{"saving":1,"time":1}
,"saving":{"compacted":1}
,"compacted":{"copy":1}
,"copy":{"copies":1,"if":1,"recent":1}
,"copies":{"all":1}
,"all":{"data":1,"displayed":1}
,"data":{"rebuilds":1,"existing":1,"blocks":1,"distribution":1,"recovered":1}
,"rebuilds":{"tree":1}
,"tree":{"structure":1}
,"structure":{"database":1,"schema":1,"scanned":1}
,"database":{"saving":1,"dialog":1,"administrator":1,"component":1,"larger":1,"caused":1,"recovered":1,"take":1,"closed":1,"result":1}
,"can\u2019t":{"use":1}
,"use":{"advanced":1,"use":1,"recover":1,"steps":1,"file":1}
,"advanced":{"recovery":1,"ru":1,"file":1,"displays":1,"options":1,"filemaker":1}
,"recovery":{"options":1,"features":1,"settings":1,"operation":1,"process":1,"place":1,"event":1,"search":1,"recover":1}
,"options":{"dialog":1,"deselected":1,"set":1,"advanced":1,"save":1,"table":1,"component":1}
,"dialog":{"box":1}
,"box":{"compacted":1,"original":1,"type":1}
,"open":{"use":1,"encrypted":1,"log":1,"database":1}
,"recover":{"command":1,"select":1,"log":1,"file":1,"damaged":1}
,"command":{"alvage":1}
,"alvage":{"create":1}
,"create":{"new":1}
,"new":{"recovered":1,"disk":1}
,"recovered":{"file":1,"displays":1,"filemaker":1,"settings":1,"database":1,"rebuilding":1}
,"note":{"filemaker":1,"steps":1}
,"filemaker":{"pro":1,"knowledge":1}
,"pro":{"advanced":1,"12":1,"format":1,"11":1}
,"ru":{"ntime":1}
,"ntime":{"applications":1}
,"applications":{"support":1}
,"support":{"advanced":1}
,"features":{"choose":1}
,"choose":{"file":1}
,"menu":{"recover":1}
,"select":{"file":1,"filemaker":1,"use":1}
,"displays":{"ame":1,"file":1,"status":1,"separate":1}
,"ame":{"new":1}
,"ialog":{"box":1}
,"original":{"damaged":1,"database":1,"file":1}
,"filename":{"by":1,"error":1}
,"by":{"recovered":1,"new":1,"field":1,"record":1}
,"name":{"windows":1,"enter":1,"recovered":1}
,"windows":{"save":1}
,"save":{"macos":1,"if":1,"print":1}
,"macos":{"accept":1}
,"accept":{"default":1}
,"default":{"name":1,"file":1}
,"enter":{"name":1}
,"se":{"default":1,"recover":1}
,"settings":{"recommended":1,"select":1,"set":1}
,"recommended":{"sure":1}
,"sure":{"use":1}
,"deselected":{"skip":1}
,"skip":{"next":1}
,"next":{"step":1}
,"step":{"change":1}
,"change":{"recovery":1}
,"set":{"options":1,"tin":1}
,"tin":{"advanced":1}
,"encrypted":{"database":1}
,"type":{"encryption":1}
,"encryption":{"password":1}
,"password":{"if":1,"database":1}
,"don\u2019t":{"encryption":1}
,"administrator":{"progress":1}
,"progress":{"file":1}
,"operation":{"finished":1,"options":1}
,"finished":{"filemaker":1}
,"status":{"recovered":1,"depends":1}
,"log":{"recovery":1,"file":1}
,"process":{"open":1}
,"recover.log":{"file":1}
,"separate":{"window":1}
,"window":{"tab-delimited":1,"recent":1}
,"tab-delimited":{"format":1}
,"format":{"left":1,"fmp12":1,"convert":1,"if":1}
,"left":{"right":1}
,"right":{"columns":1}
,"columns":{"show":1}
,"show":{"date":1}
,"date":{"time":1}
,"time":{"time":1,"zone":1,"first":1,"recovered":1}
,"zone":{"recovery":1}
,"place":{"filename":1}
,"error":{"number":1}
,"number":{"description":1}
,"description":{"recovery":1}
,"event":{"save":1}
,"print":{"file":1}
,"further":{"examination":1}
,"examination":{"close":1}
,"close":{"window":1}
,"recent":{"data":1}
,"existing":{"recover.log":1}
,"scroll":{"end":1}
,"end":{"file":1}
,"search":{"filemaker":1}
,"knowledge":{"base":1}
,"base":{"keywords":1}
,"keywords":{"message":1}
,"message":{"note":1}
,"steps":{"apply":1,"recover":1}
,"apply":{"files":1}
,"12":{"format":1}
,"fmp12":{"use":1}
,"created":{"filemaker":1}
,"convert":{"file":1,"recover":1}
,"version":{"application":1}
,"application":{"converting":1}
,"converting":{"files":1}
,"11":{"advanced":1,"earlier":1}
,"earlier":{"file":1}
,"depends":{"result":1}
,"result":{"recovery":1,"rebuilding":1}
,"table":{"all":1}
,"displayed":{"each":1,"file":1}
,"each":{"database":1}
,"component":{"recovered":1,"messages":1}
,"messages":{"displayed":1}
,"blocks":{"scanned":1,"copied":1,"allocated":1}
,"scanned":{"rebuilt":1,"fields":1,"structure":1,"nnn":1,"field":1}
,"rebuilt":{"nnn":1,"modified":1,"removed":1}
,"nnn":{"locks":1,"nvalid":1,"issing":1,"tems":1}
,"locks":{"dropped":1}
,"dropped":{"nnn":1}
,"nvalid":{"data":1}
,"copied":{"copied":1,"logical":1}
,"logical":{"structure":1}
,"schema":{"scanned":1}
,"fields":{"tables":1,"scanned":1}
,"tables":{"nnn":1}
,"issing":{"fields":1}
,"tems":{"modified":1}
,"modified":{"scanned":1,"removed":1}
,"field":{"indexes":1,"by":1,"record":1}
,"indexes":{"rebuilt":1}
,"removed":{"rebuilding":1}
,"rebuilding":{"rebuilt":1,"cases":1,"index":1,"various":1}
,"cases":{"recovered":1}
,"larger":{"original":1}
,"caused":{"by":1}
,"disk":{"blocks":1}
,"allocated":{"database":1}
,"index":{"field":1}
,"record":{"by":1,"data":1}
,"distribution":{"larger":1}
,"backup":{"opy":1}
,"opy":{"original":1}
,"safest":{"use":1}
,"newly":{"recovered":1}
,"take":{"open":1}
,"closed":{"properly":1}
,"properly":{"last":1}
,"last":{"time":1}
,"various":{"internal":1}
,"internal":{"structures":1}
,"structures":{"deleted":1}
,"deleted":{"during":1}
,"during":{"recovery":1}
}
;Search.control.loadWordPairs(pairs);
