var pairs =
{
"changing":{"table":1}
,"table":{"layout":1,"want":1,"if":1,"occurrence":1}
,"layout":{"create":1,"database":1,"change":1,"mode":1,"want":1,"pop-up":1,"setup":1,"bar":1}
,"create":{"layout":1}
,"database":{"file":1}
,"file":{"multiple":1}
,"multiple":{"tables":1}
,"tables":{"choose":1}
,"choose":{"table":1,"layout":1}
,"want":{"records":1,"layout":1}
,"records":{"displayed":1,"list":1}
,"displayed":{"layout":1}
,"change":{"underlying":1,"table":1}
,"underlying":{"table":1}
,"if":{"layout":1}
,"mode":{"choose":1}
,"pop-up":{"menu":1}
,"menu":{"layout":1}
,"setup":{"layout":1,"button":1,"dialog":1}
,"button":{"layout":1}
,"bar":{"layout":1}
,"dialog":{"box":1}
,"box":{"choose":1}
,"occurrence":{"rom":1}
,"rom":{"show":1}
,"show":{"records":1}
,"list":{"change":1}
}
;Search.control.loadWordPairs(pairs);
