var pairs =
{
"onrecordrevert":{"performs":1}
,"performs":{"script":1}
,"script":{"efore":1,"step":1,"script":1,"return":1,"proceeds":1,"canceled":1,"rigger":1,"trigger":1,"triggers":1,"runs":1}
,"efore":{"set":1}
,"set":{"records":1}
,"records":{"reverted":1,"menu":1}
,"reverted":{"by":1}
,"by":{"records":1,"revert":1}
,"menu":{"revert":1}
,"revert":{"record":1,"record\u002Frequest":1,"field":1}
,"record":{"command":1,"script":1,"automatically":1,"clicking":1}
,"command":{"by":1}
,"record\u002Frequest":{"script":1}
,"step":{"event":1,"triggered":1}
,"event":{"processed":1,"triggered":1}
,"processed":{"browse":1}
,"browse":{"find":1}
,"find":{"modes":1}
,"modes":{"use":1,"trigger":1}
,"use":{"exit":1}
,"exit":{"script":1}
,"triggered":{"script":1}
,"return":{"true":1}
,"true":{"false":1,"event":1}
,"false":{"true":1,"event":1}
,"proceeds":{"false":1}
,"canceled":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"10.0":1}
,"10.0":{"script":1}
,"rigger":{"activates":1}
,"activates":{"nly":1,"if":1}
,"nly":{"uncommitted":1}
,"uncommitted":{"record":1}
,"trigger":{"activates":1,"actions":1,"script":1,"result":1}
,"if":{"save":1}
,"save":{"record":1}
,"automatically":{"layout":1}
,"layout":{"setup":1}
,"setup":{"dialog":1}
,"dialog":{"box":1}
,"box":{"selected":1,"activate":1}
,"selected":{"user":1}
,"user":{"reverts":1}
,"reverts":{"record":1}
,"clicking":{"revert":1}
,"field":{"field":1,"validation":1}
,"validation":{"error":1}
,"error":{"dialog":1}
,"activate":{"script":1}
,"actions":{"don\u2019t":1,"activate":1}
,"don\u2019t":{"activate":1}
,"triggers":{"list":1}
,"list":{"actions":1}
,"runs":{"modes":1}
}
;Search.control.loadWordPairs(pairs);
