var pairs =
{
"repeating":{"functions":1,"fields":1,"field":1}
,"functions":{"repeating":1,"perform":1}
,"perform":{"calculations":1}
,"calculations":{"repeating":1}
,"fields":{"function":1}
,"function":{"returns":1}
,"returns":{"extend":1}
,"extend":{"al":1}
,"al":{"lows":1}
,"lows":{"value":1}
,"value":{"non-repeating":1,"ield":1}
,"non-repeating":{"field":1}
,"field":{"repetition":1,"getrepetition":1,"by":1}
,"repetition":{"repeating":1}
,"getrepetition":{"contents":1}
,"contents":{"re":1}
,"re":{"peating":1}
,"peating":{"field":1}
,"by":{"number":1}
,"number":{"last":1}
,"last":{"last":1,"valid":1}
,"valid":{"non-blank":1}
,"non-blank":{"value":1}
}
;Search.control.loadWordPairs(pairs);
