var pairs =
{
"go":{"previous":1}
,"previous":{"field":1}
,"field":{"oves":1,"tab":1,"selected":1,"formatted":1,"object":1,"controls":1,"entry":1,"end":1}
,"oves":{"previous":1}
,"tab":{"order":1}
,"order":{"current":1,"data":1}
,"current":{"layout":1}
,"layout":{"none":1,"if":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"if":1}
,"if":{"field":1,"[isempty":1,"setting":1}
,"selected":{"script":1,"button":1,"field":1}
,"script":{"step":1,"trigger":1}
,"step":{"performed":1,"moves":1}
,"performed":{"script":1}
,"moves":{"last":1,"selected":1}
,"last":{"field":1}
,"formatted":{"button":1}
,"button":{"field":1,"object":1}
,"object":{"selected":1,"filemaker":1}
,"webdirect":{"cursor":1}
,"cursor":{"moves":1}
,"controls":{"field":1}
,"entry":{"validation":1,"automating":1}
,"validation":{"started":1}
,"started":{"onobjectexit":1}
,"onobjectexit":{"script":1}
,"trigger":{"if":1}
,"[isempty":{"customers":1}
,"customers":{":first":1}
,":first":{"name":1}
,"name":{")]":1,"\u0022]":1}
,")]":{"show":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"dialog":{"[\u0022":1}
,"[\u0022":{"enter":1}
,"enter":{"first":1}
,"first":{"name":1}
,"\u0022]":{"go":1}
,"end":{"if":1}
,"setting":{"tab":1}
,"data":{"entry":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
