var pairs =
{
"automating":{"odbc":1}
,"odbc":{"import":1,"data":1,"sql":1,"enter":1,"alerts":1,"driver":1}
,"import":{"import":1,"records":1,"script":1,"record":1,"order":1,"field":1,"feature":1,"keep":1,"odbc":1,"execute":1}
,"records":{"script":1}
,"script":{"step":1,"import":1}
,"step":{"accessing":1,"automates":1,"options":1,"choose":1,"odbc":1,"use":1,"save":1,"suppresses":1,"import":1,"external":1}
,"accessing":{"odbc":1}
,"data":{"sources":1,"source":1,"unicode":1}
,"sources":{"task":1,"supported":1}
,"task":{"repeat":1}
,"repeat":{"frequently":1}
,"frequently":{"create":1}
,"create":{"script":1}
,"automates":{"odbc":1}
,"options":{"behave":1,"windows":1}
,"behave":{"file":1}
,"file":{"formats":1}
,"formats":{"data":1}
,"source":{"option":1,"name":1,"im":1,"import":1,"options":1}
,"option":{"stores":1}
,"stores":{"data":1,"field":1}
,"name":{"location":1,"password":1,"user":1}
,"location":{"user":1}
,"user":{"id":1,"name":1}
,"id":{"password":1}
,"password":{"optional":1,"select":1,"odbc":1,"dialog":1,"sql":1}
,"optional":{"sql":1}
,"sql":{"query":1,"statements":1,"script":1,"data":1}
,"query":{"executed":1,"dialog":1,"including":1,"toring":1,"field":1,"stored":1,"builder":1,"previous":1,"non-global":1,"current":1}
,"executed":{"data":1,"defining":1}
,"im":{"port":1}
,"port":{"records":1}
,"choose":{"odbc":1,"execute":1}
,"dialog":{"box":1,"boxes":1}
,"box":{"calculation":1,"dialog:off":1,"scripted":1}
,"calculation":{"generate":1}
,"generate":{"query":1}
,"including":{"ch":1}
,"ch":{"oos":1}
,"oos":{"ing":1}
,"ing":{"field":1}
,"field":{"query":1,"type":1,"order":1,"mapping":1}
,"toring":{"sql":1}
,"type":{"new":1}
,"new":{"query":1}
,"stored":{"import":1}
,"record":{"script":1,"executed":1}
,"use":{"sql":1,"import":1}
,"builder":{"construct":1}
,"construct":{"query":1}
,"save":{"user":1}
,"select":{"save":1}
,"enter":{"password":1}
,"dialog:off":{"ption":1}
,"ption":{"hides":1}
,"hides":{"all":1}
,"all":{"dialog":1}
,"boxes":{"during":1}
,"during":{"odbc":1}
,"order":{"option":1,"import":1,"data":1}
,"mapping":{"dialog":1}
,"scripted":{"imports":1}
,"imports":{"set":1}
,"set":{"error":1}
,"error":{"capture":1}
,"capture":{"script":1}
,"suppresses":{"odbc":1}
,"alerts":{"odbc":1}
,"feature":{"saves":1}
,"saves":{"data":1}
,"previous":{"odbc":1}
,"keep":{"mind":1}
,"mind":{"selecting":1}
,"selecting":{"import":1}
,"windows":{"automate":1,"if":1}
,"automate":{"interaction":1}
,"interaction":{"across":1}
,"across":{"multiple":1}
,"multiple":{"applications":1}
,"applications":{"explore":1}
,"explore":{"activex":1}
,"activex":{"functionality":1,"automation":1}
,"functionality":{"scripting":1}
,"scripting":{"activex":1}
,"automation":{"windows":1}
,"if":{"choose":1,"use":1}
,"execute":{"query":1,"sql":1}
,"non-global":{"field":1}
,"current":{"record":1}
,"defining":{"global":1}
,"global":{"fields":1,"storage":1}
,"fields":{"fields":1,"global":1}
,"storage":{"sql":1}
,"statements":{"limited":1}
,"limited":{"maximum":1}
,"maximum":{"length":1}
,"length":{"256":1}
,"256":{"characters":1}
,"characters":{"512":1}
,"512":{"kb":1}
,"kb":{"if":1}
,"unicode":{"strings":1,"inconsistent":1}
,"strings":{"odbc":1}
,"driver":{"support":1}
,"support":{"unicode":1}
,"inconsistent":{"odbc":1}
,"external":{"sql":1}
,"supported":{"runtime":1}
,"runtime":{"solutions":1}
}
;Search.control.loadWordPairs(pairs);
