var pairs =
{
"hexdecode":{"returns":1,"data":1,"46696c654d616b6572":1,"table":1}
,"returns":{"container":1,"text":1,"hexdecode":1,"filemaker":1}
,"container":{"text":1,"field":1,"filemaker":1,"data":1}
,"text":{"content":1,"encoded":1,"field":1,"container":1,"data":1,"utf-8":1}
,"content":{"text":1,"stored":1}
,"encoded":{"hexadecimal":1,"decode":1}
,"hexadecimal":{"format":1,"data":1,"value":1}
,"format":{"hexdecode":1,"hex":1}
,"data":{"filenamewithextension":1,"-text":1,"decode":1,"data":1,"parameter":1,"return":1,"function":1,"text":1}
,"filenamewithextension":{"data":1,"-text":1,"parameter":1}
,"-text":{"expression":1}
,"expression":{"text":1}
,"field":{"hexadecimal":1,"filename":1,"text":1,"variable":1,"stores":1,"set":1,"[table":1}
,"decode":{"filenamewithextension":1,"hexadecimal":1}
,"filename":{"extension":1}
,"extension":{"use":1,"function":1}
,"use":{"returned":1}
,"returned":{"content":1}
,"stored":{"container":1}
,"filemaker":{"pro":1,"decodes":1}
,"pro":{"16.0":1}
,"16.0":{"decode":1}
,"value":{"return":1,"represents":1}
,"return":{"result":1}
,"result":{"text":1,"container":1}
,"variable":{"text":1,"container":1}
,"parameter":{"text":1,"if":1}
,"utf-8":{"format":1}
,"hex":{"encoded":1}
,"represents":{"binary":1}
,"binary":{"data":1}
,"if":{"filename":1}
,"function":{"returns":1,"supported":1}
,"supported":{"runtime":1}
,"runtime":{"solutions":1}
,"solutions":{"returns":1}
,"46696c654d616b6572":{"returns":1}
,"decodes":{"hexadecimal":1}
,"stores":{"file":1}
,"file":{"named":1}
,"named":{"key.data":1}
,"key.data":{"container":1}
,"set":{"field":1}
,"[table":{":container":1}
,":container":{"hexdecode":1}
,"table":{":text":1}
,":text":{"key.data":1}
}
;Search.control.loadWordPairs(pairs);
