var pairs =
{
"script":{"workspace":1,"steps":1,"ctrl":1,"new":1,"use":1,"editing":1,"step":1,"script":1}
,"workspace":{"eyboard":1,"create":1,"alt":1,"anes":1}
,"eyboard":{"shortcuts":1}
,"shortcuts":{"windows":1,"script":1,"debug":1}
,"windows":{"use":1}
,"use":{"hese":1,"advanced":1}
,"hese":{"keyboard":1}
,"keyboard":{"shortcuts":1}
,"create":{"edit":1,"new":1}
,"edit":{"scripts":1}
,"scripts":{"note":1,"disable":1,"debug":1}
,"note":{"keyboard":1}
,"debug":{"scripts":1,"selected":1}
,"disable":{"script":1,"selected":1}
,"steps":{"use":1}
,"advanced":{"tools":1}
,"tools":{"general":1,"press":1,"selected":1}
,"general":{"preference":1}
,"preference":{"selected":1}
,"selected":{"ad":1,"script":1,"ctrl":1}
,"ad":{"vanced":1}
,"vanced":{"tools":1}
,"press":{"create":1}
,"new":{"script":1,"tab":1,"window":1}
,"ctrl":{"save":1,"open":1,"shift":1,"alt":1,"close":1,"apostrophe":1,"up":1,"arrow":1,"disable":1,"+\u002Fprint":1}
,"save":{"script":1,"run":1,"all":1}
,"open":{"selected":1}
,"tab":{"ctrl":1,"script":1,"shift":1,"select":1}
,"window":{"ctrl":1}
,"shift":{"run":1,"debug":1,"alt":1,"move":1,"tab":1}
,"run":{"selected":1}
,"alt":{"save":1,"close":1,"f4":1}
,"all":{"scripts":1,"tabs":1,"script":1}
,"close":{"current":1,"all":1,"script":1}
,"current":{"tab":1}
,"tabs":{"ctrl":1}
,"f4":{"move":1}
,"move":{"next":1,"previous":1,"script":1,"selected":1,"options":1}
,"next":{"tab":1}
,"editing":{"pane":1}
,"pane":{"ctrl":1,"left":1}
,"previous":{"tab":1}
,"anes":{"ctrl":1}
,"apostrophe":{"move":1}
,"step":{"up":1,"options":1,"option":1,"delete":1,"ctrl":1,"use":1}
,"up":{"script":1,"arrow":1}
,"arrow":{"ctrl":1,"add":1,"right":1,"tab":1}
,"add":{"comment":1}
,"comment":{"blank":1}
,"blank":{"line":1}
,"line":{"display":1}
,"display":{"script":1}
,"options":{"plus":1,"brackets":1,"esc":1}
,"plus":{"move":1}
,"brackets":{"script":1}
,"left":{"arrow":1}
,"right":{"arrow":1}
,"select":{"script":1}
,"option":{"hen":1}
,"hen":{"focus":1}
,"focus":{"pace":1,"all":1}
,"pace":{"bar":1}
,"bar":{"remove":1}
,"remove":{"focus":1}
,"esc":{"delete":1}
,"delete":{"selected":1,"backspace":1}
,"backspace":{"duplicate":1}
,"duplicate":{"selected":1}
,"+\u002Fprint":{"selected":1}
}
;Search.control.loadWordPairs(pairs);
