var pairs =
{
"troubleshooting":{"if":1,"topics":1}
,"if":{"question":1}
,"question":{"issue":1,"filemaker":1}
,"issue":{"basic":1}
,"basic":{"steps":1}
,"steps":{"help":1}
,"help":{"find":1,"menu":1}
,"find":{"solution":1}
,"solution":{"sure":1}
,"sure":{"system":1}
,"system":{"meets":1}
,"meets":{"requirements":1}
,"requirements":{"filemaker":1}
,"filemaker":{"pro":1,"knowledge":1,"community":1}
,"pro":{"advanced":1}
,"advanced":{"technical":1,"update":1}
,"technical":{"specifications":1}
,"specifications":{"install":1}
,"install":{"filemaker":1}
,"update":{"choose":1}
,"choose":{"help":1}
,"menu":{"check":1,"product":1,"filemaker":1,"service":1}
,"check":{"updates":1,"documentation":1}
,"updates":{"check":1}
,"documentation":{"release":1,"filemaker":1}
,"release":{"notes":1}
,"notes":{"choose":1}
,"product":{"documentation":1}
,"knowledge":{"base":1}
,"base":{"article":1,"post":1,"filemaker":1}
,"article":{"common":1}
,"common":{"troubleshooting":1}
,"topics":{"search":1}
,"search":{"articles":1}
,"articles":{"filemaker":1}
,"post":{"question":1}
,"community":{"choose":1,"support":1,"all":1}
,"support":{"options":1,"filemaker":1}
,"options":{"choose":1}
,"service":{"support":1}
,"all":{"languages":1}
}
;Search.control.loadWordPairs(pairs);
