var pairs =
{
"get":{"activemodifier":1,"activemodifierkeys":1,"active":1,"modifier":1,"current":1}
,"activemodifier":{"keys":1}
,"keys":{"returns":1,"pressed":1,"shift":1,"get":1}
,"returns":{"number":1,"returns":1,"shift":1}
,"number":{"keyboard":1,"filemaker":1,"returned":1}
,"keyboard":{"modifier":1}
,"modifier":{"keys":1,"key":1}
,"pressed":{"get":1,"values":1,"computer":1}
,"activemodifierkeys":{"none":1,"get":1}
,"none":{"number":1}
,"filemaker":{"pro":1,"webdirect":1,"go":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"number":1}
,"returned":{"calculated":1}
,"calculated":{"by":1}
,"by":{"summing":1}
,"summing":{"numbers":1}
,"numbers":{"representing":1}
,"representing":{"each":1}
,"each":{"modifier":1}
,"key":{"control":1,"while":1,"get":1,"active":1}
,"control":{"shift":1,"macos":1}
,"shift":{"pressed":1,"=1":1,"alt":1}
,"values":{"assigned":1}
,"assigned":{"keys":1}
,"=1":{"caps":1}
,"caps":{"lock":1}
,"lock":{"=2":1}
,"=2":{"ctrl":1}
,"ctrl":{"windows":1}
,"windows":{"control":1,"option":1,"get":1}
,"macos":{"=4":1,"=8":1,"=16":1}
,"=4":{"alt":1}
,"alt":{"windows":1,"option":1,"pressed":1}
,"option":{"macos":1,"key":1}
,"=8":{"command":1}
,"command":{"macos":1}
,"=16":{"use":1}
,"use":{"function":1}
,"function":{"script":1,"supported":1}
,"script":{"includes":1,"step":1}
,"includes":{"custom":1}
,"custom":{"dialog":1}
,"dialog":{"box":1}
,"box":{"script":1}
,"step":{"cancel":1}
,"cancel":{"button":1}
,"button":{"perform":1}
,"perform":{"special":1}
,"special":{"action":1}
,"action":{"if":1}
,"if":{"user":1}
,"user":{"presses":1}
,"presses":{"alt":1}
,"while":{"clicking":1}
,"clicking":{"filemaker":1}
,"webdirect":{"filemaker":1}
,"go":{"function":1}
,"supported":{"returns":1}
,"computer":{"running":1}
,"running":{"windows":1}
,"active":{"modifier":1}
,"current":{"modifier":1}
}
;Search.control.loadWordPairs(pairs);
