var pairs =
{
"navigating":{"web":1}
,"web":{"viewers":1,"browsers":1,"content":1,"viewer":1}
,"viewers":{"web":1,"display":1}
,"browsers":{"except":1}
,"except":{"display":1}
,"display":{"webpages":1,"web":1,"map":1}
,"webpages":{"filemaker":1,"copy":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"unique":1}
,"unique":{"feature":1}
,"feature":{"web":1}
,"content":{"related":1}
,"related":{"current":1}
,"current":{"record":1}
,"record":{"browse":1,"table":1,"se":1}
,"browse":{"each":1}
,"each":{"record":1}
,"table":{"names":1}
,"names":{"addresses":1}
,"addresses":{"web":1}
,"viewer":{"display":1,"move":1}
,"map":{"location":1}
,"location":{"record":1}
,"se":{"shortcut":1}
,"shortcut":{"menu":1}
,"menu":{"web":1}
,"move":{"webpages":1}
,"copy":{"text":1}
,"text":{"images":1}
,"images":{"perform":1}
,"perform":{"tasks":1}
}
;Search.control.loadWordPairs(pairs);
