var pairs =
{
"get":{"last":1,"lasterror":1,"lastexternalerrordetail":1,"error":1,"recent":1}
,"last":{"error":1}
,"error":{"returns":1,"occurred":1,"codes":1,"occurs":1,"code":1,"1408":1,"use":1,"1409":1,"condition":1,"capture":1,"calculation":1,"get":1}
,"returns":{"number":1,"filemaker":1,"false":1,"error":1,"recent":1,"401":1}
,"number":{"error":1,"filemaker":1}
,"occurred":{"execution":1}
,"execution":{"executed":1}
,"executed":{"script":1,"by":1,"returns":1}
,"script":{"step":1,"steps":1,"triggers":1,"executed":1,"trigger":1,"halt":1,"if":1,"responds":1,"set":1}
,"step":{"get":1,"applescript":1,"option":1,"executed":1}
,"lasterror":{"none":1,"get":1}
,"none":{"number":1}
,"filemaker":{"pro":1,"error":1}
,"pro":{"6.0":1,"advanced":1}
,"6.0":{"earlier":1}
,"earlier":{"use":1}
,"use":{"function":1,"get":1,"evaluationerror":1}
,"function":{"detect":1,"if":1,"returns":1,"create":1,"set":1}
,"detect":{"control":1}
,"control":{"outcome":1,"script":1}
,"outcome":{"errors":1}
,"errors":{"filemaker":1,"displaying":1}
,"codes":{"macos":1}
,"macos":{"filemaker":1}
,"advanced":{"if":1}
,"if":{"error":1,"script":1,"else":1,"end":1,"loop":1}
,"occurs":{"while":1}
,"while":{"performing":1}
,"performing":{"applescript":1,"sql":1}
,"applescript":{"via":1,"mac":1,"error":1}
,"via":{"erform":1}
,"erform":{"applescript":1}
,"mac":{"os":1}
,"os":{"script":1}
,"code":{"returned":1,"set":1,"detailed":1}
,"returned":{"odbc":1}
,"odbc":{"imports":1,"data":1}
,"imports":{"execute":1}
,"execute":{"sql":1}
,"sql":{"script":1,"query":1}
,"steps":{"if":1,"clear":1}
,"query":{"returns":1}
,"1408":{"detailed":1,"script":1}
,"detailed":{"error":1}
,"lastexternalerrordetail":{"function":1}
,"1409":{"odbc":1}
,"data":{"sources":1}
,"sources":{"relationships":1}
,"relationships":{"graph":1}
,"graph":{"returns":1}
,"triggers":{"allow":1}
,"allow":{"activating":1}
,"activating":{"command":1}
,"command":{"event":1}
,"event":{"canceled":1}
,"canceled":{"if":1,"error":1}
,"by":{"script":1,"filemaker":1}
,"trigger":{"returns":1}
,"false":{"value":1}
,"value":{"command":1}
,"set":{"20":1,"error":1}
,"20":{"control":1}
,"clear":{"last":1}
,"condition":{"reported":1,"exists":1,"cleared":1}
,"reported":{"by":1}
,"else":{"else":1,"if":1}
,"end":{"if":1,"loop":1}
,"loop":{"exit":1,"if":1}
,"exit":{"loop":1,"script":1}
,"halt":{"script":1}
,"exists":{"user":1}
,"user":{"cancels":1}
,"cancels":{"action":1}
,"action":{"existing":1}
,"existing":{"error":1}
,"cleared":{"actions":1}
,"actions":{"fail":1}
,"fail":{"connect":1}
,"connect":{"host":1}
,"host":{"host\u2019s":1}
,"host\u2019s":{"ssl":1}
,"ssl":{"certificate":1}
,"certificate":{"verified":1}
,"verified":{"function":1}
,"create":{"script":1}
,"responds":{"errors":1}
,"displaying":{"alerts":1}
,"alerts":{"use":1}
,"capture":{"script":1}
,"option":{"evaluate":1}
,"evaluate":{"error":1}
,"calculation":{"expression":1}
,"expression":{"use":1}
,"evaluationerror":{"function":1}
,"recent":{"script":1,"error":1}
,"401":{"records":1}
,"records":{"found":1}
,"found":{"perform":1}
,"perform":{"find":1}
,"find":{"script":1}
}
;Search.control.loadWordPairs(pairs);
