var pairs =
{
"creating":{"new":1}
,"new":{"table":1,"target":1}
,"table":{"imported":1,"based":1,"schemas":1,"set":1,"target":1,"source":1,"name":1,"number":1,"references":1,"import":1,"table":1,"preserve":1,"first":1,"data":1}
,"imported":{"data":1,"via":1,"table":1,"tables":1,"resolve":1,"references":1,"fields":1}
,"data":{"importing":1,"existing":1,"consolidate":1,"new":1,"accessed":1,"first":1,"update":1,"imported":1,"if":1}
,"importing":{"data":1}
,"existing":{"filemaker":1,"file":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"file":1,"session":1,"setti":1}
,"file":{"import":1,"manually":1,"refreshes":1,"choose":1,"table":1,"imported":1,"menu":1}
,"import":{"new":1,"data":1,"read-only":1,"field":1,"table":1,"process":1}
,"based":{"schema":1}
,"schema":{"imported":1}
,"consolidate":{"tables":1}
,"tables":{"multiple":1,"contain":1}
,"multiple":{"files":1}
,"files":{"single":1}
,"single":{"database":1}
,"database":{"file":1,"target":1,"references":1}
,"manually":{"re-create":1,"run":1,"imported":1}
,"re-create":{"table":1}
,"schemas":{"import":1}
,"set":{"up":1}
,"up":{"recurring":1}
,"recurring":{"imports":1,"import":1}
,"imports":{"data":1,"follow":1}
,"accessed":{"external":1}
,"external":{"file":1}
,"refreshes":{"automatically":1}
,"automatically":{"view":1}
,"view":{"imported":1}
,"first":{"time":1,"references":1}
,"time":{"during":1}
,"during":{"filemaker":1}
,"session":{"manually":1}
,"run":{"data":1}
,"update":{"script":1}
,"script":{"data":1}
,"via":{"recurring":1}
,"read-only":{"filemaker":1}
,"setti":{"ng":1}
,"ng":{"up":1}
,"follow":{"procedures":1}
,"procedures":{"mporting":1}
,"mporting":{"data":1}
,"choose":{"new":1}
,"target":{"ist":1,"list":1,"fields":1,"table":1}
,"ist":{"import":1}
,"field":{"mapping":1}
,"mapping":{"dialog":1}
,"dialog":{"box":1}
,"box":{"name":1,"anage":1}
,"name":{"imported":1,"if":1}
,"source":{"table":1}
,"if":{"file":1,"referenced":1,"table":1,"import":1}
,"number":{"table\u2019s":1}
,"table\u2019s":{"name":1}
,"contain":{"broken":1}
,"broken":{"references":1,"import":1}
,"references":{"fields":1,"manually":1,"maintained":1,"table":1,"if":1,"broken":1}
,"fields":{"file":1,"type":1,"new":1,"by":1,"source":1}
,"resolve":{"references":1}
,"maintained":{"if":1}
,"referenced":{"fields":1}
,"preserve":{"references":1}
,"type":{"calculation":1}
,"calculation":{"summary":1}
,"summary":{"select":1}
,"select":{"new":1}
,"list":{"modify":1,"import":1}
,"modify":{"target":1,"fields":1}
,"anage":{"database":1}
,"process":{"complete":1}
,"complete":{"modify":1}
,"by":{"choosing":1}
,"choosing":{"file":1}
,"menu":{"manage":1}
,"manage":{"database":1}
}
;Search.control.loadWordPairs(pairs);
