var pairs =
{
"verifycontainer":{"returns":1,"field":1}
,"returns":{"false":1,"true":1,"boolean":1,"if":1}
,"false":{"if":1}
,"if":{"container":1,"files":1,"deletions":1,"field":1}
,"container":{"data":1,"field":1}
,"data":{"changed":1,"stored":1}
,"changed":{"deleted":1}
,"deleted":{"filemaker":1,"true":1}
,"filemaker":{"returns":1,"pro":1}
,"true":{"verifycontainer":1,"if":1}
,"field":{"field":1,"-any":1,"text":1,"false":1,"container":1}
,"-any":{"text":1}
,"text":{"number":1,"expression":1,"filemaker":1}
,"number":{"date":1}
,"date":{"time":1}
,"time":{"timestamp":1}
,"timestamp":{"container":1}
,"expression":{"numeric":1,"text":1}
,"numeric":{"expression":1}
,"pro":{"12.0":1}
,"12.0":{"returns":1}
,"boolean":{"value":1}
,"value":{"representing":1}
,"representing":{"validity":1}
,"validity":{"data":1}
,"stored":{"externally":1}
,"externally":{"container":1,"modified":1}
,"files":{"saved":1}
,"saved":{"externally":1}
,"modified":{"deleted":1}
,"deletions":{"occurred":1}
,"occurred":{"returns":1}
}
;Search.control.loadWordPairs(pairs);
