var pairs =
{
"finding":{"replacing":1}
,"replacing":{"data":1}
,"data":{"yo":1,"across":1,"search":1,"find":1,"fields":1,"layout":1}
,"yo":{"find":1}
,"find":{"replace":1,"request":1,"requests":1,"layout":1,"box":1,"travel.com":1,"stone":1,"mode":1,"match":1,"half-width":1,"data":1,"modes":1}
,"replace":{"data":1,"box":1,"invisible":1,"characters":1,"text":1}
,"across":{"multiple":1,"found":1,"text":1,"browse":1,"all":1}
,"multiple":{"fields":1}
,"fields":{"including":1,"record":1,"permitted":1,"formatted":1,"frontmost":1}
,"including":{"related":1}
,"related":{"fields":1}
,"record":{"find":1}
,"request":{"across":1,"note":1}
,"found":{"set":1}
,"set":{"records":1,"earch":1}
,"records":{"find":1,"current":1}
,"requests":{"across":1,"current":1}
,"text":{"objects":1,"all":1}
,"objects":{"layout":1}
,"layout":{"browse":1,"mode":1,"just":1,"buttons":1,"includes":1,"panel":1}
,"browse":{"find":1,"mode":1}
,"mode":{"choose":1,"search":1,"filemaker":1,"find":1}
,"choose":{"edit":1}
,"edit":{"menu":1,"boxes":1}
,"menu":{"find\u002Freplace":1}
,"find\u002Freplace":{"find\u002Freplace":1,"find":1,"operation":1}
,"box":{"type":1,"set":1}
,"type":{"data":1,"replacement":1,"find\u002Freplace":1}
,"search":{"replace":1,"occurrences":1,"across":1,"web":1}
,"replacement":{"data":1}
,"invisible":{"characters":1}
,"characters":{"tabs":1,"field":1,"examples":1,"perform":1}
,"tabs":{"carriage":1}
,"carriage":{"returns":1}
,"returns":{"manually":1}
,"manually":{"copy":1}
,"copy":{"paste":1}
,"paste":{"characters":1}
,"field":{"find":1}
,"earch":{"options":1}
,"options":{"select":1}
,"select":{"match":1}
,"match":{"search":1,"case":1}
,"occurrences":{"bounded":1}
,"bounded":{"by":1}
,"by":{"spaces":1}
,"spaces":{"and\u002For":1}
,"and\u002For":{"punctuation":1}
,"punctuation":{"characters":1}
,"examples":{"finds":1}
,"finds":{"good-bye":1,"travel":1,"stone":1,"half-width":1}
,"good-bye":{"travel":1}
,"travel":{"finds":1,"travel":1,"travel.com":1}
,"travel.com":{".com":1,"stone":1}
,".com":{"find":1}
,"stone":{"house":1}
,"house":{"[space]":1,"sentence":1}
,"[space]":{"finds":1,"[space]":1,"large":1}
,"sentence":{"old":1}
,"old":{"stone":1}
,"large":{"garden":1}
,"garden":{"ut":1,"option":1}
,"ut":{"find":1}
,"option":{"search":1,"cleared":1}
,"all":{"records":1,"find":1,"panels":1}
,"current":{"layout":1,"record":1,"find":1}
,"just":{"current":1}
,"note":{"layout":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"searches":1}
,"searches":{"current":1}
,"buttons":{"perform":1,"checkboxes":1}
,"perform":{"type":1,"separate":1}
,"operation":{"want":1}
,"want":{"files":1}
,"files":{"contain":1}
,"contain":{"japanese":1}
,"japanese":{"data":1}
,"case":{"option":1}
,"cleared":{"simultaneously":1}
,"simultaneously":{"find":1}
,"half-width":{"full-width":1}
,"full-width":{"version":1,"character":1}
,"version":{"character":1}
,"character":{"comprehensively":1,"ou":1}
,"comprehensively":{"find":1}
,"separate":{"finds":1}
,"ou":{"search":1}
,"web":{"viewers":1}
,"viewers":{"find":1}
,"permitted":{"view":1,"modify":1}
,"view":{"replace":1}
,"modify":{"find":1}
,"formatted":{"pop-up":1,"edit":1}
,"pop-up":{"menus":1}
,"menus":{"radio":1}
,"radio":{"buttons":1}
,"checkboxes":{"limitation":1}
,"limitation":{"find":1}
,"includes":{"fields":1}
,"boxes":{"drop-down":1}
,"drop-down":{"lists":1}
,"lists":{"if":1}
,"if":{"current":1}
,"panel":{"controls":1}
,"controls":{"browse":1}
,"modes":{"find":1}
,"frontmost":{"anel":1}
,"anel":{"layout":1}
,"panels":{"find":1}
}
;Search.control.loadWordPairs(pairs);
