var pairs =
{
"insert":{"index":1}
,"index":{"astes":1,"field":1,"inserts":1,"value":1,"active":1,"browse":1,"dialog":1,"returns":1,"display":1,"[customers":1,"automating":1}
,"astes":{"value":1}
,"value":{"index":1,"field":1,"enter":1}
,"field":{"select":1,"if":1,"allows":1,"paste":1,"type":1,"use":1,"filemaker":1,"exist":1,"deselected":1,"indexing":1,"find":1,"index":1}
,"select":{"entire":1,"option":1,"entry":1,"preexisting":1}
,"entire":{"contents":1}
,"contents":{"replaces":1,"field":1}
,"replaces":{"contents":1}
,"if":{"select":1,"field":1,"indexing":1}
,"option":{"insert":1,"view":1,"automatically":1}
,"inserts":{"result":1}
,"result":{"cursor":1}
,"cursor":{"position":1}
,"position":{"end":1}
,"end":{"field\u0027s":1}
,"field\u0027s":{"data":1}
,"data":{"go":1,"entry":1}
,"go":{"target":1}
,"target":{"field":1}
,"allows":{"field":1}
,"paste":{"index":1}
,"type":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1,"advanced":1}
,"6.0":{"earlier":1}
,"earlier":{"script":1}
,"script":{"step":1,"if":1,"performed":1}
,"step":{"displays":1,"field":1}
,"displays":{"index":1,"view":1}
,"active":{"field":1}
,"use":{"insert":1}
,"browse":{"find":1}
,"find":{"modes":1,"mode":1,"[]":1}
,"modes":{"filemaker":1}
,"advanced":{"displays":1,"last":1}
,"view":{"index":1}
,"dialog":{"box":1}
,"box":{"user":1,"remembered":1}
,"user":{"select":1}
,"entry":{"method":1,"correct":1}
,"method":{"promotes":1}
,"promotes":{"consistent":1}
,"consistent":{"data":1}
,"correct":{"spelling":1}
,"spelling":{"script":1}
,"last":{"selected":1}
,"selected":{"show":1}
,"show":{"individual":1}
,"individual":{"option":1}
,"remembered":{"script":1}
,"exist":{"layout":1}
,"layout":{"script":1}
,"performed":{"insert":1}
,"returns":{"error":1}
,"error":{"code":1}
,"code":{"captured":1,"returned":1}
,"captured":{"get":1}
,"get":{"lasterror":1}
,"lasterror":{"function":1}
,"function":{"if":1}
,"indexing":{"field":1,"defining":1,"options":1}
,"deselected":{"option":1}
,"automatically":{"create":1}
,"create":{"indexes":1}
,"indexes":{"index":1}
,"display":{"error":1}
,"returned":{"field":1}
,"defining":{"field":1}
,"options":{"displays":1}
,"mode":{"user":1,"[pause":1}
,"preexisting":{"value":1}
,"enter":{"find":1}
,"[pause":{"on]":1}
,"on]":{"insert":1}
,"[customers":{":company]":1}
,":company]":{"perform":1}
,"perform":{"find":1}
,"[]":{"field":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
