var pairs =
{
"get":{"folder":1,"desktoppath":1,"directory":1}
,"folder":{"path":1,"allow":1,"set":1,"selection":1,"sets":1,"windows":1,"macos":1,"folder":1,"get":1,"$folder]":1,"export":1,"creation":1,"\u0022]":1}
,"path":{"ets":1,"folder":1,"selected":1,"format":1,"[$folder":1,"[allow":1}
,"ets":{"variable":1}
,"variable":{"qualified":1,"sets":1,"path":1,"script":1,"[$path":1}
,"qualified":{"path":1}
,"allow":{"fo":1}
,"fo":{"lder":1}
,"lder":{"cr":1}
,"cr":{"eation":1}
,"eation":{"users":1}
,"users":{"create":1}
,"create":{"new":1,"folders":1}
,"new":{"folders":1}
,"folders":{"while":1,"go":1}
,"while":{"browse":1}
,"browse":{"file":1}
,"file":{"system":1}
,"system":{"variable":1}
,"sets":{"local":1,"variable":1,"products":1}
,"local":{"global":1}
,"global":{"variable":1}
,"selected":{"folder":1}
,"set":{"variable":1,"field":1}
,"script":{"step":1}
,"step":{"dialog":1,"prompts":1}
,"dialog":{"ti":1,"box":1}
,"ti":{"tle":1}
,"tle":{"custom":1}
,"custom":{"name":1}
,"name":{"folder":1}
,"selection":{"dialog":1}
,"box":{"default":1,"displays":1}
,"default":{"lo":1}
,"lo":{"cation":1}
,"cation":{"path":1}
,"displays":{"filemaker":1,"desktop":1}
,"filemaker":{"pro":1}
,"pro":{"14.0":1}
,"14.0":{"script":1}
,"prompts":{"user":1}
,"user":{"select":1}
,"select":{"folder":1,"pictures":1}
,"windows":{"path":1}
,"format":{"\u002Fdrive:\u002F<":1,"\u002Fdrivename\u002F<":1}
,"\u002Fdrive:\u002F<":{"selected":1}
,"macos":{"path":1}
,"\u002Fdrivename\u002F<":{"selected":1}
,"desktop":{"prompts":1}
,"pictures":{"folder":1}
,"products":{":pictures":1,":picture":1}
,":pictures":{"folder":1}
,"[$folder":{"select":1}
,"desktoppath":{")]":1}
,")]":{"set":1}
,"field":{"[products":1,"perform":1,"contents":1}
,"[products":{":pictures":1,":picture":1}
,"$folder]":{"performs":1}
,"performs":{"find":1}
,"find":{"prompts":1,"[restore]":1}
,"export":{"loops":1,"files":1,"folder":1,"field":1}
,"loops":{"records":1}
,"records":{"export":1}
,"files":{"products":1,"automating":1}
,":picture":{"field":1,"$path":1}
,"perform":{"find":1}
,"[restore]":{"get":1}
,"[allow":{"folder":1}
,"creation":{"$folder":1}
,"$folder":{"export":1}
,"\u0022]":{"loop":1}
,"loop":{"set":1,"get":1}
,"[$path":{"value:$folder":1}
,"value:$folder":{"&products":1}
,"&products":{":picture]":1}
,":picture]":{"export":1}
,"contents":{"[products":1}
,"$path":{"create":1}
,"go":{"record\u002Frequest\u002Fpage":1}
,"record\u002Frequest\u002Fpage":{"[next":1}
,"[next":{"exit":1}
,"exit":{"last":1}
,"last":{"end":1}
,"end":{"loop":1}
,"directory":{"managing":1}
,"managing":{"files":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
