var pairs =
{
"setting":{"up":1,"script":1}
,"up":{"field":1,"control":1,"value":1}
,"field":{"display":1,"inspector":1,"choose":1,"data":1,"select":1,"combo":1,"save":1,"layout":1,"tab":1,"option":1,"stored":1,"displayed":1,"list":1,"note":1,"types":1,"use":1,"filemaker":1,"checkbox":1,"if":1,"layouts":1,"formatted":1,"larger":1,"text":1,"attributes":1,"auto-complete":1,"you\u2019re":1,"values":1,"set":1,"options":1,"users":1,"field":1,"displays":1,"triggers":1,"user":1,"script":1,"setting":1,"by":1,"pressing":1}
,"display":{"pop-up":1,"values":1,"edit":1,"data":1,"value":1,"related":1}
,"pop-up":{"menu":1,"menus":1}
,"menu":{"checkbox":1,"value":1,"users":1,"list":1,"first":1,"if":1}
,"checkbox":{"set":1,"sets":1,"allows":1,"columnar":1}
,"set":{"control":1,"up":1,"value":1,"radio":1,"selected":1,"checkbox":1,"default":1}
,"control":{"data":1,"styles":1,"style":1}
,"data":{"entry":1,"data":1,"tab":1,"default":1,"conceal":1,"concealed":1,"value":1,"formatting":1,"type":1}
,"entry":{"easier":1,"values":1,"if":1,"format":1}
,"easier":{"consistent":1}
,"consistent":{"by":1}
,"by":{"displaying":1,"method":1}
,"displaying":{"fields":1}
,"fields":{"drop-down":1,"tab":1,"field":1,"select":1,"formatting":1,"set":1}
,"drop-down":{"lists":1,"list":1,"calendar":1}
,"lists":{"pop-up":1,"table":1,"layout":1,"choose":1,"behave":1,"calendar":1,"calendars":1}
,"menus":{"checkbox":1,"display":1,"activate":1,"clicking":1}
,"sets":{"radio":1,"controls":1}
,"radio":{"button":1,"buttons":1}
,"button":{"sets":1,"set":1}
,"controls":{"note":1}
,"note":{"control":1,"closed":1}
,"styles":{"display":1,"save":1,"selection":1}
,"values":{"value":1,"continue":1,"option":1,"field":1,"second":1,"create":1,"properly":1,"set":1}
,"value":{"lists":1,"list":1,"select":1,"checkbox":1,"choose":1,"drop-down":1,"first":1,"second":1,"value":1,"field":1,"entered":1,"all":1,"system":1,"close":1,"pop-up":1,"if":1,"user":1,"pull-down":1}
,"table":{"define":1,"describes":1}
,"define":{"value":1,"field\u2019s":1}
,"list":{"set":1,"value":1,"items":1,"users":1,"format":1,"if":1,"current":1,"option":1,"allow":1,"across":1,"edit":1,"chose":1,"dialog":1,"pop-up":1,"closed":1,"displays":1,"ignore":1,"two":1,"created":1,"setting":1,"portal":1,"defined":1,"display":1,"includes":1,"field":1,"control":1,"defining":1,"select":1}
,"style":{"defining":1,"choose":1,"add":1,"checkbox":1,"fields":1,"behavior":1,"field":1}
,"defining":{"value":1,"changing":1,"automatic":1}
,"layout":{"mode":1,"choose":1,"define":1,"defining":1}
,"mode":{"select":1}
,"select":{"field":1,"show":1,"include":1,"allow":1,"override":1,"auto-complete":1,"value":1,"data":1}
,"inspector":{"data":1,"control":1}
,"tab":{"field":1,"drag":1,"table":1,"select":1,"use":1,"running":1}
,"choose":{"control":1,"display":1,"value":1,"symbol":1,"date":1,"values":1,"options":1,"file":1,"edit":1}
,"edit":{"box":1,"option":1,"value":1}
,"box":{"field":1,"pop-up":1,"dots":1,"encrypted":1,"selected":1,"entered":1,"control":1,"that\u2019s":1,"if":1,"users":1,"drop-down":1}
,"default":{"control":1,"value":1}
,"add":{"scroll":1,"values":1,"change":1,"new":1}
,"scroll":{"bar":1}
,"bar":{"field":1,"drop-down":1}
,"show":{"vertical":1,"hide":1,"values":1}
,"vertical":{"scroll":1}
,"items":{"list":1,"pop-up":1,"checkboxes":1,"radio":1,"alphabetical":1}
,"users":{"use":1,"choose":1,"enter":1,"typing":1,"add":1}
,"use":{"arrow":1,"value":1,"script":1,"get":1}
,"arrow":{"keys":1,"show":1}
,"keys":{"mouse":1}
,"mouse":{"type":1,"choose":1}
,"type":{"choose":1,"concealed":1,"default":1}
,"include":{"arrow":1,"related":1}
,"hide":{"list":1}
,"format":{"field":1,"fields":1}
,"combo":{"box":1}
,"checkboxes":{"users":1,"check":1}
,"symbol":{"displayed":1}
,"displayed":{"checkboxes":1,"drop-down":1,"field":1}
,"check":{"mark":1}
,"mark":{"radio":1}
,"buttons":{"users":1}
,"calendar":{"current":1,"type":1,"pop-up":1}
,"current":{"date":1,"record":1}
,"date":{"users":1,"drop-down":1}
,"concealed":{"dit":1,"edit":1}
,"dit":{"box":1}
,"dots":{"data":1}
,"conceal":{"confidential":1}
,"confidential":{"data":1}
,"encrypted":{"hidden":1}
,"hidden":{"control":1}
,"continue":{"step":1}
,"step":{"all":1,"values":1}
,"all":{"control":1,"values":1}
,"save":{"layout":1}
,"options":{"value":1,"auto-enter":1}
,"if":{"desired":1,"selected":1,"control":1,"value":1,"apply":1,"modify":1,"user":1,"field":1,"press":1,"script":1}
,"desired":{"allow":1}
,"allow":{"user":1,"entry":1,"editing":1,"users":1}
,"user":{"add":1,"required":1,"pass":1,"clicked":1}
,"record":{"select":1,"database":1}
,"option":{"appears":1,"if":1,"edit":1}
,"appears":{"value":1,"field":1}
,"selected":{"drop-down":1,"checkbox":1,"all":1}
,"change":{"values":1,"concealed":1}
,"across":{"records":1}
,"records":{"select":1}
,"editing":{"value":1}
,"chose":{"step":1}
,"field\u2019s":{"control":1}
,"drag":{"field":1}
,"changing":{"fields":1}
,"describes":{"control":1}
,"behave":{"show":1}
,"second":{"field":1}
,"dialog":{"box":1}
,"selection":{"value":1}
,"first":{"field":1,"value":1,"triggers":1,"script":1}
,"stored":{"database":1}
,"database":{"control":1,"fields":1,"dialog":1,"value":1}
,"behavior":{"radio":1}
,"closed":{"value":1,"pop-up":1}
,"displays":{"values":1,"first":1,"pop-up":1}
,"ignore":{"data":1}
,"formatting":{"select":1,"value":1,"field":1,"display":1,"fields":1}
,"override":{"data":1}
,"two":{"fields":1}
,"types":{"format":1}
,"created":{"values":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"isplays":1,"displays":1}
,"isplays":{"value":1}
,"alphabetical":{"order":1}
,"order":{"formatting":1,"value":1}
,"allows":{"users":1}
,"enter":{"value":1,"change":1,"field":1,"select":1}
,"entered":{"field":1,"roman":1}
,"layouts":{"field":1}
,"formatted":{"checkbox":1}
,"columnar":{"report":1}
,"report":{"filemaker":1}
,"larger":{"field":1}
,"text":{"enter":1,"text":1,"attributes":1,"paragraph":1}
,"roman":{"characters":1}
,"characters":{"if":1}
,"apply":{"concealed":1}
,"attributes":{"italics":1,"lost":1,"applied":1,"scripts":1}
,"italics":{"color":1}
,"color":{"paragraph":1}
,"paragraph":{"formats":1}
,"formats":{"tabs":1,"retained":1}
,"tabs":{"carriage":1}
,"carriage":{"returns":1}
,"returns":{"retained":1}
,"retained":{"text":1,"data":1}
,"lost":{"if":1}
,"modify":{"text":1}
,"that\u2019s":{"field":1}
,"applied":{"appears":1}
,"scripts":{"calculations":1}
,"calculations":{"access":1}
,"access":{"data":1,"value":1}
,"required":{"privileges":1}
,"privileges":{"allow":1}
,"typing":{"value":1}
,"system":{"completion":1}
,"completion":{"select":1}
,"auto-complete":{"value":1,"during":1}
,"during":{"data":1}
,"you\u2019re":{"formatting":1}
,"portal":{"value":1}
,"defined":{"include":1}
,"related":{"values":1,"field":1}
,"create":{"self-join":1}
,"self-join":{"relationship":1}
,"relationship":{"order":1}
,"properly":{"xample":1}
,"xample":{"value":1}
,"includes":{"related":1}
,"file":{"enu":1}
,"enu":{"manage":1}
,"manage":{"database":1}
,"auto-enter":{"tab":1}
,"close":{"manage":1}
,"new":{"record":1}
,"automatic":{"data":1}
,"activate":{"onrecordload":1}
,"onrecordload":{"script":1}
,"script":{"trigger":1,"enter":1,"access":1,"parameter":1,"use":1,"triggers":1,"activates":1,"runs":1}
,"trigger":{"onobjectenter":1,"ifferently":1}
,"onobjectenter":{"script":1}
,"ifferently":{"drop-down":1}
,"clicking":{"field":1}
,"triggers":{"activated":1,"objects":1,"first":1}
,"activated":{"select":1,"first":1}
,"press":{"tab":1}
,"pass":{"value":1}
,"parameter":{"script":1}
,"get":{"scriptparameter":1,"field\u0027s":1}
,"scriptparameter":{"function":1}
,"function":{"get":1}
,"field\u0027s":{"value":1}
,"clicked":{"field":1}
,"objects":{"drop-down":1}
,"calendars":{"entering":1}
,"entering":{"field":1}
,"method":{"clicking":1}
,"pressing":{"tab":1}
,"running":{"script":1}
,"activates":{"triggers":1}
,"runs":{"enter":1}
,"pull-down":{"pull":1}
,"pull":{"format":1}
}
;Search.control.loadWordPairs(pairs);
