var pairs =
{
"setting":{"preferences":1}
,"preferences":{"customize":1,"preferences":1,"affect":1,"set":1,"individual":1}
,"customize":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"by":1}
,"by":{"changing":1}
,"changing":{"standard":1}
,"standard":{"settings":1}
,"settings":{"called":1}
,"called":{"preferences":1}
,"affect":{"behavior":1}
,"behavior":{"application":1}
,"application":{"specific":1}
,"specific":{"document":1}
,"document":{"types":1}
,"types":{"preferences":1}
,"set":{"include":1,"preferences":1}
,"include":{"general":1}
,"general":{"layout":1}
,"layout":{"memory":1}
,"memory":{"plug-in":1}
,"plug-in":{"permitted":1}
,"permitted":{"hosts":1}
,"hosts":{"set":1}
,"individual":{"documents":1}
,"documents":{"etting":1}
,"etting":{"file":1}
,"file":{"options":1}
}
;Search.control.loadWordPairs(pairs);
