var pairs =
{
"ormatting":{"setting":1}
,"setting":{"up":1}
,"up":{"field":1}
,"field":{"objects":1,"formats":1,"layout":1,"format":1,"type":1,"validation":1,"names":1,"inserting":1,"formatting":1,"setup":1}
,"objects":{"la":1,"if":1,"field":1}
,"la":{"yout":1}
,"yout":{"mode":1}
,"mode":{"use":1,"choose":1}
,"use":{"filemaker":1,"data":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"field":1,"displays":1,"replaces":1}
,"formats":{"control":1,"change":1,"filemaker":1,"set":1,"file":1,"each":1,"number":1,"layout":1,"numbers":1,"currently":1,"format":1,"field":1}
,"control":{"data":1,"panel":1,"type":1}
,"data":{"appears":1,"stored":1,"meets":1,"based":1,"extraneous":1,"users":1,"fields":1,"filemaker":1,"record":1,"if":1,"formatting":1}
,"appears":{"layout":1}
,"layout":{"formats":1,"layout":1,"if":1,"objects":1,"mode":1,"format":1}
,"change":{"data":1,"automatically":1}
,"stored":{"database":1}
,"database":{"format":1,"created":1,"system":1}
,"format":{"each":1,"place":1,"date":1,"number":1,"numbers":1}
,"each":{"time":1,"field":1}
,"time":{"place":1,"timestamp":1,"symbol":1,"select":1,"field":1}
,"place":{"field":1,"display":1,"5123":1}
,"if":{"enter":1,"don\u2019t":1,"united":1}
,"enter":{"-5123":1,"data":1,"field":1}
,"-5123":{"number":1}
,"number":{"field":1,"date":1,"variable":1}
,"display":{"-$5,123.00":1,"data":1,"sample":1}
,"-$5,123.00":{"place":1}
,"5123":{"field":1}
,"automatically":{"data":1}
,"meets":{"criteria":1}
,"criteria":{"defining":1}
,"defining":{"conditional":1,"field":1}
,"conditional":{"formatting":1}
,"formatting":{"layout":1,"inspector":1,"numbers":1,"field":1}
,"don\u2019t":{"formats":1}
,"displays":{"numbers":1,"current":1}
,"numbers":{"dates":1,"format":1,"formatting":1}
,"dates":{"times":1}
,"times":{"based":1,"affect":1}
,"based":{"system":1,"current":1}
,"system":{"formats":1,"preferences":1}
,"set":{"control":1,"specific":1}
,"panel":{"windows":1}
,"windows":{"system":1}
,"preferences":{"macos":1}
,"macos":{"file":1}
,"file":{"created":1,"help":1}
,"created":{"number":1,"system":1,"australia":1}
,"date":{"time":1,"symbol":1,"page":1}
,"timestamp":{"fields":1}
,"fields":{"display":1,"users":1,"formatted":1}
,"current":{"system":1,"date":1,"time":1}
,"help":{"topics":1}
,"topics":{"formats":1}
,"type":{"set":1,"data":1}
,"specific":{"formats":1}
,"users":{"enter":1}
,"extraneous":{"characters":1}
,"characters":{"pound":1}
,"pound":{"control":1}
,"validation":{"options":1,"display":1}
,"options":{"defining":1}
,"sample":{"data":1}
,"formatted":{"field":1}
,"choose":{"view":1}
,"view":{"menu":1}
,"menu":{"show":1}
,"show":{"sample":1}
,"replaces":{"field":1}
,"names":{"sample":1}
,"record":{"currently":1}
,"currently":{"browsed":1,"computer":1}
,"browsed":{"files":1}
,"files":{"created":1,"system":1}
,"affect":{"appearance":1}
,"appearance":{"data":1}
,"united":{"states":1}
,"states":{"open":1}
,"open":{"database":1}
,"australia":{"database":1}
,"computer":{"files":1}
,"symbol":{"displays":1,"currentdate":1}
,"select":{"symbol":1}
,"currentdate":{"currenttime":1}
,"currenttime":{"layout":1}
,"inspector":{"format":1}
,"inserting":{"date":1}
,"page":{"number":1}
,"variable":{"layout":1}
,"setup":{"number":1}
}
;Search.control.loadWordPairs(pairs);
