var pairs =
{
"open":{"ing":1,"protected":1,"file":1,"encryption":1,"filename":1}
,"ing":{"files":1}
,"files":{"protected":1}
,"protected":{"password":1,"file":1}
,"password":{"attempt":1,"file":1,"blank":1,"leave":1,"don\u2019t":1,"if":1,"entered":1,"default":1}
,"attempt":{"open":1}
,"file":{"enter":1,"file":1,"hosted":1,"doesn\u2019t":1,"etting":1,"options":1,"want":1,"open":1}
,"enter":{"passwords":1,"account":1}
,"passwords":{"supply":1}
,"supply":{"account":1}
,"account":{"name":1,"leave":1,"na":1,"names":1,"stored":1,"credentials":1,"hold":1,"choose":1,"if":1}
,"name":{"order":1,"password":1}
,"order":{"open":1}
,"hosted":{"lock":1}
,"lock":{"icon":1,"icons":1}
,"icon":{"security":1}
,"security":{"level":1,"lock":1}
,"level":{"connection":1}
,"connection":{"host":1}
,"host":{"security":1}
,"icons":{"if":1}
,"if":{"you\u2019re":1,"don\u2019t":1,"open":1,"account":1,"forgot":1}
,"you\u2019re":{"prompted":1}
,"prompted":{"password":1}
,"doesn\u2019t":{"sign":1}
,"sign":{"admin":1}
,"admin":{"account":1,"password":1}
,"leave":{"password":1,"blank":1}
,"blank":{"account":1,"set":1}
,"na":{"admin":1}
,"set":{"default":1}
,"default":{"account":1,"password":1}
,"etting":{"file":1}
,"options":{"asswords":1}
,"asswords":{"case":1}
,"case":{"sensitive":1}
,"sensitive":{"account":1,"if":1}
,"names":{"case":1}
,"don\u2019t":{"account":1,"encryption":1}
,"encryption":{"password":1,"database":1}
,"database":{"dialog":1,"administrator":1}
,"dialog":{"box":1}
,"box":{"database":1,"account":1}
,"administrator":{"if":1}
,"stored":{"by":1}
,"by":{"oauth":1}
,"oauth":{"identity":1}
,"identity":{"provider":1}
,"provider":{"hoose":1,"provider\u2019s":1}
,"hoose":{"oauth":1}
,"provider\u2019s":{"webpage":1}
,"webpage":{"enter":1}
,"credentials":{"if":1}
,"entered":{"automatically":1}
,"automatically":{"open":1}
,"want":{"enter":1}
,"hold":{"shift":1}
,"shift":{"key":1}
,"key":{"windows":1,"macos":1}
,"windows":{"option":1}
,"option":{"key":1}
,"macos":{"file":1}
,"filename":{"dialog":1}
,"choose":{"uest":1}
,"uest":{"account":1}
,"forgot":{"password":1}
}
;Search.control.loadWordPairs(pairs);
