var pairs =
{
"onrecordcommit":{"performs":1}
,"performs":{"script":1,"commit":1}
,"script":{"efore":1,"steps":1,"performs":1,"step":1,"script":1,"return":1,"proceeds":1,"canceled":1,"trigger":1,"triggers":1,"runs":1}
,"efore":{"record":1}
,"record":{"changed":1,"committed":1,"moves":1,"user":1,"accesses":1,"record":1,"modified":1,"if":1,"inside":1,"related":1,"exiting":1,"had":1,"exited":1}
,"changed":{"committed":1,"records":1,"actions":1}
,"committed":{"actions":1,"include":1,"focus":1}
,"actions":{"record":1,"don\u2019t":1,"activate":1}
,"include":{"user":1}
,"user":{"data":1,"record":1,"presses":1,"clicks":1}
,"data":{"record":1}
,"moves":{"record":1}
,"accesses":{"manage":1}
,"manage":{"database":1}
,"database":{"dialog":1}
,"dialog":{"box":1}
,"box":{"user":1}
,"presses":{"enter":1}
,"enter":{"key":1}
,"key":{"user":1}
,"clicks":{"layout":1}
,"layout":{"activated":1}
,"activated":{"record":1}
,"modified":{"script":1}
,"steps":{"move":1}
,"move":{"focus":1}
,"focus":{"record":1,"leaves":1,"activates":1}
,"if":{"previous":1}
,"previous":{"record":1}
,"commit":{"records\u002Frequests":1,"changed":1}
,"records\u002Frequests":{"script":1}
,"step":{"event":1,"ithin":1}
,"event":{"processed":1,"triggered":1}
,"processed":{"browse":1}
,"browse":{"find":1}
,"find":{"modes":1}
,"modes":{"use":1,"trigger":1}
,"use":{"exit":1}
,"exit":{"script":1}
,"ithin":{"triggered":1}
,"triggered":{"script":1}
,"return":{"true":1}
,"true":{"false":1,"event":1}
,"false":{"true":1,"event":1}
,"proceeds":{"false":1}
,"canceled":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"10.0":1}
,"10.0":{"portal":1}
,"portal":{"displays":1,"oes":1}
,"displays":{"records":1}
,"records":{"related":1,"committed":1}
,"related":{"table":1,"script":1}
,"table":{"mo":1}
,"mo":{"ving":1}
,"ving":{"record":1}
,"inside":{"portal":1}
,"oes":{"commit":1}
,"leaves":{"main":1}
,"main":{"record":1}
,"trigger":{"activates":1,"record":1,"script":1,"result":1}
,"activates":{"nly":1,"script":1}
,"nly":{"uncommitted":1}
,"uncommitted":{"record":1}
,"exiting":{"record":1}
,"had":{"keyboard":1}
,"keyboard":{"focus":1}
,"exited":{"changed":1}
,"don\u2019t":{"activate":1}
,"activate":{"script":1}
,"triggers":{"list":1}
,"list":{"actions":1}
,"runs":{"modes":1}
}
;Search.control.loadWordPairs(pairs);
