var pairs =
{
"get":{"screen":1,"screenwidth":1,"monitor":1}
,"screen":{"width":1,"window":1,"function":1,"largest":1,"resolution":1,"size":1}
,"width":{"returns":1,"points":1,"value":1,"get":1}
,"returns":{"width":1,"640":1}
,"points":{"screen":1}
,"window":{"current":1,"spans":1,"if":1,"own":1,"returns":1}
,"current":{"file":1,"database":1}
,"file":{"open":1,"each":1}
,"open":{"get":1,"current":1}
,"screenwidth":{"none":1,"get":1}
,"none":{"number":1}
,"number":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"window":1}
,"spans":{"screen":1}
,"function":{"screen":1}
,"largest":{"percentage":1}
,"percentage":{"window":1}
,"if":{"multiple":1}
,"multiple":{"windows":1}
,"windows":{"open":1}
,"database":{"file":1}
,"each":{"window":1}
,"own":{"screen":1}
,"value":{"returned":1}
,"returned":{"foreground":1}
,"foreground":{"window":1}
,"640":{"screen":1,"480":1}
,"resolution":{"set":1}
,"set":{"640":1}
,"480":{"get":1}
,"size":{"get":1}
,"monitor":{"width":1,"size":1}
}
;Search.control.loadWordPairs(pairs);
