var pairs =
{
"textstyleremove":{"removes":1,"text":1,"plaid":1,"firstname":1,"mytable":1}
,"removes":{"styles":1}
,"styles":{"text":1,"-any":1,"by":1,"function":1,"styles":1,"case":1,"bold":1,"textstyleremove":1,"removed":1}
,"text":{"single":1,"styles":1,"-any":1,"expression":1,"field":1,"filemaker":1,"formatting":1,"contained":1}
,"single":{"action":1}
,"action":{"textstyleremove":1}
,"-any":{"text":1,"named":1}
,"expression":{"text":1}
,"field":{"styles":1,"type":1,"sophie":1}
,"named":{"style":1}
,"style":{"list":1,"names":1,"called":1,"removed":1}
,"list":{"styles":1}
,"filemaker":{"pro":1}
,"pro":{"7.0":1}
,"7.0":{"remove":1}
,"remove":{"multiple":1,"all":1}
,"multiple":{"styles":1}
,"by":{"operator":1}
,"operator":{"style":1}
,"names":{"negative":1}
,"negative":{"values":1}
,"values":{"valid":1}
,"valid":{"plain":1}
,"plain":{"styles":1,"ignored":1}
,"function":{"plain":1}
,"ignored":{"if":1}
,"if":{"intermingled":1,"field":1}
,"intermingled":{"styles":1}
,"case":{"sensitive":1}
,"sensitive":{"contain":1}
,"contain":{"spaces":1}
,"spaces":{"additional":1}
,"additional":{"style":1}
,"called":{"allstyles":1}
,"allstyles":{"easier":1,"all":1,"returns":1}
,"easier":{"remove":1}
,"all":{"styles":1}
,"formatting":{"options":1}
,"options":{"lost":1}
,"lost":{"if":1}
,"type":{"returned":1}
,"returned":{"text":1}
,"bold":{"italic":1,"underline":1,"underlined":1}
,"italic":{"underline":1,"returns":1}
,"underline":{"highlightyellow":1,"returns":1}
,"highlightyellow":{"condense":1,"returns":1,"style":1}
,"condense":{"extend":1}
,"extend":{"strikethrough":1}
,"strikethrough":{"smallcaps":1}
,"smallcaps":{"superscript":1}
,"superscript":{"subscript":1}
,"subscript":{"uppercase":1}
,"uppercase":{"lowercase":1}
,"lowercase":{"titlecase":1}
,"titlecase":{"wordunderline":1}
,"wordunderline":{"doubleunderline":1}
,"doubleunderline":{"allstyles":1}
,"plaid":{"italic":1,"italics":1}
,"returns":{"word":1,"sophie":1,"text":1}
,"word":{"plaid":1}
,"italics":{"style":1}
,"removed":{"textstyleremove":1,"firstname":1}
,"firstname":{"bold":1,"field":1,"allstyles":1}
,"sophie":{"bold":1,"textstyleremove":1,"styles":1}
,"underlined":{"styles":1}
,"mytable":{":mytext":1}
,":mytext":{"highlightyellow":1}
,"contained":{"mytable":1}
}
;Search.control.loadWordPairs(pairs);
