var pairs =
{
"bout":{"ayout":1}
,"ayout":{"types":1}
,"types":{"use":1,"layouts":1,"if":1}
,"use":{"new":1,"layout":1}
,"new":{"layout\u002Freport":1}
,"layout\u002Freport":{"assistant":1}
,"assistant":{"create":1,"further":1,"computer":1,"add":1,"choose":1,"define":1,"if":1,"choosing":1}
,"create":{"types":1,"report":1}
,"layouts":{"choose":1,"designed":1,"enlightened":1,"data":1}
,"choose":{"category":1,"computer":1,"view":1,"touch":1,"orientation":1,"include":1}
,"category":{"corresponds":1}
,"corresponds":{"layout":1}
,"layout":{"viewed":1,"finish":1,"default":1,"theme":1,"various":1,"objects":1,"choose":1,"custom":1,"fields":1,"type":1,"li":1,"except":1,"simple":1,"complex":1,"assistant":1,"sort":1,"form":1,"mode":1,"standard":1,"list":1,"computer":1}
,"viewed":{"computer":1}
,"computer":{"screen":1,"layouts":1,"screens":1,"choose":1,"touch":1}
,"screen":{"touch":1,"printed":1,"form":1}
,"touch":{"device":1,"printer":1}
,"device":{"screen":1,"layouts":1,"dimensions":1,"choose":1,"printer":1}
,"printed":{"additional":1}
,"additional":{"choices":1}
,"choices":{"layout":1,"new":1,"default":1}
,"finish":{"assistant":1,"first":1}
,"further":{"customize":1}
,"customize":{"layout":1,"assistant":1}
,"default":{"layout":1,"theme":1}
,"theme":{"assigned":1,"computer":1,"touch":1,"printer":1,"changing":1,"layout":1}
,"assigned":{"each":1}
,"each":{"layout":1,"region":1}
,"various":{"choices":1}
,"designed":{"display":1,"printing":1}
,"display":{"dimensions":1,"layout":1,"touch-compatible":1}
,"dimensions":{"laptop":1,"customize":1,"large":1,"print":1}
,"laptop":{"desktop":1}
,"desktop":{"computer":1}
,"screens":{"choose":1}
,"view":{"want":1,"layout":1,"blank":1}
,"want":{"display":1,"layout":1,"custom":1}
,"add":{"fields":1,"use":1,"header":1}
,"fields":{"layout":1,"select":1,"text":1,"subtotal":1,"add":1,"want":1}
,"objects":{"embellishments":1}
,"embellishments":{"want":1}
,"enlightened":{"touch":1,"print":1}
,"touch-compatible":{"input":1}
,"input":{"devices":1}
,"devices":{"including":1,"layout\u0027s":1}
,"including":{"pad":1,"subtotals":1}
,"pad":{"ipad":1}
,"ipad":{"mini":1}
,"mini":{"phone":1}
,"phone":{"device":1}
,"orientation":{"ortrait":1}
,"ortrait":{"landscape":1}
,"landscape":{"layout":1}
,"custom":{"devices":1,"label":1}
,"layout\u0027s":{"width":1}
,"width":{"height":1}
,"height":{"finish":1}
,"printer":{"layouts":1,"choices":1,"abels":1}
,"printing":{"data":1}
,"data":{"labels":1,"dd":1,"entry":1,"vertical":1,"add":1,"new":1,"predefined":1,"grouped":1,"by":1,"groups":1,"modify":1}
,"labels":{"horizontal":1,"layout":1,"vertically":1}
,"horizontal":{"vertical":1}
,"vertical":{"envelopes":1,"labels":1,"writing":1}
,"envelopes":{"reports":1}
,"reports":{"printer":1}
,"print":{"labels":1,"horizontally":1,"preview":1,"standard":1}
,"select":{"arranged":1}
,"arranged":{"print":1}
,"horizontally":{"virtually":1}
,"virtually":{"label":1}
,"label":{"stock":1,"types":1,"type":1,"dimensions":1}
,"stock":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"includes":1,"creates":1}
,"includes":{"dimensions":1}
,"large":{"number":1}
,"number":{"standard":1,"current":1}
,"standard":{"label":1,"umber":1,"form":1}
,"if":{"label":1,"finish":1}
,"type":{"want":1,"data":1,"list":1,"filemaker":1}
,"preview":{"data":1}
,"dd":{"layout":1}
,"entry":{"finding":1,"screen":1}
,"finding":{"data":1}
,"li":{"ke":1}
,"ke":{"labels":1}
,"except":{"asian":1}
,"asian":{"full-width":1}
,"full-width":{"characters":1}
,"characters":{"rotated":1}
,"rotated":{"labels":1}
,"vertically":{"se":1}
,"se":{"formatting":1}
,"formatting":{"fields":1}
,"text":{"vertical":1,"company\u0027s":1,"page":1}
,"writing":{"envelope":1}
,"envelope":{"layout":1,"print":1,"report":1}
,"umber":{"10":1}
,"10":{"usiness":1}
,"usiness":{"envelope":1}
,"define":{"varied":1}
,"varied":{"report":1}
,"report":{"formats":1,"layout":1,"data":1,"add":1,"switch":1,"list":1}
,"formats":{"create":1}
,"simple":{"rows":1}
,"rows":{"columns":1}
,"columns":{"data":1}
,"predefined":{"layout":1}
,"list":{"view":1,"report":1}
,"complex":{"report":1,"layouts":1}
,"grouped":{"by":1}
,"by":{"values":1,"sorting":1,"selected":1,"region":1}
,"values":{"including":1}
,"subtotals":{"grand":1}
,"grand":{"totals":1}
,"totals":{"group":1,"report":1}
,"group":{"records":1,"sales":1}
,"records":{"by":1}
,"sorting":{"data":1,"subtotal":1}
,"selected":{"fields":1}
,"subtotal":{"subsummarize":1,"sales":1}
,"subsummarize":{"ata":1,"data":1}
,"ata":{"groups":1}
,"groups":{"group":1}
,"sales":{"data":1,"each":1}
,"region":{"subtotal":1,"create":1,"save":1}
,"include":{"subtotals":1}
,"header":{"footer":1}
,"footer":{"parts":1}
,"parts":{"static":1}
,"static":{"text":1}
,"company\u0027s":{"name":1}
,"name":{"dynamic":1}
,"dynamic":{"text":1}
,"page":{"number":1}
,"current":{"date":1}
,"date":{"graphic":1}
,"graphic":{"company":1}
,"company":{"logo":1}
,"logo":{"group":1}
,"save":{"script":1}
,"script":{"rerun":1}
,"rerun":{"report":1}
,"switch":{"report":1}
,"sort":{"data":1}
,"modify":{"options":1}
,"options":{"finish":1}
,"first":{"panel":1}
,"panel":{"new":1}
,"choosing":{"layout":1}
,"creates":{"blank":1}
,"blank":{"layout":1}
,"form":{"view":1,"letter":1,"layout":1}
,"mode":{"blank":1}
,"letter":{"change":1}
,"change":{"layout":1}
,"changing":{"theme":1}
,"abels":{"ertical":1}
,"ertical":{"la":1}
,"la":{"bels":1}
,"bels":{"envelope":1}
}
;Search.control.loadWordPairs(pairs);
