var pairs =
{
"odbc":{"jdbc":1,"open":1,"client":1,"data":1,"install":1,"client\u002Faccess":1,"import":1,"driver":1}
,"jdbc":{"filemaker":1,"java":1,"including":1,"enabling":1,"guide":1,"sql":1,"query":1,"driver":1}
,"filemaker":{"pro":1,"database":1,"server":1,"odbc":1,"sql":1,"ro":1,"terminology":1}
,"pro":{"advanced":1}
,"advanced":{"use":1,"data":1,"oracle":1,"odbc":1,"includes":1,"client":1,"next":1,"database":1}
,"use":{"filemaker":1,"access":1}
,"data":{"source":1,"applications":1,"sources":1,"oracle":1,"via":1,"batch":1,"source\u002Fshare":1,"odbc":1,"interactively":1,"want":1,"path":1,"sql":1,"data":1,"table":1,"stored":1,"client":1}
,"source":{"sharing":1,"elow":1,"filemaker":1,"interactively":1,"via":1,"network":1,"you\u2019re":1,"client":1,"data":1,"odbc":1,"by":1,"supplied":1}
,"sharing":{"database":1,"instructions":1}
,"database":{"files":1,"connectivity":1,"data":1,"applications":1,"file":1,"odbc":1,"management":1,"sql":1,"delivers":1,"user":1,"administrator":1}
,"files":{"applications":1}
,"applications":{"computer":1,"ilemaker":1,"share":1}
,"computer":{"odbc":1,"network":1}
,"open":{"database":1,"import":1}
,"connectivity":{"jdbc":1,"create":1}
,"java":{"database":1,"archive":1}
,"create":{"charts":1}
,"charts":{"analyze":1}
,"analyze":{"numbers":1}
,"numbers":{"generate":1}
,"generate":{"reports":1}
,"reports":{"filemaker":1}
,"ilemaker":{"pro":1}
,"elow":{"odbc":1,"filemaker":1}
,"client":{"application":1,"drivers":1,"driver":1,"want":1}
,"application":{"interacting":1,"elow":1,"install":1,"allows":1,"application":1,"requesting":1,"jdbc":1,"odbc":1,"deciding":1}
,"interacting":{"data":1}
,"sources":{"computer":1,"referred":1,"ess":1,"odbc":1,"interactively":1,"importing":1,"term":1,"install":1}
,"network":{"import":1,"use":1}
,"import":{"data":1,"file":1,"records":1}
,"oracle":{"data":1,"database":1,"odbc":1}
,"interactively":{"relationships":1,"real":1,"via":1}
,"relationships":{"graph":1}
,"graph":{"layouts":1,"one-time":1}
,"layouts":{"ilemaker":1,"co":1}
,"includes":{"all":1}
,"all":{"software":1}
,"software":{"share":1}
,"share":{"database":1,"filemaker":1}
,"via":{"odbc":1,"relationships":1}
,"including":{"client":1}
,"drivers":{"use":1,"filemaker":1,"odbc":1,"number":1}
,"access":{"database":1,"data":1,"dbms":1,"filemaker":1}
,"file":{"data":1,"sharing":1,"menu":1,"column":1,"row":1,"odbc":1,"sends":1}
,"server":{"sh":1}
,"sh":{"ari":1}
,"ari":{"ng":1}
,"ng":{"filemaker":1}
,"enabling":{"database":1}
,"instructions":{"installing":1}
,"installing":{"filemaker":1}
,"guide":{"details":1,"use":1,"filemaker":1}
,"details":{"supported":1}
,"supported":{"sql":1}
,"sql":{"statements":1,"reference":1,"sources":1,"queries":1,"script":1,"standard":1,"data":1,"query":1}
,"statements":{"xpressions":1,"table":1}
,"xpressions":{"catalog":1}
,"catalog":{"functions":1}
,"functions":{"filemaker":1}
,"reference":{"filemaker":1,"use":1}
,"install":{"configure":1,"odbc":1}
,"configure":{"drivers":1,"oracle":1}
,"you\u2019re":{"accessing":1}
,"accessing":{"access":1}
,"driver":{"third-party":1,"note":1,"dll":1,"jar":1,"ip":1}
,"third-party":{"drivers":1}
,"number":{"vendors":1}
,"vendors":{"configuring":1}
,"configuring":{"odbc":1}
,"note":{"odbc":1}
,"referred":{"external":1}
,"external":{"sql":1,"data":1}
,"ess":{"ccessing":1}
,"ccessing":{"external":1}
,"real":{"time":1}
,"time":{"relationships":1}
,"co":{"nnecting":1}
,"nnecting":{"external":1}
,"importing":{"odbc":1}
,"batch":{"operations":1}
,"operations":{"by":1}
,"by":{"writing":1,"sending":1,"database":1}
,"writing":{"sql":1}
,"queries":{"uerying":1,"filemaker":1}
,"uerying":{"odbc":1}
,"next":{"overview":1}
,"overview":{"filemaker":1}
,"want":{"use":1,"access":1}
,"source\u002Fshare":{"filemaker":1}
,"ro":{"advanced":1}
,"client\u002Faccess":{"odbc":1}
,"one-time":{"static":1}
,"static":{"via":1}
,"menu":{"open":1}
,"records":{"script":1}
,"script":{"step":1}
,"step":{"xecute":1,"ccessing":1}
,"xecute":{"sql":1}
,"term":{"description":1}
,"description":{"database":1}
,"management":{"system":1}
,"system":{"dbms":1}
,"dbms":{"application":1,"data":1,"locate":1}
,"allows":{"users":1}
,"users":{"store":1}
,"store":{"process":1}
,"process":{"retrieve":1}
,"retrieve":{"database":1}
,"standard":{"programming":1}
,"programming":{"language":1}
,"language":{"controls":1}
,"controls":{"interacts":1}
,"interacts":{"dbms":1}
,"locate":{"data":1}
,"path":{"ip":1}
,"ip":{"address":1}
,"address":{"client":1,"domain":1}
,"requesting":{"data":1}
,"query":{"retrieval":1,"access":1}
,"retrieval":{"manipulation":1}
,"manipulation":{"modification":1}
,"modification":{"data":1}
,"sending":{"sql":1}
,"table":{"collection":1,"filemaker":1,"field":1,"record":1}
,"collection":{"data":1}
,"column":{"attribute":1}
,"attribute":{"table":1}
,"field":{"filemaker":1}
,"row":{"set":1}
,"set":{"cells":1}
,"cells":{"table":1}
,"record":{"filemaker":1}
,"dll":{"windows":1}
,"windows":{"shared":1}
,"shared":{"library":1}
,"library":{"macos":1}
,"macos":{"sends":1}
,"sends":{"sql":1}
,"stored":{"database":1}
,"delivers":{"requested":1}
,"requested":{"data":1}
,"jar":{"java":1}
,"archive":{"file":1}
,"domain":{"name":1}
,"name":{"odbc":1,"password":1}
,"user":{"name":1}
,"password":{"odbc":1}
,"supplied":{"by":1}
,"administrator":{"access":1,"determines":1}
,"determines":{"allowed":1}
,"allowed":{"read-write":1}
,"read-write":{"read-only":1}
,"read-only":{"access":1}
,"deciding":{"odbc":1}
}
;Search.control.loadWordPairs(pairs);
