var pairs =
{
"pecify":{"label":1}
,"label":{"contents":1,"place":1,"fields":1,"co":1,"label":1}
,"contents":{"new":1,"place":1,"select":1}
,"new":{"layout\u002Freport":1,"field":1,"line":1}
,"layout\u002Freport":{"assistant":1}
,"assistant":{"panel":1,"place":1}
,"panel":{"new":1}
,"place":{"fields":1,"field":1,"insertion":1,"text":1}
,"fields":{"text":1,"label":1,"double-click":1,"labels":1,"merge":1,"enclosed":1,"use":1}
,"text":{"want":1,"punctuation":1,"inside":1,"vertical":1,"up":1}
,"want":{"print":1,"order":1,"choose":1,"move":1,"text":1,"remove":1}
,"print":{"each":1}
,"each":{"label":1,"field":1}
,"double-click":{"each":1}
,"field":{"want":1,"table":1,"create":1,"new":1,"label":1,"name":1}
,"order":{"want":1}
,"choose":{"field":1,"table":1}
,"table":{"first":1,"list":1,"by":1}
,"first":{"choose":1}
,"list":{"place":1,"tables":1}
,"create":{"new":1}
,"by":{"choosing":1,"double":1}
,"choosing":{"manage":1}
,"manage":{"database":1}
,"database":{"list":1}
,"tables":{"move":1}
,"move":{"field":1,"angle":1,"delete":1,"text":1}
,"line":{"label":1}
,"insertion":{"point":1}
,"point":{"field":1}
,"angle":{"bracket":1,"brackets":1}
,"bracket":{"delimiters":1}
,"delimiters":{"press":1}
,"press":{"enter":1,"backspace":1}
,"enter":{"retur":1,"edit":1}
,"retur":{"place":1}
,"punctuation":{"fields":1,"type":1,"text":1}
,"co":{"ntents":1}
,"ntents":{"want":1}
,"type":{"want":1}
,"remove":{"field":1}
,"select":{"field":1,"brackets":1}
,"name":{"delimiters":1,"if":1,"layout":1,"ou":1}
,"backspace":{"delete":1}
,"delete":{"filemaker":1,"field":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"formats":1}
,"formats":{"fields":1}
,"labels":{"layout":1,"adjustments":1}
,"layout":{"merge":1,"insert":1,"purpose":1}
,"merge":{"fields":1}
,"enclosed":{"by":1}
,"double":{"angle":1}
,"brackets":{"sure":1,"field":1,"part":1}
,"sure":{"select":1}
,"if":{"move":1}
,"insert":{"punctuation":1}
,"inside":{"brackets":1}
,"part":{"field":1}
,"ou":{"can\u2019t":1}
,"can\u2019t":{"enter":1}
,"edit":{"data":1}
,"data":{"merge":1}
,"use":{"layout":1}
,"purpose":{"modify":1}
,"modify":{"alignment":1}
,"alignment":{"text":1}
,"vertical":{"labels":1}
,"adjustments":{"left":1,"right":1}
,"left":{"move":1}
,"up":{"adjustments":1}
,"right":{"move":1}
}
;Search.control.loadWordPairs(pairs);
