var pairs =
{
"xact":{"returns":1}
,"returns":{"true":1,"false":1}
,"true":{"if":1,"exact":1,"value":1,"recipient":1,"country":1}
,"if":{"contents":1,"case":1}
,"contents":{"two":1}
,"two":{"fields":1}
,"fields":{"match":1,"data":1}
,"match":{"returns":1,"uppercase":1,"exact":1}
,"false":{"exact":1}
,"exact":{"originaltext":1,"match":1,"mcdonald":1,"john":1,"upper":1,"billto":1,"recipient":1,"country":1}
,"originaltext":{"comparisontext":1,"-any":1}
,"comparisontext":{"originaltext":1,"-any":1}
,"-any":{"text":1}
,"text":{"expression":1,"field":1,"match":1,"attributes":1}
,"expression":{"text":1}
,"field":{"container":1,"comparisontext":1,"number":1,"spain":1}
,"container":{"field":1,"fields":1}
,"number":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"text":1}
,"uppercase":{"lowercase":1}
,"lowercase":{"usage":1}
,"usage":{"container":1}
,"data":{"stored":1,"checking":1}
,"stored":{"manner":1,"by":1}
,"manner":{"embedded":1}
,"embedded":{"stored":1}
,"by":{"reference":1}
,"reference":{"evaluating":1}
,"evaluating":{"values":1}
,"values":{"text":1}
,"attributes":{"font":1}
,"font":{"styles":1}
,"styles":{"sizes":1}
,"sizes":{"considered":1}
,"considered":{"if":1}
,"case":{"use":1}
,"use":{"lower":1}
,"lower":{"function":1}
,"function":{"upper":1,"parameters":1}
,"upper":{"function":1,"mcdonald":1,"recipient":1}
,"parameters":{"process":1}
,"process":{"data":1}
,"checking":{"exact":1}
,"mcdonald":{"mcdonald":1,"returns":1,"upper":1}
,"john":{"john":1,"returns":1}
,"billto":{"shipto":1,"value":1}
,"shipto":{"returns":1,"exact":1}
,"value":{"billto":1,"shipto":1}
,"recipient":{"upper":1,"returns":1,"johnson":1}
,"johnson":{"exact":1}
,"country":{"spain":1,"field":1}
,"spain":{"returns":1}
}
;Search.control.loadWordPairs(pairs);
