var pairs =
{
"degrees":{"converts":1,"degrees":1,"angleinradians":1,"equation":1,"atan":1,"1.0472":1}
,"converts":{"angleinradians":1}
,"angleinradians":{"degrees":1,"angleinradians":1,"-any":1}
,"-any":{"numeric":1}
,"numeric":{"expression":1}
,"expression":{"field":1,"radians":1}
,"field":{"numeric":1}
,"radians":{"number":1,"degrees":1}
,"number":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"use":1}
,"use":{"function":1}
,"function":{"translate":1}
,"translate":{"trigonometric":1}
,"trigonometric":{"functions":1}
,"functions":{"radians":1}
,"equation":{"degrees":1}
,"atan":{"returns":1}
,"returns":{"45":1,"60.00014030":1}
,"45":{"degrees":1}
,"1.0472":{"returns":1}
}
;Search.control.loadWordPairs(pairs);
