var pairs =
{
"get":{"filen":1,"filename":1,"file":1,"active":1,"database":1}
,"filen":{"ame":1}
,"ame":{"returns":1}
,"returns":{"name":1,"contacts":1}
,"name":{"currently":1,"get":1}
,"currently":{"active":1}
,"active":{"file":1,"database":1}
,"file":{"filename":1,"get":1,"name":1}
,"filename":{"extension":1,"none":1,"function":1,"filename":1,"period":1,"get":1}
,"extension":{"get":1,"parameter":1,"lead":1}
,"none":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"if":1}
,"if":{"current":1,"use":1}
,"current":{"calculation":1,"window":1}
,"calculation":{"stored":1}
,"stored":{"context":1}
,"context":{"function":1,"evaluated":1,"current":1}
,"function":{"evaluated":1,"parameter":1}
,"evaluated":{"based":1}
,"based":{"context":1}
,"window":{"if":1}
,"use":{"get":1}
,"parameter":{"requires":1,"functions":1}
,"requires":{"filename":1}
,"period":{"include":1,"filename":1}
,"include":{"filename":1}
,"functions":{"interpret":1}
,"interpret":{"period":1}
,"lead":{"unexpected":1}
,"unexpected":{"returns":1}
,"contacts":{"contacts":1,"active":1}
,"database":{"filename":1}
}
;Search.control.loadWordPairs(pairs);
