var pairs =
{
"get":{"fi":1,"filesize":1,"file":1}
,"fi":{"lesize":1}
,"lesize":{"returns":1}
,"returns":{"size":1,"15000":1}
,"size":{"bytes":1,"15000":1,"function":1}
,"bytes":{"currently":1,"get":1}
,"currently":{"active":1}
,"active":{"file":1}
,"file":{"get":1,"size":1}
,"filesize":{"none":1,"get":1}
,"none":{"number":1}
,"number":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"if":1}
,"if":{"current":1}
,"current":{"calculation":1,"window":1,"file":1}
,"calculation":{"stored":1}
,"stored":{"context":1}
,"context":{"function":1,"evaluated":1,"current":1}
,"function":{"evaluated":1,"file":1,"return":1}
,"evaluated":{"based":1}
,"based":{"context":1}
,"window":{"returns":1}
,"15000":{"current":1,"bytes":1}
,"return":{"file":1}
}
;Search.control.loadWordPairs(pairs);
