var pairs =
{
"isvalid":{"returns":1,"field":1,"check":1,"datefield":1,"table":1}
,"returns":{"false":1,"true":1,"data":1,"if":1}
,"false":{"if":1}
,"if":{"data":1,"field":1,"non-date":1,"text":1,"related":1}
,"data":{"invalid":1,"valid":1,"correctly":1,"entry":1,"datefield":1}
,"invalid":{"returns":1,"value":1}
,"true":{"isvalid":1}
,"field":{"field":1,"-any":1,"name":1,"invalid":1,"type":1,"filemaker":1,"defined":1,"deleted":1,"source":1,"validation":1,"isvalid":1}
,"-any":{"field":1}
,"name":{"number":1}
,"number":{"filemaker":1,"field":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1,"advanced":1}
,"6.0":{"earlier":1}
,"earlier":{"returns":1}
,"value":{"field":1}
,"type":{"mismatch":1}
,"mismatch":{"text":1}
,"text":{"date":1,"imported":1,"number":1}
,"date":{"field":1}
,"advanced":{"locate":1}
,"locate":{"temporarily":1}
,"temporarily":{"permanently":1}
,"permanently":{"related":1}
,"related":{"table":1}
,"table":{"referenced":1,"therefore":1,"invalid":1,":field":1,"renamed":1}
,"referenced":{"field":1}
,"defined":{"field":1,"manage":1}
,"deleted":{"related":1}
,"therefore":{"references":1}
,"references":{"field":1}
,"source":{"table":1}
,"valid":{"isvalid":1}
,"check":{"field":1}
,"validation":{"options":1,"isvalid":1}
,"options":{"defined":1,"sure":1}
,"manage":{"database":1}
,"database":{"dialog":1}
,"dialog":{"box":1}
,"box":{"define":1}
,"define":{"field":1}
,"sure":{"data":1}
,"correctly":{"entered":1}
,"entered":{"fields":1}
,"fields":{"during":1}
,"during":{"data":1}
,"entry":{"import":1}
,"import":{"defining":1}
,"defining":{"field":1}
,"datefield":{"returns":1,"if":1}
,"non-date":{"data":1}
,"imported":{"isvalid":1}
,":field":{"returns":1}
,"renamed":{"relationship":1}
,"relationship":{"isn\u2019t":1}
,"isn\u2019t":{"updated":1}
,"updated":{"new":1}
,"new":{"filename":1}
}
;Search.control.loadWordPairs(pairs);
