var pairs =
{
"amaged":{"layouts":1}
,"layouts":{"if":1,"select":1,"advanced":1}
,"if":{"filemaker":1,"deleting":1,"corrupted":1,"problem":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"atabase":1,"close":1,"recovery":1,"switches":1,"file":1,"ru":1,"ile":1}
,"atabase":{"file":1}
,"file":{"stops":1,"displaying":1,"file":1,"corrupted":1,"menu":1,"advanced":1,"blocks":1,"recovery":1,"badfile":1,"define":1,"rebuilding":1}
,"stops":{"responding":1}
,"responding":{"closes":1}
,"closes":{"unexpectedly":1}
,"unexpectedly":{"hen":1,"unresponsive":1}
,"hen":{"switch":1,"display":1}
,"switch":{"layout":1}
,"layout":{"layout":1,"contain":1,"deletes":1,"if":1,"displays":1,"choose":1,"delete":1,"combination":1,"open":1,"perform":1,"follow":1,"recovering":1,"file":1}
,"contain":{"damaged":1}
,"damaged":{"corrupted":1}
,"corrupted":{"object":1,"layout":1}
,"object":{"if":1,"difficult":1,"object":1,"hard":1,"open":1}
,"deleting":{"corrupted":1}
,"difficult":{"corruption":1}
,"corruption":{"visible":1,"filemaker":1}
,"visible":{"corruption":1}
,"close":{"unexpectedly":1}
,"unresponsive":{"hen":1}
,"display":{"object":1}
,"hard":{"isolate":1}
,"isolate":{"delete":1}
,"delete":{"instances":1,"entire":1,"if":1}
,"instances":{"simplest":1}
,"simplest":{"solution":1}
,"solution":{"delete":1}
,"entire":{"layout":1}
,"deletes":{"corrupted":1}
,"open":{"file":1,"script":1,"create":1}
,"displaying":{"corrupted":1}
,"displays":{"open":1}
,"choose":{"file":1}
,"menu":{"manage":1}
,"manage":{"layouts":1}
,"select":{"corrupted":1,"copy":1}
,"problem":{"persists":1}
,"persists":{"recover":1}
,"recover":{"file":1}
,"recovery":{"options":1,"features":1}
,"options":{"dialog":1,"creates":1,"note":1,"deleting":1}
,"dialog":{"box":1}
,"box":{"select":1,"details":1}
,"copy":{"file":1,"old":1}
,"blocks":{"as-is":1}
,"as-is":{"bypass":1}
,"bypass":{"startup":1}
,"startup":{"script":1}
,"script":{"layout":1,"option":1,"step":1,"[specified":1,"scriptname":1,"badfile":1}
,"combination":{"options":1}
,"creates":{"new":1}
,"new":{"database":1,"blank":1}
,"database":{"copy":1}
,"old":{"filemaker":1}
,"switches":{"new":1,"layout":1}
,"blank":{"layout":1}
,"option":{"disabled":1}
,"disabled":{"set":1}
,"set":{"tin":1}
,"tin":{"advanced":1}
,"note":{"ilemaker":1}
,"ilemaker":{"pro":1}
,"ru":{"ntime":1}
,"ntime":{"applications":1}
,"applications":{"support":1}
,"support":{"advanced":1}
,"features":{"open":1}
,"create":{"filemaker":1,"script":1}
,"ile":{"create":1}
,"step":{"perform":1}
,"perform":{"script":1}
,"[specified":{"list":1}
,"list":{"scriptname":1}
,"scriptname":{"file":1,"badfile":1}
,"badfile":{"parameter":1,"switches":1,"layout":1}
,"parameter":{"adfile":1}
,"adfile":{"name":1}
,"name":{"unopenable":1}
,"unopenable":{"file":1}
,"define":{"step":1}
,"follow":{"steps":1}
,"steps":{"deleting":1}
,"recovering":{"file":1}
,"rebuilding":{"file\u2019s":1}
,"file\u2019s":{"structure":1}
,"structure":{"by":1}
,"by":{"selecting":1}
,"selecting":{"scan":1}
,"scan":{"rebuild":1}
,"rebuild":{"scripts":1}
,"scripts":{"layouts":1}
,"details":{"set":1}
}
;Search.control.loadWordPairs(pairs);
