var pairs =
{
"stdevp":{"eturns":1,"field":1,"function":1,"table":1,"field4":1,"field2":1,"field1":1}
,"eturns":{"standard":1}
,"standard":{"deviation":1}
,"deviation":{"population":1,"single":1}
,"population":{"represented":1,"first":1,"second":1,"standard":1}
,"represented":{"by":1}
,"by":{"series":1,"table":1}
,"series":{"non-blank":1}
,"non-blank":{"values":1}
,"values":{"field":1,"field2":1,"field3":1,"field4":1}
,"field":{"stdevp":1,"field":1,"-any":1,"repeating":1,"set":1,"repeatingfield":1,"matching":1,"number":1,"scores":1}
,"-any":{"related":1}
,"related":{"field":1,"records":1,"values":1}
,"repeating":{"field":1,"fields":1}
,"set":{"non-repeating":1}
,"non-repeating":{"fields":1,"field":1}
,"fields":{"expression":1,"parameters":1,"record":1,"first":1,"tables":1,"standard":1,"portal":1}
,"expression":{"returns":1}
,"returns":{"field":1,"standard":1,"1.11803398":1,"2.16024689":1}
,"parameters":{"braces":1}
,"braces":{"optional":1}
,"optional":{"number":1}
,"number":{"filemaker":1,"repeats":1,"defined":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"field":1}
,"repeatingfield":{"field":1}
,"matching":{"related":1,"record":1}
,"records":{"by":1,"portal":1}
,"table":{":field":1,":field1":1,":field2":1,":scores":1}
,":field":{"records":1,"table":1,"equation":1}
,"portal":{"non-repeating":1,"displays":1}
,"record":{"field1":1,"repeatingfield1":1,"by":1}
,"field1":{"field2":1,"two":1}
,"field2":{"field3":1,"repetitions":1,"returns":1}
,"field3":{"repetitions":1,"returns":1}
,"repetitions":{"repeating":1,"values":1}
,"repeatingfield1":{"repeatingfield2":1}
,"repeatingfield2":{"repeatingfield3":1}
,"repeatingfield3":{"if":1}
,"if":{"result":1}
,"result":{"returned":1}
,"returned":{"repeating":1}
,"repeats":{"fields":1}
,"first":{"matching":1,"repetition":1}
,":field1":{"table":1}
,":field2":{"include":1}
,"include":{"fields":1}
,"tables":{"table":1}
,"equation":{"referenced":1}
,"referenced":{"field":1}
,"function":{"returns":1}
,"repetition":{"fields":1,"value":1}
,"second":{"repetition":1}
,"displays":{"related":1}
,"scores":{"stdevp":1}
,":scores":{"returns":1}
,"1.11803398":{"examples":1,"non-repeating":1}
,"examples":{"field1":1}
,"two":{"repetitions":1}
,"field4":{"repetition":1,"error":1}
,"value":{"stdevp":1}
,"error":{"population":1}
,"single":{"number":1}
,"defined":{"stdevp":1}
,"2.16024689":{"2.49443825":1}
,"2.49443825":{"1.5":1}
,"1.5":{"repeating":1}
}
;Search.control.loadWordPairs(pairs);
