var pairs =
{
"fining":{"changing":1}
,"changing":{"button":1,"popover":1}
,"button":{"bar":1,"popover":1,"add":1,"button":1,"vertical":1,"choose":1,"left":1,"move":1,"define":1,"icon":1,"icons":1,"type":1,"if":1,"continue":1}
,"bar":{"define":1,"display":1,"perform":1,"status":1,"tool":1,"filemaker":1,"segments":1,"setup":1,"definition":1,"layout":1,"horizontal":1,"by":1,"remove":1,"hold":1,"drag":1,"new":1,"rearrange":1,"move":1}
,"define":{"button":1,"new":1,"segments":1,"calculation":1,"each":1,"change":1}
,"display":{"multiple":1,"state":1}
,"multiple":{"buttons":1}
,"buttons":{"popover":1,"horizontally":1,"assign":1,"change":1,"button":1,"use":1,"defining":1}
,"popover":{"buttons":1,"button":1,"assign":1,"changing":1,"settings":1}
,"horizontally":{"vertically":1}
,"vertically":{"each":1}
,"each":{"button":1,"segment":1}
,"add":{"text":1,"segment":1}
,"text":{"label":1,"icon":1,"center":1,"type":1,"box":1,"button":1}
,"label":{"icon":1,"text":1,"labels":1,"add":1}
,"icon":{"text":1,"buttons":1,"image":1,"choices":1,"drag":1,"choose":1,"list":1,"icon":1,"removed":1,"change":1,"type":1}
,"assign":{"single":1,"script":1}
,"single":{"command":1,"filemaker":1}
,"command":{"script":1,"create":1}
,"script":{"perform":1,"opposed":1,"first":1,"triggers":1}
,"perform":{"if":1,"script":1}
,"if":{"button":1,"chose":1}
,"opposed":{"single":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1,"svg":1}
,"advanced":{"command":1,"creates":1}
,"create":{"script":1,"calculation":1,"label":1}
,"first":{"creating":1}
,"creating":{"editing":1}
,"editing":{"scripts":1}
,"scripts":{"layout":1}
,"layout":{"mode":1,"pop-up":1,"button":1,"displays":1,"enter":1}
,"mode":{"layout":1,"select":1}
,"pop-up":{"menu":1}
,"menu":{"choose":1}
,"choose":{"layout":1,"orientation":1,"want":1,"segment":1,"none":1,"enter":1,"filename":1,"button":1,"action":1,"direction":1}
,"new":{"button":1,"position":1,"location":1}
,"status":{"toolbar":1}
,"toolbar":{"button":1}
,"tool":{"button":1,"drag":1}
,"drag":{"crosshair":1,"slider":1,"segment":1,"button":1}
,"crosshair":{"draw":1}
,"draw":{"button":1}
,"creates":{"button":1,"label":1}
,"segments":{"layout":1,"buttons":1,"button":1}
,"displays":{"button":1}
,"setup":{"dialog":1}
,"dialog":{"box":1}
,"box":{"define":1,"choose":1,"calculation":1,"icon":1}
,"change":{"button":1,"size":1,"text":1,"cursor":1}
,"definition":{"double-click":1}
,"double-click":{"button":1}
,"orientation":{"button":1}
,"horizontal":{"orientation":1}
,"vertical":{"orientation":1}
,"want":{"labels":1,"design":1}
,"labels":{"all":1,"text":1}
,"all":{"buttons":1}
,"by":{"default":1}
,"default":{"filemaker":1,"active":1}
,"center":{"aligned":1}
,"aligned":{"active":1}
,"active":{"segment":1,"display":1}
,"segment":{"choose":1,"by":1,"naming":1,"want":1,"button":1,"select":1,"layout":1,"moment":1,"new":1}
,"state":{"browse":1}
,"browse":{"find":1}
,"find":{"modes":1}
,"modes":{"active":1}
,"none":{"create":1}
,"calculation":{"active":1,"text":1,"calculation":1,"dialog":1}
,"enter":{"formula":1,"size":1}
,"formula":{"returns":1}
,"returns":{"object":1}
,"object":{"name":1}
,"name":{"segment":1}
,"naming":{"objects":1}
,"objects":{"formulas":1}
,"formulas":{"functions":1}
,"functions":{"right":1}
,"right":{"arrow":1}
,"arrow":{"button":1}
,"left":{"arrow":1}
,"move":{"segment":1,"button":1}
,"design":{"create":1}
,"type":{"label":1,"segment":1}
,"image":{"button":1}
,"choices":{"change":1,"file":1,"use":1}
,"size":{"icon":1,"layout":1,"points":1}
,"slider":{"icon\u0027s":1}
,"icon\u0027s":{"size":1}
,"points":{"use":1}
,"use":{"custom":1,"removed":1,"complete":1}
,"custom":{"icon":1}
,"filename":{"png":1}
,"png":{"svg":1}
,"svg":{"format":1,"support":1,"grammar":1}
,"format":{"open":1}
,"open":{"windows":1}
,"windows":{"insert":1}
,"insert":{"macos":1}
,"macos":{"svg":1}
,"support":{"filemaker":1}
,"grammar":{"button":1}
,"icons":{"remove":1}
,"remove":{"custom":1,"segment":1}
,"list":{"choices":1,"buttons":1}
,"file":{"select":1}
,"select":{"icon":1,"segment":1,"button":1}
,"removed":{"list":1,"icon":1}
,"complete":{"label":1}
,"chose":{"button":1}
,"action":{"change":1}
,"cursor":{"appearance":1}
,"appearance":{"steps":1}
,"steps":{"defining":1,"define":1}
,"defining":{"changing":1}
,"continue":{"step":1}
,"step":{"popover":1,"repeat":1}
,"direction":{"popover":1}
,"triggers":{"popover":1}
,"settings":{"continue":1}
,"repeat":{"steps":1}
,"hold":{"segment":1}
,"moment":{"drag":1}
,"position":{"layout":1}
,"location":{"additional":1}
,"additional":{"notes":1}
,"notes":{"specific":1}
,"specific":{"buttons":1}
,"rearrange":{"segments":1}
}
;Search.control.loadWordPairs(pairs);
