var pairs =
{
"get":{"windowzo":1,"windowzoomlevel":1,"window":1}
,"windowzo":{"omlevel":1}
,"omlevel":{"returns":1}
,"returns":{"zoom":1,"100":1,"200":1,"200*in":1}
,"zoom":{"percentage":1,"level":1}
,"percentage":{"current":1,"enlarge":1,"set":1}
,"current":{"window":1,"window\u2019s":1}
,"window":{"get":1,"contents":1,"zoom":1}
,"windowzoomlevel":{"none":1,"get":1}
,"none":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"8.0":1}
,"8.0":{"windows":1}
,"windows":{"asterisk":1,"current":1}
,"asterisk":{"appears":1}
,"appears":{"next":1}
,"next":{"zoom":1}
,"enlarge":{"window":1}
,"contents":{"improve":1}
,"improve":{"readability":1}
,"readability":{"selected":1}
,"selected":{"general":1,"get":1}
,"general":{"tab":1}
,"tab":{"preferences":1}
,"preferences":{"dialog":1}
,"dialog":{"box":1}
,"box":{"filemaker":1}
,"webdirect":{"function":1}
,"function":{"supported":1}
,"supported":{"returns":1}
,"100":{"returns":1}
,"200":{"current":1,"returns":1,"enlarge":1}
,"window\u2019s":{"zoom":1}
,"set":{"200":1}
,"200*in":{"windows":1}
}
;Search.control.loadWordPairs(pairs);
