var pairs =
{
"bout":{"formulas":1}
,"formulas":{"formulas":1,"perform":1,"define":1,"filemaker":1}
,"perform":{"specific":1}
,"specific":{"operations":1,"calculations":1,"values":1}
,"operations":{"values":1}
,"values":{"database":1,"field":1,"don\u2019t":1,"functions":1,"each":1}
,"database":{"file":1}
,"file":{"return":1}
,"return":{"single":1}
,"single":{"result":1,"specific":1}
,"result":{"formulas":1,"replace":1}
,"define":{"calculation":1,"function":1}
,"calculation":{"field":1,"fields":1,"evaluates":1,"syntax":1}
,"field":{"defining":1,"validation":1,"by":1,"contents":1,"calculations":1,"insert":1,"references":1,"referenced":1,"related":1,"multiplied":1}
,"defining":{"calculation":1,"automatic":1,"field":1,"function":1}
,"fields":{"calculated":1}
,"calculated":{"value":1,"result":1}
,"value":{"automatic":1,"replace":1,"subtotal":1}
,"automatic":{"entry":1,"data":1}
,"entry":{"field":1,"calculation":1}
,"data":{"entry":1,"validation":1}
,"evaluates":{"true":1}
,"true":{"false":1}
,"false":{"data":1}
,"validation":{"defining":1,"calculated":1}
,"replace":{"values":1,"field":1}
,"by":{"replace":1,"space":1,".08":1}
,"contents":{"command":1,"field":1,"automating":1}
,"command":{"records":1}
,"records":{"menu":1}
,"menu":{"script":1}
,"script":{"step":1,"steps":1}
,"step":{"replacing":1}
,"replacing":{"contents":1}
,"calculations":{"filemaker":1,"return":1}
,"filemaker":{"script":1,"pro":1}
,"steps":{"script":1,"if":1}
,"if":{"exit":1,"set":1,"formula":1}
,"exit":{"loop":1}
,"loop":{"if":1}
,"set":{"field":1}
,"insert":{"calculated":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
,"scripts":{"ormulas":1}
,"ormulas":{"contain":1}
,"contain":{"constants":1}
,"constants":{"-numbers":1}
,"-numbers":{"text":1}
,"text":{"date":1}
,"date":{"time":1}
,"time":{"values":1}
,"don\u2019t":{"change":1}
,"change":{"operators":1}
,"operators":{"-symbols":1}
,"-symbols":{"combine":1}
,"combine":{"compare":1}
,"compare":{"two":1}
,"two":{"values":1}
,"functions":{"-predefined":1}
,"-predefined":{"named":1}
,"named":{"formulas":1}
,"each":{"repetition":1,"separate":1}
,"repetition":{"field":1}
,"references":{"-fields":1}
,"-fields":{"table":1}
,"table":{"related":1}
,"related":{"table":1,"field":1,"tables":1}
,"referenced":{"calculation":1}
,"syntax":{"tablename":1}
,"tablename":{":related":1}
,":related":{"field":1}
,"tables":{"if":1}
,"formula":{"can\u2019t":1,"evaluationerror":1}
,"can\u2019t":{"evaluated":1}
,"evaluated":{"returns":1}
,"returns":{"get":1,"value":1,"first":1}
,"get":{"error":1}
,"error":{"code":1}
,"code":{"problem":1}
,"problem":{"enclose":1}
,"enclose":{"formula":1}
,"evaluationerror":{"function":1}
,"function":{"formulas":1,"design":1,"use":1,"define":1,"creating":1,"designing":1,"function":1,"defining":1,"examples":1}
,"pro":{"advanced":1}
,"advanced":{"examples":1}
,"examples":{"eturns":1}
,"eturns":{"first":1}
,"first":{"last":1}
,"last":{"name":1}
,"name":{"separated":1,"each":1}
,"separated":{"by":1}
,"space":{"firstname":1}
,"firstname":{"&\u0022":1}
,"&\u0022":{"&lastname":1}
,"&lastname":{"michelle":1}
,"michelle":{"cannon":1}
,"cannon":{"returns":1}
,"subtotal":{"field":1,"*.0":1}
,"multiplied":{"by":1}
,".08":{"subtotal":1}
,"*.0":{"returns":1}
,"separate":{"line":1}
,"line":{"field1":1}
,"field1":{"&\u00B6":1}
,"&\u00B6":{"&field2":1}
,"&field2":{"fred":1}
,"fred":{"jane":1}
,"jane":{"create":1}
,"create":{"function":1}
,"design":{"function":1}
,"use":{"function":1}
,"creating":{"function":1}
,"designing":{"function":1}
}
;Search.control.loadWordPairs(pairs);
