var pairs =
{
"japanese":{"functions":1,"convert":1,"kana":1,"full":1,"text":1,"numtojtext":1,"year":1}
,"functions":{"japanese":1,"return":1}
,"return":{"date":1}
,"date":{"parts":1,"number":1,"furigana":1,"japanese":1,"format":1}
,"parts":{"japanese":1}
,"convert":{"date":1}
,"number":{"text":1}
,"text":{"values":1,"hiragana":1,"romanhankaku":1}
,"values":{"data":1}
,"data":{"types":1}
,"types":{"japanese":1}
,"kana":{"systems":1}
,"systems":{"function":1}
,"function":{"daynamej":1}
,"daynamej":{"returns":1}
,"returns":{"te":1,"th":1}
,"te":{"xt":1}
,"xt":{"japanese":1}
,"full":{"name":1}
,"name":{"weekday":1,"month":1,"date":1}
,"weekday":{"date":1}
,"furigana":{"converts":1}
,"converts":{"japanese":1,"katakana":1,"ze":1,"ha":1,"ar":1,"hi":1}
,"hiragana":{"katakana":1,"converts":1,"kanahankaku":1}
,"katakana":{"roman":1,"hankaku":1,"converts":1}
,"roman":{"text":1}
,"hankaku":{"zenkaku":1}
,"zenkaku":{"text":1}
,"kanahankaku":{"converts":1}
,"ze":{"nkaku":1}
,"nkaku":{"ka":1,"alphanumeric":1}
,"ka":{"takana":1,"nji":1}
,"takana":{"ha":1,"kanazenkaku":1,"ze":1,"kanjinumeral":1,"monthnamej":1}
,"ha":{"nkaku":1}
,"kanazenkaku":{"converts":1}
,"kanjinumeral":{"converts":1}
,"ar":{"abic":1}
,"abic":{"numerals":1}
,"numerals":{"ka":1,"katakana":1,"japanese":1}
,"nji":{"numerals":1}
,"hi":{"ragana":1}
,"ragana":{"ze":1}
,"monthnamej":{"returns":1}
,"th":{"name":1,"japanese":1}
,"month":{"date":1}
,"numtojtext":{"converts":1}
,"romanhankaku":{"converts":1}
,"alphanumeric":{"symbols":1}
,"symbols":{"ha":1,"romanzenkaku":1,"ze":1,"yearname":1}
,"romanzenkaku":{"converts":1}
,"yearname":{"returns":1}
,"year":{"name":1}
}
;Search.control.loadWordPairs(pairs);
