var pairs =
{
"go":{"next":1}
,"next":{"field":1}
,"field":{"oves":1,"tab":1,"selected":1,"formatted":1,"object":1,"next":1,"current":1,"end":1}
,"oves":{"next":1}
,"tab":{"order":1}
,"order":{"current":1,"status":1,"data":1}
,"current":{"layout":1,"record":1}
,"layout":{"none":1,"if":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"if":1}
,"if":{"field":1,"[isempty":1,"setting":1}
,"selected":{"script":1,"button":1,"field":1}
,"script":{"step":1}
,"step":{"performed":1,"moves":1}
,"performed":{"script":1}
,"moves":{"first":1,"selected":1}
,"first":{"field":1}
,"formatted":{"button":1}
,"button":{"field":1,"object":1}
,"object":{"selected":1,"note":1}
,"note":{"filemaker":1}
,"webdirect":{"cursor":1}
,"cursor":{"moves":1}
,"status":{"field":1,"empty":1}
,"record":{"empty":1}
,"empty":{"if":1,"\u0022]":1}
,"[isempty":{"invoices":1}
,"invoices":{":status":1}
,":status":{")]":1}
,")]":{"show":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"dialog":{"[\u0022":1}
,"[\u0022":{"invoice":1}
,"invoice":{"status":1}
,"\u0022]":{"else":1}
,"else":{"go":1}
,"end":{"if":1}
,"setting":{"tab":1}
,"data":{"entry":1}
,"entry":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
