var pairs =
{
"install":{"plug-in":1,"update":1,"plug-ins":1,"64-bit":1,"setup":1,"version":1}
,"plug-in":{"file":1,"want":1,"current":1,"container":1,"se":1,"files":1,"function":1,"plug-in":1,"required":1,"preferences":1,"update":1,"disabled":1,"etting":1,"updates":1,"show":1,"\u0022]":1,"if":1}
,"file":{"nstalls":1,"container":1,"installing":1,"located":1,"get":1,"script":1,"during":1,"[plugins":1}
,"nstalls":{"updates":1,"update":1}
,"updates":{"plug-in":1,"installing":1}
,"container":{"field":1}
,"field":{"computer":1,"pecif":1,"plug-in":1,"filemaker":1,"active":1,"install":1,"action":1}
,"computer":{"target":1}
,"target":{"field":1,"active":1}
,"pecif":{"ies":1}
,"ies":{"container":1}
,"want":{"install":1}
,"update":{"if":1,"plug-in":1,"enable":1}
,"if":{"field":1,"non-plug-in":1,"install":1,"[get":1,"detects":1,"get":1,"installing":1}
,"filemaker":{"pro":1,"plug-in":1,"server":1,"cloud":1,"ro":1}
,"pro":{"advanced":1,"12.0":1,"etwork":1}
,"advanced":{"installs":1,".fmx64":1,"macos":1,"recognize":1,"nstalls":1,"install":1,"application\u2019s":1,"filemaker":1}
,"installs":{"plug-in":1,"video":1,"version":1}
,"current":{"container":1,"application\u0027s":1}
,"active":{"table":1,"container":1}
,"table":{"filemaker":1}
,"12.0":{"insert":1}
,"insert":{"plug-in":1,"file":1}
,"se":{"insert":1}
,"installing":{"plug-ins":1,"filemaker":1}
,"plug-ins":{"nly":1,"extension":1,"enabled":1,"match":1,"use":1,"prevent":1,"automating":1}
,"nly":{"filemaker":1}
,"files":{"installed":1,"zip":1,"tar":1}
,"installed":{"if":1,"use":1,"plug-in":1}
,"non-plug-in":{"file":1}
,"located":{"target":1}
,"action":{"takes":1}
,"takes":{"place":1}
,"place":{"script":1}
,"script":{"runs":1,"step":1}
,"runs":{"windows":1}
,"windows":{"plug-ins":1}
,"extension":{".fmx":1,"fmplugin":1}
,".fmx":{"32-bit":1}
,"32-bit":{"filemaker":1}
,".fmx64":{"64-bit":1}
,"64-bit":{"filemaker":1,"version":1,"plug-ins":1}
,"macos":{"plug-ins":1}
,"fmplugin":{"compressed":1}
,"compressed":{"plug-in":1}
,"zip":{"ormat":1}
,"ormat":{"plug-in":1,"can\u2019t":1}
,"tar":{"ormat":1}
,"can\u2019t":{"installed":1}
,"use":{"get":1,"personalization":1}
,"get":{"installedfmplugins":1,"applicationarchitecture":1}
,"installedfmplugins":{"function":1,"plug-ins":1}
,"function":{"identify":1,"help":1,"determine":1}
,"identify":{"name":1}
,"name":{"version":1}
,"version":{"enabled":1,"filemaker":1,"video":1,"plug-in":1}
,"enabled":{"state":1,"plug-in":1}
,"state":{"installed":1}
,"help":{"determine":1,"filemaker":1}
,"determine":{"installed":1,"current":1}
,"required":{"by":1}
,"by":{"solution":1,"filemaker":1}
,"solution":{"file":1}
,"preferences":{"filemaker":1,"iles":1}
,"recognize":{"if":1}
,"step":{"installs":1,"dmin":1,"supported":1}
,"disabled":{"plug-in":1}
,"enable":{"plug-in":1}
,"etting":{"plug-in":1}
,"iles":{"hosted":1}
,"hosted":{"by":1}
,"server":{"filemaker":1,"administrator":1,"help":1}
,"cloud":{"server":1,"help":1,"host":1}
,"administrator":{"nable":1,"use":1}
,"nable":{"install":1}
,"dmin":{"console":1}
,"console":{"filemaker":1}
,"ro":{"advanced":1}
,"match":{"filemaker":1}
,"application\u2019s":{"architecture":1}
,"architecture":{"64-bit":1,"system":1,"installs":1}
,"applicationarchitecture":{"function":1,"=\u0022":1}
,"application\u0027s":{"architecture":1}
,"system":{"administrator":1}
,"personalization":{"file":1}
,"during":{"installation":1}
,"installation":{"multiple":1}
,"multiple":{"computers":1}
,"computers":{"disable":1}
,"disable":{"plug-ins":1}
,"prevent":{"plug-in":1}
,"etwork":{"install":1}
,"setup":{"guide":1}
,"guide":{"script":1}
,"supported":{"server-side":1}
,"server-side":{"scripts":1}
,"scripts":{"performed":1}
,"performed":{"by":1}
,"host":{"installs":1}
,"video":{"plug-in":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"dialog":{"[\u0022":1}
,"[\u0022":{"want":1}
,"\u0022]":{"if":1,"install":1}
,"[get":{"lastmessagechoice":1,"applicationarchitecture":1}
,"lastmessagechoice":{"=1]":1}
,"=1]":{"install":1}
,"[plugins":{":video]":1,":32bit]":1,":64bit]":1}
,":video]":{"end":1}
,"end":{"if":1}
,"detects":{"application":1}
,"application":{"architecture":1}
,"=\u0022":{"i386":1,"x86_64":1}
,"i386":{"\u0022]":1}
,":32bit]":{"else":1}
,"else":{"if":1}
,"x86_64":{"\u0022]":1}
,":64bit]":{"end":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
