var pairs =
{
"manage":{"database":1}
,"database":{"keyboard":1,"dialog":1}
,"keyboard":{"shortcuts":1,"hortcuts":1}
,"shortcuts":{"windows":1,"manage":1,"relationship":1,"relationships":1}
,"windows":{"use":1}
,"use":{"keyboard":1,"se":1}
,"dialog":{"box":1}
,"box":{"use":1,"assign":1}
,"se":{"keyboard":1}
,"hortcuts":{"fields":1}
,"fields":{"tab":1}
,"tab":{"manage":1,"move":1,"snap":1,"left":1}
,"assign":{"field":1}
,"field":{"type":1}
,"type":{"press":1,"characters":1,"percentage":1,"keyboard":1}
,"press":{"text":1,"move":1,"ctrl":1,"add":1}
,"text":{"ctrl":1,"specific":1,"note":1}
,"ctrl":{"number":1,"date":1,"time":1,"timestamp":1,"container":1,"calculation":1,"summary":1,"press":1,"typing":1,"up":1,"arrow":1,"right":1,"shift":1,"drag":1,"select":1,"toggle":1,"table":1,"relationship":1,"ctrl":1,"choose":1,"=(":1,"-(":1,"change":1,"page":1,"display":1,"red":1}
,"number":{"ctrl":1}
,"date":{"ctrl":1}
,"time":{"ctrl":1}
,"timestamp":{"ctrl":1}
,"container":{"ctrl":1}
,"calculation":{"ctrl":1}
,"summary":{"ctrl":1}
,"move":{"selection":1,"selected":1}
,"selection":{"relationships":1,"incrementally":1,"object":1,"next":1,"pointer":1,"ctrl":1,"cursor":1,"command":1,"menu":1,"arrangement":1}
,"relationships":{"graph":1,"up":1,"selected":1}
,"graph":{"individually":1,"command":1,"type":1,"add":1,"shortcuts":1}
,"individually":{"selecting":1}
,"selecting":{"tables":1,"table":1,"expanded":1}
,"tables":{"notes":1,"shift-click":1,"drag":1,"note":1,"press":1,"ctrl":1,"related":1,"source":1,"selected":1}
,"notes":{"relationships":1,"ctrl":1}
,"up":{"arrow":1}
,"arrow":{"arrow":1,"eft":1,"right":1,"move":1,"shift":1,"hift":1,"ctrl":1,"trl":1,"selecting":1,"issue":1,"selection":1}
,"eft":{"arrow":1}
,"right":{"arrow":1,"tab":1,"left":1}
,"incrementally":{"objects":1}
,"objects":{"shift":1,"share":1}
,"shift":{"up":1,"arrow":1,"right":1,"left":1,"select":1,"edit":1,"duplicate":1,"tab":1,"ield":1}
,"hift":{"left":1}
,"left":{"arrow":1,"right":1,"relationships":1}
,"object":{"includes":1,"ctrl":1,"selection":1}
,"includes":{"text":1}
,"specific":{"characters":1}
,"characters":{"type":1,"note":1,"move":1,"switch":1}
,"note":{"if":1,"select":1,"ctrl":1,"shift-click":1,"tool":1}
,"if":{"multiple":1}
,"multiple":{"objects":1,"tables":1}
,"share":{"initial":1}
,"initial":{"characters":1}
,"next":{"occurrence":1}
,"occurrence":{"by":1}
,"by":{"pressing":1,"dragging":1}
,"pressing":{"ctrl":1}
,"typing":{"characters":1}
,"switch":{"relationships":1}
,"command":{"buttons":1,"shift":1,"button":1,"selected":1,"undo":1,"ctrl":1}
,"buttons":{"tab":1,"proceed":1,"right":1}
,"selected":{"object":1,"table":1,"tables":1,"delete":1,"add":1,"ctrl":1,"command":1,"button\u2019s":1}
,"trl":{"left":1,"shift":1}
,"table":{"drag":1,"resize":1,"select":1,"ctrl":1,"selected":1,"delete":1,"command":1}
,"drag":{"selected":1,"selection":1,"select":1,"choose":1}
,"resize":{"selected":1}
,"expanded":{"table":1}
,"select":{"multiple":1,"by":1,"all":1,"tables":1,"button":1}
,"shift-click":{"multiple":1,"temporarily":1}
,"pointer":{"multiple":1}
,"dragging":{"completely":1}
,"completely":{"tables":1}
,"all":{"tables":1}
,"related":{"currently":1}
,"currently":{"selected":1}
,"source":{"table":1}
,"toggle":{"display":1}
,"display":{"state":1,"percentage":1,"print":1,"menu":1}
,"state":{"selected":1}
,"add":{"table":1,"relationship":1,"text":1}
,"edit":{"table":1,"relationship":1}
,"delete":{"table":1,"tables":1,"relationship":1,"relationships":1}
,"relationship":{"ctrl":1,"selected":1,"delete":1,"selection":1}
,"duplicate":{"selection":1}
,"choose":{"keep":1}
,"keep":{"object":1,"magnification":1,"view":1,"note":1}
,"cursor":{"selected":1,"choose":1}
,"magnification":{"cursor":1}
,"=(":{"equals":1}
,"equals":{"note":1}
,"temporarily":{"ch":1}
,"ch":{"ooses":1}
,"ooses":{"view":1,"magnification":1}
,"view":{"reduction":1}
,"reduction":{"cursor":1}
,"-(":{"hyphen":1}
,"hyphen":{"note":1}
,"tool":{"selected":1}
,"change":{"display":1}
,"percentage":{"relationships":1,"value":1}
,"value":{"enter":1}
,"enter":{"move":1,"space":1,"issue":1}
,"proceed":{"left":1}
,"snap":{"fit":1}
,"fit":{"ctrl":1}
,"page":{"guides":1}
,"guides":{"ctrl":1}
,"print":{"setup":1}
,"setup":{"options":1}
,"options":{"ctrl":1}
,"button":{"tab":1,"space":1}
,"issue":{"selected":1,"command":1}
,"space":{"bar":1}
,"bar":{"issue":1,"display":1}
,"button\u2019s":{"menu":1}
,"menu":{"enter":1,"up":1}
,"undo":{"last":1}
,"last":{"command":1}
,"red":{"last":1}
,"ield":{"type":1}
,"arrangement":{"shortcuts":1}
}
;Search.control.loadWordPairs(pairs);
