var pairs =
{
"get":{"currenthosttime":1,"currenthosttimestamp":1,"currenttimestamp":1,"current":1,"timestamp":1,"time":1}
,"currenthosttime":{"stamp":1}
,"stamp":{"returns":1,"get":1}
,"returns":{"host\u0027s":1,"timestamp":1,"1\u002F1\u002F2019":1}
,"host\u0027s":{"current":1}
,"current":{"date":1,"host":1,"timestamp":1}
,"date":{"time":1}
,"time":{"nearest":1,"format":1,"characteristics":1,"characteristic":1,"stamp":1}
,"nearest":{"second":1}
,"second":{"system":1}
,"system":{"clock":1,"settings":1,"format":1}
,"clock":{"get":1,"january":1}
,"currenthosttimestamp":{"none":1,"get":1,"function":1}
,"none":{"timestamp":1}
,"timestamp":{"filemaker":1,"text":1,"each":1,"get":1,"current":1}
,"filemaker":{"pro":1}
,"pro":{"7.0":1}
,"7.0":{"data":1}
,"data":{"type":1}
,"type":{"calculation":1}
,"calculation":{"result":1,"field":1,"fields":1}
,"result":{"determines":1,"function":1}
,"determines":{"returned":1}
,"returned":{"value":1}
,"value":{"function":1}
,"function":{"represented":1,"returns":1,"affect":1,"unstored":1,"if":1}
,"represented":{"if":1}
,"if":{"calculation":1,"number":1,"use":1,"automatically":1}
,"text":{"th":1}
,"th":{"current":1,"total":1}
,"format":{"determined":1,"date":1}
,"determined":{"by":1}
,"by":{"operating":1}
,"operating":{"system":1}
,"settings":{"file":1}
,"file":{"created":1,"users":1,"if":1}
,"created":{"note":1,"record":1}
,"note":{"if":1}
,"number":{"seconds":1,"th":1}
,"seconds":{"zero":1,"included":1,"elapsed":1}
,"zero":{"seconds":1}
,"included":{"1\u002F1\u002F2019":1}
,"1\u002F1\u002F2019":{"11:30":1,"11:30:01":1}
,"11:30":{"number":1}
,"total":{"number":1}
,"elapsed":{"midnight":1}
,"midnight":{"january":1}
,"january":{"0001":1,"2019":1}
,"0001":{"client":1}
,"client":{"machine":1}
,"machine":{"host":1,"times":1,"get":1}
,"host":{"machine":1,"system":1,"time":1,"timestamp":1}
,"times":{"zones":1}
,"zones":{"get":1}
,"currenttimestamp":{"return":1}
,"return":{"date\u002Ftime":1}
,"date\u002Ftime":{"values":1}
,"values":{"current":1}
,"characteristics":{"host":1}
,"characteristic":{"database":1}
,"database":{"file":1}
,"users":{"connected":1}
,"connected":{"network":1}
,"network":{"get":1,"access":1}
,"affect":{"performance":1}
,"performance":{"database":1}
,"use":{"function":1}
,"unstored":{"calculation":1}
,"field":{"field":1,"visible":1,"requires":1,"minimize":1}
,"visible":{"list":1}
,"list":{"view":1}
,"view":{"each":1}
,"each":{"display":1,"newly":1}
,"display":{"field":1}
,"requires":{"additional":1}
,"additional":{"network":1}
,"access":{"stored":1,"returns":1}
,"stored":{"calculation":1}
,"fields":{"use":1}
,"automatically":{"enter":1}
,"enter":{"timestamp":1}
,"newly":{"created":1}
,"record":{"stored":1}
,"minimize":{"network":1}
,"11:30:01":{"system":1,"host":1}
,"2019":{"11:30:01":1}
}
;Search.control.loadWordPairs(pairs);
