var pairs =
{
"case":{"returns":1,"test1":1,"function":1,"score":1,"shipment":1}
,"returns":{"based":1,"value":1,"empty":1,"shipment":1,"10":1}
,"based":{"series":1}
,"series":{"tests":1}
,"tests":{"case":1}
,"test1":{"result1":1}
,"result1":{"test2":1}
,"test2":{"result2":1}
,"result2":{"defaultresult":1}
,"defaultresult":{"test":1,"if":1}
,"test":{"-any":1,"expression":1}
,"-any":{"text":1}
,"text":{"numeric":1,"number":1}
,"numeric":{"expression":1}
,"expression":{"result":1,"parameters":1,"order":1,"found":1,"include":1}
,"result":{"-result":1,"expression":1,"end":1,"supplied":1,"case":1}
,"-result":{"expression":1}
,"parameters":{"braces":1}
,"braces":{"optional":1}
,"optional":{"text":1}
,"number":{"date":1}
,"date":{"time":1}
,"time":{"timestamp":1}
,"timestamp":{"container":1}
,"container":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"case":1}
,"function":{"evaluates":1,"returns":1}
,"evaluates":{"each":1}
,"each":{"test":1}
,"order":{"true":1}
,"true":{"expression":1,"case":1}
,"found":{"returns":1}
,"value":{"result":1,"defaultresult":1}
,"include":{"default":1}
,"default":{"result":1}
,"end":{"parameter":1}
,"parameter":{"list":1}
,"list":{"if":1}
,"if":{"none":1,"default":1}
,"none":{"expressions":1}
,"expressions":{"evaluated":1}
,"evaluated":{"return":1}
,"return":{"true":1}
,"supplied":{"case":1}
,"empty":{"result":1}
,"score":{">=90":1,"50":1,"90":1,"case":1}
,">=90":{"excellent":1}
,"excellent":{"score":1}
,"50":{"satisfactory":1,"90":1}
,"satisfactory":{"improvement":1,"score":1}
,"improvement":{"displays":1,"score":1}
,"displays":{"excellent":1}
,"90":{"satisfactory":1,"improvement":1}
,"shipment":{"method=\u0022":1,"method":1}
,"method=\u0022":{"ground":1,"air":1}
,"ground":{"shipment":1,"returns":1}
,"air":{"10":1}
,"10":{"returns":1,"shipment":1}
,"method":{"field":1}
,"field":{"ground":1,"air":1}
}
;Search.control.loadWordPairs(pairs);
