var pairs =
{
"options":{"developer":1,"solution":1,"dialog":1,"bind":1,"error":1}
,"developer":{"solution":1,"utilities":1}
,"solution":{"note":1,"close":1,"solution":1,"options":1,"application":1,"permanently":1,"select":1,"removing":1,"kiosk":1,"setting":1}
,"note":{"topic":1,"option":1}
,"topic":{"describes":1}
,"describes":{"features":1}
,"features":{"use":1}
,"use":{"advanced":1,"feature":1}
,"advanced":{"tools":1}
,"tools":{"general":1,"se":1,"menu":1}
,"general":{"preference":1}
,"preference":{"selected":1}
,"selected":{"ad":1}
,"ad":{"vanced":1}
,"vanced":{"tools":1}
,"se":{"developer":1}
,"utilities":{"customize":1,"if":1,"database":1,"settings":1}
,"customize":{"set":1,"choose":1,"if":1,"database":1}
,"set":{"database":1}
,"database":{"files":1,"saved":1,"encryption":1,"force":1,"file":1}
,"files":{"bind":1,"runtime":1,"customize":1,"want":1,"double-click":1,"developer":1,"remove":1,"permanently":1,"select":1,"extensions":1,"note":1,"bound":1}
,"bind":{"files":1,"databases":1}
,"runtime":{"solution":1,"applications":1}
,"close":{"all":1}
,"all":{"database":1,"except":1}
,"choose":{"tools":1,"folder":1}
,"menu":{"developer":1}
,"if":{"developer":1,"add":1,"select":1,"don\u2019t":1,"error":1}
,"saved":{"settings":1,"project":1}
,"settings":{"load":1,"add":1,"required":1,"choose":1,"file":1}
,"load":{"settings":1}
,"add":{"locate":1,"multiple":1,"filemaker":1,"extensions":1}
,"locate":{"files":1}
,"want":{"customize":1}
,"multiple":{"files":1}
,"double-click":{"file":1}
,"file":{"list":1,"select":1,"extension":1,"record":1,"decrypt":1,"saving":1}
,"list":{"primary":1}
,"primary":{"file":1}
,"select":{"developer":1,"options":1,"create":1,"remove":1,"enable":1,"databases":1}
,"required":{"setting":1}
,"setting":{"up":1,"11":1}
,"up":{"files":1}
,"dialog":{"box":1}
,"box":{"select":1}
,"databases":{"runtime":1,"filemaker":1,"kiosk":1}
,"applications":{"select":1,"encrypting":1}
,"create":{"runtime":1,"log":1,"error":1,"customize":1}
,"application":{"note":1,"use":1}
,"option":{"combined":1,"if":1}
,"combined":{"all":1}
,"except":{"databases":1}
,"filemaker":{"file":1,"extension":1}
,"extension":{"enable":1,"filenames":1,"note":1}
,"enable":{"database":1,"kiosk":1}
,"encryption":{"re-encrypt":1,"creating":1,"decrypting":1}
,"re-encrypt":{"files":1,"database":1}
,"remove":{"database":1,"admin":1}
,"creating":{"runtime":1}
,"permanently":{"prohibit":1,"removed":1}
,"prohibit":{"administrative":1}
,"administrative":{"access":1}
,"access":{"solution":1,"files":1,"restored":1,"database":1,"privileges":1}
,"admin":{"access":1}
,"removed":{"administrative":1}
,"restored":{"custom":1}
,"custom":{"solution":1}
,"removing":{"admin":1}
,"force":{"accounts":1}
,"accounts":{"full":1,"displaying":1}
,"full":{"access":1}
,"privileges":{"open":1}
,"open":{"solution":1}
,"kiosk":{"mode":1,"mod":1}
,"mode":{"select":1,"non-admin":1}
,"non-admin":{"accounts":1}
,"displaying":{"databases":1}
,"mod":{"add":1}
,"filenames":{"database":1}
,"feature":{"add":1,"encrypt":1}
,"extensions":{"files":1,"create":1}
,"log":{"file":1,"processing":1,"notes":1,"saved":1,"error":1}
,"record":{"errors":1}
,"errors":{"encountered":1,"location":1}
,"encountered":{"during":1,"encrypt":1}
,"during":{"processing":1}
,"processing":{"select":1,"errors":1,"options":1}
,"error":{"log":1,"occurs":1,"logged":1,"message":1,"encountered":1}
,"location":{"filename":1,"error":1,"settings":1}
,"filename":{"error":1,"location":1,"logfile.txt":1}
,"notes":{"if":1}
,"don\u2019t":{"filename":1}
,"project":{"folder":1}
,"folder":{"filename":1,"location":1}
,"logfile.txt":{"if":1}
,"occurs":{"during":1}
,"logged":{"error":1}
,"message":{"error":1}
,"encrypt":{"re-encrypt":1,"database":1}
,"bound":{"runtime":1}
,"encrypting":{"database":1}
,"decrypt":{"database":1}
,"decrypting":{"fil":1}
,"fil":{"10":1}
,"10":{"quickly":1}
,"quickly":{"repeat":1}
,"repeat":{"process":1}
,"process":{"save":1}
,"save":{"settings":1}
,"saving":{"solution":1}
,"11":{"create":1}
}
;Search.control.loadWordPairs(pairs);
