var pairs =
{
"portals":{"layouts":1,"display":1,"master-detail":1}
,"layouts":{"portal":1}
,"portal":{"layout":1,"want":1,"display":1,"records":1,"list":1}
,"layout":{"object":1,"creating":1}
,"object":{"displays":1}
,"displays":{"list":1}
,"list":{"records":1}
,"records":{"record":1,"related":1,"table":1,"current":1}
,"record":{"each":1,"portal":1,"add":1,"master-detail":1}
,"each":{"row":1}
,"row":{"use":1}
,"use":{"portal":1}
,"want":{"display":1}
,"display":{"data":1,"records":1,"related":1}
,"data":{"record":1}
,"related":{"table":1,"records":1,"record":1}
,"table":{"current":1,"add":1,"create":1,"occurrence":1,"custom":1,"next":1}
,"current":{"table":1}
,"add":{"portal":1,"dd-on":1}
,"create":{"relationship":1,"portal":1}
,"relationship":{"table":1}
,"occurrence":{"create":1,"reating":1}
,"reating":{"portals":1}
,"dd-on":{"table":1}
,"custom":{"app":1,"apps":1}
,"app":{"dding":1}
,"dding":{"add-on":1}
,"add-on":{"tables":1}
,"tables":{"custom":1}
,"apps":{"use":1}
,"next":{"details":1}
,"details":{"record":1}
,"master-detail":{"layout":1,"layouts":1}
,"creating":{"portals":1}
}
;Search.control.loadWordPairs(pairs);
