var pairs =
{
"defining":{"field":1}
,"field":{"indexing":1,"filemaker":1,"fields":1,"appears":1,"name":1,"dialog":1,"calculation":1,"normal":1,"minimal":1,"returning":1,"if":1,"match":1,"relationship":1,"each":1,"indexed":1,"field\u2019s":1,"first":1,"faster":1,"create":1}
,"indexing":{"options":1,"field":1,"sorting":1}
,"options":{"yo":1,"double-click":1,"field":1,"select":1}
,"yo":{"create":1}
,"create":{"indexes":1,"value":1,"word":1,"index":1,"relationships":1}
,"indexes":{"lists":1,"searching":1,"increase":1,"tasks":1,"created":1,"joining":1,"each":1,"select":1,"text":1,"create":1,"indexes":1,"field":1,"fields":1,"combination":1,"prevents":1}
,"lists":{"values":1}
,"values":{"field":1,"automatically":1,"text":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"indexes":1,"indexing":1,"calculate":1}
,"searching":{"joining":1}
,"joining":{"related":1}
,"related":{"tables":1,"records":1}
,"tables":{"indexes":1}
,"increase":{"speed":1,"file":1}
,"speed":{"searches":1}
,"searches":{"increase":1,"number":1,"word":1,"field":1}
,"file":{"size":1,"menu":1}
,"size":{"filemaker":1,"choose":1,"word":1}
,"tasks":{"value":1}
,"value":{"indexes":1,"index":1}
,"created":{"text":1,"by":1,"subsequent":1}
,"text":{"number":1,"fields":1,"result":1,"generate":1,"field":1,"field\u2019s":1,"all":1,"delimited":1}
,"number":{"date":1}
,"date":{"time":1}
,"time":{"timestamp":1,"calculate":1,"each":1,"user":1}
,"timestamp":{"fields":1}
,"fields":{"calculation":1,"return":1,"large":1,"tab":1,"returning":1,"select":1,"significantly":1,"match":1,"creating":1,"use":1}
,"calculation":{"fields":1,"field":1,"dialog":1,"if":1}
,"return":{"types":1,"text":1,"character":1}
,"types":{"value":1,"note":1,"all":1}
,"records":{"searches":1,"take":1}
,"note":{"behavior":1}
,"behavior":{"dependent":1}
,"dependent":{"data":1}
,"data":{"source":1}
,"source":{"drivers":1}
,"drivers":{"japanese":1}
,"japanese":{"collation":1}
,"collation":{"distinguish":1}
,"distinguish":{"ka":1}
,"ka":{"takana":1}
,"takana":{"hi":1}
,"hi":{"ragana":1}
,"ragana":{"full-or":1}
,"full-or":{"half-width":1}
,"half-width":{"case":1}
,"case":{"ro":1}
,"ro":{"characters":1}
,"characters":{"accents":1}
,"accents":{"word":1}
,"word":{"indexes":1,"index":1,"field":1,"text":1,"value":1}
,"result":{"searches":1,"value":1}
,"index":{"created":1,"significantly":1,"text":1,"field\u0027s":1,"if":1,"import":1,"option":1,"field":1}
,"by":{"storing":1,"each":1,"carriage":1}
,"storing":{"each":1}
,"each":{"unique":1,"language":1,"line":1,"word":1}
,"unique":{"word":1}
,"large":{"amounts":1,"indexes":1}
,"amounts":{"text":1}
,"generate":{"large":1}
,"appears":{"word":1}
,"significantly":{"increase":1}
,"choose":{"file":1}
,"menu":{"manage":1}
,"manage":{"database":1}
,"database":{"fields":1,"table":1}
,"tab":{"if":1}
,"if":{"database":1,"selected":1,"user":1,"field":1,"want":1}
,"table":{"select":1,"table":1,"list":1}
,"select":{"table":1,"indexing":1,"automatically":1,"none":1,"store":1}
,"list":{"field":1,"language":1}
,"name":{"options":1}
,"double-click":{"field":1}
,"dialog":{"box":1}
,"box":{"storage":1}
,"storage":{"tab":1,"options":1}
,"selected":{"calculation":1}
,"normal":{"use":1}
,"use":{"use":1,"none":1,"index":1,"minimal":1}
,"none":{"minimal":1,"prevent":1,"deselecting":1}
,"minimal":{"select":1,"create":1,"deselect":1}
,"automatically":{"create":1}
,"prevent":{"filemaker":1}
,"field\u2019s":{"contents":1,"index":1}
,"contents":{"calculation":1}
,"returning":{"text":1,"types":1}
,"all":{"create":1,"creates":1,"text":1}
,"creates":{"index":1}
,"field\u0027s":{"values":1}
,"user":{"performs":1}
,"performs":{"search":1,"find":1}
,"search":{"field":1,"slow":1}
,"match":{"field":1,"fields":1}
,"relationship":{"language":1,"create":1}
,"language":{"default":1,"list":1,"indexing":1,"tailored":1}
,"default":{"language":1}
,"sorting":{"values":1,"requirements":1,"tored":1}
,"tailored":{"support":1}
,"support":{"language-specific":1}
,"language-specific":{"indexing":1}
,"requirements":{"calculation":1}
,"store":{"calculation":1}
,"want":{"filemaker":1}
,"calculate":{"result":1,"electing":1}
,"line":{"text":1}
,"delimited":{"by":1}
,"carriage":{"return":1}
,"character":{"hoosing":1}
,"hoosing":{"language":1}
,"tored":{"require":1}
,"require":{"disk":1,"time":1}
,"disk":{"space":1}
,"space":{"unstored":1}
,"unstored":{"require":1}
,"electing":{"all":1}
,"indexed":{"operations":1}
,"operations":{"importing":1}
,"importing":{"records":1}
,"take":{"time":1}
,"import":{"occurs":1}
,"occurs":{"automatically":1}
,"first":{"time":1,"search":1}
,"find":{"request":1}
,"request":{"searches":1}
,"slow":{"index":1}
,"subsequent":{"searches":1}
,"faster":{"use":1}
,"option":{"creates":1}
,"relationships":{"text":1,"set":1}
,"creating":{"word":1}
,"deselect":{"automatically":1}
,"combination":{"selecting":1}
,"selecting":{"none":1}
,"deselecting":{"automatically":1}
,"prevents":{"field":1}
,"set":{"indexing":1}
}
;Search.control.loadWordPairs(pairs);
