var pairs =
{
"orking":{"ex":1}
,"ex":{"cel":1}
,"cel":{"use":1}
,"use":{"excel":1,"filemaker":1,"scripts":1}
,"excel":{"filemaker":1,"file":1,"files":1,"format":1,"im":1,"export":1,"data":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1,"format":1}
,"advanced":{"variety":1,"import":1,"easy":1,"data":1,"bring":1,"ile":1,"file":1,"save":1,"excel":1,"interprets":1}
,"variety":{"use":1}
,"import":{"data":1,"modified":1}
,"data":{"stored":1,"imported":1,"made":1,"excel":1,"existing":1,"file":1,"filemaker":1}
,"stored":{"excel":1}
,"file":{"regular":1,"reimported":1,"existing":1,"mporting":1,"create":1,"convert":1,"new":1,"data":1,"export":1}
,"regular":{"basis":1}
,"basis":{"set":1}
,"set":{"up":1}
,"up":{"recurring":1}
,"recurring":{"imports":1,"import":1}
,"imports":{"filemaker":1,"note":1}
,"easy":{"import":1}
,"files":{"setti":1}
,"setti":{"ng":1}
,"ng":{"up":1}
,"note":{"data":1}
,"imported":{"via":1}
,"via":{"recurring":1}
,"modified":{"filemaker":1}
,"made":{"excel":1}
,"reimported":{"filemaker":1}
,"bring":{"data":1}
,"existing":{"filemaker":1,"file":1}
,"ile":{"import":1,"data":1}
,"mporting":{"data":1}
,"create":{"new":1}
,"new":{"filemaker":1,"excel":1}
,"convert":{"data":1}
,"format":{"filemaker":1,"onverting":1,"xporting":1,"aving":1}
,"onverting":{"data":1}
,"export":{"data":1,"records":1}
,"xporting":{"data":1}
,"save":{"records":1}
,"records":{"excel":1,"formats":1,"ave":1,"learn":1}
,"aving":{"sending":1}
,"sending":{"records":1}
,"formats":{"use":1}
,"scripts":{"import":1}
,"im":{"port":1}
,"port":{"records":1}
,"ave":{"records":1}
,"learn":{"filemaker":1}
,"interprets":{"excel":1}
}
;Search.control.loadWordPairs(pairs);
