var pairs =
{
"speci":{"fy":1}
,"fy":{"find":1}
,"find":{"requests":1,"request":1,"enter":1,"mode":1,"extend":1,"records":1,"omit":1,"script":1,"matching":1,"criteria":1,"text":1}
,"requests":{"edit":1,"script":1,"list":1,"if":1,"create":1,"elow":1,"dialog":1}
,"edit":{"find":1,"selected":1,"edit":1}
,"request":{"dialog":1,"aving":1,"new":1,"edit":1,"list":1,"find":1,"by":1,"change":1,"represent":1,"include":1,"can\u2019t":1,"validation":1,"enter":1,"variable":1}
,"dialog":{"boxes":1,"box":1}
,"boxes":{"use":1,"create":1}
,"use":{"dialog":1,"multiple":1,"slash":1}
,"create":{"manage":1,"saved":1,"edit":1}
,"manage":{"find":1}
,"script":{"steps":1,"step":1}
,"steps":{"create":1}
,"saved":{"find":1}
,"enter":{"find":1,"$symbol":1}
,"mode":{"perform":1}
,"perform":{"find":1}
,"extend":{"found":1}
,"found":{"set":1,"use":1}
,"set":{"constrain":1,"saving":1,"omitting":1}
,"constrain":{"found":1}
,"saving":{"find":1}
,"aving":{"find":1}
,"new":{"edit":1,"list":1}
,"box":{"define":1,"otes":1,"field":1,"remove":1,"filemaker":1,"edit":1}
,"define":{"criteria":1}
,"criteria":{"find":1,"selected":1,"insert":1,"finding":1,"select":1,"top":1,"change":1,"date":1,"return":1,"record":1}
,"selected":{"find":1,"field":1}
,"list":{"duplicate":1,"delete":1,"action":1,"fields":1,"select":1,"change":1,"operators":1}
,"duplicate":{"duplicates":1}
,"duplicates":{"selected":1}
,"delete":{"deletes":1,"existing":1}
,"deletes":{"selected":1}
,"action":{"select":1,"criteria":1}
,"select":{"find":1,"field":1,"related":1,"line":1}
,"records":{"omit":1,"find":1,"finding":1,"adds":1,"excludes":1,"use":1,"during":1,"list":1,"include":1,"accurately":1,"found":1,"assume":1,"entered":1,"table":1}
,"omit":{"records":1}
,"finding":{"records":1,"text":1}
,"adds":{"found":1}
,"omitting":{"records":1}
,"excludes":{"individual":1}
,"individual":{"request":1}
,"multiple":{"requests":1}
,"if":{"find":1,"variables":1}
,"during":{"perform":1,"validation":1}
,"step":{"find":1}
,"fields":{"current":1}
,"current":{"table":1}
,"table":{"construct":1,"name":1,"top":1,"want":1,"criteria":1,":firstname":1}
,"construct":{"find":1}
,"by":{"selecting":1}
,"selecting":{"field":1}
,"field":{"list":1,"related":1,"new":1,"type":1,"criteria":1,"syntax":1,"edit":1,"called":1}
,"related":{"table":1,"field":1}
,"name":{"current":1}
,"top":{"list":1,"dialog":1}
,"want":{"select":1}
,"change":{"value":1,"existing":1,"store":1}
,"value":{"repetition":1,"$birthquery":1,"variable":1}
,"repetition":{"cell":1,"index":1}
,"cell":{"repeating":1}
,"repeating":{"field":1}
,"type":{"search":1}
,"search":{"criteria":1}
,"insert":{"operator":1}
,"operator":{"further":1}
,"further":{"refine":1}
,"refine":{"search":1}
,"include":{"local":1,"repetition":1,"additional":1}
,"local":{"variables":1}
,"variables":{"$)":1,"$$)":1,"find":1,"filemaker":1,"nested":1}
,"$)":{"global":1}
,"global":{"variables":1}
,"$$)":{"find":1}
,"otes":{"variables":1}
,"elow":{"add":1}
,"add":{"add":1,"criteria":1}
,"existing":{"criteria":1}
,"line":{"field":1}
,"store":{"delete":1}
,"remove":{"variable":1}
,"variable":{"find":1,"unknown":1,"enter":1,"if":1,"filemaker":1,"evaluated":1,"file":1}
,"represent":{"simple":1}
,"simple":{"expression":1}
,"expression":{"*\u002F*\u002F$birthyear":1,"$birthquery":1}
,"*\u002F*\u002F$birthyear":{"complex":1}
,"complex":{"expression":1}
,"$birthquery":{"value":1,"*\u002F*\u002F1994":1}
,"*\u002F*\u002F1994":{"variable":1}
,"index":{"number":1}
,"number":{"repeating":1}
,"syntax":{"$variable":1}
,"$variable":{"[repetition]":1}
,"[repetition]":{"file":1}
,"file":{"path":1}
,"path":{"variables":1,"table":1}
,"can\u2019t":{"include":1}
,"additional":{"variables":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"find":1,"detects":1,"stops":1,"doesn\u2019t":1}
,"matching":{"records":1}
,"accurately":{"if":1}
,"nested":{"value":1}
,"unknown":{"during":1}
,"validation":{"field\u2019s":1,"stops":1}
,"field\u2019s":{"find":1}
,"stops":{"filemaker":1,"validating":1}
,"detects":{"variable":1}
,"date":{"field":1}
,"validating":{"request":1}
,"$symbol":{"indicating":1}
,"indicating":{"variable":1}
,"doesn\u2019t":{"recognize":1}
,"recognize":{"variable":1}
,"evaluated":{"matching":1}
,"slash":{"(\u002F)":1}
,"(\u002F)":{"colon":1}
,"colon":{"terminator":1}
,"terminator":{"character":1}
,"character":{"variable":1}
,"return":{"records":1}
,"assume":{"records":1}
,"entered":{"text":1}
,"text":{"field":1,"finding":1,"characters":1}
,"called":{"firstname":1}
,"firstname":{"anne":1}
,"anne":{"andrew":1,"find":1}
,"andrew":{"lando5":1,"find":1,"han":1}
,"lando5":{"han":1}
,"han":{"han":1,"susan":1,"find":1}
,"susan":{"action":1,"find":1,"list":1}
,"record":{"returned":1}
,"returned":{"find":1}
,":firstname":{"[==\u0022":1,"[*an]":1,"[@an]":1,"[!]":1,"[@an*]":1,"[*e*]":1,"[*w*]":1,"[*an*]":1,"[*#]":1}
,"[==\u0022":{"ndrew":1}
,"ndrew":{"\u0022]":1}
,"\u0022]":{"andrew":1}
,"[*an]":{"han":1}
,"[@an]":{"han":1}
,"[!]":{"han":1}
,"[@an*]":{"lando5":1}
,"[*e*]":{"table":1}
,"[*w*]":{"anne":1}
,"[*an*]":{"table":1}
,"[*#]":{"anne":1}
,"operators":{"find":1}
,"characters":{"find":1}
}
;Search.control.loadWordPairs(pairs);
