var pairs =
{
"furigana":{"converts":1,"text":1,"returns":1,"japanese":1}
,"converts":{"japanese":1,"text":1}
,"japanese":{"text":1,"kanji":1,"hiragana":1}
,"text":{"hiragana":1,"furigana":1,"option":1,"-any":1,"expression":1,"field":1,"text":1,"filemaker":1,"composed":1,"roman":1}
,"hiragana":{"katakana":1,"full-width":1,"converts":1,"furigana":1,"pronounced":1}
,"katakana":{"roman":1,"kanji":1}
,"roman":{"text":1,"romaji":1}
,"option":{"text":1,"-1":1,"parameter":1,"converts":1,"value":1}
,"-any":{"text":1}
,"expression":{"text":1}
,"field":{"option":1}
,"-1":{"depending":1}
,"depending":{"want":1}
,"want":{"convert":1}
,"convert":{"text":1}
,"filemaker":{"pro":1}
,"pro":{"14.0":1}
,"14.0":{"japanese":1}
,"composed":{"kana":1}
,"kana":{"hiragana":1,"phonetic":1}
,"kanji":{"characters":1}
,"characters":{"kanji":1,"multiple":1,"arbitrary":1,"meaningful":1,"pronounced":1}
,"multiple":{"readings":1}
,"readings":{"unicode":1}
,"unicode":{"characters":1}
,"arbitrary":{"sort":1}
,"sort":{"kanji":1,"by":1}
,"meaningful":{"sort":1}
,"by":{"kana":1}
,"phonetic":{"syllabary":1}
,"syllabary":{"reading":1}
,"reading":{"intended":1}
,"intended":{"each":1}
,"each":{"character":1}
,"character":{"option":1}
,"parameter":{"determines":1}
,"determines":{"furigana":1}
,"romaji":{"text":1}
,"full-width":{"ka":1,"ro":1}
,"ka":{"takana":1}
,"takana":{"full-width":1,"half-width":1}
,"ro":{"ro":1,"maji":1}
,"maji":{"half-width":1,"if":1}
,"half-width":{"ka":1,"ro":1}
,"if":{"option":1}
,"value":{"furigana":1}
,"returns":{"text":1,"japanese":1,"toukyouto":1}
,"pronounced":{"tokyoto":1}
,"tokyoto":{"returns":1,"converts":1}
}
;Search.control.loadWordPairs(pairs);
