var pairs =
{
"revert":{"record\u002Frequest":1,"action":1,"if":1}
,"record\u002Frequest":{"eturns":1,"[with":1}
,"eturns":{"current":1}
,"current":{"record":1}
,"record":{"find":1,"modified":1,"if":1}
,"find":{"request":1}
,"request":{"editing":1}
,"editing":{"dialog":1}
,"dialog":{"displays":1,"box":1,"[\u0022":1,"off]":1}
,"displays":{"dialog":1}
,"box":{"script":1,"if":1}
,"script":{"step":1}
,"step":{"performed":1}
,"performed":{"users":1}
,"users":{"confirm":1}
,"confirm":{"revert":1}
,"action":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"displays":1}
,"if":{"current":1,"[get":1,"end":1,"restoring":1}
,"modified":{"committed":1,"last":1}
,"committed":{"user":1}
,"user":{"option":1}
,"option":{"reverting":1}
,"reverting":{"record":1}
,"[get":{"recordopenstate":1,"lastmessagechoice":1}
,"recordopenstate":{"=2]":1}
,"=2]":{"show":1,"revert":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"[\u0022":{"record":1}
,"last":{"entered":1}
,"entered":{"\u0022]":1}
,"\u0022]":{"button":1}
,"button":{"commit":1,"revert":1}
,"commit":{"button":1}
,"lastmessagechoice":{"=2]":1}
,"[with":{"dialog":1}
,"off]":{"end":1}
,"end":{"if":1}
,"restoring":{"data":1}
,"data":{"records":1}
,"records":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
