var pairs =
{
"set":{"ting":1,"name":1,"language":1,"style":1,"font":1}
,"ting":{"general":1}
,"general":{"preferences":1,"application":1,"tab":1}
,"preferences":{"general":1,"affect":1,"cl":1,"macos":1}
,"application":{"preferences":1}
,"affect":{"all":1}
,"all":{"filemaker":1,"layout":1,"dialog":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"documents":1,"enu":1,"menus":1,"if":1,"installation":1,"development":1,"tools":1,"selecting":1}
,"documents":{"indows":1}
,"indows":{"choose":1}
,"choose":{"dit":1,"ilemaker":1,"insert":1,"language":1,"style":1}
,"dit":{"menu":1}
,"menu":{"preference":1,"recent":1,"current":1}
,"preference":{"acos":1,"order":1,"stop":1}
,"acos":{"choose":1}
,"ilemaker":{"pro":1}
,"enu":{"preferences":1}
,"cl":{"ick":1}
,"ick":{"general":1}
,"tab":{"enable":1,"reset":1}
,"enable":{"drag":1}
,"drag":{"drop":1}
,"drop":{"capabilities":1,"select":1,"text":1}
,"capabilities":{"move":1}
,"move":{"text":1}
,"text":{"fields":1,"selection":1,"easier":1,"box":1}
,"fields":{"fields":1,"layouts":1,"field":1}
,"layouts":{"applications":1}
,"applications":{"support":1}
,"support":{"drag":1}
,"select":{"allow":1,"show":1,"enlarge":1,"se":1,"system":1,"type":1,"use":1}
,"allow":{"drag":1}
,"selection":{"display":1}
,"display":{"names":1,"manage":1}
,"names":{"up":1}
,"up":{"30":1}
,"30":{"files":1,"windows":1}
,"files":{"file":1,"enter":1,"deselecting":1,"system":1}
,"file":{"menu":1,"select":1,"system":1}
,"recent":{"menu":1,"window":1}
,"window":{"select":1,"contents":1}
,"show":{"files":1}
,"enter":{"number":1}
,"number":{"30":1}
,"windows":{"text":1,"font":1,"type":1,"user":1,"set":1}
,"easier":{"read":1}
,"read":{"by":1}
,"by":{"increasing":1}
,"increasing":{"size":1}
,"size":{"all":1,"position":1}
,"layout":{"objects":1,"mode":1}
,"objects":{"select":1}
,"enlarge":{"window":1}
,"contents":{"improve":1}
,"improve":{"readability":1}
,"readability":{"note":1}
,"note":{"windows":1,"restart":1}
,"font":{"smoothing":1}
,"smoothing":{"75":1,"font":1,"style":1,"styles":1,"100":1,"options":1}
,"75":{"zoom":1}
,"zoom":{"level":1}
,"level":{"option":1,"macos":1}
,"option":{"selected":1,"displays":1}
,"selected":{"display":1}
,"manage":{"database":1}
,"database":{"dialog":1,"encryption":1}
,"dialog":{"bo":1,"create":1,"boxes":1,"sizes":1}
,"bo":{"create":1}
,"create":{"new":1,"files":1}
,"new":{"file":1,"language":1}
,"se":{"manage":1}
,"deselecting":{"option":1}
,"displays":{"layout":1}
,"mode":{"defining":1}
,"defining":{"changing":1}
,"changing":{"fields":1}
,"field":{"tab":1}
,"reset":{"size":1,"dialog":1,"set":1}
,"position":{"all":1}
,"boxes":{"defaults":1,"messages":1}
,"defaults":{"reset":1}
,"sizes":{"positions":1}
,"positions":{"reset":1}
,"name":{"identifies":1,"windows":1,"user":1,"macos":1,"select":1,"text":1,"name":1,"entered":1}
,"identifies":{"user":1}
,"user":{"value":1,"name":1,"interface":1}
,"value":{"choose":1}
,"insert":{"menu":1}
,"current":{"user":1}
,"type":{"name":1}
,"macos":{"select":1,"elp":1,"use":1,"nd":1,"set":1}
,"system":{"user":1,"name":1,"preferences":1,"formats":1}
,"box":{"system":1}
,"entered":{"system":1}
,"elp":{"set":1,"log":1,"use":1}
,"language":{"filemaker":1,"choose":1,"macos":1,"notes":1,"take":1,"components":1,"pack":1}
,"menus":{"dialog":1,"database":1}
,"messages":{"windows":1}
,"interface":{"language":1}
,"use":{"system":1,"filemaker":1,"advanced":1}
,"log":{"macos":1,"back":1}
,"nd":{"log":1}
,"back":{"new":1}
,"notes":{"new":1,"if":1}
,"take":{"restart":1}
,"restart":{"filemaker":1}
,"if":{"language":1,"fonts":1,"deselect":1}
,"components":{"installed":1}
,"installed":{"ay":1}
,"ay":{"alert":1}
,"alert":{"ed":1}
,"ed":{"install":1}
,"install":{"language":1}
,"pack":{"ilemaker":1}
,"installation":{"guide":1}
,"guide":{"setting":1}
,"setting":{"change":1}
,"change":{"system":1}
,"formats":{"displaying":1,"files":1,"windows":1}
,"displaying":{"sorting":1}
,"sorting":{"dates":1}
,"dates":{"times":1}
,"times":{"numbers":1}
,"numbers":{"file":1}
,"style":{"font":1,"choose":1,"notes":1}
,"fonts":{"screen":1}
,"screen":{"fuzzy":1}
,"fuzzy":{"want":1}
,"want":{"experiment":1}
,"experiment":{"font":1}
,"styles":{"find":1}
,"find":{"monitor":1}
,"monitor":{"windows":1}
,"100":{"zoom":1}
,"options":{"system":1}
,"development":{"deployment":1}
,"deployment":{"features":1}
,"features":{"script":1}
,"script":{"debugger":1}
,"debugger":{"custom":1}
,"custom":{"menus":1}
,"encryption":{"select":1}
,"tools":{"ad":1,"note":1,"restart":1}
,"ad":{"vanced":1}
,"vanced":{"tools":1}
,"selecting":{"preference":1}
,"order":{"use":1}
,"deselect":{"preference":1}
,"stop":{"tools":1}
}
;Search.control.loadWordPairs(pairs);
