var pairs =
{
"get":{"windowdeskto":1,"windowdesktopwidth":1,"window":1,"desktop":1}
,"windowdeskto":{"pwidth":1}
,"pwidth":{"returns":1}
,"returns":{"width":1,"1920":1,"2560":1}
,"width":{"points":1,"get":1}
,"points":{"desktop":1}
,"desktop":{"space":1,"width":1}
,"space":{"get":1,"monitor":1,"main":1,"entire":1}
,"windowdesktopwidth":{"none":1,"get":1}
,"none":{"number":1}
,"number":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1,"go":1}
,"pro":{"7.0":1,"advanced":1}
,"7.0":{"filemaker":1}
,"advanced":{"desktop":1}
,"monitor":{"screen":1,"active":1,"taskbar":1,"resolution":1}
,"screen":{"active":1,"macos":1,"returns":1}
,"active":{"window":1}
,"window":{"located":1,"desktop":1}
,"located":{"excluding":1,"windows":1,"filemaker":1}
,"excluding":{"taskbar":1}
,"taskbar":{"windows":1,"located":1}
,"windows":{"menu":1,"main":1,"single":1}
,"menu":{"bar":1,"bars":1}
,"bar":{"dock":1}
,"dock":{"macos":1}
,"macos":{"filemaker":1,"all":1,"single":1}
,"webdirect":{"desktop":1}
,"main":{"monitor":1}
,"all":{"monitors":1}
,"monitors":{"menu":1}
,"bars":{"main":1}
,"go":{"desktop":1}
,"entire":{"screen":1}
,"1920":{"windows":1,"1080":1}
,"single":{"monitor":1}
,"resolution":{"set":1}
,"set":{"1920":1,"2560":1}
,"1080":{"returns":1}
,"2560":{"macos":1,"1440":1}
,"1440":{"get":1}
}
;Search.control.loadWordPairs(pairs);
