var pairs =
{
"pv":{"returns":1,"series":1,"payment":1,"equation":1,"function":1,"500":1}
,"returns":{"value":1,"result":1,"2164.73833531":1}
,"value":{"pv":1}
,"series":{"equal":1}
,"equal":{"payments":1}
,"payments":{"made":1,"number":1,"worth":1}
,"made":{"regular":1,"period":1}
,"regular":{"intervals":1}
,"intervals":{"assuming":1,"payments":1}
,"assuming":{"fixed":1}
,"fixed":{"interest":1}
,"interest":{"rate":1}
,"rate":{"interval":1,"period":1}
,"interval":{"pv":1}
,"payment":{"interestrate":1,"-payment":1,"*periods":1}
,"interestrate":{"periods":1,"-interest":1,"function":1}
,"periods":{"payment":1,"-number":1,"intervals":1}
,"-payment":{"made":1}
,"period":{"type":1,"periods":1}
,"type":{"negative":1}
,"negative":{"number":1}
,"number":{"money":1,"filemaker":1}
,"money":{"pay":1,"receive":1}
,"pay":{"positive":1,"back":1}
,"positive":{"number":1}
,"receive":{"interestrate":1}
,"-interest":{"rate":1}
,"-number":{"periods":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"use":1}
,"use":{"function":1}
,"function":{"calculate":1,"returns":1,"pv":1}
,"calculate":{"pv":1}
,"equation":{"interestrate":1}
,"result":{"payment":1}
,"*periods":{"cousin":1}
,"cousin":{"borrowed":1}
,"borrowed":{"$2,000":1}
,"$2,000":{"offering":1}
,"offering":{"pay":1}
,"back":{"$500":1}
,"$500":{"year":1}
,"year":{"years":1}
,"years":{"total":1,"if":1}
,"total":{"$2,500":1}
,"$2,500":{"end":1}
,"end":{"years":1}
,"if":{"inflation":1}
,"inflation":{"percent":1}
,"percent":{"annually":1}
,"annually":{"entry":1}
,"entry":{"find":1}
,"find":{"payments":1}
,"worth":{"pv":1}
,"500":{".05;5":1}
,".05;5":{"returns":1}
}
;Search.control.loadWordPairs(pairs);
