var pairs =
{
"onverting":{"data":1}
,"data":{"file":1,"creates":1,"standard":1,"existing":1,"filemaker":1,"import":1,"dialog":1,"you\u2019re":1,"backward":1,"each":1,"if":1,"source":1,"imported":1,"new":1}
,"file":{"new":1,"convert":1,"application":1,"source":1,"mporting":1,"type":1,"formats":1,"menu":1,"choose":1,"filemaker":1,"dialog":1,"if":1,"lick":1,"save":1,"target":1,"you\u2019re":1,"partial":1}
,"new":{"filemaker":1,"double-click":1,"file":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1,"comma-separated":1,"excel":1}
,"advanced":{"file":1,"ile":1,"mports":1,"save":1,"upports":1,"choose":1,"application":1,"creates":1,"setti":1}
,"convert":{"data":1,"two":1,"field":1,"excel":1,"all":1,"ilemaker":1,"use":1,"hoose":1,"file":1,"if":1}
,"application":{"new":1,"application":1,"importing":1,"icon":1}
,"ile":{"filemaker":1,"converted":1,"contain":1}
,"mports":{"data":1}
,"creates":{"new":1,"file":1}
,"converted":{"ile":1,"field":1,"data":1}
,"contain":{"data":1}
,"source":{"convert":1,"application":1,"data":1,"mapping":1,"file":1,"automate":1}
,"two":{"layouts":1}
,"layouts":{"displaying":1}
,"displaying":{"data":1}
,"standard":{"form":1}
,"form":{"layout":1}
,"layout":{"list":1,"converted":1}
,"list":{"view":1,"current":1}
,"view":{"layout":1}
,"field":{"names":1,"types":1,"source":1,"delimiter":1}
,"names":{"if":1,"generic":1,"convert":1,"column":1,"appears":1,"subsequent":1,"source":1}
,"if":{"file":1,"locate":1,"you\u2019re":1,"record":1,"step":1,"routinely":1}
,"generic":{"f1":1}
,"f1":{"f2":1}
,"f2":{"f3":1}
,"f3":{"field":1}
,"excel":{"filemaker":1,"odbc":1,"spreadsheet":1,"data":1}
,"comma-separated":{"values":1}
,"values":{"custom-separated":1,"dbf":1}
,"custom-separated":{"values":1}
,"dbf":{"merge":1,"xml":1}
,"merge":{"odbc":1}
,"odbc":{"xml":1,"dbf":1}
,"xml":{"formats":1}
,"formats":{"converted":1,"importing":1,"filemaker":1}
,"types":{"text":1,"convert":1}
,"text":{"number":1,"fields":1}
,"number":{"date":1}
,"date":{"if":1}
,"all":{"fields":1}
,"fields":{"text":1,"field":1,"list":1,"during":1}
,"ilemaker":{"pro":1}
,"importing":{"data":1,"field":1,"dialog":1,"stop":1}
,"existing":{"file":1}
,"mporting":{"data":1}
,"save":{"data":1,"ialog":1,"convert":1}
,"import":{"file":1,"target":1,"data":1,"options":1,"action":1,"10":1,"process":1,"read-only":1}
,"type":{"filemaker":1,"windows":1,"file":1,"name":1}
,"upports":{"supported":1}
,"supported":{"import\u002Fexport":1}
,"import\u002Fexport":{"file":1}
,"choose":{"file":1,"type":1,"worksheet":1,"location":1,"use":1,"import":1,"character":1}
,"menu":{"create":1,"open":1}
,"create":{"new":1}
,"double-click":{"convert":1}
,"use":{"methods":1,"field":1}
,"methods":{"open":1}
,"open":{"data":1,"continue":1,"file":1,"if":1}
,"continue":{"next":1}
,"next":{"step":1}
,"step":{"dr":1,"open":1,"etting":1}
,"dr":{"ag":1}
,"ag":{"data":1}
,"icon":{"skip":1}
,"skip":{"step":1}
,"dialog":{"box":1}
,"box":{"files":1,"appears":1,"type":1,"if":1,"progress":1}
,"files":{"type":1}
,"windows":{"show":1}
,"show":{"macos":1}
,"macos":{"choose":1}
,"locate":{"file":1}
,"hoose":{"file":1}
,"lick":{"open":1}
,"you\u2019re":{"converting":1,"importing":1}
,"converting":{"excel":1,"large":1}
,"spreadsheet":{"excel":1}
,"appears":{"choose":1}
,"worksheet":{"named":1}
,"named":{"range":1}
,"range":{"workbook":1}
,"workbook":{"file":1}
,"ialog":{"box":1}
,"name":{"new":1,"table":1}
,"location":{"save":1}
,"record":{"source":1,"field":1}
,"column":{"headings":1,"each":1}
,"headings":{"data":1}
,"backward":{"arrow":1}
,"arrow":{"forward":1,"record":1}
,"forward":{"arrow":1}
,"subsequent":{"records":1}
,"records":{"import":1}
,"target":{"field":1,"name":1}
,"mapping":{"column":1,"choose":1,"fields":1}
,"each":{"pair":1,"field":1}
,"pair":{"fields":1}
,"current":{"mapping":1}
,"table":{"import":1}
,"options":{"choose":1,"if":1}
,"character":{"set":1}
,"set":{"field":1,"converted":1}
,"delimiter":{"options":1}
,"etting":{"import":1}
,"action":{"mapping":1}
,"during":{"import":1}
,"10":{"convert":1}
,"large":{"importing":1}
,"progress":{"import":1}
,"process":{"stop":1,"by":1}
,"stop":{"importing":1,"filemaker":1}
,"partial":{"set":1}
,"routinely":{"import":1}
,"automate":{"process":1}
,"by":{"setting":1}
,"setting":{"up":1}
,"up":{"recurring":1}
,"recurring":{"imports":1,"import":1}
,"imports":{"data":1,"import":1}
,"imported":{"via":1}
,"via":{"recurring":1}
,"read-only":{"filemaker":1}
,"setti":{"ng":1}
,"ng":{"up":1}
}
;Search.control.loadWordPairs(pairs);
