var pairs =
{
"save":{"copy":1}
,"copy":{"xml":1,"open":1}
,"xml":{"saves":1,"representation":1,"file":1,"documenting":1,"format":1,"[window":1}
,"saves":{"copy":1}
,"open":{"file":1}
,"file":{"xml":1,"destination":1,"path":1,"create":1,"paths":1,"window":1,"save":1,"inventory.xml":1}
,"representation":{"schema":1}
,"schema":{"layouts":1}
,"layouts":{"scripts":1}
,"scripts":{"window":1,"saves":1}
,"window":{"name":1}
,"name":{"specifies":1,"open":1,"inventory":1}
,"specifies":{"window":1}
,"destination":{"file":1}
,"path":{"xml":1}
,"create":{"creating":1}
,"creating":{"file":1,"editing":1}
,"paths":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"18.0":1,"advanced":1}
,"18.0":{"advanced":1}
,"advanced":{"script":1,"versions":1}
,"script":{"step":1,"full":1}
,"step":{"choosing":1,"user":1}
,"choosing":{"tools":1}
,"tools":{"menu":1}
,"menu":{"save":1}
,"documenting":{"database":1}
,"database":{"schemas":1}
,"schemas":{"xml":1}
,"format":{"preview":1}
,"preview":{"gather":1}
,"gather":{"customer":1}
,"customer":{"feedback":1}
,"feedback":{"change":1}
,"change":{"significantly":1}
,"significantly":{"future":1}
,"future":{"filemaker":1}
,"versions":{"intended":1}
,"intended":{"use":1}
,"use":{"production":1}
,"production":{"systems":1}
,"systems":{"perform":1}
,"perform":{"script":1}
,"user":{"script":1}
,"full":{"access":1}
,"access":{"privileges":1}
,"privileges":{"creating":1}
,"editing":{"scripts":1}
,"inventory":{"xml":1,"destination":1}
,"[window":{"name":1}
,"inventory.xml":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
