var pairs =
{
"efining":{"summary":1}
,"summary":{"fields":1,"field":1,"based":1,"calculations":1,"create":1,"calculation":1,"option":1,"type":1,"each":1,"value":1,"values":1}
,"fields":{"use":1,"calculate":1,"associated":1,"summary":1,"tab":1,"type":1,"10":1,"getsummary":1}
,"use":{"summary":1,"new":1}
,"calculate":{"values":1,"population":1,"fraction":1,"single":1,"summary":1,"value":1}
,"values":{"subtotals":1,"included":1,"field":1,"value":1,"etting":1}
,"subtotals":{"averages":1}
,"averages":{"grand":1}
,"grand":{"totals":1,"total":1}
,"totals":{"across":1}
,"across":{"multiple":1}
,"multiple":{"records":1}
,"records":{"summary":1,"value":1,"found":1,"sorted":1,"currently":1,"group":1,"if":1,"by":1,"contain":1,"restart":1}
,"field":{"display":1,"change":1,"layout":1,"reflects":1,"non-blank":1,"name":1,"naming":1,"dialog":1,"group":1,"found":1,"average":1,"count":1,"if":1,"100":1,"maximum":1,"standard":1,"each":1,"fraction":1,"total":1,"find":1,"select":1,"sort":1,"list":1,"weight":1,"based":1,"summarizing":1,"summarize":1,"ndividually":1,"repeating":1,"subtotaled":1,"calculate":1,"manually":1}
,"display":{"grand":1,"individual":1,"repeating":1}
,"total":{"all":1,"calculating":1,"values":1,"sales":1,"running":1,"show":1,"current":1,"each":1,"subtotaled":1,"based":1,"group":1}
,"all":{"sales":1,"records":1,"values":1,"previous":1,"repetitions":1}
,"sales":{"month":1,"attributed":1}
,"month":{"report":1}
,"report":{"summary":1}
,"associated":{"groups":1}
,"groups":{"records":1}
,"value":{"summary":1,"fields":1,"field":1,"each":1,"all":1,"correctly":1}
,"change":{"depending":1,"value":1,"found":1,"data":1}
,"depending":{"place":1}
,"place":{"field":1}
,"layout":{"records":1,"summarizes":1,"choose":1}
,"found":{"set":1,"records":1}
,"set":{"records":1,"filemaker":1}
,"sorted":{"data":1,"group":1}
,"data":{"summary":1,"by":1,"creating":1}
,"reflects":{"records":1}
,"currently":{"browsed":1}
,"browsed":{"all":1}
,"group":{"found":1,"data":1,"select":1,"by":1,"records":1,"field":1}
,"if":{"change":1,"database":1,"field":1,"applicable":1}
,"based":{"if":1,"value":1,"group":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"recalculates":1}
,"recalculates":{"result":1}
,"result":{"summary":1,"count":1}
,"non-blank":{"values":1}
,"included":{"summary":1}
,"calculations":{"choose":1,"summary":1}
,"choose":{"file":1,"summary":1,"field":1,"summarize":1,"ll":1,"fraction":1}
,"file":{"menu":1}
,"menu":{"manage":1}
,"manage":{"database":1}
,"database":{"fields":1,"table":1}
,"tab":{"if":1}
,"table":{"select":1,"table":1,"list":1}
,"select":{"table":1,"summary":1,"total":1,"restart":1,"field":1}
,"list":{"field":1,"creating":1,"alues":1,"average":1,"appears":1,"standard":1}
,"name":{"type":1,"field":1}
,"type":{"name":1,"select":1,"choose":1}
,"naming":{"fields":1}
,"create":{"options":1,"layout":1}
,"options":{"summary":1}
,"dialog":{"box":1}
,"box":{"choose":1}
,"calculation":{"type":1}
,"by":{"choose":1,"total":1,"population":1,"calculate":1,"group":1}
,"summarize":{"non-blank":1,"repetitions":1}
,"calculating":{"total":1,"average":1,"ratio":1}
,"average":{"calculating":1,"values":1,"weighted":1,"field":1}
,"count":{"counting":1,"100":1,"running":1,"show":1,"current":1,"each":1}
,"counting":{"number":1}
,"number":{"records":1,"earliest":1,"date":1}
,"contain":{"value":1}
,"100":{"values":1,"minimum":1}
,"each":{"record":1,"option":1,"salesperson":1,"sorted":1,"repetition":1}
,"record":{"result":1}
,"minimum":{"finding":1}
,"finding":{"lowest":1,"number":1,"values":1}
,"lowest":{"number":1}
,"earliest":{"date":1}
,"date":{"time":1}
,"time":{"timestamp":1}
,"timestamp":{"field":1}
,"maximum":{"finding":1}
,"standard":{"deviation":1}
,"deviation":{"finding":1,"mean":1,"by":1,"fraction":1,"formula":1,"change":1}
,"option":{"calculates":1,"if":1}
,"calculates":{"standard":1}
,"mean":{"values":1}
,"fraction":{"total":1}
,"ratio":{"value":1}
,"find":{"fraction":1}
,"attributed":{"each":1}
,"salesperson":{"list":1}
,"creating":{"return-delimited":1,"layout":1}
,"return-delimited":{"list":1}
,"alues":{"field":1}
,"applicable":{"summary":1}
,"running":{"total":1,"count":1}
,"show":{"cumulative":1}
,"cumulative":{"total":1,"count":1}
,"current":{"all":1}
,"previous":{"records":1}
,"restart":{"running":1,"summary":1}
,"sort":{"restarted":1,"by":1}
,"restarted":{"field":1}
,"weighted":{"average":1,"normal":1}
,"appears":{"select":1}
,"weight":{"factor":1}
,"factor":{"determine":1,"count":1}
,"determine":{"average":1}
,"population":{"calculate":1,"standard":1}
,"subtotaled":{"field":1,"return":1}
,"summarizing":{"repeating":1}
,"repeating":{"field":1,"fields":1}
,"repetitions":{"choose":1,"field":1}
,"ll":{"calculate":1}
,"single":{"summary":1}
,"ndividually":{"calculate":1}
,"repetition":{"note":1}
,"note":{"format":1}
,"format":{"ummary":1}
,"ummary":{"field":1}
,"individual":{"summary":1}
,"etting":{"up":1}
,"up":{"display":1}
,"10":{"lick":1}
,"lick":{"use":1}
,"new":{"layout\u002Freport":1}
,"layout\u002Freport":{"assistant":1}
,"assistant":{"quickly":1}
,"quickly":{"create":1}
,"summarizes":{"data":1}
,"return":{"browse":1}
,"browse":{"mode":1}
,"mode":{"sort":1}
,"correctly":{"standard":1}
,"formula":{"-1":1}
,"-1":{"weighted":1}
,"normal":{"standard":1}
,"manually":{"copy":1}
,"copy":{"perform":1}
,"perform":{"calculations":1}
,"getsummary":{"function":1}
,"function":{"define":1}
,"define":{"summary":1}
}
;Search.control.loadWordPairs(pairs);
