var pairs =
{
"ser":{"fi":1,"databases":1}
,"fi":{"le":1}
,"le":{"ption":1}
,"ption":{"dialog":1}
,"dialog":{"box":1,"title":1}
,"box":{"dialog":1,"appears":1,"create":1,"custom":1,"add":1,"type":1,"remove":1,"store":1,"allow":1,"if":1,"file":1,"compress":1,"settings":1,"new":1,"storage":1,"unavailable":1}
,"appears":{"ialog":1,"users":1,"custom":1,"field":1}
,"ialog":{"options":1}
,"options":{"script":1,"dialog":1,"choose":1,"select":1}
,"script":{"editing":1,"step":1,"custom":1}
,"editing":{"pane":1}
,"pane":{"insert":1}
,"insert":{"file":1,"container":1,"allows":1,"media":1,"insert":1,"choice":1}
,"file":{"script":1,"dialog":1,"insert":1,"options":1,"types":1,"stored":1,"custom":1,"option":1,"by":1,"field":1,"externally":1,"export":1,"extensions":1,"displays":1,"type":1,"compressed":1,"inserted":1,"selected":1,"content":1,"compress":1,"uncompressed":1,"displayed":1,"unsupported":1,"let":1,"compression":1}
,"step":{"use":1}
,"use":{"dialog":1}
,"create":{"custom":1,"title":1,"filter":1}
,"custom":{"insert":1,"dialog":1,"menu":1}
,"users":{"choose":1,"decide":1,"play":1,"display":1}
,"choose":{"file":1,"filter":1,"calculation":1,"want":1,"allows":1,"option":1,"compression":1,"video":1,"all":1,"insert":1,"content":1,"compress":1}
,"container":{"field":1,"fields":1}
,"field":{"custom":1,"choose":1,"storing":1,"icon":1,"file":1,"content":1,"filemaker":1,"result":1,"let":1,"if":1,"efining":1,"displays":1,"can\u2019t":1,"settings":1,"save":1}
,"title":{"type":1,"calculation":1,"title":1,"appears":1}
,"type":{"name":1,"filter":1,"icon":1,"insert":1,"pdf":1,".pdf":1}
,"name":{"create":1,"filename":1,"extensions":1,"field":1,"remove":1,"select":1,"type":1}
,"calculation":{"localize":1,"edit":1}
,"localize":{"title":1,"filter":1}
,"add":{"edit":1,"filename":1}
,"edit":{"delete":1,"filter":1,"edit":1,"arrow":1}
,"delete":{"filters":1,"storage":1}
,"filters":{"file":1}
,"types":{"custom":1}
,"filter":{"new":1,"dialog":1,"name":1,"list":1,"calculation":1,"choose":1,"edit":1,"delete":1,"show":1}
,"new":{"new":1,"filter":1,"name":1,"arrow":1}
,"filename":{"extensions":1,"displays":1,"file":1}
,"extensions":{"name":1,"fields":1,"entered":1,"create":1,"supported":1,"remove":1,"type":1}
,"fields":{"arrow":1,"change":1,"display":1}
,"arrow":{"button":1}
,"button":{"next":1,"choose":1}
,"next":{"name":1}
,"list":{"name":1}
,"entered":{"name":1}
,"change":{"name":1}
,"remove":{"add":1,"filter":1,".mpg":1}
,"storage":{"options":1,"option":1}
,"want":{"file":1,"supported":1,"files":1}
,"stored":{"let":1,"attachment":1}
,"let":{"user":1}
,"user":{"choose":1}
,"allows":{"users":1,"storing":1,"embedding":1}
,"decide":{"store":1,"custom":1}
,"store":{"file":1,"reference":1}
,"reference":{"file":1,"allows":1,"insert":1,"container":1,"storage":1}
,"option":{"reference":1,"if":1,"let":1,"unavailable":1,"selected":1,"file":1,"custom":1}
,"storing":{"file":1}
,"by":{"reference":1,"filemaker":1}
,"embedding":{"file":1}
,"externally":{"location":1}
,"location":{"manage":1}
,"manage":{"containers":1}
,"containers":{"dialog":1}
,"allow":{"storing":1}
,"display":{"choose":1,"setting":1}
,"supported":{"image":1,"by":1}
,"image":{"files":1}
,"files":{"video":1,"displayed":1,"compressed":1,"container":1,"ilter":1,"insert":1,"all":1,"graphics":1}
,"video":{"audio":1,"extensions":1,"movies":1}
,"audio":{"files":1,"video":1}
,"displayed":{"field":1,"icon":1,"file":1}
,"icon":{"filename":1,"field":1,"appears":1,"displayed":1,"create":1,"custom":1}
,"displays":{"icon":1,"content":1,"file":1}
,"attachment":{"file":1}
,"export":{"choose":1}
,"if":{"want":1,"reference":1,"store":1,"conditions":1,"compressed":1,"file":1,"jpeg":1,"excel":1}
,"compressed":{"include":1,"note":1,"if":1,"it\u2019s":1,"file":1,"displayed":1,"display":1}
,"include":{"file":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"content":1,"recognizes":1,"assesses":1,"inserts":1,"adds":1,"compress":1,"compresses":1}
,"content":{"file":1,"users":1,"displayed":1,"icon":1,"file\u2019s":1,"field":1}
,"play":{"interact":1}
,"interact":{"file":1}
,"recognizes":{"file":1}
,"compression":{"option":1,"choose":1,"setting":1,"if":1}
,"unavailable":{"compression":1}
,"note":{"filemaker":1}
,"assesses":{"compression":1}
,"setting":{"file":1,"setting":1,"icon":1}
,"inserted":{"field":1}
,"result":{"expected":1}
,"expected":{"file":1}
,"selected":{"insert":1,"custom":1}
,"it\u2019s":{"mp3":1}
,"mp3":{"file":1}
,"compress":{"file":1,"option":1,"compresses":1,"if":1,"settings":1,"choose":1}
,"uncompressed":{"file":1}
,"conditions":{"exist":1}
,"exist":{"compress":1,"options":1}
,"compresses":{"file":1}
,"select":{"content":1,"ll":1,"store":1}
,"unsupported":{"extension":1}
,"extension":{"inserted":1}
,"menu":{"container":1,"typical":1}
,"efining":{"custom":1}
,"typical":{"configuration":1}
,"configuration":{"insert":1}
,"settings":{"filemaker":1,"file":1,"can\u2019t":1}
,"inserts":{"files":1}
,"file\u2019s":{"content":1}
,"media":{"filemaker":1,"files":1}
,"adds":{"double-quotation":1}
,"double-quotation":{"marks":1}
,"marks":{"filter":1}
,"ll":{"files":1}
,"ilter":{"edit":1}
,".mpg":{"insert":1}
,"pdf":{"documents":1,"songs":1}
,"documents":{"extensions":1}
,".pdf":{"insert":1}
,"all":{"files":1,"users":1}
,"choice":{"multi":1}
,"multi":{"ser":1}
,"databases":{"ensures":1}
,"ensures":{"all":1}
,"can\u2019t":{"compressed":1,"select":1}
,"jpeg":{"file":1}
,"excel":{"file":1}
,"save":{"run":1}
,"run":{"script":1}
,"show":{"audio":1}
,"movies":{"sound":1}
,"sound":{"music":1}
,"music":{"clips":1}
,"clips":{"multimedia":1}
,"multimedia":{"media":1}
,"graphics":{"pictures":1}
,"pictures":{"photos":1}
,"photos":{"interactive":1}
,"interactive":{"pdf":1}
}
;Search.control.loadWordPairs(pairs);
