var pairs =
{
"create":{"data":1,"creating":1,"folders":1,"new":1}
,"data":{"file":1,"write":1}
,"file":{"creates":1,"open":1,"script":1,"path":1,"create":1,"paths":1,"exists":1,"locked":1,"named":1,"[\u0022":1,"if":1,"can\u2019t":1,"[\u0022$file":1,"automating":1}
,"creates":{"empty":1,"file":1}
,"empty":{"closed":1,"data":1}
,"closed":{"data":1}
,"open":{"open":1,"data":1}
,"script":{"step":1,"displays":1,"[text":1}
,"step":{"add":1,"file":1,"creates":1}
,"add":{"data":1}
,"write":{"data":1}
,"path":{"data":1,"filemaker":1,"can\u2019t":1,"exists":1}
,"creating":{"file":1,"filemaker":1}
,"paths":{"create":1}
,"folders":{"specifies":1,"if":1,"checks":1,"set":1}
,"specifies":{"create":1}
,"new":{"folders":1}
,"if":{"don\u2019t":1,"path":1,"doesn\u2019t":1,"file":1,"[$fileexists":1,"create":1,"[$error":1,"creating":1}
,"don\u2019t":{"exist":1}
,"exist":{"path":1}
,"filemaker":{"pro":1}
,"pro":{"18.0":1,"advanced":1}
,"18.0":{"advanced":1}
,"advanced":{"if":1,"file":1}
,"can\u2019t":{"accessed":1,"created":1}
,"accessed":{"file":1}
,"exists":{"get":1,"script":1,"create":1,"documents":1,"[\u0022$file":1,"exit":1}
,"get":{"lasterror":1,"file":1,"documentspath":1}
,"lasterror":{"returns":1,"if":1,"end":1}
,"returns":{"300":1}
,"300":{"file":1}
,"locked":{"use":1}
,"use":{"get":1}
,"named":{"data.txt":1,"change.log":1}
,"data.txt":{"if":1,"create":1}
,"[\u0022":{"data.txt":1}
,"checks":{"file":1}
,"change.log":{"exists":1,"get":1}
,"documents":{"folder":1}
,"folder":{"if":1}
,"doesn\u2019t":{"creates":1}
,"created":{"script":1,"else":1,"error":1}
,"displays":{"error":1}
,"error":{"code":1,"capture":1}
,"code":{"set":1,"&get":1}
,"set":{"error":1,"variable":1}
,"capture":{"[on":1}
,"[on":{"set":1}
,"variable":{"[$file":1,"[$error":1}
,"[$file":{"value":1,"&\u0022":1}
,"value":{"get":1}
,"documentspath":{"&\u0022":1}
,"&\u0022":{"change.log":1,"exists":1,"created":1}
,"[\u0022$file":{"target":1,"create":1}
,"target":{"$fileexists":1}
,"$fileexists":{"if":1}
,"[$fileexists":{"show":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"dialog":{"[$file":1}
,"exit":{"script":1}
,"[text":{"result":1}
,"result":{"end":1}
,"end":{"if":1}
,"[$error":{"=get":1,"=0":1}
,"=get":{"lasterror":1}
,"=0":{"show":1}
,"else":{"show":1}
,"&get":{"lasterror":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
