var pairs =
{
"get":{"screende":1,"screendepth":1,"screen":1,"color":1}
,"screende":{"pth":1}
,"pth":{"returns":1}
,"returns":{"number":1,"32":1,"16":1,"vga":1,"black-and-white":1}
,"number":{"bits":1,"filemaker":1}
,"bits":{"represent":1}
,"represent":{"color":1}
,"color":{"shade":1,"depth":1}
,"shade":{"gray":1}
,"gray":{"pixel":1,"filemaker":1}
,"pixel":{"main":1}
,"main":{"screen":1}
,"screen":{"get":1,"depth":1}
,"screendepth":{"none":1,"get":1}
,"none":{"number":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"value":1}
,"value":{"represents":1}
,"represents":{"256":1}
,"256":{"equal":1}
,"equal":{"colors":1}
,"colors":{"shades":1,"returns":1}
,"shades":{"gray":1}
,"webdirect":{"function":1}
,"function":{"supported":1}
,"supported":{"returns":1}
,"32":{"returns":1,"display":1,"colors":1}
,"display":{"millions":1,"thousands":1,"returns":1,"get":1}
,"millions":{"32":1}
,"16":{"display":1,"colors":1}
,"thousands":{"16":1}
,"vga":{"display":1}
,"black-and-white":{"display":1}
,"depth":{"get":1}
}
;Search.control.loadWordPairs(pairs);
