var pairs =
{
"design":{"functions":1,"function":1}
,"functions":{"design":1,"return":1,"left":1,"interpret":1}
,"return":{"structure":1,"first":1,"current":1}
,"structure":{"open":1}
,"open":{"database":1,"computer":1}
,"database":{"files":1,"file":1}
,"files":{"determine":1,"filename":1,"open":1}
,"determine":{"names":1}
,"names":{"all":1,"windows":1}
,"all":{"layouts":1,"files":1,"field":1,"fields":1,"layout":1,"named":1,"script":1,"scripts":1,"table":1,"value":1}
,"layouts":{"fields":1,"layoutname":1,"filename":1}
,"fields":{"open":1,"layoutname":1}
,"file":{"esign":1,"creating":1,"filename":1,"function":1}
,"esign":{"function":1}
,"function":{"parameters":1,"privilege":1,"evaluates":1,"returns":1}
,"parameters":{"filenames":1}
,"filenames":{"ustomer":1}
,"ustomer":{"literal":1}
,"literal":{"text":1}
,"text":{"jack":1,"number":1}
,"jack":{"layouts":1}
,"layoutname":{"functions":1,"fieldnames":1,"filename":1}
,"left":{"text":1}
,"number":{"filemaker":1,"orientation":1,"fieldname":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"limits":1}
,"limits":{"returned":1}
,"returned":{"by":1}
,"by":{"design":1}
,"privilege":{"set":1,"sets":1}
,"set":{"function":1}
,"evaluates":{"database":1}
,"creating":{"editing":1}
,"editing":{"privilege":1}
,"sets":{"granting":1}
,"granting":{"access":1}
,"access":{"database":1}
,"filename":{"parameter":1,"filename":1,"ontains":1,"extension":1,"functions":1,"layoutname":1,"fieldrepetitions":1,"fieldtype":1,"layoutids":1,"layoutnames":1,"layoutobjectnames":1,"relationinfo":1,"scriptnames":1,"tableids":1,"tablenames":1,"valuelistids":1,"valuelistitems":1,"windownames":1}
,"parameter":{"design":1,"functions":1}
,"first":{"file":1}
,"ontains":{"period":1}
,"period":{"include":1,"filename":1}
,"include":{"filename":1}
,"extension":{"parameter":1,"lead":1}
,"interpret":{"period":1}
,"lead":{"unexpected":1}
,"unexpected":{"if":1}
,"if":{"filename":1}
,"current":{"file":1}
,"returns":{"databasenames":1}
,"databasenames":{"list":1}
,"list":{"names":1,"all":1,"values":1,"ids":1,"valuelistnames":1}
,"computer":{"fieldbounds":1}
,"fieldbounds":{"location":1}
,"location":{"points":1}
,"points":{"each":1}
,"each":{"field":1,"relationship":1}
,"field":{"boundary":1,"ids":1,"formatted":1,"formatting":1}
,"boundary":{"nd":1}
,"nd":{"field\u2019s":1}
,"field\u2019s":{"otation":1,"comment":1}
,"otation":{"degrees":1}
,"degrees":{"fieldcomment":1}
,"fieldcomment":{"field\u2019s":1}
,"comment":{"fieldids":1}
,"fieldids":{"list":1}
,"ids":{"filename":1}
,"fieldnames":{"list":1}
,"fieldrepetitions":{"number":1}
,"orientation":{"repetitions":1}
,"repetitions":{"repeating":1}
,"repeating":{"field":1}
,"formatted":{"layout":1}
,"layout":{"fieldstyle":1,"ids":1}
,"fieldstyle":{"field":1}
,"formatting":{"applied":1}
,"applied":{"fieldname":1}
,"fieldname":{"layoutname":1,"getnextserialvalue":1,"filename":1}
,"fieldtype":{"fieldname":1}
,"getnextserialvalue":{"next":1}
,"next":{"serial":1}
,"serial":{"number":1}
,"layoutids":{"list":1}
,"layoutnames":{"list":1}
,"layoutobjectnames":{"list":1}
,"named":{"objects":1}
,"objects":{"layoutname":1}
,"relationinfo":{"list":1}
,"values":{"each":1,"alue":1}
,"relationship":{"related":1}
,"related":{"tablename":1}
,"tablename":{"scriptids":1}
,"scriptids":{"list":1}
,"script":{"ids":1}
,"scriptnames":{"list":1}
,"scripts":{"filename":1}
,"tableids":{"list":1}
,"table":{"occurrence":1,"occurrences":1}
,"occurrence":{"ids":1}
,"tablenames":{"list":1}
,"occurrences":{"relationships":1}
,"relationships":{"graph":1}
,"graph":{"filename":1}
,"valuelistids":{"list":1}
,"value":{"list":1,"lists":1}
,"valuelistitems":{"list":1}
,"alue":{"list":1}
,"valuelistnames":{"list":1}
,"lists":{"filename":1}
,"windownames":{"list":1}
,"windows":{"currently":1}
,"currently":{"open":1}
}
;Search.control.loadWordPairs(pairs);
