var pairs =
{
"accounts":{"script":1,"accounts":1,"delete":1,"reset":1,"log":1,"created":1}
,"script":{"steps":1,"script":1,"pane":1}
,"steps":{"accounts":1,"allow":1,"add":1,"granted":1,"enable":1,"right-click":1,"diting":1}
,"allow":{"create":1}
,"create":{"manage":1}
,"manage":{"user":1}
,"user":{"accounts":1}
,"add":{"accounts":1}
,"delete":{"accounts":1}
,"reset":{"account":1}
,"account":{"passwords":1,"password":1,"script":1}
,"passwords":{"change":1,"enable":1}
,"change":{"passwords":1}
,"enable":{"accounts":1,"users":1}
,"log":{"file":1}
,"file":{"account":1}
,"password":{"accounts":1}
,"created":{"script":1,"manually":1}
,"granted":{"full":1}
,"full":{"access":1}
,"access":{"privileges":1,"privilege":1}
,"privileges":{"accounts":1,"perform":1,"access":1,"script":1}
,"manually":{"users":1}
,"users":{"assigned":1,"less":1}
,"assigned":{"full":1}
,"privilege":{"set":1}
,"set":{"execute":1}
,"execute":{"account":1}
,"less":{"full":1}
,"perform":{"account":1}
,"right-click":{"current":1}
,"current":{"script":1}
,"pane":{"choose":1}
,"choose":{"grant":1}
,"grant":{"full":1}
,"diting":{"scripts":1}
,"scripts":{"privileges":1}
}
;Search.control.loadWordPairs(pairs);
