var pairs =
{
"getasurlencoded":{"returns":1,"text":1,"san":1,"fran\u00E7ais":1}
,"returns":{"text":1,"getasurlencoded":1,"san":1,"fran":1}
,"text":{"url":1,"text":1,"-any":1,"expression":1,"field":1,"filemaker":1,"all":1}
,"url":{"uniform":1,"getasurlencoded":1,"encoding":1}
,"uniform":{"resource":1}
,"resource":{"locator":1}
,"locator":{"encoding":1}
,"encoding":{"use":1,"getasurlencoded":1}
,"use":{"url":1}
,"-any":{"text":1}
,"expression":{"text":1}
,"field":{"text":1}
,"filemaker":{"pro":1}
,"pro":{"8.5":1}
,"8.5":{"function":1}
,"function":{"removes":1}
,"removes":{"all":1}
,"all":{"styles":1,"characters":1}
,"styles":{"text":1}
,"characters":{"first":1,"letters":1}
,"first":{"converted":1}
,"converted":{"utf-8":1,"hh":1}
,"utf-8":{"format":1}
,"format":{"characters":1,"percent":1}
,"letters":{"digits":1}
,"digits":{"digits":1,"upper":1}
,"upper":{"ascii":1}
,"ascii":{"range":1}
,"range":{"converted":1}
,"hh":{"format":1}
,"percent":{"sign":1}
,"sign":{"by":1}
,"by":{"character\u2019s":1}
,"character\u2019s":{"hexadecimal":1}
,"hexadecimal":{"value":1}
,"value":{"www.w3.org":1}
,"www.w3.org":{"url":1}
,"san":{"francisco":1,"20francisco":1}
,"francisco":{"returns":1}
,"20francisco":{"getasurlencoded":1}
,"fran\u00E7ais":{"returns":1}
,"fran":{"c3":1}
,"c3":{"a7ais":1}
}
;Search.control.loadWordPairs(pairs);
