var pairs =
{
"etting":{"up":1}
,"up":{"container":1,"storage":1,"external":1}
,"container":{"fields":1,"field":1,"data":1,"select":1,"files":1}
,"fields":{"store":1,"database":1,"tab":1,"manually":1,"managed":1,"set":1}
,"store":{"data":1,"container":1}
,"data":{"externally":1,"by":1,"that\u2019s":1,"directory":1,"choose":1,"stored":1,"readable":1,"transferring":1,"if":1}
,"externally":{"create":1,"data":1,"by":1,"individual":1,"folders":1,"relative":1}
,"create":{"container":1}
,"field":{"data":1,"set":1,"store":1,"define":1,"name":1,"dialog":1,"open":1}
,"by":{"default":1,"filemaker":1}
,"default":{"embedded":1,"encrypted":1,"encrypt":1,"path":1,"open":1}
,"embedded":{"field":1,"stored":1,"container":1}
,"set":{"up":1}
,"that\u2019s":{"stored":1,"embedded":1}
,"stored":{"externally":1,"choose":1,"default":1,"duplicate":1}
,"encrypted":{"secure":1,"files":1}
,"secure":{"storage":1,"base":1}
,"storage":{"read":1,"option":1,"options":1,"tab":1,"container":1,"default":1,"filemaker":1,"allow":1,"path":1,"if":1,"candidates\u002F\u0022":1}
,"read":{"by":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"application":1,"manages":1,"secure":1,"creates":1,"appends":1}
,"application":{"filemaker":1}
,"manages":{"encrypted":1}
,"files":{"automatically":1,"native":1,"across":1,"stay":1,"stored":1}
,"automatically":{"use":1}
,"use":{"open":1}
,"open":{"storage":1}
,"option":{"removes":1}
,"removes":{"encryption":1}
,"encryption":{"files":1}
,"native":{"formats":1}
,"formats":{"set":1}
,"options":{"embedded":1,"double-click":1,"field":1}
,"individual":{"container":1}
,"database":{"store":1,"fields":1,"table":1,"base":1,"filename":1,"expect":1}
,"folders":{"file":1}
,"file":{"system":1,"menu":1,"named":1}
,"system":{"choose":1}
,"choose":{"file":1,"base":1,"want":1,"secure":1}
,"menu":{"manage":1}
,"manage":{"database":1}
,"tab":{"if":1,"container":1}
,"if":{"database":1,"calculation":1,"filename":1,"design":1}
,"table":{"select":1,"table":1,"list":1,"database":1,"default":1,"name":1}
,"select":{"table":1,"existing":1,"store":1}
,"list":{"select":1,"store":1}
,"existing":{"field":1,"data":1}
,"define":{"new":1}
,"new":{"options":1,"subdirectories":1}
,"double-click":{"field":1}
,"name":{"options":1,"properties":1,"move":1}
,"dialog":{"box":1}
,"box":{"storage":1}
,"relative":{"choose":1,"base":1}
,"base":{"directory":1}
,"directory":{"list":1,"managing":1,"randomly":1,"format":1,"path":1,"[database":1}
,"managing":{"external":1}
,"external":{"storage":1}
,"want":{"container":1}
,"encrypt":{"data":1}
,"readable":{"by":1}
,"creates":{"subdirectory":1,"new":1}
,"subdirectory":{"named":1}
,"named":{"secure":1,"resume.doc":1}
,"randomly":{"distributes":1}
,"distributes":{"files":1}
,"across":{"subdirectories":1}
,"subdirectories":{"creates":1,"open":1}
,"allow":{"container":1}
,"stay":{"original":1}
,"original":{"format":1}
,"format":{"control":1,"table\u002Ffield":1}
,"control":{"files":1}
,"path":{"relative":1,"calculation":1,"table":1,"name":1,"properties\u002Fphoto":1}
,"table\u002Ffield":{"type":1}
,"type":{"path":1}
,"calculation":{"10":1,"container":1,"unique":1,"reduce":1,"open":1}
,"10":{"if":1}
,"properties":{"base":1,"open":1}
,"[database":{"location]\u002Fproperties":1}
,"location]\u002Fproperties":{"database":1}
,"filename":{"properties":1,"calculation":1,"sequential":1}
,"properties\u002Fphoto":{"table":1}
,"move":{"existing":1}
,"manually":{"transfer":1}
,"transfer":{"data":1}
,"transferring":{"container":1}
,"unique":{"filemaker":1}
,"appends":{"duplicate":1}
,"duplicate":{"filename":1,"filenames":1}
,"sequential":{"number":1}
,"number":{"invoice_1.txt":1,"stored":1}
,"invoice_1.txt":{"design":1}
,"design":{"calculation":1,"candidates":1}
,"reduce":{"number":1}
,"filenames":{"if":1}
,"candidates":{"recruitment":1}
,"recruitment":{"database":1}
,"expect":{"records":1}
,"records":{"contain":1}
,"contain":{"file":1}
,"resume.doc":{"calculation":1}
,"candidates\u002F\u0022":{"&candidateid":1}
,"&candidateid":{"remote":1}
,"remote":{"container":1}
,"managed":{"container":1}
}
;Search.control.loadWordPairs(pairs);
