var pairs =
{
"pecify":{"subtotals":1}
,"subtotals":{"new":1,"grand":1,"averages":1,"remove":1}
,"new":{"layout\u002Freport":1,"summary":1}
,"layout\u002Freport":{"assistant":1}
,"assistant":{"if":1,"define":1,"modify":1,"order":1,"subtotal":1}
,"if":{"selected":1,"subtotaling":1,"subtotal":1,"choose":1,"define":1}
,"selected":{"include":1,"organize":1}
,"include":{"su":1,"subtotals":1}
,"su":{"btotals":1,"mmary":1}
,"btotals":{"include":1}
,"grand":{"totals":1}
,"totals":{"anel":1}
,"anel":{"use":1}
,"use":{"panel":1}
,"panel":{"efine":1,"summary":1,"subtotal":1,"defining":1}
,"efine":{"note":1}
,"note":{"filemaker":1,"full":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"term":1,"creates":1}
,"term":{"subsummary":1}
,"subsummary":{"include":1,"select":1,"definition":1,"list":1,"remove":1,"panel":1,"part":1,"break":1,"fields":1}
,"averages":{"counts":1}
,"counts":{"summary":1}
,"summary":{"data":1,"field":1,"fields":1}
,"data":{"subset":1,"by":1}
,"subset":{"records":1}
,"records":{"categories":1,"defined":1,"by":1}
,"categories":{"records":1}
,"defined":{"organize":1,"summary":1}
,"organize":{"records":1}
,"by":{"category":1,"choose":1,"region":1}
,"category":{"panel":1,"summarize":1}
,"field":{"hoose":1,"list":1,"fields":1,"type":1,"current":1,"dialog":1,"table":1,"if":1,"summary":1,"leading":1,"placement":1}
,"hoose":{"summary":1}
,"list":{"define":1,"se":1,"selected":1,"change":1}
,"define":{"new":1,"summary":1,"ummary":1,"subsummary":1}
,"fields":{"defined":1,"note":1,"category":1,"list":1,"assistant":1,"subsummary":1,"finish":1}
,"type":{"list":1}
,"current":{"table":1}
,"table":{"add":1,"choose":1}
,"add":{"options":1,"subtotal":1}
,"options":{"su":1}
,"mmary":{"field":1}
,"dialog":{"box":1}
,"box":{"new":1}
,"choose":{"manage":1,"break":1,"region":1,"option":1,"record":1}
,"manage":{"database":1}
,"database":{"list":1}
,"se":{"defining":1,"hanging":1}
,"defining":{"summary":1,"leading":1,"trailing":1}
,"full":{"access":1}
,"access":{"privileges":1}
,"privileges":{"define":1}
,"ummary":{"fields":1}
,"summarize":{"by":1}
,"break":{"field":1}
,"subtotaling":{"sales":1}
,"sales":{"data":1}
,"region":{"choose":1,"field":1}
,"subtotal":{"placement":1,"remove":1,"double-click":1}
,"placement":{"choose":1,"if":1,"order":1}
,"option":{"lick":1}
,"lick":{"add":1}
,"remove":{"subsummary":1,"subtotal":1}
,"select":{"subsummary":1}
,"definition":{"subtotals":1,"redefine":1}
,"double-click":{"subsummary":1}
,"change":{"subsummary":1,"order":1}
,"redefine":{"define":1}
,"leading":{"subsummary":1}
,"part":{"if":1,"finish":1,"fo":1,"hold":1,"break":1,"report":1}
,"record":{"group":1}
,"group":{"you\u2019re":1,"filemaker":1}
,"you\u2019re":{"defining":1}
,"trailing":{"subsummary":1}
,"finish":{"assistant":1}
,"modify":{"characteristics":1}
,"characteristics":{"pagination":1}
,"pagination":{"page":1}
,"page":{"numbering":1}
,"numbering":{"se":1}
,"hanging":{"layout":1}
,"layout":{"part":1}
,"fo":{"subtotal":1}
,"creates":{"ot":1}
,"ot":{"trailing":1}
,"hold":{"break":1}
,"order":{"define":1,"summary":1}
,"report":{"change":1}
}
;Search.control.loadWordPairs(pairs);
