var pairs =
{
"get":{"usercou":1,"usercount":1,"user":1,"client":1}
,"usercou":{"nt":1}
,"nt":{"returns":1}
,"returns":{"number":1,"if":1,"clients":1}
,"number":{"clients":1,"filemaker":1}
,"clients":{"currently":1,"if":1,"accessing":1}
,"currently":{"accessing":1}
,"accessing":{"file":1,"database":1}
,"file":{"get":1,"via":1}
,"usercount":{"none":1,"get":1}
,"none":{"number":1}
,"filemaker":{"pro":1,"network":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"returns":1}
,"if":{"filemaker":1,"context":1}
,"network":{"sharing":1}
,"sharing":{"number":1,"function":1}
,"function":{"count":1,"evaluated":1}
,"count":{"clients":1,"get":1}
,"database":{"file":1}
,"via":{"odbc":1}
,"odbc":{"jdbc":1}
,"jdbc":{"if":1}
,"context":{"current":1,"evaluated":1}
,"current":{"calculation":1,"window":1}
,"calculation":{"function":1}
,"evaluated":{"based":1}
,"based":{"context":1}
,"window":{"returns":1}
,"user":{"count":1}
,"client":{"count":1}
}
;Search.control.loadWordPairs(pairs);
