var pairs =
{
"factorial":{"returns":1,"number":1,"10;3":1}
,"returns":{"factorial":1,"=3":1,"720":1}
,"number":{"stopping":1,"numberoffactors":1,"-numeric":1,"represents":1,"filemaker":1}
,"stopping":{"optional":1}
,"optional":{"numberoffactors":1,"number":1}
,"numberoffactors":{"factorial":1,"number":1,"-any":1}
,"-numeric":{"expression":1}
,"expression":{"field":1}
,"field":{"positive":1,"number":1}
,"positive":{"integer":1}
,"integer":{"numberoffactors":1}
,"-any":{"numeric":1}
,"numeric":{"expression":1}
,"represents":{"factors":1}
,"factors":{"include":1}
,"include":{"multiplication":1}
,"multiplication":{"parameters":1}
,"parameters":{"braces":1}
,"braces":{"optional":1}
,"filemaker":{"pro":1}
,"pro":{"7.0":1}
,"7.0":{"function":1}
,"function":{"statistics":1}
,"statistics":{"combinatorics":1}
,"combinatorics":{"=number":1}
,"=number":{"=numberoffactors":1}
,"=numberoffactors":{"equation":1}
,"equation":{"equation":1,"factorial":1}
,"=3":{"*2":1}
,"*2":{"*1":1}
,"*1":{"factorial":1}
,"10;3":{"returns":1}
,"720":{"=10":1}
,"=10":{"*9":1}
,"*9":{"*8":1}
}
;Search.control.loadWordPairs(pairs);
