var pairs =
{
"sh":{"ari":1}
,"ari":{"ng":1}
,"ng":{"filemaker":1}
,"filemaker":{"pro":1,"database":1,"odbc":1,"sql":1}
,"pro":{"advanced":1}
,"advanced":{"data":1,"serve":1,"database":1,"stops":1}
,"data":{"via":1,"source":1,"inadvertently":1,"review":1,"errors":1,"transactions":1}
,"via":{"odbc":1,"odbc\u002Fjdbc":1}
,"odbc":{"jdbc":1,"-and":1,"client":1}
,"jdbc":{"filemaker":1,"-compliant":1,"guide":1,"sql":1}
,"serve":{"data":1}
,"source":{"sharing":1,"create":1}
,"sharing":{"database":1,"status":1,"enable":1,"select":1,"filemaker":1}
,"database":{"files":1,"file":1,"odbc\u002Fjdbc":1,"want":1}
,"files":{"odbc":1,"minimum":1,"enable":1,"hoose":1,"intend":1}
,"-and":{"jdbc":1}
,"-compliant":{"applications":1}
,"applications":{"prevent":1,"update":1}
,"prevent":{"data":1}
,"inadvertently":{"modified":1}
,"modified":{"deleted":1}
,"deleted":{"applications":1}
,"update":{"delete":1}
,"delete":{"unprotected":1}
,"unprotected":{"shared":1}
,"shared":{"data":1,"database":1}
,"review":{"privilege":1}
,"privilege":{"sets":1,"choose":1,"set":1,"access":1}
,"sets":{"you\u2019ve":1,"extended":1,"select":1}
,"you\u2019ve":{"assigned":1}
,"assigned":{"accounts":1,"selected":1}
,"accounts":{"access":1,"passwords":1,"privilege":1,"assigned":1}
,"access":{"shared":1,"privileges":1,"file":1,"ers":1,"database":1,"via":1,"separate":1,"instructions":1}
,"minimum":{"level":1}
,"level":{"protection":1}
,"protection":{"database":1}
,"file":{"accounts":1,"menu":1,"choose":1,"require":1,"options":1,"open":1,"want":1}
,"passwords":{"open":1}
,"open":{"database":1,"account":1,"files":1,"set":1}
,"enable":{"change":1,"odbc\u002Fjdbc":1}
,"change":{"file\u2019s":1}
,"file\u2019s":{"sharing":1}
,"status":{"open":1}
,"account":{"manage":1,"users":1,"name":1}
,"manage":{"extended":1,"security":1}
,"extended":{"privileges":1,"privilege":1}
,"privileges":{"access":1,"accounts":1}
,"choose":{"file":1,"all":1}
,"menu":{"sharing":1}
,"odbc\u002Fjdbc":{"odbc\u002Fjdbc":1,"sharing":1,"users":1,"repeat":1}
,"select":{"filename":1,"privileges":1}
,"filename":{"share":1}
,"share":{"list":1,"via":1,"databases":1}
,"list":{"open":1}
,"hoose":{"users":1}
,"users":{"access":1,"provide":1,"by":1,"nter":1,"default":1,"data":1}
,"all":{"users":1}
,"provide":{"access":1}
,"ers":{"account":1,"accounts":1}
,"by":{"privilege":1}
,"set":{"provide":1,"up":1}
,"selected":{"privilege":1}
,"require":{"fmxdbc":1}
,"fmxdbc":{"extended":1}
,"nter":{"account":1}
,"name":{"password":1}
,"password":{"defined":1}
,"defined":{"manage":1}
,"security":{"dialog":1}
,"dialog":{"box":1}
,"box":{"depending":1,"etting":1}
,"depending":{"setting":1}
,"setting":{"file":1,"pr":1}
,"options":{"dialog":1,"users":1}
,"etting":{"file":1}
,"default":{"setting":1}
,"pr":{"event":1}
,"event":{"ny":1}
,"ny":{"user":1}
,"user":{"accessing":1}
,"accessing":{"database":1}
,"repeat":{"steps":1}
,"steps":{"-5":1}
,"-5":{"each":1}
,"each":{"database":1,"filemaker":1,"individual":1}
,"want":{"publish":1,"access":1}
,"publish":{"each":1}
,"up":{"access":1}
,"separate":{"data":1}
,"create":{"dsn":1}
,"dsn":{"each":1}
,"individual":{"filemaker":1}
,"instructions":{"installing":1}
,"installing":{"filemaker":1}
,"client":{"drivers":1,"application":1}
,"drivers":{"filemaker":1}
,"guide":{"details":1,"note":1}
,"details":{"supported":1}
,"supported":{"sql":1}
,"sql":{"statements":1,"reference":1,"query":1}
,"statements":{"expressions":1}
,"expressions":{"catalog":1}
,"catalog":{"functions":1}
,"functions":{"filemaker":1}
,"reference":{"filemaker":1}
,"note":{"avoid":1}
,"avoid":{"spaces":1}
,"spaces":{"field":1,"column":1}
,"field":{"names":1}
,"names":{"database":1,"disable":1}
,"intend":{"share":1}
,"query":{"tools":1}
,"tools":{"don\u2019t":1}
,"don\u2019t":{"allow":1}
,"allow":{"spaces":1}
,"column":{"names":1}
,"disable":{"odbc\u002Fjdbc":1}
,"stops":{"serving":1}
,"serving":{"data":1}
,"errors":{"reported":1}
,"reported":{"client":1}
,"application":{"notify":1}
,"notify":{"users":1}
,"transactions":{"completed":1}
,"completed":{"share":1}
,"databases":{"odbc":1}
}
;Search.control.loadWordPairs(pairs);
