var pairs =
{
"setting":{"up":1}
,"up":{"form":1}
,"form":{"list":1,"view":1}
,"list":{"table":1,"view":1}
,"table":{"views":1,"change":1,"view":1,"propertie":1,"grid":1,"new":1}
,"views":{"layout":1,"each":1,"change":1,"tab":1,"select":1,"modes":1}
,"layout":{"filemaker":1,"form":1,"mode":1,"want":1,"pop-up":1,"setup":1,"bar":1,"parts":1,"they\u2019re":1,"default":1,"if":1,"part":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"views":1,"tab":1}
,"each":{"layout":1}
,"change":{"views":1,"records":1}
,"records":{"display":1,"form":1,"current":1}
,"display":{"print":1,"select":1,"top":1,"field":1,"first":1}
,"print":{"layout":1}
,"mode":{"choose":1,"find":1,"select":1}
,"choose":{"layout":1,"color":1,"unit":1,"view":1,"command":1,"layouts":1}
,"want":{"layout":1}
,"pop-up":{"menu":1}
,"menu":{"layout":1,"item":1,"command":1}
,"setup":{"layout":1,"button":1,"dialog":1,"general":1}
,"button":{"layout":1}
,"bar":{"layout":1,"left":1}
,"dialog":{"box":1}
,"box":{"views":1,"filemaker":1,"reordering":1,"select":1}
,"tab":{"select":1,"order":1,"layout":1}
,"select":{"views":1,"view":1,"horizontal":1,"parts":1,"include":1,"resizable":1,"reorderable":1,"use":1,"show":1}
,"view":{"menu":1,"view":1,"form":1,"list":1,"table":1,"options":1,"olumn":1,"choose":1,"display":1,"data":1,"include":1,"set":1,"properties":1,"reorder":1,"displayed":1,"current":1}
,"item":{"enabled":1}
,"enabled":{"browse":1}
,"browse":{"find":1,"mode":1}
,"find":{"modes":1,"mode":1}
,"modes":{"form":1}
,"propertie":{"pecify":1}
,"pecify":{"view":1}
,"options":{"table":1}
,"grid":{"settings":1,"style":1,"lines":1}
,"settings":{"select":1,"atter":1}
,"horizontal":{"vertical":1}
,"vertical":{"choose":1,"bar":1}
,"color":{"grid":1}
,"style":{"grid":1}
,"lines":{"layout":1}
,"parts":{"display":1}
,"top":{"navigation":1}
,"navigation":{"header":1,"settings":1}
,"header":{"footer":1,"choosing":1}
,"footer":{"bottom":1}
,"bottom":{"navigation":1}
,"atter":{"if":1}
,"if":{"defined":1,"include":1,"resizable":1,"reorderable":1}
,"defined":{"arts":1,"fields":1}
,"arts":{"layout":1}
,"they\u2019re":{"nly":1}
,"nly":{"table":1}
,"olumn":{"headers":1}
,"headers":{"displayed":1,"display":1,"selected":1}
,"displayed":{"nd":1,"fill":1}
,"nd":{"behave":1}
,"behave":{"select":1}
,"include":{"column":1}
,"column":{"headers":1,"widths":1,"boundaries":1,"heading":1,"header":1,"width":1}
,"field":{"names":1}
,"names":{"allow":1}
,"allow":{"users":1}
,"users":{"resize":1,"reorder":1,"right-click":1}
,"resize":{"column":1,"columns":1}
,"widths":{"by":1}
,"by":{"dragging":1,"right-clicking":1,"default":1}
,"dragging":{"column":1,"browse":1}
,"boundaries":{"browse":1}
,"resizable":{"columns":1}
,"columns":{"allow":1,"by":1,"custom":1,"cleared":1,"table":1,"if":1,"selected":1,"viewing":1}
,"reorder":{"columns":1}
,"reorderable":{"columns":1}
,"custom":{"row":1,"height":1}
,"row":{"height":1}
,"height":{"all":1,"select":1,"choose":1,"adjusted":1}
,"all":{"rows":1}
,"rows":{"height":1}
,"use":{"custom":1}
,"unit":{"measure":1}
,"measure":{"type":1}
,"type":{"value":1}
,"value":{"option":1}
,"option":{"cleared":1}
,"cleared":{"row":1,"table":1}
,"adjusted":{"accommodate":1}
,"accommodate":{"largest":1}
,"largest":{"font":1}
,"font":{"size":1}
,"size":{"defined":1}
,"fields":{"layout":1,"hide":1,"create":1}
,"default":{"view":1,"order":1,"current":1}
,"first":{"open":1}
,"open":{"layout":1}
,"selected":{"users":1,"table":1}
,"right-click":{"column":1}
,"heading":{"browse":1}
,"command":{"define":1,"if":1}
,"define":{"fields":1}
,"hide":{"delete":1}
,"delete":{"fields":1}
,"create":{"dynamic":1}
,"dynamic":{"report":1}
,"report":{"reset":1}
,"reset":{"table":1}
,"data":{"table":1}
,"right-clicking":{"column":1}
,"choosing":{"table":1}
,"set":{"column":1}
,"width":{"shortcut":1}
,"shortcut":{"menu":1}
,"properties":{"dialog":1}
,"order":{"determine":1,"columns":1}
,"determine":{"default":1}
,"reordering":{"columns":1}
,"viewing":{"records":1}
,"new":{"layouts":1}
,"layouts":{"by":1,"menu":1}
,"current":{"active":1,"record":1}
,"active":{"record":1}
,"record":{"list":1,"solid":1,"choose":1,"indicator":1,"fill":1}
,"fill":{"records":1,"hanging":1}
,"solid":{"vertical":1}
,"left":{"record":1}
,"general":{"tab":1}
,"show":{"current":1}
,"indicator":{"list":1}
,"hanging":{"layout":1}
,"part":{"views":1}
}
;Search.control.loadWordPairs(pairs);
