var pairs =
{
"orking":{"related":1}
,"related":{"data":1,"records":1,"field":1,"record":1,"fields":1,"values":1,"table":1}
,"data":{"portals":1,"portal":1,"related":1,"filtered":1,"transaction":1,"record":1,"salesperson":1,"single":1,"use":1,"filtering":1}
,"portals":{"display":1,"show":1,"master-detail":1,"page":1,"summarizing":1}
,"display":{"related":1,"sets":1,"ou":1,"just":1,"all":1,"data":1,"purposes":1}
,"portal":{"values":1,"use":1,"portal":1,"records":1,"setup":1,"relationship":1,"creation":1,"layout":1,"select":1,"product":1,"filtered":1,"displaying":1,"summarizing":1,"get":1,"suppose":1,"display":1,"simple":1,"related":1,"transaction":1,"calculates":1,"filtering":1,"iltering":1,"filter":1,"data":1}
,"values":{"all":1,"sales":1}
,"all":{"related":1,"sales":1}
,"records":{"displayed":1,"portal":1,"selected":1,"re-sorted":1,"reevaluated":1,"re-sort":1,"display":1,"define":1,"lineitems":1,"just":1,"total":1,"summary":1,"use":1,"place":1,"sales":1,"current":1,"update":1,"portals":1}
,"displayed":{"subject":1,"sort":1,"portal":1,"records":1,"table":1}
,"subject":{"user\u2019s":1}
,"user\u2019s":{"access":1}
,"access":{"privileges":1}
,"privileges":{"by":1}
,"by":{"contrast":1,"each":1}
,"contrast":{"wh":1}
,"wh":{"en":1}
,"en":{"related":1}
,"field":{"ortal":1,"portal":1,"control":1,"total":1,"calculation":1,"displayed":1,"table":1,"layout":1,"displays":1,"name":1,"type":1,"defining":1,"sales":1,"data":1,"switch":1,"related":1,"define":1}
,"ortal":{"value":1}
,"value":{"first":1,"match":1,"total":1}
,"first":{"related":1}
,"record":{"displayed":1,"change":1,"filter":1,"number":1,"loaded":1}
,"sort":{"related":1,"records":1,"order":1}
,"use":{"edit":1,"refresh":1,"formula":1,"data":1,"related":1,"sort":1,"calculation":1}
,"edit":{"relationship":1}
,"relationship":{"dialog":1,"related":1,"criteria":1,"summary":1,"two":1,"multiple":1}
,"dialog":{"box":1}
,"box":{"creating":1,"takes":1,"if":1,"place":1,"unavailable":1}
,"creating":{"nd":1,"portals":1}
,"nd":{"changing":1}
,"changing":{"relationships":1}
,"relationships":{"sort":1,"graph":1}
,"selected":{"data":1}
,"re-sorted":{"related":1}
,"reevaluated":{"records":1}
,"re-sort":{"browse":1}
,"browse":{"back":1,"mode":1}
,"back":{"record":1}
,"change":{"value":1}
,"match":{"field":1}
,"control":{"sort":1}
,"order":{"refreshed":1,"portal":1,"edit":1,"reating":1,"each":1}
,"refreshed":{"use":1}
,"refresh":{"rtal":1}
,"rtal":{"script":1}
,"script":{"step":1}
,"step":{"sort":1,"complex":1}
,"setup":{"dialog":1}
,"takes":{"precedence":1}
,"precedence":{"sort":1}
,"if":{"don\u2019t":1,"lineitems":1,"portal":1,"haven\u2019t":1}
,"don\u2019t":{"sort":1}
,"creation":{"order":1}
,"reating":{"portals":1}
,"filter":{"records":1,"portal":1,"calculation":1,"evaluated":1}
,"sets":{"related":1}
,"layout":{"mode":1,"portal":1,"if":1,"salesperson":1,"create":1,"placing":1,"add":1}
,"mode":{"uble-click":1,"add":1}
,"uble-click":{"portal":1}
,"select":{"filter":1}
,"define":{"calculation":1,"formula":1}
,"calculation":{"evaluates":1,"find":1,"result":1,"field":1,"fields":1}
,"evaluates":{"true":1}
,"true":{"portal":1}
,"ou":{"invoices":1}
,"invoices":{"layout":1}
,"product":{"records":1}
,"lineitems":{"table":1,":quantity":1}
,"table":{"display":1,"related":1,"displayed":1,"sales":1,"salesperson":1,"include":1,"portal":1,"record":1,"rows":1,"creating":1,"fields":1}
,"just":{"products":1,"records":1,"displayed":1}
,"products":{"quantities":1}
,"quantities":{"greater":1}
,"greater":{"equal":1}
,"equal":{"use":1}
,"formula":{"if":1,"defining":1}
,":quantity":{"ummary":1}
,"ummary":{"fields":1}
,"fields":{"calculations":1,"relationship":1,"name":1,"salesperson":1,"layout":1,"sales":1,"layou":1,"portal":1,"sorting":1}
,"calculations":{"find":1}
,"find":{"requests":1,"request":1}
,"requests":{"based":1}
,"based":{"full":1}
,"full":{"set":1}
,"set":{"related":1}
,"filtered":{"if":1,"subset":1,"portal":1}
,"displaying":{"filtered":1}
,"subset":{"records":1}
,"total":{"summary":1,"all":1,"sales":1,"field":1}
,"summary":{"field":1,"computes":1,"fields":1,"data":1}
,"summarizing":{"records":1,"data":1}
,"request":{"create":1,"summarize":1}
,"create":{"new":1,"two":1,"relationship":1,"portal":1}
,"new":{"relationship":1}
,"criteria":{"filtered":1}
,"summarize":{"data":1}
,"get":{"total":1}
,"place":{"summary":1}
,"suppose":{"layout":1}
,"sales":{"by":1,"summarize":1,"transaction":1,"summary":1,"table":1,"layout":1,"place":1,":total":1,"salesperson":1,"field":1}
,"each":{"salesperson":1,"portal":1}
,"salesperson":{"want":1,"id":1,"salesperson":1,"table":1,"layout":1,"total":1}
,"want":{"include":1}
,"include":{"summary":1,"related":1}
,"displays":{"total":1}
,"simple":{"create":1}
,"two":{"tables":1,"salesperson":1,"fields":1}
,"tables":{"fields":1}
,"name":{"field":1,"text":1,"andre":1,"sophie":1}
,"type":{"comment":1}
,"comment":{"sales":1}
,"transaction":{"id":1}
,"id":{"text":1,"fields":1,"total":1,"t1":1,"s1":1,"t2":1,"s2":1,"t3":1,"t4":1,"t5":1}
,"text":{"primary":1,"foreign":1,"relationships":1}
,"primary":{"key":1}
,"key":{"salesperson":1,"number":1,"name":1}
,"foreign":{"key":1}
,"number":{"total":1,"field":1}
,"computes":{"total":1}
,"defining":{"summary":1,"calculation":1}
,"graph":{"create":1}
,"add":{"fields":1,"two":1,"records":1,"data":1}
,"haven\u2019t":{"automatically":1}
,"automatically":{"add":1}
,":total":{"sales":1}
,"placing":{"removing":1}
,"removing":{"fields":1}
,"layou":{"switch":1}
,"switch":{"browse":1,"salesperson":1}
,"t1":{"salesperson":1}
,"s1":{"246.00":1,"10.50":1,"17.80":1,"name":1}
,"246.00":{"transaction":1}
,"t2":{"salesperson":1}
,"s2":{"52.75":1,"150.00":1,"name":1}
,"52.75":{"transaction":1}
,"t3":{"salesperson":1}
,"10.50":{"transaction":1}
,"t4":{"salesperson":1}
,"150.00":{"transaction":1}
,"t5":{"salesperson":1}
,"17.80":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"fills":1,"enters":1}
,"fills":{"value":1}
,"andre":{"common":1}
,"common":{"salesperson":1}
,"sophie":{"tang":1}
,"tang":{"filemaker":1}
,"enters":{"related":1}
,"rows":{"portal":1}
,"calculates":{"total":1}
,"filtering":{"sorting":1,"record":1,"records":1}
,"sorting":{"options":1,"portal":1}
,"options":{"portal":1}
,"unavailable":{"portals":1}
,"show":{"records":1}
,"current":{"table":1}
,"master-detail":{"layouts":1}
,"layouts":{"yo":1}
,"yo":{"display":1}
,"single":{"relationship":1}
,"multiple":{"portals":1}
,"page":{"use":1}
,"iltering":{"records":1}
,"purposes":{"security":1,"result":1}
,"security":{"purposes":1}
,"result":{"portal":1,"calculation":1}
,"update":{"data":1,"portal":1}
,"evaluated":{"record":1}
,"loaded":{"update":1,"use":1}
,"complex":{"summary":1}
}
;Search.control.loadWordPairs(pairs);
