var pairs =
{
"url":{"encoding":1,"by":1,"filemaker":1,"checkbox":1,"remains":1}
,"encoding":{"web":1,"rules":1,"standard":1,"problems":1,"url":1}
,"web":{"viewers":1,"viewer\u0027s":1,"address":1,"viewer":1}
,"viewers":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"evaluates":1,"url":1,"correct":1,"automatically":1}
,"evaluates":{"web":1}
,"viewer\u0027s":{"web":1}
,"address":{"encodes":1}
,"encodes":{"url":1}
,"by":{"default":1,"url":1,"deselecting":1}
,"default":{"load":1}
,"load":{"webpage":1}
,"webpage":{"sing":1}
,"sing":{"url":1}
,"rules":{"fix":1}
,"fix":{"common":1}
,"common":{"problems":1}
,"problems":{"characters":1,"test":1}
,"characters":{"automatically":1,"encoded":1,"listed":1,"character":1}
,"automatically":{"encoded":1,"encoding":1,"encode":1}
,"encoded":{"abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz":1,"if":1,"ut":1,"all":1,"bytes":1,"separately":1,"prevent":1}
,"abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz":{"0123456789-_":1}
,"0123456789-_":{"!*":1}
,"!*":{":@=+$,\u002F?":1}
,":@=+$,\u002F?":{"[]":1}
,"[]":{"ampersand":1}
,"ampersand":{"(&)":1}
,"(&)":{"encoded":1}
,"if":{"space":1,"number":1}
,"space":{"\u0022&\u00A0":1}
,"\u0022&\u00A0":{"encoded":1}
,"ut":{"\u0022&x":1}
,"\u0022&x":{"pound":1}
,"pound":{"sign":1}
,"sign":{"encoded":1}
,"number":{"character":1}
,"character":{"backslash":1,"encoded":1}
,"backslash":{"(\u005C)":1}
,"(\u005C)":{"percent":1}
,"percent":{"characters":1}
,"all":{"characters":1,"url":1}
,"listed":{"unicode":1}
,"unicode":{"characters":1}
,"bytes":{"encoded":1}
,"separately":{"first":1}
,"first":{"byte":1}
,"byte":{"00":1}
,"00":{"by":1}
,"standard":{"ww.w3.org\u002Faddressing\u002F":1}
,"ww.w3.org\u002Faddressing\u002F":{"filemaker":1}
,"correct":{"all":1}
,"test":{"web":1}
,"viewer":{"ensure":1,"setup":1}
,"ensure":{"urls":1}
,"urls":{"correctly":1}
,"correctly":{"encoded":1}
,"prevent":{"filemaker":1}
,"deselecting":{"automatically":1}
,"encode":{"url":1}
,"checkbox":{"web":1}
,"setup":{"dialog":1}
,"dialog":{"box":1}
,"box":{"option":1}
,"option":{"deselected":1}
,"deselected":{"url":1}
,"remains":{"entered":1}
}
;Search.control.loadWordPairs(pairs);
