var pairs =
{
"patterncount":{"returns":1,"text":1,"start":1,"mississippi":1,"attending":1,"get":1}
,"returns":{"number":1,"patterncount":1,"second":1,"if":1}
,"number":{"occurrences":1,"filemaker":1}
,"occurrences":{"searchstring":1}
,"searchstring":{"text":1,"-any":1,"patterncount":1}
,"text":{"patterncount":1,"searchstring":1,"-any":1,"expression":1,"field":1,"counts":1}
,"-any":{"text":1}
,"expression":{"text":1}
,"field":{"searchstring":1,"representing":1,"patterncount":1}
,"representing":{"set":1}
,"set":{"characters":1}
,"characters":{"want":1,"patterncount":1}
,"want":{"find":1}
,"find":{"number":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"function":1}
,"function":{"case":1}
,"case":{"sensitive":1}
,"sensitive":{"patterncount":1}
,"start":{"text":1}
,"counts":{"each":1}
,"each":{"non-overlapping":1}
,"non-overlapping":{"occurrence":1}
,"occurrence":{"searchstring":1,"starting":1,"characters":1}
,"mississippi":{"returns":1,"issi":1}
,"issi":{"returns":1}
,"second":{"occurrence":1}
,"starting":{"character":1}
,"character":{"counted":1}
,"counted":{"overlaps":1}
,"overlaps":{"first":1}
,"first":{"occurrence":1}
,"attending":{"guest":1,"field":1}
,"guest":{"returns":1,"checkbox":1}
,"if":{"guest":1,"current":1}
,"checkbox":{"items":1}
,"items":{"selected":1}
,"selected":{"attending":1}
,"get":{"accountprivilegesetname":1}
,"accountprivilegesetname":{"guest":1}
,"current":{"account":1}
,"account":{"full":1}
,"full":{"access":1}
,"access":{"privilege":1}
,"privilege":{"set":1}
}
;Search.control.loadWordPairs(pairs);
