var pairs =
{
"mporting":{"folder":1}
,"folder":{"files":1,"text":1,"image":1,"audio\u002Fvideo":1,"folder":1,"levels":1,"picture":1,"import":1}
,"files":{"all":1,"single":1,"faster":1,"plain":1,".txt":1,"container":1,"interactive":1,"text":1,"thumbnail":1,"existing":1,"filemaker":1,"import":1,"want":1,"exist":1,"continue":1,"select":1,"choose":1,"movie":1,"usually":1,"importing":1,"by":1,"image":1,"folders":1}
,"all":{"filemaker":1,"ou":1,"enclosed":1}
,"filemaker":{"pro":1,"pr":1}
,"pro":{"advanced":1}
,"advanced":{"import":1,"ile":1,"won\u2019t":1,"file":1,"target":1,"shortcuts":1,"locates":1,"oes":1,"select":1}
,"import":{"folder":1,"all":1,"image":1,"each":1,"data":1,"if":1,"records":1,"options":1,"select":1,"files":1,"up":1,"field":1,"action":1,"source":1,"details":1,"process":1,"depending":1,"file":1,"import":1,"shortcuts":1,"items":1,"invisible":1}
,"single":{"operation":1}
,"operation":{"inserting":1}
,"inserting":{"picture":1}
,"picture":{"pdf":1,"insert":1,"audio\u002Fvideo":1,"movie":1,"files":1,"file":1}
,"pdf":{"audio\u002Fvideo":1,"ile":1,"ommand":1,"files":1}
,"audio\u002Fvideo":{"iles":1,"pdf":1,"insert":1,"formats":1}
,"iles":{"by":1}
,"by":{"import":1,"reference":1}
,"ou":{"import":1}
,"text":{"files":1,"file":1,"number":1,"field":1,"content":1,"right-click":1,"choose":1}
,"faster":{"copying":1}
,"copying":{"pasting":1}
,"pasting":{"contents":1}
,"contents":{"each":1}
,"each":{"file":1,"record":1,"picture":1,"source":1,"original":1}
,"file":{"filemaker":1,"type":1,"content":1,"filename":1,"path":1,"if":1,"you\u2019re":1,"undone":1,"menu":1,"local":1,"located":1,"multiple":1,"sure":1,"replaces":1,"browse":1,"mport":1,"option":1,"im":1,"data":1,"name":1,"imports":1,"shortcut":1}
,"image":{"audio\u002Fvideo":1,"files":1,"open":1,"container":1,"thumbnail":1,"pecifying":1}
,"ile":{"insert":1,"want":1,"import":1,"type":1}
,"insert":{"insert":1,"picture":1,"audio\u002Fvideo":1,"pdf":1}
,"ommand":{"supported":1}
,"supported":{"picture":1}
,"formats":{"data":1,"container":1}
,"data":{"container":1,"new":1,"target":1,"choose":1,"filemaker":1,"if":1,"matches":1,"correct":1,"each":1,"want":1}
,"container":{"fields":1,"field":1,"folder":1,"image":1}
,"fields":{"ext":1,"target":1,"during":1,"hen":1}
,"ext":{"files":1}
,"plain":{"text-only":1}
,"text-only":{"files":1}
,".txt":{"filename":1}
,"filename":{"extension":1,"file":1}
,"extension":{"text":1}
,"type":{"import":1,"choose":1,"chose":1,"each":1,"source":1,"picture":1}
,"field":{"folder":1,"addition":1,"data":1,"mapping":1,"type":1,"want":1,"file":1,"image":1,"text":1,"audio\u002Fvideo":1,"open":1}
,"interactive":{"container":1,"choose":1}
,"number":{"date":1}
,"date":{"time":1}
,"time":{"timestamp":1}
,"timestamp":{"container":1}
,"addition":{"file":1}
,"content":{"import":1,"text":1}
,"path":{"picture":1,"text":1,"source":1}
,"movie":{"files":1}
,"thumbnail":{"image":1,"container":1}
,"open":{"filemaker":1,"original":1,"file":1}
,"want":{"import":1,"update":1,"change":1}
,"existing":{"filemaker":1,"matching":1,"records":1}
,"won\u2019t":{"convert":1,"display":1}
,"convert":{"imported":1}
,"imported":{"data":1,"by":1,"windows":1}
,"new":{"file":1,"records":1}
,"if":{"you\u2019re":1,"match":1,"sort":1,"import":1}
,"you\u2019re":{"updating":1,"importing":1,"adding":1,"replacing":1}
,"updating":{"existing":1,"matching":1,"replacing":1,"atching":1}
,"matching":{"records":1}
,"records":{"backup":1,"replacing":1,"overwrites":1,"importing":1,"table":1,"import":1,"skip":1,"sure":1,"want":1,"found":1,"file":1,"data":1,"folder":1}
,"backup":{"opy":1,"copy":1}
,"opy":{"target":1}
,"target":{"file":1,"filemaker":1,"field":1}
,"importing":{"updating":1,"data":1,"folder":1,"large":1,"reference":1}
,"replacing":{"existing":1,"records":1}
,"overwrites":{"data":1}
,"undone":{"safeguard":1}
,"safeguard":{"data":1}
,"choose":{"file":1,"folder":1,"picture":1,"target":1,"interactive":1,"open":1}
,"menu":{"save":1,"display":1,"import":1}
,"save":{"copy":1}
,"copy":{"backup":1,"target":1,"each":1}
,"local":{"file":1}
,"located":{"computer":1}
,"computer":{"sure":1}
,"sure":{"understand":1,"found":1}
,"understand":{"updating":1}
,"pr":{"advanced":1}
,"multiple":{"tables":1}
,"tables":{"use":1}
,"use":{"layout":1}
,"layout":{"pop-up":1,"records":1}
,"pop-up":{"menu":1}
,"display":{"layout":1,"import":1}
,"table":{"want":1}
,"atching":{"records":1}
,"adding":{"new":1}
,"skip":{"next":1}
,"next":{"step":1}
,"step":{"if":1,"choose":1}
,"found":{"set":1}
,"set":{"records":1,"updated":1}
,"update":{"records":1}
,"updated":{"if":1}
,"match":{"field":1}
,"matches":{"if":1}
,"change":{"if":1}
,"sort":{"records":1}
,"correct":{"record":1}
,"record":{"source":1,"target":1}
,"source":{"file":1,"files":1,"field":1,"fields":1,"data":1}
,"replaces":{"data":1}
,"browse":{"mode":1}
,"mode":{"choose":1}
,"options":{"dialog":1}
,"dialog":{"box":1}
,"box":{"appears":1,"import":1,"finishing":1}
,"appears":{"location":1}
,"location":{"choose":1}
,"select":{"include":1,"mport":1,"entire":1}
,"include":{"all":1}
,"enclosed":{"folders":1}
,"folders":{"import":1,"filemaker":1,"hidden":1,"invisible":1}
,"exist":{"enclosed":1}
,"up":{"100":1}
,"100":{"folder":1}
,"levels":{"deep":1}
,"deep":{"ile":1}
,"continue":{"if":1}
,"mport":{"reference":1,"action":1}
,"reference":{"each":1,"if":1,"move":1}
,"option":{"deselected":1}
,"deselected":{"copy":1}
,"im":{"port":1}
,"port":{"ed":1}
,"ed":{"irectly":1}
,"irectly":{"database":1}
,"database":{"pdf":1}
,"usually":{"large":1}
,"large":{"imported":1,"picture":1}
,"move":{"rename":1}
,"rename":{"delete":1}
,"delete":{"source":1}
,"mapping":{"dialog":1,"fields":1}
,"action":{"icon":1,"perform":1,"mapping":1}
,"icon":{"hoose":1}
,"hoose":{"mport":1}
,"perform":{"map":1}
,"map":{"fields":1}
,"details":{"import":1}
,"finishing":{"import":1}
,"process":{"etting":1}
,"etting":{"import":1}
,"during":{"import":1}
,"depending":{"import":1}
,"chose":{"step":1}
,"name":{"text":1}
,"pecifying":{"formats":1}
,"hen":{"folder":1}
,"shortcuts":{"windows":1,"liases":1}
,"windows":{"aliases":1,"filemaker":1}
,"aliases":{"macos":1}
,"macos":{"files":1,"filemaker":1}
,"liases":{"files":1,"folders":1}
,"locates":{"each":1}
,"original":{"file":1,"folders":1}
,"imports":{"shortcuts":1}
,"oes":{"locate":1}
,"locate":{"original":1}
,"items":{"imported":1}
,"hidden":{"offline":1}
,"offline":{"system":1}
,"system":{"temporary":1}
,"temporary":{"macos":1}
,"invisible":{"files":1,"import":1}
,"entire":{"file":1}
,"right-click":{"text":1}
,"shortcut":{"menu":1}
}
;Search.control.loadWordPairs(pairs);
