var pairs =
{
"rightwords":{"returns":1,"text":1,"plaid":1,"name":1}
,"returns":{"text":1,"canvas":1,"virtanen":1}
,"text":{"numberofwords":1,"counting":1,"-any":1,"expression":1,"field":1,"filemaker":1}
,"numberofwords":{"text":1,"-any":1}
,"counting":{"right":1}
,"right":{"rightwords":1}
,"-any":{"text":1,"numeric":1}
,"expression":{"text":1,"field":1}
,"field":{"numberofwords":1,"number":1,"matti":1}
,"numeric":{"expression":1}
,"number":{"text":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"rightwords":1}
,"plaid":{"canvas":1}
,"canvas":{"suitcase":1}
,"suitcase":{"returns":1,"rightwords":1}
,"name":{"returns":1,"field":1}
,"virtanen":{"name":1}
,"matti":{"virtanen":1}
}
;Search.control.loadWordPairs(pairs);
