var pairs =
{
"get":{"installedfmplugins":1}
,"installedfmplugins":{"returns":1,"none":1}
,"returns":{"name":1,"values":1,"get":1,"plug-in":1,"myplugin1;1.0":1}
,"name":{"version":1}
,"version":{"number":1,"plug-in":1,"resource":1}
,"number":{"enabled":1,"returned":1}
,"enabled":{"state":1,"plug-in":1,"filemaker":1,"plug-ins":1,"myplugin2;1.1":1}
,"state":{"installed":1,"returned":1}
,"installed":{"plug-ins":1,"plug-in":1,"get":1,"enabled":1,"disabled":1}
,"plug-ins":{"get":1,"installed":1,"stored":1,"tab":1}
,"none":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"12.0":1,"advanced":1}
,"12.0":{"function":1}
,"function":{"determining":1}
,"determining":{"installed":1}
,"plug-in":{"plug-in":1,"required":1,"separate":1,"version":1,"developers":1,"enabled":1,"disabled":1,"failed":1}
,"required":{"by":1}
,"by":{"file":1,"carriage":1}
,"file":{"version":1,"windows":1,"macos":1}
,"returned":{"if":1,"enabled":1}
,"if":{"if":1,"multiple":1}
,"multiple":{"plug-ins":1}
,"values":{"each":1}
,"each":{"plug-in":1}
,"separate":{"lines":1}
,"lines":{"separated":1}
,"separated":{"by":1}
,"carriage":{"returns":1}
,"developers":{"entered":1}
,"entered":{"version":1}
,"resource":{"file":1}
,"windows":{"info.plist":1}
,"info.plist":{"file":1}
,"macos":{"macos":1,"plug-ins":1}
,"stored":{"packages":1}
,"packages":{"enabled":1}
,"advanced":{"preferences":1}
,"preferences":{"loaded":1,"dialog":1}
,"loaded":{"disabled":1,"ignored":1,"get":1}
,"disabled":{"plug-in":1,"filemaker":1,"plug-ins":1,"myplugin3":1}
,"ignored":{"plug-in":1}
,"failed":{"load":1}
,"load":{"software":1}
,"software":{"incompatibility":1}
,"incompatibility":{"myplugin1":1}
,"myplugin1":{"installed":1}
,"tab":{"preferences":1}
,"dialog":{"box":1}
,"box":{"myplugin2":1,"myplugin3":1}
,"myplugin2":{"installed":1}
,"myplugin3":{"loaded":1,"ignored":1}
,"myplugin1;1.0":{"enabled":1}
,"myplugin2;1.1":{"disabled":1}
}
;Search.control.loadWordPairs(pairs);
