var pairs =
{
"get":{"found":1,"foundcount":1}
,"found":{"count":1,"set":1}
,"count":{"returns":1,"value":1,"found":1,"find":1,"function":1}
,"returns":{"number":1,"records":1}
,"number":{"records":1,"filemaker":1}
,"records":{"current":1}
,"current":{"found":1,"database":1,"calculation":1,"window":1}
,"set":{"get":1,"scripts":1,"count":1}
,"foundcount":{"none":1,"get":1}
,"none":{"number":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"if":1}
,"if":{"multiple":1,"context":1,"script":1}
,"multiple":{"windows":1}
,"windows":{"open":1}
,"open":{"current":1}
,"database":{"file":1}
,"file":{"each":1}
,"each":{"window":1}
,"window":{"own":1,"if":1,"returns":1}
,"own":{"found":1}
,"value":{"returned":1}
,"returned":{"foreground":1}
,"foreground":{"window":1}
,"context":{"current":1,"evaluated":1}
,"calculation":{"function":1}
,"function":{"evaluated":1}
,"evaluated":{"based":1}
,"based":{"context":1}
,"scripts":{"if":1}
,"script":{"step":1}
,"step":{"get":1}
,"find":{"count":1}
}
;Search.control.loadWordPairs(pairs);
