var pairs =
{
"defining":{"value":1,"field":1}
,"value":{"lists":1,"list":1,"separate":1,"entered":1}
,"lists":{"if":1,"help":1,"manage":1,"dialog":1,"defined":1,"character":1,"odbc":1}
,"if":{"field":1,"table":1,"display":1,"selected":1,"choose":1,"value":1,"change":1,"search":1,"want":1}
,"field":{"set":1,"display":1,"displaying":1,"current":1,"list":1,"related":1,"fields":1,"select":1,"want":1,"values":1,"selected":1,"dimmed":1,"left":1,"step":1,"value":1,"use":1,"efining":1,"store":1,"if":1,"specific":1,"referenced":1,"option":1,"format":1,"empty":1,"formatted":1,"validation":1}
,"set":{"text":1,"control":1}
,"text":{"number":1,"field":1,"strings":1}
,"number":{"date":1}
,"date":{"time":1}
,"time":{"values":1}
,"values":{"all":1,"format":1,"pop-up":1,"new":1,"list":1,"order":1,"field":1,"existing":1,"displayed":1,"type":1,"value":1,"change":1,"choose":1,"first":1,"include":1,"starting":1,"records":1,"second":1,"two":1,"text":1,"based":1,"sorted":1,"efining":1}
,"all":{"records":1,"values":1}
,"records":{"create":1,"satisfy":1,"if":1}
,"create":{"value":1,"custom":1,"type":1}
,"list":{"includes":1,"series":1,"two":1,"radio":1,"two-step":1,"create":1,"use":1,"file":1,"checkboxes":1,"type":1,"dialog":1,"name":1,"setting":1,"created":1,"based":1,"if":1,"choose":1,"add":1,"value":1,"display":1,"select":1,"help":1,"step":1,"displays":1,"sort":1,"want":1,"re-creating":1,"follow":1,"note":1,"item":1,"matter":1,"enforce":1,"privileges":1,"defining":1,"field":1}
,"includes":{"values":1}
,"format":{"field":1}
,"display":{"values":1,"pop-up":1,"all":1,"field":1,"associated":1,"part":1,"value":1,"fields":1}
,"pop-up":{"menu":1}
,"menu":{"drop-down":1,"manage":1,"checkbox":1,"displays":1}
,"drop-down":{"list":1}
,"series":{"checkboxes":1}
,"checkboxes":{"radio":1}
,"radio":{"buttons":1,"button":1}
,"buttons":{"define":1,"field":1,"value":1,"method":1}
,"define":{"value":1,"customer":1}
,"two":{"values":1,"fields":1}
,"new":{"continuing":1,"edit":1}
,"continuing":{"define":1}
,"customer":{"type":1}
,"type":{"field":1,"values":1,"name":1,"each":1,"value":1}
,"displaying":{"radio":1,"data":1}
,"help":{"data":1}
,"data":{"entry":1,"value":1,"first":1,"second":1,"source":1,"sources":1,"entered":1,"access":1,"predefined":1}
,"entry":{"faster":1,"display":1,"value":1}
,"faster":{"accurate":1}
,"accurate":{"display":1}
,"order":{"by":1,"want":1,"choose":1,"select":1,"field\u2019s":1}
,"by":{"month":1}
,"month":{"region":1}
,"region":{"displaying":1}
,"two-step":{"process":1}
,"process":{"create":1}
,"custom":{"value":1,"values":1,"privilege":1}
,"use":{"values":1,"inspector":1,"custom":1,"lookup":1,"determining":1,"list":1,"value":1,"se":1,"use":1}
,"current":{"file":1}
,"file":{"file":1,"use":1,"layout":1,"menu":1,"list":1,"dimmed":1,"relationships":1,"create":1,"defining":1,"change":1}
,"existing":{"value":1,"records":1}
,"layout":{"mode":1,"fields":1}
,"mode":{"use":1}
,"inspector":{"format":1}
,"method":{"easiest":1,"dynamically":1}
,"easiest":{"create":1}
,"displayed":{"choose":1}
,"choose":{"file":1,"manage":1,"display":1,"include":1,"related":1,"field":1,"show":1,"select":1,"language":1,"add":1}
,"manage":{"value":1,"database":1}
,"dialog":{"box":1}
,"box":{"new":1,"value":1,"use":1,"edit":1}
,"edit":{"value":1,"delete":1}
,"name":{"type":1,"select":1}
,"select":{"use":1,"table":1,"field":1,"display":1,"option":1,"show":1,"re-sort":1,"value":1}
,"each":{"value":1}
,"separate":{"line":1}
,"line":{"order":1}
,"want":{"format":1,"select":1,"file":1,"display":1,"defined":1,"use":1,"field":1}
,"setting":{"up":1,"ignored":1}
,"up":{"field":1}
,"checkbox":{"set":1,"radio":1}
,"control":{"value":1,"if":1,"choose":1}
,"created":{"method":1}
,"dynamically":{"updated":1}
,"updated":{"values":1}
,"change":{"field":1,"value":1,"duplicate":1}
,"based":{"if":1,"choose":1,"values":1}
,"related":{"table":1,"values":1}
,"table":{"show":1,"field":1,"want":1,"relationships":1,"list":1,"table":1,"file":1}
,"show":{"all":1,"values":1,"related":1}
,"fields":{"value":1,"enters":1,"pop-up":1,"want":1,"hoosing":1,"object":1}
,"first":{"field":1,"select":1}
,"database":{"list":1,"diting":1}
,"add":{"table":1,"data":1}
,"relationships":{"graph":1,"choose":1}
,"graph":{"creating":1,"current":1}
,"creating":{"nd":1}
,"nd":{"changing":1}
,"changing":{"relationships":1}
,"include":{"related":1}
,"starting":{"choose":1}
,"satisfy":{"relationship":1}
,"relationship":{"criteria":1}
,"criteria":{"related":1}
,"selected":{"use":1,"second":1}
,"associated":{"values":1}
,"second":{"field":1}
,"option":{"display":1,"add":1,"field\u2019s":1}
,"part":{"names":1,"numbers":1}
,"names":{"next":1}
,"next":{"part":1}
,"numbers":{"if":1}
,"dimmed":{"first":1,"alue":1}
,"left":{"field":1}
,"step":{"note":1,"second":1}
,"note":{"during":1,"redefining":1}
,"during":{"data":1}
,"displays":{"values":1,"fields":1}
,"enters":{"data":1}
,"entered":{"field":1,"unexpected":1}
,"lookup":{"automatically":1}
,"automatically":{"enter":1}
,"enter":{"data":1}
,"efining":{"updating":1,"custom":1}
,"updating":{"lookups":1}
,"lookups":{"if":1}
,"determining":{"value":1}
,"sort":{"order":1}
,"store":{"data":1}
,"specific":{"language\u2019s":1}
,"language\u2019s":{"dictionary":1}
,"dictionary":{"sort":1}
,"re-sort":{"values":1}
,"language":{"values":1,"setting":1,"indexing":1}
,"sorted":{"index":1}
,"index":{"order":1}
,"field\u2019s":{"default":1,"definition":1}
,"default":{"language":1}
,"ignored":{"types":1}
,"types":{"fields":1}
,"hoosing":{"language":1}
,"indexing":{"sorting":1}
,"sorting":{"10":1}
,"10":{"times":1}
,"times":{"11":1}
,"11":{"ormat":1}
,"ormat":{"field":1}
,"defined":{"file":1,"show":1}
,"re-creating":{"choose":1}
,"source":{"ontaining":1}
,"ontaining":{"value":1}
,"se":{"co":1}
,"co":{"nnecting":1}
,"nnecting":{"external":1}
,"external":{"data":1,"sql":1}
,"sources":{"value":1}
,"alue":{"lists":1}
,"referenced":{"file":1}
,"follow":{"instructions":1}
,"instructions":{"defining":1}
,"delete":{"duplicate":1,"value":1}
,"duplicate":{"list":1,"delete":1}
,"redefining":{"value":1}
,"item":{"data":1,"accessory":1}
,"unexpected":{"if":1}
,"accessory":{"accessories":1}
,"accessories":{"field":1,"if":1}
,"empty":{"layouts":1}
,"layouts":{"field":1}
,"formatted":{"checkbox":1}
,"button":{"find":1}
,"find":{"existing":1}
,"search":{"accessories":1}
,"matter":{"layout":1}
,"object":{"validation":1}
,"validation":{"option":1,"ields":1}
,"definition":{"defining":1}
,"ields":{"odbc":1}
,"odbc":{"data":1}
,"character":{"large":1}
,"large":{"objects":1}
,"objects":{"clobs":1}
,"clobs":{"text":1}
,"strings":{"supported":1}
,"supported":{"value":1,"prohibit":1}
,"access":{"privilege":1}
,"privilege":{"limited":1,"supported":1}
,"limited":{"custom":1}
,"prohibit":{"user":1}
,"user":{"odbc":1}
,"enforce":{"row-level":1}
,"row-level":{"security":1}
,"security":{"external":1}
,"sql":{"database":1}
,"diting":{"value":1}
,"privileges":{"preset":1}
,"preset":{"data":1}
,"predefined":{"values":1}
}
;Search.control.loadWordPairs(pairs);
