var pairs =
{
"onobjectenter":{"performs":1,"script":1,"assigned":1,"activate":1,"activated":1}
,"performs":{"script":1}
,"script":{"hen":1,"step":1,"trigger":1,"rigger":1,"triggers":1,"runs":1}
,"hen":{"layout":1}
,"layout":{"object":1}
,"object":{"active":1,"user":1,"script":1,"entered":1,"activate":1,"portal":1}
,"active":{"result":1,"clicking":1,"activate":1,"object":1,"activates":1}
,"result":{"user":1}
,"user":{"tabs":1,"clicks":1,"moves":1}
,"tabs":{"object":1}
,"clicks":{"object":1}
,"step":{"object":1,"associated":1}
,"entered":{"user":1,"onobjectenter":1}
,"moves":{"repetitions":1}
,"repetitions":{"repeating":1}
,"repeating":{"field":1}
,"field":{"event":1,"entered":1}
,"event":{"processed":1}
,"processed":{"browse":1}
,"browse":{"find":1}
,"find":{"modes":1,"mode":1}
,"modes":{"none":1,"trigger":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"10.0":1,"advanced":1}
,"10.0":{"filemaker":1}
,"webdirect":{"script":1}
,"trigger":{"activate":1,"onobjectexit":1,"onobjectkeystroke":1,"activated":1,"set":1,"clicking":1,"button":1,"actions":1,"script":1,"result":1}
,"activate":{"assigned":1,"portal":1,"onobjectenter":1,"script":1}
,"assigned":{"web":1,"summary":1,"portal":1}
,"web":{"viewer":1}
,"viewer":{"onobjectenter":1}
,"onobjectexit":{"script":1}
,"onobjectkeystroke":{"script":1}
,"activated":{"assigned":1,"if":1}
,"summary":{"calculation":1}
,"calculation":{"fields":1}
,"fields":{"if":1}
,"if":{"onobjectenter":1,"trigger":1}
,"portal":{"object":1,"row":1,"find":1}
,"row":{"active":1,"portal\u2019s":1}
,"clicking":{"object":1,"button":1}
,"portal\u2019s":{"onobjectenter":1}
,"mode":{"filemaker":1,"field":1,"scrolling":1}
,"advanced":{"switches":1}
,"switches":{"find":1}
,"set":{"run":1}
,"run":{"find":1}
,"scrolling":{"object":1}
,"button":{"opover":1,"anel":1,"tab":1,"ab":1,"active":1}
,"opover":{"button":1}
,"anel":{"control":1}
,"control":{"activate":1}
,"tab":{"pressing":1,"navigate":1}
,"pressing":{"tab":1}
,"navigate":{"button":1}
,"ab":{"panel":1}
,"panel":{"slide":1,"nd":1}
,"slide":{"panel":1}
,"nd":{"active":1}
,"rigger":{"closing":1}
,"closing":{"popover":1}
,"popover":{"esc":1,"script":1,"button":1}
,"esc":{"key":1}
,"key":{"close":1}
,"close":{"popover":1}
,"associated":{"popover":1}
,"activates":{"onobjectenter":1}
,"actions":{"don\u2019t":1,"activate":1}
,"don\u2019t":{"activate":1}
,"triggers":{"list":1}
,"list":{"actions":1}
,"runs":{"modes":1}
}
;Search.control.loadWordPairs(pairs);
