var pairs =
{
"textcolor":{"color":1,"text":1,"plaid":1,"mytable":1}
,"color":{"text":1,"by":1,"layout":1,"palette":1,"values":1,"sliders":1}
,"text":{"color":1,"rgb":1,"-any":1,"expression":1,"field":1,"filemaker":1,"text":1,"formatting":1,"determine":1,"contained":1,"courier":1}
,"by":{"rgb":1,"combining":1}
,"rgb":{"function":1,"red":1,"value":1,"sliders":1,"255":1,"returns":1,"125":1}
,"function":{"textcolor":1,"change":1,"supported":1}
,"red":{"green":1,"textcolor":1}
,"green":{"blue":1,"textcolor":1,"text":1}
,"blue":{"text":1,"-any":1,"values":1,"textcolor":1}
,"-any":{"text":1,"integer":1}
,"expression":{"text":1}
,"field":{"rgb":1,"type":1}
,"integer":{"16777215":1}
,"16777215":{"by":1}
,"combining":{"red":1}
,"values":{"each":1}
,"each":{"ranging":1,"basic":1}
,"ranging":{"255":1}
,"255":{"represent":1,"returns":1}
,"represent":{"color":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"7.0":1}
,"7.0":{"use":1}
,"use":{"function":1}
,"change":{"color":1}
,"formatting":{"options":1,"bar":1}
,"options":{"lost":1}
,"lost":{"if":1}
,"if":{"field":1}
,"type":{"returned":1}
,"returned":{"text":1}
,"determine":{"rgb":1}
,"value":{"color":1}
,"layout":{"mode":1}
,"mode":{"fill":1}
,"fill":{"color":1}
,"palette":{"formatting":1}
,"bar":{"choose":1}
,"choose":{"color":1,"rgb":1}
,"basic":{"colors":1}
,"colors":{"macos":1}
,"macos":{"select":1}
,"select":{"color":1}
,"sliders":{"tab":1,"list":1}
,"tab":{"choose":1}
,"list":{"function":1}
,"supported":{"filemaker":1}
,"webdirect":{"textcolor":1}
,"plaid":{"rgb":1,"red":1,"green":1,"blue":1,"black":1}
,"returns":{"word":1,"text":1}
,"word":{"plaid":1}
,"black":{"textsize":1}
,"textsize":{"textfont":1}
,"textfont":{"textcolor":1}
,"mytable":{":mytext":1}
,":mytext":{"rgb":1,"formatted":1}
,"125":{"125":1,"courier":1}
,"courier":{"12":1,"font":1}
,"12":{"returns":1}
,"contained":{"mytable":1}
,"formatted":{"12pt":1}
,"12pt":{"green":1}
}
;Search.control.loadWordPairs(pairs);
