var pairs =
{
"lookup":{"returns":1,"sourcefield":1,"value":1,"fails":1,"function":1}
,"returns":{"value":1}
,"value":{"sourcefield":1,"failexpression":1}
,"sourcefield":{"relationships":1,"failexpression":1,"-the":1}
,"relationships":{"relationships":1,"graph":1}
,"graph":{"lookup":1}
,"failexpression":{"sourcefield":1,"-any":1,"returned":1}
,"-the":{"field":1}
,"field":{"lookup":1,"tables":1,"calculation":1,"related":1,"companyid":1}
,"-any":{"expression":1}
,"expression":{"parameters":1}
,"parameters":{"braces":1}
,"braces":{"optional":1}
,"optional":{"text":1,"failexpression":1}
,"text":{"number":1}
,"number":{"date":1,"field":1}
,"date":{"time":1}
,"time":{"timestamp":1}
,"timestamp":{"container":1}
,"container":{"filemaker":1}
,"filemaker":{"pro":1,"95054":1,"second":1}
,"pro":{"7.0":1}
,"7.0":{"result":1}
,"result":{"optional":1}
,"returned":{"if":1}
,"if":{"lookup":1}
,"fails":{"function":1}
,"function":{"access":1,"won\u2019t":1}
,"access":{"contents":1}
,"contents":{"source":1}
,"source":{"field":1}
,"tables":{"source":1,"people":1,"related":1}
,"calculation":{"field":1,"companyname":1}
,"related":{"calculations":1,"number":1}
,"calculations":{"lookup":1,"two":1}
,"won\u2019t":{"forced":1}
,"forced":{"unstored":1}
,"unstored":{"calculations":1}
,"two":{"tables":1}
,"people":{"company":1,"table":1}
,"company":{"database":1,"table":1,"tables":1,":companyname":1}
,"database":{"file":1}
,"file":{"data":1}
,"data":{"people":1}
,"table":{"companyid":1,"return":1}
,"companyid":{"employee":1,"companyname":1,"calculation":1}
,"employee":{"100":1}
,"100":{"john":1,"apple":1}
,"john":{"smith":1}
,"smith":{"200":1}
,"200":{"peter":1,"filemaker":1}
,"peter":{"wong":1}
,"wong":{"300":1}
,"300":{"sally":1}
,"sally":{"anderson":1}
,"anderson":{"company":1}
,"companyname":{"code":1,"=lookup":1}
,"code":{"100":1}
,"apple":{"91234":1,"82345":1,"first":1}
,"91234":{"100":1}
,"82345":{"200":1}
,"95054":{"people":1}
,"=lookup":{"company":1}
,":companyname":{"found":1}
,"found":{"defined":1,"record":1}
,"defined":{"people":1}
,"return":{"apple":1}
,"first":{"record":1}
,"record":{"filemaker":1,"found":1}
,"second":{"record":1}
}
;Search.control.loadWordPairs(pairs);
