var pairs =
{
"perform":{"script":1,"by":1,"external":1}
,"script":{"erforms":1,"list":1,"want":1,"name":1,"parameter":1,"filemaker":1,"parameters":1,"passed":1,"steps":1,"explicitly":1,"calls":1,"independent":1,"exist":1,"script":1,"performed":1,"changing":1,"contain":1,"step":1,"returns":1,"names":1,"select":1,"optional":1,"if":1,"[specified":1,"named":1,"current":1}
,"erforms":{"script":1}
,"list":{"calculated":1,"allows":1,"print":1,"view":1}
,"calculated":{"by":1}
,"by":{"name":1,"calculation":1,"putting":1,"script":1,"defining":1,"get":1,"carriage":1}
,"name":{"list":1,"allows":1,"by":1,"case":1,"script":1,"invoices":1,"parameter":1,"customer":1,"button":1}
,"allows":{"select":1,"script":1}
,"select":{"script":1}
,"want":{"perform":1,"use":1,"return":1,"continue":1}
,"calculation":{"script":1,"evaluate":1}
,"case":{"sensitive":1}
,"sensitive":{"pa":1,"if":1}
,"pa":{"rameter":1}
,"rameter":{"pecifies":1}
,"pecifies":{"script":1}
,"parameter":{"script":1,"parameter":1,"accessed":1,"sub-script":1,"if":1,"field":1,"invoices":1,"automating":1}
,"filemaker":{"pro":1,"webdirect":1,"data":1}
,"pro":{"6.0":1,"advanced":1}
,"6.0":{"earlier":1}
,"earlier":{"open":1}
,"open":{"external":1}
,"external":{"file":1,"script":1}
,"file":{"script":1,"add":1,"if":1,"calculation":1,"bound":1}
,"advanced":{"use":1,"file":1}
,"use":{"separate":1,"page":1,"script":1,"leftvalues":1,"by":1}
,"separate":{"scripts":1}
,"scripts":{"break":1,"accessed":1,"by":1,"easy":1,"run":1,"host":1,"main":1}
,"break":{"complex":1}
,"complex":{"tasks":1}
,"tasks":{"segments":1,"printing":1,"scripts":1}
,"segments":{"easier":1}
,"easier":{"troubleshoot":1}
,"troubleshoot":{"save":1}
,"save":{"time":1}
,"time":{"by":1,"script":1,"sub-script":1}
,"putting":{"common":1}
,"common":{"tasks":1}
,"printing":{"exporting":1,"options":1}
,"exporting":{"records":1}
,"records":{"separate":1,"[replace":1,"[restore":1}
,"accessed":{"by":1,"script":1}
,"page":{"setup":1}
,"setup":{"printing":1}
,"options":{"scripts":1}
,"defining":{"steps":1,"custom":1}
,"steps":{"saving":1,"times":1,"get":1}
,"saving":{"separate":1}
,"easy":{"access":1}
,"access":{"steps":1,"ee":1}
,"times":{"use":1}
,"parameters":{"pass":1,"exist":1,"called":1,"parent":1,"reset":1,"each":1,"passed":1,"returned":1,"se":1,"go":1}
,"pass":{"text":1}
,"text":{"numbers":1}
,"numbers":{"script":1}
,"passed":{"script":1,"sub-script":1,"sub-scripts":1}
,"get":{"scriptparameter":1,"lastmessagechoice":1}
,"scriptparameter":{"function":1,"parent":1,"layout":1}
,"function":{"script":1,"parameter":1,"middlevalues":1,"rightvalues":1,"isolate":1}
,"exist":{"parent":1,"duration":1}
,"parent":{"script":1}
,"explicitly":{"passed":1}
,"sub-script":{"if":1,"parameters":1,"called":1,"modify":1,"defined":1,"view":1}
,"if":{"script":1,"performed":1,"use":1,"defining":1,"external":1}
,"calls":{"script":1,"view":1}
,"called":{"script":1,"perform":1}
,"independent":{"parameters":1}
,"duration":{"script":1}
,"reset":{"each":1}
,"each":{"time":1}
,"performed":{"modified":1,"external":1}
,"modified":{"script":1}
,"sub-scripts":{"by":1}
,"changing":{"parameters":1}
,"modify":{"value":1}
,"value":{"parameters":1,"customer":1}
,"returned":{"get":1,"new":1}
,"contain":{"multiple":1}
,"multiple":{"values":1}
,"values":{"separated":1}
,"separated":{"by":1}
,"carriage":{"returns":1}
,"returns":{"use":1,"original":1}
,"leftvalues":{"function":1}
,"middlevalues":{"function":1}
,"rightvalues":{"function":1}
,"isolate":{"specific":1}
,"specific":{"parameter":1}
,"return":{"original":1}
,"original":{"file":1}
,"add":{"enter":1}
,"enter":{"browse":1}
,"browse":{"mode":1}
,"mode":{"step":1}
,"step":{"go":1,"right":1,"original":1}
,"go":{"layout":1}
,"layout":{"step":1,"[\u0022":1,"find":1,"invoice":1}
,"right":{"perform":1}
,"evaluate":{"data":1}
,"data":{"source":1,"api":1}
,"source":{"name":1,"script":1}
,"invoices":{":do":1,"current":1,":customer":1,"sub-script":1,"parameter":1,")]":1}
,":do":{"quarterly":1}
,"quarterly":{"billing":1}
,"billing":{"data":1}
,"names":{"case":1}
,"custom":{"menu":1,"web":1,"dialog":1}
,"menu":{"item":1,"scripts":1}
,"item":{"performs":1}
,"performs":{"script":1}
,"optional":{"script":1}
,"se":{"efining":1}
,"efining":{"custom":1}
,"run":{"via":1}
,"via":{"filemaker":1}
,"webdirect":{"filemaker":1}
,"api":{"custom":1}
,"web":{"publishing":1}
,"publishing":{"files":1}
,"files":{"scripts":1}
,"host":{"nd":1}
,"nd":{"extended":1}
,"extended":{"privileges":1}
,"privileges":{"enabled":1,"privilege":1}
,"enabled":{"permit":1}
,"permit":{"access":1}
,"ee":{"diting":1}
,"diting":{"extended":1}
,"privilege":{"set":1}
,"set":{"runtime":1}
,"runtime":{"solution":1}
,"solution":{"perform":1,"runs":1}
,"bound":{"solution":1}
,"runs":{"print":1}
,"print":{"invoice":1}
,"invoice":{"report":1}
,"report":{"script":1,"\u0022]":1,"parameter":1,"layout":1,"invoices":1}
,"[\u0022":{"invoice":1,"want":1}
,"\u0022]":{"perform":1}
,"[specified":{"list":1,"by":1}
,"field":{"value":1}
,"customer":{"name":1,"returned":1,"invoices":1,"&get":1}
,"current":{"customer":1}
,"new":{"window":1}
,"window":{"invoice":1,"[style":1}
,"find":{"matching":1}
,"matching":{"records":1}
,"[replace":{"invoices":1}
,":customer":{"id]":1,"name]":1}
,"id]":{"calls":1}
,"view":{"customer":1}
,"defined":{"perform":1}
,"name]":{"new":1}
,"[style":{"document":1}
,"document":{"name":1}
,"&get":{"scriptparameter":1,"lastmessagechoice":1}
,")]":{"sort":1}
,"sort":{"records":1}
,"[restore":{"dialog":1}
,"dialog":{"custom":1,"box":1,"[\u0022":1}
,"box":{"default":1}
,"default":{"button":1}
,"button":{"button":1,"performs":1,"&get":1}
,"named":{"button1":1}
,"button1":{"button2":1}
,"button2":{"depending":1}
,"depending":{"user\u2019s":1}
,"user\u2019s":{"choice":1}
,"choice":{"returned":1}
,"lastmessagechoice":{"show":1,"parameter":1}
,"show":{"custom":1}
,"continue":{"perform":1}
,"automating":{"tasks":1}
,"main":{"script":1}
}
;Search.control.loadWordPairs(pairs);
