var pairs =
{
"mporting":{"layout":1}
,"layout":{"themes":1,"access":1,"mode":1}
,"themes":{"import":1,"full":1,"layout":1,"manage":1,"dialog":1,"want":1}
,"import":{"themes":1,"select":1,"open":1,"imported":1,"theme":1}
,"full":{"layout":1}
,"access":{"privileges":1}
,"privileges":{"source":1,"diting":1,"open":1}
,"source":{"destination":1}
,"destination":{"files":1}
,"files":{"diting":1}
,"diting":{"record":1,"layouts":1}
,"record":{"access":1}
,"layouts":{"privileges":1,"menu":1}
,"open":{"file":1,"import":1}
,"file":{"theme":1,"menu":1,"themes":1,"located":1,"view":1}
,"theme":{"imported":1,"import":1,"filemaker":1}
,"imported":{"choose":1,"themes":1,"hen":1}
,"choose":{"file":1,"layouts":1}
,"menu":{"manage":1,"change":1}
,"manage":{"themes":1}
,"mode":{"choose":1}
,"change":{"theme":1}
,"dialog":{"box":1}
,"box":{"import":1,"select":1,"order":1}
,"select":{"file":1,"themes":1}
,"want":{"import":1}
,"order":{"imported":1}
,"hen":{"import":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"logs":1}
,"logs":{"entry":1}
,"entry":{"import.log":1}
,"import.log":{"file":1}
,"located":{"folder":1}
,"folder":{"database":1}
,"database":{"double-click":1}
,"double-click":{"log":1}
,"log":{"file":1,"entries":1}
,"view":{"log":1}
,"entries":{"import":1}
}
;Search.control.loadWordPairs(pairs);
