var pairs =
{
"pecifying":{"formats":1}
,"formats":{"container":1,"want":1}
,"container":{"fields":1,"interactively":1,"field":1,"use":1}
,"fields":{"control":1,"formatting":1,"inspector":1,"store":1,"portals":1,"movies":1}
,"control":{"filemaker":1,"preserve":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"displays":1,"affect":1}
,"displays":{"content":1}
,"content":{"container":1,"choose":1,"pdf":1,"field":1,"selected":1,"inserted":1}
,"formatting":{"options":1,"graphic":1}
,"options":{"choose":1,"set":1,"files":1}
,"choose":{"affect":1,"crop":1,"options":1,"horizontal":1,"images":1,"interactive":1,"preserve":1}
,"affect":{"display":1,"original":1}
,"display":{"filemaker":1,"each":1,"container":1,"white":1}
,"original":{"data":1,"size":1}
,"data":{"layout":1,"data":1,"tab":1,"formatting":1,"field":1,"stored":1}
,"layout":{"mode":1}
,"mode":{"select":1}
,"select":{"container":1,"formats":1,"start":1,"interactive":1}
,"inspector":{"data":1}
,"tab":{"data":1}
,"graphic":{"graphic":1,"button":1}
,"button":{"select":1}
,"want":{"use":1}
,"use":{"display":1,"all":1,"option":1,"solid":1}
,"each":{"image":1}
,"image":{"original":1,"up":1,"stored":1,"transparent":1}
,"size":{"format":1}
,"format":{"list":1}
,"list":{"choose":1}
,"crop":{"frame":1}
,"frame":{"scale":1}
,"scale":{"each":1}
,"up":{"up":1,"depending":1}
,"depending":{"data":1}
,"field":{"fit":1,"boundaries":1,"interactive":1,"scroll":1,"play":1,"select":1,"optimized":1,"transparent":1,"use":1,"sure":1,"popover":1,"choose":1}
,"fit":{"field":1}
,"boundaries":{"format":1}
,"set":{"horizontal":1}
,"horizontal":{"vertical":1}
,"vertical":{"alignment":1,"alignments":1}
,"alignment":{"alignment":1,"choose":1}
,"alignments":{"optimize":1}
,"optimize":{"static":1,"interactive":1}
,"static":{"content":1}
,"images":{"jpeg":1,"formats":1}
,"jpeg":{"png":1}
,"png":{"optimize":1}
,"interactive":{"content":1,"container":1,"containers":1}
,"pdf":{"mp3":1,"inserted":1,"file":1,"transparency":1,"files":1,"command":1}
,"mp3":{"option":1}
,"option":{"selected":1,"container":1,"supported":1}
,"selected":{"field":1,"start":1,"background":1,"option":1}
,"interactively":{"files":1}
,"files":{"interactive":1,"by":1,"windows":1,"field":1,"stored":1,"pictures":1}
,"containers":{"pdf":1}
,"inserted":{"field":1,"container":1}
,"scroll":{"pages":1}
,"pages":{"zoom":1}
,"zoom":{"copy":1}
,"copy":{"text":1}
,"text":{"audio":1}
,"audio":{"file":1,"video":1}
,"file":{"video":1,"field":1,"container":1,"script":1}
,"video":{"file":1,"play":1,"files":1,"audio":1,"multimedia":1}
,"play":{"media":1,"fast-forward":1,"display":1,"control":1}
,"media":{"use":1,"type":1,"files":1}
,"all":{"controls":1}
,"controls":{"media":1}
,"type":{"pause":1,"content":1}
,"pause":{"play":1}
,"fast-forward":{"audio":1}
,"start":{"playback":1,"audio":1}
,"playback":{"automatically":1}
,"automatically":{"if":1}
,"if":{"option":1,"select":1,"plan":1,"installed":1,"interactive":1,"container":1,"add":1}
,"by":{"clicking":1}
,"clicking":{"play":1}
,"preserve":{"transparency":1,"pdf":1}
,"transparency":{"image":1,"option":1}
,"stored":{"pdf":1,"externally":1,"displayed":1}
,"optimized":{"static":1}
,"background":{"container":1,"fill":1}
,"transparent":{"image":1,"display":1}
,"white":{"if":1}
,"store":{"embedded":1}
,"embedded":{"data":1}
,"externally":{"local":1}
,"local":{"references":1,"machine":1}
,"references":{"files":1}
,"windows":{"if":1}
,"plan":{"insert":1}
,"insert":{"pdf":1,"menu":1,"file":1}
,"sure":{"web":1}
,"web":{"browser":1}
,"browser":{"plug-in":1}
,"plug-in":{"adobe":1}
,"adobe":{"reader":1}
,"reader":{"installed":1}
,"installed":{"local":1,"insert":1}
,"machine":{"if":1}
,"menu":{"pdf":1}
,"command":{"unavailable":1}
,"unavailable":{"if":1}
,"supported":{"container":1,"if":1}
,"portals":{"supported":1}
,"popover":{"portal":1}
,"portal":{"customize":1}
,"customize":{"type":1}
,"displayed":{"compressed":1}
,"compressed":{"insert":1}
,"script":{"step":1}
,"step":{"if":1}
,"add":{"background":1}
,"fill":{"interactive":1,"adding":1,"baselines":1}
,"solid":{"color":1}
,"color":{"fill":1}
,"adding":{"borders":1}
,"borders":{"fill":1}
,"baselines":{"fields":1}
,"movies":{"songs":1}
,"songs":{"sound":1}
,"sound":{"clips":1}
,"clips":{"video":1}
,"multimedia":{"media":1}
,"pictures":{"graphics":1}
,"graphics":{"photos":1}
,"photos":{"images":1}
}
;Search.control.loadWordPairs(pairs);
