var pairs =
{
"tarting":{"runtime":1}
,"runtime":{"solution":1,"application":1}
,"solution":{"note":1,"if":1,"files":1,"file":1,"by":1,"auxiliary":1,"computers":1,"installed":1,"icon":1,"sure":1,"include":1}
,"note":{"feature":1}
,"feature":{"use":1}
,"use":{"advanced":1}
,"advanced":{"tools":1}
,"tools":{"general":1,"fter":1}
,"general":{"preference":1}
,"preference":{"selected":1}
,"selected":{"ad":1}
,"ad":{"vanced":1}
,"vanced":{"tools":1}
,"fter":{"user":1}
,"user":{"run":1,"double-clicks":1,"locate":1}
,"run":{"installation":1}
,"installation":{"program":1}
,"program":{"runtime":1}
,"application":{"files":1,"registered":1,"won\u2019t":1,"icon":1,"hard":1,"specific":1,"users":1,"runtime":1,"primary":1}
,"files":{"installed":1,"if":1,"result":1}
,"installed":{"user\u2019s":1,"attempt":1}
,"user\u2019s":{"hard":1}
,"hard":{"drive":1,"disk":1}
,"drive":{"solution\u2019s":1}
,"solution\u2019s":{"three-character":1}
,"three-character":{"filename":1,"extension":1}
,"filename":{"extension":1}
,"extension":{"registered":1,"runtime":1,"double-click":1}
,"registered":{"operating":1,"extension":1}
,"operating":{"system":1}
,"system":{"windows":1,"preferences":1,"locate":1}
,"windows":{"system":1}
,"preferences":{"macos":1}
,"macos":{"registration":1}
,"registration":{"allows":1}
,"allows":{"operating":1}
,"locate":{"launch":1,"primary":1}
,"launch":{"runtime":1}
,"if":{"user":1,"primary":1,"users":1,"relationships":1}
,"double-clicks":{"primary":1}
,"primary":{"auxiliary":1,"file":1}
,"auxiliary":{"solution":1,"files":1}
,"file":{"double-clicked":1,"icon":1,"first":1,"correct":1,"each":1,"bound":1,"can\u2019t":1,"caution":1}
,"double-clicked":{"runtime":1}
,"won\u2019t":{"found":1}
,"found":{"users":1,"user":1}
,"users":{"start":1,"solution":1,"double-click":1,"rename":1,"import":1}
,"start":{"solution":1,"runtime":1}
,"by":{"double-clicking":1}
,"double-clicking":{"runtime":1,"icons":1}
,"icon":{"solution":1,"double-clicking":1,"description":1,"runtime":1,"start":1}
,"icons":{"solution":1}
,"result":{"errors":1}
,"errors":{"depending":1}
,"depending":{"copies":1}
,"copies":{"runtime":1}
,"disk":{"if":1}
,"computers":{"associated":1}
,"associated":{"three-character":1}
,"double-click":{"icon":1}
,"first":{"solution":1}
,"attempt":{"open":1}
,"open":{"file":1}
,"correct":{"application":1}
,"specific":{"solutions":1}
,"solutions":{"file":1}
,"description":{"runtime":1}
,"each":{"time":1}
,"time":{"runtime":1}
,"bound":{"if":1}
,"can\u2019t":{"found":1}
,"caution":{"users":1}
,"rename":{"primary":1}
,"relationships":{"external":1}
,"external":{"scripts":1}
,"scripts":{"properly":1}
,"properly":{"change":1}
,"change":{"solution":1}
,"sure":{"users":1}
,"import":{"data":1}
,"data":{"updated":1,"new":1}
,"updated":{"solution":1}
,"include":{"script":1}
,"script":{"attached":1}
,"attached":{"button":1}
,"button":{"easy":1}
,"easy":{"users":1}
,"new":{"solution":1}
}
;Search.control.loadWordPairs(pairs);
