var pairs =
{
"umber":{"fields":1}
,"fields":{"use":1,"store":1,"by":1,"number":1,"numbers":1,"adding":1,"add":1}
,"use":{"number":1,"setprecision":1,"numbers":1,"text":1}
,"number":{"fields":1,"values":1,"phone":1,"format":1}
,"store":{"numeric":1,"numbers":1,"postal":1}
,"numeric":{"values":1,"order":1}
,"values":{"use":1,"combination":1,"leading":1}
,"numbers":{"sorted":1,"decimal":1,"calculation":1,"letters":1,"calculations":1,"values":1,"zip":1,"format":1,"add":1}
,"sorted":{"numeric":1}
,"order":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"ndexes":1,"erforms":1}
,"ndexes":{"first":1}
,"first":{"400":1}
,"400":{"digits":1}
,"digits":{"numbers":1,"precision":1}
,"decimal":{"points":1,"point":1,"separator":1}
,"points":{"signs":1}
,"signs":{"field":1}
,"field":{"ignoring":1,"changing":1,"2.45":1,"adding":1}
,"ignoring":{"letters":1}
,"letters":{"symbols":1,"special":1}
,"symbols":{"numbers":1}
,"calculation":{"formulas":1}
,"formulas":{"summary":1}
,"summary":{"fields":1}
,"by":{"default":1}
,"default":{"filemaker":1}
,"erforms":{"fixed-point":1}
,"fixed-point":{"math":1}
,"math":{"minimum":1}
,"minimum":{"16":1}
,"16":{"digits":1}
,"precision":{"right":1,"number":1}
,"right":{"decimal":1}
,"point":{"use":1}
,"setprecision":{"function":1}
,"function":{"further":1}
,"further":{"expand":1}
,"expand":{"precision":1}
,"combination":{"numbers":1}
,"special":{"characters":1}
,"characters":{"use":1,"hyphens":1,"displayed":1}
,"calculations":{"sorting":1}
,"sorting":{"$400":1}
,"$400":{"offer":1}
,"offer":{"use":1}
,"text":{"fields":1}
,"postal":{"codes":1}
,"codes":{"phone":1}
,"phone":{"numbers":1,"number":1}
,"leading":{"zeroes":1}
,"zeroes":{"characters":1}
,"hyphens":{"parentheses":1}
,"parentheses":{"characters":1}
,"displayed":{"decimal":1}
,"separator":{"thousands":1,"depend":1}
,"thousands":{"separator":1}
,"depend":{"system":1}
,"system":{"formats":1}
,"formats":{"set":1,"fields":1}
,"set":{"database":1}
,"database":{"file":1}
,"file":{"display":1}
,"display":{"format":1}
,"format":{"field":1,"phone":1}
,"changing":{"display":1}
,"2.45":{"$2.45":1}
,"$2.45":{"formats":1}
,"zip":{"code":1,"codes":1}
,"code":{"zip":1}
,"add":{"fields":1,"field":1}
,"adding":{"fields":1,"field":1}
}
;Search.control.loadWordPairs(pairs);
