var pairs =
{
"inding":{"empty":1}
,"empty":{"non-empty":1,"ields":1,"define":1,"repeating":1,"fields":1,"container":1}
,"non-empty":{"fields":1,"container":1}
,"fields":{"start":1,"enter":1,"formatted":1}
,"start":{"find":1}
,"find":{"request":1,"fields":1,"status":1,"empty":1}
,"request":{"aking":1,"find":1,"records":1,"ight-click":1}
,"aking":{"find":1}
,"enter":{"field":1}
,"field":{"empty":1,"table":1,"calculation":1,"layout":1,"perform":1,"show":1,"search":1,"find":1,"hoose":1}
,"ields":{"data":1}
,"data":{"*empty":1}
,"*empty":{"=2":1}
,"=2":{"perform":1}
,"perform":{"find":1}
,"status":{"toolbar":1}
,"toolbar":{"use":1}
,"use":{"methods":1,"getastext":1}
,"methods":{"define":1}
,"define":{"calculation":1,"script":1}
,"calculation":{"field":1,"use":1}
,"table":{"container":1,":container":1}
,"container":{"field":1,"fields":1}
,"getastext":{"function":1,"table":1}
,"function":{"getastext":1}
,":container":{"place":1,"omit":1}
,"place":{"calculation":1}
,"layout":{"container":1}
,"records":{"calculation":1,"omits":1,"go":1}
,"script":{"all":1}
,"all":{"records":1}
,"omits":{"each":1}
,"each":{"record":1}
,"record":{"non-empty":1,"else":1}
,"show":{"all":1}
,"go":{"record\u002Frequest\u002Fpage":1}
,"record\u002Frequest\u002Fpage":{"[first":1,"[next":1}
,"[first":{"loop":1}
,"loop":{"if":1}
,"if":{"[not":1,"end":1,"value":1}
,"[not":{"isempty":1}
,"isempty":{"table":1}
,"omit":{"record":1}
,"else":{"go":1}
,"[next":{"exit":1}
,"exit":{"last":1}
,"last":{"end":1}
,"end":{"if":1,"loop":1}
,"value":{"empty":1}
,"repeating":{"field":1}
,"search":{"\u0022=\u0022":1}
,"\u0022=\u0022":{"returns":1}
,"returns":{"field":1}
,"formatted":{"checkbox":1}
,"checkbox":{"set":1}
,"set":{"radio":1,"find":1}
,"radio":{"button":1}
,"button":{"set":1}
,"ight-click":{"field":1}
,"hoose":{"operators":1}
,"operators":{"choose":1}
,"choose":{"find":1}
}
;Search.control.loadWordPairs(pairs);
