var pairs =
{
"get":{"hostn":1,"hostname":1,"host":1,"server":1}
,"hostn":{"ame":1}
,"ame":{"returns":1}
,"returns":{"registered":1,"fred":1}
,"registered":{"name":1,"computer":1}
,"name":{"computer":1,"displayed":1,"host":1,"get":1,"function":1}
,"computer":{"hosting":1,"name":1,"use":1}
,"hosting":{"file":1}
,"file":{"get":1,"current":1}
,"hostname":{"none":1}
,"none":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"computer":1}
,"current":{"registered":1,"calculation":1,"window":1}
,"displayed":{"control":1}
,"control":{"panel":1}
,"panel":{"windows":1}
,"windows":{"system":1}
,"system":{"preferences":1}
,"preferences":{"macos":1}
,"macos":{"if":1}
,"if":{"current":1}
,"calculation":{"stored":1}
,"stored":{"context":1}
,"context":{"function":1,"evaluated":1,"current":1}
,"function":{"evaluated":1}
,"evaluated":{"based":1}
,"based":{"context":1}
,"window":{"returns":1}
,"fred":{"jones":1}
,"jones":{"fred":1,"registered":1}
,"host":{"computer":1,"name":1}
,"use":{"get":1}
,"server":{"name":1}
}
;Search.control.loadWordPairs(pairs);
