var pairs =
{
"financial":{"functions":1,"value":1}
,"functions":{"financial":1,"calculate":1}
,"calculate":{"financial":1,"monthly":1}
,"value":{"payments":1,"fv":1,"npv":1,"pv":1}
,"payments":{"calculate":1,"required":1,"made":1}
,"monthly":{"payments":1}
,"required":{"car":1}
,"car":{"loan":1}
,"loan":{"rate":1}
,"rate":{"pmt":1,"payment":1,"interval":1}
,"pmt":{"function":1,"payment":1,"equired":1}
,"function":{"function":1,"returns":1}
,"returns":{"fv":1}
,"fv":{"future":1,"initial":1}
,"future":{"value":1}
,"initial":{"investment":1}
,"investment":{"based":1}
,"based":{"constant":1}
,"constant":{"interest":1}
,"interest":{"rate":1,"ra":1}
,"payment":{"number":1,"pmt":1}
,"number":{"periods":1}
,"periods":{"months":1}
,"months":{"npv":1}
,"npv":{"value":1,"series":1}
,"series":{"unequal":1,"equal":1}
,"unequal":{"payments":1}
,"made":{"regular":1}
,"regular":{"intervals":1}
,"intervals":{"assuming":1}
,"assuming":{"fixed":1}
,"fixed":{"interest":1}
,"interval":{"pmt":1}
,"equired":{"by":1}
,"by":{"term":1}
,"term":{"interest":1}
,"ra":{"te":1}
,"te":{"principal":1}
,"principal":{"pv":1}
,"pv":{"value":1,"series":1}
,"equal":{"payments":1}
}
;Search.control.loadWordPairs(pairs);
