var pairs =
{
"orking":{"data":1}
,"data":{"table":1,"rows":1,"browse":1,"add":1,"new":1,"record":1,"delete":1,"reorder":1,"first":1}
,"table":{"view":1,"create":1,"definitions":1,"enter":1,"new":1,"if":1,"removes":1,"resetting":1,"doesn\u2019t":1,"table":1,"defining":1,"vie":1}
,"view":{"view":1,"records":1,"filemaker":1,"browse":1,"create":1,"current":1,"dialog":1,"right-click":1,"set":1,"properties":1,"edit":1,"restore":1,"reset":1,"settings":1,"select":1,"displays":1}
,"records":{"table":1,"by":1,"sorted":1,"dialog":1,"time":1,"delete":1,"menu":1,"right-click":1,"use":1,"options":1,"browse":1,"column":1,"related":1,"setting":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"displays":1,"creates":1}
,"displays":{"data":1,"record":1,"field":1,"fields":1}
,"rows":{"columns":1}
,"columns":{"spreadsheet":1,"order":1,"selected":1,"sorting":1,"drag":1,"select":1}
,"spreadsheet":{"each":1}
,"each":{"row":1,"column":1}
,"row":{"displays":1,"end":1,"last":1,"sorted":1,"duplicate":1,"adding":1,"portal":1,"table":1}
,"record":{"each":1,"blank":1,"bottom":1,"button":1,"right-click":1,"want":1,"copy":1,"paste":1,"delete":1,"choose":1,"first":1}
,"column":{"displays":1,"heading":1,"table":1,"choose":1,"headings":1,"width":1,"adding":1}
,"field":{"while":1,"first":1,"create":1,"column":1,"press":1,"name":1,"want":1,"names":1,"type":1,"field":1,"options":1,"multifield":1,"hide":1,"display":1,"table":1,"list":1,"right-click":1,"delete":1,"deleting":1,"definitions":1,"row":1,"adding":1,"placing":1,"layout":1,"order":1}
,"while":{"viewing":1}
,"viewing":{"data":1}
,"browse":{"mode":1}
,"mode":{"create":1,"add":1,"find":1,"reorder":1}
,"create":{"modify":1,"field":1,"additional":1,"automatically":1,"dynamic":1}
,"modify":{"delete":1,"fields":1,"layout":1,"table":1}
,"delete":{"fields":1,"field":1,"record":1,"choose":1,"multiple":1,"found":1,"all":1}
,"fields":{"note":1,"table":1,"column":1,"create":1,"current":1,"sort":1,"select":1,"remain":1,"hide":1,"modify":1,"delete":1,"darker":1,"body":1,"fields":1,"global":1,"reordering":1,"move":1,"changing":1,"records":1}
,"note":{"log":1,"resetting":1}
,"log":{"full":1}
,"full":{"access":1}
,"access":{"privilege":1}
,"privilege":{"set":1}
,"set":{"modify":1,"field":1,"precise":1,"column":1}
,"first":{"field":1,"column":1,"related":1,"row":1}
,"heading":{"first":1,"cancel":1,"field":1,"press":1,"filemaker":1,"choose":1,"optionally":1,"deselect":1,"want":1,"right-click":1,"sorted":1,"new":1,"right":1,"left":1}
,"additional":{"fields":1,"headings":1}
,"cancel":{"creating":1}
,"creating":{"new":1,"dynamic":1}
,"new":{"field":1,"fields":1,"name":1,"column":1,"record":1,"row":1,"location":1,"records":1}
,"press":{"esc":1,"tab":1}
,"esc":{"submitting":1,"exit":1}
,"submitting":{"change":1}
,"change":{"prevent":1,"field":1,"color":1}
,"prevent":{"new":1}
,"automatically":{"placed":1}
,"placed":{"current":1}
,"current":{"layout":1,"sort":1}
,"layout":{"by":1,"preferences":1,"bar":1,"if":1,"portal":1,"reorder":1}
,"by":{"deselecting":1,"fields":1,"right-click":1,"predefined":1,"value":1,"two":1}
,"deselecting":{"add":1}
,"add":{"newly":1,"new":1,"record":1,"field":1}
,"newly":{"defined":1}
,"defined":{"fields":1}
,"preferences":{"dialog":1,"change":1}
,"dialog":{"box":1}
,"box":{"etting":1,"displaying":1,"sorted":1,"sort":1}
,"etting":{"layout":1}
,"name":{"double-click":1,"discard":1,"press":1,"sort":1}
,"double-click":{"column":1}
,"want":{"rename":1,"remove":1,"duplicate":1,"copy":1,"delete":1}
,"rename":{"type":1}
,"type":{"new":1,"right-click":1,"display":1,"set":1}
,"discard":{"field":1}
,"exit":{"column":1}
,"tab":{"shift-tab":1,"-r":1}
,"shift-tab":{"edit":1}
,"edit":{"field":1,"table":1,"properties":1,"global":1}
,"names":{"if":1}
,"if":{"press":1,"select":1,"records":1,"keep":1,"customized":1,"layout":1}
,"-r":{"ight":1}
,"ight":{"column":1}
,"creates":{"new":1}
,"choose":{"field":1,"sort":1,"remove":1,"value":1,"unsort":1,"duplicate":1,"copy":1,"delete":1,"records":1,"table":1,"part":1,"color":1}
,"right-click":{"column":1,"selected":1,"heading":1,"choose":1,"left":1}
,"display":{"shortcut":1,"fields":1,"hidden":1,"background":1,"settings":1,"options":1}
,"shortcut":{"menu":1}
,"menu":{"choose":1,"delete":1,"edit":1,"if":1,"note":1}
,"options":{"right-click":1,"setting":1,"fields":1,"modify":1,"sorting":1,"table":1}
,"setting":{"options":1,"if":1,"display":1}
,"sort":{"records":1,"ascending":1,"descending":1,"icon":1,"setting":1,"order":1,"sort":1,"by":1,"file":1,"da":1,"status":1,"data":1}
,"select":{"column":1,"multiple":1,"unsorted":1,"right-click":1}
,"optionally":{"ctrl-click":1}
,"ctrl-click":{"windows":1}
,"windows":{"command-click":1}
,"command-click":{"macos":1}
,"macos":{"additional":1}
,"headings":{"right-click":1,"choose":1,"indicating":1}
,"selected":{"column":1,"determines":1,"field":1,"row":1}
,"ascending":{"sort":1}
,"descending":{"sort":1}
,"icon":{"appears":1}
,"appears":{"column":1}
,"indicating":{"sort":1}
,"multiple":{"columns":1,"records":1,"cells":1}
,"order":{"columns":1,"remove":1,"select":1,"choose":1,"re-sort":1,"sort":1,"unsort":1,"cleared":1,"fields":1}
,"determines":{"sort":1}
,"remove":{"field":1,"sort":1,"fields":1}
,"multifield":{"sort":1}
,"unsorted":{"heading":1}
,"deselect":{"columns":1}
,"sorting":{"by":1,"records":1}
,"predefined":{"value":1}
,"value":{"list":1}
,"list":{"select":1,"choose":1,"remove":1,"existing":1}
,"re-sort":{"sort":1}
,"file":{"by":1,"right-click":1,"choose":1}
,"two":{"fields":1}
,"da":{"ta":1}
,"ta":{"re-sorts":1}
,"re-sorts":{"based":1}
,"based":{"fields":1}
,"remain":{"sort":1}
,"status":{"toolbar":1}
,"toolbar":{"view":1}
,"unsort":{"file":1,"display":1}
,"sorted":{"file":1,"if":1,"order":1,"data":1,"category":1}
,"hide":{"fields":1,"field":1,"selected":1}
,"bar":{"use":1}
,"use":{"options":1,"sort":1}
,"displaying":{"hiding":1,"records":1}
,"hiding":{"fields":1}
,"hidden":{"field":1}
,"existing":{"fields":1}
,"deleting":{"table":1}
,"definitions":{"field":1,"data":1}
,"blank":{"record":1}
,"bottom":{"table":1}
,"enter":{"data":1}
,"button":{"left":1}
,"left":{"margin":1,"right":1}
,"margin":{"bottom":1,"record":1,"choose":1}
,"end":{"table":1}
,"keep":{"records":1}
,"cleared":{"sort":1}
,"last":{"row":1}
,"category":{"currently":1}
,"currently":{"selected":1}
,"duplicate":{"record":1,"choose":1}
,"right":{"margin":1,"left":1}
,"copy":{"data":1,"choose":1,"record":1}
,"paste":{"copied":1}
,"copied":{"tab-separated":1}
,"tab-separated":{"data":1}
,"time":{"yo":1}
,"yo":{"switch":1}
,"switch":{"find":1}
,"find":{"mode":1,"records":1,"request":1}
,"found":{"records":1}
,"all":{"aking":1}
,"aking":{"find":1}
,"request":{"sort":1}
,"reorder":{"columns":1,"resize":1,"fields":1}
,"drag":{"column":1}
,"location":{"set":1}
,"precise":{"column":1}
,"width":{"select":1,"shortcut":1}
,"properties":{"right-click":1,"change":1}
,"color":{"background":1,"shortcut":1,"color":1,"row":1,"display":1,"alternating":1,"alternate":1,"filled":1}
,"background":{"right-click":1,"color":1}
,"part":{"color":1,"image":1,"locked":1,"current":1}
,"adding":{"new":1,"field":1}
,"darker":{"main":1}
,"main":{"background":1}
,"alternating":{"records":1}
,"alternate":{"color":1}
,"customized":{"color":1}
,"filled":{"part":1}
,"image":{"part":1}
,"locked":{"create":1}
,"dynamic":{"report":1,"reports":1}
,"report":{"creating":1}
,"reports":{"table":1}
,"restore":{"default":1}
,"default":{"display":1}
,"settings":{"right-click":1,"appearance":1}
,"reset":{"shortcut":1}
,"resetting":{"table":1}
,"appearance":{"table":1}
,"removes":{"leading":1}
,"leading":{"trailing":1}
,"trailing":{"subtotals":1}
,"subtotals":{"fill":1}
,"fill":{"colors":1}
,"colors":{"table":1}
,"doesn\u2019t":{"impact":1}
,"impact":{"data":1}
,"resize":{"sort":1}
,"cells":{"table":1}
,"body":{"part":1}
,"portal":{"displaying":1,"ou":1}
,"related":{"table":1,"record":1}
,"ou":{"edit":1}
,"global":{"field":1,"fields":1,"storage":1}
,"defining":{"global":1}
,"storage":{"add":1}
,"placing":{"field":1}
,"reordering":{"fields":1}
,"move":{"fields":1}
,"changing":{"field":1}
}
;Search.control.loadWordPairs(pairs);
