var pairs =
{
"weekofyearfiscal":{"returns":1,"date":1}
,"returns":{"number":1,"weekofyearfiscal":1,"53":1}
,"number":{"53":1,"represents":1,"filemaker":1}
,"53":{"representing":1,"fiscal":1}
,"representing":{"week":1}
,"week":{"date":1,"first":1,"year":1,"days":1,"fiscal":1,"previous":1,"53":1}
,"date":{"starting":1,"startingday":1,"-any":1,"january":1,"2008":1,"2009":1}
,"starting":{"day":1,"date":1}
,"day":{"weekofyearfiscal":1,"considered":1,"week":1,"january":1,"fiscal":1}
,"startingday":{"date":1,"-any":1,"day":1}
,"-any":{"calendar":1,"number":1}
,"calendar":{"date":1}
,"represents":{"sunday":1}
,"sunday":{"number":1,"starting":1,"monday":1,"january":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"startingday":1}
,"considered":{"first":1}
,"first":{"day":1,"week":1}
,"year":{"first":1,"if":1,"function":1,"returned":1,"2008":1,"2009":1}
,"days":{"year":1}
,"if":{"select":1,"2008":1}
,"select":{"sunday":1,"monday":1}
,"january":{"sunday":1,"monday":1,"2009":1,"thursday":1,"selected":1}
,"monday":{"tuesday":1,"starting":1}
,"tuesday":{"wednesday":1}
,"wednesday":{"week":1,"thursday":1}
,"fiscal":{"year":1}
,"thursday":{"week":1,"first":1}
,"function":{"dates":1}
,"dates":{"year":1}
,"returned":{"53rd":1}
,"53rd":{"week":1}
,"previous":{"year":1}
,"2008":{"selected":1,"2009":1,"returns":1}
,"selected":{"sunday":1}
,"2009":{"occur":1,"january":1,"sunday":1,"returns":1}
,"occur":{"week":1}
}
;Search.control.loadWordPairs(pairs);
