var pairs =
{
"sp":{"ecifying":1}
,"ecifying":{"formats":1}
,"formats":{"fields":1,"want":1,"decimals":1,"file":1,"field":1}
,"fields":{"nu":1,"calculation":1,"numeric":1,"inspector":1,"press":1}
,"nu":{"mber":1}
,"mber":{"layout":1}
,"layout":{"mode":1,"field":1}
,"mode":{"select":1,"entire":1}
,"select":{"number":1,"general":1,"entered":1,"boolean":1,"decimal":1,"fixed":1,"percent":1,"currency":1,"display":1,"system":1,"text":1}
,"number":{"fields":1,"number":1,"button":1,"fits":1,"format":1,"select":1,"decimals":1,"type":1,"zero":1,"if":1,"10":1,"scientific":1,"expressed":1,"field":1,"decimal":1,"calculations":1}
,"calculation":{"fields":1,"summary":1}
,"numeric":{"summary":1,"value":1,"content":1}
,"summary":{"fields":1,"numeric":1}
,"inspector":{"data":1,"text":1,"apply":1,"display":1}
,"data":{"data":1,"tab":1,"formatting":1,"display":1}
,"tab":{"data":1,"inspector":1}
,"formatting":{"number":1,"select":1,"numbers":1,"field":1}
,"button":{"choose":1}
,"choose":{"formats":1,"options":1,"notation":1,"character":1,"4th":1,"display":1}
,"want":{"use":1}
,"use":{"format":1,"field":1}
,"format":{"list":1,"select":1,"choose":1,"field":1,"produces":1,"boolean":1,"number":1,"numbers":1}
,"list":{"display":1,"insert":1}
,"display":{"numbers":1,"field":1,"unit":1,"number":1,"type":1,"text":1,"blank":1}
,"numbers":{"rounded":1,"change":1,"formatted":1,"displayed":1,"format":1,"formatting":1}
,"rounded":{"expressed":1,"number":1}
,"expressed":{"scientific":1,"two":1,"power":1}
,"scientific":{"notation":1}
,"notation":{"number":1,"list":1,"color":1,"options":1,"rounds":1,"decimal":1}
,"fits":{"default":1}
,"default":{"field":1,"values":1}
,"field":{"boundaries":1,"appears":1,"format":1,"value":1,"enlarging":1,"displaying":1,"if":1,"formatted":1,"select":1,"calculation":1,"contain":1,"content":1,"formatting":1,"objects":1,"formats":1,"setup":1}
,"boundaries":{"format":1,"number":1,"layout":1,"truncates":1}
,"general":{"entered":1,"format":1}
,"entered":{"if":1,"boolean":1}
,"if":{"value":1,"number":1,"zero":1,"you\u2019re":1,"general":1,"fit":1,"field":1,"filemaker":1,"enter":1,"fixed":1,"-2":1,"use":1,"format":1}
,"value":{"digits":1,"value":1,"expressed":1,"up":1,"displayed":1,"positive":1,"specifies":1,"by":1,"number":1,"print":1,"if":1,"abc":1}
,"digits":{"display":1,"include":1,"filemaker":1,"general":1,"fit":1,"numbers":1,"exceeds":1,"if":1,"789.780":1,"790":1,"800":1}
,"appears":{"field":1}
,"boolean":{"value":1,"change":1,"values":1}
,"two":{"values":1}
,"values":{"zero":1,"type":1,"number":1}
,"zero":{"non-zero":1,"format":1,"current":1}
,"non-zero":{"format":1}
,"change":{"default":1,"decimal":1}
,"type":{"new":1,"value":1,"symbol":1,"if":1,"text":1}
,"new":{"value":1}
,"up":{"characters":1}
,"characters":{"show":1,"format":1}
,"show":{"non-zeros":1,"zeros":1}
,"non-zeros":{"show":1}
,"zeros":{"decimal":1}
,"decimal":{"number":1,"each":1,"place":1,"separator":1,"select":1,"digits":1,"except":1,"points":1,"point":1}
,"each":{"value":1}
,"displayed":{"number":1,"1.2346e":1,"printed":1}
,"fixed":{"number":1,"digits":1}
,"decimals":{"type":1,"thousands":1,"rounded":1}
,"positive":{"value":1}
,"specifies":{"right":1,"left":1}
,"right":{"decimal":1}
,"place":{"negative":1,"full":1}
,"negative":{"value":1,"numbers":1}
,"left":{"unit":1}
,"unit":{"number":1,"choose":1}
,"symbol":{"display":1,"choose":1}
,"options":{"notation":1,"percentage":1,"appearance":1}
,"insert":{"symbol":1}
,"color":{"negative":1}
,"separator":{"haracter":1,"kanji":1,"choose":1,"thousands":1,"based":1}
,"haracter":{"choose":1}
,"character":{"hat":1}
,"hat":{"separates":1}
,"separates":{"thousands":1}
,"thousands":{"digits":1,"separators":1,"separator":1}
,"include":{"ka":1}
,"ka":{"nji":1}
,"nji":{"separator":1}
,"kanji":{"separator":1}
,"4th":{"place":1}
,"full":{"notation":1}
,"percentage":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"ultiplies":1,"displays":1,"prints":1,"stores":1}
,"ultiplies":{"value":1}
,"by":{"100":1}
,"100":{"displays":1}
,"displays":{"format":1,"decimal":1,"number":1}
,"percent":{"currency":1}
,"currency":{"format":1,"if":1}
,"current":{"system":1}
,"system":{"formats":1,"settings":1}
,"separators":{"separators":1,"select":1,"notations":1}
,"settings":{"filemaker":1}
,"based":{"current":1}
,"file":{"japanese":1}
,"japanese":{"numeral":1,"characters":1}
,"numeral":{"type":1}
,"you\u2019re":{"font":1}
,"font":{"japanese":1}
,"text":{"formatting":1,"options":1,"formats":1,"symbols":1}
,"appearance":{"appearance":1,"tab":1}
,"press":{"enter":1}
,"enter":{"tab":1,"789.78":1}
,"apply":{"if":1}
,"10":{"digits":1,"123,456,789,000":1}
,"rounds":{"number":1}
,"fit":{"10-character":1,"field":1}
,"10-character":{"maximum":1}
,"maximum":{"default":1}
,"power":{"10":1}
,"123,456,789,000":{"displayed":1}
,"1.2346e":{"11":1}
,"11":{"if":1}
,"produces":{"result":1}
,"result":{"entered":1}
,"enlarging":{"field":1}
,"entire":{"value":1}
,"print":{"layout":1}
,"displaying":{"filemaker":1}
,"prints":{"digits":1}
,"truncates":{"digits":1}
,"formatted":{"decimals":1,"decimal":1}
,"exceeds":{"fixed":1}
,"789.78":{"fixed":1}
,"789.780":{"field":1}
,"790":{"if":1}
,"-2":{"fixed":1}
,"800":{"filemaker":1}
,"stores":{"unrounded":1}
,"unrounded":{"number":1}
,"calculations":{"summaries":1,"commas":1}
,"summaries":{"numbers":1}
,"printed":{"number":1}
,"except":{"separators":1}
,"notations":{"inspector":1}
,"symbols":{"@1.98":1}
,"@1.98":{"pound":1}
,"pound":{"number":1}
,"contain":{"non-numeric":1,"numeric":1}
,"non-numeric":{"data":1,"field":1}
,"blank":{"contain":1,"non-numeric":1}
,"content":{"value":1,"returns":1}
,"abc":{"display":1}
,"returns":{"false":1}
,"false":{"calculations":1}
,"commas":{"decimal":1}
,"points":{"comma":1}
,"comma":{"number":1}
,"point":{"number":1}
,"objects":{"field":1}
,"setup":{"number":1}
}
;Search.control.loadWordPairs(pairs);
