var pairs =
{
"rganize":{"records":1}
,"records":{"by":1,"panel":1,"container":1,"categorizing":1,"delete":1}
,"by":{"category":1,"if":1,"region":1,"city":1,"all":1,"fields":1,"changing":1}
,"category":{"new":1}
,"new":{"layout\u002Freport":1,"position":1}
,"layout\u002Freport":{"assistant":1,"panel":1}
,"assistant":{"panel":1,"ou":1,"saves":1,"displays":1,"filemaker":1,"modify":1}
,"panel":{"new":1,"if":1,"next":1,"filemaker":1,"subsummaries":1,"assistant":1}
,"ou":{"select":1}
,"select":{"break":1,"checkboxes":1}
,"break":{"fields":1,"field":1}
,"fields":{"want":1,"determines":1,"double-click":1,"chose":1,"body":1,"include":1,"report":1,"selected":1,"change":1,"shades":1,"choose":1,"based":1,"break":1,"dimmed":1,"each":1}
,"want":{"categorize":1,"group":1,"order":1,"hierarchy":1,"display":1,"prevent":1,"remove":1,"filemaker":1,"summary":1}
,"categorize":{"report":1}
,"report":{"by":1,"categories":1,"fields":1,"report":1,"hide":1,"note":1,"grouped":1,"remove":1,"detail":1}
,"if":{"sales":1,"want":1,"add":1}
,"sales":{"data":1}
,"data":{"want":1,"by":1,"report":1,"subset":1}
,"group":{"by":1,"sales":1,"records":1}
,"region":{"choose":1,"field":1,"by":1}
,"choose":{"region":1,"report":1,"panel":1,"up":1}
,"field":{"report":1,"first":1,"include":1,"back":1,"want":1,"name":1,"add":1,"appears":1,"detail":1}
,"categories":{"order":1,"if":1,"list":1,"double-click":1,"drag":1,"image":1,"pre":1,"choose":1}
,"order":{"break":1,"want":1}
,"determines":{"hierarchy":1}
,"hierarchy":{"nesting":1,"note":1,"grouping":1,"want":1}
,"nesting":{"categories":1}
,"city":{"choose":1,"field":1}
,"first":{"city":1}
,"include":{"break":1,"report":1,"subtotals":1}
,"double-click":{"fields":1,"field":1}
,"note":{"fields":1,"data":1}
,"chose":{"previous":1,"include":1}
,"previous":{"panel":1}
,"add":{"field":1,"filemaker":1}
,"back":{"assistant":1}
,"saves":{"choices":1}
,"choices":{"all":1,"assistant":1}
,"all":{"preceding":1,"fields":1}
,"preceding":{"panels":1}
,"panels":{"display":1}
,"display":{"break":1,"body":1}
,"body":{"report":1,"part":1}
,"list":{"select":1,"clear":1,"non-selected":1}
,"checkboxes":{"break":1,"next":1}
,"hide":{"break":1}
,"clear":{"checkboxes":1}
,"next":{"fields":1,"field":1,"chose":1}
,"prevent":{"appearing":1}
,"appearing":{"body":1}
,"grouped":{"by":1}
,"non-selected":{"fields":1}
,"remove":{"fields":1,"change":1}
,"selected":{"report":1,"break":1}
,"change":{"order":1,"hierarchy":1,"number":1}
,"grouping":{"report":1}
,"drag":{"double-arrow":1,"field":1}
,"double-arrow":{"next":1}
,"name":{"windows":1,"macos":1}
,"windows":{"drag":1}
,"macos":{"new":1}
,"position":{"change":1}
,"number":{"break":1}
,"image":{"right":1}
,"right":{"reflect":1}
,"reflect":{"choices":1}
,"displays":{"selected":1}
,"shades":{"blue":1}
,"blue":{"help":1}
,"help":{"judge":1}
,"judge":{"hierarchy":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"automatically":1,"subsummarize":1,"term":1,"adds":1}
,"automatically":{"sorts":1}
,"sorts":{"report":1}
,"pre":{"elected":1}
,"elected":{"sort":1}
,"sort":{"records":1}
,"subtotals":{"new":1,"panel":1,"averages":1}
,"subsummarize":{"fields":1}
,"based":{"report":1}
,"subsummaries":{"subtotals":1}
,"term":{"subsummary":1}
,"subsummary":{"include":1,"part":1}
,"averages":{"counts":1}
,"counts":{"summary":1}
,"summary":{"data":1,"fields":1,"report":1}
,"subset":{"records":1}
,"container":{"calculation":1}
,"calculation":{"summary":1}
,"dimmed":{"report":1}
,"up":{"10":1}
,"10":{"break":1}
,"each":{"break":1}
,"adds":{"subsummary":1}
,"part":{"layout":1,"each":1,"set":1,"se":1,"if":1,"finish":1}
,"layout":{"finish":1,"part":1}
,"finish":{"assistant":1}
,"modify":{"characteristics":1}
,"characteristics":{"pagination":1}
,"pagination":{"page":1}
,"page":{"numbering":1}
,"numbering":{"hanging":1}
,"hanging":{"layout":1}
,"appears":{"group":1}
,"categorizing":{"leading":1}
,"leading":{"subsummary":1}
,"set":{"break":1}
,"detail":{"records":1}
,"changing":{"trailing":1}
,"trailing":{"subsummary":1}
,"se":{"hanging":1}
,"delete":{"body":1}
}
;Search.control.loadWordPairs(pairs);
