var pairs =
{
"log":{"returns":1,"number":1,"function":1,"100":1}
,"returns":{"base-10":1,"value":1,"log":1}
,"base-10":{"common":1}
,"common":{"logarithm":1}
,"logarithm":{"number":1}
,"number":{"log":1,"number":1,"-any":1,"filemaker":1,"positive":1}
,"-any":{"positive":1}
,"positive":{"numeric":1,"value":1}
,"numeric":{"expression":1}
,"expression":{"field":1,"number":1}
,"field":{"numeric":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"number":1}
,"value":{"negative":1,"acceptable":1}
,"negative":{"values":1}
,"values":{"return":1}
,"return":{"error":1}
,"error":{"log":1}
,"function":{"returns":1}
,"acceptable":{"range":1}
,"range":{"equation":1}
,"equation":{"log":1}
,"100":{"returns":1}
}
;Search.control.loadWordPairs(pairs);
