var pairs =
{
"choose":{"returns":1,"test":1,"ordinal":1,"function":1,"rating":1}
,"returns":{"result":1,"applicable":1}
,"result":{"value":1,"test":1,"access":1,"result":1,"-one":1,"choose":1,"if":1,"fair":1,"poor":1,"parameters":1}
,"value":{"integer":1,"test":1,"if":1,"map":1}
,"integer":{"value":1,"calculation":1}
,"test":{"choose":1,"result0":1,"-any":1,"number":1,"result":1,"obtain":1,"evaluates":1}
,"result0":{"result1":1}
,"result1":{"result2":1}
,"result2":{"test":1,"chosen":1}
,"-any":{"integer":1}
,"calculation":{"calculation":1,"result":1}
,"number":{"indexes":1,"date":1,"choose":1,"field":1}
,"indexes":{"list":1}
,"list":{"index":1,"first":1,"indexed":1}
,"index":{"0-based":1,"test":1,"number":1}
,"0-based":{"index":1,"list":1}
,"access":{"first":1}
,"first":{"result":1,"item":1}
,"-one":{"parameters":1}
,"parameters":{"braces":1,"choose":1}
,"braces":{"optional":1}
,"optional":{"text":1}
,"text":{"number":1}
,"date":{"time":1}
,"time":{"timestamp":1}
,"timestamp":{"container":1}
,"container":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1,"advanced":1}
,"6.0":{"earlier":1}
,"earlier":{"filemaker":1}
,"advanced":{"evaluates":1}
,"evaluates":{"test":1,"result2":1}
,"obtain":{"index":1}
,"ordinal":{"result":1}
,"function":{"0-based":1,"returns":1}
,"item":{"list":1}
,"indexed":{"second":1,"if":1}
,"second":{"item":1}
,"if":{"test":1,"rating":1,"result":1}
,"chosen":{"choose":1}
,"rating":{"applicable":1,"number":1,"empty":1,"result":1,"value":1}
,"applicable":{"fair":1,"if":1}
,"fair":{"poor":1,"if":1}
,"poor":{"rating":1,"if":1}
,"field":{"empty":1}
,"empty":{"holds":1,"choose":1}
,"holds":{"value":1}
,"map":{"result":1}
}
;Search.control.loadWordPairs(pairs);
