var pairs =
{
"onwindowopen":{"performs":1,"activates":1}
,"performs":{"script":1}
,"script":{"ach":1,"trigger":1,"triggers":1,"open":1,"relationship":1,"runs":1}
,"ach":{"time":1}
,"time":{"open":1}
,"open":{"window":1}
,"window":{"database":1,"onfirstwindowopen":1,"hidden":1}
,"database":{"file":1}
,"file":{"window":1,"via":1}
,"onfirstwindowopen":{"script":1}
,"trigger":{"if":1,"script":1,"result":1}
,"if":{"selected":1}
,"selected":{"script":1}
,"triggers":{"tab":1}
,"tab":{"activated":1}
,"activated":{"onwindowopen":1}
,"activates":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1,"12.0":1}
,"advanced":{"enters":1}
,"enters":{"mode":1}
,"mode":{"none":1}
,"none":{"filemaker":1}
,"12.0":{"trigger":1}
,"hidden":{"file":1}
,"via":{"script":1}
,"relationship":{"script":1}
,"runs":{"modes":1}
,"modes":{"trigger":1}
}
;Search.control.loadWordPairs(pairs);
