var pairs =
{
"get":{"activefieldcon":1,"activefieldcontents":1,"active":1,"field":1}
,"activefieldcon":{"tents":1}
,"tents":{"returns":1}
,"returns":{"contents":1,"someshop":1}
,"contents":{"field":1,"active":1,"get":1,"getactivefieldcontents":1}
,"field":{"focus":1,"function":1,"depends":1,"result":1,"field":1,"data":1,"contents":1}
,"focus":{"get":1,"repeating":1,"name":1}
,"activefieldcontents":{"none":1,"calculation":1,"get":1}
,"none":{"text":1}
,"text":{"number":1}
,"number":{"date":1}
,"date":{"time":1}
,"time":{"timestamp":1}
,"timestamp":{"container":1}
,"container":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"focus":1}
,"repeating":{"field":1}
,"function":{"returns":1,"type":1}
,"active":{"repetition":1,"field":1}
,"repetition":{"result":1}
,"result":{"type":1}
,"type":{"active":1,"assigned":1,"calculation":1}
,"depends":{"data":1}
,"data":{"type":1,"fields":1,"someshop":1}
,"assigned":{"get":1}
,"calculation":{"function":1,"if":1}
,"if":{"script":1}
,"script":{"want":1,"proceeds":1}
,"want":{"examine":1}
,"examine":{"data":1}
,"fields":{"script":1}
,"proceeds":{"returns":1}
,"someshop":{"focus":1,"get":1}
,"name":{"field":1}
}
;Search.control.loadWordPairs(pairs);
