var pairs =
{
"relationships":{"create":1,"database":1,"graph":1,"promote":1,"relationship":1,"one-to-many":1,"self-join":1,"type":1,"by":1,"match":1,"group":1,"determine":1,"types":1}
,"create":{"related":1,"relationship":1,"change":1,"file":1,"table":1}
,"related":{"tables":1,"create":1,"customer":1,"table":1,"records":1,"data":1,"match":1,"fields":1}
,"tables":{"define":1,"relationship":1,"related":1,"match":1,"design":1,"use":1}
,"define":{"relationship":1}
,"relationship":{"two":1,"established":1,"compares":1,"criteria":1,"create":1,"value":1,"determine":1,"successful":1,"type":1,"many-to-many":1,"relational":1,"lookup":1,"global":1,"fields":1}
,"two":{"tables":1,"types":1,"occurrences":1}
,"established":{"value":1}
,"value":{"field":1,"match":1,"student":1,"unique":1}
,"field":{"called":1,"relationship":1,"students":1,"classes":1,"field":1,"combination":1,"hold":1,"keys":1,"table":1,"by":1,"foreign":1,"uniquely":1,"customers":1,"invoice":1,"values":1,"tables":1,"record":1,"types":1,"lookup":1,"related":1}
,"called":{"match":1,"key":1}
,"match":{"field":1,"fields":1}
,"key":{"field":1,"type":1,"value":1,"table":1,"consist":1}
,"compares":{"value":1}
,"criteria":{"relationship":1,"record":1}
,"student":{"id":1}
,"id":{"field":1,"two":1,"invoices":1,"display":1}
,"students":{"table":1}
,"table":{"equals":1,"records":1,"match":1,"record":1,"key":1,"manage":1,"primary":1,"identifies":1,"values":1,"empty":1,"sales":1,"invoice":1,"each":1,"foreign":1,"it\u2019s":1,"customer":1,"display":1,"determine":1,"therefore":1,"indexed":1,"associated":1,"ee":1,"self-joining":1,"any-to-many":1,"use":1,"relationships":1,"limit":1}
,"equals":{"value":1}
,"classes":{"table":1}
,"records":{"two":1,"meet":1,"table":1}
,"change":{"view":1}
,"view":{"relationships":1,"related":1}
,"database":{"orking":1,"dialog":1,"customers":1,"filemaker":1,"systems":1,"supports":1}
,"orking":{"ith":1}
,"ith":{"relationships":1}
,"graph":{"match":1}
,"combination":{"fields":1}
,"fields":{"identifies":1,"two":1,"related":1,"field":1,"can\u2019t":1,"current":1,"relationship":1,"relationships":1}
,"identifies":{"record":1,"primary":1,"each":1}
,"record":{"table":1,"identifies":1,"customers":1,"current":1}
,"hold":{"dates":1,"values":1}
,"dates":{"compared":1}
,"compared":{"criteria":1}
,"determine":{"relationship":1,"related":1,"current":1}
,"successful":{"key":1}
,"type":{"match":1,"description":1,"relationship":1}
,"keys":{"usually":1,"primary":1,"don\u2019t":1,"table":1,"re":1}
,"usually":{"hold":1,"allow":1}
,"values":{"ids":1,"foreign":1,"originate":1,"match":1}
,"ids":{"product":1}
,"product":{"id":1}
,"types":{"keys":1,"text":1,"relationships":1}
,"primary":{"key":1,"keys":1}
,"unique":{"empty":1,"table":1}
,"empty":{"non-null":1,"null":1}
,"non-null":{"primary":1}
,"consist":{"field":1}
,"by":{"default":1,"intermediate":1}
,"default":{"create":1}
,"file":{"create":1}
,"manage":{"database":1}
,"dialog":{"box":1}
,"box":{"new":1}
,"new":{"table":1}
,"foreign":{"key":1,"keys":1}
,"don\u2019t":{"unique":1}
,"null":{"multiple":1}
,"multiple":{"foreign":1,"tables":1}
,"sales":{"database":1,"projections":1}
,"customers":{"table":1}
,"invoice":{"table":1,"matching":1,"customer":1}
,"each":{"use":1,"customer":1,"invoice":1}
,"use":{"customer":1,"match":1,"access":1}
,"customer":{"id":1,"purchase":1,"customer":1,"data":1}
,"uniquely":{"identify":1,"identifies":1}
,"identify":{"each":1}
,"purchase":{"customer":1}
,"originate":{"table":1}
,"it\u2019s":{"customers":1}
,"display":{"portal":1,"consistent":1}
,"portal":{"each":1}
,"matching":{"customer":1}
,"invoices":{"table":1}
,"consistent":{"customer":1,"data":1}
,"data":{"filemaker":1,"enforce":1,"resolve":1,"across":1,"users":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"searches":1,"upports":1}
,"searches":{"indexed":1,"relationships":1}
,"indexed":{"values":1,"match":1,"can\u2019t":1}
,"meet":{"relationship":1}
,"current":{"table":1,"inventory":1}
,"therefore":{"match":1}
,"text":{"number":1}
,"number":{"date":1}
,"date":{"time":1}
,"time":{"timestamp":1}
,"timestamp":{"calculation":1,"result":1}
,"calculation":{"text":1}
,"result":{"relationships":1}
,"promote":{"entry":1}
,"entry":{"consistent":1}
,"enforce":{"rules":1}
,"rules":{"database":1}
,"upports":{"types":1}
,"description":{"one-to-one":1}
,"one-to-one":{"record":1,"relationships":1}
,"associated":{"record":1,"records":1}
,"ee":{"one-to-one":1,"ne-to-many":1}
,"one-to-many":{"many-to-one":1}
,"many-to-one":{"record":1}
,"ne-to-many":{"relationships":1}
,"self-join":{"primary":1}
,"re":{"defined":1}
,"defined":{"two":1}
,"occurrences":{"table":1}
,"self-joining":{"relationships":1}
,"many-to-many":{"relationship":1,"relationships":1}
,"relational":{"database":1}
,"systems":{"usually":1}
,"allow":{"implement":1}
,"implement":{"direct":1}
,"direct":{"many-to-many":1}
,"design":{"database":1}
,"supports":{"many-to-many":1}
,"intermediate":{"table":1}
,"any-to-many":{"relationships":1}
,"lookup":{"target":1,"based":1}
,"target":{"field":1}
,"based":{"relationship":1}
,"global":{"fields":1}
,"can\u2019t":{"indexed":1,"use":1}
,"group":{"data":1}
,"resolve":{"complex":1}
,"complex":{"searches":1}
,"inventory":{"levels":1}
,"levels":{"sales":1}
,"projections":{"tasks":1}
,"tasks":{"find":1}
,"find":{"data":1}
,"across":{"multiple":1}
,"access":{"privileges":1,"related":1}
,"privileges":{"source":1,"view":1}
,"source":{"table":1}
,"limit":{"prevent":1}
,"prevent":{"access":1}
,"users":{"access":1}
}
;Search.control.loadWordPairs(pairs);
