var pairs =
{
"diting":{"odbc":1,"value":1}
,"odbc":{"data":1,"tables":1,"apis":1,"client":1,"driver":1,"table":1,"jdbc":1,"administrators":1}
,"data":{"sources":1,"source":1,"external":1,"sql":1,"odbc":1,"filemaker":1,"access":1,"value":1,"type":1,"structured":1,"treat":1}
,"sources":{"odbc":1,"supported":1,"connect":1,"linked":1,"elect":1,"depends":1,"decide":1,"if":1,"add":1,"value":1,"field":1,"don\u2019t":1,"apply":1,"filemaker":1,"limitations":1}
,"source":{"filemaker":1,"via":1,"co":1,"list":1,"dsn":1,"set":1,"single":1,"catalog":1,"odbc":1,"choose":1,"if":1,"select":1,"move":1,"table":1,"copy":1,"storage":1,"etting":1}
,"filemaker":{"file":1,"tables":1,"connect":1,"pro":1,"table":1,"adds":1,"odbc":1,"automatically":1,"requires":1,"control":1,"files":1,"server":1,"clients":1,"use":1,"execute":1,"views":1}
,"file":{"access":1,"set":1,"menu":1,"prompted":1}
,"access":{"data":1,"table":1,"external":1,"odbc":1,"privilege":1}
,"external":{"odbc":1,"use":1,"data":1,"table":1,"tables":1,"sql":1,"database":1,"fields":1}
,"tables":{"view":1,"interactively":1,"filemaker":1,"views":1,"data":1,"all":1,"by":1,"relationships":1,"retrieve":1,"order":1,"tab":1,"want":1,"fields":1,"queries":1,"imported":1}
,"view":{"update":1,"options":1}
,"update":{"odbc":1,"filemaker":1,"delete":1}
,"interactively":{"relationships":1,"real":1}
,"relationships":{"graph":1,"tab":1,"created":1}
,"graph":{"view":1,"default":1,"layouts":1,"table":1,"orking":1,"identify":1,"filemaker":1,"tatic":1,"considerations":1}
,"connect":{"relational":1,"ata":1}
,"relational":{"database":1}
,"database":{"management":1,"files":1,"relationships":1,"dialog":1,"diting":1,"controls":1}
,"management":{"systems":1}
,"systems":{"rdbmss":1}
,"rdbmss":{"provide":1}
,"provide":{"odbc":1}
,"apis":{"external":1}
,"use":{"configuring":1,"variables":1,"windows":1,"sql":1}
,"configuring":{"odbc":1}
,"client":{"driver":1}
,"driver":{"list":1,"set":1,"add":1,"enhance":1}
,"list":{"data":1,"edit":1,"external":1,"all":1,"table":1,"tables":1,"enforce":1,"privileges":1}
,"supported":{"odbc":1,"by":1,"value":1,"prohibit":1,"binary":1,"you\u2019re":1,"setting":1}
,"ata":{"source":1,"sources":1}
,"via":{"odbc":1}
,"set":{"up":1,"edit":1,"authentication":1,"view":1,"updating":1,"semantics":1}
,"up":{"dsns":1,"calculations":1,"dsn":1,"machine":1,"odbc":1}
,"dsns":{"configuring":1}
,"add":{"dbc":1,"relationships":1,"update":1,"table":1,"color":1,"supplemental":1}
,"dbc":{"data":1,"imports":1}
,"co":{"nnecting":1}
,"nnecting":{"external":1}
,"linked":{"odbc":1}
,"pro":{"advanced":1}
,"advanced":{"file":1,"display":1,"representation":1,"determine":1}
,"edit":{"options":1,"ou":1,"odbc":1}
,"options":{"choose":1,"log":1,"authentication":1,"odbc":1,"supported":1,"fields":1,"auto-enter":1,"sync":1}
,"choose":{"file":1,"odbc":1}
,"menu":{"manage":1,"table":1}
,"manage":{"external":1,"database":1}
,"elect":{"odbc":1}
,"ou":{"change":1}
,"change":{"name":1,"schema":1,"field":1}
,"name":{"data":1,"password":1,"enabling":1,"enter":1,"tables":1,"list":1,"appears":1,"layout":1}
,"dsn":{"set":1,"access":1}
,"authentication":{"options":1,"default":1,"single":1}
,"log":{"named":1}
,"named":{"odbc":1}
,"default":{"option":1,"list":1,"datetime":1}
,"option":{"prompt":1}
,"prompt":{"user":1}
,"user":{"user":1,"name":1,"filemaker":1,"access":1,"odbc":1}
,"password":{"users":1,"first":1,"applies":1,"create":1,"odbc":1}
,"users":{"enter":1}
,"enter":{"user":1,"spn":1,"name":1}
,"first":{"time":1}
,"time":{"access":1,"choose":1,"data":1,"portion":1,"field":1}
,"table":{"if":1,"use":1,"name":1,"filter":1,"note":1,"interactively":1,"button":1,"dialog":1,"want":1,"appears":1,"relationships":1,"odbc":1,"header":1,"listed":1,"fields":1,"schema":1,"columns":1,"layout":1,"large":1,"result":1,"timestamp":1,"likewise":1}
,"if":{"don\u2019t":1,"shared":1,"prompted":1,"want":1,"filemaker":1,"imported":1,"import":1,"field":1}
,"don\u2019t":{"want":1,"inherent":1}
,"want":{"user":1,"enable":1,"include":1,"external":1,"add":1,"filemaker":1,"odbc":1,"access":1,"retain":1}
,"prompted":{"select":1,"enter":1}
,"select":{"user":1,"use":1,"table":1,"columns":1}
,"applies":{"all":1}
,"all":{"users":1,"tables":1,"catalogs":1,"schemas":1,"filter":1,"records":1}
,"create":{"calculation":1,"records":1,"views":1}
,"calculation":{"determine":1,"dialog":1}
,"determine":{"user":1,"tables":1,"table\u2019s":1}
,"variables":{"fields":1}
,"fields":{"calculations":1,"tab":1,"if":1,"odbc":1,"field":1,"defining":1}
,"calculations":{"calculation":1,"if":1,"summaries":1}
,"dialog":{"box":1}
,"box":{"setting":1,"add":1,"data":1,"field":1}
,"setting":{"up":1,"options":1}
,"shared":{"database":1}
,"files":{"access":1,"linked":1}
,"sql":{"server":1,"data":1,"database":1,"set":1,"join":1,"predicates":1}
,"server":{"want":1,"imestamp":1,"hosts":1,"filemaker":1,"by":1}
,"enable":{"odbc":1}
,"single":{"sign-on":1}
,"sign-on":{"select":1,"enter":1,"windows":1}
,"windows":{"authentication":1,"note":1}
,"spn":{"service":1}
,"service":{"principal":1}
,"principal":{"name":1}
,"enabling":{"odbc":1}
,"note":{"ilemaker":1,"want":1}
,"ilemaker":{"encrypts":1}
,"encrypts":{"passwords":1}
,"passwords":{"encryption":1}
,"encryption":{"ata":1,"supported":1}
,"depends":{"encryption":1}
,"by":{"odbc":1,"type":1,"external":1,"create":1,"default":1}
,"enhance":{"performance":1}
,"performance":{"filter":1,"sql":1}
,"filter":{"list":1,"by":1}
,"views":{"add":1,"system":1,"access":1,"views":1,"called":1}
,"catalog":{"name":1}
,"catalogs":{"listed":1}
,"listed":{"schema":1,"table":1,"tables":1}
,"schema":{"name":1,"filemaker":1,"updating":1,"dbc":1}
,"schemas":{"listed":1}
,"type":{"tables":1,"options":1,"ot":1,"change":1,"timestamp":1}
,"system":{"table":1}
,"include":{"types":1}
,"types":{"deselect":1}
,"deselect":{"all":1}
,"layouts":{"filemaker":1}
,"retrieve":{"add":1}
,"delete":{"data":1}
,"real":{"time":1}
,"tab":{"manage":1,"table":1,"field":1,"auto-enter":1,"unique":1,"disabled":1}
,"button":{"table":1}
,"appears":{"relationships":1,"italics":1}
,"italics":{"linking":1,"columns":1,"remove":1}
,"linking":{"tables":1}
,"orking":{"ith":1}
,"ith":{"relationships":1}
,"identify":{"table":1,"easily":1}
,"move":{"pointer":1}
,"pointer":{"arrow":1}
,"arrow":{"table":1}
,"header":{"want":1}
,"color":{"odbc":1}
,"order":{"identify":1}
,"easily":{"add":1}
,"adds":{"layout":1}
,"layout":{"table":1,"pop-up":1,"objects":1,"if":1}
,"pop-up":{"menu":1}
,"columns":{"odbc":1,"removed":1,"comprise":1,"unique":1}
,"field":{"names":1,"options":1,"determined":1,"type":1,"date":1,"time":1,"primary":1}
,"names":{"italics":1}
,"remove":{"fields":1}
,"display":{"solution":1}
,"solution":{"columns":1}
,"removed":{"external":1}
,"representation":{"table\u2019s":1}
,"table\u2019s":{"schema":1,"primary":1}
,"updating":{"data":1}
,"decide":{"want":1}
,"tatic":{"dbc":1}
,"imports":{"overview":1}
,"overview":{"various":1}
,"various":{"odbc":1}
,"jdbc":{"filemaker":1}
,"automatically":{"determine":1}
,"primary":{"key":1}
,"key":{"select":1,"filemaker":1,"values":1}
,"comprise":{"unique":1}
,"unique":{"key":1,"value":1,"inconsistent":1}
,"requires":{"table":1}
,"value":{"each":1,"lists":1,"list":1,"copy":1,"disabled":1,"existing":1}
,"each":{"row":1,"related":1}
,"row":{"change":1}
,"supplemental":{"fields":1}
,"summaries":{"data":1}
,"lists":{"character":1,"odbc":1}
,"character":{"large":1}
,"large":{"objects":1,"table":1}
,"objects":{"clobs":1,"blobs":1,"filemaker":1}
,"clobs":{"text":1}
,"text":{"strings":1}
,"strings":{"supported":1}
,"privilege":{"limited":1,"supported":1}
,"limited":{"custom":1}
,"custom":{"privilege":1}
,"prohibit":{"user":1}
,"enforce":{"row-level":1}
,"row-level":{"security":1}
,"security":{"external":1}
,"privileges":{"sql":1}
,"imestamp":{"data":1}
,"ot":{"supported":1}
,"binary":{"large":1}
,"blobs":{"pictures":1}
,"pictures":{"sounds":1}
,"sounds":{"supported":1}
,"you\u2019re":{"external":1}
,"auto-enter":{"tab":1,"serial":1}
,"serial":{"numbers":1}
,"numbers":{"create":1}
,"records":{"commit":1,"external":1,"committed":1,"table":1}
,"commit":{"records":1}
,"controls":{"records":1}
,"committed":{"lookup":1}
,"lookup":{"related":1}
,"related":{"data":1,"table":1}
,"copy":{"next":1}
,"next":{"lower":1,"value":1}
,"lower":{"value":1}
,"disabled":{"validation":1,"maximum":1,"filemaker":1}
,"validation":{"tab":1,"options":1}
,"existing":{"value":1}
,"maximum":{"number":1}
,"number":{"characters":1}
,"characters":{"allowed":1}
,"allowed":{"field":1}
,"determined":{"by":1}
,"storage":{"tab":1}
,"control":{"validation":1}
,"administrators":{"set":1}
,"sync":{"operations":1}
,"operations":{"filemaker":1}
,"inherent":{"relationships":1}
,"created":{"odbc":1}
,"apply":{"conditional":1}
,"conditional":{"formatting":1}
,"formatting":{"data":1,"layout":1}
,"defining":{"conditional":1}
,"hosts":{"databases":1}
,"databases":{"linked":1}
,"clients":{"set":1}
,"machine":{"running":1}
,"running":{"filemaker":1}
,"semantics":{"queries":1}
,"queries":{"filemaker":1,"attempts":1}
,"execute":{"query":1}
,"query":{"each":1}
,"retain":{"sql":1}
,"join":{"behavior":1}
,"behavior":{"obtain":1}
,"obtain":{"sql":1}
,"predicates":{"group":1}
,"group":{"by":1}
,"called":{"irtual":1}
,"irtual":{"tables":1}
,"attempts":{"scroll":1}
,"scroll":{"entire":1}
,"entire":{"odbc":1}
,"result":{"slower":1}
,"slower":{"performance":1}
,"datetime":{"datetime2":1}
,"datetime2":{"smalldatetime":1}
,"smalldatetime":{"data":1}
,"imported":{"timestamp":1,"odbc":1}
,"timestamp":{"field":1,"shadow":1,"data":1}
,"shadow":{"field":1}
,"date":{"time":1,"field":1,"portion":1}
,"structured":{"specific":1}
,"specific":{"manner":1}
,"manner":{"if":1}
,"treat":{"timestamp":1}
,"portion":{"equal":1}
,"equal":{"12:00":1,"1900-01-01":1}
,"12:00":{"midnight":1}
,"midnight":{"all":1}
,"likewise":{"if":1}
,"import":{"odbc":1}
,"1900-01-01":{"january":1}
,"january":{"1900":1}
,"1900":{"all":1}
,"values":{"unique":1}
,"inconsistent":{"edit":1}
,"etting":{"up":1}
,"considerations":{"odbc":1}
,"limitations":{"odbc":1}
}
;Search.control.loadWordPairs(pairs);
