var pairs =
{
"object":{"oves":1,"current":1,"name":1,"active":1,"field":1,"assign":1,"layout":1,"tab":1,"selected":1,"[object":1}
,"oves":{"object":1}
,"current":{"layout":1}
,"layout":{"object":1,"naming":1,"want":1,"[\u0022":1,"parts":1,"background":1}
,"name":{"named":1,"identify":1,"each":1,"go":1,"first":1,"\u0022]":1,"invoice":1,"invoices":1}
,"named":{"object":1,"first":1}
,"active":{"current":1}
,"naming":{"objects":1}
,"objects":{"repetition":1,"layout":1}
,"repetition":{"optional":1,"go":1}
,"optional":{"choose":1}
,"choose":{"field\u0027s":1}
,"field\u0027s":{"repetition":1}
,"go":{"defaults":1,"if":1,"object":1,"layout":1}
,"defaults":{"option":1}
,"option":{"ignored":1}
,"ignored":{"if":1}
,"if":{"object":1,"script":1,"[invoices":1,"navigates":1}
,"field":{"filemaker":1,"popover":1,"named":1}
,"filemaker":{"pro":1}
,"pro":{"8.5":1}
,"8.5":{"script":1}
,"script":{"step":1}
,"step":{"object":1,"specifies":1}
,"identify":{"object":1}
,"assign":{"unique":1}
,"unique":{"object":1}
,"each":{"object":1}
,"want":{"go":1}
,"specifies":{"object":1,"field":1}
,"tab":{"panel":1,"control":1,"\u0022]":1,"unpaid":1,"tab":1}
,"panel":{"slide":1,"frontmost":1,"moves":1,"control":1}
,"slide":{"panel":1}
,"frontmost":{"anel":1}
,"anel":{"object":1}
,"selected":{"panel":1}
,"moves":{"front":1}
,"front":{"panel":1}
,"control":{"if":1,"depending":1}
,"popover":{"popover":1,"navigates":1}
,"navigates":{"text":1,"tabs":1,"paid":1}
,"text":{"field":1}
,"first":{"name":1}
,"[object":{"name":1}
,"\u0022]":{"navigates":1,"go":1,"else":1,"end":1}
,"tabs":{"tab":1}
,"[invoices":{":status":1}
,":status":{"=\u0022":1,"go":1}
,"=\u0022":{"paid":1,"unpaid":1}
,"paid":{"\u0022]":1,"tab":1}
,"invoice":{"statement":1,"payment":1,"details":1}
,"statement":{"tab":1}
,"else":{"if":1}
,"unpaid":{"\u0022]":1,"tab":1}
,"payment":{"tab":1}
,"end":{"if":1}
,"depending":{"value":1}
,"value":{"invoices":1}
,"invoices":{":status":1,":status]":1}
,"[\u0022":{"invoice":1}
,"details":{"\u0022]":1}
,":status]":{"editing":1}
,"editing":{"objects":1}
,"parts":{"layout":1}
,"background":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
