var pairs =
{
"eader":{"footer":1}
,"footer":{"new":1,"report":1,"add":1,"part":1,"ou":1,"maximum":1,"panel":1}
,"new":{"layout\u002Freport":1}
,"layout\u002Freport":{"assistant":1}
,"assistant":{"panel":1,"ou":1,"choose":1,"if":1}
,"panel":{"new":1,"assistant":1,"creating":1}
,"ou":{"text":1,"place":1}
,"text":{"want":1,"left-aligned":1,"font":1,"size":1,"custom":1,"dialog":1,"type":1,"add":1}
,"want":{"header":1,"location":1}
,"header":{"footer":1}
,"report":{"choose":1}
,"choose":{"text":1,"page":1,"current":1,"layout":1,"large":1,"custom":1,"logo":1,"file":1,"include":1}
,"left-aligned":{"right-aligned":1}
,"right-aligned":{"centered":1}
,"centered":{"header":1}
,"add":{"layout":1,"left":1,"center":1,"right":1}
,"layout":{"page":1,"mode":1,"name":1,"theme":1}
,"page":{"number":1,"height":1,"filemaker":1}
,"number":{"preview":1,"symbol":1,"current":1}
,"preview":{"print":1}
,"print":{"layout":1}
,"mode":{"page":1,"current":1}
,"symbol":{"pagenumber":1,"currentdate":1}
,"pagenumber":{"choose":1}
,"current":{"system":1,"date":1,"page":1}
,"system":{"date":1}
,"date":{"preview":1,"symbol":1,"layout":1}
,"currentdate":{"choose":1}
,"name":{"first":1,"text":1,"header":1,"entered":1,"change":1}
,"first":{"panel":1}
,"font":{"size":1}
,"size":{"larger":1,"size":1,"defined":1,"currently":1}
,"larger":{"1.5":1}
,"1.5":{"times":1}
,"times":{"currently":1}
,"currently":{"defined":1}
,"defined":{"text":1,"by":1}
,"by":{"layout":1}
,"theme":{"choose":1}
,"large":{"custom":1}
,"custom":{"text":1}
,"dialog":{"box":1}
,"box":{"custom":1,"choose":1}
,"type":{"want":1}
,"location":{"text":1,"graphic":1}
,"graphic":{"insert":1,"logo":1}
,"insert":{"choose":1,"open":1}
,"logo":{"dialog":1,"header":1,"one-quarter":1}
,"file":{"insert":1}
,"open":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"left-aligns":1,"name":1,"applies":1}
,"left-aligns":{"text":1}
,"left":{"positions":1}
,"positions":{"center-aligns":1,"right-aligns":1,"if":1}
,"center-aligns":{"text":1}
,"center":{"positions":1}
,"right-aligns":{"text":1}
,"right":{"positions":1}
,"if":{"choose":1,"change":1}
,"include":{"layout":1}
,"part":{"filemaker":1,"style":1}
,"entered":{"first":1}
,"change":{"layout":1,"reflected":1}
,"reflected":{"header":1}
,"place":{"graphic":1}
,"maximum":{"height":1,"width":1}
,"height":{"logo":1,"maximum":1}
,"one-quarter":{"current":1}
,"width":{"width":1,"current":1}
,"applies":{"header":1}
,"style":{"merge":1}
,"merge":{"fields":1}
,"fields":{"create":1}
,"create":{"header":1}
,"creating":{"styles":1}
,"styles":{"ayout":1}
,"ayout":{"heading":1}
,"heading":{"headings":1}
}
;Search.control.loadWordPairs(pairs);
