var pairs =
{
"onfirstwindowopen":{"performs":1,"activates":1}
,"performs":{"script":1}
,"script":{"ach":1,"trigger":1,"step":1,"script":1,"rigger":1,"file":1,"creates":1,"runs":1}
,"ach":{"time":1}
,"time":{"open":1}
,"open":{"window":1,"first":1,"file":1}
,"window":{"database":1,"file":1,"created":1,"relationship":1}
,"database":{"file":1}
,"file":{"windows":1,"open":1,"onfirstwindowopen":1,"manually":1,"script":1,"hidden":1,"activate":1,"if":1}
,"windows":{"file":1}
,"first":{"window":1}
,"activates":{"filemaker":1}
,"filemaker":{"pro":1,"go":1,"webdirect":1,"server":1,"cloud":1}
,"pro":{"advanced":1,"12.0":1}
,"advanced":{"enters":1,"filemaker":1}
,"enters":{"mode":1}
,"mode":{"none":1}
,"none":{"filemaker":1}
,"12.0":{"filemaker":1}
,"go":{"filemaker":1}
,"webdirect":{"script":1}
,"trigger":{"activated":1,"activate":1,"behaves":1,"result":1}
,"activated":{"first":1}
,"created":{"file":1,"performing":1}
,"manually":{"open":1}
,"step":{"if":1,"performing":1}
,"if":{"file":1,"script":1}
,"hidden":{"window":1}
,"relationship":{"script":1}
,"rigger":{"doesn\u2019t":1,"file":1}
,"doesn\u2019t":{"activate":1}
,"activate":{"window":1,"script":1,"file":1}
,"performing":{"script":1}
,"creates":{"first":1}
,"behaves":{"server-side":1}
,"server-side":{"scripts":1}
,"scripts":{"running":1,"filemaker":1}
,"running":{"scripts":1}
,"server":{"filemaker":1}
,"cloud":{"script":1}
,"runs":{"modes":1}
,"modes":{"trigger":1}
}
;Search.control.loadWordPairs(pairs);
