var pairs =
{
"defining":{"changing":1,"database":1,"fields":1}
,"changing":{"fields":1,"field":1}
,"fields":{"field":1,"current":1,"tab":1,"defined":1,"table":1,"layout":1,"add":1,"delete":1,"hoose":1,"naming":1,"sort":1,"fields":1,"list":1,"button":1,"you\u2019ve":1,"placed":1,"define":1,"creating":1,"defining":1,"change":1,"new":1,"changing":1,"remove":1,"deleting":1}
,"field":{"tab":1,"new":1,"button":1,"nd":1,"type":1,"position":1,"labels":1,"display":1,"name":1,"options":1,"right-click":1,"fields":1,"change":1,"field":1,"references":1,"list":1,"create":1,"define":1,"add":1,"remove":1,"removing":1,"delete":1}
,"tab":{"yo":1,"layout":1,"if":1}
,"yo":{"define":1}
,"define":{"fields":1,"field":1,"change":1}
,"current":{"layout":1,"table":1}
,"layout":{"current":1,"mode":1,"layout":1,"pop-up":1,"field":1,"fields":1,"create":1,"preferences":1}
,"table":{"by":1,"use":1,"choose":1,"list":1}
,"by":{"fields":1}
,"mode":{"default":1,"choose":1}
,"default":{"fields":1}
,"defined":{"defining":1,"layout":1}
,"database":{"tables":1,"dialog":1,"drag":1}
,"tables":{"define":1,"list":1}
,"use":{"manage":1}
,"manage":{"database":1}
,"dialog":{"box":1}
,"box":{"defining":1,"if":1,"search":1,"tables":1}
,"choose":{"layout":1,"field":1,"new":1,"sort":1,"table":1,"manage":1}
,"pop-up":{"menu":1}
,"menu":{"objects":1,"checkbox":1}
,"objects":{"pane":1}
,"pane":{"button":1}
,"button":{"status":1,"ype":1,"choose":1,"display":1,"open":1}
,"status":{"toolbar":1}
,"toolbar":{"fields":1}
,"add":{"field":1,"fields":1}
,"new":{"field":1,"type":1,"fields":1}
,"ype":{"name":1}
,"name":{"field":1,"hoose":1,"elect":1,"type":1,"th":1,"changed":1,"search":1}
,"nd":{"choose":1}
,"type":{"if":1,"select":1,"choose":1,"rom":1,"change":1,"new":1,"field":1}
,"if":{"cl":1,"don\u2019t":1}
,"cl":{"ick":1}
,"ick":{"drag":1}
,"drag":{"preferences":1,"fields":1}
,"preferences":{"hange":1,"create":1}
,"hange":{"options":1}
,"options":{"field":1,"validation":1,"setting":1,"fields":1}
,"position":{"abels":1}
,"abels":{"control":1}
,"control":{"style":1,"change":1}
,"style":{"se":1}
,"se":{"adding":1}
,"adding":{"changing":1}
,"labels":{"setting":1}
,"setting":{"up":1,"options":1}
,"up":{"field":1}
,"display":{"pop-up":1,"fields":1}
,"checkbox":{"set":1}
,"set":{"control":1}
,"change":{"ield":1,"options":1,"field":1,"fields":1}
,"ield":{"type":1,"right-click":1}
,"select":{"field":1}
,"rom":{"list":1}
,"list":{"bout":1,"sort":1,"type":1,"top":1,"tables":1,"button":1,"choose":1}
,"bout":{"choosing":1}
,"choosing":{"field":1}
,"validation":{"auto":1}
,"auto":{"entry":1}
,"entry":{"storage":1}
,"storage":{"ield":1}
,"right-click":{"field":1}
,"hoose":{"field":1,"delete":1}
,"delete":{"field":1,"fields":1}
,"elect":{"field":1}
,"th":{"name":1}
,"changed":{"each":1}
,"each":{"layout":1}
,"references":{"calculation":1}
,"calculation":{"summary":1}
,"summary":{"fields":1}
,"naming":{"fields":1}
,"sort":{"fields":1,"order":1}
,"order":{"locate":1}
,"locate":{"field":1}
,"search":{"box":1,"fields":1}
,"don\u2019t":{"search":1,"tables":1}
,"top":{"tab":1}
,"open":{"manage":1}
,"you\u2019ve":{"defined":1}
,"placed":{"layout":1}
,"create":{"etting":1,"field":1,"fields":1}
,"etting":{"layout":1}
,"creating":{"fields":1}
,"remove":{"fields":1,"field":1}
,"removing":{"fields":1}
,"deleting":{"fields":1}
}
;Search.control.loadWordPairs(pairs);
