var pairs =
{
"onlayoutenter":{"performs":1}
,"performs":{"script":1}
,"script":{"fter":1,"rigger":1,"triggers":1,"trigger":1,"runs":1}
,"fter":{"layout":1}
,"layout":{"loaded":1,"changed":1}
,"loaded":{"event":1}
,"event":{"processed":1}
,"processed":{"browse":1}
,"browse":{"find":1}
,"find":{"preview":1}
,"preview":{"modes":1}
,"modes":{"none":1,"trigger":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"10.0":1}
,"10.0":{"script":1}
,"rigger":{"activate":1}
,"activate":{"if":1,"script":1}
,"if":{"layout":1}
,"changed":{"remotely":1}
,"remotely":{"actions":1}
,"actions":{"don\u2019t":1,"activate":1}
,"don\u2019t":{"activate":1}
,"triggers":{"list":1}
,"list":{"actions":1}
,"trigger":{"script":1,"result":1}
,"runs":{"modes":1}
}
;Search.control.loadWordPairs(pairs);
