var pairs =
{
"emoving":{"blank":1}
,"blank":{"spaces":1,"space":1}
,"spaces":{"printouts":1,"parts":1}
,"printouts":{"fields":1,"browse":1}
,"fields":{"database":1,"portals":1,"shrink":1,"slide":1,"left":1,"empty":1,"minimum":1,"sliding":1,"table":1,"use":1,"want":1,"value":1,"continuous":1,"text":1,"layout":1}
,"database":{"varies":1}
,"varies":{"print":1}
,"print":{"filemaker":1,"items":1,"note":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"shrink":1,"omits":1,"leaves":1,"prints":1}
,"shrink":{"field":1,"eliminate":1,"portals":1,"filemaker":1,"fields":1,"slide":1,"layout":1,"sliding":1,"inspector":1,"note":1}
,"field":{"boundaries":1,"fill":1,"boundary":1,"slide":1,"left":1,"non-field":1,"want":1,"shrinks":1,"objects":1,"formatted":1}
,"boundaries":{"shift":1,"field":1}
,"shift":{"objects":1}
,"objects":{"left":1,"layout":1,"slide":1,"horizontal":1,"non-field":1,"portal":1,"shrink":1,"want":1,"up":1,"reduce":1,"close":1,"set":1,"sliding":1,"remember":1,"use":1,"graphics":1,"objects":1,"parts":1,"relative":1}
,"left":{"up":1,"field":1,"objects":1,"based":1,"reduce":1}
,"up":{"layout":1,"blank":1,"space":1,"enclosing":1,"headers":1,"set":1,"based":1,"relative":1,"slide":1}
,"layout":{"close":1,"parts":1,"shrink":1,"requires":1,"mode":1,"part":1,"layout":1,"data":1,"resize":1}
,"close":{"up":1}
,"space":{"caused":1,"items":1,"field":1,"fields":1,"leave":1,"lowest":1,"layout":1}
,"caused":{"field":1}
,"fill":{"field":1}
,"boundary":{"catalog":1}
,"catalog":{"description":1}
,"description":{"item":1}
,"item":{"if":1}
,"if":{"use":1,"sliding":1,"portal":1,"create":1,"want":1}
,"use":{"sliding":1,"merge":1,"layout":1}
,"sliding":{"feature":1,"shrinking":1,"field":1,"remove":1,"options":1,"&visibility":1,"left":1,"up":1,"group":1,"inspector":1,"effects":1,"objects":1}
,"feature":{"close":1}
,"items":{"print":1,"page":1}
,"page":{"slide":1,"align":1}
,"slide":{"object":1,"fields":1,"if":1,"non-field":1,"up":1,"left":1,"part":1,"leftmost":1,"shrink":1,"all":1,"non-text":1,"directions":1,"objects":1}
,"object":{"including":1,"slide":1,"slides":1,"objects":1,"set":1,"print":1,"resize":1}
,"including":{"fields":1}
,"portals":{"objects":1,"slide":1}
,"parts":{"objects":1,"shrink":1,"if":1,"filemaker":1}
,"eliminate":{"empty":1}
,"empty":{"space":1,"portal":1,"spaces":1}
,"shrinking":{"field":1}
,"non-field":{"objects":1,"object":1}
,"horizontal":{"line":1}
,"line":{"text":1}
,"text":{"object":1,"mailing":1,"continuous":1,"form":1}
,"slides":{"moves":1,"up":1}
,"moves":{"place":1}
,"place":{"layout":1}
,"portal":{"slide":1,"slides":1,"rows":1}
,"enclosing":{"part":1}
,"part":{"shrink":1,"inch":1,"selected":1,"up":1,"effects":1,"fit":1}
,"omits":{"empty":1}
,"rows":{"set":1}
,"set":{"layout":1,"part":1,"all":1,"preview":1,"option":1,"choose":1,"sliding":1}
,"headers":{"footers":1,"itle":1}
,"footers":{"title":1,"top":1}
,"title":{"headers":1}
,"itle":{"footers":1}
,"top":{"navigation":1,"ost":1}
,"navigation":{"bottom":1,"parts":1}
,"bottom":{"navigation":1}
,"requires":{"fixed":1}
,"fixed":{"vertical":1}
,"vertical":{"spacing":1}
,"spacing":{"labels":1,"columns":1,"column":1}
,"labels":{"all":1,"slide":1}
,"all":{"objects":1,"selected":1}
,"remove":{"empty":1,"sliding":1}
,"leave":{"fields":1}
,"create":{"body":1}
,"body":{"part":1}
,"inch":{"space":1,"lowest":1}
,"lowest":{"object":1}
,"leaves":{"inch":1}
,"note":{"effects":1,"option":1}
,"effects":{"sliding":1,"by":1}
,"options":{"set":1,"want":1,"modify":1,"objects":1}
,"preview":{"mode":1,"se":1}
,"mode":{"printouts":1,"layout":1,"select":1,"choose":1}
,"browse":{"mode":1}
,"select":{"objects":1,"sliding":1,"option":1,"leftmost":1}
,"want":{"slide":1,"objects":1,"select":1,"change":1,"remove":1,"cases":1,"use":1}
,"leftmost":{"topmost":1,"top":1}
,"topmost":{"field":1}
,"inspector":{"lick":1,"position":1}
,"lick":{"position":1}
,"position":{"position":1,"tab":1}
,"tab":{"sliding":1}
,"&visibility":{"select":1,"deselect":1}
,"option":{"reduce":1,"maintains":1,"allows":1,"all":1,"object":1}
,"reduce":{"width":1,"height":1}
,"width":{"selected":1}
,"selected":{"fields":1,"objects":1}
,"minimum":{"data":1}
,"data":{"slide":1,"layout":1,"entry":1,"field":1}
,"based":{"space":1,"field":1,"all":1,"objects":1}
,"height":{"selected":1}
,"shrinks":{"note":1}
,"maintains":{"consistent":1}
,"consistent":{"vertical":1}
,"columns":{"repeating":1}
,"repeating":{"fields":1}
,"allows":{"spacing":1}
,"column":{"adjust":1}
,"adjust":{"independently":1}
,"independently":{"columns":1}
,"relative":{"all":1,"single":1,"each":1}
,"single":{"object":1}
,"resize":{"enclosing":1,"resizing":1}
,"choose":{"view":1}
,"view":{"menu":1}
,"menu":{"preview":1,"show":1}
,"se":{"previewing":1,"placing":1}
,"previewing":{"data":1}
,"change":{"if":1}
,"group":{"objects":1}
,"remember":{"select":1}
,"ost":{"field":1}
,"deselect":{"options":1}
,"cases":{"achieve":1}
,"achieve":{"sliding":1}
,"by":{"merge":1}
,"merge":{"fields":1,"field":1}
,"table":{"summarizes":1}
,"summarizes":{"use":1}
,"non-text":{"objects":1}
,"graphics":{"shrink":1}
,"fit":{"page":1}
,"align":{"formatted":1}
,"formatted":{"fields":1,"merge":1}
,"value":{"lists":1}
,"lists":{"repeating":1}
,"entry":{"enter":1}
,"enter":{"data":1}
,"continuous":{"block":1}
,"block":{"text":1}
,"mailing":{"labels":1}
,"form":{"letters":1}
,"letters":{"se":1}
,"placing":{"merge":1}
,"show":{"sliding":1}
,"directions":{"slide":1}
,"prints":{"objects":1}
,"each":{"precisely":1}
,"precisely":{"placed":1}
,"placed":{"layout":1}
,"resizing":{"set":1}
,"modify":{"remove":1}
}
;Search.control.loadWordPairs(pairs);
