var pairs =
{
"estoring":{"data":1}
,"data":{"records":1,"incorrectly":1,"record":1,"committed":1,"related":1}
,"records":{"by":1,"automatically":1,"choose":1,"menu":1,"displayed":1,"restore":1}
,"by":{"default":1}
,"default":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"saves":1}
,"saves":{"records":1}
,"automatically":{"commit":1}
,"commit":{"each":1,"record":1}
,"each":{"record":1,"time":1}
,"record":{"if":1,"restore":1,"committed":1,"data":1,"dimmed":1,"record":1,"removed":1,"specific":1,"made":1,"browse":1}
,"if":{"enter":1,"revert":1}
,"enter":{"data":1}
,"incorrectly":{"record":1}
,"restore":{"original":1,"record":1}
,"original":{"data":1}
,"committed":{"committing":1,"if":1}
,"committing":{"data":1,"hen":1}
,"choose":{"records":1}
,"menu":{"revert":1,"undo":1,"redo":1}
,"revert":{"record":1,"field":1}
,"dimmed":{"select":1}
,"select":{"edit":1}
,"edit":{"menu":1}
,"undo":{"revert":1,"edit":1}
,"field":{"efore":1}
,"efore":{"commit":1}
,"removed":{"incrementally":1}
,"incrementally":{"each":1,"enabling":1}
,"time":{"select":1}
,"redo":{"restores":1}
,"restores":{"incrementally":1}
,"enabling":{"restore":1}
,"specific":{"state":1}
,"state":{"made":1}
,"made":{"multiple":1,"related":1}
,"multiple":{"committing":1}
,"hen":{"revert":1}
,"related":{"data":1,"records":1}
,"displayed":{"portal":1}
,"portal":{"reverted":1}
,"reverted":{"committing":1}
,"browse":{"mode":1}
}
;Search.control.loadWordPairs(pairs);
