var pairs =
{
"getascss":{"returns":1,"text":1,"function":1}
,"returns":{"text":1,"result":1}
,"text":{"converted":1,"text":1,"-any":1,"expression":1,"field":1,"filemaker":1,"span":1,"returns":1,"word":1,"attributes":1}
,"converted":{"css":1}
,"css":{"cascading":1,"properties":1}
,"cascading":{"style":1}
,"style":{"sheets":1,"=bold":1,"=\u0022":1}
,"sheets":{"format":1}
,"format":{"getascss":1}
,"-any":{"text":1}
,"expression":{"text":1}
,"field":{"text":1}
,"filemaker":{"pro":1}
,"pro":{"7.0":1}
,"7.0":{"getascss":1}
,"span":{"element":1,"style":1}
,"element":{"css":1}
,"properties":{"getascss":1}
,"function":{"return":1}
,"return":{"formats":1}
,"formats":{"set":1}
,"set":{"conditional":1}
,"conditional":{"formatting":1}
,"formatting":{"dialog":1}
,"dialog":{"box":1}
,"box":{"getascss":1}
,"result":{"field":1}
,"word":{"frank":1}
,"frank":{"word":1,"text":1,"<\u002Fspan":1}
,"attributes":{"font":1}
,"font":{"=helvetica":1,"size":1,"color":1,"style":1}
,"=helvetica":{"font":1}
,"size":{"=12":1}
,"=12":{"points":1}
,"points":{"font":1}
,"color":{"=red":1,"ff0000":1}
,"=red":{"font":1}
,"=bold":{"span":1}
,"=\u0022":{"font-family":1}
,"font-family":{"\u0027helvetica":1}
,"\u0027helvetica":{"font-size":1}
,"font-size":{"12px":1}
,"12px":{"color":1}
,"ff0000":{"font-weight":1}
,"font-weight":{"bold":1}
,"bold":{"text-align":1}
,"text-align":{"left":1}
,"left":{"frank":1}
}
;Search.control.loadWordPairs(pairs);
