var pairs =
{
"allowing":{"preventing":1}
,"preventing":{"entry":1}
,"entry":{"fields":1,"select":1,"field":1}
,"fields":{"layout":1,"inspector":1}
,"layout":{"mode":1,"restrict":1,"database":1}
,"mode":{"select":1,"it\u2019s":1}
,"select":{"fields":1,"ptions":1,"prohibit":1}
,"inspector":{"data":1}
,"data":{"data":1,"tab":1,"field":1,"entry":1}
,"tab":{"behavior":1}
,"behavior":{"field":1}
,"field":{"entry":1,"field":1,"object":1,"layout":1,"se":1,"browse":1,"clipboard":1,"changed":1,"enter":1}
,"ptions":{"preventing":1}
,"object":{"layout":1}
,"restrict":{"access":1}
,"access":{"field":1}
,"database":{"define":1}
,"define":{"privilege":1,"field":1}
,"privilege":{"set":1}
,"set":{"permit":1}
,"permit":{"view":1,"clipboard":1}
,"view":{"ield":1}
,"ield":{"access":1}
,"se":{"protecting":1,"defining":1}
,"protecting":{"databases":1}
,"databases":{"prevent":1}
,"prevent":{"entry":1,"field":1}
,"browse":{"mode":1}
,"it\u2019s":{"copy":1}
,"copy":{"data":1}
,"clipboard":{"if":1,"copying":1}
,"if":{"want":1}
,"want":{"prevent":1}
,"changed":{"permit":1}
,"copying":{"define":1}
,"enter":{"auto-entered":1}
,"auto-entered":{"value":1}
,"value":{"select":1,"se":1}
,"prohibit":{"modification":1}
,"modification":{"value":1}
,"defining":{"automatic":1}
,"automatic":{"data":1}
}
;Search.control.loadWordPairs(pairs);
