var pairs =
{
"get":{"systemd":1,"systemdrive":1,"system":1,"volume":1,"operating":1}
,"systemd":{"rive":1}
,"rive":{"returns":1}
,"returns":{"drive":1,"empty":1,"\u002Fc:\u002Fin":1,"\u002Fdrivename\u002Fin":1}
,"drive":{"letter":1,"returns":1,"get":1}
,"letter":{"windows":1}
,"windows":{"volume":1,"operating":1}
,"volume":{"name":1,"named":1}
,"name":{"macos":1,"get":1}
,"macos":{"running":1,"operating":1}
,"running":{"operating":1}
,"operating":{"system":1}
,"system":{"located":1,"drive":1,"volume":1,"disc":1}
,"located":{"get":1}
,"systemdrive":{"none":1,"get":1}
,"none":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1,"products":1}
,"pro":{"8.0":1,"advanced":1}
,"8.0":{"function":1}
,"function":{"supported":1}
,"supported":{"filemaker":1,"returns":1}
,"advanced":{"runtime":1}
,"runtime":{"solutions":1}
,"solutions":{"filemaker":1}
,"products":{"it\u2019s":1}
,"it\u2019s":{"supported":1}
,"empty":{"string":1}
,"string":{"returns":1}
,"\u002Fc:\u002Fin":{"windows":1}
,"\u002Fdrivename\u002Fin":{"macos":1}
,"named":{"drivename":1}
,"drivename":{"get":1}
}
;Search.control.loadWordPairs(pairs);
