var pairs =
{
"creating":{"editing":1}
,"editing":{"scripts":1,"pane":1,"script":1}
,"scripts":{"note":1,"menu":1,"script":1,"sing":1,"pane":1,"steps":1,"duplicate":1,"drag":1,"full":1,"folders":1,"set":1,"feature":1,"override":1,"marked":1,"check":1,"running":1}
,"note":{"each":1,"edit":1,"can\u2019t":1,"asterisk":1}
,"each":{"script":1}
,"script":{"step":1,"steps":1,"examples":1,"workspace":1,"editing":1,"create":1,"cl":1,"button":1,"press":1,"script":1,"name":1,"edit":1,"double-click":1,"open":1,"blank":1,"helps":1,"drag":1,"select":1,"included":1,"run":1,"changed":1,"filemaker":1,"ight-click":1,"reorder":1,"windows":1,"macos":1,"full":1,"choose":1,"allowed":1,"scripts":1,"defined":1,"set":1,"right-click":1,"highlights":1,"new":1,"dialog":1,"manage":1}
,"step":{"options":1,"name":1,"list":1,"script":1,"text":1,"restore":1,"last":1,"executed":1,"favorites":1,"gray":1,"blue":1,"escription":1,"compatibility":1,"opying":1,"select":1,"choose":1,"macos":1,"press":1,"option":1}
,"options":{"examples":1,"by":1,"action":1,"brackets":1,"problem":1}
,"examples":{"script":1,"choose":1}
,"steps":{"reference":1,"pane":1,"alphabetically":1,"compatible":1,"script":1,"press":1,"open":1,"conditions":1}
,"reference":{"alphabetical":1,"category":1}
,"alphabetical":{"list":1,"sort":1}
,"list":{"cript":1,"se":1,"appears":1,"view":1,"category":1,"print":1}
,"cript":{"steps":1}
,"category":{"list":1,"script":1,"select":1,"if":1,"sort":1,"filemaker":1}
,"se":{"script":1}
,"choose":{"scripts":1,"file":1,"script":1,"comment":1,"edit":1,"menu":1,"grant":1,"check":1,"view":1,"move":1}
,"menu":{"script":1,"manage":1,"button":1,"duplicate":1,"save":1,"lick":1,"print":1,"preferences":1,"grant":1}
,"workspace":{"choose":1,"pens":1,"windows":1,"ch":1,"preferences":1}
,"file":{"menu":1,"script":1,"users":1}
,"manage":{"scripts":1,"folders":1}
,"pens":{"create":1}
,"create":{"edit":1,"open":1,"script":1,"duplicate":1}
,"edit":{"scripts":1,"button":1,"script":1,"calculation":1,"menu":1,"delete":1,"color":1}
,"sing":{"panes":1}
,"panes":{"window":1}
,"window":{"scripts":1,"right-click":1,"press":1}
,"pane":{"left":1,"center":1,"right":1,"type":1,"switch":1,"if":1,"script\u2019s":1,"add":1,"comment":1,"select":1,"sorted":1,"script":1,"alphabetical":1,"new":1,"rename":1,"managing":1,"choose":1}
,"left":{"script":1}
,"center":{"script":1}
,"right":{"create":1}
,"open":{"script":1,"calculation":1}
,"cl":{"ick":1,"ose":1}
,"ick":{"new":1}
,"new":{"script":1,"location":1,"window":1}
,"button":{"script":1,"switch":1,"next":1,"options":1,"open":1,"remove":1,"note":1,"view":1,"isplay":1,"list":1,"ch":1,"action":1}
,"type":{"name":1,"choose":1}
,"name":{"new":1,"scripts":1,"choose":1,"script":1}
,"press":{"enter":1,"nter":1,"arrow":1,"shift":1,"up":1,"delete":1,"ctrl-click":1,"alt":1,"ctrl":1}
,"enter":{"return":1,"shift-return":1}
,"return":{"preview":1}
,"preview":{"script":1}
,"switch":{"edit":1,"previewing":1}
,"previewing":{"editing":1}
,"double-click":{"script":1}
,"if":{"script":1,"accessed":1}
,"script\u2019s":{"tab":1}
,"tab":{"active":1,"save":1,"script":1,"edit":1,"new":1}
,"active":{"egin":1}
,"egin":{"typing":1}
,"typing":{"script":1}
,"appears":{"double-click":1}
,"by":{"text":1,"action":1,"categor":1,"users":1,"converting":1}
,"text":{"enclosed":1,"brackets":1}
,"enclosed":{"brackets":1}
,"brackets":{"[\u00A0":1,"options":1,"edit":1}
,"[\u00A0":{"by":1}
,"action":{"menu":1,"script":1}
,"next":{"script":1}
,"calculation":{"calculation":1,"button":1,"dialog":1}
,"dialog":{"box":1}
,"box":{"calculations":1,"allow":1,"by":1}
,"calculations":{"editable":1}
,"editable":{"inline":1}
,"inline":{"note":1}
,"restore":{"option":1,"criteria":1,"restore":1,"parameter":1}
,"option":{"restore":1,"ctrl-click":1,"run":1,"macos":1,"create":1}
,"criteria":{"script":1}
,"last":{"edited":1,"line":1}
,"edited":{"script":1}
,"executed":{"script":1}
,"add":{"line":1,"comment":1,"script":1,"duplicate":1}
,"line":{"script":1,"press":1,"selected":1,"type":1}
,"nter":{"eturn":1}
,"eturn":{"last":1}
,"blank":{"select":1,"line":1}
,"select":{"last":1,"script":1,"multiple":1}
,"arrow":{"add":1,"arrow":1}
,"selected":{"line":1}
,"shift":{"enter":1}
,"shift-return":{"move":1}
,"move":{"lines":1,"tab":1}
,"lines":{"script":1,"problems":1,"highlighted":1}
,"up":{"arrow":1}
,"comment":{"script":1}
,"helps":{"view":1}
,"view":{"modify":1,"script":1,"help":1,"cript":1,"menu":1}
,"modify":{"add":1}
,"favorites":{"category":1}
,"gray":{"star":1}
,"star":{"button":1}
,"remove":{"script":1}
,"blue":{"star":1}
,"can\u2019t":{"add":1}
,"sorted":{"phabetically":1}
,"phabetically":{"view":1}
,"escription":{"ppears":1}
,"ppears":{"list":1}
,"help":{"button":1}
,"alphabetically":{"by":1,"category":1}
,"categor":{"script":1}
,"sort":{"button":1}
,"isplay":{"cript":1}
,"filemaker":{"products":1,"pro":1,"go":1}
,"products":{"support":1}
,"support":{"script":1}
,"compatibility":{"button":1}
,"ch":{"oose":1}
,"oose":{"product":1,"file":1}
,"product":{"all":1,"displayed":1}
,"all":{"scripts":1}
,"compatible":{"product":1}
,"displayed":{"copy":1}
,"copy":{"paste":1}
,"paste":{"script":1}
,"opying":{"pasting":1}
,"pasting":{"scripts":1}
,"duplicate":{"script":1,"windows":1,"step":1,"delete":1,"import":1}
,"windows":{"duplicate":1,"command-click":1,"choose":1,"script":1,"view":1,"option":1,"scripts":1,"command-r":1}
,"macos":{"delete":1,"add":1,"script":1,"rename":1,"filemaker":1,"syntax":1,"double-click":1,"if":1}
,"delete":{"script":1,"reorder":1,"multiple":1,"scripts":1,"records":1}
,"reorder":{"script":1,"scripts":1}
,"drag":{"script":1}
,"location":{"script":1,"list":1}
,"multiple":{"script":1,"steps":1}
,"ctrl-click":{"windows":1}
,"command-click":{"macos":1}
,"included":{"script":1}
,"run":{"script":1,"ull":1,"full":1}
,"asterisk":{"(*)":1}
,"(*)":{"next":1}
,"changed":{"saved":1}
,"saved":{"cl":1}
,"ose":{"tab":1}
,"save":{"choose":1,"script":1}
,"pro":{"advanced":1}
,"advanced":{"enu":1,"checks":1}
,"enu":{"bar":1}
,"bar":{"macos":1,"choose":1}
,"rename":{"duplicate":1,"script":1}
,"ight-click":{"script":1}
,"lick":{"script":1}
,"print":{"script":1,"perform":1}
,"perform":{"script":1,"scripted":1,"exporting":1}
,"full":{"access":1}
,"access":{"privileges":1,"carry":1,"restrictions":1}
,"privileges":{"right-click":1,"running":1,"manage":1,"allows":1,"perform":1,"change":1,"user":1,"by":1,"edit":1,"file":1,"delete":1,"permission":1,"required":1,"choose":1,"windows":1,"macos":1}
,"right-click":{"script":1,"tab":1}
,"grant":{"full":1}
,"running":{"scripts":1}
,"folders":{"scripts":1,"setting":1}
,"managing":{"scripts":1}
,"setting":{"script":1}
,"ull":{"access":1}
,"allows":{"sers":1}
,"sers":{"limited":1}
,"limited":{"access":1}
,"scripted":{"tasks":1}
,"tasks":{"therwise":1}
,"therwise":{"nable":1}
,"nable":{"perform":1}
,"exporting":{"deleting":1}
,"deleting":{"records":1}
,"records":{"access":1,"access-restricted":1}
,"change":{"script":1}
,"allowed":{"privileges":1}
,"user":{"furthermore":1}
,"furthermore":{"full":1}
,"carry":{"subsequent":1}
,"subsequent":{"sub-script":1}
,"sub-script":{"feature":1}
,"feature":{"enabled":1}
,"enabled":{"script":1}
,"set":{"run":1,"users":1,"full":1}
,"users":{"fu":1,"full":1}
,"fu":{"ll":1}
,"ll":{"ac":1}
,"ac":{"cess":1}
,"cess":{"privilege":1}
,"privilege":{"set":1}
,"defined":{"scripts":1}
,"override":{"access":1}
,"restrictions":{"external":1}
,"external":{"files":1,"file":1}
,"files":{"script":1}
,"access-restricted":{"external":1}
,"permission":{"edit":1}
,"marked":{"modifiable":1}
,"modifiable":{"assigned":1}
,"assigned":{"privilege":1}
,"required":{"create":1}
,"import":{"and\u002For":1}
,"and\u002For":{"delete":1}
,"check":{"problems":1}
,"problems":{"build":1,"filemaker":1,"missing":1,"script":1}
,"build":{"script":1}
,"checks":{"script":1}
,"highlights":{"lines":1}
,"missing":{"options":1}
,"problem":{"detected":1,"color":1}
,"detected":{"lines":1}
,"highlighted":{"default":1}
,"default":{"problem":1}
,"color":{"syntax":1,"coding":1}
,"syntax":{"coloring":1}
,"coloring":{"tab":1}
,"preferences":{"edit":1,"windows":1,"macos":1}
,"coding":{"script":1}
,"conditions":{"problems":1}
,"alt":{"windows":1}
,"allow":{"script":1}
,"accessed":{"edit":1}
,"converting":{"button":1}
,"ctrl":{"windows":1}
,"command-r":{"macos":1}
,"go":{"restore":1}
,"parameter":{"restore":1}
}
;Search.control.loadWordPairs(pairs);
