var pairs =
{
"exp":{"returns":1,"number":1,"function":1,"ln":1}
,"returns":{"value":1,"2.71828182":1,"exp":1}
,"value":{"constant":1}
,"constant":{"raised":1,"base":1}
,"raised":{"power":1}
,"power":{"number":1}
,"number":{"exp":1,"number":1,"-any":1,"filemaker":1}
,"-any":{"numeric":1}
,"numeric":{"expression":1}
,"expression":{"field":1,"number":1}
,"field":{"numeric":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"function":1}
,"function":{"returns":1,"inverse":1,"exp":1}
,"base":{"natural":1}
,"natural":{"logarithm":1}
,"logarithm":{"equal":1}
,"equal":{"2.7182818":1}
,"2.7182818":{"raised":1}
,"inverse":{"ln":1}
,"ln":{"function":1,"returns":1}
,"2.71828182":{"exp":1}
}
;Search.control.loadWordPairs(pairs);
