var pairs =
{
"etting":{"up":1}
,"up":{"display":1,"repetitions":1}
,"display":{"repeating":1,"specific":1,"up":1,"first":1,"last":1,"choose":1}
,"repeating":{"fields":1,"field":1,"values":1}
,"fields":{"yo":1,"inspector":1}
,"yo":{"format":1}
,"format":{"repeating":1,"field":1}
,"field":{"display":1,"defined":1,"object":1,"show":1,"repetitions":1}
,"specific":{"ange":1}
,"ange":{"epetitions":1}
,"epetitions":{"if":1}
,"if":{"repeating":1}
,"defined":{"display":1}
,"repetitions":{"format":1,"field":1,"layout":1,"enter":1,"orientation":1}
,"object":{"display":1}
,"first":{"repetitions":1}
,"last":{"repetitions":1}
,"layout":{"mode":1}
,"mode":{"select":1}
,"select":{"repeating":1}
,"inspector":{"lick":1,"apply":1}
,"lick":{"data":1}
,"data":{"data":1,"tab":1}
,"tab":{"field":1,"inspector":1}
,"show":{"repetitions":1}
,"enter":{"range":1,"tab":1}
,"range":{"repeating":1}
,"values":{"want":1}
,"want":{"display":1}
,"choose":{"orientation":1}
,"orientation":{"displaying":1,"list":1}
,"displaying":{"field":1}
,"list":{"press":1}
,"press":{"enter":1}
,"apply":{"format":1}
}
;Search.control.loadWordPairs(pairs);
