var pairs =
{
"ort":{"records":1,"by":1}
,"records":{"new":1,"sorted":1,"based":1,"dialog":1,"panel":1,"repeating":1,"by":1,"permanently":1}
,"new":{"layout\u002Freport":1,"position":1}
,"layout\u002Freport":{"assistant":1}
,"assistant":{"panel":1,"select":1,"next":1}
,"panel":{"new":1,"choose":1,"data":1,"select":1}
,"select":{"fields":1,"non-summary":1,"summary":1,"additional":1,"region":1,"reorder":1}
,"fields":{"want":1,"top":1,"first":1,"double-click":1,"selected":1,"change":1,"field":1,"current":1,"return":1,"panel":1,"select":1,"sort":1}
,"want":{"records":1,"order":1,"sort":1,"remove":1,"reorder":1,"group":1}
,"sorted":{"by":1}
,"by":{"sort":1,"order":1,"year":1,"fields":1,"report":1,"month":1,"default":1,"value":1,"region":1,"category":1,"operating":1}
,"sort":{"hierarchy":1,"order":1,"by":1,"alphabetical":1,"reverse":1,"records":1,"fields":1,"grouped":1,"define":1,"language":1}
,"hierarchy":{"determined":1,"remove":1,"sort":1}
,"determined":{"by":1}
,"order":{"ort":1,"list":1,"want":1,"double-click":1,"fields":1,"drag":1,"ascending":1,"sort":1,"text":1,"based":1,"matches":1,"by":1,"select":1}
,"year":{"month":1,"field":1}
,"month":{"choose":1,"field":1,"reorder":1}
,"choose":{"year":1,"define":1,"table":1,"summary":1}
,"field":{"first":1,"if":1,"sort":1,"want":1,"name":1,"selected":1,"reorder":1,"field":1,"dialog":1,"by":1,"list":1,"types":1,"option":1,"file":1,"choose":1,"total":1,"default":1,"indexing":1}
,"first":{"month":1,"report":1,"repetition":1}
,"if":{"creating":1}
,"creating":{"report":1}
,"report":{"grouped":1,"categories":1,"fields":1,"by":1}
,"grouped":{"data":1,"summary":1}
,"data":{"selected":1,"sorts":1,"suppose":1,"by":1}
,"selected":{"break":1,"sort":1}
,"break":{"fields":1}
,"top":{"sort":1}
,"list":{"lock":1,"choose":1,"sort":1,"list":1,"fields":1,"assistant\u2019s":1}
,"lock":{"icon":1}
,"icon":{"remove":1}
,"remove":{"change":1,"fields":1}
,"change":{"position":1,"order":1,"sorting":1,"filemaker":1,"field\u2019s":1}
,"position":{"records":1,"change":1}
,"categories":{"display":1}
,"display":{"properly":1,"total":1}
,"properly":{"include":1}
,"include":{"field":1,"select":1}
,"double-click":{"fields":1,"field":1}
,"sorting":{"hierarchy":1,"records":1,"text":1}
,"drag":{"double":1}
,"double":{"arrow":1}
,"arrow":{"next":1}
,"next":{"field":1,"include":1}
,"name":{"new":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"sorts":1,"running":1}
,"sorts":{"fields":1,"field":1}
,"ascending":{"order":1}
,"alphabetical":{"order":1}
,"text":{"lowest":1,"field":1,"determined":1}
,"lowest":{"numbers":1,"alphabetically":1}
,"numbers":{"earliest":1,"dates":1}
,"earliest":{"dates":1}
,"dates":{"times":1}
,"times":{"descending":1,"sort":1}
,"descending":{"order":1}
,"reverse":{"rder":1}
,"rder":{"custom":1}
,"custom":{"order":1}
,"based":{"value":1,"values":1,"summary":1}
,"value":{"list":1,"first":1}
,"define":{"value":1,"summary":1,"text":1}
,"matches":{"field\u0027s":1}
,"field\u0027s":{"value":1}
,"reorder":{"records":1,"based":1}
,"values":{"summary":1}
,"summary":{"field":1,"data":1}
,"non-summary":{"field":1}
,"dialog":{"box":1}
,"box":{"select":1,"fields":1,"system":1}
,"default":{"field":1,"language":1}
,"current":{"layout":1}
,"layout":{"sort":1}
,"return":{"fields":1,"sort":1}
,"table":{"tables":1}
,"tables":{"list":1}
,"additional":{"fields":1}
,"types":{"se":1}
,"se":{"sorting":1}
,"repeating":{"fields":1}
,"repetition":{"reorder":1}
,"option":{"sort":1}
,"suppose":{"want":1}
,"group":{"data":1,"report":1}
,"region":{"display":1,"lowest":1,"define":1,"organize":1,"field":1}
,"total":{"sales":1}
,"sales":{"each":1,"group":1,"ield":1}
,"each":{"region":1}
,"alphabetically":{"by":1}
,"file":{"total":1}
,"organize":{"records":1}
,"category":{"panel":1}
,"assistant\u2019s":{"sort":1}
,"ield":{"dialog":1}
,"system":{"formats":1,"filemaker":1}
,"formats":{"affect":1}
,"affect":{"numbers":1}
,"language":{"indexing":1,"sort":1,"options":1,"defining":1}
,"indexing":{"sorting":1,"options":1}
,"operating":{"system":1}
,"running":{"override":1}
,"override":{"default":1}
,"options":{"sorting":1}
,"permanently":{"change":1}
,"field\u2019s":{"default":1}
,"defining":{"field":1}
}
;Search.control.loadWordPairs(pairs);
