var pairs =
{
"esh":{"object":1}
,"object":{"pdates":1,"object":1,"name":1,"current":1,"field":1,"support":1,"hidden":1,"portal":1,"updates":1,"visible":1,"confidential":1,"hides":1,"[\u0022":1}
,"pdates":{"contents":1}
,"contents":{"conditional":1}
,"conditional":{"formatting":1}
,"formatting":{"visibility":1}
,"visibility":{"state":1}
,"state":{"object":1,"confidential":1}
,"name":{"named":1}
,"named":{"object":1}
,"current":{"layout":1,"window":1}
,"layout":{"naming":1}
,"naming":{"objects":1}
,"objects":{"repetition":1,"current":1}
,"repetition":{"optional":1,"refresh":1,"numbers":1,"calculation":1}
,"optional":{"choose":1}
,"choose":{"field":1}
,"field":{"repetition":1,"filemaker":1}
,"refresh":{"defaults":1,"object":1,"window":1}
,"defaults":{"option":1}
,"option":{"ignored":1}
,"ignored":{"if":1}
,"if":{"object":1,"repetition":1}
,"filemaker":{"pro":1}
,"pro":{"13.0":1}
,"13.0":{"refresh":1}
,"support":{"repetition":1}
,"numbers":{"updating":1}
,"updating":{"visibility":1}
,"hidden":{"condition":1}
,"condition":{"if":1}
,"portal":{"refresh":1,"row":1}
,"updates":{"object":1,"visibility":1}
,"visible":{"portal":1}
,"row":{"if":1}
,"calculation":{"returns":1}
,"returns":{"zero":1}
,"zero":{"expression":1}
,"expression":{"exist":1}
,"exist":{"all":1}
,"all":{"repetitions":1,"objects":1}
,"repetitions":{"refreshed":1}
,"refreshed":{"update":1}
,"update":{"all":1}
,"window":{"use":1,"script":1}
,"use":{"refresh":1}
,"script":{"step":1}
,"step":{"allows":1}
,"allows":{"user":1}
,"user":{"log":1,"logged":1}
,"log":{"account":1}
,"account":{"updates":1,"re-login":1}
,"confidential":{"object":1,"\u0022]":1}
,"hides":{"user":1}
,"logged":{"admin":1}
,"admin":{"account":1}
,"re-login":{"[with":1}
,"[with":{"dialog":1}
,"dialog":{"on]":1}
,"on]":{"refresh":1}
,"[\u0022":{"confidential":1}
,"\u0022]":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
