var pairs =
{
"new":{"window":1,"window\u2019s":1,"document":1,"virtual":1,"card":1,"floating":1}
,"window":{"reates":1,"based":1,"choose":1,"styles":1,"floating":1,"dialog":1,"card":1,"settings":1,"na":1,"window":1,"names":1,"points":1,"left":1,"ou":1,"options":1,"darkens":1,"menu":1,"hat":1,"ialog":1,"command":1,"if":1,"controls":1,"inactive":1,"use":1,"script":1,"style":1,"[style":1,"enters":1}
,"reates":{"new":1}
,"based":{"foreground":1}
,"foreground":{"window":1}
,"choose":{"window":1}
,"styles":{"document":1,"disable":1}
,"document":{"pens":1,"window":1,"dialog":1,"windows":1,"name":1}
,"pens":{"document":1,"floating":1,"dialog":1}
,"floating":{"document":1,"window":1}
,"dialog":{"pens":1,"window":1}
,"card":{"card":1,"window":1,"top":1,"left":1,"esize":1,"toolbars":1,"enter":1,"customers":1,"layout":1}
,"settings":{"window":1,"supported":1}
,"na":{"name":1}
,"name":{"new":1,"layout":1,"print":1}
,"names":{"unique":1}
,"unique":{"layout":1}
,"layout":{"name":1,"height":1,"parent":1,"nd":1,"customers":1,"new":1,"print":1}
,"height":{"height":1,"new":1}
,"points":{"width":1,"top":1,"left":1}
,"width":{"width":1,"new":1}
,"top":{"new":1,"screen":1,"layout":1,"window":1,"get":1}
,"window\u2019s":{"distance":1,"title":1}
,"distance":{"points":1}
,"screen":{"card":1,"new":1}
,"parent":{"window":1}
,"left":{"new":1,"screen":1,"parent":1,"get":1}
,"ou":{"set":1}
,"set":{"window":1,"option":1}
,"options":{"close":1,"filemaker":1,"positioning":1}
,"close":{"enables":1,"button":1}
,"enables":{"close":1,"minimize":1,"maximize":1}
,"button":{"window\u2019s":1,"script":1}
,"title":{"bar":1}
,"bar":{"minimize":1,"maximize":1,"dim":1,"use":1,"filemaker":1}
,"minimize":{"enables":1,"button":1,"buttons":1}
,"maximize":{"enables":1,"button":1,"minimize":1}
,"dim":{"parent":1}
,"darkens":{"layout":1}
,"esize":{"allows":1}
,"allows":{"users":1}
,"users":{"resize":1}
,"resize":{"window":1}
,"menu":{"ba":1,"set":1,"new":1}
,"ba":{"th":1}
,"th":{"top":1}
,"hat":{"displays":1}
,"displays":{"installed":1,"document":1}
,"installed":{"menu":1}
,"option":{"supported":1,"value":1,"filemaker":1}
,"supported":{"macos":1,"filemaker":1}
,"macos":{"active":1}
,"active":{"window":1,"virtual":1}
,"toolbars":{"sh":1}
,"sh":{"ows":1}
,"ows":{"filemaker":1}
,"filemaker":{"pro":1,"go":1,"webdirect":1,"data":1}
,"pro":{"advanced":1,"6.0":1}
,"advanced":{"tatus":1,"ses":1}
,"tatus":{"toolbar":1}
,"toolbar":{"nd":1,"filemaker":1}
,"nd":{"filemaker":1,"custom":1,"sorts":1}
,"go":{"oolbar":1,"support":1,"upport":1}
,"oolbar":{"editing":1}
,"editing":{"toolbar":1}
,"6.0":{"earlier":1}
,"earlier":{"script":1}
,"script":{"step":1,"button":1}
,"step":{"creates":1,"control":1,"new":1,"window":1}
,"creates":{"new":1}
,"ialog":{"window":1}
,"enter":{"values":1,"preview":1}
,"values":{"each":1}
,"each":{"option":1}
,"value":{"entered":1,"associated":1}
,"entered":{"filemaker":1}
,"ses":{"default":1}
,"default":{"value":1}
,"associated":{"window":1}
,"command":{"windows":1}
,"windows":{"window":1,"remain":1,"cards":1,"full":1}
,"disable":{"maximize":1}
,"buttons":{"buttons":1,"window\u2019s":1}
,"use":{"script":1,"elect":1}
,"control":{"window":1}
,"if":{"window":1}
,"controls":{"disabled":1}
,"disabled":{"window\u2019s":1}
,"webdirect":{"filemaker":1,"re":1,"support":1}
,"data":{"api":1}
,"api":{"nd":1}
,"custom":{"web":1}
,"web":{"publishing":1}
,"publishing":{"script":1}
,"virtual":{"window":1,"windows":1}
,"inactive":{"virtual":1}
,"remain":{"open":1}
,"open":{"filemaker":1}
,"re":{"visible":1}
,"visible":{"change":1}
,"change":{"current":1}
,"current":{"active":1}
,"elect":{"window":1}
,"style":{"settings":1,"option":1,"options":1}
,"support":{"card":1,"floating":1}
,"upport":{"options":1}
,"positioning":{"resizing":1}
,"resizing":{"windows":1}
,"cards":{"lways":1}
,"lways":{"displays":1}
,"full":{"screen":1}
,"customers":{"layout":1,"customers":1,")]":1,":customer":1}
,"sorts":{"records":1}
,"records":{"customer":1,"by":1}
,"customer":{"id":1}
,"id":{"field":1}
,"field":{"new":1,"[descending":1}
,"[style":{"card":1,"floating":1}
,")]":{"sort":1}
,"sort":{"records":1}
,"by":{"field":1}
,"[descending":{"customers":1}
,":customer":{"id]":1}
,"id]":{"print":1}
,"print":{"invoices":1}
,"invoices":{"layout":1,"invoices":1,"top":1}
,"enters":{"preview":1}
,"preview":{"mode":1}
,"mode":{"new":1,"[pause":1}
,"get":{"windowtop":1,"windowleft":1}
,"windowtop":{"25":1}
,"25":{"left":1,"enter":1}
,"windowleft":{"25":1}
,"[pause":{"off]":1}
,"off]":{"managing":1}
,"managing":{"files":1}
,"files":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
