var pairs =
{
"go":{"field":1,"target":1,"layout":1}
,"field":{"oves":1,"current":1,"if":1,"specifies":1,"filemaker":1,"tab":1,"selected":1,"appears":1,"first":1,"forward":1,"by":1,"object":1,"repetition":1,"script":1,"based":1,"popover":1,"visible":1,"scroll":1,"go":1,"[invoices":1,"browse":1}
,"oves":{"field":1}
,"current":{"layout":1}
,"layout":{"select\u002Fperform":1,"script":1,"multiple":1,"focus":1,"creates":1,"[\u0022":1}
,"select\u002Fperform":{"tells":1,"document":1}
,"tells":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"advanced":1,"6.0":1}
,"advanced":{"select":1,"find":1}
,"select":{"all":1}
,"all":{"contents":1}
,"contents":{"field":1}
,"if":{"primary":1,"script":1,"field":1,"object":1,"target":1}
,"primary":{"command":1}
,"command":{"edit":1}
,"edit":{"select\u002Fperform":1}
,"document":{"state":1}
,"state":{"ready":1}
,"ready":{"editing":1}
,"editing":{"go":1}
,"target":{"field":1}
,"specifies":{"target":1,"field":1}
,"6.0":{"earlier":1}
,"earlier":{"if":1}
,"script":{"step":1,"finds":1,"includes":1}
,"step":{"specifies":1,"move":1,"run":1,"if":1}
,"tab":{"panel":1}
,"panel":{"slide":1,"frontmost":1,"moves":1,"control":1,"field":1}
,"slide":{"panel":1}
,"frontmost":{"anel":1}
,"anel":{"field":1}
,"selected":{"panel":1}
,"moves":{"front":1,"field":1}
,"front":{"panel":1}
,"control":{"if":1}
,"appears":{"layout":1}
,"finds":{"field":1}
,"first":{"panel":1,"visible":1}
,"forward":{"force":1}
,"force":{"filemaker":1}
,"find":{"specific":1,"mode":1}
,"specific":{"field":1}
,"by":{"assigning":1}
,"assigning":{"object":1}
,"object":{"name":1,"script":1,"repeating":1}
,"name":{"field":1}
,"move":{"instance":1}
,"instance":{"field":1,"use":1}
,"repeating":{"field":1}
,"repetition":{"want":1}
,"want":{"go":1}
,"multiple":{"instances":1}
,"instances":{"field":1}
,"includes":{"go":1}
,"run":{"first":1}
,"visible":{"instance":1,"web":1,"invoice":1}
,"based":{"creation":1}
,"creation":{"order":1}
,"order":{"layout":1}
,"focus":{"instance":1}
,"use":{"object":1}
,"popover":{"popover":1,"filemaker":1}
,"webdirect":{"cursor":1}
,"cursor":{"moves":1}
,"web":{"browser":1}
,"browser":{"window":1}
,"window":{"go":1,"target":1}
,"scroll":{"window":1}
,"invoice":{"details":1}
,"details":{"layout":1,"\u0022]":1}
,"creates":{"record":1}
,"record":{"summary":1}
,"summary":{"field":1}
,"[\u0022":{"invoice":1}
,"\u0022]":{"new":1}
,"new":{"record\u002Frequest":1}
,"record\u002Frequest":{"go":1}
,"[invoices":{":summary]":1}
,":summary]":{"selecting":1}
,"selecting":{"field":1}
,"browse":{"mode":1}
,"mode":{"find":1,"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
