var pairs =
{
"xecute":{"sql":1}
,"sql":{"xecutes":1,"statement":1,"dialog":1,"text":1,"query":1,"interface":1,"steps":1,"statements":1,"script":1,"data":1,"server":1,"select":1,"[with":1,"interact":1}
,"xecutes":{"sql":1}
,"statement":{"odbc":1,"filemaker":1,"update":1}
,"odbc":{"data":1,"sql":1,"get":1,"driver":1,"import":1,"automating":1}
,"data":{"source":1,"odbc":1,"sources":1,"api":1,"unicode":1,"doesn\u2019t":1}
,"source":{"dialog":1,"displays":1,"list":1,"calculated":1,"odbc":1,"sql":1,"execute":1}
,"dialog":{"specifies":1,"box":1,"users":1,"option":1,"sql":1,"calculated":1}
,"specifies":{"display":1,"calculation":1}
,"display":{"sql":1}
,"box":{"select":1,"dialog":1,"entering":1}
,"select":{"odbc":1,"data":1,"save":1,"statements":1}
,"entering":{"password":1}
,"password":{"script":1,"note":1,"if":1}
,"script":{"step":1,"get":1,"if":1}
,"step":{"performed":1,"manage":1,"send":1,"external":1,"performs":1}
,"performed":{"odbc":1}
,"displays":{"select":1}
,"list":{"enter":1}
,"enter":{"valid":1,"sql":1}
,"valid":{"user":1}
,"user":{"name":1}
,"name":{"password":1}
,"note":{"select":1}
,"save":{"user":1}
,"if":{"set":1,"dialog":1,"use":1}
,"set":{"dialog":1,"if":1,"title":1}
,"users":{"unable":1}
,"unable":{"access":1}
,"access":{"data":1}
,"calculated":{"sql":1}
,"text":{"specifies":1,"manually":1,"insert":1}
,"calculation":{"use":1}
,"use":{"sql":1,"script":1,"execute":1,"executesql":1}
,"query":{"sql":1,"statement":1,"tables":1}
,"manually":{"enter":1}
,"filemaker":{"pro":1,"data":1}
,"pro":{"6.0":1,"advanced":1}
,"6.0":{"earlier":1}
,"earlier":{"use":1}
,"manage":{"data":1}
,"interface":{"control":1}
,"control":{"filemaker":1}
,"advanced":{"nteraction":1,"error":1}
,"nteraction":{"odbc":1}
,"sources":{"add":1,"supported":1,"filemaker":1,"query":1,"via":1}
,"add":{"multiple":1}
,"multiple":{"execute":1}
,"execute":{"sql":1}
,"steps":{"script":1}
,"get":{"unctions":1,"lastexternalerrordetail":1,"lasterror":1}
,"unctions":{"error":1}
,"error":{"handling":1,"state":1,"sql":1}
,"handling":{"get":1}
,"lastexternalerrordetail":{"function":1}
,"function":{"returns":1,"updates":1}
,"returns":{"error":1,"last":1}
,"state":{"returned":1}
,"returned":{"by":1}
,"by":{"odbc":1}
,"lasterror":{"function":1}
,"last":{"filemaker":1}
,"statements":{"limited":1,"odbc":1,"use":1}
,"limited":{"maximum":1}
,"maximum":{"length":1}
,"length":{"256":1}
,"256":{"characters":1}
,"characters":{"512":1,"passed":1}
,"512":{"kb":1}
,"kb":{"server-side":1}
,"server-side":{"scripts":1}
,"scripts":{"ilemaker":1}
,"ilemaker":{"webdirect":1}
,"webdirect":{"filemaker":1}
,"api":{"nd":1}
,"nd":{"custom":1}
,"custom":{"web":1}
,"web":{"publishing":1}
,"publishing":{"support":1}
,"support":{"script":1,"unicode":1}
,"option":{"set":1}
,"send":{"odbc":1}
,"unicode":{"strings":1,"inconsistent":1,"non-unicode":1,"string":1}
,"strings":{"odbc":1,"uppercase":1}
,"driver":{"support":1}
,"inconsistent":{"odbc":1}
,"import":{"execute":1}
,"external":{"sql":1,"odbc":1}
,"supported":{"runtime":1}
,"runtime":{"solution":1}
,"solution":{"sql":1}
,"server":{"supports":1,"lose":1,"code":1}
,"supports":{"unicode":1}
,"non-unicode":{"field":1}
,"field":{"types":1}
,"types":{"prefix":1}
,"prefix":{"all":1}
,"all":{"unicode":1}
,"uppercase":{"stands":1}
,"stands":{"ational":1}
,"ational":{"sql-92":1}
,"sql-92":{"standard":1}
,"standard":{"unicode":1}
,"string":{"non-english":1}
,"non-english":{"characters":1}
,"passed":{"sql":1}
,"lose":{"data":1}
,"doesn\u2019t":{"exist":1}
,"exist":{"sql":1}
,"code":{"page":1}
,"page":{"execute":1}
,"performs":{"ql":1,"sql":1}
,"ql":{"statements":1}
,"tables":{"filemaker":1}
,"executesql":{"function":1}
,"updates":{"records":1}
,"records":{"employees":1,"customers":1}
,"employees":{"table":1,"employeeid":1,"set":1}
,"table":{"external":1}
,"[with":{"dialog":1}
,"insert":{"employees":1,"customers":1}
,"employeeid":{"firstname":1,"=103":1,"=103]":1}
,"firstname":{"lastname":1}
,"lastname":{"title":1,"values":1}
,"title":{"workphone":1,"=n\u0027manager":1}
,"workphone":{"salary":1}
,"salary":{"values":1}
,"values":{"100":1,"&customers":1}
,"100":{"n\u0027joe":1}
,"n\u0027joe":{"n\u0027smith":1}
,"n\u0027smith":{"n\u0027software":1}
,"n\u0027software":{"engineer":1}
,"engineer":{"987-7000":1}
,"987-7000":{"100000":1}
,"100000":{"update":1}
,"update":{"employees":1,"records":1}
,"=n\u0027manager":{"employeeid":1}
,"=103":{"delete":1}
,"delete":{"employees":1}
,"=103]":{"calculates":1}
,"calculates":{"performs":1}
,"customers":{"table":1,"company":1}
,"company":{"lastname":1}
,"&customers":{":company":1,":last":1}
,":company":{"&\u0022":1}
,"&\u0022":{"&\u0022":1,"&customers":1,"\u0022]":1}
,":last":{"&\u0022":1}
,"\u0022]":{"xecuting":1}
,"xecuting":{"sql":1}
,"interact":{"data":1}
,"via":{"odbc":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
