var pairs =
{
"sing":{"rulers":1}
,"rulers":{"grid":1,"choose":1,"guide":1,"meet":1}
,"grid":{"rulers":1,"help":1,"layout":1,"inspector":1,"select":1,"major":1,"ob":1,"grid":1,"hidden":1,"enter":1,"spacing":1,"steps":1,"hanging":1}
,"help":{"lign":1}
,"lign":{"size":1}
,"size":{"position":1}
,"position":{"objects":1,"pointer":1,"position":1,"tab":1}
,"objects":{"precisely":1,"created":1,"snap":1}
,"precisely":{"layout":1}
,"layout":{"blank":1,"rulers":1,"mode":1,"show":1}
,"blank":{"layout":1}
,"mode":{"show":1}
,"show":{"hide":1,"grid":1}
,"hide":{"rulers":1,"grid":1}
,"choose":{"view":1}
,"view":{"menu":1}
,"menu":{"rulers":1,"upper-left":1}
,"guide":{"lines":1}
,"lines":{"each":1}
,"each":{"ruler":1}
,"ruler":{"track":1,"hoose":1,"increment":1}
,"track":{"position":1}
,"pointer":{"move":1,"layout":1}
,"move":{"pointer":1,"resize":1}
,"inspector":{"position":1,"right-click":1,"unit":1}
,"tab":{"grid":1}
,"select":{"deselect":1}
,"deselect":{"show":1,"snap":1}
,"major":{"gridlines":1,"gridline":1,"grid":1}
,"gridlines":{"darker":1,"gridlines":1,"print":1,"new":1,"inspector":1}
,"darker":{"minor":1}
,"minor":{"gridlines":1,"grid":1}
,"print":{"snap-to":1}
,"snap-to":{"inspector":1,"press":1}
,"snap":{"grid":1,"minor":1}
,"ob":{"jects":1}
,"jects":{"move":1}
,"resize":{"snap":1}
,"new":{"objects":1}
,"created":{"aligning":1}
,"aligning":{"nearest":1}
,"nearest":{"major":1}
,"gridline":{"objects":1}
,"hidden":{"override":1}
,"override":{"grid\u0027s":1}
,"grid\u0027s":{"snap-to":1}
,"press":{"alt":1}
,"alt":{"windows":1}
,"windows":{"command":1}
,"command":{"macos":1}
,"macos":{"drag":1}
,"drag":{"object":1}
,"object":{"change":1}
,"change":{"distance":1,"unit":1}
,"distance":{"gridlines":1}
,"enter":{"values":1}
,"values":{"major":1}
,"spacing":{"minor":1}
,"steps":{"change":1}
,"unit":{"measure":1}
,"measure":{"by":1,"shortcut":1,"want":1,"appears":1,"each":1}
,"by":{"rulers":1}
,"right-click":{"ruler":1}
,"hoose":{"unit":1}
,"shortcut":{"menu":1}
,"upper-left":{"corner":1}
,"corner":{"document":1}
,"document":{"horizontal":1}
,"horizontal":{"vertical":1}
,"vertical":{"rulers":1}
,"meet":{"unit":1}
,"want":{"inspector":1,"each":1}
,"appears":{"next":1}
,"next":{"options":1}
,"options":{"want":1}
,"increment":{"measures":1}
,"measures":{"space":1,"inch":1}
,"space":{"unit":1}
,"inch":{"1\u002F8":1,"centimeter":1}
,"1\u002F8":{"inch":1}
,"centimeter":{"cm":1}
,"cm":{".25":1}
,".25":{"centimeters":1}
,"centimeters":{"points":1}
,"points":{"pt":1,"rulers":1}
,"pt":{"10":1}
,"10":{"points":1}
,"hanging":{"unit":1}
}
;Search.control.loadWordPairs(pairs);
