var pairs =
{
"configure":{"local":1}
,"local":{"notification":1}
,"notification":{"queues":1,"action":1,"clears":1,"name":1,"queue":1,"script":1,"displayed":1,"title":1,"alert":1,"values":1,"notificationnotdisplayed":1,"previous":1,"cleared":1,"filemaker":1,"[action":1,"configure":1,"10-minute":1,"delay":1}
,"queues":{"clears":1,"local":1,"notification":1}
,"clears":{"local":1,"existing":1,"queued":1}
,"action":{"queues":1}
,"existing":{"queued":1}
,"queued":{"notification":1,"if":1,"optional":1}
,"name":{"specifies":1,"local":1,"each":1,"notification":1,"queued":1,"beacondetected":1,"remindme":1}
,"specifies":{"name":1,"script":1,"number":1,"title":1,"text":1,"label":1,"tapping":1}
,"queue":{"clear":1,"name":1}
,"clear":{"unique":1,"name":1}
,"unique":{"name":1}
,"each":{"notification":1,"button":1,"time":1}
,"script":{"specifies":1,"runs":1,"step":1,"multiline":1,"line":1,"queued":1,"parameter":1,"dialog":1,"run":1,"buttons":1,"user":1,"process":1,"set":1,"[specified":1}
,"runs":{"user":1,"notification":1,"if":1,"send":1,"prepare":1}
,"user":{"interacts":1,"tapped":1,"taps":1,"doesn\u2019t":1,"reminder":1}
,"interacts":{"notification":1}
,"displayed":{"if":1,"optional":1,"filemaker":1,"user":1}
,"if":{"filemaker":1,"notifications":1,"calculation":1,"result":1,"script":1,"new":1,"user":1,"notification":1,"[(":1,"[exact":1,"automating":1}
,"filemaker":{"go":1,"pro":1}
,"go":{"foreground":1,"delay":1,"stays":1,"running":1,"background":1,"moves":1}
,"foreground":{"if":1,"specifies":1,"keep":1,"notificationnotallowed":1,"script":1,"true":1}
,"notifications":{"disabled":1}
,"disabled":{"filemaker":1,"ios":1}
,"delay":{"specifies":1,"if":1,"30":1,"each":1,"600":1}
,"number":{"seconds":1,"parameter":1}
,"seconds":{"wait":1}
,"wait":{"queuing":1}
,"queuing":{"notification":1}
,"title":{"specifies":1,"notification":1,"beacon":1,"inventory":1}
,"alert":{"body":1,"button":1,"device":1,"if":1}
,"body":{"specifies":1,"$beaconmessage":1,"prepare":1}
,"text":{"notification":1}
,"button":{"label":1,"notification":1,"foreground":1,"move":1,"moves":1,"process":1,"remindme":1}
,"label":{"specifies":1,"each":1,"-the":1,"prepare":1,"snooze":1}
,"tapping":{"button":1}
,"move":{"filemaker":1}
,"keep":{"background":1}
,"background":{"if":1,"filemaker":1,"notification":1,"script":1}
,"calculation":{"result":1}
,"result":{"true":1,"false":1}
,"true":{"tapping":1,"else":1}
,"moves":{"filemaker":1,"foreground":1}
,"false":{"filemaker":1}
,"stays":{"background":1}
,"pro":{"7.0":1}
,"7.0":{"advanced":1}
,"advanced":{"use":1}
,"use":{"script":1}
,"step":{"display":1}
,"display":{"notification":1}
,"device":{"filemaker":1,"button":1}
,"running":{"background":1,"if":1}
,"optional":{"delay":1,"script":1}
,"multiline":{"parameter":1}
,"parameter":{"passed":1,"value":1,"script":1,"end":1}
,"passed":{"script":1,"process":1}
,"line":{"number":1}
,"value":{"name":1,"get":1,"getvalue":1}
,"values":{"notificationselected":1}
,"notificationselected":{"-the":1}
,"-the":{"user":1,"notification":1}
,"tapped":{"notification":1,"button":1}
,"notificationnotdisplayed":{"-the":1}
,"notificationnotallowed":{"-notifications":1}
,"-notifications":{"disabled":1}
,"ios":{"device":1}
,"dialog":{"box":1}
,"box":{"if":1}
,"new":{"notification":1,"queued":1}
,"previous":{"notification":1}
,"cleared":{"new":1}
,"taps":{"notification":1,"snooze":1,"prepare":1}
,"doesn\u2019t":{"interact":1}
,"interact":{"script":1}
,"run":{"queues":1}
,"buttons":{"configure":1}
,"[action":{"queue":1,"clear":1}
,"beacondetected":{"delay":1,";]":1}
,"30":{"title":1}
,"beacon":{"detected":1}
,"detected":{"body":1}
,"$beaconmessage":{";]":1}
,";]":{"clears":1,"queues":1}
,"10-minute":{"delay":1}
,"time":{"user":1}
,"snooze":{"button":1,"if":1,"configure":1}
,"process":{"notification":1}
,"send":{"user":1}
,"reminder":{"10":1}
,"10":{"minutes":1}
,"minutes":{"multiline":1}
,"remindme":{"snooze":1,"script":1}
,"prepare":{"button":1,"report":1,"inventory":1,"perform":1}
,"report":{"script":1,"body":1,"button":1,"parameter":1}
,"set":{"variable":1}
,"variable":{"[$param":1,"[$buttonlabel":1}
,"[$param":{"value":1}
,"get":{"scriptparameter":1}
,"scriptparameter":{"set":1}
,"[$buttonlabel":{"value":1}
,"getvalue":{"$param":1}
,"$param":{"if":1,"=0":1}
,"[(":{"valuecount":1}
,"valuecount":{"$param":1}
,"=0":{"patterncount":1}
,"patterncount":{"$buttonlabel":1}
,"$buttonlabel":{"snooze":1}
,"600":{"title":1}
,"inventory":{"report":1}
,"else":{"if":1}
,"[exact":{"($buttonlabel":1}
,"($buttonlabel":{"prepare":1}
,"perform":{"script":1}
,"[specified":{"list":1}
,"list":{"prepare":1}
,"end":{"if":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
