var pairs =
{
"opying":{"formatting":1}
,"formatting":{"attributes":1,"custom":1}
,"attributes":{"ayout":1,"custom":1,"layout":1,"selected":1,"choose":1,"pasted":1,"object":1,"want":1,"single":1}
,"ayout":{"use":1,"background":1}
,"use":{"inspector":1,"format":1,"pasted":1}
,"inspector":{"apply":1,"appearance":1,"copy":1}
,"apply":{"formatting":1,"copied":1,"objects":1}
,"custom":{"styles":1,"style":1}
,"styles":{"layout":1,"objects":1,"applied":1}
,"layout":{"objects":1,"mode":1,"part":1,"background":1,"formatting":1,"if":1,"layout":1,"pop-up":1,"parts":1}
,"objects":{"parts":1,"choose":1,"paste":1,"multiple":1,"objects":1,"type":1,"drag":1,"selection":1,"avoid":1,"press":1,"individually":1}
,"parts":{"backgrounds":1,"selected":1,"transparent":1}
,"backgrounds":{"use":1,"layout":1,"note":1}
,"format":{"painter":1,"custom":1,"entire":1,"menu":1}
,"painter":{"tool":1,"copy":1}
,"tool":{"apply":1,"format":1,"status":1,"lock":1,"press":1}
,"mode":{"inspector":1,"select":1}
,"appearance":{"appearance":1,"tab":1}
,"tab":{"copy":1,"inspector":1}
,"copy":{"formatting":1,"button":1,"object":1,"paste":1,"popover":1,"styles":1,"display":1}
,"style":{"all":1,"pplied":1,"layout":1,"portals":1,"formats":1,"entire":1,"listed":1,"name":1,"shadows":1}
,"all":{"states":1,"display":1}
,"states":{"object":1,"display":1}
,"object":{"format":1,"part":1,"type":1,"select":1,"choose":1,"state":1,"copy":1,"copied":1,"portal":1,"case":1,"first":1,"use":1,"change":1,"hold":1,"layout":1,"unlock":1}
,"pplied":{"layout":1}
,"part":{"select":1,"label":1,"copied":1}
,"select":{"object":1,"copy":1,"objects":1,"part":1,"paste":1,"layout":1}
,"label":{"copy":1,"layout":1,"want":1}
,"button":{"right":1,"filemaker":1,"solution":1}
,"right":{"object":1,"list":1}
,"type":{"ist":1,"types":1,"formatting":1}
,"ist":{"top":1,"copy":1,"paste":1,"note":1}
,"top":{"ab":1,"appearance":1}
,"ab":{"copy":1,"display":1,"paste":1}
,"selected":{"display":1,"format":1,"objects":1}
,"display":{"state":1,"states":1,"layout":1}
,"state":{"object":1,"want":1,"ist":1,"copied":1,"list":1}
,"choose":{"display":1,"format":1,"layout":1}
,"want":{"copy":1,"apply":1,"change":1}
,"list":{"top":1,"paste":1}
,"background":{"layout":1,"select":1,"formatting":1,"ensure":1,"choose":1,"new":1,"display":1}
,"paste":{"ormatting":1,"button":1,"formatting":1,"custom":1,"format":1}
,"ormatting":{"attribute":1}
,"attribute":{"select":1}
,"copied":{"formatting":1,"paste":1,"select":1,"formats":1}
,"note":{"paste":1,"select":1}
,"pasted":{"objects":1,"style":1}
,"multiple":{"components":1,"objects":1}
,"components":{"each":1,"copy":1}
,"each":{"component":1,"object":1}
,"component":{"separate":1}
,"separate":{"style":1}
,"portals":{"portal":1}
,"portal":{"style":1,"rows":1,"objects":1,"portal":1}
,"formats":{"entire":1,"rows":1,"multiple":1}
,"entire":{"object":1}
,"rows":{"style":1,"portal":1}
,"case":{"portal":1}
,"first":{"style":1}
,"listed":{"object":1}
,"types":{"rectangle":1}
,"rectangle":{"oval":1}
,"oval":{"layout":1}
,"if":{"objects":1,"copy":1}
,"name":{"target":1}
,"target":{"object":1}
,"change":{"if":1,"multiple":1}
,"popover":{"button":1,"identical":1}
,"filemaker":{"pro":1,"ro":1}
,"pro":{"advanced":1}
,"advanced":{"solution":1,"doesn\u2019t":1}
,"solution":{"popover":1,"except":1,"layout":1}
,"identical":{"solution":1}
,"except":{"filemaker":1}
,"ro":{"advanced":1}
,"doesn\u2019t":{"copy":1}
,"applied":{"popover":1}
,"ensure":{"objects":1}
,"status":{"toolbar":1}
,"toolbar":{"choose":1}
,"menu":{"format":1,"layout":1}
,"hold":{"alt":1}
,"alt":{"key":1}
,"key":{"windows":1,"macos":1}
,"windows":{"option":1,"command":1}
,"option":{"key":1}
,"macos":{"format":1,"drag":1}
,"single":{"object":1}
,"drag":{"arrow":1,"apply":1}
,"arrow":{"pointer":1}
,"pointer":{"selection":1}
,"selection":{"box":1}
,"box":{"includes":1,"completely":1}
,"includes":{"objects":1}
,"completely":{"surround":1}
,"surround":{"objects":1}
,"avoid":{"including":1}
,"including":{"partially":1}
,"partially":{"selected":1}
,"press":{"ctrl":1,"esc":1}
,"ctrl":{"windows":1}
,"command":{"macos":1}
,"individually":{"double-click":1}
,"double-click":{"format":1}
,"lock":{"shift-click":1}
,"shift-click":{"each":1}
,"unlock":{"format":1}
,"esc":{"layout":1}
,"pop-up":{"menu":1}
,"new":{"layout":1}
,"transparent":{"setting":1}
,"setting":{"fill":1}
,"fill":{"line":1}
,"line":{"style":1}
,"shadows":{"padding":1}
,"padding":{"clone":1}
,"clone":{"stamp":1}
}
;Search.control.loadWordPairs(pairs);
