var pairs =
{
"lug-in":{"update":1,"preferences":1}
,"update":{"compares":1,"store":1,"add":1,":plug-in":1,":plugin":1,"\u0022]":1,":installed":1,":required":1,"script":1}
,"compares":{"version":1}
,"version":{"installed":1,"located":1,"number":1,"calculation":1,"plugin":1}
,"installed":{"plug-in":1,"plugin":1,"ensure":1,"initialized":1,"\u0022]":1,"updated":1,"mplugins":1}
,"plug-in":{"version":1,"if":1,"define":1,"enabled":1,"set":1,"file":1,"versions":1,"installed":1,"parameter":1,"preferences":1,"disabled":1,"stored":1,"by":1,"container":1}
,"located":{"container":1}
,"container":{"field":1,"create":1,"fields":1}
,"field":{"filemaker":1,"name":1,"type":1,"if":1,"view":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"file":1,"lug-in":1}
,"file":{"updates":1,"create":1,"container":1,"[plugin":1,"&\u0022":1}
,"updates":{"plug-in":1}
,"if":{"solution":1,"[get":1,"end":1,"create":1,"[plugin":1,"go":1,"enabled":1,"patterncount":1,"plug-in":1}
,"solution":{"file":1}
,"create":{"table":1,"layout":1,"script":1,"start-up":1}
,"table":{"named":1}
,"named":{"plugin":1}
,"plugin":{"update":1,"version":1,"state":1,"file":1,"version]":1,"name":1}
,"store":{"plug-in":1}
,"define":{"fields":1}
,"fields":{"field":1,"defined":1,"single":1}
,"name":{"field":1,"text":1,"install":1,"check":1,"pluginversionstart":1,"pluginversionend":1,"=0":1,"pluginstatestart":1}
,"type":{"plug":1}
,"plug":{"name":1}
,"text":{"required":1}
,"required":{"plugin":1,"plug-ins":1}
,"number":{"installed":1}
,"calculation":{"unstored":1,"installed":1,"plugin":1,"client":1}
,"unstored":{"code":1}
,"code":{"client":1}
,"client":{"plug-in":1}
,"state":{"calculation":1,"field":1}
,"enabled":{"state":1,"set":1,"installed":1,"ensure":1,"parameter":1,"by":1}
,"layout":{"named":1,"[\u0022":1,"[original":1,"client":1}
,"add":{"fields":1}
,"defined":{"step":1}
,"step":{"create":1}
,"script":{"name":1,"[specified":1,"named":1,"references":1}
,"install":{"plug-in":1,"files":1,"allow":1,"accessible":1}
,"set":{"error":1}
,"error":{"capture":1,"&get":1}
,"capture":{"[on]":1}
,"[on]":{"install":1,"perform":1}
,"[plugin":{"update":1}
,":plug-in":{"file]":1}
,"file]":{"deal":1,"end":1}
,"deal":{"errors":1}
,"errors":{"if":1}
,"[get":{"lasterror":1,"foundcount":1}
,"lasterror":{"0]":1,"=3]":1,"=1550]":1,"=1551]":1,"&\u0022":1}
,"0]":{"if":1,"show":1}
,"=3]":{"show":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"dialog":{"[plugin":1,"[\u0022":1}
,":plugin":{"file":1,"file]":1}
,"&\u0022":{"installed":1,"occured":1}
,"ensure":{"allow":1}
,"allow":{"solutions":1}
,"solutions":{"install":1}
,"files":{"selected":1,"option":1}
,"selected":{"filemaker":1,"client\u2019s":1}
,"preferences":{"\u0022]":1,"etting":1,"if":1,"install":1}
,"\u0022]":{"else":1,"go":1,"end":1}
,"else":{"if":1,"show":1}
,"=1550]":{"show":1}
,"initialized":{"\u0022]":1}
,"=1551]":{"show":1}
,"[\u0022":{"general":1,"plugin":1,"required":1}
,"general":{"error":1}
,"&get":{"lasterror":1}
,"occured":{"installing":1}
,"installing":{"&plugin":1}
,"&plugin":{"update":1}
,"end":{"if":1,"loop":1}
,"check":{"plug-in":1,"if":1}
,"versions":{"go":1,"parameter":1}
,"go":{"layout":1,"record\u002Frequest\u002Fpage":1}
,"record\u002Frequest\u002Fpage":{"[first]":1,"[next":1}
,"[first]":{"loop":1}
,"loop":{"if":1,"create":1}
,":installed":{"plugin":1}
,":required":{"plugin":1}
,"version]":{"plug-in":1}
,"updated":{"perform":1}
,"perform":{"script":1,"find":1}
,"[specified":{"list":1}
,"list":{"install":1,"check":1}
,"parameter":{"end":1,"perform":1,"go":1}
,"[next":{"exit":1}
,"exit":{"last":1}
,"last":{"on]":1}
,"on]":{"end":1}
,"find":{"[restore]":1,"enabled":1}
,"[restore]":{"find":1}
,"foundcount":{"0]":1}
,"plug-ins":{"enabled":1,"install":1}
,"start-up":{"script":1}
,"references":{"scripts":1}
,"scripts":{"order":1}
,"order":{"database":1}
,"database":{"perform":1}
,"[original":{"layout]":1}
,"layout]":{"let":1}
,"let":{"[pluginnameposition":1}
,"[pluginnameposition":{"=position":1}
,"=position":{"get":1}
,"get":{"installedfmplugins":1,"installed":1}
,"installedfmplugins":{"plugin":1,"pluginnameposition":1,"pluginversionstart":1,"pluginstatelength":1,"pluginstatestart":1}
,"pluginversionstart":{"=pluginnameposition":1,"pluginversionlength":1}
,"=pluginnameposition":{"length":1}
,"length":{"plugin":1,"get":1}
,"pluginversionend":{"=position":1}
,"pluginnameposition":{"pluginversionlength":1,"pluginstateend":1,"position":1,"length":1}
,"pluginversionlength":{"=pluginversionend":1,"let":1}
,"=pluginversionend":{"-pluginversionstart":1}
,"-pluginversionstart":{"if":1}
,"patterncount":{"get":1}
,"mplugins":{"plugin":1}
,"=0":{"middle":1}
,"middle":{"get":1}
,"pluginstatestart":{"=position":1,"pluginstatelength":1}
,"pluginstateend":{"=if":1}
,"=if":{"position":1}
,"position":{"get":1}
,"pluginstatelength":{"=pluginstateend":1,"plug-ins":1}
,"=pluginstateend":{"-pluginstatestart":1}
,"-pluginstatestart":{"if":1}
,"option":{"selected":1}
,"client\u2019s":{"plug-in":1}
,"etting":{"plug-in":1}
,"disabled":{"client\u2019s":1}
,"accessible":{"manually":1}
,"manually":{"enabled":1}
,"by":{"user":1,"creating":1}
,"user":{"plug-in":1}
,"stored":{"each":1}
,"each":{"container":1}
,"view":{"all":1}
,"all":{"plug-in":1}
,"creating":{"multiple":1}
,"multiple":{"plug-in":1}
,"single":{"layout":1}
}
;Search.control.loadWordPairs(pairs);
