var pairs =
{
"exit":{"loop":1,"last":1}
,"loop":{"if":1,"script":1,"exited":1,"exit":1,"automating":1}
,"if":{"xits":1,"calculation":1,"false":1,"script":1,"record":1,"[isempty":1}
,"xits":{"loop":1}
,"calculation":{"true":1,"want":1,"if":1}
,"true":{"zero":1}
,"zero":{"sp":1,"script":1,"loop":1}
,"sp":{"ecifies":1}
,"ecifies":{"boolean":1}
,"boolean":{"calculation":1}
,"want":{"evaluated":1}
,"evaluated":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"if":1}
,"script":{"continues":1,"step":1}
,"continues":{"script":1}
,"step":{"end":1,"if":1,"exit":1,"loops":1}
,"end":{"loop":1}
,"false":{"zero":1}
,"exited":{"script":1}
,"loops":{"records":1}
,"records":{"export":1}
,"export":{"files":1,"field":1}
,"files":{"container":1}
,"container":{"fields":1,"field":1}
,"fields":{"exits":1}
,"exits":{"loop":1}
,"record":{"empty":1}
,"empty":{"container":1}
,"field":{"set":1,"contents":1}
,"set":{"variable":1}
,"variable":{"[$path":1}
,"[$path":{"value":1}
,"value":{"get":1}
,"get":{"documentspath":1}
,"documentspath":{"&products":1}
,"&products":{":container]":1}
,":container]":{"go":1}
,"go":{"record\u002Frequest\u002Fpage":1}
,"record\u002Frequest\u002Fpage":{"[first]":1,"[next":1}
,"[first]":{"loop":1}
,"[isempty":{"products":1}
,"products":{":container":1}
,":container":{")]":1,"\u0022$path":1}
,")]":{"export":1}
,"contents":{"[products":1}
,"[products":{":container":1}
,"\u0022$path":{"create":1}
,"create":{"folders":1}
,"folders":{"off]":1}
,"off]":{"go":1}
,"[next":{"exit":1}
,"last":{"end":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
