var pairs =
{
"close":{"file":1,"external":1}
,"file":{"loses":1,"closes":1,"runs":1,"disconnect":1,"filemaker":1,"script":1,"if":1,"close":1,"can\u2019t":1,"[open":1,"invoices":1,"[current":1}
,"loses":{"ilemaker":1}
,"ilemaker":{"pro":1,"data":1}
,"pro":{"advanced":1,"6.0":1}
,"advanced":{"ile":1,"file":1,"stops":1,"close":1}
,"ile":{"disconnects":1}
,"disconnects":{"odbc":1}
,"odbc":{"data":1}
,"data":{"source":1,"sources":1}
,"source":{"current":1,"specifies":1,"disconnect":1,"e-login":1,"user":1}
,"current":{"file":1,"database":1}
,"closes":{"file":1,"filemaker":1,"current":1}
,"runs":{"script":1}
,"script":{"step":1,"closes":1,"running":1,"[specified":1}
,"step":{"add":1,"disconnects":1}
,"add":{"filemaker":1,"odbc":1}
,"filemaker":{"data":1,"pro":1,"file":1}
,"specifies":{"filemaker":1,"odbc":1}
,"disconnect":{"add":1,"manage":1}
,"manage":{"data":1}
,"sources":{"allows":1,"editing":1,"diting":1,"filemaker":1,"referenced":1}
,"allows":{"modify":1}
,"modify":{"remove":1}
,"remove":{"external":1}
,"external":{"data":1}
,"editing":{"ilemaker":1}
,"diting":{"odbc":1}
,"6.0":{"earlier":1}
,"earlier":{"if":1}
,"if":{"file":1,"user":1}
,"stops":{"currently":1}
,"currently":{"running":1}
,"running":{"script":1}
,"e-login":{"odbc":1}
,"user":{"name":1,"moves":1}
,"name":{"password":1}
,"password":{"closing":1}
,"closing":{"filemaker":1}
,"moves":{"file":1}
,"can\u2019t":{"close":1}
,"referenced":{"relationships":1}
,"relationships":{"graph":1}
,"graph":{"invoices":1}
,"invoices":{"database":1,"\u0022]":1,"parameter":1}
,"database":{"performs":1,"open":1}
,"performs":{"script":1}
,"open":{"file":1}
,"[open":{"hidden":1}
,"hidden":{"invoices":1}
,"\u0022]":{"perform":1}
,"perform":{"script":1}
,"[specified":{"list":1}
,"list":{"sort":1}
,"sort":{"records":1}
,"records":{"file":1}
,"parameter":{"close":1}
,"[current":{"file]":1}
,"file]":{"managing":1}
,"managing":{"files":1}
,"files":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
