var pairs =
{
"layout":{"part":1,"top":1,"title":1,"browse":1,"footer":1,"bottom":1,"display":1,"subtotals":1,"parts":1,"leading":1,"subsummary":1,"multiple":1,"if":1}
,"part":{"types":1,"type":1,"escription":1,"scrolled":1,"print":1,"use":1,"layout":1,"header":1,"table":1,"grand":1,"summary":1,"leading":1,"body":1,"depending":1,"place":1,"get":1,"change":1,"sales":1}
,"types":{"sections":1}
,"sections":{"each":1}
,"each":{"layout":1,"object":1,"record":1,"option":1,"subset":1,"salesperson\u0027s":1}
,"type":{"non-summary":1,"field":1}
,"non-summary":{"layout":1}
,"escription":{"top":1,"grand":1}
,"top":{"navigation":1,"screen":1,"first":1,"bottom":1}
,"navigation":{"appears":1,"part":1}
,"appears":{"top":1,"each":1,"bottom":1}
,"screen":{"contain":1,"page":1}
,"contain":{"buttons":1}
,"buttons":{"controls":1}
,"controls":{"help":1}
,"help":{"users":1}
,"users":{"navigate":1}
,"navigate":{"layout":1}
,"scrolled":{"zoomed":1}
,"zoomed":{"part":1}
,"print":{"display":1,"separate":1,"data":1}
,"display":{"preview":1,"top":1,"summary":1,"ubsummary":1}
,"preview":{"mode":1,"print":1}
,"mode":{"fields":1,"title":1,"header":1,"footer":1}
,"fields":{"top":1,"title":1,"text":1,"bottom":1,"summary":1,"display":1}
,"use":{"data":1,"titles":1}
,"data":{"current":1,"active":1,"first":1,"layout":1}
,"current":{"record":1}
,"record":{"top":1,"fields":1,"found":1,"body":1,"title":1,"bottom":1,"leading":1,"trailing":1}
,"title":{"header":1,"page":1,"footer":1}
,"header":{"appears":1,"if":1,"layout":1,"displays":1,"preview":1,"use":1,"footer":1}
,"first":{"screen":1,"record":1}
,"page":{"replaces":1,"title":1,"add":1}
,"replaces":{"normal":1}
,"normal":{"header":1,"footer":1}
,"if":{"reports":1,"title":1,"type":1,"want":1}
,"reports":{"print":1,"header":1}
,"separate":{"title":1}
,"browse":{"mode":1}
,"displays":{"data":1,"summary":1,"ubsummary":1}
,"active":{"record":1}
,"found":{"set":1}
,"set":{"header":1,"body":1,"grand":1}
,"add":{"title":1}
,"titles":{"column":1}
,"column":{"headings":1}
,"headings":{"columnar":1}
,"columnar":{"reports":1}
,"body":{"each":1,"including":1,"layout":1,"part":1}
,"object":{"body":1}
,"including":{"fields":1}
,"text":{"objects":1}
,"objects":{"graphics":1}
,"graphics":{"appears":1}
,"footer":{"appears":1,"footer":1,"layout":1,"displays":1,"if":1,"part":1}
,"bottom":{"screen":1,"first":1,"navigation":1}
,"table":{"view":1}
,"view":{"select":1,"properties":1}
,"select":{"each":1,"month":1}
,"option":{"table":1}
,"properties":{"dialog":1}
,"dialog":{"box":1}
,"box":{"include":1}
,"include":{"summary":1,"grand":1}
,"summary":{"data":1,"fields":1,"layout":1,"parts":1,"subsummary":1,"usually":1,"totals":1,"leading":1,"field":1,"all":1,"part":1,"trailing":1,"summarize":1}
,"subtotals":{"grand":1,"subset":1}
,"grand":{"totals":1,"summary":1,"total":1}
,"totals":{"averages":1,"all":1,"salesperson":1,"non-summary":1}
,"averages":{"counts":1}
,"counts":{"place":1}
,"place":{"summary":1,"subsummary":1,"sales":1}
,"parts":{"summary":1,"include":1,"layout":1}
,"subsummary":{"parts":1,"usually":1,"part":1,"leading":1}
,"usually":{"summary":1}
,"all":{"records":1,"transactions":1}
,"records":{"browsed":1,"records":1,"grouped":1,"found":1,"sorted":1,"summary":1}
,"browsed":{"subsummary":1}
,"ubsummary":{"nformation":1}
,"nformation":{"subtotals":1,"each":1}
,"subset":{"records":1}
,"grouped":{"sorted":1}
,"sorted":{"by":1}
,"by":{"values":1,"break":1}
,"values":{"field":1}
,"field":{"break":1,"value":1,"report":1,"part":1,"displays":1,"subsummary":1,"filemaker":1,"identify":1,"totaling":1,"create":1,"salesperson\u0027s":1,"counting":1,"grand":1,"sales":1,"get":1}
,"break":{"field":1}
,"value":{"break":1}
,"report":{"breaks":1,"depending":1,"by":1,"subsummary":1}
,"breaks":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"inserts":1,"displays":1}
,"inserts":{"subsummary":1}
,"leading":{"trailing":1,"end":1,"grand":1,"last":1}
,"trailing":{"place":1,"report":1,"grand":1,"group":1}
,"end":{"trailing":1}
,"depending":{"placement":1}
,"placement":{"layout":1}
,"multiple":{"subsummary":1}
,"last":{"record":1}
,"group":{"break":1}
,"identify":{"subset":1}
,"summarize":{"each":1}
,"salesperson\u0027s":{"sales":1,"name":1,"transactions":1}
,"sales":{"figures":1,"transactions":1,"field":1,"summary":1,"report":1,"select":1}
,"figures":{"database":1}
,"database":{"recording":1}
,"recording":{"sales":1}
,"transactions":{"define":1,"create":1,"place":1}
,"define":{"summary":1}
,"totaling":{"sales":1}
,"create":{"subsummary":1,"second":1}
,"name":{"if":1}
,"want":{"count":1}
,"count":{"salesperson\u0027s":1}
,"second":{"summary":1}
,"counting":{"transactions":1}
,"get":{"grand":1,"monthly":1,"individual":1}
,"total":{"all":1}
,"change":{"focus":1}
,"focus":{"report":1}
,"month":{"break":1}
,"monthly":{"totals":1}
,"salesperson":{"get":1}
,"individual":{"performance":1}
,"performance":{"totals":1}
}
;Search.control.loadWordPairs(pairs);
