var pairs =
{
"sign":{"returns":1,"number":1,"15.12":1,"(-175":1,"balancedue":1}
,"returns":{"-1":1,"sign":1,"if":1}
,"-1":{"number":1,"sign":1}
,"number":{"negative":1,"number":1,"-any":1,"filemaker":1,"field":1}
,"negative":{"zero":1}
,"zero":{"positive":1}
,"positive":{"sign":1}
,"-any":{"numeric":1}
,"numeric":{"expression":1}
,"expression":{"field":1,"number":1}
,"field":{"numeric":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"sign":1}
,"15.12":{"returns":1}
,"(-175":{"returns":1}
,"balancedue":{"returns":1,"number":1}
,"if":{"balancedue":1}
}
;Search.control.loadWordPairs(pairs);
