var pairs =
{
"peak":{"mac":1}
,"mac":{"os":1}
,"os":{"roduces":1}
,"roduces":{"speech":1}
,"speech":{"text":1,"completion":1,"completed":1}
,"text":{"type":1,"spoken":1,"entry":1,"calculation":1,"string":1}
,"type":{"text":1}
,"spoken":{"text":1,"voice":1}
,"entry":{"create":1}
,"create":{"spoken":1,"text":1}
,"calculation":{"use":1,"create":1}
,"use":{"voice":1,"calculation":1,"wait":1}
,"voice":{"specifies":1,"various":1,"synthesizer":1}
,"specifies":{"voice":1}
,"various":{"voices":1}
,"voices":{"computer":1}
,"computer":{"wait":1,"script":1,"tells":1}
,"wait":{"speech":1}
,"completion":{"continuing":1}
,"continuing":{"tells":1,"next":1}
,"tells":{"filemaker":1,"user":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1,"6.0":1}
,"advanced":{"wait":1}
,"completed":{"continuing":1}
,"next":{"script":1}
,"script":{"step":1,"edited":1,"steps":1,"run":1,"trigger":1}
,"step":{"filemaker":1,"if":1}
,"6.0":{"earlier":1}
,"earlier":{"enter":1}
,"enter":{"literal":1,"company":1}
,"literal":{"text":1}
,"string":{"use":1}
,"synthesizer":{"use":1,"speak":1}
,"if":{"database":1,"company":1,"[isempty":1,"speaks":1}
,"database":{"non-speaking":1}
,"non-speaking":{"computer":1}
,"edited":{"default":1}
,"default":{"voice":1}
,"speak":{"script":1,"[\u0022":1,"[invoices":1}
,"steps":{"executed":1}
,"executed":{"script":1}
,"run":{"non-speaking":1}
,"user":{"enter":1}
,"company":{"name":1,"field":1}
,"name":{"if":1,"\u0022]":1}
,"field":{"empty":1,"current":1}
,"empty":{"started":1}
,"started":{"by":1}
,"by":{"onrecordcommit":1}
,"onrecordcommit":{"script":1}
,"trigger":{"onlayoutexit":1,"onwindowclose":1,"if":1}
,"onlayoutexit":{"script":1}
,"onwindowclose":{"script":1}
,"[isempty":{"contacts":1}
,"contacts":{":company":1}
,":company":{")]":1}
,")]":{"speak":1}
,"[\u0022":{"enter":1,"invoice":1}
,"\u0022]":{"end":1,"speak":1}
,"end":{"if":1}
,"speaks":{"contents":1}
,"contents":{"summary":1}
,"summary":{"field":1}
,"current":{"record":1}
,"record":{"go":1}
,"go":{"layout":1}
,"layout":{"[\u0022":1}
,"invoice":{"details":1}
,"details":{"\u0022]":1}
,"[invoices":{":summary]":1}
,":summary]":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
