var pairs =
{
"etting":{"plug-in":1}
,"plug-in":{"preferences":1,"plug-in":1,"name":1,"select":1,"configure":1,"documentation":1,"allow":1,"folder":1}
,"preferences":{"use":1,"enable":1,"macos":1,"preferences":1,"dialog":1}
,"use":{"plug-in":1}
,"enable":{"configure":1,"disable":1}
,"configure":{"plug-ins":1,"selected":1,"configuring":1}
,"plug-ins":{"note":1,"knowledge":1,"indows":1,"tab":1,"enabled":1,"list":1,"check":1,"automatically":1,"installed":1}
,"note":{"if":1}
,"if":{"software":1}
,"software":{"eveloper":1}
,"eveloper":{"write":1}
,"write":{"custom":1}
,"custom":{"plug-ins":1}
,"knowledge":{"programming":1}
,"programming":{"required":1}
,"required":{"plug-ins":1}
,"indows":{"choose":1}
,"choose":{"edit":1,"filemaker":1}
,"edit":{"menu":1}
,"menu":{"preferences":1}
,"macos":{"choose":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"enu":1}
,"enu":{"preferences":1}
,"dialog":{"box":1}
,"box":{"plug-ins":1}
,"tab":{"installed":1}
,"installed":{"plug-ins":1,"reveal":1,"press":1}
,"enabled":{"plug-ins":1}
,"list":{"enabled":1}
,"check":{"mark":1}
,"mark":{"description":1}
,"description":{"plug-in":1}
,"name":{"enable":1,"configure":1}
,"disable":{"plug-in":1}
,"select":{"deselect":1,"allow":1}
,"deselect":{"checkbox":1}
,"checkbox":{"next":1}
,"next":{"plug-in\u2019s":1}
,"plug-in\u2019s":{"name":1}
,"selected":{"plug-in":1}
,"configuring":{"plug-in":1}
,"documentation":{"plug-in":1}
,"allow":{"solutions":1}
,"solutions":{"install":1}
,"install":{"update":1,"files":1}
,"update":{"plug-ins":1}
,"automatically":{"select":1}
,"files":{"open":1}
,"open":{"folder":1,"all":1}
,"folder":{"plug-ins":1,"running":1,"open":1}
,"reveal":{"plug-in":1}
,"running":{"version":1}
,"version":{"application":1}
,"application":{"current":1}
,"current":{"user\u2019s":1}
,"user\u2019s":{"extensions":1}
,"extensions":{"folder":1,"folders":1}
,"all":{"extensions":1}
,"folders":{"plug-ins":1}
,"press":{"shift":1}
,"shift":{"while":1}
,"while":{"reveal":1}
}
;Search.control.loadWordPairs(pairs);
