var pairs =
{
"export":{"field":1,"path":1}
,"field":{"contents":1,"active":1,"specifies":1,"exported":1,"filemaker":1,"text":1,"all":1}
,"contents":{"xports":1,"single":1,"current":1,"exported":1,"web":1,"[products":1}
,"xports":{"contents":1}
,"single":{"field":1}
,"active":{"record":1,"table":1}
,"record":{"new":1}
,"new":{"file":1,"email":1,"folders":1,"folder":1}
,"file":{"target":1,"specifies":1,"field":1,"paths":1,"user":1,"output":1,"open":1,"attachment":1,"attached":1,"path":1,"convert":1,"create":1}
,"target":{"field":1}
,"specifies":{"field":1,"name":1}
,"exported":{"if":1,"se":1,"field":1,"utf-8":1}
,"if":{"field":1,"file":1,"contents":1}
,"filemaker":{"pro":1,"creates":1,"webdirect":1,"go":1}
,"pro":{"advanced":1,"6.0":1}
,"advanced":{"xport":1,"automating":1}
,"xport":{"contents":1}
,"current":{"field":1}
,"table":{"output":1}
,"output":{"file":1}
,"name":{"location":1}
,"location":{"file":1,"script":1,"th":1}
,"se":{"creating":1}
,"creating":{"file":1}
,"paths":{"if":1}
,"user":{"choose":1}
,"choose":{"filename":1}
,"filename":{"location":1,"exports":1,"export":1}
,"script":{"step":1}
,"step":{"performed":1,"supported":1}
,"performed":{"ou":1}
,"ou":{"select":1}
,"select":{"utomatically":1}
,"utomatically":{"open":1}
,"open":{"file":1,"default":1}
,"default":{"application":1,"email":1,"download":1}
,"application":{"reate":1,"output":1}
,"reate":{"email":1}
,"email":{"file":1,"message":1,"application":1}
,"attachment":{"display":1}
,"display":{"new":1}
,"message":{"user\u2019s":1}
,"user\u2019s":{"default":1}
,"attached":{"create":1}
,"create":{"folders":1,"new":1}
,"folders":{"pecifies":1,"hat":1,"ptions":1,"ption":1,"on]":1,"go":1}
,"pecifies":{"create":1}
,"hat":{"output":1}
,"path":{"filemaker":1,"new":1,"record\u002Frequest\u002Fpage":1}
,"6.0":{"earlier":1}
,"earlier":{"if":1}
,"text":{"filemaker":1,"file":1,"format":1}
,"creates":{"utf-16":1}
,"utf-16":{"format":1}
,"format":{"text":1,"first":1}
,"convert":{"text":1}
,"first":{"use":1}
,"use":{"textencode":1}
,"textencode":{"function":1}
,"function":{"filemaker":1}
,"webdirect":{"pecify":1,"exports":1}
,"pecify":{"output":1}
,"ptions":{"supported":1}
,"supported":{"filemaker":1,"mobile":1,"dialog":1}
,"exports":{"field":1,"image":1,"files":1}
,"web":{"browser\u2019s":1}
,"browser\u2019s":{"default":1}
,"download":{"location":1}
,"th":{"script":1}
,"mobile":{"browsers":1}
,"browsers":{"filemaker":1}
,"go":{"te":1,"record\u002Frequest\u002Fpage":1}
,"te":{"xt":1}
,"xt":{"exported":1}
,"utf-8":{"format":1}
,"ption":{"supported":1}
,"dialog":{"box":1}
,"box":{"set":1}
,"set":{"export":1,"set":1,"file":1,"variable":1}
,"folder":{"nd":1}
,"nd":{"filename":1}
,"image":{"export":1}
,"[products":{":picture":1,":container":1}
,":picture":{"obile":1}
,"obile":{"phone.png":1}
,"phone.png":{"create":1}
,"on]":{"exports":1}
,"files":{"container":1}
,"container":{"field":1}
,"all":{"records":1}
,"records":{"found":1}
,"found":{"set":1}
,"record\u002Frequest\u002Fpage":{"[first":1,"[next":1}
,"[first":{"loop":1}
,"loop":{"set":1,"xporting":1}
,"variable":{"[$path":1}
,"[$path":{"value":1}
,"value":{"get":1}
,"get":{"documentspath":1}
,"documentspath":{"&getcontainerattribute":1}
,"&getcontainerattribute":{"products":1}
,"products":{":container":1}
,":container":{"filename":1,"\u0022$path":1}
,"\u0022$path":{"create":1}
,"[next":{"exit":1}
,"exit":{"last":1}
,"last":{"end":1}
,"end":{"loop":1}
,"xporting":{"data":1}
,"data":{"filemaker":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
