var pairs =
{
"naming":{"objects":1}
,"objects":{"assign":1,"grouped":1,"script":1,"if":1}
,"assign":{"names":1,"object":1}
,"names":{"objects":1,"object":1,"case":1}
,"grouped":{"objects":1,"object":1}
,"script":{"steps":1,"go":1,"step":1}
,"steps":{"functions":1}
,"functions":{"use":1}
,"use":{"names":1,"go":1}
,"object":{"layout":1,"grouped":1,"want":1,"that\u2019s":1,"group":1,"bjects":1,"type":1,"name":1,"script":1,"names":1}
,"layout":{"mode":1,"field":1}
,"mode":{"select":1}
,"select":{"object":1,"group":1}
,"want":{"name":1,"navigate":1}
,"name":{"name":1,"object":1,"press":1,"create":1,"copy":1,"by":1,"field":1}
,"that\u2019s":{"group":1}
,"group":{"select":1,"inspector":1}
,"inspector":{"position":1,"apply":1}
,"position":{"position":1,"tab":1,"type":1}
,"tab":{"position":1,"inspector":1,"bjects":1,"objects":1,"panels":1}
,"type":{"value":1,"assign":1}
,"value":{"name":1}
,"press":{"enter":1}
,"enter":{"tab":1}
,"apply":{"name":1}
,"bjects":{"tab":1}
,"if":{"automate":1,"copy":1}
,"automate":{"navigation":1}
,"navigation":{"object":1}
,"create":{"script":1}
,"go":{"object":1,"field":1}
,"step":{"if":1,"go":1,"refer":1}
,"copy":{"field":1}
,"field":{"layout":1,"tab":1,"want":1,"script":1,"by":1,"name":1,"manage":1}
,"panels":{"assign":1}
,"navigate":{"use":1}
,"refer":{"desired":1}
,"desired":{"copy":1}
,"by":{"object":1,"field":1}
,"case":{"sensitive":1}
,"sensitive":{"name":1}
,"manage":{"database":1}
,"database":{"dialog":1}
,"dialog":{"box":1}
,"box":{"independent":1}
,"independent":{"object":1}
}
;Search.control.loadWordPairs(pairs);
