var pairs =
{
"creating":{"accounts":1,"editing":1}
,"accounts":{"authenticate":1,"each":1,"external":1,"sure":1,"contain":1,"follow":1,"situations":1,"authentication":1,"set":1}
,"authenticate":{"via":1,"users":1,"authentication":1,"user":1}
,"via":{"external":1,"choose":1}
,"external":{"server":1,"authentication":1}
,"server":{"if":1,"organization":1,"allows":1,"control":1,"authenticate":1,"database":1,"accounts":1,"environment":1,"documentation":1,"group":1,"privilege":1,"account":1,"external":1,"se":1,"help":1,"configure":1,"uthenticating":1}
,"if":{"you\u2019re":1,"manage":1,"filemaker":1}
,"you\u2019re":{"hosting":1}
,"hosting":{"filemaker":1,"files":1}
,"filemaker":{"pro":1,"server":1,"uthenticated":1}
,"pro":{"advanced":1}
,"advanced":{"iles":1,"database":1,"won\u2019t":1,"file":1}
,"iles":{"filemaker":1}
,"organization":{"centrally":1}
,"centrally":{"anaged":1}
,"anaged":{"authentication":1}
,"authentication":{"users":1,"server":1,"servers":1,"order":1,"enabling":1}
,"users":{"groups":1,"based":1,"authentication":1,"if":1,"external":1,"multiple":1}
,"groups":{"apple":1}
,"apple":{"open":1}
,"open":{"directory":1}
,"directory":{"windows":1}
,"windows":{"main":1,"single":1,"create":1}
,"main":{"set":1}
,"set":{"up":1,"choose":1,"creating":1,"ssigned":1,"clear":1,"authentication":1,"additional":1}
,"up":{"accounts":1,"privilege":1,"multiple":1}
,"based":{"authentication":1}
,"allows":{"use":1}
,"use":{"existing":1,"operating":1,"basic":1}
,"existing":{"authentication":1}
,"control":{"access":1}
,"access":{"databases":1,"file":1,"odbc":1}
,"databases":{"manage":1}
,"manage":{"independent":1,"security":1}
,"independent":{"list":1}
,"list":{"accounts":1}
,"each":{"filemaker":1,"account":1}
,"database":{"file":1,"files":1}
,"file":{"note":1,"external":1,"unauthorized":1,"system":1,"filemaker":1,"menu":1,"contain":1,"first":1,"se":1}
,"note":{"set":1}
,"servers":{"filemaker":1}
,"files":{"hosted":1,"shared":1,"filemaker":1,"access":1}
,"hosted":{"by":1}
,"by":{"filemaker":1}
,"shared":{"by":1,"database":1}
,"won\u2019t":{"authenticate":1}
,"sure":{"use":1}
,"operating":{"system":1}
,"system":{"security":1,"replicates":1}
,"security":{"settings":1,"if":1,"dialog":1}
,"settings":{"limit":1,"use":1}
,"limit":{"direct":1}
,"direct":{"access":1}
,"unauthorized":{"user":1}
,"user":{"move":1,"file":1}
,"move":{"file":1}
,"replicates":{"authentication":1}
,"environment":{"gain":1}
,"gain":{"access":1}
,"documentation":{"choose":1}
,"choose":{"file":1,"external":1,"create":1}
,"menu":{"manage":1}
,"dialog":{"box":1}
,"box":{"displays":1}
,"displays":{"detailed":1}
,"detailed":{"security":1}
,"basic":{"setup":1}
,"setup":{"new":1}
,"new":{"account":1}
,"account":{"authenticate":1,"determines":1,"active":1,"inactive":1,"external":1,"name":1,"authentication":1,"access":1,"unique":1,"authenticates":1}
,"group":{"name":1,"defined":1,"members":1,"member":1}
,"name":{"enter":1,"group":1,"auth":1,"two":1,"you\u2019ll":1}
,"enter":{"name":1}
,"defined":{"external":1}
,"privilege":{"set":1,"sets":1}
,"create":{"edit":1,"account":1}
,"edit":{"privilege":1}
,"editing":{"privilege":1,"accounts":1}
,"sets":{"privilege":1}
,"ssigned":{"account":1}
,"determines":{"externally":1}
,"externally":{"authenticated":1}
,"authenticated":{"group":1}
,"members":{"ile":1}
,"ile":{"account":1}
,"active":{"select":1}
,"select":{"checkbox":1}
,"checkbox":{"account":1,"it\u2019s":1}
,"inactive":{"set":1}
,"clear":{"checkbox":1}
,"it\u2019s":{"file":1,"set":1}
,"contain":{"multiple":1,"filemaker":1,"group":1}
,"multiple":{"accounts":1}
,"uthenticated":{"account":1,"accounts":1}
,"auth":{"identity":1}
,"identity":{"provider":1}
,"provider":{"ac":1}
,"ac":{"count":1}
,"count":{"external":1}
,"two":{"external":1}
,"member":{"hen":1}
,"hen":{"user":1}
,"first":{"matching":1,"ignored":1}
,"matching":{"account":1,"accounts":1}
,"order":{"matching":1,"accounts":1,"issue":1,"concern":1}
,"follow":{"first":1}
,"ignored":{"therefore":1}
,"therefore":{"it\u2019s":1}
,"situations":{"exist":1}
,"exist":{"wrong":1}
,"wrong":{"account":1}
,"se":{"creating":1,"filemaker":1}
,"issue":{"under":1}
,"under":{"specific":1}
,"specific":{"circumstances":1}
,"circumstances":{"hosting":1}
,"concern":{"each":1}
,"unique":{"name":1}
,"you\u2019ll":{"set":1}
,"additional":{"options":1}
,"options":{"filemaker":1}
,"help":{"shared":1}
,"odbc":{"data":1}
,"data":{"sql":1,"source":1}
,"sql":{"server":1}
,"configure":{"windows":1}
,"single":{"sign-on":1}
,"sign-on":{"authentication":1,"windows":1}
,"enabling":{"odbc":1}
,"source":{"single":1}
,"authenticates":{"via":1}
,"uthenticating":{"users":1}
}
;Search.control.loadWordPairs(pairs);
