var pairs =
{
"set":{"error":1,"running":1}
,"error":{"capture":1,"result":1,"condition":1,"take":1,"code":1,"codes":1,"dialog":1}
,"capture":{"uppresses":1,"filemaker":1,"script":1,"set":1,"[on]":1}
,"uppresses":{"enables":1}
,"enables":{"normal":1}
,"normal":{"filemaker":1}
,"filemaker":{"lert":1,"pro":1,"alert":1,"error":1,"data":1,"server":1,"cloud":1}
,"lert":{"messages":1}
,"messages":{"suppresses":1,"dialog":1,"filemaker":1,"caused":1}
,"suppresses":{"filemaker":1,"error":1}
,"pro":{"advanced":1,"6.0":1}
,"advanced":{"alert":1}
,"alert":{"messages":1}
,"dialog":{"boxes":1,"box":1,"off]":1,"[\u0022":1}
,"boxes":{"if":1,"suppressed":1}
,"if":{"error":1,"set":1,"records":1,"errors":1,"find":1,"[get":1,"automating":1}
,"result":{"100":1}
,"100":{"803":1}
,"803":{"standard":1}
,"standard":{"file":1}
,"file":{"dialog":1}
,"suppressed":{"open":1}
,"open":{"file":1}
,"box":{"re":1,"if":1,"set":1}
,"re":{"nables":1}
,"nables":{"alert":1}
,"6.0":{"earlier":1}
,"earlier":{"use":1}
,"use":{"script":1,"get":1}
,"script":{"step":1,"steps":1,"handle":1,"sub-script":1}
,"step":{"suppress":1,"returned":1,"intend":1,"clear":1}
,"suppress":{"normal":1}
,"caused":{"by":1}
,"by":{"subsequent":1,"get":1}
,"subsequent":{"script":1}
,"steps":{"script":1,"check":1}
,"handle":{"errors":1}
,"errors":{"anticipate":1,"sub-script":1,"occur":1}
,"anticipate":{"problems":1}
,"problems":{"include":1}
,"include":{"clear":1}
,"clear":{"instructions":1,"error":1}
,"instructions":{"error":1}
,"condition":{"by":1}
,"get":{"lasterror":1}
,"lasterror":{"function":1,"script":1,"=0]":1,"=400]":1,"=401]":1}
,"function":{"control":1}
,"control":{"script":1}
,"check":{"previous":1}
,"previous":{"script":1}
,"returned":{"error":1}
,"take":{"action":1}
,"action":{"use":1}
,"intend":{"test":1}
,"test":{"successful":1}
,"successful":{"intervening":1}
,"intervening":{"step":1}
,"code":{"intending":1}
,"intending":{"capture":1}
,"codes":{"set":1}
,"sub-script":{"errors":1,"captured":1}
,"captured":{"server-side":1}
,"server-side":{"scripts":1}
,"scripts":{"scripts":1,"performed":1,"filemaker":1}
,"performed":{"via":1}
,"via":{"ustom":1}
,"ustom":{"web":1}
,"web":{"publishing":1}
,"publishing":{"filemaker":1}
,"data":{"api":1}
,"api":{"lways":1}
,"lways":{"run":1}
,"run":{"if":1}
,"running":{"scripts":1}
,"server":{"filemaker":1}
,"cloud":{"performs":1}
,"performs":{"find":1}
,"find":{"suppresses":1,"[restore]":1,"if":1,"criteria":1,"request":1,"records":1}
,"records":{"found":1,"if":1,"match":1,"[restore":1,"else":1}
,"found":{"set":1,"\u0022]":1}
,"[on]":{"perform":1}
,"perform":{"find":1}
,"[restore]":{"performs":1,"if":1}
,"occur":{"sorts":1}
,"sorts":{"records":1}
,"criteria":{"all":1}
,"all":{"records":1}
,"match":{"find":1}
,"request":{"displays":1}
,"displays":{"custom":1}
,"custom":{"dialog":1}
,"[get":{"lasterror":1}
,"=0]":{"sort":1}
,"sort":{"records":1}
,"[restore":{"dialog":1}
,"off]":{"else":1}
,"else":{"if":1}
,"=400]":{"show":1}
,"show":{"all":1,"custom":1}
,"=401]":{"show":1}
,"[\u0022":{"find":1}
,"\u0022]":{"end":1}
,"end":{"if":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
