var pairs =
{
"functions":{"reference":1,"by":1,"grouped":1,"operates":1,"bout":1,"compatible":1}
,"reference":{"links":1,"category":1,"alphabetical":1}
,"links":{"find":1}
,"find":{"functions":1}
,"by":{"category":1,"type":1}
,"category":{"alphabetically":1,"list":1}
,"alphabetically":{"functions":1}
,"list":{"functions":1,"category":1,"filemaker":1}
,"alphabetical":{"list":1}
,"filemaker":{"pro":1,"clients":1}
,"pro":{"functions":1}
,"grouped":{"by":1,"text":1}
,"type":{"data":1}
,"data":{"operate":1,"return":1,"use":1}
,"operate":{"by":1}
,"return":{"position":1}
,"position":{"function":1}
,"function":{"returns":1}
,"returns":{"number":1}
,"number":{"grouped":1}
,"text":{"functions":1,"data":1}
,"operates":{"text":1}
,"use":{"functions":1}
,"bout":{"formulas":1}
,"formulas":{"note":1}
,"note":{"all":1}
,"all":{"functions":1,"filemaker":1}
,"compatible":{"all":1}
,"clients":{"exceptions":1}
,"exceptions":{"individual":1}
,"individual":{"topics":1}
}
;Search.control.loadWordPairs(pairs);
