var pairs =
{
"selecting":{"field":1}
,"field":{"browse":1,"data":1,"enter":1,"field":1,"select":1,"choose":1,"record":1,"setting":1,"press":1,"formatted":1}
,"browse":{"mode":1}
,"mode":{"find":1,"browse":1,"select":1,"press":1}
,"find":{"mode":1,"request":1}
,"select":{"field":1,"contents":1,"all":1,"summary":1}
,"data":{"find":1,"entry":1}
,"enter":{"find":1,"return":1}
,"request":{"select":1}
,"contents":{"field":1}
,"choose":{"edit":1}
,"edit":{"menu":1}
,"menu":{"select":1}
,"all":{"move":1}
,"move":{"next":1,"previous":1,"fields":1,"summary":1}
,"next":{"field":1}
,"record":{"established":1}
,"established":{"tab":1}
,"tab":{"order":1,"enter":1,"panels":1}
,"order":{"pressing":1,"layout":1,"data":1,"browse":1}
,"pressing":{"tab":1,"key":1}
,"return":{"notes":1}
,"notes":{"set":1}
,"set":{"keys":1,"tab":1}
,"keys":{"move":1}
,"setting":{"eys":1,"tab":1}
,"eys":{"moving":1}
,"moving":{"fields":1}
,"fields":{"fields":1,"tab":1,"set":1,"move":1,"omitted":1,"find":1,"if":1}
,"panels":{"slide":1,"front":1}
,"slide":{"panels":1}
,"front":{"ost":1}
,"ost":{"panel":1}
,"panel":{"skipped":1}
,"skipped":{"move":1}
,"previous":{"field":1}
,"press":{"shift-tab":1,"key":1}
,"shift-tab":{"shift-return":1}
,"shift-return":{"shift-enter":1}
,"shift-enter":{"change":1}
,"change":{"order":1}
,"key":{"moves":1,"move":1,"select":1}
,"moves":{"fields":1}
,"layout":{"setting":1}
,"entry":{"press":1,"allowing":1,"fields":1}
,"omitted":{"tab":1}
,"summary":{"calculation":1,"fields":1}
,"calculation":{"fields":1}
,"if":{"select":1}
,"formatted":{"prevent":1}
,"prevent":{"entry":1}
,"allowing":{"preventing":1}
,"preventing":{"entry":1}
}
;Search.control.loadWordPairs(pairs);
