var pairs =
{
"effects":{"changing":1}
,"changing":{"field":1}
,"field":{"types":1,"type":1,"contain":1,"if":1,"text":1,"date":1,"number":1,"first":1,"existing":1,"deleted":1,"container":1,"field":1,"global":1,"summary":1,"delete":1,"changing":1,"relationship":1,"match":1}
,"types":{"changing":1}
,"type":{"data":1,"field":1,"remove":1,"calculation":1,"summary":1,"if":1,"match":1}
,"data":{"field":1,"changed":1,"deleted":1,"replaced":1}
,"contain":{"find":1,"text":1}
,"find":{"sort":1}
,"sort":{"field":1,"chronologically":1}
,"if":{"change":1,"field":1}
,"change":{"date":1,"text":1,"summary":1,"field":1}
,"date":{"field":1,"sort":1,"time":1}
,"text":{"field":1,"number":1}
,"chronologically":{"change":1}
,"number":{"date":1}
,"time":{"timestamp":1,"fields":1}
,"timestamp":{"field":1}
,"first":{"255":1,"line":1}
,"255":{"characters":1}
,"characters":{"converted":1,"values":1}
,"converted":{"moved":1}
,"moved":{"first":1}
,"line":{"deleting":1}
,"deleting":{"remaining":1}
,"remaining":{"characters":1}
,"values":{"dates":1}
,"dates":{"times":1}
,"times":{"displayed":1}
,"displayed":{"indexed":1}
,"indexed":{"question":1}
,"question":{"mark":1}
,"mark":{"date":1}
,"fields":{"contain":1,"match":1,"fields":1,"global":1,"key":1,"indexing":1}
,"existing":{"data":1}
,"changed":{"container":1}
,"container":{"field":1,"fields":1}
,"remove":{"option":1}
,"option":{"global":1}
,"global":{"storage":1}
,"storage":{"existing":1,"summary":1}
,"deleted":{"field":1}
,"calculation":{"summary":1}
,"summary":{"field":1,"alert":1,"include":1,"fields":1}
,"replaced":{"formula":1}
,"formula":{"summary":1}
,"alert":{"change":1}
,"include":{"field":1}
,"delete":{"summary":1}
,"relationship":{"change":1,"new":1,"container":1}
,"match":{"field":1,"fields":1}
,"new":{"field":1}
,"key":{"fields":1}
,"indexing":{"disabled":1}
,"disabled":{"key":1}
}
;Search.control.loadWordPairs(pairs);
