var pairs =
{
"get":{"windowcontentheig":1,"windowcontentheight":1,"windowheight":1,"window":1}
,"windowcontentheig":{"ht":1}
,"ht":{"returns":1}
,"returns":{"height":1,"400":1,"37":1,"663":1}
,"height":{"points":1,"437":1,"title":1,"44":1,"window":1}
,"points":{"window":1,"menu":1}
,"window":{"content":1,"doesn\u2019t":1,"height":1}
,"content":{"get":1,"depends":1,"space":1,"includes":1,"height":1}
,"windowcontentheight":{"none":1,"get":1,"returns":1,"function":1}
,"none":{"number":1}
,"number":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1,"go":1}
,"pro":{"7.0":1}
,"7.0":{"content":1}
,"depends":{"current":1}
,"current":{"size":1,"window":1}
,"size":{"active":1}
,"active":{"window":1}
,"doesn\u2019t":{"include":1}
,"include":{"title":1,"status":1}
,"title":{"bar":1}
,"bar":{"scroll":1,"status":1,"menu":1,"toolbar":1,"horizontal":1,"get":1,"27":1,"734":1,"hidden":1,"showin":1}
,"scroll":{"bars":1,"bar":1}
,"bars":{"page":1,"footer":1}
,"page":{"margins":1}
,"margins":{"content":1}
,"space":{"inside":1}
,"inside":{"controls":1}
,"controls":{"include":1}
,"status":{"toolbar":1,"bar":1}
,"toolbar":{"if":1,"scroll":1,"macos":1,"isn\u2019t":1,"44":1,"menu":1}
,"if":{"currently":1}
,"currently":{"filemaker":1}
,"webdirect":{"content":1}
,"includes":{"menu":1,"layout":1}
,"menu":{"bar":1}
,"footer":{"filemaker":1}
,"go":{"content":1}
,"layout":{"doesn\u2019t":1}
,"macos":{"returns":1,"combines":1}
,"400":{"current":1}
,"437":{"status":1}
,"isn\u2019t":{"macos":1,"iphone":1}
,"combines":{"get":1}
,"windowheight":{"determine":1,"-get":1}
,"determine":{"height":1}
,"horizontal":{"scroll":1}
,"-get":{"windowcontentheight":1}
,"37":{"window":1}
,"iphone":{"5.8-inch":1}
,"5.8-inch":{"displays":1}
,"displays":{"portrait":1}
,"portrait":{"orientation":1}
,"orientation":{"height":1}
,"44":{"points":1,"oints":1}
,"27":{"oints":1}
,"oints":{"toolbar":1,"status":1}
,"function":{"returns":1}
,"663":{"hen":1}
,"hen":{"toolbar":1}
,"734":{"hen":1}
,"hidden":{"status":1}
,"showin":{"get":1}
}
;Search.control.loadWordPairs(pairs);
