var pairs =
{
"transf":{"ring":1}
,"ring":{"container":1}
,"container":{"data":1,"field":1,"fields":1}
,"data":{"set":1,"externally":1,"field":1,"stored":1,"filemaker":1,"base":1,"that\u2019s":1,"secure":1,"text":1,"if":1,"transfer":1,"container":1,"embedded":1,"all":1,"transferred":1,"failed":1,"existing":1,"reading":1}
,"set":{"up":1}
,"up":{"container":1}
,"field":{"store":1,"automatically":1,"dialog":1,"convert":1,"options":1,"checkbox":1,"data":1,"transfer":1}
,"store":{"data":1}
,"externally":{"embedded":1,"use":1,"container":1,"base":1}
,"embedded":{"data":1,"container":1,"stored":1}
,"automatically":{"moved":1}
,"moved":{"external":1}
,"external":{"directory":1}
,"directory":{"if":1,"transfer":1,"storage":1}
,"if":{"want":1,"changed":1}
,"want":{"embedded":1}
,"stored":{"externally":1,"by":1}
,"use":{"steps":1}
,"steps":{"transfer":1}
,"transfer":{"data":1,"dialog":1,"destination":1,"exclude":1,"deselect":1,"filemaker":1,"process":1,"doesn\u2019t":1,"completed":1,"summary":1,"open":1,"recent":1,"session":1,"place":1,"event":1,"container":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"settings":1,"transfers":1}
,"settings":{"choose":1}
,"choose":{"options":1}
,"options":{"field":1,"container":1}
,"dialog":{"box":1}
,"box":{"move":1,"container":1,"appears":1,"note":1,"transfer":1,"stopping":1}
,"move":{"data":1,"files":1}
,"base":{"directory":1,"directories":1}
,"that\u2019s":{"stored":1}
,"convert":{"data":1}
,"secure":{"storage":1}
,"storage":{"open":1,"vice":1,"calculation":1,"options":1,"type":1}
,"open":{"storage":1,"log":1}
,"vice":{"versa":1}
,"versa":{"move":1}
,"directories":{"move":1}
,"files":{"open":1,"stored":1,"transferred":1,"skipped":1}
,"calculation":{"changed":1}
,"changed":{"files":1,"storage":1}
,"by":{"reference":1,"default":1,"steps":1}
,"reference":{"embedded":1}
,"text":{"objects":1}
,"objects":{"layout":1,"transferred":1}
,"layout":{"objects":1}
,"transferred":{"full":1,"restart":1,"number":1}
,"full":{"access":1}
,"access":{"privileges":1}
,"privileges":{"transfer":1}
,"appears":{"exit":1,"all":1,"list":1,"status":1}
,"exit":{"dialog":1}
,"note":{"manage":1}
,"manage":{"containers":1}
,"containers":{"dialog":1}
,"all":{"container":1,"selected":1}
,"fields":{"transfer":1,"by":1,"destinations":1}
,"destination":{"including":1}
,"including":{"data":1}
,"type":{"file":1}
,"file":{"path":1,"reading":1,"next":1,"displays":1,"scroll":1,"data":1}
,"path":{"field":1}
,"checkbox":{"list":1,"next":1}
,"list":{"appears":1,"fields":1}
,"default":{"selected":1}
,"selected":{"data":1,"fields":1}
,"exclude":{"field":1}
,"deselect":{"checkbox":1}
,"next":{"field":1,"transfer.log":1}
,"transfers":{"data":1}
,"destinations":{"stop":1}
,"stop":{"transfer":1,"container":1}
,"process":{"stop":1,"time":1}
,"stopping":{"transfer":1}
,"doesn\u2019t":{"roll":1}
,"roll":{"back":1}
,"back":{"data":1}
,"restart":{"process":1}
,"time":{"by":1,"time":1,"zone":1}
,"completed":{"transfer":1}
,"summary":{"dialog":1}
,"status":{"number":1}
,"number":{"files":1,"description":1}
,"skipped":{"log":1}
,"log":{"transfer":1,"file":1}
,"reading":{"file":1,"transfer.log":1}
,"transfer.log":{"file":1}
,"displays":{"container":1}
,"failed":{"transfer":1}
,"recent":{"data":1}
,"existing":{"transfer.log":1}
,"scroll":{"end":1}
,"end":{"file":1}
,"session":{"left":1}
,"left":{"right":1}
,"right":{"columns":1}
,"columns":{"show":1}
,"show":{"date":1}
,"date":{"time":1}
,"zone":{"transfer":1}
,"place":{"filename":1}
,"filename":{"error":1}
,"error":{"number":1}
,"description":{"transfer":1}
,"event":{"transfer":1}
}
;Search.control.loadWordPairs(pairs);
