var pairs =
{
"insert":{"pdf":1,"interactive":1}
,"pdf":{"mports":1,"file":1,"performed":1,"returns":1,"relative":1,"[\u0022":1,"files":1}
,"mports":{"pdf":1}
,"file":{"file":1,"reference":1,"container":1,"option":1,"if":1,"referenced":1,"allows":1,"intend":1,"path":1,"paths":1,"source":1,"imported":1,"options":1,"field":1}
,"reference":{"current":1,"instructs":1,"source":1}
,"current":{"interactive":1}
,"interactive":{"container":1,"containers":1}
,"container":{"store":1,"field":1,"file":1,"fields":1}
,"store":{"reference":1,"link":1}
,"instructs":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"advanced":1,"12.0":1}
,"advanced":{"store":1,"file":1,"display":1,"displays":1}
,"link":{"pdf":1}
,"field":{"actual":1,"field":1,"use":1,"script":1,"layout":1,"inserts":1,"[products":1}
,"actual":{"file":1}
,"option":{"reduce":1,"filemaker":1}
,"reduce":{"size":1}
,"size":{"filemaker":1}
,"if":{"move":1,"active":1}
,"move":{"delete":1}
,"delete":{"file":1}
,"referenced":{"filemaker":1}
,"display":{"source":1}
,"source":{"file":1}
,"allows":{"pdf":1}
,"intend":{"insert":1}
,"path":{"image":1,"image:documents\u002Fproduct":1}
,"image":{"imagemac":1}
,"imagemac":{"magewin":1}
,"magewin":{"imagelinux":1}
,"imagelinux":{"creating":1}
,"creating":{"file":1}
,"paths":{"filemaker":1}
,"12.0":{"field":1}
,"use":{"go":1}
,"go":{"field":1}
,"script":{"step":1,"performed":1}
,"step":{"performing":1,"insert":1,"interactive":1}
,"performing":{"script":1}
,"performed":{"file":1,"insert":1}
,"displays":{"dialog":1}
,"dialog":{"box":1}
,"box":{"user":1}
,"user":{"select":1}
,"select":{"preview":1}
,"preview":{"file":1}
,"imported":{"filemaker":1}
,"webdirect":{"support":1}
,"support":{"store":1}
,"options":{"if":1}
,"active":{"container":1}
,"layout":{"script":1}
,"returns":{"error":1}
,"error":{"code":1}
,"code":{"captured":1}
,"captured":{"get":1}
,"get":{"lasterror":1}
,"lasterror":{"function":1}
,"function":{"script":1}
,"containers":{"pecifying":1,"automating":1}
,"pecifying":{"formats":1}
,"formats":{"container":1}
,"fields":{"file":1}
,"inserts":{"pdf":1}
,"relative":{"path":1}
,"image:documents\u002Fproduct":{"description.pdf":1}
,"description.pdf":{"go":1,"\u0022]":1}
,"[products":{":file]":1}
,":file]":{"insert":1}
,"[\u0022":{"roduct":1}
,"roduct":{"description.pdf":1}
,"\u0022]":{"pdf":1}
,"files":{"interactive":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
