var pairs =
{
"get":{"connectionattributes":1}
,"connectionattributes":{"returns":1,"none":1}
,"returns":{"name":1,"empty":1,"[peer":1}
,"name":{"current":1}
,"current":{"file\u0027s":1,"file":1,"ssl":1}
,"file\u0027s":{"host":1}
,"host":{"certificate":1,"filemaker":1,"use":1,"single-machine":1,"named":1}
,"certificate":{"authority":1,"secure":1,"issued":1,"commonname":1}
,"authority":{"issued":1}
,"issued":{"ssl":1,"by":1}
,"ssl":{"certificate":1}
,"secure":{"connection":1}
,"connection":{"get":1,"client":1}
,"none":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1,"server":1,"cloud":1}
,"pro":{"13.0":1}
,"13.0":{"get":1}
,"empty":{"string":1}
,"string":{"if":1}
,"if":{"current":1,"host":1}
,"file":{"hosted":1}
,"hosted":{"host":1}
,"server":{"filemaker":1,"macos":1}
,"cloud":{"host":1}
,"use":{"ssl":1}
,"client":{"host":1}
,"single-machine":{"deployment":1}
,"deployment":{"filemaker":1}
,"macos":{"if":1}
,"named":{"group_server":1}
,"group_server":{"current":1,"ca":1}
,"by":{"xyz":1}
,"xyz":{"get":1}
,"[peer":{"certificate":1}
,"commonname":{"group_server":1}
,"ca":{"issuers":1}
,"issuers":{"xyz":1}
}
;Search.control.loadWordPairs(pairs);
