var pairs =
{
"nserting":{"merge":1}
,"merge":{"variables":1,"variable":1,"values":1,"field":1,"fields":1}
,"variables":{"layout":1,"tasks":1,"use":1,"field":1}
,"layout":{"create":1,"mode":1,"want":1,"insert":1,"$$and":1,"display":1,"header":1,"by":1,"use":1,"get":1,"examples":1}
,"create":{"merge":1,"variable":1,"script":1}
,"variable":{"displays":1,"use":1,"display":1,"value":1,"set":1,"script":1,"choose":1,"insert":1,"text":1,"<$$>":1,"type":1,"name":1,"created":1,"named":1,"[$$acctname":1,"<$$acctname":1,"[$$ponum":1,"<$$ponum":1,"[$pp":1,"layout":1,"merge":1,"include":1,"attributes":1,"inserted":1,"inserting":1}
,"displays":{"value":1,"name":1}
,"value":{"variable":1,"browse":1,"get":1,"merge":1}
,"use":{"merge":1,"esh":1,"get":1}
,"tasks":{"place":1}
,"place":{"global":1}
,"global":{"fields":1,"variables":1,"variable":1}
,"fields":{"unstored":1,"merge":1,"layout":1}
,"unstored":{"calculation":1}
,"calculation":{"fields":1}
,"display":{"total":1,"name":1,"current":1,"data":1}
,"total":{"cost":1,"number":1}
,"cost":{"bottom":1}
,"bottom":{"invoice":1}
,"invoice":{"display":1}
,"name":{"account":1,"name":1,"variable":1,"user\u2019s":1}
,"account":{"print":1,"create":1}
,"print":{"report":1,"records":1}
,"report":{"merge":1,"page":1}
,"browse":{"find":1}
,"find":{"preview":1}
,"preview":{"modes":1,"mode":1}
,"modes":{"print":1}
,"records":{"create":1,"manually":1}
,"set":{"variable":1}
,"script":{"step":1,"includes":1,"enter":1,"[indefinitely]":1}
,"step":{"it\u2019s":1,"ensure":1,"automatically":1,"if":1,"create":1,"set":1}
,"it\u2019s":{"idea":1}
,"idea":{"reate":1}
,"reate":{"global":1}
,"mode":{"layout":1,"go":1,"including":1}
,"want":{"insert":1,"view":1}
,"insert":{"variable":1,"menu":1,"merge":1}
,"choose":{"insert":1}
,"menu":{"merge":1}
,"text":{"block":1,"\u2011mpo":1,"page":1,"attributes":1,"formatting":1,"use":1}
,"block":{"by":1,"inserted":1}
,"by":{"itself":1,"creating":1}
,"itself":{"layout":1,"change":1}
,"field":{"object":1,"syntax":1,"display":1}
,"object":{"want":1,"script":1}
,"view":{"placeholder":1}
,"placeholder":{"merge":1,"variable":1}
,"<$$>":{"appears":1}
,"appears":{"layout":1}
,"$$and":{"symbols":1}
,"symbols":{"placeholder":1,"select":1}
,"type":{"merge":1}
,"created":{"step":1}
,"ensure":{"merge":1}
,"values":{"displayed":1,"select":1}
,"displayed":{"accurately":1}
,"accurately":{"each":1}
,"each":{"record":1}
,"record":{"refreshed":1,"number":1}
,"refreshed":{"browsed":1}
,"browsed":{"previewed":1}
,"previewed":{"printed":1}
,"printed":{"refresh":1}
,"refresh":{"records":1,"window":1,"objects":1}
,"manually":{"by":1}
,"creating":{"efresh":1,"script":1,"merge":1}
,"efresh":{"utton":1}
,"utton":{"calls":1}
,"calls":{"refresh":1}
,"window":{"script":1,"use":1}
,"automatically":{"by":1}
,"includes":{"refresh":1}
,"if":{"refresh":1,"merge":1}
,"objects":{"window":1}
,"esh":{"object":1}
,"named":{"<$$acctname":1,"<$$ponum":1,"<$pp":1}
,"<$$acctname":{"displays":1,"layout":1}
,"user\u2019s":{"account":1}
,"[$$acctname":{"value":1}
,"get":{"accountname":1,"recordnumber":1,"function":1,"unctions":1}
,"accountname":{")]":1}
,")]":{"insert":1,"go":1}
,"<$$ponum":{"appends":1,"layout":1}
,"appends":{"text":1}
,"\u2011mpo":{"current":1,"\u0022]":1}
,"current":{"record":1,"page":1}
,"number":{"form":1,"create":1,"total":1,"pages":1,"symbol":1,"repeating":1,"variable":1}
,"form":{"purchase":1}
,"purchase":{"order":1}
,"order":{"number":1}
,"[$$ponum":{"value":1}
,"recordnumber":{"&\u0022":1}
,"&\u0022":{"\u2011mpo":1}
,"\u0022]":{"insert":1}
,"page":{"number":1,"10":1,"pagenumber":1}
,"pages":{"report":1}
,"10":{"start":1}
,"start":{"by":1}
,"<$pp":{"create":1,"variable":1}
,"enter":{"preview":1}
,"go":{"record\u002Frequest\u002Fpage":1}
,"record\u002Frequest\u002Fpage":{"[last]":1,"[first]":1}
,"[last]":{"set":1}
,"[$pp":{"value:get":1}
,"value:get":{"pagenumber":1}
,"pagenumber":{")]":1,"merge":1,"<$pp":1}
,"[first]":{"pause\u002Fresume":1}
,"pause\u002Fresume":{"script":1}
,"[indefinitely]":{"combine":1}
,"combine":{"text":1}
,"symbol":{"pagenumber":1}
,"header":{"footer":1}
,"footer":{"page":1}
,"include":{"repetition":1}
,"repetition":{"index":1}
,"index":{"number":1}
,"repeating":{"field":1}
,"syntax":{"$variable":1}
,"$variable":{"[repetition]":1}
,"[repetition]":{"file":1}
,"file":{"path":1}
,"path":{"value":1}
,"attributes":{"text":1,"if":1,"merge":1}
,"inserted":{"layout\u2019s":1,"layout":1}
,"layout\u2019s":{"default":1}
,"default":{"text":1}
,"change":{"text":1}
,"select":{"entire":1,"text":1}
,"entire":{"merge":1}
,"including":{"$$":1}
,"$$":{"symbols":1}
,"formatting":{"options":1,"text":1}
,"options":{"formatting":1}
,"data":{"placing":1}
,"placing":{"merge":1}
,"function":{"global":1}
,"inserting":{"date":1}
,"date":{"page":1}
,"unctions":{"insert":1}
}
;Search.control.loadWordPairs(pairs);
