var pairs =
{
"automating":{"tasks":1}
,"tasks":{"scripts":1,"ike":1,"creates":1,"define":1}
,"scripts":{"scripts":1,"simple":1,"by":1,"run":1,"filemaker":1,"complex":1,"sub-scripts":1,"conditional":1,"defined":1,"each":1,"performed":1,"debugging":1,"react":1,"use":1,"all":1,"set":1,"menu":1,"database":1,"planning":1}
,"simple":{"tasks":1}
,"ike":{"setting":1,"preparing":1}
,"setting":{"print":1,"script":1}
,"print":{"orientation":1}
,"orientation":{"complex":1}
,"complex":{"tasks":1,"set":1,"reuse":1}
,"preparing":{"customized":1}
,"customized":{"mailing":1}
,"mailing":{"each":1}
,"each":{"client":1,"task":1,"file":1,"privileges":1}
,"client":{"define":1,"script":1,"want":1}
,"define":{"complex":1,"sub-scripts":1,"script":1,"test":1}
,"set":{"tasks":1,"specific":1,"records":1,"all":1,"use":1,"up":1,"field":1,"capture":1,"error":1,"default":1,"future":1}
,"creates":{"email":1}
,"email":{"clients":1,"tailored":1}
,"clients":{"clients":1,"database":1}
,"database":{"made":1,"current":1,"file":1,"solutions":1,"define":1,"considered":1,"creating":1}
,"made":{"purchases":1}
,"purchases":{"last":1}
,"last":{"week":1,"record":1,"error":1}
,"week":{"script":1}
,"script":{"composes":1,"switches":1,"steps":1,"accomplish":1,"performs":1,"script":1,"step":1,"call":1,"number":1,"run":1,"operate":1,"all":1,"open":1,"defined":1,"record":1,"start":1,"performed":1,"initially":1,"remains":1,"associated":1,"switch":1,"proper":1,"requires":1,"advance":1,"finish":1,"reaches":1,"while":1,"contain":1,"finishes":1,"test":1,"use":1,"save":1,"preserve":1,"debugger":1,"handle":1,"behalf":1,"eed":1,"scripts":1,"workspace":1,"trigger":1,"database":1}
,"composes":{"email":1}
,"tailored":{"each":1}
,"switches":{"preview":1,"window":1,"foreground":1}
,"preview":{"mode":1,"modes":1}
,"mode":{"pauses":1,"acts":1,"script":1,"automatically":1,"executing":1}
,"pauses":{"message":1}
,"message":{"ooks":1}
,"ooks":{"task":1}
,"task":{"initiated":1,"scripts":1,"tasks":1,"define":1,"script":1,"exit":1}
,"initiated":{"by":1}
,"by":{"clicking":1,"selecting":1,"filemaker":1,"get":1,"assigned":1}
,"clicking":{"button":1}
,"button":{"sales":1,"perform":1}
,"sales":{"entry":1}
,"entry":{"layout":1}
,"layout":{"build":1,"scripts":1,"sure":1,"layouts":1,"script":1,"preview":1,"mode":1,"while":1,"fields":1}
,"build":{"scripts":1}
,"selecting":{"list":1}
,"list":{"filemaker":1}
,"filemaker":{"pro":1,"server":1,"cloud":1}
,"pro":{"advanced":1}
,"advanced":{"commands":1,"by":1}
,"commands":{"called":1}
,"called":{"script":1,"layout":1}
,"steps":{"pecifying":1,"correct":1,"hould":1,"creating":1,"want":1,"include":1,"script":1,"go":1,"users":1,"run":1}
,"pecifying":{"options":1}
,"options":{"if":1}
,"if":{"arranging":1,"multiple":1,"include":1,"window":1,"windows":1,"script":1,"users":1}
,"arranging":{"steps":1}
,"correct":{"order":1}
,"order":{"perform":1,"decide":1,"sort":1,"unsorted":1,"records":1}
,"perform":{"task":1,"script":1,"sub-script":1,"find":1,"all":1}
,"run":{"client":1,"scripts":1,"schedule":1,"nder":1,"run":1,"number":1,"layout":1,"browse":1,"condition":1,"full":1,"script":1}
,"want":{"run":1,"plan":1,"script":1,"found":1,"use":1}
,"server":{"filemaker":1}
,"cloud":{"improve":1,"time":1}
,"improve":{"performance":1}
,"performance":{"automatically":1}
,"automatically":{"run":1,"switch":1}
,"schedule":{"running":1}
,"running":{"scripts":1,"script":1}
,"time":{"spend":1}
,"spend":{"planning":1}
,"planning":{"script":1}
,"accomplish":{"want":1}
,"plan":{"questions":1}
,"questions":{"separate":1,"ready":1}
,"separate":{"task":1,"scripts":1}
,"sub-scripts":{"each":1,"easier":1,"use":1,"control":1}
,"performs":{"sub-scripts":1}
,"easier":{"design":1}
,"design":{"test":1}
,"test":{"scripts":1,"script":1,"troubleshoot":1}
,"reuse":{"sub-scripts":1}
,"use":{"perform":1,"go":1,"found":1,"script":1,"elect":1,"enter":1,"sort":1,"if":1,"allow":1,"ause\u002Fresume":1,"function":1,"set":1,"privilege":1,"onfirstwindowopen":1}
,"step":{"perform":1,"run":1,"change":1,"decide":1,"related":1,"go":1,"starting":1,"determine":1,"window":1,"modify":1,"set":1,"insert":1,"require":1,"don\u2019t":1,"switch":1,"unsort":1,"entering":1,"loop":1,"exit":1,"end":1,"control":1,"else":1,"script":1,"pause":1,"create":1,"suppress":1,"all":1}
,"sub-script":{"inside":1}
,"inside":{"script":1}
,"hould":{"run":1}
,"nder":{"conditions":1}
,"conditions":{"script":1,"empty":1}
,"number":{"times":1,"control":1}
,"times":{"condition":1}
,"condition":{"met":1,"users":1,"reported":1}
,"met":{"script":1,"use":1}
,"call":{"scripts":1}
,"control":{"progression":1,"script":1,"multiple":1,"if":1,"use":1,"users":1}
,"progression":{"script":1}
,"creating":{"scripts":1,"editing":1}
,"conditional":{"steps":1}
,"defined":{"file":1,"cases":1}
,"file":{"level":1,"script":1,"if":1,"data":1,"separate":1,"depending":1,"pause":1,"setting":1}
,"level":{"called":1}
,"sure":{"script":1}
,"operate":{"layout":1,"file":1}
,"layouts":{"expect":1,"script":1}
,"expect":{"use":1}
,"go":{"layout":1,"record\u002Frequest\u002Fpage":1,"portal":1,"field":1}
,"change":{"layouts":1}
,"all":{"records":1,"data":1,"script":1,"users":1,"scripts":1}
,"records":{"database":1,"use":1,"want":1,"processed":1,"created":1,"script":1,"properly":1}
,"current":{"found":1,"record":1,"script":1,"layout":1,"sort":1}
,"found":{"set":1,"sets":1}
,"specific":{"set":1,"record":1,"window":1}
,"sets":{"script":1,"control":1,"users":1}
,"include":{"records":1,"navigation":1}
,"data":{"database":1,"processing":1,"fields":1,"if":1,"note":1}
,"multiple":{"files":1,"fields":1,"field":1}
,"files":{"script":1}
,"open":{"file":1}
,"cases":{"script":1}
,"processing":{"database":1,"script":1}
,"solutions":{"file":1}
,"depending":{"complexity":1}
,"complexity":{"task":1}
,"record":{"script":1,"specific":1,"current":1,"found":1,"if":1,"loop":1,"processing":1}
,"start":{"loop":1}
,"loop":{"script":1,"starts":1,"record":1,"order":1,"if":1}
,"decide":{"loop":1,"current":1}
,"starts":{"first":1}
,"first":{"last":1}
,"record\u002Frequest\u002Fpage":{"script":1}
,"related":{"record":1}
,"portal":{"row":1}
,"row":{"script":1}
,"starting":{"record":1}
,"navigation":{"script":1}
,"determine":{"current":1}
,"performed":{"window":1,"layout":1}
,"window":{"want":1,"background":1,"scripted":1,"use":1,"script":1,"if":1,"file":1,"foreground":1}
,"initially":{"attached":1}
,"attached":{"specific":1}
,"background":{"script":1}
,"remains":{"window":1}
,"scripted":{"action":1}
,"action":{"switches":1}
,"elect":{"window":1}
,"foreground":{"window":1}
,"pause":{"script":1,"predefined":1}
,"associated":{"window":1}
,"windows":{"script":1}
,"switch":{"modes":1,"browse":1,"layout":1}
,"modes":{"script":1,"sure":1}
,"browse":{"find":1,"mode":1}
,"find":{"layout":1,"mode":1,"request":1}
,"proper":{"mode":1}
,"acts":{"use":1}
,"enter":{"browse":1,"find":1}
,"modify":{"data":1,"individual":1}
,"fields":{"records":1,"layouts":1,"script":1,"gray":1}
,"up":{"perform":1}
,"request":{"note":1}
,"note":{"scripts":1,"yo":1}
,"executing":{"fields":1}
,"field":{"script":1,"current":1,"record":1}
,"insert":{"text":1}
,"text":{"script":1}
,"require":{"field":1}
,"while":{"set":1,"running":1}
,"don\u2019t":{"use":1}
,"requires":{"place":1}
,"place":{"fields":1}
,"gray":{"right":1}
,"right":{"layout":1}
,"users":{"records":1,"stop":1,"allowed":1,"access":1,"perform":1}
,"processed":{"order":1}
,"sort":{"order":1,"records":1}
,"unsorted":{"order":1}
,"created":{"use":1}
,"unsort":{"records":1}
,"entering":{"loop":1}
,"properly":{"processing":1}
,"advance":{"multiple":1}
,"exit":{"loop":1,"script":1}
,"end":{"loop":1}
,"finish":{"all":1}
,"else":{"if":1,"script":1}
,"reaches":{"condition":1}
,"stop":{"script":1}
,"contain":{"process":1}
,"process":{"result":1}
,"result":{"incomplete":1}
,"incomplete":{"incorrect":1}
,"incorrect":{"data":1}
,"finishes":{"use":1}
,"allow":{"user":1,"script":1}
,"user":{"abort":1,"errors":1,"allowed":1}
,"abort":{"script":1}
,"ause\u002Fresume":{"script":1}
,"predefined":{"points":1}
,"points":{"script":1}
,"save":{"copy":1}
,"copy":{"database":1}
,"preserve":{"original":1}
,"original":{"data":1}
,"yo":{"use":1}
,"debugger":{"test":1}
,"troubleshoot":{"scripts":1}
,"debugging":{"script":1}
,"handle":{"error":1}
,"error":{"conditions":1,"condition":1,"capture":1,"alerts":1}
,"empty":{"found":1}
,"capture":{"last":1,"script":1}
,"reported":{"by":1}
,"get":{"lasterror":1}
,"lasterror":{"function":1}
,"function":{"use":1,"if":1}
,"create":{"scripts":1,"button":1}
,"react":{"gracefully":1}
,"gracefully":{"user":1}
,"errors":{"unexpected":1}
,"unexpected":{"greater":1}
,"greater":{"control":1}
,"suppress":{"error":1}
,"alerts":{"ormally":1}
,"ormally":{"display":1}
,"display":{"ed":1}
,"ed":{"situations":1}
,"situations":{"replace":1}
,"replace":{"own":1}
,"own":{"ow":1}
,"ow":{"custom":1}
,"custom":{"dialog":1}
,"dialog":{"script":1}
,"allowed":{"perform":1,"execute":1,"by":1}
,"privilege":{"sets":1}
,"access":{"scripting":1,"privileges":1}
,"scripting":{"use":1}
,"execute":{"modify":1}
,"individual":{"scripts":1}
,"default":{"permission":1}
,"permission":{"each":1}
,"privileges":{"set":1,"allow":1,"creating":1}
,"future":{"new":1}
,"new":{"scripts":1}
,"full":{"access":1}
,"behalf":{"user":1}
,"assigned":{"privileges":1}
,"editing":{"privilege":1,"scripts":1}
,"eed":{"create":1}
,"menu":{"scripts":1}
,"workspace":{"script":1}
,"trigger":{"activated":1,"run":1}
,"activated":{"use":1}
,"onfirstwindowopen":{"script":1}
,"considered":{"questions":1}
,"ready":{"manage":1}
,"manage":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
