var pairs =
{
"dding":{"add-on":1}
,"add-on":{"tables":1,"table":1}
,"tables":{"custom":1,"add":1,"join":1}
,"custom":{"apps":1,"app":1}
,"apps":{"create":1}
,"create":{"custom":1,"portal":1}
,"app":{"extend":1,"phone":1,"first":1,"layout":1,"lready":1,"table":1,"add-on":1}
,"extend":{"by":1}
,"by":{"adding":1}
,"adding":{"add-on":1}
,"table":{"display":1,"add-on":1,"predefined":1,"adds":1,"fields":1,"current":1,"track":1,"illustration":1,"store":1,"layout":1,"primary":1,"if":1,"table":1,"lick":1,"custom":1,"based":1,"chose":1,"dialog":1,"choose":1,"create":1,"many-to-many":1,"people":1,"list":1}
,"display":{"related":1}
,"related":{"records":1,"each":1,"attachment":1,"record":1}
,"records":{"new":1,"add-on":1,"dd-on":1,"choose":1}
,"new":{"table":1,"dd-on":1,"add-on":1,"related":1}
,"add":{"table":1,"add-on":1,"people":1,"dd-on":1}
,"predefined":{"set":1}
,"set":{"fields":1}
,"fields":{"custom":1,"phone":1,"scripts":1}
,"phone":{"numbers":1,"number":1}
,"numbers":{"add-on":1}
,"adds":{"table":1,"portal":1,"scripts":1,"custom":1}
,"number":{"type":1,"field":1}
,"type":{"addition":1}
,"addition":{"relationship":1}
,"relationship":{"created":1,"current":1}
,"created":{"new":1}
,"current":{"table":1,"layout":1,"ayout":1}
,"track":{"multiple":1}
,"multiple":{"file":1}
,"file":{"attachments":1,"attachment":1}
,"attachments":{"related":1,"add-on":1}
,"each":{"record":1,"related":1}
,"record":{"custom":1,"button":1,"ap":1}
,"first":{"draw":1}
,"draw":{"portal":1}
,"portal":{"existing":1,"setup":1,"field":1,"allows":1,"choosing":1,"table":1,"tool":1,"drag":1,"new":1}
,"existing":{"layout":1}
,"layout":{"portal":1,"creates":1,"browse":1,"mode":1,"want":1,"based":1,"move":1,"resizing":1}
,"setup":{"dialog":1}
,"dialog":{"box":1}
,"box":{"choose":1,"show":1,"hoose":1}
,"choose":{"attachments":1,"new":1,"dd-on":1,"enter":1,"people":1}
,"illustration":{"choosing":1}
,"choosing":{"add-on":1,"show":1}
,"field":{"button":1,"enter":1,"note":1,"meets":1,"uto-enter":1,"auto-enter":1,"stored":1,"includes":1,"indexing":1}
,"button":{"objects":1,"button":1,"entering":1}
,"objects":{"layout":1,"moving":1,"add":1}
,"creates":{"new":1}
,"store":{"attachment":1}
,"attachment":{"relates":1,"field":1,"drawing":1}
,"relates":{"new":1}
,"scripts":{"layout":1,"custom":1}
,"browse":{"mode":1}
,"mode":{"portal":1,"switch":1}
,"allows":{"insert":1}
,"insert":{"file":1}
,"enter":{"description":1,"name":1}
,"description":{"each":1}
,"drawing":{"portal":1}
,"show":{"records":1}
,"switch":{"layout":1}
,"want":{"isplay":1,"portal":1}
,"isplay":{"records":1}
,"dd-on":{"table":1}
,"based":{"table":1,"rimary":1,"dd-on":1}
,"primary":{"key":1}
,"key":{"field":1}
,"note":{"portal":1,"choose":1}
,"tool":{"portal":1,"status":1}
,"status":{"toolbar":1}
,"toolbar":{"position":1}
,"position":{"crosshair":1}
,"crosshair":{"pointer":1}
,"pointer":{"layout":1,"diagonally":1}
,"drag":{"pointer":1}
,"diagonally":{"portal":1}
,"if":{"new":1}
,"rimary":{"key":1}
,"lick":{"choose":1}
,"name":{"new":1}
,"lready":{"table":1}
,"chose":{"table":1}
,"hoose":{"xisting":1}
,"xisting":{"table":1}
,"entering":{"new":1}
,"ap":{"pear":1}
,"pear":{"layout":1}
,"move":{"resize":1}
,"resize":{"objects":1}
,"moving":{"objects":1}
,"resizing":{"reshaping":1}
,"reshaping":{"objects":1}
,"ayout":{"based":1}
,"meets":{"criteria":1}
,"criteria":{"field":1}
,"uto-enter":{"erial":1}
,"erial":{"number":1}
,"auto-enter":{"alculation":1}
,"alculation":{"hat":1}
,"hat":{"includes":1}
,"includes":{"get":1}
,"get":{"uuid":1,"uuidnumber":1,"uuidnu":1}
,"uuid":{"get":1}
,"uuidnumber":{"function":1}
,"function":{"field":1}
,"stored":{"calculation":1}
,"calculation":{"field":1}
,"uuidnu":{"mber":1}
,"mber":{"functi":1}
,"functi":{"defining":1}
,"defining":{"automatic":1,"field":1}
,"automatic":{"data":1}
,"data":{"entry":1}
,"entry":{"defining":1}
,"indexing":{"options":1}
,"options":{"people":1}
,"people":{"add-on":1,"table":1,"choose":1,"list":1}
,"join":{"table":1}
,"many-to-many":{"relationship":1}
,"list":{"details":1,"add":1}
,"details":{"layouts":1}
,"layouts":{"buttons":1}
,"buttons":{"let":1}
,"let":{"add":1}
}
;Search.control.loadWordPairs(pairs);
