var pairs =
{
"drawing":{"inserting":1,"tools":1}
,"inserting":{"objects":1}
,"objects":{"layout":1,"tabbed":1,"simplify":1}
,"layout":{"enhance":1,"number":1,"objects":1}
,"enhance":{"design":1}
,"design":{"layout":1}
,"number":{"including":1}
,"including":{"adding":1}
,"adding":{"text":1,"graphic":1,"panel":1,"popovers":1}
,"text":{"fields":1}
,"fields":{"field":1}
,"field":{"labels":1}
,"labels":{"column":1}
,"column":{"headings":1}
,"headings":{"drawing":1}
,"tools":{"add":1}
,"add":{"lines":1}
,"lines":{"rectangles":1}
,"rectangles":{"shapes":1}
,"shapes":{"adding":1}
,"graphic":{"video":1}
,"video":{"adding":1}
,"panel":{"controls":1}
,"controls":{"group":1}
,"group":{"layout":1}
,"tabbed":{"sliding":1}
,"sliding":{"panels":1}
,"panels":{"adding":1}
,"popovers":{"group":1}
,"simplify":{"data":1}
,"data":{"viewing":1}
,"viewing":{"entering":1}
}
;Search.control.loadWordPairs(pairs);
