var pairs =
{
"flush":{"cache":1,"save":1,"nternal":1}
,"cache":{"disk":1,"computer\u0027s":1,"extensive":1}
,"disk":{"mmediately":1,"none":1,"storage":1,"perform":1,"automating":1}
,"mmediately":{"flushes":1}
,"flushes":{"nternal":1,"disk":1}
,"nternal":{"file":1}
,"file":{"cache":1}
,"computer\u0027s":{"hard":1}
,"hard":{"disk":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1,"clients":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"filemaker":1}
,"clients":{"utomatically":1,"flush":1}
,"utomatically":{"flush":1}
,"save":{"nternal":1}
,"storage":{"during":1}
,"during":{"idle":1}
,"idle":{"time":1}
,"time":{"use":1}
,"use":{"script":1}
,"script":{"step":1,"steps":1}
,"step":{"force":1}
,"force":{"filemaker":1}
,"extensive":{"made":1}
,"made":{"script":1}
,"steps":{"im":1}
,"im":{"port":1}
,"port":{"records":1}
,"records":{"replace":1,"found":1,"[restore":1}
,"replace":{"field":1}
,"field":{"contents":1}
,"contents":{"assigns":1,"[with":1}
,"assigns":{"serial":1}
,"serial":{"numbers":1,"numbers]":1}
,"numbers":{"all":1}
,"all":{"records":1}
,"found":{"set":1}
,"set":{"flushes":1}
,"perform":{"find":1}
,"find":{"[restore]":1}
,"[restore]":{"sort":1}
,"sort":{"records":1}
,"[restore":{"dialog":1}
,"dialog":{"on]":1,"products":1}
,"on]":{"go":1}
,"go":{"record\u002Frequest\u002Fpage":1}
,"record\u002Frequest\u002Fpage":{"[first]":1}
,"[first]":{"replace":1}
,"[with":{"dialog":1}
,"products":{":serial":1}
,":serial":{"number":1}
,"number":{"serial":1}
,"numbers]":{"flush":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
