var pairs =
{
"ne-to-many":{"relationships":1}
,"relationships":{"one-to-many":1,"graph":1,"many-to-one":1}
,"one-to-many":{"relationship":1}
,"relationship":{"record":1,"relationships":1,"line":1,"returns":1}
,"record":{"table":1}
,"table":{"associated":1,"each":1,"table":1,"one-to-many":1,"customer":1,"value":1,"records":1}
,"associated":{"records":1}
,"records":{"table":1,"value":1,"customers":1}
,"each":{"customer":1}
,"customer":{"sales":1,"id":1}
,"sales":{"one-to-many":1}
,"graph":{"customers":1}
,"customers":{"table":1,"tables":1}
,"line":{"primary":1}
,"primary":{"key":1}
,"key":{"field":1}
,"field":{"customers":1,"table":1}
,"id":{"designed":1,"field":1}
,"designed":{"contain":1,"allow":1}
,"contain":{"unique":1}
,"unique":{"values":1}
,"values":{"foreign":1}
,"foreign":{"key":1}
,"allow":{"multiple":1}
,"multiple":{"instances":1}
,"instances":{"value":1}
,"value":{"relationship":1,"customer":1}
,"returns":{"related":1}
,"related":{"records":1}
,"tables":{"result":1}
,"result":{"one-to-many":1}
,"many-to-one":{"relationships":1}
}
;Search.control.loadWordPairs(pairs);
