var pairs =
{
"avplayer":{"set":1}
,"set":{"playback":1,"stop":1,"play":1}
,"playback":{"state":1}
,"state":{"auses":1,"[playing]":1,"[stopped]":1}
,"auses":{"resumes":1}
,"resumes":{"stops":1,"playing":1}
,"stops":{"playing":1,"media":1}
,"playing":{"media":1,"paused":1,"resumes":1,"if":1}
,"media":{"file":1}
,"file":{"playing":1,"paused":1,"player":1,"if":1}
,"paused":{"paused":1,"pauses":1,"stopped":1,"resumes":1,"avplayer":1}
,"pauses":{"playing":1}
,"stopped":{"stops":1}
,"player":{"set":1}
,"stop":{"set":1,"playing":1}
,"play":{"script":1}
,"script":{"step":1}
,"step":{"filemaker":1,"pause":1}
,"filemaker":{"pro":1}
,"pro":{"14.0":1}
,"14.0":{"use":1}
,"use":{"script":1}
,"pause":{"resume":1}
,"resume":{"stop":1}
,"[playing]":{"stops":1}
,"if":{"playing":1,"[getavplayerattribute":1,"container":1}
,"[getavplayerattribute":{"playbackstate":1}
,"playbackstate":{"=1":1}
,"=1":{"avplayer":1}
,"[stopped]":{"end":1}
,"end":{"if":1}
,"container":{"fields":1}
,"fields":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
