var pairs =
{
"creating":{"quick":1,"dynamic":1}
,"quick":{"charts":1,"chart":1,"charting":1}
,"charts":{"create":1,"column":1,"single":1,"form":1,"including":1,"pie":1,"scatter":1,"note":1}
,"create":{"print":1,"quick":1}
,"print":{"quick":1,"chart":1}
,"chart":{"browse":1,"based":1,"if":1,"layout":1,"adding":1,"data":1,"by":1,"field":1,"setup":1,"settings":1,"type":1,"change":1,"inspector":1,"preview":1,"add":1,"title":1,"quick":1,"modify":1,"axes":1,"lick":1,"pecify":1,"records":1,"summary":1,"print":1,"copy":1,"clipboard":1,"choose":1,"new":1,"via":1,"filemaker":1,"save":1,"printing":1}
,"browse":{"mode":1}
,"mode":{"start":1,"filemaker":1,"view":1,"right-click":1,"managing":1}
,"start":{"browse":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"sets":1,"chooses":1,"current":1,"adds":1}
,"sets":{"up":1,"extended":1}
,"up":{"chart":1}
,"based":{"field":1,"active":1,"sort":1}
,"field":{"type":1,"field":1,"right-click":1,"group":1,"name":1,"plot":1,"chart":1,"created":1}
,"type":{"contents":1,"based":1,"choose":1,"change":1,"data":1,"satisfied":1}
,"contents":{"active":1,"selected":1}
,"active":{"field":1}
,"selected":{"fields":1,"use":1}
,"fields":{"sort":1}
,"sort":{"order":1,"data":1,"field":1}
,"order":{"note":1,"chart":1}
,"note":{"active":1,"by":1,"scatter":1,"if":1}
,"right-click":{"create":1,"control-click":1,"column":1,"chart":1,"layout":1}
,"if":{"correct":1,"data":1,"applicable":1,"chart":1,"leave":1,"summary":1,"print":1,"choose":1}
,"correct":{"privileges":1}
,"privileges":{"save":1}
,"save":{"chart":1,"layout":1,"quick":1}
,"layout":{"database":1,"bar":1,"file":1,"mode":1,"choose":1,"save":1,"correct":1,"accounts":1,"pop-up":1,"menus":1,"manage":1,"if":1,"summary":1}
,"database":{"quick":1,"if":1}
,"column":{"bar":1,"choose":1,"values":1,"chart":1,"groups":1}
,"bar":{"pie":1,"switch":1,"line":1,"positive\u002Fnegative":1}
,"pie":{"line":1,"charts":1}
,"line":{"charts":1}
,"single":{"data":1}
,"data":{"series":1,"right-click":1,"chart":1,"points":1,"table":1,"current":1,"set":1,"charting":1,"source":1,"choose":1,"related":1,"labels":1,"formatting":1,"summary":1}
,"series":{"axis":1,"column":1}
,"axis":{"data":1,"browse":1}
,"view":{"table":1,"button":1,"create":1,"list":1,"it\u2019s":1,"use":1,"sort":1,"creating":1,"filemaker":1}
,"table":{"view":1,"save":1}
,"button":{"layout":1,"title":1}
,"switch":{"table":1,"layout":1}
,"form":{"view":1}
,"list":{"view":1}
,"it\u2019s":{"easier":1}
,"easier":{"table":1}
,"use":{"table":1,"chart":1,"layouts":1}
,"control-click":{"column":1}
,"choose":{"sorting":1,"choose":1,"chart":1,"use":1,"current":1,"copy":1,"paste":1,"save":1}
,"sorting":{"option":1}
,"option":{"shortcut":1}
,"shortcut":{"menu":1}
,"menu":{"quick":1,"chart":1,"include":1,"go":1}
,"charting":{"first":1,"choose":1,"data":1}
,"first":{"sort":1}
,"group":{"summarize":1}
,"summarize":{"data":1}
,"adding":{"groups":1}
,"groups":{"summaries":1,"based":1}
,"summaries":{"if":1}
,"points":{"intend":1,"current":1}
,"intend":{"chart":1}
,"dynamic":{"reports":1}
,"reports":{"table":1}
,"chooses":{"summary":1}
,"summary":{"type":1,"data":1,"menu":1,"field":1,"ield":1}
,"values":{"charting":1}
,"by":{"field":1,"sort":1,"default":1}
,"name":{"plot":1,"by":1}
,"plot":{"individual":1,"data":1}
,"individual":{"data":1}
,"current":{"column":1,"state":1,"record":1,"table":1}
,"setup":{"dialog":1}
,"dialog":{"box":1}
,"box":{"appears":1,"adjustments":1,"chart":1,"change":1,"display":1,"create":1}
,"appears":{"chart":1}
,"state":{"file":1}
,"file":{"context":1,"right-click":1,"file":1,"layout":1}
,"context":{"selection":1}
,"selection":{"estimate":1}
,"estimate":{"chart":1}
,"settings":{"depending":1,"chart":1}
,"depending":{"complexity":1}
,"complexity":{"data":1}
,"set":{"chart":1,"charted":1,"tick":1,"delimited":1}
,"adjustments":{"quick":1}
,"change":{"settings":1,"source":1,"chart":1,"data":1}
,"inspector":{"right":1,"chart":1,"changing":1,"pecifying":1,"select":1}
,"right":{"modify":1}
,"modify":{"chart":1}
,"preview":{"helps":1,"note":1}
,"helps":{"efficiently":1}
,"efficiently":{"chart":1}
,"default":{"records":1}
,"records":{"found":1,"pecifying":1,"related":1,"lick":1}
,"found":{"set":1}
,"charted":{"change":1}
,"source":{"data":1,"chart":1}
,"record":{"delimited":1}
,"delimited":{"data":1,"records":1}
,"related":{"records":1}
,"pecifying":{"data":1}
,"add":{"title":1}
,"title":{"chart":1,"type":1,"button":1,"choose":1}
,"including":{"stacked":1}
,"stacked":{"column":1}
,"positive\u002Fnegative":{"charts":1}
,"scatter":{"bubble":1}
,"bubble":{"charts":1,"chart":1}
,"labels":{"show":1}
,"show":{"hide":1}
,"hide":{"tick":1}
,"tick":{"marks":1,"mark":1}
,"marks":{"set":1}
,"mark":{"scale":1}
,"scale":{"if":1}
,"applicable":{"format":1}
,"format":{"data":1}
,"formatting":{"scaling":1}
,"scaling":{"chart":1}
,"axes":{"hange":1}
,"hange":{"color":1}
,"color":{"scheme":1}
,"scheme":{"legend":1}
,"legend":{"fonts":1}
,"fonts":{"chart":1}
,"lick":{"styles":1,"data":1}
,"styles":{"chart":1}
,"changing":{"chart":1}
,"pecify":{"type":1}
,"select":{"summary":1,"print":1}
,"satisfied":{"chart\u2019s":1}
,"chart\u2019s":{"appearance":1}
,"appearance":{"select":1}
,"copy":{"chart":1,"switch":1}
,"clipboard":{"paste":1}
,"paste":{"layout":1,"save":1}
,"new":{"layout":1}
,"accounts":{"privilege":1}
,"privilege":{"sets":1,"access":1}
,"extended":{"privilege":1}
,"access":{"chart":1}
,"via":{"layout":1}
,"pop-up":{"menu":1}
,"include":{"layout":1}
,"menus":{"if":1,"selected":1}
,"leave":{"include":1}
,"layouts":{"menu":1,"dialog":1,"note":1}
,"go":{"layout":1}
,"manage":{"layouts":1}
,"display":{"chart":1}
,"managing":{"layouts":1}
,"adds":{"summary":1}
,"ield":{"current":1}
,"created":{"database":1}
,"printing":{"cancel":1}
,"cancel":{"close":1}
,"close":{"chart":1}
}
;Search.control.loadWordPairs(pairs);
