var pairs =
{
"get":{"currenttimestam":1,"currenttimestamp":1,"host":1,"currenthosttimestamp":1,"current":1,"time":1,"system":1}
,"currenttimestam":{"returns":1}
,"returns":{"current":1,"timestamp":1,"time":1,"1\u002F1\u002F2019":1}
,"current":{"date":1,"timestamp":1,"time":1}
,"date":{"time":1,"client":1}
,"time":{"nearest":1,"format":1,"date":1,"use":1,"stamp":1,"get":1,"current":1}
,"nearest":{"second":1}
,"second":{"system":1}
,"system":{"clock":1,"settings":1,"time":1}
,"clock":{"get":1,"january":1}
,"currenttimestamp":{"none":1,"get":1}
,"none":{"timestamp":1}
,"timestamp":{"filemaker":1,"text":1,"get":1}
,"filemaker":{"pro":1}
,"pro":{"7.0":1}
,"7.0":{"data":1}
,"data":{"type":1}
,"type":{"calculation":1}
,"calculation":{"result":1}
,"result":{"determines":1,"function":1,"text":1}
,"determines":{"returned":1}
,"returned":{"value":1}
,"value":{"function":1}
,"function":{"represented":1,"returns":1}
,"represented":{"if":1}
,"if":{"calculation":1,"number":1}
,"text":{"th":1,"system":1}
,"th":{"current":1,"total":1}
,"format":{"determined":1}
,"determined":{"by":1}
,"by":{"operating":1}
,"operating":{"system":1}
,"settings":{"file":1}
,"file":{"created":1}
,"created":{"note":1}
,"note":{"if":1}
,"number":{"seconds":1,"th":1}
,"seconds":{"zero":1,"included":1,"elapsed":1}
,"zero":{"seconds":1}
,"included":{"1\u002F1\u002F2019":1}
,"1\u002F1\u002F2019":{"11:30":1,"11:30:01":1}
,"11:30":{"number":1}
,"total":{"number":1}
,"elapsed":{"midnight":1}
,"midnight":{"january":1}
,"january":{"0001":1,"2019":1}
,"0001":{"client-server":1}
,"client-server":{"peer-to-peer":1}
,"peer-to-peer":{"environments":1}
,"environments":{"function":1}
,"client":{"machine":1}
,"machine":{"get":1}
,"host":{"machine\u2019s":1}
,"machine\u2019s":{"date":1}
,"use":{"get":1}
,"currenthosttimestamp":{"function":1}
,"11:30:01":{"calculation":1,"get":1}
,"2019":{"11:30:01":1}
,"stamp":{"get":1}
}
;Search.control.loadWordPairs(pairs);
