var pairs =
{
"sa":{"ng":1}
,"ng":{"layout":1}
,"layout":{"theme":1,"save":1,"import":1,"mode":1,"opying":1,"set":1}
,"theme":{"if":1,"saving":1,"level":1,"all":1,"name":1,"definition":1,"unsaved":1,"button":1,"applied":1,"xample":1,"remains":1,"attributes":1,"time":1,"layout":1,"leave":1,"started":1,"type":1,"updates":1}
,"if":{"changed":1}
,"changed":{"style":1,"theme":1}
,"style":{"attributes":1,"made":1}
,"attributes":{"layout":1,"ayout":1,"original":1}
,"save":{"theme":1,"diting":1,"style":1,"default":1,"made":1,"new":1}
,"saving":{"theme":1}
,"level":{"allows":1,"save":1,"revert":1}
,"allows":{"apply":1}
,"apply":{"theme":1}
,"all":{"styles":1,"layouts":1}
,"styles":{"layout":1,"file":1,"edit":1,"save":1,"theme":1}
,"import":{"theme":1}
,"file":{"layout":1,"use":1,"recovery":1}
,"mode":{"create":1}
,"create":{"new":1}
,"new":{"styles":1,"theme":1,"name":1}
,"edit":{"existing":1}
,"existing":{"styles":1}
,"diting":{"creating":1}
,"creating":{"styles":1}
,"opying":{"formatting":1}
,"formatting":{"attributes":1,"predefined":1}
,"ayout":{"inspector":1}
,"inspector":{"appearance":1}
,"appearance":{"appearance":1,"tab":1}
,"tab":{"asterisk":1}
,"asterisk":{"*)":1}
,"*)":{"appears":1}
,"appears":{"theme":1}
,"name":{"arrow":1,"theme":1,"rename":1,"remove":1}
,"arrow":{"red":1}
,"red":{"indicating":1}
,"indicating":{"theme":1}
,"definition":{"changed":1}
,"unsaved":{"theme":1}
,"button":{"choose":1}
,"choose":{"save":1}
,"made":{"theme":1,"new":1}
,"applied":{"all":1}
,"layouts":{"file":1}
,"use":{"theme":1}
,"xample":{"value":1}
,"value":{"list":1}
,"list":{"includes":1}
,"includes":{"related":1}
,"related":{"field":1}
,"field":{"values":1}
,"values":{"note":1}
,"note":{"default":1}
,"default":{"themes":1,"theme":1,"settings":1}
,"themes":{"filemaker":1,"dialog":1,"file":1,"changing":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"brackets":1,"theme":1,"software":1,"file":1}
,"brackets":{"[\u00A0":1,"removed":1}
,"[\u00A0":{"manage":1}
,"manage":{"themes":1}
,"dialog":{"box":1}
,"box":{"save":1,"indicating":1}
,"remains":{"brackets":1}
,"removed":{"manage":1}
,"original":{"default":1}
,"settings":{"reapply":1}
,"reapply":{"filemaker":1}
,"time":{"changing":1,"saved":1}
,"changing":{"theme":1}
,"leave":{"theme":1}
,"started":{"unchanged":1}
,"unchanged":{"save":1}
,"type":{"new":1}
,"rename":{"theme":1}
,"remove":{"last":1}
,"last":{"time":1}
,"saved":{"styles":1}
,"revert":{"theme":1}
,"updates":{"filemaker":1}
,"software":{"include":1}
,"include":{"formatting":1}
,"predefined":{"themes":1}
,"recovery":{"options":1}
,"options":{"update":1,"save":1}
,"update":{"custom":1}
,"custom":{"themes":1}
,"set":{"tin":1}
,"tin":{"advanced":1}
}
;Search.control.loadWordPairs(pairs);
