var pairs =
{
"get":{"windowmo":1,"windowmode":1,"window":1}
,"windowmo":{"de":1}
,"de":{"returns":1}
,"returns":{"number":1,"browse":1,"if":1}
,"number":{"representing":1,"filemaker":1}
,"representing":{"mode":1}
,"mode":{"filemaker":1,"find":1,"preview":1,"if":1,"returns":1,"value":1,"function":1}
,"filemaker":{"product":1,"pro":1}
,"product":{"function":1}
,"function":{"evaluated":1,"data":1,"runs":1}
,"evaluated":{"get":1}
,"windowmode":{"none":1,"get":1}
,"none":{"number":1}
,"pro":{"6.0":1,"advanced":1}
,"6.0":{"earlier":1}
,"earlier":{"returns":1}
,"browse":{"mode":1}
,"find":{"mode":1}
,"preview":{"mode":1}
,"if":{"printing":1,"evaluating":1,"script":1,"multiple":1,"file":1}
,"printing":{"progress":1}
,"progress":{"if":1}
,"evaluating":{"function":1}
,"data":{"viewer":1}
,"viewer":{"current":1}
,"current":{"window":1,"database":1}
,"window":{"layout":1,"own":1,"mode":1,"returns":1}
,"layout":{"mode":1}
,"script":{"function":1}
,"runs":{"while":1}
,"while":{"file":1}
,"file":{"layout":1,"each":1,"preview":1}
,"advanced":{"switches":1}
,"switches":{"browse":1}
,"multiple":{"windows":1}
,"windows":{"open":1}
,"open":{"current":1}
,"database":{"file":1}
,"each":{"window":1}
,"own":{"window":1}
,"value":{"returned":1}
,"returned":{"foreground":1}
,"foreground":{"window":1}
}
;Search.control.loadWordPairs(pairs);
