var pairs =
{
"diting":{"value":1}
,"value":{"list":1,"lists":1}
,"list":{"privileges":1,"set":1,"names":1,"select":1,"created":1,"editing":1,"deleting":1,"privilege":1,"prohibits":1,"manage":1,"user":1,"value":1,"items":1,"modifiable":1,"enforce":1}
,"privileges":{"privilege":1,"all":1,"individual":1,"custom":1,"dialog":1,"new":1,"want":1,"ormat":1}
,"privilege":{"sets":1,"set":1,"choose":1,"view":1,"limited":1,"supported":1}
,"sets":{"limit":1,"data":1}
,"limit":{"access":1}
,"access":{"value":1,"design":1,"options":1,"prohibits":1,"list":1,"allow":1,"privilege":1}
,"lists":{"file":1,"permit":1,"viewing":1,"each":1,"choose":1,"duplicating":1,"creating":1,"all":1,"prohibits":1,"dialog":1,"start":1,"custom":1,"setting":1,"if":1,"odbc":1,"edit":1}
,"file":{"file":1,"set":1}
,"set":{"privileges":1,"modifiable":1,"edit":1,"dialog":1,"view-only":1,"control":1}
,"all":{"value":1,"modifiable":1,"view":1,"access":1}
,"permit":{"viewing":1,"adding":1}
,"viewing":{"editing":1,"custom":1,"modifying":1,"existing":1,"value":1}
,"editing":{"deleting":1,"new":1,"privilege":1,"value":1,"existing":1}
,"deleting":{"value":1}
,"custom":{"privileges":1,"value":1,"privilege":1}
,"individual":{"value":1}
,"each":{"value":1}
,"modifiable":{"view":1,"all":1,"allows":1,"allow":1,"users":1}
,"view":{"accessible":1,"all":1,"allows":1,"prohibit":1,"choosing":1,"prohibits":1}
,"accessible":{"start":1}
,"start":{"editing":1}
,"new":{"existing":1,"value":1}
,"existing":{"privilege":1,"value":1}
,"edit":{"privilege":1,"value":1,"rivileges":1,"privileges":1}
,"dialog":{"box":1,"boxes":1}
,"box":{"ee":1,"order":1,"dialog":1,"creating":1,"select":1,"allow":1,"privilege":1}
,"ee":{"creating":1}
,"creating":{"editing":1,"new":1}
,"data":{"access":1,"value":1}
,"design":{"value":1}
,"choose":{"all":1,"custom":1,"modifiable":1,"view":1,"access":1}
,"options":{"allow":1,"permit":1}
,"allow":{"prohibit":1,"viewing":1,"creating":1,"creation":1}
,"prohibit":{"all":1,"items":1,"user":1}
,"allows":{"viewing":1}
,"modifying":{"value":1}
,"duplicating":{"deleting":1,"viewable":1}
,"prohibits":{"manage":1,"items":1,"accessing":1,"editing":1}
,"manage":{"value":1}
,"order":{"create":1}
,"create":{"edit":1}
,"items":{"all":1,"value":1,"prohibits":1,"editing":1,"setting":1}
,"accessing":{"value":1}
,"names":{"sort":1,"prohibits":1}
,"sort":{"dialog":1}
,"boxes":{"display":1}
,"display":{"value":1,"pop-up":1}
,"select":{"each":1,"new":1,"allow":1}
,"created":{"set":1}
,"want":{"you\u2019re":1}
,"you\u2019re":{"setting":1}
,"setting":{"privileges":1,"value":1,"up":1}
,"user":{"access":1,"odbc":1}
,"viewable":{"value":1}
,"creation":{"new":1}
,"choosing":{"all":1}
,"if":{"value":1}
,"view-only":{"ake":1}
,"ake":{"value":1}
,"users":{"privileges":1}
,"ormat":{"field":1}
,"field":{"object":1,"display":1}
,"object":{"options":1}
,"adding":{"new":1}
,"up":{"field":1}
,"pop-up":{"menu":1}
,"menu":{"checkbox":1}
,"checkbox":{"set":1}
,"control":{"value":1}
,"odbc":{"data":1}
,"limited":{"custom":1}
,"supported":{"prohibit":1}
,"enforce":{"row-level":1}
,"row-level":{"security":1}
,"security":{"external":1}
,"external":{"sql":1}
,"sql":{"database":1}
,"database":{"edit":1}
,"rivileges":{"all":1}
}
;Search.control.loadWordPairs(pairs);
