var pairs =
{
"get":{"lastmessag":1,"lastmessagechoice":1,"last":1,"message":1,"dialog":1}
,"lastmessag":{"echoice":1}
,"echoice":{"returns":1}
,"returns":{"number":1,"first":1}
,"number":{"button":1,"filemaker":1}
,"button":{"clicked":1,"by":1,"script":1}
,"clicked":{"alert":1}
,"alert":{"message":1}
,"message":{"displayed":1,"choice":1}
,"displayed":{"by":1}
,"by":{"show":1,"default":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"dialog":{"script":1,"choice":1}
,"script":{"step":1,"ow":1}
,"step":{"get":1}
,"lastmessagechoice":{"none":1,"get":1}
,"none":{"number":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"returns":1}
,"first":{"button":1}
,"default":{"labeled":1}
,"labeled":{"second":1,"cancel":1}
,"second":{"button":1}
,"cancel":{"button":1}
,"ow":{"custom":1}
,"last":{"message":1}
,"choice":{"get":1}
}
;Search.control.loadWordPairs(pairs);
