var pairs =
{
"custom":{"fu":1,"function":1,"functions":1}
,"fu":{"nction":1}
,"nction":{"dependency":1}
,"dependency":{"rule":1,"rules":1,"function_b":1}
,"rule":{"note":1}
,"note":{"feature":1}
,"feature":{"use":1}
,"use":{"advanced":1}
,"advanced":{"tools":1,"attempts":1,"updates":1,"enames":1}
,"tools":{"general":1,"hen":1}
,"general":{"preference":1}
,"preference":{"selected":1}
,"selected":{"ad":1}
,"ad":{"vanced":1}
,"vanced":{"tools":1}
,"hen":{"copy":1}
,"copy":{"import":1}
,"import":{"custom":1}
,"function":{"file":1,"contain":1,"invalid":1,"maintain":1}
,"file":{"filemaker":1,"function_b":1,"unexpected":1,"function_a":1,"if":1,"existing":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"attempts":{"resolve":1}
,"resolve":{"dependencies":1}
,"dependencies":{"function":1}
,"contain":{"dependency":1}
,"rules":{"apply":1}
,"apply":{"under":1}
,"under":{"conditions":1}
,"conditions":{"if":1}
,"if":{"function_a":1}
,"function_a":{"dependency":1,"copied":1,"calls":1,"appears":1,"function_b":1,"operate":1,"call":1,"operates":1,"original":1,"filemaker":1}
,"function_b":{"function_a":1,"located":1,"copied":1,"functions":1,"renamed":1,"filemaker":1}
,"copied":{"imported":1,"function_b":1,"functions":1,"function":1}
,"imported":{"target":1}
,"target":{"file":1}
,"calls":{"function_b":1,"itself":1}
,"located":{"target":1}
,"unexpected":{"if":1}
,"appears":{"enclosed":1}
,"enclosed":{"comment":1}
,"comment":{"characters":1}
,"characters":{"(\u002F*<":1}
,"(\u002F*<":{"function_definition":1}
,"function_definition":{"*\u002F)":1}
,"*\u002F)":{"manage":1}
,"manage":{"custom":1}
,"functions":{"dialog":1,"copied":1,"renamed":1}
,"dialog":{"box":1}
,"box":{"indicating":1}
,"indicating":{"new":1}
,"new":{"function":1}
,"invalid":{"target":1}
,"operate":{"expected":1}
,"expected":{"if":1}
,"existing":{"function_b":1,"function_a":1}
,"renamed":{"function_b":1,"function_a":1}
,"updates":{"function_a":1}
,"call":{"function_b":1}
,"operates":{"expected":1,"function_a":1}
,"original":{"file":1}
,"itself":{"recursively":1}
,"recursively":{"copied":1}
,"enames":{"copied":1}
,"maintain":{"integrity":1}
,"integrity":{"dependency":1}
}
;Search.control.loadWordPairs(pairs);
