var pairs =
{
"defining":{"repeating":1}
,"repeating":{"fields":1,"field":1,"enter":1}
,"fields":{"store":1,"tab":1,"find":1,"help":1}
,"store":{"value":1}
,"value":{"text":1,"repeating":1}
,"text":{"number":1,"field":1}
,"number":{"date":1,"maximum":1,"repetitions":1}
,"date":{"time":1}
,"time":{"container":1}
,"container":{"calculation":1}
,"calculation":{"global":1,"field":1,"dialog":1,"summary":1,"aggregate":1}
,"global":{"field":1}
,"field":{"by":1,"repeating":1,"create":1,"named":1,"enter":1,"note":1,"easier":1,"want":1,"options":1,"name":1,"dialog":1,"calculation":1,"separate":1,"repeat":1,"characteristics":1,"feature":1,"easily":1}
,"by":{"field":1}
,"create":{"text":1,"summary":1,"find":1,"report":1}
,"named":{"color":1}
,"color":{"stores":1,"repeating":1,"field":1}
,"stores":{"colors":1}
,"colors":{"each":1}
,"each":{"product":1,"repetition":1}
,"product":{"sell":1,"color":1}
,"sell":{"if":1}
,"if":{"color":1,"database":1,"field":1,"define":1}
,"enter":{"all":1,"number":1,"umber":1}
,"all":{"colors":1,"repetitions":1,"values":1}
,"note":{"repeating":1}
,"easier":{"use":1}
,"use":{"related":1,"data":1,"first":1}
,"related":{"table":1}
,"table":{"portal":1,"select":1,"table":1,"list":1}
,"portal":{"sort":1}
,"sort":{"insert":1}
,"insert":{"data":1}
,"data":{"create":1,"data":1,"tab":1,"record-by-record":1}
,"summary":{"report":1,"fields":1}
,"report":{"choose":1,"define":1}
,"choose":{"file":1}
,"file":{"menu":1}
,"menu":{"manage":1}
,"manage":{"database":1}
,"database":{"fields":1,"table":1}
,"tab":{"if":1,"repeating":1,"inspector":1}
,"select":{"table":1,"field":1}
,"list":{"select":1}
,"want":{"repeat":1}
,"repeat":{"define":1,"all":1}
,"define":{"new":1,"field":1,"calculation":1,"repeating":1}
,"new":{"field":1}
,"options":{"double-click":1,"field":1}
,"double-click":{"field":1}
,"name":{"options":1}
,"dialog":{"box":1}
,"box":{"storage":1,"options":1,"number":1}
,"storage":{"tab":1}
,"maximum":{"number":1}
,"repetitions":{"if":1,"enter":1,"displayed":1,"size":1,"visible":1}
,"umber":{"cl":1}
,"cl":{"ick":1}
,"ick":{"use":1}
,"inspector":{"change":1}
,"change":{"number":1}
,"displayed":{"layout":1}
,"layout":{"repeating":1,"eatures":1}
,"separate":{"display":1}
,"display":{"each":1}
,"repetition":{"if":1}
,"size":{"field":1}
,"characteristics":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"features":1,"searches":1}
,"features":{"calculation":1}
,"find":{"requests":1,"request":1}
,"requests":{"include":1}
,"include":{"all":1}
,"values":{"repeating":1,"all":1}
,"request":{"filemaker":1}
,"searches":{"values":1}
,"visible":{"current":1}
,"current":{"layout":1}
,"eatures":{"sorting":1}
,"sorting":{"use":1}
,"first":{"value":1}
,"feature":{"repeating":1,"values":1}
,"help":{"topic":1}
,"topic":{"feature":1}
,"easily":{"summarized":1}
,"summarized":{"create":1}
,"aggregate":{"function":1}
,"function":{"summarizing":1}
,"summarizing":{"data":1}
,"record-by-record":{"basis":1}
,"basis":{"define":1}
}
;Search.control.loadWordPairs(pairs);
