var pairs =
{
"documenting":{"database":1}
,"database":{"schemas":1,"design":1,"save":1,"use":1,"if":1,"files":1,"schema":1,"document":1,"file":1}
,"schemas":{"note":1}
,"note":{"feature":1}
,"feature":{"use":1,"document":1}
,"use":{"advanced":1,"standard":1,"production":1,"report":1,"database":1}
,"advanced":{"tools":1,"two":1,"file":1,"versions":1,"atabase":1,"choose":1}
,"tools":{"general":1,"filemaker":1,"compare":1,"menu":1,"use":1}
,"general":{"preference":1}
,"preference":{"selected":1}
,"selected":{"ad":1}
,"ad":{"vanced":1}
,"vanced":{"tools":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"two":{"document":1}
,"document":{"details":1,"chema":1,"troubleshoot":1}
,"details":{"custom":1,"file":1,"lements":1}
,"custom":{"app":1}
,"app":{"by":1}
,"by":{"saving":1,"clearing":1}
,"saving":{"copy":1}
,"copy":{"file":1,"filemaker":1,"xml":1}
,"file":{"xml":1,"record":1,"text":1,"save":1,"choose":1,"se":1,"database":1,"report":1,"ready":1,"want":1,"open":1,"if":1}
,"xml":{"format":1,"file":1,"full":1,"change":1,"analyze":1,"output":1,"report":1,"version":1,"save":1,"creating":1}
,"format":{"database":1,"represents":1,"details":1,"preview":1,"includes":1,"elements":1,"require":1,"default":1,"create":1}
,"design":{"report":1}
,"report":{"save":1,"feature":1,"produce":1,"re-create":1,"html":1,"overview":1,"xml":1,"full":1,"file":1,"files":1,"by":1,"select":1,"clear":1,"if":1,"format":1,"subset":1,"create":1,"notes":1}
,"save":{"copy":1,"xml":1,"folder":1,"html":1,"save":1,"database":1}
,"represents":{"schema":1}
,"schema":{"layouts":1,"choose":1}
,"layouts":{"scripts":1}
,"scripts":{"parts":1,"tables":1}
,"parts":{"file":1}
,"record":{"data":1}
,"data":{"account":1}
,"account":{"encrypted":1}
,"encrypted":{"xml":1}
,"text":{"store":1}
,"store":{"version":1}
,"version":{"control":1,"saving":1}
,"control":{"systems":1}
,"systems":{"git":1,"open":1}
,"git":{"use":1}
,"standard":{"text-based":1}
,"text-based":{"tools":1}
,"compare":{"versions":1}
,"versions":{"xml":1,"intended":1}
,"preview":{"gather":1}
,"gather":{"customer":1,"statistics":1}
,"customer":{"feedback":1}
,"feedback":{"change":1}
,"change":{"significantly":1,"default":1}
,"significantly":{"future":1}
,"future":{"filemaker":1}
,"intended":{"use":1}
,"production":{"systems":1}
,"open":{"file":1,"gather":1,"all":1,"filemaker":1}
,"full":{"access":1}
,"access":{"privileges":1}
,"privileges":{"file":1}
,"choose":{"tools":1,"folder":1,"elements":1}
,"menu":{"save":1,"database":1}
,"default":{"filename":1,"html":1}
,"filename":{"choose":1,"addition":1}
,"folder":{"if":1,"xml":1}
,"if":{"save":1,"lose":1,"files":1,"prefer":1}
,"se":{"database":1}
,"chema":{"database":1}
,"html":{"xml":1,"format":1,"select":1,"report":1}
,"produce":{"reports":1,"database":1}
,"reports":{"databases":1}
,"databases":{"currently":1,"filemaker":1}
,"currently":{"open":1}
,"statistics":{"structure":1}
,"structure":{"database":1,"databases":1}
,"re-create":{"structure":1}
,"lose":{"original":1}
,"original":{"database":1}
,"files":{"examine":1,"want":1,"list":1,"contain":1}
,"examine":{"textual":1}
,"textual":{"representation":1}
,"representation":{"database":1}
,"elements":{"fields":1,"each":1,"want":1}
,"fields":{"relationships":1}
,"relationships":{"scripts":1,"calculations":1}
,"tables":{"database":1,"want":1}
,"troubleshoot":{"missing":1}
,"missing":{"references":1}
,"references":{"broken":1}
,"broken":{"relationships":1}
,"calculations":{"database":1}
,"includes":{"report":1}
,"overview":{"snapshot":1,"hyperlinks":1}
,"snapshot":{"elements":1}
,"each":{"database":1}
,"hyperlinks":{"details":1}
,"lements":{"each":1}
,"ready":{"transformed":1}
,"transformed":{"format":1}
,"require":{"create":1}
,"create":{"tools":1,"save":1,"database":1}
,"analyze":{"process":1}
,"process":{"structure":1}
,"atabase":{"design":1}
,"output":{"grammar":1}
,"grammar":{"open":1}
,"all":{"database":1}
,"want":{"produce":1,"exclude":1}
,"list":{"clear":1,"include":1}
,"clear":{"files":1,"elements":1}
,"exclude":{"report":1}
,"clearing":{"checkbox":1}
,"checkbox":{"associated":1,"files":1}
,"associated":{"file":1}
,"contain":{"tables":1}
,"select":{"filename":1,"xml":1}
,"addition":{"checkbox":1}
,"include":{"report":1}
,"prefer":{"publish":1}
,"publish":{"report":1}
,"subset":{"xml":1}
,"creating":{"database":1}
}
;Search.control.loadWordPairs(pairs);
