var pairs =
{
"print":{"rints":1,"dialog":1,"options":1,"job":1,"correctly":1,"setup":1,"step":1,"pdf":1,"script":1,"invoices":1,"[restore":1}
,"rints":{"current":1}
,"current":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1,"server":1,"go":1}
,"pro":{"advanced":1,"6.0":1}
,"advanced":{"file":1}
,"file":{"dialog":1}
,"dialog":{"specifies":1,"box":1,"filemaker":1,"option":1,"doesn\u2019t":1,"print":1,"off]":1}
,"specifies":{"display":1}
,"display":{"print":1,"correctly":1,"content":1,"filemaker":1}
,"box":{"script":1,"choose":1}
,"script":{"step":1,"runs":1,"if":1,"saved":1}
,"step":{"performed":1,"script":1,"printer":1,"user\u2019s":1,"allow":1,"executes":1,"print":1,"filemaker":1,"creates":1,"settings":1,"option":1}
,"performed":{"print":1}
,"options":{"allows":1,"stored":1,"script":1,"print":1}
,"allows":{"output":1}
,"output":{"destination":1,"script":1,"format":1}
,"destination":{"restore":1,"if":1,"saving":1}
,"restore":{"print":1}
,"stored":{"script":1}
,"runs":{"output":1}
,"printer":{"fax":1,"found":1,"filemaker":1,"name":1,"dialog":1}
,"fax":{"macos":1,"pdf":1}
,"macos":{"alternative":1}
,"alternative":{"printer":1}
,"pdf":{"print":1,"option":1,"output":1,"new":1,"use":1,"sure":1}
,"choose":{"pdf":1,"edit":1,"resolution":1}
,"option":{"list":1,"setting":1,"displays":1}
,"list":{"choose":1}
,"edit":{"menu":1}
,"menu":{"define":1}
,"define":{"custom":1}
,"custom":{"pdf":1}
,"format":{"destination":1}
,"if":{"output":1,"printer":1,"print":1,"fonts":1}
,"saving":{"script":1}
,"found":{"script":1}
,"user\u2019s":{"default":1}
,"default":{"printer":1}
,"6.0":{"earlier":1}
,"earlier":{"ou":1}
,"ou":{"store":1}
,"store":{"print":1}
,"allow":{"user":1}
,"user":{"enter":1}
,"enter":{"printing":1}
,"printing":{"criteria":1,"number":1,"automating":1}
,"criteria":{"step":1}
,"executes":{"if":1}
,"job":{"special":1}
,"special":{"page":1}
,"page":{"setup":1}
,"setup":{"options":1,"script":1,"dialog":1}
,"correctly":{"add":1,"pdf":1}
,"add":{"print":1}
,"webdirect":{"script":1}
,"creates":{"pdf":1}
,"new":{"web":1}
,"web":{"browser":1,"browser\u2019s":1,"publishing":1,"viewers":1}
,"browser":{"tab":1}
,"tab":{"print":1}
,"use":{"web":1,"print":1}
,"browser\u2019s":{"controls":1}
,"controls":{"if":1}
,"fonts":{"don\u2019t":1,"installed":1}
,"don\u2019t":{"display":1}
,"sure":{"all":1}
,"all":{"required":1}
,"required":{"fonts":1}
,"installed":{"web":1}
,"publishing":{"engine":1}
,"engine":{"filemaker":1}
,"server":{"deployment":1,"help":1}
,"deployment":{"filemaker":1}
,"help":{"web":1}
,"viewers":{"don\u2019t":1}
,"content":{"pdfs":1}
,"pdfs":{"use":1}
,"saved":{"printer":1}
,"name":{"applies":1}
,"applies":{"print":1}
,"settings":{"double-sided":1}
,"double-sided":{"printing":1}
,"number":{"copies":1}
,"copies":{"filemaker":1}
,"go":{"script":1,"print":1,"setting":1,"layout":1}
,"setting":{"maximum":1,"dialog":1}
,"maximum":{"image":1}
,"image":{"dpi":1}
,"dpi":{"choose":1}
,"resolution":{"filemaker":1}
,"displays":{"ios":1}
,"ios":{"print":1}
,"doesn\u2019t":{"display":1}
,"invoices":{"layout":1,"\u0022]":1}
,"layout":{"sorts":1,"[\u0022":1}
,"sorts":{"records":1}
,"records":{"prints":1,"[restore":1}
,"prints":{"go":1}
,"[\u0022":{"print":1}
,"\u0022]":{"sort":1}
,"sort":{"records":1}
,"[restore":{"dialog":1,"printer":1}
,"off]":{"print":1,"previewing":1}
,"previewing":{"printing":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
