var pairs =
{
"chart":{"type":1,"bar":1,"icons":1,"compare":1,"comparing":1,"compares":1,"single":1,"positive\u002Fnegative":1,"icon":1,"show":1,"easy":1,"chart":1,"scatter":1,"plot":1}
,"type":{"use":1}
,"use":{"column":1,"line":1,"stacked":1,"pie":1,"positive\u002Fnegative":1,"scatter":1,"bubble":1}
,"column":{"chart":1,"bar":1,"stacked":1}
,"bar":{"chart":1,"compares":1,"total":1}
,"icons":{"column":1,"stacked":1}
,"compare":{"two":1,"15":1,"parts":1,"annual":1,"positive":1,"earnings":1,"individual":1,"data":1,"monthly":1,"totals":1,"large":1,"number":1,"market":1}
,"two":{"numerical":1}
,"numerical":{"values":1}
,"values":{"dates":1,"data":1,"positive":1,"mid-point":1,"each":1,"reveal":1,"rises":1}
,"dates":{"under":1}
,"under":{"conditions":1}
,"conditions":{"comparing":1}
,"comparing":{"increases":1,"values":1,"categories":1,"number":1}
,"increases":{"decreases":1}
,"decreases":{"lowest":1}
,"lowest":{"single-series":1}
,"single-series":{"column":1}
,"data":{"category":1,"monthly":1,"points":1,"series":1,"point":1,"pie":1,"continuously":1,"time":1,"trends":1,"values":1,"considered":1,"characteristic":1}
,"category":{"monthly":1,"use":1}
,"monthly":{"sales":1}
,"sales":{"single":1,"products":1,"figures":1,"each":1,"year":1,"all":1,"region":1,"totals":1}
,"single":{"product":1,"data":1}
,"product":{"multi":1,"sales":1,"percentage":1}
,"multi":{"eries":1}
,"eries":{"column":1}
,"categories":{"data":1}
,"products":{"use":1,"years":1,"sold":1}
,"line":{"chart":1,"charts":1,"each":1}
,"15":{"data":1}
,"points":{"stacked":1,"category":1,"line":1,"charts":1,"reveal":1,"regard":1,"terms":1}
,"stacked":{"column":1,"bar":1}
,"parts":{"each":1}
,"each":{"column":1,"segment":1,"bar":1,"data":1,"bubble":1}
,"compares":{"multiple":1,"specific":1,"total":1}
,"multiple":{"data":1}
,"annual":{"sales":1}
,"figures":{"products":1,"product":1}
,"years":{"each":1,"chart":1}
,"segment":{"each":1}
,"specific":{"product":1}
,"total":{"product":1,"sales":1,"all":1}
,"year":{"entire":1,"charting":1}
,"entire":{"chart":1}
,"all":{"years":1,"data":1,"that\u2019s":1,"regions":1}
,"series":{"sales":1,"value":1,"charted":1,"display":1,"data":1,"bar":1,"quantitative":1,"emphasized":1}
,"region":{"use":1,"display":1}
,"pie":{"chart":1,"pie":1,"charts":1}
,"positive\u002Fnegative":{"chart":1,"column":1}
,"icon":{"positive\u002Fnegative":1,"pie":1,"line":1,"chart":1,"scatter":1,"bubble":1}
,"positive":{"negative":1,"values":1,"if":1}
,"negative":{"values":1,"if":1}
,"mid-point":{"zero":1,"set":1,"use":1}
,"zero":{"by":1}
,"by":{"default":1,"region":1,"colors":1,"comparing":1}
,"default":{"negative":1}
,"set":{"custom":1}
,"custom":{"mid-point":1}
,"earnings":{"losses":1}
,"losses":{"track":1}
,"track":{"productivity":1}
,"productivity":{"time":1}
,"time":{"pie":1,"historical":1,"use":1,"while":1}
,"show":{"relationship":1,"data":1}
,"relationship":{"each":1}
,"value":{"total":1}
,"charted":{"proportions":1}
,"proportions":{"single":1}
,"display":{"percentage":1,"trends":1}
,"percentage":{"values":1,"total":1}
,"point":{"slice":1,"represents":1}
,"slice":{"pie":1}
,"charts":{"effective":1,"pie":1,"commonly":1,"connect":1,"rise":1,"multiple":1,"compare":1}
,"effective":{"slices":1}
,"slices":{"represent":1}
,"represent":{"25":1}
,"25":{"50":1}
,"50":{"it\u2019s":1}
,"it\u2019s":{"difficult":1}
,"difficult":{"compare":1}
,"individual":{"sections":1,"measurement":1,"values":1,"data":1}
,"sections":{"pie":1}
,"commonly":{"general":1}
,"general":{"comparison":1}
,"comparison":{"all":1}
,"that\u2019s":{"required":1}
,"required":{"line":1}
,"continuously":{"trends":1}
,"trends":{"time":1,"cycles":1}
,"historical":{"financial":1}
,"financial":{"line":1}
,"connect":{"contiguous":1}
,"contiguous":{"series":1}
,"represents":{"individual":1}
,"measurement":{"line":1}
,"rise":{"fall":1}
,"fall":{"data":1}
,"totals":{"regions":1,"by":1}
,"regions":{"span":1,"use":1}
,"span":{"year":1}
,"charting":{"data":1}
,"easy":{"compare":1}
,"cycles":{"across":1}
,"across":{"all":1}
,"while":{"emphasizing":1}
,"emphasizing":{"highs":1}
,"highs":{"lows":1}
,"lows":{"movement":1}
,"movement":{"data":1}
,"quantitative":{"difference":1}
,"difference":{"each":1}
,"emphasized":{"by":1}
,"colors":{"chart":1}
,"scatter":{"chart":1}
,"plot":{"coordinates":1}
,"coordinates":{"individual":1}
,"reveal":{"correlation":1,"clear":1}
,"correlation":{"patterns":1}
,"patterns":{"if":1}
,"if":{"trend":1,"data":1}
,"trend":{"data":1,"considered":1,"falls":1}
,"rises":{"left":1}
,"left":{"right":1}
,"right":{"trend":1}
,"considered":{"positive":1,"negative":1,"correlated":1}
,"falls":{"left":1}
,"clear":{"slope":1}
,"slope":{"data":1}
,"correlated":{"scatter":1}
,"large":{"numbers":1}
,"numbers":{"data":1}
,"regard":{"time":1}
,"number":{"beverages":1,"products":1}
,"beverages":{"sold":1}
,"sold":{"restaurant":1,"sales":1}
,"restaurant":{"temperature":1}
,"temperature":{"changed":1}
,"changed":{"day":1}
,"day":{"bubble":1}
,"bubble":{"chart":1,"bubble":1,"charts":1}
,"characteristic":{"radius":1}
,"radius":{"each":1}
,"terms":{"size":1}
,"size":{"magnitude":1}
,"magnitude":{"use":1}
,"market":{"share":1}
,"share":{"by":1}
}
;Search.control.loadWordPairs(pairs);
