var pairs =
{
"dding":{"comments":1}
,"comments":{"formula":1,"explain":1,"end-of-line":1,"hich":1,"line":1,"defining":1,"nested":1,"\u002F*-----it":1}
,"formula":{"complex":1,"block":1,"\u002F*this":1,"ex":1}
,"complex":{"infrequently":1}
,"infrequently":{"formulas":1}
,"formulas":{"add":1}
,"add":{"comments":1}
,"explain":{"details":1}
,"details":{"use":1}
,"use":{"block":1}
,"block":{"comments":1,"omments":1,"comment":1}
,"end-of-line":{"comments":1,"omments":1,"comment":1}
,"hich":{"enter":1}
,"enter":{"formula":1,"comments":1}
,"omments":{"start":1,"end-of-line":1,"characters":1}
,"start":{"characters":1}
,"characters":{"\u002F*and":1,"*\u002F":1,"comments":1,"\u002F\u002Fand":1}
,"\u002F*and":{"finish":1}
,"finish":{"first":1,"end":1}
,"first":{"occurrence":1,"word":1}
,"occurrence":{"characters":1}
,"*\u002F":{"explanatory":1}
,"explanatory":{"text":1}
,"text":{"appears":1}
,"appears":{"two":1}
,"two":{"asterisk":1}
,"asterisk":{"characters":1}
,"line":{"end":1,"calculation":1}
,"end":{"lines":1,"line":1}
,"lines":{"nest":1}
,"nest":{"block":1}
,"\u002F\u002Fand":{"finish":1}
,"calculation":{"dialog":1,"fields":1,"block":1}
,"dialog":{"box":1}
,"box":{"enter":1,"entered":1}
,"defining":{"calculation":1}
,"fields":{"dialog":1}
,"entered":{"inside":1}
,"inside":{"formula":1}
,"\u002F*this":{"calculation":1}
,"nested":{"multiline":1}
,"multiline":{"comments":1}
,"\u002F*-----it":{"returns":1}
,"returns":{"title":1}
,"title":{"if":1,"*\u002F)":1}
,"if":{"exists":1,"first":1,"field":1}
,"exists":{"name":1}
,"name":{"-----*\u002F*\u002Fcase":1,"\u002F*returns":1,"\u002F*extracts":1}
,"-----*\u002F*\u002Fcase":{"patterncount":1}
,"patterncount":{"mrmsmrs":1}
,"mrmsmrs":{"leftwords":1}
,"leftwords":{"name":1}
,"\u002F*returns":{"true":1}
,"true":{"if":1}
,"word":{"fieldname":1}
,"fieldname":{"matches":1}
,"matches":{"titles":1}
,"titles":{"mr":1}
,"mr":{"ms":1}
,"ms":{"mrs*\u002Fleftwords":1}
,"mrs*\u002Fleftwords":{"name":1}
,"\u002F*extracts":{"title":1}
,"*\u002F)":{"greeting":1}
,"greeting":{"&\u0022":1,"string":1}
,"&\u0022":{"\u002F\u002Freturns":1}
,"\u002F\u002Freturns":{"if":1}
,"field":{"greeting":1}
,"string":{"add":1}
,"ex":{"ample":1}
,"ample":{"block":1}
,"comment":{"end-of-line":1}
}
;Search.control.loadWordPairs(pairs);
