var pairs =
{
"get":{"triggerkey":1,"triggerkeystroke":1,"trigger":1,"script":1}
,"triggerkey":{"stroke":1}
,"stroke":{"returns":1}
,"returns":{"characters":1,"value":1,"empty":1}
,"characters":{"activated":1,"returned":1}
,"activated":{"onobjectkeystroke":1}
,"onobjectkeystroke":{"onlayoutkeystroke":1,"script":1}
,"onlayoutkeystroke":{"script":1}
,"script":{"trigger":1,"triggered":1,"called":1,"returns":1}
,"trigger":{"get":1,"onlayoutkeystroke":1,"running":1,"keystroke":1,"key":1}
,"triggerkeystroke":{"none":1,"=13":1,"get":1}
,"none":{"text":1}
,"text":{"filemaker":1,"processing":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"10.0":1}
,"10.0":{"returns":1}
,"value":{"running":1}
,"running":{"script":1}
,"triggered":{"by":1,"script":1}
,"by":{"onobjectkeystroke":1}
,"called":{"triggered":1}
,"empty":{"string":1}
,"string":{"multiple":1,"code":1}
,"multiple":{"characters":1}
,"returned":{"input":1}
,"input":{"input":1,"method":1,"carriage":1,"\u0022]":1}
,"method":{"editor":1}
,"editor":{"ime":1}
,"ime":{"filemaker":1}
,"webdirect":{"function":1}
,"function":{"supported":1}
,"supported":{"returns":1}
,"code":{"displays":1}
,"displays":{"text":1}
,"processing":{"input":1}
,"carriage":{"return":1}
,"return":{"entered":1}
,"entered":{"if":1}
,"if":{"[code":1,"get":1}
,"[code":{"get":1}
,"=13":{"show":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"dialog":{"[\u0022":1}
,"[\u0022":{"processing":1}
,"\u0022]":{"end":1}
,"end":{"if":1}
,"keystroke":{"get":1}
,"key":{"script":1}
}
;Search.control.loadWordPairs(pairs);
