var pairs =
{
"get":{"modifiedfields":1}
,"modifiedfields":{"returns":1,"none":1}
,"returns":{"list":1,"new":1,"customer":1}
,"list":{"fields":1,"includes":1,"empty":1}
,"fields":{"modified":1,"dependent":1}
,"modified":{"current":1,"last":1,"field":1,"record":1}
,"current":{"record":1,"table":1}
,"record":{"current":1,"committed":1,"list":1,"open":1}
,"table":{"get":1}
,"none":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"13.0":1}
,"13.0":{"returns":1}
,"last":{"time":1}
,"time":{"record":1}
,"committed":{"list":1,"invoices":1}
,"includes":{"stored":1}
,"stored":{"calculation":1}
,"calculation":{"fields":1}
,"dependent":{"fields":1}
,"field":{"names":1}
,"names":{"separated":1}
,"separated":{"by":1}
,"by":{"carriage":1}
,"carriage":{"returns":1}
,"new":{"record":1}
,"empty":{"record":1}
,"invoices":{":customer":1,":company":1}
,":customer":{"name":1}
,"name":{"invoices":1,"company":1}
,":company":{"fields":1}
,"open":{"get":1}
,"customer":{"name":1}
}
;Search.control.loadWordPairs(pairs);
