var pairs =
{
"adding":{"vertical":1}
,"vertical":{"scroll":1}
,"scroll":{"bar":1,"bars":1}
,"bar":{"fiel":1,"choose":1,"portal":1,"filemaker":1}
,"fiel":{"layout":1}
,"layout":{"mode":1}
,"mode":{"select":1}
,"select":{"fields":1,"show":1}
,"fields":{"inspector":1,"repeating":1,"fields":1,"formatted":1}
,"inspector":{"data":1}
,"data":{"data":1,"tab":1,"visible":1,"resize":1}
,"tab":{"field":1}
,"field":{"control":1,"portal":1}
,"control":{"style":1}
,"style":{"choose":1}
,"choose":{"edit":1,"option":1}
,"edit":{"box":1}
,"box":{"select":1}
,"show":{"vertical":1}
,"option":{"add":1}
,"add":{"scroll":1}
,"portal":{"reating":1,"scroll":1,"larger":1}
,"reating":{"portals":1}
,"portals":{"display":1}
,"display":{"related":1}
,"related":{"record":1}
,"record":{"print":1}
,"print":{"field":1,"all":1,"add":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"prints":1}
,"prints":{"data":1}
,"visible":{"scrolling":1}
,"scrolling":{"print":1}
,"all":{"data":1}
,"resize":{"field":1}
,"larger":{"sliding":1}
,"sliding":{"options":1}
,"options":{"remove":1}
,"remove":{"extra":1}
,"extra":{"blank":1}
,"blank":{"space":1}
,"space":{"print":1}
,"bars":{"container":1}
,"container":{"fields":1}
,"repeating":{"fields":1}
,"formatted":{"use":1}
,"use":{"value":1}
,"value":{"list":1}
}
;Search.control.loadWordPairs(pairs);
