var pairs =
{
"sort":{"records":1,"by":1,"order":1,"perform":1}
,"records":{"by":1,"current":1,"want":1,"script":1,"[replace":1,"automating":1}
,"by":{"field":1,"ascending":1,"value":1,"active":1,"onobjectvalidate":1}
,"field":{"orts":1,"target":1,"specifies":1,"want":1,"filemaker":1,"letting":1,"script":1,"active":1,"sorts":1,"started":1,"values":1,"[ascending]":1,"[descending":1}
,"orts":{"records":1}
,"current":{"found":1,"customer":1}
,"found":{"set":1,"set\u0027s":1}
,"set":{"context":1,"by":1}
,"context":{"field":1}
,"target":{"field":1}
,"specifies":{"field":1}
,"want":{"sort":1}
,"ascending":{"displays":1,"order":1}
,"displays":{"data":1,"invalid":1}
,"data":{"ascending":1,"descending":1,"order":1}
,"order":{"descending":1,"associated":1,"determined":1,"alert":1,"field":1}
,"descending":{"displays":1,"order":1}
,"associated":{"value":1,"field":1}
,"value":{"list":1}
,"list":{"displays":1,"associated":1}
,"determined":{"by":1}
,"filemaker":{"pro":1}
,"pro":{"12.0":1,"advanced":1}
,"12.0":{"sorts":1}
,"sorts":{"records":1,"by":1,"current":1}
,"letting":{"create":1}
,"create":{"scripts":1}
,"scripts":{"behave":1}
,"behave":{"similarly":1}
,"similarly":{"interactively":1}
,"interactively":{"shortcut":1}
,"shortcut":{"menu":1}
,"menu":{"table":1}
,"table":{"view":1}
,"view":{"if":1}
,"if":{"field":1,"active":1}
,"script":{"sorts":1,"runs":1,"step":1,"trigger":1}
,"active":{"script":1,"field":1}
,"runs":{"if":1,"filemaker":1}
,"advanced":{"displays":1}
,"invalid":{"sort":1}
,"alert":{"find":1}
,"find":{"records":1,"script":1,"matching":1}
,"perform":{"find":1}
,"step":{"show":1,"script":1,"use":1,"go":1,"sort":1}
,"show":{"all":1}
,"all":{"records":1}
,"use":{"enter":1}
,"enter":{"browse":1}
,"browse":{"mode":1}
,"mode":{"script":1}
,"go":{"record\u002Frequest\u002Fpage":1}
,"record\u002Frequest\u002Fpage":{"script":1}
,"started":{"by":1}
,"onobjectvalidate":{"script":1}
,"trigger":{"maintain":1}
,"maintain":{"current":1}
,"set\u0027s":{"sort":1}
,"values":{"change":1}
,"change":{"sort":1}
,"[ascending]":{"invoices":1}
,"invoices":{"current":1,":customer":1,":invoice":1}
,"customer":{"id":1}
,"id":{"recent":1}
,"recent":{"invoice":1}
,"invoice":{"listed":1}
,"listed":{"first":1}
,"first":{"find":1}
,"matching":{"records":1}
,"[replace":{"invoices":1}
,":customer":{"id]":1}
,"id]":{"sort":1,"options":1}
,"[descending":{"invoices":1}
,":invoice":{"id]":1}
,"options":{"sorting":1}
,"sorting":{"records":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
