var pairs =
{
"decrypting":{"fil":1}
,"fil":{"note":1}
,"note":{"feature":1}
,"feature":{"use":1}
,"use":{"advanced":1}
,"advanced":{"tools":1}
,"tools":{"general":1,"se":1,"menu":1}
,"general":{"preference":1}
,"preference":{"selected":1}
,"selected":{"ad":1}
,"ad":{"vanced":1}
,"vanced":{"tools":1}
,"se":{"developer":1}
,"developer":{"utilities":1}
,"utilities":{"decrypt":1,"if":1,"database":1}
,"decrypt":{"encrypted":1,"choose":1,"add":1,"file":1}
,"encrypted":{"file":1,"solution":1,"copy":1}
,"file":{"file":1,"decrypted":1,"etting":1,"load":1,"files":1,"rename":1,"type":1,"saving":1,"account":1}
,"decrypted":{"secure":1,"change":1,"file":1}
,"secure":{"open":1}
,"open":{"storage":1}
,"storage":{"container":1}
,"container":{"data":1,"fields":1}
,"data":{"stored":1,"externally":1}
,"stored":{"externally":1,"decrypted":1}
,"externally":{"remains":1,"close":1}
,"remains":{"file":1}
,"change":{"data":1,"quickly":1}
,"etting":{"up":1}
,"up":{"container":1}
,"fields":{"store":1}
,"store":{"data":1}
,"close":{"all":1}
,"all":{"database":1}
,"database":{"files":1,"solution":1,"encryption":1}
,"files":{"decrypt":1,"want":1,"11":1}
,"choose":{"tools":1,"location":1,"folder":1}
,"menu":{"developer":1}
,"if":{"developer":1}
,"solution":{"saved":1,"rename":1,"setting":1,"options":1}
,"saved":{"settings":1}
,"settings":{"load":1,"locate":1,"choose":1,"file":1}
,"load":{"settings":1,"add":1}
,"locate":{"select":1,"file":1}
,"select":{".sav":1,"remove":1}
,".sav":{"file":1}
,"add":{"locate":1,"project":1}
,"want":{"decrypt":1}
,"project":{"folder":1}
,"folder":{"choose":1,"location":1}
,"location":{"encrypted":1,"settings":1}
,"rename":{"encrypted":1,"file":1}
,"copy":{"file":1}
,"type":{"filename":1}
,"filename":{"change":1}
,"quickly":{"repeat":1}
,"repeat":{"process":1}
,"process":{"save":1}
,"save":{"settings":1}
,"saving":{"solution":1}
,"setting":{"solution":1}
,"options":{"solution":1,"dialog":1}
,"dialog":{"box":1}
,"box":{"select":1}
,"remove":{"database":1}
,"encryption":{"10":1,"password":1}
,"10":{"encryption":1}
,"password":{"enter":1,"database":1,"account":1}
,"enter":{"current":1,"filemaker":1}
,"current":{"encryption":1}
,"11":{"filemaker":1}
,"filemaker":{"account":1,"file":1}
,"account":{"12":1,"name":1,"full":1}
,"12":{"enter":1}
,"name":{"password":1}
,"full":{"access":1}
,"access":{"privileges":1}
,"privileges":{"13":1}
,"13":{"create":1}
,"create":{"decrypt":1}
}
;Search.control.loadWordPairs(pairs);
