var pairs =
{
"chan":{"ging":1}
,"ging":{"theme":1}
,"theme":{"layout":1,"existing":1,"attributes":1,"applied":1,"all":1,"button":1,"dialog":1,"fr":1,"filemaker":1,"want":1,"if":1,"creating":1,"saving":1,"reveals":1,"hen":1,"doesn\u2019t":1,"supports":1,"custom":1,"based":1,"write":1}
,"layout":{"change":1,"exceptions":1,"layout":1,"background":1,"parts":1,"mode":1,"want":1,"bar":1,"theme":1,"themes":1,"objects":1,"undo":1,"looked":1,"if":1,"level":1}
,"change":{"theme":1,"layout\u2019s":1,"default":1,"name":1,"two":1,"layout\u0027s":1}
,"existing":{"layout":1}
,"layout\u2019s":{"theme":1}
,"attributes":{"new":1,"applied":1}
,"new":{"theme":1,"themes":1,"theme\u0027s":1}
,"applied":{"all":1,"objects":1,"automatically":1}
,"all":{"objects":1,"text":1}
,"objects":{"layout":1,"text":1,"controlled":1,"saved":1,"if":1,"formatted":1,"retain":1}
,"exceptions":{"objects":1}
,"text":{"font":1,"properties":1,"size":1}
,"font":{"color":1,"family":1}
,"color":{"font":1}
,"family":{"change":1}
,"default":{"style":1,"styles":1}
,"style":{"defined":1,"style":1,"names":1,"setting":1,"occasionally":1}
,"defined":{"theme":1,"new":1}
,"properties":{"text":1}
,"size":{"retained":1}
,"retained":{"buttons":1,"layout":1}
,"buttons":{"created":1}
,"created":{"versions":1}
,"versions":{"filemaker":1}
,"filemaker":{"pro":1,"go":1}
,"pro":{"advanced":1,"arlier":1}
,"advanced":{"filemaker":1,"file":1,"software":1}
,"arlier":{"version":1}
,"version":{"12":1,"predefined":1}
,"12":{"retain":1}
,"retain":{"original":1,"default":1}
,"original":{"formatting":1}
,"formatting":{"if":1,"predefined":1}
,"if":{"objects":1,"pre-designed":1,"change":1,"name":1,"switch":1,"solution":1}
,"background":{"re":1}
,"re":{"filled":1,"case":1}
,"filled":{"image":1}
,"image":{"image":1,"retained":1,"display":1}
,"parts":{"filled":1}
,"display":{"fill":1,"layout":1,"change":1,"preview":1,"object":1}
,"fill":{"defined":1}
,"mode":{"display":1,"switch":1}
,"want":{"change":1,"import":1,"create":1}
,"name":{"current":1,"saved":1}
,"current":{"theme":1}
,"bar":{"status":1}
,"status":{"toolbar":1}
,"toolbar":{"layout":1}
,"button":{"display":1}
,"dialog":{"box":1}
,"box":{"apply":1,"select":1}
,"apply":{"theme":1}
,"fr":{"om":1}
,"om":{"file":1}
,"file":{"select":1,"import":1,"theme":1,"ormatting":1}
,"select":{"theme":1,"themes":1}
,"themes":{"list":1,"choose":1,"import":1,"dialog":1,"display":1,"if":1,"attributes":1,"additional":1}
,"list":{"display":1,"styles":1}
,"preview":{"each":1}
,"each":{"theme":1}
,"import":{"themes":1,"open":1}
,"choose":{"file":1}
,"open":{"select":1}
,"styles":{"layout":1,"want":1,"second":1,"old":1,"stored":1,"objects":1,"reset":1,"if":1,"styles":1,"tab":1}
,"controlled":{"by":1}
,"by":{"layout\u2019s":1}
,"pre-designed":{"themes":1}
,"object":{"styles":1}
,"create":{"custom":1}
,"custom":{"theme":1,"styles":1}
,"creating":{"theme":1}
,"saving":{"managing":1}
,"managing":{"layout":1}
,"undo":{"change":1,"first":1,"new":1,"reverts":1}
,"two":{"levels":1}
,"levels":{"undo":1}
,"first":{"undo":1}
,"reveals":{"attributes":1}
,"saved":{"styles":1,"custom":1}
,"second":{"undo":1}
,"reverts":{"layout":1}
,"looked":{"changed":1}
,"changed":{"theme":1}
,"hen":{"change":1}
,"old":{"new":1}
,"theme\u0027s":{"style":1}
,"names":{"re":1}
,"case":{"sensitive":1}
,"sensitive":{"unsaved":1}
,"unsaved":{"styles":1}
,"stored":{"layout":1}
,"level":{"deleted":1}
,"deleted":{"ome":1}
,"ome":{"themes":1}
,"additional":{"predefined":1,"styles":1}
,"predefined":{"styles":1,"style":1,"themes":1,"theme":1}
,"switch":{"theme":1,"layout":1}
,"doesn\u2019t":{"support":1}
,"support":{"additional":1}
,"formatted":{"additional":1}
,"reset":{"default":1}
,"supports":{"additional":1}
,"setting":{"use":1}
,"use":{"styles":1}
,"tab":{"inspector":1}
,"inspector":{"reapply":1}
,"reapply":{"additional":1}
,"occasionally":{"filemaker":1}
,"software":{"updates":1}
,"updates":{"include":1}
,"include":{"formatting":1}
,"solution":{"version":1}
,"based":{"version":1}
,"write":{"permission":1}
,"permission":{"file":1}
,"ormatting":{"applied":1}
,"automatically":{"switch":1}
,"layout\u0027s":{"theme":1}
,"go":{"change":1}
}
;Search.control.loadWordPairs(pairs);
