var pairs =
{
"efining":{"custom":1}
,"custom":{"menu":1,"menus":1,"keyboard":1,"order":1,"shortcuts":1}
,"menu":{"note":1,"items":1,"menu":1,"item":1,"assigning":1,"sets":1,"by":1,"duplicate":1,"modifying":1,"manage":1,"create":1,"select":1,"list":1,"edit":1,"delete":1,"name":1,"set":1,"display":1,"sets\u002Fcomments":1,"dialog":1,"comments":1,"bar":1,"title":1,"access":1,"installed":1,"file":1,"if":1,"cut":1,"add":1,"command":1,"japanese":1}
,"note":{"feature":1,"change":1}
,"feature":{"use":1}
,"use":{"advanced":1,"characters":1,"yen":1}
,"advanced":{"tools":1,"ncludes":1,"menus":1,"enus":1,"create":1}
,"tools":{"general":1,"yo":1}
,"general":{"preference":1}
,"preference":{"selected":1}
,"selected":{"ad":1,"create":1}
,"ad":{"vanced":1}
,"vanced":{"tools":1}
,"yo":{"create":1}
,"create":{"custom":1,"menu":1,"choose":1,"create":1,"empty":1,"edit":1,"new":1}
,"menus":{"database":1,"menu":1,"users":1,"custom":1,"tab":1,"exist":1,"file":1,"dialog":1,"edited":1,"based":1,"dimmed":1}
,"database":{"solutions":1}
,"solutions":{"add":1}
,"add":{"edit":1,"missing":1,"custom":1,"menu":1}
,"edit":{"duplicate":1,"modify":1,"edit":1,"custom":1,"menu":1}
,"duplicate":{"delete":1,"menu":1}
,"delete":{"menus":1,"menu":1,"default":1}
,"items":{"changing":1,"mode":1,"sort":1,"list":1,"creating":1,"new":1,"manually":1,"dimmed":1,"based":1}
,"changing":{"menu":1}
,"item":{"name":1,"run":1,"manage":1,"shortcut":1,"customize":1,"standard":1,"disable":1}
,"name":{"performing":1,"display":1,"comments":1,"windows":1}
,"performing":{"script":1}
,"script":{"script":1,"step":1,"menu":1}
,"step":{"menu":1}
,"run":{"scripts":1}
,"scripts":{"associated":1}
,"associated":{"toolbar":1}
,"toolbar":{"icon":1}
,"icon":{"shortcut":1}
,"shortcut":{"menu":1,"character":1,"edit":1}
,"assigning":{"custom":1}
,"keyboard":{"shortcuts":1}
,"shortcuts":{"access":1,"add":1,"use":1}
,"access":{"keys":1,"key":1}
,"keys":{"platform":1}
,"platform":{"menus":1}
,"mode":{"menus":1,"titles":1,"erforms":1}
,"sets":{"files":1,"created":1}
,"files":{"layouts":1}
,"layouts":{"create":1}
,"by":{"starting":1,"editing":1,"create":1,"shortcut":1}
,"starting":{"blank":1}
,"blank":{"menu":1,"if":1}
,"editing":{"copy":1,"custom":1}
,"copy":{"standard":1,"paste":1}
,"standard":{"filemaker":1}
,"filemaker":{"menu":1,"pro":1,"features":1}
,"modifying":{"original":1}
,"original":{"delete":1}
,"users":{"choose":1,"don\u2019t":1}
,"choose":{"file":1,"creation":1,"view":1,"menu":1}
,"file":{"menu":1,"update":1,"manage":1,"windows":1,"macos":1,"choose":1}
,"manage":{"custom":1}
,"tab":{"if":1}
,"if":{"filemaker":1,"start":1,"selected":1,"calculation":1,"abs":1,"included":1,"remove":1,"customize":1,"users":1,"attach":1,"use":1}
,"pro":{"advanced":1}
,"ncludes":{"menus":1}
,"exist":{"file":1}
,"update":{"add":1}
,"missing":{"menus":1}
,"dialog":{"box":1,"boxes":1}
,"box":{"create":1,"name":1,"solution":1,"default":1,"if":1}
,"creation":{"option":1}
,"option":{"if":1}
,"start":{"standard":1}
,"select":{"menu":1,"override":1}
,"list":{"hift":1,"edit":1,"delete":1,"choose":1,"menu":1}
,"hift":{"-c":1}
,"-c":{"lick":1}
,"lick":{"create":1}
,"empty":{"menu":1}
,"modify":{"edit":1}
,"default":{"filemaker":1,"menu":1,"action":1}
,"edited":{"list":1}
,"sort":{"menu":1}
,"view":{"by":1}
,"order":{"drag":1}
,"drag":{"items":1}
,"display":{"title":1,"menu":1,"comments":1,"file":1}
,"title":{"column":1,"select":1,"enter":1,"result":1,"help":1}
,"column":{"headings":1,"heading":1}
,"headings":{"display":1}
,"set":{"menu":1,"file":1,"filemaker":1}
,"comments":{"describing":1,"options":1,"manage":1}
,"describing":{"menu":1}
,"sets\u002Fcomments":{"column":1}
,"heading":{"if":1}
,"options":{"entire":1}
,"entire":{"custom":1}
,"solution":{"itle":1,"menu":1}
,"itle":{"display":1}
,"bar":{"solution":1,"button":1}
,"override":{"title":1}
,"enter":{"name":1,"if":1,"create":1,"key":1}
,"windows":{"access":1,"enter":1}
,"key":{"type":1,"character":1,"base":1,"find":1}
,"type":{"ampersand":1,"&file":1}
,"ampersand":{"(&)":1}
,"(&)":{"access":1}
,"character":{"type":1,"japanese":1,"shortcut":1,"appears":1,"find":1}
,"&file":{"display":1}
,"base":{"menu":1}
,"result":{"calculation":1}
,"calculation":{"note":1,"boolean":1,"evaluates":1}
,"change":{"title":1}
,"help":{"ilemaker":1}
,"ilemaker":{"pro":1}
,"enus":{"install":1}
,"install":{"menus":1,"calculation":1,"enter":1,"menu":1}
,"based":{"conditions":1,"existing":1,"field":1}
,"conditions":{"install":1}
,"boolean":{"value":1}
,"value":{"if":1}
,"evaluates":{"true":1,"false":1}
,"true":{"non-zero":1}
,"non-zero":{"menu":1}
,"installed":{"menu":1,"install":1}
,"abs":{"get":1}
,"get":{"systemplatform":1}
,"systemplatform":{"=2":1,"=1":1}
,"=2":{"if":1}
,"false":{"zero":1}
,"zero":{"menu":1}
,"macos":{"enter":1,"install":1}
,"=1":{"ensure":1}
,"ensure":{"menu":1}
,"creating":{"editing":1}
,"features":{"if":1,"menu":1}
,"included":{"menu":1}
,"remove":{"edit":1,"perform":1}
,"cut":{"copy":1}
,"paste":{"shortcuts":1}
,"new":{"features":1,"custom":1}
,"created":{"previous":1}
,"previous":{"versions":1}
,"versions":{"filemaker":1}
,"manually":{"create":1}
,"customize":{"menu":1,"behavior":1,"action":1}
,"behavior":{"performed":1}
,"performed":{"by":1}
,"dimmed":{"if":1}
,"don\u2019t":{"privileges":1}
,"privileges":{"perform":1}
,"perform":{"menu":1,"find":1}
,"command":{"menus":1,"custom":1,"rom":1}
,"attach":{"script":1}
,"disable":{"based":1}
,"existing":{"command":1}
,"characters":{"found":1}
,"found":{"english\u002Fu.s":1}
,"english\u002Fu.s":{"keyboards":1}
,"keyboards":{"use":1,"if":1}
,"yen":{"character":1}
,"japanese":{"keyboards":1,"system":1}
,"appears":{"backslash":1,"properly":1}
,"backslash":{"(\u005C)":1}
,"(\u005C)":{"shortcut":1}
,"boxes":{"macos":1}
,"system":{"character":1}
,"properly":{"yen":1}
,"find":{"mode":1,"ommand":1,"button":1,"command":1}
,"titles":{"custom":1}
,"field":{"values":1}
,"values":{"global":1}
,"global":{"blank":1}
,"action":{"perform":1,"if":1,"create":1}
,"ommand":{"clicking":1}
,"clicking":{"perform":1}
,"button":{"pressing":1,"keystroke":1}
,"pressing":{"enter":1}
,"erforms":{"customized":1,"default":1}
,"customized":{"action":1}
,"rom":{"menu":1}
,"keystroke":{"erforms":1}
}
;Search.control.loadWordPairs(pairs);
