var pairs =
{
"get":{"activeselection":1,"activeselectionstart":1,"active":1,"selection":1,"current":1,"starting":1}
,"activeselection":{"start":1}
,"start":{"returns":1,"get":1}
,"returns":{"number":1,"cursor\u0027s":1,"selection":1}
,"number":{"representing":1,"filemaker":1}
,"representing":{"starting":1}
,"starting":{"character":1,"characters":1}
,"character":{"selected":1,"get":1}
,"selected":{"text":1,"if":1}
,"text":{"get":1,"selected":1,"concealed":1}
,"activeselectionstart":{"none":1,"get":1}
,"none":{"number":1}
,"filemaker":{"pro":1,"go":1,"webdirect":1}
,"pro":{"7.0":1}
,"7.0":{"returns":1}
,"cursor\u0027s":{"current":1}
,"current":{"position":1,"database":1,"selection":1}
,"position":{"if":1}
,"if":{"text":1,"multiple":1,"selected":1}
,"multiple":{"windows":1}
,"windows":{"open":1}
,"open":{"current":1}
,"database":{"file":1}
,"file":{"result":1}
,"result":{"returned":1}
,"returned":{"foreground":1}
,"foreground":{"window":1}
,"window":{"filemaker":1}
,"go":{"function":1}
,"function":{"return":1,"supported":1}
,"return":{"inaccurate":1}
,"inaccurate":{"value":1}
,"value":{"if":1}
,"concealed":{"edit":1}
,"edit":{"box":1}
,"box":{"function":1}
,"supported":{"filemaker":1}
,"webdirect":{"returns":1}
,"selection":{"starts":1,"start":1}
,"starts":{"character":1}
,"active":{"selection":1}
,"characters":{"active":1}
}
;Search.control.loadWordPairs(pairs);
