var pairs =
{
"reating":{"layout":1}
,"layout":{"new":1,"type":1,"types":1,"mode":1,"want":1,"defining":1,"parts":1,"depending":1,"create":1,"theme":1,"if":1,"table":1,"time":1,"placing":1,"duplicate":1,"customize":1}
,"new":{"layout\u002Freport":1,"new":1,"fit":1}
,"layout\u002Freport":{"assistant":1,"status":1}
,"assistant":{"helps":1,"complete":1,"layout":1}
,"helps":{"design":1,"create":1}
,"design":{"types":1}
,"types":{"layouts":1,"devices":1,"layout":1}
,"layouts":{"reports":1,"new":1,"labels":1,"designed":1,"current":1,"properly":1,"divided":1,"heading":1}
,"reports":{"display":1,"mailing":1,"additional":1}
,"display":{"types":1,"layout":1}
,"devices":{"laptop":1,"add":1}
,"laptop":{"computer":1}
,"computer":{"screens":1}
,"screens":{"touch":1,"purposes":1}
,"touch":{"device":1,"devices":1}
,"device":{"screens":1}
,"purposes":{"browsing":1}
,"browsing":{"records":1}
,"records":{"entering":1}
,"entering":{"data":1}
,"data":{"printing":1}
,"printing":{"reports":1}
,"mailing":{"labels":1}
,"labels":{"envelopes":1}
,"envelopes":{"views":1,"reports":1}
,"views":{"form":1}
,"form":{"view":1}
,"view":{"table":1,"list":1,"details":1}
,"table":{"view":1,"database":1}
,"list":{"view":1}
,"details":{"each":1}
,"each":{"layout":1}
,"type":{"bout":1,"layout":1}
,"bout":{"layout":1}
,"mode":{"new":1,"choose":1,"print":1}
,"status":{"toolbar":1}
,"toolbar":{"browse":1,"modified":1}
,"browse":{"mode":1}
,"choose":{"file":1}
,"file":{"menu":1,"change":1,"etting":1,"options":1}
,"menu":{"manage":1,"print":1,"page":1}
,"manage":{"layouts":1}
,"create":{"type":1,"assigned":1,"layout":1}
,"want":{"choices":1}
,"choices":{"additional":1,"current":1,"new":1}
,"additional":{"options":1,"panels":1}
,"options":{"types":1,"add":1}
,"panels":{"onscreen":1}
,"onscreen":{"help":1}
,"help":{"topic":1}
,"topic":{"explains":1}
,"explains":{"choices":1}
,"current":{"panel":1,"file":1}
,"panel":{"press":1}
,"press":{"f1":1}
,"f1":{"windows":1}
,"windows":{"command-?":1,"file":1,"page":1}
,"command-?":{"macos":1}
,"macos":{"layouts":1,"confirm":1,"status":1}
,"designed":{"computers":1}
,"computers":{"touch":1}
,"add":{"fields":1}
,"fields":{"layout":1,"if":1,"existing":1}
,"defining":{"changing":1}
,"changing":{"fields":1,"theme":1}
,"if":{"intend":1,"include":1}
,"intend":{"print":1}
,"print":{"report":1,"setup":1,"layouts":1}
,"report":{"landscape":1}
,"landscape":{"orientation":1}
,"orientation":{"special":1,"paper":1}
,"special":{"paper":1}
,"paper":{"size":1,"settings":1}
,"size":{"choose":1}
,"setup":{"windows":1,"macos":1,"page":1,"settings":1}
,"page":{"setup":1}
,"confirm":{"orientation":1}
,"settings":{"preview":1,"affect":1,"print":1}
,"preview":{"mode":1}
,"modified":{"print":1}
,"affect":{"all":1}
,"all":{"layouts":1}
,"change":{"settings":1}
,"properly":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"layouts":1,"includes":1,"file":1}
,"divided":{"layout":1}
,"parts":{"filemaker":1,"layout":1,"complete":1,"each":1}
,"includes":{"parts":1}
,"depending":{"choices":1}
,"complete":{"control":1,"assistant":1}
,"control":{"layout":1}
,"assigned":{"layout":1}
,"theme":{"changing":1,"layout":1}
,"include":{"field":1}
,"field":{"layout":1,"understand":1}
,"database":{"related":1,"concepts":1}
,"related":{"field":1,"tables":1}
,"understand":{"relational":1}
,"relational":{"database":1}
,"concepts":{"related":1}
,"tables":{"display":1}
,"time":{"open":1}
,"open":{"filemaker":1}
,"etting":{"file":1}
,"existing":{"label":1,"layout":1}
,"label":{"envelope":1}
,"envelope":{"layout":1}
,"placing":{"merge":1}
,"merge":{"fields":1}
,"duplicate":{"existing":1}
,"customize":{"new":1}
,"fit":{"duplicating":1}
,"duplicating":{"deleting":1}
,"deleting":{"renaming":1}
,"renaming":{"layouts":1}
,"heading":{"headings":1}
,"headings":{"create":1}
}
;Search.control.loadWordPairs(pairs);
