var pairs =
{
"executesql":{"executes":1,"sqlquery":1,"enables":1,"recognize":1,"sql":1,"treats":1,"accepts":1,"accept":1,"function":1,"select":1}
,"executes":{"sql":1}
,"sql":{"query":1,"select":1,"dynamic":1,"statements":1,"unicode":1,"reference":1,"script":1}
,"query":{"statement":1,"use":1,"filemaker":1,"parsing":1,"tables":1,"dynamic":1}
,"statement":{"table":1,"statement":1,"include":1,"contain":1,"text":1,"if":1,"executesql":1,"syntax":1,"round":1}
,"table":{"occurrence":1,"independent":1,"commands":1,"display":1,"aliases":1,"salaries":1,"fields":1,"use":1}
,"occurrence":{"filemaker":1}
,"filemaker":{"pro":1,"sql":1,"odbc":1,"data":1}
,"pro":{"advanced":1,"12.0":1}
,"advanced":{"file":1,"databases":1,"flexibility":1,"returns":1,"sort":1,"generate":1}
,"file":{"executesql":1}
,"sqlquery":{"fieldseparator":1,"-an":1,"first":1}
,"fieldseparator":{"rowseparator":1,"-the":1}
,"rowseparator":{"arguments":1,"-the":1}
,"arguments":{"sqlquery":1,"query":1,"-one":1,"parameter":1}
,"-an":{"sql":1}
,"select":{"statement":1,"statements":1,"supported":1,"department":1,"sum":1}
,"include":{"union":1}
,"union":{"clause":1}
,"clause":{"combines":1}
,"combines":{"two":1}
,"two":{"queries":1,"tables":1}
,"queries":{"statement":1}
,"contain":{"programmatically":1}
,"programmatically":{"generated":1}
,"generated":{"sql":1}
,"dynamic":{"parameters":1,"parameter":1}
,"parameters":{"optional":1,"query":1,"safely":1,"sqlquery":1,"table":1}
,"optional":{"arguments":1}
,"use":{"question":1,"multiple":1,"date":1,"xecute":1,"executesql":1,"calculation":1}
,"question":{"mark":1}
,"mark":{"character":1}
,"character":{"dynamic":1,"string":1,"replaced":1}
,"parameter":{"fieldseparator":1,"second":1}
,"-the":{"character":1}
,"string":{"separator":1}
,"separator":{"fields":1,"comma":1,"displayed":1,"records":1,"carriage":1}
,"fields":{"result":1,"number":1,"use":1,"s.salary":1}
,"result":{"if":1,"rowseparator":1,"arguments":1}
,"if":{"empty":1,"error":1,"use":1}
,"empty":{"string":1}
,"comma":{"field":1}
,"field":{"separator":1,"result":1,"list":1,"value":1,"employees":1,"displays":1}
,"displayed":{"last":1}
,"last":{"field":1,"row":1,"name":1}
,"records":{"result":1}
,"carriage":{"return":1}
,"return":{"row":1,"field":1}
,"row":{"separator":1,"result":1}
,"-one":{"expressions":1}
,"expressions":{"separated":1,"catalog":1}
,"separated":{"by":1}
,"by":{"semicolons":1,"first":1,"second":1}
,"semicolons":{"evaluated":1}
,"evaluated":{"values":1}
,"values":{"dynamic":1}
,"text":{"filemaker":1}
,"12.0":{"executesql":1}
,"enables":{"execute":1}
,"execute":{"sql":1,"select":1}
,"statements":{"dynamic":1,"retrieve":1,"modify":1,"expressions":1,"query":1,"odbc":1}
,"safely":{"query":1}
,"databases":{"order":1}
,"order":{"avoid":1,"filemaker":1,"language":1,"details":1}
,"avoid":{"security":1}
,"security":{"vulnerabilities":1}
,"vulnerabilities":{"injection":1}
,"injection":{"attacks":1}
,"attacks":{"executesql":1}
,"recognize":{"relationships":1}
,"relationships":{"created":1,"sql":1}
,"created":{"filemaker":1}
,"flexibility":{"define":1}
,"define":{"relationships":1,"calculation":1}
,"retrieve":{"data":1}
,"data":{"table":1,"database":1,"unicode\u002Fsql":1,"sources":1}
,"independent":{"layout":1}
,"layout":{"context":1,"suppose":1}
,"context":{"executesql":1}
,"modify":{"data":1}
,"database":{"schema":1,"two":1}
,"schema":{"insert":1}
,"insert":{"delete":1}
,"delete":{"table":1}
,"commands":{"use":1}
,"multiple":{"dynamic":1}
,"first":{"question":1,"arguments":1}
,"replaced":{"by":1}
,"second":{"by":1,"if":1}
,"error":{"occurs":1}
,"occurs":{"during":1}
,"during":{"query":1}
,"parsing":{"execution":1}
,"execution":{"filemaker":1}
,"returns":{"apply":1,"date":1,"development":1,"52.97":1,"100":1}
,"apply":{"correct":1}
,"correct":{"formatting":1}
,"formatting":{"dates":1}
,"dates":{"sql":1,"literal":1}
,"date":{"statement":1,"time":1}
,"treats":{"dates":1}
,"literal":{"strings":1}
,"strings":{"filemaker":1}
,"time":{"number":1,"formats":1,"timestamp":1}
,"number":{"data":1,"fields":1}
,"unicode\u002Fsql":{"format":1}
,"format":{"locale":1,"date":1}
,"locale":{"operating":1}
,"operating":{"system":1}
,"system":{"file":1}
,"accepts":{"sql-92":1}
,"sql-92":{"syntax":1}
,"syntax":{"iso":1,"supported":1}
,"iso":{"date":1}
,"formats":{"braces":1}
,"braces":{"executesql":1,"filemaker":1}
,"accept":{"odbc\u002Fjdbc":1}
,"odbc\u002Fjdbc":{"format":1}
,"timestamp":{"constants":1}
,"constants":{"braces":1}
,"unicode":{"binary":1}
,"binary":{"sort":1}
,"sort":{"order":1}
,"language":{"sorting":1}
,"sorting":{"default":1}
,"default":{"language-neutral":1}
,"language-neutral":{"sort":1}
,"details":{"select":1}
,"supported":{"sql":1}
,"catalog":{"functions":1}
,"functions":{"filemaker":1}
,"odbc":{"jdbc":1,"data":1}
,"jdbc":{"guide":1}
,"guide":{"filemaker":1}
,"reference":{"executesql":1}
,"function":{"sql":1,"return":1,"query":1}
,"tables":{"filemaker":1,"employees":1}
,"sources":{"odbc":1,"execute":1,"use":1}
,"xecute":{"sql":1}
,"script":{"step":1}
,"step":{"suppose":1}
,"suppose":{"database":1,"want":1}
,"employees":{"salaries":1,":empid":1,"empid":1,"table":1,"join":1,":department":1}
,"salaries":{"related":1,"note":1,":empid":1,":salary":1,"department":1,"table":1,"e.empid":1,"employee\u0027s":1}
,"related":{"empid":1}
,"empid":{"field":1,"=1":1}
,"list":{"displaying":1}
,"displaying":{"employees":1}
,"note":{"employees":1}
,":empid":{"salaries":1}
,":salary":{"fields":1,"\u002Fexecutesql":1}
,"value":{"specific":1,"use":1}
,"specific":{"record":1}
,"record":{"changing":1,"modifying":1,"found":1,"calculation":1,"last":1}
,"changing":{"current":1}
,"current":{"record":1}
,"modifying":{"found":1}
,"found":{"set":1}
,"set":{"executesql":1,"layout":1}
,"department":{"employees":1,"use":1,"record":1}
,"=1":{"returns":1}
,"development":{"current":1}
,"want":{"add":1}
,"add":{"field":1}
,"display":{"percentage":1}
,"percentage":{"employee\u2019s":1,"employee\u0027s":1}
,"employee\u2019s":{"salary":1}
,"salary":{"relative":1}
,"relative":{"total":1,"sum":1}
,"total":{"salaries":1}
,"calculation":{"filemaker":1,"field":1}
,"generate":{"value":1}
,"aliases":{"employees":1}
,"s.salary":{"e.empid":1,"employees":1}
,"e.empid":{"s.empid":1,"=s.empid":1}
,"s.empid":{"define":1}
,"round":{"100":1}
,"100":{"*salaries":1}
,"*salaries":{":salary":1}
,"\u002Fexecutesql":{"select":1}
,"sum":{"s.salary":1,"salaries":1}
,"join":{"salaries":1}
,"=s.empid":{"e.department":1}
,"e.department":{"=?":1}
,"=?":{"employees":1}
,":department":{"each":1}
,"each":{"employee":1}
,"employee":{"record":1}
,"displays":{"percentage":1}
,"employee\u0027s":{"salary":1,"department":1}
,"name":{"smith":1,"mehmet":1}
,"smith":{"returns":1}
,"52.97":{"record":1}
,"mehmet":{"returns":1}
}
;Search.control.loadWordPairs(pairs);
