var pairs =
{
"get":{"activerecordnumber":1,"recordid":1,"recordnumber":1,"active":1,"current":1}
,"activerecordnumber":{"returns":1,"none":1,"apply":1,"get":1}
,"returns":{"number":1,"fourth":1}
,"number":{"representing":1,"filemaker":1,"displayed":1,"record":1,"get":1}
,"representing":{"record":1}
,"record":{"focus":1,"number":1,"found":1,"table":1,"list":1}
,"focus":{"current":1,"portal":1,"hide":1}
,"current":{"found":1,"record":1,"table":1}
,"found":{"set":1}
,"set":{"get":1,"depending":1,"focus":1,"number":1}
,"none":{"number":1}
,"filemaker":{"pro":1}
,"pro":{"7.0":1}
,"7.0":{"advanced":1}
,"advanced":{"value":1}
,"value":{"returned":1,"uniquely":1}
,"returned":{"current":1}
,"displayed":{"navigation":1}
,"navigation":{"controls":1}
,"controls":{"status":1}
,"status":{"toolbar":1}
,"toolbar":{"determined":1}
,"determined":{"by":1}
,"by":{"relative":1}
,"relative":{"place":1}
,"place":{"record":1}
,"depending":{"find":1}
,"find":{"criteria":1}
,"criteria":{"sort":1}
,"sort":{"order":1}
,"order":{"return":1}
,"return":{"value":1}
,"uniquely":{"permanently":1}
,"permanently":{"identifies":1}
,"identifies":{"record":1}
,"table":{"use":1,"suppose":1}
,"use":{"get":1}
,"recordid":{"function":1}
,"function":{"returns":1}
,"fourth":{"record":1}
,"portal":{"records":1,"row":1}
,"records":{"current":1}
,"suppose":{"want":1}
,"want":{"display":1}
,"display":{"button":1}
,"button":{"portal":1,"row":1,"data":1,"active":1}
,"row":{"row":1,"active":1,"condition":1,"select":1}
,"active":{"portal":1,"record":1}
,"condition":{"occurs":1}
,"occurs":{"record\u2019s":1}
,"record\u2019s":{"position":1}
,"position":{"current":1}
,"hide":{"button":1,"object":1}
,"select":{"button":1}
,"data":{"data":1,"tab":1}
,"tab":{"inspector":1}
,"inspector":{"enter":1}
,"enter":{"formula":1}
,"formula":{"hide":1}
,"object":{"get":1}
,"recordnumber":{"=get":1}
,"=get":{"activerecordnumber":1}
,"apply":{"show":1}
,"show":{"button":1}
,"list":{"view":1}
,"view":{"creating":1}
,"creating":{"portals":1}
,"portals":{"master-detail":1}
,"master-detail":{"layouts":1}
,"layouts":{"hiding":1}
,"hiding":{"layout":1}
,"layout":{"objects":1}
,"objects":{"get":1}
}
;Search.control.loadWordPairs(pairs);
