var pairs =
{
"toring":{"sql":1}
,"sql":{"query":1,"script":1}
,"query":{"field":1,"text":1,"dynamically":1,"builder":1,"copy":1,"error":1,"each":1,"global":1,"executed":1}
,"field":{"store":1,"use":1,"create":1,"execute":1,"guarantee":1}
,"store":{"sql":1,"execute":1,"query":1}
,"text":{"field":1}
,"use":{"im":1,"sql":1,"get":1,"filemaker":1}
,"im":{"port":1}
,"port":{"records":1}
,"records":{"script":1}
,"script":{"step":1}
,"step":{"xecute":1,"type":1}
,"xecute":{"sql":1}
,"type":{"query":1}
,"create":{"query":1}
,"dynamically":{"calculation":1}
,"calculation":{"field":1}
,"builder":{"construct":1,"validates":1}
,"construct":{"query":1}
,"copy":{"paste":1}
,"paste":{"field":1}
,"execute":{"stored":1,"query":1}
,"stored":{"query":1}
,"error":{"checking":1,"string":1}
,"checking":{"performed":1}
,"performed":{"runtime":1}
,"runtime":{"use":1}
,"get":{"lasterror":1,"lastexternalerrordetail":1}
,"lasterror":{"function":1}
,"function":{"use":1,"return":1}
,"lastexternalerrordetail":{"function":1}
,"return":{"last":1}
,"last":{"readable":1}
,"readable":{"error":1}
,"string":{"generated":1}
,"generated":{"by":1}
,"by":{"odbc":1}
,"odbc":{"driver":1}
,"driver":{"sql":1}
,"validates":{"queries":1}
,"queries":{"use":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"store":1}
,"each":{"record":1}
,"record":{"database":1,"store":1}
,"database":{"file":1}
,"file":{"store":1}
,"global":{"field":1}
,"guarantee":{"query":1}
,"executed":{"record":1}
}
;Search.control.loadWordPairs(pairs);
