var pairs =
{
"render":{"file":1}
,"file":{"xml":1,"window":1,"target":1}
,"xml":{"stores":1,"representation":1,"if":1,"documenting":1,"format":1,"[window":1}
,"stores":{"field":1,"xml":1}
,"field":{"variable":1,"render":1}
,"variable":{"xml":1,"store":1,"doesn\u2019t":1}
,"representation":{"schema":1,"open":1}
,"schema":{"layouts":1}
,"layouts":{"scripts":1}
,"scripts":{"open":1,"stores":1}
,"open":{"file":1}
,"window":{"name":1}
,"name":{"window":1,"open":1,"inventory":1}
,"target":{"field":1,"table":1}
,"store":{"xml":1}
,"if":{"variable":1}
,"doesn\u2019t":{"exist":1}
,"exist":{"script":1}
,"script":{"step":1,"full":1}
,"step":{"creates":1,"choosing":1,"user":1}
,"creates":{"sing":1}
,"sing":{"variables":1}
,"variables":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"18.0":1,"advanced":1}
,"18.0":{"advanced":1}
,"advanced":{"script":1,"versions":1}
,"choosing":{"tools":1}
,"tools":{"menu":1}
,"menu":{"save":1}
,"save":{"copy":1}
,"copy":{"xml":1}
,"documenting":{"database":1}
,"database":{"schemas":1}
,"schemas":{"xml":1}
,"format":{"preview":1}
,"preview":{"gather":1}
,"gather":{"customer":1}
,"customer":{"feedback":1}
,"feedback":{"change":1}
,"change":{"significantly":1}
,"significantly":{"future":1}
,"future":{"filemaker":1}
,"versions":{"intended":1}
,"intended":{"use":1}
,"use":{"production":1}
,"production":{"systems":1}
,"systems":{"perform":1}
,"perform":{"script":1}
,"user":{"script":1}
,"full":{"access":1}
,"access":{"privileges":1}
,"privileges":{"creating":1}
,"creating":{"editing":1}
,"editing":{"scripts":1}
,"inventory":{"text":1,"target":1}
,"text":{"field":1}
,"[window":{"name":1}
,"table":{":xml":1}
,":xml":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
