var pairs =
{
"ormatting":{"fields":1}
,"fields":{"text":1,"by":1,"numbers":1,"format":1}
,"text":{"vertical":1,"entry":1,"objects":1,"layout":1,"object":1,"rotating":1,"hankaku":1,"zenkaku":1,"tool":1,"except":1,"columns":1,"rotated":1,"temporarily":1,"if":1,"rranging":1,"functions":1,"romanzenkaku":1,"kanazenkaku":1,"kanjinumeral":1}
,"vertical":{"writing":1,"text":1,"format":1,"columns":1,"ou":1}
,"writing":{"if":1,"format":1,"characters":1}
,"if":{"operating":1,"rotate":1}
,"operating":{"system":1}
,"system":{"configured":1}
,"configured":{"support":1}
,"support":{"japanese":1}
,"japanese":{"text":1}
,"entry":{"format":1}
,"format":{"field":1,"vertical":1,"choose":1,"characters":1,"menu":1,"formats":1,"fields":1}
,"field":{"objects":1,"rotate":1,"text":1,"object":1,"half-width":1,"browse":1,"function":1,"type":1,"format":1}
,"objects":{"text":1,"display":1,"set":1,"layout":1,"re-entering":1,"vertical":1}
,"display":{"japanese":1,"left-to-right":1,"screen":1,"vertically":1,"full-width":1}
,"characters":{"displayed":1,"field":1,"display":1,"displaying":1,"rotate":1,"full-width":1,"chinese":1,"rotating":1,"object":1,"hankaku":1,"zenkaku":1,"90":1,"displays":1,"function":1,"number":1}
,"displayed":{"read":1,"vertically":1}
,"read":{"top-to-bottom":1}
,"top-to-bottom":{"successive":1,"vertical":1}
,"successive":{"columns":1}
,"columns":{"displayed":1,"remain":1,"note":1,"display":1}
,"vertically":{"right-to-left":1,"choose":1}
,"right-to-left":{"two":1}
,"two":{"format":1}
,"layout":{"format":1,"each":1,"mode":1,"by":1,"print":1,"choose":1,"functions":1}
,"choose":{"usually":1,"format":1,"arrange":1,"file":1}
,"usually":{"depends":1}
,"depends":{"page":1}
,"page":{"orientation":1,"setup":1}
,"orientation":{"layout":1,"use":1,"sideways":1,"portrait":1}
,"each":{"text":1,"character":1}
,"object":{"field":1,"case":1,"rotated":1,"half-width":1,"hankaku":1,"zenkaku":1,"layout":1}
,"rotate":{"characters":1,"sideways":1,"address":1,"selected":1,"depending":1,"graphics":1}
,"case":{"each":1}
,"character":{"rotated":1,"object":1}
,"rotated":{"90":1,"rotate":1,"field":1,"text":1}
,"90":{"degrees":1}
,"degrees":{"counter-clockwise":1,"clockwise":1}
,"counter-clockwise":{"characters":1,"text":1,"choose":1}
,"left-to-right":{"columns":1}
,"remain":{"horizontal":1,"original":1}
,"horizontal":{"rotate":1}
,"clockwise":{"characters":1}
,"screen":{"vertical":1}
,"displaying":{"top-to-bottom":1}
,"note":{"alphabetic":1}
,"alphabetic":{"numeric":1,"characters":1}
,"numeric":{"half-width":1,"full-width":1,"numtojtext":1}
,"half-width":{"hankaku":1,"numbers":1,"characters":1,"original":1,"rotating":1,"ka":1}
,"hankaku":{"characters":1,"full-width":1}
,"sideways":{"alphabetic":1,"half-width":1,"all":1}
,"full-width":{"zenkaku":1,"characters":1,"original":1,"rotating":1,"text":1,"display":1}
,"zenkaku":{"characters":1,"half-width":1,"layout":1}
,"address":{"field":1}
,"numbers":{"street":1,"remain":1,"notes":1,"convert":1,"alphabetic":1,"chinese":1,"numeric":1,"full-width":1,"formats":1}
,"street":{"number":1}
,"number":{"sideways":1,"date":1}
,"original":{"orientation":1,"japanese":1}
,"use":{"functions":1}
,"functions":{"convert":1,"text":1,"field":1}
,"convert":{"alphabetic":1,"characters":1}
,"chinese":{"numbers":1}
,"notes":{"table":1}
,"table":{"formatting":1}
,"formatting":{"choices":1}
,"choices":{"original":1}
,"rotating":{"characters":1,"character":1}
,"mode":{"select":1,"print":1,"rotated":1,"text":1}
,"select":{"fields":1,"all":1,"text":1}
,"set":{"vertical":1}
,"ou":{"select":1}
,"all":{"text":1,"rotate":1}
,"by":{"clicking":1,"changing":1}
,"clicking":{"text":1}
,"tool":{"text":1,"status":1}
,"status":{"toolbar":1}
,"toolbar":{"choosing":1,"select":1}
,"choosing":{"edit":1}
,"edit":{"menu":1}
,"menu":{"select":1,"orientation":1,"rotate":1,"print":1}
,"except":{"alphabetic":1}
,"displays":{"rotated":1,"unrotated":1}
,"selected":{"field":1}
,"arrange":{"menu":1}
,"depending":{"want":1}
,"want":{"layout":1,"change":1}
,"print":{"want":1,"setup":1}
,"change":{"page":1}
,"file":{"menu":1}
,"setup":{"windows":1,"macos":1}
,"windows":{"page":1}
,"macos":{"change":1,"status":1}
,"portrait":{"landscape":1}
,"landscape":{"preview":1}
,"preview":{"mode":1}
,"browse":{"mode":1}
,"temporarily":{"displays":1}
,"unrotated":{"while":1}
,"while":{"you\u2019re":1}
,"you\u2019re":{"editing":1}
,"editing":{"text":1}
,"graphics":{"match":1}
,"match":{"vertical":1}
,"rranging":{"objects":1}
,"re-entering":{"data":1}
,"data":{"use":1}
,"function":{"define":1,"place":1,"conversion":1}
,"define":{"new":1}
,"new":{"calculation":1}
,"calculation":{"field":1}
,"place":{"layout":1}
,"type":{"function":1,"text":1}
,"conversion":{"type":1}
,"romanzenkaku":{"half-width":1}
,"kanazenkaku":{"half-width":1}
,"ka":{"takana":1}
,"takana":{"full-width":1}
,"kanjinumeral":{"half-width":1}
,"numtojtext":{"half-width":1}
,"date":{"time":1}
,"time":{"fields":1,"timestamp":1}
,"changing":{"field":1}
,"formats":{"fields":1,"date":1}
,"timestamp":{"fields":1}
}
;Search.control.loadWordPairs(pairs);
