var pairs =
{
"charting":{"delimited":1}
,"delimited":{"data":1}
,"data":{"filemaker":1,"entries":1,"value":1,"create":1,"stored":1,"edit":1,"source":1,"chart":1,"button":1,"values":1,"comparing":1,"measuring":1,"entered":1,"file":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"chart":1}
,"chart":{"multiple":1,"compares":1,"chart":1,"tool":1,"setup":1,"inspector":1,"labels":1,"x-series":1,"show":1,"create":1}
,"multiple":{"data":1}
,"entries":{"single":1}
,"single":{"field":1}
,"field":{"each":1,"separated":1,"button":1,"type":1,"named":1,"field":1,"label":1,"drag":1,"select":1,"choose":1,"name":1,"chart":1,"y-series":1,"corresponds":1,"order":1}
,"each":{"data":1,"country":1,"value":1,"return-delimited":1}
,"value":{"field":1,"15":1,"country":1,"member":1}
,"separated":{"by":1}
,"by":{"carriage-return":1,"country":1}
,"carriage-return":{"character":1}
,"character":{"carriage":1}
,"carriage":{"return-delimited":1}
,"return-delimited":{"data":1,"fields":1,"value":1}
,"create":{"new":1,"column":1,"field":1,"file":1}
,"new":{"file":1,"double-click":1,"field":1,"record":1}
,"file":{"ontaining":1,"menu":1,"worldwide":1,"hard":1,"browse":1,"choose":1,"define":1,"create":1}
,"ontaining":{"two":1}
,"two":{"return-delimited":1,"fields":1}
,"fields":{"country":1,"located":1,"tab":1,"contain":1,"add":1}
,"country":{"customer":1,"choose":1,"field":1,"name":1,"type":1,"list":1}
,"customer":{"count":1}
,"count":{"fields":1,"layout":1,"field":1,"list":1}
,"located":{"layout":1,"each":1}
,"layout":{"all":1,"created":1,"mode":1,"se":1,"exit":1,"save":1,"automatically":1,"saved":1,"layout":1,"bar":1,"part":1}
,"all":{"data":1}
,"stored":{"record":1}
,"record":{"create":1,"status":1,"delimited":1}
,"column":{"chart":1,"x-axis":1,"compare":1}
,"compares":{"number":1}
,"number":{"customers":1}
,"customers":{"located":1,"save":1,"by":1,"data":1,"each":1}
,"choose":{"file":1,"view":1,"layouts":1,"current":1,"column":1,"field":1,"country":1,"customer":1}
,"menu":{"create":1,"layout":1,"save":1}
,"double-click":{"blank":1}
,"blank":{"name":1}
,"name":{"file":1,"spain":1,"choose":1}
,"worldwide":{"customers":1}
,"save":{"save":1,"file":1,"layout":1,"eturn":1,"return":1}
,"hard":{"disk":1}
,"disk":{"file":1}
,"browse":{"mode":1}
,"mode":{"if":1,"fields":1,"select":1,"drag":1,"each":1}
,"if":{"manage":1,"want":1}
,"manage":{"database":1}
,"database":{"dialog":1}
,"dialog":{"box":1}
,"box":{"displayed":1,"appears":1}
,"displayed":{"th":1}
,"th":{"first":1}
,"first":{"table":1}
,"table":{"layout":1}
,"created":{"name":1,"two":1}
,"view":{"menu":1}
,"tab":{"new":1}
,"button":{"add":1,"choose":1}
,"add":{"new":1,"data":1}
,"type":{"ountry":1,"pressing":1,"customers":1,"choose":1,"countries":1,"number":1}
,"ountry":{"create":1}
,"named":{"customer":1}
,"se":{"lect":1}
,"lect":{"customer":1}
,"label":{"drag":1}
,"drag":{"inch":1,"bottom":1,"gray":1,"large":1}
,"inch":{"select":1}
,"select":{"country":1,"customer":1,"save":1}
,"bottom":{"handle":1,"andle":1}
,"handle":{"own":1}
,"own":{"ows":1}
,"ows":{"field":1}
,"andle":{"own":1}
,"layouts":{"menu":1}
,"exit":{"layout":1,"new":1}
,"eturn":{"browse":1}
,"automatically":{"if":1}
,"want":{"layout":1,"chart":1}
,"saved":{"exit":1}
,"status":{"toolbar":1}
,"toolbar":{"country":1,"body":1}
,"pressing":{"enter":1}
,"enter":{"return":1,"title":1}
,"return":{"fter":1,"browse":1}
,"fter":{"each":1}
,"spain":{"italy":1}
,"italy":{"japan":1}
,"japan":{"germany":1}
,"germany":{"usa":1}
,"usa":{"customer":1}
,"15":{"23":1}
,"23":{"10":1}
,"10":{"29":1}
,"29":{"created":1}
,"contain":{"return-delimited":1}
,"edit":{"layout":1}
,"bar":{"switch":1}
,"switch":{"layout":1}
,"gray":{"bo":1}
,"bo":{"dy":1}
,"dy":{"part":1}
,"part":{"boundary":1,"drag":1}
,"boundary":{"chart":1}
,"tool":{"chart":1,"status":1}
,"body":{"layout":1}
,"large":{"rectangle":1}
,"rectangle":{"want":1}
,"setup":{"dialog":1}
,"appears":{"chart":1}
,"inspector":{"data":1,"enter":1}
,"source":{"choose":1}
,"current":{"record":1}
,"title":{"type":1}
,"x-axis":{"horizontal":1}
,"horizontal":{"title":1}
,"countries":{"data":1}
,"list":{"data":1,"columns":1}
,"values":{"country":1,"customer":1}
,"labels":{"columns":1}
,"columns":{"chart":1}
,"x-series":{"data":1}
,"comparing":{"y-axis":1}
,"y-axis":{"vertical":1}
,"vertical":{"title":1}
,"show":{"data":1}
,"y-series":{"data":1}
,"measuring":{"choose":1}
,"corresponds":{"return-delimited":1}
,"member":{"count":1}
,"order":{"data":1}
,"entered":{"chart":1}
,"define":{"format":1}
,"format":{"fields":1}
,"compare":{"number":1}
}
;Search.control.loadWordPairs(pairs);
