var pairs =
{
"get":{"applicationlan":1,"applicationlanguage":1,"application":1,"current":1,"lanugage":1,"system":1}
,"applicationlan":{"guage":1}
,"guage":{"returns":1}
,"returns":{"text":1,"client\u2019s":1,"web":1,"english":1}
,"text":{"representing":1,"filemaker":1,"returned":1}
,"representing":{"current":1}
,"current":{"application":1,"language":1,"lanugage":1}
,"application":{"language":1,"lanugage":1}
,"language":{"get":1,"hosted":1,"filemaker":1,"returns":1,"english":1}
,"applicationlanguage":{"none":1,"returns":1,"get":1}
,"none":{"text":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"7.0":1,"advanced":1}
,"7.0":{"text":1}
,"returned":{"by":1}
,"by":{"function":1}
,"function":{"english":1}
,"english":{"language":1,"french":1,"current":1,"get":1}
,"hosted":{"databases":1}
,"databases":{"get":1}
,"client\u2019s":{"current":1}
,"advanced":{"supports":1}
,"supports":{"english":1}
,"french":{"italian":1}
,"italian":{"german":1}
,"german":{"swedish":1}
,"swedish":{"spanish":1}
,"spanish":{"dutch":1}
,"dutch":{"japanese":1}
,"japanese":{"simplified":1}
,"simplified":{"chinese":1}
,"chinese":{"brazilian":1}
,"brazilian":{"portuguese":1}
,"portuguese":{"korean":1}
,"korean":{"filemaker":1}
,"webdirect":{"get":1}
,"web":{"browser\u2019s":1}
,"browser\u2019s":{"current":1}
,"lanugage":{"get":1}
,"system":{"lanugage":1}
}
;Search.control.loadWordPairs(pairs);
