var pairs =
{
"send":{"mail":1,"via":1,"tachment":1,"message":1,"attachment":1}
,"mail":{"email":1,"sends":1,"transfer":1,"via":1,"script":1,"[send":1}
,"email":{"message":1,"application":1,"client":1,"data":1,"addresses":1,"address":1,"clients":1,"type":1,"if":1,"placed":1,"application\u2019s":1,"hrough":1,"messages":1,"isplays":1,"ia":1,"ontains":1,"plain":1,"field":1}
,"message":{"email":1,"by":1,"all":1,"each":1,"multiple":1,"text":1,"calculation":1,"left":1,"manually":1,"send":1,"dear":1}
,"application":{"via":1,"applications":1,"supported":1,"yo":1,"installed":1}
,"via":{"smtp":1,"specifies":1,"email":1,"e-mail":1}
,"smtp":{"send":1,"server":1,"options":1,"simple":1,"if":1}
,"specifies":{"message":1,"filemaker":1}
,"by":{"email":1,"user":1}
,"client":{"smtp":1,"filemaker":1,"font":1,"set":1,"dialog":1}
,"server":{"if":1,"smtp":1,"multiple":1,"encrypted":1,"unavailable":1}
,"if":{"choose":1,"multiple":1,"set":1,"dialog":1,"attach":1,"email":1,"certificate":1,"server":1,"had":1}
,"choose":{"smtp":1,"email":1,"field":1,"calculation":1,"send":1,"connect":1}
,"options":{"dialog":1,"ne":1,"2000":1}
,"dialog":{"box":1,"specifies":1,"composed":1,"option":1,"customers":1,"invoice.pdf":1}
,"box":{"appears":1}
,"appears":{"se":1}
,"se":{"nt":1,"creating":1,"ave":1}
,"nt":{"ing":1}
,"ing":{"editing":1}
,"editing":{"smtp":1}
,"ne":{"email":1}
,"data":{"current":1,"api":1,"send":1,"automating":1}
,"current":{"record":1,"found":1,"file":1}
,"record":{"sends":1,"found":1,"prompting":1,"pdf":1,"go":1,"create":1,"data":1}
,"sends":{"message":1,"intranet":1,"email":1,"prewritten":1}
,"all":{"recipients":1,"values":1,"files":1}
,"recipients":{"multiple":1,"if":1,"option":1}
,"multiple":{"emails":1,"recipients":1,"email":1}
,"emails":{"each":1,"pdf":1}
,"each":{"record":1,"address":1,"recipient\u0027s":1}
,"found":{"set":1}
,"set":{"sends":1,"all":1,"filemaker":1,"use":1,"address":1,"dialog":1,"error":1,"script":1,"option":1}
,"filemaker":{"pro":1,"data":1,"webdirect":1,"go":1}
,"pro":{"advanced":1,"6.0":1}
,"advanced":{"ncounters":1,"handle":1,"technical":1,"sends":1,"verifies":1}
,"ncounters":{"error":1}
,"error":{"while":1,"capture":1}
,"while":{"emailing":1}
,"emailing":{"records":1}
,"records":{"remaining":1,"stores":1,"pdf":1,"excel":1}
,"remaining":{"records":1}
,"stores":{"address":1}
,"address":{"es":1,"semicolon":1,"message":1,"carriage":1,"email":1}
,"es":{"recipient":1,"carbon":1,"blind":1}
,"recipient":{"cc":1,"bcc":1}
,"cc":{"stores":1,"bcc":1}
,"carbon":{"copy":1}
,"copy":{"recipient":1}
,"bcc":{"stores":1,"windows":1,"entries":1,"separate":1,"subject":1}
,"blind":{"carbon":1}
,"windows":{"choose":1}
,"addresses":{"enter":1,"separate":1,"choose":1,"select":1,"across":1,"cc":1}
,"enter":{"email":1}
,"separate":{"each":1}
,"semicolon":{"carriage":1,"email":1}
,"carriage":{"return":1}
,"return":{"character":1,"semicolon":1}
,"character":{"choose":1}
,"field":{"name":1,"email":1,"calculation":1,"value":1,"current":1}
,"name":{"field":1,"calculation":1}
,"calculation":{"calculation":1,"generates":1,"result":1,"option":1,"insert":1}
,"generates":{"email":1}
,"select":{"collect":1}
,"collect":{"addresses":1}
,"across":{"found":1}
,"use":{"all":1,"field":1,"email":1}
,"values":{"field":1}
,"result":{"current":1}
,"option":{"if":1,"value":1,"web":1,"ilemaker":1,"sending":1,"email":1,"edit":1,"selected":1}
,"file":{"use":1,"ttach":1,"fi":1,"paths":1,"locate":1,"file":1,"folder":1,"option":1,"required":1,"data":1}
,"value":{"cc":1,"create":1}
,"entries":{"note":1}
,"note":{"if":1}
,"recipient\u0027s":{"email":1}
,"clients":{"accept":1}
,"accept":{"separators":1}
,"separators":{"comma":1}
,"comma":{"ubject":1}
,"ubject":{"title":1}
,"title":{"email":1}
,"text":{"email":1,"use":1,"file":1,"edit":1}
,"type":{"message":1}
,"create":{"message":1,"pdf":1,"folders":1}
,"insert":{"text":1}
,"ttach":{"file":1}
,"fi":{"le":1}
,"le":{"send":1}
,"tachment":{"essage":1}
,"essage":{"se":1}
,"creating":{"file":1}
,"paths":{"searching":1,"dialog":1,"server-side":1}
,"searching":{"list":1}
,"list":{"potential":1,"find":1}
,"potential":{"files":1}
,"files":{"choosing":1,"list":1,"email":1}
,"choosing":{"first":1}
,"first":{"file":1}
,"locate":{"step":1}
,"step":{"attaches":1,"sends":1,"control":1,"if":1,"set":1,"behaves":1}
,"attaches":{"all":1}
,"find":{"paths":1,"sends":1,"[restore]":1}
,"handle":{"composed":1}
,"composed":{"email":1,"message":1}
,"left":{"open":1,"drafts":1}
,"open":{"review":1}
,"review":{"email":1}
,"applications":{"new":1}
,"new":{"message":1}
,"drafts":{"folder":1}
,"folder":{"if":1,"server-side":1}
,"placed":{"email":1}
,"application\u2019s":{"outbox":1}
,"outbox":{"ready":1}
,"ready":{"filemaker":1}
,"6.0":{"earlier":1}
,"earlier":{"send":1}
,"intranet":{"internet":1}
,"internet":{"email":1}
,"hrough":{"email":1}
,"simple":{"mail":1}
,"transfer":{"protocol":1}
,"protocol":{"sending":1}
,"sending":{"mail":1,"email":1}
,"supported":{"server-side":1,"email":1}
,"server-side":{"scripts":1}
,"scripts":{"filemaker":1,"support":1,"llowed":1}
,"api":{"ustom":1,"\u2019t":1}
,"ustom":{"web":1}
,"web":{"publishing":1,"users":1,"browser":1}
,"publishing":{"server-side":1,"filemaker":1}
,"support":{"sending":1,"attach":1}
,"attach":{"file":1,"saved":1}
,"llowed":{"access":1}
,"access":{"paths":1}
,"webdirect":{"doesn\u2019t":1,"limit":1,"send":1,"script":1}
,"doesn\u2019t":{"support":1,"upport":1}
,"users":{"manually":1,"choose":1}
,"manually":{"attach":1,"script":1}
,"saved":{"exported":1}
,"exported":{"files":1}
,"messages":{"ustom":1,"based":1}
,"\u2019t":{"support":1}
,"ilemaker":{"webdirect":1}
,"upport":{"dialog":1}
,"go":{"doesn\u2019t":1,"layout":1}
,"isplays":{"device":1}
,"device":{"send":1}
,"script":{"step":1}
,"ia":{"email":1}
,"limit":{"cc":1}
,"subject":{"body":1,"invoices":1}
,"body":{"options":1}
,"2000":{"characters":1}
,"characters":{"total":1,"web":1}
,"total":{"if":1}
,"ontains":{"2000":1}
,"browser":{"allow":1}
,"allow":{"filemaker":1}
,"yo":{"supported":1}
,"installed":{"configured":1}
,"configured":{"properly":1}
,"properly":{"computer":1}
,"computer":{"filemaker":1}
,"technical":{"specifications":1}
,"specifications":{"indows":1}
,"indows":{"[mail]":1}
,"[mail]":{"win.ini":1}
,"win.ini":{"file":1}
,"required":{"ou":1}
,"ou":{"create":1}
,"pdf":{"excel":1,"ave":1,"emails":1,"address":1,"[restore":1}
,"excel":{"file":1,"send":1}
,"attachment":{"se":1}
,"ave":{"records":1}
,"control":{"font\u2019s":1}
,"font\u2019s":{"appearance":1}
,"appearance":{"use":1}
,"font":{"filemaker":1}
,"plain":{"text":1}
,"edit":{"message\u0027s":1,"message":1}
,"message\u0027s":{"contents":1}
,"contents":{"formatting":1}
,"formatting":{"choose":1}
,"verifies":{"ssl":1}
,"ssl":{"certificate":1}
,"certificate":{"smtp":1,"verified":1}
,"encrypted":{"connection":1}
,"connection":{"if":1}
,"verified":{"users":1,"set":1,"server-side":1}
,"connect":{"cancel":1}
,"cancel":{"skip":1}
,"skip":{"script":1}
,"capture":{"script":1}
,"behaves":{"if":1}
,"unavailable":{"if":1}
,"had":{"canceled":1}
,"canceled":{"by":1}
,"user":{"customers":1,"go":1}
,"customers":{"layout":1,"\u0022]":1,":email":1}
,"layout":{"performs":1,"[\u0022":1,"[original":1}
,"performs":{"find":1}
,"prewritten":{"email":1}
,"prompting":{"user":1}
,"[\u0022":{"customers":1,"print":1}
,"\u0022]":{"perform":1,"collect":1,"save":1,"go":1}
,"perform":{"find":1}
,"[restore]":{"send":1}
,"[send":{"via":1}
,"e-mail":{"client":1}
,":email":{"subject":1}
,"invoices":{":summary":1,"\u0022]":1}
,":summary":{"message":1}
,"dear":{"customer":1}
,"customer":{"business":1}
,"business":{"\u0022]":1,"invoice":1}
,"selected":{"saves":1}
,"saves":{"current":1}
,"print":{"invoices":1}
,"save":{"records":1}
,"[restore":{"dialog":1}
,"invoice.pdf":{"current":1,"\u0022]":1}
,"folders":{"off]":1}
,"off]":{"send":1}
,"invoice":{"attached":1}
,"attached":{"invoice.pdf":1}
,"[original":{"layout]":1}
,"layout]":{"sending":1}
,"based":{"record":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
