var pairs =
{
"keyboard":{"shortcuts":1,"space":1}
,"shortcuts":{"windows":1,"perform":1,"creating":1,"navigate":1,"move":1,"moving":1,"all":1,"enter":1,"window":1,"insert":1}
,"windows":{"use":1,"ctrl":1,"press":1,"shift":1,"horizontally":1,"navigation":1}
,"use":{"keyboard":1,"hese":1,"account":1,"eyboard":1}
,"perform":{"tasks":1,"first":1}
,"tasks":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"note":1,"alt":1,"help":1,"saves":1,"odes":1}
,"note":{"create":1,"database":1,"select":1}
,"create":{"own":1,"record":1}
,"own":{"keyboard":1}
,"creating":{"editing":1}
,"editing":{"custom":1}
,"custom":{"menu":1}
,"menu":{"item":1,"f2":1,"ctrl":1}
,"item":{"use":1,"list":1}
,"hese":{"keyboard":1}
,"navigate":{"cancel":1}
,"cancel":{"operation":1,"running":1}
,"operation":{"display":1,"dialog":1}
,"display":{"database":1,"keyboard":1}
,"database":{"ile":1,"dialog":1,"designer":1}
,"ile":{"press":1}
,"press":{"cancel":1,"next":1,"cascade":1,"current":1,"text":1,"replace":1,"ctrl":1}
,"dialog":{"box":1,"boxes":1}
,"box":{"esc":1,"ctrl":1,"includes":1,"press":1}
,"esc":{"cancel":1,"selected":1,"close":1}
,"running":{"script":1}
,"script":{"esc":1,"workspace":1}
,"selected":{"button":1,"right":1,"left":1,"ctrl":1,"item":1}
,"button":{"popover":1,"layout":1,"tab":1}
,"popover":{"button":1}
,"layout":{"ith":1,"pop-up":1,"ctrl":1,"object":1,"page":1,"mode":1}
,"ith":{"keyboard":1}
,"space":{"bar":1}
,"bar":{"close":1}
,"close":{"dialog":1,"file":1,"all":1,"window":1}
,"boxes":{"confirmation":1}
,"confirmation":{"discard":1,"ctrl":1}
,"discard":{"shift":1}
,"shift":{"sc":1,"pen":1,"open":1,"perform":1,"duplicate":1,"tab":1,"pgdn":1,"pgup":1,"f5":1,"f4":1,"f3":1,"index":1,"quotation":1,"press":1,"select":1}
,"sc":{"close":1}
,"file":{"window":1,"shift":1,"open":1,"dialog":1}
,"window":{"ctrl":1,"full":1,"display":1}
,"ctrl":{"ctrl":1,"f4":1,"alt":1,"open":1,"shift":1,"print":1,"undo":1,"create":1,"delete":1,"save":1,"use":1,"arrow":1,"up":1,"pgup":1,"pgdn":1,"-(":1,"current":1,"last":1,"apostrophe":1,"paste":1,"text":1,"=select":1,"select":1,"drag":1}
,"f4":{"close":1,"ctrl":1,"resize":1,"zoom":1}
,"all":{"files":1,"filemaker":1,"objects":1}
,"files":{"windows":1}
,"alt":{"exit":1,"f4":1,"use":1,"save":1,"scroll":1,"tile":1}
,"exit":{"quit":1}
,"quit":{"filemaker":1}
,"open":{"filemaker":1,"apps":1,"file":1,"host":1,"open":1,"manage":1,"find\u002Freplace":1,"layout":1,"script":1}
,"help":{"f1":1}
,"f1":{"open":1}
,"apps":{"window":1}
,"account":{"name":1}
,"name":{"password":1,"ctrl":1}
,"password":{"open":1}
,"pen":{"file":1}
,"host":{"dialog":1}
,"manage":{"database":1,"layouts":1}
,"find\u002Freplace":{"dialog":1}
,"layouts":{"dialog":1,"note":1}
,"pop-up":{"menu":1}
,"f2":{"print":1}
,"print":{"ctrl":1,"print":1,"dialog":1}
,"save":{"by":1,"layout":1}
,"by":{"default":1}
,"default":{"filemaker":1}
,"saves":{"record":1}
,"record":{"data":1,"find":1,"request":1,"confirmation":1,"move":1}
,"data":{"automatically":1}
,"automatically":{"sort":1}
,"sort":{"ctrl":1}
,"undo":{"last":1}
,"last":{"command":1,"visited":1,"record":1}
,"command":{"ctrl":1}
,"workspace":{"ctrl":1}
,"first":{"scripts":1}
,"scripts":{"listed":1,"menu":1}
,"listed":{"scripts":1}
,"find":{"request":1,"requests":1}
,"request":{"ayout":1,"layout":1}
,"ayout":{"ctrl":1}
,"delete":{"record":1}
,"duplicate":{"record":1}
,"object":{"ctrl":1,"field":1,"drag":1,"selected":1}
,"move":{"fields":1,"press":1,"items":1,"next":1,"selected":1}
,"fields":{"records":1,"co":1,"move":1,"elect":1}
,"records":{"find":1}
,"requests":{"layouts":1}
,"designer":{"changed":1,"setting":1}
,"changed":{"keyboard":1}
,"moving":{"fields":1}
,"co":{"nsult":1}
,"nsult":{"database":1}
,"setting":{"eys":1}
,"eys":{"moving":1}
,"next":{"object":1,"record":1,"tab":1,"field":1}
,"field":{"button":1,"ctrl":1}
,"tab":{"tab":1,"previous":1,"shift":1,"next":1,"wh":1,"selected":1}
,"previous":{"object":1,"record":1,"tab":1,"size":1}
,"page":{"ctrl":1}
,"arrow":{"shift":1,"previous":1,"use":1,"pointer":1,"arrow":1,"move":1,"ctrl":1,"eneral":1}
,"pgdn":{"previous":1,"scroll":1,"show":1}
,"up":{"arrow":1,"pgup":1}
,"pgup":{"next":1,"scroll":1}
,"wh":{"en":1}
,"en":{"tab":1}
,"right":{"arrow":1,"ctrl":1}
,"left":{"arrow":1,"ctrl":1}
,"odes":{"scroll":1}
,"scroll":{"ocument":1,"document":1}
,"ocument":{"arrange":1}
,"arrange":{"windows":1,"document":1}
,"cascade":{"document":1}
,"document":{"windows":1,"pgdn":1,"up":1,"left":1,"right":1,"larger":1,"shift":1}
,"f5":{"close":1}
,"resize":{"window":1}
,"full":{"screen":1}
,"screen":{"previous":1}
,"size":{"ctrl":1}
,"show":{"ide":1}
,"ide":{"status":1}
,"status":{"toolbar":1}
,"toolbar":{"ctrl":1}
,"tile":{"arrange":1}
,"horizontally":{"shift":1}
,"zoom":{"document":1}
,"larger":{"f3":1}
,"f3":{"zoom":1,"use":1}
,"eyboard":{"shortcuts":1}
,"enter":{"replace":1}
,"replace":{"alues":1,"field\u0027s":1}
,"alues":{"fields":1}
,"elect":{"objects":1}
,"objects":{"nd":1,"layout":1,"shift-click":1,"note":1,"enclosed":1,"type":1,"keyboard":1}
,"nd":{"move":1}
,"items":{"ist":1,"list":1}
,"ist":{"insert":1}
,"insert":{"press":1,"paste":1}
,"current":{"date":1,"time":1,"user":1}
,"date":{"ctrl":1,"timestamp":1}
,"-(":{"hyphen":1}
,"hyphen":{"current":1}
,"time":{"ctrl":1,"date":1}
,"timestamp":{"field":1}
,"user":{"name":1}
,"index":{"ctrl":1}
,"visited":{"ecord":1}
,"ecord":{"ctrl":1}
,"apostrophe":{"last":1}
,"quotation":{"merge":1}
,"merge":{"field":1}
,"paste":{"press":1,"select":1}
,"text":{"clipboard":1,"styles":1}
,"clipboard":{"ctrl":1}
,"styles":{"ctrl":1}
,"field\u0027s":{"value":1}
,"value":{"ctrl":1}
,"=select":{"all":1}
,"mode":{"ctrl":1}
,"select":{"multiple":1,"objects":1,"items":1,"values":1}
,"multiple":{"objects":1}
,"shift-click":{"each":1}
,"each":{"object":1}
,"drag":{"arrow":1,"select":1}
,"pointer":{"box":1}
,"includes":{"objects":1}
,"enclosed":{"selection":1}
,"selection":{"box":1}
,"type":{"object":1}
,"list":{"up":1,"ctrl":1}
,"eneral":{"keyboard":1}
,"navigation":{"keyboard":1}
,"values":{"objects":1}
}
;Search.control.loadWordPairs(pairs);
