var pairs =
{
"filemaker":{"pro":1}
,"pro":{"format":1,"advanced":1,"ile":1,"11":1,"ormats":1}
,"format":{"import":1,"fmp12":1,"first":1,"choose":1}
,"import":{"export":1,"data":1,"process":1,"repeat":1,"import":1,"related":1,"portion":1,"finding":1,"foreground":1,"records":1,"filemaker":1}
,"export":{"files":1,"data":1,"export":1,"records":1,"fields":1,"creates":1,"portion":1,"global":1}
,"files":{"filemaker":1,"importing":1}
,"fmp12":{"import":1}
,"data":{"filemaker":1,"table":1,"single":1,"import":1,"related":1,"export":1,"imported":1,"exported":1,"layouts":1,"open":1,"saving":1}
,"advanced":{"file":1,"ile":1,"determines":1,"mports":1,"filemaker":1,"exports":1}
,"file":{"import":1,"table":1,"if":1,"want":1,"perform":1,"open":1,"displaying":1,"current":1,"created":1,"export":1,"rge":1,"single":1,"each":1,"note":1,"data":1,"exporting":1}
,"table":{"source":1,"target":1,"time":1,"file":1,"want":1,"import":1,"you\u2019re":1,"exported":1}
,"source":{"file":1,"filemaker":1,"table":1}
,"target":{"file":1}
,"if":{"source":1,"import":1,"tables":1,"change":1}
,"ile":{"multiple":1,"open":1,"reated":1,"new":1}
,"multiple":{"tables":1}
,"tables":{"import":1,"related":1,"data":1}
,"single":{"table":1,"standard":1}
,"time":{"during":1,"if":1}
,"during":{"import":1}
,"process":{"choose":1,"each":1}
,"choose":{"table":1,"applications":1}
,"want":{"import":1,"copy":1,"removing":1}
,"repeat":{"import":1}
,"each":{"table":1,"exported":1}
,"related":{"data":1,"table":1,"source":1,"tables":1}
,"portion":{"records":1}
,"records":{"filemaker":1,"want":1,"closed":1,"found":1,"single":1,"source":1}
,"open":{"file":1,"copied":1}
,"perform":{"find":1}
,"find":{"found":1,"first":1}
,"found":{"set":1}
,"set":{"current":1,"import":1,"exported":1}
,"current":{"window":1,"format":1}
,"window":{"records":1,"file":1}
,"finding":{"records":1}
,"determines":{"found":1}
,"foreground":{"window":1}
,"closed":{"file":1}
,"displaying":{"windows":1}
,"windows":{"filemaker":1}
,"mports":{"all":1}
,"all":{"records":1}
,"reated":{"previous":1}
,"previous":{"version":1}
,"version":{"convert":1}
,"convert":{"file":1}
,"first":{"converting":1,"records":1}
,"converting":{"files":1}
,"11":{"advanced":1,"earlier":1}
,"earlier":{"export":1}
,"new":{"filemaker":1,"file":1}
,"created":{"data":1}
,"you\u2019re":{"exporting":1}
,"exporting":{"export":1,"data":1,"filemaker":1}
,"fields":{"related":1,"export":1,"exported":1}
,"creates":{"single":1}
,"exported":{"file":1,"finding":1,"data":1,"global":1,"record":1}
,"exports":{"field":1}
,"field":{"names":1,"types":1,"non-global":1,"repeats":1,"value":1,"global":1,"exported":1}
,"names":{"field":1,"application":1,"importing":1}
,"types":{"exported":1}
,"rge":{"filemaker":1}
,"ormats":{"include":1}
,"include":{"field":1}
,"application":{"data":1}
,"imported":{"support":1}
,"support":{"format":1}
,"applications":{"strip":1}
,"strip":{"field":1}
,"importing":{"exported":1,"filemaker":1}
,"standard":{"fo":1}
,"fo":{"rm":1}
,"rm":{"layout":1}
,"layout":{"global":1}
,"global":{"fields":1,"field":1}
,"non-global":{"field":1}
,"repeats":{"global":1}
,"value":{"each":1}
,"record":{"if":1}
,"change":{"field":1}
,"note":{"create":1}
,"create":{"new":1}
,"layouts":{"scripts":1}
,"scripts":{"elements":1}
,"elements":{"source":1}
,"copy":{"file":1}
,"copied":{"file":1}
,"removing":{"data":1}
,"saving":{"copying":1}
,"copying":{"files":1}
}
;Search.control.loadWordPairs(pairs);
