var pairs =
{
"get":{"statu":1,"statusareastate":1,"status":1,"toolbar":1}
,"statu":{"sareastate":1}
,"sareastate":{"returns":1}
,"returns":{"number":1,"zero":1,"current":1}
,"number":{"representing":1,"filemaker":1}
,"representing":{"current":1}
,"current":{"status":1}
,"status":{"toolbar":1,"state":1}
,"toolbar":{"state":1,"hidden":1,"visible":1}
,"state":{"get":1}
,"statusareastate":{"none":1,"get":1}
,"none":{"number":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"returns":1}
,"zero":{"if":1}
,"if":{"status":1,"multiple":1}
,"hidden":{"if":1,"locked":1}
,"visible":{"if":1,"locked":1,"get":1}
,"locked":{"if":1}
,"multiple":{"windows":1}
,"windows":{"open":1}
,"open":{"currently":1}
,"currently":{"active":1}
,"active":{"file":1,"window":1}
,"file":{"returned":1}
,"returned":{"active":1}
,"window":{"returns":1}
}
;Search.control.loadWordPairs(pairs);
