var pairs =
{
"enter":{"browse":1,"data":1,"preview":1}
,"browse":{"mode":1}
,"mode":{"witches":1,"pause":1,"prints":1,"go":1,"[pause":1}
,"witches":{"browse":1}
,"pause":{"temporarily":1}
,"temporarily":{"stops":1}
,"stops":{"script":1}
,"script":{"allow":1}
,"allow":{"users":1}
,"users":{"enter":1}
,"data":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1,"advanced":1}
,"6.0":{"earlier":1}
,"earlier":{"print":1}
,"print":{"invoices":1,"[with":1}
,"invoices":{"layout":1,"\u0022]":1}
,"layout":{"enters":1,"[\u0022":1}
,"enters":{"preview":1,"browse":1}
,"preview":{"mode":1}
,"prints":{"enters":1}
,"go":{"layout":1}
,"[\u0022":{"print":1}
,"\u0022]":{"enter":1}
,"[pause":{"off]":1}
,"off]":{"print":1,"enter":1,"bout":1}
,"[with":{"dialog":1}
,"dialog":{"off]":1}
,"bout":{"filemaker":1}
,"advanced":{"modes":1}
,"modes":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
