var pairs =
{
"substitute":{"returns":1,"text":1,"conditions":1,"description":1}
,"returns":{"text":1}
,"text":{"string":1,"replaced":1,"searchstring":1,"-any":1,"expression":1,"field":1,"filemaker":1,"[search1":1,"[\u0022":1}
,"string":{"occurrence":1}
,"occurrence":{"searchstring":1,"acronym":1}
,"searchstring":{"text":1,"replacestring":1,"-any":1}
,"replaced":{"by":1}
,"by":{"replacestring":1,"subsequent":1}
,"replacestring":{"substitute":1,"text":1,"-any":1,"parameters":1}
,"-any":{"text":1}
,"expression":{"text":1}
,"field":{"searchstring":1,"replacestring":1,"text":1,"phrase":1}
,"filemaker":{"pro":1,"supports":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"function":1}
,"function":{"case":1,"multiple":1}
,"case":{"sensitive":1}
,"sensitive":{"compare":1}
,"compare":{"replace":1}
,"replace":{"function":1}
,"multiple":{"substitutions":1}
,"substitutions":{"allowed":1,"performed":1,"filemaker":1}
,"allowed":{"enclose":1}
,"enclose":{"each":1}
,"each":{"pair":1}
,"pair":{"searchstring":1}
,"parameters":{"brackets":1}
,"brackets":{"[]":1}
,"[]":{"separate":1}
,"separate":{"semicolons":1}
,"semicolons":{"substitutions":1}
,"performed":{"order":1}
,"order":{"substitution":1}
,"substitution":{"further":1}
,"further":{"modified":1}
,"modified":{"by":1}
,"subsequent":{"substitutions":1}
,"supports":{"up":1}
,"up":{"999":1}
,"999":{"nested":1}
,"nested":{"substitute":1}
,"conditions":{"substitute":1}
,"[search1":{"replace1]":1}
,"replace1]":{"[search2":1}
,"[search2":{"replace2]":1}
,"replace2]":{"[searchn":1}
,"[searchn":{"replacen]":1}
,"replacen]":{"substitute":1}
,"description":{"wysiwyg":1,"field":1}
,"wysiwyg":{"get":1,"description":1}
,"get":{"replaces":1,"substitute":1}
,"replaces":{"occurrence":1,"lowercase":1}
,"acronym":{"wysiwyg":1}
,"phrase":{"get":1}
,"[\u0022":{"\u0022]":1}
,"\u0022]":{"[\u0022":1,"replaces":1}
}
;Search.control.loadWordPairs(pairs);
