var pairs =
{
"pie":{"charts":1,"category":1,"slice":1,"if":1,"chart":1}
,"charts":{"get":1,"creating":1,"layout":1,"finish":1}
,"get":{"started":1}
,"started":{"creating":1}
,"creating":{"chart":1,"quick":1,"editing":1}
,"chart":{"creating":1,"aking":1,"chart":1,"setup":1,"summary":1,"inspector":1,"select":1,"it\u2019s":1,"display":1,"print":1}
,"quick":{"charts":1,"chart":1}
,"editing":{"charts":1}
,"layout":{"mode":1,"quick":1}
,"mode":{"find":1,"charts":1,"set":1}
,"find":{"records":1,"request":1}
,"records":{"want":1,"data":1}
,"want":{"chart":1}
,"aking":{"find":1}
,"request":{"if":1}
,"if":{"charting":1,"you\u2019re":1}
,"charting":{"delimited":1}
,"delimited":{"data":1}
,"data":{"stored":1,"related":1,"source":1,"comparing":1,"button":1,"series":1,"measuring":1,"summary":1,"points":1,"values":1,"select":1,"data":1,"type":1,"format":1,"decimal":1}
,"stored":{"single":1,"database":1}
,"single":{"record":1}
,"record":{"data":1}
,"related":{"records":1}
,"source":{"settings":1,"chart":1}
,"settings":{"pecifying":1}
,"pecifying":{"data":1}
,"setup":{"dialog":1}
,"dialog":{"box":1}
,"box":{"type":1,"data":1}
,"type":{"choose":1,"select":1,"slice":1}
,"choose":{"pie":1,"field":1,"data":1,"value":1,"position":1}
,"category":{"labels":1,"label":1}
,"labels":{"button":1,"each":1}
,"button":{"choose":1,"data":1}
,"field":{"name":1,"type":1}
,"name":{"calculation":1}
,"calculation":{"complete":1}
,"complete":{"dialog":1}
,"comparing":{"company":1}
,"company":{"names":1}
,"names":{"determines":1}
,"determines":{"labels":1,"width":1}
,"each":{"slice":1}
,"slice":{"pie":1,"data":1,"represents":1}
,"series":{"data":1}
,"measuring":{"annual":1}
,"annual":{"sales":1}
,"sales":{"determines":1}
,"width":{"each":1}
,"you\u2019re":{"creating":1}
,"summary":{"data":1,"menu":1,"type":1}
,"menu":{"chart":1}
,"inspector":{"select":1,"changing":1}
,"select":{"summary":1,"show":1,"options":1,"percentages":1,"actual":1,"use":1}
,"show":{"legend":1,"values":1}
,"legend":{"display":1,"chart":1,"appearance":1}
,"display":{"legend":1,"category":1,"percentage":1,"data":1,"number":1,"slice":1}
,"options":{"chart":1}
,"it\u2019s":{"label":1}
,"label":{"all":1,"values":1}
,"all":{"data":1}
,"points":{"chart":1}
,"values":{"select":1,"chart":1,"slice":1,"field":1,"stored":1}
,"percentage":{"total":1,"currency":1}
,"total":{"each":1}
,"represents":{"select":1}
,"percentages":{"number":1,"enter":1}
,"number":{"decimal":1,"fixed":1,"decimals":1,"data":1}
,"decimal":{"percentages":1,"percentage":1,"digits":1,"thousands":1,"enter":1,"currency":1}
,"enter":{"number":1,"positive":1,"character":1,"custom":1}
,"fixed":{"number":1}
,"decimals":{"display":1,"separators":1}
,"actual":{"values":1}
,"format":{"characteristics":1,"choose":1}
,"characteristics":{"display":1}
,"currency":{"notes":1,"format":1,"notation":1}
,"notes":{"custom":1}
,"custom":{"decimals":1,"decimal":1,"character":1}
,"separators":{"ascii":1}
,"ascii":{"printable":1}
,"printable":{"characters":1}
,"characters":{"tilde":1}
,"tilde":{"character":1}
,"character":{"allowed":1,"decimal":1,"select":1,"include":1,"notation":1,"change":1}
,"allowed":{"decimal":1}
,"digits":{"zero":1}
,"zero":{"99":1}
,"99":{"enter":1}
,"positive":{"number":1}
,"database":{"decimal":1}
,"value":{"custom":1}
,"thousands":{"separator":1}
,"separator":{"character":1,"enter":1}
,"use":{"thousands":1}
,"include":{"decimal":1}
,"notation":{"character":1,"choose":1,"enter":1}
,"position":{"notation":1}
,"change":{"color":1}
,"color":{"scheme":1}
,"scheme":{"legend":1}
,"appearance":{"font":1}
,"font":{"style":1}
,"style":{"style":1,"chart":1}
,"changing":{"chart":1}
,"print":{"save":1}
,"save":{"layout":1}
,"finish":{"chart":1}
,"set":{"up":1}
,"up":{"pie":1}
}
;Search.control.loadWordPairs(pairs);
