var pairs =
{
"resizing":{"reshaping":1}
,"reshaping":{"objects":1}
,"objects":{"layout":1,"rag":1,"keeping":1,"match":1,"resize":1,"object":1}
,"layout":{"mode":1,"override":1,"objects":1}
,"mode":{"select":1}
,"select":{"objects":1}
,"rag":{"selection":1}
,"selection":{"handles":1,"inspector":1}
,"handles":{"change":1}
,"change":{"object\u2019s":1,"height":1}
,"object\u2019s":{"shape":1,"border":1}
,"shape":{"size":1}
,"size":{"change":1,"object":1,"shape":1}
,"height":{"width":1}
,"width":{"two-dimensional":1}
,"two-dimensional":{"object":1}
,"object":{"fields":1,"equal":1,"step":1,"size":1,"shape":1}
,"fields":{"rectangles":1,"imported":1}
,"rectangles":{"ovals":1}
,"ovals":{"fields":1}
,"imported":{"graphics":1}
,"graphics":{"drag":1}
,"drag":{"handle":1,"45-degree":1}
,"handle":{"appears":1,"resize":1,"precisely":1,"press":1,"sing":1}
,"appears":{"center":1}
,"center":{"object\u2019s":1}
,"border":{"force":1}
,"force":{"height":1}
,"equal":{"rectangle":1}
,"rectangle":{"square":1}
,"square":{"oval":1}
,"oval":{"circle":1}
,"circle":{"constrain":1}
,"constrain":{"line":1,"direction":1}
,"line":{"horizontal":1,"press":1}
,"horizontal":{"vertical":1}
,"vertical":{"constrain":1}
,"direction":{"drag":1}
,"45-degree":{"increments":1}
,"increments":{"resize":1}
,"resize":{"line":1,"selected":1,"button":1,"selection":1,"automatically":1}
,"press":{"ctrl":1,"shift":1,"alt":1}
,"ctrl":{"windows":1,"shift":1}
,"windows":{"option":1,"option-shift":1,"command":1}
,"option":{"macos":1}
,"macos":{"drag":1}
,"selected":{"objects":1}
,"keeping":{"proportions":1,"difference":1}
,"proportions":{"press":1}
,"shift":{"drag":1,"windows":1}
,"match":{"all":1}
,"all":{"widths":1,"heights":1}
,"widths":{"all":1,"press":1}
,"heights":{"largest":1}
,"largest":{"object":1}
,"step":{"inspector":1}
,"inspector":{"resize":1,"use":1}
,"button":{"arrange":1}
,"arrange":{"&align":1}
,"&align":{"position":1}
,"position":{"position":1,"tab":1}
,"tab":{"resize":1,"rulers":1}
,"difference":{"lengths":1}
,"lengths":{"widths":1}
,"option-shift":{"macos":1}
,"precisely":{"resize":1}
,"use":{"position":1}
,"rulers":{"guides":1,"grid":1}
,"guides":{"dynamic":1,"grid":1}
,"dynamic":{"guides":1}
,"grid":{"ee":1,"dragging":1,"allow":1}
,"ee":{"positioning":1}
,"positioning":{"objects":1}
,"override":{"grid":1}
,"dragging":{"handle":1}
,"alt":{"windows":1}
,"command":{"macos":1}
,"sing":{"rulers":1}
,"allow":{"objects":1}
,"automatically":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"window":1}
,"window":{"resized":1}
,"resized":{"setting":1}
,"setting":{"auto-resize":1}
,"auto-resize":{"options":1}
,"options":{"layout":1}
}
;Search.control.loadWordPairs(pairs);
