var pairs =
{
"bout":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"modes":1,"browse":1,"returns":1}
,"modes":{"data":1,"by":1}
,"data":{"filemaker":1,"file":1,"entry":1,"sorting":1,"forms":1,"layout":1}
,"browse":{"find":1,"data":1,"mode":1,"cancel":1}
,"find":{"layout":1,"command":1,"search":1,"group":1,"find":1,"browse":1,"edit":1,"preview":1}
,"layout":{"preview":1,"determine":1,"create":1,"switch":1,"edit":1,"cancel":1,"table":1,"button":1,"mode":1,"exit":1,"returns":1}
,"preview":{"mode":1,"data":1,"preview":1,"find":1,"cancel":1,"edit":1,"exit":1,"returns":1}
,"mode":{"choose":1,"view":1,"menu":1,"deciding":1,"it\u2019s":1,"browse":1,"you\u2019ll":1,"finding":1,"viewing":1,"you\u2019re":1,"by":1,"mode":1,"button":1,"ode":1,"switch":1,"exit":1}
,"choose":{"mode":1}
,"view":{"menu":1,"change":1,"if":1,"switch":1,"list":1,"access":1}
,"menu":{"use":1,"toolbar":1}
,"use":{"keyboard":1,"mode":1}
,"keyboard":{"shortcut":1}
,"shortcut":{"each":1}
,"each":{"mode":1}
,"toolbar":{"options":1,"buttons":1,"vary":1,"se":1,"switch":1}
,"options":{"choose":1}
,"deciding":{"if":1}
,"if":{"you\u2019re":1,"table":1}
,"you\u2019re":{"database":1,"customize":1}
,"database":{"can\u2019t":1}
,"can\u2019t":{"find":1}
,"command":{"wrong":1,"use":1}
,"wrong":{"mode":1}
,"it\u2019s":{"access":1}
,"access":{"privileges":1,"edit":1}
,"privileges":{"prohibit":1}
,"prohibit":{"command":1}
,"file":{"add":1}
,"add":{"view":1}
,"change":{"sort":1}
,"sort":{"omit":1}
,"omit":{"hide":1}
,"hide":{"delete":1}
,"delete":{"records":1}
,"records":{"browse":1,"find":1,"match":1,"called":1,"filemaker":1,"layout":1}
,"you\u2019ll":{"data":1}
,"entry":{"se":1,"printing":1}
,"se":{"adding":1,"creating":1,"previewing":1,"status":1}
,"adding":{"viewing":1}
,"viewing":{"data":1,"layouts":1}
,"sorting":{"records":1}
,"search":{"records":1}
,"match":{"set":1}
,"set":{"criteria":1,"find":1}
,"criteria":{"subset":1}
,"subset":{"records":1}
,"called":{"found":1}
,"found":{"set":1}
,"group":{"records":1}
,"returns":{"browse":1,"mode":1}
,"finding":{"records":1}
,"determine":{"screen":1}
,"screen":{"printed":1}
,"printed":{"reports":1}
,"reports":{"labels":1,"preview":1,"print":1,"summaries":1}
,"labels":{"forms":1,"reports":1}
,"forms":{"design":1,"reports":1}
,"design":{"layouts":1}
,"layouts":{"specific":1,"se":1,"reports":1,"multiple":1}
,"specific":{"tasks":1}
,"tasks":{"data":1}
,"printing":{"invoices":1}
,"invoices":{"select":1}
,"select":{"arrange":1}
,"arrange":{"fields":1}
,"fields":{"modify":1}
,"modify":{"existing":1}
,"existing":{"layout":1}
,"create":{"new":1}
,"new":{"layouts":1}
,"creating":{"managing":1}
,"managing":{"layouts":1}
,"print":{"preview":1}
,"multiple":{"columns":1}
,"columns":{"mailing":1}
,"mailing":{"labels":1}
,"summaries":{"se":1}
,"previewing":{"data":1}
,"switch":{"modes":1,"mode":1,"form":1,"layout":1,"preview":1}
,"by":{"clicking":1,"customizing":1}
,"clicking":{"buttons":1}
,"buttons":{"status":1,"each":1,"browse":1}
,"status":{"toolbar":1}
,"vary":{"depending":1}
,"depending":{"mode":1}
,"customize":{"buttons":1}
,"customizing":{"status":1}
,"button":{"series":1,"switch":1}
,"series":{"buttons":1}
,"edit":{"layout":1}
,"cancel":{"find":1}
,"table":{"view":1}
,"form":{"view":1}
,"list":{"view":1}
,"ode":{"exit":1}
,"exit":{"layout":1,"preview":1}
}
;Search.control.loadWordPairs(pairs);
