var pairs =
{
"selecting":{"portals":1}
,"portals":{"resize":1,"layout":1,"display":1}
,"resize":{"edit":1,"field":1,"portal":1}
,"edit":{"delete":1,"menu":1}
,"delete":{"portals":1,"choose":1,"portal":1}
,"layout":{"mode":1,"overlap":1,"part":1,"inserting":1,"select":1}
,"mode":{"arrow":1,"portal":1,"first":1}
,"arrow":{"pointer":1}
,"pointer":{"border":1,"select":1}
,"border":{"portal":1}
,"portal":{"portal":1,"contain":1,"by":1,"row":1,"double-click":1,"setup":1,"press":1,"object":1,"display":1,"records":1,"displayed":1,"if":1,"objects":1,"place":1,"associated":1,"number":1,"layout":1,"rows":1,"resize":1,"delete":1,"contents":1}
,"contain":{"field":1,"portal":1}
,"field":{"object":1,"objects":1}
,"object":{"select":1,"selection":1,"displays":1,"table":1,"placed":1}
,"select":{"portal":1,"allow":1}
,"by":{"clicking":1}
,"clicking":{"border":1}
,"selection":{"handles":1,"handle":1}
,"handles":{"each":1}
,"each":{"corner":1,"additional":1,"ecord":1}
,"corner":{"first":1,"object":1}
,"first":{"portal":1,"row":1}
,"row":{"drag":1,"resizes":1,"if":1,"portal":1,"want":1,"change":1}
,"drag":{"selection":1}
,"handle":{"first":1}
,"resizes":{"each":1,"match":1}
,"additional":{"row":1}
,"match":{"first":1}
,"if":{"resize":1,"vertical":1,"filtering":1,"sorting":1,"can\u2019t":1,"place":1}
,"objects":{"objects":1,"portal":1,"fields":1,"layout":1}
,"double-click":{"portal":1}
,"setup":{"dialog":1}
,"dialog":{"box":1}
,"box":{"change":1,"allows":1}
,"change":{"options":1,"record":1}
,"options":{"reating":1,"display":1,"portal":1}
,"reating":{"portals":1}
,"display":{"related":1,"plus":1,"purposes":1,"objects":1,"choose":1,"options":1}
,"related":{"record":1,"table":1,"records":1}
,"record":{"arrow":1,"display":1,"number":1,"options":1}
,"press":{"backspace":1}
,"backspace":{"delete":1}
,"choose":{"edit":1,"insert":1}
,"menu":{"clear":1,"record":1}
,"clear":{"layout":1}
,"displays":{"characteristics":1}
,"characteristics":{"lower":1}
,"lower":{"-l":1}
,"-l":{"eft":1}
,"eft":{"corner":1}
,"table":{"name":1,"select":1}
,"name":{"range":1}
,"range":{"rows":1}
,"rows":{"portal":1,"browse":1}
,"plus":{"sign":1}
,"sign":{"if":1}
,"vertical":{"scrolling":1}
,"scrolling":{"enabled":1,"portal":1}
,"enabled":{"filter":1,"sort":1,"filtering":1}
,"filter":{"if":1}
,"filtering":{"enabled":1,"records":1}
,"sort":{"if":1}
,"sorting":{"enabled":1,"records":1}
,"records":{"performed":1,"filtering":1,"intended":1,"calculations":1,"portal":1,"related":1,"displayed":1,"reating":1}
,"performed":{"sorting":1}
,"intended":{"display":1}
,"purposes":{"security":1,"filtering":1}
,"security":{"purposes":1}
,"calculations":{"summaries":1}
,"summaries":{"find":1}
,"find":{"requests":1}
,"requests":{"if":1}
,"can\u2019t":{"all":1,"place":1}
,"all":{"records":1}
,"allow":{"vertical":1}
,"allows":{"scroll":1}
,"scroll":{"related":1}
,"displayed":{"enter":1,"each":1}
,"enter":{"new":1}
,"new":{"related":1}
,"fields":{"first":1}
,"placed":{"first":1}
,"ecord":{"ou":1}
,"ou":{"can\u2019t":1}
,"place":{"tab":1,"objects":1,"popover":1,"portals":1}
,"tab":{"control":1}
,"control":{"web":1}
,"web":{"viewer":1}
,"viewer":{"portal":1}
,"overlap":{"portal":1}
,"popover":{"button":1,"contain":1}
,"button":{"portal":1}
,"associated":{"popover":1}
,"part":{"portal":1}
,"number":{"rows":1,"symbol":1,"variable":1}
,"want":{"numbers":1}
,"numbers":{"display":1,"portal":1}
,"insert":{"menu":1}
,"symbol":{"numbers":1}
,"browse":{"preview":1}
,"preview":{"modes":1}
,"modes":{"print":1}
,"print":{"layout":1}
,"inserting":{"date":1}
,"date":{"page":1}
,"page":{"number":1}
,"variable":{"layout":1}
}
;Search.control.loadWordPairs(pairs);
