var pairs =
{
"set":{"multi-user":1}
,"multi-user":{"llows":1,"[on]":1}
,"llows":{"disallows":1}
,"disallows":{"network":1}
,"network":{"access":1,"sh":1,"settings":1,"haring":1,"\u0022]":1,"sharing":1}
,"access":{"file":1,"via":1,"prevents":1,"selecting":1}
,"file":{"allows":1,"that\u2019s":1,"network":1}
,"allows":{"network":1}
,"via":{"filemaker":1}
,"filemaker":{"network":1,"pro":1}
,"sh":{"aring":1}
,"aring":{"selecting":1}
,"selecting":{"all":1,"users":1}
,"all":{"users":1}
,"users":{"filemaker":1,"display":1,"network":1}
,"settings":{"dialog":1}
,"dialog":{"box":1,"ptions":1,"[\u0022":1}
,"box":{"hidden":1,"selecting":1,"disallows":1,"filemaker":1}
,"hidden":{"allows":1}
,"prevents":{"name":1}
,"name":{"shared":1}
,"shared":{"database":1,"multi":1}
,"database":{"appearing":1,"file":1,"hosted":1}
,"appearing":{"hosts":1}
,"hosts":{"dialog":1}
,"display":{"hosts":1}
,"ptions":{"filemaker":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"shared":1}
,"multi":{"ser":1}
,"ser":{"database":1}
,"that\u2019s":{"users":1}
,"haring":{"hosting":1}
,"hosting":{"files":1}
,"files":{"guarantees":1}
,"guarantees":{"database":1}
,"hosted":{"launch":1}
,"launch":{"started":1}
,"started":{"by":1}
,"by":{"onfirstwindowopen":1}
,"onfirstwindowopen":{"script":1}
,"script":{"trigger":1}
,"trigger":{"show":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"[\u0022":{"file":1}
,"\u0022]":{"if":1}
,"if":{"[get":1,"network":1,"if":1,"automating":1}
,"[get":{"lastmessagechoice":1,"multiuserstate":1}
,"lastmessagechoice":{"=1]":1}
,"=1]":{"set":1}
,"[on]":{"end":1}
,"end":{"if":1}
,"sharing":{"if":1}
,"multiuserstate":{"=0]":1}
,"=0]":{"set":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
