var pairs =
{
"up":{"licating":1}
,"licating":{"deleting":1}
,"deleting":{"renaming":1,"layout":1,"objects":1,"layouts":1}
,"renaming":{"layouts":1}
,"layouts":{"duplicate":1,"manage":1,"dialog":1,"menu":1,"by":1,"deleting":1,"delete":1}
,"duplicate":{"delete":1,"layout":1}
,"delete":{"rename":1,"layout":1,"delete":1,"alert":1,"last":1,"layouts":1}
,"rename":{"layouts":1,"choose":1,"layout":1,"duplicate":1}
,"manage":{"layouts":1}
,"dialog":{"box":1}
,"box":{"layout":1,"want":1,"continue":1,"refers":1}
,"layout":{"mode":1,"want":1,"select":1,"duplicate":1,"name":1,"delete":1,"rename":1,"double-click":1,"setup":1,"can\u2019t":1,"names":1,"copy":1,"filemaker":1,"file":1,"objects":1,"by":1,"script":1,"go":1,"layout":1,"dialog":1,"internal":1,"update":1,"change":1}
,"mode":{"save":1,"rename":1}
,"save":{"layout":1}
,"want":{"duplicate":1,"copy":1,"each":1}
,"choose":{"file":1,"edit":1}
,"file":{"menu":1,"layout":1,"copy":1,"select":1,"choose":1}
,"menu":{"manage":1,"copy":1,"paste":1,"layout":1}
,"select":{"layout":1}
,"name":{"duplicated":1,"list":1,"edit":1,"type":1,"file":1,"each":1,"rename":1}
,"duplicated":{"copy":1}
,"copy":{"appended":1,"complete":1,"paste":1,"choose":1,"switch":1}
,"appended":{"delete":1}
,"alert":{"message":1}
,"message":{"can\u2019t":1}
,"can\u2019t":{"undo":1,"delete":1}
,"undo":{"deleting":1}
,"double-click":{"layout":1}
,"list":{"select":1}
,"edit":{"display":1,"menu":1}
,"display":{"layout":1,"copying":1}
,"setup":{"dialog":1}
,"type":{"descriptive":1}
,"descriptive":{"name":1}
,"last":{"layout":1}
,"names":{"unique":1,"identical":1}
,"unique":{"it\u2019s":1,"name":1}
,"it\u2019s":{"recommended":1}
,"recommended":{"use":1}
,"use":{"unique":1}
,"each":{"layout":1,"field":1}
,"complete":{"layout":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"file":1}
,"paste":{"all":1,"if":1}
,"all":{"layout\u2019s":1}
,"layout\u2019s":{"objects":1}
,"objects":{"layout":1,"want":1,"placing":1,"reference":1}
,"switch":{"layout":1}
,"if":{"field":1}
,"field":{"names":1,"want":1,"object":1}
,"identical":{"files":1}
,"files":{"respecify":1}
,"respecify":{"field":1}
,"object":{"display":1}
,"copying":{"duplicating":1}
,"duplicating":{"deleting":1}
,"placing":{"removing":1}
,"removing":{"fields":1}
,"fields":{"layou":1}
,"layou":{"duplicate":1}
,"by":{"choosing":1,"name":1}
,"choosing":{"layouts":1}
,"script":{"steps":1}
,"steps":{"go":1,"objects":1}
,"go":{"layout":1,"related":1}
,"related":{"records":1}
,"records":{"selected":1}
,"selected":{"layout":1}
,"continue":{"refer":1}
,"refer":{"layout":1}
,"refers":{"layout":1}
,"internal":{"id":1}
,"id":{"doesn\u2019t":1}
,"doesn\u2019t":{"change":1}
,"change":{"rename":1,"theme":1}
,"update":{"script":1}
,"reference":{"layouts":1}
,"theme":{"duplicate":1}
}
;Search.control.loadWordPairs(pairs);
