var pairs =
{
"mitting":{"records":1}
,"records":{"found":1,"temporarily":1,"menu":1,"display":1,"omit":1,"file":1}
,"found":{"set":1}
,"set":{"all":1,"omitted":1,"new":1,"exist":1,"pie":1}
,"all":{"records":1,"status":1}
,"omitted":{"hidden":1,"records":1,"set":1,"view":1}
,"hidden":{"omit":1}
,"omit":{"additional":1,"specific":1,"hoose":1,"omit":1,"series":1,"choose":1,"multiple":1,"view":1}
,"additional":{"records":1}
,"new":{"find":1}
,"find":{"omitted":1,"mode":1}
,"temporarily":{"excluded":1}
,"excluded":{"found":1}
,"exist":{"database":1}
,"database":{"omit":1}
,"specific":{"record":1}
,"record":{"display":1,"omit":1,"number":1}
,"display":{"select":1}
,"select":{"record":1,"first":1}
,"hoose":{"records":1}
,"menu":{"omit":1,"show":1}
,"series":{"records":1}
,"first":{"record":1}
,"number":{"consecutive":1,"records":1}
,"consecutive":{"records":1}
,"choose":{"records":1,"requests":1}
,"multiple":{"omit":1,"dialog":1}
,"dialog":{"box":1}
,"box":{"type":1}
,"type":{"number":1}
,"view":{"omitted":1,"all":1}
,"pie":{"chart":1}
,"chart":{"pie":1,"icon":1}
,"icon":{"status":1}
,"status":{"toolbar":1}
,"toolbar":{"choose":1,"find":1}
,"show":{"omitted":1,"all":1}
,"file":{"browse":1}
,"browse":{"mode":1}
,"mode":{"show":1,"choose":1}
,"requests":{"menu":1}
}
;Search.control.loadWordPairs(pairs);
