var pairs =
{
"control":{"script":1,"progression":1}
,"script":{"steps":1,"by":1,"based":1,"finished":1,"condition":1,"interval":1,"user":1}
,"steps":{"control":1,"call":1,"if\u002Fthen\u002Felse":1,"script":1}
,"progression":{"script":1}
,"by":{"letting":1}
,"letting":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"if":1}
,"if":{"specific":1}
,"specific":{"conditions":1,"condition":1}
,"conditions":{"occur":1,"conditionally":1}
,"occur":{"use":1}
,"use":{"script":1}
,"call":{"scripts":1,"script":1}
,"scripts":{"sub-scripts":1}
,"sub-scripts":{"pause":1}
,"pause":{"resume":1}
,"resume":{"script":1}
,"based":{"defined":1}
,"defined":{"conditions":1}
,"conditionally":{"perform":1}
,"perform":{"script":1}
,"if\u002Fthen\u002Felse":{"logic":1}
,"logic":{"stop":1}
,"stop":{"script":1}
,"finished":{"if":1}
,"condition":{"met":1}
,"met":{"create":1,"call":1}
,"create":{"loops":1}
,"loops":{"repetitively":1}
,"repetitively":{"carry":1}
,"carry":{"sequence":1}
,"sequence":{"steps":1}
,"interval":{"ios":1}
,"ios":{"device":1}
,"device":{"enters":1}
,"enters":{"exits":1}
,"exits":{"region":1}
,"region":{"queue":1}
,"queue":{"clear":1}
,"clear":{"local":1}
,"local":{"notification":1}
,"notification":{"perform":1}
,"user":{"interacts":1}
,"interacts":{"notification":1}
}
;Search.control.loadWordPairs(pairs);
