var pairs =
{
"sing":{"variables":1}
,"variables":{"variables":1,"provide":1,"file":1,"users":1,"two":1,"scripts":1,"store":1,"calculations":1,"nserting":1,"layout":1,"supported":1,"erge":1,"ile":1,"data":1,"filemaker":1}
,"provide":{"temporary":1}
,"temporary":{"location":1}
,"location":{"storing":1}
,"storing":{"data":1}
,"data":{"accessed":1,"file":1,"files":1,"type":1,"variables":1,"types":1}
,"accessed":{"context":1}
,"context":{"file":1}
,"file":{"define":1,"nsert":1,"defined":1,"closed":1,"paths":1}
,"define":{"ariables":1,"variable":1}
,"ariables":{"calculations":1,"supported":1}
,"calculations":{"let":1,"scripts":1}
,"let":{"while":1,"[$var":1}
,"while":{"functions":1}
,"functions":{"scripts":1}
,"scripts":{"cript":1,"name":1,"file":1}
,"cript":{"steps":1}
,"steps":{"set":1,"variables":1}
,"set":{"variable":1}
,"variable":{"get":1,"define":1,"scope":1,"name":1,"na":1,"determined":1}
,"get":{"folder":1}
,"folder":{"path":1}
,"path":{"ow":1}
,"ow":{"custom":1}
,"custom":{"dialog":1}
,"dialog":{"read":1,"box":1,"boxes":1}
,"read":{"data":1}
,"nsert":{"script":1}
,"script":{"steps":1,"defined":1,"global":1}
,"defined":{"user\u2019s":1,"local":1,"sub-scripts":1,"cleared":1}
,"user\u2019s":{"variables":1}
,"users":{"if":1,"use":1}
,"if":{"data":1}
,"files":{"multiple":1}
,"multiple":{"users":1}
,"use":{"field":1,"variables":1}
,"field":{"global":1,"data":1,"type":1}
,"global":{"storage":1,"$$$$variable":1,"variables":1,"va":1}
,"storage":{"variable":1}
,"scope":{"by":1,"prefix":1}
,"by":{"adding":1}
,"adding":{"prefix":1}
,"prefix":{"variable":1,"availability":1}
,"name":{"scope":1,"treated":1,"returns":1,"follow":1,"naming":1}
,"availability":{"unction":1}
,"unction":{"none":1,"defined":1}
,"none":{"variable":1}
,"na":{"unction":1,"script":1,"file":1}
,"local":{"$$variable":1,"global":1,"variables":1}
,"$$variable":{"na":1}
,"sub-scripts":{"cleared":1}
,"cleared":{"script":1,"file":1}
,"$$$$variable":{"na":1}
,"closed":{"local":1}
,"two":{"local":1}
,"treated":{"variables":1}
,"store":{"values":1}
,"values":{"use":1}
,"paths":{"creating":1,"find":1,"ind":1,"stored":1}
,"creating":{"file":1}
,"find":{"requests":1,"request":1}
,"requests":{"create":1,"edit":1,"va":1}
,"create":{"edit":1}
,"edit":{"edit":1,"find":1}
,"request":{"dialog":1}
,"box":{"speci":1}
,"speci":{"fy":1}
,"fy":{"find":1}
,"boxes":{"layouts":1}
,"layouts":{"merge":1}
,"merge":{"variables":1}
,"nserting":{"merge":1}
,"layout":{"local":1}
,"va":{"riables":1,"riable":1}
,"riables":{"include":1}
,"include":{"optional":1}
,"optional":{"repetition":1}
,"repetition":{"number":1}
,"number":{"appears":1}
,"appears":{"brackets":1}
,"brackets":{"[]":1}
,"[]":{"variable":1}
,"returns":{"111":1}
,"111":{"let":1}
,"[$var":{"[1]":1}
,"[1]":{"=1":1,"$var":1}
,"=1":{"$var":1}
,"$var":{"[2]":1,"[3]":1,"[1]":1}
,"[2]":{"=10":1,"$var":1}
,"=10":{"$var":1}
,"[3]":{"=100":1,"repetitions":1}
,"=100":{"$var":1}
,"repetitions":{"variables":1}
,"supported":{"function":1,"ile":1}
,"function":{"variables":1}
,"erge":{"variables":1}
,"ile":{"paths":1}
,"ind":{"requests":1}
,"riable":{"name":1}
,"follow":{"aming":1}
,"aming":{"restrictions":1}
,"restrictions":{"ield":1}
,"ield":{"name":1}
,"naming":{"fields":1}
,"fields":{"ariables":1,"except":1,"bout":1}
,"stored":{"container":1}
,"container":{"field":1}
,"type":{"variable":1,"variables":1}
,"determined":{"dynamically":1}
,"dynamically":{"based":1}
,"based":{"assigned":1}
,"assigned":{"data":1}
,"types":{"fields":1}
,"except":{"calculation":1}
,"calculation":{"summary":1}
,"summary":{"fields":1}
,"bout":{"choosing":1}
,"choosing":{"field":1}
,"filemaker":{"knowledge":1}
,"knowledge":{"base":1}
,"base":{"repetitions":1}
}
;Search.control.loadWordPairs(pairs);
