var pairs =
{
"custom":{"function":1,"functions":1}
,"function":{"note":1,"rewritten":1,"dialog":1}
,"note":{"feature":1}
,"feature":{"use":1}
,"use":{"advanced":1}
,"advanced":{"tools":1,"files":1}
,"tools":{"general":1,"cu":1,"option":1}
,"general":{"preference":1}
,"preference":{"selected":1}
,"selected":{"ad":1,"ewly":1}
,"ad":{"vanced":1}
,"vanced":{"tools":1}
,"cu":{"stom":1}
,"stom":{"fu":1}
,"fu":{"nctions":1}
,"nctions":{"utility":1}
,"utility":{"create":1}
,"create":{"custom":1}
,"functions":{"reused":1,"filemaker":1,"file":1,"under":1,"list":1,"disable":1}
,"reused":{"database":1}
,"database":{"file":1}
,"file":{"created":1,"by":1}
,"created":{"copy":1}
,"copy":{"paste":1}
,"paste":{"custom":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"files":{"import":1,"formula":1}
,"import":{"custom":1}
,"formula":{"written":1}
,"written":{"changed":1}
,"changed":{"function":1}
,"rewritten":{"applied":1}
,"applied":{"fields":1}
,"fields":{"scripts":1}
,"scripts":{"ustom":1}
,"ustom":{"functions":1}
,"by":{"user":1,"users":1}
,"user":{"by":1}
,"users":{"full":1}
,"full":{"access":1}
,"access":{"privileges":1}
,"privileges":{"across":1}
,"across":{"multiple":1}
,"multiple":{"platforms":1}
,"platforms":{"replace":1}
,"replace":{"third-party":1}
,"third-party":{"plug-ins":1}
,"plug-ins":{"purposes":1}
,"purposes":{"use":1}
,"option":{"selected":1}
,"ewly":{"defined":1}
,"defined":{"functions":1}
,"under":{"own":1}
,"own":{"category":1}
,"category":{"functions":1}
,"list":{"calculation":1}
,"calculation":{"edit":1}
,"edit":{"custom":1}
,"dialog":{"boxes":1}
,"boxes":{"if":1}
,"if":{"reveal":1}
,"reveal":{"custom":1}
,"disable":{"display":1}
,"display":{"dialog":1}
}
;Search.control.loadWordPairs(pairs);
