var pairs =
{
"check":{"selection":1,"selected":1,"spelling":1}
,"selection":{"ses":1,"[select":1}
,"ses":{"spelling":1}
,"spelling":{"checker":1,"dialog":1,"returns":1,"notes":1,"automating":1}
,"checker":{"check":1}
,"selected":{"text":1,"doesn\u2019t":1}
,"text":{"select":1,"active":1,"script":1}
,"select":{"entire":1,"text":1}
,"entire":{"contents":1}
,"contents":{"checks":1,"select":1,"target":1,"selected":1}
,"checks":{"all":1,"spelling":1}
,"all":{"text":1}
,"active":{"field":1}
,"field":{"if":1,"allows":1,"checked":1,"empty":1,"current":1}
,"if":{"use":1,"select":1}
,"use":{"select":1}
,"script":{"step":1}
,"step":{"performs":1,"selects":1}
,"performs":{"go":1}
,"go":{"target":1}
,"target":{"field":1}
,"allows":{"field":1}
,"checked":{"filemaker":1}
,"filemaker":{"pro":1,"data":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"displays":1}
,"displays":{"spelling":1}
,"dialog":{"box":1}
,"box":{"field":1}
,"empty":{"filemaker":1}
,"data":{"api":1}
,"api":{"custom":1}
,"custom":{"web":1}
,"web":{"publishing":1}
,"publishing":{"script":1}
,"selects":{"contents":1}
,"doesn\u2019t":{"check":1}
,"returns":{"error":1}
,"error":{"command":1}
,"command":{"unavailable":1}
,"unavailable":{"checks":1}
,"notes":{"field":1}
,"current":{"record":1}
,"record":{"check":1}
,"[select":{"products":1}
,"products":{":notes]":1}
,":notes]":{"checking":1}
,"checking":{"spelling":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
