var pairs =
{
"enabling":{"odbc":1}
,"odbc":{"data":1,"dsn":1}
,"data":{"source":1,"sql":1,"shared":1,"sources":1,"accessed":1}
,"source":{"single":1,"list":1}
,"single":{"sign-on":1}
,"sign-on":{"windows":1,"sso":1,"permits":1,"enter":1,"supported":1}
,"windows":{"if":1,"domain":1,"user":1,"authentication":1}
,"if":{"database":1}
,"database":{"files":1,"open":1,"administrator":1}
,"files":{"hosted":1,"efore":1}
,"hosted":{"by":1,"database":1}
,"by":{"filemaker":1}
,"filemaker":{"pro":1,"server":1}
,"pro":{"advanced":1}
,"advanced":{"filemaker":1}
,"server":{"access":1,"configure":1,"use":1,"service":1,"installation":1}
,"access":{"odbc":1}
,"sql":{"server":1}
,"configure":{"host":1,"account":1,"trust":1,"odbc":1,"sql":1,"filemaker":1}
,"host":{"computer":1}
,"computer":{"enable":1,"configure":1}
,"enable":{"single":1,"odbc":1,"impersonate":1}
,"sso":{"odbc":1}
,"permits":{"client":1}
,"client":{"use":1,"configure":1,"authentication":1}
,"use":{"windows-authenticated":1,"kerberos":1,"windows":1}
,"windows-authenticated":{"login":1}
,"login":{"access":1}
,"shared":{"files":1}
,"efore":{"enable":1}
,"domain":{"administrator":1,"name":1}
,"administrator":{"configure":1,"provide":1}
,"account":{"trusted":1,"client":1,"host":1,"filemaker":1}
,"trusted":{"delegation":1}
,"delegation":{"security":1,"use":1}
,"security":{"setting":1,"settings":1}
,"setting":{"windows":1}
,"user":{"account":1,"delegation":1}
,"trust":{"user":1}
,"kerberos":{"security":1}
,"settings":{"windows":1}
,"impersonate":{"client":1}
,"authentication":{"privilege":1,"host":1,"database":1,"select":1,"single":1}
,"privilege":{"windows":1}
,"dsn":{"use":1}
,"open":{"chose":1,"hosted":1}
,"chose":{"file":1}
,"file":{"menu":1}
,"menu":{"manage":1}
,"manage":{"external":1}
,"external":{"data":1}
,"sources":{"elect":1}
,"elect":{"odbc":1}
,"list":{"edit":1}
,"edit":{"authentication":1}
,"select":{"use":1}
,"enter":{"spn":1}
,"spn":{"service":1,"format":1}
,"service":{"principal":1,"log":1}
,"principal":{"name":1}
,"name":{"note":1,"port":1}
,"note":{"windows":1}
,"provide":{"spn":1}
,"format":{"mssqlsvc\u002F<":1}
,"mssqlsvc\u002F<":{"qualified":1}
,"qualified":{"domain":1}
,"port":{"mssqlsvc\u002Fsql2005.filemaker.com:1433":1}
,"mssqlsvc\u002Fsql2005.filemaker.com:1433":{"order":1}
,"order":{"open":1}
,"log":{"privileged":1}
,"privileged":{"user":1}
,"installation":{"configuration":1}
,"configuration":{"uide":1}
,"uide":{"odbc":1}
,"supported":{"macintosh":1}
,"macintosh":{"odbc":1}
,"accessed":{"mysql":1}
,"mysql":{"oracle":1}
,"oracle":{"web":1}
,"web":{"publishing":1}
,"publishing":{"enable":1}
}
;Search.control.loadWordPairs(pairs);
