var pairs =
{
"et":{"zoom":1}
,"zoom":{"level":1,"reduces":1,"enlarges":1,"levels":1,"pre-set":1}
,"level":{"nlarges":1,"allow":1,"perform":1,"zoom":1,"reduction":1,"use":1,"100":1,"go":1,"[lock":1,"etting":1,"automating":1}
,"nlarges":{"reduces":1}
,"reduces":{"image":1,"screen":1}
,"image":{"screen":1,"by":1}
,"screen":{"lock":1,"image":1}
,"lock":{"prohibits":1,"option":1}
,"prohibits":{"users":1}
,"users":{"zoom":1,"change":1}
,"allow":{"users":1}
,"change":{"zoom":1}
,"perform":{"script":1}
,"script":{"step":1,"trigger":1}
,"step":{"lock":1,"preset":1}
,"option":{"zoom":1}
,"by":{"zoom":1}
,"enlarges":{"screen":1}
,"reduction":{"values":1}
,"values":{"100":1,"150":1}
,"100":{"75":1,"locks":1,"%]":1}
,"75":{"50":1}
,"50":{"25":1}
,"25":{"enlargement":1}
,"enlargement":{"values":1,"value":1}
,"150":{"200":1}
,"200":{"300":1,"filemaker":1}
,"300":{"400":1}
,"400":{"note":1}
,"note":{"filemaker":1}
,"filemaker":{"go":1,"pro":1}
,"go":{"maximum":1,"layout":1}
,"maximum":{"enlargement":1}
,"value":{"200":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"use":1}
,"use":{"script":1,"onwindowopen":1}
,"preset":{"zoom":1}
,"levels":{"set":1}
,"set":{"default":1,"zoom":1}
,"default":{"zoom":1}
,"onwindowopen":{"script":1}
,"trigger":{"invoices":1}
,"invoices":{"iphone":1}
,"iphone":{"layout":1,"\u0022]":1}
,"layout":{"sets":1,"[\u0022":1}
,"sets":{"zoom":1}
,"locks":{"zoom":1}
,"[\u0022":{"invoices":1}
,"\u0022]":{"set":1}
,"[lock":{"100":1}
,"%]":{"pre-set":1}
,"pre-set":{"zoom":1}
,"etting":{"zoom":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
