var pairs =
{
"getnthrecord":{"returns":1,"fieldname":1,"updated":1,"record":1,"current":1,"related":1,"first":1,"contacts":1}
,"returns":{"contents":1,"field":1,"nth":1}
,"contents":{"fieldname":1,"first":1,"second":1}
,"fieldname":{"record":1,"recordnumber":1,"-any":1}
,"record":{"number":1,"referred":1,"calculation":1,"found":1,"related":1,"based":1,"current":1,"contacts":1}
,"number":{"getnthrecord":1,"want":1,"date":1}
,"recordnumber":{"fieldname":1,"-the":1,"returns":1}
,"-any":{"related":1}
,"related":{"field":1,"table":1,"set":1}
,"field":{"repeating":1,"expression":1,"recordnumber":1,"record":1,"next":1}
,"repeating":{"field":1}
,"expression":{"returns":1}
,"-the":{"record":1}
,"want":{"data":1}
,"data":{"text":1}
,"text":{"number":1}
,"date":{"time":1}
,"time":{"timestamp":1}
,"timestamp":{"container":1}
,"container":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"8.0":1}
,"8.0":{"result":1}
,"result":{"getnthrecord":1}
,"updated":{"record":1}
,"referred":{"by":1}
,"by":{"getnthrecord":1}
,"calculation":{"currently":1}
,"currently":{"evaluated":1}
,"evaluated":{"getnthrecord":1}
,"current":{"table":1,"record":1}
,"table":{"returns":1,"sorted":1,"getnthrecord":1}
,"nth":{"record":1}
,"found":{"set":1}
,"set":{"current":1,"relative":1}
,"sorted":{"getnthrecord":1}
,"relative":{"current":1}
,"based":{"sort":1}
,"sort":{"order":1}
,"order":{"relationship":1}
,"relationship":{"getnthrecord":1}
,"first":{"name":1}
,"name":{";2":1,"field":1,"get":1}
,";2":{"returns":1}
,"get":{"recordnumber":1}
,"next":{"record":1}
,"contacts":{":first":1,"table":1,":has":1}
,":first":{"name":1}
,":has":{"repetitions":1}
,"repetitions":{"[2]":1,"field":1}
,"[2]":{";2":1}
,"second":{"repetition":1}
,"repetition":{"repetitions":1}
}
;Search.control.loadWordPairs(pairs);
