var pairs =
{
"middle":{"extracts":1,"text":1,"408":1,"phonenumber":1,"abcdefghij":1,"name":1}
,"extracts":{"numberofcharacters":1}
,"numberofcharacters":{"text":1,"-any":1}
,"text":{"starting":1,"start":1,"-any":1,"expression":1,"field":1,"filemaker":1,"function":1}
,"starting":{"character":1}
,"character":{"position":1}
,"position":{"middle":1,"name":1}
,"start":{"numberofcharacters":1,"-any":1,"function":1,"=1":1,"greater":1}
,"-any":{"text":1,"numeric":1}
,"expression":{"text":1,"field":1}
,"field":{"start":1,"number":1,"408":1,"name":1}
,"numeric":{"expression":1}
,"number":{"numberofcharacters":1,"text":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"if":1}
,"if":{"start":1}
,"function":{"evaluated":1,"returns":1}
,"evaluated":{"if":1}
,"=1":{"if":1}
,"greater":{"length":1}
,"length":{"text":1}
,"returns":{"middle":1,"408":1,"ef":1,"smi":1}
,"408":{"555-9054":1,"middle":1,"phonenumber":1}
,"555-9054":{"returns":1,"middle":1}
,"phonenumber":{"returns":1,"field":1}
,"abcdefghij":{"returns":1}
,"ef":{"middle":1}
,"name":{"position":1,"returns":1,"john":1}
,"smi":{"text":1}
,"john":{"smith":1}
}
;Search.control.loadWordPairs(pairs);
