var pairs =
{
"izi":{"ng":1}
,"ng":{"layouts":1}
,"layouts":{"devices":1,"ipad":1}
,"devices":{"use":1,"multiple":1}
,"use":{"screen":1}
,"screen":{"stencils":1,"resolutions":1,"stencil":1,"each":1}
,"stencils":{"nonprinting":1,"provide":1,"button":1,"by":1,"aren\u2019t":1}
,"nonprinting":{"guides":1}
,"guides":{"help":1,"show":1}
,"help":{"design":1}
,"design":{"layouts":1}
,"ipad":{"iphone":1}
,"iphone":{"ipod":1}
,"ipod":{"touch":1}
,"touch":{"computers":1}
,"computers":{"screen":1}
,"resolutions":{"layout":1}
,"layout":{"mode":1,"bar":1,"setting":1,"objects":1,"expands":1}
,"mode":{"screen":1,"arrow":1}
,"provide":{"estimated":1}
,"estimated":{"viewing":1}
,"viewing":{"device\u2019s":1}
,"device\u2019s":{"display":1}
,"display":{"layout":1}
,"arrow":{"screen":1}
,"stencil":{"screen":1,"choose":1,"deselect":1,"visible":1,"hidden":1,"time":1}
,"button":{"layout":1}
,"bar":{"show":1,"if":1}
,"show":{"screen":1,"hide":1}
,"choose":{"size":1,"custom":1}
,"size":{"ist":1,"enter":1,"if":1}
,"ist":{"set":1}
,"set":{"custom":1}
,"custom":{"screen":1,"size":1}
,"enter":{"values":1}
,"values":{"height":1}
,"height":{"width":1}
,"width":{"hide":1}
,"hide":{"screen":1,"all":1}
,"deselect":{"size":1}
,"if":{"screen":1,"you\u2019re":1,"devices":1}
,"visible":{"database":1,"all":1,"screen":1}
,"database":{"visible":1}
,"all":{"databases":1,"visible":1}
,"databases":{"stencil":1}
,"hidden":{"custom":1}
,"time":{"show":1}
,"by":{"clicking":1}
,"clicking":{"screen":1}
,"you\u2019re":{"shared":1}
,"shared":{"file":1}
,"file":{"screen":1}
,"aren\u2019t":{"displayed":1}
,"displayed":{"users":1}
,"users":{"if":1}
,"multiple":{"sizes":1}
,"sizes":{"access":1}
,"access":{"layout":1}
,"setting":{"layout":1,"auto-resize":1}
,"objects":{"resize":1,"filemaker":1}
,"resize":{"ensures":1}
,"ensures":{"layout":1}
,"expands":{"fill":1}
,"fill":{"entire":1}
,"entire":{"screen":1}
,"each":{"device":1}
,"device":{"setting":1,"guides":1}
,"auto-resize":{"options":1}
,"options":{"layout":1}
,"filemaker":{"go":1}
,"go":{"device":1}
}
;Search.control.loadWordPairs(pairs);
