var pairs =
{
"diting":{"creating":1}
,"creating":{"styles":1}
,"styles":{"layout":1,"save":1,"styles":1,"tab":1,"layouts":1,"theme":1,"intend":1,"ome":1,"slide":1,"rename":1}
,"layout":{"edit":1,"parts":1,"background":1,"theme":1,"mode":1,"part":1,"level":1,"assigned":1,"objects":1,"select":1}
,"edit":{"display":1,"style":1,"menu":1,"create":1}
,"display":{"attributes":1,"new":1}
,"attributes":{"objects":1,"selected":1,"attributes":1,"saved":1,"asterisk":1}
,"objects":{"layout":1,"parts":1,"current":1,"revert":1,"buttons":1}
,"parts":{"layout":1,"selected":1}
,"background":{"tyles":1,"select":1,"ensure":1,"editing":1,"asterisk":1}
,"tyles":{"create":1}
,"create":{"new":1,"separate":1,"styles":1}
,"new":{"custom":1,"style":1,"attributes":1,"theme":1,"name":1}
,"custom":{"styles":1,"style":1,"theme":1}
,"save":{"current":1,"new":1,"theme":1,"styles":1,"custom":1}
,"current":{"layout":1,"style":1,"theme":1}
,"theme":{"layout":1,"name":1,"if":1,"update":1,"unsaved":1,"button":1,"save":1,"type":1,"arrow":1,"start":1,"minimalist":1,"custom":1}
,"mode":{"select":1}
,"select":{"object":1,"note":1,"layout":1,"show":1,"appearance":1}
,"object":{"part":1,"layout":1,"style":1,"revert":1}
,"part":{"label":1,"layout":1}
,"label":{"layout":1}
,"note":{"select":1,"rename":1,"if":1,"incrementally":1}
,"ensure":{"objects":1}
,"selected":{"inspector":1,"object":1,"style":1}
,"inspector":{"appearance":1,"arrow":1,"style":1,"select":1}
,"appearance":{"appearance":1,"tab":1}
,"tab":{"change":1,"inspector":1,"delete":1}
,"change":{"display":1}
,"editing":{"objects":1}
,"asterisk":{"*)":1,"disappears":1,"appears":1}
,"*)":{"appears":1}
,"appears":{"style":1,"theme":1}
,"style":{"name":1,"style":1,"unsaved":1,"button":1,"choose":1,"create":1,"type":1,"layout":1,"all":1,"reformatted":1,"selected":1,"definition":1,"saved":1,"save":1,"current":1,"new":1,"appearance":1,"styles":1,"want":1,"select":1,"note":1,"applied":1,"object":1,"red":1,"arrow":1}
,"name":{"arrow":1,"asterisk":1,"inspector":1,"stored":1,"theme":1,"note":1}
,"arrow":{"red":1,"gray":1,"pointer":1,"unsaved":1}
,"red":{"indicating":1,"if":1,"arrow":1}
,"indicating":{"display":1,"edits":1}
,"saved":{"current":1,"style":1,"theme":1}
,"unsaved":{"style":1,"theme":1}
,"button":{"edit":1,"indicating":1,"choose":1,"rename":1,"note":1}
,"choose":{"save":1,"rename":1,"delete":1,"revert":1,"edit":1}
,"type":{"new":1,"name":1}
,"disappears":{"arrow":1}
,"gray":{"saved":1}
,"edits":{"saved":1}
,"level":{"if":1}
,"if":{"you\u2019ve":1,"edited":1,"created":1,"delete":1,"styles":1}
,"you\u2019ve":{"edited":1}
,"edited":{"existing":1,"style":1}
,"existing":{"style":1}
,"all":{"objects":1,"pause":1,"layout-level":1}
,"assigned":{"style":1}
,"reformatted":{"display":1}
,"definition":{"style":1}
,"stored":{"current":1}
,"created":{"style":1}
,"update":{"edited":1}
,"rename":{"custom":1,"style":1,"styles":1,"delete":1}
,"delete":{"custom":1,"style":1,"appearance":1,"revert":1}
,"show":{"all":1}
,"pause":{"arrow":1}
,"pointer":{"style":1}
,"want":{"delete":1}
,"applied":{"objects":1}
,"revert":{"default":1,"all":1,"style":1,"reapply":1,"styles":1}
,"default":{"style":1}
,"layout-level":{"styles":1}
,"incrementally":{"revert":1}
,"reapply":{"style":1}
,"menu":{"undo":1}
,"undo":{"redo":1}
,"redo":{"can\u2019t":1}
,"can\u2019t":{"use":1}
,"use":{"styles":1}
,"layouts":{"save":1}
,"intend":{"save":1}
,"start":{"minimalist":1}
,"minimalist":{"theme":1,"touch":1}
,"touch":{"theme":1}
,"ome":{"objects":1}
,"buttons":{"popovers":1}
,"popovers":{"slide":1}
,"slide":{"controls":1,"control":1,"panels":1}
,"controls":{"components":1}
,"components":{"formatted":1}
,"formatted":{"independently":1}
,"independently":{"slide":1}
,"control":{"create":1,"dots":1}
,"separate":{"styles":1}
,"panels":{"dots":1}
,"dots":{"slide":1,"edit":1}
}
;Search.control.loadWordPairs(pairs);
