var pairs =
{
"get":{"file":1,"documentspath":1}
,"file":{"exists":1,"path":1,"check":1,"paths":1,"named":1}
,"exists":{"returns":1,"get":1,"[\u0022":1,"documents":1,"[\u0022$file":1,"exist":1}
,"returns":{"true":1,"false":1}
,"true":{"if":1}
,"if":{"file":1,"variable":1}
,"false":{"source":1}
,"source":{"file":1}
,"path":{"file":1}
,"check":{"creating":1}
,"creating":{"file":1}
,"paths":{"target":1}
,"target":{"field":1,"table":1,"$fileexists":1}
,"field":{"variable":1,"if":1}
,"variable":{"store":1,"doesn\u2019t":1,"[$file":1}
,"store":{"result":1}
,"result":{"if":1}
,"doesn\u2019t":{"exist":1}
,"exist":{"script":1,"automating":1}
,"script":{"step":1}
,"step":{"creates":1}
,"creates":{"sing":1}
,"sing":{"variables":1}
,"variables":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"18.0":1}
,"18.0":{"advanced":1}
,"advanced":{"sets":1}
,"sets":{"table":1}
,"table":{":data":1}
,":data":{"field":1,"displays":1}
,"named":{"data.txt":1,"change.log":1}
,"data.txt":{"exists":1,"target":1}
,"[\u0022":{"data.txt":1}
,"displays":{"file":1}
,"change.log":{"exists":1,"get":1}
,"documents":{"folder":1}
,"folder":{"set":1}
,"set":{"variable":1}
,"[$file":{"value":1,"&\u0022":1}
,"value":{"get":1}
,"documentspath":{"&\u0022":1}
,"&\u0022":{"change.log":1,"&if":1}
,"[\u0022$file":{"target":1}
,"$fileexists":{"show":1,"exists":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"dialog":{"[$file":1}
,"&if":{"$fileexists":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
