var pairs =
{
"orking":{"json":1}
,"json":{"functions":1,"data":1,"format":1,"objects":1,"specifies":1,"object":1,"array":1,"keyorindexorpath":1,"value":1,"parser":1,"formatted":1,"element":1,"deletes":1,"parameter":1}
,"functions":{"filemaker":1,"enable":1,"handle":1,"parse":1,"json":1,"return":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"text":1,"utility":1}
,"text":{"functions":1,"field":1,"expression":1}
,"enable":{"solution":1}
,"solution":{"parse":1}
,"parse":{"modify":1,"json":1}
,"modify":{"json":1}
,"data":{"sources":1,"json":1,"format":1,"$$json":1,"returned":1,"filemaker":1,"doesn\u2019t":1,"easier":1,"use":1,"get":1,"element":1,"jsonlistvalues":1,"first":1,"operate":1,"stored":1,"if":1,"value":1,"type":1,"types":1,"set":1,"keyorindexorpath":1,"calculation":1,"valid":1,"end":1,"bakery":1,"web":1,"parsing":1,"changing":1,"elements":1}
,"sources":{"web":1}
,"web":{"services":1,"service":1}
,"services":{"transfer":1}
,"transfer":{"data":1}
,"format":{"via":1,"json.org":1}
,"via":{"rest":1}
,"rest":{"api":1,"apis":1}
,"api":{"json":1,"returns":1}
,"json.org":{"use":1}
,"use":{"ins":1,"jsonformatelements":1,"json":1,"jsonsetelement":1,"jsondeleteelement":1}
,"ins":{"ert":1}
,"ert":{"url":1}
,"url":{"script":1,"[w":1}
,"script":{"step":1,"determines":1,"[text":1}
,"step":{"access":1}
,"access":{"web":1}
,"service":{"parameters":1,"formatting":1}
,"parameters":{"retrieve":1,"function":1}
,"retrieve":{"send":1}
,"send":{"receive":1}
,"receive":{"http":1}
,"http":{"headers":1}
,"headers":{"store":1}
,"store":{"variable":1}
,"variable":{"field":1,"set":1,"[$url":1,"text":1,"jsonlistkeys":1,"[$productcount":1,"[$i":1,"json":1,"[$newproduct":1,"[$nextindex":1,"[$$json":1,"[$id":1,"[$result":1}
,"field":{"bakery":1,"variable":1,"[products":1}
,"bakery":{"product":1,"key":1,"object":1}
,"product":{"list":1,"sets":1,"set":1,"empty":1,"array":1,"objects":1,"[{":1}
,"list":{"clients":1,"today\u2019s":1}
,"clients":{"json":1}
,"returns":{"list":1,"error":1}
,"today\u2019s":{"specials":1}
,"specials":{"json":1}
,"$$json":{"variable":1,"$url":1,"json":1,"bakery.product":1,"if":1,"invalid":1}
,"set":{"variable":1,"nested":1,"field":1,"type":1}
,"[$url":{"https:\u002F\u002F<":1}
,"https:\u002F\u002F<":{"bakery_domain_name":1}
,"bakery_domain_name":{">\u002Frest\u002Fapi\u002Fproducts":1}
,">\u002Frest\u002Fapi\u002Fproducts":{"insert":1}
,"insert":{"url":1,"data":1}
,"[w":{"ith":1}
,"ith":{"dialog":1}
,"dialog":{"target":1,"set":1}
,"target":{"$$json":1}
,"$url":{"verify":1}
,"verify":{"ssl":1}
,"ssl":{"certificates":1}
,"certificates":{"curl":1}
,"curl":{"options":1}
,"options":{"--data":1}
,"--data":{"list=specials":1}
,"list=specials":{"data":1}
,"returned":{"$$json":1}
,"utility":{"functions":1}
,"handle":{"character":1}
,"character":{"encoding":1,"[n]":1,"set":1}
,"encoding":{"cryptographic":1}
,"cryptographic":{"signing":1}
,"signing":{"required":1}
,"required":{"by":1}
,"by":{"rest":1,"error":1}
,"apis":{"hexdecode":1}
,"hexdecode":{"function":1}
,"function":{"hexencode":1,"textdecode":1,"textencode":1,"base64decode":1,"base64encoderfc":1,"cryptauthcode":1,"cryptdigest":1,"json":1,"adds":1,"parsing":1,"insert":1,"test":1}
,"hexencode":{"function":1}
,"textdecode":{"function":1}
,"textencode":{"function":1}
,"base64decode":{"function":1}
,"base64encoderfc":{"function":1}
,"cryptauthcode":{"function":1}
,"cryptdigest":{"function":1}
,"doesn\u2019t":{"require":1,"exist":1}
,"require":{"spaces":1}
,"spaces":{"line":1}
,"line":{"endings":1,"characters":1}
,"endings":{"elements":1}
,"elements":{"data":1,"index":1,"json":1,"array":1,"object":1,"deleting":1,"handling":1}
,"easier":{"read":1}
,"read":{"while":1}
,"while":{"debug":1,"parsing":1}
,"debug":{"problems":1}
,"problems":{"use":1}
,"jsonformatelements":{"function":1}
,"adds":{"tabs":1,"key-value":1}
,"tabs":{"line":1}
,"characters":{"json":1}
,"get":{"keys":1}
,"keys":{"values":1,"array":1}
,"values":{"entire":1,"json":1,"jsongetelement":1,"add":1}
,"entire":{"json":1}
,"objects":{"arrays":1,"each":1}
,"arrays":{"process":1,"script":1}
,"process":{"further":1}
,"further":{"jsongetelement":1}
,"jsongetelement":{"queries":1,"each":1,"$$json":1}
,"queries":{"json":1}
,"element":{"object":1,"json":1,"index":1,"array":1,"value":1,"changed":1,"doesn\u2019t":1,"jsonsetelement":1,"set":1,"use":1,"product":1}
,"object":{"array":1,"names":1,"index":1,"named":1,"level":1,"new":1,"end":1,"member":1,"therefore":1,"order":1}
,"array":{"value":1,"indexes":1,"first":1,"root":1,"namea":1,"type":1,"$$json":1,"id":1,"product":1,"order":1}
,"value":{"jsonlistkeys":1,"valuecount":1,"if":1,"$i":1,"element":1,"parameter":1,"simple":1,"json":1,"jsonsetelement":1,"fb3":1,"jsongetelement":1,"jsondeleteelement":1,"determine":1,"jsonformatelement":1}
,"jsonlistkeys":{"lists":1,"creates":1,"$$json":1}
,"lists":{"object":1,"values":1}
,"names":{"keys":1,"array":1}
,"indexes":{"json":1,"syntax":1}
,"jsonlistvalues":{"lists":1}
,"first":{"parameter":1,"element":1,"character":1}
,"parameter":{"functions":1,"keyorindexorpath":1,"supported":1,"optional":1,"valid":1,"specifies":1,"existing":1,"json":1}
,"specifies":{"text":1,"portion":1,"existing":1,"type":1}
,"expression":{"valid":1}
,"valid":{"json":1,"use":1}
,"operate":{"second":1,"key":1}
,"second":{"parameter":1}
,"keyorindexorpath":{"specifies":1,"parameter":1,"parameters":1}
,"portion":{"json":1}
,"key":{"name":1,"json":1,"names":1,"object":1,"value":1,"missing":1}
,"name":{"key":1,"root":1,"vanilla":1,"*line":1,"donuts":1,"chocolate":1,"baguette":1}
,"index":{"index":1,"element":1,"path":1,"array":1}
,"path":{"hierarchical":1}
,"hierarchical":{"string":1}
,"string":{"key":1,"number":1}
,"syntax":{"keyorindexorpath":1}
,"supported":{"keyorindexorpath":1,"data":1}
,"optional":{"root":1}
,"root":{"level":1}
,"level":{"if":1,".name":1,".namea.nameb.namec":1,"set":1}
,"if":{"it\u2019s":1,"[$productcount":1,"[$i":1,"change":1,"keyorindexorpath":1,"element":1,"[$id":1,"set":1,"if":1,"error":1,"[left":1,"json":1}
,"it\u2019s":{"first":1}
,"[n]":{"elements":1}
,".name":{"key":1}
,"named":{"name":1,"namec":1}
,".namea.nameb.namec":{"object":1}
,"namec":{"descendent":1}
,"descendent":{"nameb":1}
,"nameb":{"namea":1}
,"namea":{"[3]":1,"[0]":1,"object":1}
,"[3]":{"[2]":1}
,"[2]":{"[1]":1}
,"[1]":{"namea":1}
,"[0]":{"first":1,"id":1}
,"nested":{"arrays":1}
,"determines":{"number":1}
,"number":{"products":1,"complex":1}
,"products":{"json":1}
,"stored":{"$$json":1}
,"creates":{"record":1}
,"record":{"each":1,"values":1}
,"each":{"product":1,"record":1,"data":1,"key-value":1}
,"sets":{"fields":1,"element":1}
,"fields":{"each":1}
,"[$productcount":{"value":1,"loop":1}
,"valuecount":{"jsonlistkeys":1}
,"bakery.product":{"set":1,"[\u0022":1,"[0]":1}
,"[$i":{"value":1,"$productcount":1}
,"loop":{"new":1,"if":1,"end":1,"set":1}
,"new":{"record\u002Frequest":1,"element":1,"product":1,"object":1}
,"record\u002Frequest":{"set":1}
,"[products":{":id":1,":price":1,":stock":1}
,":id":{"jsongetelement":1}
,"[\u0022":{"&$i":1,"id":1,"name":1,"price":1,"stock":1,"category":1,"special":1,"&$nextindex":1}
,"&$i":{"&\u0022]":1}
,"&\u0022]":{"id":1,"price":1,"stock":1,"$newproduct":1,"exit":1}
,"id":{"set":1,"fb4":1,"key":1,"if":1,"returns":1,"fb1":1,"fb2":1,"fb3":1}
,":price":{"jsongetelement":1}
,"price":{"set":1,"17.5":1,"1.99":1,"22.5":1,"3.95":1}
,":stock":{"jsongetelement":1}
,"stock":{"commit":1,"12":1,"43":1,"23":1,"34":1}
,"commit":{"records\u002Frequests":1}
,"records\u002Frequests":{"[with":1}
,"[with":{"dialog":1}
,"$i":{"exit":1}
,"exit":{"loop":1,"script":1}
,"$productcount":{"end":1}
,"end":{"loop":1,"if":1,"product":1}
,"change":{"values":1}
,"add":{"elements":1}
,"jsonsetelement":{"function":1,"sets":1,"[\u0022":1,"$$json":1}
,"parsing":{"json":1}
,"existing":{"element":1}
,"changed":{"if":1}
,"exist":{"new":1}
,"simple":{"string":1}
,"complex":{"object":1}
,"type":{"parameter":1,"data":1,"supported":1,"jsonraw":1}
,"parser":{"follow":1,"bakery":1,"preserves":1}
,"follow":{"strict":1}
,"strict":{"rules":1}
,"rules":{"handling":1}
,"handling":{"each":1,"errors":1}
,"types":{"jsonsetelement":1}
,"formatted":{"valid":1}
,"jsonraw":{"adds":1}
,"key-value":{"pairs":1}
,"pairs":{"new":1,"bakery":1}
,"empty":{"json":1}
,"[$newproduct":{"value":1}
,"fb4":{"jsonstring":1}
,"jsonstring":{"[\u0022":1}
,"vanilla":{"cake":1}
,"cake":{"jsonstring":1,"stock":1}
,"17.5":{"jsonnumber":1}
,"jsonnumber":{"[\u0022":1}
,"12":{"jsonnumber":1}
,"category":{"cakes":1,"breads":1}
,"cakes":{"jsonstring":1,"special":1}
,"special":{"true":1}
,"true":{"jsonboolean":1,"id":1,"json":1}
,"jsonboolean":{"set":1}
,"[$nextindex":{"value":1}
,"[$$json":{"value":1}
,"&$nextindex":{"&\u0022]":1}
,"$newproduct":{"jsonobject":1}
,"jsonobject":{"delete":1}
,"delete":{"element":1}
,"jsondeleteelement":{"function":1,"$$json":1}
,"deletes":{"element":1}
,"fb3":{"$$json":1,"set":1,"price":1}
,"[$id":{"value":1,"=\u0022":1}
,"=\u0022":{"fb3":1,"$$json":1}
,"[text":{"result":1}
,"result":{"end":1}
,"error":{"occurs":1,"message":1}
,"occurs":{"while":1}
,"return":{"by":1,"elements":1}
,"message":{"json":1,"*line":1}
,"missing":{"json":1,"object":1}
,"calculation":{"jsongetelement":1}
,"*line":{"column":1,"13":1}
,"column":{"missing":1,"extra":1}
,"member":{"name":1}
,"13":{"column":1}
,"extra":{"non-whitespace":1}
,"non-whitespace":{"json":1}
,"determine":{"json":1}
,"test":{"first":1}
,"[$result":{"value":1}
,"jsonformatelement":{"$$json":1}
,"[left":{"$result":1}
,"$result":{"=\u0022":1}
,"invalid":{"json":1}
,"[{":{"id":1}
,"fb1":{"name":1}
,"donuts":{"price":1}
,"1.99":{"stock":1}
,"43":{"category":1}
,"breads":{"special":1}
,"fb2":{"price":1}
,"22.5":{"name":1}
,"chocolate":{"cake":1}
,"23":{"category":1}
,"3.95":{"name":1}
,"baguette":{"stock":1}
,"34":{"category":1}
,"preserves":{"order":1}
,"order":{"elements":1,"order":1,"retrieving":1}
,"therefore":{"json":1}
,"retrieving":{"json":1}
,"formatting":{"json":1}
,"changing":{"adding":1}
,"adding":{"json":1}
,"deleting":{"json":1}
,"errors":{"json":1}
}
;Search.control.loadWordPairs(pairs);
