var pairs =
{
"erforming":{"quick":1}
,"quick":{"find":1,"finds":1}
,"find":{"browse":1,"search":1,"current":1,"records":1,"find":1,"mode":1,"box":1,"request":1,"match":1,"term":1}
,"browse":{"mode":1}
,"mode":{"perform":1,"finding":1,"type":1}
,"perform":{"quick":1,"find":1}
,"search":{"across":1,"ox":1,"box":1,"includes":1,"summary":1,"term":1,"history":1}
,"across":{"all":1}
,"all":{"fields":1,"typed":1,"records":1}
,"fields":{"enabled":1,"current":1,"show":1}
,"enabled":{"quick":1}
,"current":{"layout":1}
,"layout":{"find":1,"enabled":1}
,"records":{"match":1,"highlighted":1,"displayed":1,"all":1,"choose":1,"menu":1,"view":1}
,"match":{"set":1,"multiple":1,"phrase":1}
,"set":{"criteria":1,"records":1}
,"criteria":{"perform":1,"browse":1}
,"finding":{"records":1}
,"multiple":{"criteria":1}
,"type":{"search":1,"word":1}
,"ox":{"search":1}
,"box":{"quick":1,"upper-right":1,"filemaker":1,"choose":1}
,"upper-right":{"corner":1}
,"corner":{"status":1}
,"status":{"toolbar":1}
,"toolbar":{"press":1,"portion":1}
,"press":{"enter":1}
,"enter":{"return":1}
,"return":{"search":1}
,"includes":{"all":1}
,"request":{"returns":1}
,"returns":{"found":1}
,"found":{"set":1}
,"highlighted":{"rea":1}
,"rea":{"pie":1}
,"pie":{"chart":1}
,"chart":{"pie":1,"icon":1}
,"icon":{"status":1}
,"portion":{"total":1}
,"total":{"records":1}
,"displayed":{"operator":1}
,"operator":{"supported":1,"double":1}
,"supported":{"by":1}
,"by":{"quick":1}
,"phrase":{"operator":1}
,"double":{"quotation":1}
,"quotation":{"marks":1}
,"marks":{"if":1}
,"if":{"type":1}
,"word":{"search":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"searches":1}
,"searches":{"records":1}
,"typed":{"quick":1}
,"summary":{"container":1}
,"container":{"global":1}
,"global":{"fields":1}
,"show":{"all":1}
,"choose":{"records":1,"search":1}
,"menu":{"show":1}
,"view":{"list":1}
,"list":{"recent":1,"perform":1}
,"recent":{"quick":1}
,"finds":{"arrow":1}
,"arrow":{"search":1}
,"term":{"search":1,"perform":1}
,"history":{"list":1}
}
;Search.control.loadWordPairs(pairs);
