var pairs =
{
"cripting":{"activex":1}
,"activex":{"automation":1,"client":1}
,"automation":{"windows":1,"protocol":1,"support":1,"server":1,"accessed":1,"controller":1,"filemaker":1,"visual":1,"procedure":1,"user\u2019s":1,"search":1}
,"windows":{"windows":1,"applications":1}
,"applications":{"use":1,"accomplish":1,"access":1}
,"use":{"activex":1}
,"protocol":{"expose":1}
,"expose":{"object":1}
,"object":{"models":1}
,"models":{"external":1}
,"external":{"control":1}
,"control":{"activex":1}
,"support":{"filemaker":1}
,"filemaker":{"pro":1,"solution":1,"knowledge":1}
,"pro":{"advanced":1}
,"advanced":{"allows":1,"atabase":1,"scripts":1,"automation":1,"exposes":1,"ability":1,"application":1,"activex":1,"file":1,"script":1,"proficient":1}
,"allows":{"open":1}
,"open":{"close":1,"filemaker":1}
,"close":{"filemaker":1}
,"atabase":{"files":1}
,"files":{"toggle":1}
,"toggle":{"application\u2019s":1}
,"application\u2019s":{"visibility":1}
,"visibility":{"run":1}
,"run":{"filemaker":1}
,"scripts":{"filemaker":1}
,"server":{"objects":1}
,"objects":{"filemaker":1}
,"exposes":{"automation":1}
,"accessed":{"by":1}
,"by":{"activex":1,"calling":1}
,"client":{"automation":1}
,"controller":{"including":1}
,"including":{"visual":1}
,"visual":{"basic":1}
,"basic":{"programming":1,"create":1,"button":1,"scripting":1}
,"programming":{"tools":1,"language":1}
,"tools":{"primary":1}
,"primary":{"benefit":1}
,"benefit":{"activex":1}
,"ability":{"initiate":1}
,"initiate":{"filemaker":1}
,"application":{"filemaker":1,"own":1}
,"create":{"own":1}
,"own":{"application":1,"interface":1}
,"interface":{"drive":1}
,"drive":{"multiple":1}
,"multiple":{"applications":1}
,"accomplish":{"task":1}
,"task":{"define":1}
,"define":{"window":1}
,"window":{"visual":1}
,"button":{"get":1}
,"get":{"today\u2019s":1}
,"today\u2019s":{"sales":1}
,"sales":{"data":1}
,"data":{"procedure":1,"open":1,"automation":1,"allow":1}
,"procedure":{"get":1,"start":1}
,"file":{"by":1}
,"calling":{"filemaker":1}
,"script":{"find":1}
,"find":{"export":1}
,"export":{"all":1}
,"all":{"day\u0027s":1}
,"day\u0027s":{"sales":1}
,"start":{"up":1}
,"up":{"excel":1}
,"excel":{"graph":1}
,"graph":{"exported":1}
,"exported":{"data":1}
,"allow":{"applications":1}
,"access":{"filemaker":1}
,"solution":{"activex":1}
,"user\u2019s":{"account":1}
,"account":{"fmextscriptaccess":1}
,"fmextscriptaccess":{"extended":1}
,"extended":{"privilege":1,"privileges":1}
,"privilege":{"enabled":1,"set":1}
,"enabled":{"diting":1}
,"diting":{"extended":1}
,"privileges":{"privilege":1}
,"set":{"implement":1}
,"implement":{"activex":1}
,"proficient":{"programming":1}
,"language":{"visual":1}
,"scripting":{"activex":1}
,"search":{"filemaker":1}
,"knowledge":{"base":1}
}
;Search.control.loadWordPairs(pairs);
