var pairs =
{
"creating":{"filemaker":1,"first":1,"managing":1}
,"filemaker":{"pro":1,"knowledge":1}
,"pro":{"advanced":1}
,"advanced":{"file":1,"cr":1,"sample":1,"contacts":1,"new":1,"filenames":1}
,"file":{"cr":1,"custom":1,"create":1,"data":1,"format":1,"se":1,"new":1,"choose":1,"menu":1}
,"cr":{"eate":1}
,"eate":{"file":1,"empty":1}
,"custom":{"app":1,"apps":1}
,"app":{"based":1,"categories":1,"main":1,"racks":1,"ort":1,"browse":1,"easily":1,"ee":1,"rowse":1,"adding":1,"ased":1,"sample":1,"create":1,"new":1}
,"based":{"predefined":1}
,"predefined":{"starter":1,"app":1}
,"starter":{"apps":1,"app":1}
,"apps":{"sample":1,"filemaker":1,"simple":1,"track":1,"related":1,"advanced":1,"show":1,"choose":1}
,"sample":{"apps":1,"app":1}
,"empty":{"file":1}
,"create":{"ables":1,"new":1,"filemaker":1,"type":1,"custom":1}
,"ables":{"fields":1,"define":1}
,"fields":{"layouts":1,"defined":1,"choose":1,"add":1,"field":1}
,"layouts":{"co":1,"apps":1,"contacts":1,"reports":1}
,"co":{"nvert":1}
,"nvert":{"file":1}
,"data":{"file":1,"custom":1,"define":1}
,"format":{"excel":1}
,"excel":{"file":1}
,"se":{"onverting":1}
,"onverting":{"data":1}
,"new":{"filemaker":1,"choose":1,"custom":1,"empty":1}
,"choose":{"file":1,"predefined":1,"folder":1,"blank":1,"options":1}
,"menu":{"create":1}
,"categories":{"ca":1}
,"ca":{"tegory":1}
,"tegory":{"description":1}
,"description":{"starter":1}
,"simple":{"apps":1}
,"track":{"multiple":1}
,"multiple":{"related":1,"street":1}
,"related":{"items":1,"tables":1,"records":1}
,"items":{"place":1}
,"place":{"start":1}
,"start":{"creating":1}
,"first":{"custom":1}
,"main":{"table":1}
,"table":{"records":1}
,"records":{"displayed":1,"custom":1}
,"displayed":{"list":1,"portals":1}
,"list":{"details":1,"print":1}
,"details":{"layouts":1}
,"tables":{"records":1,"display":1,"custom":1,"define":1,"related":1,"close":1}
,"portals":{"additional":1,"sample":1}
,"additional":{"layouts":1}
,"contacts":{"starter":1,"each":1,"sample":1,"list":1}
,"racks":{"contacts":1}
,"each":{"ave":1}
,"ave":{"multiple":1}
,"street":{"ddresses":1}
,"ddresses":{"phone":1}
,"phone":{"numbers":1}
,"numbers":{"email":1}
,"email":{"addresses":1}
,"addresses":{"displayed":1}
,"show":{"what\u2019s":1}
,"what\u2019s":{"create":1}
,"ort":{"nd":1}
,"nd":{"filter":1}
,"filter":{"contacts":1}
,"print":{"ddress":1}
,"ddress":{"labels":1}
,"labels":{"create":1}
,"type":{"name":1}
,"name":{"file":1}
,"folder":{"if":1}
,"if":{"save":1}
,"save":{"filemaker":1}
,"browse":{"mode":1}
,"mode":{"create":1,"displays":1,"add":1,"defining":1}
,"easily":{"add":1}
,"add":{"add-on":1,"ables":1,"objects":1,"data":1,"field":1}
,"add-on":{"tables":1}
,"display":{"related":1}
,"ee":{"dding":1}
,"dding":{"add-on":1}
,"blank":{"create":1}
,"rowse":{"mode":1}
,"displays":{"manage":1}
,"manage":{"database":1}
,"database":{"dialog":1,"tables":1}
,"dialog":{"box":1}
,"box":{"define":1,"defining":1,"optional":1}
,"define":{"ields":1,"fields":1,"elationships":1}
,"ields":{"default":1}
,"default":{"fields":1}
,"defined":{"defining":1}
,"defining":{"database":1,"changing":1}
,"options":{"defining":1}
,"changing":{"fields":1}
,"elationships":{"manage":1}
,"close":{"manage":1}
,"optional":{"switch":1}
,"switch":{"layout":1}
,"layout":{"mode":1,"creating":1}
,"objects":{"layout":1}
,"managing":{"layouts":1}
,"reports":{"browse":1}
,"adding":{"viewing":1}
,"viewing":{"data":1}
,"field":{"tab":1,"create":1}
,"tab":{"layout":1,"avoid":1}
,"avoid":{"filemaker":1}
,"filenames":{"period":1}
,"period":{"filename":1,"fmp12":1}
,"filename":{"include":1,"extension":1}
,"include":{"period":1}
,"fmp12":{"filename":1}
,"extension":{"quotation":1}
,"quotation":{"mark":1}
,"mark":{"slash":1,"colon":1}
,"slash":{"(\u002F)":1}
,"(\u002F)":{"backslash":1}
,"backslash":{"(\u005C)":1}
,"(\u005C)":{"angle":1}
,"angle":{"brackets":1}
,"brackets":{"asterisk":1}
,"asterisk":{"(*)":1}
,"(*)":{"question":1}
,"question":{"mark":1}
,"colon":{"vertical":1}
,"vertical":{"bar":1}
,"bar":{"filemaker":1}
,"knowledge":{"base":1}
,"base":{"add":1}
,"ased":{"starter":1}
}
;Search.control.loadWordPairs(pairs);
