var pairs =
{
"get":{"scriptparame":1,"scriptparameter":1,"script":1,"passed":1}
,"scriptparame":{"ter":1}
,"ter":{"returns":1}
,"returns":{"script":1}
,"script":{"parameter":1,"get":1,"script":1,"parameters":1,"via":1,"trigger":1,"perform":1,"step":1,"attached":1,"[specified":1,"current":1}
,"parameter":{"passed":1,"navigates":1,"invoices":1,"get":1,"main":1}
,"passed":{"current":1,"script":1,"parameter":1}
,"current":{"script":1,"customer":1}
,"scriptparameter":{"none":1,"\u0022]":1,")]":1,"style":1,"get":1}
,"none":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"7.0":1}
,"7.0":{"use":1}
,"use":{"function":1}
,"function":{"part":1}
,"part":{"calculation":1}
,"calculation":{"evaluated":1}
,"evaluated":{"script":1}
,"parameters":{"passed":1}
,"via":{"button":1}
,"button":{"script":1}
,"trigger":{"script":1}
,"perform":{"script":1}
,"step":{"clears":1}
,"clears":{"contents":1}
,"contents":{"field":1,"multiple":1}
,"field":{"script":1,"if":1,"object\u2019s":1,"name":1,"clear":1,"by":1,"parameter":1}
,"navigates":{"field":1}
,"if":{"field":1}
,"object\u2019s":{"name":1}
,"name":{"field":1,"naming":1,"[get":1,"get":1}
,"naming":{"objects":1}
,"objects":{"script":1}
,"attached":{"multiple":1}
,"multiple":{"buttons":1,"fields":1}
,"buttons":{"each":1}
,"each":{"referencing":1}
,"referencing":{"field":1}
,"clear":{"contents":1}
,"fields":{"set":1}
,"set":{"field":1}
,"by":{"name":1}
,"[get":{"scriptparameter":1}
,"\u0022]":{"go":1,"sort":1}
,"go":{"object":1,"layout":1}
,"object":{"[object":1}
,"[object":{"name":1}
,")]":{"invoices":1}
,"invoices":{":customer":1,"current":1,"sub-script":1,"parameter":1}
,":customer":{"name":1,"id]":1,"name]":1}
,"customer":{"returned":1,"invoices":1,"&get":1}
,"returned":{"new":1}
,"new":{"window":1}
,"window":{"invoice":1,"[name":1}
,"invoice":{"report":1}
,"report":{"layout":1,"\u0022]":1}
,"layout":{"find":1,"[\u0022":1}
,"find":{"matching":1}
,"matching":{"records":1}
,"records":{"[replace":1,"[restore":1}
,"[replace":{"invoices":1}
,"id]":{"calls":1}
,"calls":{"view":1}
,"view":{"customer":1}
,"sub-script":{"defined":1,"view":1}
,"defined":{"perform":1}
,"[specified":{"list":1}
,"list":{"view":1}
,"name]":{"new":1}
,"[name":{"customer":1}
,"&get":{"scriptparameter":1}
,"style":{"document]":1}
,"document]":{"go":1}
,"[\u0022":{"invoice":1}
,"sort":{"records":1}
,"[restore":{"dialog":1}
,"dialog":{"off]":1}
,"off]":{"get":1}
,"main":{"script":1}
}
;Search.control.loadWordPairs(pairs);
