var pairs =
{
"scroll":{"window":1}
,"window":{"crolls":1,"layout":1,"end":1,"up":1,"creates":1,"[end]":1,"perform":1,"[home]":1}
,"crolls":{"window":1}
,"layout":{"vertically":1,"brings":1,"scrolls":1,"[\u0022":1}
,"vertically":{"brings":1}
,"brings":{"current":1}
,"current":{"field":1}
,"field":{"view":1,"filemaker":1}
,"view":{"end":1,"tabbing":1,"invoices":1}
,"end":{"page":1,"up":1}
,"page":{"up":1,"scrolls":1,"page":1,"selection":1}
,"up":{"page":1,"scrolls":1}
,"scrolls":{"window":1,"top":1,"bottom":1}
,"selection":{"brings":1}
,"tabbing":{"field":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"script":1}
,"script":{"step":1}
,"step":{"scrolls":1}
,"top":{"bottom":1,"window":1}
,"bottom":{"layout":1,"window":1}
,"invoices":{"layout":1,"\u0022]":1}
,"creates":{"new":1}
,"new":{"record":1,"record\u002Frequest":1}
,"record":{"go":1}
,"go":{"layout":1}
,"[\u0022":{"invoices":1}
,"\u0022]":{"scroll":1}
,"[end]":{"new":1}
,"record\u002Frequest":{"performs":1}
,"performs":{"find":1}
,"find":{"sorts":1,"[restore]":1}
,"sorts":{"scrolls":1}
,"perform":{"find":1}
,"[restore]":{"sort":1}
,"sort":{"records":1}
,"records":{"[restore":1}
,"[restore":{"dialog":1}
,"dialog":{"off]":1}
,"off]":{"scroll":1}
,"[home]":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
