var pairs =
{
"saving":{"reverting":1}
,"reverting":{"layout":1}
,"layout":{"design":1,"layout":1,"mode":1,"part":1,"objects":1,"previewed":1,"browse":1,"close":1,"theme":1,"automatically":1,"preferences":1,"extensive":1}
,"design":{"layout":1}
,"mode":{"save":1,"continue":1,"etting":1}
,"save":{"don\u2019t":1,"revert":1,"layout":1}
,"don\u2019t":{"wait":1}
,"wait":{"finish":1}
,"finish":{"save":1}
,"revert":{"undo":1}
,"undo":{"layouts":1,"redo":1}
,"layouts":{"use":1,"edit":1,"changing":1}
,"use":{"commands":1}
,"commands":{"layouts":1}
,"edit":{"menus":1}
,"menus":{"undo":1}
,"redo":{"layouts":1}
,"changing":{"layout":1}
,"part":{"moving":1}
,"moving":{"resizing":1}
,"resizing":{"layout":1}
,"objects":{"you\u2019ve":1}
,"you\u2019ve":{"saved":1}
,"saved":{"layout":1}
,"previewed":{"layout":1}
,"browse":{"mode":1}
,"continue":{"redoing":1}
,"redoing":{"switch":1}
,"switch":{"layout":1}
,"close":{"window":1}
,"window":{"user":1,"layout":1}
,"user":{"window":1}
,"theme":{"shared":1}
,"shared":{"file":1}
,"file":{"set":1}
,"set":{"application":1}
,"application":{"preference":1}
,"preference":{"save":1}
,"automatically":{"leave":1}
,"leave":{"layout":1}
,"etting":{"layout":1}
,"preferences":{"it\u2019s":1}
,"it\u2019s":{"idea":1}
,"idea":{"duplicate":1}
,"duplicate":{"layout":1}
}
;Search.control.loadWordPairs(pairs);
