var pairs =
{
"validating":{"data":1}
,"data":{"during":1,"existing":1,"validated":1,"target":1,"mporting":1,"uerying":1,"source":1,"validation":1}
,"during":{"import":1}
,"import":{"import":1,"data":1,"filemaker":1,"operation":1,"process":1,"ummary":1,"table":1,"note":1,"reasons":1,"action":1,"validate":1}
,"existing":{"filemaker":1,"file":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"ile":1,"skip":1,"import":1,"attempts":1}
,"ile":{"validate":1}
,"validate":{"data":1}
,"skip":{"importing":1}
,"importing":{"records":1,"defined":1}
,"records":{"fields":1}
,"fields":{"don\u2019t":1,"import":1,"want":1,"defining":1,"skipped":1,"record":1,"during":1}
,"don\u2019t":{"match":1}
,"match":{"validation":1}
,"validation":{"requirements":1,"options":1,"use":1,"option":1,"occurs":1,"failures":1,"fails":1,"errors":1}
,"requirements":{"report":1}
,"report":{"number":1}
,"number":{"skipped":1,"records":1}
,"skipped":{"records":1,"during":1,"item":1,"record":1,"all":1,"field":1}
,"operation":{"complete":1}
,"complete":{"target":1,"check":1}
,"target":{"file":1}
,"file":{"define":1,"follow":1,"mporting":1}
,"define":{"validation":1}
,"options":{"fields":1,"empty":1,"evaluated":1}
,"want":{"imported":1}
,"imported":{"data":1}
,"validated":{"during":1,"by":1}
,"process":{"defining":1,"complete":1}
,"defining":{"validation":1,"field":1}
,"field":{"validation":1,"skipped":1,"defined":1,"field":1,"you\u2019re":1,"prevent":1}
,"use":{"validation":1}
,"option":{"ensure":1,"validation":1}
,"ensure":{"validation":1}
,"occurs":{"during":1}
,"follow":{"instructions":1}
,"instructions":{"sections":1}
,"sections":{"import":1}
,"mporting":{"data":1,"folder":1,"xml":1}
,"folder":{"files":1}
,"files":{"all":1}
,"all":{"mporting":1,"validation":1,"field":1}
,"xml":{"data":1}
,"uerying":{"odbc":1}
,"odbc":{"data":1}
,"source":{"filemaker":1}
,"check":{"import":1}
,"ummary":{"dialog":1}
,"dialog":{"box":1}
,"box":{"number":1}
,"table":{"describes":1}
,"describes":{"data":1}
,"failures":{"record":1,"entire":1}
,"record":{"field":1,"during":1,"therefore":1,"skipped":1,"imported":1}
,"item":{"skipped":1}
,"defined":{"empty":1,"field":1}
,"empty":{"validated":1}
,"by":{"calculation":1}
,"calculation":{"field":1,"options":1}
,"fails":{"record":1,"during":1}
,"note":{"all":1,"skipped":1}
,"evaluated":{"filemaker":1}
,"attempts":{"commit":1}
,"commit":{"each":1}
,"each":{"record":1,"field":1}
,"therefore":{"types":1}
,"types":{"validation":1}
,"entire":{"record":1}
,"you\u2019re":{"importing":1}
,"prevent":{"fields":1}
,"errors":{"eason":1}
,"eason":{"hat":1}
,"hat":{"records":1}
,"reasons":{"step":1}
,"step":{"11":1}
,"11":{"etting":1}
,"etting":{"import":1}
,"action":{"mapping":1}
,"mapping":{"fields":1}
}
;Search.control.loadWordPairs(pairs);
