var pairs =
{
"position":{"returns":1,"occurrence":1,"text":1,"mississippi":1,"name":1}
,"returns":{"starting":1,"result":1,"position":1,"left":1,"william":1,"smith":1}
,"starting":{"position":1}
,"occurrence":{"searchstring":1,"text":1,"-any":1,"positive":1,"negative":1,"invalid":1,"zero":1}
,"searchstring":{"text":1,"start":1,"-any":1,"isn\u2019t":1}
,"text":{"position":1,"searchstring":1,"-any":1,"expression":1,"field":1,"string":1,"if":1}
,"start":{"occurrence":1,"-any":1,"text":1,"value":1}
,"-any":{"text":1,"numeric":1}
,"expression":{"text":1,"field":1}
,"field":{"searchstring":1,"representing":1,"number":1,"william":1}
,"representing":{"set":1,"number":1,"instance":1}
,"set":{"characters":1}
,"characters":{"want":1,"start":1}
,"want":{"find":1}
,"find":{"start":1,"scan":1}
,"numeric":{"expression":1}
,"number":{"representing":1,"characters":1,"filemaker":1}
,"string":{"search":1,"occurrence":1,"want":1,"if":1,"zero":1}
,"search":{"start":1,"first":1}
,"value":{"less":1,"if":1,"occurrence":1}
,"less":{"search":1}
,"first":{"character":1}
,"character":{"text":1}
,"instance":{"text":1}
,"scan":{"start":1,"continues":1}
,"if":{"occurrence":1,"searchstring":1}
,"positive":{"continues":1}
,"continues":{"end":1,"text":1}
,"end":{"text":1}
,"negative":{"scan":1}
,"zero":{"value":1,"number":1,"returned":1}
,"invalid":{"returns":1}
,"result":{"zero":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"function":1}
,"function":{"case":1}
,"case":{"sensitive":1}
,"sensitive":{"if":1}
,"isn\u2019t":{"contained":1}
,"contained":{"text":1}
,"returned":{"position":1}
,"mississippi":{"iss":1}
,"iss":{"returns":1}
,"left":{"name":1}
,"name":{"position":1,"-1":1,"text":1,"length":1,"-position":1}
,"-1":{"returns":1}
,"william":{"name":1,"smith":1}
,"smith":{"right":1}
,"right":{"name":1}
,"length":{"name":1}
,"-position":{"name":1}
}
;Search.control.loadWordPairs(pairs);
