var pairs =
{
"etting":{"options":1,"up":1}
,"options":{"fields":1,"define":1,"entering":1,"japanese":1,"all":1,"calculation":1,"find":1}
,"fields":{"set":1,"entering":1,"store":1,"add":1,"filemaker":1}
,"set":{"field":1,"options":1,"indexing":1}
,"field":{"options":1,"time":1,"indexing":1,"types":1}
,"define":{"field":1}
,"time":{"set":1}
,"entering":{"default":1,"data":1}
,"default":{"data":1}
,"data":{"fields":1,"fast":1,"validation":1,"storing":1,"externally":1,"entry":1,"if":1}
,"fast":{"accurate":1}
,"accurate":{"consistent":1}
,"consistent":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"perform":1,"update":1}
,"perform":{"calculation":1}
,"calculation":{"automatically":1,"fields":1}
,"automatically":{"format":1}
,"format":{"phone":1}
,"phone":{"number":1}
,"number":{"checking":1}
,"checking":{"data":1}
,"validation":{"requirements":1,"repeating":1}
,"requirements":{"repeating":1}
,"repeating":{"field":1,"storage":1}
,"indexing":{"storing":1,"options":1,"storage":1}
,"storing":{"data":1,"container":1,"global":1}
,"container":{"data":1,"fields":1}
,"externally":{"etting":1,"storing":1}
,"up":{"container":1}
,"store":{"data":1}
,"global":{"value":1}
,"value":{"setting":1}
,"setting":{"furigana":1}
,"furigana":{"input":1}
,"input":{"options":1}
,"japanese":{"language":1}
,"language":{"fields":1}
,"add":{"change":1}
,"change":{"remove":1,"field":1,"data":1}
,"remove":{"data":1}
,"entry":{"validation":1}
,"storage":{"indexing":1,"options":1}
,"all":{"field":1}
,"types":{"except":1}
,"except":{"summary":1}
,"summary":{"set":1}
,"update":{"existing":1}
,"existing":{"records":1}
,"records":{"if":1,"change":1}
,"if":{"change":1}
,"find":{"existing":1}
}
;Search.control.loadWordPairs(pairs);
