var pairs =
{
"textencode":{"returns":1,"text":1,"table":1}
,"returns":{"text":1,"encoding":1,"returns":1}
,"text":{"file":1,"character":1,"encoding":1,"-any":1,"expression":1,"utf-8":1,"field":1}
,"file":{"container":1,"set":1}
,"container":{"data":1,"filemaker":1,"field":1}
,"data":{"text":1}
,"character":{"encoding":1}
,"encoding":{"line":1,"lineendings":1,"-the":1,"use":1,"parameter":1,"if":1,"encodes":1,"leaves":1,"windows":1}
,"line":{"endings":1,"feed":1}
,"endings":{"textencode":1,"use":1,"left":1,"unchanged":1,"exports":1}
,"lineendings":{"text":1,"-a":1,"parameter":1,"line":1}
,"-any":{"text":1}
,"expression":{"field":1}
,"field":{"encoding":1,"japanese":1,"iso-8859-1":1,"text":1,"[table":1,"contents":1}
,"-the":{"name":1}
,"name":{"character":1}
,"use":{"lineendings":1,"if":1,"names":1,"value":1,"values":1,"unrecognized":1}
,"-a":{"number":1}
,"number":{"specifies":1}
,"specifies":{"line":1}
,"if":{"line":1,"use":1}
,"left":{"unchanged":1}
,"unchanged":{"container":1,"lineendings":1,"carriage":1,"textencode":1}
,"filemaker":{"pro":1}
,"pro":{"16.0":1}
,"16.0":{"encoding":1}
,"parameter":{"use":1}
,"names":{"character":1}
,"value":{"unrecognized":1,"function":1,"line":1}
,"unrecognized":{"value":1}
,"function":{"returns":1,"supported":1}
,"encodes":{"text":1}
,"utf-8":{"unicode":1}
,"unicode":{"iso-8859-1":1}
,"iso-8859-1":{"latin":1,"character":1,"export":1}
,"latin":{"windows-1251":1}
,"windows-1251":{"cyrillic":1}
,"cyrillic":{"shift_jis":1}
,"shift_jis":{"japanese":1,"converts":1}
,"japanese":{"windows-1252":1,"character":1}
,"windows-1252":{"windows":1}
,"windows":{"gb18030":1,"standard":1,"line":1}
,"gb18030":{"simplified":1}
,"simplified":{"chinese":1}
,"chinese":{"euc-kr":1,"macintosh":1}
,"euc-kr":{"korean":1}
,"korean":{"big5":1}
,"big5":{"traditional":1}
,"traditional":{"chinese":1}
,"macintosh":{"mac":1}
,"mac":{"roman":1,"standard":1,"unix\u002Flinux":1}
,"roman":{"lineendings":1}
,"values":{"line":1}
,"carriage":{"return":1}
,"return":{"legacy":1,"by":1}
,"legacy":{"mac":1}
,"standard":{"line":1,"carriage":1,"function":1}
,"feed":{"modern":1,"windows":1}
,"modern":{"mac":1}
,"unix\u002Flinux":{"standard":1}
,"by":{"line":1}
,"supported":{"runtime":1}
,"runtime":{"solutions":1}
,"solutions":{"returns":1}
,"leaves":{"line":1}
,"table":{":text":1}
,":text":{"shift_jis":1,"iso-8859-1":1}
,"converts":{"contents":1}
,"contents":{"text":1,"[table":1}
,"exports":{"container":1}
,"set":{"field":1}
,"[table":{":container":1}
,":container":{"textencode":1,"output.txt":1}
,"export":{"field":1}
,"output.txt":{"create":1}
,"create":{"folders":1}
,"folders":{"off]":1}
}
;Search.control.loadWordPairs(pairs);
