var pairs =
{
"get":{"allowformattingbar":1,"allowformattingbarstate":1,"allow":1,"formatting":1}
,"allowformattingbar":{"state":1}
,"state":{"returns":1,"filemaker":1,"get":1,"allow":1}
,"returns":{"true":1,"false":1,"returns":1,"if":1}
,"true":{"if":1}
,"if":{"formatting":1}
,"formatting":{"bar":1}
,"bar":{"allowed":1,"script":1,"state":1}
,"allowed":{"visible":1}
,"visible":{"returns":1,"get":1}
,"false":{"get":1}
,"allowformattingbarstate":{"none":1,"get":1}
,"none":{"number":1}
,"number":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"8.0":1}
,"8.0":{"allow":1}
,"allow":{"formatting":1}
,"script":{"step":1}
,"step":{"sets":1}
,"sets":{"formatting":1}
,"webdirect":{"function":1}
,"function":{"supported":1}
,"supported":{"returns":1}
}
;Search.control.loadWordPairs(pairs);
