var pairs =
{
"last":{"returns":1,"valid":1,"repeatingfield":1,"non-blank":1,"related":1,"function":1,"parcelbids":1,"payments":1,"matching":1,"if":1,"non-empty":1}
,"returns":{"last":1,"reference":1,"value":1,"1500":1,"payment":1}
,"valid":{"non-blank":1}
,"non-blank":{"value":1,"repetition":1}
,"value":{"field":1,"related":1,"depend":1,"based":1}
,"field":{"last":1,"related":1,"expression":1,"text":1,"returns":1,"defined":1,"personalphone":1,"empty":1,"workphone":1}
,"repeatingfield":{"repeatingfield":1,"-any":1,"specifies":1}
,"-any":{"repeating":1}
,"repeating":{"field":1}
,"related":{"field":1,"set":1,"value":1,"records":1}
,"expression":{"returns":1}
,"reference":{"repeating":1}
,"text":{"number":1}
,"number":{"date":1,"field":1,"repeating":1}
,"date":{"time":1,"last":1}
,"time":{"timestamp":1}
,"timestamp":{"container":1}
,"container":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"if":1}
,"if":{"repeatingfield":1,"related":1,"parcelbids":1,"isempty":1,"company":1}
,"specifies":{"repeating":1,"related":1}
,"repetition":{"if":1}
,"set":{"last":1}
,"depend":{"related":1}
,"records":{"sorted":1,"last":1}
,"sorted":{"if":1,"last":1}
,"function":{"returns":1}
,"based":{"creation":1}
,"creation":{"order":1}
,"order":{"records":1}
,"parcelbids":{"returns":1,"number":1}
,"1500":{"if":1,"last":1}
,"defined":{"repeat":1}
,"repeat":{"values":1}
,"values":{"values":1,"2500":1}
,"2500":{"1200":1}
,"1200":{"1500":1}
,"payments":{":paymentdate":1,"table":1}
,":paymentdate":{"returns":1}
,"payment":{"date":1}
,"matching":{"record":1}
,"record":{"payments":1}
,"table":{"last":1}
,"isempty":{"company":1}
,"company":{"personalphone":1,"field":1}
,"personalphone":{"workphone":1,"company":1}
,"workphone":{"returns":1}
,"non-empty":{"phone":1}
,"phone":{"number":1}
,"empty":{"if":1,"function":1}
}
;Search.control.loadWordPairs(pairs);
