var pairs =
{
"previewing":{"data":1}
,"data":{"layout":1}
,"layout":{"switch":1,"appears":1,"bar":1,"move":1}
,"switch":{"preview":1}
,"preview":{"mode":1,"printing":1,"layout":1,"data":1}
,"mode":{"layout":1,"erify":1,"use":1,"choose":1,"preview":1}
,"appears":{"printed":1}
,"printed":{"page":1}
,"page":{"printing":1,"viewing":1}
,"printing":{"record":1}
,"record":{"can\u2019t":1,"preview":1,"use":1}
,"can\u2019t":{"enter":1}
,"enter":{"edit":1}
,"edit":{"fields":1}
,"fields":{"preview":1}
,"erify":{"found":1}
,"found":{"set":1}
,"set":{"records":1}
,"records":{"want":1,"menu":1}
,"want":{"preview":1}
,"bar":{"browse":1,"move":1}
,"browse":{"mode":1}
,"use":{"navigation":1,"vertical":1}
,"navigation":{"controls":1,"parts":1}
,"controls":{"status":1,"preview":1}
,"status":{"toolbar":1}
,"toolbar":{"navigation":1}
,"choose":{"records":1}
,"menu":{"go":1}
,"go":{"record":1,"end":1}
,"vertical":{"scroll":1}
,"scroll":{"bar":1}
,"move":{"up":1,"pages":1}
,"up":{"page":1}
,"viewing":{"go":1}
,"end":{"report":1}
,"report":{"total":1}
,"total":{"number":1}
,"number":{"pages":1}
,"pages":{"accurately":1,"preview":1}
,"accurately":{"displayed":1}
,"displayed":{"laceholder":1}
,"laceholder":{"text":1}
,"text":{"visible":1}
,"visible":{"navigation":1}
,"parts":{"display":1}
,"display":{"preview":1}
}
;Search.control.loadWordPairs(pairs);
