var pairs =
{
"arrange":{"all":1}
,"all":{"windows":1,"open":1,"front":1,"filemaker":1}
,"windows":{"djusts":1,"tile":1,"left\u002Fright":1,"resized":1,"top\u002Fbottom":1,"overlapping":1,"front":1,"change":1,"[cascade":1,"arranges":1,"[tile":1}
,"djusts":{"size":1}
,"size":{"location":1}
,"location":{"all":1,"open":1}
,"open":{"windows":1,"filemaker":1}
,"tile":{"horizontally":1,"vertically":1}
,"horizontally":{"positions":1}
,"positions":{"open":1,"windows":1}
,"left\u002Fright":{"orientation":1}
,"orientation":{"windows":1}
,"resized":{"prevent":1,"fill":1,"filemaker":1}
,"prevent":{"overlapping":1}
,"overlapping":{"tile":1,"cascade":1,"pattern":1}
,"vertically":{"positions":1}
,"top\u002Fbottom":{"orientation":1}
,"cascade":{"window":1}
,"window":{"positions":1,"active":1,"invoices":1,"[style":1}
,"pattern":{"top-left":1,"new":1}
,"top-left":{"corner":1}
,"corner":{"screen":1}
,"screen":{"windows":1,"less":1}
,"fill":{"screen":1}
,"less":{"offset":1}
,"offset":{"bring":1}
,"bring":{"all":1}
,"front":{"oves":1,"windows":1}
,"oves":{"all":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1,"6.0":1}
,"advanced":{"windows":1}
,"6.0":{"earlier":1}
,"earlier":{"size":1}
,"change":{"current":1}
,"current":{"table":1}
,"table":{"active":1}
,"active":{"window":1,"record":1}
,"record":{"by":1}
,"by":{"script":1}
,"script":{"step":1}
,"step":{"new":1}
,"new":{"window":1}
,"invoices":{"layout":1,"invoices":1,")]":1}
,"layout":{"arranges":1,"invoices":1,"customers":1}
,"arranges":{"all":1,"op":1}
,"[style":{"document":1}
,"document":{"name":1}
,"name":{"invoice":1,"customer":1}
,"invoice":{"list":1}
,"list":{"layout":1}
,")]":{"arrange":1,"new":1}
,"[cascade":{"window]":1}
,"window]":{"two":1}
,"two":{"windows":1}
,"op":{"bottom":1}
,"bottom":{"new":1}
,"customer":{"list":1}
,"customers":{"customers":1,")]":1}
,"[tile":{"vertically]":1}
,"vertically]":{"saving":1}
,"saving":{"copying":1}
,"copying":{"files":1}
,"files":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
