var pairs =
{
"get":{"activeselections":1,"activeselectionsize":1,"active":1,"selection":1,"current":1}
,"activeselections":{"ize":1}
,"ize":{"returns":1}
,"returns":{"number":1,"filemaker":1,"empty":1,"characters":1}
,"number":{"representing":1,"filemaker":1}
,"representing":{"characters":1}
,"characters":{"selected":1}
,"selected":{"get":1,"text":1}
,"activeselectionsize":{"none":1,"get":1}
,"none":{"number":1}
,"filemaker":{"pro":1,"webdirect":1,"go":1}
,"pro":{"7.0":1}
,"7.0":{"if":1}
,"if":{"selection":1,"field":1,"selected":1}
,"selection":{"active":1,"size":1}
,"active":{"field":1,"returns":1,"selection":1}
,"field":{"re":1,"active":1}
,"re":{"if":1}
,"webdirect":{"function":1}
,"function":{"supported":1,"return":1}
,"supported":{"returns":1}
,"empty":{"string":1}
,"string":{"filemaker":1}
,"go":{"function":1}
,"return":{"inaccurate":1}
,"inaccurate":{"value":1}
,"value":{"if":1}
,"text":{"concealed":1}
,"concealed":{"edit":1}
,"edit":{"box":1}
,"box":{"returns":1}
,"size":{"get":1,"active":1}
,"current":{"selection":1}
}
;Search.control.loadWordPairs(pairs);
