var pairs =
{
"eyboard":{"shortcuts":1}
,"shortcuts":{"macos":1,"perform":1,"creating":1,"navigate":1,"move":1,"mission":1,"moving":1,"all":1,"enter":1,"window":1,"insert":1}
,"macos":{"keyboard":1,"mission":1,"navigation":1}
,"keyboard":{"shortcuts":1,"space":1}
,"perform":{"tasks":1,"first":1}
,"tasks":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"note":1,"help":1,"saves":1,"change":1,"odes":1,"application":1}
,"note":{"reate":1,"database":1,"select":1}
,"reate":{"own":1}
,"own":{"eyboard":1}
,"creating":{"editing":1}
,"editing":{"custom":1}
,"custom":{"menu":1}
,"menu":{"item":1,"command":1}
,"item":{"keyboard":1,"list":1}
,"navigate":{"edit":1}
,"edit":{"cancel":1}
,"cancel":{"operation":1,"running":1}
,"operation":{"display":1,"dialog":1}
,"display":{"database":1,"keyboard":1}
,"database":{"ile":1,"dialog":1,"designer":1}
,"ile":{"press":1}
,"press":{"cancel":1,"next":1,"close":1,"current":1,"text":1,"replace":1,"command":1}
,"dialog":{"box":1}
,"box":{"esc":1,"command":1,"includes":1,"press":1}
,"esc":{"cancel":1,"selected":1,"close":1}
,"running":{"script":1}
,"script":{"command":1,"workspace":1}
,"command":{"period":1,"-w":1,"-q":1,"-?":1,"-option-o":1,"-shift-o":1,"-o":1,"-shift-d":1,"-shift-f":1,"-shift-l":1,"print":1,"-p":1,"-option-p":1,"-s":1,"command":1,"-z":1,"-shift-s":1,"-1":1,"-0":1,"-n":1,"-e":1,"-option-e":1,"-d":1,"-option-z":1,"-option-s":1,"-m":1,"-h":1,"-shift-+":1,"-+":1,"--(":1,"current":1,"-shift-n":1,"-i":1,"apostrophe":1,"-shift-\u0022":1,"-option-m":1,"-v":1,"-option-shift-v":1,"-=select":1,"-a":1,"rag":1,"-option-a":1}
,"period":{"esc":1}
,"selected":{"button":1,"right":1,"left":1,"command":1,"item":1}
,"button":{"popover":1,"layout":1,"tab":1}
,"popover":{"button":1}
,"layout":{"keyboard":1,"command":1,"object":1,"page":1,"mode":1}
,"space":{"bar":1}
,"bar":{"close":1}
,"close":{"dialog":1,"file":1,"all":1,"window":1}
,"file":{"command":1,"option":1,"open":1,"dialog":1}
,"-w":{"close":1,"quit":1,"resize":1}
,"all":{"files":1,"filemaker":1,"objects":1}
,"files":{"option-command":1}
,"option-command":{"-w":1}
,"quit":{"command":1}
,"-q":{"open":1}
,"open":{"filemaker":1,"apps":1,"file":1,"host":1,"open":1,"manage":1,"find\u002Freplace":1,"preferences":1,"script":1}
,"help":{"command":1}
,"-?":{"open":1}
,"apps":{"window":1}
,"window":{"command":1,"full":1,"display":1}
,"-option-o":{"use":1}
,"use":{"account":1,"hese":1,"keys":1,"eyboard":1}
,"account":{"name":1}
,"name":{"password":1,"command":1}
,"password":{"open":1}
,"option":{"pen":1}
,"pen":{"file":1}
,"host":{"dialog":1}
,"-shift-o":{"open":1}
,"-o":{"open":1}
,"manage":{"database":1,"layouts":1}
,"-shift-d":{"open":1}
,"find\u002Freplace":{"dialog":1}
,"-shift-f":{"open":1}
,"layouts":{"dialog":1,"macos":1}
,"-shift-l":{"open":1}
,"preferences":{"dialog":1,"note":1}
,"print":{"command":1,"print":1,"dialog":1}
,"-p":{"print":1}
,"-option-p":{"save":1}
,"save":{"by":1,"layout":1}
,"by":{"default":1}
,"default":{"filemaker":1}
,"saves":{"record":1}
,"record":{"ata":1,"find":1,"confirmation":1,"request":1,"command":1,"move":1}
,"ata":{"automatically":1}
,"automatically":{"sort":1}
,"sort":{"command":1}
,"-s":{"undo":1,"use":1}
,"undo":{"last":1}
,"last":{"command":1,"visited":1,"record":1}
,"-z":{"open":1}
,"workspace":{"command":1}
,"-shift-s":{"perform":1}
,"first":{"scripts":1}
,"scripts":{"listed":1,"menu":1}
,"listed":{"scripts":1}
,"-1":{"hrough":1}
,"hrough":{"command":1}
,"-0":{"create":1}
,"create":{"record":1}
,"find":{"request":1,"requests":1}
,"request":{"layout":1}
,"-n":{"delete":1}
,"delete":{"record":1}
,"-e":{"delete":1}
,"confirmation":{"command":1}
,"-option-e":{"duplicate":1}
,"duplicate":{"record":1}
,"object":{"command":1,"field":1,"drag":1,"selected":1}
,"-d":{"save":1}
,"hese":{"keyboard":1}
,"move":{"fields":1,"records":1,"press":1,"items":1,"next":1,"selected":1}
,"fields":{"records":1,"co":1,"move":1,"elect":1}
,"records":{"find":1,"filemaker":1}
,"requests":{"nd":1}
,"nd":{"layouts":1,"move":1}
,"mission":{"control":1}
,"control":{"feature":1,"preferences":1}
,"feature":{"control-down":1}
,"control-down":{"arrow":1}
,"arrow":{"control-up":1,"keys":1,"previous":1,"next":1,"use":1,"pointer":1,"arrow":1,"move":1,"control-down":1,"eneral":1}
,"control-up":{"arrow":1}
,"keys":{"use":1,"move":1}
,"change":{"keyboard":1}
,"designer":{"changed":1,"setting":1}
,"changed":{"keyboard":1}
,"moving":{"fields":1}
,"co":{"nsult":1}
,"nsult":{"database":1}
,"setting":{"eys":1}
,"eys":{"moving":1}
,"next":{"object":1,"record":1,"tab":1,"field":1}
,"field":{"button":1,"command":1}
,"tab":{"tab":1,"previous":1,"shift-tab":1,"wh":1,"selected":1}
,"previous":{"object":1,"record":1,"tab":1,"size":1}
,"shift-tab":{"next":1}
,"page":{"control-down":1,"control-up":1,"scroll":1,"up":1}
,"wh":{"en":1}
,"en":{"tab":1}
,"right":{"arrow":1}
,"left":{"arrow":1}
,"odes":{"scroll":1}
,"scroll":{"ocument":1,"document":1,"end":1}
,"ocument":{"arrange":1}
,"arrange":{"windows":1}
,"windows":{"press":1}
,"resize":{"window":1}
,"full":{"screen":1}
,"screen":{"previous":1}
,"size":{"command":1}
,"-option-z":{"scroll":1}
,"document":{"page":1,"up":1,"scroll":1,"end":1,"larger":1,"selected":1}
,"up":{"page":1,"scroll":1,"arrow":1}
,"end":{"document":1,"show":1}
,"show":{"hide":1}
,"hide":{"status":1,"filemaker":1}
,"status":{"toolbar":1}
,"toolbar":{"command":1}
,"-option-s":{"minimize":1}
,"minimize":{"current":1}
,"current":{"window":1,"date":1,"time":1,"user":1}
,"-m":{"hide":1}
,"application":{"command":1}
,"-h":{"zoom":1}
,"zoom":{"document":1}
,"larger":{"selected":1}
,"-shift-+":{"command":1}
,"-+":{"numeric":1}
,"numeric":{"keypad":1}
,"keypad":{"zoom":1}
,"--(":{"hyphen":1}
,"hyphen":{"use":1,"current":1}
,"enter":{"replace":1}
,"replace":{"values":1,"field\u0027s":1}
,"values":{"fields":1}
,"elect":{"objects":1}
,"objects":{"nd":1,"layout":1,"shift-click":1,"note":1,"enclosed":1,"type":1,"keyboard":1}
,"items":{"ist":1,"list":1}
,"ist":{"insert":1}
,"insert":{"press":1,"pa":1}
,"date":{"command":1,"timestamp":1}
,"time":{"command":1,"date":1}
,"timestamp":{"field":1}
,"user":{"name":1}
,"-shift-n":{"index":1}
,"index":{"command":1}
,"-i":{"last":1}
,"visited":{"record":1}
,"apostrophe":{"last":1}
,"-shift-\u0022":{"quotation":1}
,"quotation":{"rge":1}
,"rge":{"field":1}
,"-option-m":{"paste":1}
,"paste":{"press":1}
,"text":{"clipboard":1,"styles":1}
,"clipboard":{"command":1}
,"-v":{"text":1}
,"styles":{"command":1}
,"-option-shift-v":{"press":1}
,"field\u0027s":{"value":1}
,"value":{"command":1}
,"-=select":{"all":1}
,"mode":{"command":1}
,"-a":{"select":1}
,"select":{"multiple":1,"objects":1,"items":1,"alues":1}
,"multiple":{"objects":1}
,"shift-click":{"each":1}
,"each":{"object":1}
,"drag":{"arrow":1}
,"pointer":{"box":1}
,"includes":{"objects":1}
,"enclosed":{"selection":1}
,"selection":{"box":1}
,"rag":{"select":1}
,"type":{"object":1}
,"-option-a":{"select":1}
,"list":{"up":1,"control-up":1}
,"eneral":{"keyboard":1}
,"navigation":{"keyboard":1}
,"pa":{"ste":1}
,"ste":{"select":1}
,"alues":{"objects":1}
}
;Search.control.loadWordPairs(pairs);
