var pairs =
{
"constrain":{"found":1}
,"found":{"set":1}
,"set":{"arrows":1,"current":1,"perform":1,"zero":1,"paid":1,"field":1,"[]":1,"automating":1}
,"arrows":{"existing":1}
,"existing":{"found":1}
,"current":{"stored":1}
,"stored":{"find":1}
,"find":{"requests":1,"request":1,"script":1,"criteria":1,"mode":1}
,"requests":{"pecify":1}
,"pecify":{"fi":1}
,"fi":{"nd":1}
,"nd":{"re":1}
,"re":{"quests":1}
,"quests":{"llows":1}
,"llows":{"create":1}
,"create":{"store":1}
,"store":{"find":1}
,"request":{"script":1,"filemaker":1}
,"script":{"step":1}
,"step":{"restore":1,"equivalent":1,"if":1,"returns":1}
,"restore":{"stored":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"script":1}
,"equivalent":{"logical":1}
,"logical":{"search":1}
,"search":{"constrain":1}
,"perform":{"find":1}
,"if":{"records":1,"[get":1,"onstraining":1}
,"records":{"match":1,"constrains":1,"show":1,"end":1}
,"match":{"find":1}
,"criteria":{"script":1}
,"returns":{"found":1}
,"zero":{"records":1}
,"constrains":{"found":1}
,"paid":{"invoices":1,"\u0022]":1}
,"invoices":{"all":1,"\u0022]":1}
,"all":{"records":1}
,"show":{"custom":1,"all":1}
,"custom":{"dialog":1}
,"dialog":{"[\u0022":1}
,"[\u0022":{"display":1}
,"display":{"paid":1}
,"\u0022]":{"if":1,"constrain":1}
,"[get":{"lastmessagechoice":1}
,"lastmessagechoice":{"=1]":1}
,"=1]":{"enter":1}
,"enter":{"find":1}
,"mode":{"[pause":1}
,"[pause":{"off]":1}
,"off]":{"set":1}
,"field":{"[invoices":1}
,"[invoices":{":status":1}
,":status":{"paid":1}
,"[]":{"else":1}
,"else":{"show":1}
,"end":{"if":1}
,"onstraining":{"narrowing":1}
,"narrowing":{"found":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
