var pairs =
{
"dentifying":{"text":1}
,"text":{"constants":1,"empty":1,"use":1}
,"constants":{"special":1,"quotation":1}
,"special":{"characters":1,"operator":1}
,"characters":{"formulas":1,"double":1,"string":1}
,"formulas":{"use":1}
,"use":{"closing":1,"backslashes":1}
,"closing":{"quotation":1}
,"quotation":{"marks":1}
,"marks":{"end":1,"text":1,"carriage":1}
,"end":{"text":1}
,"empty":{"value":1}
,"value":{"text":1}
,"backslashes":{"preserve":1}
,"preserve":{"special":1}
,"operator":{"characters":1}
,"double":{"quotation":1}
,"carriage":{"return":1}
,"return":{"character":1}
,"character":{"simply":1}
,"simply":{"characters":1}
,"string":{"operators":1}
,"operators":{"\u0022\u005C\u0022":1}
,"\u0022\u005C\u0022":{"fred":1}
,"fred":{"&\u0022":1,"jane":1}
,"&\u0022":{"jane\u005C\u0022":1}
,"jane\u005C\u0022":{"returns":1}
,"returns":{"fred":1}
,"jane":{"exampl":1}
}
;Search.control.loadWordPairs(pairs);
