var pairs =
{
"column":{"bar":1,"chart":1}
,"bar":{"line":1,"stacked":1,"charts":1}
,"line":{"charts":1}
,"charts":{"get":1,"creating":1,"layout":1,"y-axis":1,"choose":1,"finish":1}
,"get":{"started":1}
,"started":{"creating":1}
,"creating":{"chart":1,"quick":1,"editing":1}
,"chart":{"creating":1,"aking":1,"chart":1,"setup":1,"type":1,"types":1,"summary":1,"inspector":1,"effective":1,"multi":1,"layered":1,"choose":1,"determined":1,"if":1,"change":1,"axes":1,"print":1}
,"quick":{"charts":1,"chart":1}
,"editing":{"charts":1}
,"layout":{"mode":1,"quick":1}
,"mode":{"find":1,"charts":1}
,"find":{"records":1,"request":1}
,"records":{"want":1,"data":1}
,"want":{"chart":1}
,"aking":{"find":1}
,"request":{"if":1}
,"if":{"charting":1,"you\u2019re":1}
,"charting":{"delimited":1,"multi":1}
,"delimited":{"data":1}
,"data":{"stored":1,"related":1,"source":1,"button":1,"series":1,"comparing":1,"summary":1,"settings":1,"point":1,"select":1}
,"stored":{"single":1}
,"single":{"record":1}
,"record":{"data":1}
,"related":{"records":1}
,"source":{"settings":1,"chart":1}
,"settings":{"pecifying":1,"x-axis":1,"y-axis":1}
,"pecifying":{"data":1}
,"setup":{"dialog":1}
,"dialog":{"box":1}
,"box":{"choose":1,"data":1,"first":1,"set":1}
,"choose":{"chart":1,"field":1,"symbol":1,"none":1}
,"type":{"chart":1,"title":1,"enter":1}
,"types":{"enter":1}
,"enter":{"settings":1,"up":1}
,"x-axis":{"horizontal":1,"data":1}
,"horizontal":{"title":1}
,"title":{"type":1,"button":1,"data":1}
,"button":{"choose":1,"data":1}
,"field":{"name":1}
,"name":{"calculation":1,"if":1,"title":1,"text":1}
,"calculation":{"complete":1}
,"complete":{"dialog":1,"series":1}
,"series":{"x-axis":1,"y-axis":1,"repeat":1,"name":1,"remove":1,"change":1,"drag":1,"reflects":1,"list":1}
,"comparing":{"company":1,"stacked":1}
,"company":{"name":1}
,"you\u2019re":{"creating":1}
,"summary":{"data":1,"menu":1,"type":1}
,"menu":{"chart":1}
,"inspector":{"select":1,"changing":1}
,"select":{"summary":1,"series":1,"show":1}
,"y-axis":{"vertical":1,"additional":1,"add":1,"series":1,"select":1,"data":1,"notes":1}
,"vertical":{"title":1}
,"additional":{"data":1}
,"add":{"series":1}
,"repeat":{"step":1}
,"step":{"complete":1}
,"remove":{"data":1}
,"change":{"order":1,"labels":1,"color":1}
,"order":{"y-axis":1,"data":1,"y-series":1}
,"drag":{"items":1}
,"items":{"list":1}
,"list":{"enter":1,"appears":1,"symbol":1}
,"up":{"12":1}
,"12":{"data":1}
,"notes":{"bar":1}
,"stacked":{"bar":1,"column":1}
,"effective":{"comparison":1}
,"comparison":{"y-series":1}
,"y-series":{"chart":1,"defined":1}
,"multi":{"eries":1}
,"eries":{"chart":1,"data":1}
,"layered":{"order":1}
,"reflects":{"order":1}
,"defined":{"chart":1}
,"first":{"series":1}
,"appears":{"top":1}
,"top":{"by":1}
,"by":{"next":1,"color":1}
,"next":{"series":1}
,"symbol":{"line":1,"mark":1,"color":1}
,"mark":{"each":1}
,"each":{"data":1}
,"point":{"chart":1}
,"none":{"hide":1}
,"hide":{"symbols":1}
,"symbols":{"symbol":1}
,"color":{"final":1,"scheme":1}
,"final":{"chart":1}
,"determined":{"by":1}
,"scheme":{"setting":1,"legend":1}
,"setting":{"styles":1}
,"styles":{"chart":1}
,"changing":{"chart":1}
,"show":{"legend":1}
,"legend":{"display":1,"chart":1,"edit":1,"appearance":1}
,"display":{"legend":1}
,"labels":{"legend":1}
,"edit":{"series":1}
,"text":{"box":1}
,"set":{"axis":1}
,"axis":{"options":1}
,"options":{"formatting":1}
,"formatting":{"scaling":1}
,"scaling":{"chart":1}
,"axes":{"change":1}
,"appearance":{"font":1}
,"font":{"style":1}
,"style":{"style":1,"chart":1}
,"print":{"save":1}
,"save":{"layout":1}
,"finish":{"chart":1}
}
;Search.control.loadWordPairs(pairs);
