var pairs =
{
"end":{"loop":1}
,"loop":{"arks":1,"script":1,"step":1,"end":1,"automatically":1,"set":1,"automating":1}
,"arks":{"end":1}
,"script":{"structure":1,"step":1,"editing":1}
,"structure":{"none":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"use":1}
,"use":{"loop":1}
,"step":{"script":1,"steps":1,"placed":1,"copies":1}
,"editing":{"pane":1}
,"pane":{"automatically":1}
,"automatically":{"enters":1,"indented":1}
,"enters":{"end":1}
,"steps":{"loop":1}
,"indented":{"end":1}
,"placed":{"indentation":1}
,"indentation":{"level":1}
,"level":{"loop":1}
,"copies":{"data":1}
,"data":{"customers":1}
,"customers":{":work":1,":day":1}
,":work":{"phone":1,"phone]":1}
,"phone":{"customers":1}
,":day":{"contact":1}
,"contact":{"all":1,"customers":1}
,"all":{"records":1}
,"records":{"go":1}
,"go":{"record\u002Frequest\u002Fpage":1}
,"record\u002Frequest\u002Fpage":{"[first]":1,"[next":1}
,"[first]":{"loop":1}
,"set":{"field":1}
,"field":{"[customers":1}
,"[customers":{":day":1}
,"phone]":{"go":1}
,"[next":{"exit":1}
,"exit":{"last":1}
,"last":{"end":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
