var pairs =
{
"etting":{"automatic":1}
,"automatic":{"record-saving":1}
,"record-saving":{"option":1}
,"option":{"layout":1}
,"layout":{"data":1,"mode":1,"want":1,"pop-up":1,"setup":1,"bar":1}
,"data":{"entry":1,"changed":1}
,"entry":{"record":1}
,"record":{"ormally":1,"display":1,"if":1,"confirmation":1,"data":1,"automatically":1}
,"ormally":{"saved":1}
,"saved":{"au":1}
,"au":{"tomatically":1}
,"tomatically":{"exit":1}
,"exit":{"record":1}
,"display":{"record":1,"save":1,"confirmation":1}
,"if":{"prefer":1}
,"prefer":{"set":1}
,"set":{"filemaker":1,"usage":1,"automatic":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"display":1}
,"save":{"record":1}
,"confirmation":{"dialog":1}
,"dialog":{"box":1}
,"box":{"exiting":1,"layout-by-layout":1,"save":1}
,"exiting":{"record":1}
,"changed":{"ou":1,"clear":1}
,"ou":{"set":1}
,"usage":{"confirmation":1}
,"layout-by-layout":{"basis":1}
,"basis":{"layout":1}
,"mode":{"choose":1}
,"choose":{"layout":1}
,"want":{"layout":1}
,"pop-up":{"menu":1}
,"menu":{"layout":1}
,"setup":{"layout":1,"button":1,"dialog":1}
,"button":{"layout":1}
,"bar":{"layout":1}
,"automatically":{"select":1,"display":1,"set":1}
,"select":{"save":1}
,"clear":{"save":1}
}
;Search.control.loadWordPairs(pairs);
