var pairs =
{
"window":{"styles":1,"behaves":1,"style":1,"review":1,"inactive":1,"display":1,"open":1,"script":1,"ers":1,"operations":1,"itself":1,"ope":1,"arrange":1,"move\u002Fresize":1,"op":1,"new":1,"pen":1,"card":1,"select":1,"macos":1,"all":1,"apple":1,"users":1,"use":1,"menu":1,"filemaker":1,"frame":1,"floating":1,"dialog":1}
,"styles":{"window":1,"allow":1}
,"allow":{"new":1,"users":1}
,"new":{"window":1,"process":1,"dialog":1,"file":1}
,"behaves":{"solution":1}
,"solution":{"each":1}
,"each":{"layout":1}
,"layout":{"task":1,"dialog":1,"active":1,"larger":1}
,"task":{"designed":1}
,"designed":{"window":1}
,"style":{"mind":1}
,"mind":{"document":1}
,"document":{"windows":1,"window":1,"floating":1,"indow":1}
,"windows":{"allow":1,"typical":1,"remain":1,"floating":1,"display":1,"foreground":1,"activate":1,"use":1,"collect":1,"open":1,"cards":1,"users":1,"ata":1,"script":1,"adjust":1,"convert":1,"ards":1}
,"users":{"start":1,"close":1,"situations":1,"non-document":1,"find":1}
,"start":{"new":1}
,"process":{"view":1}
,"view":{"additional":1}
,"additional":{"use":1}
,"use":{"document":1,"floating":1,"dialog":1,"cards":1,"ove\u002Fresize":1}
,"typical":{"user-input":1}
,"user-input":{"tasks":1}
,"tasks":{"tasks":1,"take":1,"visible":1}
,"take":{"place":1}
,"place":{"order":1}
,"order":{"open":1}
,"open":{"document":1,"floating":1,"dialog":1,"new":1,"script":1,"file":1,"hosts":1,"cards":1,"card":1,"windows":1}
,"review":{"invoice":1}
,"invoice":{"while":1}
,"while":{"customer\u2019s":1,"blocking":1,"filemaker":1,"allowing":1}
,"customer\u2019s":{"purchase":1}
,"purchase":{"history":1}
,"history":{"floating":1}
,"floating":{"document":1,"window":1}
,"remain":{"top":1}
,"top":{"windows":1}
,"inactive":{"use":1}
,"display":{"tasks":1,"interactive":1,"alert":1,"status":1}
,"visible":{"all":1}
,"all":{"times":1,"open":1,"windows":1,"qualities":1}
,"times":{"open":1}
,"interactive":{"table":1}
,"table":{"contents":1}
,"contents":{"dialog":1}
,"dialog":{"windows":1,"window":1,"box":1}
,"foreground":{"users":1,"current":1}
,"close":{"all":1,"card":1,"option":1,"button":1,"card\u2019s":1}
,"activate":{"open":1}
,"collect":{"required":1}
,"required":{"alert":1}
,"alert":{"users":1,"user":1}
,"situations":{"while":1}
,"blocking":{"access":1}
,"access":{"windows":1,"open":1}
,"user":{"attempts":1,"close":1}
,"attempts":{"modify":1,"close":1}
,"modify":{"sensitive":1}
,"sensitive":{"data":1}
,"data":{"hen":1}
,"hen":{"dialog":1}
,"script":{"step":1,"debugger":1,"workspace":1,"trigger":1,"file":1,"launches":1,"steps":1,"fail":1,"assigned":1,"attempts":1,"first":1,"returns":1}
,"step":{"creates":1,"supported":1,"filemaker":1,"hide":1,"if":1}
,"creates":{"dialog":1}
,"cards":{"ut":1,"foreground":1,"collect":1,"window":1,"display":1}
,"ut":{"create":1}
,"create":{"document":1}
,"non-document":{"windows":1}
,"ata":{"viewer":1}
,"viewer":{"script":1}
,"debugger":{"if":1}
,"if":{"windows":1,"active":1,"select":1,"don\u2019t":1,"script":1,"close":1}
,"ers":{"manage":1}
,"manage":{"layout":1}
,"box":{"script":1}
,"workspace":{"apps":1}
,"apps":{"window":1}
,"operations":{"attempt":1}
,"attempt":{"open":1}
,"indow":{"fail":1}
,"fail":{"dialog":1,"executed":1}
,"trigger":{"run":1,"fails":1}
,"run":{"script":1}
,"file":{"ontimer":1,"go":1,"new":1,"open":1,"quit":1,"while":1}
,"ontimer":{"scripts":1}
,"scripts":{"execute":1}
,"execute":{"dialog":1}
,"launches":{"dialog":1}
,"itself":{"restrictions":1}
,"restrictions":{"apply":1,"standard":1}
,"apply":{"script":1}
,"steps":{"they\u2019re":1}
,"they\u2019re":{"dialog":1}
,"supported":{"restriction":1}
,"restriction":{"dialog":1}
,"adjust":{"window":1}
,"ope":{"rates":1}
,"rates":{"current":1}
,"current":{"window":1,"dialog":1,"layout":1}
,"arrange":{"all":1}
,"convert":{"file":1}
,"go":{"related":1,"hide":1,"if":1}
,"related":{"record":1}
,"record":{"pen":1}
,"pen":{"new":1}
,"move\u002Fresize":{"window":1}
,"op":{"erates":1}
,"erates":{"current":1}
,"card":{"open":1,"card\u2019s":1,"prompt":1,"if":1,"parent":1,"use":1,"hide":1,"gesture":1,"disabled":1,"focus":1,"by":1,"filemaker":1,"include":1,"performs":1,"script":1}
,"hosts":{"perform":1}
,"perform":{"script":1}
,"executed":{"open":1}
,"quit":{"application":1}
,"application":{"select":1}
,"select":{"window":1,"current":1,"close":1}
,"macos":{"filemaker":1,"ialog":1}
,"filemaker":{"pro":1,"go":1}
,"pro":{"advanced":1}
,"advanced":{"dialog":1,"include":1,"cards":1,"by":1}
,"qualities":{"restrictions":1}
,"standard":{"macos":1}
,"ialog":{"window":1}
,"apple":{"events":1}
,"events":{"communicate":1}
,"communicate":{"file":1}
,"active":{"window":1,"layout":1}
,"card\u2019s":{"parent":1,"height":1}
,"parent":{"window":1}
,"allowing":{"access":1}
,"prompt":{"users":1}
,"find":{"criteria":1}
,"criteria":{"while":1}
,"ards":{"can\u2019t":1}
,"can\u2019t":{"minimized":1}
,"minimized":{"maximized":1}
,"maximized":{"filemaker":1}
,"include":{"cards":1,"script":1}
,"menu":{"card\u2019s":1,"bar":1}
,"height":{"width":1}
,"width":{"exceed":1,"open":1}
,"exceed":{"screen":1}
,"screen":{"size":1}
,"size":{"scroll":1}
,"scroll":{"bars":1}
,"bars":{"card":1}
,"larger":{"card\u2019s":1}
,"status":{"toolbar":1}
,"toolbar":{"formatting":1,"card":1}
,"formatting":{"bar":1}
,"bar":{"title":1,"window":1,"toolbar":1,"displaying":1}
,"title":{"bar":1}
,"frame":{"move":1}
,"move":{"resize":1}
,"resize":{"card":1}
,"ove\u002Fresize":{"window":1}
,"hide":{"show":1}
,"show":{"menu":1,"bar":1,"card":1}
,"displaying":{"card":1}
,"gesture":{"script":1}
,"disabled":{"card":1}
,"focus":{"if":1}
,"option":{"user":1,"users":1}
,"by":{"clicking":1,"tapping":1}
,"clicking":{"close":1}
,"button":{"filemaker":1,"card":1}
,"tapping":{"card":1}
,"don\u2019t":{"select":1}
,"assigned":{"button":1}
,"performs":{"lose":1}
,"lose":{"window":1}
,"first":{"attempts":1}
,"fails":{"script":1}
,"returns":{"error":1}
,"error":{"code":1}
,"code":{"document":1}
}
;Search.control.loadWordPairs(pairs);
