var pairs =
{
"get":{"triggermodif":1,"triggermodifierkeys":1,"activemodifierkeys":1,"triggerkeystroke":1,"trigger":1,"modifier":1,"script":1}
,"triggermodif":{"ierkeys":1}
,"ierkeys":{"returns":1}
,"returns":{"state":1,"value":1,"empty":1,"display":1,"modifier":1}
,"state":{"keyboard":1}
,"keyboard":{"modifier":1}
,"modifier":{"keys":1}
,"keys":{"onobjectkeystroke":1,"code":1,"codes":1,"activated":1,"use":1,"active":1,"pressed":1,"get":1}
,"onobjectkeystroke":{"onlayoutkeystroke":1}
,"onlayoutkeystroke":{"script":1}
,"script":{"trigger":1,"activated":1,"returns":1,"modifier":1,"triggers":1,"triggered":1,"runs":1}
,"trigger":{"activated":1,"sub-script":1,"time":1,"pressed":1,"modifier":1}
,"activated":{"get":1,"by":1,"script":1,"use":1}
,"triggermodifierkeys":{"none":1,"capture":1,"=0":1,"returns":1,"get":1}
,"none":{"number":1}
,"number":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1,"go":1}
,"pro":{"10.0":1}
,"10.0":{"returns":1}
,"value":{"called":1,"returned":1}
,"called":{"script":1,"triggered":1}
,"by":{"script":1,"trigger":1}
,"sub-script":{"called":1}
,"triggered":{"script":1,"get":1}
,"empty":{"string":1}
,"string":{"get":1,"filemaker":1}
,"activemodifierkeys":{"description":1,"capture":1}
,"description":{"values":1}
,"values":{"assigned":1}
,"assigned":{"keyboard":1}
,"code":{"function":1}
,"function":{"list":1,"supported":1}
,"list":{"navigational":1}
,"navigational":{"keys":1}
,"codes":{"returned":1}
,"returned":{"script":1,"shift-option":1}
,"time":{"elapse":1}
,"elapse":{"keys":1}
,"pressed":{"script":1,"windows":1,"computer":1,"mac":1,"trigger":1}
,"use":{"get":1}
,"triggerkeystroke":{"get":1,"=\u0022":1}
,"capture":{"keys":1,"current":1}
,"active":{"script":1}
,"current":{"keys":1}
,"windows":{"alt":1}
,"alt":{"ctrl":1}
,"ctrl":{"key":1}
,"key":{"combinations":1}
,"combinations":{"activate":1}
,"activate":{"script":1}
,"triggers":{"macos":1,"filemaker":1}
,"macos":{"command":1,"if":1}
,"command":{"key":1}
,"webdirect":{"function":1}
,"supported":{"returns":1}
,"go":{"function":1}
,"display":{"custom":1}
,"custom":{"dialog":1}
,"dialog":{"box":1,"[\u0022":1}
,"box":{"lowercase":1}
,"lowercase":{"entered":1}
,"entered":{"if":1,"\u005C\u0022":1}
,"if":{"[get":1,"value":1,"option":1}
,"[get":{"triggerkeystroke":1}
,"=\u0022":{"get":1}
,"=0":{"show":1}
,"show":{"custom":1}
,"[\u0022":{"entered":1}
,"\u005C\u0022":{"a\u005C\u0022":1}
,"a\u005C\u0022":{"\u0022]":1}
,"\u0022]":{"end":1}
,"end":{"if":1}
,"shift-option":{"pressed":1}
,"computer":{"running":1}
,"running":{"macos":1}
,"option":{"shift":1}
,"shift":{"keys":1}
,"mac":{"script":1}
,"runs":{"get":1}
}
;Search.control.loadWordPairs(pairs);
