var pairs =
{
"thorizing":{"ccess":1}
,"ccess":{"files":1}
,"files":{"part":1,"permitted":1,"enabling":1,"authorized":1,"access":1,"open":1,"select":1,"reference":1,"currently":1,"each":1,"if":1,"multifile":1,"file":1}
,"part":{"security":1}
,"security":{"plan":1,"measures":1,"shared":1,"if":1,"dialog":1,"settings":1}
,"plan":{"control":1}
,"control":{"filemaker":1}
,"filemaker":{"pro":1,"data":1}
,"pro":{"advanced":1}
,"advanced":{"files":1}
,"permitted":{"access":1}
,"access":{"schema":1,"enforced":1,"protecting":1,"files":1,"privilege":1,"tab":1,"privileges":1,"deselect":1,"list":1,"if":1,"protected":1,"resetting":1,"file":1}
,"schema":{"file":1}
,"file":{"including":1,"filemaker":1,"creating":1,"tables":1,"implement":1,"bypass":1,"open":1,"script":1,"assigned":1,"track":1,"remains":1,"unsuccessful":1,"authorizing":1,"account":1,"want":1,"menu":1,"access":1,"unwanted":1,"if":1,"currently":1,"remove":1,"select":1,"dialog":1,"authorize":1,"references":1,"appears":1,"reference":1,"refer":1,"file":1,"salesreport":1,"retains":1,"cloned":1,"each":1,"id":1,"unique":1,"protected":1,"authorized":1}
,"including":{"tables":1}
,"tables":{"layouts":1,"file":1}
,"layouts":{"scripts":1}
,"scripts":{"value":1}
,"value":{"lists":1}
,"lists":{"secured":1}
,"secured":{"solution":1}
,"solution":{"protection":1,"authorize":1,"don\u2019t":1}
,"protection":{"enabled":1,"prevents":1}
,"enabled":{"use":1}
,"use":{"protected":1,"alternative":1,"detailed":1,"references":1,"files":1}
,"protected":{"file":1,"if":1,"file\u2019s":1,"files":1}
,"data":{"source":1,"security":1}
,"source":{"require":1,"file":1}
,"require":{"authorization":1,"full":1}
,"authorization":{"therefore":1,"by":1,"file":1,"deauthorize":1,"newly":1,"prevent":1,"process":1}
,"therefore":{"multi":1}
,"multi":{"ile":1}
,"ile":{"solution":1,"manage":1}
,"authorize":{"files":1,"file":1,"additional":1,"open":1,"access":1}
,"enabling":{"protection":1}
,"prevents":{"account":1,"files":1}
,"account":{"file":1,"assigned":1,"full":1,"create":1}
,"creating":{"file":1}
,"implement":{"business":1}
,"business":{"logic":1}
,"logic":{"script":1,"record-level":1}
,"script":{"triggers":1,"step":1}
,"triggers":{"use":1}
,"alternative":{"file":1}
,"bypass":{"intended":1,"authorization":1}
,"intended":{"business":1}
,"record-level":{"access":1}
,"enforced":{"option":1}
,"option":{"prevents":1}
,"authorized":{"protected":1,"file":1,"account":1,"files":1,"access":1}
,"open":{"file":1,"alert":1,"clients":1,"authorize":1,"enter":1,"new":1}
,"step":{"each":1}
,"each":{"authorized":1,"file":1,"add":1}
,"assigned":{"unique":1,"full":1}
,"unique":{"numeric":1,"id":1}
,"numeric":{"identifier":1}
,"identifier":{"protected":1}
,"track":{"ensuring":1}
,"ensuring":{"protected":1}
,"remains":{"protected":1}
,"if":{"renamed":1,"manage":1,"files":1,"want":1,"deauthorized":1,"rename":1,"file":1,"duplicate":1,"use":1}
,"renamed":{"duplicated":1,"file":1}
,"duplicated":{"efforts":1}
,"efforts":{"bypass":1}
,"by":{"replacing":1,"clicking":1}
,"replacing":{"authorized":1}
,"unsuccessful":{"protecting":1}
,"protecting":{"file":1,"file\u2019s":1}
,"authorizing":{"files":1}
,"file\u2019s":{"record":1,"unique":1}
,"record":{"data":1}
,"measures":{"take":1}
,"take":{"planning":1,"next":1}
,"planning":{"security":1}
,"shared":{"ile":1}
,"manage":{"access":1,"security":1}
,"full":{"access":1}
,"privilege":{"set":1}
,"set":{"privilege":1,"permits":1}
,"permits":{"privileges":1}
,"privileges":{"file":1,"use":1,"create":1,"don\u2019t":1}
,"want":{"protect":1,"authorize":1,"remove":1}
,"protect":{"choose":1,"file":1}
,"choose":{"file":1}
,"menu":{"manage":1}
,"dialog":{"box":1}
,"box":{"displays":1,"choose":1,"authorize":1}
,"displays":{"basic":1}
,"basic":{"security":1}
,"settings":{"use":1}
,"detailed":{"setup":1}
,"setup":{"file":1}
,"tab":{"protect":1}
,"unwanted":{"access":1}
,"select":{"require":1,"file":1}
,"references":{"file":1,"protected":1,"authorized":1,"manually":1}
,"reference":{"protected":1,"itself":1}
,"currently":{"open":1}
,"alert":{"each":1}
,"remove":{"authorization":1,"all":1,"self":1}
,"deauthorize":{"if":1}
,"deauthorized":{"file":1}
,"clients":{"deauthorization":1}
,"deauthorization":{"take":1}
,"next":{"time":1,"original":1}
,"time":{"file":1,"authorized":1}
,"all":{"restrictions":1,"resetting":1,"files":1}
,"restrictions":{"file":1}
,"deselect":{"require":1}
,"create":{"references":1,"authorization":1}
,"additional":{"files":1}
,"enter":{"name":1}
,"name":{"password":1,"appears":1,"file":1}
,"password":{"account":1}
,"don\u2019t":{"authorize":1,"repeat":1}
,"appears":{"file":1,"next":1,"list":1}
,"list":{"date":1,"enables":1,"remove":1,"if":1,"protected":1,"authorized":1}
,"date":{"time":1}
,"newly":{"created":1}
,"created":{"file":1}
,"itself":{"file":1,"copied":1}
,"enables":{"data":1}
,"refer":{"itself":1}
,"copied":{"cloned":1}
,"cloned":{"files":1,"included":1}
,"add":{"references":1}
,"manually":{"file":1}
,"self":{"authorization":1}
,"prevent":{"type":1}
,"type":{"access":1}
,"rename":{"authorized":1}
,"new":{"name":1}
,"original":{"name":1}
,"salesreport":{"execreport":1,"appears":1}
,"execreport":{"execreport":1,"salesreport":1}
,"retains":{"list":1}
,"included":{"runtime":1}
,"runtime":{"solution":1}
,"repeat":{"process":1,"authorization":1}
,"process":{"th":1,"if":1}
,"th":{"helpful":1}
,"helpful":{"don\u2019t":1}
,"duplicate":{"clone":1}
,"clone":{"protected":1}
,"id":{"if":1,"files":1,"reset":1,"undone":1}
,"multifile":{"olution":1}
,"olution":{"reset":1}
,"reset":{"id":1,"protected":1,"all":1}
,"resetting":{"reauthorize":1,"id":1}
,"reauthorize":{"all":1}
,"undone":{"by":1}
,"clicking":{"cancel":1}
,"cancel":{"manage":1}
}
;Search.control.loadWordPairs(pairs);
