var pairs =
{
"copy":{"opies":1,"field":1,"clipboard":1,"script":1,"contents":1,"customer\u0027s":1,"[customers":1}
,"opies":{"contents":1}
,"contents":{"field":1,"clipboard":1,"copies":1,"selected":1,"want":1,"cut":1,"email":1}
,"field":{"current":1,"specifies":1,"contents":1,"selected":1,"remove":1,"use":1,"data":1,"show":1}
,"current":{"record":1}
,"record":{"saves":1,"clipboard":1,"filemaker":1}
,"saves":{"contents":1}
,"clipboard":{"select":1,"if":1,"accessible":1}
,"select":{"entire":1,"field":1}
,"entire":{"contents":1}
,"copies":{"entire":1,"values":1}
,"if":{"use":1,"manually":1,"selection":1,"[get":1,"opying":1}
,"use":{"select":1,"cut":1,"et":1}
,"selected":{"portion":1,"filemaker":1}
,"portion":{"field\u0027s":1}
,"field\u0027s":{"data":1}
,"data":{"copied":1,"clipboard":1,"run":1,"records":1}
,"copied":{"go":1}
,"go":{"target":1}
,"target":{"field":1}
,"specifies":{"field":1}
,"want":{"copy":1,"cut":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"advanced":1,"6.0":1}
,"advanced":{"copies":1}
,"values":{"all":1}
,"all":{"fields":1}
,"fields":{"current":1}
,"6.0":{"earlier":1}
,"earlier":{"script":1}
,"script":{"step":1}
,"step":{"duplicates":1,"contents":1,"place":1,"filemaker":1,"performs":1,"prompts":1}
,"duplicates":{"contents":1}
,"remove":{"field":1}
,"cut":{"script":1,"copy":1,"[customers":1}
,"accessible":{"applications":1}
,"applications":{"filemaker":1}
,"webdirect":{"copy":1,"script":1,"use":1}
,"place":{"data":1}
,"manually":{"select":1}
,"run":{"script":1}
,"performs":{"if":1}
,"selection":{"select":1,"script":1}
,"et":{"selection":1}
,"prompts":{"user":1}
,"user":{"cut":1}
,"email":{"field":1,"address":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"dialog":{"[\u0022":1}
,"[\u0022":{"want":1}
,"customer\u0027s":{"email":1}
,"address":{"\u0022]":1}
,"\u0022]":{"if":1}
,"[get":{"lastmessagechoice":1}
,"lastmessagechoice":{"=1]":1,"=2]":1}
,"=1]":{"cut":1}
,"[customers":{":email]":1}
,":email]":{"else":1,"end":1}
,"else":{"if":1}
,"=2]":{"copy":1}
,"end":{"if":1}
,"opying":{"moving":1}
,"moving":{"data":1}
,"records":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
