var pairs =
{
"fieldbounds":{"eturns":1,"filename":1,"change":1,"customers":1}
,"eturns":{"location":1}
,"location":{"points":1,"returned":1}
,"points":{"each":1}
,"each":{"field":1}
,"field":{"boundary":1,"layout":1,"boundaries":1,"fieldbounds":1,"returns":1}
,"boundary":{"field\u0027s":1,"position":1,"degree":1}
,"field\u0027s":{"rotation":1}
,"rotation":{"degrees":1,"measured":1}
,"degrees":{"fieldbounds":1,"unrotated":1}
,"filename":{"layoutname":1,"-the":1}
,"layoutname":{"fieldname":1,"-the":1}
,"fieldname":{"filename":1,"-the":1}
,"-the":{"name":1}
,"name":{"open":1,"layout":1,"field":1}
,"open":{"database":1}
,"database":{"file":1}
,"file":{"local":1,"fieldname":1}
,"local":{"remote":1}
,"remote":{"layoutname":1}
,"layout":{"database":1,"text":1,"printer":1,"margins":1,"boundaries":1,"field":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"location":1}
,"returned":{"measured":1,"by":1}
,"measured":{"top":1,"counter-clockwise":1,"left":1}
,"top":{"-l":1,"field":1,"layout":1}
,"-l":{"eft":1}
,"eft":{"corner":1}
,"corner":{"layout":1}
,"printer":{"margins":1}
,"margins":{"order":1,"end":1}
,"order":{"position":1}
,"position":{"left":1,"top":1,"right":1,"bottom":1}
,"left":{"field":1,"top":1}
,"right":{"field":1}
,"bottom":{"field":1}
,"degree":{"rotation":1}
,"counter-clockwise":{"direction":1}
,"direction":{"degrees":1}
,"unrotated":{"layout":1}
,"end":{"field":1}
,"boundaries":{"measured":1,"returned":1}
,"by":{"fieldbounds":1}
,"change":{"move":1}
,"move":{"re-size":1}
,"re-size":{"field":1}
,"customers":{"layout":1}
,"returns":{"36":1}
,"36":{"48":1}
,"48":{"295":1}
,"295":{"65":1}
,"65":{"notice":1}
,"notice":{"all":1}
,"all":{"parameters":1}
,"parameters":{"enclosed":1}
,"enclosed":{"quotation":1}
,"quotation":{"marks":1}
,"marks":{"field":1}
}
;Search.control.loadWordPairs(pairs);
