var pairs =
{
"ving":{"nd":1}
,"nd":{"sending":1}
,"sending":{"records":1}
,"records":{"excel":1,"xporting":1,"repeating":1}
,"excel":{"fil":1,"file":1,"preview":1,"status":1,"dialog":1,"files":1}
,"fil":{"isplay":1}
,"isplay":{"layout":1}
,"layout":{"fields":1,"mode":1}
,"fields":{"want":1,"curre":1,"popovers":1,"frontmost":1,"hidden":1,"excel":1}
,"want":{"include":1,"control":1}
,"include":{"excel":1}
,"file":{"switching":1,"menu":1,"options":1,"except":1,"export":1}
,"switching":{"layouts":1}
,"layouts":{"browse":1}
,"browse":{"layout":1}
,"mode":{"choose":1,"save":1}
,"choose":{"file":1}
,"menu":{"save\u002Fsend":1}
,"save\u002Fsend":{"records":1}
,"preview":{"mode":1}
,"save":{"excel":1,"records":1}
,"status":{"toolbar":1}
,"toolbar":{"save":1}
,"dialog":{"box":1}
,"box":{"enter":1}
,"enter":{"name":1}
,"name":{"file":1}
,"options":{"lick":1}
,"lick":{"ave":1}
,"ave":{"all":1}
,"all":{"fields":1}
,"curre":{"nt":1}
,"nt":{"ayout":1}
,"ayout":{"re":1}
,"re":{"included":1}
,"included":{"excel":1,"if":1}
,"except":{"fields":1}
,"popovers":{"fields":1}
,"frontmost":{"anel":1}
,"anel":{"anel":1,"control":1}
,"control":{"fields":1}
,"hidden":{"by":1}
,"by":{"ide":1}
,"ide":{"object":1}
,"object":{"ption":1}
,"ption":{"included":1}
,"if":{"want":1}
,"export":{"records":1}
,"xporting":{"data":1}
,"data":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"ll":1}
,"ll":{"records":1}
,"repeating":{"field":1}
,"field":{"exported":1}
,"exported":{"single":1}
,"single":{"cell":1}
,"cell":{"access":1}
,"access":{"privileges":1}
,"privileges":{"allow":1}
,"allow":{"exporting":1}
,"exporting":{"order":1}
,"order":{"save":1}
,"files":{"database":1}
,"database":{"administrator":1}
}
;Search.control.loadWordPairs(pairs);
