var pairs =
{
"ting":{"fill":1}
,"fill":{"line":1,"layout":1,"object":1,"fill":1,"body":1,"setting":1,"color":1,"choose":1,"extend":1}
,"line":{"style":1,"color":1,"theme":1,"choose":1}
,"style":{"shadows":1,"width":1}
,"shadows":{"padding":1,"change":1,"objects":1,"pencil":1}
,"padding":{"change":1,"advanced":1,"object\u2019s":1,"values":1}
,"change":{"appearance":1,"choose":1,"value":1,"padding":1,"transparency":1}
,"appearance":{"objects":1,"appearance":1,"tab":1,"object":1,"shadows":1}
,"objects":{"layout":1,"fields":1,"inner":1,"part":1}
,"layout":{"parts":1,"background":1,"part":1,"mode":1,"bar":1}
,"parts":{"fill":1,"transparent":1,"selected":1,"change":1,"rounded":1}
,"background":{"solid":1,"transparent":1,"table":1,"select":1,"sure":1,"fill":1}
,"solid":{"color":1}
,"color":{"object":1,"border":1,"line":1,"palette":1,"opacity":1,"color":1,"fill":1,"swatch":1,"light":1,"generated":1,"hexadecimal":1,"value":1,"button":1,"add":1,"change":1,"drag":1,"picker":1,"chooser":1}
,"object":{"layout":1,"body":1,"state":1,"graphic":1,"including":1,"ayout":1,"types":1}
,"part":{"layout":1,"label":1,"it\u2019s":1,"fill":1,"background":1,"combination":1,"line":1,"color":1,"corner":1,"select":1}
,"transparent":{"layout":1,"ormatting":1,"object":1,"sure":1,"transparent":1,"fill":1}
,"mode":{"select":1}
,"select":{"objects":1,"effects":1,"graphic":1,"selecting":1}
,"label":{"inspector":1,"layout":1}
,"inspector":{"appearance":1,"graphic":1}
,"tab":{"change":1,"display":1,"fo":1,"controls":1}
,"body":{"part":1}
,"it\u2019s":{"state":1}
,"state":{"button":1,"list":1,"object":1}
,"button":{"pressed":1,"curvature":1,"mo":1,"next":1,"choose":1,"drag":1,"layout":1}
,"pressed":{"choose":1}
,"choose":{"object":1,"fill":1,"each":1,"solid":1,"color":1,"none":1,"transparent":1}
,"list":{"second":1,"tab":1}
,"second":{"list":1}
,"display":{"state":1,"formatting":1}
,"graphic":{"add":1,"inner":1,"th":1,"appearance":1,"all":1}
,"add":{"change":1,"existing":1,"shadows":1}
,"including":{"backgrounds":1}
,"backgrounds":{"text":1}
,"text":{"objects":1,"box":1}
,"fields":{"portals":1,"borders":1}
,"portals":{"layout":1,"border":1,"transparency":1}
,"table":{"table":1,"view":1}
,"view":{"if":1}
,"if":{"fill":1}
,"setting":{"portal":1}
,"portal":{"set":1,"rows":1,"ows":1}
,"set":{"portal":1,"specific":1,"individual":1}
,"rows":{"transparent":1}
,"ormatting":{"portals":1}
,"border":{"object":1,"control":1,"radius":1}
,"combination":{"borders":1}
,"borders":{"border":1,"repeating":1,"repetitions":1,"portal":1,"lines":1,"rounded":1}
,"control":{"borders":1,"style":1}
,"repeating":{"fields":1}
,"repetitions":{"alternate":1}
,"alternate":{"row":1}
,"row":{"border":1}
,"width":{"border":1}
,"ayout":{"part":1}
,"palette":{"button":1,"macos":1,"drag":1,"dr":1,"color":1,"use":1,"formatting":1,"fill":1,"display":1}
,"curvature":{"corners":1}
,"corners":{"object":1,"rounded":1}
,"corner":{"radius":1,"change":1,"rounded":1}
,"radius":{"choose":1,"frame":1}
,"each":{"corner":1}
,"value":{"points":1,"corner":1,"color":1,"characters":1,"sample":1}
,"points":{"larger":1,"ma":1}
,"larger":{"value":1}
,"rounded":{"borders":1,"corners":1,"rectangles":1}
,"ows":{"ormatting":1}
,"transparency":{"fill":1}
,"opacity":{"slider":1}
,"slider":{"windows":1,"color":1,"custom":1,"macos":1}
,"windows":{"drag":1,"color":1}
,"drag":{"slider":1,"opacity":1}
,"macos":{"color":1,"se":1}
,"custom":{"color":1}
,"theme":{"colors":1}
,"colors":{"color":1,"rgb":1}
,"dr":{"ag":1}
,"ag":{"color":1}
,"swatch":{"theme":1}
,"light":{"dark":1}
,"dark":{"variations":1}
,"variations":{"custom":1}
,"generated":{"by":1}
,"by":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"replace":1,"graphic":1}
,"replace":{"add":1}
,"existing":{"theme":1}
,"rgb":{"value":1}
,"hexadecimal":{"format":1}
,"format":{"appears":1}
,"appears":{"text":1}
,"box":{"enter":1}
,"enter":{"paste":1}
,"paste":{"value":1}
,"characters":{"set":1}
,"specific":{"color":1}
,"sample":{"color":1}
,"mo":{"ve":1}
,"ve":{"mouse":1}
,"mouse":{"pointer":1}
,"pointer":{"screen":1}
,"screen":{"color":1}
,"inner":{"outer":1,"shadow":1}
,"outer":{"shadows":1}
,"shadow":{"layout":1}
,"effects":{"options":1}
,"options":{"change":1,"advanced":1}
,"pencil":{"button":1}
,"next":{"option":1}
,"option":{"padding":1}
,"object\u2019s":{"edge":1}
,"edge":{"contents":1}
,"contents":{"change":1}
,"values":{"points":1}
,"ma":{"ke":1}
,"ke":{"sure":1}
,"sure":{"fill":1,"objects":1}
,"selected":{"layout":1,"inspector":1}
,"th":{"appearance":1}
,"fo":{"fill":1}
,"use":{"custom":1}
,"se":{"lect":1}
,"lect":{"objects":1}
,"selecting":{"layout":1}
,"none":{"transparent":1}
,"formatting":{"bar":1,"formatting":1}
,"bar":{"line":1,"formatting":1,"button":1,"can\u2019t":1}
,"can\u2019t":{"set":1}
,"individual":{"borders":1}
,"lines":{"ovals":1}
,"ovals":{"circles":1}
,"circles":{"tab":1}
,"controls":{"slide":1,"all":1}
,"slide":{"controls":1}
,"all":{"options":1,"object":1}
,"types":{"layout":1}
,"extend":{"behind":1}
,"behind":{"navigation":1}
,"navigation":{"parts":1}
,"rectangles":{"border":1}
,"frame":{"field":1,"color":1}
,"field":{"frame":1}
,"picker":{"color":1}
}
;Search.control.loadWordPairs(pairs);
