var pairs =
{
"dding":{"tab":1}
,"tab":{"contro":1,"control":1,"tab":1,"name":1,"panel":1,"label":1,"panels":1,"choose":1,"justification":1,"width":1}
,"contro":{"layout":1}
,"layout":{"mode":1,"want":1,"pop-up":1,"tools":1}
,"mode":{"choose":1,"mode":1,"switch":1,"frontmost":1}
,"choose":{"layout":1,"tab":1,"panel":1,"units":1,"insert":1}
,"want":{"layout":1,"apply":1,"front":1}
,"pop-up":{"menu":1}
,"menu":{"status":1,"drag":1}
,"status":{"toolbar":1}
,"toolbar":{"windows":1,"choose":1}
,"windows":{"arrow":1}
,"arrow":{"next":1}
,"next":{"tab":1}
,"control":{"tool":1,"drag":1,"macos":1,"name":1,"setup":1,"select":1,"portal":1,"popover":1}
,"tool":{"tab":1,"slide":1,"choose":1}
,"slide":{"control":1}
,"drag":{"crosshair":1,"objects":1}
,"crosshair":{"draw":1}
,"draw":{"tab":1}
,"macos":{"hold":1}
,"hold":{"tab":1}
,"name":{"tab":1,"type":1}
,"setup":{"dialog":1}
,"dialog":{"box":1}
,"box":{"tab":1,"create":1,"11":1}
,"type":{"name":1}
,"panel":{"create":1,"want":1,"last":1,"use":1,"ou":1}
,"create":{"tab":1,"repeat":1,"additional":1}
,"label":{"based":1,"width":1,"minimum":1}
,"based":{"calculation":1}
,"calculation":{"calculation":1,"dialog":1}
,"repeat":{"steps":1}
,"steps":{"create":1}
,"additional":{"tab":1}
,"panels":{"if":1}
,"if":{"want":1}
,"apply":{"style":1}
,"style":{"all":1,"default":1}
,"all":{"tabs":1}
,"tabs":{"tab":1,"share":1}
,"select":{"tabs":1}
,"share":{"single":1}
,"single":{"style":1}
,"default":{"front":1}
,"front":{"tab":1,"switch":1}
,"switch":{"layout":1}
,"frontmost":{"ab":1}
,"ab":{"panel":1}
,"last":{"displayed":1}
,"displayed":{"previous":1}
,"previous":{"mode":1}
,"justification":{"options":1}
,"options":{"left":1,"label":1}
,"left":{"center":1}
,"center":{"right":1}
,"right":{"full":1}
,"full":{"choose":1}
,"width":{"options":1,"label":1,"margin":1,"widest":1,"10":1,"choose":1}
,"margin":{"width":1,"minimum":1}
,"widest":{"label":1}
,"minimum":{"fixed":1}
,"fixed":{"width":1}
,"10":{"label":1}
,"units":{"option":1}
,"option":{"inches":1}
,"inches":{"centimeter":1}
,"centimeter":{"points":1}
,"points":{"enter":1}
,"enter":{"value":1}
,"value":{"box":1}
,"11":{"12":1}
,"12":{"add":1}
,"add":{"objects":1}
,"objects":{"tab":1}
,"use":{"layout":1}
,"tools":{"status":1}
,"insert":{"menu":1}
,"ou":{"place":1}
,"place":{"tab":1}
,"portal":{"place":1}
,"popover":{"portal":1}
}
;Search.control.loadWordPairs(pairs);
