var pairs =
{
"onobjectkeystroke":{"performs":1,"script":1,"onlayoutkeystroke":1}
,"performs":{"script":1}
,"script":{"hen":1,"trigger":1,"script":1,"step":1,"return":1,"proceeds":1,"canceled":1,"rigger":1,"processes":1,"char":1,"triggered":1,"executed":1,"triggers":1,"runs":1}
,"hen":{"object":1}
,"object":{"active":1,"if":1,"alert":1,"web":1}
,"active":{"receives":1,"object":1}
,"receives":{"characters":1}
,"characters":{"keyboard":1,"activated":1,"navigational":1,"code":1,"unicode":1,"script":1}
,"keyboard":{"via":1,"shortcut":1,"shortcuts":1}
,"via":{"input":1}
,"input":{"method":1}
,"method":{"editor":1}
,"editor":{"ime":1}
,"ime":{"use":1,"activate":1,"triggered":1}
,"use":{"get":1,"exit":1,"key":1}
,"get":{"triggerkeystroke":1,"triggermodifierkeys":1}
,"triggerkeystroke":{"function":1}
,"function":{"return":1,"list":1,"returns":1}
,"return":{"characters":1,"true":1}
,"activated":{"script":1,"assigned":1}
,"trigger":{"event":1,"activates":1,"rocesses":1,"processes":1,"stop":1,"arrow":1,"entering":1,"onobjectexit":1,"onobjectkeystroke":1,"activated":1,"result":1}
,"event":{"processed":1,"triggered":1}
,"processed":{"browse":1,"order":1,"by":1}
,"browse":{"find":1}
,"find":{"modes":1}
,"modes":{"use":1,"trigger":1}
,"exit":{"script":1}
,"step":{"ithin":1}
,"ithin":{"triggered":1}
,"triggered":{"script":1,"by":1}
,"true":{"false":1,"event":1}
,"false":{"true":1,"event":1,"keyboard":1}
,"proceeds":{"false":1}
,"canceled":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"10.0":1,"advanced":1}
,"10.0":{"ombining":1}
,"ombining":{"keystrokes":1}
,"keystrokes":{"ime":1,"processed":1}
,"activate":{"script":1,"if":1}
,"rigger":{"trigger":1,"onobjectkeystroke":1,"script":1}
,"activates":{"text":1}
,"text":{"committed":1,"fields":1}
,"committed":{"ime":1,"string":1}
,"processes":{"committed":1,"keys":1,"keyboard":1,"characters":1}
,"string":{"use":1}
,"triggermodifierkeys":{"code":1}
,"code":{"char":1,"function":1,"points":1}
,"char":{"functions":1,"function":1}
,"functions":{"special":1}
,"special":{"characters":1}
,"navigational":{"keys":1}
,"keys":{"tab":1,"general":1,"codes":1,"filemaker":1,"script":1,"navigation":1,"processed":1,"first":1,"mouse":1}
,"tab":{"arrow":1}
,"arrow":{"keys":1}
,"general":{"unicode":1}
,"unicode":{"characters":1,"code":1}
,"list":{"navigational":1,"actions":1}
,"codes":{"reported":1}
,"reported":{"script":1}
,"returns":{"characters":1}
,"points":{"keystrokes":1}
,"order":{"operating":1}
,"operating":{"system":1}
,"system":{"processes":1}
,"advanced":{"processes":1}
,"shortcut":{"keys":1}
,"by":{"onobjectkeystroke":1,"onlayoutkeystroke":1,"active":1,"returning":1}
,"rocesses":{"characters":1}
,"onlayoutkeystroke":{"script":1}
,"navigation":{"while":1}
,"while":{"non-navigational":1}
,"non-navigational":{"keys":1}
,"if":{"if":1,"active":1}
,"alert":{"displays":1}
,"displays":{"non-navigational":1}
,"first":{"steps":1}
,"steps":{"use":1}
,"key":{"stops":1}
,"stops":{"process":1}
,"process":{"script":1}
,"executed":{"by":1}
,"stop":{"further":1}
,"further":{"processing":1}
,"processing":{"keystroke":1}
,"keystroke":{"by":1}
,"returning":{"false":1}
,"shortcuts":{"cut":1}
,"cut":{"paste":1}
,"paste":{"actions":1}
,"actions":{"trl":1,"don\u2019t":1,"activate":1}
,"trl":{"ctrl":1}
,"ctrl":{"windows":1}
,"windows":{"ommand-x":1}
,"ommand-x":{"command-v":1}
,"command-v":{"macos":1}
,"macos":{"activate":1}
,"mouse":{"navigate":1}
,"navigate":{"select":1}
,"select":{"pop-up":1}
,"pop-up":{"lists":1}
,"lists":{"menus":1}
,"menus":{"calendars":1}
,"calendars":{"activate":1}
,"entering":{"text":1}
,"fields":{"activate":1,"actions":1}
,"triggers":{"activate":1,"list":1}
,"web":{"viewer":1}
,"viewer":{"onobjectenter":1}
,"onobjectenter":{"script":1}
,"onobjectexit":{"script":1}
,"assigned":{"summary":1}
,"summary":{"calculation":1}
,"calculation":{"fields":1}
,"don\u2019t":{"activate":1}
,"runs":{"modes":1}
}
;Search.control.loadWordPairs(pairs);
