var pairs =
{
"get":{"windowdesktop":1,"windowdesktopheight":1,"window":1}
,"windowdesktop":{"height":1}
,"height":{"returns":1,"points":1}
,"returns":{"height":1,"1040":1,"1347":1}
,"points":{"desktop":1,"dock":1,"located":1}
,"desktop":{"space":1,"height":1}
,"space":{"get":1,"monitor":1,"main":1,"entire":1}
,"windowdesktopheight":{"none":1,"get":1}
,"none":{"number":1}
,"number":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1,"go":1}
,"pro":{"7.0":1,"advanced":1}
,"7.0":{"filemaker":1}
,"advanced":{"desktop":1}
,"monitor":{"screen":1,"active":1,"taskbar":1,"resolution":1}
,"screen":{"active":1,"macos":1,"returns":1,"get":1}
,"active":{"window":1}
,"window":{"located":1,"desktop":1}
,"located":{"excluding":1,"windows":1,"filemaker":1,"bottom":1}
,"excluding":{"taskbar":1}
,"taskbar":{"windows":1,"located":1}
,"windows":{"menu":1,"main":1,"single":1}
,"menu":{"bar":1,"bars":1}
,"bar":{"dock":1,"23":1}
,"dock":{"macos":1,"70":1}
,"macos":{"filemaker":1,"all":1,"single":1}
,"webdirect":{"desktop":1}
,"main":{"monitor":1}
,"all":{"monitors":1}
,"monitors":{"menu":1}
,"bars":{"main":1}
,"go":{"desktop":1}
,"entire":{"screen":1}
,"1040":{"windows":1}
,"single":{"monitor":1}
,"resolution":{"set":1}
,"set":{"1920":1,"2560":1}
,"1920":{"1080":1}
,"1080":{"returns":1}
,"1347":{"macos":1}
,"2560":{"1440":1}
,"1440":{"menu":1}
,"23":{"points":1}
,"70":{"points":1}
,"bottom":{"screen":1}
}
;Search.control.loadWordPairs(pairs);
