var pairs =
{
"tablenames":{"eturns":1,"filename":1,"university":1}
,"eturns":{"list":1}
,"list":{"all":1}
,"all":{"table":1}
,"table":{"occurrences":1,"occurrence":1}
,"occurrences":{"relationships":1,"teachers":1}
,"relationships":{"graph":1}
,"graph":{"filename":1}
,"filename":{"tablenames":1,"filename":1,"-the":1}
,"-the":{"name":1}
,"name":{"open":1}
,"open":{"database":1}
,"database":{"file":1,"returns":1,"database":1}
,"file":{"local":1,"if":1}
,"local":{"remote":1}
,"remote":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"listed":1}
,"listed":{"items":1}
,"items":{"separated":1}
,"separated":{"by":1}
,"by":{"carriage":1}
,"carriage":{"returns":1}
,"returns":{"tablenames":1,"table":1}
,"university":{"database":1}
,"teachers":{"coaches":1,"table":1}
,"coaches":{"university":1,"table":1}
,"if":{"teachers":1}
,"occurrence":{"coaches":1,"defined":1}
,"defined":{"file":1}
}
;Search.control.loadWordPairs(pairs);
