var pairs =
{
"hanging":{"tab":1}
,"tab":{"control":1,"panel":1,"name":1,"label":1,"panels":1,"choose":1,"controls":1}
,"control":{"layout":1,"select":1,"choose":1,"setup":1,"add":1,"next":1,"deleting":1}
,"layout":{"mode":1,"reorder":1}
,"mode":{"double-click":1,"mode":1,"switch":1,"front":1,"delete":1}
,"double-click":{"tab":1}
,"select":{"tab":1,"name":1}
,"choose":{"format":1,"panel":1}
,"format":{"menu":1}
,"menu":{"tab":1}
,"setup":{"ake":1}
,"ake":{"tab":1}
,"add":{"new":1}
,"new":{"tab":1,"name":1}
,"panel":{"tab":1,"tabs":1,"deleted":1,"want":1,"last":1}
,"name":{"type":1,"create":1,"rename":1,"delete":1,"set":1}
,"type":{"new":1}
,"create":{"create":1,"tab":1}
,"label":{"based":1}
,"based":{"calculation":1}
,"calculation":{"calculation":1,"dialog":1,"remove":1}
,"dialog":{"box":1}
,"box":{"rename":1}
,"rename":{"tab":1,"create":1}
,"tabs":{"list":1}
,"list":{"select":1,"drag":1}
,"remove":{"tab":1}
,"delete":{"all":1,"tab":1}
,"all":{"objects":1}
,"objects":{"tab":1}
,"deleted":{"layout":1}
,"reorder":{"tab":1}
,"panels":{"tabs":1}
,"drag":{"double":1}
,"double":{"arrow":1}
,"arrow":{"double":1,"control":1}
,"next":{"tab":1}
,"set":{"tab":1}
,"want":{"front":1}
,"front":{"by":1,"tab":1,"switch":1}
,"by":{"default":1}
,"default":{"default":1,"front":1}
,"switch":{"layout":1}
,"last":{"displayed":1}
,"displayed":{"previous":1}
,"previous":{"mode":1}
,"deleting":{"tab":1}
}
;Search.control.loadWordPairs(pairs);
