var pairs =
{
"get":{"trigger":1,"triggergestureinfo":1,"script":1}
,"trigger":{"gestureinfo":1,"get":1,"value":1,"activated":1,"gesture":1}
,"gestureinfo":{"returns":1}
,"returns":{"details":1,"list":1,"values":1,"empty":1,"tap":1}
,"details":{"gesture":1}
,"gesture":{"activated":1,"occurred":1,"list":1,"info":1}
,"activated":{"ongesturetap":1,"filemaker":1}
,"ongesturetap":{"script":1}
,"script":{"trigger":1,"started":1,"triggered":1}
,"triggergestureinfo":{"none":1,"get":1}
,"none":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1,"go":1,"webdirect":1}
,"pro":{"13.0":1,"advanced":1}
,"13.0":{"filemaker":1}
,"advanced":{"windows":1}
,"windows":{"filemaker":1,"returns":1}
,"go":{"returns":1}
,"list":{"items":1,"view":1,"if":1,"entire":1,"return":1}
,"items":{"string":1}
,"string":{"tap":1,"if":1,"script":1}
,"tap":{"indicating":1,"count":1,"coordinate":1,"entire":1,"bottom":1,"two":1,"gesture":1,"400":1}
,"indicating":{"script":1,"tap":1,"fingers":1}
,"started":{"by":1}
,"by":{"ongesturetap":1,"three-finger":1}
,"value":{"indicating":1}
,"count":{"value":1}
,"fingers":{"tap":1,"ios":1,"windows":1}
,"coordinate":{"document":1}
,"document":{"gesture":1}
,"occurred":{"coordinate":1,"coordinates":1}
,"coordinates":{"0,0":1,"returned":1,"21,199140":1,"400,600":1}
,"0,0":{"located":1}
,"located":{"top-left":1}
,"top-left":{"corner":1}
,"corner":{"topmost":1}
,"topmost":{"layout":1}
,"layout":{"part":1,"header":1,"200,075":1}
,"part":{"multifinger":1}
,"multifinger":{"gestures":1}
,"gestures":{"coordinates":1,"tap":1}
,"returned":{"center":1,"reflect":1}
,"center":{"point":1}
,"point":{"gesture":1}
,"view":{"coordinates":1}
,"reflect":{"location":1}
,"location":{"tap":1}
,"entire":{"list":1,"layout":1}
,"if":{"layout":1,"function":1}
,"header":{"50":1}
,"50":{"points":1}
,"points":{"height":1}
,"height":{"body":1,"footer":1,"1000":1,"tap":1}
,"body":{"200":1}
,"200":{"points":1}
,"footer":{"25":1}
,"25":{"points":1}
,"1000":{"records":1}
,"records":{"list":1}
,"200,075":{"points":1}
,"bottom":{"list":1}
,"return":{"coordinates":1}
,"21,199140":{"function":1}
,"function":{"returns":1,"executed":1,"supported":1}
,"values":{"gestures":1}
,"two":{"fingers":1}
,"ios":{"double-tap":1,"tap":1}
,"double-tap":{"finger":1}
,"finger":{"ios":1}
,"empty":{"string":1}
,"executed":{"ongesturetap":1}
,"webdirect":{"function":1}
,"supported":{"returns":1}
,"triggered":{"by":1}
,"three-finger":{"tap":1}
,"400,600":{"function":1}
,"400":{"600":1}
,"600":{"get":1}
,"info":{"get":1}
}
;Search.control.loadWordPairs(pairs);
