var pairs =
{
"cryptdecryptbase64":{"decrypts":1,"text":1,"cryptencryptbase64":1}
,"decrypts":{"base64-encoded":1}
,"base64-encoded":{"text":1}
,"text":{"key":1,"container":1,"-any":1,"expression":1,"field":1,"text":1,"returned":1,"encrypted":1}
,"key":{"returns":1,"text":1,"-any":1,"encrypt":1,"cryptdecryptbase64":1}
,"returns":{"text":1,"returns":1,"protection":1}
,"container":{"data":1,"filemaker":1}
,"data":{"cryptdecryptbase64":1,"returned":1}
,"-any":{"text":1,"expression":1}
,"expression":{"text":1,"field":1}
,"field":{"data":1,"key":1}
,"returned":{"by":1}
,"by":{"cryptencryptbase64":1}
,"cryptencryptbase64":{"function":1,"key":1,"protection":1}
,"function":{"key":1,"cryptdecrypt":1,"except":1,"function":1,"supported":1}
,"encrypt":{"text":1}
,"filemaker":{"pro":1}
,"pro":{"16.0":1}
,"16.0":{"function":1}
,"cryptdecrypt":{"function":1}
,"except":{"accepts":1}
,"accepts":{"base64-encoded":1}
,"supported":{"runtime":1}
,"runtime":{"solutions":1}
,"solutions":{"returns":1}
,"protection":{"text":1,"secret":1}
,"encrypted":{"cryptencryptbase64":1}
,"secret":{"password":1}
,"password":{"secret":1}
}
;Search.control.loadWordPairs(pairs);
