var pairs =
{
"get":{"systemlangu":1,"systemlanguage":1,"system":1}
,"systemlangu":{"age":1}
,"age":{"returns":1}
,"returns":{"language":1,"client\u2019s":1,"web":1,"japanese":1}
,"language":{"currently":1,"hosted":1,"filemaker":1,"returns":1}
,"currently":{"set":1}
,"set":{"current":1,"use":1}
,"current":{"system":1,"language":1,"format":1}
,"system":{"get":1,"preferences":1,"language":1,"formats":1,"lanugage":1}
,"systemlanguage":{"none":1,"evaluated":1,"returns":1,"get":1}
,"none":{"text":1}
,"text":{"filemaker":1,"returned":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"get":1}
,"evaluated":{"formats":1}
,"formats":{"setting":1,"script":1}
,"setting":{"control":1}
,"control":{"panel":1}
,"panel":{"windows":1}
,"windows":{"system":1}
,"preferences":{"macos":1}
,"macos":{"text":1}
,"returned":{"english":1}
,"english":{"language":1}
,"hosted":{"databases":1}
,"databases":{"get":1}
,"client\u2019s":{"current":1}
,"webdirect":{"get":1}
,"web":{"browser\u2019s":1}
,"browser\u2019s":{"current":1}
,"japanese":{"japanese":1,"current":1}
,"format":{"region":1}
,"region":{"script":1}
,"script":{"set":1,"step":1}
,"use":{"system":1}
,"step":{"get":1}
}
;Search.control.loadWordPairs(pairs);
