var pairs =
{
"ial":{"phone":1}
,"phone":{"ials":1,"script":1,"dialog":1,"number":1,"preferences":1,"[with":1,"field":1,")]":1,"1234567890":1}
,"ials":{"phone":1}
,"script":{"dialog":1,"step":1,"dial":1}
,"dialog":{"specifies":1,"box":1,"5550987654":1,"customers":1,"filter":1}
,"specifies":{"display":1}
,"display":{"dial":1}
,"dial":{"phone":1,"create":1}
,"box":{"script":1}
,"step":{"performed":1,"supported":1,"use":1}
,"performed":{"phone":1}
,"number":{"enter":1,"dial":1,"filemaker":1,"calculation":1,"number":1,"text":1,"translated":1,"numerical":1,"contained":1,"go":1}
,"enter":{"phone":1}
,"create":{"calculation":1,"phone":1,"scripts":1}
,"calculation":{"generate":1,"create":1,"global":1}
,"generate":{"phone":1}
,"filemaker":{"pro":1,"go":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"enter":1}
,"text":{"calculation":1}
,"global":{"fields":1}
,"fields":{"letters":1}
,"letters":{"phone":1}
,"translated":{"numbers":1}
,"numbers":{"except":1}
,"except":{"choose":1}
,"choose":{"use":1}
,"use":{"current":1,"filemaker":1}
,"current":{"phone":1,"location":1,"record":1}
,"preferences":{"based":1}
,"based":{"current":1}
,"location":{"place":1}
,"place":{"international":1}
,"international":{"call":1}
,"call":{"filemaker":1}
,"go":{"filter":1,"dials":1,"layout":1}
,"filter":{"phone":1,"customers":1}
,"numerical":{"digits":1}
,"digits":{"symbol":1}
,"symbol":{"dial":1}
,"supported":{"macos":1}
,"macos":{"create":1}
,"scripts":{"include":1}
,"include":{"dial":1}
,"dials":{"phone":1,"filtered":1}
,"contained":{"script":1,"phone":1}
,"[with":{"dialog":1}
,"5550987654":{"\u0022]":1}
,"\u0022]":{"dials":1,"if":1}
,"field":{"current":1,"characters":1}
,"record":{"go":1}
,"layout":{"[\u0022":1}
,"[\u0022":{"customer":1}
,"customer":{"details":1}
,"details":{"\u0022]":1}
,"if":{"[not":1,"filters":1,"automating":1}
,"[not":{"isempty":1}
,"isempty":{"customers":1}
,"customers":{":work":1}
,":work":{"phone":1,"phone]":1}
,")]":{"dial":1,"end":1}
,"phone]":{"end":1}
,"end":{"if":1}
,"filters":{"contents":1}
,"contents":{"phone":1}
,"characters":{"dials":1}
,"filtered":{"number":1}
,"1234567890":{")]":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
