var pairs =
{
"get":{"uuid":1,"uuidnumber":1}
,"uuid":{"returns":1,"get":1,"none":1,"evaluated":1,"defining":1,"storage":1}
,"returns":{"text":1,"unique":1,"new":1}
,"text":{"representing":1,"filemaker":1,"field":1}
,"representing":{"universally":1}
,"universally":{"unique":1}
,"unique":{"identifier":1,"16-byte":1,"id":1}
,"identifier":{"uuid":1}
,"none":{"text":1}
,"filemaker":{"pro":1}
,"pro":{"12.0":1,"advanced":1}
,"12.0":{"returns":1}
,"16-byte":{"128-bit":1}
,"128-bit":{"string":1}
,"string":{"use":1,"each":1,"generated":1}
,"use":{"function":1,"technique":1,"get":1}
,"function":{"generate":1,"requires":1}
,"generate":{"unique":1}
,"id":{"record":1,"field":1}
,"record":{"unstored":1,"unique":1,"accessed":1}
,"unstored":{"calculations":1,"calculation":1}
,"calculations":{"returns":1}
,"new":{"string":1,"record":1}
,"each":{"time":1}
,"time":{"get":1,"record":1}
,"evaluated":{"auto-enter":1}
,"auto-enter":{"calculation":1}
,"calculation":{"text":1,"get":1,"calculation":1,"field":1,"time":1}
,"field":{"auto-enter":1,"e47e7ae0-5cf0-ff45-b3ad-c12b3e765cd5":1,"if":1,"calculation":1}
,"defining":{"automatic":1}
,"automatic":{"data":1}
,"data":{"entry":1}
,"entry":{"new":1}
,"e47e7ae0-5cf0-ff45-b3ad-c12b3e765cd5":{"use":1}
,"technique":{"define":1}
,"define":{"primary":1}
,"primary":{"key":1}
,"key":{"field":1}
,"if":{"can\u2019t":1}
,"can\u2019t":{"use":1}
,"uuidnumber":{"function":1}
,"requires":{"version":1}
,"version":{"filemaker":1}
,"advanced":{"unstored":1}
,"storage":{"options":1}
,"options":{"select":1}
,"select":{"store":1}
,"store":{"calculation":1}
,"accessed":{"new":1}
}
;Search.control.loadWordPairs(pairs);
