var pairs =
{
"get":{"triggercurrent":1,"triggercurrentpanel":1,"triggertargetpanel":1,"triggercurrenttabpanel":1,"trigger":1}
,"triggercurrent":{"panel":1}
,"panel":{"returns":1,"switch":1,"slide":1,"invalid":1,"switched":1,"number":1}
,"returns":{"index":1,"if":1,"category":1}
,"index":{"object":1,"value":1}
,"object":{"name":1}
,"name":{"panel":1,"assigned":1}
,"switch":{"onpanelswitch":1}
,"onpanelswitch":{"script":1}
,"script":{"trigger":1,"triggered":1}
,"trigger":{"activated":1,"object":1,"use":1,"current":1}
,"activated":{"get":1}
,"triggercurrentpanel":{"none":1,"onpanelswitch":1,"tab":1,"returns":1}
,"none":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"12.0":1}
,"12.0":{"use":1}
,"use":{"get":1,"getvalue":1,"index":1}
,"triggertargetpanel":{"function":1}
,"function":{"returns":1,"extract":1}
,"value":{"starting":1,"want":1,"returned":1}
,"starting":{"running":1}
,"running":{"script":1}
,"triggered":{"by":1}
,"by":{"onpanelswitch":1,"get":1}
,"assigned":{"tab":1}
,"tab":{"panel":1}
,"slide":{"panel":1}
,"if":{"panel":1,"get":1}
,"invalid":{"if":1}
,"getvalue":{"function":1}
,"extract":{"value":1}
,"want":{"use":1}
,"returned":{"by":1}
,"switched":{"panel":1}
,"number":{"named":1}
,"named":{"category":1}
,"category":{"get":1}
,"triggercurrenttabpanel":{"get":1}
,"current":{"tab":1}
}
;Search.control.loadWordPairs(pairs);
