var pairs =
{
"ccessing":{"external":1}
,"external":{"data":1,"sql":1}
,"data":{"sources":1,"external":1,"current":1,"iles":1,"odbc":1,"interactively":1,"source":1,"via":1}
,"sources":{"connect":1,"data":1,"filemaker":1,"odbc":1,"referred":1,"ess":1}
,"connect":{"data":1}
,"current":{"active":1}
,"active":{"filemaker":1}
,"filemaker":{"file":1,"fields":1,"tables":1,"pro":1,"odbc":1,"sql":1}
,"file":{"create":1}
,"create":{"tables":1,"relationships":1}
,"tables":{"relationships":1,"perform":1,"add":1,"fields":1,"construct":1}
,"relationships":{"graph":1,"fields":1}
,"graph":{"ilemaker":1}
,"ilemaker":{"files":1}
,"files":{"odbc":1}
,"odbc":{"data":1,"tables":1,"uerying":1,"client":1,"jdbc":1,"table":1}
,"iles":{"filemaker":1}
,"fields":{"layouts":1,"odbc":1,"filemaker":1,"called":1}
,"layouts":{"add":1}
,"add":{"supplemental":1,"change":1}
,"supplemental":{"fields":1}
,"perform":{"unstored":1}
,"unstored":{"calculations":1}
,"calculations":{"summarize":1}
,"summarize":{"data":1}
,"change":{"delete":1,"odbc":1}
,"delete":{"external":1}
,"interactively":{"create":1}
,"called":{"olumns":1}
,"olumns":{"odbc":1}
,"construct":{"sql":1}
,"sql":{"queries":1,"reference":1,"sources":1}
,"queries":{"importing":1,"use":1}
,"importing":{"via":1}
,"via":{"odbc":1}
,"uerying":{"odbc":1}
,"source":{"filemaker":1,"sh":1,"use":1}
,"pro":{"advanced":1}
,"advanced":{"link":1,"odbc":1,"data":1,"modify":1,"if":1}
,"link":{"odbc":1}
,"client":{"application":1}
,"application":{"write":1}
,"write":{"sql":1}
,"use":{"filemaker":1,"manage":1}
,"sh":{"ari":1}
,"ari":{"ng":1}
,"ng":{"filemaker":1}
,"jdbc":{"filemaker":1,"guide":1}
,"guide":{"filemaker":1}
,"reference":{"overview":1}
,"overview":{"various":1}
,"various":{"odbc":1}
,"modify":{"schema":1}
,"schema":{"dbc":1}
,"dbc":{"data":1}
,"if":{"table":1}
,"table":{"names":1,"est":1}
,"names":{"change":1}
,"manage":{"database":1}
,"database":{"dialog":1}
,"dialog":{"box":1}
,"box":{"re":1}
,"re":{"ink":1}
,"ink":{"odbc":1}
,"est":{"ks":1}
,"ks":{"odbc":1}
,"referred":{"external":1}
}
;Search.control.loadWordPairs(pairs);
