var pairs =
{
"get":{"multi":1,"multiuserstate":1,"multiuser":1,"sharing":1}
,"multi":{"userstate":1,"user":1}
,"userstate":{"returns":1}
,"returns":{"number":1,"network":1,"access":1}
,"number":{"representing":1,"filemaker":1}
,"representing":{"level":1}
,"level":{"sharing":1}
,"sharing":{"file":1,"network":1,"you\u2019re":1,"level":1}
,"file":{"filemaker":1,"host":1,"network":1,"client":1,"if":1}
,"filemaker":{"network":1,"pro":1}
,"network":{"get":1,"sharing":1,"access":1}
,"multiuserstate":{"none":1,"get":1}
,"none":{"number":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"returns":1}
,"you\u2019re":{"accessing":1}
,"accessing":{"database":1}
,"database":{"file":1}
,"host":{"computer":1}
,"computer":{"all":1}
,"all":{"users":1}
,"users":{"specific":1,"based":1,"script":1}
,"specific":{"group":1}
,"group":{"users":1}
,"based":{"privilege":1,"context":1}
,"privilege":{"set":1}
,"set":{"network":1,"multi-user":1}
,"access":{"database":1,"denied":1}
,"client":{"computer":1}
,"if":{"current":1}
,"current":{"calculation":1,"window":1}
,"calculation":{"stored":1}
,"stored":{"context":1}
,"context":{"function":1,"evaluated":1,"current":1}
,"function":{"evaluated":1}
,"evaluated":{"based":1}
,"window":{"returns":1}
,"denied":{"users":1}
,"script":{"set":1,"step":1}
,"multi-user":{"script":1}
,"step":{"get":1}
,"multiuser":{"state":1}
,"state":{"get":1}
,"user":{"state":1}
}
;Search.control.loadWordPairs(pairs);
