var pairs =
{
"onstructing":{"sql":1}
,"sql":{"query":1,"statement":1}
,"query":{"importing":1,"builder":1,"sql":1,"store":1,"field":1,"insert":1,"constructs":1,"box":1,"by":1,"map":1,"use":1}
,"importing":{"via":1,"existing":1,"order":1}
,"via":{"odbc":1}
,"odbc":{"access":1,"data":1}
,"access":{"odbc":1}
,"data":{"source":1,"two":1}
,"source":{"use":1,"dbms":1,"if":1,"choose":1,"sql":1,"records":1,"decide":1}
,"use":{"sql":1,"toring":1}
,"builder":{"construct":1,"dialog":1}
,"construct":{"execute":1,"queries":1,"search":1,"query":1}
,"execute":{"query":1}
,"queries":{"search":1,"retrieving":1}
,"search":{"odbc":1,"criteria":1}
,"dbms":{"fetch":1}
,"fetch":{"specific":1}
,"specific":{"records":1}
,"records":{"import":1,"filemaker":1,"take":1,"odbc":1,"choose":1,"imported":1,"importing":1,"create":1,"data":1,"want":1,"database":1}
,"import":{"records":1,"columns":1,"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"atabase":1,"file":1,"mports":1}
,"atabase":{"file":1}
,"file":{"execute":1,"choose":1,"menu":1,"data":1,"dialog":1,"files":1,"type":1}
,"store":{"field":1}
,"field":{"repeated":1,"details":1}
,"repeated":{"use":1}
,"toring":{"sql":1}
,"details":{"note":1}
,"note":{"performing":1}
,"performing":{"complex":1}
,"complex":{"queries":1}
,"retrieving":{"large":1}
,"large":{"number":1}
,"number":{"records":1}
,"take":{"time":1}
,"time":{"batching":1}
,"batching":{"requests":1}
,"requests":{"optimal":1}
,"optimal":{"performance":1}
,"performance":{"choose":1}
,"choose":{"data":1,"file":1,"odbc":1,"column":1,"append":1}
,"if":{"you\u2019re":1}
,"you\u2019re":{"importing":1,"creating":1}
,"existing":{"filemaker":1}
,"menu":{"import":1,"open":1}
,"dialog":{"box":1}
,"box":{"appears":1,"first":1,"locate":1,"table":1,"choose":1,"insert":1,"assure":1}
,"appears":{"password":1}
,"password":{"user":1}
,"user":{"name":1}
,"name":{"dialog":1,"tab":1,"column":1}
,"first":{"if":1,"select":1}
,"creating":{"filemaker":1}
,"open":{"open":1,"file":1}
,"locate":{"file":1}
,"files":{"type":1}
,"type":{"windows":1,"sql":1}
,"windows":{"show":1}
,"show":{"macos":1}
,"macos":{"choose":1}
,"select":{"tab":1}
,"tab":{"tables":1,"construct":1,"name":1}
,"tables":{"list":1,"sort":1}
,"list":{"box":1}
,"table":{"want":1,"columns":1,"browse":1}
,"want":{"import":1}
,"columns":{"associated":1,"list":1,"sql":1}
,"associated":{"table":1}
,"column":{"insert":1,"name":1,"sort":1}
,"insert":{"sql":1,"additional":1}
,"constructs":{"sql":1}
,"statement":{"sql":1}
,"additional":{"columns":1}
,"by":{"double-clicking":1,"tab":1,"sort":1}
,"double-clicking":{"column":1}
,"criteria":{"reduces":1}
,"reduces":{"number":1}
,"imported":{"join":1}
,"join":{"data":1}
,"two":{"tables":1}
,"sort":{"records":1,"by":1,"ascending":1}
,"order":{"by":1}
,"ascending":{"descending":1}
,"descending":{"execute":1}
,"map":{"fields":1}
,"fields":{"choose":1}
,"append":{"records":1}
,"create":{"table":1}
,"browse":{"records":1}
,"decide":{"records":1}
,"mports":{"records":1}
,"database":{"file":1}
,"assure":{"valid":1}
,"valid":{"sql":1}
}
;Search.control.loadWordPairs(pairs);
