var pairs =
{
"sing":{"field":1}
,"field":{"index":1,"view":1,"prevent":1,"defining":1,"indexing":1,"want":1,"treated":1,"filemaker":1}
,"index":{"filemaker":1,"values":1,"insert":1,"value":1,"view":1,"dialog":1,"want":1,"index":1,"order":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"create":1,"sorts":1}
,"create":{"index":1}
,"values":{"each":1,"index":1,"incorrectly":1,"indexing":1,"specific":1,"based":1}
,"each":{"text":1}
,"text":{"number":1,"field":1}
,"number":{"date":1}
,"date":{"time":1}
,"time":{"timestamp":1}
,"timestamp":{"calculation":1}
,"calculation":{"field":1}
,"view":{"values":1,"index":1}
,"insert":{"field":1,"index":1,"menu":1,"values":1}
,"prevent":{"typing":1}
,"typing":{"values":1}
,"incorrectly":{"note":1}
,"note":{"use":1}
,"use":{"index":1}
,"indexing":{"options":1,"sorting":1}
,"options":{"enabled":1,"browse":1}
,"enabled":{"field":1}
,"defining":{"field":1}
,"browse":{"mode":1}
,"mode":{"find":1,"field":1}
,"find":{"mode":1}
,"want":{"insert":1,"name":1,"display":1}
,"value":{"choose":1,"paste":1,"index":1}
,"choose":{"insert":1,"value":1,"language":1}
,"menu":{"index":1}
,"dialog":{"box":1}
,"box":{"choose":1,"show":1}
,"paste":{"ou":1}
,"ou":{"enter":1}
,"enter":{"two":1,"space":1}
,"two":{"field":1,"treated":1}
,"treated":{"word":1,"enter":1}
,"word":{"by":1,"view":1}
,"by":{"index":1,"pressing":1}
,"name":{"jean":1}
,"jean":{"louis":1}
,"louis":{"word":1}
,"show":{"individual":1}
,"individual":{"selected":1}
,"selected":{"two":1}
,"space":{"by":1,"bar":1}
,"pressing":{"ctrl":1}
,"ctrl":{"space":1}
,"bar":{"windows":1,"macos":1,"text":1}
,"windows":{"option-space":1}
,"option-space":{"bar":1}
,"macos":{"space":1}
,"sorts":{"value":1}
,"order":{"field\u2019s":1,"select":1}
,"field\u2019s":{"default":1}
,"default":{"language":1}
,"language":{"if":1,"hoosing":1,"indexing":1}
,"if":{"want":1}
,"display":{"values":1}
,"specific":{"language\u2019s":1}
,"language\u2019s":{"dictionary":1}
,"dictionary":{"sort":1}
,"sort":{"order":1}
,"select":{"re-sort":1}
,"re-sort":{"values":1}
,"based":{"choose":1}
,"hoosing":{"language":1}
,"sorting":{"insert":1}
}
;Search.control.loadWordPairs(pairs);
