var pairs =
{
"files":{"system":1,"filemaker":1,"use":1}
,"system":{"formats":1,"etting":1,"preferences":1,"saving":1}
,"formats":{"create":1,"determine":1,"use":1,"match":1,"file":1,"command":1,"change":1,"control":1,"first":1}
,"create":{"database":1}
,"database":{"files":1,"file":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"computer\u2019s":1}
,"computer\u2019s":{"system":1}
,"determine":{"dates":1}
,"dates":{"times":1}
,"times":{"numbers":1}
,"numbers":{"display":1}
,"display":{"sort":1}
,"sort":{"if":1}
,"if":{"open":1}
,"open":{"share":1,"file":1}
,"share":{"database":1}
,"file":{"created":1,"computer":1,"last":1,"option":1,"operating":1,"options":1,"note":1,"inherits":1}
,"created":{"system":1,"choose":1}
,"use":{"computer\u2019s":1,"system":1,"new":1}
,"match":{"formats":1}
,"choose":{"format":1}
,"format":{"menu":1}
,"menu":{"use":1,"open":1}
,"command":{"appears":1,"doesn\u2019t":1}
,"appears":{"format":1}
,"computer":{"system":1}
,"change":{"system":1}
,"last":{"use":1}
,"doesn\u2019t":{"interfere":1}
,"interfere":{"date":1}
,"date":{"time":1}
,"time":{"number":1}
,"number":{"formatting":1}
,"formatting":{"layout":1}
,"layout":{"mode":1}
,"mode":{"note":1}
,"note":{"set":1,"cloned":1}
,"set":{"data":1}
,"data":{"entry":1}
,"entry":{"file":1}
,"option":{"determines":1}
,"determines":{"occur":1}
,"occur":{"system":1}
,"operating":{"system":1}
,"etting":{"file":1}
,"options":{"change":1}
,"control":{"panel":1}
,"panel":{"windows":1}
,"windows":{"system":1}
,"preferences":{"macos":1}
,"macos":{"use":1}
,"new":{"settings":1}
,"settings":{"system\u2019s":1,"reopen":1}
,"system\u2019s":{"settings":1}
,"reopen":{"file":1}
,"cloned":{"database":1}
,"inherits":{"system":1}
,"first":{"operating":1}
,"saving":{"copying":1}
,"copying":{"files":1}
}
;Search.control.loadWordPairs(pairs);
