var pairs =
{
"sending":{"mail":1}
,"mail":{"messag":1,"send":1,"script":1}
,"messag":{"es":1}
,"es":{"find":1}
,"find":{"record":1}
,"record":{"records":1,"send":1,"found":1,"subject":1,"email":1}
,"records":{"data":1,"choose":1,"current":1}
,"data":{"want":1,"current":1}
,"want":{"use":1}
,"use":{"email":1,"contents":1}
,"email":{"finding":1,"application":1,"data":1,"addresses":1,"client":1,"step":1,"pecify":1,"address":1,"plain":1,"message\u2019s":1}
,"finding":{"records":1}
,"choose":{"file":1,"smtp":1,"field":1}
,"file":{"menu":1,"message":1,"next":1,"repeat":1}
,"menu":{"send":1}
,"send":{"mail":1,"via":1,"supported":1,"smtp":1,"message":1,"essage":1,"email":1}
,"via":{"send":1}
,"supported":{"email":1}
,"application":{"accept":1,"choose":1}
,"accept":{"default":1}
,"default":{"e-mail":1,"email":1}
,"e-mail":{"client":1}
,"client":{"send":1,"pecify":1,"message":1}
,"smtp":{"email":1,"server":1,"options":1}
,"server":{"enter":1}
,"enter":{"nt":1,"email":1,"text":1}
,"nt":{"ing":1}
,"ing":{"editing":1}
,"editing":{"smtp":1}
,"options":{"create":1}
,"create":{"send":1}
,"message":{"all":1,"depends":1,"enter":1,"nsert":1,"optional":1,"each":1}
,"all":{"ecipients":1,"recipients":1,"records":1}
,"ecipients":{"select":1}
,"select":{"email":1,"multiple":1,"collect":1,"file":1}
,"current":{"record":1,"found":1,"month":1}
,"essage":{"ach":1}
,"ach":{"record":1}
,"found":{"set":1}
,"set":{"all":1,"cc":1,"gather":1,"number":1}
,"recipients":{"select":1,"message":1}
,"multiple":{"emails":1}
,"emails":{"each":1}
,"each":{"record":1,"semicolon":1,"address":1}
,"cc":{"bcc":1}
,"bcc":{"enter":1}
,"addresses":{"separating":1,"pecify":1,"default":1,"if":1,"across":1,"all":1}
,"separating":{"each":1}
,"semicolon":{"return":1}
,"return":{"character":1,"characters":1}
,"character":{"arrow":1}
,"arrow":{"choose":1}
,"field":{"email":1,"name":1,"calculation":1,"text":1,"address":1}
,"pecify":{"field":1,"calculation":1,"email":1}
,"name":{"calculation":1}
,"calculation":{"generates":1,"windows":1,"step":1,"therwise":1,"if":1,"subject":1}
,"generates":{"email":1,"text":1}
,"windows":{"enter":1}
,"if":{"chose":1,"current":1,"contents":1}
,"chose":{"send":1}
,"step":{"field":1,"select":1}
,"collect":{"addresses":1}
,"across":{"found":1}
,"gather":{"addresses":1}
,"number":{"recipients":1}
,"depends":{"contents":1}
,"contents":{"fields":1,"text":1,"field":1,"send":1}
,"fields":{"result":1}
,"result":{"calculation":1}
,"therwise":{"address":1}
,"address":{"current":1,"field":1,"separated":1,"each":1}
,"subject":{"message":1,"returns":1}
,"text":{"arrow":1,"email":1,"file":1,"apply":1}
,"month":{"july":1}
,"july":{"calculation":1,"monthly":1}
,"returns":{"monthly":1}
,"monthly":{"report":1}
,"report":{"july":1,"&month":1}
,"&month":{"get":1}
,"get":{"currentdate":1}
,"currentdate":{"use":1}
,"nsert":{"text":1}
,"next":{"message":1}
,"optional":{"ttach":1}
,"ttach":{"fi":1}
,"fi":{"le":1}
,"le":{"select":1}
,"repeat":{"attach":1}
,"attach":{"additional":1}
,"additional":{"files":1}
,"files":{"if":1}
,"separated":{"by":1}
,"by":{"semicolons":1,"email":1}
,"semicolons":{"return":1}
,"characters":{"commas":1}
,"commas":{"required":1}
,"required":{"by":1}
,"plain":{"text":1}
,"apply":{"formatting":1}
,"formatting":{"change":1}
,"change":{"email":1}
,"message\u2019s":{"contents":1}
,"script":{"step":1}
}
;Search.control.loadWordPairs(pairs);
