var pairs =
{
"orking":{"popovers":1}
,"popovers":{"layouts":1,"simplify":1,"allow":1}
,"layouts":{"use":1}
,"use":{"popovers":1,"web":1}
,"simplify":{"entering":1}
,"entering":{"viewing":1}
,"viewing":{"data":1}
,"data":{"popover":1,"move":1,"fields":1}
,"popover":{"layout":1,"button":1,"created":1,"popover":1,"browse":1,"enter":1,"view":1}
,"layout":{"object":1,"popovers":1,"window":1,"layout":1,"mode":1}
,"object":{"allows":1}
,"allows":{"fields":1}
,"fields":{"text":1,"icons":1,"popover":1}
,"text":{"objects":1}
,"objects":{"layout":1,"popover":1}
,"allow":{"access":1}
,"access":{"additional":1}
,"additional":{"details":1}
,"details":{"controls":1}
,"controls":{"data":1,"just":1}
,"move":{"layout":1}
,"window":{"helping":1}
,"helping":{"maintain":1}
,"maintain":{"context":1}
,"context":{"add":1}
,"add":{"popover":1,"fields":1}
,"mode":{"create":1,"popover":1}
,"create":{"popover":1}
,"button":{"associated":1,"add":1,"open":1}
,"associated":{"popover":1}
,"created":{"popover":1}
,"icons":{"nd":1}
,"nd":{"objects":1}
,"browse":{"mode":1}
,"open":{"popover":1}
,"enter":{"view":1}
,"view":{"data":1,"charts":1}
,"charts":{"use":1}
,"web":{"viewers":1}
,"viewers":{"panel":1}
,"panel":{"controls":1}
,"just":{"layout":1}
}
;Search.control.loadWordPairs(pairs);
