var pairs =
{
"saving":{"copying":1,"compacted":1,"reverting":1}
,"copying":{"files":1}
,"files":{"by":1,"hosted":1}
,"by":{"default":1,"open":1,"creating":1,"filemaker":1}
,"default":{"filemaker":1,"ayout":1}
,"filemaker":{"pro":1,"server":1,"go":1}
,"pro":{"advanced":1}
,"advanced":{"automatically":1,"doesn\u2019t":1,"saves":1,"constantly":1,"database":1}
,"automatically":{"saves":1,"se":1,"option":1}
,"saves":{"commits":1,"sort":1,"computer\u2019s":1}
,"commits":{"data":1}
,"data":{"save":1,"actions":1,"self-contained":1,"stored":1,"if":1,"container":1,"externally":1,"saved":1,"failed":1}
,"save":{"command":1,"copy":1,"clone":1,"choose":1,"macos":1,"windows":1,"file\u2019s":1,"made":1,"record":1}
,"command":{"save":1,"moves":1,"supported":1}
,"copy":{"file":1,"navigate":1,"disk":1,"current":1,"optimize":1,"clone":1,"single":1,"copy":1,"options":1,"externally":1,"menu":1,"transfer.log":1}
,"file":{"backup":1,"data":1,"saved":1,"menu":1,"name":1,"duplicate":1,"compacted":1,"remove":1,"create":1,"all":1,"reference":1,"includes":1,"open":1,"sort":1,"add":1,"filemaker":1,"located":1}
,"backup":{"save":1}
,"clone":{"file":1,"records":1,"ile":1}
,"actions":{"file":1}
,"saved":{"se":1,"while":1,"di":1,"if":1,"disk":1,"by":1,"utomatically":1,"automatically":1,"clear":1}
,"se":{"filemaker":1,"etting":1,"saving":1}
,"doesn\u2019t":{"save":1}
,"choose":{"file":1,"copy":1,"self-contained":1}
,"menu":{"save":1,"command":1}
,"navigate":{"want":1}
,"want":{"save":1,"use":1,"control":1}
,"disk":{"file":1,"se":1,"script":1,"by":1}
,"name":{"windows":1}
,"windows":{"save":1,"type":1}
,"macos":{"type":1,"choose":1}
,"type":{"filename":1,"macos":1}
,"filename":{"save":1}
,"current":{"file":1}
,"duplicate":{"current":1}
,"compacted":{"copy":1}
,"optimize":{"file":1}
,"remove":{"blank":1}
,"blank":{"space":1}
,"space":{"saving":1}
,"records":{"save":1,"modifying":1,"omit":1,"close":1}
,"file\u2019s":{"tables":1,"container":1}
,"tables":{"layouts":1}
,"layouts":{"scripts":1}
,"scripts":{"page":1}
,"page":{"setup":1}
,"setup":{"options":1}
,"options":{"field":1,"copy":1,"embed":1}
,"field":{"definitions":1}
,"definitions":{"data":1}
,"self-contained":{"copy":1}
,"single":{"file":1}
,"create":{"copy":1}
,"all":{"container":1,"records":1}
,"container":{"data":1,"fields":1}
,"stored":{"file":1,"externally":1,"data":1,"ram":1}
,"reference":{"stored":1}
,"externally":{"by":1,"choose":1,"stored":1,"save":1}
,"open":{"secure":1,"re":1,"file":1}
,"secure":{"storage":1}
,"storage":{"embedded":1}
,"embedded":{"file\u2019s":1}
,"fields":{"note":1,"first":1,"store":1}
,"note":{"copy":1}
,"includes":{"container":1}
,"if":{"want":1,"open":1,"alert":1}
,"use":{"options":1}
,"embed":{"data":1}
,"first":{"se":1}
,"etting":{"up":1,"memory":1,"automatic":1}
,"up":{"container":1}
,"store":{"data":1}
,"made":{"state":1}
,"state":{"file":1}
,"while":{"file":1,"designing":1}
,"re":{"saved":1}
,"di":{"splaying":1}
,"splaying":{"record":1}
,"record":{"layout":1,"modifying":1,"sort":1,"filemaker":1,"data":1,"automatically":1}
,"layout":{"rting":1,"layout":1,"mode":1,"saved":1,"if":1,"save":1}
,"rting":{"records":1}
,"modifying":{"sort":1,"find":1}
,"sort":{"order":1,"records":1}
,"order":{"pe":1,"saved":1,"new":1}
,"pe":{"rforming":1}
,"rforming":{"find":1}
,"find":{"operations":1,"show":1,"reques":1}
,"operations":{"find":1}
,"show":{"all":1}
,"omit":{"record":1}
,"reques":{"hiding":1}
,"hiding":{"status":1}
,"status":{"toolbar":1}
,"toolbar":{"if":1}
,"close":{"file":1}
,"add":{"new":1}
,"new":{"record":1}
,"constantly":{"saves":1}
,"computer\u2019s":{"ram":1}
,"ram":{"cache":1,"hard":1}
,"cache":{"set":1,"disk":1}
,"set":{"interval":1,"preference":1}
,"interval":{"saved":1}
,"memory":{"preferences":1}
,"preferences":{"pecify":1}
,"pecify":{"hanges":1}
,"hanges":{"saved":1}
,"creating":{"executing":1}
,"executing":{"script":1}
,"script":{"flush":1,"step":1,"command":1}
,"flush":{"cache":1}
,"step":{"script":1}
,"moves":{"stored":1}
,"hard":{"disk":1}
,"ayout":{"design":1}
,"design":{"saved":1}
,"utomatically":{"therefore":1}
,"therefore":{"ave":1}
,"ave":{"periodically":1}
,"periodically":{"while":1}
,"designing":{"layout":1}
,"mode":{"set":1}
,"preference":{"layout":1}
,"reverting":{"layout":1}
,"control":{"record":1}
,"clear":{"save":1}
,"option":{"layout-by-layout":1,"layout":1}
,"layout-by-layout":{"basis":1}
,"basis":{"se":1}
,"automatic":{"record-saving":1}
,"record-saving":{"option":1}
,"supported":{"filemaker":1}
,"database":{"files":1}
,"hosted":{"by":1}
,"server":{"if":1}
,"alert":{"container":1}
,"failed":{"transfer":1}
,"transfer":{"created":1}
,"created":{"self-contained":1}
,"transfer.log":{"file":1}
,"located":{"user\u2019s":1}
,"user\u2019s":{"documents":1}
,"documents":{"folder":1}
,"folder":{"details":1}
,"details":{"filemaker":1}
,"go":{"copy":1}
,"ile":{"filemaker":1}
}
;Search.control.loadWordPairs(pairs);
