var pairs =
{
"hexencode":{"returns":1,"data":1,"filemaker":1,"table":1}
,"returns":{"data":1,"hexencode":1,"46696c654d616b6572":1}
,"data":{"text":1,"data":1,"-any":1,"converted":1}
,"text":{"hexadecimal":1,"expression":1,"filemaker":1,"text":1,"fields":1,"stores":1,"field":1}
,"hexadecimal":{"format":1}
,"format":{"hexencode":1,"encoding":1}
,"-any":{"text":1}
,"expression":{"field":1}
,"field":{"text":1,"hex-encoded":1,"set":1,"[table":1}
,"filemaker":{"pro":1,"returns":1}
,"pro":{"16.0":1}
,"16.0":{"function":1}
,"function":{"converts":1,"supported":1}
,"converts":{"text":1,"contents":1}
,"fields":{"variables":1}
,"variables":{"calculations":1}
,"calculations":{"utf-8":1}
,"utf-8":{"format":1}
,"encoding":{"container":1,"function":1}
,"container":{"data":1,"field":1}
,"converted":{"encoding":1}
,"supported":{"runtime":1}
,"runtime":{"solutions":1}
,"solutions":{"returns":1}
,"46696c654d616b6572":{"converts":1}
,"contents":{"container":1}
,"hex-encoded":{"text":1}
,"stores":{"text":1}
,"set":{"field":1}
,"[table":{":hexdata":1}
,":hexdata":{"hexencode":1}
,"table":{":container":1}
}
;Search.control.loadWordPairs(pairs);
