var pairs =
{
"save":{"records":1,"snapshot":1}
,"records":{"snapshot":1,"filemaker":1,"browsed":1,"current":1}
,"snapshot":{"link":1,"links":1}
,"link":{"aves":1,"fmpsl":1,"path":1,"file":1,"script":1,"user":1,"[current":1,"temporary":1,"attachment":1,"[\u0022$path":1,"automating":1}
,"aves":{"found":1}
,"found":{"set":1}
,"set":{"records":1,"snapshot":1,"variable":1}
,"filemaker":{"pro":1,"webdirect":1,"go":1}
,"pro":{"napshot":1,"advanced":1,"11.0":1}
,"napshot":{"link":1}
,"fmpsl":{"file":1}
,"file":{"output":1,"allows":1,"paths":1,"attachment":1,"attached":1,"script":1,"path":1,"via":1,"temporary":1,"locally":1,"dialog":1,"create":1,"save":1,"multiple":1,"stored":1,"created":1,"local":1,"matching":1}
,"output":{"file":1}
,"allows":{"enter":1}
,"enter":{"path":1}
,"path":{"snapshot":1,"line":1,"locates":1,"database":1,"assumed":1,"filemaker":1,"first":1}
,"line":{"filemaker":1}
,"advanced":{"se":1,"runs":1,"file":1}
,"se":{"first":1}
,"first":{"path":1,"assign":1}
,"locates":{"creating":1}
,"creating":{"file":1}
,"paths":{"ou":1,"filemaker":1,"server-side":1}
,"ou":{"elect":1}
,"elect":{"create":1}
,"create":{"email":1,"folders":1,"new":1}
,"email":{"file":1,"message":1,"application":1,"snapshot":1,"records":1}
,"attachment":{"display":1,"place":1,"set":1}
,"display":{"new":1}
,"new":{"email":1,"folders":1}
,"message":{"user\u2019s":1}
,"user\u2019s":{"default":1,"documents":1}
,"default":{"email":1,"download":1}
,"application":{"output":1}
,"attached":{"if":1}
,"if":{"filemaker":1,"store":1,"use":1,"don\u2019t":1}
,"runs":{"script":1}
,"script":{"absolute":1,"hosted":1,"step":1,"use":1}
,"absolute":{"path":1}
,"database":{"file":1}
,"hosted":{"path":1}
,"assumed":{"current":1}
,"current":{"user\u2019s":1,"record":1}
,"documents":{"folder":1}
,"folder":{"records":1,"creates":1}
,"browsed":{"saves":1,"create":1}
,"saves":{"entire":1,"current":1,"snapshot":1,"found":1}
,"entire":{"found":1}
,"record":{"saves":1,"create":1,"snapshot":1}
,"folders":{"pecifies":1,"hat":1,"ptions":1,"ption":1,"ee":1,"saves":1,"savin":1}
,"pecifies":{"create":1}
,"hat":{"output":1}
,"11.0":{"script":1}
,"step":{"operates":1,"snapshot":1,"script":1,"get":1,"supported":1}
,"operates":{"all":1}
,"all":{"modes":1}
,"modes":{"except":1}
,"except":{"find":1}
,"find":{"mode":1}
,"mode":{"send":1}
,"send":{"snapshot":1,"mail":1}
,"via":{"smtp":1}
,"smtp":{"use":1}
,"use":{"send":1,"script":1,"get":1,"variable":1}
,"mail":{"script":1}
,"place":{"save":1}
,"get":{"temporarypath":1}
,"temporarypath":{"function":1,"form":1,"&\u0022":1}
,"function":{"save":1}
,"temporary":{"location":1,"folder":1}
,"location":{"if":1,"script":1,"saves":1}
,"store":{"file":1}
,"locally":{"if":1}
,"form":{"file":1}
,"assign":{"variable":1}
,"variable":{"use":1,"output":1,"[$path":1}
,"dialog":{"box":1}
,"box":{"creating":1}
,"webdirect":{"output":1,"saves":1}
,"ptions":{"supported":1}
,"supported":{"filemaker":1,"mobile":1,"server-side":1}
,"links":{"web":1}
,"web":{"browser\u2019s":1}
,"browser\u2019s":{"default":1}
,"download":{"location":1}
,"mobile":{"browsers":1}
,"browsers":{"filemaker":1}
,"go":{"if":1,"name":1,"original":1}
,"don\u2019t":{"output":1}
,"name":{"file":1}
,"ption":{"supported":1}
,"server-side":{"scripts":1}
,"scripts":{"access":1,"open":1}
,"access":{"folders":1}
,"ee":{"paths":1}
,"open":{"snapshot":1}
,"multiple":{"ios":1}
,"ios":{"devices":1}
,"devices":{"if":1}
,"stored":{"each":1}
,"each":{"device":1}
,"device":{"snapshot":1}
,"created":{"filemaker":1}
,"original":{"filemaker":1}
,"local":{"copy":1}
,"copy":{"file":1}
,"matching":{"filenames":1}
,"filenames":{"relative":1}
,"relative":{"location":1}
,"user":{"save":1}
,"[current":{"record":1}
,"creates":{"email":1}
,"[$path":{"value":1}
,"value":{"get":1}
,"&\u0022":{"invoices.fmpsl":1}
,"invoices.fmpsl":{"\u0022]":1}
,"\u0022]":{"save":1}
,"[\u0022$path":{"create":1}
,"savin":{"sending":1}
,"sending":{"records":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
