var pairs =
{
"valuecount":{"returns":1,"text":1,"item":1,"valuelistitems":1}
,"returns":{"count":1,"valuecount":1,"last":1,"total":1}
,"count":{"total":1}
,"total":{"number":1}
,"number":{"values":1,"filemaker":1}
,"values":{"text":1,"ogether":1,"value":1,"literal":1,"recognize":1,"character":1,"carriage":1,"employee":1}
,"text":{"valuecount":1,"text":1,"-any":1,"expression":1,"field":1,"items":1}
,"-any":{"text":1}
,"expression":{"text":1}
,"field":{"number":1}
,"filemaker":{"pro":1}
,"pro":{"7.0":1}
,"7.0":{"values":1}
,"items":{"each":1}
,"each":{"end":1,"item":1}
,"end":{"arriage":1}
,"arriage":{"return":1}
,"return":{"place":1,"start":1,"list":1,"character":1,"13":1,"refer":1}
,"place":{"values":1}
,"ogether":{"create":1}
,"create":{"carriage-return-delimited":1}
,"carriage-return-delimited":{"list":1}
,"list":{"values":1,"insert":1,"employees":1}
,"value":{"empty":1,"if":1,"list":1}
,"empty":{"single":1,"ill":1,"valuecount":1}
,"single":{"character":1}
,"character":{"word":1,"each":1,"button":1,"name":1}
,"word":{"sentence":1}
,"sentence":{"paragraph":1}
,"paragraph":{"press":1,"separator":1}
,"press":{"enter":1}
,"enter":{"return":1}
,"start":{"creating":1}
,"creating":{"new":1}
,"new":{"value":1}
,"if":{"last":1}
,"last":{"value":1}
,"ill":{"recognized":1}
,"recognized":{"trailing":1}
,"trailing":{"carriage":1}
,"carriage":{"return":1}
,"literal":{"string":1,"carriage":1}
,"string":{"insert":1}
,"insert":{"literal":1}
,"item":{"list":1,"item":1,"returns":1}
,"button":{"calculation":1}
,"calculation":{"dialog":1}
,"dialog":{"box":1}
,"box":{"aluecount":1}
,"aluecount":{"functions":1}
,"functions":{"lists":1}
,"lists":{"values":1}
,"recognize":{"all":1}
,"all":{"characters":1}
,"characters":{"separators":1,"valuecount":1}
,"separators":{"values":1}
,"name":{"unicode":1}
,"unicode":{"code":1}
,"code":{"point":1}
,"point":{"line":1}
,"line":{"feed":1,"separator":1}
,"feed":{"10":1}
,"10":{"carriage":1}
,"13":{"line":1}
,"separator":{"8232":1,"8233":1,"characters":1}
,"8232":{"paragraph":1}
,"8233":{"referring":1}
,"referring":{"lists":1}
,"refer":{"separator":1}
,"valuelistitems":{"employees":1}
,"employees":{"employee":1,"database":1}
,"employee":{"names":1}
,"names":{"returns":1,"value":1}
,"database":{"file":1}
}
;Search.control.loadWordPairs(pairs);
