var pairs =
{
"creating":{"custom":1,"managing":1,"filemaker":1}
,"custom":{"app":1,"apps":1}
,"app":{"first":1,"plan":1,"romotes":1,"related":1}
,"first":{"step":1,"save":1,"last":1}
,"step":{"creating":1}
,"plan":{"content":1,"database":1,"use":1,"review":1,"separate":1}
,"content":{"structure":1}
,"structure":{"design":1}
,"design":{"create":1}
,"create":{"filemaker":1,"separate":1,"relationships":1,"form":1,"database":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"ile":1,"flexible":1,"file":1}
,"ile":{"define":1}
,"define":{"tables":1}
,"tables":{"nd":1,"relational":1,"ensure":1,"tables":1,"group":1,"single":1,"if":1,"multiple":1,"note":1,"easily":1,"file":1,"external":1,"data":1,"fields":1}
,"nd":{"fields":1,"estrict":1}
,"fields":{"well-designed":1,"easy":1,"first":1,"time":1,"capture":1,"each":1}
,"well-designed":{"custom":1}
,"romotes":{"consistent":1}
,"consistent":{"data":1}
,"data":{"entry":1,"atabase":1,"it\u2019s":1,"desktop":1,"store":1,"each":1,"common":1,"category":1,"complex":1,"custom":1,"single":1,"stored":1,"include":1,"multiple":1,"tables":1,"nd":1}
,"entry":{"retrieval":1,"easier":1}
,"retrieval":{"reduces":1}
,"reduces":{"existence":1}
,"existence":{"duplicate":1}
,"duplicate":{"data":1}
,"atabase":{"tables":1}
,"relational":{"database":1}
,"database":{"tables":1,"paper":1,"problem":1,"sure":1,"typically":1,"store":1,"intended":1,"records":1,"terminology":1,"etermine":1,"users":1,"people":1,"use":1,"protecting":1,"se":1}
,"ensure":{"correct":1}
,"correct":{"data":1}
,"it\u2019s":{"idea":1}
,"idea":{"plan":1}
,"paper":{"first":1,"plan":1}
,"save":{"time":1}
,"time":{"effort":1,"data":1}
,"effort":{"determine":1}
,"determine":{"purpose":1}
,"purpose":{"database":1,"use":1}
,"problem":{"want":1}
,"want":{"solve":1}
,"solve":{"keep":1}
,"keep":{"list":1}
,"list":{"customers":1,"forms":1}
,"customers":{"manage":1,"order":1,"products":1}
,"manage":{"inventory":1}
,"inventory":{"grade":1}
,"grade":{"students":1}
,"students":{"data":1,"classes":1}
,"desktop":{"computer":1}
,"computer":{"ipad":1}
,"ipad":{"web":1,"iphone":1}
,"web":{"browser":1}
,"browser":{"if":1,"creating":1}
,"if":{"people":1,"track":1,"data":1,"share":1,"plan":1,"you\u2019re":1}
,"people":{"use":1,"test":1}
,"use":{"database":1,"table":1,"single":1,"multiple":1,"custom":1,"show":1,"data":1,"people":1,"plan":1}
,"sure":{"talk":1}
,"talk":{"data":1}
,"store":{"database":1,"types":1,"names":1,"transaction":1,"tax":1,"data":1}
,"typically":{"falls":1}
,"falls":{"broad":1}
,"broad":{"categories":1}
,"categories":{"accurately":1,"critical":1,"ustomers":1,"students":1,"referred":1,"related":1,"interact":1}
,"accurately":{"identifying":1}
,"identifying":{"categories":1}
,"critical":{"designing":1}
,"designing":{"efficient":1,"database":1}
,"efficient":{"database":1}
,"types":{"amounts":1}
,"amounts":{"data":1}
,"each":{"category":1,"transaction":1,"task":1,"table":1}
,"category":{"database":1,"show":1,"data":1,"ypically":1,"names":1}
,"intended":{"track":1}
,"track":{"sales":1,"ustomers":1,"data":1}
,"sales":{"categories":1}
,"ustomers":{"products":1,"draw":1}
,"products":{"invoices":1}
,"invoices":{"database":1,"track":1,"multiple":1}
,"records":{"student":1,"create":1}
,"student":{"grades":1}
,"grades":{"categories":1}
,"classes":{"assignments":1}
,"assignments":{"database":1}
,"terminology":{"categories":1}
,"referred":{"tables":1}
,"group":{"data":1}
,"common":{"element":1}
,"element":{"purpose":1}
,"table":{"store":1,"single":1,"if":1,"list":1,"11":1}
,"names":{"addresses":1}
,"addresses":{"while":1,"multiple":1,"city":1}
,"while":{"use":1}
,"transaction":{"details":1,"easier":1}
,"details":{"date":1}
,"date":{"sale":1,"item":1}
,"sale":{"item":1}
,"item":{"number":1}
,"number":{"unit":1,"quantity":1}
,"unit":{"price":1}
,"price":{"categories":1,"each":1}
,"related":{"by":1,"tables":1}
,"by":{"writing":1}
,"writing":{"simple":1}
,"simple":{"sentences":1}
,"sentences":{"categories":1}
,"interact":{"customers":1}
,"order":{"products":1}
,"draw":{"each":1}
,"show":{"connection":1,"paper":1}
,"connection":{"ach":1}
,"ach":{"pair":1}
,"pair":{"uggests":1}
,"uggests":{"relationship":1}
,"relationship":{"data":1}
,"ypically":{"databases":1}
,"databases":{"organized":1,"decide":1}
,"organized":{"single":1}
,"single":{"table":1,"file":1}
,"file":{"use":1,"if":1,"multiple":1,"tables":1,"level":1,"sharing":1,"12":1}
,"multiple":{"tables":1,"files":1,"fields":1}
,"complex":{"customers":1,"custom":1}
,"files":{"use":1,"if":1,"packaging":1,"relationships":1,"etermine":1,"planning":1,"network":1,"tables":1}
,"share":{"data":1,"database":1}
,"apps":{"store":1,"benefit":1}
,"tax":{"rates":1}
,"rates":{"shipping":1}
,"shipping":{"separate":1}
,"separate":{"file":1,"fields":1,"layout":1,"layouts":1}
,"note":{"filemaker":1}
,"flexible":{"decision":1}
,"decision":{"store":1}
,"packaging":{"convenience":1}
,"convenience":{"data":1}
,"stored":{"tables":1,"file":1}
,"easily":{"shared":1}
,"shared":{"tables":1}
,"external":{"files":1}
,"relationships":{"elements":1,"share":1}
,"elements":{"scripts":1}
,"scripts":{"access":1}
,"access":{"privileges":1,"file":1,"database":1}
,"privileges":{"stored":1}
,"level":{"complex":1}
,"benefit":{"multiple":1}
,"etermine":{"database":1,"share":1}
,"include":{"fields":1}
,"easy":{"search":1}
,"search":{"sort":1}
,"sort":{"records":1}
,"last":{"name":1}
,"name":{"titles":1}
,"titles":{"mr":1}
,"mr":{"dr":1}
,"dr":{"items":1}
,"items":{"addresses":1}
,"city":{"state":1}
,"state":{"province":1}
,"province":{"country":1}
,"country":{"postal":1}
,"postal":{"code":1}
,"code":{"separating":1}
,"separating":{"data":1}
,"easier":{"generate":1,"compile":1}
,"generate":{"future":1,"each":1}
,"future":{"reports":1}
,"reports":{"separate":1,"end":1,"10":1,"generate":1}
,"capture":{"transaction":1}
,"quantity":{"unit":1}
,"compile":{"summary":1}
,"summary":{"subsummary":1}
,"subsummary":{"reports":1}
,"end":{"week":1}
,"week":{"month":1}
,"month":{"year":1}
,"year":{"create":1}
,"planning":{"relational":1}
,"users":{"access":1}
,"sharing":{"files":1}
,"network":{"if":1}
,"you\u2019re":{"designing":1}
,"review":{"ho":1}
,"ho":{"use":1}
,"estrict":{"access":1}
,"protecting":{"databases":1}
,"decide":{"layouts":1}
,"layouts":{"plan":1,"printing":1,"reports":1}
,"layout":{"each":1}
,"task":{"create":1}
,"printing":{"labels":1}
,"labels":{"envelopes":1}
,"envelopes":{"ios":1}
,"ios":{"device":1}
,"device":{"ipad":1}
,"iphone":{"web":1}
,"managing":{"layouts":1}
,"10":{"create":1}
,"form":{"lists":1}
,"lists":{"all":1}
,"all":{"files":1}
,"forms":{"reports":1}
,"11":{"create":1}
,"se":{"creating":1}
,"12":{"you\u2019ve":1}
,"you\u2019ve":{"designed":1}
,"designed":{"database":1}
,"test":{"fix":1}
,"fix":{"problems":1}
,"problems":{"general":1}
,"general":{"use":1}
}
;Search.control.loadWordPairs(pairs);
