var pairs =
{
"get":{"sorts":1,"sortstate":1,"sort":1,"current":1}
,"sorts":{"tate":1}
,"tate":{"returns":1}
,"returns":{"value":1,"if":1,"records":1}
,"value":{"representing":1}
,"representing":{"current":1}
,"current":{"sort":1,"calculation":1,"window":1}
,"sort":{"state":1,"order":1,"found":1}
,"state":{"get":1,"records":1,"include":1}
,"sortstate":{"none":1,"get":1}
,"none":{"number":1}
,"number":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"returns":1}
,"if":{"records":1,"context":1}
,"records":{"active":1,"imported":1,"sorted":1,"sort":1}
,"active":{"table":1}
,"table":{"sorted":1,"partially":1}
,"sorted":{"if":1,"semi-sorted":1,"set":1,"get":1}
,"partially":{"sorted":1}
,"semi-sorted":{"each":1,"state":1}
,"each":{"window":1}
,"window":{"own":1,"returns":1}
,"own":{"sort":1}
,"imported":{"file":1,"records":1}
,"file":{"found":1}
,"found":{"sorted":1,"set":1}
,"set":{"records":1,"exist":1,"importing":1}
,"exist":{"semi-sorted":1}
,"include":{"imported":1}
,"order":{"sort":1}
,"importing":{"if":1}
,"context":{"current":1,"evaluated":1}
,"calculation":{"function":1}
,"function":{"evaluated":1}
,"evaluated":{"based":1}
,"based":{"context":1}
}
;Search.control.loadWordPairs(pairs);
