var pairs =
{
"layout":{"objects":1,"custom":1,"mode":1,"object":1,"text":1,"help":1,"accessibility":1,"imagine":1,"succinct":1}
,"objects":{"accessible":1,"database":1,"visual":1,"se":1,"screen":1,"delete":1}
,"accessible":{"screen":1,"assistive":1}
,"screen":{"readers":1,"reader":1}
,"readers":{"add":1,"object":1,"can\u2019t":1,"access":1,"speak":1}
,"add":{"accessibility":1}
,"accessibility":{"labels":1,"label":1,"inspector":1}
,"labels":{"layout":1,"ensure":1}
,"database":{"accessible":1}
,"assistive":{"applications":1}
,"applications":{"screen":1}
,"object":{"connected":1,"accessibility":1,"text":1,"layout":1,"select":1,"selected":1,"title":1,"calculation":1,"label":1,"telephone":1,"high-level":1}
,"connected":{"object":1}
,"label":{"if":1,"accessibility":1,"select":1,"object":1,"text":1,"want":1,"label":1,"screen":1,"decorative":1}
,"if":{"object":1,"text":1,"image":1}
,"text":{"field":1,"object":1,"result":1,"spoken":1,"accessibility":1,"want":1,"calculation":1,"title":1,"box":1,"exists":1,"boxes":1,"layout":1,"appears":1,"screen":1,"include":1,"images":1,"add":1}
,"field":{"stores":1}
,"stores":{"customer":1}
,"customer":{"number":1}
,"number":{"data":1,"help":1}
,"data":{"specific":1}
,"specific":{"format":1}
,"format":{"enter":1}
,"enter":{"title":1}
,"title":{"customer":1,"type":1,"text":1,"help":1}
,"help":{"unique":1,"type":1,"text":1}
,"unique":{"five-digit":1}
,"five-digit":{"id":1}
,"id":{"tracking":1}
,"tracking":{"customers":1}
,"customers":{"poken":1}
,"poken":{"text":1}
,"custom":{"text":1}
,"result":{"calculation":1}
,"calculation":{"layout":1,"button":1,"provide":1,"dialog":1,"instruction":1}
,"mode":{"choose":1}
,"choose":{"view":1}
,"view":{"menu":1}
,"menu":{"inspectors":1}
,"inspectors":{"ccessibility":1,"accessibility":1}
,"ccessibility":{"inspector":1}
,"inspector":{"select":1,"label":1,"text":1}
,"select":{"object":1,"select":1,"second":1}
,"second":{"appears":1}
,"appears":{"label":1,"layout":1}
,"spoken":{"first":1,"object":1,"text":1}
,"first":{"object":1}
,"selected":{"active":1}
,"active":{"custom":1}
,"type":{"text":1,"instruction":1}
,"want":{"spoken":1,"delete":1}
,"button":{"calculation":1}
,"provide":{"spoken":1,"additional":1,"function":1}
,"dialog":{"box":1}
,"box":{"if":1,"screen":1,"speaks":1}
,"reader":{"speak":1,"pauses":1}
,"speak":{"text":1,"placeholder":1}
,"speaks":{"text":1}
,"instruction":{"object":1,"layout":1}
,"delete":{"if":1,"developing":1,"accessibility":1}
,"exists":{"title":1}
,"boxes":{"delete":1}
,"developing":{"text":1}
,"ensure":{"content":1}
,"content":{"write":1}
,"write":{"alternate":1,"descriptions":1}
,"alternate":{"equivalent":1}
,"equivalent":{"text":1}
,"imagine":{"describing":1}
,"describing":{"layout":1,"purpose":1}
,"telephone":{"user":1}
,"user":{"complete":1}
,"complete":{"form":1}
,"form":{"avoid":1}
,"avoid":{"redundancy":1}
,"redundancy":{"don\u2019t":1}
,"don\u2019t":{"simply":1,"label":1}
,"simply":{"repeat":1}
,"repeat":{"text":1}
,"succinct":{"provide":1}
,"additional":{"users":1}
,"users":{"by":1}
,"by":{"describing":1}
,"purpose":{"object":1}
,"high-level":{"functionality":1}
,"functionality":{"write":1}
,"descriptions":{"context":1}
,"context":{"include":1}
,"include":{"punctuation":1,"text":1}
,"punctuation":{"label":1}
,"pauses":{"times":1}
,"times":{"if":1}
,"image":{"layout":1}
,"can\u2019t":{"read":1}
,"read":{"text":1}
,"images":{"don\u2019t":1}
,"decorative":{"objects":1}
,"visual":{"enhancements":1}
,"enhancements":{"decorations":1}
,"decorations":{"embellishments":1}
,"embellishments":{"provide":1}
,"function":{"aesthetics":1}
,"aesthetics":{"creen":1}
,"creen":{"readers":1}
,"access":{"hidden":1}
,"hidden":{"objects":1}
,"se":{"hiding":1}
,"hiding":{"layout":1}
,"placeholder":{"text":1}
}
;Search.control.loadWordPairs(pairs);
