var pairs =
{
"deciding":{"place":1}
,"place":{"related":1,"fields":1}
,"related":{"fields":1,"tables":1,"records":1,"record":1,"field":1,"data":1,"teacher":1,"values":1}
,"fields":{"place":1,"related":1,"layout":1,"portal":1,"invoice":1,"each":1,"select":1,"placed":1,"portals":1,"while":1,"referenced":1}
,"tables":{"layouts":1,"relationships":1,"teachers":1,"school":1,"placed":1}
,"layouts":{"portals":1,"place":1}
,"portals":{"display":1,"place":1,"value":1}
,"display":{"related":1,"data":1,"record":1,"enrolled":1,"each":1,"value":1,"change":1}
,"records":{"layouts":1,"match":1,"order":1,"filemaker":1}
,"layout":{"display":1,"invoices":1,"portal":1,"displays":1,"table":1,"includes":1}
,"data":{"first":1,"all":1,"clients":1,"client":1,"each":1,"display":1,"field":1}
,"first":{"related":1}
,"record":{"related":1,"match":1,"displayed":1,"clients":1,"create":1,"portal\u2019s":1,"layout\u2019s":1,"placed":1}
,"match":{"criteria":1,"field":1,"client\u0027s":1}
,"criteria":{"relationship":1}
,"relationship":{"first":1,"specifies":1,"invoice":1,"recent":1}
,"displayed":{"determined":1,"value":1}
,"determined":{"by":1}
,"by":{"relationship":1,"defining":1,"modifying":1}
,"specifies":{"sort":1}
,"sort":{"order":1}
,"order":{"portals":1,"date":1,"history":1,"multiple":1,"order":1,"id":1}
,"portal":{"layout":1,"place":1,"hold":1,"displays":1,"tables":1,"name":1,"first":1,"redundant":1,"addition":1,"filemaker":1,"formatted":1,"active":1}
,"all":{"related":1}
,"invoice":{"layout":1,"displays":1,"display":1,"displaying":1}
,"invoices":{"database":1}
,"database":{"place":1,"client\u0027s":1,"each":1,"match":1,"tables":1,"layout":1}
,"displays":{"data":1,"recent":1,"related":1,"filemaker":1,"enrolled":1}
,"clients":{"database":1}
,"client\u0027s":{"identification":1,"client":1}
,"identification":{"number":1}
,"number":{"contact":1}
,"contact":{"match":1}
,"field":{"client":1,"invoice":1,"order":1,"define":1,"placed":1,"portal":1,"displays":1,"if":1,"path":1,"students":1,"portal\u2019s":1,"display":1,"advisors":1,"repeat":1,"layout\u2019s":1,"field":1}
,"client":{"id":1,"place":1,"placed":1}
,"id":{"record":1,"each":1,"if":1,"by":1,"product":1,"cases":1}
,"each":{"client":1,"related":1,"item":1,"row":1,"class":1,"student":1,"student\u2019s":1}
,"recent":{"value":1,"date":1}
,"value":{"order":1,"each":1,"lists":1,"list":1}
,"date":{"field":1,"displays":1}
,"history":{"database":1,"match":1}
,"if":{"client":1,"path":1,"layout":1}
,"placed":{"order":1,"layout":1,"field":1,"portal":1}
,"multiple":{"records":1}
,"defining":{"sort":1}
,"define":{"relationship":1}
,"item":{"product":1,"database":1}
,"product":{"id":1,"name":1,"invoice":1}
,"name":{"unit":1,"field":1,"teachers":1,"classes":1,"each":1}
,"unit":{"price":1}
,"price":{"match":1}
,"cases":{"product":1}
,"displaying":{"related":1}
,"create":{"portal":1}
,"hold":{"related":1}
,"row":{"portal":1}
,"select":{"line":1}
,"line":{"item":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"two":1,"determines":1,"method":1,"valuates":1}
,"two":{"starting":1,"tables":1}
,"starting":{"points":1,"point":1}
,"points":{"evaluate":1,"fields":1}
,"evaluate":{"related":1}
,"portal\u2019s":{"table":1,"record":1}
,"table":{"record":1,"starting":1,"field\u2019s":1,"table":1,"placed":1,"includes":1,"students":1,"occurrence":1,"assigns":1,"classes":1,"describes":1,"path":1,"classes-enrollment-students":1,"common":1,"classes-enrollment-students-advisors":1,"classes-teachers":1,"uncommon":1}
,"layout\u2019s":{"table":1,"record":1}
,"point":{"related":1,"use":1,"record":1,"relationships":1,"comment":1,"references":1,"determines":1,"by":1}
,"determines":{"starting":1,"values":1,"correct":1}
,"use":{"based":1}
,"based":{"path":1}
,"path":{"relationships":1,"layout\u2019s":1,"include":1}
,"relationships":{"two":1,"graph":1,"layout\u2019s":1,"tables":1,"changing":1}
,"graph":{"layout\u2019s":1,"school":1,"include":1}
,"field\u2019s":{"table":1}
,"includes":{"portal\u2019s":1,"class":1}
,"school":{"enrollment":1}
,"enrollment":{"database":1,"table":1}
,"teachers":{"classes":1,"table":1}
,"classes":{"students":1,"portal\u2019s":1,"table":1,"layout\u2019s":1}
,"students":{"enrollment":1,"each":1,"class":1,"portal":1,"table":1}
,"class":{"advisors":1,"layout\u2019s":1,"each":1,"name":1}
,"advisors":{"table":1}
,"occurrence":{"teachers":1,"field":1}
,"assigns":{"faculty":1}
,"faculty":{"advisor":1}
,"advisor":{"each":1}
,"student":{"relationships":1,"each":1,"class":1}
,"enrolled":{"students":1,"student":1}
,"describes":{"filemaker":1}
,"include":{"portal\u2019s":1,"related":1,"tables":1}
,"comment":{"name":1}
,"classes-enrollment-students":{"portal\u2019s":1}
,"common":{"occurrence":1}
,"classes-enrollment-students-advisors":{"portal\u2019s":1}
,"student\u2019s":{"advisor":1}
,"classes-teachers":{"layout\u2019s":1}
,"repeat":{"teacher":1,"class":1}
,"teacher":{"class":1,"value":1}
,"uncommon":{"occurrence":1}
,"redundant":{"if":1}
,"addition":{"fields":1}
,"method":{"determine":1}
,"determine":{"starting":1}
,"references":{"fields":1,"related":1}
,"lists":{"value":1}
,"list":{"defined":1,"starting":1,"calculations":1}
,"defined":{"include":1}
,"values":{"field":1,"displayed":1}
,"formatted":{"display":1}
,"calculations":{"scripted":1,"refer":1}
,"scripted":{"calculations":1}
,"refer":{"fields":1}
,"while":{"portal":1}
,"active":{"usually":1}
,"usually":{"filemaker":1}
,"correct":{"related":1}
,"change":{"starting":1}
,"modifying":{"relationships":1}
,"changing":{"related":1}
,"referenced":{"portal":1}
,"valuates":{"references":1}
}
;Search.control.loadWordPairs(pairs);
