var pairs =
{
"status":{"toolbar":1}
,"toolbar":{"status":1,"quick":1,"choose":1,"ake":1,"add":1,"macos":1,"remove":1,"dialog":1,"restore":1,"reset":1,"display":1,"icons":1,"insert":1,"customize":1,"each":1,"application-wide":1}
,"quick":{"access":1}
,"access":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"menu":1}
,"menu":{"commands":1,"status":1,"customize":1,"toolbar":1}
,"commands":{"all":1,"tab":1,"list":1}
,"all":{"modes":1}
,"modes":{"includes":1}
,"includes":{"navigation":1,"layout":1}
,"navigation":{"controls":1}
,"controls":{"customizable":1}
,"customizable":{"buttons":1,"standard":1}
,"buttons":{"layout":1,"drag":1,"windows":1,"macos":1,"adjusts":1}
,"layout":{"bar":1,"mode":1,"tools":1}
,"bar":{"layouts":1,"customized":1}
,"layouts":{"layout":1}
,"mode":{"includes":1,"status":1}
,"tools":{"move":1}
,"move":{"pointer":1}
,"pointer":{"button":1}
,"button":{"description":1,"windows":1,"dialog":1,"drag":1}
,"description":{"choose":1}
,"choose":{"view":1,"option":1}
,"view":{"menu":1}
,"customize":{"status":1}
,"ake":{"status":1}
,"add":{"button":1}
,"windows":{"commands":1,"toolbars":1}
,"tab":{"select":1}
,"select":{"customizable":1,"status":1,"use":1}
,"standard":{"categories":1}
,"categories":{"list":1}
,"list":{"drag":1,"status":1}
,"drag":{"utton":1,"button":1,"status":1,"desired":1,"default":1,"space":1,"flexible":1}
,"utton":{"commands":1}
,"macos":{"drag":1,"choose":1,"select":1}
,"dialog":{"box":1}
,"box":{"status":1,"rearrange":1}
,"remove":{"button":1}
,"rearrange":{"buttons":1}
,"desired":{"locations":1,"location":1}
,"locations":{"status":1}
,"restore":{"default":1}
,"default":{"set":1}
,"set":{"buttons":1,"dialog":1}
,"toolbars":{"tab":1}
,"reset":{"macos":1}
,"display":{"icons":1}
,"icons":{"text":1,"macos":1}
,"text":{"macos":1}
,"option":{"show":1}
,"show":{"pop-up":1,"hide":1}
,"pop-up":{"menu":1}
,"use":{"size":1}
,"size":{"insert":1,"macos":1}
,"insert":{"fixed":1,"flexible":1}
,"fixed":{"space":1}
,"space":{"buttons":1,"icon":1}
,"icon":{"desired":1}
,"location":{"status":1}
,"flexible":{"space":1}
,"adjusts":{"depending":1}
,"depending":{"window":1}
,"window":{"size":1}
,"each":{"mode":1}
,"application-wide":{"buttons":1}
,"customized":{"show":1}
,"hide":{"status":1}
}
;Search.control.loadWordPairs(pairs);
