var pairs =
{
"setting":{"up":1,"script":1}
,"up":{"script":1}
,"script":{"triggers":1,"trigger":1,"runs":1,"automatically":1,"event":1,"field":1,"run":1,"step":1,"defined":1,"by":1}
,"triggers":{"set":1,"run":1,"activated":1,"layouts":1,"objects":1,"assigned":1,"script":1,"trigger":1,"perform":1,"order":1,"use":1,"if":1,"allow":1,"macos":1,"timing":1}
,"set":{"up":1,"20":1}
,"trigger":{"script":1,"run":1,"activate":1,"cript":1,"processing":1,"returns":1}
,"runs":{"event":1,"user\u2019s":1}
,"event":{"occurs":1,"processed":1,"script":1,"onobjectenter":1,"canceled":1}
,"occurs":{"use":1}
,"use":{"script":1,"onobjectenter":1,"existing":1}
,"run":{"script":1,"field":1,"by":1,"full":1,"onlastwindowclose":1}
,"automatically":{"enters":1}
,"enters":{"data":1,"specific":1,"modifies":1}
,"data":{"fields":1,"api":1,"filemaker":1}
,"fields":{"based":1}
,"based":{"entered":1}
,"entered":{"field":1,"by":1}
,"field":{"script":1,"entered":1,"object":1,"event":1}
,"processed":{"by":1}
,"by":{"database":1,"user":1,"scripts":1,"go":1,"event":1,"triggering":1,"script":1,"direct":1}
,"database":{"engine":1}
,"engine":{"script":1,"use":1}
,"onobjectenter":{"script":1,"onobjectkeystroke":1}
,"object":{"entering":1,"script":1,"objects":1,"onobjectenter":1}
,"entering":{"field":1}
,"activated":{"by":1}
,"user":{"actions":1,"clicking":1,"enters":1,"interaction":1,"interface":1}
,"actions":{"by":1}
,"scripts":{"use":1,"run":1}
,"activate":{"script":1,"user":1}
,"clicking":{"by":1}
,"go":{"object":1}
,"step":{"set":1,"ocus":1}
,"specific":{"layout":1}
,"layout":{"setting":1,"objects":1,"mode":1,"onrecordload":1}
,"layouts":{"user":1,"script":1}
,"modifies":{"exits":1}
,"exits":{"object":1}
,"objects":{"layout":1,"file":1,"layouts":1}
,"file":{"closed":1,"etting":1,"options":1,"close":1}
,"closed":{"playback":1}
,"playback":{"state":1}
,"state":{"media":1}
,"media":{"file":1}
,"etting":{"file":1}
,"options":{"layout":1,"onfirstwindowopen":1}
,"assigned":{"layout":1}
,"mode":{"choose":1}
,"choose":{"view":1}
,"view":{"menu":1}
,"menu":{"show":1}
,"show":{"script":1}
,"cript":{"trigger":1}
,"processing":{"processing":1,"object":1}
,"onobjectkeystroke":{"onobjectmodify":1,"onlayoutkeystroke":1}
,"onobjectmodify":{"onobjectvalidate":1,"10":1}
,"onobjectvalidate":{"onobjectsave":1,"11":1}
,"onobjectsave":{"onobjectexit":1,"12":1}
,"onobjectexit":{"onpanelswitch":1,"13":1}
,"onpanelswitch":{"onobjectavplayerchange":1,"onobjectmodify":1}
,"onobjectavplayerchange":{"layout":1,"onfileavplayerchange":1}
,"onrecordload":{"onrecordcommit":1,"onlayoutsizechange":1}
,"onrecordcommit":{"onrecordrevert":1}
,"onrecordrevert":{"onlayoutkeystroke":1,"14":1}
,"onlayoutkeystroke":{"onlayoutenter":1,"ongesturetap":1}
,"onlayoutenter":{"onlayoutexit":1,"onmodeenter":1}
,"onlayoutexit":{"onlayoutsizechange":1,"16":1}
,"onlayoutsizechange":{"onmodeenter":1,"onviewchange":1}
,"onmodeenter":{"onmodeexit":1,"onrecordload":1}
,"onmodeexit":{"onviewchange":1,"15":1}
,"onviewchange":{"ongesturetap":1,"script":1}
,"ongesturetap":{"onexternalcommandreceived":1,"onobjectavplayerchange":1}
,"onexternalcommandreceived":{"file":1,"onpanelswitch":1}
,"onfirstwindowopen":{"onlastwindowclose":1,"onwindowopen":1}
,"onlastwindowclose":{"onwindowopen":1,"scripts":1,"script":1}
,"onwindowopen":{"onwindowclose":1,"onlayoutenter":1}
,"onwindowclose":{"onfileavplayerchange":1,"17":1}
,"onfileavplayerchange":{"multiple":1,"onexternalcommandreceived":1}
,"multiple":{"script":1}
,"perform":{"relative":1}
,"relative":{"order":1}
,"order":{"onfirstwindowopen":1,"controlled":1}
,"controlled":{"by":1}
,"triggering":{"event":1}
,"10":{"onobjectvalidate":1}
,"11":{"onobjectsave":1}
,"12":{"onobjectexit":1}
,"13":{"onrecordcommit":1}
,"14":{"onmodeexit":1}
,"15":{"onlayoutexit":1}
,"16":{"onwindowclose":1}
,"17":{"onlastwindowclose":1}
,"existing":{"privileges":1}
,"privileges":{"script":1,"ustom":1}
,"defined":{"run":1}
,"full":{"privileges":1}
,"user\u2019s":{"privileges":1}
,"ustom":{"web":1}
,"web":{"publishing":1}
,"publishing":{"filemaker":1}
,"filemaker":{"data":1,"user":1}
,"api":{"script":1,"don\u2019t":1}
,"direct":{"user":1}
,"interaction":{"custom":1}
,"custom":{"web":1}
,"don\u2019t":{"access":1}
,"access":{"data":1}
,"interface":{"users":1}
,"users":{"activate":1}
,"if":{"script":1}
,"ocus":{"move":1}
,"move":{"ield":1}
,"ield":{"script":1}
,"allow":{"triggering":1}
,"canceled":{"if":1,"error":1}
,"returns":{"false":1}
,"false":{"value":1}
,"value":{"command":1,"file":1}
,"command":{"event":1,"key":1}
,"error":{"code":1}
,"code":{"set":1}
,"20":{"get":1}
,"get":{"lasterror":1}
,"lasterror":{"function":1}
,"function":{"if":1}
,"close":{"windows":1}
,"windows":{"alt":1}
,"alt":{"ctrl":1}
,"ctrl":{"key":1}
,"key":{"combinations":1}
,"combinations":{"activate":1}
,"macos":{"command":1}
,"timing":{"script":1}
}
;Search.control.loadWordPairs(pairs);
