var pairs =
{
"committing":{"data":1}
,"data":{"records":1,"called":1,"data":1,"committed":1,"usually":1,"solution":1,"incorrectly":1,"record":1,"related":1,"replace":1}
,"records":{"filemaker":1,"prompt":1,"displayed":1,"window":1,"portal":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"aves":1}
,"aves":{"data":1}
,"called":{"committing":1}
,"committed":{"all":1,"press":1,"se":1,"commit":1}
,"all":{"fields":1}
,"fields":{"record":1}
,"record":{"press":1,"switch":1,"restore":1,"committed":1,"etting":1,"displaying":1,"if":1,"replace":1}
,"press":{"ente":1,"enter":1}
,"ente":{"notes":1}
,"notes":{"windows":1}
,"windows":{"press":1}
,"enter":{"numeric":1,"computers":1,"return":1,"if":1,"commit":1,"data":1}
,"numeric":{"keypad":1}
,"keypad":{"ctrl":1,"macos":1,"switch":1}
,"ctrl":{"enter":1}
,"computers":{"numeric":1}
,"macos":{"press":1}
,"return":{"fn-return":1}
,"fn-return":{"computers":1}
,"switch":{"mode":1,"layout":1}
,"mode":{"select":1}
,"select":{"record":1}
,"layout":{"data":1,"change":1}
,"usually":{"committed":1}
,"if":{"pressing":1,"uncommitted":1}
,"pressing":{"enter":1}
,"commit":{"data":1,"record":1,"active":1}
,"solution":{"developer":1}
,"developer":{"enter":1}
,"incorrectly":{"record":1}
,"restore":{"original":1}
,"original":{"data":1}
,"se":{"restoring":1}
,"restoring":{"data":1}
,"prompt":{"users":1}
,"users":{"save":1}
,"save":{"commit":1}
,"etting":{"automatic":1}
,"automatic":{"record-saving":1}
,"record-saving":{"option":1}
,"option":{"layout":1}
,"change":{"related":1}
,"related":{"data":1,"records":1}
,"displayed":{"portal":1}
,"portal":{"committed":1}
,"displaying":{"related":1}
,"replace":{"field":1,"ookup":1,"elookup":1}
,"field":{"contents":1}
,"contents":{"relookup":1,"commands":1}
,"relookup":{"field":1}
,"commands":{"script":1}
,"script":{"steps":1}
,"steps":{"commit":1}
,"active":{"record":1}
,"uncommitted":{"records":1,"ommit":1}
,"window":{"by":1}
,"by":{"replace":1}
,"ookup":{"operation":1}
,"operation":{"remain":1}
,"remain":{"uncommitted":1}
,"ommit":{"active":1}
,"elookup":{"related":1}
}
;Search.control.loadWordPairs(pairs);
