var pairs =
{
"pening":{"managing":1,"hared":1}
,"managing":{"files":1}
,"files":{"ou":1,"network":1,"client":1,"created":1,"tab-delimited":1,"filemaker":1,"host":1,"recent":1,"protected":1,"system":1,"fmp12":1}
,"ou":{"open":1}
,"open":{"local":1,"navigate":1,"open":1,"favorite":1,"file":1,"ing":1,"multiple":1,"hidden":1,"files":1}
,"local":{"filemaker":1,"file":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1,"12":1,"11":1}
,"advanced":{"iles":1,"file":1,"close":1,"version":1,"filemaker":1}
,"iles":{"located":1}
,"located":{"computer":1}
,"computer":{"op":1,"alert":1}
,"op":{"en":1}
,"en":{"shared":1}
,"shared":{"files":1}
,"network":{"pening":1}
,"hared":{"files":1}
,"client":{"co":1}
,"co":{"nvert":1}
,"nvert":{"compatible":1}
,"compatible":{"files":1}
,"created":{"applications":1,"earlier":1}
,"applications":{"excel":1}
,"excel":{"files":1}
,"tab-delimited":{"text":1}
,"text":{"files":1}
,"12":{"format":1,"open":1}
,"format":{"fmp12":1,"convert":1}
,"fmp12":{"se":1,"format":1}
,"se":{"onverting":1}
,"onverting":{"data":1}
,"data":{"file":1,"file\u2019s":1}
,"file":{"new":1,"open":1,"choose":1,"menu":1,"select":1,"hat":1,"recent":1,"isn\u2019t":1,"perform":1,"saved":1,"default":1,"displaying":1,"etting":1,"options":1,"remain":1,"if":1,"window":1,"attempted":1,"close":1,"files":1}
,"new":{"filemaker":1,"window":1}
,"choose":{"file":1,"filename":1,"remove":1,"window":1,"display":1}
,"menu":{"open":1,"apps":1,"ee":1,"recent":1,"display":1,"set":1,"new":1}
,"navigate":{"file":1}
,"select":{"filename":1}
,"filename":{"open":1,"choose":1,"menu":1}
,"favorite":{"file":1,"files":1}
,"apps":{"show":1,"apps":1,"window":1,"choose":1}
,"show":{"apps":1,"recent":1}
,"window":{"double-click":1,"recent":1,"right-click":1,"menu":1,"allows":1,"file":1,"displaying":1}
,"double-click":{"filename":1}
,"ee":{"favorite":1}
,"host":{"open":1}
,"hat":{"ecently":1}
,"ecently":{"choose":1}
,"recent":{"show":1,"recent":1,"window":1,"choose":1,"files":1,"menu":1}
,"display":{"recent":1,"sort":1}
,"set":{"ting":1,"computer":1}
,"ting":{"general":1}
,"general":{"preferences":1}
,"preferences":{"remove":1}
,"remove":{"file":1}
,"right-click":{"filename":1}
,"isn\u2019t":{"deleted":1}
,"deleted":{"hard":1}
,"hard":{"disk":1}
,"disk":{"removed":1}
,"removed":{"lists":1}
,"lists":{"nter":1}
,"nter":{"account":1}
,"account":{"name":1}
,"name":{"password":1}
,"password":{"if":1,"open":1,"password":1,"by":1}
,"if":{"open":1,"file":1,"close":1,"window":1}
,"ing":{"files":1}
,"protected":{"password":1}
,"multiple":{"windows":1}
,"windows":{"file":1,"simultaneously":1,"open":1,"option":1,"all":1}
,"allows":{"view":1}
,"view":{"layout":1,"layouts":1}
,"layout":{"separate":1,"file":1}
,"separate":{"windows":1}
,"simultaneously":{"view":1}
,"layouts":{"file":1}
,"perform":{"sort":1}
,"sort":{"operations":1,"data":1}
,"operations":{"find":1,"independently":1}
,"find":{"operations":1}
,"independently":{"windows":1}
,"saved":{"date":1}
,"date":{"time":1}
,"time":{"number":1}
,"number":{"formats":1}
,"formats":{"system":1,"set":1,"system\u2019s":1,"files":1,"if":1}
,"system":{"formats":1}
,"alert":{"message":1}
,"message":{"choose":1}
,"file\u2019s":{"formats":1}
,"system\u2019s":{"formats":1}
,"default":{"password":1}
,"by":{"pressing":1}
,"pressing":{"shift":1}
,"shift":{"key":1}
,"key":{"windows":1,"macos":1}
,"option":{"key":1}
,"macos":{"file":1}
,"displaying":{"specific":1,"data":1,"related":1}
,"specific":{"layout":1}
,"etting":{"file":1}
,"options":{"if":1}
,"close":{"file":1,"filemaker":1,"all":1}
,"remain":{"open":1}
,"hidden":{"file":1}
,"related":{"data":1}
,"attempted":{"close":1}
,"all":{"dependent":1,"versions":1}
,"dependent":{"windows":1}
,"versions":{"ilemaker":1,"converted":1}
,"ilemaker":{"pro":1}
,"version":{"12":1}
,"convert":{"file":1}
,"earlier":{"versions":1,"launch":1}
,"converted":{"converting":1}
,"converting":{"files":1}
,"11":{"advanced":1,"earlier":1}
,"launch":{"center":1}
,"center":{"logout":1}
,"logout":{"switch":1}
,"switch":{"accounts":1}
}
;Search.control.loadWordPairs(pairs);
