var pairs =
{
"xtending":{"broadening":1}
,"broadening":{"found":1}
,"found":{"set":1}
,"set":{"extending":1,"expand":1,"perform":1,"aking":1,"first":1,"boolean":1,"xample":1}
,"extending":{"found":1}
,"expand":{"search":1}
,"search":{"include":1,"perform":1,"choose":1,"customers":1}
,"include":{"additional":1,"customers":1}
,"additional":{"applicable":1}
,"applicable":{"records":1}
,"records":{"starting":1,"match":1}
,"starting":{"if":1}
,"if":{"you\u2019ve":1}
,"you\u2019ve":{"constrained":1}
,"constrained":{"previous":1}
,"previous":{"find":1}
,"find":{"request":1,"records":1,"next":1,"database":1,"mode":1,"new":1}
,"request":{"find":1,"switch":1,"type":1}
,"match":{"multiple":1}
,"multiple":{"criteria":1}
,"criteria":{"fields":1,"choose":1,"broaden":1}
,"fields":{"logical":1}
,"logical":{"search":1}
,"perform":{"find":1}
,"next":{"criteria":1}
,"choose":{"requests":1}
,"requests":{"menu":1}
,"menu":{"extend":1}
,"extend":{"found":1,"broaden":1}
,"database":{"found":1}
,"aking":{"find":1}
,"switch":{"back":1}
,"back":{"find":1}
,"mode":{"type":1,"enter":1}
,"type":{"criteria":1,"hong":1}
,"broaden":{"search":1,"found":1}
,"first":{"search":1}
,"customers":{"new":1,"hong":1}
,"new":{"york":1}
,"york":{"broaden":1,"city":1}
,"hong":{"kong":1}
,"kong":{"perform":1,"city":1}
,"city":{"field":1}
,"field":{"go":1,"choose":1}
,"go":{"find":1}
,"enter":{"second":1}
,"second":{"find":1}
,"boolean":{"extend":1}
}
;Search.control.loadWordPairs(pairs);
