var pairs =
{
"onobjectexit":{"performs":1,"script":1,"activate":1}
,"performs":{"script":1}
,"script":{"efore":1,"step":1,"script":1,"return":1,"proceeds":1,"canceled":1,"trigger":1,"triggered":1,"triggers":1,"determines":1,"result":1,"runs":1}
,"efore":{"active":1}
,"active":{"object":1,"activate":1}
,"object":{"exited":1,"user":1,"script":1,"active":1,"formatted":1,"set":1,"entered":1}
,"exited":{"result":1,"user":1,"onobjectenter":1}
,"result":{"user":1,"scrolling":1}
,"user":{"tabs":1,"clicks":1,"requests":1,"attempts":1}
,"tabs":{"object":1}
,"clicks":{"object":1}
,"step":{"attempts":1,"ithin":1,"onobjectenter":1}
,"attempts":{"object":1,"move":1}
,"requests":{"dialog":1}
,"dialog":{"box":1}
,"box":{"field":1}
,"field":{"exited":1,"event":1}
,"move":{"rows":1,"repetitions":1}
,"rows":{"portal":1}
,"portal":{"object":1,"row":1,"find":1}
,"repetitions":{"repeating":1}
,"repeating":{"field":1}
,"event":{"processed":1,"triggered":1}
,"processed":{"browse":1}
,"browse":{"find":1}
,"find":{"modes":1,"mode":1}
,"modes":{"use":1,"trigger":1}
,"use":{"exit":1}
,"exit":{"script":1,"occurs":1,"successful":1}
,"ithin":{"triggered":1}
,"triggered":{"script":1,"if":1}
,"return":{"true":1}
,"true":{"false":1,"event":1}
,"false":{"true":1,"event":1}
,"proceeds":{"false":1}
,"canceled":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"10.0":1}
,"10.0":{"filemaker":1}
,"webdirect":{"script":1}
,"trigger":{"activate":1,"onobjectexit":1,"onobjectkeystroke":1,"activated":1,"set":1,"new":1,"actions":1,"result":1}
,"activate":{"assigned":1,"object":1,"onobjectexit":1,"script":1,"portal":1}
,"assigned":{"web":1,"summary":1,"objects":1}
,"web":{"viewer":1}
,"viewer":{"trigger":1}
,"formatted":{"if":1}
,"if":{"object":1}
,"set":{"allow":1,"row":1}
,"allow":{"entry":1}
,"entry":{"script":1}
,"entered":{"script":1}
,"onobjectenter":{"script":1}
,"onobjectkeystroke":{"script":1}
,"activated":{"assigned":1,"exit":1}
,"summary":{"calculation":1}
,"calculation":{"fields":1}
,"fields":{"clicking":1}
,"clicking":{"portal":1}
,"row":{"activate":1,"exited":1,"onobjectexit":1}
,"new":{"row":1}
,"triggers":{"assigned":1,"list":1}
,"objects":{"script":1}
,"occurs":{"script":1}
,"determines":{"exit":1}
,"successful":{"based":1}
,"based":{"script":1}
,"scrolling":{"object":1}
,"actions":{"don\u2019t":1,"activate":1}
,"don\u2019t":{"activate":1}
,"list":{"actions":1}
,"mode":{"script":1}
,"runs":{"modes":1}
}
;Search.control.loadWordPairs(pairs);
