var pairs =
{
"layoutobjectnames":{"eturns":1,"filename":1,"customers":1}
,"eturns":{"list":1}
,"list":{"names":1,"named":1}
,"names":{"all":1,"returned":1}
,"all":{"named":1}
,"named":{"objects":1,"tab":1}
,"objects":{"layoutname":1,"object":1,"portal":1,"contain":1,"by":1,"enclosed":1,"contained":1,"layoutobjectnames":1,"customers":1}
,"layoutname":{"filename":1,"-the":1,"isn\u2019t":1}
,"filename":{"layoutobjectnames":1,"layoutname":1,"-the":1}
,"-the":{"name":1}
,"name":{"open":1,"layout":1}
,"open":{"database":1}
,"database":{"file":1}
,"file":{"local":1,"text":1,"data":1}
,"local":{"remote":1}
,"remote":{"layoutname":1}
,"layout":{"database":1,"objects":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"8.5":1}
,"8.5":{"listed":1}
,"listed":{"items":1}
,"items":{"separated":1}
,"separated":{"by":1}
,"by":{"carriage":1,"list":1}
,"carriage":{"returns":1}
,"returns":{"layout":1,"list":1}
,"object":{"names":1}
,"returned":{"if":1,"named":1}
,"if":{"layoutname":1,"named":1}
,"isn\u2019t":{"object":1}
,"tab":{"controls":1}
,"controls":{"grouped":1}
,"grouped":{"objects":1}
,"portal":{"objects":1}
,"contain":{"named":1}
,"enclosed":{"angle":1}
,"angle":{"brackets":1}
,"brackets":{"angle":1,"if":1}
,"contained":{"named":1}
,"customers":{"data":1,"database":1}
,"data":{"entry":1}
,"entry":{"returns":1,"layout":1}
}
;Search.control.loadWordPairs(pairs);
