var pairs =
{
"data":{"date":1}
,"date":{"fields":1,"system":1,"line":1,"field":1}
,"fields":{"entering":1,"type":1}
,"entering":{"data":1,"dates":1}
,"type":{"dates":1,"date":1,"day":1,"year":1}
,"dates":{"enter":1,"two-digit":1}
,"enter":{"date":1,"dates":1}
,"system":{"format":1,"preferences":1}
,"format":{"file":1}
,"file":{"created":1}
,"created":{"type":1}
,"line":{"each":1}
,"each":{"field":1,"separator":1}
,"field":{"type":1,"typed":1}
,"day":{"month":1,"week":1}
,"month":{"year":1}
,"year":{"numbers":1,"date":1,"filemaker":1,"if":1}
,"numbers":{"separated":1}
,"separated":{"by":1}
,"by":{"lash":1}
,"lash":{"separator":1}
,"separator":{"character":1,"2\u002F3\u002F201":1,"except":1}
,"character":{"use":1,"each":1,"separator":1,"year":1}
,"use":{"character":1,"control":1}
,"2\u002F3\u002F201":{"use":1}
,"except":{"letter":1}
,"letter":{"colon":1}
,"colon":{"ign":1}
,"ign":{"if":1}
,"if":{"type":1,"enter":1}
,"typed":{"separator":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"enters":1}
,"enters":{"current":1}
,"current":{"year":1}
,"two-digit":{"years":1}
,"years":{"5\u002F12\u002F19":1,"entering":1,"use":1}
,"5\u002F12\u002F19":{"changed":1}
,"changed":{"four-digit":1}
,"four-digit":{"years":1}
,"control":{"panel":1}
,"panel":{"windows":1}
,"windows":{"system":1}
,"preferences":{"macos":1}
,"macos":{"change":1}
,"change":{"day":1}
,"week":{"drop-down":1}
,"drop-down":{"calendar":1}
}
;Search.control.loadWordPairs(pairs);
