var pairs =
{
"exit":{"script":1,"main":1}
,"script":{"orces":1,"sub-script":1,"stop":1,"value":1,"filemaker":1,"optional":1,"result":1,"script":1,"triggers":1,"step":1,"perform":1,"[text":1,"[specified":1,"exit":1,"print":1}
,"orces":{"running":1}
,"running":{"script":1}
,"sub-script":{"external":1,"returns":1,"users":1,"defined":1,"completed":1,"print":1}
,"external":{"script":1}
,"stop":{"text":1}
,"text":{"result":1,"value":1}
,"result":{"pecifies":1,"if":1,"script":1,"returned":1,"deleted":1,"stored":1,"end":1,"enter":1,"parameter":1,"get":1}
,"pecifies":{"text":1}
,"value":{"pass":1,"typically":1,"called":1}
,"pass":{"back":1,"user\u2019s":1}
,"back":{"parent":1}
,"parent":{"script":1}
,"typically":{"based":1}
,"based":{"state":1}
,"state":{"current":1}
,"current":{"script":1,"date":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"if":1}
,"if":{"exit":1,"optional":1,"records":1,"[get":1,"print":1,"users":1,"show":1,"result":1}
,"returns":{"main":1,"value":1}
,"main":{"script":1}
,"optional":{"script":1}
,"returned":{"stored":1}
,"stored":{"main":1,"local":1}
,"called":{"script":1}
,"deleted":{"exit":1}
,"local":{"global":1}
,"global":{"variable":1}
,"variable":{"use":1}
,"use":{"scripts":1,"script":1}
,"scripts":{"run":1,"main":1}
,"run":{"by":1}
,"by":{"script":1}
,"triggers":{"use":1,"reference":1}
,"step":{"return":1}
,"return":{"true":1}
,"true":{"false":1}
,"false":{"determine":1}
,"determine":{"triggering":1}
,"triggering":{"event":1}
,"event":{"processed":1}
,"processed":{"script":1}
,"reference":{"performs":1}
,"performs":{"find":1}
,"find":{"prints":1,"[restore]":1}
,"prints":{"if":1,"unpaid":1}
,"records":{"found":1,"exits":1,"exit":1,"sort":1,"[restore":1}
,"found":{"displays":1}
,"displays":{"all":1}
,"all":{"records":1}
,"exits":{"script":1}
,"perform":{"find":1,"script":1}
,"[restore]":{"if":1,"calls":1}
,"[get":{"foundcount":1,"scriptresult":1,"lastmessagechoice":1}
,"foundcount":{"=0]":1}
,"=0]":{"show":1}
,"show":{"all":1,"custom":1}
,"[text":{"result":1}
,"end":{"if":1}
,"print":{"[with":1,"sub-script":1,"invoices":1,"exit":1,"parameter":1,"unpaid":1}
,"[with":{"dialog":1}
,"dialog":{"off]":1,"invoices":1,"[\u0022":1}
,"off]":{"prints":1,"end":1,"else":1}
,"unpaid":{"invoices":1}
,"invoices":{"print":1,"if":1,"invoices":1,")]":1,":status":1,"want":1,"\u0022]":1,"sub-script":1}
,"users":{"choose":1}
,"choose":{"want":1,"print":1}
,"want":{"print":1}
,"enter":{"rinted":1}
,"rinted":{"current":1}
,"date":{"status":1}
,"status":{"field":1}
,"field":{"new":1,"contents":1}
,"new":{"window":1}
,"window":{"[style":1,"[current":1}
,"[style":{"document":1}
,"document":{"name":1}
,"name":{"invoice":1}
,"invoice":{"list":1}
,"list":{"layout":1,"print":1}
,"layout":{"print":1}
,")]":{"perform":1,"else":1,"automating":1}
,"calls":{"print":1}
,"defined":{"perform":1}
,"[specified":{"list":1}
,"parameter":{"continues":1,"pass":1}
,"continues":{"sub-script":1}
,"completed":{"if":1}
,"scriptresult":{"=1]":1}
,"=1]":{"replace":1,"print":1}
,"replace":{"field":1}
,"contents":{"[with":1}
,":status":{"printed":1}
,"printed":{"&get":1}
,"&get":{"currentdate":1}
,"currentdate":{")]":1}
,"else":{"show":1,"close":1}
,"sort":{"records":1}
,"[restore":{"dialog":1}
,"custom":{"dialog":1}
,"[\u0022":{"print":1}
,"\u0022]":{"if":1}
,"lastmessagechoice":{"=1]":1,")]":1}
,"close":{"window":1}
,"[current":{"window]":1}
,"window]":{"end":1}
,"user\u2019s":{"choice":1}
,"choice":{"main":1}
,"get":{"lastmessagechoice":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
