var pairs =
{
"number":{"functions":1,"ceiling":1,"rounded":1,"unique":1,"by":1,"stopping":1,"ithout":1,"ln":1,"decimal":1,"truncate":1,"truncated":1}
,"functions":{"number":1,"manipulate":1}
,"manipulate":{"numeric":1}
,"numeric":{"data":1}
,"data":{"function":1}
,"function":{"returns":1,"precision":1}
,"returns":{"abs":1}
,"abs":{"absolute":1}
,"absolute":{"value":1}
,"value":{"number":1,"dividing":1,"constant":1}
,"ceiling":{"number":1}
,"rounded":{"up":1,"next":1,"precision":1}
,"up":{"next":1}
,"next":{"integer":1,"lowest":1,"lower":1}
,"integer":{"combination":1,"value":1,"int":1,"art":1}
,"combination":{"number":1}
,"unique":{"hoose":1}
,"hoose":{"numberofchoices":1}
,"numberofchoices":{"items":1}
,"items":{"set":1}
,"set":{"etsize":1}
,"etsize":{"div":1}
,"div":{"next":1}
,"lowest":{"integer":1}
,"dividing":{"number":1}
,"by":{"ivisor":1,"divisor":1}
,"ivisor":{"exp":1}
,"exp":{"value":1}
,"constant":{"aised":1}
,"aised":{"power":1}
,"power":{"umber":1}
,"umber":{"factorial":1,"log":1,"mod":1,"divided":1,"nd":1,"negative":1}
,"factorial":{"factorial":1,"number":1}
,"stopping":{"optional":1}
,"optional":{"numberoffactors":1}
,"numberoffactors":{"floor":1}
,"floor":{"number":1}
,"lower":{"integer":1}
,"int":{"integer":1}
,"art":{"number":1}
,"ithout":{"rounding":1}
,"rounding":{"lg":1}
,"lg":{"base":1}
,"base":{"-2":1}
,"-2":{"logarithm":1}
,"logarithm":{"number":1,"umber":1}
,"ln":{"base-e":1}
,"base-e":{"natural":1}
,"natural":{"logarithm":1}
,"log":{"base-10":1}
,"base-10":{"common":1}
,"common":{"logarithm":1}
,"mod":{"remainder":1}
,"remainder":{"umber":1}
,"divided":{"by":1}
,"divisor":{"random":1}
,"random":{"umber":1}
,"nd":{"including":1}
,"including":{"including":1,"round":1}
,"round":{"number":1}
,"precision":{"number":1,"16":1}
,"decimal":{"setprecision":1,"point":1}
,"setprecision":{"math":1}
,"math":{"function":1}
,"16":{"400":1}
,"400":{"digits":1}
,"digits":{"right":1}
,"right":{"decimal":1}
,"point":{"sign":1}
,"sign":{"-1":1}
,"-1":{"umber":1}
,"negative":{"ero":1}
,"ero":{"ositive":1}
,"ositive":{"sqrt":1}
,"sqrt":{"square":1}
,"square":{"root":1}
,"root":{"number":1}
,"truncate":{"number":1}
,"truncated":{"number":1}
}
;Search.control.loadWordPairs(pairs);
