var pairs =
{
"creating":{"editing":1}
,"editing":{"extended":1,"number":1}
,"extended":{"rivileges":1,"privileges":1,"privilege":1}
,"rivileges":{"extended":1}
,"privileges":{"determine":1,"file":1,"privilege":1,"manage":1,"except":1,"tab":1,"allowable":1}
,"determine":{"data":1}
,"data":{"sharing":1,"access":1,"set":1}
,"sharing":{"options":1,"type":1,"files":1}
,"options":{"permitted":1}
,"permitted":{"by":1}
,"by":{"privilege":1,"default":1,"editing":1}
,"privilege":{"set":1,"determines":1,"sets":1,"create":1,"if":1,"view":1,"privilege":1,"dialog":1,"access":1,"time":1}
,"set":{"file":1,"allows":1,"manage":1,"choose":1,"want":1,"enabling":1,"up":1}
,"file":{"if":1,"shared":1,"client":1,"rom":1,"open":1,"account":1,"privilege":1,"menu":1}
,"if":{"file":1,"privilege":1,"open":1,"manage":1}
,"shared":{"access":1,"file":1,"data":1}
,"access":{"via":1,"all":1,"privilege":1,"select":1,"shared":1,"want":1}
,"via":{"filemaker":1}
,"filemaker":{"network":1,"webdirect":1,"pro":1}
,"network":{"extended":1,"odbc":1}
,"determines":{"if":1,"privilege":1}
,"allows":{"shared":1,"accessing":1}
,"client":{"access":1}
,"webdirect":{"extended":1}
,"accessing":{"file":1}
,"rom":{"web":1}
,"web":{"browser":1,"keyword":1}
,"browser":{"se":1}
,"se":{"accounts":1}
,"accounts":{"privilege":1}
,"sets":{"extended":1,"want":1,"access":1}
,"create":{"manage":1,"edit":1}
,"manage":{"extended":1,"security":1}
,"open":{"file":1}
,"account":{"assigned":1}
,"assigned":{"privilege":1}
,"menu":{"manage":1}
,"security":{"command":1,"detailed":1,"if":1,"dialog":1,"settings":1}
,"command":{"disabled":1}
,"disabled":{"diting":1,"by":1}
,"diting":{"privilege":1}
,"view":{"extended":1}
,"detailed":{"settings":1,"setup":1}
,"settings":{"dialog":1,"use":1}
,"dialog":{"box":1}
,"box":{"enable":1,"displays":1,"enter":1,"time":1}
,"enable":{"each":1,"disable":1}
,"each":{"extended":1,"privilege":1}
,"want":{"permit":1,"enable":1,"sharing":1}
,"permit":{"access":1}
,"all":{"extended":1}
,"except":{"fmreauthenticate10":1}
,"fmreauthenticate10":{"disabled":1,"10":1,"extended":1}
,"default":{"full":1,"time":1}
,"full":{"access":1}
,"choose":{"file":1}
,"displays":{"basic":1}
,"basic":{"security":1}
,"use":{"detailed":1}
,"setup":{"extended":1}
,"tab":{"new":1}
,"new":{"select":1,"privilege":1,"fmreauthenticate10":1}
,"select":{"keyword":1,"clear":1}
,"keyword":{"edit":1,"description":1}
,"edit":{"edit":1,"extended":1}
,"enter":{"change":1}
,"change":{"keyword":1,"default":1}
,"description":{"extended":1}
,"clear":{"checkbox":1}
,"checkbox":{"each":1}
,"disable":{"new":1}
,"enabling":{"extended":1}
,"allowable":{"privilege":1}
,"up":{"sharing":1,"maximum":1}
,"type":{"access":1}
,"files":{"network":1}
,"odbc":{"jdbc":1}
,"jdbc":{"filemaker":1}
,"pro":{"advanced":1}
,"advanced":{"publishing":1}
,"publishing":{"databases":1}
,"databases":{"web":1}
,"time":{"required":1,"fmreauthenticate10":1,"up":1,"fmreauthenticate":1}
,"required":{"user":1}
,"user":{"re-login":1}
,"re-login":{"accept":1}
,"accept":{"default":1}
,"10":{"minutes":1}
,"minutes":{"change":1,"by":1}
,"maximum":{"10080":1}
,"10080":{"minutes":1}
,"number":{"end":1}
,"end":{"fmreauthenticate":1}
,"fmreauthenticate":{"reate":1,"create":1}
,"reate":{"new":1}
}
;Search.control.loadWordPairs(pairs);
