var pairs =
{
"pecify":{"envelope":1}
,"envelope":{"contents":1,"place":1,"fields":1,"envelope":1,"layout":1}
,"contents":{"new":1,"place":1,"want":1,"select":1}
,"new":{"layout\u002Freport":1,"field":1,"line":1}
,"layout\u002Freport":{"assistant":1}
,"assistant":{"panel":1,"ou":1}
,"panel":{"new":1}
,"ou":{"place":1,"can\u2019t":1}
,"place":{"fields":1,"field":1,"insertion":1,"text":1}
,"fields":{"text":1,"envelope":1,"double-click":1,"merge":1,"enclosed":1,"use":1}
,"text":{"want":1,"punctuation":1,"inside":1}
,"want":{"print":1,"order":1,"choose":1,"move":1,"text":1,"remove":1}
,"print":{"each":1}
,"each":{"envelope":1,"field":1}
,"double-click":{"each":1}
,"field":{"want":1,"table":1,"create":1,"new":1,"envelope":1,"name":1}
,"order":{"want":1}
,"choose":{"field":1,"table":1}
,"table":{"first":1,"list":1,"by":1}
,"first":{"choose":1}
,"list":{"tables":1}
,"tables":{"place":1,"move":1}
,"create":{"new":1}
,"by":{"choosing":1,"double":1}
,"choosing":{"manage":1}
,"manage":{"database":1}
,"database":{"list":1}
,"move":{"field":1,"angle":1,"delete":1}
,"line":{"envelope":1}
,"insertion":{"point":1}
,"point":{"field":1}
,"angle":{"bracket":1}
,"bracket":{"delimiters":1}
,"delimiters":{"press":1,"sure":1}
,"press":{"enter":1,"backspace":1}
,"enter":{"return":1,"edit":1}
,"return":{"place":1}
,"punctuation":{"fields":1,"type":1,"text":1}
,"type":{"want":1}
,"remove":{"field":1}
,"select":{"field":1,"brackets":1}
,"name":{"delimiters":1,"if":1,"layout":1,"ou":1}
,"backspace":{"delete":1}
,"delete":{"filemaker":1,"field":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"formats":1}
,"formats":{"fields":1}
,"layout":{"merge":1,"insert":1,"purpose":1}
,"merge":{"fields":1}
,"enclosed":{"by":1}
,"double":{"angle":1}
,"sure":{"select":1}
,"brackets":{"field":1,"part":1}
,"if":{"move":1}
,"insert":{"punctuation":1}
,"inside":{"brackets":1}
,"part":{"field":1}
,"can\u2019t":{"enter":1}
,"edit":{"data":1}
,"data":{"merge":1}
,"use":{"layout":1}
}
;Search.control.loadWordPairs(pairs);
