var pairs =
{
"setting":{"auto-resize":1}
,"auto-resize":{"options":1,"vertically":1,"table":1,"settings":1,"display":1,"fixed":1}
,"options":{"layout":1,"grouped":1}
,"layout":{"objects":1,"viewed":1,"tab":1,"page":1,"mode":1,"inspector":1,"expand":1,"part":1,"settings":1,"object\u2019s":1,"window":1,"multiple":1,"applying":1,"parts":1,"background":1,"size":1,"edge":1,"browse":1}
,"objects":{"set":1,"automatically":1,"move":1,"anchored":1,"layout":1,"located":1,"inside":1,"align":1,"panel":1,"popover":1,"retain":1,"positioned":1,"maintain":1,"reduced":1,"nested":1,"applies":1,"ungrouping":1,"prevent":1,"se":1,"change":1,"right":1,"placed":1,"resize":1,"windows":1}
,"set":{"objects":1,"resize":1,"expand":1,"object":1,"auto-resize":1}
,"automatically":{"resize":1}
,"resize":{"move":1,"maintain":1,"panel":1,"settings":1,"objects":1,"individual":1,"popover":1,"vertically":1,"relative":1,"behave":1,"horizontally":1,"autoresize":1}
,"move":{"horizontally":1,"expand":1,"object":1,"resize":1,"filemaker":1}
,"horizontally":{"vertically":1,"enclosing":1,"table":1,"auto":1}
,"vertically":{"filemaker":1,"by":1,"keep":1,"anchored":1,"list":1,"resize":1}
,"filemaker":{"pro":1,"ro":1}
,"pro":{"adva":1,"advanced":1}
,"adva":{"nced":1}
,"nced":{"window":1}
,"window":{"resized":1,"made":1,"layout":1,"original":1,"auto-resize":1,"browse":1,"horizontally":1}
,"resized":{"horizontal":1,"anchor":1,"window":1,"object":1,"objects":1,"anchoring":1}
,"horizontal":{"settings":1,"position":1,"resize":1}
,"settings":{"apply":1,"tab":1,"applies":1,"objects":1,"vertical":1,"behave":1,"top":1,"included":1,"object":1,"group":1,"ndividual":1,"changed":1,"if":1}
,"apply":{"preview":1,"settings":1}
,"preview":{"mode":1}
,"mode":{"printing":1,"select":1,"objects":1}
,"printing":{"page":1}
,"page":{"size":1,"layout":1,"preview":1}
,"size":{"wider":1,"layout":1,"object\u2019s":1,"window":1,"object":1,"filemaker":1,"original":1}
,"wider":{"size":1,"leave":1,"left":1,"top":1}
,"viewed":{"printed":1}
,"printed":{"layout":1}
,"maintain":{"constant":1,"horizontal":1,"relative":1}
,"constant":{"distance":1,"rows":1}
,"distance":{"object":1,"center":1,"overlap":1}
,"object":{"anchored":1,"resides":1,"want":1,"maintain":1,"set":1,"inside":1,"portal":1,"under":1,"alignment":1,"position":1,"stays":1,"left-aligned":1,"moves":1,"right-aligned":1,"expands":1,"moved":1,"maintains":1,"by":1}
,"anchored":{"allows":1,"top":1,"layout":1,"tab":1,"right":1,"left":1,"object":1,"window":1,"horizontally":1}
,"allows":{"objects":1}
,"expand":{"contract":1,"right":1,"by":1,"move":1,"fill":1}
,"contract":{"filemaker":1}
,"advanced":{"indow":1,"window":1}
,"indow":{"resized":1,"made":1,"anchor":1}
,"anchor":{"points":1,"left":1,"settings":1,"selected":1,"object":1}
,"points":{"layout":1}
,"tab":{"slide":1,"autosizing":1,"control":1,"controls":1,"control\u2019s":1,"panel":1}
,"slide":{"control":1,"controls":1,"panel":1}
,"control":{"portal":1,"slide":1,"popover":1,"anchored":1}
,"portal":{"margin":1,"boundary":1,"if":1,"object":1,"auto-resize":1,"enlarged":1,"margins":1}
,"margin":{"object":1,"allow":1,"inner":1,"window":1,"layout":1,"each":1}
,"resides":{"by":1}
,"by":{"default":1,"anchoring":1,"increasing":1,"right":1}
,"default":{"objects":1,"left":1}
,"top":{"left":1,"anchors":1,"right":1,"and\u002For":1,"bottom":1,"anchor":1}
,"left":{"layout":1,"top":1,"objects":1,"window\u2019s":1,"if":1,"aligned":1,"right":1}
,"select":{"objects":1,"line":1,"right":1}
,"inspector":{"position":1,"objects":1,"object":1}
,"position":{"position":1,"tab":1,"layout":1,"width":1,"resized":1,"window":1,"left":1}
,"autosizing":{"select":1,"autosize":1}
,"line":{"object":1}
,"want":{"anchored":1,"fields":1}
,"allow":{"object":1,"objects":1}
,"right":{"window":1,"anchor":1,"anchors":1,"objects":1,"margin":1,"margins":1,"layout":1,"top":1,"bottom":1}
,"made":{"wider":1,"larger":1,"size":1}
,"leave":{"default":1}
,"anchors":{"selected":1}
,"selected":{"select":1,"inspector":1}
,"located":{"tab":1,"panel":1,"inside":1}
,"controls":{"slide":1,"popovers":1}
,"popovers":{"portals":1,"if":1}
,"portals":{"adhere":1,"anchored":1,"objects":1}
,"adhere":{"rules":1}
,"rules":{"objects":1}
,"popover":{"portal":1,"resize":1,"popover":1,"itself":1,"layout":1}
,"boundary":{"window":1,"if":1,"set":1}
,"part":{"boundary":1,"vertically":1}
,"if":{"tab":1,"want":1,"panel":1,"portal":1,"layout":1,"place":1}
,"inside":{"tab":1,"portals":1,"portal":1}
,"align":{"tab":1}
,"control\u2019s":{"left":1}
,"window\u2019s":{"left":1}
,"fields":{"tab":1,"located":1,"popover":1}
,"panel":{"slide":1,"resize":1,"fields":1,"if":1,"set":1,"controls":1}
,"individual":{"resize":1}
,"applies":{"popovers":1,"settings":1}
,"itself":{"objects":1}
,"and\u002For":{"bottom":1}
,"bottom":{"each":1,"entire":1,"layout":1,"margins":1,"except":1,"navigation":1}
,"each":{"row":1,"therefore":1}
,"row":{"top":1,"height":1}
,"entire":{"portal":1}
,"anchoring":{"top":1,"objects":1}
,"increasing":{"height":1}
,"height":{"existing":1,"constant":1,"static":1}
,"existing":{"rows":1}
,"rows":{"row":1,"displayed":1,"set":1}
,"displayed":{"window":1,"object":1,"views":1}
,"larger":{"increase":1}
,"increase":{"height":1,"number":1}
,"keep":{"row":1}
,"static":{"increase":1}
,"number":{"rows":1}
,"enlarged":{"set":1}
,"table":{"compares":1,"view":1}
,"compares":{"effects":1}
,"effects":{"combined":1}
,"combined":{"horizontal":1}
,"vertical":{"resize":1,"orientation":1}
,"behave":{"illustrations":1,"displayed":1}
,"illustrations":{"outer":1}
,"outer":{"rectangle":1}
,"rectangle":{"represents":1,"alignment":1}
,"represents":{"layout":1}
,"inner":{"rectangle":1}
,"alignment":{"anchored":1,"size":1}
,"under":{"layout":1}
,"included":{"objects":1}
,"retain":{"vertical":1}
,"orientation":{"layout":1}
,"object\u2019s":{"position":1}
,"width":{"window":1}
,"original":{"size":1,"position":1,"layout":1}
,"stays":{"original":1}
,"aligned":{"window":1}
,"left-aligned":{"expand":1}
,"moves":{"right":1}
,"right-aligned":{"moving":1}
,"moving":{"right":1}
,"expands":{"left":1,"meet":1}
,"margins":{"window":1,"object":1,"move":1}
,"meet":{"left":1}
,"moved":{"relative":1}
,"relative":{"center":1,"layout":1,"distance":1}
,"center":{"layout":1}
,"maintains":{"constant":1}
,"multiple":{"objects":1}
,"positioned":{"side-by-side":1}
,"side-by-side":{"stacked":1}
,"stacked":{"vertically":1}
,"therefore":{"adjacent":1}
,"adjacent":{"objects":1}
,"overlap":{"window":1}
,"reduced":{"original":1}
,"applying":{"resizing":1}
,"resizing":{"options":1,"auto-resize":1}
,"grouped":{"objects":1}
,"nested":{"groups":1}
,"groups":{"objects":1}
,"group":{"bjects":1,"apply":1}
,"bjects":{"group":1}
,"ndividual":{"objects":1}
,"ungrouping":{"editing":1}
,"editing":{"objects":1}
,"parts":{"layout":1,"set":1}
,"background":{"locking":1}
,"locking":{"objects":1}
,"prevent":{"resizing":1}
,"changed":{"locked":1}
,"locked":{"objects":1}
,"se":{"protecting":1}
,"protecting":{"objects":1}
,"change":{"if":1}
,"except":{"popover":1}
,"fill":{"window":1}
,"browse":{"find":1,"mode":1}
,"find":{"modes":1}
,"modes":{"page":1}
,"views":{"form":1}
,"form":{"view":1}
,"view":{"objects":1,"auto-resize":1}
,"enclosing":{"layout":1}
,"list":{"view":1}
,"place":{"objects":1}
,"edge":{"auto-resize":1}
,"display":{"layout":1}
,"placed":{"top":1}
,"navigation":{"parts":1}
,"fixed":{"vertically":1}
,"auto":{"resize":1}
,"autoresize":{"autosizing":1}
,"autosize":{"allow":1}
,"ro":{"advanced":1}
,"windows":{"resized":1}
}
;Search.control.loadWordPairs(pairs);
