var pairs =
{
"clear":{"eletes":1,"customer\u0027s":1,"[select":1}
,"eletes":{"contents":1}
,"contents":{"field":1,"deletes":1,"selected":1,"want":1,"clipboard":1,"if":1}
,"field":{"current":1,"if":1,"specifies":1,"contents":1,"use":1,"data":1}
,"current":{"record":1}
,"record":{"select":1,"placing":1,"show":1}
,"select":{"entire":1,"field":1}
,"entire":{"contents":1}
,"deletes":{"entire":1}
,"if":{"use":1,"want":1,"manually":1,"selection":1,"[get":1,"opying":1}
,"use":{"select":1,"cut":1,"undo":1,"et":1}
,"selected":{"portion":1}
,"portion":{"field\u0027s":1}
,"field\u0027s":{"data":1}
,"data":{"deleted":1,"run":1,"records":1}
,"deleted":{"go":1}
,"go":{"target":1}
,"target":{"field":1}
,"specifies":{"field":1}
,"want":{"delete":1,"cut":1,"clear":1}
,"delete":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"script":1}
,"script":{"step":1}
,"step":{"removes":1,"use":1,"filemaker":1,"performs":1,"clears":1}
,"removes":{"contents":1}
,"placing":{"contents":1}
,"clipboard":{"if":1}
,"cut":{"paste":1,"script":1}
,"paste":{"field":1}
,"undo":{"restore":1}
,"restore":{"contents":1}
,"manually":{"select":1}
,"run":{"script":1}
,"webdirect":{"script":1,"use":1}
,"performs":{"if":1}
,"selection":{"select":1,"script":1}
,"et":{"selection":1}
,"clears":{"email":1}
,"email":{"field":1,"address":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"dialog":{"[\u0022":1}
,"[\u0022":{"want":1}
,"customer\u0027s":{"email":1}
,"address":{"\u0022]":1}
,"\u0022]":{"if":1}
,"[get":{"lastmessagechoice":1}
,"lastmessagechoice":{"=1]":1}
,"=1]":{"clear":1}
,"[select":{"customers":1}
,"customers":{":email]":1}
,":email]":{"end":1}
,"end":{"if":1}
,"opying":{"moving":1}
,"moving":{"data":1}
,"records":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
