var pairs =
{
"diting":{"layouts":1,"record":1}
,"layouts":{"privileges":1,"file":1,"allow":1,"prohibit":1,"set":1,"choose":1,"allowed":1,"custom":1,"duplicating":1,"edit":1}
,"privileges":{"privilege":1,"all":1,"individual":1,"record":1,"use":1,"limit":1,"se":1,"if":1,"allow":1,"apply":1,"custom":1,"dialog":1,"layout":1,"want":1,"diting":1,"manage":1,"comparison":1,"search":1}
,"privilege":{"sets":1,"set":1,"all":1}
,"sets":{"limit":1,"data":1}
,"limit":{"access":1}
,"access":{"layouts":1,"all":1,"limits":1,"layout":1,"data":1,"field":1,"privileges":1,"tables":1,"design":1,"options":1,"viewing":1,"allow":1,"each":1}
,"file":{"file":1,"set":1,"custom":1}
,"set":{"privileges":1,"two":1,"permits":1,"edit":1,"dialog":1,"accounts":1}
,"all":{"layouts":1,"data":1,"instances":1,"occurrences":1,"modifiable":1,"view":1,"access":1}
,"allow":{"prohibit":1,"viewing":1,"creating":1,"creation":1}
,"prohibit":{"ability":1,"access":1,"privilege":1,"design":1,"viewing":1,"editing":1,"data":1}
,"ability":{"switch":1}
,"switch":{"layout":1}
,"layout":{"mode":1,"design":1,"privilege":1,"layout":1,"access":1,"privileges":1,"by":1,"basis":1,"select":1,"set":1,"created":1,"changing":1,"choose":1,"prohibit":1,"records":1,"user":1,"protect":1}
,"mode":{"design":1,"view-only":1,"order":1,"deleting":1}
,"design":{"all":1,"view":1,"layout":1,"layouts":1,"allowed":1}
,"custom":{"privileges":1,"layout":1}
,"individual":{"layouts":1}
,"two":{"types":1}
,"types":{"access":1}
,"limits":{"each":1}
,"each":{"layout":1,"field":1}
,"view":{"limits":1,"layout":1,"data":1,"all":1,"prohibit":1,"access":1}
,"permits":{"design":1,"accessing":1}
,"view-only":{"layout":1}
,"data":{"access":1,"displayed":1,"prohibited":1,"distinctions":1,"settings":1,"layout":1,"limit":1,"record":1,"editing":1,"creating":1,"prohibit":1,"records":1,"scripts":1,"relationships":1,"files":1}
,"accessing":{"viewing":1}
,"viewing":{"modifying":1,"editing":1,"all":1,"layout":1,"data":1}
,"modifying":{"data":1}
,"displayed":{"by":1,"accessed":1}
,"by":{"each":1,"layout":1}
,"prohibited":{"user":1,"duplicating":1,"prohibited":1,"creating":1,"entering":1,"start":1}
,"user":{"view":1,"access":1}
,"field":{"data":1,"field":1}
,"distinctions":{"interactions":1}
,"interactions":{"layouts":1}
,"record":{"access":1}
,"use":{"layout":1,"record":1}
,"settings":{"protect":1}
,"protect":{"single":1,"all":1}
,"single":{"view":1}
,"basis":{"protect":1}
,"instances":{"data":1}
,"occurrences":{"specific":1}
,"specific":{"tables":1}
,"tables":{"records":1,"fields":1}
,"records":{"fields":1,"start":1,"layout":1,"via":1,"diting":1}
,"fields":{"matter":1,"records":1}
,"matter":{"displayed":1}
,"accessed":{"use":1}
,"se":{"diting":1}
,"if":{"use":1}
,"editing":{"data":1,"new":1,"privilege":1,"accounts":1}
,"apply":{"limit":1}
,"start":{"editing":1}
,"new":{"existing":1,"layouts":1,"layout":1}
,"existing":{"privilege":1}
,"edit":{"privilege":1,"rivileges":1,"privileges":1}
,"dialog":{"box":1}
,"box":{"creating":1,"select":1,"allow":1,"view":1,"assign":1}
,"creating":{"editing":1,"new":1,"deleting":1}
,"choose":{"all":1,"custom":1,"modifiable":1,"view":1,"access":1}
,"modifiable":{"all":1,"allow":1}
,"options":{"allow":1,"records":1}
,"allowed":{"allowed":1,"prohibited":1}
,"duplicating":{"deleting":1,"viewable":1}
,"deleting":{"all":1,"layout":1,"records":1}
,"entering":{"layout":1}
,"order":{"design":1}
,"select":{"each":1,"new":1,"allow":1}
,"created":{"set":1}
,"want":{"you\u2019re":1}
,"you\u2019re":{"setting":1}
,"setting":{"privileges":1}
,"changing":{"design":1}
,"via":{"layout":1}
,"viewable":{"layout":1}
,"creation":{"new":1}
,"scripts":{"access":1}
,"relationships":{"display":1}
,"display":{"data":1}
,"files":{"limit":1}
,"manage":{"security":1}
,"security":{"dialog":1}
,"assign":{"privilege":1}
,"accounts":{"creating":1,"ny":1}
,"ny":{"record":1}
,"comparison":{"layouts":1}
,"search":{"filemaker":1}
,"filemaker":{"knowledge":1}
,"knowledge":{"base":1}
,"base":{"edit":1}
,"rivileges":{"all":1}
}
;Search.control.loadWordPairs(pairs);
