var pairs =
{
"install":{"ontimer":1}
,"ontimer":{"script":1}
,"script":{"uns":1,"interval":1,"want":1,"parameter":1,"filemaker":1,"step":1,"window":1,"running":1,"new":1,"performed":1,"started":1,"use":1,"step\u2019s":1,"minute":1,"[\u0022":1,"clock":1}
,"uns":{"script":1}
,"interval":{"ript":1,"seconds":1,"if":1,"60]":1}
,"ript":{"script":1}
,"want":{"perform":1}
,"perform":{"optional":1}
,"optional":{"script":1}
,"parameter":{"script":1,"option":1}
,"seconds":{"value":1,"timer":1}
,"value":{"seconds":1,"optional":1,"timer":1}
,"timer":{"waits":1,"active":1,"window":1,"by":1,"user":1,"each":1,"operating":1,"script":1,"installed":1}
,"waits":{"running":1}
,"running":{"script":1,"install":1,"scripts":1,"finishes":1,"value":1}
,"filemaker":{"pro":1,"server":1,"cloud":1}
,"pro":{"10.0":1}
,"10.0":{"script":1}
,"step":{"installs":1,"script":1,"run":1}
,"installs":{"single":1,"timer":1}
,"single":{"timer":1}
,"active":{"window":1}
,"window":{"repeats":1,"install":1,"window":1,"closes":1,"installed":1,"new":1,"inherits":1,"separate":1,"styles":1}
,"repeats":{"script":1}
,"closes":{"halt":1}
,"halt":{"installed":1}
,"installed":{"timer":1,"time":1}
,"by":{"running":1}
,"if":{"script":1,"active":1,"windows":1,"you\u2019re":1}
,"scripts":{"associated":1,"schedule":1,"script":1}
,"associated":{"timers":1}
,"timers":{"run":1,"continue":1,"window":1}
,"run":{"script":1,"if":1,"scripts":1,"clock":1}
,"finishes":{"if":1}
,"user":{"script":1}
,"new":{"window":1}
,"inherits":{"timer":1}
,"each":{"window":1}
,"separate":{"timer":1}
,"operating":{"time":1}
,"time":{"timers":1,"get":1}
,"continue":{"run":1}
,"windows":{"background":1,"timers":1,"filemaker":1}
,"background":{"hidden":1}
,"hidden":{"if":1}
,"you\u2019re":{"dialog":1}
,"dialog":{"windows":1}
,"styles":{"value":1}
,"option":{"evaluated":1,"run":1}
,"evaluated":{"timer":1}
,"performed":{"timer":1}
,"get":{"scriptparameter":1,"currenttime":1}
,"scriptparameter":{"value":1,"script":1}
,"started":{"while":1}
,"while":{"script":1}
,"use":{"use":1,"constant":1}
,"constant":{"global":1}
,"global":{"field":1,"local":1}
,"field":{"global":1,"[clock":1}
,"local":{"variable":1}
,"variable":{"calculation":1}
,"calculation":{"functions":1}
,"functions":{"get":1}
,"step\u2019s":{"optional":1}
,"schedule":{"independently":1}
,"independently":{"open":1}
,"open":{"windows":1}
,"server":{"help":1}
,"help":{"filemaker":1}
,"cloud":{"documentation":1}
,"documentation":{"install":1}
,"clock":{"script":1,"ontimer":1}
,"minute":{"install":1}
,"[\u0022":{"lock":1}
,"lock":{"interval":1}
,"60]":{"set":1}
,"set":{"field":1}
,"[clock":{":time":1}
,":time":{"get":1}
,"currenttime":{")]":1}
,")]":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
