var pairs =
{
"get":{"device":1}
,"device":{"returns":1,"running":1,"none":1,"currently":1,"mac":1,"get":1}
,"returns":{"number":1,"unknown":1,"if":1}
,"number":{"representing":1,"filemaker":1,"indicating":1}
,"representing":{"type":1}
,"type":{"computer":1,"ios":1}
,"computer":{"mobile":1,"running":1,"windows":1}
,"mobile":{"device":1}
,"running":{"filemaker":1,"windows":1,"computer":1,"ipad":1}
,"filemaker":{"product":1,"pro":1,"webdirect":1,"go":1}
,"product":{"get":1}
,"none":{"number":1}
,"pro":{"13.0":1,"advanced":1}
,"13.0":{"function":1}
,"function":{"returns":1}
,"indicating":{"type":1}
,"currently":{"running":1}
,"advanced":{"filemaker":1}
,"webdirect":{"type":1,"currently":1}
,"ios":{"device":1}
,"go":{"returns":1,"filemaker":1}
,"unknown":{"device":1}
,"mac":{"computer":1}
,"windows":{"ipad":1,"returns":1}
,"ipad":{"iphone":1,"script":1}
,"iphone":{"ipod":1}
,"ipod":{"touch":1}
,"touch":{"android":1}
,"android":{"returns":1}
,"if":{"filemaker":1}
,"script":{"avplayer":1,"step":1}
,"avplayer":{"play":1}
,"play":{"script":1}
,"step":{"get":1}
}
;Search.control.loadWordPairs(pairs);
