var pairs =
{
"nt":{"ing":1}
,"ing":{"editing":1}
,"editing":{"smtp":1}
,"smtp":{"options":1,"supply":1,"server":1,"enter":1,"server\u2019s":1}
,"options":{"send":1,"dialog":1,"first":1,"smtp":1,"step":1}
,"send":{"email":1,"mail":1,"via":1}
,"email":{"smtp":1,"send":1,"sender":1,"address":1,"ort":1,"requires":1,"options":1,"messages":1}
,"supply":{"sender":1}
,"sender":{"smtp":1,"name":1}
,"server":{"smtp":1,"edit":1,"selected":1,"name":1,"enter":1,"email":1,"connection":1,"choose":1,"users":1,"password":1,"returned":1}
,"dialog":{"box":1}
,"box":{"ilemaker":1,"by":1,"enter":1,"continue":1}
,"ilemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"send":1}
,"enter":{"each":1,"smtp":1,"user":1,"name":1,"email":1,"reply-to":1,"number":1,"correct":1,"password":1,"edit":1}
,"each":{"time":1}
,"time":{"send":1}
,"mail":{"display":1,"dialog":1,"create":1,"script":1,"me@mycompany.com":1,"server":1}
,"display":{"send":1}
,"by":{"choose":1}
,"choose":{"file":1,"smtp":1,"none":1,"ssl":1,"tls":1,"plain":1}
,"file":{"menu":1}
,"menu":{"send":1}
,"create":{"script":1}
,"script":{"sends":1,"step":1}
,"sends":{"email":1}
,"step":{"send":1,"sending":1}
,"first":{"time":1}
,"via":{"choose":1}
,"edit":{"smtp":1}
,"selected":{"smtp":1}
,"user":{"smtp":1,"name":1,"id":1}
,"name":{"enter":1,"email":1,"name":1,"appears":1,"smtp":1,"if":1,"password":1}
,"appears":{"field":1}
,"field":{"outgoing":1}
,"outgoing":{"messages":1,"mail":1,"address":1,"smtp":1}
,"messages":{"e-mail":1,"enter":1}
,"e-mail":{"address":1}
,"address":{"enter":1,"outgoing":1,"incoming":1,"you@mycompany.com":1,"replies":1}
,"me@mycompany.com":{"reply-to":1}
,"reply-to":{"address":1}
,"incoming":{"replies":1}
,"replies":{"outgoing":1}
,"you@mycompany.com":{"if":1}
,"if":{"enter":1,"secure":1,"email":1,"choose":1}
,"ort":{"keep":1}
,"keep":{"default":1}
,"default":{"25":1,"none":1}
,"25":{"enter":1}
,"number":{"x.400":1,"connect":1}
,"x.400":{"port":1}
,"port":{"number":1,"actual":1}
,"connect":{"smtp":1}
,"connection":{"encryption":1,"choose":1}
,"encryption":{"choose":1,"depends":1,"cram":1,"user":1}
,"none":{"if":1,"require":1}
,"secure":{"connection":1,"sockets":1,"ins":1}
,"ssl":{"secure":1}
,"sockets":{"layer":1}
,"layer":{"if":1,"security":1}
,"requires":{"secure":1}
,"tls":{"transport":1}
,"transport":{"layer":1}
,"security":{"allow":1}
,"allow":{"secure":1}
,"ins":{"ecure":1}
,"ecure":{"connections":1}
,"connections":{"port":1}
,"actual":{"connection":1}
,"depends":{"smtp":1}
,"server\u2019s":{"configuration":1}
,"configuration":{"authentication":1}
,"authentication":{"keep":1,"smtp":1,"enter":1}
,"require":{"login":1}
,"login":{"authentication":1}
,"plain":{"password":1}
,"password":{"password":1,"encryption":1,"cram-md5":1,"send":1,"if":1,"authenticate":1}
,"cram":{"\u2011md5":1}
,"\u2011md5":{"password":1}
,"cram-md5":{"authentication":1}
,"id":{"authenticate":1}
,"authenticate":{"user":1}
,"users":{"enter":1}
,"correct":{"name":1}
,"returned":{"send":1}
,"continue":{"setting":1}
,"setting":{"email":1}
,"sending":{"email":1}
}
;Search.control.loadWordPairs(pairs);
