var pairs =
{
"evaluationerror":{"returns":1,"expression":1,"function":1,"getfield":1,"evaluate":1}
,"returns":{"error":1,"102":1,"1207":1}
,"error":{"code":1,"invalid":1,"field":1,"codes":1}
,"code":{"if":1}
,"if":{"expression":1}
,"expression":{"evaluationerror":1,"expression":1,"-any":1,"number":1}
,"-any":{"calculation":1}
,"calculation":{"expression":1,"runtime":1,"currently":1}
,"number":{"filemaker":1}
,"filemaker":{"pro":1,"error":1}
,"pro":{"7.0":1}
,"7.0":{"two":1}
,"two":{"types":1}
,"types":{"errors":1}
,"errors":{"syntax":1,"evaluationerror":1}
,"syntax":{"runtime":1,"error":1,"errors":1}
,"runtime":{"syntax":1,"error":1}
,"invalid":{"calculation":1}
,"field":{"missing":1,"total":1}
,"missing":{"record":1,"occurs":1,"field":1}
,"record":{"missing":1}
,"occurs":{"calculation":1}
,"currently":{"run":1}
,"run":{"valid":1}
,"valid":{"properly":1}
,"properly":{"execute":1}
,"execute":{"filemaker":1}
,"codes":{"list":1,"messages":1}
,"list":{"error":1}
,"messages":{"evaluationerror":1}
,"function":{"enclose":1,"return":1}
,"enclose":{"evaluate":1}
,"evaluate":{"function":1,"calculationfield":1}
,"return":{"syntax":1}
,"getfield":{"total":1}
,"total":{"returns":1,"deleted":1}
,"102":{"field":1}
,"deleted":{"renamed":1}
,"renamed":{"evaluationerror":1}
,"calculationfield":{"returns":1,"abs":1}
,"1207":{"unbalanced":1}
,"unbalanced":{"parenthesis":1}
,"parenthesis":{"calculationfield":1}
,"abs":{"(-1":1}
,"(-1":{"closing":1}
,"closing":{"parenthesis":1}
}
;Search.control.loadWordPairs(pairs);
