var pairs =
{
"e-login":{"llows":1}
,"llows":{"logging":1}
,"logging":{"file":1}
,"file":{"account":1,"dialog":1}
,"account":{"password":1,"name":1,"authenticated":1,"filemaker":1,"take":1,"note":1,"step":1,"[account":1}
,"password":{"close":1,"edit":1,"stored":1,"allows":1,"account":1,"set":1,"dialog":1,"script":1}
,"close":{"reopen":1}
,"reopen":{"file":1}
,"dialog":{"controls":1,"box":1,"set":1,"option":1,"on]":1}
,"controls":{"open":1}
,"open":{"filename":1,"file":1}
,"filename":{"dialog":1}
,"box":{"displays":1,"requires":1,"open":1,"if":1,"prompts":1}
,"displays":{"script":1,"dialog":1}
,"script":{"step":1,"runs":1,"delete":1}
,"step":{"performed":1,"generates":1,"users":1,"re-login":1,"enabled":1,"if":1,"displayed":1}
,"performed":{"dialog":1,"account":1}
,"requires":{"user":1}
,"user":{"manually":1,"re-login":1,"\u0022]":1}
,"manually":{"enter":1}
,"enter":{"account":1}
,"edit":{"displayed":1}
,"displayed":{"dialog":1}
,"set":{"filemaker":1,"error":1}
,"filemaker":{"pro":1,"data":1,"webdirect":1}
,"pro":{"advanced":1,"7.0":1}
,"advanced":{"account":1}
,"stored":{"script":1}
,"generates":{"calculations":1}
,"calculations":{"script":1}
,"name":{"allows":1,"account":1,"user":1}
,"allows":{"name":1,"password":1}
,"authenticated":{"password":1}
,"7.0":{"privileges":1}
,"privileges":{"assigned":1,"perform":1,"run":1}
,"assigned":{"new":1}
,"new":{"account":1}
,"take":{"including":1}
,"including":{"access":1}
,"access":{"tables":1,"privileges":1,"use":1}
,"tables":{"records":1}
,"records":{"layouts":1}
,"layouts":{"scripts":1}
,"scripts":{"value":1,"filemaker":1}
,"value":{"lists":1}
,"lists":{"full":1}
,"full":{"access":1}
,"perform":{"script":1}
,"users":{"level":1,"get":1,"full":1}
,"level":{"access":1}
,"use":{"script":1}
,"re-login":{"database":1,"deleting":1,"[with":1}
,"database":{"users":1}
,"get":{"attempts":1,"single":1}
,"attempts":{"enter":1}
,"error":{"capture":1}
,"capture":{"script":1}
,"enabled":{"if":1,"users":1}
,"if":{"set":1,"option":1,"store":1}
,"single":{"attempt":1}
,"attempt":{"enter":1}
,"option":{"depending":1,"set":1,"displays":1}
,"depending":{"script":1}
,"runs":{"server-side":1}
,"server-side":{"scripts":1}
,"data":{"api":1}
,"api":{"nd":1}
,"nd":{"custom":1}
,"custom":{"web":1}
,"web":{"publishing":1}
,"publishing":{"run":1}
,"run":{"script":1}
,"webdirect":{"setting":1}
,"setting":{"option":1}
,"store":{"account":1}
,"prompts":{"current":1}
,"current":{"user":1}
,"deleting":{"account":1}
,"note":{"delete":1}
,"delete":{"account":1}
,"[account":{"name":1}
,"\u0022]":{"re-login":1}
,"[with":{"dialog":1}
,"on]":{"relogin":1}
,"relogin":{"login":1}
,"login":{"log":1}
,"log":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
