var pairs =
{
"xample":{"value":1}
,"value":{"list":1,"list\u0027s":1,"entered":1,"category":1,"lists":1}
,"list":{"includes":1,"field":1,"display":1,"assign":1,"instructions":1,"displaying":1,"categories":1,"values":1,"include":1,"defining":1,"created":1}
,"includes":{"related":1}
,"related":{"field":1,"records":1,"values":1,"selected":1}
,"field":{"values":1,"filemaker":1,"value":1,"related":1,"imagine":1,"display":1,"category":1,"accessory":1,"called":1,"products":1,"item":1,"choose":1,"displays":1,"relationship":1}
,"values":{"if":1,"value":1,"based":1,"second":1,"first":1,"category":1,"item":1,"rom":1,"match":1}
,"if":{"generating":1}
,"generating":{"values":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"dynamically":1}
,"dynamically":{"change":1}
,"change":{"value":1}
,"list\u0027s":{"values":1}
,"based":{"values":1}
,"second":{"field":1}
,"display":{"values":1,"subset":1,"value":1,"pop-up":1}
,"first":{"field":1}
,"records":{"relationship":1}
,"relationship":{"definition":1,"products":1,"creates":1,"reside":1}
,"definition":{"met":1}
,"met":{"by":1}
,"by":{"value":1}
,"entered":{"second":1}
,"imagine":{"table":1}
,"table":{"called":1,"use":1,"relationships":1,"define":1,"defining":1,"display":1,"choose":1}
,"called":{"products":1,"item":1,"category":1}
,"products":{"tracks":1,"fields":1,"table":1}
,"tracks":{"large":1}
,"large":{"number":1}
,"number":{"inventory":1}
,"inventory":{"items":1}
,"items":{"define":1,"based":1,"related":1}
,"define":{"value":1,"self-join":1}
,"assign":{"item":1}
,"item":{"name":1,"necklace":1,"item":1}
,"name":{"field":1,"values":1,"list":1,"each":1,"set":1}
,"subset":{"items":1}
,"category":{"during":1,"field":1,"equals":1,"displays":1,"fields":1,"item":1}
,"during":{"data":1}
,"data":{"entry":1}
,"entry":{"value":1}
,"accessory":{"item":1,"show":1,"clothing":1}
,"equals":{"accessory":1}
,"show":{"up":1}
,"up":{"value":1,"field":1}
,"instructions":{"assume":1}
,"assume":{"table":1}
,"fields":{"products":1,"match":1,"self-joining":1}
,"displaying":{"name":1}
,"each":{"item":1}
,"necklace":{"bracelet":1}
,"bracelet":{"field":1}
,"displays":{"list":1,"items":1}
,"categories":{"accessory":1}
,"clothing":{"define":1}
,"self-join":{"relationship":1}
,"use":{"category":1}
,"match":{"fields":1,"field":1}
,"self-joining":{"relationships":1}
,"relationships":{"defining":1,"graph":1}
,"defining":{"self-join":1,"value":1}
,"creates":{"occurrence":1}
,"occurrence":{"products":1}
,"graph":{"referred":1}
,"referred":{"products":1}
,"include":{"related":1}
,"rom":{"products":1}
,"lists":{"ormat":1}
,"ormat":{"item":1}
,"created":{"step":1}
,"step":{"setting":1}
,"setting":{"up":1}
,"pop-up":{"menu":1}
,"menu":{"checkbox":1}
,"checkbox":{"set":1}
,"set":{"control":1,"up":1}
,"control":{"browse":1}
,"browse":{"mode":1}
,"mode":{"products":1}
,"choose":{"ca":1,"item":1}
,"ca":{"tegory":1}
,"tegory":{"category":1}
,"selected":{"category":1}
,"reside":{"file":1}
,"file":{"category":1}
}
;Search.control.loadWordPairs(pairs);
