var pairs =
{
"di":{"ting":1}
,"ting":{"layouts":1}
,"layouts":{"you\u2019ve":1}
,"you\u2019ve":{"created":1}
,"created":{"layout":1}
,"layout":{"choose":1,"appears":1,"active":1,"change":1,"layout":1,"setup":1,"bar":1,"mode":1}
,"choose":{"displayed":1,"views":1,"default":1,"save":1}
,"displayed":{"choose":1}
,"views":{"layout":1}
,"default":{"view":1,"table":1}
,"view":{"first":1,"associate":1}
,"first":{"open":1}
,"open":{"layout":1}
,"table":{"records":1}
,"records":{"displayed":1,"changed":1}
,"save":{"records":1}
,"changed":{"show":1}
,"show":{"hide":1,"field":1}
,"hide":{"field":1}
,"field":{"frames":1,"borders":1}
,"frames":{"browse":1}
,"browse":{"find":1}
,"find":{"modes":1}
,"modes":{"show":1}
,"borders":{"fill":1}
,"fill":{"current":1}
,"current":{"record":1}
,"record":{"list":1}
,"list":{"view":1}
,"associate":{"menu":1}
,"menu":{"set":1}
,"set":{"layout":1}
,"appears":{"layout":1}
,"active":{"change":1}
,"change":{"theme":1,"width":1}
,"theme":{"layout":1}
,"width":{"layout":1}
,"setup":{"dialog":1}
,"dialog":{"box":1}
,"box":{"layout":1}
,"bar":{"layout":1}
}
;Search.control.loadWordPairs(pairs);
