var pairs =
{
"evaluate":{"evaluates":1,"expression":1,"function":1,"recognize":1,"textfield":1,"getfield":1,"let":1,"statetaxformula":1,"get":1}
,"evaluates":{"expression":1,"user-defined":1}
,"expression":{"calculation":1,"[field1":1,"-any":1,"text":1,"including":1}
,"calculation":{"evaluate":1,"update":1,"dependent":1,"if":1,"&\u0022":1,"subtotal":1,"formula":1,"evaluation":1,"total":1,"reevaluated":1,"field":1}
,"[field1":{"field2":1}
,"field2":{".]":1}
,".]":{"expression":1}
,"-any":{"text":1}
,"text":{"expression":1,"field":1,"number":1}
,"field":{"fields":1,"list":1,"isn\u2019t":1,"won\u2019t":1,"10.00":1,"tax":1,"values":1,"dependencies":1,"computes":1,"subtotal":1,"calculation":1,"contents":1,"fieldb":1}
,"fields":{"-a":1,"function":1,"modified":1,"parameter":1,"calculation":1,"record":1}
,"-a":{"list":1}
,"list":{"fields":1,"enclosed":1}
,"function":{"dependent":1,"use":1,"names":1,"returns":1,"evaluates":1,"triggered":1,"optional":1}
,"dependent":{"fields":1,"if":1,"field":1,"dependent":1,"parameter":1}
,"modified":{"calculation":1}
,"update":{"result":1}
,"result":{"parameters":1,"calculation":1}
,"parameters":{"braces":1,"evaluate":1,"allowing":1,"while":1}
,"braces":{"optional":1}
,"optional":{"notice":1,"field":1,"fields":1,"second":1}
,"notice":{"optional":1}
,"enclosed":{"brackets":1}
,"brackets":{"[]":1}
,"[]":{"text":1}
,"number":{"date":1}
,"date":{"time":1}
,"time":{"timestamp":1}
,"timestamp":{"container":1,"calculation":1}
,"container":{"filemaker":1}
,"filemaker":{"pro":1,"server":1,"cloud":1}
,"pro":{"7.0":1,"advanced":1}
,"7.0":{"optional":1}
,"parameter":{"list":1,"second":1,"complex":1,"let":1,"field":1,"cases":1}
,"if":{"field":1,"server-side":1}
,"isn\u2019t":{"listed":1}
,"listed":{"modifying":1}
,"modifying":{"dependent":1}
,"won\u2019t":{"update":1}
,"server-side":{"script":1}
,"script":{"evaluate":1,"running":1}
,"use":{"english":1}
,"english":{"function":1}
,"names":{"evaluate\u2019s":1,"evaluated":1}
,"evaluate\u2019s":{"calculation":1}
,"recognize":{"localized":1}
,"localized":{"function":1}
,"evaluated":{"server-side":1,"calculation":1}
,"running":{"scripts":1}
,"scripts":{"filemaker":1}
,"server":{"filemaker":1}
,"cloud":{"evaluate":1}
,"textfield":{"returns":1,"evaluate":1,"[amount]":1,".08":1}
,"returns":{"textfield":1,".80":1,".50":1,"scriptparameter":1,"12":1}
,"getfield":{"textfield":1}
,"[amount]":{"returns":1}
,".80":{"textfield":1}
,".08":{"*amount":1}
,"*amount":{"field":1}
,"10.00":{"evaluate":1,"pass":1}
,"let":{"taxrate":1,"get":1,"[\u0022":1,"function":1,"[a":1}
,"taxrate":{"=.05":1}
,"=.05":{"&tax":1}
,"&tax":{"rate":1}
,"rate":{"calculation":1}
,"&\u0022":{"returns":1,"&b":1}
,".50":{"field":1}
,"tax":{"rate":1,"evaluate":1,"shipping":1}
,"subtotal":{"*taxrate":1,"numeric":1,"*1.0875":1,"field":1,"tax":1,"evaluate":1,"shippingcost":1}
,"*taxrate":{"subtotal":1}
,"numeric":{"field":1}
,"pass":{"named":1}
,"named":{"parameters":1}
,"get":{"scriptparameter":1,"currenttimestamp":1}
,"scriptparameter":{"functions":1,"=\u0022":1,"&\u0022]":1}
,"functions":{"allowing":1}
,"allowing":{"access":1}
,"access":{"variable":1}
,"variable":{"returns":1,"simplified":1}
,"=\u0022":{"=5":1}
,"=5":{"=10":1}
,"=10":{"evaluate":1,"let":1}
,"[\u0022":{"&get":1}
,"&get":{"scriptparameter":1}
,"&\u0022]":{"pass":1,"&\u005C\u0022":1,"=evaluate":1,")]":1}
,"simplified":{"first":1}
,"first":{"parameter":1}
,"second":{"parameter":1}
,"complex":{"returns":1}
,"12":{"scriptparameter":1}
,"&\u005C\u0022":{"\u005C\u0022":1}
,"\u005C\u0022":{"&b":1}
,"&b":{"pass":1,"evaluate":1}
,"while":{"keeping":1}
,"keeping":{"ability":1}
,"ability":{"check":1}
,"check":{"syntax":1}
,"syntax":{"second":1}
,"[a":{"=evaluate":1}
,"=evaluate":{"let":1}
,")]":{"&\u0022":1}
,"including":{"field":1}
,"values":{"evaluated":1}
,"formula":{"allows":1,"total":1}
,"allows":{"field":1}
,"dependencies":{"calculation":1}
,"evaluation":{"function":1}
,"triggered":{"fields":1}
,"record":{"function":1}
,"user-defined":{"formulas":1}
,"formulas":{"create":1}
,"create":{"formula":1}
,"total":{"field":1,"calculation":1}
,"computes":{"state":1}
,"state":{"tax":1}
,"statetaxformula":{"shippingcost":1,"field":1,"subtotal":1}
,"shippingcost":{"statetaxformula":1,"dependent":1}
,"*1.0875":{"subtotal":1}
,"shipping":{"evaluate":1}
,"contents":{"change":1}
,"change":{"filemaker":1}
,"advanced":{"reevaluates":1}
,"reevaluates":{"calculation":1}
,"reevaluated":{"subtotal":1}
,"cases":{"evaluate":1}
,"currenttimestamp":{"[fieldb":1}
,"[fieldb":{"fieldc":1}
,"fieldc":{"store":1}
,"store":{"timestamp":1}
,"fieldb":{"fieldc":1}
}
;Search.control.loadWordPairs(pairs);
