var pairs =
{
"ln":{"returns":1,"number":1,"function":1,"2.7182818":1,"exp":1}
,"returns":{"base-e":1,".99999998":1}
,"base-e":{"natural":1}
,"natural":{"logarithm":1}
,"logarithm":{"number":1}
,"number":{"ln":1,"number":1,"-any":1,"filemaker":1,"positive":1}
,"-any":{"numeric":1}
,"numeric":{"expression":1}
,"expression":{"field":1,"number":1}
,"field":{"numeric":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"number":1}
,"positive":{"value":1}
,"value":{"negative":1}
,"negative":{"values":1}
,"values":{"return":1}
,"return":{"error":1}
,"error":{"exp":1}
,"exp":{"function":1,"returns":1}
,"function":{"inverse":1,"ln":1}
,"inverse":{"ln":1}
,"2.7182818":{"returns":1}
,".99999998":{"ln":1}
}
;Search.control.loadWordPairs(pairs);
