var pairs =
{
"onrecordload":{"performs":1}
,"performs":{"script":1,"find":1}
,"script":{"fter":1,"switches":1,"want":1,"triggers":1,"trigger":1,"runs":1}
,"fter":{"record":1}
,"record":{"made":1,"performs":1,"activated":1}
,"made":{"current":1}
,"current":{"entered":1}
,"entered":{"user":1}
,"user":{"script":1}
,"switches":{"layout":1,"records":1}
,"layout":{"switches":1}
,"records":{"new":1}
,"new":{"window":1}
,"window":{"creates":1}
,"creates":{"deletes":1}
,"deletes":{"record":1}
,"find":{"operation":1,"modes":1}
,"operation":{"event":1}
,"event":{"processed":1}
,"processed":{"browse":1}
,"browse":{"find":1}
,"modes":{"none":1,"trigger":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"10.0":1,"advanced":1}
,"10.0":{"filemaker":1}
,"advanced":{"pass":1}
,"pass":{"record":1}
,"activated":{"script":1}
,"want":{"use":1}
,"use":{"additional":1}
,"additional":{"script":1}
,"triggers":{"capture":1,"list":1}
,"capture":{"actions":1}
,"actions":{"don\u2019t":1,"activate":1}
,"don\u2019t":{"activate":1}
,"activate":{"script":1}
,"list":{"actions":1}
,"trigger":{"script":1,"result":1}
,"runs":{"modes":1}
}
;Search.control.loadWordPairs(pairs);
