var pairs =
{
"lose":{"window":1}
,"window":{"loses":1,"window":1,"by":1,"closes":1,"name":1,"want":1,"file":1,"logs":1,"go":1,"[current":1,"if":1,"[name":1}
,"loses":{"currently":1}
,"currently":{"active":1}
,"active":{"window":1}
,"by":{"name":1}
,"name":{"current":1,"specifies":1}
,"current":{"window":1,"file":1,"script":1,"web":1}
,"closes":{"active":1,"file":1,"window":1,"current":1,"invoice":1}
,"specifies":{"window":1}
,"want":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"advanced":1,"6.0":1}
,"advanced":{"close":1,"iles":1,"exits":1}
,"close":{"current":1,"window":1}
,"file":{"restricts":1,"selecting":1,"closes":1,"halts":1}
,"restricts":{"matches":1}
,"matches":{"current":1,"all":1}
,"selecting":{"option":1}
,"option":{"matches":1}
,"all":{"filemaker":1}
,"iles":{"filemaker":1}
,"6.0":{"earlier":1}
,"earlier":{"cl":1}
,"cl":{"osing":1}
,"osing":{"last":1}
,"last":{"window":1}
,"halts":{"execution":1}
,"execution":{"current":1}
,"script":{"additionally":1}
,"additionally":{"windows":1}
,"windows":{"filemaker":1,"open":1}
,"exits":{"hen":1}
,"hen":{"windows":1}
,"open":{"hidden":1,"if":1}
,"hidden":{"filemaker":1,"if":1}
,"webdirect":{"closing":1}
,"closing":{"last":1}
,"logs":{"current":1}
,"web":{"session":1}
,"session":{"related":1}
,"related":{"record":1,"records":1}
,"record":{"invoices":1,"[show":1}
,"invoices":{"table":1,"layout":1,"new":1}
,"table":{"print":1,"invoices":1}
,"print":{"invoices":1,"[restore":1}
,"layout":{"prints":1,"rint":1}
,"prints":{"closes":1}
,"go":{"related":1}
,"[show":{"related":1}
,"records":{"table":1}
,"rint":{"invoices":1}
,"new":{"window]":1}
,"window]":{"print":1,"closes":1,"end":1}
,"[restore":{"printer":1}
,"printer":{"dialog":1}
,"dialog":{"off]":1}
,"off]":{"close":1}
,"[current":{"window]":1}
,"if":{"hidden":1,"[get":1,"closes":1,"open":1,"[patterncount":1,"managing":1}
,"[get":{"windowvisible":1}
,"windowvisible":{"=0]":1}
,"=0]":{"close":1}
,"end":{"if":1}
,"invoice":{"details":1}
,"details":{"window":1,")]":1,"\u0022]":1}
,"[patterncount":{"windownames":1}
,"windownames":{"get":1}
,"get":{"filename":1}
,"filename":{"invoice":1}
,")]":{"close":1}
,"[name":{"invoice":1}
,"\u0022]":{"end":1}
,"managing":{"files":1}
,"files":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
