var pairs =
{
"copying":{"moving":1,"field":1}
,"moving":{"fields":1}
,"fields":{"table":1,"tab":1,"if":1,"reference":1,"full":1}
,"table":{"note":1,"paste":1,"file":1,"choose":1,"want":1,"copy":1}
,"note":{"feature":1}
,"feature":{"use":1}
,"use":{"advanced":1}
,"advanced":{"tools":1,"etains":1}
,"tools":{"general":1,"ou":1}
,"general":{"preference":1}
,"preference":{"selected":1}
,"selected":{"ad":1}
,"ad":{"vanced":1}
,"vanced":{"tools":1}
,"ou":{"copy":1}
,"copy":{"fields":1,"copy":1,"multiple":1,"step":1,"time":1,"paste":1,"field":1}
,"paste":{"table":1,"field":1,"filemaker":1,"if":1,"fields":1}
,"file":{"file":1,"ield":1,"menu":1,"table":1}
,"ield":{"data":1}
,"data":{"copied":1,"source":1}
,"copied":{"choose":1}
,"choose":{"file":1,"table":1}
,"menu":{"manage":1}
,"manage":{"database":1}
,"database":{"fields":1}
,"tab":{"select":1,"file":1}
,"select":{"field":1}
,"field":{"want":1,"lick":1,"duplicate":1,"current":1,"pasting":1}
,"want":{"copy":1,"paste":1}
,"lick":{"paste":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"etains":{"data":1}
,"source":{"references":1,"destination":1}
,"references":{"fields":1,"if":1,"lost":1,"pasting":1}
,"if":{"valid":1,"copy":1}
,"valid":{"paste":1,"copy":1}
,"multiple":{"fields":1}
,"reference":{"each":1}
,"each":{"copy":1}
,"step":{"retain":1}
,"retain":{"references":1}
,"time":{"references":1}
,"lost":{"check":1}
,"check":{"all":1}
,"all":{"data":1}
,"pasting":{"ensure":1,"file":1}
,"ensure":{"valid":1}
,"full":{"access":1}
,"access":{"privileges":1}
,"privileges":{"source":1}
,"destination":{"files":1}
,"files":{"difference":1}
,"difference":{"duplicating":1}
,"duplicating":{"copying":1}
,"duplicate":{"duplicates":1}
,"duplicates":{"field":1}
,"current":{"table":1}
}
;Search.control.loadWordPairs(pairs);
