var pairs =
{
"get":{"layouttablen":1,"layouttablename":1,"layout":1,"table":1,"current":1}
,"layouttablen":{"ame":1}
,"ame":{"returns":1}
,"returns":{"name":1,"table":1,"teachers":1,"coaches":1}
,"name":{"table":1,"layout":1,"get":1}
,"table":{"occurrence":1,"occurrences":1,"name":1}
,"occurrence":{"displaying":1,"name":1}
,"displaying":{"records":1}
,"records":{"current":1}
,"current":{"layout":1,"window":1,"table":1}
,"layout":{"get":1,"current":1,"coaches":1,"table":1,"teachers":1,"returns":1}
,"layouttablename":{"none":1,"returns":1,"get":1}
,"none":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"7.0":1}
,"7.0":{"returns":1}
,"window":{"if":1}
,"if":{"windows":1}
,"windows":{"open":1}
,"open":{"empty":1}
,"empty":{"string":1}
,"string":{"returned":1}
,"returned":{"two":1}
,"two":{"layouts":1}
,"layouts":{"teachers":1}
,"teachers":{"layout":1,"coaches":1,"current":1}
,"coaches":{"layout":1,"unstored":1,"current":1}
,"occurrences":{"named":1}
,"named":{"teachers":1}
,"unstored":{"calculation":1}
,"calculation":{"get":1}
}
;Search.control.loadWordPairs(pairs);
