var pairs =
{
"scriptids":{"eturns":1,"filename":1,"customers":1}
,"eturns":{"list":1}
,"list":{"all":1}
,"all":{"script":1}
,"script":{"ids":1}
,"ids":{"filename":1,"customers":1}
,"filename":{"scriptids":1,"filename":1,"-the":1}
,"-the":{"name":1}
,"name":{"open":1}
,"open":{"database":1}
,"database":{"file":1}
,"file":{"local":1}
,"local":{"remote":1}
,"remote":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"listed":1}
,"listed":{"items":1}
,"items":{"separated":1}
,"separated":{"by":1}
,"by":{"carriage":1}
,"carriage":{"returns":1}
,"returns":{"scriptids":1,"list":1}
,"customers":{"returns":1,"database":1}
}
;Search.control.loadWordPairs(pairs);
