var pairs =
{
"defining":{"changing":1,"button":1}
,"changing":{"button":1}
,"button":{"define":1,"add":1,"create":1,"displays":1,"performs":1,"continue":1,"definition":1,"skip":1,"select":1,"layout":1,"status":1,"tool":1,"menu":1,"macos":1,"attach":1,"setup":1,"definitions":1,"positioning":1,"by":1,"type":1,"icon":1,"icons":1,"text":1,"perform":1,"command":1,"action":1,"script":1,"browse":1,"buttons":1,"badge":1,"filemaker":1,"pause":1}
,"define":{"button":1,"new":1,"script":1,"change":1}
,"add":{"text":1}
,"text":{"label":1,"icon":1,"field":1,"center":1,"button":1,"box":1,"bottom":1,"top":1,"right":1,"left":1}
,"label":{"icon":1,"type":1,"text":1,"action":1}
,"icon":{"text":1,"assign":1,"image":1,"choices":1,"drag":1,"choose":1,"list":1,"icon":1,"removed":1,"change":1,"top":1,"bottom":1,"left":1,"right":1,"increased":1,"png":1,"256":1}
,"assign":{"single":1}
,"single":{"command":1,"filemaker":1,"step":1}
,"command":{"script":1,"go":1}
,"script":{"perform":1,"opposed":1,"creating":1,"step":1,"convert":1,"enter":1,"save":1,"script":1,"workspace":1,"full":1,"allowed":1,"choose":1,"dialog":1,"parameter":1,"each":1,"button":1,"if":1,"currently":1,"remains":1,"resumed":1,"runs":1,"exited":1,"called":1,"control":1,"halt":1,"halted":1}
,"perform":{"type":1,"choose":1,"script":1}
,"type":{"button":1,"label":1}
,"create":{"popover":1,"script":1,"new":1,"label":1}
,"popover":{"button":1,"popovers":1,"buttons":1}
,"displays":{"popover":1,"retina":1}
,"popovers":{"layouts":1}
,"layouts":{"if":1}
,"if":{"defining":1,"select":1,"attached":1,"don\u2019t":1,"button":1,"want":1,"current":1,"custom":1}
,"performs":{"script":1}
,"opposed":{"single":1}
,"filemaker":{"pro":1,"go":1}
,"pro":{"advanced":1,"svg":1}
,"advanced":{"ommand":1,"groups":1,"creates":1,"saves":1,"badges":1,"custom":1}
,"ommand":{"create":1}
,"creating":{"editing":1}
,"editing":{"scripts":1}
,"scripts":{"layout":1,"note":1,"script":1,"except":1}
,"layout":{"mode":1,"pop-up":1,"button":1,"create":1,"if":1,"enter":1,"single":1,"objects":1}
,"mode":{"layout":1,"if":1}
,"pop-up":{"menu":1}
,"menu":{"choose":1,"drag":1,"button":1,"show":1}
,"choose":{"layout":1,"button":1,"format":1,"filename":1,"want":1,"action":1,"option":1,"script":1,"view":1,"pause":1}
,"new":{"button":1}
,"continue":{"step":1}
,"step":{"change":1,"create":1,"button":1,"save":1}
,"change":{"button":1,"size":1,"text":1,"appearance":1,"cursor":1}
,"definition":{"double-click":1,"existing":1}
,"double-click":{"button":1}
,"skip":{"step":1}
,"select":{"object":1,"multiple":1,"objects":1,"label":1,"icon":1,"define":1,"run":1,"change":1}
,"object":{"serve":1,"objects":1,"choose":1,"use":1}
,"serve":{"button":1}
,"status":{"toolbar":1}
,"toolbar":{"windows":1}
,"windows":{"arrow":1,"insert":1,"macos":1,"option-double-click":1}
,"arrow":{"next":1,"arrow":1,"choices":1}
,"next":{"button":1}
,"tool":{"button":1,"popover":1,"choose":1}
,"drag":{"crosshair":1,"slider":1}
,"crosshair":{"draw":1}
,"draw":{"button":1}
,"macos":{"hold":1,"svg":1,"filemaker":1,"open":1}
,"hold":{"button":1}
,"attach":{"button":1}
,"existing":{"object":1}
,"objects":{"text":1,"select":1,"previous":1,"define":1,"layout":1,"perform":1}
,"field":{"select":1}
,"format":{"menu":1,"open":1,"icons":1,"icon":1}
,"setup":{"if":1,"dialog":1}
,"multiple":{"objects":1}
,"previous":{"button":1}
,"definitions":{"filemaker":1}
,"groups":{"objects":1}
,"positioning":{"objects":1}
,"attached":{"button":1}
,"use":{"action":1,"custom":1,"removed":1,"complete":1}
,"action":{"button":1,"choose":1,"default":1,"dialog":1,"script":1}
,"dialog":{"box":1}
,"box":{"select":1,"icon":1,"optional":1,"press":1}
,"by":{"default":1,"user\u2019s":1,"badge":1,"badges":1,"script":1,"256":1}
,"default":{"filemaker":1,"choose":1,"paused":1}
,"creates":{"label":1}
,"center":{"aligned":1}
,"aligned":{"create":1}
,"image":{"button":1}
,"choices":{"scroll":1,"change":1,"file":1,"use":1}
,"scroll":{"press":1}
,"press":{"up":1,"alt-double-click":1}
,"up":{"arrow":1}
,"size":{"icon":1,"layout":1,"points":1}
,"slider":{"icon\u0027s":1}
,"icon\u0027s":{"size":1}
,"enter":{"size":1,"name":1}
,"points":{"use":1}
,"custom":{"icon":1,"icons":1}
,"filename":{"png":1}
,"png":{"svg":1,"format":1}
,"svg":{"format":1,"support":1,"grammar":1}
,"open":{"windows":1,"script":1}
,"insert":{"macos":1}
,"support":{"filemaker":1}
,"grammar":{"button":1}
,"icons":{"remove":1,"layout":1,"svg":1,"filemaker":1,"provide":1}
,"remove":{"custom":1}
,"list":{"choices":1,"buttons":1}
,"file":{"select":1}
,"removed":{"list":1,"icon":1}
,"buttons":{"popover":1,"use":1,"identified":1,"if":1}
,"top":{"text":1,"icon":1}
,"bottom":{"button":1}
,"left":{"text":1,"icon":1}
,"right":{"button":1}
,"complete":{"label":1}
,"want":{"button":1,"run":1}
,"option":{"disable":1}
,"disable":{"button":1}
,"go":{"specific":1,"define":1}
,"specific":{"layout":1}
,"save":{"action":1,"windows":1}
,"convert":{"script":1}
,"name":{"script":1}
,"saves":{"script":1}
,"workspace":{"creating":1,"cursor":1}
,"note":{"select":1}
,"run":{"script":1,"sub-scripts":1}
,"full":{"access":1}
,"access":{"privileges":1}
,"privileges":{"allow":1,"defined":1}
,"allow":{"script":1}
,"allowed":{"by":1}
,"user\u2019s":{"assigned":1}
,"assigned":{"privileges":1}
,"defined":{"script":1}
,"optional":{"script":1}
,"parameter":{"hen":1}
,"hen":{"choose":1}
,"each":{"button":1}
,"alt-double-click":{"windows":1}
,"option-double-click":{"macos":1}
,"cursor":{"change":1,"hand":1}
,"appearance":{"button":1}
,"browse":{"find":1}
,"find":{"modes":1}
,"modes":{"under":1}
,"under":{"options":1}
,"options":{"select":1}
,"hand":{"button":1}
,"identified":{"by":1}
,"badge":{"button":1,"layout":1,"choose":1,"obscured":1}
,"don\u2019t":{"badge":1}
,"view":{"menu":1}
,"show":{"buttons":1}
,"badges":{"associated":1,"identifying":1,"icons":1}
,"associated":{"button":1}
,"obscured":{"by":1}
,"identifying":{"badges":1}
,"sub-scripts":{"choose":1}
,"pause":{"resume":1,"default":1}
,"resume":{"exit":1,"paused":1}
,"exit":{"halt":1,"current":1}
,"halt":{"script":1,"execution":1}
,"currently":{"running":1}
,"running":{"user":1}
,"user":{"clicks":1}
,"clicks":{"button":1}
,"paused":{"script":1,"resume":1}
,"remains":{"paused":1}
,"resumed":{"button\u2019s":1}
,"button\u2019s":{"script":1}
,"runs":{"exit":1}
,"current":{"paused":1,"script":1}
,"exited":{"if":1}
,"called":{"by":1}
,"control":{"returns":1}
,"returns":{"original":1}
,"original":{"script":1}
,"execution":{"all":1}
,"all":{"scripts":1}
,"except":{"button\u2019s":1}
,"halted":{"button":1}
,"provide":{"remain":1}
,"remain":{"sharp":1}
,"sharp":{"size":1}
,"increased":{"if":1}
,"256":{"by":1,"pixels":1}
,"pixels":{"high-resolution":1}
,"high-resolution":{"displays":1}
,"retina":{"display":1}
,"display":{"phone":1}
,"phone":{"filemaker":1}
}
;Search.control.loadWordPairs(pairs);
