var pairs =
{
"open":{"data":1,"creating":1,"use":1,"get":1,"time":1,"files":1}
,"data":{"file":1,"file\u2019s":1,"files":1}
,"file":{"data":1,"use":1,"script":1,"path":1,"open":1,"paths":1,"id":1,"position":1,"set":1,"filemaker":1,"read-write":1,"locked":1,"ids":1,"named":1,"[\u0022":1,"displays":1,"exists":1,"[\u0022$file":1,"[file":1}
,"use":{"data":1,"file":1,"close":1,"25":1,"get":1}
,"script":{"steps":1,"step":1,"creates":1}
,"steps":{"source":1,"get":1}
,"source":{"file":1}
,"path":{"data":1}
,"creating":{"file":1}
,"paths":{"target":1}
,"target":{"field":1,"$fileid":1,"$fileexists":1}
,"field":{"variable":1}
,"variable":{"store":1,"doesn\u2019t":1,"open":1,"[$file":1}
,"store":{"data":1}
,"file\u2019s":{"file":1}
,"id":{"if":1,"script":1,"variable":1,"set":1,"&$file":1,"$fileid":1}
,"if":{"variable":1,"file":1,"limit":1,"doesn\u2019t":1,"[not":1,"open":1}
,"doesn\u2019t":{"exist":1,"script":1}
,"exist":{"script":1}
,"step":{"creates":1,"close":1,"if":1}
,"creates":{"sing":1,"file":1}
,"sing":{"variables":1}
,"variables":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"18.0":1,"advanced":1}
,"18.0":{"advanced":1}
,"advanced":{"file":1,"quits":1}
,"get":{"data":1,"lasterror":1,"file":1,"opendatafileinfo":1,"documentspath":1}
,"position":{"read":1,"write":1,"set":1,"script":1}
,"read":{"data":1}
,"set":{"data":1,"variable":1}
,"write":{"data":1}
,"files":{"remain":1,"open":1,"use":1,"automating":1}
,"remain":{"open":1}
,"close":{"data":1,"file":1}
,"quits":{"file":1}
,"read-write":{"position":1}
,"lasterror":{"returns":1}
,"returns":{"300":1,"memory":1}
,"300":{"file":1}
,"locked":{"use":1}
,"25":{"data":1}
,"time":{"if":1}
,"limit":{"exceeded":1}
,"exceeded":{"get":1}
,"memory":{"error":1}
,"error":{"get":1}
,"ids":{"all":1}
,"all":{"currently":1}
,"currently":{"open":1}
,"opendatafileinfo":{"function":1}
,"function":{"data":1}
,"named":{"data.txt":1,"change.log":1}
,"data.txt":{"stores":1,"target":1}
,"stores":{"file":1}
,"[\u0022":{"data.txt":1,"file":1}
,"$fileid":{"checks":1,"show":1,"managing":1}
,"checks":{"file":1}
,"change.log":{"exists":1,"get":1}
,"exists":{"documents":1,"[\u0022$file":1}
,"documents":{"folder":1}
,"folder":{"if":1}
,"displays":{"file":1}
,"[$file":{"value":1}
,"value":{"get":1}
,"documentspath":{"&\u0022":1}
,"&\u0022":{"change.log":1,"&$fileid":1}
,"[\u0022$file":{"target":1,"create":1}
,"$fileexists":{"if":1,"create":1}
,"[not":{"$fileexists":1}
,"create":{"data":1,"folders":1}
,"folders":{"end":1}
,"end":{"if":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"dialog":{"[\u0022":1}
,"&$file":{"&\u0022":1}
,"&$fileid":{"close":1}
,"[file":{"id":1}
,"managing":{"files":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
