var pairs =
{
"copy":{"record\u002Frequest":1,"edit":1,"clipboard":1,"records":1}
,"record\u002Frequest":{"opies":1,"step":1,"show":1}
,"opies":{"values":1}
,"values":{"record":1}
,"record":{"find":1,"layout":1,"displays":1,"spreadsheet":1}
,"find":{"request":1}
,"request":{"clipboard":1}
,"clipboard":{"none":1,"accessible":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1,"advanced":1}
,"6.0":{"earlier":1}
,"earlier":{"text":1}
,"text":{"fields":1,"container":1,"editor":1}
,"fields":{"copied":1,"filemaker":1,"located":1}
,"copied":{"tab-delimited":1,"script":1}
,"tab-delimited":{"format":1}
,"format":{"styles":1}
,"styles":{"order":1}
,"order":{"record":1}
,"layout":{"text":1}
,"container":{"fields":1}
,"script":{"step":1}
,"step":{"equivalent":1,"repeating":1}
,"equivalent":{"choosing":1}
,"choosing":{"copy":1}
,"edit":{"menu":1}
,"menu":{"active":1}
,"active":{"field":1}
,"field":{"contents":1}
,"contents":{"cut":1,"current":1}
,"cut":{"copy":1}
,"accessible":{"applications":1}
,"applications":{"copy":1}
,"repeating":{"fields":1}
,"advanced":{"inserts":1}
,"inserts":{"group":1}
,"group":{"separator":1}
,"separator":{"character":1}
,"character":{"each":1}
,"each":{"repetition":1}
,"repetition":{"use":1}
,"use":{"text":1}
,"editor":{"replace":1}
,"replace":{"characters":1}
,"characters":{"delimiter":1}
,"delimiter":{"tab":1}
,"tab":{"space":1}
,"space":{"fields":1}
,"located":{"popovers":1}
,"popovers":{"ignored":1}
,"ignored":{"copy":1}
,"records":{"copies":1,"automating":1}
,"copies":{"contents":1}
,"current":{"record":1}
,"displays":{"custom":1}
,"custom":{"dialog":1}
,"dialog":{"box":1,"[\u0022":1}
,"box":{"copy":1}
,"show":{"custom":1}
,"[\u0022":{"paste":1}
,"paste":{"current":1}
,"spreadsheet":{"software":1}
,"software":{"\u0022]":1}
,"\u0022]":{"opying":1}
,"opying":{"moving":1}
,"moving":{"data":1}
,"data":{"records":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
