var pairs =
{
"set":{"tin":1,"send":1,"if":1,"advanced":1}
,"tin":{"advanced":1}
,"advanced":{"file":1,"default":1,"ru":1,"options":1,"displays":1,"recovery":1,"generate":1,"update":1,"creates":1}
,"file":{"recovery":1,"change":1,"note":1,"menu":1,"recover":1,"ialog":1,"select":1,"blocks":1,"include":1,"scan":1,"drop":1,"new":1,"generated":1,"option":1,"matches":1,"predefined":1,"import":1,"scripts":1,"options":1,"during":1,"if":1}
,"recovery":{"options":1,"features":1,"indexes":1,"process":1,"settings":1}
,"options":{"filemaker":1,"dialog":1,"selected":1,"select":1,"define":1,"saved":1,"onfirstwindowopen":1,"bypass":1,"set":1,"deselected":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"default":{"settings":1,"recovery":1,"copy":1,"scan":1,"file":1}
,"settings":{"recovers":1,"attempt":1,"made":1,"remove":1,"including":1,"layout":1,"next":1,"keep":1,"deselect":1,"switch":1,"restored":1}
,"recovers":{"file":1}
,"change":{"settings":1,"file":1}
,"attempt":{"recover":1}
,"recover":{"damaged":1,"select":1,"file":1}
,"damaged":{"file":1,"blocks":1,"admin":1}
,"note":{"filemaker":1,"scanning":1}
,"ru":{"ntime":1}
,"ntime":{"applications":1}
,"applications":{"support":1}
,"support":{"advanced":1}
,"features":{"choose":1}
,"choose":{"file":1}
,"menu":{"recover":1}
,"select":{"file":1,"ame":1,"use":1,"option":1,"default":1,"next":1,"additional":1,"rebuild":1,"copy":1}
,"ame":{"new":1}
,"new":{"recovered":1,"file":1,"database":1}
,"recovered":{"file":1,"bypass":1}
,"ialog":{"box":1}
,"box":{"select":1,"default":1,"displayed":1,"change":1,"revert":1}
,"use":{"advanced":1,"settings":1}
,"displays":{"advanced":1}
,"dialog":{"box":1,"boxes":1}
,"selected":{"if":1,"ame":1,"bypass":1}
,"if":{"first":1,"fields":1,"locale":1,"conditions":1,"change":1,"return":1}
,"first":{"time":1}
,"time":{"dialog":1,"it\u2019s":1,"recover":1}
,"displayed":{"during":1}
,"during":{"current":1,"file":1,"application":1}
,"current":{"application":1}
,"application":{"launch":1}
,"launch":{"recent":1,"select":1,"keep":1}
,"recent":{"settings":1,"sorts":1,"finds":1}
,"made":{"during":1}
,"option":{"want":1,"forces":1,"re-creates":1,"find":1,"prompts":1}
,"want":{"filemaker":1,"bypass":1}
,"generate":{"new":1}
,"copy":{"file":1,"all":1,"logical":1,"copy":1}
,"blocks":{"as-is":1,"recovered":1,"copy":1,"rebuild":1,"include":1}
,"as-is":{"copy":1,"nd":1}
,"all":{"file":1,"original":1,"records":1}
,"include":{"damaged":1,"undamaged":1}
,"logical":{"structure":1}
,"structure":{"compacted":1,"recovered":1,"if":1}
,"compacted":{"copy":1}
,"original":{"data":1}
,"data":{"checking":1,"rebuild":1,"scanned":1,"take":1}
,"checking":{"blocks":1}
,"rebuild":{"tree":1,"file":1,"new":1,"fields":1,"file\u2019s":1,"scripts":1,"field":1}
,"tree":{"structure":1}
,"scan":{"blocks":1,"rebuild":1,"record":1}
,"drop":{"invalid":1}
,"invalid":{"blocks":1,"locations":1}
,"undamaged":{"non-duplicate":1}
,"non-duplicate":{"blocks":1}
,"generated":{"scanned":1,"select":1}
,"scanned":{"new":1,"note":1}
,"database":{"rebuilt":1,"new":1,"use":1}
,"rebuilt":{"options":1}
,"next":{"step":1,"time":1}
,"step":{"select":1}
,"additional":{"options":1}
,"define":{"scan":1}
,"record":{"data":1}
,"fields":{"tables":1,"records":1}
,"tables":{"rebuild":1}
,"file\u2019s":{"schema":1,"structure":1}
,"schema":{"option":1}
,"forces":{"all":1}
,"records":{"field":1,"invalid":1}
,"field":{"data":1,"table":1,"indexes":1}
,"scanning":{"all":1}
,"take":{"time":1}
,"it\u2019s":{"option":1}
,"re-creates":{"missing":1}
,"missing":{"field":1,"runtime":1}
,"table":{"definitions":1,"file":1}
,"definitions":{"if":1}
,"locations":{"file":1}
,"find":{"remove":1}
,"remove":{"scan":1,"settings":1}
,"scripts":{"layouts":1,"created":1}
,"layouts":{"rebuild":1,"file":1}
,"locale":{"themes":1}
,"themes":{"stored":1,"disk":1,"custom":1,"based":1,"updated":1}
,"stored":{"file":1}
,"matches":{"installed":1}
,"installed":{"themes":1}
,"disk":{"filemaker":1}
,"update":{"version":1}
,"version":{"version":1,"themes":1,"file":1}
,"predefined":{"themes":1}
,"custom":{"themes":1}
,"based":{"predefined":1}
,"updated":{"rebuild":1}
,"indexes":{"select":1,"during":1,"delete":1}
,"delete":{"cached":1}
,"cached":{"settings":1}
,"including":{"page":1}
,"page":{"format":1}
,"format":{"print":1}
,"print":{"settings":1}
,"layout":{"formatting":1,"bypass":1,"file":1,"selected":1,"open":1,"leave":1}
,"formatting":{"defaults":1}
,"defaults":{"table":1}
,"import":{"export":1}
,"export":{"order":1}
,"order":{"recent":1}
,"sorts":{"recent":1}
,"finds":{"last":1,"recovered":1}
,"last":{"found":1}
,"found":{"set":1}
,"send":{"mail":1}
,"mail":{"options":1}
,"saved":{"finds":1}
,"bypass":{"startup":1,"scripts":1,"allowed":1,"layout":1}
,"startup":{"script":1}
,"script":{"layout":1,"triggers":1,"bypasses":1}
,"created":{"file":1}
,"onfirstwindowopen":{"onwindowopen":1}
,"onwindowopen":{"script":1}
,"triggers":{"disabled":1}
,"disabled":{"filemaker":1}
,"creates":{"blank":1}
,"blank":{"layout":1}
,"prompts":{"end":1}
,"end":{"recovery":1}
,"process":{"enter":1}
,"enter":{"account":1}
,"account":{"password":1,"missing":1}
,"password":{"full":1}
,"full":{"access":1}
,"access":{"database":1}
,"keep":{"use":1}
,"revert":{"filemaker":1}
,"deselect":{"use":1}
,"allowed":{"if":1}
,"conditions":{"exist":1}
,"exist":{"user":1}
,"user":{"fails":1}
,"fails":{"attempts":1}
,"attempts":{"log":1}
,"log":{"accounts":1}
,"accounts":{"catalog":1}
,"catalog":{"damaged":1}
,"admin":{"account":1}
,"runtime":{"version":1}
,"switch":{"script":1}
,"bypasses":{"dialog":1}
,"boxes":{"filemaker":1,"changed":1}
,"return":{"recovering":1}
,"recovering":{"files":1}
,"files":{"dialog":1}
,"changed":{"settings":1}
,"restored":{"want":1}
,"open":{"file":1}
,"nd":{"bypass":1}
,"leave":{"options":1}
,"deselected":{"set":1}
}
;Search.control.loadWordPairs(pairs);
