var pairs =
{
"encrypting":{"database":1}
,"database":{"file":1,"files":1,"encryption":1,"solution":1}
,"file":{"note":1,"protects":1,"copied":1,"warning":1,"if":1,"attempts":1,"filemaker":1,"load":1,"files":1,"rename":1,"type":1,"saving":1,"account":1,"encryption":1,"encrypted":1,"records":1,"format":1,"change":1}
,"note":{"feature":1,"change":1,"encryption":1}
,"feature":{"use":1}
,"use":{"advanced":1}
,"advanced":{"tools":1,"isplays":1,"ses":1}
,"tools":{"general":1,"ncryption":1,"menu":1}
,"general":{"preference":1}
,"preference":{"selected":1}
,"selected":{"ad":1,"files":1}
,"ad":{"vanced":1}
,"vanced":{"tools":1}
,"ncryption":{"protects":1}
,"protects":{"filemaker":1,"data":1}
,"filemaker":{"database":1,"pro":1,"account":1,"file":1}
,"files":{"unauthorized":1,"stored":1,"decrypted":1,"encryption":1,"encrypt":1,"want":1,"multi":1,"10":1,"select":1,"etting":1,"password":1,"note":1,"encrypted":1,"created":1,"solution":1}
,"unauthorized":{"access":1}
,"access":{"while":1,"change":1,"encrypted":1,"privileges":1}
,"while":{"files":1}
,"stored":{"disk":1,"externally":1}
,"disk":{"encrypted":1}
,"encrypted":{"files":1,"database":1,"file":1,"solution":1,"copy":1,"create":1,"add":1,"multi":1,"export":1}
,"decrypted":{"create":1}
,"create":{"encryption":1,"close":1,"temporary":1}
,"encryption":{"password":1,"passwords":1,"re-encrypt":1}
,"password":{"file":1,"re-encrypt":1,"assign":1,"access":1,"shared":1,"dialog":1,"account":1,"14":1,"password":1,"hint":1,"case":1,"change":1,"text":1,"database":1,"encrypted":1}
,"data":{"if":1,"stored":1,"encrypt":1,"externally":1}
,"if":{"file":1,"write":1,"lose":1,"multifile":1,"files":1,"developer":1,"want":1,"selected":1}
,"copied":{"stolen":1}
,"stolen":{"change":1}
,"change":{"file\u2019s":1,"file":1,"quickly":1,"secure":1,"follow":1,"password":1}
,"file\u2019s":{"encryption":1}
,"re-encrypt":{"file":1,"files":1}
,"warning":{"encryption":1}
,"passwords":{"recovered":1,"shared":1}
,"recovered":{"forget":1}
,"forget":{"encryption":1}
,"assign":{"encrypted":1}
,"write":{"store":1}
,"store":{"secure":1,"data":1}
,"secure":{"place":1,"storage":1,"open":1}
,"place":{"if":1}
,"lose":{"forget":1}
,"multifile":{"solution":1}
,"solution":{"encrypt":1,"saved":1,"all":1,"rename":1,"setting":1,"options":1,"export":1}
,"encrypt":{"all":1,"choose":1,"add":1,"files":1,"container":1,"database":1,"file":1,"new":1}
,"all":{"database":1,"time":1,"encrypted":1}
,"shared":{"id":1,"ids":1}
,"id":{"encrypted":1,"type":1,"case":1,"11":1,"database":1}
,"attempts":{"access":1}
,"pro":{"advanced":1}
,"isplays":{"database":1}
,"dialog":{"box":1}
,"box":{"if":1,"select":1,"bottom":1,"enter":1,"visible":1}
,"ids":{"match":1}
,"match":{"close":1}
,"close":{"all":1}
,"choose":{"tools":1,"location":1,"folder":1}
,"menu":{"developer":1}
,"developer":{"utilities":1}
,"utilities":{"if":1,"database":1}
,"saved":{"settings":1}
,"settings":{"load":1,"locate":1,"choose":1,"file":1}
,"load":{"settings":1,"add":1}
,"locate":{"select":1}
,"select":{".sav":1,"file":1,"enable":1,"keep":1}
,".sav":{"file":1}
,"add":{"select":1,"encrypt":1,"new":1}
,"want":{"encrypt":1}
,"multi":{"ile":1}
,"ile":{"solution":1,"solutions":1}
,"time":{"project":1}
,"project":{"folder":1}
,"folder":{"choose":1,"location":1}
,"location":{"encrypted":1,"settings":1}
,"rename":{"encrypted":1,"file":1}
,"copy":{"file":1}
,"type":{"filename":1,"combination":1,"encryption":1}
,"filename":{"change":1}
,"quickly":{"repeat":1}
,"repeat":{"process":1}
,"process":{"save":1}
,"save":{"settings":1}
,"saving":{"solution":1}
,"setting":{"solution":1}
,"options":{"solution":1,"dialog":1}
,"enable":{"database":1}
,"10":{"shared":1}
,"combination":{"uppercase":1}
,"uppercase":{"lowercase":1}
,"lowercase":{"characters":1}
,"characters":{"numbers":1,"shared":1}
,"numbers":{"symbols":1}
,"symbols":{"32":1}
,"32":{"characters":1}
,"case":{"sensitive":1}
,"sensitive":{"encrypted":1,"15":1}
,"solutions":{"linked":1}
,"linked":{"by":1}
,"by":{"shared":1,"default":1,"encrypted":1}
,"11":{"filemaker":1}
,"account":{"12":1,"name":1,"full":1}
,"12":{"enter":1}
,"enter":{"filemaker":1,"current":1}
,"name":{"password":1}
,"full":{"access":1}
,"privileges":{"13":1}
,"13":{"encryption":1}
,"14":{"type":1}
,"hint":{"files":1}
,"15":{"by":1}
,"default":{"filemaker":1}
,"ses":{"secure":1}
,"storage":{"encrypt":1,"note":1,"container":1}
,"container":{"data":1,"fields":1}
,"externally":{"if":1,"encrypt":1,"16":1}
,"keep":{"open":1}
,"open":{"storage":1}
,"etting":{"up":1}
,"up":{"container":1}
,"fields":{"store":1}
,"16":{"create":1}
,"follow":{"steps":1}
,"steps":{"2-15":1}
,"2-15":{"encrypt":1}
,"text":{"box":1}
,"bottom":{"solution":1}
,"current":{"encryption":1}
,"visible":{"if":1}
,"temporary":{"files":1}
,"created":{"by":1}
,"new":{"database":1,"file":1}
,"export":{"records":1,"file":1}
,"records":{"encrypted":1,"exported":1}
,"exported":{"file":1}
,"format":{"encrypt":1}
}
;Search.control.loadWordPairs(pairs);
