var pairs =
{
"istributing":{"runtime":1}
,"runtime":{"solution":1,"database":1,"application":1,"solutions":1,"installer":1}
,"solution":{"note":1,"bundle":1,"media":1,"addition":1,"organize":1,"components":1,"files":1,"folder":1,"delete":1,"open":1,"control-click":1,"reduce":1,"windows":1,"macos":1}
,"note":{"feature":1}
,"feature":{"use":1}
,"use":{"advanced":1,"custom":1,"installer":1}
,"advanced":{"tools":1,"pplication":1,"technical":1}
,"tools":{"general":1,"final":1}
,"general":{"preference":1}
,"preference":{"selected":1}
,"selected":{"ad":1}
,"ad":{"vanced":1}
,"vanced":{"tools":1}
,"final":{"steps":1}
,"steps":{"developing":1}
,"developing":{"runtime":1}
,"database":{"solution":1,"reduce":1}
,"bundle":{"all":1}
,"all":{"files":1}
,"files":{"choose":1,"folders":1,"software":1,"deleting":1,"languages":1,"location":1}
,"choose":{"distribute":1,"distribution":1,"use":1,"show":1}
,"distribute":{"solution":1}
,"media":{"network":1}
,"network":{"provide":1,"downloads":1,"access":1}
,"provide":{"users":1,"uninstall":1}
,"users":{"documentation":1}
,"documentation":{"installing":1,"include":1}
,"installing":{"solution":1}
,"addition":{"documentation":1}
,"include":{"instructions":1,"minimum":1,"required":1}
,"instructions":{"starting":1}
,"starting":{"runtime":1}
,"application":{"if":1,"windows":1,"package":1}
,"if":{"file":1,"filemaker":1}
,"file":{"damaged":1}
,"damaged":{"distribute":1}
,"organize":{"solution":1}
,"components":{"rename":1,"proper":1}
,"rename":{"files":1}
,"folders":{"developer":1,"languages":1,"(*.lproj":1}
,"developer":{"utilities":1}
,"utilities":{"generates":1}
,"generates":{"choose":1}
,"distribution":{"method":1}
,"method":{"choose":1,"distributing":1}
,"custom":{"installation":1}
,"installation":{"program":1}
,"program":{"compression":1,"software":1}
,"compression":{"utility":1}
,"utility":{"program":1}
,"software":{"distributions":1,"software":1,"install":1,"required":1}
,"distributions":{"internet":1,"reducing":1}
,"internet":{"network":1}
,"downloads":{"ensure":1}
,"ensure":{"master":1}
,"master":{"password":1}
,"password":{"enable":1}
,"enable":{"change":1}
,"change":{"network":1}
,"access":{"files":1}
,"reducing":{"size":1}
,"size":{"solution":1,"application":1}
,"deleting":{"dictionaries":1}
,"dictionaries":{"language":1,"folder":1,"languages":1}
,"language":{"resource":1}
,"resource":{"files":1,"folders":1,"folder":1}
,"languages":{"supported":1}
,"supported":{"by":1}
,"by":{"database":1,"filemaker":1,"solution":1}
,"reduce":{"size":1}
,"windows":{"proper":1,"filesystem":1,"runtime":1,"require":1,"include":1,"reduce":1}
,"proper":{"method":1,"location":1}
,"distributing":{"runtime":1}
,"solutions":{"including":1,"windows":1}
,"including":{"executable":1}
,"executable":{"use":1}
,"installer":{"software":1,"install":1}
,"install":{"components":1,"required":1}
,"location":{"windows":1,"installed":1,"restrictions":1}
,"filesystem":{"provide":1}
,"uninstall":{"capability":1}
,"capability":{"website":1}
,"website":{"location":1}
,"installed":{"files":1,"versions":1}
,"restrictions":{"include":1}
,"minimum":{"equipment":1}
,"equipment":{"software":1}
,"required":{"by":1,"version":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"pplication":{"windows":1}
,"require":{".net":1}
,".net":{"framework":1,"therefore":1,"if":1}
,"framework":{"installed":1}
,"versions":{"windows":1}
,"version":{".net":1}
,"therefore":{"runtime":1}
,"technical":{"specifications":1}
,"specifications":{"open":1}
,"open":{"extensions":1,"dictionaries":1}
,"extensions":{"folder":1}
,"folder":{"copied":1,"delete":1,"english":1,"open":1,"contents":1}
,"copied":{"runtime":1}
,"delete":{"language":1,"dictionaries":1}
,"english":{"open":1}
,"control-click":{"runtime":1}
,"package":{"choose":1,"contents":1}
,"show":{"package":1}
,"contents":{"locate":1,"folder":1}
,"locate":{"resources":1}
,"resources":{"folder":1}
,"(*.lproj":{"languages":1}
}
;Search.control.loadWordPairs(pairs);
