var pairs =
{
"halt":{"script":1,"unanticipated":1}
,"script":{"orces":1,"leave":1,"halt":1,"perform":1,"end":1,"calls":1,"sub-script":1,"[specified":1,"print":1}
,"orces":{"all":1}
,"all":{"scripts":1,"records":1}
,"scripts":{"sub-scripts":1,"running":1,"main":1}
,"sub-scripts":{"external":1}
,"external":{"scripts":1}
,"running":{"current":1}
,"current":{"filemaker":1}
,"filemaker":{"application":1,"pro":1}
,"application":{"stop":1}
,"stop":{"none":1,"if":1}
,"none":{"filemaker":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"halt":1}
,"leave":{"database":1}
,"database":{"unpredictable":1}
,"unpredictable":{"state":1}
,"state":{"script":1}
,"unanticipated":{"layout":1}
,"layout":{"view":1,"print":1}
,"view":{"mode":1}
,"mode":{"performs":1}
,"performs":{"find":1}
,"find":{"prints":1,"[restore]":1,"criteria":1}
,"prints":{"if":1}
,"if":{"records":1,"[get":1,"print":1,"user":1,"automating":1}
,"records":{"found":1,"halts":1,"halt":1,"displayed":1,"sort":1,"[restore":1}
,"found":{"displays":1}
,"displays":{"all":1}
,"halts":{"script":1,"sub-script":1}
,"perform":{"find":1,"script":1}
,"[restore]":{"if":1,"calls":1}
,"[get":{"foundcount":1,"lastmessagechoice":1}
,"foundcount":{"=0]":1}
,"=0]":{"show":1}
,"show":{"all":1,"custom":1}
,"end":{"if":1}
,"print":{"[with":1,"unpaid":1,"sub-script":1,"invoices":1,"parameter":1}
,"[with":{"dialog":1}
,"dialog":{"off]":1,"[\u0022":1}
,"off]":{"print":1,"show":1,"else":1}
,"unpaid":{"invoices":1}
,"invoices":{"script":1,"unpaid":1,"match":1,"invoices":1,")]":1,"show":1,"want":1,"\u0022]":1,"sub-script":1}
,"calls":{"print":1}
,"sub-script":{"if":1,"stop":1,"defined":1,"completed":1,"main":1,"print":1}
,"user":{"chooses":1,"chose":1}
,"chooses":{"print":1}
,"match":{"find":1}
,"criteria":{"printed":1}
,"printed":{"printing":1}
,"printing":{"all":1}
,"displayed":{"sorted":1}
,"sorted":{"new":1}
,"new":{"window":1}
,"window":{"[style":1,"[current":1}
,"[style":{"document":1}
,"document":{"name":1}
,"name":{"invoice":1}
,"invoice":{"list":1}
,"list":{"layout":1,"print":1}
,")]":{"perform":1}
,"defined":{"perform":1}
,"[specified":{"list":1}
,"parameter":{"continues":1}
,"continues":{"sub-script":1}
,"completed":{"if":1}
,"chose":{"print":1}
,"sort":{"records":1}
,"[restore":{"dialog":1}
,"custom":{"dialog":1}
,"[\u0022":{"print":1}
,"want":{"print":1}
,"\u0022]":{"if":1}
,"lastmessagechoice":{"=1]":1}
,"=1]":{"print":1}
,"else":{"close":1}
,"close":{"window":1}
,"[current":{"window]":1}
,"window]":{"halts":1}
,"main":{"script":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
