var pairs =
{
"get":{"currentdat":1,"currentdate":1,"current":1,"system":1,"date":1,"day":1}
,"currentdat":{"returns":1}
,"returns":{"current":1,"2\u002F2\u002F2019":1,"system":1}
,"current":{"date":1,"layout":1,"day":1}
,"date":{"system":1,"filemaker":1,"format":1,"time":1,"set":1,"get":1}
,"system":{"calendar":1,"if":1,"date":1}
,"calendar":{"get":1}
,"currentdate":{"none":1,"-date":1,"get":1}
,"none":{"date":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"format":1}
,"format":{"result":1,"use":1,"mm\u002Fdd\u002Fyyyy":1,"field":1}
,"result":{"function":1,"displayed":1}
,"function":{"varies":1}
,"varies":{"based":1}
,"based":{"date":1}
,"use":{"database":1}
,"database":{"file":1}
,"file":{"created":1}
,"created":{"united":1}
,"united":{"states":1}
,"states":{"dates":1}
,"dates":{"format":1}
,"mm\u002Fdd\u002Fyyyy":{"change":1}
,"change":{"date":1}
,"time":{"formats":1}
,"formats":{"operating":1}
,"operating":{"system":1}
,"if":{"result":1}
,"displayed":{"field":1}
,"field":{"formatted":1,"current":1}
,"formatted":{"date":1}
,"layout":{"returns":1}
,"2\u002F2\u002F2019":{"system":1}
,"set":{"february":1,"january":1}
,"february":{"2019":1}
,"2019":{"get":1,"returns":1,"script":1}
,"-date":{"2019":1}
,"january":{"2019":1}
,"script":{"exit":1,"step":1}
,"exit":{"application":1}
,"application":{"script":1}
,"step":{"get":1}
,"day":{"get":1,"current":1}
}
;Search.control.loadWordPairs(pairs);
