var pairs =
{
"filemaker":{"id":1,"cloud":1}
,"id":{"filemaker":1,"integrated":1,"user":1,"account":1}
,"integrated":{"sign-on":1}
,"sign-on":{"system":1}
,"system":{"allows":1}
,"allows":{"files":1}
,"files":{"hosted":1}
,"hosted":{"by":1}
,"by":{"filemaker":1}
,"cloud":{"sign":1}
,"sign":{"filemaker":1}
,"user":{"name":1}
,"name":{"password":1}
,"password":{"if":1}
,"if":{"filemaker":1}
,"account":{"create":1}
}
;Search.control.loadWordPairs(pairs);
