var pairs =
{
"ode":{"keyboard":1}
,"keyboard":{"shortcuts":1}
,"shortcuts":{"mac":1,"filemaker":1,"browse":1,"go":1,"move":1,"find":1,"arrange":1,"layout":1,"object":1,"inspector":1,"fields":1,"bjects":1,"ayout":1}
,"mac":{"os":1}
,"os":{"use":1}
,"use":{"keyboard":1,"eyboard":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"odes":1}
,"odes":{"switch":1}
,"switch":{"press":1}
,"press":{"browse":1,"create":1,"ente":1,"select\u002Fdeselect":1,"enter":1,"select":1,"command":1,"align":1,"bring":1,"show":1,"open":1,"toggle":1}
,"browse":{"mode":1}
,"mode":{"command":1,"create":1,"se":1,"keyboard":1}
,"command":{"-b":1,"-f":1,"-l":1,"-u":1,"-n":1,"-d":1,"-e":1,"-option-e":1,"-r":1,"-j":1,"-s":1,"-t":1,"-shift-t":1,"-p":1,"-option-p":1,"-shift-r":1,"-option-f":1,"-=use":1,"-i":1,"drag":1,"-1":1,"-option-c":1,"-option-v":1,"-option-left":1,"-option-right":1,"-option-up":1,"-option-down":1,"-option-shift-r":1,"-option-y":1,"-option-shift-y":1,"-option-":1,"-option-shift-":1,"-shift-[bring":1,"-option-[change":1,"label":1,"-option-l":1,"-option-r":1,"-shift-]":1,"-option-]":1,"-shift-option-l":1,"-2":1,"-3":1,"-4":1,"-k":1,"-return":1,"-enter":1,"-option-t":1}
,"-b":{"find":1}
,"find":{"mode":1,"command":1,"box":1,"requests":1,"request":1}
,"-f":{"layout":1}
,"layout":{"mode":1,"tools":1,"command":1,"navigation":1,"esc":1,"number":1,"tab":1,"part":1,"creation":1}
,"-l":{"preview":1}
,"preview":{"mode":1}
,"-u":{"use":1}
,"eyboard":{"shortcuts":1}
,"create":{"delete":1,"record":1,"duplicate":1,"find":1,"layouts":1,"new":1}
,"delete":{"duplicate":1,"record":1,"find":1}
,"duplicate":{"omit":1,"record":1,"find":1,"selected":1,"object":1}
,"omit":{"sort":1,"record":1,"multiple":1}
,"sort":{"print":1,"records":1}
,"print":{"records":1}
,"records":{"press":1,"command":1,"dialog":1}
,"record":{"command":1,"confirmation":1,"navigation":1,"esc":1,"number":1}
,"-n":{"duplicate":1,"delete":1,"go":1}
,"-d":{"delete":1,"show":1,"duplicate":1}
,"-e":{"delete":1,"duplicate":1}
,"confirmation":{"command":1}
,"-option-e":{"modify":1}
,"modify":{"last":1}
,"last":{"find":1}
,"-r":{"show":1,"lock":1}
,"show":{"all":1,"hide":1}
,"all":{"record":1,"records":1}
,"-j":{"sort":1,"perform":1}
,"-s":{"go":1}
,"go":{"next":1,"previous":1}
,"next":{"record":1,"find":1,"layout":1}
,"navigation":{"keyboard":1,"object":1}
,"previous":{"record":1,"find":1,"layout":1}
,"move":{"specific":1,"next":1,"previous":1,"position":1,"selected":1,"object":1}
,"specific":{"record":1,"find":1,"layout":1}
,"esc":{"activate":1,"open":1}
,"activate":{"current":1,"quick":1}
,"current":{"record":1,"request":1,"layout":1,"tool":1}
,"number":{"box":1,"press":1}
,"box":{"type":1,"command":1,"field":1,"includes":1,"completely":1,"press":1}
,"type":{"record":1,"request":1,"layout":1,"ize":1}
,"ente":{"omit":1}
,"-t":{"omit":1,"create":1}
,"multiple":{"records":1,"objects":1}
,"-shift-t":{"open":1}
,"open":{"close":1,"replace":1,"field":1}
,"close":{"drop-down":1,"pop-up":1}
,"drop-down":{"list":1}
,"list":{"alendar":1}
,"alendar":{"active":1}
,"active":{"field":1}
,"field":{"esc":1,"space":1,"contents":1,"selected":1,"tab":1,"field":1,"return":1}
,"pop-up":{"menu":1}
,"menu":{"active":1}
,"space":{"bar":1}
,"bar":{"print":1}
,"-p":{"print":1}
,"dialog":{"box":1}
,"-option-p":{"refresh":1}
,"refresh":{"window":1}
,"window":{"command":1}
,"-shift-r":{"activate":1,"unlock":1}
,"quick":{"find":1}
,"-option-f":{"open":1}
,"replace":{"field":1}
,"contents":{"dialog":1}
,"selected":{"command":1,"select":1,"object":1,"objects":1,"layout":1,"part":1,"field":1}
,"-=use":{"eyboard":1}
,"requests":{"press":1}
,"select\u002Fdeselect":{"mit":1}
,"mit":{"button":1}
,"button":{"command":1}
,"request":{"command":1,"enter":1,"navigation":1,"esc":1,"number":1}
,"perform":{"find":1}
,"enter":{"disabled":1,"layout":1,"press":1,"shift-enter":1}
,"disabled":{"script":1}
,"script":{"paused":1}
,"paused":{"paste":1}
,"paste":{"index":1,"style":1}
,"index":{"command":1}
,"-i":{"move":1,"display":1}
,"se":{"keyboard":1}
,"arrange":{"align":1}
,"align":{"objects":1,"left":1,"right":1,"top":1,"bottom":1}
,"objects":{"format":1,"shift":1,"selection":1,"select":1,"enclosed":1,"keeping":1,"remain":1,"copy":1,"grid":1,"command":1,"guides":1}
,"format":{"fields":1}
,"fields":{"ontrol":1,"tab":1}
,"ontrol":{"layout":1}
,"tools":{"create":1,"keyboard":1}
,"layouts":{"press":1}
,"new":{"layout":1,"field":1}
,"select":{"object":1,"multiple":1,"objects":1}
,"object":{"layout":1,"selected":1,"individually":1,"inspector":1,"command":1,"grid":1,"toggle":1,"forward":1,"front":1,"option":1,"by":1,"group":1,"point":1,"10":1,"backward":1,"back":1,"horizontally":1,"draw":1,"square":1,"browse":1,"selection":1,"alignment":1,"arrangement":1}
,"tab":{"shift-tab":1,"command":1,"layout":1,"eyboard":1}
,"shift-tab":{"repeatedly":1}
,"repeatedly":{"desired":1}
,"desired":{"object":1,"sizing":1}
,"shift":{"each":1,"drag":1,"draw":1,"while":1}
,"each":{"object":1}
,"individually":{"note":1}
,"note":{"drag":1}
,"drag":{"arrow":1,"resize":1,"handle":1,"object\u0027s":1,"object":1,"selected":1,"part":1}
,"arrow":{"pointer":1,"align":1,"show":1,"keys":1}
,"pointer":{"selection":1}
,"selection":{"box":1,"tool":1,"modification":1}
,"includes":{"objects":1}
,"completely":{"surround":1}
,"surround":{"objects":1}
,"enclosed":{"selection":1}
,"resize":{"selected":1,"multiple":1,"objects":1}
,"inspector":{"pe":1,"ab":1,"command":1,"keyboard":1}
,"pe":{"command":1}
,"-1":{"move":1,"display":1}
,"position":{"position":1,"ab":1,"resize":1}
,"ab":{"inspector":1,"desired":1}
,"sizing":{"action":1}
,"action":{"type":1}
,"ize":{"return":1}
,"return":{"resize":1,"enter":1}
,"keeping":{"proportions":1,"difference":1}
,"proportions":{"shift":1}
,"handle":{"resize":1,"edges":1,"snap-to":1}
,"difference":{"lengths":1}
,"lengths":{"widths":1}
,"widths":{"option-shift":1}
,"option-shift":{"drag":1}
,"edges":{"objects":1,"command":1}
,"remain":{"fixed":1}
,"fixed":{"position":1}
,"copy":{"style":1}
,"style":{"selected":1,"object":1}
,"-option-c":{"paste":1}
,"-option-v":{"press":1}
,"left":{"edges":1}
,"-option-left":{"arrow":1}
,"right":{"edges":1}
,"-option-right":{"arrow":1}
,"top":{"edges":1}
,"-option-up":{"arrow":1}
,"bottom":{"edges":1}
,"-option-down":{"arrow":1}
,"hide":{"rulers":1,"object":1,"guides":1,"inspector":1,"bjects":1}
,"rulers":{"command":1}
,"-option-shift-r":{"show":1}
,"grid":{"command":1,"guides":1}
,"-option-y":{"snap-to":1}
,"snap-to":{"grid":1}
,"guides":{"dynamic":1,"while":1,"drag":1,"creating":1,"command":1}
,"dynamic":{"guides":1}
,"while":{"resizing":1,"moving":1}
,"resizing":{"object":1}
,"object\u0027s":{"handle":1}
,"toggle":{"snapping":1,"dynamic":1,"current":1}
,"snapping":{"objects":1}
,"-option-shift-y":{"show":1}
,"creating":{"editing":1}
,"editing":{"objects":1}
,"-option-":{"toggle":1,"apostrophe":1}
,"-option-shift-":{"toggle":1}
,"apostrophe":{"press":1}
,"bring":{"selected":1}
,"forward":{"command":1}
,"-shift-[bring":{"selected":1}
,"front":{"command":1}
,"-option-[change":{"part":1}
,"part":{"labels":1,"object":1,"duplicate":1,"shift":1,"rotate":1}
,"labels":{"horizontal":1}
,"horizontal":{"vertical":1,"command":1}
,"vertical":{"vertical":1,"horizontal":1,"line":1}
,"label":{"drag":1}
,"option":{"drag":1,"draw":1,"esize":1}
,"by":{"dragging":1}
,"dragging":{"option":1}
,"group":{"objects":1}
,"lock":{"object":1}
,"-option-l":{"move":1}
,"point":{"if":1}
,"if":{"set":1}
,"set":{"points":1,"cm":1}
,"points":{"inches":1}
,"inches":{"0.1":1}
,"0.1":{"cm":1}
,"cm":{"if":1,"arrow":1}
,"keys":{"move":1,"shift-arrow":1,"reorder":1}
,"10":{"times":1}
,"times":{"arrow":1}
,"shift-arrow":{"keys":1}
,"reorder":{"selected":1}
,"rotate":{"object":1}
,"-option-r":{"send":1}
,"send":{"selected":1,"object":1}
,"backward":{"command":1}
,"-shift-]":{"send":1}
,"back":{"command":1}
,"-option-]":{"ungroup":1}
,"ungroup":{"objects":1}
,"unlock":{"object":1}
,"-shift-option-l":{"press":1}
,"display":{"position":1,"styles":1,"appearance":1,"data":1}
,"styles":{"styles":1,"ab":1}
,"-2":{"display":1}
,"appearance":{"appearance":1,"ab":1}
,"-3":{"display":1}
,"data":{"data":1,"ab":1}
,"-4":{"press":1}
,"-k":{"add":1}
,"add":{"new":1}
,"-return":{"command":1}
,"-enter":{"rename":1}
,"rename":{"selected":1}
,"bjects":{"tab":1}
,"-option-t":{"press":1}
,"tool":{"selection":1,"enter":1,"shift":1,"option":1}
,"shift-enter":{"numeric":1}
,"numeric":{"keypad":1}
,"keypad":{"fn-enter":1,"draw":1}
,"fn-enter":{"fn-shift-enter":1}
,"fn-shift-enter":{"computers":1}
,"computers":{"numeric":1}
,"draw":{"horizontal":1,"line":1,"circle":1,"square":1}
,"line":{"line":1,"tool":1,"draw":1,"45-degree":1,"move":1}
,"45-degree":{"increment":1}
,"increment":{"line":1}
,"horizontally":{"vertically":1}
,"vertically":{"shift":1}
,"moving":{"object":1}
,"circle":{"oval":1,"draw":1,"option":1}
,"oval":{"tool":1}
,"square":{"rectangle":1,"constrain":1,"circle":1}
,"rectangle":{"tool":1}
,"constrain":{"resizing":1}
,"esize":{"object":1}
,"creation":{"navigation":1}
,"modification":{"keyboard":1}
,"alignment":{"keyboard":1}
,"arrangement":{"keyboard":1}
,"ayout":{"tools":1}
}
;Search.control.loadWordPairs(pairs);
