var pairs =
{
"script":{"steps":1,"step":1}
,"steps":{"reference":1,"by":1,"skipped":1}
,"reference":{"links":1,"category":1,"alphabetical":1}
,"links":{"find":1}
,"find":{"script":1}
,"by":{"category":1}
,"category":{"alphabetically":1,"list":1}
,"alphabetically":{"cript":1}
,"cript":{"steps":1}
,"list":{"script":1,"each":1}
,"alphabetical":{"list":1}
,"each":{"script":1,"topic":1}
,"step":{"topic":1,"options":1,"usage":1,"supported":1,"compatibility":1}
,"topic":{"describes":1,"script":1}
,"describes":{"script":1}
,"options":{"parameters":1}
,"parameters":{"format":1}
,"format":{"script":1}
,"usage":{"create":1}
,"create":{"scripts":1}
,"scripts":{"automating":1,"compatibility":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
,"compatibility":{"each":1}
,"supported":{"run":1}
,"run":{"unsupported":1}
,"unsupported":{"script":1}
,"skipped":{"return":1}
,"return":{"error":1}
,"error":{"command":1}
,"command":{"unavailable":1}
,"unavailable":{"get":1}
,"get":{"lasterror":1}
,"lasterror":{"function":1}
,"function":{"script":1}
}
;Search.control.loadWordPairs(pairs);
