var pairs =
{
"get":{"highcontra":1,"highcontrastcolor":1,"high":1}
,"highcontra":{"stcolor":1}
,"stcolor":{"returns":1}
,"returns":{"current":1,"empty":1,"high":1}
,"current":{"high":1}
,"high":{"contrast":1}
,"contrast":{"default":1,"option":1,"color":1,"white":1}
,"default":{"color":1}
,"color":{"scheme":1}
,"scheme":{"name":1,"active":1}
,"name":{"get":1,"if":1}
,"highcontrastcolor":{"none":1,"get":1}
,"none":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"function":1}
,"function":{"returns":1,"macos":1,"supported":1}
,"if":{"high":1,"option":1,"function":1}
,"option":{"enabled":1,"unavailable":1}
,"enabled":{"windows":1}
,"windows":{"ease":1,"theme":1}
,"ease":{"access":1}
,"access":{"center":1}
,"center":{"if":1}
,"active":{"returns":1}
,"empty":{"string":1}
,"string":{"if":1,"returns":1}
,"unavailable":{"inactive":1}
,"inactive":{"if":1}
,"macos":{"filemaker":1}
,"webdirect":{"function":1}
,"supported":{"returns":1}
,"white":{"windows":1,"get":1}
,"theme":{"set":1}
,"set":{"high":1}
}
;Search.control.loadWordPairs(pairs);
