var pairs =
{
"fieldtype":{"eturns":1,"filename":1,"customers":1}
,"eturns":{"fieldname":1}
,"fieldname":{"fieldtype":1,"filename":1,"-the":1}
,"filename":{"fieldname":1,"-the":1}
,"-the":{"name":1}
,"name":{"open":1,"field":1}
,"open":{"database":1,"global":1}
,"database":{"file":1}
,"file":{"local":1,"text":1,"phone":1,"current":1,"today\u2019s":1,"statement":1}
,"local":{"remote":1}
,"remote":{"fieldname":1}
,"field":{"database":1,"names":1,"exists":1,"type":1,"if":1,"isn\u2019t":1,"value":1,"defined":1,"repeats":1,"fieldtype":1,"indexed":1,"stores":1}
,"text":{"filemaker":1,"number":1,"unindexed":1,"field":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"field":1}
,"names":{"format":1}
,"format":{"tablename":1}
,"tablename":{":fieldname":1}
,":fieldname":{"field":1}
,"exists":{"table":1}
,"table":{"current":1,"result":1}
,"current":{"table":1,"balance":1}
,"result":{"values":1}
,"values":{"separated":1}
,"separated":{"by":1}
,"by":{"spaces":1}
,"spaces":{"first":1}
,"first":{"value":1}
,"value":{"standard":1,"field":1,"indexed":1,"maximum":1,"fieldtype":1}
,"standard":{"storedcalc":1,"text":1}
,"storedcalc":{"summary":1,"number":1}
,"summary":{"unstoredcalc":1}
,"unstoredcalc":{"external":1}
,"external":{"secure":1,"open":1}
,"secure":{"external":1,"container":1,"storage":1}
,"global":{"second":1,"date":1,"field":1,"fields":1}
,"second":{"value":1}
,"type":{"text":1,"date":1}
,"number":{"date":1,"repetitions":1,"returns":1,"field":1,"indexed":1}
,"date":{"time":1,"returns":1,"unindexed":1,"field":1,"global":1}
,"time":{"timestamp":1}
,"timestamp":{"container":1}
,"container":{"value":1,"unindexed":1,"field":1,"fields":1}
,"indexed":{"unindexed":1,"find":1,"customers":1,"fieldtype":1}
,"unindexed":{"fourth":1,"customers":1}
,"fourth":{"value":1}
,"maximum":{"number":1,"times":1}
,"repetitions":{"defined":1}
,"defined":{"field":1,"repeating":1,"text":1,"stored":1,"global":1,"container":1}
,"if":{"field":1}
,"isn\u2019t":{"defined":1}
,"repeating":{"field":1}
,"customers":{"phone":1,"database":1,"current":1,"today\u2019s":1,"statement":1}
,"phone":{"number":1}
,"returns":{"standard":1,"storedcalc":1,"global":1,"external":1}
,"repeats":{"maximum":1}
,"times":{"storage":1}
,"storage":{"options":1,"container":1}
,"options":{"left":1}
,"left":{"unchanged":1}
,"unchanged":{"fields":1}
,"fields":{"indexed":1}
,"find":{"performed":1}
,"performed":{"field":1}
,"balance":{"returns":1,"field":1}
,"stored":{"numeric":1}
,"numeric":{"calculation":1}
,"calculation":{"field":1}
,"today\u2019s":{"date":1}
,"statement":{"returns":1,"field":1}
,"stores":{"data":1}
,"data":{"externally":1}
,"externally":{"secure":1}
}
;Search.control.loadWordPairs(pairs);
