var pairs =
{
"inding":{"files":1}
,"files":{"runtime":1,"bind":1,"customize":1,"want":1,"double-click":1,"developer":1,"10":1,"ensures":1,"open":1,"pertaining":1,"existing":1,"key":1,"new":1,"permanently":1,"can\u2019t":1,"order":1}
,"runtime":{"solutio":1,"database":1,"application":1,"solution":1,"name":1,"applications":1,"file":1}
,"solutio":{"note":1,"12":1}
,"note":{"feature":1}
,"feature":{"use":1}
,"use":{"advanced":1,"default":1,"binding":1}
,"advanced":{"tools":1,"developer":1,"modifications":1,"nd":1}
,"tools":{"general":1,"se":1,"menu":1}
,"general":{"preference":1}
,"preference":{"selected":1}
,"selected":{"ad":1,"remove":1}
,"ad":{"vanced":1}
,"vanced":{"tools":1}
,"se":{"developer":1}
,"developer":{"utilities":1,"solution":1}
,"utilities":{"produce":1,"create":1,"if":1,"database":1,"settings":1}
,"produce":{"standalone":1}
,"standalone":{"runtime":1}
,"database":{"solution":1,"file":1,"files":1,"saved":1,"case":1}
,"solution":{"users":1,"solution":1,"options":1,"application":1,"files":1,"11":1,"15":1,"setting":1,"rebind":1,"you\u2019ll":1,"including":1,"bind":1}
,"users":{"access":1}
,"access":{"running":1,"files":1,"features":1,"database":1}
,"running":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"create":{"copy":1,"runtime":1,"setting":1}
,"copy":{"files":1}
,"bind":{"database":1}
,"file":{"files":1,"list":1,"select":1,"saving":1,"filemaker":1}
,"application":{"name":1,"runtime":1,"filename":1,"database":1,"binding":1,"open":1}
,"name":{"close":1,"type":1,"runtime":1,"folder":1}
,"close":{"all":1}
,"all":{"database":1}
,"customize":{"choose":1,"if":1}
,"choose":{"tools":1,"folder":1}
,"menu":{"developer":1}
,"if":{"developer":1,"add":1,"forget":1,"selected":1}
,"saved":{"settings":1}
,"settings":{"load":1,"add":1,"required":1,"choose":1,"file":1}
,"load":{"settings":1}
,"add":{"locate":1,"multiple":1,"company":1,"auxiliary":1}
,"locate":{"files":1}
,"want":{"customize":1,"splash":1,"change":1}
,"multiple":{"files":1}
,"double-click":{"file":1}
,"list":{"primary":1}
,"primary":{"file":1}
,"select":{"developer":1,"create":1,"closing":1,"image":1,"options":1}
,"required":{"setting":1,"options":1}
,"setting":{"up":1,"17":1,"binding":1,"if":1}
,"up":{"files":1}
,"options":{"solution":1,"dialog":1,"required":1,"developer":1}
,"dialog":{"box":1}
,"box":{"select":1}
,"type":{"name":1,"one-to":1,"key":1}
,"filename":{"name":1,"extension":1}
,"folder":{"runtime":1,"location":1}
,"10":{"extension":1}
,"extension":{"type":1,"use":1,".fmpur":1,"associate":1}
,"one-to":{"five-character":1}
,"five-character":{"filename":1}
,"default":{"extension":1}
,".fmpur":{"extension":1}
,"associate":{"solution":1}
,"applications":{"aming":1}
,"aming":{"runtime":1}
,"11":{"bindkey":1}
,"bindkey":{"type":1}
,"key":{"24":1,"links":1,"if":1,"use":1,"you\u2019ll":1,"want":1,"redistribute":1,"assigned":1}
,"24":{"characters":1}
,"characters":{"binding":1}
,"binding":{"keys":1,"key":1,"installs":1}
,"keys":{"case":1}
,"case":{"sensitive":1,"you\u2019ll":1}
,"sensitive":{"binding":1}
,"links":{"runtime":1}
,"ensures":{"bound":1}
,"bound":{"files":1,"runtime":1}
,"open":{"runtime":1,"bound":1,"original":1}
,"installs":{"system":1}
,"system":{"files":1}
,"pertaining":{"each":1}
,"each":{"platform":1}
,"platform":{"preparing":1}
,"preparing":{"files":1}
,"12":{"add":1}
,"company":{"logo":1}
,"logo":{"custom":1}
,"custom":{"image":1,"splash":1}
,"image":{"closing":1,"select":1,"382":1,"formats":1}
,"closing":{"splash":1,"image":1}
,"splash":{"screen":1}
,"screen":{"select":1,"display":1,"by":1}
,"382":{"175":1}
,"175":{"pixels":1}
,"pixels":{"72":1}
,"72":{"dpi":1}
,"dpi":{"distorted":1}
,"distorted":{"displayed":1}
,"displayed":{"supported":1}
,"supported":{"image":1}
,"formats":{"jpeg":1}
,"jpeg":{"gif":1}
,"gif":{"13":1}
,"13":{"delay":1}
,"delay":{"set":1}
,"set":{"number":1}
,"number":{"seconds":1}
,"seconds":{"want":1}
,"display":{"preview":1}
,"preview":{"custom":1,"14":1}
,"by":{"clicking":1,"saving":1}
,"clicking":{"preview":1}
,"14":{"select":1}
,"15":{"16":1}
,"16":{"quickly":1}
,"quickly":{"repeat":1}
,"repeat":{"process":1}
,"process":{"save":1}
,"save":{"settings":1}
,"location":{"settings":1}
,"saving":{"solution":1,"developer":1}
,"17":{"create":1}
,"auxiliary":{"files":1}
,"existing":{"runtime":1}
,"rebind":{"files":1,"all":1,"binding":1}
,"you\u2019ll":{"remember":1,"rebind":1,"open":1}
,"remember":{"record":1}
,"record":{"safe":1}
,"safe":{"place":1}
,"place":{"by":1}
,"forget":{"binding":1}
,"change":{"runtime":1}
,"new":{"binding":1,"runtime":1}
,"redistribute":{"entire":1}
,"entire":{"solution":1}
,"including":{"new":1}
,"modifications":{"if":1}
,"remove":{"admin":1}
,"admin":{"access":1}
,"permanently":{"option":1}
,"option":{"bound":1}
,"can\u2019t":{"regain":1}
,"regain":{"access":1}
,"features":{"removing":1}
,"removing":{"admin":1}
,"original":{"database":1}
,"order":{"design":1}
,"design":{"filemaker":1}
,"nd":{"rebind":1}
,"assigned":{"runtime":1}
}
;Search.control.loadWordPairs(pairs);
