var pairs =
{
"orking":{"plug-ins":1}
,"plug-ins":{"plug-in":1,"third-party":1,"nd":1,"solution":1,"automatically":1,"support":1,"result":1,"search":1}
,"plug-in":{"software":1,"implements":1,"describes":1,"version":1,"supports":1}
,"software":{"extends":1,"companies":1}
,"extends":{"capabilities":1}
,"capabilities":{"filemaker":1}
,"filemaker":{"pro":1,"knowledge":1}
,"pro":{"advanced":1}
,"advanced":{"plug-ins":1,"deployed":1,"runs":1,"stop":1,"windows":1}
,"third-party":{"software":1}
,"companies":{"development":1}
,"development":{"systems":1}
,"systems":{"group":1}
,"group":{"organization":1}
,"organization":{"plug-in":1}
,"implements":{"features":1}
,"features":{"access":1}
,"access":{"by":1}
,"by":{"external":1}
,"external":{"functions":1,"script":1}
,"functions":{"external":1}
,"script":{"steps":1}
,"steps":{"documentation":1}
,"documentation":{"plug-in":1}
,"describes":{"cr":1}
,"cr":{"eate":1}
,"eate":{"plug-ins":1}
,"nd":{"users":1}
,"users":{"install":1}
,"install":{"plug-ins":1}
,"solution":{"files":1}
,"files":{"set":1,"check":1}
,"set":{"up":1}
,"up":{"solution":1}
,"check":{"plug-in":1}
,"version":{"update":1}
,"update":{"plug-ins":1}
,"automatically":{"if":1}
,"if":{"neede":1,"plug-in":1}
,"neede":{"windows":1}
,"windows":{"filemaker":1,"disable":1}
,"deployed":{"32-bit":1}
,"32-bit":{"64-bit":1}
,"64-bit":{"application":1,"contact":1,"filemaker":1}
,"application":{"macos":1,"affect":1}
,"macos":{"filemaker":1}
,"runs":{"64-bit":1}
,"affect":{"compatibility":1}
,"compatibility":{"plug-ins":1}
,"support":{"single":1}
,"single":{"architecture":1}
,"architecture":{"incompatible":1}
,"incompatible":{"combination":1,"plug-ins":1}
,"combination":{"filemaker":1}
,"result":{"unexpected":1}
,"unexpected":{"behavior":1}
,"behavior":{"filemaker":1}
,"stop":{"determine":1}
,"determine":{"if":1}
,"supports":{"32-bit":1}
,"contact":{"plug-in\u0027s":1}
,"plug-in\u0027s":{"developer":1}
,"developer":{"switch":1}
,"switch":{"32-bit":1}
,"disable":{"incompatible":1}
,"search":{"filemaker":1}
,"knowledge":{"base":1}
,"base":{"plugin":1}
,"plugin":{"plugins":1}
}
;Search.control.loadWordPairs(pairs);
