var pairs =
{
"comment":{"dds":1,"text":1}
,"dds":{"comments":1}
,"comments":{"list":1,"filemaker":1,"document":1,"bold":1,"viewing":1,"print":1,"explain":1}
,"list":{"steps":1}
,"steps":{"script":1,"go":1}
,"script":{"en":1,"comments":1,"script":1,"performed":1,"steps":1}
,"en":{"ter":1}
,"ter":{"comments":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"use":1}
,"use":{"comments":1}
,"document":{"script":1}
,"bold":{"prefaced":1}
,"prefaced":{"comments":1}
,"viewing":{"script":1}
,"performed":{"add":1}
,"add":{"new":1}
,"new":{"line":1}
,"line":{"comment":1}
,"text":{"press":1}
,"press":{"windows":1}
,"windows":{"ctrl":1}
,"ctrl":{"enter":1}
,"enter":{"alt":1,"macos":1}
,"alt":{"enter":1}
,"macos":{"ctrl-return":1}
,"ctrl-return":{"opt-return":1}
,"opt-return":{"comments":1}
,"print":{"italics":1}
,"italics":{"comments":1}
,"explain":{"script":1}
,"go":{"layout":1,"back":1}
,"layout":{"[\u0022":1,"go":1,"[original":1}
,"[\u0022":{"invoices":1}
,"invoices":{"\u0022]":1,"current":1,":customer":1}
,"\u0022]":{"find":1}
,"find":{"all":1,"matching":1}
,"all":{"invoices":1,"records":1}
,"current":{"customer":1}
,"customer":{"find":1,"backup.pdf":1}
,"matching":{"records":1}
,"records":{"[replace":1,"[restore":1,"found":1,"pdf":1,"browsed":1}
,"[replace":{"invoices":1}
,":customer":{"id]":1}
,"id]":{"sort":1}
,"sort":{"found":1,"records":1}
,"found":{"set":1}
,"set":{"by":1,"pdf":1}
,"by":{"invoice":1}
,"invoice":{"id":1}
,"id":{"sort":1}
,"[restore":{"dialog":1}
,"dialog":{"off]":1,"customer":1}
,"off]":{"save":1,"go":1}
,"save":{"all":1,"records":1}
,"pdf":{"save":1,"[with":1}
,"[with":{"dialog":1}
,"backup.pdf":{"records":1}
,"browsed":{"create":1}
,"create":{"folders":1}
,"folders":{"off]":1}
,"back":{"original":1}
,"original":{"layout":1}
,"[original":{"layout]":1}
,"layout]":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
