var pairs =
{
"creating":{"editing":1,"managing":1,"layout":1,"dynamic":1}
,"editing":{"charts":1}
,"charts":{"layout":1,"created":1,"including":1,"pie":1,"scatter":1,"change":1,"sort":1,"summary":1}
,"layout":{"mod":1,"mode":1,"creating":1,"part":1,"parts":1,"chart":1,"displaying":1,"plot":1,"edit":1,"layout":1,"exit":1,"placing":1,"sorted":1}
,"mod":{"create":1}
,"create":{"edit":1,"chart":1,"new":1,"summary":1}
,"edit":{"chart":1}
,"chart":{"chart":1,"summary":1,"open":1,"resizing":1,"blank":1,"don\u2019t":1,"creating":1,"double-click":1,"layout":1,"tool":1,"choose":1,"note":1,"setup":1,"inspector":1,"preview":1,"title":1,"type":1,"axes":1,"lick":1,"pecify":1,"records":1,"placeholder":1,"based":1,"worldwide":1,"total":1,"body":1,"x-axis":1,"data":1,"display":1,"compares":1,"sales":1,"settings":1,"subsummary":1}
,"summary":{"data":1,"field":1,"fields":1,"part":1}
,"data":{"layout":1,"chart":1,"series":1,"labels":1,"formatting":1,"source":1,"choose":1,"database":1,"by":1,"data":1,"table":1,"pie":1,"select":1}
,"mode":{"create":1,"chart":1,"depending":1,"sample":1,"sort":1}
,"open":{"layout":1}
,"managing":{"layouts":1}
,"layouts":{"reports":1,"menu":1}
,"reports":{"if":1,"table":1}
,"if":{"resize":1,"applicable":1}
,"resize":{"layout":1}
,"part":{"chart":1,"placed":1,"layout":1,"sorted":1}
,"resizing":{"layout":1}
,"parts":{"use":1}
,"use":{"new":1}
,"new":{"layout\u002Freport":1,"layout":1}
,"layout\u002Freport":{"assistant":1}
,"assistant":{"create":1}
,"blank":{"layout":1}
,"displaying":{"chart":1}
,"don\u2019t":{"add":1}
,"add":{"fields":1,"title":1}
,"fields":{"layout":1,"chart":1}
,"plot":{"data":1}
,"double-click":{"chart":1}
,"tool":{"chart":1,"status":1}
,"status":{"toolbar":1}
,"toolbar":{"drag":1}
,"drag":{"rectangle":1}
,"rectangle":{"want":1}
,"want":{"chart":1}
,"choose":{"insert":1,"chart":1,"layouts":1}
,"insert":{"enu":1}
,"enu":{"chart":1}
,"note":{"charts":1}
,"created":{"layout":1}
,"depending":{"layout":1}
,"placed":{"placing":1}
,"placing":{"chart":1}
,"setup":{"dialog":1}
,"dialog":{"box":1}
,"box":{"appears":1,"chart":1}
,"appears":{"change":1}
,"change":{"settings":1,"chart":1,"data":1}
,"settings":{"chart":1,"sort":1}
,"inspector":{"right":1,"changing":1,"pecifying":1,"chart":1,"data":1}
,"right":{"modify":1}
,"modify":{"chart":1}
,"preview":{"helps":1,"add":1}
,"helps":{"efficiently":1}
,"efficiently":{"chart":1}
,"title":{"chart":1,"type":1,"button":1,"choose":1}
,"type":{"change":1,"data":1}
,"button":{"title":1}
,"series":{"column":1}
,"column":{"bar":1}
,"bar":{"line":1,"positive\u002Fnegative":1}
,"line":{"charts":1}
,"including":{"stacked":1}
,"stacked":{"column":1}
,"positive\u002Fnegative":{"charts":1}
,"pie":{"charts":1}
,"scatter":{"bubble":1}
,"bubble":{"charts":1}
,"labels":{"show":1,"pie":1,"subcategory":1}
,"show":{"hide":1}
,"hide":{"tick":1}
,"tick":{"marks":1,"mark":1}
,"marks":{"set":1}
,"set":{"tick":1,"delimited":1,"chart":1,"x-axis":1}
,"mark":{"scale":1}
,"scale":{"if":1}
,"applicable":{"format":1}
,"format":{"data":1}
,"formatting":{"scaling":1}
,"scaling":{"chart":1}
,"axes":{"hange":1}
,"hange":{"color":1}
,"color":{"scheme":1}
,"scheme":{"legend":1}
,"legend":{"fonts":1}
,"fonts":{"chart":1}
,"lick":{"styles":1,"data":1}
,"styles":{"chart":1}
,"changing":{"chart":1}
,"pecify":{"type":1}
,"records":{"found":1,"related":1,"lick":1,"by":1,"chart":1}
,"found":{"set":1}
,"delimited":{"records":1}
,"related":{"records":1}
,"source":{"chart":1}
,"pecifying":{"data":1}
,"placeholder":{"image":1}
,"image":{"chart":1}
,"sample":{"data":1}
,"menu":{"save":1}
,"save":{"layout":1}
,"exit":{"layout":1}
,"based":{"data":1}
,"database":{"browse":1,"calculate":1}
,"browse":{"mode":1}
,"sort":{"data":1,"field":1,"records":1,"by":1}
,"by":{"break":1,"subsummary":1,"country":1,"subcategory":1,"company":1,"main":1}
,"break":{"field":1}
,"field":{"form":1,"create":1,"database":1,"total":1,"country":1,"y-axis":1,"chart":1}
,"form":{"groupings":1}
,"groupings":{"categories":1}
,"categories":{"data":1}
,"table":{"view":1}
,"view":{"sorting":1,"defining":1}
,"sorting":{"records":1}
,"subsummary":{"values":1,"layout":1}
,"values":{"chart":1}
,"worldwide":{"sales":1}
,"sales":{"by":1,"create":1,"sums":1,"field":1,"usa":1}
,"country":{"sort":1,"field":1,"chart":1,"change":1,"by":1}
,"calculate":{"aggregate":1}
,"aggregate":{"value":1}
,"value":{"category":1}
,"category":{"creating":1,"labels":1,"subcategory":1,"country":1}
,"dynamic":{"reports":1}
,"defining":{"summary":1}
,"total":{"sales":1}
,"sums":{"sales":1}
,"body":{"header":1}
,"header":{"footer":1}
,"footer":{"top":1}
,"top":{"bottom":1}
,"bottom":{"navigation":1}
,"navigation":{"ubsummary":1}
,"ubsummary":{"grand":1}
,"grand":{"summary":1}
,"x-axis":{"horizontal":1,"category":1}
,"horizontal":{"category":1}
,"y-axis":{"vertical":1}
,"vertical":{"slice":1}
,"slice":{"data":1}
,"select":{"current":1,"summarized":1}
,"current":{"found":1}
,"display":{"layout":1}
,"sorted":{"select":1,"by":1}
,"summarized":{"groups":1}
,"groups":{"records":1}
,"compares":{"total":1}
,"subcategory":{"total":1,"sort":1,"company":1}
,"company":{"country":1,"set":1,"place":1}
,"main":{"category":1}
,"place":{"chart":1}
}
;Search.control.loadWordPairs(pairs);
