var pairs =
{
"let":{"sets":1,"[}":1,"function":1,"complex":1,"formulas":1,"[variable":1,"=5":1,"[x":1,"city":1,"$privilege_set":1,"$counter":1,"get":1,"[\u0022":1,"[a":1}
,"sets":{"variable":1,"variables":1,"local":1}
,"variable":{"variables":1,"name":1,"returned":1,"script":1,"values":1,"nested":1,"scope":1,"defined":1,"current":1,"if":1,"duration":1,"counter":1,"returns":1,"variable":1,"simplified":1}
,"variables":{"result":1,"expression":1,"return":1,"use":1,"reuse":1,"let":1,"easier":1,"left":1,"function":1,"defined":1,"hat":1}
,"result":{"expression":1,"use":1,"function":1}
,"expression":{"duration":1,"-any":1,"field":1}
,"duration":{"calculation":1,"script":1}
,"calculation":{"script":1,"var":1,"expression":1,"-any":1,"separate":1,"let":1,"scope":1,"scoped":1}
,"script":{"exits":1,"step":1,"local":1,"let":1}
,"exits":{"file":1}
,"file":{"closed":1,"scripts":1}
,"closed":{"let":1}
,"[}":{"var1=expression1":1}
,"var1=expression1":{"var2=expression2":1}
,"var2=expression2":{".]":1}
,".]":{"calculation":1}
,"var":{"-any":1}
,"-any":{"variable":1,"calculation":1}
,"name":{"sing":1}
,"sing":{"variables":1}
,"field":{"constant":1}
,"constant":{"calculation":1,"parameters":1}
,"parameters":{"braces":1,"evaluate":1,"allowing":1,"while":1}
,"braces":{"optional":1}
,"optional":{"text":1}
,"text":{"number":1}
,"number":{"date":1,"redundant":1}
,"date":{"time":1}
,"time":{"timestamp":1}
,"timestamp":{"container":1}
,"container":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"7.0":1}
,"7.0":{"let":1}
,"function":{"allows":1,"calls":1,"use":1,"sets":1,"variables":1,"local":1,"if":1,"function":1,"variable":1,"returns":1}
,"allows":{"assign":1}
,"assign":{"expressions":1,"multiple":1}
,"expressions":{"variables":1}
,"return":{"result":1}
,"use":{"variables":1,"let":1,"list":1,"defined":1}
,"complex":{"formulas":1,"returns":1}
,"formulas":{"easier":1,"efficient":1}
,"easier":{"read":1}
,"read":{"by":1,"each":1}
,"by":{"reducing":1,"storing":1,"semicolons":1,"account":1}
,"reducing":{"calling":1,"number":1}
,"calling":{"functions":1}
,"functions":{"functions":1,"let":1,"allowing":1}
,"efficient":{"by":1}
,"storing":{"result":1}
,"calls":{"variables":1,"assign":1}
,"reuse":{"formula":1}
,"formula":{"reducing":1}
,"redundant":{"function":1}
,"multiple":{"variables":1}
,"list":{"syntax":1}
,"syntax":{"enclosed":1,"second":1}
,"enclosed":{"brackets":1}
,"brackets":{"[]":1}
,"[]":{"separated":1}
,"separated":{"by":1}
,"semicolons":{"multiple":1}
,"each":{"variable":1}
,"returned":{"calculation":1}
,"separate":{"lines":1}
,"lines":{"formatting":1}
,"formatting":{"required":1}
,"required":{"let":1}
,"[variable":{"=value":1}
,"=value":{"variable2":1}
,"variable2":{"=value2":1}
,"=value2":{"calculation":1}
,"left":{"right":1}
,"right":{"use":1}
,"defined":{"variables":1,"earlier":1,"set":1,"unction":1,"completely":1,"ariables":1,"calculation":1}
,"earlier":{"let":1}
,"local":{"global":1,"variables":1,"variable":1}
,"global":{"variables":1}
,"hat":{"defined":1}
,"set":{"variable":1,"returns":1,"sets":1}
,"step":{"define":1}
,"define":{"new":1}
,"new":{"variable":1}
,"values":{"yo":1}
,"yo":{"nest":1}
,"nest":{"let":1}
,"if":{"use":1,"had":1,"calculation":1,"evaluated":1}
,"unction":{"variable":1}
,"nested":{"let":1,"function":1}
,"scope":{"nested":1,"local":1}
,"had":{"defined":1}
,"completely":{"unique":1}
,"unique":{"variable":1}
,"ariables":{"referenced":1}
,"referenced":{"calculation":1}
,"scoped":{"file":1}
,"scripts":{"running":1}
,"running":{"sing":1}
,"=5":{"x*x":1,"squared":1,"=10":1}
,"x*x":{"returns":1}
,"returns":{"25":1,"125":1,"san":1,"contents":1,"[full":1,"240":1,"scriptparameter":1,"12":1}
,"25":{"let":1}
,"[x":{"=5":1}
,"squared":{"=x*x":1}
,"=x*x":{"cubed":1}
,"cubed":{"=squared*x":1,"returns":1}
,"=squared*x":{"cubed":1}
,"125":{"returns":1}
,"san":{"francisco":1}
,"francisco":{"-paris":1,"city":1}
,"-paris":{"let":1}
,"city":{"=\u0022":1,"&\u0022":1}
,"=\u0022":{"paris":1,"san":1,"=5":1}
,"paris":{"let":1}
,"&\u0022":{"-\u0022":1,"pass":1,"&\u005C\u0022":1,"=evaluate":1,"&\u0022":1,"&b":1}
,"-\u0022":{"&city":1}
,"&city":{"sets":1}
,"current":{"account\u0027s":1}
,"account\u0027s":{"privilege":1}
,"privilege":{"set":1}
,"contents":{"variable":1}
,"$privilege_set":{"=get":1,"returns":1}
,"=get":{"accountprivilegesetname":1}
,"accountprivilegesetname":{"$privilege_set":1}
,"[full":{"access]":1}
,"access]":{"if":1}
,"evaluated":{"by":1}
,"account":{"full":1}
,"full":{"access":1}
,"access":{"privilege":1,"variable":1}
,"counter":{"repetition":1}
,"repetition":{"50":1}
,"50":{"value":1}
,"value":{"120":1}
,"120":{"let":1}
,"$counter":{"[50]":1,"[50]*2":1}
,"[50]":{"=120":1}
,"=120":{"$counter":1}
,"[50]*2":{"returns":1}
,"240":{"pass":1}
,"pass":{"named":1}
,"named":{"parameters":1}
,"evaluate":{"let":1}
,"get":{"scriptparameter":1}
,"scriptparameter":{"functions":1,"=\u0022":1,"&\u0022":1}
,"allowing":{"access":1}
,"=10":{"evaluate":1,"let":1}
,"[\u0022":{"&get":1}
,"&get":{"scriptparameter":1}
,"simplified":{"first":1}
,"first":{"parameter":1}
,"parameter":{"second":1,"complex":1,"let":1}
,"second":{"parameter":1}
,"12":{"scriptparameter":1}
,"&\u005C\u0022":{"\u005C\u0022":1}
,"\u005C\u0022":{"&b":1}
,"&b":{"pass":1}
,"while":{"keeping":1}
,"keeping":{"ability":1}
,"ability":{"check":1}
,"check":{"syntax":1}
,"[a":{"=evaluate":1}
,"=evaluate":{"let":1}
}
;Search.control.loadWordPairs(pairs);
