var pairs =
{
"defining":{"conditional":1}
,"conditional":{"formatting":1,"conditional":1,"fill":1,"format":1,"settings":1}
,"formatting":{"layout":1,"automatically":1,"settings":1,"dialog":1,"data":1,"additional":1,"options":1,"moderation":1,"choose":1,"conditional":1,"badge":1,"buttons":1,"non-textual":1,"criteria":1,"set":1,"conditions":1,"ignored":1,"inspector":1,"field":1,"objects":1}
,"layout":{"objects":1,"mode":1,"object":1}
,"objects":{"format":1,"change":1,"hoose":1,"conditional":1,"rectangular":1,"previous":1,"examples":1}
,"format":{"layout":1,"menu":1,"based":1,"data":1,"buttons":1,"custom":1,"changing":1,"settings":1}
,"change":{"automatically":1,"conditional":1,"order":1}
,"automatically":{"meet":1,"display":1}
,"meet":{"conditions":1}
,"conditions":{"use":1,"condition":1,"select":1,"object":1,"evaluated":1,"less":1}
,"use":{"conditional":1,"elf":1,"apple":1,"value":1}
,"display":{"balances":1,"state":1,"red":1,"negative":1}
,"balances":{"30":1}
,"30":{"days":1}
,"days":{"bold":1,"passed":1,"current":1,"inclusive":1,"11\u002F24\u002F201":1}
,"bold":{"red":1}
,"red":{"text":1,"set":1,"number":1}
,"text":{"conditional":1,"field":1,"yellow":1,"effects":1,"style":1}
,"settings":{"affect":1,"change":1,"applied":1,"while":1,"onditional":1,"data":1,"therefore":1,"combined":1,"conditional":1,"transferred":1}
,"affect":{"data":1,"performance":1}
,"data":{"displayed":1,"stored":1,"selected":1,"meets":1,"note":1,"formatting":1,"value":1}
,"displayed":{"printed":1}
,"printed":{"data":1}
,"stored":{"database":1}
,"database":{"layout":1}
,"mode":{"select":1,"choose":1}
,"select":{"objects":1,"bold":1,"icon":1}
,"hoose":{"format":1}
,"menu":{"conditional":1,"show":1}
,"dialog":{"box":1}
,"box":{"add":1,"use":1}
,"add":{"define":1}
,"define":{"new":1,"calculation":1}
,"new":{"condition":1}
,"condition":{"condition":1,"formatting":1,"choose":1,"evaluates":1}
,"selected":{"objects":1,"object":1}
,"based":{"common":1,"calculation":1}
,"common":{"conditions":1}
,"choose":{"value":1,"ondition":1,"formula":1,"view":1}
,"value":{"choose":1,"option":1,"condition":1}
,"ondition":{"nd":1}
,"nd":{"set":1}
,"set":{"parameters":1,"multiple":1,"focus":1,"negative":1,"conditional":1}
,"parameters":{"format":1}
,"calculation":{"condition":1,"calculation":1,"dialog":1}
,"formula":{"define":1}
,"elf":{"function":1}
,"function":{"reference":1}
,"reference":{"data":1}
,"object":{"text":1,"onditional":1,"placeholder":1,"all":1,"set":1,"number":1}
,"field":{"fill":1,"data":1,"display":1,"system":1}
,"fill":{"format":1,"color":1}
,"meets":{"conditions":1,"criteria":1,"formatting":1,"conditional":1}
,"yellow":{"field":1,"result":1}
,"criteria":{"apply":1,"conditional":1,"number":1}
,"apply":{"conditional":1}
,"color":{"icons":1,"formatting":1,"filemaker":1,"defined":1,"yellow":1}
,"icons":{"svg":1,"custom":1,"moving":1}
,"svg":{"format":1,"file":1,"grammar":1}
,"buttons":{"popover":1,"button":1}
,"popover":{"buttons":1}
,"button":{"bars":1,"icons":1}
,"bars":{"drop-down":1,"change":1}
,"drop-down":{"lists":1}
,"lists":{"select":1}
,"icon":{"color":1}
,"additional":{"formatting":1}
,"options":{"use":1}
,"moderation":{"affect":1}
,"performance":{"fields":1}
,"fields":{"conditional":1,"objects":1}
,"view":{"menu":1}
,"show":{"conditional":1,"sample":1}
,"badge":{"fields":1}
,"custom":{"icons":1}
,"changing":{"fill":1}
,"filemaker":{"ro":1,"pro":1}
,"ro":{"advanced":1,"svg":1}
,"advanced":{"elements":1,"files":1}
,"elements":{"fill":1}
,"defined":{"svg":1}
,"file":{"filemaker":1,"contain":1}
,"grammar":{"button":1}
,"moving":{"disabling":1}
,"disabling":{"enabling":1}
,"enabling":{"deleting":1}
,"deleting":{"conditional":1}
,"order":{"conditional":1}
,"applied":{"object":1,"conditional":1}
,"onditional":{"formatting":1}
,"non-textual":{"objects":1}
,"rectangular":{"layout":1}
,"placeholder":{"text":1}
,"effects":{"conditional":1}
,"while":{"layout":1}
,"sample":{"data":1}
,"note":{"file":1}
,"contain":{"record":1}
,"record":{"data":1}
,"multiple":{"formatting":1}
,"all":{"conditions":1}
,"evaluated":{"starting":1}
,"starting":{"top":1}
,"top":{"list":1}
,"list":{"each":1}
,"each":{"condition":1}
,"evaluates":{"true":1,"11\u002F20\u002F201":1}
,"true":{"appended":1,"11\u002F20\u002F201":1,"11\u002F21\u002F201":1,"11\u002F19\u002F201":1,"conditional":1}
,"appended":{"objects":1}
,"previous":{"format":1}
,"ignored":{"display":1}
,"state":{"object":1}
,"focus":{"display":1}
,"number":{"date":1,"yellow":1,"days":1}
,"date":{"format":1,"conditional":1,"included":1,"future":1,"true":1}
,"inspector":{"applied":1}
,"therefore":{"preserved":1}
,"preserved":{"if":1}
,"if":{"data":1,"set":1,"use":1,"current":1}
,"combined":{"if":1}
,"negative":{"numbers":1}
,"numbers":{"display":1,"blue":1}
,"blue":{"fill":1}
,"result":{"red":1}
,"system":{"formats":1}
,"formats":{"conditional":1}
,"transferred":{"records":1,"use":1}
,"records":{"copied":1}
,"copied":{"filemaker":1}
,"pro":{"advanced":1}
,"files":{"exported":1,"macos":1}
,"exported":{"filemaker":1}
,"macos":{"if":1}
,"apple":{"events":1}
,"events":{"get":1}
,"get":{"text":1}
,"style":{"conditional":1}
,"option":{"predefined":1}
,"predefined":{"conditions":1}
,"less":{"days":1}
,"passed":{"less":1,"11\u002F16\u002F201":1}
,"current":{"date":1,"day":1}
,"included":{"number":1}
,"inclusive":{"if":1}
,"day":{"data":1}
,"11\u002F20\u002F201":{"hen":1,"true":1}
,"hen":{"less":1}
,"11\u002F16\u002F201":{"false":1}
,"false":{"11\u002F17\u002F2019":1,"11\u002F23\u002F201":1}
,"11\u002F17\u002F2019":{"true":1}
,"11\u002F21\u002F201":{"date":1}
,"future":{"true":1}
,"11\u002F24\u002F201":{"false":1}
,"11\u002F23\u002F201":{"true":1}
,"11\u002F19\u002F201":{"date":1}
}
;Search.control.loadWordPairs(pairs);
