var pairs =
{
"elete":{"account":1}
,"account":{"eletes":1,"account":1,"name":1,"displaying":1,"assigned":1,"full":1,"delete":1,"[account":1,"if":1,"\u0022]":1}
,"eletes":{"account":1}
,"name":{"allows":1,"existing":1,"sales":1,"get":1}
,"allows":{"name":1}
,"existing":{"filemaker":1,"account":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1,"7.0":1}
,"advanced":{"ccount":1}
,"ccount":{"deleted":1}
,"deleted":{"filemaker":1}
,"7.0":{"script":1}
,"script":{"step":1,"script":1,"pane":1}
,"step":{"deletes":1,"enable":1,"right-click":1,"delete":1}
,"deletes":{"account":1,"sales":1,"current":1}
,"displaying":{"dialog":1}
,"dialog":{"box":1,"on]":1,"[\u0022":1}
,"box":{"existing":1}
,"assigned":{"full":1}
,"full":{"access":1}
,"access":{"privilege":1,"privileges":1}
,"privilege":{"set":1}
,"set":{"perform":1}
,"perform":{"script":1}
,"enable":{"users":1}
,"users":{"less":1}
,"less":{"full":1}
,"privileges":{"perform":1,"use":1,"deletes":1,"if":1,"delete":1}
,"right-click":{"current":1}
,"current":{"script":1,"account":1}
,"pane":{"choose":1}
,"choose":{"grant":1}
,"grant":{"full":1}
,"use":{"script":1}
,"delete":{"account":1}
,"sales":{"account":1,"\u0022]":1}
,"[account":{"name":1}
,"\u0022]":{"deletes":1,"delete":1,"end":1}
,"if":{"full":1,"[get":1,"creating":1}
,"[get":{"accountprivilegesetname":1}
,"accountprivilegesetname":{"=\u0022":1}
,"=\u0022":{"[full":1}
,"[full":{"access]":1}
,"access]":{"\u0022]":1}
,"get":{"accountname":1}
,"accountname":{")]":1}
,")]":{"re-login":1}
,"re-login":{"[with":1}
,"[with":{"dialog":1}
,"on]":{"else":1}
,"else":{"show":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"[\u0022":{"privileges":1}
,"end":{"if":1}
,"creating":{"editing":1}
,"editing":{"accounts":1}
,"accounts":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
