var pairs =
{
"onlastwindowclose":{"performs":1,"activates":1,"script":1}
,"performs":{"script":1}
,"script":{"ach":1,"script":1,"step":1,"return":1,"proceeds":1,"canceled":1,"run":1,"performed":1,"executed":1,"trigger":1,"closes":1,"runs":1}
,"ach":{"time":1}
,"time":{"close":1,"last":1}
,"close":{"last":1,"filemaker":1}
,"last":{"window":1,"open":1,"virtual":1}
,"window":{"database":1,"file":1,"script":1}
,"database":{"file":1}
,"file":{"last":1,"closed":1,"itself":1,"open":1,"close":1}
,"closed":{"onlastwindowclose":1,"if":1}
,"activates":{"filemaker":1}
,"filemaker":{"pro":1,"data":1}
,"pro":{"advanced":1,"12.0":1}
,"advanced":{"exits":1}
,"exits":{"mode":1}
,"mode":{"use":1}
,"use":{"exit":1}
,"exit":{"script":1}
,"step":{"ithin":1}
,"ithin":{"triggered":1}
,"triggered":{"script":1}
,"return":{"true":1}
,"true":{"false":1,"event":1}
,"false":{"true":1,"event":1,"value":1}
,"event":{"triggered":1}
,"proceeds":{"false":1}
,"canceled":{"filemaker":1}
,"12.0":{"script":1}
,"run":{"if":1}
,"if":{"file":1,"referenced":1,"script":1}
,"itself":{"remains":1}
,"remains":{"open":1}
,"open":{"if":1,"windows":1,"window":1}
,"referenced":{"by":1}
,"by":{"file":1,"onlastwindowclose":1}
,"windows":{"closing":1}
,"closing":{"script":1}
,"performed":{"each":1}
,"each":{"time":1}
,"executed":{"by":1}
,"trigger":{"returns":1,"activated":1,"result":1}
,"returns":{"false":1}
,"value":{"file":1}
,"data":{"api":1}
,"api":{"custom":1}
,"custom":{"web":1}
,"web":{"publishing":1}
,"publishing":{"onlastwindowclose":1}
,"activated":{"script":1}
,"closes":{"last":1}
,"virtual":{"window":1}
,"runs":{"modes":1}
,"modes":{"trigger":1}
}
;Search.control.loadWordPairs(pairs);
