var pairs =
{
"set":{"data":1,"variable":1}
,"data":{"file":1,"file\u2019s":1,"source":1}
,"file":{"position":1,"file":1,"id":1,"new":1,"start":1,"read-write":1,"size":1,"named":1,"exists":1,"[\u0022$file":1,"[file":1}
,"position":{"sets":1,"open":1,"numeric":1,"filemaker":1,"number":1,"end":1,"file":1,"get":1,"[file":1,"$position":1,"$filesize":1}
,"sets":{"read-write":1}
,"read-write":{"position":1}
,"open":{"data":1,"file":1}
,"id":{"numeric":1,"open":1,"value":1,"new":1,"$fileid":1}
,"numeric":{"expression":1,"xpression":1}
,"expression":{"specifies":1}
,"specifies":{"file":1,"data":1}
,"new":{"position":1,"read-write":1}
,"xpression":{"specifies":1}
,"file\u2019s":{"new":1}
,"filemaker":{"pro":1}
,"pro":{"18.0":1}
,"18.0":{"advanced":1}
,"advanced":{"read-write":1}
,"number":{"bytes":1}
,"bytes":{"file":1}
,"start":{"reading":1}
,"reading":{"writing":1}
,"writing":{"data":1}
,"end":{"file":1,"if":1}
,"size":{"get":1,"script":1,"[\u0022$file":1}
,"get":{"file":1,"lasterror":1,"documentspath":1}
,"script":{"step":1,"[text":1}
,"step":{"if":1}
,"if":{"negative":1,"[not":1,"get":1}
,"negative":{"value":1}
,"value":{"new":1,"stored":1,"get":1}
,"lasterror":{"function":1}
,"function":{"returns":1}
,"returns":{"error":1}
,"error":{"sets":1}
,"stored":{"variable":1}
,"variable":{"set":1,"[$file":1}
,"[file":{"id":1}
,"$position":{"writes":1}
,"writes":{"contents":1}
,"contents":{"utilities":1}
,"utilities":{":log":1}
,":log":{"entry":1}
,"entry":{"field":1,"write":1}
,"field":{"end":1}
,"named":{"change.log":1}
,"change.log":{"documents":1,"get":1}
,"documents":{"folder":1}
,"folder":{"set":1}
,"[$file":{"value":1}
,"documentspath":{"&\u0022":1}
,"&\u0022":{"change.log":1}
,"exists":{"[\u0022$file":1}
,"[\u0022$file":{"target":1}
,"target":{"$fileexists":1,"$filesize":1,"$fileid":1}
,"$fileexists":{"if":1,"exit":1}
,"[not":{"$fileexists":1}
,"exit":{"script":1}
,"[text":{"result":1}
,"result":{"end":1}
,"$filesize":{"open":1,"write":1}
,"$fileid":{"set":1,"new":1,"data":1}
,"write":{"data":1,"utf-8":1}
,"source":{"utilities":1}
,"utf-8":{"append":1}
,"append":{"line":1}
,"line":{"feed":1}
,"feed":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
