var pairs =
{
"delete":{"portal":1,"record\u002Frequest":1,"product":1,"&products":1}
,"portal":{"row":1,"displays":1}
,"row":{"eletes":1,"dialog":1,"filemaker":1,"script":1,"selected":1,"if":1,"[with":1,"show":1}
,"eletes":{"selected":1}
,"selected":{"portal":1,"use":1,"script":1}
,"dialog":{"specifies":1,"box":1,"on]":1,"[\u0022":1,"off]":1}
,"specifies":{"display":1}
,"display":{"dialog":1}
,"box":{"script":1}
,"script":{"step":1}
,"step":{"performed":1,"control":1,"if":1,"deletes":1,"filemaker":1,"portal":1,"commit":1}
,"performed":{"users":1,"if":1}
,"users":{"confirm":1}
,"confirm":{"deletion":1}
,"deletion":{"portal":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"undo":1}
,"undo":{"delete":1}
,"control":{"row":1}
,"use":{"go":1,"cript":1,"commit":1}
,"go":{"portal":1}
,"if":{"portal":1,"user":1,"product":1,"[products":1,"if":1,"[get":1,"adding":1}
,"displays":{"records":1,"related":1}
,"records":{"related":1,"current":1,"layout":1,"automating":1}
,"related":{"table":1,"record":1,"records":1}
,"table":{"script":1,"additional":1}
,"deletes":{"related":1,"current":1}
,"record":{"if":1,"performing":1}
,"current":{"table":1,"record":1,"portal":1}
,"performing":{"delete":1}
,"record\u002Frequest":{"script":1}
,"webdirect":{"af":1}
,"af":{"ter":1}
,"ter":{"use":1}
,"cript":{"step":1}
,"layout":{"use":1}
,"commit":{"records\u002Frequests":1,"deletion":1,"action":1}
,"records\u002Frequests":{"script":1}
,"additional":{"commit":1}
,"action":{"if":1}
,"user":{"delete":1}
,"product":{"discontinued":1,"current":1}
,"discontinued":{"if":1,"\u0022]":1}
,"[products":{":availability":1}
,":availability":{"=\u0022":1}
,"=\u0022":{"discontinued":1}
,"\u0022]":{"delete":1,"if":1}
,"[with":{"dialog":1}
,"on]":{"end":1}
,"end":{"if":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"[\u0022":{"want":1}
,"want":{"delete":1}
,"&products":{":name":1}
,":name":{"&\u0022":1}
,"&\u0022":{"\u0022]":1}
,"[get":{"lastmessagechoice":1}
,"lastmessagechoice":{"=1]":1}
,"=1]":{"delete":1}
,"off]":{"end":1}
,"adding":{"duplicating":1}
,"duplicating":{"deleting":1}
,"deleting":{"records":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
