var pairs =
{
"getfield":{"evaluates":1,"fieldname":1,"phone":1,"calculated":1,"returns":1,"contactmethod":1,"function":1,"suppose":1,"sortselection":1}
,"evaluates":{"fieldname":1}
,"fieldname":{"returns":1,"fieldname":1,"-any":1,"matches":1,"double":1,"getfield":1,"quotation":1,"field":1}
,"returns":{"contents":1,"value":1,"company":1,"change":1,"values":1}
,"contents":{"field":1,"customer":1}
,"field":{"getfield":1,"refers":1,"table":1,"return":1,"name":1,"value":1,"match":1,"defined":1,"by":1,"city":1,"sortselection":1,"sortkey":1,"go":1,"found":1,"if":1}
,"-any":{"text":1}
,"text":{"expression":1,"field":1,"number":1}
,"expression":{"text":1}
,"refers":{"field\u2019s":1}
,"field\u2019s":{"name":1}
,"name":{"text":1,"across":1,"field":1,"sortkey":1,"subsummary":1}
,"number":{"date":1}
,"date":{"time":1}
,"time":{"timestamp":1}
,"timestamp":{"container":1}
,"container":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"getfield":1}
,"matches":{"result":1,"name":1}
,"result":{"field":1}
,"table":{"calculation":1,"returns":1,"return":1,"change":1,"table":1,"fields":1}
,"calculation":{"performed":1,"field":1}
,"performed":{"returns":1}
,"return":{"values":1}
,"values":{"fields":1,"multiple":1,"customer":1,"city":1,"returned":1}
,"fields":{"field":1,"enclose":1,"customer":1}
,"across":{"multiple":1}
,"multiple":{"tables":1,"fields":1}
,"tables":{"enclose":1}
,"enclose":{"fieldname":1}
,"double":{"quotation":1}
,"quotation":{"marks":1}
,"marks":{"getfield":1}
,"phone":{"returns":1,"getfield":1}
,"value":{"customer":1,"matches":1,"getfield":1,"field":1}
,"customer":{":phone":1,"table":1,":contactmethod":1,":email":1,"name":1}
,":phone":{"getfield":1,"customer":1}
,"calculated":{"customer":1,"company":1}
,"company":{":phone":1,"table":1}
,"change":{"value":1,"perform":1}
,"match":{"name":1}
,":contactmethod":{"customer":1,"phone":1,"email":1}
,":email":{"customer":1,"if":1}
,"contactmethod":{"returns":1}
,"email":{"getfield":1}
,"if":{"sort":1,"sortselection":1}
,"sort":{"records":1,"by":1,"automatically":1,"operation":1}
,"records":{"calculation":1,"display":1,"sortkey":1,"[restore":1,"sorted":1}
,"defined":{"by":1,"getfield":1}
,"by":{"getfield":1,"changing":1,"sortkey":1,"customer":1,"city":1}
,"function":{"dynamically":1}
,"dynamically":{"sort":1}
,"display":{"subsummary":1}
,"subsummary":{"data":1}
,"data":{"by":1,"records":1,"displayed":1}
,"changing":{"value":1}
,"suppose":{"database":1}
,"database":{"fields":1}
,"city":{"text":1,"sortkey":1,"field":1,"subsummary":1}
,"sortselection":{"global":1,"script":1,"customer":1,"changed":1}
,"global":{"field":1}
,"sortkey":{"calculation":1,"field":1,"returns":1,"displayed":1,"sort":1,"change":1}
,"script":{"invoices":1}
,"invoices":{"layout":1,"invoices":1,")]":1}
,"layout":{"sorts":1,"[\u0022":1}
,"sorts":{"records":1}
,"go":{"layout":1,"record\u002Frequest\u002Fpage":1}
,"[\u0022":{"invoices":1}
,")]":{"sort":1}
,"[restore":{"dialog":1}
,"dialog":{"off]":1}
,"off]":{"sort":1}
,"record\u002Frequest\u002Fpage":{"[first]":1}
,"[first]":{"if":1}
,"found":{"set":1}
,"set":{"sorted":1,"re-sorted":1}
,"sorted":{"by":1}
,"displayed":{"customer":1,"city":1}
,"changed":{"contain":1}
,"contain":{"city":1}
,"re-sorted":{"by":1}
,"automatically":{"updated":1}
,"updated":{"values":1}
,"returned":{"by":1}
,"perform":{"sort":1}
}
;Search.control.loadWordPairs(pairs);
