var pairs =
{
"go":{"layout":1,"specifies":1,"filemaker":1,"layouts":1,"field":1}
,"layout":{"witches":1,"original":1,"active":1,"script":1,"specifies":1,"by":1,"name":1,"number":1,"numbers":1,"filemaker":1,"displayed":1,"want":1,"list":1,"[\u0022":1,"menu":1,"layout":1,"if":1,"while":1}
,"witches":{"layout":1}
,"original":{"layout":1}
,"active":{"layout":1,"window":1}
,"script":{"initiated":1,"step":1,"sure":1,"itself":1,"file":1,"first":1,"script":1}
,"initiated":{"layout":1}
,"specifies":{"layout":1,"formula":1,"animation":1}
,"by":{"name":1,"calculation":1}
,"name":{"list":1,"by":1,"layout":1,"select":1,"source":1,"clarity":1}
,"list":{"layouts":1,"use":1}
,"layouts":{"you\u2019ve":1,"file":1,"defined":1,"external":1,"names":1,"name":1,"verify":1,"go":1,"automating":1}
,"you\u2019ve":{"defined":1}
,"defined":{"file":1}
,"file":{"layout":1,"animation":1,"script":1,"define":1,"go":1,"perform":1,"two":1}
,"calculation":{"specifies":1,"recognizes":1,"define":1,"field":1}
,"formula":{"result":1}
,"result":{"valid":1}
,"valid":{"layout":1}
,"number":{"by":1,"layout":1}
,"numbers":{"correspond":1,"layouts":1}
,"correspond":{"order":1}
,"order":{"layouts":1,"created":1}
,"animation":{"filemaker":1,"use":1,"zoom":1}
,"filemaker":{"go":1,"pro":1}
,"use":{"switching":1,"layout":1,"animations":1}
,"switching":{"new":1,"layouts":1}
,"new":{"layout":1}
,"pro":{"6.0":1,"advanced":1}
,"6.0":{"earlier":1}
,"earlier":{"script":1}
,"step":{"script":1,"take":1,"call":1,"layout":1}
,"sure":{"user":1}
,"user":{"starts":1}
,"starts":{"correct":1}
,"correct":{"layout":1}
,"displayed":{"go":1}
,"take":{"layouts":1}
,"itself":{"go":1}
,"external":{"file":1}
,"define":{"script":1,"unstored":1}
,"call":{"script":1}
,"first":{"file":1}
,"perform":{"script":1}
,"recognizes":{"layouts":1}
,"names":{"order":1}
,"created":{"if":1}
,"if":{"multiple":1,"[patterncount":1,"sort":1}
,"multiple":{"layouts":1}
,"select":{"specific":1}
,"specific":{"layout":1}
,"want":{"layout":1}
,"unstored":{"calculation":1}
,"field":{"get":1,"invoice":1,"[invoices":1}
,"get":{"layoutnumber":1,"applicationversion":1}
,"layoutnumber":{"function":1}
,"function":{"place":1}
,"place":{"layouts":1}
,"verify":{"layout":1}
,"two":{"tables":1}
,"tables":{"filemaker":1}
,"advanced":{"appends":1,")]":1}
,"appends":{"name":1}
,"source":{"table":1}
,"table":{"layout":1}
,"clarity":{"go":1}
,"[\u0022":{"ayout":1,"invoice":1,"customers":1,"contacts":1}
,"ayout":{"tableb":1}
,"tableb":{")]":1}
,")]":{"can\u2019t":1,"go":1}
,"can\u2019t":{"use":1}
,"animations":{"switching":1}
,"menu":{"item":1}
,"item":{"status":1}
,"status":{"toolbar":1}
,"toolbar":{"buttons":1}
,"buttons":{"active":1}
,"window":{"oes":1}
,"oes":{"summary":1}
,"summary":{"field":1}
,"invoice":{"details":1}
,"details":{"layout":1,"\u0022]":1}
,"\u0022]":{"go":1,"else":1,"end":1}
,"[invoices":{":summary]":1}
,":summary]":{"checks":1}
,"checks":{"device":1}
,"device":{"running":1}
,"running":{"database":1}
,"database":{"layout":1}
,"[patterncount":{"get":1}
,"applicationversion":{"ipad":1,"pro":1}
,"ipad":{")]":1,"\u0022]":1}
,"customers":{"ipad":1,"\u0022]":1,"iphone":1}
,"else":{"if":1,"go":1}
,"iphone":{"\u0022]":1}
,"end":{"if":1}
,"sort":{"records":1}
,"records":{"[restore":1}
,"[restore":{"dialog":1}
,"dialog":{"off]":1}
,"off]":{"switches":1}
,"switches":{"contacts":1}
,"contacts":{"layout":1,"animation":1}
,"while":{"zooming":1}
,"zooming":{"go":1}
,"zoom":{"in]":1}
,"in]":{"switching":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
