var pairs =
{
"saving":{"managing":1,"theme":1}
,"managing":{"layout":1}
,"layout":{"themes":1,"styles":1}
,"themes":{"create":1,"filemaker":1,"dialog":1,"file":1}
,"create":{"themes":1,"new":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"by":1,"files":1}
,"by":{"layout":1}
,"styles":{"saving":1,"layouts":1,"theme":1}
,"theme":{"create":1,"rename":1,"can\u2019t":1,"use":1,"applied":1}
,"new":{"theme":1}
,"rename":{"current":1,"duplicate":1}
,"current":{"theme":1}
,"can\u2019t":{"use":1}
,"use":{"styles":1,"manage":1}
,"layouts":{"save":1,"each":1}
,"save":{"styles":1}
,"manage":{"themes":1}
,"dialog":{"box":1}
,"box":{"themes":1}
,"file":{"layouts":1,"import":1}
,"each":{"theme":1}
,"applied":{"rename":1}
,"duplicate":{"delete":1}
,"delete":{"themes":1}
,"import":{"themes":1}
}
;Search.control.loadWordPairs(pairs);
