var pairs =
{
"hiding":{"field":1}
,"field":{"frames":1,"layout":1,"objects":1,"edit":1,"active":1,"frame":1,"show":1}
,"frames":{"set":1,"record":1,"outline":1,"unnecessary":1,"field":1,"layout":1}
,"set":{"field":1}
,"record":{"active":1}
,"active":{"browse":1,"show":1,"field":1,"find":1}
,"browse":{"mode":1}
,"mode":{"find":1,"field":1,"choose":1}
,"find":{"mode":1}
,"outline":{"each":1}
,"each":{"field":1}
,"layout":{"dotted":1,"mode":1,"want":1,"pop-up":1,"setup":1,"bar":1}
,"dotted":{"line":1}
,"line":{"fields":1}
,"fields":{"easy":1}
,"easy":{"users":1}
,"users":{"borders":1}
,"borders":{"field":1}
,"objects":{"field":1}
,"unnecessary":{"layout":1}
,"choose":{"layout":1}
,"want":{"layout":1}
,"pop-up":{"menu":1}
,"menu":{"layout":1}
,"setup":{"layout":1,"button":1,"dialog":1}
,"button":{"layout":1}
,"bar":{"layout":1}
,"dialog":{"box":1}
,"box":{"select":1}
,"select":{"clear":1}
,"clear":{"show":1}
,"show":{"field":1,"hide":1}
,"hide":{"field":1}
,"edit":{"field":1}
,"frame":{"badge":1}
,"badge":{"disappear":1}
,"disappear":{"tab":1}
,"tab":{"field":1}
}
;Search.control.loadWordPairs(pairs);
