var pairs =
{
"creating":{"portals":1}
,"portals":{"master-detail":1,"add":1,"current":1,"related":1,"records":1}
,"master-detail":{"layouts":1,"layout":1}
,"layouts":{"create":1,"records":1}
,"create":{"master-detail":1,"portal":1}
,"records":{"current":1,"choose":1,"display":1,"found":1,"saving":1}
,"current":{"found":1,"table":1,"sort":1,"record":1,"find":1,"portal":1}
,"found":{"set":1}
,"set":{"users":1,"fields":1,"current":1,"clicking":1,"add":1}
,"users":{"choose":1,"identify":1}
,"choose":{"list":1,"current":1,"fields":1,"portal":1}
,"list":{"items":1}
,"items":{"master":1}
,"master":{"layout":1,"weight":1,"portal":1}
,"layout":{"view":1,"products":1,"master":1,"want":1,"operate":1,"create":1,"differences":1}
,"view":{"detail":1}
,"detail":{"item":1,"layout":1,"set":1}
,"item":{"master-detail":1}
,"products":{"product":1,"illustrating":1}
,"product":{"names":1,"displayed":1,"id":1}
,"names":{"listed":1}
,"listed":{"master":1}
,"weight":{"price":1,"unit":1}
,"price":{"selected":1,"placing":1}
,"selected":{"product":1,"row":1}
,"displayed":{"detail":1}
,"portal":{"records":1,"product":1,"weight":1,"portal":1,"tool":1,"drag":1,"size":1,"setup":1,"number":1,"background":1,"rows":1,"dialog":1,"add":1,"action":1,"adding":1,"row":1,"master-detail":1}
,"table":{"allow":1,"show":1,"portals":1,"sorting":1,"displaying":1,"related":1}
,"allow":{"users":1,"filter":1}
,"identify":{"record":1}
,"record":{"add":1,"current":1,"row":1,"related":1,"choose":1,"navigating":1}
,"add":{"fields":1,"portal":1,"button":1,"delete":1}
,"fields":{"portal":1,"show":1,"layou":1,"want":1,"first":1,"tab":1}
,"id":{"name":1}
,"name":{"steps":1}
,"steps":{"detail":1}
,"show":{"selected":1,"records":1,"scroll":1}
,"row":{"portal":1,"existing":1,"row":1,"active":1,"each":1,"current":1,"don\u2019t":1,"choose":1,"all":1,"moving":1}
,"unit":{"price":1}
,"placing":{"removing":1}
,"removing":{"fields":1}
,"layou":{"master-detail":1}
,"illustrating":{"layout":1}
,"want":{"add":1,"portal":1}
,"tool":{"portal":1,"status":1}
,"status":{"toolbar":1}
,"toolbar":{"position":1}
,"position":{"crosshair":1}
,"crosshair":{"pointer":1}
,"pointer":{"layout":1,"diagonally":1}
,"drag":{"pointer":1,"objects":1}
,"diagonally":{"portal":1}
,"size":{"want":1}
,"setup":{"dialog":1}
,"dialog":{"box":1}
,"box":{"show":1,"choose":1}
,"scroll":{"bar":1}
,"bar":{"choo":1}
,"choo":{"se":1}
,"se":{"option":1}
,"option":{"select":1}
,"select":{"format":1}
,"format":{"options":1}
,"options":{"portal":1}
,"number":{"rows":1}
,"rows":{"portal":1,"ormatting":1,"add":1,"committed":1,"moving":1}
,"background":{"color":1}
,"color":{"portal":1}
,"ormatting":{"portals":1}
,"objects":{"fields":1,"layout":1}
,"first":{"row":1}
,"existing":{"portal":1}
,"action":{"portals":1,"object":1}
,"related":{"table":1}
,"sorting":{"filtering":1}
,"filtering":{"records":1}
,"display":{"all":1,"row":1}
,"all":{"records":1,"current":1,"portal":1}
,"sort":{"order":1,"rows":1}
,"order":{"allow":1,"created":1}
,"filter":{"sort":1}
,"clicking":{"row":1}
,"active":{"navigate":1}
,"navigate":{"record":1}
,"button":{"action":1}
,"object":{"portal":1}
,"adding":{"deleting":1}
,"deleting":{"rows":1}
,"delete":{"record":1}
,"displaying":{"find":1}
,"find":{"requests":1,"request":1}
,"requests":{"display":1}
,"each":{"find":1}
,"request":{"order":1,"committing":1}
,"created":{"display":1}
,"committing":{"commit":1}
,"commit":{"all":1,"current":1}
,"don\u2019t":{"commit":1}
,"committed":{"commit":1}
,"navigating":{"fields":1}
,"tab":{"key":1}
,"key":{"finding":1}
,"finding":{"replacing":1}
,"replacing":{"data":1}
,"data":{"checking":1,"excel":1}
,"checking":{"spelling":1}
,"spelling":{"copying":1}
,"copying":{"records":1}
,"saving":{"data":1}
,"excel":{"file":1}
,"file":{"operations":1}
,"operations":{"operate":1}
,"operate":{"current":1,"all":1}
,"moving":{"objects":1}
,"differences":{"portals":1}
}
;Search.control.loadWordPairs(pairs);
