var pairs =
{
"onstraining":{"narrowing":1}
,"narrowing":{"found":1}
,"found":{"set":1}
,"set":{"constraining":1,"narrow":1,"perform":1,"aking":1,"first":1,"sales":1,"boolean":1,"xample":1}
,"constraining":{"found":1}
,"narrow":{"find":1,"search":1,"found":1}
,"find":{"incrementally":1,"records":1,"next":1,"database":1,"request":1,"mode":1,"sales":1}
,"incrementally":{"specific":1}
,"specific":{"detail":1}
,"detail":{"search":1}
,"search":{"database":1,"perform":1,"choose":1,"all":1}
,"database":{"find":1,"found":1}
,"records":{"based":1}
,"based":{"multiple":1}
,"multiple":{"criteria":1}
,"criteria":{"separate":1,"choose":1,"narrow":1}
,"separate":{"fields":1}
,"fields":{"logical":1}
,"logical":{"search":1}
,"perform":{"find":1}
,"next":{"criteria":1}
,"choose":{"requests":1}
,"requests":{"menu":1}
,"menu":{"constrain":1}
,"constrain":{"found":1,"narrow":1}
,"aking":{"find":1}
,"request":{"switch":1,"type":1}
,"switch":{"back":1}
,"back":{"find":1}
,"mode":{"type":1,"enter":1}
,"type":{"criteria":1,"alvarez":1}
,"first":{"search":1}
,"all":{"employees":1}
,"employees":{"sales":1,"named":1}
,"sales":{"constrain":1,"employees":1,"department":1}
,"named":{"alvarez":1}
,"alvarez":{"perform":1,"last":1}
,"department":{"field":1}
,"field":{"go":1,"choose":1}
,"go":{"find":1}
,"enter":{"second":1}
,"second":{"find":1}
,"last":{"name":1}
,"name":{"field":1}
,"boolean":{"constrain":1}
}
;Search.control.loadWordPairs(pairs);
