var pairs =
{
"er":{"tin":1}
,"tin":{"trial":1}
,"trial":{"version":1,"copy":1,"dialog":1}
,"version":{"full":1,"filemaker":1,"all":1,"running":1,"convert":1}
,"full":{"version":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"convert":1,"full":1,"uninstalling":1,"data":1,"start":1,"filemaker":1,"trial":1,"follow":1,"license":1,"upgrade":1,"creating":1}
,"convert":{"copy":1,"trial":1}
,"copy":{"trial":1,"filemaker":1}
,"uninstalling":{"trial":1}
,"all":{"settings":1}
,"settings":{"recent":1}
,"recent":{"files":1}
,"files":{"list":1,"host":1}
,"list":{"fa":1}
,"fa":{"vorite":1}
,"vorite":{"files":1}
,"host":{"preserved":1}
,"preserved":{"continue":1}
,"continue":{"filemaker":1}
,"data":{"uninterrupted":1}
,"uninterrupted":{"note":1}
,"note":{"ou":1}
,"ou":{"internet":1}
,"internet":{"connection":1}
,"connection":{"convert":1}
,"start":{"trial":1}
,"dialog":{"box":1}
,"box":{"appears":1,"enter":1,"filemaker":1}
,"appears":{"if":1,"enter":1}
,"if":{"trial":1,"entered":1}
,"running":{"choose":1}
,"choose":{"help":1}
,"help":{"menu":1}
,"menu":{"filemaker":1}
,"follow":{"onscreen":1}
,"onscreen":{"instructions":1}
,"instructions":{"purchasing":1}
,"purchasing":{"filemaker":1}
,"license":{"key":1}
,"key":{"by":1,"safe":1,"return":1,"next":1,"new":1,"filemaker":1,"earlier":1}
,"by":{"email":1}
,"email":{"ke":1}
,"ke":{"ep":1}
,"ep":{"license":1}
,"safe":{"place":1}
,"place":{"case":1}
,"case":{"software":1}
,"software":{"reinstalled":1}
,"reinstalled":{"you\u2019ve":1}
,"you\u2019ve":{"received":1}
,"received":{"license":1}
,"return":{"filemaker":1}
,"enter":{"license":1,"user":1}
,"next":{"filemaker":1}
,"user":{"name":1}
,"name":{"organization":1,"optional":1}
,"organization":{"optional":1,"license":1}
,"optional":{"license":1,"organization":1}
,"new":{"product":1}
,"product":{"indows":1,"full":1}
,"indows":{"yo":1}
,"yo":{"provide":1}
,"provide":{"administrator":1}
,"administrator":{"login":1}
,"login":{"credentials":1}
,"credentials":{"computer":1}
,"computer":{"if":1}
,"entered":{"upgrade":1}
,"upgrade":{"license":1,"dialog":1}
,"earlier":{"product":1}
,"creating":{"runtime":1}
,"runtime":{"solutions":1}
,"solutions":{"trial":1}
}
;Search.control.loadWordPairs(pairs);
