var pairs =
{
"get":{"documen":1,"documentspath":1,"documents":1}
,"documen":{"tspath":1}
,"tspath":{"returns":1}
,"returns":{"path":1,"location":1,"empty":1,"\u002Fc:\u002Fusers\u002Fjohn":1,"\u002Fc:\u002Fprogram":1}
,"path":{"documents":1,"current":1,"format":1,"vary":1,"follow":1,"get":1}
,"documents":{"folder":1,"path":1}
,"folder":{"current":1,"path":1,"documents":1,"shared":1,"user":1}
,"current":{"user":1,"user\u2019s":1,"documents":1}
,"user":{"get":1,"named":1,"document":1}
,"documentspath":{"none":1,"returns":1,"get":1}
,"none":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1,"go":1,"server":1,"cloud":1,"webdirect":1,"data":1}
,"pro":{"8.0":1,"advanced":1}
,"8.0":{"filemaker":1}
,"advanced":{"filemaker":1,"user":1}
,"go":{"returns":1}
,"user\u2019s":{"documents":1}
,"format":{"varies":1}
,"varies":{"by":1}
,"by":{"operating":1}
,"operating":{"system":1}
,"system":{"running":1}
,"running":{"server-side":1}
,"server-side":{"scripts":1}
,"scripts":{"get":1,"sessions":1}
,"location":{"documents":1,"scripts":1}
,"shared":{"location":1}
,"sessions":{"processes":1}
,"processes":{"machine":1}
,"machine":{"use":1}
,"use":{"import":1}
,"import":{"export":1}
,"export":{"files":1}
,"files":{"filemaker":1}
,"server":{"help":1,"returns":1}
,"help":{"filemaker":1}
,"cloud":{"help":1}
,"webdirect":{"filemaker":1}
,"data":{"api":1}
,"api":{"custom":1}
,"custom":{"web":1}
,"web":{"publishing":1}
,"publishing":{"function":1}
,"function":{"supported":1}
,"supported":{"returns":1}
,"empty":{"string":1}
,"string":{"filemaker":1}
,"named":{"john":1}
,"john":{"smith":1}
,"smith":{"returns":1}
,"\u002Fc:\u002Fusers\u002Fjohn":{"smith\u002Fdocuments\u002Fin":1}
,"smith\u002Fdocuments\u002Fin":{"windows":1}
,"windows":{"\u002Fmacintosh":1}
,"\u002Fmacintosh":{"hd\u002Fusers\u002Fjohnsmith\u002Fdocuments\u002Fin":1,"hd\u002Flibrary\u002Ffilemaker":1}
,"hd\u002Fusers\u002Fjohnsmith\u002Fdocuments\u002Fin":{"macos":1}
,"macos":{"filemaker":1,"each":1}
,"\u002Fc:\u002Fprogram":{"files\u002Ffilemaker\u002Ffilemaker":1}
,"files\u002Ffilemaker\u002Ffilemaker":{"server\u002Fdata\u002Fdocuments\u002Fin":1}
,"server\u002Fdata\u002Fdocuments\u002Fin":{"windows":1,"macos":1}
,"hd\u002Flibrary\u002Ffilemaker":{"server\u002Fdata\u002Fdocuments\u002Fin":1}
,"each":{"part":1}
,"part":{"path":1}
,"vary":{"examples":1}
,"examples":{"rely":1}
,"rely":{"path":1}
,"follow":{"pattern":1}
,"pattern":{"script":1}
,"script":{"set":1,"step":1}
,"set":{"variable":1}
,"variable":{"script":1}
,"step":{"get":1}
,"document":{"folder":1}
}
;Search.control.loadWordPairs(pairs);
