var pairs =
{
"get":{"network":1,"networktype":1}
,"network":{"type":1,"access":1,"wi-fi":1,"products":1,"get":1}
,"type":{"filemaker":1,"network":1,"unknown":1}
,"filemaker":{"go":1,"pro":1,"platform":1}
,"go":{"returns":1}
,"returns":{"number":1,"if":1,"empty":1,"file":1}
,"number":{"representing":1,"filemaker":1}
,"representing":{"type":1}
,"access":{"current":1}
,"current":{"file":1}
,"file":{"get":1,"local":1,"ios":1,"accessed":1}
,"networktype":{"none":1,"get":1}
,"none":{"number":1}
,"pro":{"13.0":1}
,"13.0":{"filemaker":1}
,"if":{"current":1,"network":1}
,"local":{"file":1}
,"ios":{"device":1}
,"device":{"if":1}
,"unknown":{"cellular":1}
,"cellular":{"network":1}
,"wi-fi":{"network":1}
,"products":{"filemaker":1}
,"platform":{"function":1}
,"function":{"supported":1}
,"supported":{"returns":1}
,"empty":{"string":1}
,"string":{"returns":1}
,"accessed":{"wi-fi":1}
}
;Search.control.loadWordPairs(pairs);
