var pairs =
{
"creating":{"dynamic":1,"subtotals":1}
,"dynamic":{"reports":1}
,"reports":{"table":1}
,"table":{"view":1,"leading":1,"trailing":1,"group":1}
,"view":{"use":1,"browse":1,"quick":1,"impact":1,"remove":1,"creates":1,"display":1}
,"use":{"table":1,"grouping":1}
,"browse":{"mode":1}
,"mode":{"group":1,"right-click":1}
,"group":{"data":1,"by":1,"automatically":1,"summary":1,"field":1,"records":1,"display":1}
,"data":{"by":1,"display":1,"note":1,"choose":1,"cities":1,"earlier":1}
,"by":{"field":1,"city":1,"population":1}
,"field":{"display":1,"create":1,"want":1,"name":1,"grouping":1,"field":1,"running":1,"count":1,"if":1,"100":1,"maximum":1,"standard":1,"each":1,"total":1,"find":1,"choose":1,"displays":1,"subtotals":1,"browse":1,"remove":1}
,"display":{"subtotals":1,"grand":1,"sales":1,"name":1,"categories":1,"subtotal":1}
,"subtotals":{"field":1,"each":1,"choose":1,"trailing":1,"leading":1,"deselect":1,"shortcut":1,"table":1,"remove":1}
,"create":{"subtotals":1}
,"each":{"group":1,"city":1,"record":1,"option":1,"salesperson":1,"subtotal":1}
,"grand":{"total":1,"summary":1,"totals":1}
,"total":{"group":1,"calculate":1,"values":1,"show":1,"current":1,"all":1,"sales":1,"field":1,"right-click":1}
,"note":{"view":1,"removing":1}
,"quick":{"report":1}
,"report":{"table":1}
,"impact":{"current":1}
,"current":{"layout":1,"all":1}
,"layout":{"browse":1}
,"right-click":{"column":1,"left":1}
,"column":{"heading":1}
,"heading":{"field":1}
,"want":{"use":1,"display":1,"add":1,"remove":1}
,"grouping":{"data":1}
,"choose":{"add":1,"remove":1,"leading":1,"options":1,"file":1,"summary":1,"color":1}
,"add":{"leading":1,"trailing":1,"summary":1,"group":1,"leading\u002Ftrailing":1}
,"leading":{"group":1,"subtotals":1,"end":1,"trailing":1,"subtotal":1,"groups":1,"grand":1}
,"name":{"add":1,"if":1,"each":1,"remove":1,"browse":1,"change":1}
,"trailing":{"group":1,"subtotals":1,"displays":1,"groups":1,"subtotal":1,"grand":1}
,"if":{"want":1,"field":1,"leading":1}
,"sales":{"data":1,"attributed":1}
,"city":{"add":1,"choose":1,"if":1,"adding":1}
,"summary":{"row":1,"rows":1,"fields":1,"add":1,"new":1,"by":1,"subtotal":1,"field":1}
,"row":{"end":1,"records":1,"right-click":1,"choose":1,"table":1,"displays":1}
,"end":{"records":1,"table":1}
,"records":{"each":1,"by":1,"browse":1,"contain":1}
,"adding":{"leading\u002Ftrailing":1}
,"leading\u002Ftrailing":{"group":1,"groups":1}
,"automatically":{"sorts":1}
,"sorts":{"records":1}
,"cities":{"listed":1}
,"listed":{"alphabetical":1}
,"alphabetical":{"order":1}
,"order":{"display":1}
,"left":{"margin":1,"right":1}
,"margin":{"summary":1,"row":1}
,"groups":{"multiple":1,"average":1,"minimum":1,"table":1,"trailing":1,"browse":1}
,"multiple":{"fields":1}
,"fields":{"display":1,"database":1,"choose":1,"remove":1}
,"categories":{"each":1}
,"remove":{"leading":1,"trailing":1,"subtotal":1,"summary":1,"delete":1,"group":1,"subtotals":1,"grand":1}
,"options":{"shortcut":1,"want":1}
,"shortcut":{"menu":1}
,"menu":{"select":1,"note":1,"manage":1,"creating":1}
,"select":{"total":1}
,"calculate":{"total":1,"average":1,"population":1,"ratio":1}
,"values":{"field":1,"value":1}
,"running":{"total":1,"count":1}
,"show":{"cumulative":1,"lowest":1,"number":1}
,"cumulative":{"total":1,"count":1}
,"all":{"previous":1,"values":1}
,"previous":{"sorted":1}
,"sorted":{"groups":1}
,"average":{"calculate":1,"values":1}
,"count":{"count":1,"number":1,"100":1,"show":1,"current":1}
,"number":{"records":1,"earliest":1,"date":1}
,"contain":{"value":1}
,"value":{"field":1,"each":1}
,"100":{"values":1,"running":1}
,"record":{"result":1}
,"result":{"count":1}
,"minimum":{"show":1}
,"lowest":{"number":1}
,"earliest":{"date":1}
,"date":{"time":1}
,"time":{"timestamp":1}
,"timestamp":{"field":1}
,"maximum":{"show":1}
,"standard":{"deviation":1}
,"deviation":{"find":1,"mean":1,"by":1,"fraction":1}
,"find":{"values":1,"fraction":1}
,"option":{"calculates":1}
,"calculates":{"standard":1}
,"mean":{"values":1}
,"population":{"calculate":1,"standard":1}
,"fraction":{"total":1}
,"ratio":{"value":1}
,"attributed":{"each":1}
,"salesperson":{"new":1}
,"new":{"row":1}
,"displays":{"subtotal":1,"subtotals":1,"grand":1,"summary":1}
,"subtotal":{"field":1,"each":1,"display":1,"summary":1,"data":1,"grand":1,"group":1}
,"rows":{"display":1}
,"deselect":{"options":1}
,"removing":{"subtotals":1}
,"database":{"remove":1,"choose":1,"fields":1}
,"file":{"menu":1}
,"manage":{"database":1}
,"delete":{"gr":1}
,"gr":{"oup":1}
,"oup":{"subtotal":1}
,"earlier":{"topic":1}
,"topic":{"browse":1}
,"totals":{"choose":1,"remove":1,"table":1}
,"change":{"color":1}
,"color":{"row":1,"part":1,"shortcut":1}
,"right":{"margin":1}
,"part":{"color":1}
,"creates":{"summary":1}
}
;Search.control.loadWordPairs(pairs);
