var pairs =
{
"fieldrepetitions":{"eturns":1,"filename":1,"customers":1}
,"eturns":{"number":1}
,"number":{"orientation":1,"repetitions":1}
,"orientation":{"repetitions":1,"field":1,"data":1}
,"repetitions":{"repeating":1,"horizontal":1,"fieldname":1,"field":1,"formatted":1,"vertical":1}
,"repeating":{"field":1}
,"field":{"formatted":1,"layout":1,"currently":1,"repetitions":1,"defined":1,"returns":1}
,"formatted":{"layout":1,"number":1,"show":1}
,"layout":{"fieldrepetitions":1,"file":1,"text":1,"orientation":1}
,"filename":{"layoutname":1,"-the":1}
,"layoutname":{"fieldname":1,"-the":1}
,"fieldname":{"filename":1,"-the":1,"currently":1,"isn\u2019t":1}
,"-the":{"name":1}
,"name":{"open":1,"layout":1,"field":1}
,"open":{"database":1}
,"database":{"file":1}
,"file":{"local":1,"fieldname":1}
,"local":{"remote":1}
,"remote":{"layoutname":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"function":1}
,"function":{"returns":1}
,"returns":{"number":1,"vertical":1}
,"currently":{"formatted":1}
,"horizontal":{"vertical":1}
,"vertical":{"number":1,"fieldrepetitions":1,"if":1,"orientation":1}
,"defined":{"if":1,"repeating":1}
,"if":{"fieldname":1,"business":1}
,"isn\u2019t":{"repeating":1}
,"customers":{"data":1}
,"data":{"entry":1}
,"entry":{"business":1,"layout":1}
,"business":{"phone":1}
,"phone":{"returns":1,"field":1}
,"show":{"repetitions":1}
}
;Search.control.loadWordPairs(pairs);
