var pairs =
{
"getavplayerattribute":{"returns":1,"attributename":1}
,"returns":{"setting":1,"value":1,"empty":1,"data":1,"if":1,"number":1}
,"setting":{"attribute":1,"fill":1,"fit":1}
,"attribute":{"audio":1,"text":1,"returns":1}
,"audio":{"video":1,"embedded":1,"continues":1,"number":1}
,"video":{"image":1,"files":1,"file":1,"paused":1,"continue":1,"displayed":1,"scaled":1,"stretched":1,"played":1,"30":1}
,"image":{"file":1}
,"file":{"container":1,"playing":1,"played":1,"play":1,"if":1,"displays":1}
,"container":{"field":1}
,"field":{"getavplayerattribute":1,"layout":1,"name":1}
,"attributename":{"attributename":1,"-the":1}
,"-the":{"name":1}
,"name":{"supported":1,"layout":1,"if":1,"images":1}
,"supported":{"attribute":1}
,"text":{"number":1,"sourcetype":1,"playbackstate":1,"imageduration":1}
,"number":{"filemaker":1,"source":1,"representing":1,"presentation":1,"position":1,"startoffset":1,"endoffset":1,"duration":1,"triggerevent":1,"triggereventdetail":1,"sequence":1,"result":1,"hidecontrols":1,"disableinteraction":1,"disableexternalcontrols":1,"pauseinbackground":1,"zoom":1,"volume":1,"pictureinpicture":1,"externalplayback":1,"imagesourcetype":1,"imagesource":1,"stops":1}
,"filemaker":{"pro":1,"go":1}
,"pro":{"14.0":1}
,"14.0":{"function":1}
,"function":{"filemaker":1,"called":1}
,"go":{"if":1,"previous":1,"next":1,"moves":1}
,"if":{"function":1,"sourcetype":1,"playing":1,"playback":1,"users":1,"ios":1,"currently":1,"[getavplayerattribute":1,"checks":1,"30":1,"attributes":1}
,"called":{"media":1}
,"media":{"file":1,"playing":1,"playback":1,"embedded":1,"number":1}
,"playing":{"paused":1,"returns":1,"media":1,"end":1,"if":1}
,"paused":{"returns":1,"number":1,"except":1,"filemaker":1}
,"value":{"file\u2019s":1,"state":1}
,"file\u2019s":{"current":1}
,"current":{"playback":1,"video":1}
,"playback":{"state":1,"stopped":1,"seconds":1,"returns":1,"error":1,"controls":1,"fill":1,"stretch":1,"aspect":1}
,"state":{"if":1,"media":1,"[stopped]":1}
,"played":{"if":1,"returns":1,"next":1,"external":1}
,"empty":{"string":1}
,"string":{"attribute":1,"text":1}
,"data":{"type":1}
,"type":{"returned":1,"audio":1,"images":1}
,"returned":{"all":1}
,"all":{"all":1,"attributes":1}
,"attributes":{"values":1}
,"values":{"text":1}
,"sourcetype":{"source":1,"active":1}
,"source":{"type":1,"url":1,"returns":1}
,"files":{"none":1}
,"none":{"url":1,"-1":1}
,"url":{"field":1}
,"layout":{"object":1}
,"object":{"active":1,"number":1,"name":1,"source":1}
,"active":{"object":1,"active":1,"number":1}
,"playbackstate":{"number":1,"=1]":1}
,"representing":{"state":1}
,"stopped":{"playing":1}
,"presentation":{"method":1}
,"method":{"display":1}
,"display":{"media":1}
,"embedded":{"full":1,"number":1}
,"full":{"screen":1}
,"screen":{"full":1,"audio":1,"control":1}
,"position":{"position":1,"seconds":1,"playback":1}
,"seconds":{"currently":1,"number":1,"returns":1,"audio":1,"images":1}
,"currently":{"playing":1}
,"startoffset":{"starting":1}
,"starting":{"position":1}
,"endoffset":{"end":1}
,"end":{"position":1,"media":1,"if":1}
,"duration":{"length":1,"media":1,"1800]":1,"current":1}
,"length":{"time":1}
,"time":{"seconds":1}
,"play":{"number":1,"filemaker":1,"[field":1}
,"triggerevent":{"last":1}
,"last":{"onobjectavplayerchange":1}
,"onobjectavplayerchange":{"onfileavplayerchange":1}
,"onfileavplayerchange":{"script":1}
,"script":{"triggers":1,"remote":1,"trigger":1}
,"triggers":{"activated":1}
,"activated":{"internal":1,"last":1}
,"internal":{"script":1}
,"remote":{"number":1}
,"triggereventdetail":{"event":1}
,"event":{"activated":1}
,"trigger":{"unknown":1}
,"unknown":{"remoteplaymedia":1}
,"remoteplaymedia":{"remotepause":1}
,"remotepause":{"remotetoggleplaypause":1}
,"remotetoggleplaypause":{"remoteplaynext":1}
,"remoteplaynext":{"remoteplayprevious":1}
,"remoteplayprevious":{"remoteseek":1}
,"remoteseek":{"remotestop":1}
,"remotestop":{"scriptplaymedia":1}
,"scriptplaymedia":{"scriptchangepresentation":1}
,"scriptchangepresentation":{"10":1}
,"10":{"scripttoggleplaypause":1}
,"scripttoggleplaypause":{"11":1}
,"11":{"scriptstop":1}
,"scriptstop":{"12":1}
,"12":{"scriptchangesetting":1}
,"scriptchangesetting":{"13":1}
,"13":{"internaltoggleplaypause":1}
,"internaltoggleplaypause":{"14":1}
,"14":{"internalchangepresentation":1}
,"internalchangepresentation":{"15":1}
,"15":{"internalseek":1}
,"internalseek":{"16":1}
,"16":{"internalstop":1}
,"internalstop":{"17":1}
,"17":{"internalchangezoom":1}
,"internalchangezoom":{"18":1}
,"18":{"internalchangevolume":1}
,"internalchangevolume":{"19":1}
,"19":{"internalchangepip":1}
,"internalchangepip":{"20":1}
,"20":{"internalchangeexternalplayback":1}
,"internalchangeexternalplayback":{"number":1}
,"sequence":{"media":1}
,"next":{"none":1,"number":1}
,"-1":{"go":1}
,"previous":{"go":1}
,"result":{"if":1}
,"error":{"number":1}
,"hidecontrols":{"if":1}
,"controls":{"hidden":1,"lock":1}
,"hidden":{"returns":1}
,"disableinteraction":{"if":1}
,"users":{"interact":1,"allowed":1}
,"interact":{"playback":1}
,"disableexternalcontrols":{"if":1}
,"ios":{"playback":1}
,"lock":{"screen":1}
,"control":{"panel":1}
,"panel":{"disabled":1}
,"disabled":{"media":1}
,"pauseinbackground":{"video":1}
,"except":{"picture":1}
,"picture":{"picture":1,"audio":1,"active":1}
,"continues":{"play":1}
,"moves":{"background":1}
,"background":{"audio":1,"number":1}
,"continue":{"play":1}
,"zoom":{"video":1,"setting":1}
,"displayed":{"fit":1,"picture":1,"number":1}
,"fit":{"aspect":1,"playback":1,"users":1,"stretch":1,"fill":1}
,"aspect":{"ratio":1}
,"ratio":{"preserved":1}
,"preserved":{"video":1,"fit":1}
,"scaled":{"fit":1,"fill":1}
,"fill":{"aspect":1,"playback":1,"stretch":1,"users":1,"number":1}
,"stretch":{"video":1,"fill":1,"stretch":1,"users":1}
,"stretched":{"fill":1}
,"allowed":{"change":1}
,"change":{"zoom":1}
,"volume":{"volume":1,"level":1}
,"level":{"audio":1}
,"pictureinpicture":{"specifies":1}
,"specifies":{"video":1}
,"externalplayback":{"specifies":1}
,"external":{"device":1}
,"device":{"apple":1}
,"apple":{"tv":1}
,"tv":{"via":1}
,"via":{"airplay":1}
,"airplay":{"active":1}
,"imagesourcetype":{"source":1}
,"images":{"none":1,"text":1,"displayed":1}
,"imagesource":{"url":1}
,"imageduration":{"length":1}
,"stops":{"playing":1}
,"[getavplayerattribute":{"playbackstate":1,"duration":1}
,"=1]":{"avplayer":1}
,"avplayer":{"set":1,"play":1}
,"set":{"playback":1}
,"[stopped]":{"end":1}
,"checks":{"duration":1}
,"displays":{"message":1}
,"message":{"if":1}
,"30":{"minutes":1}
,"minutes":{"if":1,"\u0022]":1}
,"1800]":{"show":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"dialog":{"[\u0022":1}
,"[\u0022":{"exceeds":1}
,"exceeds":{"maximum":1}
,"maximum":{"duration":1}
,"\u0022]":{"else":1}
,"else":{"avplayer":1}
,"[field":{"library":1}
,"library":{":video]":1}
,":video]":{"end":1}
}
;Search.control.loadWordPairs(pairs);
