var pairs =
{
"textcolorremove":{"removes":1,"text":1,"red":1}
,"removes":{"all":1,"font":1}
,"all":{"font":1,"text":1}
,"font":{"colors":1,"color":1}
,"colors":{"text":1}
,"text":{"removes":1,"rgb":1,"-any":1,"expression":1,"field":1,"filemaker":1,"default":1,"displays":1,"displayed":1,"formatting":1,"textcolorremove":1,"green":1,"returns":1,"pure":1}
,"color":{"by":1,"parameters":1,"field":1,"all":1,"set":1,"removed":1,"portions":1,"text":1,"textcolorremove":1}
,"by":{"rgb":1,"combining":1}
,"rgb":{"function":1,"red":1,"255":1}
,"function":{"textcolorremove":1,"revert":1,"color":1,"font":1}
,"red":{"green":1,"text":1,"font":1}
,"green":{"blue":1,"text":1}
,"blue":{"text":1,"-any":1,"values":1}
,"-any":{"text":1,"integer":1}
,"expression":{"text":1}
,"field":{"rgb":1,"if":1,"font":1,"type":1}
,"integer":{"number":1}
,"number":{"16777215":1}
,"16777215":{"by":1}
,"combining":{"red":1}
,"values":{"each":1}
,"each":{"ranging":1}
,"ranging":{"255":1}
,"255":{"represent":1,"returns":1}
,"represent":{"color":1}
,"parameters":{"braces":1}
,"braces":{"optional":1}
,"optional":{"text":1}
,"filemaker":{"pro":1}
,"pro":{"8.0":1}
,"8.0":{"use":1}
,"use":{"function":1,"rgb":1}
,"revert":{"text":1}
,"default":{"font":1}
,"if":{"don\u2019t":1,"field":1}
,"don\u2019t":{"use":1}
,"displays":{"default":1}
,"set":{"layout":1}
,"layout":{"mode":1}
,"mode":{"field":1}
,"removed":{"portion":1,"red":1}
,"portion":{"text":1}
,"displayed":{"color":1,"field\u0027s":1,"field\u2019s":1}
,"portions":{"text":1}
,"field\u0027s":{"default":1}
,"formatting":{"options":1}
,"options":{"lost":1}
,"lost":{"if":1}
,"type":{"returned":1}
,"returned":{"text":1}
,"returns":{"red":1}
,"field\u2019s":{"default":1}
,"pure":{"red":1}
}
;Search.control.loadWordPairs(pairs);
