var pairs =
{
"paste":{"astes":1,"copies":1,"style":1,"filemaker":1,"data":1,"clipboard":1,"[select]":1}
,"astes":{"contents":1}
,"contents":{"clipboard":1,"replaces":1,"field":1,"paste":1,"go":1,"active":1,"\u0022]":1}
,"clipboard":{"field":1,"if":1,"currently":1,"contents":1}
,"field":{"current":1,"contents":1,"paste":1,"specifies":1,"type":1,"filemaker":1,"if":1,"data":1,"show":1}
,"current":{"record":1,"layout":1}
,"record":{"select":1}
,"select":{"entire":1,"field":1}
,"entire":{"contents":1}
,"replaces":{"contents":1}
,"if":{"use":1,"paste":1,"field":1,"manually":1,"selection":1,"[get":1,"opying":1}
,"use":{"select":1,"et":1}
,"copies":{"contents":1}
,"currently":{"selected":1}
,"selected":{"portion":1}
,"portion":{"field":1}
,"style":{"tells":1,"formatting":1}
,"tells":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"advanced":1,"6.0":1}
,"advanced":{"ignore":1,"pastes":1,"returns":1}
,"ignore":{"all":1}
,"all":{"text":1}
,"text":{"style":1}
,"formatting":{"associated":1}
,"associated":{"clipboard":1}
,"go":{"target":1}
,"target":{"field":1}
,"specifies":{"field":1}
,"6.0":{"earlier":1}
,"earlier":{"if":1}
,"data":{"match":1,"displays":1,"run":1,"records":1}
,"match":{"field":1}
,"type":{"target":1}
,"pastes":{"data":1,"clipboard":1}
,"displays":{"validation":1}
,"validation":{"alert":1}
,"alert":{"attempt":1}
,"attempt":{"exit":1}
,"exit":{"field":1}
,"layout":{"filemaker":1}
,"returns":{"error":1}
,"error":{"code":1}
,"code":{"captured":1}
,"captured":{"get":1}
,"get":{"lasterror":1}
,"lasterror":{"function":1}
,"function":{"if":1}
,"manually":{"select":1}
,"run":{"script":1}
,"script":{"step":1}
,"step":{"filemaker":1,"performs":1,"pastes":1}
,"webdirect":{"script":1,"use":1}
,"performs":{"if":1}
,"selection":{"select":1,"script":1}
,"et":{"selection":1}
,"active":{"field":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"dialog":{"[\u0022":1}
,"[\u0022":{"want":1}
,"want":{"paste":1}
,"\u0022]":{"if":1}
,"[get":{"lastmessagechoice":1}
,"lastmessagechoice":{"=1]":1}
,"=1]":{"paste":1}
,"[select]":{"end":1}
,"end":{"if":1}
,"opying":{"moving":1}
,"moving":{"data":1}
,"records":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
