var pairs =
{
"get":{"script":1,"scriptresult":1,"foundcount":1}
,"script":{"result":1,"if":1,"script":1,"step":1,"returns":1,"find":1,"reports":1,"steps":1,"[text":1,"[specified":1}
,"result":{"returns":1,"performed":1,"contents":1,"empty":1,"control":1,"use":1,"find":1,"exit":1,"stored":1,"get":1}
,"returns":{"script":1,"find":1}
,"performed":{"sub-script":1,"based":1}
,"sub-script":{"get":1,"doesn\u2019t":1,"result":1}
,"scriptresult":{"none":1,"determine":1,"set":1,"=0]":1,"get":1}
,"none":{"text":1}
,"text":{"number":1}
,"number":{"date":1}
,"date":{"time":1}
,"time":{"timestamp":1}
,"timestamp":{"container":1}
,"container":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"8.0":1}
,"8.0":{"use":1}
,"use":{"function":1,"exit":1}
,"function":{"part":1}
,"part":{"calculation":1}
,"calculation":{"evaluated":1}
,"evaluated":{"script":1}
,"if":{"sub-script":1,"[get":1,"get":1}
,"doesn\u2019t":{"return":1}
,"return":{"result":1}
,"contents":{"script":1}
,"empty":{"value":1}
,"value":{"previous":1,"sub-script":1}
,"previous":{"sub-script":1}
,"control":{"value":1}
,"exit":{"script":1}
,"step":{"sub-script":1,"script":1}
,"find":{"customers":1,"request":1,"[restore]":1}
,"customers":{"script":1,"optional":1,"parameter":1,"reports":1}
,"request":{"called":1}
,"called":{"reports":1}
,"reports":{"script":1,"get":1}
,"optional":{"script":1}
,"determine":{"script":1}
,"steps":{"performed":1}
,"based":{"returned":1}
,"returned":{"result":1}
,"stored":{"get":1}
,"set":{"error":1}
,"error":{"capture":1}
,"capture":{"[on]":1}
,"[on]":{"perform":1}
,"perform":{"find":1,"script":1}
,"[restore]":{"new":1}
,"new":{"record\u002Frequest":1}
,"record\u002Frequest":{"exit":1}
,"[text":{"result":1}
,"foundcount":{"10]":1}
,"10]":{"perform":1}
,"[specified":{"list":1}
,"list":{"find":1}
,"parameter":{"if":1}
,"[get":{"scriptresult":1}
,"=0]":{"show":1}
,"show":{"custom":1}
,"custom":{"dialog":1}
,"dialog":{"[\u0022":1}
,"[\u0022":{"created":1}
,"created":{"10":1}
,"10":{"records":1}
,"records":{"\u0022]":1}
,"\u0022]":{"end":1}
,"end":{"if":1}
}
;Search.control.loadWordPairs(pairs);
