var pairs =
{
"enable":{"touch":1,"disable":1}
,"touch":{"keyboard":1}
,"keyboard":{"nables":1,"enables":1,"disables":1,"toggle":1,"filemaker":1,"fields":1,"dialog":1,"script":1,"enable":1,"[on]":1,"if":1,"[off]":1,"type":1}
,"nables":{"disables":1}
,"disables":{"touch":1}
,"enables":{"touch":1}
,"toggle":{"switches":1}
,"switches":{"enabling":1}
,"enabling":{"disabling":1}
,"disabling":{"touch":1}
,"filemaker":{"pro":1,"go":1}
,"pro":{"14.0":1}
,"14.0":{"use":1}
,"use":{"script":1,"get":1}
,"script":{"enable":1,"step":1}
,"disable":{"touch":1}
,"go":{"windows":1,"enables":1}
,"windows":{"enable":1}
,"fields":{"impact":1}
,"impact":{"touch":1}
,"dialog":{"boxes":1}
,"boxes":{"use":1}
,"get":{"touchkeyboardstate":1}
,"touchkeyboardstate":{"function":1,"=1]":1}
,"function":{"check":1}
,"check":{"current":1}
,"current":{"setting":1}
,"setting":{"touch":1}
,"step":{"supported":1}
,"supported":{"indows":1}
,"indows":{"filemaker":1}
,"[on]":{"checks":1}
,"checks":{"current":1}
,"if":{"enabled":1,"[get":1,"hanging":1}
,"enabled":{"if":1}
,"[get":{"touchkeyboardstate":1}
,"=1]":{"enable":1}
,"[off]":{"end":1}
,"end":{"if":1}
,"hanging":{"touch":1}
,"type":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
