var pairs =
{
"ind":{"ing":1}
,"ing":{"records":1}
,"records":{"match":1,"matching":1,"meet":1,"except":1}
,"match":{"multiple":1}
,"multiple":{"criteria":1,"find":1}
,"criteria":{"narrow":1,"start":1,"logical":1,"fields":1,"all":1,"first":1,"continue":1,"include":1,"entered":1,"find":1,"boolean":1,"orking":1}
,"narrow":{"broaden":1,"search":1,"found":1}
,"broaden":{"search":1,"found":1}
,"search":{"by":1,"narrow":1,"broaden":1}
,"by":{"multiple":1,"entering":1,"excluding":1}
,"start":{"find":1}
,"find":{"request":1,"records":1,"all":1,"status":1,"requests":1,"mode":1,"broaden":1,"vendors":1}
,"request":{"aking":1,"find":1,"specific":1,"new":1,"enter":1,"type":1,"include":1,"perform":1,"including":1,"delete":1,"go":1,"want":1,"restore":1,"last":1,"requests":1}
,"aking":{"find":1}
,"matching":{"all":1,"criteria":1}
,"all":{"criteria":1,"people":1,"logical":1,"fields":1}
,"logical":{"search":1}
,"entering":{"criteria":1}
,"fields":{"find":1,"go":1}
,"specific":{"find":1}
,"people":{"named":1}
,"named":{"smith":1}
,"smith":{"sales":1,"last":1}
,"sales":{"type":1,"department":1}
,"type":{"smith":1,"new":1,"paris":1,"100":1,"100,000,000":1,"level":1}
,"last":{"name":1,"committed":1}
,"name":{"field":1}
,"field":{"sales":1,"narrow":1,"first":1,"second":1,"honors":1}
,"department":{"field":1}
,"found":{"set":1}
,"set":{"created":1,"sets":1,"criteria":1,"type":1,"narrow":1}
,"created":{"onstraining":1,"move":1,"xtending":1}
,"onstraining":{"narrowing":1}
,"narrowing":{"found":1}
,"sets":{"criteria":1}
,"first":{"find":1,"request":1}
,"new":{"request":1,"york":1}
,"enter":{"second":1}
,"second":{"set":1,"request":1}
,"continue":{"adding":1}
,"adding":{"requests":1}
,"requests":{"each":1,"stored":1,"use":1,"menu":1,"committed":1}
,"each":{"set":1}
,"include":{"customers":1,"companies":1,"6th":1}
,"customers":{"new":1,"paris":1}
,"york":{"customers":1,"city":1,"state":1}
,"paris":{"found":1,"city":1}
,"city":{"field":1,"finding":1}
,"companies":{"100":1,"$100":1}
,"100":{"employees":1,"number":1}
,"employees":{"companies":1,"field":1}
,"$100":{"assets":1}
,"assets":{"type":1}
,"number":{"employees":1}
,"100,000,000":{"capitalization":1}
,"capitalization":{"field":1}
,"6th":{"grade":1}
,"grade":{"students":1}
,"students":{"honors":1}
,"honors":{"algebra":1,"geometry":1}
,"algebra":{"7th":1,"field":1}
,"7th":{"grade":1}
,"geometry":{"type":1,"field":1}
,"level":{"field":1}
,"perform":{"find":1}
,"status":{"toolbar":1}
,"toolbar":{"requests":1,"navigation":1}
,"stored":{"order":1}
,"order":{"created":1}
,"move":{"find":1}
,"use":{"navigation":1}
,"navigation":{"controls":1}
,"controls":{"status":1,"find":1}
,"mode":{"duplicate":1}
,"duplicate":{"request":1}
,"including":{"criteria":1}
,"entered":{"choose":1}
,"choose":{"requests":1}
,"menu":{"duplicate":1,"revert":1}
,"delete":{"request":1,"delete":1}
,"go":{"request":1,"layout":1}
,"want":{"delete":1}
,"restore":{"request":1}
,"committed":{"choose":1,"all":1}
,"revert":{"request":1}
,"layout":{"request":1}
,"xtending":{"broadening":1}
,"broadening":{"found":1}
,"excluding":{"records":1}
,"meet":{"criteria":1}
,"vendors":{"new":1}
,"state":{"new":1}
,"finding":{"records":1}
,"except":{"matching":1}
,"boolean":{"complex":1}
,"complex":{"finds":1,"searches":1}
,"finds":{"complex":1}
,"searches":{"find":1}
,"orking":{"multiple":1}
}
;Search.control.loadWordPairs(pairs);
