var pairs =
{
"get":{"calculationrepetitionnu":1,"calculationrepetitionnumber":1,"calculation":1,"repetition":1,"repeating":1}
,"calculationrepetitionnu":{"mber":1}
,"mber":{"returns":1}
,"returns":{"number":1,"returns":1,"filemaker":1,"12:06:00":1,"12:12:00":1,"12:18:00":1,"12:24:00":1,"12:30:00":1}
,"number":{"representing":1,"filemaker":1,"field":1,"get":1}
,"representing":{"repetition":1}
,"repetition":{"calculation":1,"returned":1,"repeating":1,"number":1}
,"calculation":{"field":1,"repetition":1,"repetiting":1}
,"field":{"calculated":1,"isn\u2019t":1,"function":1,"field":1,"definition":1,"repetitions":1,"timer":1,"time":1,"repetition":1}
,"calculated":{"get":1}
,"calculationrepetitionnumber":{"none":1,"seconds":1,"get":1}
,"none":{"number":1}
,"filemaker":{"pro":1}
,"pro":{"7.0":1,"advanced":1}
,"7.0":{"first":1}
,"first":{"repetition":1}
,"returned":{"if":1}
,"if":{"current":1}
,"current":{"field":1}
,"isn\u2019t":{"repeating":1}
,"repeating":{"field":1,"numer":1}
,"function":{"returns":1,"allows":1}
,"advanced":{"calculating":1}
,"calculating":{"repetition":1}
,"definition":{"timer":1}
,"timer":{":reminder":1,":start":1,":snooze":1}
,":reminder":{"calculation":1,"[1]":1,"[2]":1,"[3]":1,"[4]":1,"[5]":1}
,"repetitions":{"calculates":1}
,"calculates":{"future":1}
,"future":{"times":1}
,"times":{"based":1}
,"based":{"contents":1}
,"contents":{"timer":1}
,":start":{"time":1}
,"time":{"time":1,"field":1,"hour":1,"minute":1,"extend":1,"12:00:00":1}
,":snooze":{"minutes":1}
,"minutes":{"number":1,"*get":1,"timer":1}
,"hour":{"extend":1}
,"extend":{"timer":1,"function":1}
,"minute":{"extend":1}
,"*get":{"calculationrepetitionnumber":1}
,"seconds":{"extend":1}
,"allows":{"non-repeating":1}
,"non-repeating":{"field":1}
,"12:00:00":{"timer":1}
,"[1]":{"returns":1}
,"12:06:00":{"timer":1}
,"[2]":{"returns":1}
,"12:12:00":{"timer":1}
,"[3]":{"returns":1}
,"12:18:00":{"timer":1}
,"[4]":{"returns":1}
,"12:24:00":{"timer":1}
,"[5]":{"returns":1}
,"12:30:00":{"get":1}
,"numer":{"get":1}
,"repetiting":{"number":1}
}
;Search.control.loadWordPairs(pairs);
