var pairs =
{
"damaged":{"files":1,"consistency":1,"hecking":1,"file":1,"damage":1,"remote":1,"records":1,"recovering":1}
,"files":{"frequent":1,"file":1,"open":1,"across":1,"improperly":1,"troubleshooting":1}
,"frequent":{"file":1}
,"file":{"damage":1,"closed":1,"read":1,"recovery":1,"choose":1,"suspect":1,"consistency":1,"ee":1,"all":1,"occur":1,"damaged":1,"recover":1,"if":1}
,"damage":{"filemaker":1,"media":1,"file":1}
,"filemaker":{"pro":1,"knowledge":1}
,"pro":{"advanced":1}
,"advanced":{"file":1,"two":1,"attempt":1,"runs":1,"close":1,"freezes":1,"application":1}
,"closed":{"improperly":1,"properly":1,"files":1}
,"improperly":{"file":1,"closed":1}
,"media":{"failure":1}
,"failure":{"bad":1}
,"bad":{"sectors":1}
,"sectors":{"hard":1}
,"hard":{"disk":1}
,"disk":{"parts":1}
,"parts":{"file":1}
,"read":{"by":1}
,"by":{"operating":1}
,"operating":{"system":1}
,"system":{"filemaker":1,"software":1}
,"two":{"mechanisms":1}
,"mechanisms":{"handling":1}
,"handling":{"databases":1}
,"databases":{"damaged":1}
,"consistency":{"checks":1,"file":1,"filemaker":1}
,"checks":{"file":1,"occur":1}
,"recovery":{"consistency":1}
,"occur":{"automatically":1,"active":1}
,"automatically":{"if":1}
,"if":{"file":1,"open":1,"receive":1}
,"choose":{"verify":1}
,"verify":{"consistency":1}
,"suspect":{"damaged":1}
,"hecking":{"file":1}
,"attempt":{"recover":1}
,"recover":{"damaged":1,"file":1}
,"ee":{"recovering":1}
,"recovering":{"files":1}
,"properly":{"external":1}
,"external":{"power":1}
,"power":{"interrupted":1}
,"interrupted":{"shutting":1}
,"shutting":{"computer":1}
,"computer":{"abruptly":1,"manual":1,"damaged":1}
,"abruptly":{"filemaker":1}
,"runs":{"problem":1}
,"problem":{"dialog":1,"backup":1}
,"dialog":{"box":1}
,"box":{"requires":1}
,"requires":{"user":1}
,"user":{"quit":1}
,"quit":{"application":1}
,"application":{"disk-read":1,"system":1,"open":1}
,"disk-read":{"error":1}
,"error":{"file-damaged":1,"application":1,"message":1}
,"file-damaged":{"error":1}
,"software":{"closes":1}
,"closes":{"unexpectedly":1}
,"unexpectedly":{"causing":1,"filemaker":1}
,"causing":{"filemaker":1}
,"close":{"unexpectedly":1}
,"freezes":{"forcing":1}
,"forcing":{"manual":1}
,"manual":{"reboot":1}
,"reboot":{"computer":1,"made":1}
,"made":{"reason":1}
,"reason":{"note":1}
,"note":{"each":1}
,"each":{"cases":1}
,"cases":{"active":1}
,"active":{"file":1,"inactive":1}
,"all":{"unlocked":1}
,"unlocked":{"local":1}
,"local":{"files":1}
,"open":{"time":1,"if":1,"file":1}
,"time":{"damaged":1}
,"inactive":{"tables":1}
,"tables":{"files":1}
,"across":{"network":1}
,"network":{"remote":1}
,"remote":{"computer":1,"filemaker":1}
,"records":{"missing":1}
,"missing":{"data":1}
,"data":{"expect":1}
,"expect":{"first":1}
,"first":{"filemaker":1}
,"knowledge":{"base":1}
,"base":{"suggestions":1}
,"suggestions":{"solve":1}
,"solve":{"problem":1}
,"backup":{"opy":1}
,"opy":{"file":1}
,"receive":{"error":1}
,"message":{"indicating":1}
,"indicating":{"file":1}
,"troubleshooting":{"damaged":1}
}
;Search.control.loadWordPairs(pairs);
