var pairs =
{
"get":{"activefieldtablena":1,"activefieldtablename":1,"active":1,"field":1,"current":1}
,"activefieldtablena":{"returns":1}
,"returns":{"name":1,"table":1,"empty":1,"result":1}
,"name":{"table":1,"active":1,"get":1}
,"table":{"occurrence":1,"coaches":1,"name":1,"get":1}
,"occurrence":{"field":1,"name":1,"classes":1,"related":1,"coachesa":1,"source":1}
,"field":{"focus":1,"if":1,"function":1,"return":1,"get":1,"table":1}
,"focus":{"get":1}
,"activefieldtablename":{"none":1,"field":1,"get":1}
,"none":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"7.0":1}
,"7.0":{"returns":1}
,"active":{"field":1,"table":1}
,"if":{"active":1}
,"function":{"returns":1}
,"empty":{"string":1}
,"string":{"two":1}
,"two":{"fields":1}
,"fields":{"teachers":1}
,"teachers":{":name":1,"table":1,"script":1}
,":name":{"coaches":1,"current":1,"field":1}
,"coaches":{":name":1,"creating":1}
,"current":{"layout":1,"table":1}
,"layout":{"based":1}
,"based":{"classes":1}
,"classes":{"table":1}
,"related":{"teachers":1}
,"coachesa":{"table":1,"clicking":1}
,"source":{"table":1}
,"creating":{"script":1}
,"script":{"returns":1,"performed":1}
,"result":{"get":1}
,"return":{"teachers":1,"coachesa":1}
,"performed":{"clicking":1}
,"clicking":{"teachers":1,"coaches":1}
}
;Search.control.loadWordPairs(pairs);
