var pairs =
{
"lg":{"returns":1,"number":1,"function":1,"=0":1,"=1":1,"32":1}
,"returns":{"base-2":1,"value":1}
,"base-2":{"logarithm":1}
,"logarithm":{"number":1}
,"number":{"lg":1,"number":1,"-any":1,"filemaker":1,"positive":1}
,"-any":{"numeric":1}
,"numeric":{"expression":1}
,"expression":{"field":1,"number":1}
,"field":{"numeric":1}
,"filemaker":{"pro":1}
,"pro":{"7.0":1}
,"7.0":{"number":1}
,"positive":{"value":1}
,"value":{"negative":1,"acceptable":1}
,"negative":{"values":1}
,"values":{"return":1}
,"return":{"error":1}
,"error":{"lg":1}
,"function":{"returns":1}
,"acceptable":{"range":1}
,"range":{"equation":1}
,"equation":{"lg":1}
,"=0":{"lg":1}
,"=1":{"lg":1}
,"32":{"=5":1}
}
;Search.control.loadWordPairs(pairs);
