var pairs =
{
"related":{"record":1,"table":1,"records":1,"invoice":1,"customers":1,"tables":1}
,"record":{"oes":1,"related":1,"specifies":1,"layout":1,"use":1,"option":1,"front":1,"match":1,"found":1,"if":1,"first":1,"table\u2019s":1,"creates":1,"customer":1,"display":1,"filemaker":1,"[customers]":1,"current":1,"customers":1,"question":1,"table":1,"script":1,"active":1,"performed":1,"invoices":1,"[show":1,"left":1}
,"oes":{"current":1}
,"current":{"related":1,"database":1,"file":1,"record":1,"found":1,"invoice":1,"if":1,"table":1,"layout":1}
,"table":{"get":1,"list":1,"choose":1,"file":1,"options":1,"set":1,"match":1,"currently":1,"matches":1,"related":1,"button":1,"if":1,"made":1,"first":1,"external":1,"occurrence":1,"via":1,"sorts":1,"invoices":1,"by":1}
,"get":{"related":1,"lasterror":1}
,"specifies":{"source":1,"layout":1,"animation":1}
,"source":{"relationship":1}
,"relationship":{"list":1,"manage":1,"selected":1,"layout":1,"nabled":1,"dialog":1}
,"list":{"tables":1,"if":1}
,"tables":{"current":1,"automating":1}
,"database":{"if":1,"displays":1,"dialog":1}
,"if":{"table":1,"add":1,"source":1,"don\u2019t":1,"records":1,"found":1,"record":1,"related":1,"script":1,"portal\u2019s":1,"selected":1,"select":1,"allow":1,"focus":1}
,"add":{"change":1,"elect":1}
,"change":{"relationship":1}
,"manage":{"database":1}
,"displays":{"manage":1,"error":1,"script":1,"related":1}
,"dialog":{"box":1,"off]":1}
,"box":{"create":1,"nd":1}
,"create":{"edit":1}
,"edit":{"relationships":1,"relationship":1}
,"relationships":{"show":1}
,"show":{"record":1,"new":1,"related":1}
,"layout":{"specifies":1,"current":1,"file":1,"situations":1,"if":1,"doesn\u2019t":1,"nvoices":1,"invoices":1}
,"file":{"display":1,"external":1,"show":1,"script":1,"if":1}
,"display":{"related":1,"invoices":1,"matching":1}
,"use":{"external":1,"match":1,"displaying":1,"isempty":1,"animations":1}
,"external":{"table\u2019s":1,"table":1,"file":1,"layout":1}
,"table\u2019s":{"layouts":1,"unsorted":1,"found":1}
,"layouts":{"file":1}
,"choose":{"layout":1}
,"option":{"if":1,"go":1,"set":1}
,"selected":{"references":1,"go":1,"window":1}
,"references":{"table":1}
,"new":{"window":1,"found":1,"window]":1}
,"window":{"related":1,"settings":1,"se":1,"script":1,"new":1,"doesn\u2019t":1,"can\u2019t":1,"go":1}
,"records":{"new":1,"creates":1,"match":1,"related":1,"current":1,"found":1,"if":1,"record":1,"go":1,"external":1,"option":1,"just":1,"use":1,"by":1,"table":1,"[restore":1}
,"settings":{"new":1}
,"se":{"new":1}
,"script":{"step":1,"perform":1,"go":1,"execution":1,"produce":1,"trigger":1}
,"step":{"bring":1,"show":1,"returns":1,"portal":1,"active":1,"open":1,"modify":1,"remains":1,"if":1,"new":1,"performed":1}
,"bring":{"new":1}
,"front":{"automatically":1}
,"automatically":{"add":1}
,"elect":{"window":1}
,"creates":{"new":1}
,"found":{"set":1,"script":1}
,"set":{"related":1,"first":1,"current":1,"records":1,"creates":1,"if":1,"customers":1,"display":1,"unsorted":1,"go":1,"script":1,"made":1,"filtered":1,"include":1}
,"options":{"match":1}
,"match":{"current":1,"entire":1,"customer":1,"all":1,"customers":1}
,"entire":{"found":1}
,"first":{"record":1,"related":1}
,"don\u2019t":{"select":1,"define":1}
,"select":{"option":1,"table":1}
,"go":{"related":1,"specifies":1,"filemaker":1,"external":1,"record\u002Frequest\u002Fpage":1}
,"unsorted":{"order":1,"animation":1}
,"order":{"current":1,"found":1,"maintained":1}
,"invoice":{"table":1,"invoices":1,"related":1}
,"customer":{"record":1,"table":1}
,"currently":{"viewing":1,"invoice":1,"customers":1}
,"viewing":{"want":1}
,"want":{"all":1}
,"all":{"invoices":1,"records":1,"related":1}
,"invoices":{"use":1,"match":1,"invoice":1,"if":1,"table":1,"layout":1,")]":1,"new":1,"invoices":1,"animation":1}
,"matches":{"all":1}
,"customers":{"invoices":1,"use":1,"table":1,"table\u2019s":1}
,"matching":{"invoices":1}
,"define":{"sort":1}
,"sort":{"order":1,"records":1}
,"animation":{"filemaker":1,"use":1,"slide":1}
,"filemaker":{"go":1,"pro":1}
,"displaying":{"related":1}
,"pro":{"6.0":1,"advanced":1}
,"6.0":{"earlier":1}
,"earlier":{"suppose":1}
,"suppose":{"invoices":1}
,"button":{"set":1,"determines":1}
,"[customers]":{"clicking":1}
,"clicking":{"button":1}
,"determines":{"customer":1}
,"question":{"currently":1}
,"perform":{"find":1}
,"find":{"record":1}
,"returns":{"error":1}
,"error":{"code":1,"message":1}
,"code":{"captured":1}
,"captured":{"get":1}
,"lasterror":{"function":1}
,"function":{"script":1,"determine":1}
,"portal":{"rows":1,"row":1}
,"rows":{"if":1}
,"active":{"portal":1}
,"row":{"portal\u2019s":1,"script":1,"show":1,"new":1}
,"portal\u2019s":{"table":1,"row":1}
,"made":{"current":1}
,"open":{"file":1}
,"situations":{"script":1}
,"modify":{"unintended":1}
,"unintended":{"set":1}
,"remains":{"current":1}
,"occurrence":{"there\u2019s":1,"filemaker":1}
,"there\u2019s":{"relationship":1}
,"doesn\u2019t":{"refer":1,"activate":1}
,"refer":{"correct":1}
,"correct":{"table":1}
,"advanced":{"displays":1}
,"message":{"error":1,"displays":1}
,"execution":{"continues":1}
,"continues":{"next":1}
,"next":{"script":1}
,"produce":{"unexpected":1}
,"unexpected":{"use":1,"esults":1}
,"isempty":{"function":1}
,"determine":{"if":1}
,"allow":{"creation":1}
,"creation":{"ecords":1}
,"ecords":{"table":1}
,"via":{"relationship":1}
,"nabled":{"edit":1}
,"nd":{"go":1}
,"performed":{"rom":1,"context":1}
,"rom":{"empty":1}
,"empty":{"portal":1}
,"esults":{"script":1}
,"activate":{"onfirstwindowopen":1}
,"onfirstwindowopen":{"script":1}
,"trigger":{"onwindowopen":1,"sort":1}
,"onwindowopen":{"script":1}
,"maintained":{"if":1}
,"context":{"filtered":1}
,"filtered":{"portal\u2019s":1,"records":1,"portal\u0027s":1}
,"focus":{"filtered":1}
,"portal\u0027s":{"row":1}
,"include":{"all":1}
,"just":{"filtered":1}
,"animations":{"selected":1,"navigating":1}
,"can\u2019t":{"use":1}
,"navigating":{"records":1}
,"by":{"slider":1,"sliding":1}
,"slider":{"status":1}
,"status":{"toolbar":1}
,"toolbar":{"buttons":1}
,"buttons":{"related":1}
,"sorts":{"found":1}
,"[show":{"related":1}
,"nvoices":{"invoices":1}
,")]":{"sort":1}
,"[restore":{"dialog":1}
,"off]":{"go":1}
,"record\u002Frequest\u002Fpage":{"[first]":1}
,"[first]":{"related":1,"displays":1}
,"window]":{"sort":1}
,"sliding":{"record":1}
,"left":{"go":1}
,"slide":{"left]":1}
,"left]":{"gtrr":1}
,"gtrr":{"related":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
