var pairs =
{
"close":{"popover":1}
,"popover":{"loses":1,"window":1,"target":1,"open":1,"return":1,"navigates":1,"go":1}
,"loses":{"open":1}
,"open":{"popover":1,"close":1}
,"window":{"script":1,"if":1}
,"script":{"step":1}
,"step":{"runs":1}
,"runs":{"none":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"13.0":1}
,"13.0":{"closes":1}
,"closes":{"open":1}
,"target":{"window":1}
,"if":{"popover":1}
,"return":{"error":1}
,"error":{"code":1}
,"code":{"closes":1}
,"navigates":{"paid":1}
,"paid":{"unpaid":1}
,"unpaid":{"tab":1}
,"tab":{"tab":1,"control":1}
,"control":{"depending":1}
,"depending":{"value":1}
,"value":{"invoices":1}
,"invoices":{":status":1,":status]":1}
,":status":{"close":1}
,"go":{"object":1}
,"object":{"[object":1}
,"[object":{"name":1}
,"name":{"invoices":1}
,":status]":{"popovers":1}
,"popovers":{"layouts":1}
,"layouts":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
