var pairs =
{
"list":{"eturns":1,"non-blank":1,"field":1,"values":1,"function":1,"($f1":1}
,"eturns":{"concatenated":1,"list":1}
,"concatenated":{"list":1}
,"non-blank":{"values":1}
,"values":{"field":1,"single":1,"table":1,"across":1,"red":1}
,"field":{"fields":1,"field":1,"-any":1,"repeating":1,"set":1,"table":1,"all":1}
,"fields":{"list":1,"expression":1,"variable":1,"and\u002For":1,"if":1,"related":1}
,"-any":{"related":1}
,"related":{"field":1,"records":1,"first":1,"record":1,":field4":1}
,"repeating":{"field":1,"fields":1}
,"set":{"non-repeating":1}
,"non-repeating":{"fields":1}
,"expression":{"returns":1}
,"returns":{"field":1,"single":1,"separate":1,"white":1,"red":1,"orange":1,"calculation":1,"100":1}
,"variable":{"parameters":1}
,"parameters":{"braces":1}
,"braces":{"optional":1}
,"optional":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"8.5":1}
,"8.5":{"each":1}
,"each":{"returned":1,"repetition":1}
,"returned":{"value":1}
,"value":{"except":1}
,"except":{"th":1}
,"th":{"ast":1}
,"ast":{"carriage":1}
,"carriage":{"return":1}
,"return":{"use":1,"list":1}
,"use":{"function":1}
,"function":{"return":1,"eturns":1}
,"single":{"field":1,"result":1}
,"table":{":field":1,":field1":1,":field2":1}
,":field":{"returns":1}
,"result":{"all":1,"each":1}
,"all":{"repetitions":1,"matching":1}
,"repetitions":{"if":1,"values":1}
,"if":{"field":1,"fields":1}
,"matching":{"related":1}
,"records":{"records":1,"portal":1,"contain":1}
,"portal":{"fields":1}
,"and\u002For":{"literal":1}
,"literal":{"values":1}
,":field1":{"constant":1}
,"constant":{"table":1}
,":field2":{"returns":1}
,"separate":{"result":1}
,"repetition":{"calculation":1,"fields":1,"calculation\u0027s":1,"list":1,"second":1,"field1":1,"white":1,"green":1,"blue":1}
,"calculation":{"across":1,"repetition":1}
,"across":{"each":1,"first":1,"second":1}
,"first":{"related":1,"repetition":1}
,"record":{"referencing":1}
,"referencing":{"multiple":1}
,"multiple":{"repeating":1}
,"calculation\u0027s":{"first":1}
,"second":{"repetition":1}
,"field1":{"white":1,"field2":1}
,"white":{"field2":1,"blac":1,"black":1}
,"field2":{"black":1,"returns":1,"field3":1}
,"black":{"field3":1,"ist":1,"red":1}
,"field3":{"repetitions":1,"returns":1,"$f1":1}
,"red":{"green":1,"orange":1}
,"green":{"blue":1,"blu":1,"orange":1}
,"blue":{"related":1,"orange":1}
,":field4":{"refers":1,"returns":1}
,"refers":{"records":1}
,"contain":{"100":1}
,"100":{"200":1}
,"200":{"300":1}
,"300":{"$f1":1}
,"$f1":{"orange":1,"returns":1}
,"orange":{"purple":1}
,"purple":{"ist":1,"black":1,"calculation":1}
,"ist":{"field1":1,"field3":1,"related":1}
,"blac":{"ist":1}
,"blu":{"list":1}
,"($f1":{"field2":1}
}
;Search.control.loadWordPairs(pairs);
