var pairs =
{
"rename":{"file":1,"creating":1}
,"file":{"renames":1,"source":1,"path":1,"rename":1,"paths":1,"filemaker":1,"change1.log":1,"[source":1,"change.log":1,"named":1,"exists":1,"\u0022$file":1}
,"renames":{"file":1,"change.log":1}
,"source":{"file":1}
,"path":{"file":1}
,"creating":{"file":1}
,"paths":{"new":1}
,"new":{"name":1}
,"name":{"text":1,"file":1,"change1.log":1,"let":1}
,"text":{"expression":1}
,"expression":{"specifies":1}
,"specifies":{"new":1}
,"filemaker":{"pro":1}
,"pro":{"18.0":1}
,"18.0":{"advanced":1}
,"advanced":{"renames":1}
,"change.log":{"file":1,"new":1,"if":1,"get":1}
,"change1.log":{"rename":1,"adds":1}
,"[source":{"file":1}
,"adds":{"current":1}
,"current":{"date":1}
,"date":{"end":1,"=get":1,"month":1,"day":1,"filename":1}
,"end":{"file":1,"if":1}
,"named":{"change.log":1}
,"if":{"file":1,"[$fileexists":1,"automating":1}
,"exists":{"set":1,"[\u0022$file":1}
,"set":{"variable":1}
,"variable":{"[$file":1}
,"[$file":{"value":1}
,"value":{"change.log":1}
,"get":{"file":1}
,"[\u0022$file":{"target":1}
,"target":{"$fileexists":1}
,"$fileexists":{"if":1}
,"[$fileexists":{"rename":1}
,"\u0022$file":{"new":1}
,"let":{"[filename":1}
,"[filename":{"=left":1}
,"=left":{"$file":1}
,"$file":{"length":1,"-4":1,"date":1}
,"length":{"$file":1}
,"-4":{"extension":1}
,"extension":{"=right":1}
,"=right":{"$file":1}
,"=get":{"currentdate":1}
,"currentdate":{"year":1}
,"year":{"=year":1}
,"=year":{"date":1}
,"month":{"=month":1}
,"=month":{"date":1}
,"day":{"=day":1}
,"=day":{"date":1}
,"filename":{"&\u0022-\u0022":1}
,"&\u0022-\u0022":{"&year":1,"&month":1,"&day":1}
,"&year":{"&\u0022-\u0022":1}
,"&month":{"&\u0022-\u0022":1}
,"&day":{"&\u0022":1}
,"&\u0022":{"&extension":1}
,"&extension":{"end":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
