var pairs =
{
"hanging":{"layout":1}
,"layout":{"part":1,"mode":1,"parts":1,"arrow":1,"title":1,"delete":1,"objects":1}
,"part":{"layout":1,"setup":1,"change":1,"definition":1,"select":1,"type":1,"first":1,"color":1,"label":1,"new":1,"moved":1,"delete":1,"objects":1,"drag":1,"deleting":1,"deleted":1,"enlarged":1,"want":1,"changing":1}
,"mode":{"choose":1,"selection":1}
,"choose":{"layouts":1,"table":1}
,"layouts":{"menu":1}
,"menu":{"part":1}
,"setup":{"part":1,"dialog":1}
,"dialog":{"box":1}
,"box":{"select":1,"change":1}
,"select":{"part":1,"field":1,"deselect":1}
,"change":{"part":1,"type":1,"layout":1}
,"definition":{"dialog":1}
,"type":{"part":1,"depend":1,"exists":1}
,"depend":{"part\u0027s":1}
,"part\u0027s":{"location":1}
,"location":{"function":1,"part":1}
,"function":{"break":1}
,"break":{"field":1}
,"field":{"subsummary":1,"tables":1,"name":1}
,"subsummary":{"part":1,"parts":1}
,"first":{"choose":1}
,"table":{"field":1}
,"tables":{"list":1}
,"list":{"list":1,"fields":1,"view":1}
,"fields":{"select":1,"page":1}
,"name":{"list":1,"part":1,"note":1}
,"page":{"breaks":1,"numbering":1}
,"breaks":{"page":1,"numbering":1}
,"numbering":{"defining":1,"layout":1}
,"defining":{"page":1}
,"color":{"setting":1,"right-click":1}
,"setting":{"fill":1}
,"fill":{"line":1,"by":1,"records":1}
,"line":{"style":1,"marks":1}
,"style":{"shadows":1}
,"shadows":{"padding":1}
,"padding":{"quickly":1}
,"quickly":{"change":1}
,"right-click":{"part":1}
,"label":{"records":1,"press":1,"arrow":1}
,"records":{"list":1}
,"view":{"displayed":1,"by":1}
,"displayed":{"alternating":1,"fill":1}
,"alternating":{"fill":1}
,"by":{"alternate":1,"active":1}
,"alternate":{"display":1,"row":1}
,"display":{"state":1}
,"state":{"select":1,"current":1,"order":1}
,"deselect":{"use":1}
,"use":{"alternate":1,"active":1}
,"row":{"state":1}
,"current":{"active":1}
,"active":{"record":1,"display":1,"row":1}
,"record":{"displayed":1}
,"order":{"layout":1}
,"parts":{"drag":1,"exist":1}
,"drag":{"name":1,"objects":1}
,"new":{"location":1}
,"moved":{"displays":1}
,"displays":{"lock":1}
,"lock":{"icon":1}
,"icon":{"left":1}
,"left":{"name":1}
,"note":{"while":1,"method":1}
,"while":{"layout":1}
,"selection":{"tool":1}
,"tool":{"selection":1,"status":1}
,"status":{"toolbar":1}
,"toolbar":{"shift-drag":1}
,"shift-drag":{"line":1}
,"marks":{"bottom":1}
,"bottom":{"part":1}
,"delete":{"part":1,"delete":1,"dimmed":1,"all":1}
,"objects":{"part":1,"want":1,"note":1,"holds":1}
,"want":{"keep":1,"delete":1}
,"keep":{"part":1}
,"arrow":{"pointer":1}
,"pointer":{"part":1,"press":1}
,"press":{"backspace":1,"ctrl":1}
,"backspace":{"delete":1,"windows":1}
,"deleting":{"objects":1}
,"ctrl":{"backspace":1}
,"windows":{"option-delete":1}
,"option-delete":{"macos":1}
,"macos":{"part":1}
,"deleted":{"part":1}
,"enlarged":{"retained":1}
,"retained":{"objects":1}
,"method":{"part":1}
,"dimmed":{"types":1}
,"types":{"part":1}
,"exists":{"subsummary":1}
,"exist":{"layout":1}
,"changing":{"right":1}
,"right":{"place":1}
,"place":{"layout":1}
,"title":{"header":1}
,"header":{"top":1}
,"top":{"layout":1}
,"all":{"last":1}
,"last":{"layout":1}
}
;Search.control.loadWordPairs(pairs);
