var pairs =
{
"rightvalues":{"returns":1,"text":1,"plaid":1,"names":1}
,"returns":{"values":1,"canvas":1,"john":1}
,"values":{"contained":1,"valuecount":1}
,"contained":{"text":1}
,"text":{"numberofvalues":1,"-any":1,"expression":1,"field":1,"filemaker":1}
,"numberofvalues":{"counting":1,"text":1,"-any":1}
,"counting":{"right":1}
,"right":{"rightvalues":1}
,"-any":{"text":1,"numeric":1}
,"expression":{"text":1,"field":1}
,"field":{"numberofvalues":1,"number":1,"sophie":1}
,"numeric":{"expression":1}
,"number":{"text":1}
,"filemaker":{"pro":1}
,"pro":{"7.0":1}
,"7.0":{"description":1}
,"description":{"list":1}
,"list":{"values":1}
,"valuecount":{"function":1}
,"function":{"each":1}
,"each":{"returned":1}
,"returned":{"value":1}
,"value":{"nds":1}
,"nds":{"carriage":1}
,"carriage":{"return":1}
,"return":{"allowing":1}
,"allowing":{"lists":1}
,"lists":{"easily":1}
,"easily":{"concatenated":1}
,"concatenated":{"rightvalues":1}
,"plaid":{"canvas":1}
,"canvas":{"suitcase":1}
,"suitcase":{"returns":1,"rightvalues":1}
,"names":{"returns":1,"field":1}
,"john":{"hen":1}
,"hen":{"names":1}
,"sophie":{"bill":1}
,"bill":{"john":1}
}
;Search.control.loadWordPairs(pairs);
