var pairs =
{
"pecify":{"label":1}
,"label":{"layout":1,"types":1,"measurements":1,"code":1,"stock":1,"dimensions":1,"dimension":1}
,"layout":{"new":1,"exact":1}
,"new":{"layout\u002Freport":1}
,"layout\u002Freport":{"assistant":1}
,"assistant":{"panel":1,"ou":1}
,"panel":{"new":1}
,"ou":{"choose":1}
,"choose":{"predefined":1,"label":1,"tr":1}
,"predefined":{"measurement":1,"dimension":1,"label":1}
,"measurement":{"based":1}
,"based":{"common":1}
,"common":{"label":1}
,"types":{"custom":1}
,"custom":{"easurement":1,"measurements":1,"label":1}
,"easurement":{"use":1}
,"use":{"label":1,"custom":1,"predefined":1}
,"measurements":{"list":1,"type":1}
,"list":{"choose":1}
,"code":{"matches":1,"choose":1}
,"matches":{"labels":1}
,"labels":{"filemaker":1,"layout":1,"predefined":1,"across":1,"create":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"reates":1}
,"reates":{"labels":1}
,"exact":{"dimensions":1}
,"dimensions":{"label":1,"match":1}
,"stock":{"code":1,"select":1}
,"tr":{"match":1}
,"match":{"labels":1}
,"dimension":{"if":1,"select":1}
,"if":{"match":1}
,"select":{"use":1,"fixed":1}
,"type":{"values":1}
,"values":{"labels":1,"top":1}
,"across":{"page":1}
,"page":{"width":1,"margins":1}
,"width":{"height":1}
,"height":{"measure":1}
,"measure":{"unused":1}
,"unused":{"margins":1}
,"margins":{"label":1,"enter":1}
,"fixed":{"page":1}
,"enter":{"values":1}
,"top":{"bottom":1}
,"bottom":{"left":1}
,"left":{"right":1}
,"right":{"use":1}
,"create":{"custom":1}
}
;Search.control.loadWordPairs(pairs);
