var pairs =
{
"open":{"manage":1}
,"manage":{"layouts":1,"database\u0027s":1,"database":1}
,"layouts":{"pens":1,"dialog":1,"choosing":1,"layout":1,"manage":1,"\u0022]":1,"end":1,"automating":1}
,"pens":{"manage":1}
,"dialog":{"box":1,"[\u0022":1}
,"box":{"none":1,"if":1,"show":1}
,"none":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"11.0":1}
,"11.0":{"script":1}
,"script":{"step":1}
,"step":{"choosing":1}
,"choosing":{"file":1,"manage":1}
,"file":{"menu":1}
,"menu":{"manage":1,"displays":1}
,"layout":{"pop-up":1}
,"pop-up":{"menu":1}
,"displays":{"custom":1}
,"custom":{"dialog":1}
,"if":{"user":1,"[get":1,"managing":1}
,"user":{"manage":1}
,"database\u0027s":{"layouts":1}
,"show":{"custom":1}
,"[\u0022":{"want":1}
,"want":{"manage":1}
,"database":{"layouts":1}
,"\u0022]":{"if":1}
,"[get":{"lastmessagechoice":1}
,"lastmessagechoice":{"=1]":1}
,"=1]":{"open":1}
,"end":{"if":1}
,"managing":{"layouts":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
