var pairs =
{
"hart":{"etu":1}
,"etu":{"dialog":1}
,"dialog":{"box":1,"boxes":1}
,"box":{"use":1,"modify":1,"two":1,"reducing":1,"appears":1,"chart":1,"remain":1}
,"use":{"chart":1}
,"chart":{"setup":1,"create":1,"layout":1,"creating":1,"preview":1,"inspector":1,"settings":1,"title":1,"type":1,"axes":1,"lick":1,"pecify":1,"records":1,"satisfied":1,"quick":1,"cancel":1,"new":1,"via":1,"saved":1}
,"setup":{"dialog":1}
,"modify":{"quick":1}
,"quick":{"chart":1,"charts":1}
,"create":{"edit":1}
,"edit":{"chart":1}
,"layout":{"mode":1,"save":1,"access":1,"pop-up":1,"menus":1,"accounts":1,"xit":1,"note":1}
,"mode":{"note":1,"chart":1,"print":1,"hoose":1}
,"note":{"get":1,"correct":1,"if":1}
,"get":{"started":1}
,"started":{"creating":1}
,"creating":{"chart":1,"quick":1,"editing":1}
,"charts":{"creating":1,"layout":1,"including":1,"pie":1,"scatter":1,"change":1,"created":1}
,"editing":{"charts":1}
,"two":{"sections":1}
,"sections":{"chart":1}
,"preview":{"chart":1}
,"inspector":{"chart":1,"enter":1,"changing":1,"pecifying":1}
,"settings":{"chart":1,"add":1}
,"reducing":{"found":1}
,"found":{"set":1}
,"set":{"if":1,"tick":1,"delimited":1}
,"if":{"data":1,"charting":1,"applicable":1,"cancel":1,"made":1}
,"data":{"comparison":1,"sales":1,"sort":1,"categories":1,"table":1,"series":1,"labels":1,"formatting":1,"chart":1,"source":1}
,"comparison":{"clear":1}
,"clear":{"aking":1}
,"aking":{"find":1}
,"find":{"request":1}
,"request":{"sorting":1}
,"sorting":{"data":1,"records":1}
,"sales":{"lowest":1}
,"lowest":{"if":1}
,"charting":{"summary":1}
,"summary":{"data":1}
,"sort":{"data":1,"by":1}
,"categories":{"sort":1}
,"by":{"region":1}
,"region":{"data":1}
,"table":{"view":1}
,"view":{"sorting":1}
,"records":{"chart":1,"found":1,"related":1,"lick":1}
,"enter":{"settings":1}
,"add":{"title":1}
,"title":{"chart":1,"type":1,"button":1,"choose":1}
,"type":{"change":1,"data":1}
,"change":{"chart":1,"data":1}
,"button":{"title":1}
,"choose":{"chart":1}
,"series":{"column":1}
,"column":{"bar":1}
,"bar":{"line":1,"positive\u002Fnegative":1}
,"line":{"charts":1}
,"including":{"stacked":1}
,"stacked":{"column":1}
,"positive\u002Fnegative":{"charts":1}
,"pie":{"charts":1}
,"scatter":{"bubble":1}
,"bubble":{"charts":1}
,"labels":{"show":1}
,"show":{"hide":1}
,"hide":{"tick":1}
,"tick":{"marks":1,"mark":1}
,"marks":{"set":1}
,"mark":{"scale":1}
,"scale":{"if":1}
,"applicable":{"format":1}
,"format":{"data":1}
,"formatting":{"scaling":1}
,"scaling":{"chart":1}
,"axes":{"hange":1}
,"hange":{"color":1}
,"color":{"scheme":1}
,"scheme":{"legend":1}
,"legend":{"fonts":1}
,"fonts":{"chart":1}
,"lick":{"styles":1,"data":1}
,"styles":{"chart":1}
,"changing":{"chart":1}
,"pecify":{"type":1}
,"delimited":{"records":1}
,"related":{"records":1}
,"source":{"chart":1}
,"pecifying":{"data":1}
,"satisfied":{"chart":1}
,"created":{"browse":1,"layout":1}
,"browse":{"mode":1}
,"print":{"print":1,"copy":1}
,"copy":{"chart":1}
,"cancel":{"save":1,"chart":1}
,"save":{"layout":1,"chart":1}
,"new":{"layout":1}
,"access":{"chart":1}
,"via":{"layout":1}
,"pop-up":{"menu":1}
,"menu":{"select":1,"ave":1}
,"select":{"include":1,"field":1}
,"include":{"layout":1}
,"menus":{"dialog":1}
,"appears":{"note":1}
,"correct":{"privileges":1}
,"privileges":{"save":1}
,"accounts":{"privilege":1}
,"privilege":{"sets":1,"charts":1}
,"sets":{"extended":1}
,"extended":{"privilege":1}
,"hoose":{"layouts":1}
,"layouts":{"menu":1}
,"ave":{"layout":1}
,"xit":{"layout":1}
,"saved":{"if":1}
,"made":{"database":1}
,"database":{"schema":1,"create":1}
,"schema":{"select":1}
,"field":{"field":1,"dialog":1}
,"boxes":{"while":1}
,"while":{"chart":1}
,"remain":{"database":1}
}
;Search.control.loadWordPairs(pairs);
