var pairs =
{
"etting":{"up":1}
,"up":{"print":1,"layout":1,"records":1,"columns":1}
,"print":{"records":1,"preview":1,"columns":1,"browse":1,"setup":1,"page":1,"data":1}
,"records":{"columns":1,"print":1,"across":1,"flow":1}
,"columns":{"set":1,"directory":1,"all":1,"across":1,"first":1,"records":1,"layout":1,"print":1,"type":1,"place":1,"interactively":1,"drag":1,"reduces":1,"inspector":1,"filemaker":1,"fit":1}
,"set":{"up":1,"options":1,"change":1}
,"layout":{"print":1,"arranges":1,"preview":1,"layout":1,"mode":1,"choose":1,"pop-up":1,"objects":1,"setup":1,"bar":1,"vertical":1,"removing":1,"change":1}
,"preview":{"records":1,"modes":1,"mode":1}
,"directory":{"names":1}
,"names":{"addresses":1}
,"addresses":{"contrast":1}
,"contrast":{"list":1}
,"list":{"view":1}
,"view":{"report":1,"print":1}
,"report":{"layout":1}
,"arranges":{"fields":1}
,"fields":{"columns":1,"layout":1,"fields":1,"objects":1,"extend":1,"eliminated":1,"fit":1}
,"all":{"record":1,"values":1}
,"record":{"printed":1}
,"printed":{"block":1,"order":1}
,"block":{"label":1}
,"label":{"all":1,"stock":1}
,"values":{"next":1}
,"next":{"record":1}
,"order":{"records":1}
,"across":{"rows":1,"page":1,"first":1}
,"rows":{"columns":1,"first":1,"preserve":1}
,"first":{"columns":1,"page":1,"multiple":1,"left":1,"across":1,"button":1,"top":1,"first":1,"filemaker":1}
,"page":{"two":1,"setup":1,"first":1,"width":1,"break":1,"across":1,"page":1,"defining":1,"breaks":1}
,"two":{"columns":1,"features":1}
,"multiple":{"columns":1}
,"modes":{"print":1}
,"browse":{"mode":1}
,"mode":{"find":1,"choose":1,"print":1,"create":1}
,"find":{"mode":1}
,"choose":{"file":1,"layout":1}
,"file":{"menu":1}
,"menu":{"print":1,"page":1,"easiest":1}
,"setup":{"windows":1,"macos":1,"calculates":1,"layout":1,"button":1}
,"windows":{"file":1,"page":1}
,"macos":{"confirm":1,"status":1}
,"confirm":{"printer":1}
,"printer":{"paper":1,"print":1}
,"paper":{"settings":1,"size":1}
,"settings":{"correct":1}
,"correct":{"preview":1}
,"status":{"toolbar":1}
,"toolbar":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"considers":1,"adjusts":1,"prints":1,"starts":1}
,"considers":{"selected":1}
,"selected":{"printer":1}
,"calculates":{"margins":1}
,"margins":{"measurements":1,"set":1,"readjust":1}
,"measurements":{"layout":1}
,"create":{"layout":1}
,"pop-up":{"menu":1}
,"easiest":{"start":1}
,"start":{"blank":1}
,"blank":{"layout":1,"space":1,"spaces":1}
,"objects":{"body":1,"contained":1,"sliding":1}
,"body":{"part":1}
,"part":{"se":1,"filemaker":1}
,"se":{"creating":1}
,"creating":{"layout":1,"space":1}
,"button":{"layout":1,"use":1,"careful":1}
,"bar":{"cl":1}
,"cl":{"ick":1}
,"ick":{"printing":1}
,"printing":{"tab":1}
,"tab":{"select":1,"position":1}
,"select":{"print":1,"across":1,"first":1}
,"options":{"table":1}
,"table":{"number":1}
,"number":{"columns":1,"99":1,"rows":1}
,"type":{"number":1}
,"99":{"arrange":1}
,"arrange":{"records":1,"fields":1}
,"flow":{"across":1,"page":1}
,"left":{"right":1,"use":1}
,"right":{"row":1,"column":1,"edge":1,"increase":1,"creates":1}
,"row":{"time":1}
,"time":{"select":1}
,"use":{"option":1,"fewest":1,"merge":1}
,"option":{"reports":1}
,"reports":{"labels":1,"directories":1}
,"labels":{"use":1}
,"fewest":{"number":1}
,"preserve":{"label":1}
,"stock":{"arrange":1}
,"top":{"bottom":1}
,"bottom":{"column":1}
,"column":{"time":1,"by":1,"layout":1,"left":1,"two":1,"blank":1,"calculated":1,"boundary":1,"note":1,"narrowed":1,"width":1,"gutter":1,"precisely":1,"select":1,"if":1,"new":1}
,"directories":{"usually":1}
,"usually":{"read":1}
,"read":{"top":1,"column":1}
,"by":{"column":1}
,"vertical":{"lines":1,"dashed":1}
,"lines":{"indicating":1}
,"indicating":{"columns":1}
,"place":{"arrange":1}
,"contained":{"sample":1}
,"sample":{"column":1}
,"merge":{"fields":1}
,"sliding":{"enabled":1}
,"enabled":{"fit":1}
,"fit":{"data":1,"width":1,"sample":1}
,"data":{"width":1,"placing":1}
,"width":{"column":1,"each":1,"columns":1,"fixed":1,"printable":1,"dragging":1,"read":1,"value":1,"paper":1,"page":1}
,"features":{"fields":1}
,"extend":{"gray":1}
,"gray":{"second":1}
,"second":{"column":1}
,"space":{"fields":1,"columns":1}
,"eliminated":{"view":1}
,"placing":{"merge":1}
,"removing":{"blank":1}
,"spaces":{"printouts":1}
,"printouts":{"initial":1}
,"initial":{"width":1}
,"each":{"column":1}
,"calculated":{"based":1}
,"based":{"paper":1}
,"size":{"orientation":1,"if":1,"defined":1}
,"orientation":{"margins":1}
,"change":{"width":1,"number":1}
,"interactively":{"adjust":1}
,"adjust":{"width":1}
,"drag":{"right":1,"column":1}
,"boundary":{"vertical":1,"right":1,"hold":1}
,"dashed":{"line":1}
,"line":{"right":1}
,"edge":{"sample":1}
,"note":{"page":1}
,"fixed":{"dragging":1,"margins":1}
,"dragging":{"column":1}
,"increase":{"width":1}
,"printable":{"each":1}
,"narrowed":{"column":1}
,"creates":{"utter":1}
,"utter":{"argin":1}
,"argin":{"each":1}
,"gutter":{"margin":1}
,"margin":{"creating":1}
,"reduces":{"printable":1}
,"precisely":{"measure":1}
,"measure":{"adjust":1}
,"inspector":{"position":1}
,"position":{"position":1,"tab":1,"pointer":1}
,"pointer":{"right":1}
,"hold":{"mouse":1}
,"mouse":{"button":1}
,"careful":{"drag":1}
,"value":{"size":1}
,"if":{"change":1,"page":1}
,"adjusts":{"width":1}
,"defined":{"including":1}
,"including":{"fixed":1}
,"readjust":{"fields":1}
,"prints":{"subsummary":1}
,"subsummary":{"parts":1,"part":1}
,"parts":{"width":1}
,"break":{"subsummary":1,"starts":1}
,"starts":{"new":1}
,"new":{"column":1,"page":1}
,"defining":{"page":1}
,"breaks":{"numbering":1}
,"numbering":{"set":1}
}
;Search.control.loadWordPairs(pairs);
