var pairs =
{
"bjects":{"tab":1}
,"tab":{"objects":1,"view":1,"hide":1,"isplays":1,"panel":1,"control":1,"identifying":1}
,"objects":{"layout":1,"tab":1,"current":1,"overlapping":1,"temporarily":1,"pane":1,"show":1,"type":1,"shortcut":1,"front":1,"select":1,"choose":1,"applies":1,"stay":1,"name":1,"can\u2019t":1,"button":1,"bjects":1}
,"layout":{"mode":1,"stacking":1,"use":1,"layout":1,"pop-up":1,"show\u002Fhide":1,"select":1}
,"mode":{"use":1,"choose":1,"hidden":1,"visible":1}
,"use":{"objects":1,"bjects":1}
,"view":{"all":1}
,"all":{"objects":1,"object":1,"show":1,"top-level":1,"groups":1}
,"current":{"layout":1}
,"stacking":{"order":1}
,"order":{"easier":1,"drag":1,"name":1}
,"easier":{"object":1}
,"object":{"layout":1,"show":1,"type":1,"types":1,"list":1,"grouped":1,"select":1,"name":1,"object":1,"group":1,"open":1,"groups":1,"bjects":1,"calculation":1}
,"hide":{"all":1,"object":1,"overlapping":1,"objects":1,"reorder":1,"popover":1}
,"overlapping":{"objects":1}
,"temporarily":{"layout":1}
,"choose":{"layout":1,"object":1,"all":1,"hide":1,"set":1,"conditional":1}
,"pop-up":{"menu":1}
,"menu":{"objects":1,"hide":1,"change":1,"select":1,"define":1,"if":1}
,"pane":{"button":1}
,"button":{"status":1,"next":1,"ext":1,"choose":1,"button":1,"bar":1,"field":1,"definition":1,"displayed":1,"show":1,"associated":1}
,"status":{"toolbar":1}
,"toolbar":{"objects":1}
,"show":{"hide":1,"ll":1,"all":1,"by":1,"objects":1,"choose":1}
,"show\u002Fhide":{"button":1}
,"next":{"object":1,"group":1}
,"ll":{"objects":1}
,"ext":{"search":1}
,"search":{"box":1}
,"box":{"show":1,"last":1,":country":1}
,"type":{"list":1,"button":1,"show":1,"name":1}
,"list":{"show":1,"new":1,"choose":1,"displays":1}
,"by":{"type":1,"field":1,"related":1,"name":1}
,"types":{"choose":1}
,"select":{"objects":1,"object":1}
,"shortcut":{"menu":1}
,"front":{"selected":1,"shortcut":1,"back":1}
,"selected":{"objects":1}
,"back":{"selected":1,"shortcut":1}
,"change":{"stacking":1}
,"drag":{"object":1}
,"new":{"position":1}
,"position":{"stacking":1}
,"name":{"object":1,"shortcut":1,"expand":1,"edit":1,"related":1,"portal":1,"slide":1,"panels":1}
,"grouped":{"object":1,"button":1}
,"group":{"ungrouping":1,"name":1,"select":1,"open":1,"objects":1}
,"ungrouping":{"triangle":1}
,"triangle":{"next":1}
,"expand":{"group":1}
,"open":{"close":1}
,"close":{"object":1,"all":1,"reopen":1}
,"groups":{"windows":1,"macos":1,"set":1}
,"windows":{"control-click":1}
,"control-click":{"group":1}
,"top-level":{"groups":1}
,"macos":{"command-click":1}
,"command-click":{"group":1}
,"set":{"script":1}
,"script":{"triggers":1}
,"triggers":{"object":1,"shortcut":1}
,"define":{"conditional":1}
,"conditional":{"formatting":1}
,"formatting":{"object":1,"shortcut":1}
,"if":{"name":1,"button":1}
,"isplays":{"object":1}
,"displays":{"text":1}
,"text":{"button":1,"enclosed":1,"calculation":1}
,"bar":{"segment":1}
,"segment":{"popover":1}
,"popover":{"tab":1,"button":1,"objects":1}
,"panel":{"existing":1}
,"existing":{"text":1}
,"enclosed":{"quotation":1}
,"quotation":{"marks":1}
,"marks":{"newbutton":1}
,"newbutton":{"calculation":1}
,"calculation":{"object":1,"there\u2019s":1}
,"there\u2019s":{"text":1}
,"field":{"control":1,"name":1}
,"control":{"style":1,"nd":1,"objects":1,"tab":1,"changing":1,"if":1}
,"style":{"by":1}
,"edit":{"box":1}
,"last":{"name":1}
,"related":{"field":1}
,":country":{"portal":1}
,"portal":{"portal":1,"by":1,"customers":1}
,"customers":{"hiding":1}
,"hiding":{"objects":1}
,"applies":{"layout":1}
,"hidden":{"objects":1,"exit":1}
,"stay":{"hidden":1}
,"exit":{"reenter":1}
,"reenter":{"layout":1}
,"visible":{"close":1}
,"reopen":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"can\u2019t":1}
,"can\u2019t":{"name":1,"use":1}
,"slide":{"control":1}
,"nd":{"tab":1}
,"panels":{"objects":1,"slide":1}
,"reorder":{"panels":1}
,"changing":{"tab":1,"slide":1}
,"definition":{"attached":1}
,"attached":{"object":1}
,"displayed":{"grouped":1}
,"associated":{"popover":1}
,"identifying":{"unnamed":1}
,"unnamed":{"objects":1}
}
;Search.control.loadWordPairs(pairs);
