var pairs =
{
"get":{"script":1,"scriptanimationstate":1,"current":1}
,"script":{"animationstate":1,"returns":1,"running":1,"set":1,"step":1,"animation":1}
,"animationstate":{"returns":1}
,"returns":{"true":1,"false":1,"current":1}
,"true":{"if":1}
,"if":{"animations":1}
,"animations":{"enabled":1,"by":1,"set":1}
,"enabled":{"current":1}
,"current":{"script":1}
,"false":{"get":1}
,"scriptanimationstate":{"none":1,"get":1}
,"none":{"number":1}
,"number":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"13.0":1}
,"13.0":{"animations":1}
,"by":{"default":1}
,"default":{"while":1}
,"while":{"script":1}
,"running":{"returns":1}
,"set":{"enable":1,"layout":1}
,"enable":{"animations":1}
,"layout":{"object":1}
,"object":{"animation":1}
,"animation":{"script":1,"state":1}
,"step":{"get":1}
,"state":{"get":1}
}
;Search.control.loadWordPairs(pairs);
