var pairs =
{
"functions":{"function":1,"include":1,"bout":1,"evaluate":1,"npv":1,"double":1}
,"function":{"predefined":1,"name":1,"takes":1,"each":1,"returns":1,"parameters":1,"use":1,"requires":1,"calculation":1,"choose":1,"if":1}
,"predefined":{"named":1}
,"named":{"formula":1}
,"formula":{"performs":1}
,"performs":{"specific":1}
,"specific":{"calculation":1,"value":1}
,"calculation":{"returns":1,"dialog":1}
,"returns":{"single":1,"result":1,"length":1}
,"single":{"specific":1}
,"value":{"functions":1,"stored":1}
,"include":{"basic":1}
,"basic":{"parts":1}
,"parts":{"function":1}
,"name":{"set":1,"mc":1,"field":1}
,"set":{"parentheses":1}
,"parentheses":{"if":1,"enclose":1}
,"if":{"function":1,"optional":1,"executed":1}
,"takes":{"parameters":1}
,"parameters":{"parameters":1,"required":1,"constants":1,"spaces":1,"list":1,"order":1,"case":1,"precede":1,"each":1,"filenames":1,"function":1}
,"required":{"by":1}
,"by":{"function":1,"semicolon":1}
,"each":{"function":1,"separated":1}
,"result":{"field":1}
,"field":{"type":1,"references":1,"names":1,"parameter":1,"get":1,"extendedprice":1}
,"type":{"text":1}
,"text":{"number":1,"string":1,"parameters":1,"john":1}
,"number":{"date":1,"characters":1,"representing":1}
,"date":{"time":1}
,"time":{"timestamp":1}
,"timestamp":{"container":1}
,"container":{"functions":1}
,"bout":{"formulas":1}
,"formulas":{"note":1}
,"note":{"functions":1}
,"evaluate":{"host":1}
,"host":{"client":1}
,"client":{"search":1}
,"search":{"filemaker":1}
,"filemaker":{"knowledge":1,"pro":1}
,"knowledge":{"base":1}
,"base":{"function":1}
,"constants":{"1.07":1}
,"1.07":{"field":1}
,"references":{"invoicetotal":1}
,"invoicetotal":{"expressions":1}
,"expressions":{"12":1}
,"12":{"functions":1}
,"npv":{"function":1}
,"use":{"spaces":1,"quotation":1,"semicolon":1}
,"spaces":{"parentheses":1,"function":1,"use":1}
,"enclose":{"parameters":1}
,"requires":{"parameter":1}
,"parameter":{"separate":1,"all":1,"omit":1,"use":1,"table":1}
,"separate":{"individual":1}
,"individual":{"parameters":1}
,"list":{"separator":1}
,"separator":{"semicolon":1}
,"semicolon":{"parameters":1,"aggregate":1}
,"order":{"add":1}
,"add":{"function":1,"parameters":1}
,"dialog":{"box":1}
,"box":{"braces":1}
,"braces":{"surround":1}
,"surround":{"optional":1}
,"optional":{"parameters":1,"parameter":1}
,"case":{"function":1,"indicating":1}
,"choose":{"function":1}
,"all":{"optional":1,"values":1}
,"precede":{"ellipsis":1}
,"ellipsis":{"signifies":1}
,"signifies":{"add":1}
,"separated":{"by":1}
,"aggregate":{"functions":1}
,"double":{"quotation":1}
,"quotation":{"marks":1}
,"marks":{"text":1,"use":1,"field":1,"value":1}
,"string":{"literal":1,"parameter":1,"case":1}
,"literal":{"text":1,"string":1}
,"filenames":{"layout":1}
,"layout":{"names":1}
,"names":{"enclosed":1,"literal":1}
,"enclosed":{"quotation":1}
,"omit":{"quotation":1}
,"stored":{"field":1}
,"table":{"examples":1}
,"examples":{"filemaker":1}
,"pro":{"advanced":1}
,"advanced":{"functions":1}
,"length":{"john":1}
,"john":{"number":1,"round":1}
,"characters":{"text":1}
,"round":{"salestax":1}
,"salestax":{",2":1}
,",2":{"sales":1}
,"sales":{"tax":1}
,"tax":{"rounded":1}
,"rounded":{"two":1}
,"two":{"decimal":1}
,"decimal":{"position":1}
,"position":{"name":1,"text":1,"first":1}
,"mc":{",1,1":1,"name":1}
,",1,1":{"number":1}
,"representing":{"starting":1,"error":1}
,"starting":{"position":1}
,"indicating":{"position":1}
,"first":{"occurrence":1}
,"occurrence":{"mc":1}
,"get":{"lasterror":1}
,"lasterror":{"number":1}
,"error":{"if":1}
,"executed":{"script":1}
,"script":{"step":1,"sum":1}
,"step":{"currently":1}
,"currently":{"running":1}
,"running":{"script":1}
,"sum":{"extendedprice":1}
,"extendedprice":{"total":1,"arameters":1}
,"total":{"all":1}
,"values":{"repeating":1}
,"repeating":{"field":1}
}
;Search.control.loadWordPairs(pairs);
