var pairs =
{
"et":{"applicatio":1}
,"applicatio":{"nversion":1}
,"nversion":{"returns":1}
,"returns":{"filemaker":1,"proadvanced":1}
,"filemaker":{"client\u2019s":1,"pro":1,"runtime":1,"server":1,"cloud":1,"go":1,"data":1,"version":1}
,"client\u2019s":{"product":1}
,"product":{"name":1}
,"name":{"version":1}
,"version":{"get":1,"filemaker":1,"web":1,"xdbc":1,"application":1}
,"get":{"applicationversion":1,"application":1,"app":1,"filemaker":1}
,"applicationversion":{"none":1,"get":1}
,"none":{"text":1}
,"text":{"filemaker":1}
,"pro":{"6.0":1,"advanced":1,"version":1,"runtime":1,"18":1}
,"6.0":{"earlier":1}
,"earlier":{"returns":1}
,"proadvanced":{"version":1,"18":1}
,"advanced":{"pro":1,"script":1}
,"runtime":{"version":1,"web":1}
,"web":{"publishing":1,"clients":1}
,"publishing":{"engine":1}
,"engine":{"version":1}
,"clients":{"xdbc":1}
,"xdbc":{"version":1,"client":1}
,"client":{"server":1}
,"server":{"version":1,"filemaker":1}
,"cloud":{"go":1}
,"go":{"version":1,"iphone":1,"ipad":1,"layout":1,"get":1}
,"iphone":{"ipod":1}
,"ipod":{"touch":1}
,"touch":{"go_ipad":1}
,"go_ipad":{"version":1}
,"ipad":{"filemaker":1}
,"data":{"api":1}
,"api":{"engine":1,"returns":1}
,"18":{"0.1":1}
,"0.1":{"filemaker":1,"advanced":1}
,"script":{"go":1,"step":1}
,"layout":{"script":1}
,"step":{"filemaker":1}
,"application":{"version":1}
,"app":{"version":1}
}
;Search.control.loadWordPairs(pairs);
