var pairs =
{
"fields":{"script":1,"cases":1,"variables":1,"evaluate":1}
,"script":{"steps":1}
,"steps":{"fields":1,"operate":1,"paste":1}
,"operate":{"specific":1}
,"specific":{"fields":1}
,"cases":{"variables":1}
,"variables":{"ith":1,"import":1,"export":1}
,"ith":{"script":1}
,"paste":{"data":1}
,"data":{"fields":1}
,"import":{"fields":1}
,"export":{"data":1}
,"evaluate":{"calculation":1}
,"calculation":{"assign":1}
,"assign":{"result":1}
,"result":{"field":1}
,"field":{"variable":1}
}
;Search.control.loadWordPairs(pairs);
