var pairs =
{
"get":{"touchkeyboardstate":1}
,"touchkeyboardstate":{"returns":1,"none":1,"=1]":1}
,"returns":{"true":1,"false":1,"if":1,"filemaker":1}
,"true":{"if":1}
,"if":{"touch":1,"active":1,"enabled":1,"[get":1}
,"touch":{"keyboard":1}
,"keyboard":{"set":1,"enabled":1,"disabled":1,"if":1,"concealed":1,"disables":1,"[off]":1}
,"set":{"display":1}
,"display":{"automatically":1}
,"automatically":{"returns":1}
,"false":{"get":1}
,"none":{"number":1}
,"number":{"filemaker":1}
,"filemaker":{"pro":1,"go":1,"webdirect":1,"data":1}
,"pro":{"14.0":1}
,"14.0":{"filemaker":1}
,"go":{"windows":1,"value":1,"displays":1}
,"windows":{"function":1,"macos":1}
,"function":{"returns":1,"supported":1,"state":1}
,"enabled":{"if":1}
,"disabled":{"windows":1}
,"macos":{"filemaker":1}
,"webdirect":{"server-side":1}
,"server-side":{"scripts":1}
,"scripts":{"filemaker":1}
,"data":{"api":1}
,"api":{"custom":1}
,"custom":{"web":1}
,"web":{"publishing":1}
,"publishing":{"function":1}
,"supported":{"returns":1}
,"value":{"returned":1}
,"returned":{"by":1}
,"by":{"function":1}
,"state":{"touch":1}
,"active":{"field":1}
,"field":{"concealed":1}
,"concealed":{"edit":1}
,"edit":{"box":1}
,"box":{"filemaker":1,"checks":1}
,"displays":{"touch":1}
,"checks":{"current":1}
,"current":{"setting":1}
,"setting":{"touch":1}
,"disables":{"touch":1}
,"[get":{"touchkeyboardstate":1}
,"=1]":{"enable":1}
,"enable":{"touch":1}
,"[off]":{"end":1}
,"end":{"if":1}
}
;Search.control.loadWordPairs(pairs);
