var pairs =
{
"get":{"windoworientation":1}
,"windoworientation":{"returns":1,"none":1,"return":1}
,"returns":{"value":1,"-2":1,"calculation":1,"portrait":1,"landscape":1}
,"value":{"representing":1,"listed":1,"greater":1,"less":1}
,"representing":{"orientation":1}
,"orientation":{"window":1,"get":1,"field":1,"portrait":1}
,"window":{"script":1,"if":1,"current":1}
,"script":{"acting":1}
,"acting":{"get":1,"foreground":1,"portrait":1}
,"none":{"number":1}
,"number":{"filemaker":1}
,"filemaker":{"pro":1,"go":1,"webdirect":1}
,"pro":{"13.0":1,"advanced":1}
,"13.0":{"filemaker":1}
,"advanced":{"filemaker":1}
,"go":{"returns":1}
,"-2":{"landscape":1}
,"landscape":{"left":1,"right":1,"if":1}
,"left":{"-1":1}
,"-1":{"landscape":1}
,"right":{"square":1}
,"square":{"filemaker":1}
,"webdirect":{"portrait":1}
,"portrait":{"portrait":1,"upside":1,"orientation":1,"if":1,"landscape":1}
,"upside":{"window":1}
,"foreground":{"window":1}
,"if":{"window":1,"function":1,"orientation":1}
,"current":{"script":1}
,"calculation":{"field":1}
,"field":{"named":1,"references":1,"if":1,"returns":1}
,"named":{"orientation":1}
,"return":{"value":1}
,"listed":{"calculation":1}
,"references":{"orientation":1}
,"function":{"returns":1}
,"greater":{"returns":1}
,"less":{"if":1}
}
;Search.control.loadWordPairs(pairs);
