var pairs =
{
"isempty":{"returns":1,"field":1,"ordernum":1,"lastname":1,"payments":1,"text":1}
,"returns":{"true":1,"false":1,"if":1}
,"true":{"if":1}
,"if":{"field":1,"errors":1,"related":1,"error":1,"ordernum":1,"isempty":1,"lastname":1,"entry":1,"payments":1}
,"field":{"empty":1,"field":1,"-any":1,"name":1,"related":1,"file":1,"blank":1}
,"empty":{"if":1,"use":1}
,"errors":{"occur":1}
,"occur":{"returns":1}
,"false":{"isempty":1,"container":1,"if":1}
,"-any":{"field":1}
,"name":{"text":1}
,"text":{"expression":1,"returns":1}
,"expression":{"numeric":1,"number":1}
,"numeric":{"expression":1}
,"number":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"function":1}
,"function":{"returns":1,"isempty":1}
,"related":{"field":1,"table":1}
,"table":{"relationship":1,"moved":1}
,"relationship":{"file":1}
,"file":{"missing":1,"determine":1,"container":1}
,"missing":{"if":1}
,"error":{"occurs":1}
,"occurs":{"false":1}
,"container":{"fields":1,"field":1}
,"fields":{"function":1}
,"determine":{"file":1}
,"use":{"getcontainerattribute":1}
,"getcontainerattribute":{"function":1}
,"ordernum":{"returns":1,"field":1}
,"lastname":{"invalid":1,"field":1,"isempty":1}
,"invalid":{"record":1}
,"record":{"displays":1,"if":1}
,"displays":{"invalid":1,"if":1}
,"blank":{"displays":1}
,"entry":{"lastname":1}
,"payments":{":datepaid":1,"table":1}
,":datepaid":{"returns":1}
,"moved":{"renamed":1}
,"renamed":{"isempty":1}
}
;Search.control.loadWordPairs(pairs);
