var pairs =
{
"count":{"eturns":1,"field":1,"function":1,"payments":1,"field2":1,"field1":1}
,"eturns":{"number":1}
,"number":{"valid":1,"filemaker":1,"repeats":1,"payments":1}
,"valid":{"non-blank":1}
,"non-blank":{"values":1}
,"values":{"field":1,"first":1,"second":1,"field2":1,"field3":1}
,"field":{"count":1,"field":1,"-any":1,"repeating":1,"set":1,"repeatingfield":1,"matching":1,"number":1,"accounts":1}
,"-any":{"related":1}
,"related":{"field":1,"records":1}
,"repeating":{"field":1,"fields":1}
,"set":{"non-repeating":1}
,"non-repeating":{"fields":1}
,"fields":{"expression":1,"parameters":1,"record":1,"first":1,"tables":1}
,"expression":{"returns":1}
,"returns":{"field":1,"total":1,"number":1,"calculation":1}
,"parameters":{"braces":1}
,"braces":{"optional":1}
,"optional":{"number":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"field":1}
,"repeatingfield":{"field":1}
,"matching":{"related":1,"record":1}
,"records":{"by":1,"portal":1}
,"by":{"table":1}
,"table":{":field":1,":field1":1,":field2":1}
,":field":{"records":1,"table":1,"referenced":1}
,"portal":{"non-repeating":1,"installment":1}
,"record":{"field1":1,"repeatingfield1":1,"by":1}
,"field1":{"field2":1,"two":1}
,"field2":{"field3":1,"repetitions":1,"returns":1}
,"field3":{"repetitions":1,"count":1,"returns":1}
,"repetitions":{"repeating":1,"values":1}
,"repeatingfield1":{"repeatingfield2":1}
,"repeatingfield2":{"repeatingfield3":1}
,"repeatingfield3":{"if":1}
,"if":{"result":1}
,"result":{"returned":1}
,"returned":{"repeating":1}
,"repeats":{"fields":1}
,"first":{"matching":1,"repetition":1}
,":field1":{"table":1}
,":field2":{"include":1}
,"include":{"fields":1}
,"tables":{"table":1}
,"referenced":{"field":1}
,"function":{"returns":1}
,"total":{"number":1}
,"repetition":{"field":1}
,"second":{"repetition":1}
,"accounts":{"layout":1}
,"layout":{"portal":1}
,"installment":{"payments":1}
,"payments":{"made":1,":payment":1}
,"made":{"count":1,"account":1}
,":payment":{"returns":1}
,"account":{"examples":1}
,"examples":{"field1":1}
,"two":{"repetitions":1}
,"calculation":{"isn\u2019t":1,"repeating":1}
,"isn\u2019t":{"repeating":1}
}
;Search.control.loadWordPairs(pairs);
