var pairs =
{
"sum":{"eturns":1,"field":1,"function":1,"first":1,"second":1,"lineitems":1,"hours":1,"field2":1,"field1":1}
,"eturns":{"total":1}
,"total":{"all":1,"number":1,"billable":1}
,"all":{"valid":1,"items":1}
,"valid":{"non-blank":1}
,"non-blank":{"values":1}
,"values":{"field":1,"field2":1,"field3":1}
,"field":{"sum":1,"field":1,"-any":1,"repeating":1,"set":1,"repeatingfield":1,"matching":1,"number":1,"invoice":1,"26":1,"12":1}
,"-any":{"related":1}
,"related":{"field":1,"records":1}
,"repeating":{"field":1,"fields":1}
,"set":{"non-repeating":1}
,"non-repeating":{"fields":1}
,"fields":{"expression":1,"parameters":1,"record":1,"first":1,"tables":1}
,"expression":{"returns":1}
,"returns":{"field":1,"sum":1,"total":1,"26":1,"12":1,"repeating":1}
,"parameters":{"braces":1}
,"braces":{"optional":1}
,"optional":{"number":1}
,"number":{"filemaker":1,"repeats":1,"billable":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"field":1}
,"repeatingfield":{"field":1}
,"matching":{"related":1,"record":1}
,"records":{"by":1,"portal":1}
,"by":{"table":1}
,"table":{":field":1,":field1":1,":field2":1,"portal":1}
,":field":{"records":1,"table":1,"referenced":1}
,"portal":{"non-repeating":1,"line":1,"time":1,"40":1}
,"record":{"field1":1,"repeatingfield1":1,"by":1}
,"field1":{"field2":1,"two":1}
,"field2":{"field3":1,"repetitions":1,"returns":1}
,"field3":{"repetitions":1,"if":1,"returns":1}
,"repetitions":{"repeating":1,"values":1}
,"repeatingfield1":{"repeatingfield2":1}
,"repeatingfield2":{"repeatingfield3":1}
,"repeatingfield3":{"if":1}
,"if":{"result":1,"portal":1,"calculation":1}
,"result":{"returned":1,"isn\u2019t":1,"repeating":1}
,"returned":{"repeating":1}
,"repeats":{"fields":1}
,"first":{"matching":1,"repetition":1}
,":field1":{"table":1}
,":field2":{"include":1}
,"include":{"fields":1}
,"tables":{"table":1}
,"referenced":{"field":1}
,"function":{"returns":1}
,"repetition":{"field":1,"sum":1}
,"second":{"repetition":1}
,"invoice":{"table":1,"timebilling":1}
,"line":{"items":1}
,"items":{"sum":1,"invoice":1}
,"lineitems":{":extendedprice":1}
,":extendedprice":{"totals":1}
,"totals":{"amounts":1}
,"amounts":{"all":1}
,"timebilling":{"table":1}
,"time":{"project":1,"field":1}
,"project":{"hours":1,"if":1}
,"hours":{"time":1,":billablehours":1,"project":1,"15:30":1,"total":1,"55:30":1,"examples":1}
,":billablehours":{"returns":1}
,"billable":{"hours":1}
,"40":{"hours":1}
,"15:30":{"hours":1}
,"55:30":{"55":1}
,"55":{"1\u002F2":1}
,"1\u002F2":{"hours":1}
,"examples":{"field1":1}
,"two":{"repetitions":1}
,"calculation":{"result":1}
,"isn\u2019t":{"repeating":1}
,"26":{"sum":1,"first":1}
,"12":{"if":1}
}
;Search.control.loadWordPairs(pairs);
