var pairs =
{
"exit":{"application":1}
,"application":{"loses":1,"none":1,"script":1,"end":1}
,"loses":{"all":1}
,"all":{"open":1}
,"open":{"files":1,"databases":1}
,"files":{"filemaker":1}
,"filemaker":{"pro":1,"clients":1,"webdirect":1,"closes":1,"running":1}
,"pro":{"advanced":1,"6.0":1}
,"advanced":{"exits":1}
,"exits":{"application":1}
,"none":{"filemaker":1}
,"6.0":{"earlier":1}
,"earlier":{"exit":1}
,"script":{"step":1,"trigger":1}
,"step":{"filemaker":1}
,"clients":{"filemaker":1}
,"webdirect":{"logs":1,"launch":1}
,"logs":{"current":1}
,"current":{"web":1}
,"web":{"session":1}
,"session":{"returns":1}
,"returns":{"filemaker":1}
,"launch":{"center":1}
,"center":{"filemaker":1}
,"closes":{"all":1}
,"databases":{"leaves":1}
,"leaves":{"filemaker":1}
,"running":{"prevents":1}
,"prevents":{"user":1}
,"user":{"database":1,"abort":1}
,"database":{"weekend":1}
,"weekend":{"started":1}
,"started":{"by":1}
,"by":{"onfirstwindowopen":1}
,"onfirstwindowopen":{"script":1}
,"trigger":{"allow":1}
,"allow":{"user":1}
,"abort":{"[off]":1}
,"[off]":{"if":1}
,"if":{"[dayname":1,"automating":1}
,"[dayname":{"get":1}
,"get":{"currentdate":1}
,"currentdate":{"=\u0022":1}
,"=\u0022":{"saturday":1,"sunday":1}
,"saturday":{"dayname":1}
,"dayname":{"get":1}
,"sunday":{"\u0022]":1}
,"\u0022]":{"exit":1}
,"end":{"if":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
