var pairs =
{
"naming":{"fields":1,"restrictions":1}
,"fields":{"field":1,"use":1}
,"field":{"names":1,"name":1,"naming":1}
,"names":{"unique":1}
,"unique":{"table":1}
,"table":{"follow":1}
,"follow":{"guidelines":1}
,"guidelines":{"naming":1}
,"use":{"symbols":1,"_(":1}
,"symbols":{"field":1}
,"name":{"comma":1,"filemaker":1,"calculation":1}
,"comma":{"[]":1}
,"[]":{"semicolon":1}
,"semicolon":{"colon":1}
,"colon":{"relational":1}
,"relational":{"indicator":1}
,"indicator":{"$(":1,"xor":1}
,"$(":{"variable":1}
,"variable":{"indicator":1}
,"xor":{"true":1}
,"true":{"false":1}
,"false":{"name":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"function":1,"data":1}
,"function":{"field":1}
,"calculation":{"formula":1}
,"formula":{"space":1}
,"space":{"period":1,"avoid":1}
,"period":{"number":1}
,"number":{"use":1}
,"_(":{"underscore":1}
,"underscore":{"place":1}
,"place":{"space":1}
,"avoid":{"restrictions":1,"sql":1}
,"restrictions":{"odbc":1,"file":1}
,"odbc":{"exporting":1,"jdbc":1}
,"exporting":{"web":1}
,"web":{"publishing":1}
,"publishing":{"operations":1}
,"operations":{"if":1}
,"if":{"exchanging":1,"odbc":1}
,"exchanging":{"data":1}
,"data":{"application":1,"avoid":1}
,"application":{"check":1,"if":1}
,"check":{"field":1}
,"file":{"formats":1}
,"formats":{"supported":1}
,"supported":{"by":1}
,"by":{"application":1}
,"jdbc":{"share":1}
,"share":{"filemaker":1}
,"sql":{"keywords":1}
,"keywords":{"field":1}
}
;Search.control.loadWordPairs(pairs);
