var pairs =
{
"controlling":{"animations":1}
,"animations":{"layout":1,"provide":1,"typically":1,"script":1,"call":1,"decrease":1,"supported":1,"slide":1}
,"layout":{"objects":1,"object":1}
,"objects":{"script":1}
,"script":{"steps":1,"running":1,"step":1,"use":1,"performs":1,"run":1,"slide":1,"enable":1,"[duration":1}
,"steps":{"animations":1}
,"provide":{"visual":1}
,"visual":{"feedback":1}
,"feedback":{"users":1}
,"users":{"actions":1,"open":1,"call":1}
,"actions":{"occur":1,"script":1}
,"occur":{"users":1}
,"open":{"popover":1}
,"popover":{"switch":1}
,"switch":{"panels":1}
,"panels":{"slide":1,"animation":1}
,"slide":{"control":1,"panel":1}
,"control":{"animations":1,"switch":1}
,"typically":{"disabled":1}
,"disabled":{"while":1}
,"while":{"script":1}
,"running":{"use":1}
,"use":{"set":1,"get":1}
,"set":{"layout":1}
,"object":{"animation":1,"script":1,"[object":1}
,"animation":{"script":1,"state":1,"providing":1,"object":1,"[on]":1}
,"step":{"enable":1,"script":1}
,"enable":{"disable":1,"animations":1}
,"disable":{"animations":1}
,"get":{"scriptanimationstate":1}
,"scriptanimationstate":{"function":1}
,"function":{"detect":1}
,"detect":{"current":1}
,"current":{"animation":1}
,"state":{"enable":1}
,"call":{"attention":1}
,"attention":{"actions":1,"transition":1}
,"performs":{"disable":1}
,"decrease":{"time":1}
,"time":{"required":1}
,"required":{"script":1}
,"run":{"note":1}
,"note":{"animations":1}
,"supported":{"windows":1}
,"windows":{"if":1}
,"if":{"script":1}
,"providing":{"feedback":1}
,"transition":{"panel":1}
,"panel":{"panel":1,"place":1,"switched":1,"\u0022]":1}
,"place":{"set":1}
,"switched":{"set":1}
,"[on]":{"go":1}
,"go":{"object":1}
,"[object":{"name":1}
,"name":{"panel":1}
,"\u0022]":{"pause\u002Fresume":1}
,"pause\u002Fresume":{"script":1}
,"[duration":{"seconds":1}
,"seconds":{".5]":1}
,".5]":{"go":1}
}
;Search.control.loadWordPairs(pairs);
