var pairs =
{
"insert":{"last":1}
,"last":{"visited":1,"active":1,"record":1}
,"visited":{"astes":1,"inserts":1,"returns":1,"[invoices":1,"record":1}
,"astes":{"data":1}
,"data":{"last":1,"go":1,"entry":1,"run":1,"records":1}
,"active":{"record":1}
,"record":{"field":1,"find":1,"last":1,"filemaker":1,"inserts":1,"viewed":1}
,"field":{"current":1,"if":1,"specifies":1,"paste":1,"go":1,"script":1,"exist":1,"data":1,"last":1}
,"current":{"record":1}
,"find":{"request":1,"enter":1,"mode":1,"[]":1}
,"request":{"select":1,"pauses":1}
,"select":{"entire":1,"option":1,"field":1}
,"entire":{"contents":1}
,"contents":{"replaces":1,"field":1}
,"replaces":{"contents":1}
,"if":{"select":1,"field":1,"manually":1,"selection":1}
,"option":{"insert":1}
,"inserts":{"result":1,"customer":1,"value":1}
,"result":{"insertion":1}
,"insertion":{"point":1}
,"point":{"end":1}
,"end":{"field\u0027s":1}
,"field\u0027s":{"existing":1}
,"existing":{"data":1}
,"go":{"target":1,"field":1}
,"target":{"field":1}
,"specifies":{"field":1}
,"paste":{"filemaker":1}
,"filemaker":{"pro":1,"webdirect":1}
,"pro":{"6.0":1,"advanced":1}
,"6.0":{"earlier":1}
,"earlier":{"use":1}
,"use":{"script":1,"et":1}
,"script":{"step":1,"performed":1,"[indefinitely]":1}
,"step":{"ensure":1,"if":1,"filemaker":1,"performs":1,"creates":1}
,"ensure":{"consistency":1}
,"consistency":{"automate":1}
,"automate":{"data":1}
,"entry":{"active":1}
,"advanced":{"performed":1}
,"performed":{"activity":1,"insert":1}
,"activity":{"pasting":1}
,"pasting":{"text":1}
,"text":{"moving":1}
,"moving":{"field":1,"data":1}
,"exist":{"layout":1}
,"layout":{"script":1}
,"returns":{"error":1}
,"error":{"code":1}
,"code":{"captured":1}
,"captured":{"get":1}
,"get":{"lasterror":1}
,"lasterror":{"function":1}
,"function":{"if":1}
,"manually":{"select":1}
,"run":{"script":1}
,"webdirect":{"script":1,"use":1}
,"performs":{"if":1,"find":1}
,"selection":{"select":1,"script":1}
,"et":{"selection":1}
,"creates":{"new":1}
,"new":{"record":1,"record\u002Frequest":1}
,"customer":{"name":1}
,"name":{"last":1,"field":1}
,"viewed":{"new":1}
,"record\u002Frequest":{"insert":1}
,"[invoices":{":customer":1}
,":customer":{"name]":1}
,"name]":{"inserts":1,"pause\u002Fresume":1}
,"value":{"customer":1}
,"pauses":{"user":1}
,"user":{"modifications":1}
,"modifications":{"performs":1}
,"enter":{"find":1}
,"mode":{"[pause":1}
,"[pause":{"off]":1}
,"off]":{"insert":1}
,"pause\u002Fresume":{"script":1}
,"[indefinitely]":{"perform":1}
,"perform":{"find":1}
,"[]":{"opying":1}
,"opying":{"moving":1}
,"records":{"automating":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
