var pairs =
{
"perform":{"find":1}
,"find":{"inds":1,"requests":1,"request":1,"records":1,"omit":1,"script":1,"find":1,"mode":1,"enter":1,"criteria":1,"invoice":1,"returns":1,"[]":1,"displays":1}
,"inds":{"records":1}
,"records":{"current":1,"omit":1,"find":1,"finding":1,"adds":1,"excludes":1,"use":1,"during":1,"list":1,"add":1,"found":1}
,"current":{"stored":1,"table":1,"find":1,"date":1}
,"stored":{"find":1,"script":1}
,"requests":{"pecify":1,"requests":1,"create":1,"edit":1,"list":1,"if":1,"script":1,"enters":1}
,"pecify":{"fi":1}
,"fi":{"nd":1}
,"nd":{"re":1}
,"re":{"quests":1}
,"quests":{"llows":1}
,"llows":{"create":1}
,"create":{"manage":1,"stored":1,"edit":1}
,"manage":{"find":1}
,"script":{"step":1,"allow":1}
,"step":{"restore":1,"find":1,"if":1,"enters":1,"performs":1,"pausing":1}
,"restore":{"stored":1}
,"request":{"speci":1,"dialog":1,"edit":1,"list":1,"criteria":1,"find":1,"by":1,"change":1,"script":1,"executed":1,"automating":1}
,"speci":{"fy":1}
,"fy":{"find":1}
,"edit":{"find":1,"selected":1}
,"dialog":{"boxes":1,"box":1,"[\u0022":1}
,"boxes":{"new":1}
,"new":{"edit":1,"list":1}
,"box":{"define":1,"allows":1,"field":1,"remove":1,"depending":1}
,"define":{"criteria":1}
,"criteria":{"find":1,"action":1,"selected":1,"insert":1,"finding":1,"select":1,"top":1,"change":1,"set":1,"performing":1}
,"selected":{"find":1,"field":1}
,"list":{"duplicate":1,"delete":1,"edit":1,"fields":1,"select":1,"change":1}
,"duplicate":{"duplicates":1}
,"duplicates":{"selected":1}
,"delete":{"deletes":1,"existing":1}
,"deletes":{"selected":1}
,"allows":{"create":1}
,"action":{"select":1}
,"select":{"find":1,"field":1,"related":1,"line":1}
,"omit":{"records":1}
,"finding":{"records":1}
,"adds":{"found":1}
,"found":{"set":1,"today\u2019s":1,"\u0022]":1}
,"set":{"omitting":1,"field":1,"error":1}
,"omitting":{"records":1}
,"excludes":{"individual":1}
,"individual":{"request":1}
,"use":{"multiple":1,"perform":1}
,"multiple":{"requests":1}
,"if":{"find":1,"don\u2019t":1,"[get":1,"aking":1}
,"during":{"perform":1}
,"fields":{"current":1}
,"table":{"construct":1,"name":1,"top":1,"want":1}
,"construct":{"find":1}
,"by":{"selecting":1}
,"selecting":{"field":1}
,"field":{"list":1,"related":1,"new":1,"type":1,"criteria":1,"and\u002For":1,"script":1,"current":1,"[invoices":1}
,"related":{"table":1,"field":1}
,"name":{"current":1}
,"top":{"list":1,"dialog":1}
,"want":{"select":1}
,"change":{"value":1,"existing":1,"store":1}
,"value":{"repetition":1}
,"repetition":{"cell":1}
,"cell":{"repeating":1}
,"repeating":{"field":1}
,"type":{"search":1}
,"search":{"criteria":1}
,"insert":{"operator":1}
,"operator":{"further":1}
,"further":{"refine":1}
,"refine":{"search":1}
,"add":{"add":1,"criteria":1}
,"existing":{"criteria":1}
,"line":{"field":1}
,"and\u002For":{"criteria":1}
,"store":{"delete":1}
,"remove":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"use":1}
,"enters":{"find":1,"browse":1}
,"mode":{"performs":1,"if":1,"script":1,"mode":1,"use":1,"pauses":1,"[pause":1,"sets":1}
,"performs":{"find":1,"current":1,"last":1}
,"browse":{"mode":1}
,"don\u2019t":{"find":1}
,"last":{"find":1}
,"executed":{"enters":1}
,"enter":{"find":1}
,"pausing":{"script":1}
,"allow":{"user":1}
,"user":{"enter":1,"input":1}
,"performing":{"find":1}
,"invoice":{"details":1}
,"details":{"layout":1,"\u0022]":1}
,"layout":{"enters":1,"go":1,"[\u0022":1,"[original":1,"invoices":1,"custom":1}
,"pauses":{"user":1}
,"input":{"performs":1}
,"returns":{"original":1}
,"original":{"layout":1}
,"go":{"layout":1}
,"[\u0022":{"invoice":1,"invoices":1,"records":1}
,"\u0022]":{"enter":1,"else":1,"end":1}
,"[pause":{"on]":1,"off]":1}
,"on]":{"perform":1}
,"[]":{"go":1,"if":1}
,"[original":{"layout]":1}
,"layout]":{"find":1}
,"sets":{"date":1}
,"date":{"field":1,"performs":1,"set":1}
,"displays":{"invoice":1}
,"invoices":{"layout":1,"\u0022]":1}
,"custom":{"dialog":1}
,"depending":{"records":1}
,"today\u2019s":{"date":1}
,"error":{"capture":1}
,"capture":{"[on]":1}
,"[on]":{"enter":1}
,"off]":{"set":1}
,"[invoices":{":date":1}
,":date":{"get":1}
,"get":{"currentdate":1}
,"currentdate":{")]":1}
,")]":{"perform":1}
,"[get":{"foundcount":1}
,"foundcount":{"=1]":1,"1]":1}
,"=1]":{"go":1}
,"else":{"if":1,"show":1}
,"1]":{"go":1}
,"show":{"custom":1}
,"end":{"if":1}
,"aking":{"find":1}
,"automating":{"tasks":1}
,"tasks":{"scripts":1}
}
;Search.control.loadWordPairs(pairs);
