var pairs =
{
"aving":{"sending":1}
,"sending":{"records":1}
,"records":{"formats":1,"current":1,"existing":1,"order":1}
,"formats":{"save":1}
,"save":{"filemaker":1,"current":1,"files":1,"excel":1,"pdf":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"data":1,"records":1,"pdf":1,"create":1,"files":1}
,"data":{"excel":1,"current":1,"existing":1}
,"excel":{"files":1,"file":1,"worksheet":1,"pdf":1}
,"files":{"df":1,"snapshot":1,"excel":1,"allow":1,"save":1,"choose":1,"filemaker":1,"setti":1}
,"df":{"files":1}
,"snapshot":{"link":1}
,"link":{"all":1,"send":1,"filemaker":1}
,"all":{"modes":1,"records":1}
,"modes":{"except":1}
,"except":{"find":1}
,"find":{"mode":1}
,"mode":{"save":1}
,"current":{"record":1,"found":1,"layout":1,"state":1}
,"record":{"all":1}
,"found":{"set":1}
,"set":{"creating":1,"excel":1,"records":1}
,"creating":{"excel":1,"pdf":1,"snapshot":1}
,"file":{"export":1,"store":1,"static":1,"creating":1,"snapshot":1,"attached":1,"saving":1}
,"export":{"filemaker":1}
,"layout":{"found":1}
,"worksheet":{"creating":1}
,"pdf":{"file":1,"access":1,"files":1}
,"store":{"current":1}
,"state":{"file":1}
,"static":{"document":1}
,"document":{"protect":1}
,"protect":{"password":1}
,"password":{"if":1}
,"if":{"want":1}
,"want":{"append":1}
,"append":{"filemaker":1}
,"existing":{"filemaker":1,"file":1}
,"send":{"found":1,"excel":1}
,"order":{"save":1}
,"access":{"rivileges":1}
,"rivileges":{"allow":1}
,"allow":{"exporting":1,"printing":1}
,"exporting":{"save":1}
,"printing":{"save":1}
,"create":{"new":1}
,"new":{"email":1}
,"email":{"file":1}
,"attached":{"send":1}
,"choose":{"open":1}
,"open":{"file":1}
,"saving":{"diting":1}
,"diting":{"privilege":1}
,"privilege":{"import":1}
,"import":{"read-only":1}
,"read-only":{"data":1}
,"setti":{"ng":1}
,"ng":{"up":1}
,"up":{"recurring":1}
,"recurring":{"imports":1}
,"imports":{"mporting":1}
,"mporting":{"data":1}
}
;Search.control.loadWordPairs(pairs);
