var pairs =
{
"filemake":{"pro":1}
,"pro":{"advanced":1,"12":1,"dvance":1}
,"advanced":{"features":1,"aunch":1}
,"features":{"compatible":1,"introduced":1,"current":1,"filemaker":1}
,"compatible":{"previous":1,"backward":1}
,"previous":{"versions":1}
,"versions":{"topic":1,"product":1}
,"topic":{"lists":1}
,"lists":{"features":1}
,"introduced":{"filemaker":1,"individual":1,"hide":1}
,"filemaker":{"pro":1,"go":1,"webdirect":1,"id":1}
,"12":{"dvanced":1,"hat":1}
,"dvanced":{"nd":1}
,"nd":{"ilemaker":1}
,"ilemaker":{"pro":1}
,"hat":{"ompatible":1}
,"ompatible":{"previous":1}
,"product":{"version":1}
,"version":{"each":1,"new":1,"introduced":1,"allowed":1}
,"each":{"script":1}
,"script":{"step":1,"trigger":1,"steps":1}
,"step":{"function":1}
,"function":{"script":1}
,"trigger":{"introduced":1}
,"individual":{"help":1}
,"help":{"topics":1}
,"topics":{"new":1}
,"new":{"features":1}
,"current":{"version":1,"table":1}
,"dvance":{"feature":1}
,"feature":{"version":1}
,"hide":{"object":1}
,"object":{"inspector":1}
,"inspector":{"option":1}
,"option":{"13":1}
,"13":{"slide":1,"popovers":1,"display":1,"customizing":1,"container":1,"minimum":1,"list":1}
,"slide":{"controls":1}
,"controls":{"13":1}
,"popovers":{"13":1}
,"display":{"state":1,"custom":1,"records":1}
,"state":{"enhancements":1}
,"enhancements":{"list":1}
,"list":{"view":1,"summary":1}
,"view":{"records":1}
,"records":{"portal":1,"current":1}
,"portal":{"rows":1}
,"rows":{"13":1}
,"customizing":{"layout":1}
,"layout":{"background":1,"parts":1}
,"background":{"full-screen":1}
,"full-screen":{"images":1}
,"images":{"colors":1}
,"colors":{"gradients":1}
,"gradients":{"13":1}
,"container":{"field":1}
,"field":{"improvements":1,"calculation":1}
,"improvements":{"data":1}
,"data":{"storage":1}
,"storage":{"file":1}
,"file":{"metadata":1,"file":1,"options":1}
,"metadata":{"retrieval":1}
,"retrieval":{"performance":1}
,"performance":{"13":1}
,"minimum":{"version":1}
,"allowed":{"open":1}
,"open":{"file":1}
,"options":{"dialog":1}
,"dialog":{"box":1}
,"box":{"option":1,"control":1}
,"summary":{"field":1}
,"calculation":{"option":1}
,"custom":{"app":1,"14":1}
,"app":{"con":1}
,"con":{"apps":1}
,"apps":{"recent":1}
,"recent":{"windows":1}
,"windows":{"filemaker":1}
,"aunch":{"center":1}
,"center":{"filemaker":1}
,"go":{"filemaker":1}
,"webdirect":{"14":1}
,"14":{"button":1,"placeholder":1,"navigation":1,"check":1,"concealed":1}
,"button":{"labels":1,"bars":1}
,"labels":{"text":1}
,"text":{"icon":1,"fields":1}
,"icon":{"predefined":1}
,"predefined":{"custom":1}
,"bars":{"14":1}
,"placeholder":{"text":1}
,"fields":{"14":1}
,"navigation":{"layout":1}
,"parts":{"14":1}
,"check":{"mark":1}
,"mark":{"selected":1}
,"selected":{"checkboxes":1}
,"checkboxes":{"14":1}
,"concealed":{"edit":1}
,"edit":{"box":1}
,"control":{"style":1}
,"style":{"15":1}
,"15":{"card":1}
,"card":{"window":1}
,"window":{"16":1}
,"16":{"account":1,"external":1,"portals":1}
,"account":{"authentication":1}
,"authentication":{"via":1}
,"via":{"oauth":1,"filemaker":1}
,"oauth":{"identity":1}
,"identity":{"providers":1}
,"providers":{"16":1}
,"external":{"script":1}
,"steps":{"rovided":1}
,"rovided":{"by":1}
,"by":{"plug-ins":1}
,"plug-ins":{"16":1}
,"portals":{"display":1}
,"table":{"17":1}
,"17":{"account":1}
,"id":{"18":1}
,"18":{"manage":1,"compatibility":1}
,"manage":{"accounts":1}
,"accounts":{"don\u2019t":1}
,"don\u2019t":{"full":1}
,"full":{"access":1}
,"access":{"privilege":1}
,"privilege":{"18":1}
,"compatibility":{"backward":1}
,"backward":{"compatible":1,"compatibility":1}
}
;Search.control.loadWordPairs(pairs);
