var pairs =
{
"base64decode":{"returns":1,"text":1,"products":1}
,"returns":{"container":1,"text":1,"help":1}
,"container":{"text":1,"filemaker":1,"field":1,"data":1}
,"text":{"content":1,"encoded":1,"filenamewithextension":1,"-base64":1,"decode":1,"text":1,"container":1,"field":1,"data":1,"utf-8":1}
,"content":{"text":1}
,"encoded":{"base64":1,"decode":1}
,"base64":{"format":1,"text":1,"encoded":1,"string":1}
,"format":{"base64decode":1,"base64":1}
,"filenamewithextension":{"text":1,"-the":1,"parameter":1}
,"-base64":{"text":1}
,"decode":{"filenamewithextension":1,"base64-encoded":1}
,"-the":{"filename":1}
,"filename":{"extension":1}
,"extension":{"file":1,"function":1}
,"file":{"created":1}
,"created":{"decoded":1}
,"decoded":{"base64":1}
,"filemaker":{"pro":1}
,"pro":{"13.0":1}
,"13.0":{"decode":1}
,"base64-encoded":{"value":1}
,"value":{"return":1,"represents":1}
,"return":{"result":1}
,"result":{"text":1,"container":1}
,"field":{"variable":1}
,"variable":{"text":1,"container":1}
,"data":{"data":1,"parameter":1,"return":1,"filenamewithextension":1,"base64decode":1}
,"parameter":{"text":1,"if":1}
,"utf-8":{"format":1}
,"represents":{"binary":1}
,"binary":{"data":1}
,"if":{"filename":1}
,"function":{"returns":1}
,"products":{":base64":1}
,":base64":{"question.png":1,"set":1}
,"question.png":{"returns":1}
,"help":{"button":1}
,"button":{"products":1}
,"set":{"string":1}
,"string":{"ivborw0kggoaaaansuheugaaab8":1,"shortened":1}
,"ivborw0kggoaaaansuheugaaab8":{"base64":1}
,"shortened":{"readability":1}
}
;Search.control.loadWordPairs(pairs);
