var pairs =
{
"get":{"ayoutname":1,"layoutname":1,"layoutnumber":1,"layout":1,"current":1}
,"ayoutname":{"returns":1}
,"returns":{"name":1,"product":1,"customer":1}
,"name":{"layout":1,"value":1,"returns":1,"get":1}
,"layout":{"currently":1,"name":1,"displayed":1}
,"currently":{"displayed":1}
,"displayed":{"get":1,"returns":1,"script":1}
,"layoutname":{"none":1,"if":1,"get":1}
,"none":{"text":1}
,"text":{"filemaker":1}
,"filemaker":{"pro":1}
,"pro":{"6.0":1}
,"6.0":{"earlier":1}
,"earlier":{"if":1}
,"if":{"multiple":1}
,"multiple":{"windows":1,"layouts":1}
,"windows":{"open":1}
,"open":{"current":1}
,"current":{"file":1,"layout":1}
,"file":{"each":1}
,"each":{"window":1}
,"window":{"own":1,"use":1}
,"own":{"layout":1}
,"value":{"returned":1}
,"returned":{"foreground":1}
,"foreground":{"window":1}
,"use":{"get":1}
,"layoutnumber":{"function":1}
,"function":{"alternative":1}
,"alternative":{"get":1}
,"layouts":{"name":1}
,"product":{"list":1}
,"list":{"product":1,"layout":1}
,"customer":{"invoice":1}
,"invoice":{"customer":1,"layout":1}
,"script":{"perform":1,"server":1,"step":1}
,"perform":{"script":1}
,"server":{"script":1}
,"step":{"get":1}
}
;Search.control.loadWordPairs(pairs);
