var pairs =
{
"cryptencryptbase64":{"encrypts":1,"data":1,"cryptdecryptbase64":1,"protection":1}
,"encrypts":{"data":1}
,"data":{"key":1,"-any":1,"text":1,"function":1,"base64-encoded":1}
,"key":{"returns":1,"data":1,"-any":1,"encrypt":1}
,"returns":{"text":1,"encrypted":1,"returns":1}
,"text":{"base64":1,"expression":1,"filemaker":1,"rfc":1,"increases":1,"ydjuezueje5ybjg903wuvfyaoly":1}
,"base64":{"format":1}
,"format":{"cryptencryptbase64":1}
,"-any":{"text":1}
,"expression":{"field":1}
,"field":{"encrypt":1,"key":1,"data":1}
,"encrypt":{"key":1,"data":1,"decrypt":1}
,"filemaker":{"pro":1}
,"pro":{"16.0":1}
,"16.0":{"use":1}
,"use":{"cryptencryptbase64":1}
,"cryptdecryptbase64":{"functions":1}
,"functions":{"encrypt":1}
,"decrypt":{"field":1}
,"function":{"cryptencrypt":1,"except":1,"supported":1}
,"cryptencrypt":{"function":1}
,"except":{"returns":1}
,"encrypted":{"data":1}
,"base64-encoded":{"text":1}
,"rfc":{"4648":1}
,"4648":{"standard":1}
,"standard":{"encoding":1}
,"encoding":{"binary":1}
,"binary":{"data":1}
,"increases":{"size":1}
,"size":{"by":1}
,"by":{"function":1}
,"supported":{"runtime":1}
,"runtime":{"solutions":1}
,"solutions":{"returns":1}
,"ydjuezueje5ybjg903wuvfyaoly":{"cryptencryptbase64":1}
,"protection":{"secret":1}
,"secret":{"password":1}
}
;Search.control.loadWordPairs(pairs);
