var pairs =
{
"xporting":{"data":1,"contents":1}
,"data":{"filemaker":1,"new":1,"process":1,"file":1,"th":1,"started":1,"sorted":1,"exported":1,"formatting":1,"format":1,"appears":1,"layout":1,"want":1,"field":1,"source":1,"via":1,"application":1}
,"filemaker":{"pro":1}
,"pro":{"advanced":1}
,"advanced":{"export":1,"data":1,"ource":1,"ile":1,"adds":1,"allows":1}
,"export":{"filemaker":1,"subsummary":1,"summary":1,"contents":1,"find":1,"export":1,"grouped":1,"records":1,"filename":1,"select":1,"dialog":1,"data":1,"double-click":1,"order":1,"choose":1,"process":1,"number":1,"use":1}
,"new":{"file":1}
,"file":{"open":1,"summary":1,"xporting":1,"menu":1,"dialog":1,"if":1,"correctly":1,"type":1,"format":1,"formats":1,"result":1,"character":1,"use":1,"ormatting":1,"excel":1,"system":1}
,"open":{"application":1,"filemaker":1}
,"application":{"filemaker":1,"plan":1}
,"ource":{"file":1}
,"summary":{"fields":1,"value":1,"values":1,"field":1}
,"fields":{"group":1,"current":1,"exist":1,"want":1,"list":1,"field":1,"use":1,"if":1,"layout":1}
,"group":{"by":1,"if":1}
,"by":{"sorted":1,"report":1,"region":1,"application":1,"choosing":1,"select":1,"want":1,"grouped":1,"groupbyfield":1,"nsorted":1}
,"sorted":{"field":1,"data":1,"remove":1}
,"field":{"order":1,"file":1,"open":1,"sort":1,"names":1,"export":1,"name":1,"values":1,"by":1,"grouped":1,"each":1,"selected":1,"field":1,"clear":1,"data":1,"objects":1,"formats":1}
,"order":{"export":1,"run":1,"include":1,"filemaker":1,"prevent":1,"choose":1,"fields":1,"point":1}
,"subsummary":{"values":1}
,"values":{"subtotals":1,"include":1,"individual":1,"want":1,"summarized":1,"sorted":1}
,"subtotals":{"generated":1,"want":1}
,"generated":{"by":1}
,"report":{"grouped":1,"totals":1,"generates":1}
,"grouped":{"data":1,"subsummary":1,"summary":1}
,"process":{"exports":1,"group":1}
,"exports":{"record":1}
,"record":{"each":1}
,"each":{"group":1,"region":1,"break":1}
,"if":{"report":1,"exporting":1,"you\u2019re":1,"current":1,"data":1,"output":1}
,"totals":{"sales":1}
,"sales":{"by":1}
,"region":{"export":1,"note":1}
,"value":{"each":1}
,"contents":{"field":1}
,"ile":{"display":1}
,"display":{"layout":1,"all":1}
,"layout":{"records":1,"layoutname":1,"display":1,"panel":1,"filemaker":1,"data":1,"stored":1,"mode":1,"if":1,"formatting":1}
,"records":{"want":1,"export":1,"finding":1,"sorting":1,"choose":1,"file":1,"fields":1}
,"want":{"export":1,"finding":1,"filemaker":1,"field":1,"summarize":1,"values":1,"exported":1}
,"find":{"sort":1}
,"sort":{"records":1,"order":1}
,"include":{"break":1,"field":1,"related":1}
,"break":{"field":1}
,"run":{"report":1}
,"generates":{"subtotals":1}
,"finding":{"sorting":1,"records":1}
,"sorting":{"records":1}
,"choose":{"file":1,"location":1,"ption":1,"current":1,"name":1,"field":1,"character":1}
,"menu":{"export":1}
,"dialog":{"box":1}
,"box":{"type":1,"continue":1,"xml":1,"want":1,"include":1,"move":1}
,"type":{"name":1,"save":1,"windows":1,"macos":1,"skip":1}
,"name":{"choose":1,"move":1,"related":1,"drag":1}
,"location":{"file":1}
,"exporting":{"xml":1,"file":1,"excel":1}
,"xml":{"applying":1,"xml":1,"xsl":1,"grammar":1,"during":1}
,"applying":{"xslt":1}
,"xslt":{"style":1,"source":1}
,"style":{"sheet":1}
,"sheet":{"during":1,"xml":1,"source":1,"xslt":1}
,"during":{"export":1}
,"filename":{"extension":1}
,"extension":{"corresponds":1}
,"corresponds":{"transformed":1}
,"transformed":{"file\u0027s":1}
,"file\u0027s":{"format":1}
,"format":{".txt":1,"supported":1,"fmpxmlresult":1,"apply":1,"field":1,"fields":1,"12":1}
,".txt":{".htm":1}
,".htm":{".xml":1}
,".xml":{"operating":1}
,"operating":{"systems":1}
,"systems":{"recognize":1}
,"recognize":{"file":1}
,"correctly":{"hoose":1}
,"hoose":{"file":1}
,"save":{"type":1,"use":1}
,"windows":{"type":1}
,"macos":{"save":1}
,"use":{"file":1,"exported":1,"by":1,"xsl":1,"syntax":1,"11":1,"filemaker":1}
,"supported":{"by":1,"import\u002Fexport":1}
,"plan":{"use":1}
,"exported":{"data":1,"field":1,"file":1}
,"formats":{"supported":1,"saving":1,"current":1}
,"import\u002Fexport":{"file":1}
,"saving":{"choose":1}
,"ption":{"if":1}
,"you\u2019re":{"exporting":1}
,"xsl":{"options":1,"style":1}
,"options":{"dialog":1}
,"continue":{"step":1}
,"step":{"if":1,"xml":1}
,"skip":{"step":1}
,"grammar":{"use":1}
,"choosing":{"fmpdsoresult":1}
,"fmpdsoresult":{"format":1}
,"fmpxmlresult":{"format":1}
,"apply":{"xslt":1,"current":1}
,"select":{"use":1,"each":1,"apply":1}
,"source":{"xslt":1,"file":1,"serve":1}
,"result":{"http":1}
,"http":{"request":1}
,"request":{"field":1}
,"th":{"tables":1}
,"tables":{"list":1}
,"list":{"defaults":1,"if":1,"upper-left":1,"left":1}
,"defaults":{"current":1}
,"current":{"layout":1,"table":1,"anel":1,"layout\u2019s":1}
,"layoutname":{"displays":1}
,"displays":{"visible":1}
,"visible":{"fields":1}
,"all":{"field":1}
,"names":{"current":1}
,"table":{"choose":1,"tablename":1,"list":1}
,"tablename":{"list":1}
,"panel":{"controls":1}
,"controls":{"nly":1}
,"nly":{"fields":1}
,"exist":{"current":1}
,"anel":{"displayed":1}
,"displayed":{"field":1}
,"double-click":{"field":1}
,"move":{"field":1,"fields":1,"move":1,"filemaker":1}
,"related":{"field":1,"table":1}
,"upper-left":{"corner":1}
,"corner":{"dialog":1}
,"individual":{"records":1}
,"left":{"summary":1,"field":1}
,"summarize":{"group":1}
,"summarized":{"move":1}
,"adds":{"summary":1,"grouped":1}
,"selected":{"group":1}
,"syntax":{"summaryfield":1}
,"summaryfield":{"by":1}
,"groupbyfield":{"otal":1}
,"otal":{"sales":1}
,"note":{"can\u2019t":1}
,"can\u2019t":{"export":1,"applied":1}
,"started":{"export":1}
,"nsorted":{"nstead":1}
,"nstead":{"fields":1}
,"remove":{"field":1}
,"prevent":{"data":1}
,"clear":{"change":1}
,"change":{"export":1}
,"point":{"double":1}
,"double":{"arrow":1}
,"arrow":{"left":1}
,"drag":{"up":1}
,"up":{"10":1,"field":1}
,"10":{"if":1}
,"output":{"file":1}
,"character":{"set":1,"encoding":1}
,"set":{"choose":1}
,"encoding":{"want":1}
,"11":{"select":1}
,"layout\u2019s":{"data":1}
,"formatting":{"exported":1,"can\u2019t":1}
,"appears":{"current":1}
,"allows":{"format":1}
,"stored":{"database":1}
,"database":{"file":1}
,"ormatting":{"setting":1}
,"setting":{"up":1}
,"objects":{"layout":1}
,"mode":{"select":1}
,"number":{"date":1}
,"date":{"time":1}
,"time":{"data":1}
,"applied":{"you\u2019re":1}
,"excel":{"file":1}
,"system":{"format":1}
,"12":{"lick":1}
,"lick":{"export":1}
,"serve":{"filemaker":1}
,"via":{"odbc":1}
,"odbc":{"jdbc":1}
,"jdbc":{"sh":1,"export":1}
,"sh":{"ari":1}
,"ari":{"ng":1}
,"ng":{"filemaker":1}
}
;Search.control.loadWordPairs(pairs);
